define({
  "_widgetLabel": "Vodič za reakciju u hitnom slučaju",
  "ergMainPageTitle": "Zasnovan na vodiču za reakciju u hitnom slučaju 2016",
  "coordInputLabelStart": "Lokacija prolivanja (DD)",
  "coordInputLabel": "Lokacija prolivanja",
  "addPointToolTip": "Dodaj lokaciju prolivanja",
  "drawPointToolTip": "Kliknite da biste dodali lokaciju prolivanja",
  "material": "Materijal",
  "materialPlaceholder": "Počnite upisivanje da biste pretražili materijal",
  "table3Message": "Materijal koji ste izabrali zahteva dodatne informacije, ako se bavite velikim prolivanjem.\n\nVodite računa da izaberete tačne vrednosti za brzinu vetra i transportni kontejner.",
  "table2Message": "Materijal koji ste izabrali može da proizvede veliku količinu gasova koji predstavljaju opasnost od trovanja udisanjem, u slučaju prolivanja u vodu.\n\nRazmotrite korišćenje sledećih materijala:\n\n",
  "spillSize": "Veličina prolivanja",
  "small": "Malo",
  "large": "Veliko",
  "fireLabel": "Prikaži zonu za izolaciju požara",
  "weatherLabel": "Trenutni vremenski uslovi na lokaciji prolivanja",
  "weatherIntialText": "<br />Ažuriraju se kada se identifikuje lokacija prolivanja",
  "temperature": "Temperatura",
  "wind": "Vetar",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informacije o vremenskim uslovima nisu pribavljene. Ručno ažurirajte vrednosti za brzinu vetra i vreme prolivanja",
  "windDirection": "Smer vetra (duva ka)",
  "timeOfSpill": "Vreme prolivanja",
  "day": "Dan",
  "night": "Noć",
  "windSpeed": "Brzina vetra",
  "low": "Nisko",
  "moderate": "Umereno",
  "high": "Visoko",
  "transportContainer": "Transportni kontejner",
  "rail": "Vagon cisterna",
  "semi": "Kamion sa cisternom ili prikolica",
  "mton": "Višestruki teretni cilindri",
  "ston": "Višestruki mali cilindri ili jedan teretni cilindar",
  "ag": "Poljoprivredna cisterna za uzgoj",
  "msm": "Višestruki mali cilindri",
  "bleveLabel": "Prikaži BLEVE zonu za izolaciju",
  "capacity": "Kapacitet kontejnera (litara)",
  "bleveMessage": "Za materijal koji ste izabrali se može prikazati dodatno rastojanje za evakuaciju za BLEVE.\n\nDa biste to omogućili, uključite BLEVE zonu za izolaciju i izaberite odgovarajući kapacitet zone.",
  "noPAZoneMessage": "Za ovaj materijal ne postoje rastojanja za zaštitnu radnju. Proračunate su samo zone početne izolacije i evakuacije",
  "settingsTitle": "Postavke",
  "spillLocationLabel": "Lokacija prolivanja",
  "spillLocationButtonLabel": "Konfigurišite postavke za lokaciju prolivanja",
  "IISettingsLabel": "Zona početne izolacije",
  "IIButtonLabel": "Konfigurišite postavke za početnu izolaciju",
  "PASettingsLabel": "Zona zaštitne radnje",
  "PAButtonLabel": "Konfigurišite postavke za zaštitnu radnju",
  "downwindSettingsLabel": "Zona niz vetar",
  "downwindButtonLabel": "Konfigurišite postavke za niz vetar",
  "fireSettingsLabel": "Zona za izolaciju požara",
  "fireButtonLabel": "Konfigurišite postavke za izolaciju požara",
  "bleveSettingsLabel": "BLEVE zona za izolaciju",
  "bleveButtonLabel": "Konfigurišite BLEVE postavke",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Crta",
    "esriSLSDashDot": "Crta tačka",
    "esriSLSDashDotDot": "Crta tačka tačka",
    "esriSLSDot": "Tačka",
    "esriSLSLongDash": "Duga crta",
    "esriSLSLongDashDot": "Duga crta tačka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kratka crta",
    "esriSLSShortDashDot": "Kratka crta tačka",
    "esriSLSShortDashDotDot": "Kratka crta tačka tačka",
    "esriSLSShortDot": "Kratka tačka",
    "esriSLSSolid": "Neprozirno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unazad",
    "esriSFSCross": "Krst",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Unapred",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Neprozirno",
    "esriSFSVertical": "Vertikalno"
  },
  "resultsTitle": "Rezultati",
  "publishERGBtn": "Objavi",
  "ERGLayerName": "Ime sloja objavljenog ERG",
  "invalidERGLayerName": "Ime sloja sme da sadrži samo alfanumeričke znakove i donje crte",
  "missingERGLayerName": "Morate da unesete ime za ERG",
  "publishingFailedLayerExists": "Objavljivanje nije uspelo: Već imate servis geoobjekata sa imenom {0}. Odaberite drugo ime.",
  "checkService": "Provera servisa: {0}",
  "createService": "Kreiranje servisa: {0}",
  "unableToCreate": "Kreiranje nije moguće: {0}",
  "addToDefinition": "Dodaj u definiciju: {0}",
  "successfullyPublished": "Uspešno objavljen veb sloj{0}Upravljaj veb slojem",
  "userRole": "Kreiranje servisa nije moguće, jer korisnik nema dozvole",
  "transparency": "Prozirnost",
  "outline": "Kontura",
  "fill": "Popuna (boja se primenjuje samo kada je stil podešen da bude neproziran)",
  "createERGBtn": "Kreiraj zone",
  "clearERGBtn": "Obriši",
  "labelFormat": "Format oznake",
  "helpIconTooltip": "Prag između male i velike veličine prolivanja iznosi:\nTečnosti – 55 galona (208 litara)\nČvrste materije – 60 funti (300 kilograma)",
  "cellWidth": "Širina ćelije (x)",
  "cellHeight": "Visina ćelije (y)",
  "invalidNumberMessage": "Uneta vrednost nije važeća",
  "invalidRangeMessage": "Vrednost mora da bude veća od 0",
  "gridAngleInvalidRangeMessage": "Vrednost mora da bude između -89,9 i 89,9",
  "formatIconTooltip": "Unos formata",
  "setCoordFormat": "Postavi nisku formata koordinata",
  "prefixNumbers": "Dodajte prefiks '+/-' pozitivnim i negativnim brojevima",
  "cancelBtn": "Otkaži",
  "applyBtn": "Primeni",
  "comfirmInputNotation": "Proverite unesenu oznaku",
  "notationsMatch": "oznake se podudaraju sa unosom potvrdite koje biste želeli da koristite:",
  "missingLayerNameMessage": "Morate da unesete važeće ime sloja da biste mogli da objavite",
  "parseCoordinatesError": "Raščlanjivanje koordinata nije moguće. Proverite unos.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "Univerzalni Transverzalni Merkatorov koordinatni sistem (H)",
  "UTM": "Univerzalni Transverzalni Merkatorov koordinatni sistem (UTM)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stepeni – geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stepeni – geografska dužina/širina",
  "DDMLatLongNotation": "Decimalni stepeni minuti – geografska širina/dužina",
  "DDMLongLatNotation": "Decimalni stepeni minuti – geografska dužina/širina",
  "DMSLatLongNotation": "Decimalni stepeni sekundi – geografska širina/dužina",
  "DMSLongLatNotation": "Decimalni stepeni sekundi – geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – slovo opsega",
  "UTMHemNotation": "UTM – hemisfera (S/J)"
});