define({
  "_widgetLabel": "ระยะทางและทิศทาง",
  "tabLineTitle": "เส้น",
  "tabCircleTitle": "วงกลม",
  "tabEllipseTitle": "วงรี",
  "tabRingsTitle": "วงแหวน",
  "multipleNotationsMessage": " สัญกรณ์ที่ตรงกับข้อมูลนำเข้าของคุณ โปรดยืนยันรายการที่คุณต้องการใช้:",
  "invalidCoordinateMessage": "พิกัดไม่ถูกต้อง",
  "confirmInputNotationMessage": "ยืนยันการป้อนข้อมูล",
  "prefixSuffixMessage": "ค่าพิกัดนำเข้าถูกตรวจพบว่ามีทั้งคำนำหน้าและคำต่อท้ายสำหรับค่าละติจูดหรือลองจิจูด ค่าพิกัดที่ส่งคืนจะขึ้นอยู่กับคำนำหน้า",
  "rememberDecisionMessage": "โปรดจำการตัดสินใจของฉันและไม่ต้องถามอีก <br/>",
  "majorAxisTooltipMessage": "คลิกความยาวของแกนหลัก",
  "minorAxisTooltipMessage": "เลื่อนเมาส์กลับไปที่ตำแหน่งเริ่มต้นเพื่อตั้งค่าแกนรองและเสร็จสิ้นการวาดวงรี",
  "clickToFinishLineMessage": "คลิกเพื่อเสร็จสิ้นการวาดเส้น",
  "doubleClickEllipseMesage": "ดับเบิลคลิกเพื่อสิ้นสุดการวาดวงแหวนช่วง",
  "invalidCoordinateTypeMessage": "ไม่สามารถระบุประเภทพิกัดอินพุต โปรดตรวจสอบข้อมูลนำเข้าของคุณ",
  "noCenterPointSetMessage": "ไม่มีจุดศูนย์กลาง โปรดตรวจสอบข้อมูลนำเข้าของคุณ",
  "ellipseMajorAxis": "แกนหลัก",
  "ellipseMinorAxis": "แกนรอง",
  "degreesRangeMessage": "จะต้องมีค่าระหว่าง 0 และ 360",
  "millsRangeMessage": "จะต้องมีค่าระหว่าง 0 และ 6400",
  "lengthLabel": "ความยาว",
  "angleLabel": "มุม",
  "startPointLabel": "จุดเริ่ม",
  "endPointLabel": "จุดสิ้นสุด",
  "centerPointLabel": "จุดกึ่งกลาง",
  "distanceTableErrorMessage": "ตารางระยะทางว่างเปล่า โปรดตรวจสอบให้แน่ใจว่าคุณป้อนระยะทาง",
  "setCoordFormatStringMessage": "ตั้งค่าระบบพิกัดรูปแบบสตริง",
  "prefixMessage": "เพิ่มคำนำหน้า '+/-' เป็นตัวเลขบวกและลบ",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "องศาทศนิยม - ละติจูด / ลองจิจูด",
  "DDLongLatNotation": "องศาทศนิยม - ละติจูด / ลองจิจูด",
  "DDMLatLongNotation": "องศา ทศนิยม นาที – ละติจูด / ลองจิจูด",
  "DDMLongLatNotation": "องศา ทศนิยม นาที – ละติจูด / ลองจิจูด",
  "DMSLatLongNotation": "องศา ลิปดา ฟิลิปดา - ละติจูด / ลองจิจูด",
  "DMSLongLatNotation": "องศา ลิปดา ฟิลิปดา - ละติจูด / ลองจิจูด",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisphere (N/S)",
  "circleTitle": "สร้างวงกลมจาก",
  "radiusLabel": "รัศมี",
  "diameterLabel": "เส้นผ่าศูนย์กลาง",
  "startPointPlaceHolderLabel": "ใส่ระบบพิกัด",
  "formatInputLabel": "รูปแบบข้อมูลนำเข้า",
  "drawCircleLabel": "วาดวงกลม",
  "drawLineLabel": "วาดเส้น",
  "createCircleInteractivelyLabel": "สร้างวงกลมโต้ตอบ",
  "rangeErrorMessage": "รัศมีหรือเส้นผ่าศูนย์กลางไม่ถูกต้อง",
  "numericInvalidMessage": "โปรดป้อนค่าตัวเลข",
  "timeLabel": "เวลา",
  "invalidTimeMessage": "ค่าเวลาไม่ถูกต้อง",
  "hoursLabel": "ชั่วโมง",
  "minutesLabel": "นาที",
  "secondsLabel": "วินาที",
  "rateLabel": "อัตรา",
  "invalidDistanceMessage": "ค่าระยะทางไม่ถูกต้อง",
  "feetSecondsLabel": "ฟุต/วินาที",
  "feetHourLabel": "ฟุต/ชั่วโมง",
  "kmSecondLabel": "กิโลเมตร/วินาที",
  "kmHourLabel": "กิโลเมตร/ชั่วโมง",
  "metersSecondLabel": "เมตร/วินาที",
  "metersHourLabel": "เมตร/ชั่วโมง",
  "milesSecondLabel": "ไมล์/วินาที",
  "milesHourLabel": "ไมล์/ชั่วโมง",
  "nauticalMilesSecondLabel": "ไมล์ทะเล/วินาที",
  "nauticalMilesHourLabel": "ไมล์ทะเล/ชั่วโมง",
  "clearGraphicsLabel": "ล้างกราฟิก",
  "ellipseTypeLabel": "ประเภทวงรี",
  "ellipseSemiLabel": "ครึ่งวง",
  "ellipseFullLabel": "เต็มวง",
  "drawEllipseLabel": "วาดวงรี",
  "createEllipseInteractively": "สร้างวงรีโต้ตอบ",
  "axisLabel": "แกน",
  "majorRadiusLabel": "หลัก (รัศมี)",
  "axisErrorMessage": "ค่าต้องมากกว่า 0",
  "minorRadiusLabel": "รอง (รัศมี)",
  "orientationLabel": "ทิศทางของภาพ",
  "orientationErrorMessage": "จะต้องมีค่าระหว่าง 0 และ 360",
  "warningMessage": "คำเตือน: กราฟิกที่สร้างโดยใช้เครื่องมือรูปวงรีไม่ได้เป็นจีออเดติก",
  "fromLabel": "จาก",
  "distanceBearingLabel": "ระยะทางและแบริ่ง",
  "pointsLabel": "จุด",
  "createLineInteractively": "สร้างเส้นโต้ตอบ",
  "lineLengthErrorMessage": "ความยาวเส้นไม่ถูกต้อง",
  "degreesLabel": "ลดลง",
  "milsLabel": "มิล",
  "lineTypeLabel": "ชนิด",
  "interactiveLabel": "โต้ตอบ",
  "fixedLabel": "คงที่",
  "originLabel": "จุดกำเนิด",
  "cumulativeLabel": "ที่สะสมเพิ่มขึ้น",
  "numberOfRingsLabel": "จำนวนวงแหวน",
  "ringsErrorMessage": "จำนวนวงแหวนไม่ถูกต้อง",
  "distanceBetweenRingsLabel": "ระยะห่างระหว่างวงแหวน",
  "ringsDecimalErrorMessage": "ป้อนค่าตัวเลขเป็นทศนิยม 2 ตำแหน่ง",
  "distanceUnitsLabel": "หน่วยระยะทาง",
  "distancesLabel": "ระยะทาง",
  "numberOfRadialsLabel": "ตัวเลขรัศมี",
  "upLabel": "ขึ้น",
  "downLabel": "ลง",
  "deleteLabel": "ลบ",
  "radialsErrorMessage": "ตัวเลขรัศมีไม่ถูกต้อง จำนวนสูงสุดที่อนุญาตคือ 360",
  "addPointLabel": "เพิ่มจุด",
  "valueLabel": "มูลค่า",
  "valueText": "ป้อนค่า",
  "actionLabel": "ปฏิบัติ"
});