define({
  "_widgetLabel": "Ghid pentru reacţii de urgenţă",
  "ergMainPageTitle": "Pe baza Ghidului pentru reacții de urgență 2016",
  "coordInputLabelStart": "Localizarea deversării (DD)",
  "coordInputLabel": "Localizarea deversării",
  "addPointToolTip": "Adăugați localizarea deversării",
  "drawPointToolTip": "Faceți clic pentru a adăuga localizarea deversării",
  "material": "Material",
  "materialPlaceholder": "Scrieți pentru a căuta un material",
  "table3Message": "Materialul selectat solicită informații suplimentare dacă aveți de-a face cu o deversare mare.\n\nVă rugăm să vă asigurați că aveți valorile corecte selectate pentru viteza vântului și containerul de transport.",
  "table2Message": "Materialul selectat poate produce un volum mare de gaze toxice periculoase la inhalare, atunci când este deversat în apă.\n\nPuteți lua în considerare utilizarea următoarelor materiale:\n\n",
  "spillSize": "Dimensiunea deversării",
  "small": "Mică",
  "large": "Mare",
  "fireLabel": "Arată zona de izolare a incendiului",
  "weatherLabel": "Condiții meteo actuale la locul deversării",
  "weatherIntialText": "<br />Actualizat după identificarea locului deversării",
  "temperature": "Temperatură",
  "wind": "Vânt",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Nu au fost obținute informații meteo. Actualizați manual valorile de viteză a vântului și ora deversării",
  "windDirection": "Direcția vântului (bate către)",
  "timeOfSpill": "Ora deversării",
  "day": "Zi",
  "night": "Noapte",
  "windSpeed": "Viteza vântului",
  "low": "Redus",
  "moderate": "Moderată",
  "high": "Ridicată",
  "transportContainer": "Container de transport",
  "rail": "Vagon cisternă",
  "semi": "Camion sau remorcă cisternă auto",
  "mton": "Multipli cilindri de o tonă",
  "ston": "Cilindri mici multipli sau un singur cilindru de o tonă",
  "ag": "Cisternă agricolă",
  "msm": "Cilindri mici multipli",
  "bleveLabel": "Arată zona BLEVE izolare",
  "capacity": "Capacitatea containerului (litri)",
  "bleveMessage": "Pentru materialul selectat, o distanță de evacuare suplimentară poate fi prezentată pentru BLEVE.\n\nPentru a permite acest lucru, setați comutatorul de Indicare a Zonei de Izolare BLEVE la poziția pornit și selectați capacitatea adecvată a containerului.",
  "noPAZoneMessage": "Nu există distanțe de Acțiune de Protecție pentru acest material. Au fost calculate doar zonele de izolare inițială și evacuare",
  "settingsTitle": "Setările",
  "spillLocationLabel": "Localizarea deversării",
  "spillLocationButtonLabel": "Configurați Setările Localizării Deversării",
  "IISettingsLabel": "Zona inițială de izolare",
  "IIButtonLabel": "Configurați setările de izolare inițială",
  "PASettingsLabel": "Zona de acțiune de protecție",
  "PAButtonLabel": "Configurați setările de acțiune de protecție",
  "downwindSettingsLabel": "Zonă în direcția vântului",
  "downwindButtonLabel": "Configurare setări în direcția vântului",
  "fireSettingsLabel": "Zona de izolare a incendiului",
  "fireButtonLabel": "Configurați setările de izolare a incendiului",
  "bleveSettingsLabel": "Zona de izolare BLEVE",
  "bleveButtonLabel": "Configurarea setărilor BLEVE",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Linie",
    "esriSLSDashDot": "Linie punct",
    "esriSLSDashDotDot": "Linie punct punct",
    "esriSLSDot": "Punct",
    "esriSLSLongDash": "Linie lungă",
    "esriSLSLongDashDot": "Linie lungă punct",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Linie scurtă",
    "esriSLSShortDashDot": "Linie scurtă punct",
    "esriSLSShortDashDotDot": "Linie scurtă punct punct",
    "esriSLSShortDot": "Punct scurt",
    "esriSLSSolid": "Continuu"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Înapoi",
    "esriSFSCross": "Cruce",
    "esriSFSDiagonalCross": "Diagonală",
    "esriSFSForwardDiagonal": "Înainte",
    "esriSFSHorizontal": "Orizontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Continuu",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Rezultate",
  "publishERGBtn": "Publicare",
  "ERGLayerName": "Nume strat tematic ERG publicat",
  "invalidERGLayerName": "Numele stratului tematic trebuie să includă doar caractere alfanumerice și de subliniere",
  "missingERGLayerName": "Trebuie să introduceți un nume pentru ERG",
  "publishingFailedLayerExists": "Publicarea a eșuat: Aveți deja un serviciu de obiecte spaţiale denumit {0}. Alegeți alt nume.",
  "checkService": "Bifaţi serviciu: {0}",
  "createService": "Creați serviciu: {0}",
  "unableToCreate": "Nu se poate crea: {0}",
  "addToDefinition": "Adăugați la definiție: {0}",
  "successfullyPublished": "Publicarea cu succes a stratului tematic web{0}Administrare strat tematic web",
  "userRole": "Nu se poate crea serviciu deoarece utilizatorul nu are permisiunile",
  "transparency": "Transparenţă",
  "outline": "Contur",
  "fill": "Umplere (Culoarea se aplică doar când stilul este setat la continuu)",
  "createERGBtn": "Creați Zone",
  "clearERGBtn": "Golire",
  "labelFormat": "Format etichetă",
  "helpIconTooltip": "Limita dintre dimensiunile deversării mici și mari este:\nLichide - 55 galoane (208 litri)\nSolide - 60 livre (300 kilograme)",
  "cellWidth": "Lățime celulă (x)",
  "cellHeight": "Înălțime celulă (y)",
  "invalidNumberMessage": "Valoarea introdusă nu este valabilă",
  "invalidRangeMessage": "Valoarea trebuie să fie mai mare decât 0",
  "gridAngleInvalidRangeMessage": "Valoarea trebuie să fie între -89,9 şi 89,9",
  "formatIconTooltip": "Intrare format",
  "setCoordFormat": "Setare şir format coordonate",
  "prefixNumbers": "Adăugaţi prefixul \"+/-\" la numere pozitive şi negative",
  "cancelBtn": "Anulare",
  "applyBtn": "Aplicare",
  "comfirmInputNotation": "Confirmare notare intrare",
  "notationsMatch": "notaţii se potrivesc cu introducerea dvs. Confirmaţi ce doriţi să folosiţi:",
  "missingLayerNameMessage": "Trebuie să introduceți un nume valabil al stratului tematic înainte de a putea publica",
  "parseCoordinatesError": "Imposibil de analizat coordonatele. Verificaţi intrarea.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Grade zecimale - latitudine/longitudine",
  "DDLongLatNotation": "Grade zecimale - longitudine/latitudine",
  "DDMLatLongNotation": "Grade zecimale minute - latitudine/longitudine",
  "DDMLongLatNotation": "Grade zecimale minute - longitudine/latitudine",
  "DMSLatLongNotation": "Grade minute secunde - latitudine/longitudine",
  "DMSLongLatNotation": "Grade minute secunde - longitudine/latitudine",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - literă bandă",
  "UTMHemNotation": "UTM - emisferă (N/S)"
});