define({
  "chartSettingLabel": "Diagramos nustatymai",
  "addNewLabel": "Pridėti naują",
  "generalSettingLabel": "Bendrieji parametrai",
  "searchSourceSettingLabel": "Ieškoti šaltinio parametrų",
  "layerChooser": {
    "title": "Pasirinkite diagramos sluoksnį",
    "selectPolygonLayerLabel": "Pasirinkite sluoksnį",
    "selectPolygonLayerHintText": "Patarimas: jei konfigūruojate kelias diagramas, sluoksniai turi būti to paties geometrijos tipo",
    "selectRelatedTableLayerLabel": "Pasirinkti su sluoksniu susijusią lentelę",
    "selectRelatedTableLayerHintText": "Patarimas: rodomos tik lentelės su skaitiniais laukais",
    "errorInSelectingPolygonLayer": "Pasirinkite sluoksnį, kuriame yra susijusių taškų sluoksnis.",
    "errorInSelectingRelatedLayer": "Pasirinkite tinkamą lentelę / sluoksnį, susijusį su sluoksniu.",
    "polygonLayerNotHavingRelationships": "Pasirinktas sluoksnis neturi susijusių lentelių / sluoksnių."
  },
  "ChartSetting": {
    "sectionTitle": "Skilties pavadinimas",
    "sectionTitleHintText": "Patarimas: rodoma skilties antraštės pavadinime",
    "chartTitle": "Diagramos pavadinimas",
    "chartTitleHintText": "Užuomina: rodomas centre diagramos viršuje",
    "chartDescription": "Aprašymas",
    "chartDescriptionHintText": "Užuomina: rodomas po diagrama",
    "chartType": "Diagramos tipas",
    "barChart": "Stulpelinė diagrama",
    "pieChart": "Skritulinė diagrama",
    "polarChart": "Polinė diagrama",
    "dataSeriesField": "Duomenų serijos laukas",
    "labelField": "Žymės laukas",
    "chartColor": "Diagramos spalva",
    "singleColor": "Viena spalva",
    "colorByTheme": "Spalva pagal temą",
    "colorByFieldValue": "Spalvos pagal laukų reikšmę",
    "xAxisTitle": "X ašies pavadinimas",
    "xAxisHintText": "Patarimas: X ašies pavadinimas",
    "yAxisTitle": "Y ašies pavadinimas",
    "yAxisHintText": "Patarimas: Y ašies pavadinimas",
    "fieldColorLabel": "Žymė",
    "fieldColorColor": "Spalva",
    "defaultFieldSelectLabel": "Pasirinkite",
    "errMsgFieldValuesNotFound": "Nepavyko rasti pasirinkto lauko reikšmių",
    "errMsgSectionTitle": "Įveskite skilties pavadinimą",
    "errMsgFieldByValue": "Pasirinkite lauko reikšmę",
    "settingTabTitle": "Nustatymas",
    "layoutTabTitle": "Maketas",
    "polarChartSelectFieldsHintText": "Užuomina: pasirinkite laukus, kuriais remdamiesi norite sugeneruoti polinę diagramą",
    "visibilityText": "Matomumas",
    "fieldNameText": "Lauko pavadinimas",
    "aliasNameText": "Pseudonimas",
    "errMsgPolarFieldsRequired": "Pasirinkite tris ar daugiau laukų, kuriais remdamiesi norite sugeneruoti polinę diagramą",
    "polarChartPolygonFillLabel": "Užpildykite plotą",
    "polarChartPolygonFillHintText": "Užuomina: pasirinkite žymės langelį, parodantį ploto užpildymą polinėje diagramoje",
    "viewLayoutLabel": "Maketas",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Bendrieji parametrai",
    "locationSymbolLabel": "Grafinis vietos simbolis",
    "locationSymbolHintText": "Patarimas: naudojama adreso ir paspaudimo vietos simboliui rodyti",
    "refreshIntervalLabel": "Atnaujinimo intervalas",
    "refreshIntervalHintText": "Patarimas: naudojama diagramoms atnaujinti, atsižvelgiant į šį intervalą. Nurodykite reikšmę nuo 1 iki 1440 minučių",
    "errMsgRefreshInterval": "Nurodykite atnaujinimo intervalą nuo 0 iki 1440 minučių",
    "symbolPickerPreviewText": "Peržiūra:",
    "showToolToSelectLabel": "Vietos nustatymo mygtukas",
    "showToolToSelectHintText": "Pastaba: pateikiamas mygtukas, skirtas vietai žemėlapyje nustatyti, bet ne visada spustelėjus žemėlapį nustatoma vieta"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Ieškoti šaltinio parametrų",
    "searchSourceSettingTitle": "Ieškoti šaltinio parametrų",
    "searchSourceSettingTitleHintText": "Pridėti ir sukonfigūruoti geokodavimo paslaugas arba elementų sluoksnius kaip paieškos šaltinius. Šie nurodyti šaltiniai nustato, ko galima ieškoti paieškos lauke",
    "addSearchSourceLabel": "Pridėti paieškos šaltinį",
    "featureLayerLabel": "Elementų sluoksnis",
    "geocoderLabel": "Geokoderis",
    "nameTitle": "Pavadinimas",
    "generalSettingLabel": "Bendrieji parametrai",
    "allPlaceholderLabel": "Vietos rezervavimo tekstas visų elementų paieškai:",
    "allPlaceholderHintText": "Pastaba: įveskite tekstą, kuris bus rodomas kaip vietos rezervavimo ženklas ieškant visų sluoksnių ir geokoderio",
    "generalSettingCheckboxLabel": "Rodyti kontekstinį langą, skirtą rastam elementui arba vietai",
    "countryCode": "Šalies arba regiono kodas (-ai)",
    "countryCodeEg": "pvz., ",
    "countryCodeHint": "Jei ši reikšmė nebus nurodyta, bus ieškomos visos šalys ir regionai",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Ieškoti tik esamo žemėlapio aprėptyje",
    "zoomScale": "Mastelis",
    "locatorUrl": "Geokoderio URL",
    "locatorName": "Geokoderio pavadinimas",
    "locatorExample": "Pavyzdys",
    "locatorWarning": "Ši geokodavimo paslaugos versija nepalaikoma. Valdiklis palaiko 10.0 arba vėlesnę geokodavimo paslaugą.",
    "locatorTips": "Pasiūlymų nėra, nes geokodavimo paslauga nepalaiko pasiūlymų galimybės.",
    "layerSource": "Sluoksnio šaltinis",
    "setLayerSource": "Nustatyti sluoksnio šaltinį",
    "setGeocoderURL": "Nustatyti geokodavimo paslaugos URL",
    "searchLayerTips": "Pasiūlymų nėra, nes elementų paslauga nepalaiko puslapių numeravimo galimybės.",
    "placeholder": "Vartotojui rodomas tekstas",
    "searchFields": "Paieškos laukai",
    "displayField": "Rodyti lauką",
    "exactMatch": "Tikslus atitikmuo",
    "maxSuggestions": "Maksimalus pasiūlymų skaičius",
    "maxResults": "Maksimalus rezultatų skaičius",
    "enableLocalSearch": "Įgalinti vietinę paiešką",
    "minScale": "Minimalus mastelis",
    "minScaleHint": "Vietinė paieška bus taikoma, kai žemėlapio mastelis bus didesnis nei šis",
    "radius": "Spindulys",
    "radiusHint": "Nurodo ploto aplink dabartinį žemėlapio centrą spindulį, naudojamą geokodavimo objektams išdėstyti taip, kad arčiausiai vietos esantys objektai būtų pateikiami pirmiausia.",
    "meters": "Metrai",
    "setSearchFields": "Nustatyti paieškos laukus",
    "set": "Taikyti",
    "fieldName": "Pavadinimas",
    "invalidUrlTip": "URL ${URL} yra neteisingas arba nepasiekiamas."
  }
});