define({
  root: ({
    addTaskTip: "Add one or more filters to the widget and configure parameters for each of them.",
    enableMapFilter: "Remove the preset layer filter from the map.",
    newFilter: "New filter",
    filterExpression: "Filter expression",
    layerDefaultSymbolTip: "Use layer's default symbol",
    uploadImage: "Upload an image",
    selectLayerTip: "Please select a layer.",
    setTitleTip: "Please set title.",
    noTasksTip: "No filters configured. Click \"${newFilter}\" to add a new one.",
    collapseFiltersTip: "Collapse the filter expressions (if any) when the widget is opened",
    zoomtoTip: "Zoom to the layer when the filter is applied",
    autoApplyWhenValueInput: "Apply this filter automatically after a value is input",
    autoApplyWhenWidgetOpen: "Apply this filter when the widget is opened",
    info: "Info",
    expressions: "Expressions",
    allowCustom: "Allow to create custom filters"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
