define({
  "settings": "Nastavení",
  "titleSettings": "Nastavení textu",
  "imageSettings": "Nastavení obrázku",
  "backgroundColor": "Barva pozadí",
  "alignment": "Zarovnání",
  "textSize": "Velikost textu",
  "textColor": "Barva textu",
  "dataSource": "Zdroj dat",
  "chartSettings": "Nastavení grafu",
  "data": "Data",
  "dataLabels": "Popisky dat",
  "displayMode": "Režim zobrazení",
  "featureOption": "Zobrazit hodnoty prvek po prvku",
  "categoryOption": "Zobrazit hodnoty podle kategorie",
  "countOption": "Zobrazit počty prvků podle kategorie",
  "fieldOption": "Zobrazit hodnoty atributů jako grafy",
  "categoryField": "Pole kategorie",
  "labelField": "Pole popisků",
  "valueFields": "Pole hodnot",
  "operation": "Operace",
  "sumOption": "Suma",
  "averageOption": "Průměr",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "dataFormat": "Formát dat",
  "decimalPlaces": "Desetinná místa",
  "prefix": "Předpona",
  "suffix": "Titul",
  "dataType": "Typ dat",
  "featureCount": "Počet prvků",
  "fieldStatistics": "Statistiky pole",
  "display": "Zobrazení",
  "chartColor": "Barva grafu",
  "horizontalAxis": "Vodorovná osa",
  "verticalAxis": "Svislá osa",
  "legend": "Legenda",
  "position": "Pozice",
  "top": "Nahoře",
  "bottom": "Dole",
  "useDataSourceSelection": "Použít výběr",
  "dataSourceFilterByExtent": "Filtrovat podle rozsahu",
  "changeTemplate": "Změnit šablonu",
  "numberSettings": "Nastavení čísel",
  "gaugeSettings": "Nastavení měřiče",
  "indicators": "Ukazatele",
  "ifValue": "Pokud hodnota",
  "and": "a",
  "numberOperatorIsLessThan": "je menší než",
  "numberOperatorIsGreaterThan": "je větší než",
  "numberOperatorIsBetween": "je mezi",
  "numberOperatorIsEqual": "rovná se",
  "numberOperatorIsNotEqual": "nerovná se",
  "then": "Pak",
  "ratio": "Poměr",
  "trueValue": "Hodnota True",
  "changeValueColor": "změnit barvu hodnoty na",
  "changeGaugeColor": "změnit barvu měřiče na",
  "setIndicatorIcon": "nastavit ukazatel ikony jako",
  "icons": "Ikony",
  "style": "Styl",
  "placement": "Umístění",
  "left": "Vlevo",
  "replace": "Nahradit",
  "right": "Vpravo",
  "color": "Barva",
  "categoryExists": "Kategorie již existuje!",
  "comboxHint": "Napište nebo vyberte jednu možnost",
  "comboxDisableInputHint": "Vyberte jednu možnost",
  "sortBy": "Seřadit podle",
  "labelAxis": "Popisek",
  "valueAxis": "Hodnota",
  "minPeriod": "Minimální období",
  "automatic": "Automaticky",
  "periodsWithOutRecords": "Období bez záznamů",
  "nullValue": "Nulová hodnota",
  "calculatedAsZero": "Vypočteno jako nula",
  "ignored": "Ignorováno",
  "maxCategories": "Maximum kategorií",
  "useLayerSymbology": "Použít symboliku vrstev",
  "hollowsize": "Velikost dutiny",
  "splitField": "Dělicí pole",
  "parsingperiodTip": "Výpočet se nezdařil. Příliš mnoho časových intervalů kvůli krátké době analýzy.",
  "manyCategoryTip": "Graf se nepodařilo zobrazit. Příliš mnoho kategorií.",
  "setColor": "Nastavit barvu",
  "setTheColorOf": "Následně nastavte barvu",
  "setTheColorAs": "Následně nastavte barvu jako",
  "ifStr": "Při použití možnosti",
  "as": "jako",
  "is": "je",
  "isNot": "není",
  "barCluster": "skupinový pruhový",
  "individualBar": "jednoduchý pruhový",
  "allOthers": "Všechny ostatní",
  "category": "Kategorie",
  "indicatorSum": "SUMA",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Nastavte prosím indikátory správně.",
  "dataRange": "Rozmezí dat",
  "targetValue": "Cílová hodnota",
  "currentValue": "Současná hodnota",
  "gaugeColor": "Barva měřiče",
  "min": "Minimum",
  "max": "Maximum",
  "displayValueIn": "Zobrazit hodnotu v",
  "noData": "Žádná data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "m",
  "billionAbbreviation": "G",
  "warning": "Varování",
  "noSettingWaring1": "Kliknutím na prvek nastavíte jeho vlastnosti.",
  "noSettingWaring2": "Přetažením změníte velikost nebo pořadí prvku.",
  "donNotShowAgain": "Znovu nezobrazovat",
  "changeTemplateWarning": "Veškeré vaše nastavení bude vymazáno a otevře se nová prázdná šablona.",
  "requiredFieldWarning": "Tato hodnota je povinná:",
  "dataSourceNotSet": "Nastavte zdroj dat.",
  "addIndicatorTip": "Přidat ukazatel",
  "chooseTemplatePopupTitle": "Vybrat šablonu",
  "filterExtentTipWithaTag": "Filtr můžete zakázat pomocí položky <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Další zdroj dat</a> na kartě Atributy.",
  "filterExtentTip": "Filtr můžete zakázat pomocí položky Další zdroj dat na kartě Atributy.",
  "customColorByCategory": "Vlastní barva dle kategorie",
  "randomColor": "Náhodná barva",
  "valueString": "Hodnota",
  "fieldString": "Pole",
  "includeThresholdValue": "Zahrnout mezní hodnotu",
  "percentage": "Procenta",
  "colorSchema": "Barevné schéma",
  "addCategory": "Přidat kategorii",
  "clickToEdit": "Upravit kliknutím",
  "nullText": "Prázdný",
  "others": "Jiné",
  "stringsInTemplate": {
    "name_number": "Číslo",
    "name_gauge": "Měřič",
    "name_vertical_gauge": "Svislý měřič",
    "name_horizontal_gauge": "Vodorovný měřič",
    "name_pie": "Výsečový",
    "name_donut": "Prstencový",
    "name_bar": "Pruhový",
    "name_stacked_bar": "Skládaný pruhový",
    "name_percentage_stacked_bar": "Skládaný pruhový s procenty",
    "name_column": "Sloupcový",
    "name_stacked_column": "Skládaný sloupcový",
    "name_percentage_stacked_column": "Skládaný sloupcový s procenty",
    "name_line": "Spojnicový",
    "name_area": "Plošný",
    "name_stacked_area": "Skládaný plošný",
    "name_percentage_stacked_area": "Skládaný plošný s procenty",
    "titleOfTheInfographic": "NÁZEV INFOGRAFIKY",
    "description": "Popis: další informace o této infografice."
  }
});