define({
  "serviceUrl": "Nastavte adresu URL služby:",
  "minIntSpacingLabel": "Minimální velikost mřížky",
  "lineOpacityLabel": "Neprůhlednost linie",
  "labelOpacityLabel": "Neprůhlednost popisku",
  "centerLabelOpacityLabel": "Neprůhlednost středního popisku",
  "gridZonePlacementLabel": "Umístění popisku zóny mřížky",
  "verticalLineLabels": "Popisky svislé linie",
  "styleHeaderLabel": "Styl",
  "indexHeaderLabel": "Komponenta mřížky",
  "colorHeaderLabel": "Barva",
  "fontSizeHeaderLabel": "Velikost písma",
  "lineWidthHeaderLabel": "Šířka linie",
  "horizontalLabel": "Vodorovný",
  "verticalLabel": "Svislý",
  "upperLeftLabel": "Levý horní",
  "upperRightLabel": "Pravý horní",
  "lowerLeftLabel": "Levý dolní",
  "lowerRightLabel": "Pravý dolní",
  "centerLabel": "Střed",
  "errorMessage": "Stránka konfigurace obsahuje chyby. Před uložením je prosím opravte.",
  "checkBoxLabel": "Po zavření widgetu zobrazit mřížku.",
  "checkBoxLabelDashboard": "Zobrazit mřížku",
  "gzd": "Označení zóny mřížky (Grid Zone Designator – GZD)",
  "gsid": "Velikost čtverce mřížky 100 000 metrů (Grid Square Identification – GSID)",
  "grid10k": "Linie mřížky 10 000 metrů",
  "grid1k": "Linie mřížky 1 000 metrů",
  "grid100m": "Linie mřížky 100 metrů",
  "grid10m": "Linie mřížky 10 metrů",
  "switchBasemap": "Přepnout podkladovou mapu"
});