define({
  "_widgetLabel": "دليل الاستجابة للطوارئ",
  "ergMainPageTitle": "بناءً على دليل الاستجابة للطوارئ 2016",
  "coordInputLabelStart": "موقع الإخراج (DD)",
  "coordInputLabel": "موقع الإخراج",
  "addPointToolTip": "إضافة موقع الإخراج",
  "drawPointToolTip": "انقر لإضافة موقع إخراج",
  "material": "المادة",
  "materialPlaceholder": "ابدأ الكتابة للبحث عن مادة",
  "table3Message": "تتطلب المادة التي قمت بتحديدها معلومات إضافية إذا كنت تتعامل مع إخراج كبير.\n\nيرجى التأكد من أنه يتوفر لديك القيم الصحيحة المحددة لسرعة الرياح وحاوية النقل.",
  "table2Message": "قد تتسبب المادة التي قمت بتحديدها في كمية كبيرة من غازات خطر الاستنشاق السامة عند إخراجها في الماء.\n\nقد يجب عليك أخذ استخدام المواد التالية في الاعتبار:\n\n",
  "spillSize": "حجم الإخراج",
  "small": "صغير",
  "large": "كبير",
  "fireLabel": "عرض منطقة عزل الحريق",
  "weatherLabel": "الطقس الحالي في موقع الإخراج",
  "weatherIntialText": "<br />يتم التحديث بمجرد تحديد موقع الإخراج",
  "temperature": "درجة الحرارة",
  "wind": "رياح",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "لم يتم الحصول على معلومات الطقس. قم بتحديث قيم سرعة الريح ووقت الإخراج يدويًا",
  "windDirection": "اتجاه الرياح (تهُب تجاه)",
  "timeOfSpill": "وقت الإخراج",
  "day": "يوم",
  "night": "ليلة",
  "windSpeed": "سرعة الريح",
  "low": "منخفض",
  "moderate": "متوسط",
  "high": "ارتفاع",
  "transportContainer": "حاوية النقل",
  "rail": "عربة صهريج تسير على السكك الحديدية",
  "semi": "شاحنة صهريج أو مقطورة تسير في الطريق السريع",
  "mton": "أسطوانات كبيرة عديدة",
  "ston": "أسطوانات صغيرة عديدة أو أسطوانة كبيرة مفردة",
  "ag": "صهريج زراعي",
  "msm": "أسطوانات صغيرة عديدة",
  "bleveLabel": "عرض منطقة عزل BLEVE",
  "capacity": "سعة الحاوية (باللتر)",
  "bleveMessage": "فيما يتعلق بالمادة التي قمت بتحديدها، يمكن عرض مسافة تفريغ إضافية من أجل BLEVE.\n\nولتمكين ذك، قم بتشغيل مفتاح \"عرض منطقة عزل BLEVE\"، ثم حدد سعة الحاوية المناسبة.",
  "noPAZoneMessage": "لا توجد مسافات \"إجراء وقائي\" لهذه المادة، ولم يتم حساب إلا مناطق العزل الأولي ومناطق الإفراغ",
  "settingsTitle": "إعدادات",
  "spillLocationLabel": "موقع الإخراج",
  "spillLocationButtonLabel": "تكوين إعدادات موقع الإخراج",
  "IISettingsLabel": "منطقة العزل الأوَّلي",
  "IIButtonLabel": "تكوين إعدادات العزل الأوَّلي",
  "PASettingsLabel": "منطقة الإجراء الوقائي",
  "PAButtonLabel": "تكوين إعدادات الإجراء الوقائي",
  "downwindSettingsLabel": "منطقة اتجاه الريح",
  "downwindButtonLabel": "تكوين إعدادات اتجاه الريح",
  "fireSettingsLabel": "منطقة عزل الحريق",
  "fireButtonLabel": "تكوين إعدادات عزل الحريق",
  "bleveSettingsLabel": "منطقة عزل BLEVE",
  "bleveButtonLabel": "تكوين إعدادات BLEVE",
  "style": "نمط",
  "lineStyles": {
    "esriSLSDash": "شَرطَة",
    "esriSLSDashDot": "شَرطَة ونقطة",
    "esriSLSDashDotDot": "شرطة ونقطتين",
    "esriSLSDot": "نقطة",
    "esriSLSLongDash": "شرطة طويلة",
    "esriSLSLongDashDot": "شرطة ونقطة طويلين",
    "esriSLSNull": "خالِ",
    "esriSLSShortDash": "شَرطَة قصيرة",
    "esriSLSShortDashDot": "نقطة شرطة قصيرة",
    "esriSLSShortDashDotDot": "نقطة نقطة شرطة قصيرة",
    "esriSLSShortDot": "منطقة صغيرة",
    "esriSLSSolid": "متصل"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "للخلف",
    "esriSFSCross": "شكل متصالب",
    "esriSFSDiagonalCross": "قطري",
    "esriSFSForwardDiagonal": "للأمام",
    "esriSFSHorizontal": "أفقياً",
    "esriSFSNull": "خالِ",
    "esriSFSSolid": "متصل",
    "esriSFSVertical": "عمودي"
  },
  "resultsTitle": "النتائج",
  "publishERGBtn": "نشر",
  "ERGLayerName": "اسم طبقة ERG المنشور",
  "invalidERGLayerName": "يجب ألا يحتوي اسم الطبقة إلا على أحرف أبجدية رقمية وتسطير سفلي",
  "missingERGLayerName": "يجب عليك إدخال اسم لـ ERG",
  "publishingFailedLayerExists": "فشل النشر: لديك خدمة معالم باسم {0}. يرجى اختيار اسم آخر.",
  "checkService": "فحص الخدمة: {0}.",
  "createService": "إنشاء الخدمة: {0}.",
  "unableToCreate": "يتعذر إنشاء: {0}",
  "addToDefinition": "إضافة إلى تعريف: {0}",
  "successfullyPublished": "تم نشر طبقة الويب بشكل ناجح{0}إدارة طبقة الويب",
  "userRole": "تحديث إنشاء الخدمة لأن المستخدم لا يتمتع بأذونات",
  "transparency": "الشفافية",
  "outline": "الحدود",
  "fill": "تعبئة (لا ينطبق اللون إلا عند تعيين النمط إلى مُصمَت)",
  "createERGBtn": "إنشاء مناطق",
  "clearERGBtn": "مسح",
  "labelFormat": "تنسيق التسمية",
  "helpIconTooltip": "أحجام العتبة بين مناطق الإخراج الصغيرة والكبيرة هي:\nالسوائل - 55 جالون (208 لتر)\nالمواد الصلبة - 60 باوند (300 كغم)",
  "cellWidth": "عرض الخلية (x)",
  "cellHeight": "ارتفاع الخلية (y)",
  "invalidNumberMessage": "القيمة الافتراضية غير صحيحة",
  "invalidRangeMessage": "يجب أن تكون القيمة أكبر من 0",
  "gridAngleInvalidRangeMessage": "يجب أن تكون القيمة بين -89.9 و89.9",
  "formatIconTooltip": "مدخلات التنسيق",
  "setCoordFormat": "تعيين سلسلة تنسيق الإحداثيات",
  "prefixNumbers": "أضف البادئة '+/-' إلى الأرقام السالبة والموجبة",
  "cancelBtn": "إلغاء الأمر",
  "applyBtn": "تطبيق",
  "comfirmInputNotation": "تأكيد علامة المدخلات",
  "notationsMatch": "التعليقات التي تطابق المدخلات. يرجى تأكيد ما تريد استخدامه:",
  "missingLayerNameMessage": "يجب إدخال اسم طبقة صحيح قبل النشر",
  "parseCoordinatesError": "يتعذر توزيع الإحداثيات. الرجاء فحص المدخلات.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "درجة دقيقة ثانية",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "الدرجات العشرية - دائرة العرض/خط الطول",
  "DDLongLatNotation": "الدرجات العشرية - خط الطول/دائرة العرض",
  "DDMLatLongNotation": "دقائق عشرية درجات - دائرة العرض/خط الطول",
  "DDMLongLatNotation": "دقائق عشرية درجات - خط الطول/دائرة العرض",
  "DMSLatLongNotation": "ثواني دقائق درجات - دائرة العرض/خط الطول",
  "DMSLongLatNotation": "ثواني دقائق درجات - خط الطول/دائرة العرض",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - حرف الحزمة",
  "UTMHemNotation": "UTM - نصف الكرة (N/S)"
});