define({
  "symbolologyTabLabel": "Symbolisierung konfigurieren",
  "facilitiesDescription": "Einrichtungs-Layer",
  "demographicsDescription": "Demografiedaten-Layer",
  "settingsTitle": "Einstellungen",
  "spillLocationLabel": "Kontaminationsgebiet",
  "spillLocationButtonLabel": "Einstellungen für Kontaminationsgebiete konfigurieren",
  "IISettingsLabel": "Initiale Schutzzone",
  "IIButtonLabel": "Einstellungen für initialen Schutz konfigurieren",
  "PASettingsLabel": "Schutzmaßnahmenzone",
  "PAButtonLabel": "Einstellungen für Schutzmaßnahmen konfigurieren",
  "downwindSettingsLabel": "Windzugrichtungszone",
  "downwindButtonLabel": "Einstellungen für Windzugrichtungen konfigurieren",
  "fireSettingsLabel": "Brandschutzzone",
  "fireButtonLabel": "Einstellungen für Brandschutzzonen konfigurieren",
  "bleveSettingsLabel": "BLEVE-Gefahrenbereich",
  "bleveButtonLabel": "BLEVE-Einstellungen konfigurieren",
  "transparency": "Transparenz",
  "outline": "Umrisslinie",
  "fill": "Füllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",
  "style": "Style",
  "lineStyles": {
    "esriSLSDash": "Strich",
    "esriSLSDashDot": "Strich-Punkt",
    "esriSLSDashDotDot": "Strich-Punkt-Punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Langer Strich",
    "esriSLSLongDashDot": "Langer Strich-Punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kurzer Strich",
    "esriSLSShortDashDot": "Kurzer Strich-Punkt",
    "esriSLSShortDashDotDot": "Kurzer Strich-Punkt-Punkt",
    "esriSLSShortDot": "Kurzer Punkt",
    "esriSLSSolid": "Durchgezogen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Rückwärts",
    "esriSFSCross": "Kreuzförmig",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Vorwärts",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vollfarbe",
    "esriSFSVertical": "Vertikal"
  }
});