define({
  "serviceUrl": "Atur url service:",
  "minIntSpacingLabel": "Ukuran Grid Minimum",
  "lineOpacityLabel": "Keburaman Garis",
  "labelOpacityLabel": "Keburaman Label",
  "centerLabelOpacityLabel": "Keburaman Label Pusat",
  "gridZonePlacementLabel": "Penempatan Label Zona Grid",
  "verticalLineLabels": "Label Garis Vertikal",
  "styleHeaderLabel": "Gaya",
  "indexHeaderLabel": "Komponen Grid",
  "colorHeaderLabel": "Warna",
  "fontSizeHeaderLabel": "Ukuran Font",
  "lineWidthHeaderLabel": "Lebar Garis",
  "horizontalLabel": "Horisontal",
  "verticalLabel": "Vertikal",
  "upperLeftLabel": "Kiri Atas",
  "upperRightLabel": "Kanan Atas",
  "lowerLeftLabel": "Kiri Bawah",
  "lowerRightLabel": "Kanan Bawah",
  "centerLabel": "Pusat",
  "errorMessage": "Halaman konfigurasi berisi kesalahan. Harap perbaiki sebelum menyimpan.",
  "checkBoxLabel": "Tampilkan grid ketika widget ditutup",
  "checkBoxLabelDashboard": "Tampilkan grid",
  "gzd": "Pemilih Zona Grid (GZD)",
  "gsid": "Identifikasi Persegi Grid (GSID) 100.000 meter",
  "grid10k": "Garis Grid 10.000 meter",
  "grid1k": "Garis Grid 1.000 meter",
  "grid100m": "Garis Grid 100 meter",
  "grid10m": "Garis Grid 10 meter",
  "switchBasemap": "Pindah Peta Dasar"
});