define({
  "labelBookmarkName": "Bokmerk gjeldende visning",
  "labelPlay": "Spill av alle",
  "labelStop": "Stopp",
  "labelDelete": "Slett",
  "placeholderBookmarkName": "Bokmerkenavn",
  "errorNameExist": "Bokmerket eksisterer.",
  "errorNameNull": "Ugyldig bokmerkenavn.",
  "editTip": "Rediger bokmerker",
  "exitEditTip": "Avslutt redigeringsmodus",
  "syncTip": "Synkroniser",
  "cardsTips": "Rutenettvisning",
  "listTips": "Listevisning",
  "addBtn": "Legg til",
  "deleteBtn": "Slett",
  "changeThumbnailTip": "Endre miniatyrbilde",
  "dragReorderTip": "Hold og dra for å endre rekkefølgen",
  "deleteBtnTip": "Slett bokmerket",
  "editBtnTip": "Rediger bokmerket",
  "withVisibility": "Med lagsynlighet",
  "searchBookmark": "Søk",
  "bookmarksFromConfig": "Forhåndskonfigurerte bokmerker",
  "bookmarksFromCache": "Lokale midlertidige bokmerker",
  "notice": "Merknad",
  "changeNoticeTips": "Endringer vil bli lagret bare i nettleserens cache. Synkronisering mellom widgeten og konfigurasjonen er koblet fra når du har gjort endringer.",
  "syncNoticeTips": "Dette sletter alle endringene dine og gjenoppretter de konfigurerte bokmerkene.",
  "dontShowAgain": "Ikke vis igjen",
  "saveVisibility": "Lagre synligheten for lag",
  "_widgetLabel": "Bokmerke"
});