define({
  "_widgetLabel": "Entfernung und Richtung",
  "tabLineTitle": "Linie",
  "tabCircleTitle": "Kreis",
  "tabEllipseTitle": "Ellipse",
  "tabRingsTitle": "Ringe",
  "multipleNotationsMessage": " Schreibweisen, die Ihrer Eingabe entsprechen. Geben Sie an, welche Sie verwenden möchten:",
  "invalidCoordinateMessage": "Ungültige Koordinate",
  "confirmInputNotationMessage": "Eingegebene Schreibweise bestätigen",
  "prefixSuffixMessage": "Die eingegebene Koordinate weist sowohl einen Präfix als auch einen Suffix für den Wert des Breiten- und Längengrads auf. Die ausgegebene Koordinate basiert auf dem Präfix.",
  "rememberDecisionMessage": "Meine Eingabe speichern und nicht erneut abfragen.<br/>",
  "majorAxisTooltipMessage": "Klicken Sie auf die Länge der Hauptachse.",
  "minorAxisTooltipMessage": "Bewegen Sie die Maus wieder in die Startposition, um die Nebenachse festzulegen und die Ellipse fertig zu zeichnen.",
  "clickToFinishLineMessage": "Klicken Sie, um das Zeichnen der Linie zu beenden.",
  "doubleClickEllipseMesage": "Doppelklicken Sie, um das Zeichnen von Bereichsringen zu beenden.",
  "invalidCoordinateTypeMessage": "Eingabekoordinatentyp kann nicht ermittelt werden. Überprüfen Sie Ihre Eingabe.",
  "noCenterPointSetMessage": "Kein Mittelpunkt festgelegt. Überprüfen Sie Ihre Eingabe.",
  "ellipseMajorAxis": "Hauptachse",
  "ellipseMinorAxis": "Nebenachse",
  "degreesRangeMessage": "Wert muss zwischen 0 und 360 liegen",
  "millsRangeMessage": "Wert muss zwischen 0 und 6400 liegen",
  "lengthLabel": "Länge",
  "angleLabel": "Winkel",
  "startPointLabel": "Startpunkt",
  "endPointLabel": "Endpunkt",
  "centerPointLabel": "Kreismittelpunkt",
  "distanceTableErrorMessage": "Entfernungstabelle ist leer. Stellen Sie sicher, dass Sie einige Entfernungen eingegeben haben.",
  "setCoordFormatStringMessage": "Zeichenfolge für Koordinatenformat festlegen",
  "prefixMessage": "Positiven und negativen Zahlen ein \"+/-\"-Präfix hinzufügen",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Dezimalgrad – Breitengrad/Längengrad",
  "DDLongLatNotation": "Dezimalgrad – Längengrad/Breitengrad",
  "DDMLatLongNotation": "Grad Dezimalminuten – Breitengrad/Längengrad",
  "DDMLongLatNotation": "Grad Dezimalminuten – Längengrad/Breitengrad",
  "DMSLatLongNotation": "Grad, Minuten, Sekunden – Breitengrad/Längengrad",
  "DMSLongLatNotation": "Grad, Minuten, Sekunden – Längengrad/Breitengrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbuchstabe",
  "UTMHemNotation": "UTM – Hemisphäre (N/S)",
  "circleTitle": "Kreis erstellen aus",
  "radiusLabel": "Radius",
  "diameterLabel": "Durchmesser",
  "startPointPlaceHolderLabel": "Koordinaten eingeben",
  "formatInputLabel": "Eingabe formatieren",
  "drawCircleLabel": "Kreis zeichnen",
  "drawLineLabel": "Linie zeichnen",
  "createCircleInteractivelyLabel": "Kreis interaktiv erstellen",
  "rangeErrorMessage": "Ungültiger Radius oder Durchmesser",
  "numericInvalidMessage": "Geben Sie einen numerischen Wert ein",
  "timeLabel": "Zeit",
  "invalidTimeMessage": "Ungültiger Zeitwert",
  "hoursLabel": "Stunden",
  "minutesLabel": "Minuten",
  "secondsLabel": "Sekunden",
  "rateLabel": "Geschwindigkeit",
  "invalidDistanceMessage": "Ungültiger Entfernungswert",
  "feetSecondsLabel": "Fuß/Sekunde",
  "feetHourLabel": "Fuß/Stunde",
  "kmSecondLabel": "Kilometer/Sekunde",
  "kmHourLabel": "Kilometer/Stunde",
  "metersSecondLabel": "Meter/Sekunde",
  "metersHourLabel": "Meter/Stunde",
  "milesSecondLabel": "Meilen/Sekunde",
  "milesHourLabel": "Meilen/Stunde",
  "nauticalMilesSecondLabel": "Seemeilen/Sekunde",
  "nauticalMilesHourLabel": "Seemeilen/Stunde",
  "clearGraphicsLabel": "Grafiken löschen",
  "ellipseTypeLabel": "Ellipsentyp",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Vollständig",
  "drawEllipseLabel": "Ellipse zeichnen",
  "createEllipseInteractively": "Ellipse interaktiv erstellen",
  "axisLabel": "Achse",
  "majorRadiusLabel": "Hauptachse (Radius)",
  "axisErrorMessage": "Wert muss größer als 0 sein",
  "minorRadiusLabel": "Nebenachse (Radius)",
  "orientationLabel": "Ausrichtung",
  "orientationErrorMessage": "Wert muss zwischen 0 und 360 liegen",
  "warningMessage": "Warnung: Mit dem Werkzeug \"Ellipse\" erstellte Grafiken sind nicht geodätisch.",
  "fromLabel": "Aus",
  "distanceBearingLabel": "Entfernung und Peilung",
  "pointsLabel": "Punkte",
  "createLineInteractively": "Linie interaktiv erstellen",
  "lineLengthErrorMessage": "Ungültige Linienlänge",
  "degreesLabel": "Grad",
  "milsLabel": "Mil",
  "lineTypeLabel": "Typ",
  "interactiveLabel": "Interaktiv",
  "fixedLabel": "Festgelegt",
  "originLabel": "Ursprung",
  "cumulativeLabel": "Kumulativ",
  "numberOfRingsLabel": "Anzahl der Ringe",
  "ringsErrorMessage": "Ungültige Anzahl von Ringen",
  "distanceBetweenRingsLabel": "Entfernung zwischen Ringen",
  "ringsDecimalErrorMessage": "Geben Sie einen numerischen Wert mit 2 Dezimalstellen ein.",
  "distanceUnitsLabel": "Entfernungseinheiten",
  "distancesLabel": "Entfernungen",
  "numberOfRadialsLabel": "Anzahl der Radiale",
  "upLabel": "Nach oben",
  "downLabel": "Nach unten",
  "deleteLabel": "Löschen",
  "radialsErrorMessage": "Ungültige Anzahl von Radialen. Die maximale Anzahl ist 360.",
  "addPointLabel": "Punkt hinzufügen",
  "valueLabel": "Wert",
  "valueText": "Wert eingeben",
  "actionLabel": "Aktion"
});