define({
  "add": "Kliknij, aby dodać nowe",
  "title": "Tytuł",
  "placeholderBookmarkName": "Nazwa zakładki",
  "ok": "OK",
  "cancel": "Anuluj",
  "warning": "Należy zakończyć edycję!",
  "edit": "Edytuj zakładkę",
  "errorNameExist": "Zakładka już istnieje!",
  "errorNameNull": "Nieprawidłowa nazwa zakładki!",
  "addBookmark": "Utwórz nowe",
  "thumbnail": "Miniatura",
  "thumbnailHint": "Kliknij obraz do zaktualizowania",
  "displayBookmarksAs": "Wyświetl zakładki jako",
  "cards": "Karty",
  "list": "Lista",
  "cardsTips": "Widok karty",
  "listTips": "Widok listy",
  "makeAsDefault": "Ustaw jako domyślny",
  "default": "Domyślnie",
  "editable": "Zezwól na dodawanie zakładek w widżecie.",
  "alwaysSync": "Wyświetl zakładki z mapy internetowej",
  "configCustom": "Wyświetl zakładki niestandardowe",
  "import": "Importuj",
  "create": "Tworzenie",
  "importTitle": "Importuj zakładki",
  "importFromWeb": "Importuj zakładki z bieżącej mapy internetowej",
  "selectAll": "Zaznacz wszystkie",
  "noBookmarkInConfig": "Kliknij przycisk â€œImportujâ€ lub â€œUtwórz noweâ€, aby dodać zakładki.",
  "noBookmarkInWebMap": "Na mapie nie skonfigurowano żadnych zakładek.",
  "extent": "Zasięg",
  "saveExtent": "Zapisz zasięg mapy w tej zakładce.",
  "savelayers": "Zapisz widoczność warstwy",
  "withVisibility": "Z widocznością warstwy",
  "bookmark": "Zakładka",
  "addBtn": "Dodaj",
  "deleteBtn": "Usuwanie",
  "editBtn": "Edytuj",
  "dragReorderTip": "Przytrzymaj i przeciągnij, aby zmienić kolejność",
  "deleteBtnTip": "Usuń zakładkę",
  "editBtnTip": "Edytuj zakładkę"
});