define({
  "_widgetLabel": "استعلام",
  "executeQueryTip": "انقر على أحد عناصر المهمة التالية لتنفيذ الاستعلام.",
  "invalidConfig": "تكوين غير صحيح. الرجاء استخدام صفحة إعدادات الاستعلام للحصول على التكوين الصحيح.",
  "queryParams": "خيارات",
  "parameters": "خيارات",
  "queries": "استعلامات",
  "apply": "تطبيق",
  "queryResults": "نتائج",
  "clear": "مسح",
  "noResults": "لم يتم العثور على أية معالم",
  "queryError": "فشل الاستعلام!",
  "numberFound": "عدد المعالم التي تم إيجادها",
  "mapExtentTip": "حدد النتائج على منطقة الخريطة الحالية.",
  "noValue": "لا توجد قيمة",
  "and": "و",
  "stringOperatorIs": "هو",
  "stringOperatorIsNot": "ليس",
  "stringOperatorStartsWith": "البدء بـ",
  "stringOperatorEndsWith": "الانتهاء بـ",
  "stringOperatorContains": "يحتوي على",
  "stringOperatorDoesNotContain": "لا يحتوي على",
  "stringOperatorIsBlank": "فارغ",
  "stringOperatorIsNotBlank": "ليس فارغًا",
  "dateOperatorIsOn": "هو",
  "dateOperatorIsNotOn": "ليس",
  "dateOperatorIsBefore": "قبل",
  "dateOperatorIsAfter": "بعد",
  "dateOperatorDays": "يوم",
  "dateOperatorWeeks": "أسبوع",
  "dateOperatorMonths": "شهر",
  "dateOperatorInTheLast": "في آخر",
  "dateOperatorNotInTheLast": "ليس في الآخر",
  "dateOperatorIsBetween": "بين",
  "dateOperatorIsNotBetween": "ليس بين",
  "dateOperatorIsBlank": "فارغ",
  "dateOperatorIsNotBlank": "ليس فارغًا",
  "numberOperatorIs": "هو",
  "numberOperatorIsNot": "ليس",
  "numberOperatorIsAtLeast": "على الأقل",
  "numberOperatorIsLessThan": "أقل من",
  "numberOperatorIsAtMost": "في الغالب",
  "numberOperatorIsGreaterThan": "أكبر من",
  "numberOperatorIsBetween": "بين",
  "numberOperatorIsNotBetween": "ليس بين",
  "numberOperatorIsBlank": "فارغ",
  "numberOperatorIsNotBlank": "ليس فارغًا",
  "operationalLayerTip": "أضف النتيجة باعتبارها طبقة تشغيلية",
  "queryResult": "نتيجة الاستعلام",
  "specifyParamsTip": "حدد المعلمات للمهمة الحالية",
  "useSpatialFilter": "استخدام عوامل التصفية المكانية لتقييد المعالم",
  "useCurrentMapExtent": "فقط المعالم التي تتقاطع في منطقة الخريطة الحالية",
  "drawGraphicOnMap": "فقط المعالم التي تتقاطع في المنطقة التي يُعرفها المستخدم",
  "specifySpatialFilterMsg": "يرجى تحديد عامل التصفية المكاني للمهمة الحالية.",
  "clearResults": "مسح النتائج",
  "operationalTip": "عند التأشير على الخيار الحالي، تظل النتائج على الخريطة حتى يتم النقر على زر \"${clearResults}\".",
  "noneQueryTip": "لم يتم تكوين مهمة الاستعلام لعنصر واجهة الاستخدام الحالي.",
  "noPermissionsMsg": "ليس لديك أي اذونات للوصول إلى هذه الخدمة.",
  "attributesFromRelationship": "بيانات جدولية من جدول مرتبط",
  "tasks": "المهام",
  "applySpatialFilterToLimitResults": "تطبيق التصفية المكانية لتحديد النتائج",
  "useCurrentExtentTip": "قم فقط بإرجاع المعالم ضمن مدى الخريطة الحالي",
  "useDrawGraphicTip": "لا يُرجِع إلا المعالم التي تتقاطع مع الشكل المرسوم على الخريطة",
  "useFeaturesTip": "قم فقط بإرجاع المعالم ذات العلاقة المكانية مع المعالم في طبقة أخرى",
  "noSpatialLimitTip": "قم بإرجاع المعالم ضمن المدى الكامل للخريطة",
  "applySearchDistance": "تطبيق مسافة البحث",
  "spatialRelationship": "علاقة مكانية",
  "relatedLayer": "الطبقات المرتبطة",
  "bufferDistance": "مسافة النطاق",
  "miles": "ميل",
  "kilometers": "كيلومترات",
  "feet": "قدم",
  "meters": "متر",
  "yards": "ياردة",
  "nauticalMiles": "أميال بحرية",
  "back": "الخلف",
  "execute": "تنفيذ",
  "zoomTo": "تكبير/تصغير إلى",
  "openAttributeTable": "عرض في جدول البيانات",
  "noResult": "لا توجد نتائج.",
  "noTask": "لا توجد مهام.",
  "removeThisResult": "إزالة هذه النتيجة",
  "attributeCriteira": "معايير البيانات الجدولية",
  "spatialFilter": "عامل التصفية المكاني",
  "value": "قيمة",
  "noAttributeSpatialFilterTip": "لم يتم تعريف عوامل تصفية، وسيتم إرجاع كل المعالم.",
  "showAllRelatedRecords": "إظهار كل السجلات ذات الصلة",
  "changeSymbol": "تغيير الرموز",
  "queryCriteira": "معايير الاستعلام",
  "customQuery": "استعلام مخصص",
  "layer": "طبقة",
  "createCustomQuery": "إنشاء استعلام مخصص"
});