define({
  "symbolologyTabLabel": "シンボルの構成",
  "facilitiesDescription": "施設レイヤー",
  "demographicsDescription": "人口レイヤー",
  "settingsTitle": "設定",
  "spillLocationLabel": "流出位置",
  "spillLocationButtonLabel": "流出位置設定の構成",
  "IISettingsLabel": "初期隔離ゾーン",
  "IIButtonLabel": "初期隔離設定の構成",
  "PASettingsLabel": "防護措置ゾーン",
  "PAButtonLabel": "防護措置設定の構成",
  "downwindSettingsLabel": "風下ゾーン",
  "downwindButtonLabel": "風下設定の構成",
  "fireSettingsLabel": "火炎隔離ゾーン",
  "fireButtonLabel": "火炎隔離設定の構成",
  "bleveSettingsLabel": "BLEVE 隔離ゾーン",
  "bleveButtonLabel": "BLEVE 設定の構成",
  "transparency": "透過表示",
  "outline": "アウトライン",
  "fill": "塗りつぶし (スタイルを実線に設定した場合のみ色を適用)",
  "style": "スタイル",
  "lineStyles": {
    "esriSLSDash": "破線",
    "esriSLSDashDot": "1 点鎖線",
    "esriSLSDashDotDot": "2 点鎖線",
    "esriSLSDot": "ドット",
    "esriSLSLongDash": "長い破線",
    "esriSLSLongDashDot": "長い 1 点鎖線",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "短い破線",
    "esriSLSShortDashDot": "短い 1 点鎖線",
    "esriSLSShortDashDotDot": "短い 2 点鎖線",
    "esriSLSShortDot": "短いドット",
    "esriSLSSolid": "実線"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "逆方向",
    "esriSFSCross": "クロス",
    "esriSFSDiagonalCross": "対角線",
    "esriSFSForwardDiagonal": "正方向",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "実線",
    "esriSFSVertical": "鉛直方向"
  }
});