define({
  "_widgetLabel": "Příručka pro záchranné akce v nouzových situacích",
  "ergMainPageTitle": "Na základě Příručka pro záchranné akce v nouzových situacích 2016",
  "coordInputLabelStart": "Poloha znečištění (DD)",
  "coordInputLabel": "Poloha znečištění",
  "addPointToolTip": "Přidat polohu znečištění",
  "drawPointToolTip": "Kliknutím přidejte polohu znečištění",
  "material": "Materiál",
  "materialPlaceholder": "Začněte psát pro vyhledání materiálu",
  "table3Message": "Materiál, který jste vybrali, vyžaduje dodatečné informace v případě, že se jedná o velké znečištění.\n\nUjistěte se prosím, že jste vybrali správné hodnoty pro rychlost větru a transportní kontejner.",
  "table2Message": "Materiál, který jste vybrali, může uvolnit velké množství plynů, které jsou toxické při vdechování, pokud se dostane do kontaktu s vodou.\n\nZvažte použití následujícího materiálu(ů):\n\n",
  "spillSize": "Velikost oblasti znečištění",
  "small": "Malý",
  "large": "Velký",
  "fireLabel": "Zobrazit protipožární izolační zónu",
  "weatherLabel": "Aktuální počasí v oblasti znečištění",
  "weatherIntialText": "<br />Aktualizováno, jakmile byla identifikována oblast znečištění",
  "temperature": "Teplota",
  "wind": "Vítr",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informace o počasí se nepodařilo získat. Aktualizujte rychlost větru a čas znečištění ručně",
  "windDirection": "Směr větru (kam vane)",
  "timeOfSpill": "Čas znečištění",
  "day": "Den",
  "night": "Noc",
  "windSpeed": "Rychlost větru",
  "low": "Nízká",
  "moderate": "Střední",
  "high": "Vysoká",
  "transportContainer": "Transportní kontejner",
  "rail": "Železniční cisternový vůz",
  "semi": "Kamion či přívěs s cisternou",
  "mton": "Několikatunové válce",
  "ston": "Více malých válců nebo jednotunový válec",
  "ag": "Zemědělská cisterna",
  "msm": "Více malých válců",
  "bleveLabel": "Zobrazit izolační zónu BLEVE",
  "capacity": "Kapacita kontejneru (litry)",
  "bleveMessage": "Pro vámi zvolený materiál lze zobrazit dodatečnou evakuační vzdálenost pro BLEVE.\n\nPokud si přejete tuto funkci povolit, nastavte přepínač Zobrazit izolační zónu BLEVE na ON a vyberte kapacitu příslušného kontejneru.",
  "noPAZoneMessage": "Pro tento materiál nejsou k dispozici ochranné akční vzdálenosti. Spočítány jsou pouze počáteční izolační zóny a evakuační zóny.",
  "settingsTitle": "Nastavení",
  "spillLocationLabel": "Poloha znečištění",
  "spillLocationButtonLabel": "Konfigurovat nastavení polohy znečištění",
  "IISettingsLabel": "Počáteční zóna izolace",
  "IIButtonLabel": "Konfigurovat nastavení počáteční izolace",
  "PASettingsLabel": "Ochranná akční zóna",
  "PAButtonLabel": "Konfigurovat nastavení ochranných opatření",
  "downwindSettingsLabel": "Zóna ve směru větru",
  "downwindButtonLabel": "Konfigurovat nastavení směru větru",
  "fireSettingsLabel": "Protipožární izolační zóna",
  "fireButtonLabel": "Konfigurovat nastavení protipožární izolační zóny",
  "bleveSettingsLabel": "Izolační zóna BLEVE",
  "bleveButtonLabel": "Konfigurovat nastavení BLEVE",
  "style": "Styl",
  "lineStyles": {
    "esriSLSDash": "Čárkovaná",
    "esriSLSDashDot": "Čerchovaná",
    "esriSLSDashDotDot": "Dvojčerchovaná",
    "esriSLSDot": "Tečka",
    "esriSLSLongDash": "Čárkovaná s dlouhými čárkami",
    "esriSLSLongDashDot": "Čerchovaná s dlouhými čárkami",
    "esriSLSNull": "Prázdný",
    "esriSLSShortDash": "Krátké čárky",
    "esriSLSShortDashDot": "Čerchovaná s krátkými čárkami",
    "esriSLSShortDashDotDot": "Dvojitě čerchovaná s krátkými čárkami",
    "esriSLSShortDot": "Tečkovaná",
    "esriSLSSolid": "Plný"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Dozadu",
    "esriSFSCross": "Křížek",
    "esriSFSDiagonalCross": "Diagonální",
    "esriSFSForwardDiagonal": "Dopředu",
    "esriSFSHorizontal": "Vodorovně",
    "esriSFSNull": "Prázdný",
    "esriSFSSolid": "Plný",
    "esriSFSVertical": "Svisle"
  },
  "resultsTitle": "Výsledky",
  "publishERGBtn": "Publikovat",
  "ERGLayerName": "Zveřejněný název vrstvy ERG",
  "invalidERGLayerName": "Jméno vrstvy smí obsahovat pouze alfanumerické znaky a podtržítka",
  "missingERGLayerName": "Musíte zadat název ERG",
  "publishingFailedLayerExists": "Zveřejnění se nezdařilo: Název služby funkce {0} již existuje. Zvolte prosím jiný název.",
  "checkService": "Zkontrolovat službu: {0}",
  "createService": "Vytvořit službu: {0}",
  "unableToCreate": "Nelze vytvořit: {0}",
  "addToDefinition": "Přidat do definice: {0}",
  "successfullyPublished": "Webová vrstva {0} úspěšně zveřejněna. Spravovat webovou vrstvu",
  "userRole": "Nelze vytvořit službu, protože uživatel nemá oprávnění",
  "transparency": "Průhlednost",
  "outline": "Obrys",
  "fill": "Výplň (barva se použije, pouze pokud je styl nastaven jako plný)",
  "createERGBtn": "Vytvořit zóny",
  "clearERGBtn": "Zrušit výběr",
  "labelFormat": "Formát popisku",
  "helpIconTooltip": "Prahová hodnota mezi malou a velkou velikostí znečištění je \nKapaliny - 208 litrů\nPevné látky - 300 kilogramů",
  "cellWidth": "Šířka buňky (x)",
  "cellHeight": "Výška buňky (y)",
  "invalidNumberMessage": "Zadaná hodnota je neplatná",
  "invalidRangeMessage": "Hodnota musí být větší než 0",
  "gridAngleInvalidRangeMessage": "Hodnota musí být mezi -89,9 a 89,9",
  "formatIconTooltip": "Formátovat vstup",
  "setCoordFormat": "Nastavit řetězec formátu souřadnic",
  "prefixNumbers": "Ke kladným a záporným číslům přidejte předponu +/-",
  "cancelBtn": "Storno",
  "applyBtn": "Použít",
  "comfirmInputNotation": "Potvrďte označení vstupu",
  "notationsMatch": "označení odpovídají vašemu vstupu. Potvrďte prosím, která chcete použít:",
  "missingLayerNameMessage": "Před zveřejněním musíte zadat platný název vrstvy",
  "parseCoordinatesError": "Souřadnice nelze analyzovat. Zkontrolujte zadané hodnoty.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "Vojenská hlásná síť (MGRS)",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desetinné stupně – Zeměpisná šířka / zeměpisná délka",
  "DDLongLatNotation": "Desetinné stupně – Zeměpisná délka / zeměpisná šířka",
  "DDMLatLongNotation": "Stupně a desetinné minuty – Zeměpisná šířka / zeměpisná délka",
  "DDMLongLatNotation": "Stupně a desetinné minuty – Zeměpisná délka / zeměpisná šířka",
  "DMSLatLongNotation": "Stupně minuty vteřiny – Zeměpisná šířka / zeměpisná délka",
  "DMSLongLatNotation": "Stupně minuty vteřiny – Zeměpisná délka / zeměpisná šířka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "Vojenská hlásná síť (MGRS)",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – písmeno pásma",
  "UTMHemNotation": "UTM – polokoule (S/J)"
});