define({
  "_widgetLabel": "Jarak dan Arah",
  "tabLineTitle": "Garis",
  "tabCircleTitle": "Lingkaran",
  "tabEllipseTitle": "Elips",
  "tabRingsTitle": "Cincin",
  "multipleNotationsMessage": " notasi yang sesuai dengan input Anda. Harap konfirmasikan yang ingin Anda gunakan:",
  "invalidCoordinateMessage": "Koordinat Tidak Valid",
  "confirmInputNotationMessage": "Konfirmasikan Notasi Input",
  "prefixSuffixMessage": "Koordinat input telah terdeteksi memiliki awalan dan akhiran untuk nilai lintang atau bujur, koordinat yang dihasilkan didasarkan pada awalan.",
  "rememberDecisionMessage": "Ingat keputusan saya dan jangan tanya lagi.<br/>",
  "majorAxisTooltipMessage": "Klik panjang sumbu utama",
  "minorAxisTooltipMessage": "Gerakkan mouse kembali ke posisi awal untuk mengatur sumbu minor & menyelesaikan gambar elips",
  "clickToFinishLineMessage": "Klik untuk menyelesaikan gambar garis",
  "doubleClickEllipseMesage": "Klik dua kali untuk menyelesaikan gambar cincin jangkauan",
  "invalidCoordinateTypeMessage": "Tidak dapat menentukan jenis koordinat input",
  "noCenterPointSetMessage": "Tidak ada titik tengah diatur. Harap periksa input Anda",
  "ellipseMajorAxis": "Sumbu Utama",
  "ellipseMinorAxis": "Sumbu Minor",
  "degreesRangeMessage": "Nilai harus di antara 0 dan 360",
  "millsRangeMessage": "Nilai harus di antara 0 dan 6400",
  "lengthLabel": "Panjang",
  "angleLabel": "Sudut",
  "startPointLabel": "Titik Mulai",
  "endPointLabel": "Titik Selesai",
  "centerPointLabel": "Titik Tengah",
  "distanceTableErrorMessage": "Tabel jarak kosong. Harap pastikan Anda memasukkan beberapa jarak.",
  "setCoordFormatStringMessage": "Atur Format Koordinat String",
  "prefixMessage": "Tambahkan awalan '+/-' untuk nomor positif dan negatif",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Derajat Desimal - Garis Lintang/Garis Bujur",
  "DDLongLatNotation": "Derajat Desimal - Garis Bujur/Garis Lintang",
  "DDMLatLongNotation": "Menit Derajat Desimal - Garis Lintang/Garis Bujur",
  "DDMLongLatNotation": "Menit Derajat Desimal - Garis Bujur/Garis Lintang",
  "DMSLatLongNotation": "Detik Derajat Desimal - Garis Lintang/Garis Bujur",
  "DMSLongLatNotation": "Detik Derajat Desimal - Garis Bujur/Garis Lintang",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisfer (N/S)",
  "circleTitle": "Buat Lingkaran Dari",
  "radiusLabel": "Radius",
  "diameterLabel": "Diameter",
  "startPointPlaceHolderLabel": "Masukkan Koordinat",
  "formatInputLabel": "Format Input",
  "drawCircleLabel": "Gambar Lingkaran",
  "drawLineLabel": "Gambar Garis",
  "createCircleInteractivelyLabel": "Buat Lingkaran Secara Interaktif",
  "rangeErrorMessage": "Radius atau diameter tidak valid",
  "numericInvalidMessage": "Harap masukkan nilai numerik",
  "timeLabel": "Waktu",
  "invalidTimeMessage": "Nilai waktu tidak valid",
  "hoursLabel": "Jam",
  "minutesLabel": "Menit",
  "secondsLabel": "Detik",
  "rateLabel": "Laju",
  "invalidDistanceMessage": "Nilai jarak tidak valid",
  "feetSecondsLabel": "Kaki/detik",
  "feetHourLabel": "Kaki/jam",
  "kmSecondLabel": "Kilometer/detik",
  "kmHourLabel": "Kilometer/jam",
  "metersSecondLabel": "Meter/detik",
  "metersHourLabel": "Meter/jam",
  "milesSecondLabel": "Mil/detik",
  "milesHourLabel": "Mil/jam",
  "nauticalMilesSecondLabel": "Mil Laut/detik",
  "nauticalMilesHourLabel": "Mil Laut/jam",
  "clearGraphicsLabel": "Hapus Grafik",
  "ellipseTypeLabel": "Jenis Elips",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Penuh",
  "drawEllipseLabel": "Gambar Elips",
  "createEllipseInteractively": "Buat Elips Secara Interaktif",
  "axisLabel": "Sumbu",
  "majorRadiusLabel": "Utama (Radius)",
  "axisErrorMessage": "Nilai harus lebih besar dari 0",
  "minorRadiusLabel": "Minor (Radius)",
  "orientationLabel": "Orientasi",
  "orientationErrorMessage": "Nilai harus di antara 0 dan 360",
  "warningMessage": "Peringatan: Grafik yang dibuat menggunakan alat elips tidak bersifat geodetic",
  "fromLabel": "Dari",
  "distanceBearingLabel": "Jarak dan Poros",
  "pointsLabel": "Titik",
  "createLineInteractively": "Buat Garis Secara Interaktif",
  "lineLengthErrorMessage": "Panjang Tidak Valid",
  "degreesLabel": "Degress",
  "milsLabel": "Mil",
  "lineTypeLabel": "Jenis",
  "interactiveLabel": "Interaktif",
  "fixedLabel": "Tetap",
  "originLabel": "Asli",
  "cumulativeLabel": "Kumulatif",
  "numberOfRingsLabel": "Jumlah Cincin",
  "ringsErrorMessage": "Invalid cincin tidak valid",
  "distanceBetweenRingsLabel": "Jarak Antara Cincin",
  "ringsDecimalErrorMessage": "Masukkan nilai numerik hingga 2 desimal",
  "distanceUnitsLabel": "Unit Jarak",
  "distancesLabel": "Jarak",
  "numberOfRadialsLabel": "Jumlah Radial",
  "upLabel": "Atas",
  "downLabel": "Bawah",
  "deleteLabel": "Hapus",
  "radialsErrorMessage": "Jumlah radial tidak valid. Maksimum yang diizinkan adalah 360",
  "addPointLabel": "Tambah Titik",
  "valueLabel": "Nilai",
  "valueText": "Masukkan Nilai",
  "actionLabel": "Tindakan"
});