define({
  "serviceUrl": "Ange tjänst-URL:",
  "minIntSpacingLabel": "Minsta rutnätsstorlek",
  "lineOpacityLabel": "Linjeopacitet",
  "labelOpacityLabel": "Etikettopacitet",
  "centerLabelOpacityLabel": "Opacitet i mitten av etiketten",
  "gridZonePlacementLabel": "Placering av etiketter i rutnätszon",
  "verticalLineLabels": "Etiketter för vertikal linje",
  "styleHeaderLabel": "Format",
  "indexHeaderLabel": "Rutnätskomponent",
  "colorHeaderLabel": "Färg",
  "fontSizeHeaderLabel": "Teckenstorlek",
  "lineWidthHeaderLabel": "Linjebredd",
  "horizontalLabel": "Horisontell",
  "verticalLabel": "Vertikal",
  "upperLeftLabel": "Övre vänstra",
  "upperRightLabel": "Övre högra",
  "lowerLeftLabel": "Nedre vänstra",
  "lowerRightLabel": "Nedre högra",
  "centerLabel": "Centrera",
  "errorMessage": "Konfigurationssidan innehåller fel. Åtgärda innan du sparar.",
  "checkBoxLabel": "Visa rutätet när widgeten är stängd",
  "checkBoxLabelDashboard": "Visa rutnät",
  "gzd": "Tecken för rutnätszon (GZD)",
  "gsid": "100 000 meter identifiering av rutnätskvadrat (GSID)",
  "grid10k": "10 000 meter rutnätslinjer",
  "grid1k": "1 000 meter rutnätslinjer",
  "grid100m": "100 meter rutnätslinjer",
  "grid10m": "10 meter rutnätslinjer",
  "switchBasemap": "Byt baskarta"
});