define({
  "_widgetLabel": "Consapevolezza situazionale",
  "locate_incident": "Individua incidente",
  "reverse_geocoded_address": "Indirizzo più vicino",
  "reverse_geocoded_error": "Non disponibile",
  "now": "ORA",
  "wind": "VENTO",
  "SUN": "DOM",
  "MON": "LUN",
  "TUE": "MAR",
  "WED": "MER",
  "THU": "GIO",
  "FRI": "VEN",
  "SAT": "SAB",
  "actionLabel": "Imposta posizione",
  "drawPoint": "Disegna punto",
  "drawLine": "Disegna linea",
  "drawPolygon": "Disegna poligono",
  "saveIncident": "Salva",
  "clearIncident": "Ricomincia",
  "noFeaturesFound": "Nessuna feature trovata.",
  "downloadCSV": "Scarica",
  "sum": "Somma",
  "min": "Minima",
  "max": "Massima",
  "avg": "Mediocre",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "Completato",
  "delete_btn": "Elimina",
  "get_directions": "Ottieni indicazioni",
  "incident": "Richiesta di assistenza",
  "incidents": "Incidenti",
  "buffer": "Distanza di buffer",
  "buffers": "Buffer",
  "weather": "Meteo",
  "poweredBy": "Basato su",
  "_featureAction_ActionLabel": "Imposta posizione",
  "_featureAction_AddRemoveActionLabel": "Aggiungi/rimuovi posizione",
  "snapshot": "Cartella SnapShot creata da ID app:",
  "user_credentials": "L'utente non dispone di privilegi validi.",
  "notPolySnapShot": "Specificare una distanza di buffer prima di creare uno snapshot.",
  "notPolyReport": "Nessun risultato valido da aggiungere al report.",
  "notValidDownload": "Nessun risultato valido da scaricare.",
  "of_append": "di",
  "layer_append": "layer",
  "downloadAll": "Scarica tutto",
  "createSnapshot": "Crea snapshot",
  "createReport": "Crea report",
  "calculated_results": "Informazioni di riepilogo",
  "closest": "Feature più vicina",
  "proximity": "Prossimità",
  "summary": "Riepilogo",
  "groupedSummary": "Conteggi raggruppati",
  "_count": "Conteggio",
  "approximate": "approssimativo",
  "snapshot_name": "Imposta proprietà snapshot",
  "report_name": "Imposta proprietà report",
  "invalid_snapshot_name": "Nome snapshot non valido.",
  "invalid_report_name": "Titolo report non valido.",
  "orientation": "Orientamento",
  "pageSize": "Dimensione Pagina",
  "comments": "Commenti",
  "choose_group": "Gruppi",
  "forecast": "Previsioni",
  "select_group": "Seleziona gruppo",
  "select_group_instruction": "Lo snapshot sarà creato e condiviso con il gruppo selezionato",
  "information_append": " Informazioni",
  "distance": "DISTANZA",
  "buffer_invalid": "Inserire un numero valido tra ${min} e ${max}"
});