define({
  "_widgetLabel": "Konvertering af koordinater",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader - Breddegrad/Længdegrad",
  "DDLongLatNotation": "Decimalgrader - Længdegrad/Breddegrad",
  "DDMLatLongNotation": "Grader Decimal Minutter - Breddegrad/Længdegrad",
  "DDMLongLatNotation": "Grader Decimal Minutter - Længdegrad/Breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/Længdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Længdegrad/Breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bånd Bogstav",
  "UTMHemNotation": "UTM - Hemisfære (N/S)",
  "formatInput": "Formatangivelse",
  "copyAll": "Kopiér alle",
  "copySuccessful": "Kopiering lykkedes",
  "copyFailed": "Kan ikke kopiere. Brug CTRL+C som alternativ.",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Kontrollér dit input.",
  "comfirmInputNotation": "Bekræft input-notation",
  "latLongWarningMessage": "Input-koordinaten er blevet registreret med både et præfiks og et suffiks for bredde- længdegradsværdien; den returnerede koordinat er baseret på præfikset.",
  "inputLabel": "Input",
  "outputLabel": "Output",
  "cancelButtonLabel": "Annuller",
  "applyButtonLabel": "Anvend",
  "posNegPrefixLabel": "Tilføj \"+/-\" præfikset til positive og negative tal",
  "editCoordinateDialogTitle": "Indstil koordinatformat-streng",
  "rememberDecisionLabel": "Husk min beslutning, og spørg ikke igen.<br/>",
  "coordinateInputLabel": "Angiv koordinater, eller klik på kortet",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "der er fundet notationer, der matcher dit input. Bekræft, hvilken du vil bruge:",
  "copyToClipboard": "Kopiér til udklipsholder",
  "formatOutput": "Formatér output",
  "addNewNotation": "Tilføj ny notation",
  "notationAddedMessage": "Ny notation tilføjet",
  "addLabel": "Tilføj",
  "removeCoordinate": "Fjern koordinat",
  "expandOutput": "Udvid output",
  "latitudeLabel": "Bredde",
  "longitudeLabel": "Længde",
  "quadrantLabel": "Kvadrant",
  "keyLabel": "Nøgle",
  "fifteenDegreeLabel": "15Â° Kvadrant",
  "oneDegreeLabel": "1Â° Kvadrant",
  "eastingLabel": "Østlig",
  "northingLabel": "Nordlig",
  "zoneLabel": "Zone",
  "bandLabel": "Bånd",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Gitter kv.",
  "hemisphereLabel": "Halvkugle"
});