define({
  "_widgetLabel": "Razdalja in navodila za pot",
  "tabLineTitle": "Linija",
  "tabCircleTitle": "Krog",
  "tabEllipseTitle": "Elipsa",
  "tabRingsTitle": "Obroči",
  "multipleNotationsMessage": " Najden je zapis, ki se ujema z vašim vnosom. Potrdite, katerega želite uporabiti:",
  "invalidCoordinateMessage": "Neveljavne koordinate",
  "confirmInputNotationMessage": "Potrdite zapis vnosa",
  "prefixSuffixMessage": "Zaznano je bilo, da ima vhodna koordinata tako predpono kot pripono za vrednosti geografske širine ali geografske dolžine, vrnjena je koordinata na osnovi predpone.",
  "rememberDecisionMessage": "Zapomni si mojo odločitev in me ne sprašuj več.<br/>",
  "majorAxisTooltipMessage": "Kliknite na dolžino velike osi",
  "minorAxisTooltipMessage": "Miško premaknite na začetni položaj, da nastavite malo os in dokončate izris elipse",
  "clickToFinishLineMessage": "Kliknite, da dokončate izris linije",
  "doubleClickEllipseMesage": "Dvakrat kliknite, da dokončate izris obročev dosega",
  "invalidCoordinateTypeMessage": "Tipa vhodnih koordinat ni mogoče določiti. Preverite svoj vnos",
  "noCenterPointSetMessage": "Središčna točka ni določena. Preverite svoj vnos",
  "ellipseMajorAxis": "Velika os",
  "ellipseMinorAxis": "Mala os",
  "degreesRangeMessage": "Vrednost mora biti med 0 in 360",
  "millsRangeMessage": "Vrednost mora biti med 0 in 6400",
  "lengthLabel": "Dolžina",
  "angleLabel": "Kot",
  "startPointLabel": "Začetna točka",
  "endPointLabel": "Končna točka",
  "centerPointLabel": "Središčna točka",
  "distanceTableErrorMessage": "Tabela razdalj je prazna. Vnesite nekaj razdalj.",
  "setCoordFormatStringMessage": "Nastavi format niza koordinat",
  "prefixMessage": "Pozitivnim in negativnim številkam dodaj predpono »+/–«",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Decimalne stopinje – geografska širina/geografska dolžina",
  "DDLongLatNotation": "Decimalne stopinje – geografska dolžina/geografska širina",
  "DDMLatLongNotation": "Stopinje Decimalne minute – geografska širina/geografska dolžina",
  "DDMLongLatNotation": "Stopinje Decimalne minute – geografska dolžina/geografska širina",
  "DMSLatLongNotation": "Stopinje Minute Sekunde – geografska širina/geografska dolžina",
  "DMSLongLatNotation": "Stopinje Minute Sekunde – geografska dolžina/geografska širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – črka pasu",
  "UTMHemNotation": "UTM – hemisfera (S/J)",
  "circleTitle": "Ustvari krog iz",
  "radiusLabel": "Polmer",
  "diameterLabel": "Premer",
  "startPointPlaceHolderLabel": "Vnesi koordinate",
  "formatInputLabel": "Vhodni format",
  "drawCircleLabel": "Nariši krog",
  "drawLineLabel": "Nariši linijo",
  "createCircleInteractivelyLabel": "Interaktivno ustvari krog iz",
  "rangeErrorMessage": "Neveljaven polmer ali premer",
  "numericInvalidMessage": "Vnesite številsko vrednost",
  "timeLabel": "Čas",
  "invalidTimeMessage": "Neveljavna časovna vrednost",
  "hoursLabel": "Ure",
  "minutesLabel": "Minute",
  "secondsLabel": "Sekunde",
  "rateLabel": "Stopnja",
  "invalidDistanceMessage": "Neveljavna vrednost razdalje",
  "feetSecondsLabel": "Čevljev/sekundo",
  "feetHourLabel": "Čevljev/uro",
  "kmSecondLabel": "Kilometrov/sekundo",
  "kmHourLabel": "Kilometrov/uro",
  "metersSecondLabel": "Metrov/sekundo",
  "metersHourLabel": "Metrov/uro",
  "milesSecondLabel": "Milj/sekundo",
  "milesHourLabel": "Milj/uro",
  "nauticalMilesSecondLabel": "Navtičnih milj/sekundo",
  "nauticalMilesHourLabel": "Navtičnih milj/uro",
  "clearGraphicsLabel": "Počisti grafike",
  "ellipseTypeLabel": "Tip elipse",
  "ellipseSemiLabel": "Polovična",
  "ellipseFullLabel": "Polna",
  "drawEllipseLabel": "Nariši elipso",
  "createEllipseInteractively": "Interaktivno ustvari elipso",
  "axisLabel": "os",
  "majorRadiusLabel": "Velika os (polmer)",
  "axisErrorMessage": "Vrednost mora biti večja od 0",
  "minorRadiusLabel": "Mala os (polmer)",
  "orientationLabel": "Usmerjenost",
  "orientationErrorMessage": "Vrednost mora biti med 0 in 360",
  "warningMessage": "Opozorilo: Grafike, ustvarjene s pomočjo orodja elipse, niso geodetske",
  "fromLabel": "Od",
  "distanceBearingLabel": "Razdalja in smerni kot",
  "pointsLabel": "Točke",
  "createLineInteractively": "Interaktivno ustvari linijo",
  "lineLengthErrorMessage": "Neveljavna dolžina linije",
  "degreesLabel": "Stopinje",
  "milsLabel": "Milje",
  "lineTypeLabel": "Vrsta",
  "interactiveLabel": "Interaktivno",
  "fixedLabel": "Fiksno",
  "originLabel": "Izhodišče",
  "cumulativeLabel": "Skupno",
  "numberOfRingsLabel": "Število obročev",
  "ringsErrorMessage": "Neveljavno število obročev",
  "distanceBetweenRingsLabel": "Razdalja med obroči",
  "ringsDecimalErrorMessage": "Vnesite številsko vrednost na 2 decimalni mesti",
  "distanceUnitsLabel": "Merske enote za razdaljo",
  "distancesLabel": "Razdalje",
  "numberOfRadialsLabel": "Število radialov",
  "upLabel": "Gor",
  "downLabel": "Dol",
  "deleteLabel": "Izbriši",
  "radialsErrorMessage": "Neveljavno število radialov. Največje dovoljeno je 360",
  "addPointLabel": "Dodaj točko",
  "valueLabel": "Vrednost",
  "valueText": "Vnesi vrednost",
  "actionLabel": "Dejanje"
});