define({
  "labelBookmarkName": "現在のビューをブックマークに登録",
  "labelPlay": "すべてを再生",
  "labelStop": "停止",
  "labelDelete": "削除",
  "placeholderBookmarkName": "ブックマーク名",
  "errorNameExist": "すでに存在しているブックマーク名です",
  "errorNameNull": "無効なブックマーク名です",
  "editTip": "ブックマークの編集",
  "exitEditTip": "編集モードの終了",
  "syncTip": "同期",
  "cardsTips": "グリッド ビュー",
  "listTips": "リスト表示",
  "addBtn": "追加",
  "deleteBtn": "削除",
  "changeThumbnailTip": "サムネイルの変更",
  "dragReorderTip": "クリックしたままドラッグして順序変更",
  "deleteBtnTip": "ブックマークの削除",
  "editBtnTip": "ブックマークの編集",
  "withVisibility": "レイヤーの表示設定を使用",
  "searchBookmark": "検索",
  "bookmarksFromConfig": "事前構成済みのブックマーク",
  "bookmarksFromCache": "ローカルの一時的なブックマーク",
  "notice": "注意",
  "changeNoticeTips": "変更内容は、ブラウザーのキャッシュのみに保存されます。変更を行うと、ウィジェットとその構成の間の同期は切断されます。",
  "syncNoticeTips": "これによって、すべての変更が消去され、構成済みのブックマークが復元されます。",
  "dontShowAgain": "再び表示しない",
  "saveVisibility": "レイヤーの表示設定の保存",
  "_widgetLabel": "ブックマーク"
});