define({
  "settings": "설정",
  "titleSettings": "텍스트 설정",
  "imageSettings": "이미지 설정",
  "backgroundColor": "배경 색상",
  "alignment": "정렬",
  "textSize": "텍스트 크기",
  "textColor": "텍스트 색상",
  "dataSource": "데이터 원본",
  "chartSettings": "차트 설정",
  "data": "데이터",
  "dataLabels": "데이터 레이블",
  "displayMode": "디스플레이 모드",
  "featureOption": "각 피처별로 값 표시",
  "categoryOption": "범주별로 값 표시",
  "countOption": "범주별로 피처 개수 표시",
  "fieldOption": "차트로 속성 값 표시",
  "categoryField": "범주 필드",
  "labelField": "레이블 필드",
  "valueFields": "값 필드",
  "operation": "작업",
  "sumOption": "합계",
  "averageOption": "평균",
  "minOption": "최소값",
  "maxOption": "최대값",
  "dataFormat": "데이터 형식",
  "decimalPlaces": "소수 자릿수",
  "prefix": "접두사",
  "suffix": "접미사",
  "dataType": "데이터 유형",
  "featureCount": "피처 개수",
  "fieldStatistics": "필드 통계",
  "display": "보기",
  "chartColor": "차트 색상",
  "horizontalAxis": "수평축",
  "verticalAxis": "수직축",
  "legend": "범례",
  "position": "위치",
  "top": "위쪽",
  "bottom": "아래쪽",
  "useDataSourceSelection": "선택 사용",
  "dataSourceFilterByExtent": "범위별 필터링",
  "changeTemplate": "템플릿 변경",
  "numberSettings": "숫자 설정",
  "gaugeSettings": "게이지 설정",
  "indicators": "지시자",
  "ifValue": "If 값",
  "and": "그리고",
  "numberOperatorIsLessThan": "다음보다 작음",
  "numberOperatorIsGreaterThan": "다음보다 큼",
  "numberOperatorIsBetween": "다음 사이에 속함",
  "numberOperatorIsEqual": "다음과 같음",
  "numberOperatorIsNotEqual": "다음과 같지 않음",
  "then": "Then",
  "ratio": "비율",
  "trueValue": "True 값",
  "changeValueColor": "다음으로 값 색상 변경",
  "changeGaugeColor": "다음으로 게이지 색상 변경",
  "setIndicatorIcon": "다음으로 지시자 아이콘 설정",
  "icons": "아이콘",
  "style": "스타일",
  "placement": "위치",
  "left": "왼쪽",
  "replace": "바꾸기",
  "right": "오른쪽",
  "color": "색상",
  "categoryExists": "범주가 존재합니다!",
  "comboxHint": "한 항목 입력 또는 선택",
  "comboxDisableInputHint": "단답형",
  "sortBy": "정렬 기준",
  "labelAxis": "레이블",
  "valueAxis": "값",
  "minPeriod": "최소 기간",
  "automatic": "자동",
  "periodsWithOutRecords": "레코드가 없는 기간",
  "nullValue": "Null 값",
  "calculatedAsZero": "0으로 계산됨",
  "ignored": "무시됨",
  "maxCategories": "최대 범주",
  "useLayerSymbology": "레이어의 심볼 사용",
  "hollowsize": "비어 있는 영역의 크기",
  "splitField": "분할 필드",
  "parsingperiodTip": "계산에 실패했습니다. 구문 분석 기간이 짧아 시간 간격이 너무 많습니다.",
  "manyCategoryTip": "차트 표시에 실패했습니다. 범주가 너무 많습니다.",
  "setColor": "색상 설정",
  "setTheColorOf": "그런 후 다음의 색상 설정",
  "setTheColorAs": "그런 후 다음과 같이 색상 설정",
  "ifStr": "이때",
  "as": "다음으로:",
  "is": "다음과 같음",
  "isNot": "다음과 같지 않음",
  "barCluster": "막대 군집",
  "individualBar": "개별 막대",
  "allOthers": "기타 모든 항목",
  "category": "범주",
  "indicatorSum": "SUM",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "표시기를 올바르게 설정하세요.",
  "dataRange": "데이터 범위",
  "targetValue": "대상 값",
  "currentValue": "현재 값",
  "gaugeColor": "게이지 색상",
  "min": "최소값",
  "max": "최대값",
  "displayValueIn": "다음에 값 표시:",
  "noData": "데이터 없음",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "경고",
  "noSettingWaring1": "요소를 클릭하여 등록정보를 설정하세요.",
  "noSettingWaring2": "드래그하여 요소의 크기를 조정하거나 순서를 변경하세요.",
  "donNotShowAgain": "다시 표시 안 함",
  "changeTemplateWarning": "이 작업을 수행하면 모든 설정이 지워지고 비어 있는 새 템플릿이 열립니다.",
  "requiredFieldWarning": "이 값이 필요합니다(필수).",
  "dataSourceNotSet": "데이터 원본을 설정하세요.",
  "addIndicatorTip": "지시자 추가",
  "chooseTemplatePopupTitle": "템플릿 선택",
  "filterExtentTipWithaTag": "속성 탭에서 <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>추가 데이터 원본</a>별로 필터를 비활성화할 수 있습니다.",
  "filterExtentTip": "속성 탭에서 추가 데이터 원본별로 필터를 비활성화할 수 있습니다.",
  "customColorByCategory": "범주별로 색상 사용자 정의",
  "randomColor": "임의 색상",
  "valueString": "값",
  "fieldString": "필드(Field)",
  "includeThresholdValue": "임계값 포함",
  "percentage": "백분율",
  "colorSchema": "색 구성표",
  "addCategory": "범주 추가",
  "clickToEdit": "편집하려면 클릭",
  "nullText": "Null",
  "others": "기타",
  "stringsInTemplate": {
    "name_number": "숫자",
    "name_gauge": "게이지",
    "name_vertical_gauge": "수직 게이지",
    "name_horizontal_gauge": "수평 게이지",
    "name_pie": "원형",
    "name_donut": "도넛",
    "name_bar": "바 - 술집",
    "name_stacked_bar": "누적 가로 막대형",
    "name_percentage_stacked_bar": "백분율 누적 가로 막대형",
    "name_column": "열",
    "name_stacked_column": "누적 세로 막대형",
    "name_percentage_stacked_column": "백분율 누적 세로 막대형",
    "name_line": "선형",
    "name_area": "영역",
    "name_stacked_area": "누적 영역",
    "name_percentage_stacked_area": "백분율 누적 영역",
    "titleOfTheInfographic": "인포그래픽 제목",
    "description": "설명: 이 인포그래픽에 대한 추가 정보입니다."
  }
});