define({
  "queries": "쿼리",
  "addNew": "새로 추가",
  "newQuery": "새 쿼리",
  "queryLayer": "쿼리 레이어",
  "setSource": "설정",
  "setDataSource": "데이터 원본 설정",
  "name": "이름",
  "querySource": "데이터 원본",
  "queryName": "작업 이름",
  "queryDefinition": "필터 정의",
  "resultsSetting": "결과 설정",
  "symbolSetting": "심볼 설정",
  "resultSettingTip": "출력 결과에 표시할 것과 표시 방법을 정의합니다.",
  "resultItemTitle": "각 결과 항목의 제목",
  "resultItemContent": "다음 필드 속성이 표시됩니다.",
  "fieldsSetTip": "표시할 필드를 선택합니다. 별칭을 업데이트하고, 순서를 정하고, 형식을 지정할 필드를 선택하세요.",
  "addField": "필드 추가",
  "visibility": "가시성",
  "alias": "별칭",
  "specialType": "특수 유형",
  "actions": "작업",
  "none": "없음",
  "link": "링크",
  "image": "이미지",
  "noField": "필드 없음",
  "operationalLayerTip": "결과를 운영 레이어로 추가",
  "setLayerSymbolTip": "쿼리 결과에 대한 심볼 설정: ",
  "setSelectedSymbolTip": "선택한 피처의 심볼을 설정합니다.",
  "notUseFilter": "필터 사용 안 함",
  "setSourceTip": "쿼리 원본을 설정하세요.",
  "setFilterTip": "필터를 올바르게 설정하세요.",
  "ok": "확인",
  "cancel": "취소",
  "noFilterTip": "필터 식이 정의되지 않으면 이 쿼리 작업은 지정된 데이터 원본의 모든 피처를 나열합니다.",
  "relationships": "릴레이션십",
  "addRelationshipLayer": "새 릴레이션십 추가",
  "relatedTo": "관련 항목",
  "selectOption": "선택하세요.",
  "resultItemSorting": "결과 항목 정렬",
  "field": "필드",
  "sortingOrder": "순서",
  "configureFieldsTip": "쿼리 결과가 정렬될 필드를 구성하세요.",
  "setSortingFields": "정렬 필드 설정",
  "ascending": "오름차순",
  "descending": "내림차순",
  "sortBy": "정렬 기준",
  "thenBy": "다음 기준",
  "addTask": "작업 추가",
  "noTasksTip": "구성된 쿼리가 없습니다. 새 쿼리를 추가하려면 \"${newQuery}\"를 클릭하세요.",
  "infoText": "정보",
  "filters": "필터",
  "results": "결과",
  "optionsText": "옵션",
  "summaryText": "요약",
  "attributeFilter": "속성 필터",
  "attributeFilterTip": "쿼리 레이어를 필터링하는 위젯에서 사용하기 위해 속성 식을 정의합니다.",
  "defineWhereClause": "쿼리에 대한 where 절을 정의합니다.",
  "noExpressionDefinedTip": "정의된 식이 없습니다. 모든 레코드가 반환됩니다.",
  "setExpressions": "식 설정",
  "spatialFilter": "공간 필터",
  "spatialFilterTip": "최종 사용자가 사용할 수 있는 공간 필터를 선택합니다.",
  "defaultOption": "기본값",
  "useCurrentExtentTip": "현재 맵 범위 내에 있는 피처만 반환",
  "useDrawGraphicTip": "맵에 그려진 모양과 교차하는 피처만 반환",
  "useFeaturesTip": "다른 레이어에서 피처와 공간 관계가 있는 피처만 반환",
  "noSpatialLimitTip": "맵의 전체 범위 내에 있는 피처 반환",
  "drawingTools": "그리기 도구 선택",
  "bufferSettings": "버퍼 옵션 활성화",
  "defaultDistance": "기본 거리",
  "bufferDistance": "버퍼 거리",
  "defaultUnit": "기본 단위",
  "miles": "마일",
  "kilometers": "킬로미터",
  "feet": "피트",
  "meters": "미터",
  "yards": "야드",
  "nauticalMiles": "해리",
  "availableSpatialRelationships": "공간 관계 규칙 선택",
  "setSpatialRelationships": "공간 관계 설정",
  "availability": "사용 가능 여부",
  "relationship": "릴레이션십",
  "label": "레이블",
  "intersect": "교차",
  "contain": "포함",
  "areContainedIn": "은(는) 다음에 포함됨:",
  "cross": "건너감",
  "envelopeIntersect": "엔빌롭 교차",
  "overlap": "겹치기",
  "areOverlapped": "이(가) 겹침",
  "touch": "터치",
  "within": "내",
  "areWithin": "이(가) 다음 내에 있음:",
  "indexIntersect": "색인 교차",
  "itemTitle": "항목 제목",
  "displayFields": "디스플레이 필드",
  "sortingFields": "결과 항목 정렬",
  "setDisplayFields": "디스플레이 필드 설정",
  "symbol": "심볼",
  "setSymbol": "사용자 정의 심볼 사용",
  "changeSymbolAtRuntime": "런타임에 심볼을 변경하도록 허용",
  "serviceSymbolTip": "레이어가 정의한 심볼 사용",
  "exportTip": "결과 내보내기 허용",
  "keepResultsTip": "위젯이 닫힌 후에 맵에 결과 보기 유지",
  "queryRelatedRecords": "쿼리 관련 레코드",
  "createLayerForTaskTip": "쿼리 작업이 레이어를 생성하는 방법 지정",
  "oneLayerForTaskTip": "쿼리가 실행될 때마다 레이어 덮어쓰기",
  "multipleLayerForTaskTip": "쿼리가 실행될 때마다 새 레이어 생성",
  "makeDefault": "기본으로 설정",
  "icon": "아이콘",
  "newTask": "새 태스크",
  "addTaskTip": "하나 이상의 쿼리를 위젯에 추가하고 각각에 대한 매개변수를 구성합니다.",
  "webMapPopupTip": "웹 맵에서 레이어의 팝업 구성 사용",
  "customPopupTip": "사용자 정의 콘텐츠 구성",
  "showResultsSetActions": "결과 집합에 대한 작업 표시",
  "zoomTo": "확대/축소",
  "openAttributeTable": "속성 테이블에서 보기",
  "content": "콘텐츠",
  "displaySQLTip": "최종 사용자에 대한 SQL 식 표시",
  "useLayerDefaultSymbol": "레이어의 기본 심볼 사용",
  "setCustomIcon": "사용자 정의 아이콘 설정",
  "layerDefaultSymbolTip": "레이어의 기본 심볼 사용",
  "uploadImage": "이미지 업로드",
  "attributeCriteira": "속성 기준",
  "specifyFilterAtRuntimeTip": "사용자는 이 식에 대한 매개변수를 지정해야 합니다.",
  "value": "값",
  "hideLayersTip": "위젯이 닫히면 쿼리 결과 레이어를 끄세요.",
  "tabLabels": "탭 레이블",
  "tasks": "태스크",
  "queryCriteira": "쿼리 기준",
  "allowCustomQuery": "사용자 정의 쿼리를 생성할 수 있음"
});