define({
  "_widgetLabel": "Gridli Referans Grafiği",
  "newGRGFromAreaButtonLabel": "Bir Alandan Grid Tanımla",
  "newGRGFromPointButtonLabel": "Bir Noktadan Grid Tanımla",
  "newGRGFromAreaTitle": "Bir Alandan Grid Tanımla",
  "newGRGFromPointTitle": "Bir Noktadan Grid Tanımla",
  "newGRGBySizeButtonLabel": "Boyuta göre",
  "newGRGFromRefSystemButtonLabel": "Referans Sistemine göre",
  "newGRGByTimeLabel": "Zaman ve Hıza göre",
  "newGRGFromNonStandardButtonLabel": "Standart Olmayan Grid Tanımla",
  "newGRGAreaBySizeTitle": "Boyuta göre bir Alandan GRG",
  "newGRGAreaBySizeDefineAreaLabel": "GRG Alanı",
  "addGRGAreaPolygonToolTip": "Alan kullanarak GRG Alanı çiz",
  "addGRGAreaExtentToolTip": "Yayılım kullanarak GRG Alanı çiz",
  "rotation": "Grid Döndürme",
  "numberRowsColumnsLabel": "Satır ve sütun sayısını tanımla",
  "newGRGAreaByRefSystemTitle": "Referans Sistemine göre bir Alandan GRG",
  "gridSize": "Grid Boyutu",
  "UTMZoneandBand": "Grid Bölgesi",
  "100000m": "100000 metre",
  "10000m": "10000 metre",
  "1000m": "1000 metre",
  "100m": "100 metre",
  "10m": "10 metre",
  "clipGrid": "GRG Alanına Grid Kırp",
  "newGRGAreaFromNonStandardTitle": "Yeni NGR",
  "newGRGPointBySizeTitle": "Boyuta göre bir Noktadan GRG",
  "newGRGPointByRefSystemTitle": "Referans Sistemine göre bir Noktadan GRG",
  "newGRGPointByTimeTitle": "Zaman ve Hız kullanarak bir Noktadan GRG",
  "time": "Zaman",
  "rate": "Hız",
  "hours": "Saat",
  "minutes": "Dakika",
  "seconds": "Saniye",
  "ftPerSec": "Fit / saniye",
  "ftPerHour": "Fit / saat",
  "kmPerSec": "Kilometre / saniye",
  "kmPerHour": "Kilometre / saat",
  "mPerSec": "Metre / saniye",
  "mPerHour": "Metre / saat",
  "miPerSec": "Mil / saniye",
  "miPerHour": "Mil / saat",
  "nMPerSec": "Deniz Mili / saniye",
  "nMPerHour": "Deniz Mili / saat",
  "settingsTitle": "Ayarlar",
  "labelSettingsLabel": "Etiket Ayarları",
  "labelSettingsButtonLabel": "Etiket Ayarlarını Yapılandır",
  "gridSettingsLabel": "Grid Ayarları",
  "gridSettingsButtonLabel": "Grid Ayarlarını Yapılandır",
  "transparency": "Şeffaflık",
  "labelStyle": "Etiket Stili",
  "font": "Yazı Tipi",
  "textSize": "Metin Boyutu",
  "textColor": "Metin Rengi",
  "halo": "Hale",
  "show": "Göster",
  "lockSettings": "Ayarlar uygulama sahibi tarafından kilitlendi",
  "gridSettings": {
    "cellShape": "Hücre Şekli",
    "cellUnits": "Hücre Birimleri",
    "cellOutline": "Hücre Dış Hat Ayarları",
    "cellFill": "Hücre Doldurma Ayarları",
    "gridReferenceSystem": "Referans Sistemi",
    "gridDatum": "Referans: WGS84",
    "labelStartPosition": "Etiket Başlangıç Noktası",
    "labelType": "Etiket Türü",
    "labelDirection": "Etiket Yönü",
    "gridOrigin": "Grid Başlangıç Noktası",
    "default": "Dikdörtgen",
    "hexagon": "Altıgen",
    "miles": "Mil",
    "kilometers": "Kilometre",
    "feet": "Fit",
    "meters": "Metre",
    "yards": "Yarda",
    "nautical-miles": "Deniz Mili",
    "lowerLeft": "Sol Alt",
    "lowerRight": "Sağ Alt",
    "upperLeft": "Sol Üst",
    "upperRight": "Sağ Üst",
    "center": "Orta",
    "alphaNumeric": "Alfa Sayısal",
    "alphaAlpha": "Alfa Alfa",
    "numeric": "Sayısal",
    "horizontal": "Yatay",
    "vertical": "Dikey",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Etiketleri Göster"
  },
  "publishTitle": "Portala GRG Yayınla",
  "publishGRGBtn": "Yayınla",
  "GRGLayerName": "Yayınlanan GRG Katmanı Adı",
  "invalidGRGLayerName": "Katman adı sadece alfa sayısal karakterler ve alt çizgiler içermelidir",
  "missingGRGLayerName": "GRG için bir ad girmelisiniz",
  "publishingFailedLayerExists": "Yayınlama Başarısız Oldu: Bir detay servisi adı {0} zaten var. Lütfen başka bir ad seçin.",
  "checkService": "Servisi Denetle: {0}.",
  "createService": "Servis Oluştur: {0}.",
  "unableToCreate": "Oluşturulamıyor: {0}",
  "addToDefinition": "Tanıma ekle: {0}",
  "successfullyPublished": "Web katmanı başarılı bir şekilde yayınlandı{0}Web katmanını yönet",
  "userRole": "Kullanıcı gerekli izne sahip olmadığından servis oluşturulamadı",
  "createGRGBtn": "GRG oluştur",
  "clearGRGBtn": "Temizle",
  "labelFormat": "Etiket Formatı",
  "helpIconTooltip": "Z: Grid Zone Designator (GZD)\nS: 100,000-metre Grid Karesi Tanımlama (GSID)\nX: Doğuya yöneltme (X Koordinatı)\nY: Kuzeye yöneltme (Y Koordinat)\n\nÖrnekler:\nZSXY 15SWC8081751205’tir\nZS X,Y 15SWC 80817,51205’tir",
  "addPointToolTip": "GRG Başlangıç Noktası Ekle",
  "cellWidth": "Hücre Genişliği (x)",
  "cellHeight": "Hücre Yüksekliği (y)",
  "invalidNumberMessage": "Girilen değer geçerli değil",
  "invalidRangeMessage": "Değer 0’dan büyük olmalıdır",
  "gridAngleInvalidRangeMessage": "Değer -89,9 ile 89,9 arasında olmalıdır",
  "formatIconTooltip": "Biçim Girdisi",
  "coordInputLabel": "GRG Başlangıç Noktası (DD)",
  "setCoordFormat": "Koordinat Biçimi Dizgisini Ayarla",
  "prefixNumbers": "Pozitif ve negatif sayıların önüne ‘+/-’ işareti ekleyin",
  "cancelBtn": "İptal Et",
  "applyBtn": "Uygula",
  "comfirmInputNotation": "Girdi Gösterimini Onayla",
  "notationsMatch": "gösterimler girdinizle eşleşiyor lütfen hangisini kullanmak istediğinizi belirtin:",
  "numberOfCellsHorizontal": "# Yatay Hücreler",
  "numberOfCellsVertical": "# Dikey Hücreler",
  "gridAngle": "Grid Döndürme",
  "tooManyCellsErrorMessage": "2000’den fazla hücreden oluşan bir grid oluşturmaya çalışıyorsunuz. Grid boyutunu veya grid alanını değiştirerek oluşturulan hücre sayısını azaltmanız önerilir.",
  "missingParametersMessage": "<p>GRG oluşturma formunda eksik veya geçersiz parametreler var. Lütfen kontrol edin:</p><ul><li>Bir GRG alanı çizildi.</li><li>Hücre genişliği ve yüksekliği geçerli değerler içeriyor.</li></ul>",
  "missingOriginParametersMessage": "<p>GRG oluşturma formunda eksik veya geçersiz parametreler var. Lütfen kontrol edin:</p><ul><li>Bir GRG başlangıç noktası ayarlandı.</li><li>Zaman, hız ve açı girişleri geçerli değerler içeriyor.</li></ul>",
  "invalidWidthHeightParametersMessage": ">p<GRG oluşturma formunda eksik veya geçersiz parametreler var. Hücre genişliği ve yüksekliğinin geçerli değerler içerdiğinden emin olun.</p>",
  "invalidHorizontalVerticalParametersMessage": ">p<GRG oluşturma formunda eksik veya geçersiz parametreler var. Hücrelerin yatay ve dikey giriş sayısının geçerli değerler içerdiğinden emin olun.</p>",
  "drawPointToolTip": "GRG başlangıç noktası eklemek için tıklayın",
  "missingLayerNameMessage": "Yayınlayabilmeniz için geçerli bir katman adı girmelisiniz",
  "parseCoordinatesError": "Koordinatlar ayrıştırılamıyor. Girdinizi denetleyin.",
  "grgPolarRegionError": "GRG yayılımı kutup bölgesi içinde. Kutup bölgesine düşen hücreler oluşturulmayacak.",
  "grgPolarOriginError": "Referans Sistemine göre GRG oluşturulurken GRG başlangıç noktası kutup bölgesinde olamaz.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Ondalık Dereceleri - Enlem/Boylam",
  "DDLongLatNotation": "Ondalık Dereceleri  - Boylam/Enlem",
  "DDMLatLongNotation": "Dereceler Ondalık Dakikalar - Enlem/Boylam",
  "DDMLongLatNotation": "Dereceler Ondalık Dakikalar - Boylam/Enlem",
  "DMSLatLongNotation": "Dereceler Dakikalar Saniyeler - Enlem/Boylam",
  "DMSLongLatNotation": "Dereceler Dakikalar Saniyeler - Boylam/Enlem",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bant Harf",
  "UTMHemNotation": "UTM - Yarıküre (K/G)"
});