define({
  "tabs_section_Label": "علامات تبويب",
  "addTab": "إضافة جدول...",
  "layerName": "طبقة",
  "layerType": "نوع عملية التحليل",
  "layerLabel": "التسمية",
  "actions": "إجراءات",
  "closest": "أقرب معلم",
  "proximity": "المقاربة",
  "summary": "ملخص",
  "select_lbl": "-- تحديد --",
  "general_setting_Label": "إعدادات عامة",
  "units_text_lbl": "وحدات المسافة",
  "maximum_distance_lbl": "الحد الأقصى من مسافة أقرب معلم",
  "buffer_text_lbl": "لافتة تسمية النطاق",
  "buffer_lbl": "مسافة النطاق",
  "buffer_max_lbl": "الحد الأقصى من مسافة النطاق",
  "buffer_min_lbl": "الحد الأدنى من مسافة النطاق",
  "buffer_default_lbl": "مسافة النطاق المؤقت الافتراضي",
  "not_less_than_max": "يجب أن تكون المسافة أقل من أقصى مسافة للنطاق",
  "not_between": "يجب أن تكون المسافة بين أدنى وأقصى مسافة للنطاق",
  "not_more_than_min": "يجب أن تكون المسافة أكبر من أدنى مسافة للنطاق",
  "not_valid_number": "يجب أن تكون رقمًا صحيحًا",
  "invalid_value": "قيمة ${type} غير صحيحة",
  "routing_checkBox": "تمكين التوجيه",
  "weather_Label": "إعدادات الطقس",
  "weather_checkBox": "تمكين الطقس",
  "weather_map_layers": "حدد طبقات الطقس...",
  "selected_map_layers": " تم تحديد طبقات الطقس",
  "instruction_weather": "عرض معلومات الطقس في اللوحة.",
  "instruction_weather_layers": "عرض طبقات طقس إضافية.",
  "instruction_weather_metric": "عرض القيم القياسية/المترية.",
  "selectLayers": "حدد طبقات الطقس",
  "weather_removed_message": "خيارات الطقس لم تعد متاحة لعنصر واجهة المستخدم.",
  "currentlySelectedLayer": "حدد من طبقات الخريطة",
  "missingTabLabel": "تفقد على الأقل علامة تبويب واحدة تسميتها",
  "missingLayerInWebMap": "لا توجد طبقات تشغيلية",
  "selectFields": "تحديد حقول",
  "addField": "إضافة حقل",
  "sum": "مجموع",
  "min": "الحد الأدنى",
  "max": "الحد الأقصى",
  "avg": "المتوسط",
  "count": "عدد",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "عرض عدد المعالم",
  "area_checkBox": "عرض مجموع المناطق",
  "length_checkBox": "عرض مجموع الأطوال",
  "max_records": "تم الوصول إلى الحد الأقصى",
  "save_label": "خيارات الحفظ",
  "save_checkbox": "تمكين الحفظ",
  "report_label": "خيارات التقرير",
  "report_checkbox": "تمكين التقرير",
  "csv_label": "خيارات CSV",
  "csv_checkbox": "تصدير كل الحقول",
  "display_label": "خيارات العرض",
  "display_checkbox": "عرض مميزات الملخص",
  "snapshot_label": "خيارات الالتقاط",
  "snapshot_checkbox": "تمكين الالتقاط",
  "must_select_template": "يرجى تحديد أحد قوالب التحرير في خيارات الحفظ.",
  "count_label": "عدّ التسميات",
  "area_label": "تسمية المنطقة",
  "length_label": "تسمية الطول",
  "invalid_string_width": "القيمة طويلة للغاية. ",
  "layer_type_not_supported": "نوع الطبقة غير مدعوم",
  "groupedSummary": "أعداد مُجمّعَة",
  "groupByField": "تجميع بواسطة الحقل",
  "labelType": "إلحاق التسمية",
  "prefix": "كبادئة",
  "suffix": "كلاحقة",
  "need_group_field": "يرجى استخدام إجراء التحرير لتعريف \"تجميع بواسطة الحقل\".",
  "fieldTitle": "حقل",
  "typeTitle": "النوع",
  "actionsTitle": "إجراءات",
  "save_point_checkbox": "حفظ النقاط",
  "save_line_checkbox": "حفظ الخطوط",
  "save_poly_checkbox": "حفظ المضلعات",
  "no_valid_popup_fields": "لا يوجد حقول صحيحة في النافذة المنبثقة. الرجاء استخدام إجراء التحرير لتعريف الحقل.",
  "no_valid_fields": "لا يوجد حقول صحيحة. الرجاء استخدام إجراء التحرير لعرض الخيارات.",
  "incident_label": "لافتة تسمية علامة التبويب",
  "locate_incident_label": "لافتة تسمية منطقة الاهتمام",
  "incident": "طارئ",
  "locate_incident": "تحديد موقع الحادث",
  "buffer_value": "مسافة النطاق",
  "tab_options": "تحليل",
  "export_options": "المخرجات",
  "instruction_save": "حفظ الموقع في خدمة المعالم.",
  "instruction_snapshot": "إنشاء خريطة ويب بناءً على الموقع.",
  "instruction_report": "إنشاء تقرير مطبوع للموقع.",
  "instruction_all_fields": "تصدير كل الحقول بتنزيل CSV.",
  "data_label": "إعدادات البيانات الناتجة",
  "layer_error": "الطبقة مفقودة أو غير صحيحة.",
  "visibility_checkBox": "تعطيل إدارة رؤية الطبقة",
  "downloadTab": {
    "reportLegend": "إعدادات التقرير",
    "textColorLabel": "حدد لون عناوين العمود",
    "setButtonLabel": "تعيين",
    "printGPServiceLabel": "طباعة عنوان URL للخدمة",
    "logoLabel": "الشعار",
    "logoChooserHint": "انقر على أيقونة الصورة لتغيير الصورة",
    "footnoteLabel": "حاشية سفلية"
  }
});