define({
  "_widgetLabel": "הזרמה",
  "streamControls": "פקדי זרימה",
  "streamFilter": "פילטר",
  "startStreaming": "התחל זרימה",
  "stopStreaming": "הפסק זרימה",
  "streamLayers": "שכבות זרימה",
  "startStopStream": "הפעל את האפשרות 'מפסיק הזרמה או מתחיל הזרמה'",
  "clearStream": "הפעל את האפשרות 'נקה תצפיות קודמות'",
  "attributeFilter": "הפעל סינון מאפיינים",
  "spatialFilter": "הפעל סינון מרחבי",
  "configFilter": "הגדר סינון של מאפייני זרם",
  "drawPrevious": "הפעל את האפשרות 'צייר תצפיות קודמות'",
  "addNew": "הוסף סינון",
  "setFilterName": "הגדר את שם הסינון",
  "filterNameExists": "שם הפילטר קיים בטבלה!",
  "invalidFilterName": "השם צריך להיות מילה המורכבת מאותיות a-z, A-Z, ספרות 0-9 או _.",
  "noFilterTip": "לא הוגדרה קונפיגורציית פילטר",
  "addFilterFailed": "הוספת הפילטר נכשלה",
  "filterName": "שם הסינון",
  "limitMapExtent": "הגבל את התצפיות באזור הנוכחי במפה",
  "limitDrawExtent": "הגבל את התצפיות באזור שהוגדר על ידי המשתמש",
  "newFilter": "סינון חדש",
  "filterReadOnly": "הפילטר שהועבר ממפת האינטרנט הוגדר לקריאה בלבד."
});