define({
  "_widgetLabel": "Mrežna referenčna grafika",
  "newGRGFromAreaButtonLabel": "Določi mrežo z območja",
  "newGRGFromPointButtonLabel": "Določi mrežo iz točke",
  "newGRGFromAreaTitle": "Določi mrežo z območja",
  "newGRGFromPointTitle": "Določi mrežo iz točke",
  "newGRGBySizeButtonLabel": "Po dimenziji",
  "newGRGFromRefSystemButtonLabel": "Po koordinatnem sistemu",
  "newGRGByTimeLabel": "Po času in hitrosti",
  "newGRGFromNonStandardButtonLabel": "Določi nestandardno mrežo",
  "newGRGAreaBySizeTitle": "GRG z območja po dimenziji",
  "newGRGAreaBySizeDefineAreaLabel": "Območje GRG",
  "addGRGAreaPolygonToolTip": "Nariši območje GRG s pomočjo poligona",
  "addGRGAreaExtentToolTip": "Nariši območje GRG s pomočjo obsega",
  "rotation": "Zasuk mreže",
  "numberRowsColumnsLabel": "Določi število vrstic in stolpcev",
  "newGRGAreaByRefSystemTitle": "GRG z območja po koordinatnem sistemu",
  "gridSize": "Velikost mreže",
  "UTMZoneandBand": "Mrežna cona",
  "100000m": "100000 metrov",
  "10000m": "10000 metrov",
  "1000m": "1000 metrov",
  "100m": "100 metrov",
  "10m": "10 metrov",
  "clipGrid": "Izsek mreže v območje GRG",
  "newGRGAreaFromNonStandardTitle": "Nov NRG",
  "newGRGPointBySizeTitle": "GRG iz točke po dimenziji",
  "newGRGPointByRefSystemTitle": "GRG iz točke po koordinatnem sistemu",
  "newGRGPointByTimeTitle": "GRG iz točke s pomočjo časa in hitrosti",
  "time": "Čas",
  "rate": "Hitrost",
  "hours": "Ure",
  "minutes": "Minute",
  "seconds": "Sekunde",
  "ftPerSec": "Čevljev/sekundo",
  "ftPerHour": "Čevljev/uro",
  "kmPerSec": "Kilometrov/sekundo",
  "kmPerHour": "Kilometrov/uro",
  "mPerSec": "Metrov/sekundo",
  "mPerHour": "Metrov/uro",
  "miPerSec": "Milj/sekundo",
  "miPerHour": "Milj/uro",
  "nMPerSec": "Navtičnih milj/sekundo",
  "nMPerHour": "Navtičnih milj/uro",
  "settingsTitle": "Nastavitve",
  "labelSettingsLabel": "Nastavitve napisa",
  "labelSettingsButtonLabel": "Konfiguriraj nastavitve napisa",
  "gridSettingsLabel": "Nastavitve mreže",
  "gridSettingsButtonLabel": "Konfiguriraj nastavitve mreže",
  "transparency": "Prosojnost",
  "labelStyle": "Slog napisa",
  "font": "Pisava",
  "textSize": "Velikost besedila",
  "textColor": "Barva besedila",
  "halo": "Žarenje",
  "show": "Prikaži",
  "lockSettings": "Nastavitve je zaklenil lastnik aplikacije",
  "gridSettings": {
    "cellShape": "Oblika celice",
    "cellUnits": "Enote celice",
    "cellOutline": "Nastavitve obrobe celice",
    "cellFill": "Nastavitve polnila celice",
    "gridReferenceSystem": "Koordinatni sistem",
    "gridDatum": "Geodetski datum: WGS84",
    "labelStartPosition": "Izhodišče napisa",
    "labelType": "Tip napisa",
    "labelDirection": "Smer napisa",
    "gridOrigin": "Izhodišče mreže",
    "default": "Pravokotnik",
    "hexagon": "Šestkotnik",
    "miles": "Milje",
    "kilometers": "Kilometri",
    "feet": "Čevlji",
    "meters": "Metri",
    "yards": "Jardi",
    "nautical-miles": "Navtične milje",
    "lowerLeft": "Spodaj levo",
    "lowerRight": "Spodaj desno",
    "upperLeft": "Zgoraj levo",
    "upperRight": "Zgoraj desno",
    "center": "Na sredino",
    "alphaNumeric": "Alfanumerično",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Številsko",
    "horizontal": "Horizontalno",
    "vertical": "Vertikalno",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Pokaži napise"
  },
  "publishTitle": "Objavi GRG na portalu",
  "publishGRGBtn": "Objavi",
  "GRGLayerName": "Objavljeno ime sloja GRG",
  "invalidGRGLayerName": "Ime sloja mora vsebovati le alfanumerične znake in podčrtaje",
  "missingGRGLayerName": "Vnesti morate ime za GRG",
  "publishingFailedLayerExists": "Objavljanje ni uspelo: imate že geoobjektno storitev z imenom {0}. Izberite drugo ime.",
  "checkService": "Preveri storitev: {0}",
  "createService": "Ustvari storitev: {0}",
  "unableToCreate": "Ni mogoče ustvariti: {0}",
  "addToDefinition": "Dodaj v določitev: {0}",
  "successfullyPublished": "Uspešno je bil objavljen spletni sloj{0}Upravljanje spletnega sloja",
  "userRole": "Storitve ni mogoče ustvariti, ker uporabnik nima dovoljenj",
  "createGRGBtn": "Ustvari GRG",
  "clearGRGBtn": "Počisti",
  "labelFormat": "Format napisa",
  "helpIconTooltip": "Z: Oznaka mrežne cone (GZD)\nS: 100.000-metrska identifikacija kvadrata mreže (GSID)\nX: Pomik proti vzhodu (koordinata X)\nY: Pomik proti severu (koordinata Y)\n\nPrimeri:\nZSXY je 15SWC8081751205\nZS X, Y je 15SWC 80817.51205",
  "addPointToolTip": "Dodaj izhodišče GRG",
  "cellWidth": "Širina celice (x)",
  "cellHeight": "Višina celice (y)",
  "invalidNumberMessage": "Vnesena vrednost ni veljavna",
  "invalidRangeMessage": "Vrednost mora biti večja od 0",
  "gridAngleInvalidRangeMessage": "Vrednost mora biti med -89,9 in 89,9",
  "formatIconTooltip": "Vhodni format",
  "coordInputLabel": "Izhodišče GRG (DD)",
  "setCoordFormat": "Nastavi format niza koordinat",
  "prefixNumbers": "Pozitivnim in negativnim številkam dodaj predpono »+/–«",
  "cancelBtn": "Prekliči",
  "applyBtn": "Uporabi",
  "comfirmInputNotation": "Potrdite zapis vnosa",
  "notationsMatch": "Najden je zapis, ki se ujema z vašim vnosom. Potrdite, katerega želite uporabiti:",
  "numberOfCellsHorizontal": "Število horizontalnih celic",
  "numberOfCellsVertical": "Število navpičnih celic",
  "gridAngle": "Zasuk mreže",
  "tooManyCellsErrorMessage": "Poskušate ustvariti mrežo, ki vsebuje več kot 2000 celic. Priporočamo, da med ustvarjanjem zmanjšate število celic s spreminjanjem velikosti mreže ali območja mreže.",
  "missingParametersMessage": "<p>Obrazec za ustvarjanje GRG vsebuje manjkajoče ali neveljavne parametre. Zagotovite naslednje:</p><ul><li>Območje GRG je izrisano.</li><li>Širina in višina celice vsebujeta veljavne vrednosti.</li></ul>",
  "missingOriginParametersMessage": "<p>Obrazec za ustvarjanje GRG vsebuje manjkajoče ali neveljavne parametre. Zagotovite naslednje:</p><ul><li>Izhodišče GRG je nastavljeno.</li><li>Vnosi časa, hitrosti in kota vsebujejo veljavne vrednosti.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Obrazec za ustvarjanje GRG vsebuje manjkajoče ali neveljavne parametre. Zagotovite, da vnosi širine in višine celice vsebujejo veljavne vrednosti.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Obrazec za ustvarjanje GRG vsebuje manjkajoče ali neveljavne parametre. Zagotovite, da vnosi števila horizontalnih in navpičnih celic vsebujejo veljavne vrednosti.</p>",
  "drawPointToolTip": "Kliknite, da dodate izhodiščno točko GRG",
  "missingLayerNameMessage": "Pred objavo morate vnesti veljavno ime sloja",
  "parseCoordinatesError": "Koordinat ni mogoče razčleniti. Preverite svoj vnos.",
  "grgPolarRegionError": "Obseg GRG je znotraj polarne regije. Celice, ki padejo znotraj polarne regije, ne bodo ustvarjene.",
  "grgPolarOriginError": "Izhodiščna točka GRG ne more biti znotraj polarne regije pri ustvarjanju GRG s pomočjo koordinatnega sistema.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalne stopinje – geografska širina/geografska dolžina",
  "DDLongLatNotation": "Decimalne stopinje – geografska dolžina/geografska širina",
  "DDMLatLongNotation": "Stopinje Decimalne minute – geografska širina/geografska dolžina",
  "DDMLongLatNotation": "Stopinje Decimalne minute – geografska dolžina/geografska širina",
  "DMSLatLongNotation": "Stopinje Minute Sekunde – geografska širina/geografska dolžina",
  "DMSLongLatNotation": "Stopinje Minute Sekunde – geografska dolžina/geografska širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – črka pasu",
  "UTMHemNotation": "UTM – hemisfera (S/J)"
});