define({
  "enableUndoRedo": "실행 취소/다시 실행 사용",
  "toolbarVisible": "도구막대 보이기",
  "toolbarOptions": "도구막대 옵션",
  "mergeVisible": "병합",
  "cutVisible": "잘라내기",
  "reshapeVisible": "재변형",
  "back": "뒤로",
  "label": "레이어",
  "edit": "편집 가능",
  "update": "지오메트리 업데이트 사용 안 함",
  "fields": "필드",
  "actions": "작업",
  "editpageName": "이름",
  "editpageAlias": "별칭",
  "editpageVisible": "표시",
  "editpageEditable": "편집 가능",
  "noLayers": "편집 가능한 피처 레이어를 사용할 수 없음",
  "configureFields": "레이어 필드 구성",
  "useFilterEdit": "피처 템플릿 필터 사용",
  "display": "보기",
  "autoApplyEditWhenGeometryIsMoved": "지오메트리 이동 시 편집 내용 자동 적용",
  "snappingTolerance": "픽셀로 스내핑 톨러런스 설정",
  "popupTolerance": "픽셀로 팝업을 편집하는 속성 톨러런스 설정",
  "stickyMoveTolerance": "픽셀로 스티커형 이동 톨러런스 설정",
  "usingSaveButton": "저장 버튼을 클릭할 때까지 속성에 대한 편집 내용을 적용하지 않음"
});