define({
  "add": "Bấm để thêm mới",
  "title": "Tiêu đề",
  "placeholderBookmarkName": "Tên đánh dấu",
  "ok": "OK",
  "cancel": "Hủy",
  "warning": "Vui lòng kết thúc chỉnh sửa!",
  "edit": "Chỉnh sửa đánh dấu",
  "errorNameExist": "Đánh dấu đã tồn tại!",
  "errorNameNull": "Tên đánh dấu không hợp lệ!",
  "addBookmark": "Tạo mới",
  "thumbnail": "Hình thu nhỏ",
  "thumbnailHint": "Bấm vào hình ảnh để cập nhật",
  "displayBookmarksAs": "Hiển thị đánh dấu thành",
  "cards": "Thẻ",
  "list": "Danh sách",
  "cardsTips": "Chế độ xem dạng thẻ",
  "listTips": "Chế độ xem dạng danh sách",
  "makeAsDefault": "Thiết lập làm mặc định",
  "default": "Mặc định",
  "editable": "Cho phép thêm đánh dấu trong tiện ích.",
  "alwaysSync": "Hiển thị đánh dấu từ bản đồ web",
  "configCustom": "Hiển thị đánh dấu tùy chỉnh",
  "import": "Nhập",
  "create": "Tạo",
  "importTitle": "Nhập đánh dấu",
  "importFromWeb": "Nhập đánh dấu từ bản đồ web hiện tại",
  "selectAll": "Chọn Tất cả",
  "noBookmarkInConfig": "Nhấp vào Nhập hoặc Tạo Mới để thêm đánh dấu.",
  "noBookmarkInWebMap": "Không có đánh dấu nào được cấu hình trong bản đồ.",
  "extent": "Phạm vi",
  "saveExtent": "Lưu phạm vi bản đồ vào đánh dấu này",
  "savelayers": "Lưu khả năng hiển thị lớp",
  "withVisibility": "Với khả năng hiển thị lớp",
  "bookmark": "Đánh dấu",
  "addBtn": "Thêm",
  "deleteBtn": "Xóa",
  "editBtn": "Chỉnh sửa",
  "dragReorderTip": "Giữ và kéo thả để sắp xếp lại",
  "deleteBtnTip": "Xóa đánh dấu",
  "editBtnTip": "Chỉnh sửa đánh dấu"
});