define({
  "layerSelect": "Επιλογή του θεματικού επιπέδου εικόνας",
  "displayMeasureResultInPopup": "Εμφάνιση των αποτελεσμάτων μέτρησης σε αναδυόμενο παράθυρο",
  "angularUnitSelect": "Προκαθορισμένη γωνιακή μονάδα",
  "linearUnitSelect": "Προκαθορισμένη γραμμική μονάδα",
  "areaUnitSelect": "Προκαθορισμένη μονάδα εμβαδού",
  "displayOperationSelect": "Επιλογή λειτουργιών μέτρησης",
  "errorSectionMessage": "Κανένα από τα θεματικά επίπεδα δεν υποστηρίζει δυνατότητες μέτρησης.",
  "unitLabel": {
    "esriInches": "Ίντσες",
    "esriFeet": "Πόδια",
    "esriYards": "Γιάρδες",
    "esriMiles": "Μίλια",
    "esriNauticalMiles": "Ναυτικά μίλια",
    "esriMillimeters": "Χιλιοστά",
    "esriCentimeters": "Εκατοστά",
    "esriDecimeters": "Δεκατόμετρα",
    "esriMeters": "Μέτρα",
    "esriKilometers": "Χιλιόμετρα",
    "esriDURadians": "Ακτίνια",
    "esriDUDecimalDegrees": "Μοίρες",
    "esriSquareInches": "Τετρ. ίντσες",
    "esriSquareFeet": "Τετρ. πόδια",
    "esriSquareYards": "Τετρ. γιάρδες",
    "esriAcres": "Έικρ",
    "esriSquareMiles": "Τετρ. μίλια",
    "esriSquareMillimeters": "Τετρ. χιλιοστά",
    "esriSquareCentimeters": "Τετρ. εκατοστά",
    "esriSquareDecimeters": "Τετρ. δεκατόμετρα",
    "esriSquareMeters": "Τετρ. μέτρα",
    "esriAres": "Άρια",
    "esriHectares": "Εκτάρια",
    "esriSquareKilometers": "Τετρ. χιλιόμετρα"
  },
  "operationLabel": {
    "esriMensurationPoint": "Τοποθεσία",
    "esriMensurationDistanceAndAngle": "Απόσταση και Γωνία",
    "esriMensurationAreaAndPerimeter": "Εμβαδόν και Περίμετρος",
    "esriMensurationHeightFromBaseAndTop": "Ύψος: Από τη βάση στην κορυφή",
    "esriMensurationHeightFromBaseAndTopShadow": "Ύψος: Από τη βάση στην κορυφή-Σκιά",
    "esriMensurationHeightFromTopAndTopShadow": "Ύψος: Από κορυφή σε κορυφή-Σκιά",
    "esriMensurationCentroid": "Κέντρο βάρους",
    "esriMensurationPoint3D": "Τοποθεσία (3D)",
    "esriMensurationDistanceAndAngle3D": "Απόσταση και Γωνία (3D)",
    "esriMensurationAreaAndPerimeter3D": "Εμβαδόν και Περίμετρος (3D)",
    "esriMensurationCentroid3D": "Κέντρο βάρους (3D)"
  }
});