define({
  "_widgetLabel": "ग्रिड किए गए संदर्भ का ग्राफ़िक",
  "newGRGFromAreaButtonLabel": "किसी क्षेत्र के ग्रिड को निर्धारित करें",
  "newGRGFromPointButtonLabel": "किसी पॉइंट से ग्रिड निर्धारित करें",
  "newGRGFromAreaTitle": "किसी क्षेत्र के ग्रिड को निर्धारित करें",
  "newGRGFromPointTitle": "किसी पॉइंट से ग्रिड निर्धारित करें",
  "newGRGBySizeButtonLabel": "आयाम के हिसाब से",
  "newGRGFromRefSystemButtonLabel": "संदर्भ संबंधी सिस्टम के हिसाब से",
  "newGRGByTimeLabel": "समय और गति के हिसाब से",
  "newGRGFromNonStandardButtonLabel": "गैर-मानक ग्रिड निर्धारित करें",
  "newGRGAreaBySizeTitle": "आयाम के हिसाब से क्षेत्र का GRG",
  "newGRGAreaBySizeDefineAreaLabel": "GRG क्षेत्र",
  "addGRGAreaPolygonToolTip": "बहुभुज का उपयोग करते हुए GRG क्षेत्र आरेखित करें",
  "addGRGAreaExtentToolTip": "सीमा का उपयोग करते हुए GRG क्षेत्र आरेखित करें",
  "rotation": "ग्रिड घूर्णन",
  "numberRowsColumnsLabel": "पंक्तियों और स्तंभों की संख्या निर्धारित करें",
  "newGRGAreaByRefSystemTitle": "संदर्भ संबंधी सिस्टम द्वारा किसी क्षेत्र के हिसाब से GRG",
  "gridSize": "ग्रिड का आकार",
  "UTMZoneandBand": "ग्रिड क्षेत्र",
  "100000m": "100000 मीटर",
  "10000m": "10000 मीटर",
  "1000m": "1000 मीटर",
  "100m": "100 मीटर",
  "10m": "10 मीटर",
  "clipGrid": "ग्रिड को GRG क्षेत्र से क्लिप करें",
  "newGRGAreaFromNonStandardTitle": "नया NRG",
  "newGRGPointBySizeTitle": "आयाम के हिसाब से पॉइंट से GRG",
  "newGRGPointByRefSystemTitle": "संदर्भ संबंधी सिस्टम के हिसाब से पॉइंट से GRG",
  "newGRGPointByTimeTitle": "समय और गति का उपयोग करते हुए पॉइंट से GRG",
  "time": "समय",
  "rate": "गति",
  "hours": "घंटे",
  "minutes": "मिनट",
  "seconds": "सेकंड",
  "ftPerSec": "फीट / सेकंड",
  "ftPerHour": "फीट / घंटा",
  "kmPerSec": "किलोमीटर / सेकंड",
  "kmPerHour": "किलोमीटर / घंटा",
  "mPerSec": "मीटर / सेकंड",
  "mPerHour": "मीटर / घंटा",
  "miPerSec": "मील / सेकंड",
  "miPerHour": "मील / घंटा",
  "nMPerSec": "नॉटिकल मील / सेकंड",
  "nMPerHour": "नॉटिकल मील / घंटा",
  "settingsTitle": "सेटिंग्स",
  "labelSettingsLabel": "लेबल की सेटिंग",
  "labelSettingsButtonLabel": "लेबल सेटिंग कॉन्फ़िगर करें",
  "gridSettingsLabel": "ग्रिड की सेटिंग",
  "gridSettingsButtonLabel": "ग्रिड की सेटिंग कॉन्फ़िगर करें",
  "transparency": "पारदर्शिता",
  "labelStyle": "लेबल का स्टाइल",
  "font": "फॉन्ट",
  "textSize": "टेक्स्ट आकार",
  "textColor": "टेक्स्ट रंग",
  "halo": "हैलो (प्रभामंडल)",
  "show": "दिखाएं",
  "lockSettings": "सेटिंग को ऐप्लिकेशन के स्वामी द्वारा लॉक कर दिया गया है",
  "gridSettings": {
    "cellShape": "कोष्ठक की आकृति",
    "cellUnits": "कोष्ठक इकाइयाँ",
    "cellOutline": "कोष्ठक की बाहरी परिधि की सेटिंग",
    "cellFill": "कोष्ठक में भरे जाने वाले रंग की सेटिंग",
    "gridReferenceSystem": "संदर्भ प्रणाली",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "लेबल की उत्पत्ति",
    "labelType": "लेबल का प्रकार",
    "labelDirection": "लेबल की दिशा",
    "gridOrigin": "ग्रिड की उत्पत्ति",
    "default": "आयत",
    "hexagon": "षट्कोण",
    "miles": "मील",
    "kilometers": "किलोमीटर",
    "feet": "फुट",
    "meters": "मीटर",
    "yards": "गज",
    "nautical-miles": "समुद्री मील",
    "lowerLeft": "नीचे बाईं ओर",
    "lowerRight": "नीचे दाईं ओर",
    "upperLeft": "ऊपर बाईं ओर",
    "upperRight": "ऊपर दाईं ओर",
    "center": "केंद्र",
    "alphaNumeric": "अक्षरांकीय",
    "alphaAlpha": "केवल अक्षर",
    "numeric": "संख्यात्मक",
    "horizontal": "क्षैतिज",
    "vertical": "लंबवत",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "लेबल दिखाएँ"
  },
  "publishTitle": "पोर्टल पर GRG प्रकाशित करें",
  "publishGRGBtn": "प्रकाशित करें",
  "GRGLayerName": "प्रकाशित GRG लेयर का नाम",
  "invalidGRGLayerName": "लेयर के नाम में केवल अक्षरांकीय वर्ण और अंडरस्कोर होना चाहिए",
  "missingGRGLayerName": "GRG के लिए आपको नाम दर्ज करना होगा",
  "publishingFailedLayerExists": "प्रकाशन विफल: आपके पास पहले से ही (0) नाम की एक फ़ीचर सेवा है। कृपया दूसरा नाम चुनें।",
  "checkService": "सेवा की जाँच करें: {0}",
  "createService": "सेवा बनाएँ: {0}",
  "unableToCreate": "बनाने में अक्षम: {0}",
  "addToDefinition": "परिभाषा में जोड़ें: {0}",
  "successfullyPublished": "सफलतापूर्वक प्रकाशित वेब लेयर{0}वेब लेयर प्रबंधित करें",
  "userRole": "सेवा तैयार करने में अक्षम हैं, क्योंकि उपयोगकर्ता को अनुमति नहीं है",
  "createGRGBtn": "GRG बनाएं",
  "clearGRGBtn": "हटाएँ",
  "labelFormat": "लेबल का फ़ॉर्मेट",
  "helpIconTooltip": "Z: ग्रिड ज़ोन डेजिग्नेटर (GZD)\nS: 100,000 मीटर ग्रिड स्क्वैयर आईडेंटिफिकेशन (GSID)\nX: पूर्व दिशा निर्धारण (X गुणांक)\nY: उत्तर दिशा निर्धारण (Y गुणांक)\n\nउदाहरण:\nZSXY है 15SWC8081751205\nZS X,Y है 15SWC 80817,51205",
  "addPointToolTip": "GRG उत्पत्ति जोड़ें",
  "cellWidth": "कोष्ठक की चौड़ाई (x)",
  "cellHeight": "कोष्ठक की ऊँचाई (y)",
  "invalidNumberMessage": "दर्ज की गई संख्या मान्य नहीं है",
  "invalidRangeMessage": "मान 0 से अधिक होना आवश्यक है",
  "gridAngleInvalidRangeMessage": "मान -89.9 और 89.9 के बीच होना चाहिए",
  "formatIconTooltip": "फ़ॉर्मेट आउटपुट",
  "coordInputLabel": "GRG उत्पत्ति (DD)",
  "setCoordFormat": "निर्देशांक फ़ॉर्मेट स्ट्रिंग को सेट करें",
  "prefixNumbers": "धनात्मक और ऋणात्मक संख्याओं के आगे '+/-' जोड़ें",
  "cancelBtn": "रद्द करें",
  "applyBtn": "लागू करें",
  "comfirmInputNotation": "इनपुट नोटेशन की पुष्टि करें",
  "notationsMatch": "ये नोटेशन आपके इनपुट से मेल खाते हैं, कृपया जिसका आप इस्तेमाल करना चाहते हैं, उसकी पुष्टि करें:",
  "numberOfCellsHorizontal": "# क्षैतिज कोष्ठक",
  "numberOfCellsVertical": "# लंबवत कोष्ठक",
  "gridAngle": "ग्रिड घूर्णन",
  "tooManyCellsErrorMessage": "आप 2000 कोष्ठक से अधिक का ग्रिड बना रहे हैं। सलाह दी जाती है कि ग्रिड का आकार या ग्रिड का क्षेत्र बदलकर बनाए जाने वाले कोष्ठकों की संख्या कम करें।",
  "missingParametersMessage": "<p>GRG निर्माण प्रपत्र अनुपलब्ध है या इसके पैरामीटर अमान्य हैं, कृपया सुनिश्चित करें:</p><ul><li>GRG क्षेत्र का आरेख तैयार कर लिया गया है।</li><li>कोष्ठक की चौड़ाई और लंबाई में वैध मान होते हैं।</li></ul>",
  "missingOriginParametersMessage": "<p>GRG निर्माण प्रपत्र अनुपलब्ध है या इसके पैरामीटर अमान्य हैं, कृपया सुनिश्चित करें:</p><ul><li>GRG उत्पत्ति सेट की गई।</li><li>समय, गति और कोण संबंधी इनपुट में वैध मान होते हैं।</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG निर्माण प्रपत्र अनुपलब्ध है या इसके पैरामीटर अमान्य हैं। कृपया सुनिश्चित करें कि कोष्ठक की चौड़ाई और ऊँचाई संबंधी इनपुट में वैध मान हैं।</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG निर्माण प्रपत्र अनुपलब्ध है या इसके पैरामीटर अमान्य हैं। कृपया सुनिश्चित करें कि कोष्ठकों की संख्या के क्षैतिज औऱ लंबवत डेटा संबंधी इनपुट में वैध मान हैं।</p>",
  "drawPointToolTip": "GRG उत्पत्ति बिंदु जोड़ने के लिए क्लिक करें",
  "missingLayerNameMessage": "प्रकाशित करने से पहले आपको वैध लेयर का नाम दर्ज करना होगा",
  "parseCoordinatesError": "निर्देशांकों की व्याख्या करने में सक्षम नहीं। कृपया अपना इनपुट जांचें।",
  "grgPolarRegionError": "GRG की सीमा ध्रुवीय क्षेत्र के भीतर पड़ती है। ध्रुवीय क्षेत्र में पड़ने वाले कोष्ठक नहीं बनाए जाएँगे।",
  "grgPolarOriginError": "संदर्भ संबंधी सिस्टम द्वारा GRG बनाते समय GRG उत्पत्ति बिंदु ध्रुवीय क्षेत्र में नहीं हो सकता।",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "दशमलव डिग्री - अक्षांश/देशांतर",
  "DDLongLatNotation": "दशमलव डिग्री - देशांतर/अक्षांश",
  "DDMLatLongNotation": "दशमलव डिग्री मिनट - अक्षांश/देशांतर",
  "DDMLongLatNotation": "दशमलव डिग्री मिनट - देशांतर/अक्षांश",
  "DMSLatLongNotation": "दशमलव डिग्री सेकंड - देशांतर/अक्षांश",
  "DMSLongLatNotation": "दशमलव डिग्री सेकंड - अक्षांश/देशांतर",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - बैंड लेटर",
  "UTMHemNotation": "UTM - गोलार्ध (N/S)"
});