define({
  "enableUndoRedo": "Ενεργοποίηση Αναίρεσης/Επανάληψης",
  "toolbarVisible": "Ορατή γραμμή εργαλείων",
  "toolbarOptions": "Επιλογές γραμμής εργαλείων",
  "mergeVisible": "Συγχώνευση",
  "cutVisible": "Αποκοπή",
  "reshapeVisible": "Ανασχεδίαση",
  "back": "Επιστροφή",
  "label": "Θεματικό Επίπεδο",
  "edit": "Με δυνατότητα επεξεργασίας",
  "update": "Απενεργοποίηση ενημέρωσης γεωμετρίας",
  "fields": "Πεδία",
  "actions": "Ενέργειες",
  "editpageName": "Όνομα",
  "editpageAlias": "Ψευδώνυμο",
  "editpageVisible": "Ορατό",
  "editpageEditable": "Επεξεργάσιμο",
  "noLayers": "Δεν υπάρχουν διαθέσιμα feature layers με δυνατότητα επεξεργασίας",
  "configureFields": "Διαμόρφωση πεδίων θεματικού επιπέδου",
  "useFilterEdit": "Χρήση φίλτρου προτύπου στοιχείων",
  "display": "Οθόνη",
  "autoApplyEditWhenGeometryIsMoved": "Αυτόματη εφαρμογή της αλλαγής κατά τη μετακίνηση του γεωμετρικού τύπου",
  "snappingTolerance": "Ορισμός της ανοχής αγκίστρωσης σε pixel",
  "popupTolerance": "Ορισμός της ανοχής του αναδυόμενου παραθύρου επεξεργασίας περιγραφικών γνωρισμάτων σε pixel",
  "stickyMoveTolerance": "Ορισμός της ανοχής του sticky move σε pixel",
  "usingSaveButton": "Να μην εφαρμόζονται αλλαγές στα γνωρίσματα αν δεν γίνει κλικ στο κουμπί «Αποθήκευση»."
});