define({
  "settings": "Setări",
  "titleSettings": "Setările de text",
  "imageSettings": "Setări imagine",
  "backgroundColor": "Culoare de fundal",
  "alignment": "Aliniere",
  "textSize": "Dimensiune text",
  "textColor": "Culoare text",
  "dataSource": "Sursă de date",
  "chartSettings": "Setări diagramă",
  "data": "Date",
  "dataLabels": "Etichete date",
  "displayMode": "Mod afişaj",
  "featureOption": "Afişare valori pentru fiecare obiecte spaţial",
  "categoryOption": "Afişare valori pe categorii",
  "countOption": "Afişare număr de obiecte spaţiale pe categorii",
  "fieldOption": "Afişare valori de atribute sub formă de diagramă",
  "categoryField": "Câmp pentru categorie",
  "labelField": "Câmp etichetă",
  "valueFields": "Câmp valoare",
  "operation": "Operaţie",
  "sumOption": "Sumă",
  "averageOption": "Medie",
  "minOption": "Minim",
  "maxOption": "Maxim",
  "dataFormat": "Format date",
  "decimalPlaces": "Zecimale",
  "prefix": "Prefix",
  "suffix": "Sufix",
  "dataType": "Tip de date",
  "featureCount": "Număr obiecte spaţiale",
  "fieldStatistics": "Statistici câmp",
  "display": "Afişare",
  "chartColor": "Culoare diagramă",
  "horizontalAxis": "Axă orizontală",
  "verticalAxis": "Axă verticală",
  "legend": "Legendă",
  "position": "Poziţie",
  "top": "Sus",
  "bottom": "Jos",
  "useDataSourceSelection": "Utilizare selecţie",
  "dataSourceFilterByExtent": "Filtrare după extindere",
  "changeTemplate": "Modificare şablon",
  "numberSettings": "Setări număr",
  "gaugeSettings": "Setări instrument de măsură",
  "indicators": "Indicatoare",
  "ifValue": "Dacă valoarea",
  "and": "şi",
  "numberOperatorIsLessThan": "este mai mică decât",
  "numberOperatorIsGreaterThan": "este mai mare de",
  "numberOperatorIsBetween": "este între",
  "numberOperatorIsEqual": "este egal cu",
  "numberOperatorIsNotEqual": "este diferit de",
  "then": "Atunci",
  "ratio": "Raport",
  "trueValue": "Valoare adevărată",
  "changeValueColor": "modificare culoare valoare la",
  "changeGaugeColor": "modificare culoare instrument de măsură la",
  "setIndicatorIcon": "setare pictogramă indicator ca",
  "icons": "Pictograme",
  "style": "Stil",
  "placement": "Amplasare",
  "left": "Stânga",
  "replace": "Înlocuire",
  "right": "Dreapta",
  "color": "Culoare",
  "categoryExists": "Categoria există!",
  "comboxHint": "Scrieți sau selectați una",
  "comboxDisableInputHint": "Selectaţi un eveniment",
  "sortBy": "Sortare după",
  "labelAxis": "Etichetă",
  "valueAxis": "Valoare",
  "minPeriod": "Perioadă minimă",
  "automatic": "Automat",
  "periodsWithOutRecords": "Perioade fără înregistrări",
  "nullValue": "Valoare nulă",
  "calculatedAsZero": "Calculat drept zero",
  "ignored": "Ignorat",
  "maxCategories": "Categorii maxime",
  "useLayerSymbology": "Utilizare simbolistică strat tematic â€™",
  "hollowsize": "Dimensiune superficială",
  "splitField": "Scindare câmp",
  "parsingperiodTip": "Calculul a eşuat. Prea multe intervale de timp din cauza perioadei scurte de analiză.",
  "manyCategoryTip": "Eroare la afişarea diagramei. Prea multe categorii.",
  "setColor": "Setare culoare",
  "setTheColorOf": "Atunci stabiliți culoarea",
  "setTheColorAs": "Atunci stabiliți culoarea ca fiind",
  "ifStr": "Dacă opțiunea",
  "as": "ca",
  "is": "este",
  "isNot": "nu este",
  "barCluster": "bară cluster",
  "individualBar": "bară individuală",
  "allOthers": "Toate celelalte",
  "category": "Categorie",
  "indicatorSum": "SUMĂ",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN.",
  "setCorrectyIndicatorTip": "Vă rugăm să setaţi corect indicatoarele.",
  "dataRange": "Interval date",
  "targetValue": "Valoare ţintă",
  "currentValue": "Valoare curentă",
  "gaugeColor": "Culoare instrument de măsură",
  "min": "Minim",
  "max": "Maxim",
  "displayValueIn": "Afişare valoare în",
  "noData": "Nu există date",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Avertisment",
  "noSettingWaring1": "Faceţi clic pe un element pentru a-i seta proprietăţile.",
  "noSettingWaring2": "Trageţi pentru a redimensiona sau reordona un element.",
  "donNotShowAgain": "Nu se mai afişează",
  "changeTemplateWarning": "Aceasta vă va şterge toate setările şi va deschide un şablon nou, gol.",
  "requiredFieldWarning": "Această valoare este obligatorie:",
  "dataSourceNotSet": "Setaţi sursa datelor.",
  "addIndicatorTip": "Adăugaţi un indicator",
  "chooseTemplatePopupTitle": "Alegeţi un şablon",
  "filterExtentTipWithaTag": "Puteți dezactiva filtrul de la <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Sursă de date suplimentare</a> de la fila de Atribute.",
  "filterExtentTip": "Puteți dezactiva filtrul de la Sursa de date suplimentare de la fila de Atribute.",
  "customColorByCategory": "Pe categorie de culoare particularizată",
  "randomColor": "Culoare aleatorie",
  "valueString": "Valoare",
  "fieldString": "Câmp",
  "includeThresholdValue": "Includere valoare prag",
  "percentage": "Procentaj",
  "colorSchema": "Schemă de culori",
  "addCategory": "Adaugă categorie",
  "clickToEdit": "Faceţi clic pentru a edita",
  "nullText": "Nul",
  "others": "Altele",
  "stringsInTemplate": {
    "name_number": "Număr",
    "name_gauge": "Instrument de măsură",
    "name_vertical_gauge": "Instrument de măsurare vertical",
    "name_horizontal_gauge": "Instrument de măsurare orizontal",
    "name_pie": "Proporţii",
    "name_donut": "Tor",
    "name_bar": "Bară",
    "name_stacked_bar": "Bară în stivă",
    "name_percentage_stacked_bar": "Bară procent în stivă",
    "name_column": "Coloană",
    "name_stacked_column": "Coloană în stivă",
    "name_percentage_stacked_column": "Coloană procent în stivă",
    "name_line": "Linie",
    "name_area": "Suprafaţă",
    "name_stacked_area": "Zonă în stivă",
    "name_percentage_stacked_area": "Zonă procent în stivă",
    "titleOfTheInfographic": "TITLUL GRAFICULUI INFORMATIV",
    "description": "Descriere: informaţii suplimentare despre acest infografic."
  }
});