define({
  "_widgetLabel": "Hädaolukorras reageerimise juhend",
  "ergMainPageTitle": "Põhineb juhendil „Emergency Response Guidebook 2016“",
  "coordInputLabelStart": "Saastumiskoht (DD)",
  "coordInputLabel": "Saastumiskoht",
  "addPointToolTip": "Lisa saastumiskoht",
  "drawPointToolTip": "Klõpsake saastumiskoha lisamiseks",
  "material": "Aine",
  "materialPlaceholder": "Aine otsimiseks alustage tippimist",
  "table3Message": "Kui tegemist on ulatusliku saastumisega, tuleb teie valitud aine korral sisestada lisateavet.\n\nVeenduge, et oleksite tuulekiiruse ja transpordikonteineri jaoks valinud õiged väärtused.",
  "table2Message": "Teie valitud aine võib vette sattumise korral tekitada suures koguses toksilisi gaase, mille sissehingamine on ohtlik.\n\nVõiksite kaaluda järgmiste ainete kasutamist:\n\n",
  "spillSize": "Saastumise ulatus",
  "small": "Väike",
  "large": "Suur",
  "fireLabel": "Kuva tuleisolatsiooni tsoon",
  "weatherLabel": "Praegune ilm saastumiskohas",
  "weatherIntialText": "<br />Uuendatakse pärast saastumiskoha tuvastamist",
  "temperature": "Temperatuur",
  "wind": "Tuul",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Ilmateavet ei saa tuua. Uuendage tuulekiiruse ja saastumisaja väärtused käsitsi.",
  "windDirection": "Tuule suund (sihtsuund)",
  "timeOfSpill": "Saastumisaeg",
  "day": "Päev",
  "night": "Öö",
  "windSpeed": "Tuule kiirus",
  "low": "Madal",
  "moderate": "Mõõdukas",
  "high": "Kõrge",
  "transportContainer": "Transpordikonteiner",
  "rail": "Tsisternvagun",
  "semi": "Tsisternveok või järelhaagis",
  "mton": "Mitu ühetonnise mahutavusega ballooni",
  "ston": "Mitu väikest ballooni või üks ühetonnise mahutavusega balloon",
  "ag": "Põllumajanduslik lägatsistern",
  "msm": "Mitu väikest ballooni",
  "bleveLabel": "Kuva BLEVE isolatsioonitsoon",
  "capacity": "Konteineri mahutavus (liitrites)",
  "bleveMessage": "Teie valitud aine korral saab BLEVE jaoks näidata täiendavat evakueerimiskaugust.\n\nSelle sätte lubamiseks lülitage säte „Kuva BLEVE isolatsioonitsoon“ sisse ja valige asjakohane konteineri mahutavus.",
  "noPAZoneMessage": "Selle aine korral ei saa kaitsetoimingute kaugust määrata. Arvutatud on ainult algse isolatsiooni ja evakuatsiooni tsoonid.",
  "settingsTitle": "Seaded",
  "spillLocationLabel": "Saastumiskoht",
  "spillLocationButtonLabel": "Konfigureeri saastumiskoha sätted",
  "IISettingsLabel": "Algne isolatsioonitsoon",
  "IIButtonLabel": "Konfigureeri algse isoleerimise sätted",
  "PASettingsLabel": "Kaitsetoimingute tsoon",
  "PAButtonLabel": "Konfigureeri kaitsetoimingute sätted",
  "downwindSettingsLabel": "Allatuuletsoon",
  "downwindButtonLabel": "Konfigureeri allatuulesätted",
  "fireSettingsLabel": "Tuleisolatsiooni tsoon",
  "fireButtonLabel": "Konfigureeri tuleisolatsiooni sätted",
  "bleveSettingsLabel": "BLEVE isolatsiooni tsoon",
  "bleveButtonLabel": "Konfigureeri BLEVE sätted",
  "style": "Laad",
  "lineStyles": {
    "esriSLSDash": "Katkendlik",
    "esriSLSDashDot": "Katkendlik punktiga",
    "esriSLSDashDotDot": "Katkendlik kahe punktiga",
    "esriSLSDot": "Punktiir",
    "esriSLSLongDash": "Pikk katkendlik kriips",
    "esriSLSLongDashDot": "Pikk katkendlik kriips punktiga",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lühike katkendlik kriips",
    "esriSLSShortDashDot": "Lühike katkendlik kriips punktiga",
    "esriSLSShortDashDotDot": "Lühike katkendlik kriips kahe punktiga",
    "esriSLSShortDot": "Lühike punktiir",
    "esriSLSSolid": "Pidev"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Tagasi",
    "esriSFSCross": "Rist",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Edasi",
    "esriSFSHorizontal": "Horisontaalne",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Pidev",
    "esriSFSVertical": "Vertikaalne"
  },
  "resultsTitle": "Tulemused",
  "publishERGBtn": "Publitseeri",
  "ERGLayerName": "Avaldatud ERG kihi nimi",
  "invalidERGLayerName": "Kihi nimi tohib sisaldada ainult tähe- ja numbrimärke ning allkriipse",
  "missingERGLayerName": "Peate sisestama ERG nime",
  "publishingFailedLayerExists": "Avaldamine nurjus: objektiteenus nimega {0} on juba olemas. Valige mõni muu nimi.",
  "checkService": "Kontrolli teenust: {0}",
  "createService": "Loo teenus: {0}",
  "unableToCreate": "Ei saa luua: {0}",
  "addToDefinition": "Lisa definitsiooni: {0}",
  "successfullyPublished": "Veebikiht on avaldatud{0}Halda veebikihti",
  "userRole": "Teenust ei saa luua, kuna kasutajal pole nõutavaid õigusi",
  "transparency": "Läbipaistvus",
  "outline": "Äärejoon",
  "fill": "Täida (värv rakendatakse ainult juhul, kui valitud on pidev laad)",
  "createERGBtn": "Loo tsoonid",
  "clearERGBtn": "Tühjenda",
  "labelFormat": "Sildi vorming",
  "helpIconTooltip": "Väikese ja suure saastumise vaheline lävi on järgmine:\nVedelikud – 208 liitrit (55 gallonit)\nTahkained – 300 kilogrammi (600 naela)",
  "cellWidth": "Ruudu laius (x)",
  "cellHeight": "Ruudu kõrgus (y)",
  "invalidNumberMessage": "Sisestatud väärtus ei sobi",
  "invalidRangeMessage": "Väärtus peab olema suurem kui 0",
  "gridAngleInvalidRangeMessage": "Väärtus peab olema vahemikus -89,9 kuni 89,9",
  "formatIconTooltip": "Vormingu sisestus",
  "setCoordFormat": "Määra koordinaatide vormingu string",
  "prefixNumbers": "Lisa positiivsetele ja negatiivsetele arvudele eesliide „+/-”",
  "cancelBtn": "Loobu",
  "applyBtn": "Rakenda",
  "comfirmInputNotation": "Kinnita sisestatud tähistus",
  "notationsMatch": "tähistust vastab teie sisestusele; palun kinnitage, millist soovite kasutada:",
  "missingLayerNameMessage": "Avaldamiseks peate esmalt sisestama sobiva kihinime",
  "parseCoordinatesError": "Ei saa koordinaate sõeluda. Kontrollige sisendit.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Kümnendkraadid – laiuskraad/pikkuskraad",
  "DDLongLatNotation": "Kümnendkraadid  – pikkuskraad/laiuskraad",
  "DDMLatLongNotation": "Kraadid-kümnendminutid – laiuskraad/pikkuskraad",
  "DDMLongLatNotation": "Kraadid-kümnendminutid – pikkuskraad/laiuskraad",
  "DMSLatLongNotation": "Kraadid-kümnendsekundid – laiuskraad/pikkuskraad",
  "DMSLongLatNotation": "Kraadid-kümnendsekundid – pikkuskraad/laiuskraad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – vahemiku täht",
  "UTMHemNotation": "UTM – poolkera (N/S)"
});