define({
  "_widgetLabel": "Noodhulpgids",
  "ergMainPageTitle": "Gebaseerd op het Emergency Response Guidebook 2016",
  "coordInputLabelStart": "Leklocatie (DD)",
  "coordInputLabel": "Leklocatie",
  "addPointToolTip": "Leklocatie toevoegen",
  "drawPointToolTip": "Klik om een leklocatie toe te voegen",
  "material": "Materiaal",
  "materialPlaceholder": "Begin te typen om een materiaal te zoeken",
  "table3Message": "Het materiaal dat u selecteerde vereist aanvullende informatie als u te maken hebt met een groot lek.\n\nZorg ervoor dat u de juiste waarden invoert voor windsnelheid en transportcontainer.",
  "table2Message": "Het materiaal dat u selecteerde produceert een grote hoeveelheid Giftige gassen als het in water terechtkomt.\n\nOverweeg daarom het/de volgende materia(a)l(en):\n\n",
  "spillSize": "Omvang van het lek",
  "small": "Klein",
  "large": "Groot",
  "fireLabel": "Brandisolatiezone tonen",
  "weatherLabel": "Actueel weer op de leklocatie",
  "weatherIntialText": "<br />Wordt geactualiseerd zodra er een leklocatie geïdentificeerd is",
  "temperature": "Temperatuur",
  "wind": "Wind",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Weerinformatie niet verkregen. Voer windsnelheid en tijdstip van lek handmatig in",
  "windDirection": "Windrichting (wind blaast naar)",
  "timeOfSpill": "Tijdstip van lek",
  "day": "Dag",
  "night": "Nacht",
  "windSpeed": "Windsnelheid",
  "low": "Laag",
  "moderate": "Gemiddeld",
  "high": "Hoog",
  "transportContainer": "Transportcontainer",
  "rail": "Treintankwagen",
  "semi": "Tankwagen of -trailer op snelweg",
  "mton": "Meerdere cilinders van één ton",
  "ston": "Meerdere kleine cilinders of een enkele cilinder van één ton",
  "ag": "Landbouwtankwagen",
  "msm": "Meerdere kleine cilinders",
  "bleveLabel": "BLEVE isolatiezone tonen",
  "capacity": "Containercapaciteit (liter)",
  "bleveMessage": "Voor het materiaal dat u selecteerde, wordt er voor BLEVE mogelijk een evacuatie-afstand weergegeven.\n\nOm dit te activeren, schakel de knop BLEVE isolatiezone tonen in en selecteer de gepaste containercapaciteit.",
  "noPAZoneMessage": "Er zijn geen proactieve beschermingsafstanden voor dit materiaal. Alleen de initiële isolatie- en evacuatie-afstanden werden berekend",
  "settingsTitle": "Instellingen",
  "spillLocationLabel": "Leklocatie",
  "spillLocationButtonLabel": "Leklocatie-instellingen configureren",
  "IISettingsLabel": "Initiële isolatiezone",
  "IIButtonLabel": "Initiële isolatiezone-instellingen configureren",
  "PASettingsLabel": "Beschermende actiezone",
  "PAButtonLabel": "Beschermende actie-instellingen configureren",
  "downwindSettingsLabel": "Benedenwindse zone",
  "downwindButtonLabel": "Benedenwindse zone-instellingen configureren",
  "fireSettingsLabel": "Brandisolatiezone",
  "fireButtonLabel": "Brandisolatie-instellingen configureren",
  "bleveSettingsLabel": "BLEVE isolatiezone",
  "bleveButtonLabel": "BLEVE isolatie-instellingen configureren",
  "style": "Stijl",
  "lineStyles": {
    "esriSLSDash": "Streep",
    "esriSLSDashDot": "Streep punt",
    "esriSLSDashDotDot": "Streep punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Lange streep",
    "esriSLSLongDashDot": "Lange streep punt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Korte streep",
    "esriSLSShortDashDot": "Korte streep punt",
    "esriSLSShortDashDotDot": "Korte streep punt punt",
    "esriSLSShortDot": "Korte punt",
    "esriSLSSolid": "Ononderbroken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Achterwaarts",
    "esriSFSCross": "Kruis",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Voorwaarts",
    "esriSFSHorizontal": "Horizontaal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Ononderbroken",
    "esriSFSVertical": "Verticaal"
  },
  "resultsTitle": "Resultaten",
  "publishERGBtn": "Publiceren",
  "ERGLayerName": "Gepubliceerde ERG-laagnaam",
  "invalidERGLayerName": "Laagnaam mag alleen alfanumerieke tekens en onderstrepingstekens bevatten",
  "missingERGLayerName": "U moet een naam invoeren voor de ERG",
  "publishingFailedLayerExists": "Publiceren mislukt: U hebt al een featureservice met de naam {0}. Kies een andere naam.",
  "checkService": "Controleer service: {0}",
  "createService": "Maak service: {0}",
  "unableToCreate": "Niet mogelijk om te maken: {0}",
  "addToDefinition": "Voeg toe aan definitie: {0}",
  "successfullyPublished": "Succesvolle publicatie weblaag{0}Beheer de weblaag",
  "userRole": "Kan service niet maken omdat de gebruiker niet gemachtigd is",
  "transparency": "Transparant",
  "outline": "Omtreklijn",
  "fill": "Vullen (kleur wordt alleen toegepast als stijl ingesteld is al solid)",
  "createERGBtn": "Zones maken",
  "clearERGBtn": "Annuleren",
  "labelFormat": "Labelopmaak",
  "helpIconTooltip": "De drempelwaarde tussen kleine en grote lekomvang zijn:\nVloeistoffen - 55 gallons (208 liter)\nVaste stoffen - 60 pond (300 kilogram)",
  "cellWidth": "Celbreedte (x)",
  "cellHeight": "Celhoogte (y)",
  "invalidNumberMessage": "De ingevoerde waarde is niet geldig",
  "invalidRangeMessage": "Waarde moet groter zijn dan 0",
  "gridAngleInvalidRangeMessage": "De waarde moet tussen -89,9 en 89,9 liggen",
  "formatIconTooltip": "Indeling invoer",
  "setCoordFormat": "Coördinaatindelingtekst",
  "prefixNumbers": "Voeg \"+/-\" prefix toe aan positieve en negatieve cijfers",
  "cancelBtn": "Afbreken",
  "applyBtn": "Toepassen",
  "comfirmInputNotation": "Bevestig inputnotatie",
  "notationsMatch": "notaties gevonden die overeenstemmen met uw input. Bevestig welke u wenst te gebruiken:",
  "missingLayerNameMessage": "U moet een geldige laagnaam invoeren voordat u kunt publiceren",
  "parseCoordinatesError": "Kan coördinaten niet parsen. Controleer uw input.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimale graden - Breedtegraad/Lengtegraad",
  "DDLongLatNotation": "Decimale graden - Lengtegraad/Breedtegraad",
  "DDMLatLongNotation": "Graden decimale minuten - Breedtegraad/Lengtegraad",
  "DDMLongLatNotation": "Graden decimale minuten - Lengtegraad/Breedtegraad",
  "DMSLatLongNotation": "Graden decimale seconden - Breedtegraad/Lengtegraad",
  "DMSLongLatNotation": "Graden decimale seconden - Lengtegraad/Breedtegraad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisfeer (N/S)"
});