define({
  "enableUndoRedo": "Aktifkan Urungkan/Ulangi",
  "toolbarVisible": "Bilah alat terlihat",
  "toolbarOptions": "Opsi bilah alat",
  "mergeVisible": "Gabungkan",
  "cutVisible": "Potong",
  "reshapeVisible": "Ubah bentuk",
  "back": "Kembali",
  "label": "Layer",
  "edit": "Dapat Diedit",
  "update": "Nonaktifkan Pembaruan Geometri",
  "fields": "Kolom",
  "actions": "Tindakan",
  "editpageName": "Nama",
  "editpageAlias": "Alias",
  "editpageVisible": "Terlihat",
  "editpageEditable": "Dapat Diedit",
  "noLayers": "Tidak tersedia layer fitur yang dapat diedit",
  "configureFields": "Konfigurasikan kolom layer",
  "useFilterEdit": "Gunakan filter template fitur",
  "display": "Tampilkan",
  "autoApplyEditWhenGeometryIsMoved": "Terapkan edit otomatis ketika geometri dipindahkan",
  "snappingTolerance": "Tetapkan toleransi pelekat dalam piksel",
  "popupTolerance": "Tetapkan toleransi popup pengeditan atribut dalam piksel",
  "stickyMoveTolerance": "Tetapkan toleransi gerakan pelekat dalam piksel",
  "usingSaveButton": "Jangan aplikasikan editan ke atribut sebelum mengklik tombol Simpan"
});