define({
  "labelBookmarkName": "Přidat aktuální zobrazení do záložek",
  "labelPlay": "Přehrát vše",
  "labelStop": "Zastavit",
  "labelDelete": "Smazat",
  "placeholderBookmarkName": "Název záložky",
  "errorNameExist": "Záložka již existuje!",
  "errorNameNull": "Neplatný název záložky!",
  "editTip": "Upravit záložky",
  "exitEditTip": "Opustit režim úprav",
  "syncTip": "Synchronizovat",
  "cardsTips": "Zobrazení mřížky",
  "listTips": "Zobrazení seznamu",
  "addBtn": "Přidat",
  "deleteBtn": "Smazat",
  "changeThumbnailTip": "Změnit miniaturu",
  "dragReorderTip": "Přidržením a tažením změníte pořadí",
  "deleteBtnTip": "Smazat záložku",
  "editBtnTip": "Upravit záložku",
  "withVisibility": "S viditelností vrstev",
  "searchBookmark": "Hledat",
  "bookmarksFromConfig": "Přednastavené záložky",
  "bookmarksFromCache": "Lokální dočasné záložky",
  "notice": "Poznámka",
  "changeNoticeTips": "Změny budou uloženy do vyrovnávací paměti vašeho prohlížeče. Synchronizace mezi widgetem a jeho konfigurací se odpojí, jakmile provedete změnu.",
  "syncNoticeTips": "Tím se vymažou veškeré změny a obnoví nastavené záložky.",
  "dontShowAgain": "Příště nezobrazovat",
  "saveVisibility": "Uložit viditelnost vrstev",
  "_widgetLabel": "Záložka"
});