define({
  "_widgetLabel": "Stream",
  "streamControls": "Controlos de streaming",
  "streamFilter": "Filtro",
  "startStreaming": "Iniciar streaming",
  "stopStreaming": "Parar streaming",
  "streamLayers": "Camadas de stream",
  "startStopStream": "Activar opções Parar Stream ou Iniciar Stream",
  "clearStream": "Activar opção Limpar observações anteriores",
  "attributeFilter": "Ativar filtro de atributos",
  "spatialFilter": "Ativar filtro espacial",
  "configFilter": "Configurar filtro de atributos de stream",
  "drawPrevious": "Activar opção Desenhar observações anteriores",
  "addNew": "Adicionar filtro",
  "setFilterName": "Definir nome do filtro",
  "filterNameExists": "Nome de filtro existe na tabela!",
  "invalidFilterName": "O nome deverá ser uma palavra contendo a-z, A-Z, 0-9 ou _.",
  "noFilterTip": "Nenhum filtro configurado",
  "addFilterFailed": "Falha ao adicionar filtro",
  "filterName": "Nome do filtro",
  "limitMapExtent": "Observações limitadas na área de mapa actual",
  "limitDrawExtent": "Observações limitadas na área de utilizador definida",
  "newFilter": "Novo filtro",
  "filterReadOnly": "O filtro herdado do mapa web é apenas de leitura."
});