define({
  "queries": "Forespørgsler",
  "addNew": "Tilføj nyt",
  "newQuery": "Ny forespørgsel",
  "queryLayer": "Forespørgselslag",
  "setSource": "Indstil",
  "setDataSource": "Angiv datakilde",
  "name": "Navn",
  "querySource": "Datakilde",
  "queryName": "Navn på opgave",
  "queryDefinition": "Filterdefinition",
  "resultsSetting": "Indstilling for resultat",
  "symbolSetting": "Symbolindstilling",
  "resultSettingTip": "Angiv, hvad og hvordan output-resultaterne skal vise.",
  "resultItemTitle": "Titel for hvert resultatelement",
  "resultItemContent": "Disse feltattributter vil blive vist",
  "fieldsSetTip": "Markér de felter, der skal vises. Markér et felt for at opdatere dets alias, sortere og formatere.",
  "addField": "Tilføj felt",
  "visibility": "Synlighed",
  "alias": "Alias",
  "specialType": "Speciel type",
  "actions": "Handlinger",
  "none": "Ingen",
  "link": "Link",
  "image": "Billede",
  "noField": "Intet felt",
  "operationalLayerTip": "Tilføj resultat som operationelt lag",
  "setLayerSymbolTip": "Angiv symbolet for forespørgselsresultater: ",
  "setSelectedSymbolTip": "Angiv symbolet for markeret objekt.",
  "notUseFilter": "Brug ikke filter",
  "setSourceTip": "Angiv forespørgselskilde.",
  "setFilterTip": "Angiv filteret korrekt.",
  "ok": "OK",
  "cancel": "Annullér",
  "noFilterTip": "Defineres der ikke et filterudtryk, viser denne forespørgsel alle objekter i den angivne datakilde.",
  "relationships": "Relationer",
  "addRelationshipLayer": "Tilføj ny relation",
  "relatedTo": "Relateret til",
  "selectOption": "Vælg venligst...",
  "resultItemSorting": "Sortering af resultatelement",
  "field": "Mark",
  "sortingOrder": "Rækkefølge",
  "configureFieldsTip": "Konfigurér de felter, som forespørgselsresultatet skal sorteres efter.",
  "setSortingFields": "Indstil sorteringsfelter",
  "ascending": "Stigende",
  "descending": "Faldende",
  "sortBy": "Sortér efter",
  "thenBy": "Dernæst efter",
  "addTask": "Tilføj opgave",
  "noTasksTip": "Ingen forespørgsler konfigureret. Klik på \"${newQuery}\"\" for at tilføje en ny.",
  "infoText": "Info",
  "filters": "Filtre",
  "results": "Resultater",
  "optionsText": "Indstillinger",
  "summaryText": "Oversigt",
  "attributeFilter": "Attributfilter",
  "attributeFilterTip": "Definér attributudtryk til brug i widget'en for at filtrere forespørgselslaget.",
  "defineWhereClause": "Definér en \"hvor-sætning\" for forespørgslen.",
  "noExpressionDefinedTip": "Intet udtryk defineret. Alle poster vil blive returneret.",
  "setExpressions": "Angiv udtryk",
  "spatialFilter": "Spatiale filtre",
  "spatialFilterTip": "Vælg, hvilke spatiale filtre der skal være tilgængelige for slutbrugerne.",
  "defaultOption": "Standard",
  "useCurrentExtentTip": "Returnér kun objekter inden for den aktuelle kortudstrækning",
  "useDrawGraphicTip": "Returnér kun objekter, der gennemskærer den form, der et tegnet på kortet",
  "useFeaturesTip": "Returnér kun objekter, der har en spatial relation til objekterne i et andet lag",
  "noSpatialLimitTip": "Returnér objekter inden for kortets fulde udstrækning",
  "drawingTools": "Vælg tegneværktøjer",
  "bufferSettings": "Aktivér bufferindstilling",
  "defaultDistance": "Standardafstand",
  "bufferDistance": "Bufferafstand",
  "defaultUnit": "Standardenhed",
  "miles": "Miles",
  "kilometers": "Kilometer",
  "feet": "Fod",
  "meters": "Meter",
  "yards": "Yards",
  "nauticalMiles": "Sømil",
  "availableSpatialRelationships": "Vælg regler for spatial relation",
  "setSpatialRelationships": "Angiv spatiale relationer",
  "availability": "Tilgængelighed",
  "relationship": "Relation",
  "label": "Mærke",
  "intersect": "gennemskærer",
  "contain": "indeholder",
  "areContainedIn": "er indeholdt i",
  "cross": "kors",
  "envelopeIntersect": "indkredset gennemskæring",
  "overlap": "overlapper",
  "areOverlapped": "er overlappet",
  "touch": "berør",
  "within": "inden for",
  "areWithin": "er inden for",
  "indexIntersect": "indeksgennemskæring",
  "itemTitle": "Elementtitel",
  "displayFields": "Visningsfelt",
  "sortingFields": "Sortér resultatelementer",
  "setDisplayFields": "Angiv visningsfelter",
  "symbol": "Symbol",
  "setSymbol": "Brug brugerdefineret symbol",
  "changeSymbolAtRuntime": "Tillad ændring af symboler ved runtime",
  "serviceSymbolTip": "Brug de symboler, der er defineret af laget",
  "exportTip": "Tillad eksport af resultater",
  "keepResultsTip": "Behold resultater på kortet, når widget'en lukkes",
  "queryRelatedRecords": "Forespørg på relaterede poster",
  "createLayerForTaskTip": "Angiv, hvordan forespørgselsopgaven skal oprette lag",
  "oneLayerForTaskTip": "Overskriv laget, hver gang forespørgslen udføres",
  "multipleLayerForTaskTip": "Opret et ny lag, hver gang forespørgslen udføres",
  "makeDefault": "Gør til standard",
  "icon": "Ikon",
  "newTask": "Ny opgave",
  "addTaskTip": "Tilføj en eller flere forespørgsler til widget'en, og konfigurér parametre for hver af dem.",
  "webMapPopupTip": "Brug lagets pop-up-konfiguration i webkortet",
  "customPopupTip": "Konfigurér brugerdefineret indhold",
  "showResultsSetActions": "Vis handlinger for de indstillede resultater",
  "zoomTo": "Zoom til",
  "openAttributeTable": "Vis i attributtabel",
  "content": "Indhold",
  "displaySQLTip": "Vis SQL-udtryk for slutbrugere",
  "useLayerDefaultSymbol": "Brug lagets standardsymbol",
  "setCustomIcon": "Indstil brugerdefineret ikon",
  "layerDefaultSymbolTip": "Brug lagets standardsymbol",
  "uploadImage": "Overfør et billede",
  "attributeCriteira": "Attributkriterier",
  "specifyFilterAtRuntimeTip": "Brugerne skal angive parametre for dette udtryk.",
  "value": "VÆRDI",
  "hideLayersTip": "Deaktivér forespørgselsresultatlag, når widget'en er lukket.",
  "tabLabels": "Fanemærker",
  "tasks": "Opgaver",
  "queryCriteira": "Forespørgselskriterier",
  "allowCustomQuery": "Gør det muligt at oprette en brugerdefineret forespørgsel"
});