define({
  "routeUrl": "Maršruto URL",
  "locatorUrl": "Geokoderio URL",
  "geocoderOptions": "Geokodavimo parinktys",
  "autoComplete": "Automatiškai užbaigti",
  "maximumSuggestions": "Maksimalūs patarimai",
  "minCharacters": "Minimalus simbolių skaičius",
  "searchDelay": "Paieškos delsa",
  "placeholder": "Vietos žymė",
  "routeOptions": "Maršruto parinktys",
  "directionsLanguage": "Krypčių kalba",
  "directionsLengthUnits": "Krypčių ilgio vienetai",
  "directionsOutputType": "Krypčių išvesties tipas",
  "impedanceAttribute": "Varžos atributas",
  "kilometers": "Kilometrai",
  "miles": "Mylios",
  "meters": "Metrai",
  "feet": "Pėdos",
  "yards": "Jardai",
  "nauticalMiles": "Jūrmylės",
  "parametersTip": "Nustatykite parametrus tinkamai!",
  "complete": "Pilnas",
  "completeNoEvents": "Pilnas be instrukcijų",
  "instructionsOnly": "Tik instrukcijos",
  "standard": "Standartinis",
  "summaryOnly": "Tik suvestinė",
  "travelModesUrl": "Kelionės režimų URL",
  "searchPlaceholder": "Surasti adresą arba vietą",
  "trafficLayerUrl": "Eismo sluoksnio URL",
  "presetDestinations": "Nustatyti stoteles iš naujo",
  "startPoint": "Pradžios taškas",
  "endPoint": "Pabaigos taškas",
  "destinationHolder": "Adresas arba koordinatės",
  "optional": "Neprivaloma."
});