define({
  "_widgetLabel": "تحويل الإحداثيات",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "درجة دقيقة ثانية",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "الدرجات العشرية - دائرة العرض/خط الطول",
  "DDLongLatNotation": "الدرجات العشرية - خط الطول/دائرة العرض",
  "DDMLatLongNotation": "دقائق عشرية درجات - دائرة العرض/خط الطول",
  "DDMLongLatNotation": "دقائق عشرية درجات - خط الطول/دائرة العرض",
  "DMSLatLongNotation": "ثواني دقائق درجات - دائرة العرض/خط الطول",
  "DMSLongLatNotation": "ثواني دقائق درجات - خط الطول/دائرة العرض",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - حرف الحزمة",
  "UTMHemNotation": "UTM - نصف الكرة (N/S)",
  "formatInput": "مدخلات التنسيق",
  "copyAll": "نسخ الكل",
  "copySuccessful": "نسخ ناجح",
  "copyFailed": "يتعذر النسخ. الرجاء استخدام ctrl+c كبديل.",
  "parseCoordinatesError": "يتعذر توزيع الإحداثيات. الرجاء فحص المدخلات.",
  "comfirmInputNotation": "تأكيد علامة المدخلات",
  "latLongWarningMessage": "تم الكشف عن تنسيق الإدخال حيث تحتوي على بادئة ولاحقة لقيمة خط العرض أو الطول، ويستند التنسيق المرتجع إلى البادئة.",
  "inputLabel": "المدخل",
  "outputLabel": "المخرجات",
  "cancelButtonLabel": "إلغاء الأمر",
  "applyButtonLabel": "تطبيق",
  "posNegPrefixLabel": "أضف البادئة \"+/-\" إلى الأرقام السالبة والموجبة",
  "editCoordinateDialogTitle": "تعيين سلسلة تنسيق الإحداثيات",
  "rememberDecisionLabel": "تذكر قراري ولا تسألني مرة أخرى.<br/>",
  "coordinateInputLabel": "أدخل الإحداثيات أو انقر على الخريطة",
  "zoomLabel": "تغيير مقياس الرسم",
  "multipleNotationLabel": "العلامات الموجودة التي تطابق المدخلات. الرجاء تأكيد ما تريد استخدامه:",
  "copyToClipboard": "نسخ إلى الحافظة",
  "formatOutput": "مخرجات التنسيق",
  "addNewNotation": "إضافة علامة جديدة",
  "notationAddedMessage": "تمت إضافة تعليق توضيحي جديد",
  "addLabel": "إضافة",
  "removeCoordinate": "إزالة الإحداثيات",
  "expandOutput": "توسيع المخرجات",
  "latitudeLabel": "دائرة عرض",
  "longitudeLabel": "خطوط الطول",
  "quadrantLabel": "رباعي",
  "keyLabel": "مفتاح",
  "fifteenDegreeLabel": "15Â° رباعية",
  "oneDegreeLabel": "1Â° رباعية",
  "eastingLabel": "شرقي",
  "northingLabel": "شمالي",
  "zoneLabel": "منطقة",
  "bandLabel": "مجال",
  "gzdLabel": "GZD",
  "gridSquareLabel": "شبكة مربعة",
  "hemisphereLabel": "نصف الكرة الأرضية"
});