define({
  "_widgetLabel": "Situatiebewustzijn",
  "locate_incident": "Incident zoeken",
  "reverse_geocoded_address": "Dichtstbijzijnde adres",
  "reverse_geocoded_error": "Not available",
  "now": "NU",
  "wind": "WIND",
  "SUN": "ZON",
  "MON": "MAA",
  "TUE": "DIN",
  "WED": "WOE",
  "THU": "DON",
  "FRI": "VRIJ",
  "SAT": "ZAT",
  "actionLabel": "Locatie instellen",
  "drawPoint": "Teken punt",
  "drawLine": "Teken lijn",
  "drawPolygon": "Teken polygoon",
  "saveIncident": "Opslaan",
  "clearIncident": "Opnieuw beginnen",
  "noFeaturesFound": "Geen objecten gevonden.",
  "downloadCSV": "Downloaden",
  "sum": "Som",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Gemiddelde",
  "count": "TELLEN",
  "area": "GEBIED",
  "length": "LENGTE",
  "update_btn": "Gereed",
  "delete_btn": "Verwijderen",
  "get_directions": "Routebeschrijving krijgen",
  "incident": "Incident",
  "incidents": "Incidenten",
  "buffer": "Buffer",
  "buffers": "Buffers",
  "weather": "Weer",
  "poweredBy": "Powered by",
  "_featureAction_ActionLabel": "Locatie instellen",
  "_featureAction_AddRemoveActionLabel": "Locatie toevoegen/verwijderen",
  "snapshot": "SnapShot-map gemaakt door App-id:",
  "user_credentials": "De gebruiker heeft geen geldige machtigingen.",
  "notPolySnapShot": "Geef een bufferafstand op voor het maken van een snapshot.",
  "notPolyReport": "Geen geldige resultaten om aan het rapport toe te voegen.",
  "notValidDownload": "Geen geldige resultaten te downloaden.",
  "of_append": "van",
  "layer_append": "laag",
  "downloadAll": "Alles downloaden",
  "createSnapshot": "Snapshot maken",
  "createReport": "Maak rapport",
  "calculated_results": "Samengevatte informatie",
  "closest": "Dichtstbijzijnde object",
  "proximity": "Nabijheid",
  "summary": "Samenvatting",
  "groupedSummary": "Gegroepeerde telling",
  "_count": "Aantal",
  "approximate": "benaderend",
  "snapshot_name": "Snapshoteigenschappen instellen",
  "report_name": "Rapporteigenschappen instellen",
  "invalid_snapshot_name": "Ongeldige snapshotnaam.",
  "invalid_report_name": "Ongeldige rapporttitel.",
  "orientation": "Oriëntatie",
  "pageSize": "Paginagrootte",
  "comments": "Opmerkingen",
  "choose_group": "Groepen",
  "forecast": "Voorspelling",
  "select_group": "Groep selecteren",
  "select_group_instruction": "Het snapshot zal gemaakt worden en gedeeld worden met de geselecteerde groep",
  "information_append": " Informatie",
  "distance": "AFSTAND",
  "buffer_invalid": "Voer een geldig cijfer in tussen ${min} en ${max}"
});