define({
  "_widgetLabel": "Podobnost modelara",
  "general": {
    "clear": "Obriši",
    "cancel": "Otkaži",
    "save": "Pokreni",
    "saveAs": "Izvezi"
  },
  "saveModel": {
    "save": "Izvezi",
    "title": "Naslov: ",
    "summary": "Rezime: ",
    "description": "Opis: ",
    "tags": "Oznake: ",
    "folder": "Fascikla: ",
    "homeFolderPattern": "{username} (Home)",
    "failed": "Izvoz nije uspeo."
  },
  "util": {
    "colorRamp": {
      "1": "Izuzetno nisko",
      "2": "Veoma nisko",
      "3": "Nisko",
      "4": "Nisko srednje",
      "5": "Srednje",
      "6": "Visoko srednje",
      "7": "Visoko",
      "8": "Veoma visoko",
      "9": "Izuzetno visoko",
      "low": "Nisko",
      "high": "Visoko",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Okreni"
    }
  },
  "wro": {
    "caption": "Podobnost modelara",
    "browsePrompt": "Servis težinskog preklapanja",
    "selectLayersCaption": "Selektujte slojeve",
    "selectLayers": "Slojevi",
    "designModelCaption": "Model dizajna",
    "designModel": "Model dizajna",
    "transparency": "Prozirnost",
    "visible": "Vidljivo",
    "total": "Zbir",
    "unableToLoad": "Učitavanje modela nije moguće.",
    "projectNotOpen": "Projekat nije otvoren.",
    "readMore": "Pročitaj više",
    "validation": {
      "validating": "Proveravanje valjanosti...",
      "invalidItemCaption": "Upozorenje servisa težinskog preklapanja",
      "notAnImageService": "Ova stavka nije servis slike.",
      "notAWroService": "Ova stavka nije servis težinskog preklapanja.",
      "undefinedUrl": "URL ove stavke nije definisan.",
      "inaccessible": "Servis je nepristupačan.",
      "generalError": "Otvaranje stavke nije moguće.",
      "missingFieldPattern": "{field} je obavezno polje",
      "notAllowRasterFunction": "allowRasterFunction mora da bude postavljeno na istinito",
      "notNearestResampling": "defaultResamplingMethod mora da bude najbliže",
      "notIsWeightedOverlayProp": "Ključno svojstvo IsWeightedOverlay mora da bude postavljeno na istinito",
      "invalidLink": "Nevažeći URL. Nije uspelo otvaranje sajta za izabrani sloj.",
      "unexpectedError": "Nastupilo je neočekivano stanje.",
      "rangeMessage": "Vrednost mora da bude između ${0} i ${1}",
      "rangeMessage100": "Vrednost mora da bude između 0 i 100",
      "maxLayers": "Maksimum od ${0} slojeva dozvoljenih od strane servisa, najpre morate da uklonite sloj pre dodavanja novog.",
      "notFound": "Sloj ${0} nije pronađen u servisu težinskog preklapanja",
      "wroServiceNotDefined": "Nije definisan servis težinskog preklapanja za model.",
      "overlayLayerOutputInvalid": "Izlazna vrednost sloj preklapanja [${0}] ponovno mapiranje opsega [${1}] nedostaje ili je nevažeća",
      "overlayLayerInputInvalid": "Ulazna min/maks vrednost sloj preklapanja [${0}] ponovno mapiranje opsega [${1}] nedostaje ili je nevažeća",
      "overlayLayerRangesMissing": "Sloj preklapanja [${0}] nedostaje ponovno mapiranje opsega",
      "overlayLayerWeight": "Težine slojeva preklapanja moraju u zbiru da daju 100",
      "overlayLayerRequired": "Obavezan je barem jedan sloj preklapanja",
      "overlayLayerNotDefined": "Preklapanje slojeva nije definisano",
      "requiresColormap": "Rasterska funkcija zahteva mapu u boji, ali model nema važeću definiciju skale boja",
      "createModelError": "Greška pri kreiranju modela",
      "invalidModel": "Model nije validan",
      "imageServiceNotDefined": "Sloj servisa slike nije definisan",
      "imageLayerNotDefined": "Sloj servisa slike nije definisan",
      "histogramNotDefined": "Nije definisana funkcija histograma težinskog preklapanja."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zeleno žuto crveno",
      "Red Yellow Green": "Crveno žuto zeleno",
      "Yellow to Dark Red": "Žuto do tamno crveno",
      "Dark Red to Yellow": "Tamno crveno do žuto",
      "Light Gray to Dark Gray": "Svetlo sivo do tamno sivo",
      "Dark Gray to Light Gray": "Tamno sivo do svetlo sivo",
      "Light Brown to Dark Brown": "Svetlo braon do tamno braon",
      "Dark Brown to Light Brown": "Tamno braon do svetlo braon",
      "Full Spectrum - Bright Red to Blue": "Pun spektar - jarko crveno do plavo",
      "Full Spectrum - Bright Blue to Red": "Pun spektar - jarko plavo do crveno",
      "Partial Spectrum - Yellow to Blue": "Delimičan spektar - žuto do plavo",
      "Partial Spectrum - Blue to Yellow": "Delimičan spektar - plavo do žuto",
      "Yellow-Green to Dark Blue": "Žuto-zeleno do tamno plavo",
      "Dark Blue to Yellow-Green": "Tamno plavo do žuto-zeleno",
      "Cold to Hot Diverging": "Hladno do vruće divergentno",
      "Hot to Cold Diverging": "Vruće do hladno divergentno",
      "Surface - Low to High": "Površina - nisko do visoko",
      "Surface - High to Low": "Površina - visoko do nisko"
    }
  },
  "tabs": {
    "layers": "Slojevi",
    "model": "Model",
    "chart": "Grafikon"
  },
  "chart": {
    "prompt": "Geoobjekti",
    "working": "Ažuriranje...",
    "polygonTool": "Nacrtajte poligon",
    "freehandPolygonTool": "Nacrtajte poligon slobodnom rukom",
    "selectTool": "Izaberite iz sloja",
    "panTool": "Pomeri",
    "clearButton": "Obriši",
    "noModelLayer": "Nema modela.",
    "noSubjectLayers": "Vaša mapa nema slojeve poligona.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});