define({
  "_widgetLabel": "智慧編輯器",
  "_featureAction_SmartEditor": "智慧編輯器",
  "noEditPrivileges": "您的帳號沒有建立或修改資料的權限。",
  "widgetActive": "使用中",
  "widgetNotActive": "非使用中",
  "pressStr": "按 ",
  "ctrlStr": " Ctrl 鍵 ",
  "snapStr": " 啟用貼齊",
  "noAvailableTempaltes": "沒有可用的樣板",
  "editorCache": " - 編輯器快取",
  "presetFieldAlias": "欄位",
  "presetValue": "預設值",
  "usePresetValues": " 使用預設值 (僅限新圖徵)",
  "editGeometry": " 編輯幾何",
  "savePromptTitle": "儲存圖徵",
  "savePrompt": "是否要儲存目前圖徵?",
  "deletePromptTitle": "刪除圖徵",
  "deletePrompt": "是否確定要刪除所選圖徵?",
  "attachmentLoadingError": "上傳附件出錯",
  "attachmentSaveDeleteWarning": "警告: 會自動儲存對附件的變更",
  "autoSaveEdits": "自動儲存編輯內容",
  "addNewFeature": "建立新圖徵",
  "featureCreationFailedMsg": "無法建立新記錄/圖徵",
  "noRelatedFeatureFoundMsg": "找不到相關記錄/圖徵",
  "relatedItemTitle": "相關表格/圖層",
  "invalidRelationShipMsg": "請確定主要索引鍵欄位 '${parentKeyField}’ 具備有效值",
  "pendingFeatureSaveMsg": "請先儲存圖徵編輯內容再建立相關圖徵。",
  "attachmentsRequiredMsg": "(*) 附件為必填項。",
  "filterEditor": {
    "all": "全部",
    "noAvailableTempaltes": "沒有可用的樣板",
    "searchTemplates": "搜尋樣板"
  },
  "invalidConfiguration": "未配置 widget，或配置中的圖層已從地圖中消失。請在建構器模式中開啟應用程式，並重新配置 widget。",
  "geometryServiceURLNotFoundMSG": "無法取得幾何服務 URL"
});