define({
  "_widgetLabel": "Program modelujący przydatność",
  "general": {
    "clear": "Wyczyść",
    "cancel": "Anuluj",
    "save": "Uruchom",
    "saveAs": "Eksportuj"
  },
  "saveModel": {
    "save": "Eksportuj",
    "title": "Tytuł: ",
    "summary": "Podsumowanie: ",
    "description": "Opis: ",
    "tags": "Znaczniki: ",
    "folder": "Folder: ",
    "homeFolderPattern": "{username} (folder główny)",
    "failed": "Eksport nie powiódł się."
  },
  "util": {
    "colorRamp": {
      "1": "Niezwykle niski",
      "2": "Bardzo niski",
      "3": "Niski",
      "4": "Średnio niski",
      "5": "Średnie",
      "6": "Średnio wysoki",
      "7": "Wysoki",
      "8": "Bardzo wysoki",
      "9": "Niezwykle wysoki",
      "low": "Niski",
      "high": "Wysoki",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Odwróć"
    }
  },
  "wro": {
    "caption": "Program modelujący przydatność",
    "browsePrompt": "Usługa nakładek ważonych",
    "selectLayersCaption": "Wybierz warstwy",
    "selectLayers": "Warstwy",
    "designModelCaption": "Model projektu",
    "designModel": "Model projektu",
    "transparency": "Przezroczystość",
    "visible": "Widoczne",
    "total": "Wszystkie",
    "unableToLoad": "Nie można wczytać modelu.",
    "projectNotOpen": "Projekt nie jest otwarty.",
    "readMore": "Czytaj więcej",
    "validation": {
      "validating": "Trwa weryfikacja...",
      "invalidItemCaption": "Ostrzeżenia usługi nakładek ważonych",
      "notAnImageService": "Ten element nie jest usługą rastrową.",
      "notAWroService": "Ten element nie jest usługą nakładki ważonej.",
      "undefinedUrl": "Adres URL tego elementu nie został zdefiniowany.",
      "inaccessible": "Usługa jest niedostępna.",
      "generalError": "Nie można otworzyć elementu.",
      "missingFieldPattern": "{field} jest polem wymaganym",
      "notAllowRasterFunction": "Dla właściwości allowRasterFunction należy ustawić wartość true",
      "notNearestResampling": "Dla właściwości defaultResamplingMethod należy ustawić wartość Nearest",
      "notIsWeightedOverlayProp": "Dla właściwości kluczowej IsWeightedOverlay należy ustawić wartość true",
      "invalidLink": "Adres URL jest nieprawidłowy. Otwarcie witryny dla wybranej warstwy nie powiodło się.",
      "unexpectedError": "Wystąpił nieoczekiwany stan.",
      "rangeMessage": "Wartość musi zawierać się w przedziale od ${0} do ${1}",
      "rangeMessage100": "Wartość musi zawierać się w przedziale od 0 do 100",
      "maxLayers": "W przypadku tej usługi maksymalna liczba dozwolonych warstw wynosi ${0}. Przed dodaniem nowej warstwy należy usunąć istniejącą.",
      "notFound": "Nie znaleziono warstwy ${0} w usłudze nakładki ważonej",
      "wroServiceNotDefined": "Nie zdefiniowano usługi nakładki ważonej dla modelu.",
      "overlayLayerOutputInvalid": "Brak wartości wyjściowej zakresów ponownego mapowania [${1}] warstwy nakładanej [${0}] lub jest ona nieprawidłowa",
      "overlayLayerInputInvalid": "Brak wartości minimalnej lub maksymalnej zakresów ponownego mapowania [${1}] warstwy nakładanej [${0}] lub jest ona nieprawidłowa",
      "overlayLayerRangesMissing": "Brak zakresów ponownego mapowania warstwy nakładanej [${0}]",
      "overlayLayerWeight": "Suma wag warstwy nakładanej musi wynosić 100",
      "overlayLayerRequired": "Wymagana jest co najmniej jedna warstwa nakładana",
      "overlayLayerNotDefined": "Nie zdefiniowano warstw nakładanych",
      "requiresColormap": "Ta funkcja rastra wymaga mapy kolorów, ale model nie zawiera prawidłowej definicji mapy kolorów",
      "createModelError": "Błąd podczas tworzenia modelu",
      "invalidModel": "Model jest nieprawidłowy",
      "imageServiceNotDefined": "Nie zdefiniowano warstwy usługi rastrowej",
      "imageLayerNotDefined": "Nie zdefiniowano warstwy usługi rastrowej",
      "histogramNotDefined": "Nie zdefiniowano funkcji histogramu nakładki ważonej."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zielony, żółty, czerwony",
      "Red Yellow Green": "Czerwony, żółty, zielony",
      "Yellow to Dark Red": "Żółty do ciemnoczerwonego",
      "Dark Red to Yellow": "Ciemnoczerwony do żółtego",
      "Light Gray to Dark Gray": "Jasnoszary do ciemnoszarego",
      "Dark Gray to Light Gray": "Ciemnoszary do jasnoszarego",
      "Light Brown to Dark Brown": "Jasnobrązowy do ciemnobrązowego",
      "Dark Brown to Light Brown": "Ciemnobrązowy do jasnobrązowego",
      "Full Spectrum - Bright Red to Blue": "Pełne widmo - jaskrawoczerwony do niebieskiego",
      "Full Spectrum - Bright Blue to Red": "Pełne widmo - jaskrawoniebieski do czerwonego",
      "Partial Spectrum - Yellow to Blue": "Częściowe widmo - żółty do niebieskiego",
      "Partial Spectrum - Blue to Yellow": "Częściowe widmo - niebieski do żółtego",
      "Yellow-Green to Dark Blue": "Żółtozielony do ciemnoniebieskiego",
      "Dark Blue to Yellow-Green": "Ciemnoniebieski do żółtozielonego",
      "Cold to Hot Diverging": "Zimny do gorącego rozbieżny",
      "Hot to Cold Diverging": "Gorący do zimnego rozbieżny",
      "Surface - Low to High": "Powierzchnia - niska do wysokiej",
      "Surface - High to Low": "Powierzchnia - wysoka do niskiej"
    }
  },
  "tabs": {
    "layers": "Warstwy",
    "model": "Model",
    "chart": "Wykres"
  },
  "chart": {
    "prompt": "Charakterystyka",
    "working": "Aktualizowanie...",
    "polygonTool": "Rysuj poligon",
    "freehandPolygonTool": "Rysuj dowolny poligon",
    "selectTool": "Wybierz z warstwy",
    "panTool": "Przesuń",
    "clearButton": "Wyczyść",
    "noModelLayer": "Brak modelu.",
    "noSubjectLayers": "Twoja mapa nie ma warstw poligonowych.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});