define({
  "routeUrl": "URL poti",
  "locatorUrl": "URL geokodirnika",
  "geocoderOptions": "Možnosti geokodirnika",
  "autoComplete": "Samodejno izpolnjevanje",
  "maximumSuggestions": "Maksimalno predlogov",
  "minCharacters": "Minimalno znakov",
  "searchDelay": "Zakasnitev iskanja",
  "placeholder": "Označba mesta",
  "routeOptions": "Možnosti poti",
  "directionsLanguage": "Jezik navodil za pot",
  "directionsLengthUnits": "Enote dolžine navodil za poti",
  "directionsOutputType": "Tip izhodnih navodil za pot",
  "impedanceAttribute": "Atribut impendance",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Čevlji",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "parametersTip": "Pravilno nastavite parametre!",
  "complete": "Celovito",
  "completeNoEvents": "Celovito brez dogodkov",
  "instructionsOnly": "Samo navodila",
  "standard": "Standardno",
  "summaryOnly": "Samo povzetek",
  "travelModesUrl": "URL načinov potovanja",
  "searchPlaceholder": "Najdi naslov ali kraj",
  "trafficLayerUrl": "Vnesi URL sloja prometa",
  "presetDestinations": "Prednastavi postanke",
  "startPoint": "Začetna točka",
  "endPoint": "Končna točka",
  "destinationHolder": "Naslov ali koordinate",
  "optional": "Izbirno."
});