define({
  "layerSelect": "Zaznacz warstwę obrazową",
  "displayMeasureResultInPopup": "Wyświetl wyniki pomiaru w oknie podręcznym",
  "angularUnitSelect": "Domyślna jednostka kątowa",
  "linearUnitSelect": "Domyślna jednostka liniowa",
  "areaUnitSelect": "Domyślna jednostka powierzchni",
  "displayOperationSelect": "Wybierz operacje pomiaru",
  "errorSectionMessage": "Żadna z warstw nie zapewnia możliwości pomiarowych.",
  "unitLabel": {
    "esriInches": "Cale",
    "esriFeet": "Stopy",
    "esriYards": "Jardy",
    "esriMiles": "Mile",
    "esriNauticalMiles": "Mile morskie",
    "esriMillimeters": "Milimetry",
    "esriCentimeters": "Centymetry",
    "esriDecimeters": "Decymetry",
    "esriMeters": "Metry",
    "esriKilometers": "Kilometry",
    "esriDURadians": "Radiany",
    "esriDUDecimalDegrees": "Stopnie",
    "esriSquareInches": "Cale kw.",
    "esriSquareFeet": "Stopy kw.",
    "esriSquareYards": "Jardy kw.",
    "esriAcres": "Akry",
    "esriSquareMiles": "Mile kw.",
    "esriSquareMillimeters": "Milimetry kw.",
    "esriSquareCentimeters": "Centymetry kw.",
    "esriSquareDecimeters": "Decymetry kw.",
    "esriSquareMeters": "Metry kw.",
    "esriAres": "Ary",
    "esriHectares": "Hektary",
    "esriSquareKilometers": "Kilometry kw."
  },
  "operationLabel": {
    "esriMensurationPoint": "Lokalizacja",
    "esriMensurationDistanceAndAngle": "Odległość i kąt",
    "esriMensurationAreaAndPerimeter": "Pole powierzchni i obwód",
    "esriMensurationHeightFromBaseAndTop": "Wysokość: od podstawy do wierzchołka",
    "esriMensurationHeightFromBaseAndTopShadow": "Wysokość: od podstawy do wierzchołka cienia",
    "esriMensurationHeightFromTopAndTopShadow": "Wysokość: od wierzchołka do wierzchołka cienia",
    "esriMensurationCentroid": "Centroid",
    "esriMensurationPoint3D": "Lokalizacja (3D)",
    "esriMensurationDistanceAndAngle3D": "Odległość i kąt (3D)",
    "esriMensurationAreaAndPerimeter3D": "Pole powierzchni i obwód (3D)",
    "esriMensurationCentroid3D": "Centroid (3D)"
  }
});