define({
  "_widgetLabel": "Upit",
  "executeQueryTip": "Kliknite na jednu od sledećih stavki zadataka da biste izvršili upit.",
  "invalidConfig": "Nevažeća konfiguracija. Koristite stranicu postavki Upita da biste dobili ispravnu konfiguraciju.",
  "queryParams": "Opcije",
  "parameters": "OPCIJE",
  "queries": "UPITI",
  "apply": "Primeni",
  "queryResults": "Rezultati",
  "clear": "Izbriši",
  "noResults": "Nije pronađen nijedan geoobjekat.",
  "queryError": "Neuspeo upit!",
  "numberFound": "Broj pronađenih geoobjekata",
  "mapExtentTip": "Ograniči rezultate na trenutnu oblast mape.",
  "noValue": "Nema vrednosti",
  "and": "i",
  "stringOperatorIs": "je",
  "stringOperatorIsNot": "nije",
  "stringOperatorStartsWith": "počinje sa",
  "stringOperatorEndsWith": "završava se sa",
  "stringOperatorContains": "sadrži",
  "stringOperatorDoesNotContain": "ne sadrži",
  "stringOperatorIsBlank": "je prazno",
  "stringOperatorIsNotBlank": "nije prazno",
  "dateOperatorIsOn": "je na",
  "dateOperatorIsNotOn": "nije na",
  "dateOperatorIsBefore": "je ispred",
  "dateOperatorIsAfter": "je iza",
  "dateOperatorDays": "dani",
  "dateOperatorWeeks": "sedmice",
  "dateOperatorMonths": "meseci",
  "dateOperatorInTheLast": "u poslednjih",
  "dateOperatorNotInTheLast": "nije u poslednjih",
  "dateOperatorIsBetween": "je između",
  "dateOperatorIsNotBetween": "nije između",
  "dateOperatorIsBlank": "je prazno",
  "dateOperatorIsNotBlank": "nije prazno",
  "numberOperatorIs": "je",
  "numberOperatorIsNot": "nije",
  "numberOperatorIsAtLeast": "je najmanje",
  "numberOperatorIsLessThan": "je manje od",
  "numberOperatorIsAtMost": "je najviše",
  "numberOperatorIsGreaterThan": "je veće od",
  "numberOperatorIsBetween": "je između",
  "numberOperatorIsNotBetween": "nije između",
  "numberOperatorIsBlank": "je prazno",
  "numberOperatorIsNotBlank": "nije prazno",
  "operationalLayerTip": "Dodaj rezultate kao operativni sloj",
  "queryResult": "Rezultat upita",
  "specifyParamsTip": "Navedite parametre za ovaj zadatak",
  "useSpatialFilter": "Koristite prostorni filter da biste ograničili geoobjekte",
  "useCurrentMapExtent": "Samo geoobjekti koji presecaju trenutnu površinu mape",
  "drawGraphicOnMap": "Samo geoobjekti koji presecaju površinu koju korisnik odredi",
  "specifySpatialFilterMsg": "Navedite prostorni filter za ovaj zadatak.",
  "clearResults": "Obriši rezultate",
  "operationalTip": "Kada je ova opcija potvrđena, rezultati će biti zadržani na mapi dok ne kliknete na dugme „${clearResults}“.",
  "noneQueryTip": "Nema konfigurisanog zadatka upita za ovaj vidžet.",
  "noPermissionsMsg": "Nemate dozvole da pristupite ovom servisu.",
  "attributesFromRelationship": "Atributi iz povezane table",
  "tasks": "Zadaci",
  "applySpatialFilterToLimitResults": "Primenite prostorni filter da biste ograničili rezultate",
  "useCurrentExtentTip": "Vrati samo geoobjekte unutar trenutnog obuhvata mape",
  "useDrawGraphicTip": "Vrati samo geoobjekte koji se ukrštaju sa oblikom nacrtanim na mapi",
  "useFeaturesTip": "Vrati samo geoobjekte koji imaju prostornu vezu sa geoobjektima u drugom sloju",
  "noSpatialLimitTip": "Vrati geoobjekte unutar potpunog obuhvata mape",
  "applySearchDistance": "Primeni rastojanje pretrage",
  "spatialRelationship": "Prostorna veza",
  "relatedLayer": "Povezani sloj",
  "bufferDistance": "Rastojanje zone bliskosti",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "back": "Nazad",
  "execute": "Izvrši",
  "zoomTo": "Zumiraj na",
  "openAttributeTable": "Prikaži u tabeli atributa",
  "noResult": "Bez rezultata.",
  "noTask": "Bez zadatka.",
  "removeThisResult": "Ukloni ovaj rezultat",
  "attributeCriteira": "Kriterijumi atributa",
  "spatialFilter": "Prostorni filter",
  "value": "VREDNOST",
  "noAttributeSpatialFilterTip": "Nema definisanih filtera. Svi geoobjekti će biti vraćeni.",
  "showAllRelatedRecords": "Prikaži sve povezane zapise",
  "changeSymbol": "Promeni simbol",
  "queryCriteira": "Kriterijum upita",
  "customQuery": "Prilagođeni upit",
  "layer": "Sloj",
  "createCustomQuery": "Kreiraj prilagođeni upit."
});