define({
  "gridTabLabel": "Rutnät",
  "labelTabLabel": "Etiketter",
  "referenceSystemTabLabel": "Referenssystem",
  "gridTabDescription": "Ange utseende och beteendefunktion hos rutnätsceller.",
  "cellOutlineColor": "Cellens konturfärg",
  "cellFillColor": "Cellens fyllnadsfärg",
  "transparency": "Transparens",
  "cellShapeDropDown": "Cellens form",
  "default": "Rektangel",
  "hexagon": "Hexagon",
  "cellUnitsDropDown": "Cellenheter",
  "miles": "Mile",
  "kilometers": "Kilometer",
  "feet": "Fot",
  "meters": "Meter",
  "yards": "Yard",
  "nautical-miles": "Nautiska mil",
  "gridOriginDropDown": "Rutnätets origo",
  "lowerLeft": "Nedre vänstra",
  "lowerRight": "Nedre högra",
  "upperLeft": "Övre vänstra",
  "upperRight": "Övre högra",
  "center": "Centrera",
  "labelTabDescription": "Ange utseende och beteendefunktion hos rutnätsetiketter.",
  "labelSettings": "Etikettstil",
  "font": "Teckensnitt",
  "textSize": "Textstorlek",
  "textColor": "Textfärg",
  "halo": "Ring",
  "show": "Visa",
  "labelTypeDropDown": "Etikettyp",
  "alphaNumeric": "Alfanumerisk",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Numerisk",
  "labelDirectionDropDown": "Etikettens riktning",
  "horizontal": "Horisontell",
  "vertical": "Vertikal",
  "labelOriginDropDown": "Etikettens ursprung",
  "referenceSystemlTabDescription": "Ange standardreferenssystem.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Låsinställningar – Förhindrar att användaren kan ändra de konfigurerade inställningarna i widgeten"
});