define({
  "gridTabLabel": "Сетка",
  "labelTabLabel": "Подписи",
  "referenceSystemTabLabel": "Система привязки",
  "gridTabDescription": "Задает оформление и поведение ячеек сетки.",
  "cellOutlineColor": "Цвет контура ячейки",
  "cellFillColor": "Цвет заливки ячейки",
  "transparency": "Прозрачность",
  "cellShapeDropDown": "Форма ячейки",
  "default": "Прямоугольник",
  "hexagon": "Шестиугольник",
  "cellUnitsDropDown": "Единицы измерения ячейки",
  "miles": "Мили",
  "kilometers": "Километры",
  "feet": "Футы",
  "meters": "Метры",
  "yards": "Ярды",
  "nautical-miles": "Морские мили",
  "gridOriginDropDown": "Начало сетки",
  "lowerLeft": "Нижний‑левый",
  "lowerRight": "Нижний‑правый",
  "upperLeft": "Верхний‑левый",
  "upperRight": "Верхний-правый",
  "center": "Центр",
  "labelTabDescription": "Задает оформление и поведение подписей сетки.",
  "labelSettings": "Стиль подписей",
  "font": "Шрифт",
  "textSize": "Размер текста",
  "textColor": "Цвет текста",
  "halo": "Гало",
  "show": "Показывать",
  "labelTypeDropDown": "Тип подписей",
  "alphaNumeric": "Алфавитно-цифровые",
  "alphaAlpha": "Алфавитные-алфавитные",
  "numeric": "Числовые",
  "labelDirectionDropDown": "Направление подписи",
  "horizontal": "Горизонтально",
  "vertical": "Вертикально",
  "labelOriginDropDown": "Начало подписи",
  "referenceSystemlTabDescription": "Задать систему привязки по умолчанию.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Блокировать настройки – это не даст пользователю изменять любые параметры, настроенные в виджете"
});