define({
  "chartSettingLabel": "Diagraminnstillinger",
  "addNewLabel": "Legg til ny",
  "generalSettingLabel": "Generelle innstillinger",
  "searchSourceSettingLabel": "Søkekildeinnstillinger",
  "layerChooser": {
    "title": "Velg laget du vil lage diagram av",
    "selectPolygonLayerLabel": "Velg lag",
    "selectPolygonLayerHintText": "Hint: Hvis du konfigurerer flere diagrammer, må lagene ha samme geomertritype",
    "selectRelatedTableLayerLabel": "Velg tabell knyttet til lag",
    "selectRelatedTableLayerHintText": "Hint: Bare tabeller med numeriske felt vises",
    "errorInSelectingPolygonLayer": "Velg et lag som har et tilknyttet punktlag.",
    "errorInSelectingRelatedLayer": "Velg en gyldig tilknyttet tabell/gyldig lag som det skal opprettes lag for.",
    "polygonLayerNotHavingRelationships": "Det valgte laget har ikke tilknyttet tabell/lag."
  },
  "ChartSetting": {
    "sectionTitle": "Seksjonstittel",
    "sectionTitleHintText": "Hint: Vises i overskriften for seksjonen",
    "chartTitle": "Diagramtittel",
    "chartTitleHintText": "Hint: Vises i midten øverst på diagrammet",
    "chartDescription": "Beskrivelse",
    "chartDescriptionHintText": "Hint: Vises under diagrammet",
    "chartType": "Diagramtype",
    "barChart": "Stolpediagram",
    "pieChart": "Sektordiagram",
    "polarChart": "Polardiagram",
    "dataSeriesField": "Dataseriefelt",
    "labelField": "Påskriftfelt",
    "chartColor": "Diagramfarge",
    "singleColor": "En farge",
    "colorByTheme": "Farge etter tema",
    "colorByFieldValue": "Farge etter feltverdi",
    "xAxisTitle": "Tittel på X-akse",
    "xAxisHintText": "Hint: Tittelen på X-aksen",
    "yAxisTitle": "Tittel på Y-akse",
    "yAxisHintText": "Hint: Tittelen på Y-aksen",
    "fieldColorLabel": "Etikett",
    "fieldColorColor": "Farge",
    "defaultFieldSelectLabel": "Velg",
    "errMsgFieldValuesNotFound": "Finner ingen verdier for feltet som er valgt",
    "errMsgSectionTitle": "Skriv inn seksjonstittelen",
    "errMsgFieldByValue": "Velg en feltverdi",
    "settingTabTitle": "Innstilling",
    "layoutTabTitle": "Oppsett",
    "polarChartSelectFieldsHintText": "Hint: Velg felter for å generere polardiagram",
    "visibilityText": "Synlighet",
    "fieldNameText": "Feltnavn",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Velg tre eller flere felter for å generere polardiagram",
    "polarChartPolygonFillLabel": "Fyll polygon",
    "polarChartPolygonFillHintText": "Hint: Merk av i boksen for å vise polygonfyll i polardiagram",
    "viewLayoutLabel": "Oppsett",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Ørken",
      "themeDistinctive": "Distinktiv",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Gresshoppe",
      "themeGrasslands": "Gresslette",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmoni",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Mint",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Kratt",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Våtmark",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Generelle innstillinger",
    "locationSymbolLabel": "Grafisk symbol for lokasjon",
    "locationSymbolHintText": "Hint: Brukes til å vise symbol for adresse og klikket lokasjon",
    "refreshIntervalLabel": "Oppdateringsintervall",
    "refreshIntervalHintText": "Hint: Brukes til å oppdatere diagrammer basert på dette intervallet. Angi en verdi mellom 1 tog 1440 minutter.",
    "errMsgRefreshInterval": "Angi et oppdateringsintervall på mellom 0 og 1440 minutter",
    "symbolPickerPreviewText": "Forhåndsvisning:",
    "showToolToSelectLabel": "Angi lokasjon-knapp",
    "showToolToSelectHintText": "Hint: Viser en knapp for å angi en lokasjon på kartet i stedet for at lokasjonen alltid angis ved å klikke på kartet."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Søkekildeinnstillinger",
    "searchSourceSettingTitle": "Søkekildeinnstillinger",
    "searchSourceSettingTitleHintText": "Legg til og konfigurer geokodingstjenester eller geoobjektslag som søkekilder. Disse angitte kildene avgjør hva som er søkbart i søkeboksen.",
    "addSearchSourceLabel": "Legg til søkekilde",
    "featureLayerLabel": "Geoobjektlag",
    "geocoderLabel": "Geokoder",
    "nameTitle": "Navn",
    "generalSettingLabel": "Generell innstilling",
    "allPlaceholderLabel": "Plassholdertekst for søk i alt:",
    "allPlaceholderHintText": "Hint: Skriv inn teksten som skal vises som plassholder når du søker i alle lag og geokoder.",
    "generalSettingCheckboxLabel": "Vis popuptekst for funnet geoobjekt eller lokasjon",
    "countryCode": "Lands- eller regionskode(r)",
    "countryCodeEg": "f.eks. ",
    "countryCodeHint": "Hvis du lar dette feltet stå tomt, søkes det i alle land og regioner",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Søk kun i gjeldende kartutstrekning",
    "zoomScale": "Zoomskala",
    "locatorUrl": "Geokoder-URL",
    "locatorName": "Geokodernavn",
    "locatorExample": "Eksempel",
    "locatorWarning": "Denne versjonen av geokodingstjenesten støttes ikke. Widgeten støtter versjon 10.0 og nyere av geokodingstjenesten.",
    "locatorTips": "Forslag er ikke tilgjengelige fordi geokodingstjenesten ikke har støtte for forslag.",
    "layerSource": "Lagkilde",
    "setLayerSource": "Angi lagkilde",
    "setGeocoderURL": "Angi geokoder-URL",
    "searchLayerTips": "Forslag er ikke tilgjengelige, fordi geoobjektstjenesten ikke har støtte for paginering.",
    "placeholder": "Plassholdertekst",
    "searchFields": "Søkefelter",
    "displayField": "Visningsfelt",
    "exactMatch": "Nøyaktig treff",
    "maxSuggestions": "Maks. antall forslag",
    "maxResults": "Maks. antall resultater",
    "enableLocalSearch": "Aktiver lokalt søk",
    "minScale": "Minste målestokk",
    "minScaleHint": "Når kartmålestokken er større enn denne målestokken, brukes lokalt søk",
    "radius": "Radius",
    "radiusHint": "Angir radiusen for et område rundt det gjeldende midtpunktet i kartet som brukes til å styrke rangeringen til geokodingskandidater, slik at kandidater nærmest lokasjonen returneres først",
    "meters": "Meter",
    "setSearchFields": "Angi søkefelter",
    "set": "Angi",
    "fieldName": "Navn",
    "invalidUrlTip": "URL-en ${URL} er ugyldig eller ikke tilgjengelig."
  }
});