define({
  "_widgetLabel": "Análise de Incidente",
  "_featureAction_SetAsIncident": "Definir Como Incidente",
  "incident": "Incidente",
  "weather": "Meteorologia",
  "locate_incident": "Localizar Incidente",
  "clear_incidents": "Limpar Incidentes",
  "reverse_geocoded_address": "Endereço mais próximo",
  "reverse_geocoded_error": "Não disponível",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas Náuticas",
  "now": "AGORA",
  "wind": "VENTO",
  "SUN": "DOM",
  "MON": "SEG",
  "TUE": "TER",
  "WED": "QUA",
  "THU": "QUI",
  "FRI": "SEX",
  "SAT": "SÁB",
  "defaultTabMsg": "Nenhum incidente identificado.",
  "useMapExtent": "Usar a extensão de mapa actual",
  "noFeaturesFound": "Não foram encontrados nenhuns elementos.",
  "downloadCSV": "DESCARREGAR CSV",
  "sum": "SOMA",
  "min": "MÍNIMO",
  "max": "MÁXIMO",
  "avg": "MÉDIA",
  "count": "CONTAGEM",
  "area": "ÁREA",
  "length": "COMPRIMENTO"
});