define({
  "_widgetLabel": "Grafikon",
  "executeChartTip": "Kliknite na jednu od sljedećih stavki zadatka za prikaz grafikona.",
  "invalidConfig": "Nevaljana konfiguracija.",
  "noneChartTip": "Zadatak u obliku grafikona nije konfiguriran za ovaj widget.",
  "chartParams": "Opcije",
  "charts": "GRAFIKONI",
  "apply": "PRIMIJENI",
  "useSpatialFilter": "Upotrijebite prostorni filtar kako biste ograničili geoobjekte",
  "useCurrentMapExtent": "Samo geoobjekti koji se sijeku na trenutačnom području na karti",
  "drawGraphicOnMap": "Samo geoobjekti koji se sijeku na području koje je odredio korisnik",
  "chartResults": "Rezultati grafikona",
  "clearResults": "Očisti rezultate",
  "noPermissionsMsg": "Nemate dopuštenje za pristup ovoj usluzi.",
  "specifySpatialFilterMsg": "Odredite prostorni filtar za ovaj zadatak.",
  "queryError": "Neuspješan upit.",
  "noResults": "Nema geoobjekta.",
  "category": "Kategorija",
  "count": "Broj",
  "label": "Oznaka",
  "horizontalAxis": "Vodoravna os",
  "verticalAxis": "Okomita os",
  "dataLabels": "Oznake podataka",
  "color": "Boja",
  "colorful": "Raznobojno",
  "monochromatic": "Monokromatski",
  "tasks": "Zadaci",
  "results": "Rezultati",
  "applySpatialFilterToLimitResults": "Upotrijebite prostorni filtar kako biste ograničili rezultate",
  "useCurrentExtentTip": "Djelomično ili potpuno unutar trenutačnog obuhvata karte",
  "useDrawGraphicTip": "Djelomično ili potpuno unutar oblika nacrtanog na karti",
  "useFeaturesTip": "Na temelju njihovih lokacija u odnosu na geoobjekte u drugom sloju",
  "noSpatialLimitTip": "Nemoj prostorno ograničiti rezultate",
  "applySearchDistance": "Primijenite udaljenost za pretraživanje",
  "spatialRelationship": "Prostorna relacija",
  "relatedLayer": "Povezani sloj",
  "clear": "Očisti",
  "bufferDistance": "Veličina pojasa",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "back": "Natrag",
  "execute": "Primijeni"
});