define({
  "_widgetLabel": "שאילתה",
  "executeQueryTip": "לחץ על אחד מפריטי המשימה הבאים כדי לבצע את השאילתא.",
  "invalidConfig": "הגדרה לא תקינה. אנא השתמש בדף הגדרת שאילתא כדי לתקן את ההגדרה.",
  "queryParams": "אפשרויות",
  "parameters": "אפשרויות",
  "queries": "שאילתות",
  "apply": "בצע",
  "queryResults": "תוצאות",
  "clear": "נקה",
  "noResults": "לא נמצאו ישויות",
  "queryError": "השאילתא נכשלה !",
  "numberFound": "מספר הישויות שנמצאו",
  "mapExtentTip": "הגבל את התוצאות לאזור הנוכחי במפה.",
  "noValue": "אין ערך",
  "and": "וגם",
  "stringOperatorIs": "הוא",
  "stringOperatorIsNot": "אינו",
  "stringOperatorStartsWith": "מתחיל עם",
  "stringOperatorEndsWith": "מסתיים ב",
  "stringOperatorContains": "מכיל",
  "stringOperatorDoesNotContain": "לא מכיל",
  "stringOperatorIsBlank": "ריק",
  "stringOperatorIsNotBlank": "אינו ריק",
  "dateOperatorIsOn": "הוא ב-",
  "dateOperatorIsNotOn": "אינו ב-",
  "dateOperatorIsBefore": "הוא לפני",
  "dateOperatorIsAfter": "הוא אחרי",
  "dateOperatorDays": "ימים",
  "dateOperatorWeeks": "שבועות",
  "dateOperatorMonths": "חודשים",
  "dateOperatorInTheLast": "בסוף",
  "dateOperatorNotInTheLast": "לא בסוף",
  "dateOperatorIsBetween": "בין",
  "dateOperatorIsNotBetween": "לא נמצא בין",
  "dateOperatorIsBlank": "ריק",
  "dateOperatorIsNotBlank": "אינו ריק",
  "numberOperatorIs": "הוא",
  "numberOperatorIsNot": "אינו",
  "numberOperatorIsAtLeast": "הוא לפחות",
  "numberOperatorIsLessThan": "הוא פחות מ-",
  "numberOperatorIsAtMost": "הוא לכל היותר",
  "numberOperatorIsGreaterThan": "הוא גדול מ-",
  "numberOperatorIsBetween": "בין",
  "numberOperatorIsNotBetween": "לא נמצא בין",
  "numberOperatorIsBlank": "ריק",
  "numberOperatorIsNotBlank": "אינו ריק",
  "operationalLayerTip": "הוסף תוצאה כשכבה תפעולית",
  "queryResult": "תוצאת שאילתא",
  "specifyParamsTip": "הגדר פרמטרים למשימה",
  "useSpatialFilter": "השתמש בסינון מרחבי להגבלת יישויות",
  "useCurrentMapExtent": "רק יישויות החותכות את האזור הנוכחי במפה",
  "drawGraphicOnMap": "רק יישויות החותכות אזור המוגדר על-ידי המשתמש",
  "specifySpatialFilterMsg": "הגדר בבקשה סינון למשימה הזו.",
  "clearResults": "נקה תוצאות",
  "operationalTip": "כאשר האפשרות הזו מסומנת, התוצאות תוצגנה במפה עד שתלחץ על הלחצן \"${clearResults}\".",
  "noneQueryTip": "לא הוגדרה משימת שאילתא עבור וידג'ט זה.",
  "noPermissionsMsg": "אין לך הרשאות לגשת לשירות זה.",
  "attributesFromRelationship": "מאפיינים מטבלה קשורה",
  "tasks": "משימות",
  "applySpatialFilterToLimitResults": "יישם פילטר מרחבי כדי להגביל את התוצאות",
  "useCurrentExtentTip": "החזר רק ישויות בתוך תיחום המפה הנוכחי",
  "useDrawGraphicTip": "החזר רק ישויות שמצטלבות עם הצורה שצוירה על המפה",
  "useFeaturesTip": "החזר רק ישויות בעלות קישור מרחבי עם ישויות בשכבה אחרת",
  "noSpatialLimitTip": "החזר ישויות בתוך התיחום המלא של המפה",
  "applySearchDistance": "החל מרחק חיפוש",
  "spatialRelationship": "קישור מרחבי",
  "relatedLayer": "שכבה מקושרת",
  "bufferDistance": "מרחק חיץ",
  "miles": "מיילים",
  "kilometers": "קילומטרים",
  "feet": "רגל",
  "meters": "מטרים",
  "yards": "יארד",
  "nauticalMiles": "מיילים ימיים",
  "back": "אחורה",
  "execute": "בצע",
  "zoomTo": "התמקד אל",
  "openAttributeTable": "הצג בטבלת מאפיינים",
  "noResult": "אין תוצאות.",
  "noTask": "אין משימות.",
  "removeThisResult": "הסר תוצאה זו",
  "attributeCriteira": "קריטריוני מאפיין",
  "spatialFilter": "פילטר מרחבי",
  "value": "ערך",
  "noAttributeSpatialFilterTip": "לא הוגדרו פילטרים. כל הישויות יוחזרו.",
  "showAllRelatedRecords": "הצג את כל הרשומות המקושרות",
  "changeSymbol": "שנה סמל",
  "queryCriteira": "קריטריונים של שאילתא",
  "customQuery": "שאילתה מותאמת אישית",
  "layer": "שכבה",
  "createCustomQuery": "צור שאילתה מותאמת אישית."
});