define({
  "queries": "Upiti",
  "addNew": "Dodaj novi",
  "newQuery": "Novi upit",
  "queryLayer": "Sloj upita",
  "setSource": "Postavi",
  "setDataSource": "Postavi izvor podataka",
  "name": "Naziv",
  "querySource": "Izvor podataka",
  "queryName": "Ime zadatka",
  "queryDefinition": "Definicija filtera",
  "resultsSetting": "Postavke rezultata",
  "symbolSetting": "Postavke simbola",
  "resultSettingTip": "Definišite kako i koji izlazni rezultati da budu prikazani.",
  "resultItemTitle": "Naslov svake stavke rezultata",
  "resultItemContent": "Prikazaće se ovih atributi polja",
  "fieldsSetTip": "Proverite polja koja želite da prikažete. Izaberite polje za koje ćete ažurirati pseudonim, redosled i format.",
  "addField": "Dodaj polje",
  "visibility": "Vidljivost",
  "alias": "Alias",
  "specialType": "Poseban tip",
  "actions": "Radnje",
  "none": "Ništa",
  "link": "Link",
  "image": "Snimak",
  "noField": "Nema polja",
  "operationalLayerTip": "Dodaj rezultate kao operativni sloj",
  "setLayerSymbolTip": "Postavi simbol za rezultate upita: ",
  "setSelectedSymbolTip": "Postavi simbol izabranih geoobjekata.",
  "notUseFilter": "Ne koristi filter",
  "setSourceTip": "Postavite izvor upita.",
  "setFilterTip": "Pravilno postavite filter.",
  "ok": "U redu",
  "cancel": "Otkaži",
  "noFilterTip": "Bez definisanog izraza filtera, ovaj zadatak upita će izlistati sve geoobjekte u određenom izvoru podataka.",
  "relationships": "Veze",
  "addRelationshipLayer": "Dodaj novu vezu",
  "relatedTo": "Povezano sa",
  "selectOption": "Izaberite...",
  "resultItemSorting": "Sortiranje stavke rezultata",
  "field": "Polje",
  "sortingOrder": "redosled",
  "configureFieldsTip": "Konfigurišite polja prema kojima će rezultati upita biti sortirani.",
  "setSortingFields": "Postavi polja sortiranja",
  "ascending": "Rastuće",
  "descending": "Opadajuće",
  "sortBy": "Sortiraj po",
  "thenBy": "Zatim po",
  "addTask": "Dodaj zadatak",
  "noTasksTip": "Nema konfigurisanih upita. Kliknite na „${newQuery}“ da biste dodali novi.",
  "infoText": "Informacije",
  "filters": "Filteri",
  "results": "Rezultati",
  "optionsText": "Opcije",
  "summaryText": "Rezime",
  "attributeFilter": "Filter atributa",
  "attributeFilterTip": "Definišite atributne izraze za korišćenje u vidžetu da biste filtrirali sloj upita.",
  "defineWhereClause": "Definišite odredbu gde za upit.",
  "noExpressionDefinedTip": "Nema definisanih izraza. Svi zapisi će biti vraćeni.",
  "setExpressions": "Postavi izraze",
  "spatialFilter": "Prostorni filteri",
  "spatialFilterTip": "Izaberite koji će prostorni filteri biti dostupni krajnjim korisnicima.",
  "defaultOption": "Podrazumevano",
  "useCurrentExtentTip": "Vrati samo geoobjekte unutar trenutnog obuhvata mape",
  "useDrawGraphicTip": "Vrati samo geoobjekte koji se ukrštaju sa oblikom nacrtanim na mapi",
  "useFeaturesTip": "Vrati samo geoobjekte koji imaju prostornu vezu sa geoobjektima u drugom sloju",
  "noSpatialLimitTip": "Vrati geoobjekte unutar potpunog obuhvata mape",
  "drawingTools": "Izaberi alate za crtanje",
  "bufferSettings": "Omogući opciju zone bliskosti",
  "defaultDistance": "Podrazumevano rastojanje",
  "bufferDistance": "Rastojanje zone bliskosti",
  "defaultUnit": "Podrazumevana jedinica",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "availableSpatialRelationships": "Odaberite pravila prostorne veze",
  "setSpatialRelationships": "Postavi prostorne veze",
  "availability": "Dostupnost",
  "relationship": "Veza",
  "label": "Oznaka",
  "intersect": "presecanje",
  "contain": "sadrži",
  "areContainedIn": "sadržani su u",
  "cross": "ukrštanje",
  "envelopeIntersect": "presek pravougaonika",
  "overlap": "preklapanje",
  "areOverlapped": "preklapa se",
  "touch": "dodir",
  "within": "unutar",
  "areWithin": "su unutar",
  "indexIntersect": "presecanje indeksa",
  "itemTitle": "Naslov stavke",
  "displayFields": "Prikaži polja",
  "sortingFields": "Sortiraj stavke rezultata",
  "setDisplayFields": "Postavi prikaz polja",
  "symbol": "Simbol",
  "setSymbol": "Koristi prilagođeni simbol",
  "changeSymbolAtRuntime": "Dozvoli menjanje simbola pri pokretanju",
  "serviceSymbolTip": "Koristi simbole definisane slojem",
  "exportTip": "Dozvoli izvoz rezultata",
  "keepResultsTip": "Ostavi rezultate na mapi nakon što se vidžet zatvori",
  "queryRelatedRecords": "Izvršite upit nad povezanim podacima",
  "createLayerForTaskTip": "Navedite kako zadatak upita kreira slojeve",
  "oneLayerForTaskTip": "Piši preko sloja svaki put kada se upit vrši",
  "multipleLayerForTaskTip": "Kreiraj novi sloj svaki put kada se upit vrši",
  "makeDefault": "Napravi podrazumevanim",
  "icon": "Ikona",
  "newTask": "Novi zadatak",
  "addTaskTip": "Dodajte vidžetu jedan ili više upita i konfigurišite parametre za svaki od njih.",
  "webMapPopupTip": "Koristi konfiguraciju iskačućih prozora sloja u veb mapi",
  "customPopupTip": "Konfiguriši prilagođeni sadržaj",
  "showResultsSetActions": "Prikaži radnje za skup rezultata",
  "zoomTo": "Zumiraj na",
  "openAttributeTable": "Prikaži u tabeli atributa",
  "content": "Sadržaj",
  "displaySQLTip": "Prikaži SQL izraz za krajnje korisnike",
  "useLayerDefaultSymbol": "Koristi podrazumevani simbol sloja",
  "setCustomIcon": "Podesi prilagođenu ikonu",
  "layerDefaultSymbolTip": "Koristi podrazumevani simbol sloja",
  "uploadImage": "Otpremi snimak",
  "attributeCriteira": "Kriterijumi atributa",
  "specifyFilterAtRuntimeTip": "Korisnici će trebati da navedu parametre za ovaj izraz.",
  "value": "VREDNOST",
  "hideLayersTip": "Isključite slojeve sa rezultatima upita kada je vidžet zatvoren.",
  "tabLabels": "Oznake kartice",
  "tasks": "Zadaci",
  "queryCriteira": "Kriterijum upita",
  "allowCustomQuery": "Dozvoli kreiranje prilagođenog upita"
});