define({
  "queries": "Truy vấn",
  "addNew": "Thêm mới",
  "newQuery": "Truy vấn mới",
  "queryLayer": "Lớp truy vấn",
  "setSource": "Thiết lập",
  "setDataSource": "Thiết lập nguồn Dữ liệu",
  "name": "Tên",
  "querySource": "Nguồn dữ liệu",
  "queryName": "Tên tác vụ",
  "queryDefinition": "Định nghĩa bộ lọc",
  "resultsSetting": "Thiết lập kết quả",
  "symbolSetting": "Thiết lập ký hiệu",
  "resultSettingTip": "Xác định nội dung và cách thức hiển thị kết quả đầu ra.",
  "resultItemTitle": "Tiêu đề của từng mục kết quả",
  "resultItemContent": "Các thuộc tính của trường này sẽ hiển thị",
  "fieldsSetTip": "Chọn các trường mà bạn muốn hiển thị. Chọn một trường để cập nhật bí danh, thứ tự và định dạng của trường đó.",
  "addField": "Thêm trường",
  "visibility": "Khả năng hiển thị",
  "alias": "Bí danh",
  "specialType": "Loại đặc biệt",
  "actions": "Các hành động",
  "none": "Không có",
  "link": "Liên kết",
  "image": "Hình ảnh",
  "noField": "Không có trường nào",
  "operationalLayerTip": "Thêm kết quả như lớp hoạt động",
  "setLayerSymbolTip": "Thiết lập ký hiệu cho kết quả truy vấn: ",
  "setSelectedSymbolTip": "Thiết lập ký hiệu của đối tượng được chọn.",
  "notUseFilter": "Không sử dụng bộ lọc",
  "setSourceTip": "Vui lòng thiết lập nguồn truy vấn.",
  "setFilterTip": "Vui lòng thiết lập bộ lọc chính xác.",
  "ok": "OK",
  "cancel": "Hủy",
  "noFilterTip": "Nếu biểu thức bộ lọc không được xác định, tác vụ truy vấn này sẽ liệt kê tất cả các đối tượng trong nguồn dữ liệu đã chỉ định.",
  "relationships": "Mối quan hệ",
  "addRelationshipLayer": "Thêm mối quan hệ mới",
  "relatedTo": "Liên quan đến",
  "selectOption": "Vui lòng chọn..",
  "resultItemSorting": "Sắp xếp mục kết quả",
  "field": "Trường",
  "sortingOrder": "Thứ tự",
  "configureFieldsTip": "Vui lòng cấu hình các trường dùng để sắp xếp truy vấn.",
  "setSortingFields": "Thiết lập trường sắp xếp",
  "ascending": "Tăng dần",
  "descending": "Giảm dần",
  "sortBy": "Sắp xếp theo",
  "thenBy": "Sau đó theo",
  "addTask": "Thêm tác vụ",
  "noTasksTip": "Không có truy vấn được cấu hình. Nhấp vào \"${newQuery}\" để thêm một truy vấn mới.",
  "infoText": "Thông tin",
  "filters": "Bộ lọc",
  "results": "Kết quả",
  "optionsText": "Tùy chọn",
  "summaryText": "Tóm tắt",
  "attributeFilter": "Bộ lọc thuộc tính",
  "attributeFilterTip": "Xác định biểu thức thuộc tính sử dụng trong tiện ích để lọc lớp truy vấn.",
  "defineWhereClause": "Xác định mệnh đề where cho truy vấn.",
  "noExpressionDefinedTip": "Không có biểu thức nào được xác định. Tất cả bản ghi sẽ được trả về.",
  "setExpressions": "Thiết lập biểu thức",
  "spatialFilter": "Bộ lọc không gian",
  "spatialFilterTip": "Chọn bộ lọc không gian sẽ sẵn có cho người dùng cuối.",
  "defaultOption": "Mặc định",
  "useCurrentExtentTip": "Chỉ trả về đối tượng trong phạm vi bản đồ hiện tại",
  "useDrawGraphicTip": "Chỉ trả về các đối tượng giao cắt với hình dạng đã được vẽ trên bản đồ",
  "useFeaturesTip": "Chỉ trả về đối tượng có mối quan hệ về không gian với đối tượng trong lớp khác",
  "noSpatialLimitTip": "Trả về đối tượng trong phạm vi đầy đủ của bản đồ",
  "drawingTools": "Chọn công cụ vẽ",
  "bufferSettings": "Bật tùy chọn vùng đệm",
  "defaultDistance": "Khoảng cách mặc định",
  "bufferDistance": "Khoảng cách vùng đệm",
  "defaultUnit": "Đơn vị mặc định",
  "miles": "Dặm",
  "kilometers": "Kilômét",
  "feet": "Feet",
  "meters": "Mét",
  "yards": "Thước",
  "nauticalMiles": "Hải lý",
  "availableSpatialRelationships": "Chọn quy tắc mối quan hệ không gian",
  "setSpatialRelationships": "Thiết lập mối quan hệ không gian",
  "availability": "Mức độ khả dụng",
  "relationship": "Mối quan hệ",
  "label": "Nhãn",
  "intersect": "giao cắt",
  "contain": "bao gồm",
  "areContainedIn": "được bao gồm trong",
  "cross": "gạch ngang",
  "envelopeIntersect": "đường bao giao cắt",
  "overlap": "xếp chồng",
  "areOverlapped": "bị xếp chồng",
  "touch": "chạm",
  "within": "bên trong",
  "areWithin": "ở bên trong",
  "indexIntersect": "chỉ số giao cắt",
  "itemTitle": "Tiêu đề mục",
  "displayFields": "Hiển thị trường",
  "sortingFields": "Phân loại các mục kết quả",
  "setDisplayFields": "Thiết lập hiển thị trường",
  "symbol": "Ký hiệu",
  "setSymbol": "Sử dụng ký hiệu tùy chỉnh",
  "changeSymbolAtRuntime": "Cho phép thay đổi ký hiệu khi đang thực hiện",
  "serviceSymbolTip": "Sử dụng các ký hiệu do lớp xác định",
  "exportTip": "Cho phép xuất kết quả",
  "keepResultsTip": "Lưu kết quả trên bản đồ sau khi đóng tiện ích",
  "queryRelatedRecords": "Bản ghi liên quan đến truy vấn",
  "createLayerForTaskTip": "Chỉ định cách tác vụ truy vấn tạo lớp",
  "oneLayerForTaskTip": "Ghi đè lớp mỗi lần thực hiện truy vấn",
  "multipleLayerForTaskTip": "Tạo lớp mới mỗi lần thực hiện truy vấn",
  "makeDefault": "Đặt làm mặc định",
  "icon": "Biểu tượng",
  "newTask": "Tác vụ mới",
  "addTaskTip": "Thêm một hoặc nhiều quy vấn vào tiện ích và cấu hình các thông số cho mỗi quy vấn.",
  "webMapPopupTip": "Sử dụng cấu hình pop-up của lớp trong bản đồ web",
  "customPopupTip": "Định cấu hình nội dung tùy chỉnh",
  "showResultsSetActions": "Hiện các tác vụ cho kết quả đã đặt",
  "zoomTo": "Phóng tới",
  "openAttributeTable": "Xem trong Bảng Thuộc tính",
  "content": "Nội dung",
  "displaySQLTip": "Hiển thị biểu thức SQL cho người dùng cuối",
  "useLayerDefaultSymbol": "Sử dụng ký hiệu mặc định của lớp",
  "setCustomIcon": "Đặt ký hiệu tùy chỉnh",
  "layerDefaultSymbolTip": "Sử dụng ký hiệu mặc định của lớp",
  "uploadImage": "Tải ảnh lên",
  "attributeCriteira": "Tiêu chí thuộc tính",
  "specifyFilterAtRuntimeTip": "Người dùng sẽ phải chỉ định tham số cho biểu thức này.",
  "value": "GIÁ TRỊ",
  "hideLayersTip": "Tắt lớp kết quả truy vấn khi tiện ích bị đóng.",
  "tabLabels": "Nhãn tab",
  "tasks": "Tác vụ",
  "queryCriteira": "Tiêu chuẩn truy vấn",
  "allowCustomQuery": "Cho phép tạo truy vấn tùy chỉnh"
});