define({
  "add": "Yeni eklemek için tıkla",
  "title": "Başlık",
  "placeholderBookmarkName": "Yer işareti adı",
  "ok": "Tamam",
  "cancel": "İptal",
  "warning": "Düzenlemeyi tamamlayın!",
  "edit": "Yer işaretlerini düzenle",
  "errorNameExist": "Yer işareti mevcut!",
  "errorNameNull": "Geçersiz yer işareti adı!",
  "addBookmark": "Yeni oluştur",
  "thumbnail": "Küçük Resim",
  "thumbnailHint": "Güncellemek için resme tıkla",
  "displayBookmarksAs": "Yer imlerini farklı göster",
  "cards": "Kartlar",
  "list": "Liste",
  "cardsTips": "Kart görünümü",
  "listTips": "Liste görünümü",
  "makeAsDefault": "Varsayılan yap",
  "default": "Varsayılan",
  "editable": "Araca yer imi eklemeye izin ver.",
  "alwaysSync": "Web haritasından yer imleri göster",
  "configCustom": "Özel yer imlerini göster",
  "import": "İçe aktar",
  "create": "Oluştur",
  "importTitle": "Yer imlerini içeri aktar",
  "importFromWeb": "Mevcut web haritasından yer imlerini içeri aktar",
  "selectAll": "Tümünü Seç",
  "noBookmarkInConfig": "Yer imleri eklemek için 'İçeri Aktar' veya 'Oluştur' öğesini tıklat.",
  "noBookmarkInWebMap": "Haritada yer imi yapılandırılmadı.",
  "extent": "Yayılım",
  "saveExtent": "Harita uzantısını bu yer imine kaydet",
  "savelayers": "Katman görünürlüğünü kaydet",
  "withVisibility": "Katman görünürlüğüyle",
  "bookmark": "Yer İşareti",
  "addBtn": "Ekle",
  "deleteBtn": "Sil",
  "editBtn": "Düzenle",
  "dragReorderTip": "Yeniden düzenlemek için sürükle ve bırak",
  "deleteBtnTip": "Yer imini sil",
  "editBtnTip": "Yer imini düzenle"
});