define({
  "_widgetLabel": "Μετατροπή συντεταγμένων",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Βαθμοί σε δεκαδική μορφή - Γεωγραφικό πλάτος/μήκος",
  "DDLongLatNotation": "Βαθμοί σε δεκαδική μορφή - Γεωγραφικό μήκος/πλάτος",
  "DDMLatLongNotation": "Βαθμοί με λεπτά σε δεκαδική μορφή - Γεωγραφικό πλάτος/μήκος",
  "DDMLongLatNotation": "Βαθμοί με λεπτά σε δεκαδική μορφή - Γεωγραφικό μήκος/πλάτος",
  "DMSLatLongNotation": "Βαθμοί με λεπτά και δευτερόλεπτα - Γεωγραφικό πλάτος/μήκος",
  "DMSLongLatNotation": "Βαθμοί με λεπτά και δευτερόλεπτα - Γεωγραφικό μήκος/πλάτος",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Γράμμα ζώνης",
  "UTMHemNotation": "UTM - Ημισφαίριο (Β/Ν)",
  "formatInput": "Μορφοποίηση εισόδου",
  "copyAll": "Αντιγραφή όλων",
  "copySuccessful": "Επιτυχημένη αντιγραφή",
  "copyFailed": "Δεν είναι δυνατή η αντιγραφή. Χρησιμοποιήστε εναλλακτικά τα πλήκτρα ctrl+c.",
  "parseCoordinatesError": "Δεν είναι δυνατή η ανάλυση των συντεταγμένων. Ελέγξτε την είσοδό σας.",
  "comfirmInputNotation": "Επιβεβαίωση σημειογραφίας εισόδου",
  "latLongWarningMessage": "Προσδιορίστηκε ότι η συντεταγμένη εισόδου έχει και πρόθεμα και επίθημα για την τιμή γεωγραφικού πλάτους ή γεωγραφικού μήκους. Η συντεταγμένη που επιστρέφεται βασίζεται στο πρόθεμα.",
  "inputLabel": "Είσοδος",
  "outputLabel": "Έξοδος",
  "cancelButtonLabel": "Ακύρωση",
  "applyButtonLabel": "Εφαρμογή",
  "posNegPrefixLabel": "Προσθήκη προθέματος \"+/-\" σε θετικούς και αρνητικούς αριθμούς",
  "editCoordinateDialogTitle": "Ορισμός συμβολοσειράς μορφής συντεταγμένης",
  "rememberDecisionLabel": "Απομνημόνευση της απόφασής μου και να μην ξαναγίνει ερώτηση.<br/>",
  "coordinateInputLabel": "Εισαγωγή συντεταγμένων ή κλικ σε χάρτη",
  "zoomLabel": "Εστίαση",
  "multipleNotationLabel": "σημειογραφίες βρέθηκαν που ταιριάζουν με την είσοδό σας. Επιβεβαιώστε αυτήν που θέλετε να χρησιμοποιήσετε:",
  "copyToClipboard": "Αντιγραφή στο Πρόχειρο",
  "formatOutput": "Μορφή εξόδου",
  "addNewNotation": "Προσθήκη νέας σημειογραφίας",
  "notationAddedMessage": "Προστέθηκε νέα σημειογραφία",
  "addLabel": "Προσθήκη",
  "removeCoordinate": "Κατάργηση συντεταγμένης",
  "expandOutput": "Ανάπτυξη εξόδου",
  "latitudeLabel": "Γεωγραφικό πλάτος",
  "longitudeLabel": "Γεωγραφικό μήκος",
  "quadrantLabel": "Τεταρτημόριο",
  "keyLabel": "Κλειδί",
  "fifteenDegreeLabel": "Τεταρτημόριο 15Â°",
  "oneDegreeLabel": "Τεταρτημόριο 1Â°",
  "eastingLabel": "Οριζόντια συντεταγμένη",
  "northingLabel": "Κατακόρυφη συντεταγμένη",
  "zoneLabel": "Ζώνη",
  "bandLabel": "Ζώνη",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Τετράγωνο καννάβου",
  "hemisphereLabel": "Ημισφαίριο"
});