define({
  "add": "Kliknite da biste dodali novo",
  "title": "Naslov",
  "placeholderBookmarkName": "Ime obeleživača",
  "ok": "U redu",
  "cancel": "Otkaži",
  "warning": "Završite izmene!",
  "edit": "Izmeni obeleživač",
  "errorNameExist": "Obeleživač postoji!",
  "errorNameNull": "Nevažeće ime obeleživača!",
  "addBookmark": "Kreiraj novo",
  "thumbnail": "Sličica",
  "thumbnailHint": "Kliknite na snimak da biste ažurirali",
  "displayBookmarksAs": "Prikaži obeleživače kao",
  "cards": "Kartice",
  "list": "Lista",
  "cardsTips": "Prikaz u vidu kartice",
  "listTips": "Prikaz u vidu liste",
  "makeAsDefault": "Napravi podrazumevanim",
  "default": "Podrazumevano",
  "editable": "Dozvolite dodavanje obeleživača u vidžetu.",
  "alwaysSync": "Prikaži obeleživače iz veb mape",
  "configCustom": "Prikaži prilagođene obeleživače",
  "import": "Uvezi",
  "create": "Kreiraj",
  "importTitle": "Uvezi obeleživače",
  "importFromWeb": "Uvezu obeleživače iz trenutne veb mape",
  "selectAll": "Selektuj sve",
  "noBookmarkInConfig": "Kliknite na „Uvezi“ ili „Kreiraj novi“ da dodate obeleživače.",
  "noBookmarkInWebMap": "U mapi nije konfigurisan nijedan obeleživač.",
  "extent": "Obuhvat",
  "saveExtent": "Sačuvaj obuhvat mape u ovom obeleživaču",
  "savelayers": "Sačuvaj vidljivost sloja",
  "withVisibility": "Sa vidljivošću sloja",
  "bookmark": "Obeleživač",
  "addBtn": "Dodaj",
  "deleteBtn": "Izbriši",
  "editBtn": "Izmeni",
  "dragReorderTip": "Zadržite i prevucite radi preuređivanja",
  "deleteBtnTip": "Obriši obeleživač",
  "editBtnTip": "Izmeni obeleživač"
});