define({
  "_widgetLabel": "Abfrage",
  "executeQueryTip": "Klicken Sie auf einen der folgenden Tasks, um die Abfrage auszuführen.",
  "invalidConfig": "Ungültige Konfiguration. Verwenden Sie die Seite für Abfrageeinstellungen, um die richtige Konfiguration abzurufen.",
  "queryParams": "Optionen",
  "parameters": "OPTIONEN",
  "queries": "ABFRAGEN",
  "apply": "Übernehmen",
  "queryResults": "Ergebnisse",
  "clear": "Löschen",
  "noResults": "Kein Feature gefunden.",
  "queryError": "Abfrage fehlgeschlagen!",
  "numberFound": "Anzahl der gefundenen Features",
  "mapExtentTip": "Beschränken Sie die Ergebnisse auf den aktuellen Kartenbereich.",
  "noValue": "Kein Wert",
  "and": "und",
  "stringOperatorIs": "ist",
  "stringOperatorIsNot": "ist nicht",
  "stringOperatorStartsWith": "beginnt mit",
  "stringOperatorEndsWith": "endet mit",
  "stringOperatorContains": "enthält",
  "stringOperatorDoesNotContain": "enthält nicht",
  "stringOperatorIsBlank": "ist leer",
  "stringOperatorIsNotBlank": "ist nicht leer",
  "dateOperatorIsOn": "ist am",
  "dateOperatorIsNotOn": "ist nicht am",
  "dateOperatorIsBefore": "ist vor",
  "dateOperatorIsAfter": "ist nach",
  "dateOperatorDays": "Tagen",
  "dateOperatorWeeks": "Wochen",
  "dateOperatorMonths": "Monate",
  "dateOperatorInTheLast": "in den letzten",
  "dateOperatorNotInTheLast": "nicht in den letzten",
  "dateOperatorIsBetween": "liegt zwischen",
  "dateOperatorIsNotBetween": "liegt nicht zwischen",
  "dateOperatorIsBlank": "ist leer",
  "dateOperatorIsNotBlank": "ist nicht leer",
  "numberOperatorIs": "ist",
  "numberOperatorIsNot": "ist nicht",
  "numberOperatorIsAtLeast": "ist mindestens",
  "numberOperatorIsLessThan": "ist kleiner als",
  "numberOperatorIsAtMost": "ist höchstens",
  "numberOperatorIsGreaterThan": "ist größer als",
  "numberOperatorIsBetween": "liegt zwischen",
  "numberOperatorIsNotBetween": "liegt nicht zwischen",
  "numberOperatorIsBlank": "ist leer",
  "numberOperatorIsNotBlank": "ist nicht leer",
  "operationalLayerTip": "Ergebnis als operationalen Layer hinzufügen",
  "queryResult": "Abfrageergebnis",
  "specifyParamsTip": "Parameter für diesen Task festlegen",
  "useSpatialFilter": "Räumlichen Filter zum Begrenzen von Features verwenden",
  "useCurrentMapExtent": "Nur Features, die den aktuellen Kartenbereich schneiden",
  "drawGraphicOnMap": "Nur Features, die den benutzerdefinierten Bereich schneiden",
  "specifySpatialFilterMsg": "Geben Sie einen räumlichen Filter für diesen Task an.",
  "clearResults": "Ergebnisse löschen",
  "operationalTip": "Wenn diese Option aktiviert ist, werden die Ergebnisse auf der Karte beibehalten, bis auf die Schaltfläche \"${clearResults}\" geklickt wird.",
  "noneQueryTip": "Für dieses Widget wurde kein Abfrage-Task konfiguriert.",
  "noPermissionsMsg": "Sie verfügen nicht über die entsprechenden Berechtigungen für den Zugriff auf diesen Service.",
  "attributesFromRelationship": "Attribute aus zugehöriger Tabelle",
  "tasks": "Tasks",
  "applySpatialFilterToLimitResults": "Zum Eingrenzen der Ergebnisse einen räumlichen Filter anwenden",
  "useCurrentExtentTip": "Nur Features in der aktuellen Kartenausdehnung zurückgeben",
  "useDrawGraphicTip": "Nur Features zurückgeben, die die auf der Karte gezeichnete Form schneiden",
  "useFeaturesTip": "Nur Features zurückgeben, die eine räumliche Beziehung mit Features in einem anderen Layer aufweisen",
  "noSpatialLimitTip": "Features in der vollen Ausdehnung der Karte zurückgeben",
  "applySearchDistance": "Eine Suchentfernung anwenden",
  "spatialRelationship": "Räumliche Beziehung",
  "relatedLayer": "Zugehöriger Layer",
  "bufferDistance": "Pufferabstand",
  "miles": "Meilen",
  "kilometers": "Kilometer",
  "feet": "Fuß",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Seemeilen",
  "back": "Zurück",
  "execute": "Ausführen",
  "zoomTo": "Zoomen auf",
  "openAttributeTable": "In Attributtabelle anzeigen",
  "noResult": "Kein Ergebnis.",
  "noTask": "Kein Task.",
  "removeThisResult": "Dieses Ergebnis entfernen",
  "attributeCriteira": "Attributkriterien",
  "spatialFilter": "Räumlicher Filter",
  "value": "WERT",
  "noAttributeSpatialFilterTip": "Keine Filter definiert. Alle Features werden zurückgegeben.",
  "showAllRelatedRecords": "Alle zugehörigen Datensätze anzeigen",
  "changeSymbol": "Symbol ändern",
  "queryCriteira": "Abfragekriterien",
  "customQuery": "Benutzerdefinierte Abfrage",
  "layer": "Layer",
  "createCustomQuery": "Benutzerdefinierte Abfrage erstellen."
});