define({
  "_widgetLabel": "Dòng suối",
  "streamControls": "Điều khiển phân luồng",
  "streamFilter": "Lọc",
  "startStreaming": "Bắt đầu phân luồng",
  "stopStreaming": "Dừng phân luồng",
  "streamLayers": "Các lớp phân luồng",
  "startStopStream": "Bật tùy chọn Dừng phân luồng hoặc Bắt đầu phân luồng",
  "clearStream": "Bật tùy chọn Xóa các quan sát trước đó",
  "attributeFilter": "Bật bộ lọc thuộc tính",
  "spatialFilter": "Bật bộ lọc không gian",
  "configFilter": "Cấu hình bộ lọc thuộc tính phân luồng",
  "drawPrevious": "Bật tùy chọn Vẽ các quan sát trước đó",
  "addNew": "Thêm bộ lọc",
  "setFilterName": "Thiết lập tên bộ lọc",
  "filterNameExists": "Tên bộ lọc đã tồn tại trên bảng!",
  "invalidFilterName": "Tên phải là từ có chứa các ký tự a-z, A-Z, 0-9 hoặc _.",
  "noFilterTip": "Không có bộ lọc được cấu hình",
  "addFilterFailed": "Không thể thêm bộ lọc",
  "filterName": "Tên bộ lọc",
  "limitMapExtent": "Giới hạn quan sát trong khu vực bản đồ hiện tại",
  "limitDrawExtent": "Giới hạn quan sát trong khu vực bản đồ do người dùng xác định",
  "newFilter": "Bộ lọc mới",
  "filterReadOnly": "Bộ lọc được kế thừa từ bản đồ web có dạng chỉ đọc."
});