define({
  "add": "Klik for at tilføje ny",
  "title": "Titel",
  "placeholderBookmarkName": "Bogmærkenavn",
  "ok": "OK",
  "cancel": "Annuller",
  "warning": "Færdiggør redigeringen!",
  "edit": "Rediger bogmærke",
  "errorNameExist": "Bogmærket findes!",
  "errorNameNull": "Ugyldigt bogmærkenavn!",
  "addBookmark": "Opret ny",
  "thumbnail": "Miniature",
  "thumbnailHint": "Klik på billedet for at opdatere",
  "displayBookmarksAs": "Vis bogmærker som",
  "cards": "Kort",
  "list": "Liste",
  "cardsTips": "Kortvisning",
  "listTips": "Listevisning",
  "makeAsDefault": "Gør som standard",
  "default": "Standard",
  "editable": "Tillad tilføjelse af bogmærker i widget'en.",
  "alwaysSync": "Vis bogmærker fra webkortet",
  "configCustom": "Vis brugerdefinerede bogmærker",
  "import": "Importér",
  "create": "Opret",
  "importTitle": "Importér bogmærker",
  "importFromWeb": "Importér bogmærker fra det aktuelle webkort",
  "selectAll": "Vælg alle",
  "noBookmarkInConfig": "Klik på Importér eller Opret nyt for at tilføje bogmærker.",
  "noBookmarkInWebMap": "Der er ikke konfigureret noget bogmærke i kortet.",
  "extent": "Udstrækning",
  "saveExtent": "Gem kortudstrækning til dette bogmærke",
  "savelayers": "Gem lagsynlighed",
  "withVisibility": "Med lagsynlighed",
  "bookmark": "Bogmærke",
  "addBtn": "Tilføj",
  "deleteBtn": "Slet",
  "editBtn": "Redigér",
  "dragReorderTip": "Hold og træk for at ændre rækkefølge",
  "deleteBtnTip": "Slet bogmærket",
  "editBtnTip": "Redigér bogmærket"
});