define({
  "routeUrl": "URL da Rota",
  "locatorUrl": "URL do Geocodificador",
  "geocoderOptions": "Opções do geocodificador",
  "autoComplete": "Auto Completar",
  "maximumSuggestions": "Máximo de sugestões",
  "minCharacters": "Mínimo de caracteres",
  "searchDelay": "Atraso de pesquisa",
  "placeholder": "Espaço Reservado",
  "routeOptions": "Opções da rota",
  "directionsLanguage": "Idioma das direções",
  "directionsLengthUnits": "Unidades de comprimento das direções",
  "directionsOutputType": "Tipo de saída das direções",
  "impedanceAttribute": "Atributo de impedância",
  "kilometers": "Quilômetros",
  "miles": "Milhas",
  "meters": "Metros",
  "feet": "Pés",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "parametersTip": "Configure parâmetros corretamente !",
  "complete": "Completo",
  "completeNoEvents": "Completar Sem Eventos",
  "instructionsOnly": "Instruções somente",
  "standard": "Padrão",
  "summaryOnly": "Resumo somente",
  "travelModesUrl": "URL de modos de viagem",
  "searchPlaceholder": "Encontrar endereço ou lugar",
  "trafficLayerUrl": "URL da camada de tráfego",
  "presetDestinations": "Paradas pré definidas",
  "startPoint": "Ponto Inicial",
  "endPoint": "Ponto Final",
  "destinationHolder": "Endereço ou coordenadas",
  "optional": "Opcional."
});