define({
  "_widgetLabel": "Koordinaatide teisendamine",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Kümnendkraadid – laiuskraad/pikkuskraad",
  "DDLongLatNotation": "Kümnendkraadid  – pikkuskraad/laiuskraad",
  "DDMLatLongNotation": "Kraadid-kümnendminutid – laiuskraad/pikkuskraad",
  "DDMLongLatNotation": "Kraadid-kümnendminutid – pikkuskraad/laiuskraad",
  "DMSLatLongNotation": "Kraadid-kümnendsekundid – laiuskraad/pikkuskraad",
  "DMSLongLatNotation": "Kraadid-kümnendsekundid – pikkuskraad/laiuskraad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – vahemiku täht",
  "UTMHemNotation": "UTM – poolkera (N/S)",
  "formatInput": "Vormingu sisestus",
  "copyAll": "Kopeeri kõik",
  "copySuccessful": "Kopeerimine õnnestus",
  "copyFailed": "Ei saa kopeerida. Kasutage alternatiivina ctrl+c.",
  "parseCoordinatesError": "Ei saa koordinaate sõeluda. Kontrollige sisendit.",
  "comfirmInputNotation": "Kinnita sisestatud tähistus",
  "latLongWarningMessage": "Sisestatud koordinaadil tuvastati laiuskraadi ja pikkuskraadi väärtuse puhul nii eesliide kui ka sufiks, tagastatud koordinaat põhineb eesliitel.",
  "inputLabel": "Sisend",
  "outputLabel": "Väljund",
  "cancelButtonLabel": "Loobu",
  "applyButtonLabel": "Rakenda",
  "posNegPrefixLabel": "Lisa positiivsetele ja negatiivsetele arvudele eesliide „+/-”",
  "editCoordinateDialogTitle": "Määra koordinaatide vormingu string",
  "rememberDecisionLabel": "Jäta mu otsus meelde ja ära küsi seda enam uuesti.<br/>",
  "coordinateInputLabel": "Sisestage koordinaadid või klõpsake kaardil",
  "zoomLabel": "Suumi",
  "multipleNotationLabel": "leitud tähistust vastab teie sisendile. Kinnitage, millist soovite kasutada:",
  "copyToClipboard": "Kopeeri lõikelauale",
  "formatOutput": "Vormingu väljund",
  "addNewNotation": "Lisa uus tähistus",
  "notationAddedMessage": "Lisatud on uus tähistus",
  "addLabel": "Lisa",
  "removeCoordinate": "Eemalda koordinaat",
  "expandOutput": "Laienda väljund",
  "latitudeLabel": "Laius",
  "longitudeLabel": "Pikkus",
  "quadrantLabel": "Kvadrant",
  "keyLabel": "Võti",
  "fifteenDegreeLabel": "15Â° kvadrant",
  "oneDegreeLabel": "1Â° kvadrant",
  "eastingLabel": "X-koordinaat",
  "northingLabel": "Y-koordinaat",
  "zoneLabel": "Tsoon",
  "bandLabel": "Sagedusriba",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Võrgustiku ruut",
  "hemisphereLabel": "Poolkera"
});