define({
  "_widgetLabel": "Modellatore di idoneità",
  "general": {
    "clear": "Cancella",
    "cancel": "Annulla",
    "save": "Esegui",
    "saveAs": "Esporta"
  },
  "saveModel": {
    "save": "Esporta",
    "title": "Titolo: ",
    "summary": "Riepilogo: ",
    "description": "Descrizione: ",
    "tags": "Tag: ",
    "folder": "Cartella: ",
    "homeFolderPattern": "{username} (Home)",
    "failed": "Esportazione non riuscita."
  },
  "util": {
    "colorRamp": {
      "1": "Estremamente basso",
      "2": "Molto basso",
      "3": "Basso",
      "4": "Medio basso",
      "5": "Medio",
      "6": "Medio alto",
      "7": "Alto",
      "8": "Molto alto",
      "9": "Estremamente alto",
      "low": "Basso",
      "high": "Alto",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Inverti"
    }
  },
  "wro": {
    "caption": "Modellatore di idoneità",
    "browsePrompt": "Servizio overlay pesato",
    "selectLayersCaption": "Seleziona layer",
    "selectLayers": "Livelli",
    "designModelCaption": "Modalità design",
    "designModel": "Modalità design",
    "transparency": "Trasparenza",
    "visible": "Visibile",
    "total": "Totale",
    "unableToLoad": "Impossibile caricare modello.",
    "projectNotOpen": "Un progetto non è aperto.",
    "readMore": "Ulteriori informazioni",
    "validation": {
      "validating": "Convalida in corso...",
      "invalidItemCaption": "Avviso servizio overlay pesato",
      "notAnImageService": "Questo elemento non è un image service.",
      "notAWroService": "Questo elemento non è un servizio overlay pesato.",
      "undefinedUrl": "L'URL di questo elemento non è definito.",
      "inaccessible": "Il servizio non è accessibile.",
      "generalError": "Impossibile aprire l'elemento.",
      "missingFieldPattern": "{field} è un campo obbligatorio",
      "notAllowRasterFunction": "allowRasterFunction deve essere impostata su true",
      "notNearestResampling": "defaultResamplingMethod deve essere Più vicino",
      "notIsWeightedOverlayProp": "La proprietà chiave IsWeightedOverlay deve essere impostata su true",
      "invalidLink": "URL non valido. Impossibile aprire il sito per il layer selezionato.",
      "unexpectedError": "Si è verificato uno stato imprevisto.",
      "rangeMessage": "Il valore deve essere compreso tra ${0} e ${1}",
      "rangeMessage100": "Il valore deve essere compreso tra 0 e 100",
      "maxLayers": "Consentiti massimo ${0} layer dal servizio. Rimuovere innanzitutto un layer prima di aggiungerne uno nuovo.",
      "notFound": "Layer ${0} non trovato nel servizio overlay pesato",
      "wroServiceNotDefined": "Nessun servizio overlay pesato definito per il modello.",
      "overlayLayerOutputInvalid": "Valore di output intervalli di rimappatura [${1}] del layer di sovrapposizione [${0}] mancante o non valido",
      "overlayLayerInputInvalid": "Min/max input intervalli di rimappatura [${1}] del layer di sovrapposizione [${0}] mancante o non valido",
      "overlayLayerRangesMissing": "Intervalli rimappatura layer di sovrapposizione [${0}] mancanti",
      "overlayLayerWeight": "Pesi layer di sovrapposizione devono sommare a 100",
      "overlayLayerRequired": "Specificare almeno un layer di sovrapposizione",
      "overlayLayerNotDefined": "Layer di sovrapposizione non definiti",
      "requiresColormap": "Questa funzione raster richiede una colormap, ma il non modello dispone di una definizione colormap valida",
      "createModelError": "Errore durante la creazione del modello",
      "invalidModel": "Modello non valido",
      "imageServiceNotDefined": "Layer image service non definito",
      "imageLayerNotDefined": "Layer image service non definito",
      "histogramNotDefined": "Nessuna funzione istogramma overlay pesato definita."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Verde giallo rosso",
      "Red Yellow Green": "Rosso giallo verde",
      "Yellow to Dark Red": "Da giallo a rosso scuro",
      "Dark Red to Yellow": "Da rosso scuro a giallo",
      "Light Gray to Dark Gray": "Da grigio chiaro a grigio scuro",
      "Dark Gray to Light Gray": "Da grigio scuro a grigio chiaro",
      "Light Brown to Dark Brown": "Da marrone chiaro a marrone scuro",
      "Dark Brown to Light Brown": "Da marrone scuro a marrone chiaro",
      "Full Spectrum - Bright Red to Blue": "Spettro completo - Da rosso brillante a blu",
      "Full Spectrum - Bright Blue to Red": "Spettro completo - Da blu brillante a rosso",
      "Partial Spectrum - Yellow to Blue": "Spettro parziale -Da giallo a blu",
      "Partial Spectrum - Blue to Yellow": "Spettro parziale -Da blu a giallo",
      "Yellow-Green to Dark Blue": "Giallo-Da verde a blu scuro",
      "Dark Blue to Yellow-Green": "Da blu scuro a giallo-verde",
      "Cold to Hot Diverging": "Divergente da freddo a caldo",
      "Hot to Cold Diverging": "Divergente da caldo a freddo",
      "Surface - Low to High": "Superficie - Da bassa ad alta",
      "Surface - High to Low": "Superficie - Da alta a bassa"
    }
  },
  "tabs": {
    "layers": "Layer",
    "model": "Modello",
    "chart": "Grafico"
  },
  "chart": {
    "prompt": "Feature",
    "working": "Aggiornamento in corso...",
    "polygonTool": "Disegna un poligono",
    "freehandPolygonTool": "Disegna poligono a mano libera",
    "selectTool": "Seleziona da layer",
    "panTool": "Pan",
    "clearButton": "Cancella",
    "noModelLayer": "Nessun modello",
    "noSubjectLayers": "La mappa non dispone di layer poligonali.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});