define({
  "_widgetLabel": "Acil Durum Yanıtlama Kılavuzu",
  "ergMainPageTitle": "Acil Durum Yanıtlama Kılavuz Kitapçığı 2016’yı Temel Alır",
  "coordInputLabelStart": "Sızıntı Konumu (DD)",
  "coordInputLabel": "Sızıntı Konumu",
  "addPointToolTip": "Sızıntı Konum Ekle",
  "drawPointToolTip": "Sızıntı konumu eklemek için tıkla",
  "material": "Malzeme",
  "materialPlaceholder": "Bir malzeme aramak için yazmaya başla",
  "table3Message": "Büyük bir sızıntı ile uğraşıyorsanız seçtiğiniz malzeme ek bilgi gerektirir.\n\nRüzgar hızı ve nakliye konteyneri için doğru değerleri seçtiğinizden emin olun.",
  "table2Message": "Seçtiğiniz malzeme suya sızarsa, Zehirli Solunum Tehlikesi riski içeren büyük miktarda gaz üretebilir.\n\nAşağıdaki malzemeyi (malzemeleri) kullanmayı değerlendirebilirsiniz:\n\n",
  "spillSize": "Sızıntı Boyutu",
  "small": "Küçük",
  "large": "Büyük",
  "fireLabel": "Yangın İzolasyon Bölgesini Göster",
  "weatherLabel": "Sızıntı Konumunda Güncel Hava Durumu",
  "weatherIntialText": "<br />Bir sızıntı konumu tanımlandığında güncellenir",
  "temperature": "Sıcaklık",
  "wind": "Rüzgar",
  "c": "C",
  "f": "Y",
  "weatherErrorMessage": "Hava durumu bilgileri elde edilemedi. Rüzgar Hızı ve Sızıntı Zamanı değerlerini manuel olarak güncelleyin",
  "windDirection": "Rüzgar Yönü (estiği yön)",
  "timeOfSpill": "Sızıntı Zamanı",
  "day": "Gün",
  "night": "Gece",
  "windSpeed": "Rüzgar Hızı",
  "low": "Düşük",
  "moderate": "Orta",
  "high": "Yüksek",
  "transportContainer": "Nakliye Konteyneri",
  "rail": "Demiryolu tankeri",
  "semi": "Otoyol tankeri veya römork",
  "mton": "Çok tonlu silindirler",
  "ston": "Çoklu küçük silindirler veya tek tonlu silindir",
  "ag": "Tarım amaçlı römork tank",
  "msm": "Çoklu küçük silindirler",
  "bleveLabel": "BLEVE İzolasyon Bölgesini Göster",
  "capacity": "Konteyner Kapasitesi (litre)",
  "bleveMessage": "Seçtiğiniz malzemede BLEVE için ek tahliye mesafesi gösterilebilir.\n\nBunu etkinleştirmek için BLEVE İzolasyon Bölgesini Göster anahtarını açık olarak ayarlayın ve uygun konteyner kapasitesini seçin.",
  "noPAZoneMessage": "Bu malzeme için Koruyucu İşlem mesafesi yok. Sadece İlk İzolasyon ve tahliye bölgeleri hesaplandı",
  "settingsTitle": "Ayarlar",
  "spillLocationLabel": "Sızıntı Konumu",
  "spillLocationButtonLabel": "Sızıntı Konumu Ayarlarını Yapılandır",
  "IISettingsLabel": "İlk İzolasyon Bölgesi",
  "IIButtonLabel": "İzolasyon Bölgesi Ayarlarını Yapılandır",
  "PASettingsLabel": "Koruyucu İşlem Bölgesi",
  "PAButtonLabel": "Koruyucu İşlem Ayarlarını Yapılandır",
  "downwindSettingsLabel": "Rüzgar Altı Bölgesi",
  "downwindButtonLabel": "Rüzgar Altı Ayarlarını Yapılandır",
  "fireSettingsLabel": "Yangın İzolasyon Bölgesi",
  "fireButtonLabel": "Yangın İzolasyon Ayarlarını Yapılandır",
  "bleveSettingsLabel": "BLEVE İzolasyon Bölgesi",
  "bleveButtonLabel": "BLEVE Ayarlarını Yapılandır",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Çizgi",
    "esriSLSDashDot": "Çizgi Nokta",
    "esriSLSDashDotDot": "Çizgi Nokta Nokta",
    "esriSLSDot": "Nokta",
    "esriSLSLongDash": "Uzun Çizgi",
    "esriSLSLongDashDot": "Uzun Çizgi Nokta",
    "esriSLSNull": "Boş",
    "esriSLSShortDash": "Kısa Çizgi",
    "esriSLSShortDashDot": "Kısa Çizgi Nokta",
    "esriSLSShortDashDotDot": "Kısa Çizgi Nokta Nokta",
    "esriSLSShortDot": "Kısa Nokta",
    "esriSLSSolid": "Katı"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Geri",
    "esriSFSCross": "Çapraz",
    "esriSFSDiagonalCross": "Diyagonal",
    "esriSFSForwardDiagonal": "İleri",
    "esriSFSHorizontal": "Yatay",
    "esriSFSNull": "Boş",
    "esriSFSSolid": "Katı",
    "esriSFSVertical": "Dikey"
  },
  "resultsTitle": "Sonuçlar",
  "publishERGBtn": "Yayınla",
  "ERGLayerName": "Yayınlanan ERG Katmanı Adı",
  "invalidERGLayerName": "Katman adı sadece alfa sayısal karakterler ve alt çizgiler içermelidir",
  "missingERGLayerName": "ERG için bir ad girmelisiniz",
  "publishingFailedLayerExists": "Yayınlama Başarısız Oldu: Bir detay servisi adı {0} zaten var. Lütfen başka bir ad seçin.",
  "checkService": "Servisi Denetle: {0}.",
  "createService": "Servis Oluştur: {0}.",
  "unableToCreate": "Oluşturulamıyor: {0}",
  "addToDefinition": "Tanıma ekle: {0}",
  "successfullyPublished": "Web katmanı başarılı bir şekilde yayınlandı{0}Web katmanını yönet",
  "userRole": "Kullanıcı gerekli izne sahip olmadığından servis oluşturulamadı",
  "transparency": "Şeffaflık",
  "outline": "Ana Hat",
  "fill": "Doldur (Renk sadece stil katı olarak ayarlandığında uygulanır)",
  "createERGBtn": "Bölgeler Oluştur",
  "clearERGBtn": "Temizle",
  "labelFormat": "Etiket Formatı",
  "helpIconTooltip": "Küçük ve büyük sızıntı boyutları arasındaki eşik:\nSıvılar - 55 galon (208 litre)\nKatılar - 60 libre (300 kilogram)",
  "cellWidth": "Hücre Genişliği (x)",
  "cellHeight": "Hücre Yüksekliği (y)",
  "invalidNumberMessage": "Girilen değer geçerli değil",
  "invalidRangeMessage": "Değer 0’dan büyük olmalıdır",
  "gridAngleInvalidRangeMessage": "Değer -89,9 ile 89,9 arasında olmalıdır",
  "formatIconTooltip": "Biçim Girdisi",
  "setCoordFormat": "Koordinat Biçimi Dizgisini Ayarla",
  "prefixNumbers": "Pozitif ve negatif sayıların önüne ‘+/-’ işareti ekleyin",
  "cancelBtn": "İptal Et",
  "applyBtn": "Uygula",
  "comfirmInputNotation": "Girdi Gösterimini Onayla",
  "notationsMatch": "gösterimler girdinizle eşleşiyor lütfen hangisini kullanmak istediğinizi belirtin:",
  "missingLayerNameMessage": "Yayınlayabilmeniz için geçerli bir katman adı girmelisiniz",
  "parseCoordinatesError": "Koordinatlar ayrıştırılamıyor. Girdinizi denetleyin.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Ondalık Dereceleri - Enlem/Boylam",
  "DDLongLatNotation": "Ondalık Dereceleri  - Boylam/Enlem",
  "DDMLatLongNotation": "Dereceler Ondalık Dakikalar - Enlem/Boylam",
  "DDMLongLatNotation": "Dereceler Ondalık Dakikalar - Boylam/Enlem",
  "DMSLatLongNotation": "Dereceler Dakikalar Saniyeler - Enlem/Boylam",
  "DMSLongLatNotation": "Dereceler Dakikalar Saniyeler - Boylam/Enlem",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bant Harf",
  "UTMHemNotation": "UTM - Yarıküre (K/G)"
});