define({
  "_widgetLabel": "Stream",
  "streamControls": "Streaming-Steuerungselemente",
  "streamFilter": "Filter",
  "startStreaming": "Streaming starten",
  "stopStreaming": "Streaming beenden",
  "streamLayers": "Stream-Layer",
  "startStopStream": "Die Option \"Streaming beenden\" oder \"Streaming starten\" aktivieren",
  "clearStream": "Die Option \"Vorherige Beobachtungen löschen\" aktivieren",
  "attributeFilter": "Attributfilter aktivieren",
  "spatialFilter": "Räumlichen Filter aktivieren",
  "configFilter": "Stream-Attribut-Filter konfigurieren",
  "drawPrevious": "Die Option \"Vorherige Beobachtungen darstellen\" aktivieren",
  "addNew": "Filter hinzufügen",
  "setFilterName": "Filtername festlegen",
  "filterNameExists": "Filtername ist in der Tabelle vorhanden!",
  "invalidFilterName": "Der Name darf folgende Zeichen enthalten: a-z, A-Z, 0-9 oder _.",
  "noFilterTip": "Kein Filter konfiguriert",
  "addFilterFailed": "Filter konnte nicht hinzugefügt werden",
  "filterName": "Filtername",
  "limitMapExtent": "Beobachtungen im aktuellen Kartenbereich beschränken",
  "limitDrawExtent": "Beobachtungen im benutzerdefinierten Bereich beschränken",
  "newFilter": "Neuer Filter",
  "filterReadOnly": "Der von der Karte übernommene Filter ist schreibgeschützt."
});