define({
  "_widgetLabel": "Trình lập mô hình ổn định",
  "general": {
    "clear": "Xóa",
    "cancel": "Hủy",
    "save": "Chạy",
    "saveAs": "Xuất"
  },
  "saveModel": {
    "save": "Xuất",
    "title": "Tiêu đề: ",
    "summary": "Mô tả: ",
    "description": "Mô tả: ",
    "tags": "Từ khóa: ",
    "folder": "Thư mục: ",
    "homeFolderPattern": "{username} (Trang chủ)",
    "failed": "Xuất không thành công."
  },
  "util": {
    "colorRamp": {
      "1": "Vô cùng Thấp",
      "2": "Rất Thấp",
      "3": "Thấp",
      "4": "Trung bình Thấp",
      "5": "Trung bình",
      "6": "Trung bình Cao",
      "7": "Cao",
      "8": "Rất Cao",
      "9": "Vô cùng Cao",
      "low": "Thấp",
      "high": "Cao",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Đảo"
    }
  },
  "wro": {
    "caption": "Trình lập mô hình ổn định",
    "browsePrompt": "Dịch vụ Lớp chồng lớp có Trọng số",
    "selectLayersCaption": "Chọn Lớp",
    "selectLayers": "Lớp",
    "designModelCaption": "Mô hình Thiết kế",
    "designModel": "Mô hình Thiết kế",
    "transparency": "Độ trong suốt",
    "visible": "Hiển thị",
    "total": "Tổng",
    "unableToLoad": "Không thể tải mô hình.",
    "projectNotOpen": "Dự án không mở.",
    "readMore": "Đọc thêm",
    "validation": {
      "validating": "Đang xác minh...",
      "invalidItemCaption": "Cảnh báo Dịch vụ Chồng lớp có Trọng số",
      "notAnImageService": "Mục này không phải là một Dịch vụ Hình ảnh.",
      "notAWroService": "Mục này không phải là một Dịch vụ Lớp chồng lớp có Trọng số.",
      "undefinedUrl": "URL của mục này không được xác định.",
      "inaccessible": "Không thể truy cập dịch vụ.",
      "generalError": "Không thể mở mục.",
      "missingFieldPattern": "{field} là một trường bắt buộc",
      "notAllowRasterFunction": "allowRasterFunction phải được thiết lập là đúng",
      "notNearestResampling": "defaultResamplingMethod phải là Gần nhất",
      "notIsWeightedOverlayProp": "Thuộc tính chính IsWeightedOverlay phải được thiết lập là đúng",
      "invalidLink": "URL không hợp lệ. Không mở được trang cho lớp đã chọn.",
      "unexpectedError": "Đã xảy ra trạng thái không mong muốn.",
      "rangeMessage": "Giá trị phải nằm trong khoảng từ ${0} đến ${1}",
      "rangeMessage100": "Giá trị phải nằm trong khoảng từ 0 đến 100",
      "maxLayers": "Tối đa ${0} lớp được dịch vụ cho phép, trước tiên bạn phải xóa một lớp trước khi thêm một lớp mới.",
      "notFound": "Không tìm thấy lớp ${0} nào trong dịch vụ chồng lớp có trọng số",
      "wroServiceNotDefined": "Không xác định được dịch vụ chồng lớp có trọng số cho mô hình.",
      "overlayLayerOutputInvalid": "Chồng lớp [${0}] thiết lập lại các phạm vi [${1}] giá trị đầu ra bị thiếu hoặc không hợp lệ",
      "overlayLayerInputInvalid": "Chồng lớp [${0}] thiết lập lại các phạm vi [${1}] đầu vào tối thiểu/tối đa bị thiếu hoặc không hợp lệ",
      "overlayLayerRangesMissing": "Chồng lớp [${0}] thiết lập lại các phạm vi bị thiếu",
      "overlayLayerWeight": "Trọng lượng các lớp chồng lớp phải thêm đến 100",
      "overlayLayerRequired": "Cần có ít nhất một lớp chồng lớp",
      "overlayLayerNotDefined": "Không xác định được lớp chồng lớp",
      "requiresColormap": "Chức năng raster này cần một bản đồ màu, nhưng mô hình không có định nghĩa bản đồ màu hợp lệ",
      "createModelError": "Lỗi khi Tạo Mô hình",
      "invalidModel": "Mô hình không hợp lệ",
      "imageServiceNotDefined": "Không xác định được lớp dịch vụ hình ảnh",
      "imageLayerNotDefined": "Không xác định được lớp dịch vụ hình ảnh",
      "histogramNotDefined": "Không xác định được chức năng biểu đồ tần số lớp chồng lớp có trọng số"
    },
    "colorRampLabel": {
      "Green Yellow Red": "Xanh lá cây Vàng Đỏ",
      "Red Yellow Green": "Đỏ Vàng Xanh lá cây",
      "Yellow to Dark Red": "Vàng đến Đỏ Sẫm",
      "Dark Red to Yellow": "Đỏ Sẫm đến Vàng",
      "Light Gray to Dark Gray": "Xám Nhạt đến Xám Đậm",
      "Dark Gray to Light Gray": "Xám Đậm đến Xám Nhạt",
      "Light Brown to Dark Brown": "Nâu Nhạt đến Nâu Đậm",
      "Dark Brown to Light Brown": "Nâu Đậm đến Nâu Nhạt",
      "Full Spectrum - Bright Red to Blue": "Quang phổ Toàn phần - Đỏ Sáng đến Xanh da trời",
      "Full Spectrum - Bright Blue to Red": "Quang phổ Toàn phần - Xanh da trời Sáng đến Đỏ",
      "Partial Spectrum - Yellow to Blue": "Quang phổ Một phần - Vàng đến Xanh da trời",
      "Partial Spectrum - Blue to Yellow": "Quang phổ Một phần - Xanh da trời đến Vàng",
      "Yellow-Green to Dark Blue": "Vàng-Xanh lá cây đến Xanh da trời Đậm",
      "Dark Blue to Yellow-Green": "Xanh da trời Đậm đến Vàng-Xanh lá cây",
      "Cold to Hot Diverging": "Phân kỳ từ Lạnh sang Nóng",
      "Hot to Cold Diverging": "Phân kỳ từ Nóng sang Lạnh",
      "Surface - Low to High": "Bề mặt - Thấp đến Cao",
      "Surface - High to Low": "Bề mặt - Cao đến Thấp"
    }
  },
  "tabs": {
    "layers": "Lớp",
    "model": "Mô hình",
    "chart": "Biểu đồ"
  },
  "chart": {
    "prompt": "Đối tượng",
    "working": "Đang cập nhật...",
    "polygonTool": "Vẽ đa giác",
    "freehandPolygonTool": "Vẽ đa giác tùy ý",
    "selectTool": "Chọn từ một lớp",
    "panTool": "Di chuyển",
    "clearButton": "Xóa",
    "noModelLayer": "Không có mô hình.",
    "noSubjectLayers": "Bản đồ của bạn không có lớp đa giác.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});