define({
  "symbolologyTabLabel": "配置符号",
  "facilitiesDescription": "设施点图层",
  "demographicsDescription": "人口统计图层",
  "settingsTitle": "设置",
  "spillLocationLabel": "泄漏位置",
  "spillLocationButtonLabel": "配置泄漏位置设置",
  "IISettingsLabel": "初始隔离区",
  "IIButtonLabel": "配置初始隔离设置",
  "PASettingsLabel": "防护行动区",
  "PAButtonLabel": "配置防护行动设置",
  "downwindSettingsLabel": "顺风区",
  "downwindButtonLabel": "配置顺风设置",
  "fireSettingsLabel": "隔火区",
  "fireButtonLabel": "配置隔火设置",
  "bleveSettingsLabel": "BLEVE 隔离区",
  "bleveButtonLabel": "配置 BLEVE 设置",
  "transparency": "透明度",
  "outline": "轮廓",
  "fill": "填充(仅在将样式设置为单色时应用颜色)",
  "style": "样式",
  "lineStyles": {
    "esriSLSDash": "虚线",
    "esriSLSDashDot": "点划线",
    "esriSLSDashDotDot": "双点划线",
    "esriSLSDot": "点",
    "esriSLSLongDash": "长划线",
    "esriSLSLongDashDot": "长点划线",
    "esriSLSNull": "空",
    "esriSLSShortDash": "短虚线",
    "esriSLSShortDashDot": "短点划线",
    "esriSLSShortDashDotDot": "短双点划线",
    "esriSLSShortDot": "短点线",
    "esriSLSSolid": "实线"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向后",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "对角线",
    "esriSFSForwardDiagonal": "向前",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "空",
    "esriSFSSolid": "实线",
    "esriSFSVertical": "竖直"
  }
});