define({
  "chartTasks": "Grafik tugas",
  "addNew": "Tambah baru",
  "addNewTip": "Tambahkan grafik tugas baru",
  "name": "Nama",
  "set": "Atur",
  "setDataSource": "Atur sumber data",
  "generalSettingsTip": "Atur sumber data, judul, dan deskripsi untuk grafik",
  "chartModeSettingTip": "Pilih cara menganalisis dan menampilkan data sebagai grafik.",
  "detailsSettingTip": "Atur tampilan grafik dengan menentukan jenis dan warna, serta nilai apa yang dijadikan grafik:",
  "symbolSettingTip": "Atur tampilan peta untuk data yang dijadikan grafik.",
  "addFilterTip": "Tambahkan filter ke data ini",
  "dataSource": "Sumber Data",
  "noResults": "Fitur tidak ditemukan.",
  "chartTitle": "Judul grafik",
  "description": "Deskripsi",
  "chartingMode": "Tampilan grafik",
  "featureOption": "Tampilkan fitur nilai menurut fitur",
  "categoryOption": "Tampilkan nilai menurut kategori",
  "countOption": "Tampilkan jumlah fitur menurut kategori",
  "fieldOption": "Tampilkan nilai atribut sebagai grafik",
  "category": "Kategori",
  "axisLabel": "Label kategori",
  "categoryField": "Kolom kategori",
  "operation": "Operasi",
  "originalOption": "Gunakan nilai asli",
  "sumOption": "Sum",
  "averageOption": "Rata-rata",
  "minOption": "Minimal",
  "maxOption": "Maksimal",
  "valueFields": "Kolom nilai",
  "moveUp": "Pindahkan ke atas",
  "moveDown": "Pindahkan ke bawah",
  "sortOrder": "Urutkan urutan grafik berdasarkan label kategori",
  "ascending": "Naik",
  "descending": "Turun",
  "chartType": "Jenis grafik",
  "column": "Grafik kolom",
  "bar": "Grafik batang",
  "line": "Grafik garis",
  "pie": "Diagram Pai",
  "chartColor": "Warna grafik",
  "showDataLabels": "Tampilkan label data",
  "setSymbol": "Simbol pilihan",
  "setHighLightColor": "Warna sorotan",
  "settings": "Pengaturan",
  "mapInterationOptions": "Opsi interaksi peta",
  "preview": "Pratinjau",
  "ok": "Ya",
  "cancel": "Batal",
  "close": "Tutup",
  "setFilterTip": "Tetapkan filter dengan benar. ",
  "setChartTitleTip": "Harap tetapkan judul grafik.",
  "setChartTypeTip": "Harap pilih paling sedikit satu jenis grafik.",
  "setDataFieldTip": "Harap pilih paling sedikit satu kolom nilai.",
  "setOutputFieldTip": "Harap tetapkan kolom output.",
  "count": "Count",
  "label": "Label",
  "horizontalAxis": "Sumbu horizontal",
  "verticalAxis": "Sumbu vertikal",
  "dataLabels": "Label data",
  "color": "Warna",
  "colorful": "Penuh warna",
  "monochromatic": "Monokromatik",
  "noTaskTip": "Klik Tambahkan baru untuk menambahkan tugas grafik",
  "info": "Info",
  "charts": "Grafik",
  "options": "Opsi",
  "taskName": "Nama tugas",
  "summary": "Ringkasan",
  "resultDescription": "Keterangan hasil",
  "spatialFilterTip": "Pilih filter spasial yang digunakan dalam widget untuk membatasi hasil.",
  "defaultOption": "Default",
  "useCurrentExtentTip": "Sebagian atau sepenuhnya berada dalam jangkauan peta saat ini",
  "useDrawGraphicTip": "Sebagian atau sepenuhnya berada dalam bentuk yang digambarkan pada peta",
  "useFeaturesTip": "Berdasarkan lokasinya yang relatif terhadap fitur di layer lainnya",
  "noSpatialLimitTip": "Jangan membatasi hasil secara spasial",
  "drawingTools": "Peralatan menggambar",
  "bufferSettings": "Pengaturan buffer",
  "defaultDistance": "Jarak default",
  "bufferDistance": "Jarak buffer",
  "defaultUnit": "Unit default",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil laut",
  "availableSpatialRelationships": "Hubungan spasial tersedia",
  "setSpatialRelationships": "Atur hubungan spasial",
  "availability": "Ketersediaan",
  "relationship": "Hubungan",
  "actions": "Tindakan",
  "intersect": "berpotongan",
  "contain": "berisi",
  "areContainedIn": "berada di",
  "cross": "silang",
  "envelopeIntersect": "perpotongan selubung",
  "overlap": "tumpang tindih",
  "areOverlapped": "tumpang tindih",
  "touche": "menyentuh",
  "within": "di dalam",
  "areWithin": "berada di",
  "indexIntersect": "perpotongan indeks"
});