define({
  "_widgetLabel": "Mesafe ve Yön",
  "tabLineTitle": "Çizgi",
  "tabCircleTitle": "Daire",
  "tabEllipseTitle": "Elips",
  "tabRingsTitle": "Halkalar",
  "multipleNotationsMessage": " girdinizle eşleşen gösterimler. Hangisini kullanmak istediğinizi belirtin:",
  "invalidCoordinateMessage": "Geçersiz Koordinat",
  "confirmInputNotationMessage": "Girdi Gösterimini Onayla",
  "prefixSuffixMessage": "Girdi koordinatında enlem veya boylam değeri için hem ön hem de son ek olduğu algılandı, döndürülen koordinat ön eke göredir.",
  "rememberDecisionMessage": "Tercihimi anımsa ve bir daha sorma.<br/>",
  "majorAxisTooltipMessage": "Büyük eksenin uzunluğuna tıkla",
  "minorAxisTooltipMessage": "Küçük ekseni ayarlamak ve elips çizimini tamamlamak için fareyi başlangıç konumuna getirin",
  "clickToFinishLineMessage": "Çizgi çizimini bitirmek için tıklayın",
  "doubleClickEllipseMesage": "Aralık halkaları çizimini bitirmek için çift tıklayın",
  "invalidCoordinateTypeMessage": "Girdi koordinat türü belirlenemiyor. Lütfen girdinizi kontrol edin",
  "noCenterPointSetMessage": "Merkez noktası ayarlanmadı. Lütfen girdinizi kontrol edin",
  "ellipseMajorAxis": "Büyük Eksen",
  "ellipseMinorAxis": "Küçük Eksen",
  "degreesRangeMessage": "Değer 0 ile 360 arasında olmalıdır",
  "millsRangeMessage": "Değer 0 ile 6400 arasında olmalıdır",
  "lengthLabel": "Uzunluk",
  "angleLabel": "Açı",
  "startPointLabel": "Başlangıç Noktası",
  "endPointLabel": "Bitiş Noktası",
  "centerPointLabel": "Merkez Nokta",
  "distanceTableErrorMessage": "Mesafe tablosu boş. Lütfen mesafe girdiğinizden emin olun.",
  "setCoordFormatStringMessage": "Koordinat Biçimi Dizgisini Ayarla",
  "prefixMessage": "Pozitif ve negatif sayıların önüne ‘+/-’ işareti ekleyin",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Ondalık Dereceleri - Enlem/Boylam",
  "DDLongLatNotation": "Ondalık Dereceleri  - Boylam/Enlem",
  "DDMLatLongNotation": "Dereceler Ondalık Dakikalar - Enlem/Boylam",
  "DDMLongLatNotation": "Dereceler Ondalık Dakikalar - Boylam/Enlem",
  "DMSLatLongNotation": "Dereceler Dakikalar Saniyeler - Enlem/Boylam",
  "DMSLongLatNotation": "Dereceler Dakikalar Saniyeler - Boylam/Enlem",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bant Harf",
  "UTMHemNotation": "UTM - Yarıküre (K/G)",
  "circleTitle": "Daire Oluştur",
  "radiusLabel": "Yarıçap",
  "diameterLabel": "Çap",
  "startPointPlaceHolderLabel": "Koordinatları gir",
  "formatInputLabel": "Biçim Girdisi",
  "drawCircleLabel": "Yuvarlak çiz",
  "drawLineLabel": "Çizgi Çiz",
  "createCircleInteractivelyLabel": "Etkileşimli Daire Oluştur",
  "rangeErrorMessage": "Geçersiz yarıçap veya çap",
  "numericInvalidMessage": "Lütfen sayısal bir değer girin",
  "timeLabel": "Zaman",
  "invalidTimeMessage": "Geçersiz zaman değeri",
  "hoursLabel": "Saat",
  "minutesLabel": "Dakika",
  "secondsLabel": "Saniye",
  "rateLabel": "Oran",
  "invalidDistanceMessage": "Geçersiz mesafe değeri",
  "feetSecondsLabel": "Fit / saniye",
  "feetHourLabel": "Fit / saat",
  "kmSecondLabel": "Kilometre / saniye",
  "kmHourLabel": "Kilometre / saat",
  "metersSecondLabel": "Metre / saniye",
  "metersHourLabel": "Metre / saat",
  "milesSecondLabel": "Mil / saniye",
  "milesHourLabel": "Mil / saat",
  "nauticalMilesSecondLabel": "Deniz Mili / saniye",
  "nauticalMilesHourLabel": "Deniz Mili / saat",
  "clearGraphicsLabel": "Grafikleri Sil",
  "ellipseTypeLabel": "Elips Türü",
  "ellipseSemiLabel": "Yarım",
  "ellipseFullLabel": "Tam",
  "drawEllipseLabel": "Elips Çiz",
  "createEllipseInteractively": "Etkileşimli Elips Oluştur",
  "axisLabel": "Eksen",
  "majorRadiusLabel": "Büyük (Yarıçap)",
  "axisErrorMessage": "Değer 0’dan büyük olmalıdır",
  "minorRadiusLabel": "Küçük (Yarıçap)",
  "orientationLabel": "Yönelim",
  "orientationErrorMessage": "Değer 0 ile 360 arasında olmalıdır",
  "warningMessage": "Uyarı: Elips aracı kullanılarak oluşturulan grafikler jeodezik değildir",
  "fromLabel": "Kaynak",
  "distanceBearingLabel": "Mesafe ve Konum Açısı",
  "pointsLabel": "Noktalar",
  "createLineInteractively": "Etkileşimli Çizgi Oluştur",
  "lineLengthErrorMessage": "Geçersiz Çizgi Uzunluğu",
  "degreesLabel": "Derece",
  "milsLabel": "Mil",
  "lineTypeLabel": "Tür",
  "interactiveLabel": "İnteraktif",
  "fixedLabel": "Sabit",
  "originLabel": "Başlangıç",
  "cumulativeLabel": "Yığılmalı",
  "numberOfRingsLabel": "Halka Sayısı",
  "ringsErrorMessage": "Geçersiz halka sayısı",
  "distanceBetweenRingsLabel": "Halkalar Arasındaki Mesafe",
  "ringsDecimalErrorMessage": "2 ondalık basamağa sayısal bir değer girin",
  "distanceUnitsLabel": "Mesafe Birimleri",
  "distancesLabel": "Mesafeler",
  "numberOfRadialsLabel": "Radyal Sayısı",
  "upLabel": "Yukarı",
  "downLabel": "Aşağı",
  "deleteLabel": "Sil",
  "radialsErrorMessage": "Geçersiz radyal sayısı. Maksimum izin verilen 360’tır",
  "addPointLabel": "Nokta Ekle",
  "valueLabel": "Değer",
  "valueText": "Değer Gir",
  "actionLabel": "İşlem"
});