define({
  "labelBookmarkName": "Aktuelle Ansicht als Lesezeichen speichern",
  "labelPlay": "Alle wiedergeben",
  "labelStop": "Beenden",
  "labelDelete": "Löschen",
  "placeholderBookmarkName": "Lesezeichenname",
  "errorNameExist": "Lesezeichen ist vorhanden!",
  "errorNameNull": "Ungültiger Lesezeichenname!",
  "editTip": "Lesezeichen bearbeiten",
  "exitEditTip": "Bearbeitungsmodus beenden",
  "syncTip": "Synchronisieren",
  "cardsTips": "Tabellenansicht",
  "listTips": "Listenansicht",
  "addBtn": "Hinzufügen",
  "deleteBtn": "Löschen",
  "changeThumbnailTip": "Miniaturansicht ändern",
  "dragReorderTip": "Zur Neuanordnung halten und ziehen",
  "deleteBtnTip": "Das Lesezeichen löschen",
  "editBtnTip": "Das Lesezeichen bearbeiten",
  "withVisibility": "Mit Layer-Sichtbarkeit",
  "searchBookmark": "Durchsuchen",
  "bookmarksFromConfig": "Vorkonfigurierte Lesezeichen",
  "bookmarksFromCache": "Lokale temporäre Lesezeichen",
  "notice": "Hinweis",
  "changeNoticeTips": "Änderungen werden nur im Browser-Cache gespeichert. Die Synchronisierung zwischen dem Widget und dessen Konfiguration wird unterbrochen, sobald Sie Änderungen vornehmen.",
  "syncNoticeTips": "So werden Ihre Änderungen gelöscht und die konfigurierten Lesezeichen wiederhergestellt.",
  "dontShowAgain": "Nicht noch einmal anzeigen",
  "saveVisibility": "Layer-Sichtbarkeit speichern",
  "_widgetLabel": "Lesezeichen"
});