define({
  "labelBookmarkName": "Aggiungi segnalibro per visualizzazione corrente",
  "labelPlay": "Riproduci tutto",
  "labelStop": "Arresta",
  "labelDelete": "Elimina",
  "placeholderBookmarkName": "Nome segnalibro",
  "errorNameExist": "Segnalibro esistente.",
  "errorNameNull": "Nome segnalibro non valido.",
  "editTip": "Modifica segnalibri",
  "exitEditTip": "Esci dalla modalità di modifica",
  "syncTip": "Sincronizza",
  "cardsTips": "Vista griglia",
  "listTips": "Vista elenco",
  "addBtn": "Aggiungi",
  "deleteBtn": "Elimina",
  "changeThumbnailTip": "Cambia anteprima",
  "dragReorderTip": "Seleziona e trascina per riordinare",
  "deleteBtnTip": "Cancella segnalibro",
  "editBtnTip": "Modifica segnalibro",
  "withVisibility": "Con visibilità del layer",
  "searchBookmark": "Cercare",
  "bookmarksFromConfig": "Segnalibri preconfigurati",
  "bookmarksFromCache": "Segnalibri temporanei locali",
  "notice": "Avviso",
  "changeNoticeTips": "Le modifiche saranno salvate solo nella cache del browser. La sincronizzazione tra il widget e la sua configurazione viene disconnessa una volta apportate le modifiche.",
  "syncNoticeTips": "Questo cancellerà le eventuali modifiche e ripristinerà i segnalibri configurati.",
  "dontShowAgain": "Non mostrare più",
  "saveVisibility": "Salva la visibilità del layer",
  "_widgetLabel": "Segnalibro"
});