define({
  "tabs_section_Label": "Vahekaardid",
  "addTab": "Lisa vahekaart",
  "layerName": "Kiht",
  "layerType": "Analüüsi tüüp",
  "layerLabel": "Märgis",
  "actions": "Toimingud",
  "closest": "Lähim objekt",
  "proximity": "Lähedus",
  "summary": "Kokkuvõte",
  "select_lbl": "-- Vali --",
  "general_setting_Label": "Üldseaded",
  "units_text_lbl": "Vahemaa ühikud",
  "maximum_distance_lbl": "Lähima objekti maksimaalne ulatus",
  "buffer_text_lbl": "Puhvri märgis",
  "buffer_lbl": "Puhvri ulatus",
  "buffer_max_lbl": "Maksimaalne puhvri ulatus",
  "buffer_min_lbl": "Minimaalne puhvri ulatus",
  "buffer_default_lbl": "Puhvri vaikeulatus",
  "not_less_than_max": "Vahemaa peab olema väiksem kui puhvri miinimumulatus",
  "not_between": "Vahemaa peab jääma puhvri miinimum- ja maksimumulatuse vahele",
  "not_more_than_min": "Vahemaa peab olema suurem kui puhvri maksimumulatus",
  "not_valid_number": "Peab olema sobiv arv",
  "invalid_value": "${type}-väärtus ei sobi",
  "routing_checkBox": "Luba marsruutimine",
  "weather_Label": "Ilmasätted",
  "weather_checkBox": "Liba ilm",
  "weather_map_layers": "Vali ilmakihid...",
  "selected_map_layers": " ilmakihid valitud",
  "instruction_weather": "Kuva ilmainfot paneelis.",
  "instruction_weather_layers": "Kuiva veel ilmakihte.",
  "instruction_weather_metric": "Kuva standard-/meetrilisi väärtusi.",
  "selectLayers": "Vali ilmakihid",
  "weather_removed_message": "Selle vidina jaoks pole ilmavalikud enam saadaval.",
  "currentlySelectedLayer": "Vali kaardikihtidest",
  "missingTabLabel": "Vähemalt ühel vahekaardil puudub märgis.",
  "missingLayerInWebMap": "Töökihte ei leitud.",
  "selectFields": "Vali väljad",
  "addField": "Lisa väli",
  "sum": "Summa",
  "min": "Miinimum",
  "max": "Maksimum",
  "avg": "Keskmine",
  "count": "KOGUARV",
  "area": "PINDALA",
  "length": "PIKKUS",
  "count_checkBox": "Kuva objektide arv",
  "area_checkBox": "Kuva summaarne pindala",
  "length_checkBox": "Kuva summaarne pikkus",
  "max_records": "Limiit on täis",
  "save_label": "Salvestamise valikud",
  "save_checkbox": "Luba salvestamine",
  "report_label": "Aruande valikud",
  "report_checkbox": "Luba aruanne",
  "csv_label": "CSV valikud",
  "csv_checkbox": "Ekspordi kõik väljad",
  "display_label": "Kuvamisvalikud",
  "display_checkbox": "Kuva kokkuvõtte objektid",
  "snapshot_label": "Hetktõmmise valikud",
  "snapshot_checkbox": "Luba hetktõmmis",
  "must_select_template": "Valige üks salvestamise valikute muutmise mall.",
  "count_label": "Arvu märgis",
  "area_label": "Pindala märgis",
  "length_label": "Pikkuse märgis",
  "invalid_string_width": "Väärtus on liiga pikk. ",
  "layer_type_not_supported": "Säärast tüüpi kiht ei ole toetatud",
  "groupedSummary": "Rühmitatud koguarvud",
  "groupByField": "Rühmita veeru alusel",
  "labelType": "Lisa märgis",
  "prefix": "Eesliitena",
  "suffix": "Järelliitena",
  "need_group_field": "Kasutage veeru alusel rühmitamiseks muutmise toimingut.",
  "fieldTitle": "Väli",
  "typeTitle": "Tüüp",
  "actionsTitle": "Toimingud",
  "save_point_checkbox": "Salvesta punktid",
  "save_line_checkbox": "Salvesta jooned",
  "save_poly_checkbox": "Salvesta polügoonid",
  "no_valid_popup_fields": "Hüpikaknas pole sobivaid välju. Kasutage välja määratlemiseks muutmistoimingut.",
  "no_valid_fields": "Sobivaid välju pole. Kasutage valikute kuvamiseks muutmistoimingut.",
  "incident_label": "Vahekaardi märgis",
  "locate_incident_label": "Huviala märgise ala",
  "incident": "Juhtum",
  "locate_incident": "Paiguta juhtum",
  "buffer_value": "Puhvri ulatus",
  "tab_options": "Analüüs",
  "export_options": "Väljund",
  "instruction_save": "Salvesta asukoht objektiteenusesse.",
  "instruction_snapshot": "Loo asukoha põhjal veebikaart.",
  "instruction_report": "Loo asukoha prinditud aruanne.",
  "instruction_all_fields": "Ekspordi kõik väljad koos CSV allalaadimisega.",
  "data_label": "Andmete väljastussätted",
  "layer_error": "Kiht puudub või ei sobi.",
  "visibility_checkBox": "Keela kihi nähtavuse haldamine",
  "downloadTab": {
    "reportLegend": "Aruande sätted",
    "textColorLabel": "Valige tulpade pealkirjade värv",
    "setButtonLabel": "Määra",
    "printGPServiceLabel": "Printimise teenuse URL",
    "logoLabel": "Logo",
    "logoChooserHint": "Klõpsake pildi muutmiseks pildi ikooni",
    "footnoteLabel": "Joonealune märkus"
  }
});