define({
  "_widgetLabel": "Conversie coordonate",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Grade zecimale - latitudine/longitudine",
  "DDLongLatNotation": "Grade zecimale - longitudine/latitudine",
  "DDMLatLongNotation": "Grade zecimale minute - latitudine/longitudine",
  "DDMLongLatNotation": "Grade zecimale minute - longitudine/latitudine",
  "DMSLatLongNotation": "Grade minute secunde - latitudine/longitudine",
  "DMSLongLatNotation": "Grade minute secunde - longitudine/latitudine",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - literă bandă",
  "UTMHemNotation": "UTM - emisferă (N/S)",
  "formatInput": "Intrare format",
  "copyAll": "Copiere toate",
  "copySuccessful": "Copiere reuşită",
  "copyFailed": "Imposibil de copiat. Folosiţi ctrl+c ca alternativă.",
  "parseCoordinatesError": "Imposibil de analizat coordonatele. Verificaţi intrarea.",
  "comfirmInputNotation": "Confirmare notare intrare",
  "latLongWarningMessage": "Coordonata de intrare a fost detectată ca având şi prefix şi sufix pentru valoarea de latitudine sau longitudine, coordonata returnată se bazează pe prefix.",
  "inputLabel": "Introducere",
  "outputLabel": "Ieşire",
  "cancelButtonLabel": "Anulare",
  "applyButtonLabel": "Aplicare",
  "posNegPrefixLabel": "Adăugaţi prefixul \"+/-\" la numere pozitive şi negative",
  "editCoordinateDialogTitle": "Setare şir format coordonate",
  "rememberDecisionLabel": "Se reţine decizia şi nu mai sunt întrebat în viitor.<br/>",
  "coordinateInputLabel": "Introduceţi coordonatele sau faceţi clic pe hartă",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notaţii găsite care se potrivesc cu introducerea dvs. Confirmaţi ce doriţi să folosiţi:",
  "copyToClipboard": "Copiere în clipboard",
  "formatOutput": "Ieşire format",
  "addNewNotation": "Adăugare notaţie nouă",
  "notationAddedMessage": "Notaţie nouă adăugată",
  "addLabel": "Adăugare",
  "removeCoordinate": "Eliminare coordonată",
  "expandOutput": "Extindere ieşire",
  "latitudeLabel": "Lat.",
  "longitudeLabel": "Lon",
  "quadrantLabel": "Cadran",
  "keyLabel": "Cheie",
  "fifteenDegreeLabel": "Cadran 15Â°",
  "oneDegreeLabel": "Cadran 1Â°",
  "eastingLabel": "Spre est",
  "northingLabel": "Spre nord",
  "zoneLabel": "Zonă",
  "bandLabel": "Bandă",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Pătrat de Grilă",
  "hemisphereLabel": "Emisferă"
});