define({
  "chartSettingLabel": "Nastavení grafu",
  "addNewLabel": "Přidat nové",
  "generalSettingLabel": "Obecná nastavení",
  "searchSourceSettingLabel": "Nastavení zdroje vyhledávání",
  "layerChooser": {
    "title": "Vyberte vrstvu, kterou chcete vykreslit v grafu.",
    "selectPolygonLayerLabel": "Vybrat vrstvu",
    "selectPolygonLayerHintText": "Rada: Pokud konfigurujete několik grafů, vrstvy musí mít stejný typ geometrie.",
    "selectRelatedTableLayerLabel": "Vyberte tabulku přidruženou k vrstvě",
    "selectRelatedTableLayerHintText": "Rada: Zobrazí se pouze tabulky s číselnými hodnotami.",
    "errorInSelectingPolygonLayer": "Vyberte vrstvu, která má přidruženou bodovou vrstvu.",
    "errorInSelectingRelatedLayer": "Vyberte platnou tabulku/vrstvu přidruženou k vrstvě.",
    "polygonLayerNotHavingRelationships": "Vybraná vrstva nemá žádnou přidruženou tabulku/vrstvu."
  },
  "ChartSetting": {
    "sectionTitle": "Nadpis části",
    "sectionTitleHintText": "Rada: Zobrazí se v názvu záhlaví části.",
    "chartTitle": "Název grafu",
    "chartTitleHintText": "Rada: Zobrazí se uprostřed nad grafem.",
    "chartDescription": "Popis",
    "chartDescriptionHintText": "Rada: Zobrazí se pod grafem.",
    "chartType": "Typ grafu",
    "barChart": "Sloupcový graf",
    "pieChart": "Výsečový graf",
    "polarChart": "Polární graf",
    "dataSeriesField": "Pole datových řad",
    "labelField": "Pole popisků",
    "chartColor": "Barva grafu",
    "singleColor": "Jedna barva",
    "colorByTheme": "Barva podle tématu",
    "colorByFieldValue": "Barva podle hodnoty pole",
    "xAxisTitle": "Název osy X",
    "xAxisHintText": "Rada: název osy X",
    "yAxisTitle": "Název osy Y",
    "yAxisHintText": "Rada: název osy Y",
    "fieldColorLabel": "Štítek",
    "fieldColorColor": "Barva",
    "defaultFieldSelectLabel": "Vybrat",
    "errMsgFieldValuesNotFound": "Nepodařilo se nalézt hodnoty pro zvolené pole.",
    "errMsgSectionTitle": "Zadejte název oddílu.",
    "errMsgFieldByValue": "Zvolte hodnotu pole.",
    "settingTabTitle": "Nastavení",
    "layoutTabTitle": "Rozvržení",
    "polarChartSelectFieldsHintText": "Rada: Vyberte pole, která se použijí k vytvoření polárního grafu.",
    "visibilityText": "Viditelnost",
    "fieldNameText": "Název pole",
    "aliasNameText": "Alternativní jméno",
    "errMsgPolarFieldsRequired": "Vyberte tři nebo více polí, která se použijí k vytvoření polárního grafu.",
    "polarChartPolygonFillLabel": "Vyplnit polygon",
    "polarChartPolygonFillHintText": "Rada: Označte toto zaškrtávací políčko, chcete-li zobrazit výplň polygonu v polárním grafu.",
    "viewLayoutLabel": "Rozvržení",
    "ThemeSelector": {
      "themeAdobebricks": "Vepřovice",
      "themeAlgae": "Řasy",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Poušť",
      "themeDistinctive": "Význačné",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Kobylka",
      "themeGrasslands": "Pastviny",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmonie",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irsko",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Mátové",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Mokřad",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Obecná nastavení",
    "locationSymbolLabel": "Symbol grafického umístění",
    "locationSymbolHintText": "Rada: Slouží k zobrazení symbolu pro adresu a umístění určené kliknutím.",
    "refreshIntervalLabel": "Interval aktualizace",
    "refreshIntervalHintText": "Rada: Slouží k obnovení grafů podle tohoto intervalu. Zadejte hodnotu v rozmezí 1–1440 minut.",
    "errMsgRefreshInterval": "Zadejte interval obnovení v rozmezí 0–1440 minut.",
    "symbolPickerPreviewText": "Náhled:",
    "showToolToSelectLabel": "Nastavit tlačítko polohy",
    "showToolToSelectHintText": "Nápověda: Umožňuje nastavit umístění na mapě pomocí tlačítka namísto nastavení umístění při každém kliknutí na mapu."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Nastavení zdroje vyhledávání",
    "searchSourceSettingTitle": "Nastavení zdroje vyhledávání",
    "searchSourceSettingTitleHintText": "Přidejte služby geokódování nebo vrstvy prvků a nakonfigurujte je jako zdroje vyhledávání. Tyto zadané zdroje budou určovat, co je možné vyhledávat v rámci pole pro hledání.",
    "addSearchSourceLabel": "Přidat zdroj vyhledávání",
    "featureLayerLabel": "Vrstva prvků",
    "geocoderLabel": "Geokodér",
    "nameTitle": "Název",
    "generalSettingLabel": "Obecné nastavení",
    "allPlaceholderLabel": "Zástupný text pro vyhledávání všech výsledků:",
    "allPlaceholderHintText": "Nápověda: Zadejte text, který se má zobrazit jako zástupný při prohledávání všech vrstev a geokodéru.",
    "generalSettingCheckboxLabel": "Zobrazit vyskakovací okno pro nalezený prvek nebo umístění",
    "countryCode": "Kódy země nebo oblasti",
    "countryCodeEg": "např. ",
    "countryCodeHint": "Pokud toto pole ponecháte prázdné, prohledají se všechny země a oblasti",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Vyhledávat pouze v aktuálním rozsahu mapy",
    "zoomScale": "Měřítko přiblížení",
    "locatorUrl": "URL geokodéru",
    "locatorName": "Název geokodéru",
    "locatorExample": "Příklad",
    "locatorWarning": "Tato verze služby geokódování není podporována. Tento widget podporuje službu geokódování verze 10.0 a novější.",
    "locatorTips": "Návrhy nejsou k dispozici, protože služba geokódování nepodporuje funkcionalitu návrhů.",
    "layerSource": "Zdroj vrstvy",
    "setLayerSource": "Nastavit zdroj vrstvy",
    "setGeocoderURL": "Nastavit adresu URL geokodéru",
    "searchLayerTips": "Návrhy nejsou k dispozici, protože služba Feature Service nepodporuje funkcionalitu stránkování.",
    "placeholder": "Zástupný text",
    "searchFields": "Prohledávané pole",
    "displayField": "Zobrazované pole",
    "exactMatch": "Přesná shoda",
    "maxSuggestions": "Maximální počet návrhů",
    "maxResults": "Maximální počet výsledků",
    "enableLocalSearch": "Povolit lokální vyhledávání",
    "minScale": "Min. měřítko",
    "minScaleHint": "Když je měřítko mapy větší než toto měřítko, použije se lokální vyhledávání.",
    "radius": "Poloměr",
    "radiusHint": "Stanoví poloměr oblasti okolo centra aktuální mapy, který se použije ke zvýšení hodnoty kandidátů geokódování, aby byli kandidáti nejblíže umístění vráceni jako první.",
    "meters": "metry",
    "setSearchFields": "Nastavit prohledávané pole",
    "set": "Nastavit",
    "fieldName": "Název",
    "invalidUrlTip": "Adresa URL ${URL} je neplatná nebo nepřístupná."
  }
});