define({
  "_widgetLabel": "Koordinātu pārveidošana",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "GMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimālgrādi — platums/garums",
  "DDLongLatNotation": "Decimālgrādi — garums/platums",
  "DDMLatLongNotation": "Grādi, decimālminūtes — platums/garums",
  "DDMLongLatNotation": "Grādi, decimālminūtes — garums/platums",
  "DMSLatLongNotation": "Grādi, minūtes, sekundes — platums/garums",
  "DMSLongLatNotation": "Grādi, minūtes, sekundes — garums/platums",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — joslas burts",
  "UTMHemNotation": "UTM — puslode (Z/D)",
  "formatInput": "Formatēt ievadi",
  "copyAll": "Kopēt visu",
  "copySuccessful": "Kopēšana veiksmīga",
  "copyFailed": "Nevar kopēt. Kā alternatīvu izmantojiet Ctrl+C.",
  "parseCoordinatesError": "Nevar parsēt koordinātas. Lūdzu, pārbaudiet ievadi.",
  "comfirmInputNotation": "Apstiprināt ievades notāciju",
  "latLongWarningMessage": "Tika konstatēts, ka ievades koordinātas platuma vai garuma vērtībai ir gan prefikss, gan sufikss. Atgrieztās koordinātas pamatā ir prefikss.",
  "inputLabel": "Ievade",
  "outputLabel": "Izvade",
  "cancelButtonLabel": "Atcelt",
  "applyButtonLabel": "Lietot",
  "posNegPrefixLabel": "Pievienot prefiksu \"+/-\" pozitīviem un negatīviem skaitļiem",
  "editCoordinateDialogTitle": "Iestatīt koordinātu formātu virkni",
  "rememberDecisionLabel": "Atcerēties manu izvēli un vairs nejautāt. <br/>",
  "coordinateInputLabel": "Ievadiet koordinātas vai noklikšķiniet kartē",
  "zoomLabel": "Mērogmaiņa",
  "multipleNotationLabel": "atrastas notācijas atbilst jūsu ievadei. Lūdzu, apstipriniet, ka vēlaties izmantot:",
  "copyToClipboard": "Kopēt starpliktuvē",
  "formatOutput": "Formatēt izvadi",
  "addNewNotation": "Pievienot jaunu notāciju",
  "notationAddedMessage": "Pievienota jauna notācija",
  "addLabel": "Pievienot",
  "removeCoordinate": "Noņemt koordinātu",
  "expandOutput": "Izvērst izvadi",
  "latitudeLabel": "Plat.",
  "longitudeLabel": "Gar.",
  "quadrantLabel": "Kvadrants",
  "keyLabel": "Atslēga",
  "fifteenDegreeLabel": "15Â° kvad.",
  "oneDegreeLabel": "1Â° kvad.",
  "eastingLabel": "Uz austrumiem",
  "northingLabel": "Uz ziemeļiem",
  "zoneLabel": "Zona",
  "bandLabel": "Saite",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Tīkla kv.",
  "hemisphereLabel": "Puslode"
});