define({
  "_widgetLabel": "Durum Farkındalığı",
  "locate_incident": "Olay Bul",
  "reverse_geocoded_address": "En Yakın Adres",
  "reverse_geocoded_error": "Kullanılabilir değil",
  "now": "ŞİMDİ",
  "wind": "RÜZGAR",
  "SUN": "PAZ",
  "MON": "PTS",
  "TUE": "SAL",
  "WED": "ÇAR",
  "THU": "PER",
  "FRI": "CUM",
  "SAT": "CTS",
  "actionLabel": "Konum Ayarla",
  "drawPoint": "Nokta çiz",
  "drawLine": "Çizgi çiz",
  "drawPolygon": "Alan çiz",
  "saveIncident": "Kaydet",
  "clearIncident": "Yeniden Başla",
  "noFeaturesFound": "Detay bulunamadı.",
  "downloadCSV": "İndir",
  "sum": "Toplam",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Ortalama",
  "count": "SAYIM",
  "area": "ALAN",
  "length": "UZUNLUK",
  "update_btn": "Tamam",
  "delete_btn": "Sil",
  "get_directions": "Yol Tarifi Al",
  "incident": "Oluşum",
  "incidents": "Olaylar",
  "buffer": "Tampon",
  "buffers": "Tamponlar",
  "weather": "Hava Durumu",
  "poweredBy": "Sağlayan",
  "_featureAction_ActionLabel": "Konum Ayarla",
  "_featureAction_AddRemoveActionLabel": "Konum Ekle/Kaldır",
  "snapshot": "SnapShot klasörünü oluşturan Uygulama kimliği:",
  "user_credentials": "Kullanıcının geçerli ayrıcalıkları yok.",
  "notPolySnapShot": "Anlık görüntüsü oluşturmadan önce bir tampon mesafesi belirtin.",
  "notPolyReport": "Rapora eklenecek geçerli sonuç yok.",
  "notValidDownload": "İndirilecek geçerli sonuç yok.",
  "of_append": "-",
  "layer_append": "katman",
  "downloadAll": "Tümünü indir",
  "createSnapshot": "Anlık görüntü oluştur",
  "createReport": "Rapor oluştur",
  "calculated_results": "Özet Bilgiler",
  "closest": "En Yakın Detay",
  "proximity": "Yakınlık",
  "summary": "Özet",
  "groupedSummary": "Gruplanan Sayısı",
  "_count": "Sayım",
  "approximate": "yaklaşık",
  "snapshot_name": "Anlık Görüntü Özelliklerini Ayarla",
  "report_name": "Rapor Özelliklerini Ayarla",
  "invalid_snapshot_name": "Geçersiz anlık görüntü adı.",
  "invalid_report_name": "Geçersiz rapor başlığı.",
  "orientation": "Yönelim",
  "pageSize": "Sayfa Boyutu",
  "comments": "Yorumlar",
  "choose_group": "Gruplar",
  "forecast": "Tahmin",
  "select_group": "Grup Seç",
  "select_group_instruction": "Anlık görüntü oluşturularak seçili grupla paylaşılacak",
  "information_append": " Bilgi",
  "distance": "MESAFE",
  "buffer_invalid": "${min} ve ${max} arasında geçerli bir sayı girin"
});