define({
  "settings": "Inställningar",
  "titleSettings": "Textinställningar",
  "imageSettings": "Bildinställningar",
  "backgroundColor": "Bakgrundsfärg",
  "alignment": "Justering",
  "textSize": "Textstorlek",
  "textColor": "Textfärg",
  "dataSource": "Datakälla",
  "chartSettings": "Diagraminställningar",
  "data": "Data",
  "dataLabels": "Dataetiketter",
  "displayMode": "Visningsläge",
  "featureOption": "Visa värden geoobjekt för geoobjekt",
  "categoryOption": "Visa värden efter kategori",
  "countOption": "Visa geoobjektantal efter kategori",
  "fieldOption": "Visa attributvärden som diagram",
  "categoryField": "Kategorifält",
  "labelField": "Etikettfält",
  "valueFields": "Värdefält",
  "operation": "Åtgärd",
  "sumOption": "Summa",
  "averageOption": "Genomsnitt",
  "minOption": "Minimum",
  "maxOption": "Maximalt",
  "dataFormat": "Dataformat",
  "decimalPlaces": "Decimaler",
  "prefix": "Prefix",
  "suffix": "Suffix",
  "dataType": "Datatyp",
  "featureCount": "Antal geoobjekt",
  "fieldStatistics": "Fältstatistik",
  "display": "Visa",
  "chartColor": "Diagramfärg",
  "horizontalAxis": "Horisontell axel",
  "verticalAxis": "Vertikal axel",
  "legend": "Teckenförklaring",
  "position": "Position",
  "top": "Övre",
  "bottom": "Längst ned",
  "useDataSourceSelection": "Använd markering",
  "dataSourceFilterByExtent": "Filtrera efter utbredning",
  "changeTemplate": "Ändra mall",
  "numberSettings": "Talinställningar",
  "gaugeSettings": "Mätarinställningar",
  "indicators": "Indikatorer",
  "ifValue": "Om värdet",
  "and": "och",
  "numberOperatorIsLessThan": "är mindre än",
  "numberOperatorIsGreaterThan": "är större än",
  "numberOperatorIsBetween": "är mellan",
  "numberOperatorIsEqual": "är lika med",
  "numberOperatorIsNotEqual": "är inte lika med",
  "then": "Så",
  "ratio": "Förhållande",
  "trueValue": "värdet Sant",
  "changeValueColor": "ändrar värdefärgen till",
  "changeGaugeColor": "ändrar mätarfärgen till",
  "setIndicatorIcon": "anger indikatorikonen som",
  "icons": "Icons",
  "style": "Format",
  "placement": "Placering",
  "left": "Vänster",
  "replace": "Ersätt",
  "right": "Höger",
  "color": "Färg",
  "categoryExists": "Kategorin finns redan.",
  "comboxHint": "Ange eller välj en",
  "comboxDisableInputHint": "Välj en",
  "sortBy": "Sortera efter",
  "labelAxis": "Etikett",
  "valueAxis": "Värde",
  "minPeriod": "Minsta period",
  "automatic": "Automatisk",
  "periodsWithOutRecords": "Perioder utan poster",
  "nullValue": "Null-värde",
  "calculatedAsZero": "Beräknas som noll",
  "ignored": "Ignored",
  "maxCategories": "Maximala kategorier",
  "useLayerSymbology": "Använd lagrets symbologi",
  "hollowsize": "Storlek på fördjupning",
  "splitField": "Dela fält",
  "parsingperiodTip": "Det gick inte att beräkna. För många tidsintervall på grund av den korta tolkningsperioden.",
  "manyCategoryTip": "Det gick inte att visa diagrammet. För många kategorier.",
  "setColor": "Ange färg",
  "setTheColorOf": "Ange sedan färgen på",
  "setTheColorAs": "Ange sedan färgen som",
  "ifStr": "Om",
  "as": "som",
  "is": "är",
  "isNot": "är inte",
  "barCluster": "stapelkluster",
  "individualBar": "enskild stapel",
  "allOthers": "Alla andra",
  "category": "Kategori",
  "indicatorSum": "SUMMA",
  "indicatorAve": "GMSNITT",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Ange indikatorer korrekt.",
  "dataRange": "Dataintervall",
  "targetValue": "Målvärde",
  "currentValue": "Aktuellt värde",
  "gaugeColor": "Mätarfärg",
  "min": "Minimum",
  "max": "Maximalt",
  "displayValueIn": "Visa värde i",
  "noData": "Inga data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Varning",
  "noSettingWaring1": "Klicka på ett element för att ange dess egenskaper.",
  "noSettingWaring2": "Dra för att ändra storlek eller ändra ordning för ett element.",
  "donNotShowAgain": "Visa inte igen",
  "changeTemplateWarning": "Det här raderar alla dina inställningar och öppnar en ny tom mall.",
  "requiredFieldWarning": "Det här värdet är obligatoriskt:",
  "dataSourceNotSet": "Ange datakälla.",
  "addIndicatorTip": "Lägg till en indikator",
  "chooseTemplatePopupTitle": "Välj en mall",
  "filterExtentTipWithaTag": "Du kan inaktivera filtret genom <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Extra datakälla</a> under fliken Attribut.",
  "filterExtentTip": "Du kan inaktivera filtret genom Extra datakälla under fliken Attribut.",
  "customColorByCategory": "Anpassa färgen efter kategori",
  "randomColor": "Slumpmässig färg",
  "valueString": "Värde",
  "fieldString": "Fält",
  "includeThresholdValue": "Ta med tröskelvärde",
  "percentage": "Procentandel",
  "colorSchema": "Färgschema",
  "addCategory": "Lägg till kategori",
  "clickToEdit": "Klicka för att redigera",
  "nullText": "Null",
  "others": "Övriga",
  "stringsInTemplate": {
    "name_number": "Nummer",
    "name_gauge": "Mätare",
    "name_vertical_gauge": "Vertikal mätare",
    "name_horizontal_gauge": "Horisontell mätare",
    "name_pie": "Cirkel",
    "name_donut": "Ring",
    "name_bar": "Stapel",
    "name_stacked_bar": "Staplad stapel",
    "name_percentage_stacked_bar": "Procentandel staplad stapel",
    "name_column": "Column",
    "name_stacked_column": "Staplad kolumn",
    "name_percentage_stacked_column": "Procentandel staplad kolumn",
    "name_line": "Linje",
    "name_area": "Område",
    "name_stacked_area": "Staplat område",
    "name_percentage_stacked_area": "Procentandel staplat område",
    "titleOfTheInfographic": "NAMN PÅ INFOGRAFIK",
    "description": "Beskrivning: ytterligare information om denna infografik."
  }
});