define({
  "settings": "Postavke",
  "titleSettings": "Postavke teksta",
  "imageSettings": "Postavke slike",
  "backgroundColor": "Boja pozadine",
  "alignment": "Poravnanje",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "dataSource": "Izvor podataka",
  "chartSettings": "Postavke grafikona",
  "data": "Podaci",
  "dataLabels": "Oznake podataka",
  "displayMode": "Način prikaza",
  "featureOption": "Prikaži vrijednosti geoobjekata po geoobjektu",
  "categoryOption": "Prikaži vrijednosti po kategoriji",
  "countOption": "Prikaži broj geoobjekata po kategoriji",
  "fieldOption": "Prikaži atributne vrijednosti kao grafikone",
  "categoryField": "Polje kategorije",
  "labelField": "Polje oznake",
  "valueFields": "Polja vrijednosti",
  "operation": "Radnja",
  "sumOption": "Zbroj",
  "averageOption": "Prosječno",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Format podataka",
  "decimalPlaces": "Decimalna mjesta",
  "prefix": "Prefiks",
  "suffix": "Sufiks",
  "dataType": "Vrsta podataka",
  "featureCount": "Broj geoobjekata",
  "fieldStatistics": "Statistika polja",
  "display": "Prikaži",
  "chartColor": "Boja grafikona",
  "horizontalAxis": "Vodoravna os",
  "verticalAxis": "Okomita os",
  "legend": "Legenda",
  "position": "Položaj",
  "top": "Vrh",
  "bottom": "Dno",
  "useDataSourceSelection": "Upotrijebi odabir",
  "dataSourceFilterByExtent": "Filtriraj prema obuhvatu",
  "changeTemplate": "Promijeni predložak",
  "numberSettings": "Postavke broja",
  "gaugeSettings": "Postavke mjerača",
  "indicators": "Pokazatelji",
  "ifValue": "Vrijednost ako",
  "and": "i",
  "numberOperatorIsLessThan": "manje je od",
  "numberOperatorIsGreaterThan": "veće je od",
  "numberOperatorIsBetween": "je između",
  "numberOperatorIsEqual": "jednako je",
  "numberOperatorIsNotEqual": "nije jednako",
  "then": "Onda",
  "ratio": "Omjer",
  "trueValue": "Prava vrijednost",
  "changeValueColor": "promijeni boju vrijednosti u",
  "changeGaugeColor": "promijeni boju mjerača u",
  "setIndicatorIcon": "postavi ikonu pokazatelja kao",
  "icons": "Ikone",
  "style": "Stil",
  "placement": "Raspored",
  "left": "Lijevo",
  "replace": "Zamijeni",
  "right": "Desno",
  "color": "Boja",
  "categoryExists": "Kategorija postoji!",
  "comboxHint": "Upišite ili odaberite jedno",
  "comboxDisableInputHint": "Odaberi jedno",
  "sortBy": "Sortiraj prema",
  "labelAxis": "Oznaka",
  "valueAxis": "Vrijednost",
  "minPeriod": "Minimalno razdoblje",
  "automatic": "Automatski",
  "periodsWithOutRecords": "Razdoblja bez zapisa",
  "nullValue": "Nema vrijednosti",
  "calculatedAsZero": "Izračunato kao nula",
  "ignored": "Zanemareno",
  "maxCategories": "Maksimalne kategorije",
  "useLayerSymbology": "Upotrijebi simbologiju sloja",
  "hollowsize": "Veličina šupljeg dijela",
  "splitField": "Podijeli polje",
  "parsingperiodTip": "Računanje nije uspjelo. Previše vremenskih intervala zbog kratkog razdoblja parsiranja.",
  "manyCategoryTip": "Prikaz grafikona nije uspjelo. Previše kategorija.",
  "setColor": "Postavi boju",
  "setTheColorOf": "Zatim postavite boju",
  "setTheColorAs": "Zatim postavite boju na",
  "ifStr": "Ako",
  "as": "kao",
  "is": "je",
  "isNot": "nije",
  "barCluster": "klaster trakastih grafikona",
  "individualBar": "pojedinačni trakasti grafikon",
  "allOthers": "Sve ostalo",
  "category": "Kategorija",
  "indicatorSum": "ZBROJ",
  "indicatorAve": "PROSJ.",
  "indicatorMax": "MAKS.",
  "indicatorMin": "MIN.",
  "setCorrectyIndicatorTip": "Ispravno postavite pokazatelje.",
  "dataRange": "Raspon podataka",
  "targetValue": "Ciljna vrijednost",
  "currentValue": "Trenutna vrijednost",
  "gaugeColor": "Boja mjerača",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Prikaži vrijednosti u",
  "noData": "Nema podataka",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Upozorenje",
  "noSettingWaring1": "Kliknite na element za postavljanje njegovih svojstava.",
  "noSettingWaring2": "Povucite za mijenjanje veličine ili redoslijeda elementa.",
  "donNotShowAgain": "Ne prikazuj ponovo",
  "changeTemplateWarning": "Ovo će izbrisati sve vaše postavke i otvoriti novi prazni predložak.",
  "requiredFieldWarning": "Ova je vrijednosti potrebna:",
  "dataSourceNotSet": "Postavite izvor podataka.",
  "addIndicatorTip": "Dodajte pokazatelja",
  "chooseTemplatePopupTitle": "Odaberite predložak",
  "filterExtentTipWithaTag": "Možete onemogućiti filtar prema <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>izvoru dodatnih podataka</a> na kartici Atribut.",
  "filterExtentTip": "Možete onemogućiti filtar prema izvoru dodatnih podataka na kartici Atribut.",
  "customColorByCategory": "Prilagođena boja po kategoriji",
  "randomColor": "Nasumična boja",
  "valueString": "Vrijednost",
  "fieldString": "Polje",
  "includeThresholdValue": "Uključi vrijednost praga",
  "percentage": "Postotak",
  "colorSchema": "Shema boja",
  "addCategory": "Dodaj kategoriju",
  "clickToEdit": "Kliknite za uređivanje",
  "nullText": "Nema vrijednosti",
  "others": "Ostalo",
  "stringsInTemplate": {
    "name_number": "Broj",
    "name_gauge": "Mjerač",
    "name_vertical_gauge": "Okomiti mjerač",
    "name_horizontal_gauge": "Vodoravni mjerač",
    "name_pie": "Torta",
    "name_donut": "Prsten",
    "name_bar": "Traka",
    "name_stacked_bar": "Složeni trakasti grafikon",
    "name_percentage_stacked_bar": "Složeni trakasti grafikon s postocima",
    "name_column": "Stupac",
    "name_stacked_column": "Složeni stupčasti grafikon",
    "name_percentage_stacked_column": "Složeni stupčasti grafikon s postocima",
    "name_line": "Linija",
    "name_area": "Poligon",
    "name_stacked_area": "Složeni površinski grafikon",
    "name_percentage_stacked_area": "Složeni površinski grafikon s postocima",
    "titleOfTheInfographic": "NASLOV INFOGRAFIKE",
    "description": "Opis: dodatne informacije o ovoj infografici."
  }
});