define({
  "tabs_section_Label": "Registerkarten",
  "addTab": "Registerkarte hinzufügen",
  "layerName": "Layer",
  "layerType": "Analysetyp",
  "layerLabel": "Beschriftung",
  "actions": "Aktionen",
  "closest": "Nächstgelegenes Feature",
  "proximity": "Nachbarschaftsanalyse (Proximity)",
  "summary": "Zusammenfassung",
  "select_lbl": "-- Auswählen --",
  "general_setting_Label": "Allgemeine Einstellungen",
  "units_text_lbl": "Abstandseinheiten",
  "maximum_distance_lbl": "Maximale Entfernung zum nächstgelegenen Feature",
  "buffer_text_lbl": "Pufferbeschriftung",
  "buffer_lbl": "Pufferabstand",
  "buffer_max_lbl": "Maximaler Pufferabstand",
  "buffer_min_lbl": "Minimaler Pufferabstand",
  "buffer_default_lbl": "Standardpufferabstand",
  "not_less_than_max": "Abstand muss kleiner als maximaler Pufferabstand sein",
  "not_between": "Abstand muss zwischen dem minimalen und maximalen Pufferabstand liegen",
  "not_more_than_min": "Abstand muss größer als der minimale Pufferabstand sein",
  "not_valid_number": "Muss eine gültige Zahl sein",
  "invalid_value": "${type}-Wert ist ungültig",
  "routing_checkBox": "Routing aktivieren",
  "weather_Label": "Wettereinstellungen",
  "weather_checkBox": "Wetter aktivieren",
  "weather_map_layers": "Wetter-Layer auswählen...",
  "selected_map_layers": " ausgewählte Wetter-Layer",
  "instruction_weather": "Wetterinformationen im Bereich anzeigen",
  "instruction_weather_layers": "Zusätzliche Wetter-Layer anzeigen",
  "instruction_weather_metric": "Standard-/metrische Werte anzeigen",
  "selectLayers": "Wetter-Layer auswählen",
  "weather_removed_message": "Wetteroptionen sind für dieses Widget nicht mehr verfügbar.",
  "currentlySelectedLayer": "Aus Karten-Layern auswählen",
  "missingTabLabel": "Mindestens eine Registerkarte weist keine Beschriftung auf",
  "missingLayerInWebMap": "Keine operationalen Layer gefunden.",
  "selectFields": "Felder auswählen",
  "addField": "Feld hinzufügen",
  "sum": "Summe",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Durchschnitt",
  "count": "ANZAHL",
  "area": "FLÄCHE",
  "length": "LÄNGE",
  "count_checkBox": "Feature-Anzahl anzeigen",
  "area_checkBox": "Flächensumme anzeigen",
  "length_checkBox": "Längensumme anzeigen",
  "max_records": "Maximaler Grenzwert erreicht",
  "save_label": "Speicheroptionen",
  "save_checkbox": "Speichern aktivieren",
  "report_label": "Berichtsoptionen",
  "report_checkbox": "Bericht aktivieren",
  "csv_label": "CSV-Optionen",
  "csv_checkbox": "Alle Felder exportieren",
  "display_label": "Anzeigeoptionen",
  "display_checkbox": "Features für Zusammenfassung anzeigen",
  "snapshot_label": "Snapshot-Optionen",
  "snapshot_checkbox": "Snapshot aktivieren",
  "must_select_template": "Wählen Sie eine der Bearbeitungsvorlagen unter \"Speicheroptionen\" aus.",
  "count_label": "Beschriftung für Anzahl",
  "area_label": "Flächenbeschriftung",
  "length_label": "Längenbeschriftung",
  "invalid_string_width": "Der Wert ist zu lang. ",
  "layer_type_not_supported": "Layer-Typ wird nicht unterstützt",
  "groupedSummary": "Gruppierte Anzahlen",
  "groupByField": "Nach Feld gruppieren",
  "labelType": "Beschriftung anhängen",
  "prefix": "Als Präfix",
  "suffix": "Als Suffix",
  "need_group_field": "Verwenden Sie die Aktion \"Bearbeiten\", um das Feld \"Gruppieren nach\" zu definieren.",
  "fieldTitle": "Feld",
  "typeTitle": "Typ",
  "actionsTitle": "Aktionen",
  "save_point_checkbox": "Punkte speichern",
  "save_line_checkbox": "Linien speichern",
  "save_poly_checkbox": "Polygone speichern",
  "no_valid_popup_fields": "Es sind keine gültigen Felder im Pop-up vorhanden. Verwenden Sie die Aktion \"Bearbeiten\", um ein Feld zu definieren.",
  "no_valid_fields": "Keine gültigen Felder. Verwenden Sie die Aktion \"Bearbeiten\", um Anzeigeoptionen zu definieren.",
  "incident_label": "Beschriftung für Registerkarte",
  "locate_incident_label": "Beschriftung für Interessenbereich",
  "incident": "Ereignis",
  "locate_incident": "Ereignis verorten",
  "buffer_value": "Pufferabstand",
  "tab_options": "Analyse",
  "export_options": "Ausgabe",
  "instruction_save": "Die Position in einem Feature-Service speichern.",
  "instruction_snapshot": "Eine Webkarte auf Grundlage der Position erstellen.",
  "instruction_report": "Einen gedruckten Bericht der Position erstellen.",
  "instruction_all_fields": "Alle Felder mit CSV-Download exportieren.",
  "data_label": "Einstellungen für die Datenausgabe",
  "layer_error": "Layer fehlt oder ungültig.",
  "visibility_checkBox": "Verwaltung der Layer-Sichtbarkeit deaktivieren",
  "downloadTab": {
    "reportLegend": "Berichtseinstellungen",
    "textColorLabel": "Farbe für Spaltentitel auswählen",
    "setButtonLabel": "Festlegen",
    "printGPServiceLabel": "URL des Druckservice",
    "logoLabel": "Logo",
    "logoChooserHint": "Klicken Sie auf das Symbol des Bilds, um das Bild zu ändern.",
    "footnoteLabel": "Fußnote"
  }
});