define({
  "_widgetLabel": "Koordinaattikonversio",
  "DD": "da",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desimaaliasteet – leveys-/pituusaste",
  "DDLongLatNotation": "Desimaaliasteet – pituus-/leveysaste",
  "DDMLatLongNotation": "Asteet, desimaaliminuutit – leveys-/pituusaste",
  "DDMLongLatNotation": "Asteet, desimaaliminuutit – pituus-/leveysaste",
  "DMSLatLongNotation": "Asteet, minuutit, sekunnit – leveys-/pituusaste",
  "DMSLongLatNotation": "Asteet, minuutit, sekunnit – pituus-/leveysaste",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – kaistan kirjain",
  "UTMHemNotation": "UTM – pallonpuolisko (P/E)",
  "formatInput": "Muodon lähtöaineisto",
  "copyAll": "Kopioi kaikki",
  "copySuccessful": "Kopiointi onnistui",
  "copyFailed": "Kopiointi ei onnistu. Käytä vaihtoehtoisesti näppäinyhdistelmää Ctrl+C.",
  "parseCoordinatesError": "Koordinaattien jäsennys ei onnistu. Tarkista lähtöaineistosi.",
  "comfirmInputNotation": "Vahvista lähtöaineiston esitysmuoto",
  "latLongWarningMessage": "Lähtöaineiston koordinaatissa on havaittu olevan pituusasteen tai leveysasteen sekä etu- että jälkiliite. Palautettu koordinaatti perustuu etuliitteeseen.",
  "inputLabel": "Lähtöaineisto",
  "outputLabel": "Tulosaineisto",
  "cancelButtonLabel": "Peruuta",
  "applyButtonLabel": "Käytä",
  "posNegPrefixLabel": "Lisää etuliite +/- positiivisiin ja negatiivisiin numeroihin",
  "editCoordinateDialogTitle": "Määritä koordinaatin muotomerkkijono",
  "rememberDecisionLabel": "Muista valintani äläkä kysy tietoja uudelleen.<br/>",
  "coordinateInputLabel": "Anna koordinaatit tai napsauta karttaa",
  "zoomLabel": "Tarkennus",
  "multipleNotationLabel": "Lähtöaineistoasi vastaavia esitystapoja on löytynyt. Vahvista käytettävä esitystapa:",
  "copyToClipboard": "Kopioi leikepöydälle",
  "formatOutput": "Muodon tulosaineisto",
  "addNewNotation": "Lisää uusi esitystapa",
  "notationAddedMessage": "Uusi esitystapa lisätty",
  "addLabel": "Lisää",
  "removeCoordinate": "Poista koordinaatti",
  "expandOutput": "Laajenna tulosaineisto",
  "latitudeLabel": "Lev",
  "longitudeLabel": "Pit",
  "quadrantLabel": "Kvadrantti",
  "keyLabel": "Avain",
  "fifteenDegreeLabel": "15Â°:n kvadrantti",
  "oneDegreeLabel": "1Â°:n kvadrantti",
  "eastingLabel": "Itäinen",
  "northingLabel": "Pohjoinen",
  "zoneLabel": "Vyöhyke",
  "bandLabel": "Kaista",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Ruudukkoneliö",
  "hemisphereLabel": "Pallonpuolisko"
});