define({
  "_widgetLabel": "ערנות למצב",
  "locate_incident": "אתר מקרים",
  "reverse_geocoded_address": "הכתובת הקרובה ביותר",
  "reverse_geocoded_error": "לא זמין",
  "now": "עכשיו",
  "wind": "רוח",
  "SUN": "א'",
  "MON": "ב'",
  "TUE": "ג'",
  "WED": "ד'",
  "THU": "ה'",
  "FRI": "ו'",
  "SAT": "שבת",
  "actionLabel": "קבע מיקום",
  "drawPoint": "צייר נקודה",
  "drawLine": "שרטט קו",
  "drawPolygon": "צייר פוליגון",
  "saveIncident": "שמירה",
  "clearIncident": "התחל שוב",
  "noFeaturesFound": "לא נמצאו ישויות",
  "downloadCSV": "הורדה",
  "sum": "סכום",
  "min": "מינימום",
  "max": "מקסימום",
  "avg": "ממוצע",
  "count": "ספירה",
  "area": "אזור",
  "length": "אורך",
  "update_btn": "בוצע",
  "delete_btn": "מחק",
  "get_directions": "קבל הנחיות",
  "incident": "מקרה",
  "incidents": "מקרים",
  "buffer": "חיץ",
  "buffers": "חייצים",
  "weather": "מזג אויר",
  "poweredBy": "מופעל על ידי",
  "_featureAction_ActionLabel": "קבע מיקום",
  "_featureAction_AddRemoveActionLabel": "הוסף/הסר מיקום",
  "snapshot": "תיקיית SnapShot נוצרה על ידי מזהה אפליקציה:",
  "user_credentials": "למשתמש אין הרשאות חוקיות.",
  "notPolySnapShot": "ציין מרחק חיץ לפני יצירת צילום בזק.",
  "notPolyReport": "אין תוצאות חוקיות להוספה לדוח.",
  "notValidDownload": "אין תוצאות חוקיות להורדה.",
  "of_append": "מתוך",
  "layer_append": "שכבה",
  "downloadAll": "הורד הכל",
  "createSnapshot": "צור צילום בזק",
  "createReport": "צור דוח",
  "calculated_results": "סיכום מידע",
  "closest": "היישות הקרובה ביותר",
  "proximity": "קרבה",
  "summary": "סיכום",
  "groupedSummary": "ספירות מקובצות",
  "_count": "מונה",
  "approximate": "שער",
  "snapshot_name": "הגדר מאפייני צילום בזק",
  "report_name": "הגדר מאפייני דוח",
  "invalid_snapshot_name": "שם צילום בזק לא חוקי.",
  "invalid_report_name": "כותרת דוח לא חוקית.",
  "orientation": "מיקום",
  "pageSize": "גודל עמוד",
  "comments": "הערות",
  "choose_group": "קבוצות",
  "forecast": "תחזית",
  "select_group": "בחר קבוצה",
  "select_group_instruction": "צילום הבזק ייווצר וישותף עם הקבוצה שנבחרה",
  "information_append": " מידע",
  "distance": "מרחק",
  "buffer_invalid": "הזן מספר חוקי בין ‎${min}‎ ל-‎${max}‎"
});