define({
  "_widgetLabel": "Situationsmedvetenhet",
  "locate_incident": "Hitta incident",
  "reverse_geocoded_address": "Närmaste adress",
  "reverse_geocoded_error": "Not available",
  "now": "NU",
  "wind": "VIND",
  "SUN": "SÖN",
  "MON": "MÅN",
  "TUE": "TIS",
  "WED": "ONS",
  "THU": "TOR",
  "FRI": "FRE",
  "SAT": "LÖR",
  "actionLabel": "Ange plats",
  "drawPoint": "Rita punkt",
  "drawLine": "Rita linje",
  "drawPolygon": "Rita polygon",
  "saveIncident": "Spara",
  "clearIncident": "Börja om",
  "noFeaturesFound": "Hittade inga objekt.",
  "downloadCSV": "Hämta",
  "sum": "Summa",
  "min": "Minimum",
  "max": "Maximalt",
  "avg": "Genomsnitt",
  "count": "ANTAL",
  "area": "AREA",
  "length": "LÄNGD",
  "update_btn": "Färdig",
  "delete_btn": "Ta bort",
  "get_directions": "Hämta vägbeskrivningar",
  "incident": "Händelse",
  "incidents": "Händelser",
  "buffer": "Buffert",
  "buffers": "Buffertar",
  "weather": "Väder",
  "poweredBy": "Tillhandahålls av",
  "_featureAction_ActionLabel": "Ange plats",
  "_featureAction_AddRemoveActionLabel": "Lägg till/ta bort plats",
  "snapshot": "Mapp för ögonblicksbilder skapad av app-ID:",
  "user_credentials": "Användaren har inte giltig behörighet.",
  "notPolySnapShot": "Ange ett buffertavstånd innan du skapar en ögonblicksbild.",
  "notPolyReport": "Inga giltiga resultat att lägga till i rapporten.",
  "notValidDownload": "Inga giltiga resultat att hämta.",
  "of_append": "av",
  "layer_append": "lager",
  "downloadAll": "Hämta alla",
  "createSnapshot": "Skapa ögonblicksbild",
  "createReport": "Skapa rapport",
  "calculated_results": "Sammanfattad information",
  "closest": "Närmaste geoobjekt",
  "proximity": "Närhet",
  "summary": "Sammanfattning",
  "groupedSummary": "Grupperade antal",
  "_count": "Antal",
  "approximate": "ungefärlig",
  "snapshot_name": "Ange egenskaper för ögonblicksbild",
  "report_name": "Ange rapportegenskaper",
  "invalid_snapshot_name": "Ogiltigt namn för ögonblicksbild.",
  "invalid_report_name": "Ogiltig rapporttitel",
  "orientation": "Riktning",
  "pageSize": "Sidstorlek",
  "comments": "Kommentarer",
  "choose_group": "Grupper",
  "forecast": "Prognos",
  "select_group": "Välj grupp",
  "select_group_instruction": "Ögonblicksbilden skapas och delas med den valda gruppen",
  "information_append": " Information",
  "distance": "AVSTÅND",
  "buffer_invalid": "Ange ett tal mellan ${min} och ${max}"
});