define({
  "chartSettingLabel": "图表设置",
  "addNewLabel": "新增",
  "generalSettingLabel": "常规设置",
  "searchSourceSettingLabel": "搜索源设置",
  "layerChooser": {
    "title": "选择要制表的图层",
    "selectPolygonLayerLabel": "选择图层",
    "selectPolygonLayerHintText": "提示: 如果配置多个图表，则图层必须为相同的几何类型",
    "selectRelatedTableLayerLabel": "选择图层的相关表",
    "selectRelatedTableLayerHintText": "提示: 仅显示含数值字段的表",
    "errorInSelectingPolygonLayer": "请选择具有相关点图层的图层。",
    "errorInSelectingRelatedLayer": "请选择图层的有效相关表/图层。",
    "polygonLayerNotHavingRelationships": "所选图层不具有任何相关表/图层。"
  },
  "ChartSetting": {
    "sectionTitle": "章节标题",
    "sectionTitleHintText": "提示: 显示在章节页眉标题中",
    "chartTitle": "图表标题",
    "chartTitleHintText": "提示: 居中显示在图表顶部",
    "chartDescription": "说明",
    "chartDescriptionHintText": "提示: 显示在图表下方",
    "chartType": "图表类型",
    "barChart": "条形图",
    "pieChart": "饼图",
    "polarChart": "极坐标图",
    "dataSeriesField": "数据系列字段",
    "labelField": "标注字段",
    "chartColor": "图表颜色",
    "singleColor": "单色",
    "colorByTheme": "按主题分类的颜色",
    "colorByFieldValue": "按字段值分类的颜色",
    "xAxisTitle": "X 轴标题",
    "xAxisHintText": "提示: X 轴标题",
    "yAxisTitle": "Y 轴标题",
    "yAxisHintText": "提示: Y 轴标题",
    "fieldColorLabel": "标注",
    "fieldColorColor": "颜色",
    "defaultFieldSelectLabel": "选择",
    "errMsgFieldValuesNotFound": "无法找到所选字段的值",
    "errMsgSectionTitle": "请输入章节标题",
    "errMsgFieldByValue": "请选择字段值",
    "settingTabTitle": "设置",
    "layoutTabTitle": "布局",
    "polarChartSelectFieldsHintText": "提示: 选择字段以生成极坐标图",
    "visibilityText": "可见性",
    "fieldNameText": "字段名",
    "aliasNameText": "别名",
    "errMsgPolarFieldsRequired": "请选择三个或更多的字段以生成极坐标图",
    "polarChartPolygonFillLabel": "填充面",
    "polarChartPolygonFillHintText": "提示: 选择复选框以显示填充极坐标图的面",
    "viewLayoutLabel": "布局",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "常规设置",
    "locationSymbolLabel": "图形位置符号",
    "locationSymbolHintText": "提示: 用于显示地址符号和单击位置",
    "refreshIntervalLabel": "刷新间隔",
    "refreshIntervalHintText": "提示: 用于根据此间隔刷新图表。请在 1 到 1440 分钟的区间内指定一个值",
    "errMsgRefreshInterval": "请在 0 到 1440 分钟的区间内指定刷新间隔",
    "symbolPickerPreviewText": "预览:",
    "showToolToSelectLabel": "设置位置按钮",
    "showToolToSelectHintText": "提示：请提供要在地图上设置地点的按钮，而不是始终在点击地图时设置地点"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "搜索源设置",
    "searchSourceSettingTitle": "搜索源设置",
    "searchSourceSettingTitleHintText": "添加并将地理编码服务或要素图层配置为搜索源。这些指定的源决定了搜索框中的可搜索内容",
    "addSearchSourceLabel": "添加搜索源",
    "featureLayerLabel": "要素图层",
    "geocoderLabel": "地理编码器",
    "nameTitle": "名称",
    "generalSettingLabel": "常规设置",
    "allPlaceholderLabel": "用于搜索全部内容的占位符文本：",
    "allPlaceholderHintText": "提示：搜索所有图层和地理编码器时请输入要显示为占位符的文本",
    "generalSettingCheckboxLabel": "显示已找到要素或位置的弹出窗口",
    "countryCode": "国家或区域代码",
    "countryCodeEg": "例如 ",
    "countryCodeHint": "将此值留空可搜索所有国家和地区",
    "questionMark": "?",
    "searchInCurrentMapExtent": "仅在当前地图范围内搜索",
    "zoomScale": "缩放比例",
    "locatorUrl": "地理编码器 URL",
    "locatorName": "地理编码器名称",
    "locatorExample": "示例",
    "locatorWarning": "不支持此版本的地理编码服务。该微件支持 10.0 及更高版本的地理编码服务。",
    "locatorTips": "由于地理编码服务不支持建议功能，因此建议不可用。",
    "layerSource": "图层源",
    "setLayerSource": "设置图层源",
    "setGeocoderURL": "设置地理编码器 URL",
    "searchLayerTips": "由于要素服务不支持分页功能，因此建议不可用。",
    "placeholder": "占位符文本",
    "searchFields": "搜索字段",
    "displayField": "显示字段",
    "exactMatch": "完全匹配",
    "maxSuggestions": "最大建议数",
    "maxResults": "最大结果数",
    "enableLocalSearch": "启用本地搜索",
    "minScale": "最小比例",
    "minScaleHint": "如果地图比例大于此比例，将使用本地搜索",
    "radius": "半径",
    "radiusHint": "指定以当前地图中心为中心的区域半径，用于提升地理编码候选项的等级，以便先返回距离位置最近的候选项",
    "meters": "米",
    "setSearchFields": "设置搜索字段",
    "set": "设置",
    "fieldName": "名称",
    "invalidUrlTip": "URL ${URL} 无效或不可访问。"
  }
});