define({
  "_widgetLabel": "Distanza e direzione",
  "tabLineTitle": "Linea",
  "tabCircleTitle": "Cerchio",
  "tabEllipseTitle": "Ellisse",
  "tabRingsTitle": "Anelli",
  "multipleNotationsMessage": " Notazioni corrispondenti all'input. Confermare quale si desidera utilizzare:",
  "invalidCoordinateMessage": "Coordinate non valide",
  "confirmInputNotationMessage": "Confermare l'input annotato.",
  "prefixSuffixMessage": "La coordinata di input è stata rilevata come composta da prefisso e suffisso per il valore di latitudine o di longitudine, ma la coordinata restituita è contiene solo il prefisso.",
  "rememberDecisionMessage": "Ricorda l'impostazione e non chiudere più.<br/>",
  "majorAxisTooltipMessage": "Fare clic sulla lunghezza dell’asse maggiore",
  "minorAxisTooltipMessage": "Spostare il mouse indietro nella posizione iniziale per impostare l'asse minore e terminare l'ellisse del disegno",
  "clickToFinishLineMessage": "Fare clic per completare il disegno della linea",
  "doubleClickEllipseMesage": "Fare doppio clic per completare il disegno degli anelli di intervallo",
  "invalidCoordinateTypeMessage": "Impossibile determinare il tipo di coordinate di input. Controllare l'input.",
  "noCenterPointSetMessage": "Nessun punto centrale impostato. Controllare l'input.",
  "ellipseMajorAxis": "Asse maggiore",
  "ellipseMinorAxis": "Asse minore",
  "degreesRangeMessage": "Il valore deve essere compreso tra 0 e 360",
  "millsRangeMessage": "Il valore deve essere compreso tra 0 e 6400",
  "lengthLabel": "Lunghezza",
  "angleLabel": "Angolo",
  "startPointLabel": "Punto di partenza",
  "endPointLabel": "Punto finale",
  "centerPointLabel": "Punto centrale",
  "distanceTableErrorMessage": "La tabella delle distanze è vuota. Assicurarsi di inserire qualche distanza.",
  "setCoordFormatStringMessage": "Imposta stringa di formato coordinata",
  "prefixMessage": "Aggiungere il prefisso '+/-' ai numeri positivi e negativi",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Gradi decimali - Latitudine/Longitudine",
  "DDLongLatNotation": "Gradi decimali - Longitudine/Latitudine",
  "DDMLatLongNotation": "(DDM) Degrees Decimal Minutes - Latitude/Longitude",
  "DDMLongLatNotation": "(DDM) Degrees Decimal Minutes - Longitude/Latitude",
  "DMSLatLongNotation": "(DDS) Degrees Minutes Seconds - Latitude/Longitude",
  "DMSLongLatNotation": "(DDS) Degrees Minutes Seconds - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisphere (N/S)",
  "circleTitle": "Crea cerchio da",
  "radiusLabel": "Raggio",
  "diameterLabel": "Diametro",
  "startPointPlaceHolderLabel": "Immettere le coordinate",
  "formatInputLabel": "Input formato",
  "drawCircleLabel": "Disegna cerchio",
  "drawLineLabel": "Disegna linea",
  "createCircleInteractivelyLabel": "Crea cerchio in modo interattivo",
  "rangeErrorMessage": "Raggio o diametro non valido",
  "numericInvalidMessage": "Inserire un valore numerico",
  "timeLabel": "Ora",
  "invalidTimeMessage": "Valore dell’ora non valido",
  "hoursLabel": "Ore",
  "minutesLabel": "Minuti",
  "secondsLabel": "Secondi",
  "rateLabel": "Grado",
  "invalidDistanceMessage": "Valore distanza non valida",
  "feetSecondsLabel": "Piedi al secondo",
  "feetHourLabel": "Piedi all’ora",
  "kmSecondLabel": "Chilometri al secondo",
  "kmHourLabel": "Chilometri all'ora",
  "metersSecondLabel": "Metri al secondo",
  "metersHourLabel": "Metri all’ora",
  "milesSecondLabel": "Miglia al secondo",
  "milesHourLabel": "Miglia all’ora",
  "nauticalMilesSecondLabel": "Miglia nautiche al secondo",
  "nauticalMilesHourLabel": "Miglia nautiche all’ora",
  "clearGraphicsLabel": "Cancella grafici",
  "ellipseTypeLabel": "Tipo di ellisse",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Completa",
  "drawEllipseLabel": "Disegna ellisse",
  "createEllipseInteractively": "Crea ellisse in modo interattivo",
  "axisLabel": "Asse",
  "majorRadiusLabel": "Maggiore (raggio)",
  "axisErrorMessage": "Il valore deve essere maggiore di 0",
  "minorRadiusLabel": "Minore (raggio)",
  "orientationLabel": "Orientamento",
  "orientationErrorMessage": "Il valore deve essere compreso tra 0 e 360",
  "warningMessage": "Avvertenza: i grafici generati usando lo strumento ellisse non sono geodetici",
  "fromLabel": "Da",
  "distanceBearingLabel": "Distanza e rilevamento",
  "pointsLabel": "Punti",
  "createLineInteractively": "Crea linea in modo interattivo",
  "lineLengthErrorMessage": "Lunghezza linea non valida",
  "degreesLabel": "Gradi",
  "milsLabel": "Migliaia",
  "lineTypeLabel": "Tipo",
  "interactiveLabel": "Interattivo",
  "fixedLabel": "Fisso",
  "originLabel": "Origine",
  "cumulativeLabel": "Cumulativo",
  "numberOfRingsLabel": "Numero di anelli",
  "ringsErrorMessage": "Numero di anelli non valido",
  "distanceBetweenRingsLabel": "Distanza tra anelli",
  "ringsDecimalErrorMessage": "Inserire un valore numerico con 2 posizioni decimali",
  "distanceUnitsLabel": "Unità Distanza",
  "distancesLabel": "Distanza",
  "numberOfRadialsLabel": "Numero di radiali",
  "upLabel": "Su",
  "downLabel": "Giù",
  "deleteLabel": "Elimina",
  "radialsErrorMessage": "Numero di radiali non valido. Il massimo consentito è di 360.",
  "addPointLabel": "Aggiungi Punto",
  "valueLabel": "Valore",
  "valueText": "Immetti valore",
  "actionLabel": "Azione"
});