define({
  root: ({
    serviceUrl: "Set service url:",
    minIntSpacingLabel: "Minimum Grid Size",
    lineOpacityLabel: "Line Opacity",
    labelOpacityLabel: "Label Opacity",
    centerLabelOpacityLabel: "Center Label Opacity",
    gridZonePlacementLabel: "Grid Zone Label Placement",
    verticalLineLabels: "Vertical Line Labels",
    styleHeaderLabel: "Style",
    indexHeaderLabel: "Grid Component",
    colorHeaderLabel: "Color",
    fontSizeHeaderLabel: "Font Size",
    lineWidthHeaderLabel: "Line Width",
    horizontalLabel: "Horizontal",
    verticalLabel: "Vertical",
    upperLeftLabel: "Upper Left",
    upperRightLabel: "Upper Right",
    lowerLeftLabel: "Lower Left",
    lowerRightLabel: "Lower Right",
    centerLabel: "Center",
    errorMessage: "The configuration page contains errors. Please fix before saving.",
    checkBoxLabel: "Display grid when widget is closed",
    checkBoxLabelDashboard: "Display grid",
    gzd: "Grid Zone Designator (GZD)",
    gsid: "100,000-meter Grid Square Identification (GSID)",
    grid10k: "10,000-meter Grid Lines",
    grid1k: "1,000-meter Grid Lines",
    grid100m: "100-meter Grid Lines",
    grid10m: "10-meter Grid Lines",
    switchBasemap: "Switch Basemap"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "sl": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
