define({
  "gridTabLabel": "Cuadrícula",
  "labelTabLabel": "Etiquetas",
  "referenceSystemTabLabel": "Sistema de referencia",
  "gridTabDescription": "Definir el aspecto y el comportamiento de las celdas de la cuadrícula.",
  "cellOutlineColor": "Color de contorno de celda",
  "cellFillColor": "Color de relleno de celda",
  "transparency": "Transparencia",
  "cellShapeDropDown": "Forma de celda",
  "default": "Rectángulo",
  "hexagon": "Hexágono",
  "cellUnitsDropDown": "Unidades de celda",
  "miles": "Millas",
  "kilometers": "Kilómetros",
  "feet": "Pies",
  "meters": "Metros",
  "yards": "Yardas",
  "nautical-miles": "Millas náuticas",
  "gridOriginDropDown": "Origen de la cuadrícula",
  "lowerLeft": "Inferior izquierda",
  "lowerRight": "Inferior derecha",
  "upperLeft": "Superior izquierda",
  "upperRight": "Superior derecha",
  "center": "Centro",
  "labelTabDescription": "Definir el aspecto y el comportamiento de las etiquetas de la cuadrícula.",
  "labelSettings": "Estilo de etiqueta",
  "font": "Fuente",
  "textSize": "Tamaño de texto",
  "textColor": "Color del texto",
  "halo": "Halo",
  "show": "Mostrar",
  "labelTypeDropDown": "Tipo de etiqueta",
  "alphaNumeric": "Alfanumérico",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Numérico",
  "labelDirectionDropDown": "Dirección de la etiqueta",
  "horizontal": "Horizontal",
  "vertical": "Vertical",
  "labelOriginDropDown": "Origen de la etiqueta",
  "referenceSystemlTabDescription": "Definir el sistema de referencia predeterminado.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Bloquear ajustes: de esta forma impedirá que el usuario cambie cualquiera de los ajustes configurados dentro del widget"
});