define({
  "gridTabLabel": "Gitternetz",
  "labelTabLabel": "Beschriftungen",
  "referenceSystemTabLabel": "Bezugssystem",
  "gridTabDescription": "Legen Sie das Aussehen und Verhalten der Gitterzellen fest.",
  "cellOutlineColor": "Farbe der Zellenumrisslinie",
  "cellFillColor": "Füllfarbe der Zelle",
  "transparency": "Transparenz",
  "cellShapeDropDown": "Zellenform",
  "default": "Rechteck",
  "hexagon": "Hexagon",
  "cellUnitsDropDown": "Zelleneinheiten",
  "miles": "Meilen",
  "kilometers": "Kilometer",
  "feet": "Fuß",
  "meters": "Meter",
  "yards": "Yards",
  "nautical-miles": "Seemeilen",
  "gridOriginDropDown": "Grid-Ursprung",
  "lowerLeft": "Unten links",
  "lowerRight": "Unten rechts",
  "upperLeft": "Oben links",
  "upperRight": "Oben rechts",
  "center": "Zentriert",
  "labelTabDescription": "Legen Sie das Aussehen und Verhalten der Gitternetzbeschriftungen fest.",
  "labelSettings": "Beschriftungs-Style",
  "font": "Schriftart",
  "textSize": "Textgröße",
  "textColor": "Textfarbe",
  "halo": "Halo",
  "show": "Einblenden",
  "labelTypeDropDown": "Beschriftungstyp",
  "alphaNumeric": "Alphanumerisch",
  "alphaAlpha": "Alpha-Alpha",
  "numeric": "Numerisch",
  "labelDirectionDropDown": "Beschriftungsrichtung",
  "horizontal": "Horizontal",
  "vertical": "Vertikal",
  "labelOriginDropDown": "Beschriftungsursprung",
  "referenceSystemlTabDescription": "Legen Sie das standardmäßige Bezugssystem fest.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Einstellungen sperren: Damit wird sichergestellt, dass der Benutzer keine Änderungen an den Konfigurationseinstellungen im Widget durchführen kann."
});