define({
  "_widgetLabel": "Svesnost situacije",
  "locate_incident": "Lociraj incident",
  "reverse_geocoded_address": "Najbliža adresa",
  "reverse_geocoded_error": "Nije dostupno",
  "now": "SADA",
  "wind": "VETAR",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "UTO",
  "WED": "SRE",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SUB",
  "actionLabel": "Podesi lokaciju",
  "drawPoint": "Nacrtaj tačku",
  "drawLine": "Nacrtaj liniju",
  "drawPolygon": "Nacrtaj poligon",
  "saveIncident": "Sačuvaj",
  "clearIncident": "Počni iz početka",
  "noFeaturesFound": "Nema pronađenih geoobjekata.",
  "downloadCSV": "Preuzmi",
  "sum": "Zbir",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Prosečno",
  "count": "BROJAČ",
  "area": "POVRŠINA",
  "length": "DUŽINA",
  "update_btn": "Završeno",
  "delete_btn": "Obriši",
  "get_directions": "Traži uputstva za navigaciju",
  "incident": "Incident",
  "incidents": "Incidenti",
  "buffer": "Zona bliskosti",
  "buffers": "Zone bliskosti",
  "weather": "Vreme",
  "poweredBy": "Omogućeno od",
  "_featureAction_ActionLabel": "Podesi lokaciju",
  "_featureAction_AddRemoveActionLabel": "Dodaj/ukloni lokaciju",
  "snapshot": "ID aplikacije je kreirao SnapShot fasciklu:",
  "user_credentials": "Korisnik nema odgovarajuće privilegije.",
  "notPolySnapShot": "Navedite rastojanje zone bliskosti pre nego što kreirate Snapshot.",
  "notPolyReport": "Nema važećih rezultata za dodavanje u izveštaj.",
  "notValidDownload": "Nema važećih rezultata za preuzimanje.",
  "of_append": "od",
  "layer_append": "sloj",
  "downloadAll": "Preuzmi sve",
  "createSnapshot": "Kreiraj Snapshot",
  "createReport": "Kreiraj izveštaj",
  "calculated_results": "Sumirane informacije",
  "closest": "Najbliži geoobjekat",
  "proximity": "Blizina",
  "summary": "Rezime",
  "groupedSummary": "Grupisani brojači",
  "_count": "Brojač",
  "approximate": "približno",
  "snapshot_name": "Postavi svojstva Snapshot-a",
  "report_name": "Postavi svojstva izveštaja",
  "invalid_snapshot_name": "Nevažeće ime Snapshota-a.",
  "invalid_report_name": "Nevažeći naslov izveštaja.",
  "orientation": "Orijentacija",
  "pageSize": "Veličina stranice",
  "comments": "Komentari",
  "choose_group": "Grupe",
  "forecast": "Prognoza",
  "select_group": "Izaberite grupu",
  "select_group_instruction": "Snapshot će biti kreiran i podeljen sa izabranim grupama",
  "information_append": " Informacije",
  "distance": "RASTOJANJE",
  "buffer_invalid": "Unesite važeći broj između ${min} i ${max}"
});