define({
  "routeUrl": "Maršruta URL",
  "locatorUrl": "Ģeokodētāja URL",
  "geocoderOptions": "Ģeokodētāja opcijas",
  "autoComplete": "Automātiski pabeigt",
  "maximumSuggestions": "Maksimālais ieteikumu skaits",
  "minCharacters": "Minimālais rakstzīmju skaits",
  "searchDelay": "Meklēšanas aizkave",
  "placeholder": "Vietturis",
  "routeOptions": "Maršruta opcijas",
  "directionsLanguage": "Norādījumu valoda",
  "directionsLengthUnits": "Norādījumu garuma vienības",
  "directionsOutputType": "Norādījumu izvades veids",
  "impedanceAttribute": "Impedances atribūts",
  "kilometers": "Kilometri",
  "miles": "Jūdzes",
  "meters": "Metri",
  "feet": "Pēdas",
  "yards": "Jardi",
  "nauticalMiles": "Jūras jūdzes",
  "parametersTip": "Lūdzu, iestatiet parametrus pareizi!",
  "complete": "Pabeigts",
  "completeNoEvents": "Pabeigts bez notikumiem",
  "instructionsOnly": "Tikai instrukcijas",
  "standard": "Standarta",
  "summaryOnly": "Tikai kopsavilkums",
  "travelModesUrl": "Ceļošanas režīmu URL",
  "searchPlaceholder": "Atrast adresi vai vietu",
  "trafficLayerUrl": "Satiksmes slāņa URL",
  "presetDestinations": "Iepriekš iestatīti apstāšanās punkti",
  "startPoint": "Sākuma punkts",
  "endPoint": "Beigu punkts",
  "destinationHolder": "Adrese vai koordinātes",
  "optional": "Pēc izvēles."
});