define({
  "chartSettingLabel": "Diagraminställningar",
  "addNewLabel": "Lägg till ny",
  "generalSettingLabel": "Allmänna inställningar",
  "searchSourceSettingLabel": "Sök källinställningar",
  "layerChooser": {
    "title": "Välj vilka lager som ska användas i diagrammet",
    "selectPolygonLayerLabel": "Välj lager",
    "selectPolygonLayerHintText": "Tips: Om du konfigurerar flera diagram, måste lagren vara av samma geometrityp",
    "selectRelatedTableLayerLabel": "Välj en tabell med en relation till lagret",
    "selectRelatedTableLayerHintText": "Tips: Endast tabeller med numeriska fält visas",
    "errorInSelectingPolygonLayer": "Välj ett lager som har ett tillhörande punktlager.",
    "errorInSelectingRelatedLayer": "Välj en giltig relaterad tabell eller ett giltigt relaterat lager som ska användas i lagret.",
    "polygonLayerNotHavingRelationships": "Det markerade lagret har inte någon relaterad tabell eller något relaterat lager."
  },
  "ChartSetting": {
    "sectionTitle": "Avsnittets rubrik",
    "sectionTitleHintText": "Tips: Visas i avsnittsrubriken",
    "chartTitle": "Diagramtitel",
    "chartTitleHintText": "Tips: Visas centrerad ovanför diagrammet",
    "chartDescription": "Beskrivning",
    "chartDescriptionHintText": "Tips: Visas under diagrammet",
    "chartType": "Diagramtyp",
    "barChart": "Liggande stapeldiagram",
    "pieChart": "Cirkeldiagram",
    "polarChart": "Radardiagram",
    "dataSeriesField": "Fält för dataserie",
    "labelField": "Etikettfält",
    "chartColor": "Diagramfärg",
    "singleColor": "En färg",
    "colorByTheme": "Färg enligt tema",
    "colorByFieldValue": "Färg enligt fältvärde",
    "xAxisTitle": "Titel för X-axel",
    "xAxisHintText": "Tips: Titel för X-axel",
    "yAxisTitle": "Titel för Y-axel",
    "yAxisHintText": "Tips: Titel för Y-axel",
    "fieldColorLabel": "Etikett",
    "fieldColorColor": "Färg",
    "defaultFieldSelectLabel": "Välj",
    "errMsgFieldValuesNotFound": "Det gick inte att hitta några värden för det valda fältet",
    "errMsgSectionTitle": "Ange avsnittstiteln",
    "errMsgFieldByValue": "Ange fältvärdet",
    "settingTabTitle": "Inställning",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Tips: Välj fält för att generera radardiagram",
    "visibilityText": "Synlighet",
    "fieldNameText": "Fältnamn",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Välj tre eller fler fält för att generera radardiagram",
    "polarChartPolygonFillLabel": "Fyll polygon",
    "polarChartPolygonFillHintText": "Tips: Markera kryssrutan för att visa polygonfyllning i radardiagram",
    "viewLayoutLabel": "Layout",
    "ThemeSelector": {
      "themeAdobebricks": "Adobe-tegel",
      "themeAlgae": "Alger",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlåSkymning",
      "themeCubanShirts": "Kubaskjortor",
      "themeDesert": "Öken",
      "themeDistinctive": "Distinkt",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Gräshoppa",
      "themeGrasslands": "Grässtäpp",
      "themeGreySkies": "GråSkyar",
      "themeHarmony": "Harmoni",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurpur",
      "themeSageToLime": "SalviaTillLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "Strandkant",
      "themeWetlandText": "Våtmark",
      "themePlotKitblue": "PlotKit.blå",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.grön",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.lila",
      "themePlotKitred": "PlotKit.röd"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Allmänna inställningar",
    "locationSymbolLabel": "Grafisk platssymbol",
    "locationSymbolHintText": "Tips: Används för att visa symbolen för adress och plats som någon klickat på",
    "refreshIntervalLabel": "Uppdateringsintervall",
    "refreshIntervalHintText": "Tips: Används för att uppdatera diagram baserat på detta intervall. Ange ett värde mellan 1 och 1 440 minuter",
    "errMsgRefreshInterval": "Ange ett värde för uppdateringsfrekvensen mellan 0 och 1 440 minuter",
    "symbolPickerPreviewText": "Förhandsgranska:",
    "showToolToSelectLabel": "Ange plats-knapp",
    "showToolToSelectHintText": "Tips: Tillhandahåller en knapp för att ange platsen på kartan, i stället för att alltid ange plats när kartan klickas"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Sök källinställningar",
    "searchSourceSettingTitle": "Sök källinställningar",
    "searchSourceSettingTitleHintText": "Lägg till och konfigurera geokodningstjänster eller geoobjektslager som sökkällor. Dessa angivna källor avgör vad som går att söka i sökrutan",
    "addSearchSourceLabel": "Lägg till sökkälla",
    "featureLayerLabel": "geoobjektlager",
    "geocoderLabel": "Geokodare",
    "nameTitle": "Namn",
    "generalSettingLabel": "Allmän inställning",
    "allPlaceholderLabel": "Platshållartext för sökning i alla:",
    "allPlaceholderHintText": "Tips: Ange text som ska visas som platshållare när du söker i alla lager och geokodare",
    "generalSettingCheckboxLabel": "Visa popup för det hittade geoobjekt eller den hittade platsen",
    "countryCode": "Lands- eller regionkoder",
    "countryCodeEg": "till exempel ",
    "countryCodeHint": "Om du lämnar det här värdet tomt sker sökningen i alla länder och regioner",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Sök bara i den aktuella kartutbredningen",
    "zoomScale": "Zoomningsskala",
    "locatorUrl": "Geokodarens URL",
    "locatorName": "Geokodarens namn",
    "locatorExample": "Exempel",
    "locatorWarning": "Den här versionen av geokodningstjänsten stöds inte. Widgeten har stöd för geokodningstjänsten 10.0 och högre.",
    "locatorTips": "Förslag finns inte tillgängliga eftersom geokodningstjänsten inte har stöd för förslagsfunktionen.",
    "layerSource": "Lagerkälla",
    "setLayerSource": "Ange lagerkälla",
    "setGeocoderURL": "Ange URL till geokodare",
    "searchLayerTips": "Förslag finns inte tillgängliga eftersom geoobjektstjänsten inte har stöd för pagineringsfunktionen.",
    "placeholder": "Platshållartext",
    "searchFields": "Sökfält",
    "displayField": "Visa fält",
    "exactMatch": "Exakt matchning",
    "maxSuggestions": "Maximalt antal förslag",
    "maxResults": "Maximala resultat",
    "enableLocalSearch": "Aktivera lokal sökning",
    "minScale": "Minimiskala",
    "minScaleHint": "När kartans skala är större än denna skala används lokal sökning",
    "radius": "Radie",
    "radiusHint": "Anger radien för ett område kring den aktuella kartans mitt som ska användas för att höja rangordningen för geokodningskandidater så att de kandidater som är närmast platsen returneras först",
    "meters": "Meter",
    "setSearchFields": "Ange sökfält",
    "set": "Ange",
    "fieldName": "Namn",
    "invalidUrlTip": "URL:en ${URL} är ogiltig eller går inte att öppna."
  }
});