define({
  "_widgetLabel": "Množični urejevalnik atributov",
  "widgetIntroSelectByArea": "Uporabite eno od orodij v nadaljevanju za ustvarjanje niza izbranih geoobjektov za posodabljanje. Če je vrstica <font class='maxRecordInIntro'>označena</font>, je bilo preseženo maksimalno število zapisov.",
  "widgetIntroSelectByFeature": "Uporabite orodje v nadaljevanju za izbiro geoobjekta iz sloja <font class='layerInIntro'>${0}</font> . Ta geoobjekt bo uporabljen za izbiro in posodabljanje vseh geoobjektov, ki se sekajo. Če je vrstica <font class='maxRecordInIntro'>označena</font>, je bilo preseženo maksimalno število zapisov.",
  "widgetIntroSelectByFeatureQuery": "Uporabite orodje v nadaljevanju za izbiro iz <font class='layerInIntro'>${0}</font> . Atribut tega geoobjekta <font class='layerInIntro'>${1}</font> bo uporabljen za poizvedbo slojev v nadaljevanju in posodabljanje prikazanih geoobjektov. Če je vrstica <font class='maxRecordInIntro'>označena</font>, je bilo preseženo maksimalno število zapisov.",
  "widgetIntroSelectByQuery": "Vnesite vrednost za ustvarjanje izbranega nabora. Če je vrstica <font class='maxRecordInIntro'>osvetljena</font>, je bilo preseženo maksimalno število zapisov.",
  "layerTable": {
    "colLabel": "Ime sloja",
    "numSelected": "št.",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Uredljivi sloji niso konfigurirani",
  "editorPopupTitle": "Množični urejevalnik atributov",
  "editorPopupSaveBtn": "Shrani",
  "editorPopupMultipleValues": "",
  "clear": "Počisti",
  "featuresUpdated": "Posodobljenih je ${0}/${1} geoobjektov",
  "featuresSelected": "Izbranih je ${0} geoobjektov",
  "featuresSkipped": "Zaobideno",
  "search": "Iskanje",
  "queryInput": "Vnesite vrednost za poizvedbo",
  "noFilterTip": "Če izraz filtra ni določen, bo ta naloga poizvedbe prikazala vse geoobjekte v navedenih virih podatkov.",
  "setFilterTip": "Pravilno nastavite filter.",
  "filterPopup": "Filtriraj sloj",
  "cancel": "Prekliči",
  "noValue": "Ni vrednosti",
  "emptyString": "Prazen niz",
  "existingValue": "Obdrži obstoječo vrednost",
  "newDate": "Nov datum",
  "valueChooser": "Izberi/vpiši vrednost",
  "ok": "V redu",
  "drawBox": {
    "point": "Točka",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Prostoročna polilinija",
    "extent": "Pravokotnik",
    "polygon": "Poligon",
    "freehandPolygon": "Prostoročni poligon",
    "clear": "Počisti",
    "addPointToolTip": "Kliknite, da počistite to območje",
    "addShapeToolTip": "Narišite obliko za izbiro geoobjektov",
    "freehandToolTip": "Pritisnite in držite za risanje oblike za izbiro geoobjektov",
    "startToolTip": "Narišite obliko za izbiro geoobjektov"
  },
  "errors": {
    "layerNotFound": "Sloja ${0} z ID ${1} ni mogoče najti na karti. Karta se je morda že spremenila od konfiguracije pripomočkov.",
    "queryNullID": "Geoobjekt iz ${0} je vrnil neveljaven ID",
    "noSelectedLayers": "Ni izbranih slojev z zapisi za posodabljanje",
    "inputValueError": "Neveljavna vrednost v obrazcu",
    "saveError": "${0} geoobjektov ni mogoče shraniti, podrobnosti so dodane v konzolo",
    "requiredValue": "Zahtevana vrednost"
  }
});