define({
  "tabs_section_Label": "Zavihki",
  "addTab": "Dodaj zavihek",
  "layerName": "Sloj",
  "layerType": "Tip analize",
  "layerLabel": "Napis",
  "actions": "Dejanja",
  "closest": "Najbližji geoobjekt",
  "proximity": "Bližina",
  "summary": "Povzetek",
  "select_lbl": "-- Izberite --",
  "general_setting_Label": "Splošne nastavitve",
  "units_text_lbl": "Enote razdalje",
  "maximum_distance_lbl": "Maksimalna razdalja najbližjega geoobjekta",
  "buffer_text_lbl": "Napis obrisa",
  "buffer_lbl": "Razdalja obrisa",
  "buffer_max_lbl": "Maksimalna razdalja obrisa",
  "buffer_min_lbl": "Minimalna razdalja obrisa",
  "buffer_default_lbl": "Privzeta razdalja obrisa",
  "not_less_than_max": "Razdalja mora biti manjša od maksimalne razdalje obrisa",
  "not_between": "Razdalja mora biti med minimalno in maksimalno razdaljo obrisa",
  "not_more_than_min": "Razdalja mora biti večja od minimalne razdalje obrisa",
  "not_valid_number": "Mora biti veljavno število",
  "invalid_value": "${type} vrednost je neveljavna",
  "routing_checkBox": "Omogoči usmerjanje",
  "weather_Label": "Nastavitve vremena",
  "weather_checkBox": "Omogoči vreme",
  "weather_map_layers": "Izberite vremenske sloje...",
  "selected_map_layers": " vremenski sloji izbrani",
  "instruction_weather": "Informacije o vremenu prikaži na plošči.",
  "instruction_weather_layers": "Prikaži dodatne vremenske sloje.",
  "instruction_weather_metric": "Prikaži standardne/metrične vrednosti.",
  "selectLayers": "Izberite vremenske sloje",
  "weather_removed_message": "Možnosti vremena niso več na voljo za ta pripomoček.",
  "currentlySelectedLayer": "Izberite iz kartnih slojev",
  "missingTabLabel": "Vsaj enemu zavihku manjka napis",
  "missingLayerInWebMap": "Operativnih slojev ni mogoče najti.",
  "selectFields": "Izberite polja",
  "addField": "Dodaj polje",
  "sum": "Vsota",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Povprečje",
  "count": "ŠTETJE",
  "area": "POVRŠINA",
  "length": "ŠTETJE",
  "count_checkBox": "POVRŠINA",
  "area_checkBox": "Prikaz vsote površin",
  "length_checkBox": "Prikaz vsote dolžin",
  "max_records": "Maksimalna dosežena omejitev",
  "save_label": "Možnosti shranjevanja",
  "save_checkbox": "Omogoči shranjevanje",
  "report_label": "Možnosti poročila",
  "report_checkbox": "Omogoči poročilo",
  "csv_label": "Možnosti CSV",
  "csv_checkbox": "Izvozi vsa polja",
  "display_label": "Možnosti prikaza",
  "display_checkbox": "Prikaz povzetka geoobjektov",
  "snapshot_label": "Možnosti posnetka",
  "snapshot_checkbox": "Omogoči posnetek",
  "must_select_template": "Izberite eno od predlog za urejanja v možnostih shranjevanja.",
  "count_label": "Napis štetja",
  "area_label": "Napis površine",
  "length_label": "Napis dolžine",
  "invalid_string_width": "Vrednost je predolga. ",
  "layer_type_not_supported": "Tip sloja ni podprt",
  "groupedSummary": "Združeni seštevki",
  "groupByField": "Združi po polju",
  "labelType": "Dodaj napis",
  "prefix": "Kot predpono",
  "suffix": "Kot pripono",
  "need_group_field": "Uporabite urejanje za določanje skupine po polju.",
  "fieldTitle": "Polje",
  "typeTitle": "Tip",
  "actionsTitle": "Dejanja",
  "save_point_checkbox": "Shrani točke",
  "save_line_checkbox": "Shrani linije",
  "save_poly_checkbox": "Shrani poligone",
  "no_valid_popup_fields": "V pojavnem oknu ni veljavnih polj. Uporabite urejanje za določanje polja.",
  "no_valid_fields": "Ni veljavnih polj. Uporabite urejanje za določanje možnosti prikaza.",
  "incident_label": "Napis zavihka",
  "locate_incident_label": "Napis interesnega območja",
  "incident": "Incident",
  "locate_incident": "Lociraj incident",
  "buffer_value": "Razdalja obrisa",
  "tab_options": "Analiza",
  "export_options": "Rezultat",
  "instruction_save": "Shranite lokacijo v geoobjektno storitev.",
  "instruction_snapshot": "Ustvarite spletno karto na osnovi lokacije.",
  "instruction_report": "Ustvarite natisnjeno poročilo lokacije.",
  "instruction_all_fields": "Izvozi vsa polja s prenosom CSV.",
  "data_label": "Nastavitve izpisa podatkov",
  "layer_error": "Sloj manjka ali ni veljaven.",
  "visibility_checkBox": "Onemogoči upravljanje vidnosti sloja",
  "downloadTab": {
    "reportLegend": "Nastavitve poročila",
    "textColorLabel": "Izberi barvo za naslove stolpcev",
    "setButtonLabel": "Nastavi",
    "printGPServiceLabel": "URL storitve tiskanja",
    "logoLabel": "Logotip",
    "logoChooserHint": "Kliknite ikono za zamenjavo slike",
    "footnoteLabel": "Sprotna opomba"
  }
});