define({
  "_widgetLabel": "Εργαλείο έξυπνης επεξεργασίας",
  "_featureAction_SmartEditor": "Εργαλείο έξυπνης επεξεργασίας",
  "noEditPrivileges": "Ο λογαριασμός σας δεν έχει δικαίωμα δημιουργίας ή τροποποίησης δεδομένων.",
  "widgetActive": "Ενεργή",
  "widgetNotActive": "Μη ενεργή",
  "pressStr": "Πατήστε ",
  "ctrlStr": " CTRL ",
  "snapStr": " για να ενεργοποιηθεί η λειτουργία αγκίστρωσης",
  "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
  "editorCache": " - Εργαλείο επεξεργασίας Cache",
  "presetFieldAlias": "Πεδίο",
  "presetValue": "Προκαθορισμένη τιμή",
  "usePresetValues": " Χρήση προκαθορισμένων τιμών (Μόνο νέα στοιχεία)",
  "editGeometry": " Επεξεργασία γεωμετρικού τύπου",
  "savePromptTitle": "Αποθήκευση στοιχείου",
  "savePrompt": "Θέλετε να αποθηκευτεί το τρέχον στοιχείο;",
  "deletePromptTitle": "Διαγραφή στοιχείου",
  "deletePrompt": "Είστε βέβαιοι ότι θέλετε να διαγράψετε το επιλεγμένο στοιχείο;",
  "attachmentLoadingError": "Σφάλμα στην αποστολή των συνημμένων",
  "attachmentSaveDeleteWarning": "Προειδοποίηση: Οι αλλαγές στα συνημμένα αποθηκεύτηκαν αυτόματα",
  "autoSaveEdits": "Η εργασία επεξεργασίας αποθηκεύεται αυτόματα.",
  "addNewFeature": "Δημιουργία νέου στοιχείου",
  "featureCreationFailedMsg": "Δεν είναι δυνατή η δημιουργία νέας εγγραφής/νέου στοιχείου.",
  "noRelatedFeatureFoundMsg": "Δεν βρέθηκαν σχετικές εγγραφές/σχετικά στοιχεία.",
  "relatedItemTitle": "Σχετικός πίνακας/Σχετικό θεματικό επίπεδο",
  "invalidRelationShipMsg": "Βεβαιωθείτε ότι το πεδίο πρωτεύοντος κλειδιού '${parentKeyField}' έχει έγκυρη τιμή.",
  "pendingFeatureSaveMsg": "Αποθηκεύστε τις αλλαγές στο στοιχείο προτού δημιουργήσετε σχετικό στοιχείο.",
  "attachmentsRequiredMsg": "(*) Απαιτούνται συνημμένα.",
  "filterEditor": {
    "all": "Όλοι",
    "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
    "searchTemplates": "Αναζήτηση προτύπων"
  },
  "invalidConfiguration": "To widget δεν είναι διαμορφωμένο ή τα θεματικά επίπεδα στη διαμόρφωση δεν βρίσκονται πλέον στο χάρτη. Ανοίξτε την εφαρμογή στη λειτουργία Εργαλείο δημιουργίας και αναδιαμορφώστε το widget.",
  "geometryServiceURLNotFoundMSG": "Αδύνατη η λήψη Geometry Service URL"
});