define({
  "enableUndoRedo": "Luba tühistamine ja ennistamine",
  "toolbarVisible": "Tööriistariba nähtav",
  "toolbarOptions": "Tööriistariba valikud",
  "mergeVisible": "Ühenda",
  "cutVisible": "Lõika",
  "reshapeVisible": "Muuda kuju",
  "back": "Tagasi",
  "label": "Kiht",
  "edit": "Muudetav",
  "update": "Keela geomeetria uuendamine",
  "fields": "Väljad",
  "actions": "Tegevused",
  "editpageName": "Nimi",
  "editpageAlias": "Alias",
  "editpageVisible": "Nähtav",
  "editpageEditable": "Muudetav",
  "noLayers": "Muudetavaid objektikihte pole saadaval",
  "configureFields": "Kihi väljade seadistamine",
  "useFilterEdit": "Kasuta objekti malli filtrit",
  "display": "Kuva",
  "autoApplyEditWhenGeometryIsMoved": "Rakenda muudatus geomeetria liigutamisel automaatselt",
  "snappingTolerance": "Määra snäpiga seotud tolerants pikslites",
  "popupTolerance": "Määra atribuudi muutmise hüpikakna tolerants pikslites",
  "stickyMoveTolerance": "Määra kleepuva liikumise tolerants pikslites",
  "usingSaveButton": "Ära rakenda muudatusi atribuutidele enne nupu Salvesta klõpsamist"
});