define({
  "_widgetLabel": "Nadzorna plošča recenzenta",
  "spatialFilterSelection": "Filtriraj rezultate po prostoru",
  "drawSelectionArea": "Prikažite izbrano območje rezulatov na karti",
  "currentSelection": "Pokaži rezultate samo na trenutnem obsegu karte",
  "censusBlockGroup": "Pokaži rezultate po prostoru",
  "noSpatialFilter": " Ne uporabi prostorskega filtra",
  "reviewerSessionFilter": "Filtriraj rezultate po seji recenzenta",
  "selectAttributeFilters": "Izberite podatke za prikaz",
  "phaseFieldName": "faza življenjskega cikla",
  "statusFieldName": "status življenjskega cikla",
  "allSessions": "Vse seje",
  "dashboardTab": "Nadzorna plošča",
  "filtersTab": "Nastavitve",
  "noResults": "Ni najdenih rezultatov",
  "resultsBy": "Rezultati po: ",
  "reviewed": "Pregled",
  "corrected": "Popravki",
  "verified": "Potrjevanje",
  "OtherCategory": "Drugo",
  "backButton": "Nazaj"
});