define({
  "_widgetLabel": "Khoảng cách và Hướng",
  "tabLineTitle": "Đường",
  "tabCircleTitle": "Hình tròn",
  "tabEllipseTitle": "Hình Elip",
  "tabRingsTitle": "Vòng",
  "multipleNotationsMessage": " các ký hiệu khớp với thông tin của bạn. Vui lòng xác nhận ký hiệu bạn muốn sử dụng:",
  "invalidCoordinateMessage": "Tọa độ không hợp lệ",
  "confirmInputNotationMessage": "Xác nhận Ký hiệu đầu vào",
  "prefixSuffixMessage": "Tọa độ đầu vào đã được phát hiện vì có cả tiền tố và hậu tố cho giá trị vĩ độ hoặc kinh độ, tọa độ trả lại dựa trên tiền tố.",
  "rememberDecisionMessage": "Nhớ quyết định của tôi và không thông báo nữa.<br/>",
  "majorAxisTooltipMessage": "Bấm vào chiều dài của trục lớn",
  "minorAxisTooltipMessage": "Di chuyển con trỏ quay lại vị trí xuất phát để thiết lập trục nhỏ và hoàn tất vẽ hình elip",
  "clickToFinishLineMessage": "Bấm để hoàn tất vẽ đường",
  "doubleClickEllipseMesage": "Nhấp đúp để hoàn tất vẽ vòng phạm vi",
  "invalidCoordinateTypeMessage": "Không thể xác định loại tọa độ nhập vào. Vui lòng kiểm tra mục nhập của bạn",
  "noCenterPointSetMessage": "Chưa thiết lập tâm Điểm. Vui lòng kiểm tra mục nhập của bạn",
  "ellipseMajorAxis": "Trục lớn",
  "ellipseMinorAxis": "Trục nhỏ",
  "degreesRangeMessage": "Giá trị phải nằm trong khoảng từ 0 đến 360",
  "millsRangeMessage": "Giá trị phải nằm trong khoảng từ 0 đến 6400",
  "lengthLabel": "Độ dài",
  "angleLabel": "Góc",
  "startPointLabel": "Điểm Bắt đầu",
  "endPointLabel": "Điểm kết thúc",
  "centerPointLabel": "Tâm Điểm",
  "distanceTableErrorMessage": "Bảng khoảng cách trống. Vui lòng chắc chắn nhập một số khoảng cách.",
  "setCoordFormatStringMessage": "Thiết lập chuỗi định dạng tọa độ",
  "prefixMessage": "Thêm tiền tố \"+/-\" vào số dương và số âm",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Độ thập phân - Vĩ độ/Kinh độ",
  "DDLongLatNotation": "Độ thập phân - Kinh độ/Vĩ độ",
  "DDMLatLongNotation": "Độ thập phân phút - Vĩ độ/Kinh độ",
  "DDMLongLatNotation": "Độ thập phân phút - Kinh độ/Vĩ độ",
  "DMSLatLongNotation": "Độ thập phân giây - Vĩ độ/Kinh độ",
  "DMSLongLatNotation": "Độ thập phân giây - Kinh độ/Vĩ độ",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Chữ cái dải sóng",
  "UTMHemNotation": "UTM - Bán cầu (Bắc/Nam)",
  "circleTitle": "Tạo hình tròn từ",
  "radiusLabel": "Bán kính",
  "diameterLabel": "Đường kính",
  "startPointPlaceHolderLabel": "Nhập Tọa độ",
  "formatInputLabel": "Định dạng đầu vào",
  "drawCircleLabel": "Vẽ hình tròn",
  "drawLineLabel": "Vẽ Đường",
  "createCircleInteractivelyLabel": "Tạo hình tròn theo cách tương tác",
  "rangeErrorMessage": "Bán kính hoặc đường kính không hợp lệ",
  "numericInvalidMessage": "Vui lòng nhập một giá trị số",
  "timeLabel": "Thời gian",
  "invalidTimeMessage": "Giá trị thời gian không hợp lệ",
  "hoursLabel": "Giờ",
  "minutesLabel": "Phút",
  "secondsLabel": "Giây",
  "rateLabel": "Xếp loại",
  "invalidDistanceMessage": "Giá trị khoảng cách không hợp lệ",
  "feetSecondsLabel": "Feet / giây",
  "feetHourLabel": "Feet / giờ",
  "kmSecondLabel": "Kilômét/ giây",
  "kmHourLabel": "Kilômét/ giờ",
  "metersSecondLabel": "Mét / giây",
  "metersHourLabel": "Mét / giờ",
  "milesSecondLabel": "Dặm / giây",
  "milesHourLabel": "Dặm / giờ",
  "nauticalMilesSecondLabel": "Hải lý / giây",
  "nauticalMilesHourLabel": "Hải lý / giờ",
  "clearGraphicsLabel": "Xóa đồ họa",
  "ellipseTypeLabel": "Kiểu hình elip",
  "ellipseSemiLabel": "Một nửa",
  "ellipseFullLabel": "Đầy đủ",
  "drawEllipseLabel": "Vẽ hình elip",
  "createEllipseInteractively": "Tạo hình elip theo cách tương tác",
  "axisLabel": "Trục",
  "majorRadiusLabel": "Lớn (Bán kính)",
  "axisErrorMessage": "Giá trị phải lớn hơn 0",
  "minorRadiusLabel": "Nhỏ (Bán kính)",
  "orientationLabel": "Hướng ảnh",
  "orientationErrorMessage": "Giá trị phải nằm trong khoảng từ 0 đến 360",
  "warningMessage": "Cảnh báo: Đồ họa tạo ra bằng cách sử dụng công cụ hình elip không phải là trắc địa",
  "fromLabel": "Từ",
  "distanceBearingLabel": "Khoảng cách và Góc phương vị",
  "pointsLabel": "Điểm",
  "createLineInteractively": "Tạo đường thẳng theo cách tương tác",
  "lineLengthErrorMessage": "Chiều dài đường thẳng không hợp lệ",
  "degreesLabel": "Giảm",
  "milsLabel": "Mil",
  "lineTypeLabel": "Loại",
  "interactiveLabel": "Tương tác",
  "fixedLabel": "Cố định",
  "originLabel": "Điểm gốc",
  "cumulativeLabel": "Tích lũy",
  "numberOfRingsLabel": "Số lượng vòng",
  "ringsErrorMessage": "Số lượng vòng không hợp lệ",
  "distanceBetweenRingsLabel": "Khoảng cách giữa các vòng",
  "ringsDecimalErrorMessage": "Nhập giá trị số thành 2 chữ số thập phân",
  "distanceUnitsLabel": "Đơn vị Khoảng cách",
  "distancesLabel": "Khoảng cách",
  "numberOfRadialsLabel": "Số lượng tỏa tròn",
  "upLabel": "Lên",
  "downLabel": "Xuống",
  "deleteLabel": "Xóa",
  "radialsErrorMessage": "Số lượng tỏa tròn không hợp lệ. Tối đa cho phép là 360",
  "addPointLabel": "Thêm điểm",
  "valueLabel": "Giá trị",
  "valueText": "Nhập giá trị",
  "actionLabel": "Hành động"
});