define({
  "chartTasks": "Tarefas de gráfico",
  "addNew": "Adicionar novo",
  "addNewTip": "Adicionar uma nova tarefa de gráfico",
  "name": "Nome",
  "set": "Configurar",
  "setDataSource": "Configurar fonte de dados",
  "generalSettingsTip": "Configura a fonte de dados, título e descrição para gráficos.",
  "chartModeSettingTip": "Seleciona uma maneira para analisar e exibir dados como gráficos.",
  "detailsSettingTip": "Configure a aparência do gráfico especificando seus tipos e cores, e quais valores a serem desenhados:",
  "symbolSettingTip": "Configura a exibição do mapa para dados do gráfico.",
  "addFilterTip": "Adicionar filtro para estes dados",
  "dataSource": "Fonte de Dados",
  "noResults": "Nenhuma feição encontrada.",
  "chartTitle": "Título do gráfico",
  "description": "Descrição",
  "chartingMode": "Visualização de gráfico",
  "featureOption": "Exibir valores feição por feição",
  "categoryOption": "Exibir valores por categoria",
  "countOption": "Exibir contagem de feição por categoria",
  "fieldOption": "Exibir valores de atributo como gráficos",
  "category": "Categoria",
  "axisLabel": "Rótulo de categoria",
  "categoryField": "Campo de categoria",
  "operation": "Operação",
  "originalOption": "Utilizar valores originais",
  "sumOption": "Soma",
  "averageOption": "Média",
  "minOption": "Mínimo",
  "maxOption": "Máximo",
  "valueFields": "Campos de valor",
  "moveUp": "Mover para cima",
  "moveDown": "Mover para baixo",
  "sortOrder": "Classificar gráficos por rótulos de categoria",
  "ascending": "Crescente",
  "descending": "Descendente",
  "chartType": "Tipo de gráfico",
  "column": "Gráfico de colunas",
  "bar": "Gráfico de barras",
  "line": "Gráfico de linhas",
  "pie": "Gráfico de pizza",
  "chartColor": "Cor do gráfico",
  "showDataLabels": "Mostrar rótulos de dados",
  "setSymbol": "Símbolo de seleção",
  "setHighLightColor": "Cor de Destaque",
  "settings": "Configurações",
  "mapInterationOptions": "Opções de interação do mapa",
  "preview": "Visualizar",
  "ok": "OK",
  "cancel": "Cancelar",
  "close": "Fechar",
  "setFilterTip": "Configure o filtro corretamente. ",
  "setChartTitleTip": "Configure o título do gráfico.",
  "setChartTypeTip": "Selecione um tipo de gráfico pelo menos.",
  "setDataFieldTip": "Selecione um campo de valor pelo menos.",
  "setOutputFieldTip": "Configure os campos de saída.",
  "count": "Contagem",
  "label": "Rótulo",
  "horizontalAxis": "Eixo horizontal",
  "verticalAxis": "Eixo vertical",
  "dataLabels": "Rótulos de dados",
  "color": "Cor",
  "colorful": "Colorido",
  "monochromatic": "Monocromático",
  "noTaskTip": "Clique em Adicionar Novo para adicionar uma tarefa de gráfico",
  "info": "Info",
  "charts": "Gráficos",
  "options": "Opções",
  "taskName": "Nome da tarefa",
  "summary": "Resumo",
  "resultDescription": "Descrição do resultado",
  "spatialFilterTip": "Escolha o filtro espacial utilizado no widget para limitar resultados.",
  "defaultOption": "Padrão",
  "useCurrentExtentTip": "Parcialmente ou completamente dentro da extensão de mapa atual",
  "useDrawGraphicTip": "Parcialmente ou completamente dentro da forma desenhada no mapa",
  "useFeaturesTip": "Baseado em suas localizações em relação às feições em outra camada",
  "noSpatialLimitTip": "Não limitar espacialmente os resultados",
  "drawingTools": "Ferramentas de desenho",
  "bufferSettings": "Configurações do buffer",
  "defaultDistance": "Distância Padrão",
  "bufferDistance": "Distância do Buffer",
  "defaultUnit": "Unidade Padrão",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "availableSpatialRelationships": "Relacionamentos espaciais disponíveis",
  "setSpatialRelationships": "Configurar relacionamentos espaciais",
  "availability": "Disponibilidade",
  "relationship": "Relacionamento",
  "actions": "Ações",
  "intersect": "interseccionar",
  "contain": "contém",
  "areContainedIn": "estão contidos em",
  "cross": "cruz",
  "envelopeIntersect": "intersecção de envelope",
  "overlap": "sobreposição",
  "areOverlapped": "estão sobrepostos",
  "touche": "toca",
  "within": "dentro",
  "areWithin": "estão dentro",
  "indexIntersect": "intersecção de índice"
});