define({
  "chartSettingLabel": "Impostazioni grafico",
  "addNewLabel": "Aggiungi nuovo",
  "generalSettingLabel": "Impostazioni generali",
  "searchSourceSettingLabel": "Cerca impostazioni origine",
  "layerChooser": {
    "title": "Selezionare layer da rappresentare",
    "selectPolygonLayerLabel": "Seleziona layer",
    "selectPolygonLayerHintText": "Suggerimento: se si configurano più grafici, il tipo di geometria dei layer deve essere identica",
    "selectRelatedTableLayerLabel": "Seleziona tabella correlata a layer",
    "selectRelatedTableLayerHintText": "Suggerimento: vengono visualizzate solo le tabelle con campi numerici",
    "errorInSelectingPolygonLayer": "Selezionare un layer con un layer punto correlato.",
    "errorInSelectingRelatedLayer": "Selezionare una tabella/layer correlato valido nel layer.",
    "polygonLayerNotHavingRelationships": "Il layer selezionato non dispone di tabella/layer correlato."
  },
  "ChartSetting": {
    "sectionTitle": "Titolo sezione",
    "sectionTitleHintText": "Suggerimento: visualizzato nel titolo intestazione sezione",
    "chartTitle": "Titolo grafico",
    "chartTitleHintText": "Suggerimento: visualizzato al centro nella parte superiore del grafico",
    "chartDescription": "Descrizione",
    "chartDescriptionHintText": "Suggerimento: visualizzato sotto il grafico",
    "chartType": "Tipo di grafico",
    "barChart": "Grafico a barre",
    "pieChart": "Grafico a torta",
    "polarChart": "Grafico polare",
    "dataSeriesField": "Campo serie di dati",
    "labelField": "Campo etichetta",
    "chartColor": "Colore grafico",
    "singleColor": "Colore singolo",
    "colorByTheme": "Colore in base a tema",
    "colorByFieldValue": "Colore in base a valore campo",
    "xAxisTitle": "Titolo asse X",
    "xAxisHintText": "Suggerimento: titolo asse X",
    "yAxisTitle": "Titolo asse Y",
    "yAxisHintText": "Suggerimento: titolo asse Y",
    "fieldColorLabel": "Etichetta",
    "fieldColorColor": "Colore",
    "defaultFieldSelectLabel": "Seleziona",
    "errMsgFieldValuesNotFound": "Impossibile trovare i valori per il campo selezionato",
    "errMsgSectionTitle": "Immettere i titolo di sezione",
    "errMsgFieldByValue": "Selezionare un valore campo",
    "settingTabTitle": "Impostazione",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Suggerimento: selezionare campi per generare grafico polare",
    "visibilityText": "Visibilità",
    "fieldNameText": "Nome campo",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Selezionare tre o più campi per generare grafico polare",
    "polarChartPolygonFillLabel": "Riempi poligono",
    "polarChartPolygonFillHintText": "Suggerimento: selezionare la casella di controllo per mostrare il riempimento poligono nel grafico polare",
    "viewLayoutLabel": "Layout",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Deserto",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Terreno paludoso",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Impostazioni generali",
    "locationSymbolLabel": "Simbolo posizione grafica",
    "locationSymbolHintText": "Suggerimento: utilizzato per visualizzare simbolo per posizione indirizzo e selezione",
    "refreshIntervalLabel": "Intervallo di aggiornamento",
    "refreshIntervalHintText": "Suggerimento: utilizzato per aggiornare i grafici basati su questo intervallo. Specificare un valore compreso tra 1 e 1440 minuti",
    "errMsgRefreshInterval": "Specificare l'intervallo di aggiornamento compreso tra 0 e 1440 minuti",
    "symbolPickerPreviewText": "Anteprima:",
    "showToolToSelectLabel": "Pulsante Imposta posizione",
    "showToolToSelectHintText": "Suggerimento: fornisce un pulsante per impostare la posizione sulla mappa anziché impostare sempre la posizione quando si fa clic sulla mappa"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Cerca impostazioni origine",
    "searchSourceSettingTitle": "Cerca impostazioni origine",
    "searchSourceSettingTitleHintText": "Aggiungere e configurare servizi di geocodifica o feature layer come fonti di ricerca. Queste fonti specificate determinano ciò che è possibile cercare nella casella di ricerca",
    "addSearchSourceLabel": "Aggiungi fonte di ricerca",
    "featureLayerLabel": "Feature Layer",
    "geocoderLabel": "Geocodificatore",
    "nameTitle": "Nome",
    "generalSettingLabel": "Impostazioni generali",
    "allPlaceholderLabel": "Testo segnaposto per la ricerca in tutti:",
    "allPlaceholderHintText": "Suggerimento: immettere il testo da visualizzare come segnaposto durante la ricerca di tutti i layer e geocodificatore",
    "generalSettingCheckboxLabel": "Mostra il popup per la feature o per la posizione trovata",
    "countryCode": "Codici paesi o regioni",
    "countryCodeEg": "es. ",
    "countryCodeHint": "Se si lascia vuoto questo campo, la ricerca verrà effettuata in tutti i paesi e le regioni",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Esegui la ricerca nell'estensione mappa corrente",
    "zoomScale": "Scala zoom",
    "locatorUrl": "URL del geocodificatore",
    "locatorName": "Nome geocodificatore",
    "locatorExample": "Esempio",
    "locatorWarning": "Questa versione del servizio di geocodifica non è supportata. Il widget supporta il servizio di geocodifica 10.0 e versioni successive.",
    "locatorTips": "I suggerimenti non sono disponibili perché il servizio di geocodifica non supporta tale funzionalità.",
    "layerSource": "Origine del layer",
    "setLayerSource": "Imposta layer di origine",
    "setGeocoderURL": "Imposta URL geocodificatore",
    "searchLayerTips": "I suggerimenti non sono disponibili perché il feature service non supporta la funzionalità di paginazione.",
    "placeholder": "Testo del segnaposto",
    "searchFields": "Campi di ricerca",
    "displayField": "Visualizza campo",
    "exactMatch": "Corrispondenza esatta",
    "maxSuggestions": "Suggerimenti massimi",
    "maxResults": "Risultati massimi",
    "enableLocalSearch": "Abilita ricerca locale",
    "minScale": "Scala Minima",
    "minScaleHint": "Quando la scala della mappa è più grande di questa scala, verrà applicata la ricerca locale",
    "radius": "Raggio",
    "radiusHint": "Specifica il raggio di un'area intorno al centro della mappa corrente che viene utilizzato per assegnare la priorità alla classificazione dei candidati di geocodifica in modo che i canditati più vicini alla posizione vengano restituiti per primi",
    "meters": "Metri",
    "setSearchFields": "Imposta campi di ricerca",
    "set": "Imposta",
    "fieldName": "Nome",
    "invalidUrlTip": "URL ${URL} non valido o non accessibile."
  }
});