define({
  "enableUndoRedo": "Bật Hoàn tác/Làm lại",
  "toolbarVisible": "Thanh công cụ hiển thị",
  "toolbarOptions": "Tùy chọn thanh công cụ",
  "mergeVisible": "Trộn",
  "cutVisible": "Cắt",
  "reshapeVisible": "Tạo lại hình dạng",
  "back": "Quay lại",
  "label": "Lớp",
  "edit": "Có thể chỉnh sửa",
  "update": "Tắt Cập nhật Hình học",
  "fields": "Trường",
  "actions": "Các hành động",
  "editpageName": "Tên",
  "editpageAlias": "Bí danh",
  "editpageVisible": "Hiển thị",
  "editpageEditable": "Có thể chỉnh sửa",
  "noLayers": "Không có lớp đối tượng nào có thể chỉnh sửa",
  "configureFields": "Cấu hình trường của lớp dữ liệu",
  "useFilterEdit": "Sử dụng bộ lọc mẫu đối tượng",
  "display": "Hiển thị",
  "autoApplyEditWhenGeometryIsMoved": "Tự động áp dụng chỉnh sửa khi hình học bị di chuyển",
  "snappingTolerance": "Đặt sai số bắt điểm bằng pixel",
  "popupTolerance": "Đặt sai số của cửa sổ popup chỉnh sửa thuộc tính bằng pixel",
  "stickyMoveTolerance": "Đặt sai số di chuyển dính bằng pixel",
  "usingSaveButton": "Không áp dụng các chỉnh sửa cho thuộc tính cho đến khi bấm vào nút Lưu"
});