define({
  "_widgetLabel": "עורך חכם",
  "_featureAction_SmartEditor": "עורך חכם",
  "noEditPrivileges": "לחשבונך אין הרשאות ליצור נתונים או לשנות אותם.",
  "widgetActive": "פעיל",
  "widgetNotActive": "לא פעיל",
  "pressStr": "לחץ ",
  "ctrlStr": " CTRL ",
  "snapStr": " כדי להפעיל הצמדה",
  "noAvailableTempaltes": "אין תבניות זמינות",
  "editorCache": " -- מטמון העורך",
  "presetFieldAlias": "שדה",
  "presetValue": "ערך קבוע מראש",
  "usePresetValues": " השתמש בערכים שנקבעו מראש (ישויות חדשות בלבד)",
  "editGeometry": " ערוך גיאומטריה",
  "savePromptTitle": "שמור ישות",
  "savePrompt": "האם ברצונך לשמור את הישות הנוכחית?",
  "deletePromptTitle": "מחק ישות",
  "deletePrompt": "האם אתה בטוח שברצונך למחוק את הישות שנבחרה?",
  "attachmentLoadingError": "שגיאה בטעינת קישורי קבצים",
  "attachmentSaveDeleteWarning": "אזהרה: שינויים בקישורי קבצים נשמרים באופן אוטומטי",
  "autoSaveEdits": "השינויים נשמרים אוטומטית",
  "addNewFeature": "צור ישות חדשה",
  "featureCreationFailedMsg": "לא ניתן ליצור רשומה/ישות חדשה",
  "noRelatedFeatureFoundMsg": "לא נמצאו רשומות/ישויות מקושרות",
  "relatedItemTitle": "טבלה/שכבה מקושרת",
  "invalidRelationShipMsg": "ודא ששדה המפתח הראשי: '‎${parentKeyField}‎' מכיל ערך חוקי",
  "pendingFeatureSaveMsg": "שמור את עריכת הישות לפני שתיצור ישות מקושרת.",
  "attachmentsRequiredMsg": "(*) נדרשות תוספות.",
  "filterEditor": {
    "all": "הכל",
    "noAvailableTempaltes": "אין תבניות זמינות",
    "searchTemplates": "תבניות חיפוש"
  },
  "invalidConfiguration": "תצורת הווידג'ט לא הוגדרה או שהשכבות בתצורה אינן נמצאות עוד במפה. פתח את האפליקציה במצב עריכה והגדר מחדש את תצורת הווידג'ט.",
  "geometryServiceURLNotFoundMSG": "לא ניתן לקבל כתובת URL של שירות גיאומטריה"
});