define({
  "serviceUrl": "Servis url’si ayarla:",
  "minIntSpacingLabel": "Minimum Grid Boyutu",
  "lineOpacityLabel": "Çizgi Opaklığı",
  "labelOpacityLabel": "Etiket Opaklığı",
  "centerLabelOpacityLabel": "Etiket Opaklığını Ortala",
  "gridZonePlacementLabel": "Kılavuz Alanı Etiket Değişimi",
  "verticalLineLabels": "Dikey Çizgi Etiketleri",
  "styleHeaderLabel": "Stil",
  "indexHeaderLabel": "Grid Bileşeni",
  "colorHeaderLabel": "Renkli",
  "fontSizeHeaderLabel": "Yazı Tipi Boyutu",
  "lineWidthHeaderLabel": "Çizgi Genişliği",
  "horizontalLabel": "Yatay",
  "verticalLabel": "Dikey",
  "upperLeftLabel": "Sol Üst",
  "upperRightLabel": "Sağ Üst",
  "lowerLeftLabel": "Sol Alt",
  "lowerRightLabel": "Sağ Alt",
  "centerLabel": "Orta",
  "errorMessage": "Yapılandırma sayfası hata içeriyor. Lütfen kaydetmeden önce düzeltin.",
  "checkBoxLabel": "Araç kapatıldığında şebekeyi görüntüleyin",
  "checkBoxLabelDashboard": "Grid’i göster",
  "gzd": "Grid Zone Designator (GZD)",
  "gsid": "100.000-metre Izgara Karesi Tanımlama (GSID)",
  "grid10k": "10.000-meter Grid Çizgileri",
  "grid1k": "1.000-meter Grid Çizgileri",
  "grid100m": "100-meter Grid Çizgileri",
  "grid10m": "10-meter Grid Çizgileri",
  "switchBasemap": "Altlık Haritayı Değiştir"
});