define({
  "_widgetLabel": "Referentna grafika u obliku mreže",
  "newGRGFromAreaButtonLabel": "Definiši mrežu iz oblasti",
  "newGRGFromPointButtonLabel": "Definiši mrežu iz tačke",
  "newGRGFromAreaTitle": "Definiši mrežu iz oblasti",
  "newGRGFromPointTitle": "Definiši mrežu iz tačke",
  "newGRGBySizeButtonLabel": "Pomoću dimenzije",
  "newGRGFromRefSystemButtonLabel": "Pomoću referentnog sistema",
  "newGRGByTimeLabel": "Pomoću vremena i brzine",
  "newGRGFromNonStandardButtonLabel": "Definiši nestandardnu mrežu",
  "newGRGAreaBySizeTitle": "GRG iz oblasti pomoću dimenzije",
  "newGRGAreaBySizeDefineAreaLabel": "GRG oblast",
  "addGRGAreaPolygonToolTip": "Nacrtaj GRG oblast pomoću poligona",
  "addGRGAreaExtentToolTip": "Nacrtaj GRG oblast pomoću obuhvata",
  "rotation": "Rotacija mreže",
  "numberRowsColumnsLabel": "Definiši broj redova i kolona",
  "newGRGAreaByRefSystemTitle": "GRG iz oblasti pomoću referentnog sistema",
  "gridSize": "Veličina mreže",
  "UTMZoneandBand": "Zona mreže",
  "100000m": "100.000 metara",
  "10000m": "10.000 metara",
  "1000m": "1000 metara",
  "100m": "100 metara",
  "10m": "10 metara",
  "clipGrid": "Iseci mrežu na GRG oblast",
  "newGRGAreaFromNonStandardTitle": "Novi NRG",
  "newGRGPointBySizeTitle": "GRG iz tačke pomoću dimenzije",
  "newGRGPointByRefSystemTitle": "GRG iz tačke pomoću referentnog sistema",
  "newGRGPointByTimeTitle": "GRG iz tačke pomoću  vremena i brzine",
  "time": "Vreme",
  "rate": "Brzina",
  "hours": "Sati",
  "minutes": "Minuti",
  "seconds": "Sekunde",
  "ftPerSec": "Stopa/sekundi",
  "ftPerHour": "Stopa/sat",
  "kmPerSec": "Kilometara/sekundi",
  "kmPerHour": "Kilometara/sat",
  "mPerSec": "Metara/sekundi",
  "mPerHour": "Metara/sat",
  "miPerSec": "Milja/sekundi",
  "miPerHour": "Milja/sat",
  "nMPerSec": "Nautičkih milja/sekundi",
  "nMPerHour": "Nautičkih milja/sat",
  "settingsTitle": "Postavke",
  "labelSettingsLabel": "Postavke oznake",
  "labelSettingsButtonLabel": "Konfigurišite postavke oznake",
  "gridSettingsLabel": "Postavke mreže",
  "gridSettingsButtonLabel": "Konfigurišite postavke mreže",
  "transparency": "Prozirnost",
  "labelStyle": "Stil oznake",
  "font": "Font",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "halo": "Efekat oreola",
  "show": "Prikaži",
  "lockSettings": "Vlasnik aplikacije je zaključao postavke",
  "gridSettings": {
    "cellShape": "Oblik ćelije",
    "cellUnits": "Jedinice ćelije",
    "cellOutline": "Postavke kontura ćelije",
    "cellFill": "Postavke popune ćelije",
    "gridReferenceSystem": "Referentni sistem",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Početak oznake",
    "labelType": "Vrsta oznake",
    "labelDirection": "Smer oznake",
    "gridOrigin": "Koordinatni početak mreže",
    "default": "Pravougaonik",
    "hexagon": "Šestougaonik",
    "miles": "Milje",
    "kilometers": "Kilometri",
    "feet": "Stope",
    "meters": "Metri",
    "yards": "Jardi",
    "nautical-miles": "Nautičke milje",
    "lowerLeft": "Dole levo",
    "lowerRight": "Dole desno",
    "upperLeft": "Gore levo",
    "upperRight": "Gore desno",
    "center": "Centar",
    "alphaNumeric": "Alfanumerički",
    "alphaAlpha": "Abecedno-abecedni",
    "numeric": "Brojčano",
    "horizontal": "Horizontalno",
    "vertical": "Vertikalno",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Pokaži oznake"
  },
  "publishTitle": "Objavi GRG na portalu",
  "publishGRGBtn": "Objavi",
  "GRGLayerName": "Ime sloja objavljenog GRG",
  "invalidGRGLayerName": "Ime sloja sme da sadrži samo alfanumeričke znakove i donje crte",
  "missingGRGLayerName": "Morate da unesete ime za GRG",
  "publishingFailedLayerExists": "Objavljivanje nije uspelo: Već imate servis geoobjekata sa imenom {0}. Odaberite drugo ime.",
  "checkService": "Provera servisa: {0}",
  "createService": "Kreiranje servisa: {0}",
  "unableToCreate": "Kreiranje nije moguće: {0}",
  "addToDefinition": "Dodaj u definiciju: {0}",
  "successfullyPublished": "Uspešno objavljen veb sloj{0}Upravljaj veb slojem",
  "userRole": "Kreiranje servisa nije moguće, jer korisnik nema dozvole",
  "createGRGBtn": "Kreiraj GRG",
  "clearGRGBtn": "Obriši",
  "labelFormat": "Format oznake",
  "helpIconTooltip": "Z: Oznaka zone mreže (GZD)\nS: Identifikacija kvadrata mreže na 100.000 metara (GSID)\nX: Razdaljina u odnosu na Y osu (X koordinata)\nY: Razdaljina u odnosu na X osu (Y koordinata)\n\nPrimeri:\nZSXY je 15SWC8081751205\nZS X,Y je 15SWC 80817,51205",
  "addPointToolTip": "Dodaj GRG koordinatni početak",
  "cellWidth": "Širina ćelije (x)",
  "cellHeight": "Visina ćelije (y)",
  "invalidNumberMessage": "Uneta vrednost nije važeća",
  "invalidRangeMessage": "Vrednost mora da bude veća od 0",
  "gridAngleInvalidRangeMessage": "Vrednost mora da bude između -89,9 i 89,9",
  "formatIconTooltip": "Unos formata",
  "coordInputLabel": "GRG koordinatni početak (DD)",
  "setCoordFormat": "Postavi nisku formata koordinata",
  "prefixNumbers": "Dodajte prefiks '+/-' pozitivnim i negativnim brojevima",
  "cancelBtn": "Otkaži",
  "applyBtn": "Primeni",
  "comfirmInputNotation": "Proverite unesenu oznaku",
  "notationsMatch": "oznake se podudaraju sa unosom potvrdite koje biste želeli da koristite:",
  "numberOfCellsHorizontal": "br. horizontalnih ćelija",
  "numberOfCellsVertical": "br. vertikalnih ćelija",
  "gridAngle": "Rotacija mreže",
  "tooManyCellsErrorMessage": "Pokušavate da kreirate mrežu koja se sastoji od više od 2000 ćelija. Preporučljivo je da smanjite broj ćelija koje se kreiraju promenom veličine mreže ili površine mreže.",
  "missingParametersMessage": "<p>Obrazac za kreiranje GRG ima parametre koji nedostaju ili su nevažeći. Uverite se da:</p><ul><li>GRG oblast je nacrtana.</li><li>Širina i visina ćelije sadrže važeće vrednosti.</li></ul>",
  "missingOriginParametersMessage": "<p>Obrazac za kreiranje GRG ima parametre koji nedostaju ili su nevažeći. Uverite se da:</p><ul><li>GRG koordinatni početak je podešen.</li><li>Unosi za vreme, brzinu i ugao sadrže važeće vrednosti.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Obrazac za kreiranje GRG ima parametre koji nedostaju ili su nevažeći. Uverite se da unosi za širinu i visinu ćelije sadrže važeće vrednosti.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Obrazac za kreiranje GRG ima parametre koji nedostaju ili su nevažeći. Uverite se da unosi za broj horizontalnih i vertikalnih ćelija sadrže važeće vrednosti.</p>",
  "drawPointToolTip": "Kliknite da biste GRG tačku koordinatnog početka",
  "missingLayerNameMessage": "Morate da unesete važeće ime sloja da biste mogli da objavite",
  "parseCoordinatesError": "Raščlanjivanje koordinata nije moguće. Proverite unos.",
  "grgPolarRegionError": "GRG obuhvat je unutar polarne regije. Ćelije koje upadnu u polarnu regiju se neće kreirati.",
  "grgPolarOriginError": "GRG tačka koordinatnog početka ne može da bude unutar polarne regije prilikom kreiranja GRG pomoću referentnog sistema.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "Univerzalni Transverzalni Merkatorov koordinatni sistem (H)",
  "UTM": "Univerzalni Transverzalni Merkatorov koordinatni sistem (UTM)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stepeni – geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stepeni – geografska dužina/širina",
  "DDMLatLongNotation": "Decimalni stepeni minuti – geografska širina/dužina",
  "DDMLongLatNotation": "Decimalni stepeni minuti – geografska dužina/širina",
  "DMSLatLongNotation": "Decimalni stepeni sekundi – geografska širina/dužina",
  "DMSLongLatNotation": "Decimalni stepeni sekundi – geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – slovo opsega",
  "UTMHemNotation": "UTM – hemisfera (S/J)"
});