define({
  "gridTabLabel": "그리드",
  "labelTabLabel": "레이블",
  "referenceSystemTabLabel": "기준 체계",
  "gridTabDescription": "격자 셀의 모양과 동작을 설정합니다.",
  "cellOutlineColor": "셀 윤곽선 색상",
  "cellFillColor": "셀 채우기 색상",
  "transparency": "투명도",
  "cellShapeDropDown": "셀 모양",
  "default": "직사각형",
  "hexagon": "육각형",
  "cellUnitsDropDown": "셀 단위",
  "miles": "마일",
  "kilometers": "킬로미터",
  "feet": "피트",
  "meters": "m",
  "yards": "야드",
  "nautical-miles": "해리",
  "gridOriginDropDown": "격자 원점",
  "lowerLeft": "왼쪽 하단",
  "lowerRight": "오른쪽 하단",
  "upperLeft": "왼쪽 상단",
  "upperRight": "오른쪽 하단",
  "center": "가운데 맞춤",
  "labelTabDescription": "격자 레이블의 모양과 동작을 설정합니다.",
  "labelSettings": "레이블 스타일",
  "font": "글꼴",
  "textSize": "텍스트 크기",
  "textColor": "텍스트 색상",
  "halo": "후광",
  "show": "보기",
  "labelTypeDropDown": "레이블 유형",
  "alphaNumeric": "영숫자",
  "alphaAlpha": "영자",
  "numeric": "숫자",
  "labelDirectionDropDown": "레이블 방향",
  "horizontal": "수평",
  "vertical": "수직",
  "labelOriginDropDown": "레이블 원점",
  "referenceSystemlTabDescription": "기본 참조 체계를 설정합니다.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "설정 잠금 - 이 옵션을 사용하면 사용자가 위젯에 구성되어 있는 설정을 변경할 수 없습니다."
});