define({
  "_widgetLabel": "Padėties suvokimas",
  "locate_incident": "Rasti įvykį",
  "reverse_geocoded_address": "Artimiausias adresas",
  "reverse_geocoded_error": "Negalimas",
  "now": "DABAR",
  "wind": "VĖJAS",
  "SUN": "SEK",
  "MON": "PIR",
  "TUE": "ANT",
  "WED": "TRE",
  "THU": "KET",
  "FRI": "PEN",
  "SAT": "ŠEŠ",
  "actionLabel": "Nustatyti vietą",
  "drawPoint": "Padėti tašką",
  "drawLine": "Brėžti liniją",
  "drawPolygon": "Brėžti plotą",
  "saveIncident": "Įrašyti",
  "clearIncident": "Iš naujo",
  "noFeaturesFound": "Elementų nerasta.",
  "downloadCSV": "Atsisiųsti",
  "sum": "Suma",
  "min": "Minimumas",
  "max": "Maksimumas",
  "avg": "Vidutinis",
  "count": "KIEKIS",
  "area": "PLOTAS",
  "length": "ILGIS",
  "update_btn": "Atlikta",
  "delete_btn": "Pašalinti",
  "get_directions": "Rasti kryptis",
  "incident": "Įvykis",
  "incidents": "Įvykiai",
  "buffer": "Buferis",
  "buffers": "Buferiai",
  "weather": "Orai",
  "poweredBy": "Sukurta naudojant",
  "_featureAction_ActionLabel": "Nustatyti vietą",
  "_featureAction_AddRemoveActionLabel": "Pridėti / pašalinti vietą",
  "snapshot": "SnapShot aplanką sukūrė aplikacijos ID:",
  "user_credentials": "Vartotojas neturi tinkamų teisių.",
  "notPolySnapShot": "Prieš kurdami SnapShot nurodykite buferio nuotolį.",
  "notPolyReport": "Nėra galiojančių rezultatų, kuriuos galima būtų įtraukti į ataskaitą.",
  "notValidDownload": "Tinkamų atsisiųsti rezultatų nėra.",
  "of_append": "iš",
  "layer_append": "sluoksnis",
  "downloadAll": "Atsisiųsti viską",
  "createSnapshot": "Kurti SnapShot",
  "createReport": "Kurti ataskaitą",
  "calculated_results": "Apibendrinta informacija",
  "closest": "Artimiausias elementas",
  "proximity": "Artumas",
  "summary": "Suvestinė",
  "groupedSummary": "Sugrupuoti skaičiavimai",
  "_count": "Viso",
  "approximate": "maždaug",
  "snapshot_name": "Nustatyti momentinės nuotraukos savybes",
  "report_name": "Nustatyti ataskaitų savybes",
  "invalid_snapshot_name": "Nurodytas netinkamas pavadinimas.",
  "invalid_report_name": "Neleistinas ataskaitos pavadinimas.",
  "orientation": "Padėtis",
  "pageSize": "Puslapio dydis",
  "comments": "Komentarai",
  "choose_group": "Grupės",
  "forecast": "Prognozė",
  "select_group": "Pasirinkite grupę",
  "select_group_instruction": "Momentinė nuotrauka bus sukurta ir bendrai naudojama su pasirinkta grupe",
  "information_append": " Informacija",
  "distance": "ATSTUMAS",
  "buffer_invalid": "Įveskite tinkamą skaičių nuo ${min} iki ${max}"
});