define({
  "labelBookmarkName": "الإشارة المرجعية للعرض الحالي",
  "labelPlay": "تشغيل الكل",
  "labelStop": "إيقاف",
  "labelDelete": "حذف",
  "placeholderBookmarkName": "اسم الإشارة المرجعية",
  "errorNameExist": "الإشارات المرجعية موجودة!",
  "errorNameNull": "اسم إشارة مرجعية غير صحيح!",
  "editTip": "تحرير العلامات المرجعية",
  "exitEditTip": "خروج من وضع التحرير",
  "syncTip": "تزامن",
  "cardsTips": "عرض الشبكة",
  "listTips": "عرض القائمة",
  "addBtn": "إضافة",
  "deleteBtn": "حذف",
  "changeThumbnailTip": "تغيير الصورة المُصغرة",
  "dragReorderTip": "ضغط باستمرار وسحب لإعادة الترتيب",
  "deleteBtnTip": "حذف العلامة المرجعية",
  "editBtnTip": "تحرير العلامة المرجعية",
  "withVisibility": "مع رؤية الطبقة",
  "searchBookmark": "بحث",
  "bookmarksFromConfig": "إشارات مرجعية مكونة مُسبقًا",
  "bookmarksFromCache": "إشارات مرجعية مؤقتة محلية",
  "notice": "لاحظ",
  "changeNoticeTips": "سيتم حفظ التغييرات في ذاكرة التخزين المؤقت للمستعرض. ويتم قطع اتصال المزامنة بين عنصر واجهة المستخدم والتكوين الخاص به بمجرد تنفيذ التعديلات.",
  "syncNoticeTips": "وهو ما سيقوم بمسح كل تعديلاتك واستعادة العلامات المرجعية التي تم تكوينها.",
  "dontShowAgain": "لا تعرض ذلك مجددًا",
  "saveVisibility": "حفظ رؤية الطبقة",
  "_widgetLabel": "علامة مرجعية"
});