define({
  "symbolologyTabLabel": "Konfiguriraj simbologijo",
  "facilitiesDescription": "Sloji z lokacijo storitve",
  "demographicsDescription": "Demografski sloj",
  "settingsTitle": "Nastavitve",
  "spillLocationLabel": "Lokacija razlitja",
  "spillLocationButtonLabel": "Konfiguriraj nastavitve lokacije razlitja",
  "IISettingsLabel": "Začetno zajezitveno območje",
  "IIButtonLabel": "Konfiguriraj nastavitve začetne zajezitve",
  "PASettingsLabel": "Varstvena območja",
  "PAButtonLabel": "Konfiguriraj nastavitve varstvenih ukrepov",
  "downwindSettingsLabel": "Območje smeri vetra",
  "downwindButtonLabel": "Konfiguriraj nastavitve smeri vetra",
  "fireSettingsLabel": "Območje požarne zaščite",
  "fireButtonLabel": "Konfiguriraj nastavitve požarne izolacije",
  "bleveSettingsLabel": "Območje izolacije BLEVE",
  "bleveButtonLabel": "Konfiguriraj nastavitve BLEVE",
  "transparency": "Prosojnost",
  "outline": "Obroba",
  "fill": "Polnilo (barva se uporablja le, če je slog nastavljen na enobarvno polnilo)",
  "style": "Slog",
  "lineStyles": {
    "esriSLSDash": "Črtica",
    "esriSLSDashDot": "Črtica pika",
    "esriSLSDashDotDot": "Črtica pika pika",
    "esriSLSDot": "Pika",
    "esriSLSLongDash": "Dolga črtica",
    "esriSLSLongDashDot": "Dolga črtica pika",
    "esriSLSNull": "Brez vrednosti",
    "esriSLSShortDash": "Kratka črtica",
    "esriSLSShortDashDot": "Kratka črtica pika",
    "esriSLSShortDashDotDot": "Kratka črtica pika pika",
    "esriSLSShortDot": "Kratka pika",
    "esriSLSSolid": "Enobarvno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Nazaj",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Diagonalno",
    "esriSFSForwardDiagonal": "Naprej",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Brez vrednosti",
    "esriSFSSolid": "Enobarvno",
    "esriSFSVertical": "Vertikalno"
  }
});