define({
  "queries": "Zapytania",
  "addNew": "Dodaj nowy",
  "newQuery": "Nowe zapytanie",
  "queryLayer": "Warstwa zapytania",
  "setSource": "Ustaw",
  "setDataSource": "Skonfiguruj źródło danych",
  "name": "Nazwa",
  "querySource": "Źródło danych",
  "queryName": "Nazwa zadania",
  "queryDefinition": "Definicja filtru",
  "resultsSetting": "Ustawienie wyników",
  "symbolSetting": "Ustawienie symbolu",
  "resultSettingTip": "Zdefiniuj, które wyniki mają być wyświetlane, oraz sposób ich wyświetlania.",
  "resultItemTitle": "Tytuł każdego elementu wynikowego",
  "resultItemContent": "Te atrybuty pól będą wyświetlane",
  "fieldsSetTip": "Zaznacz pola, które mają być wyświetlane. Wybierz pole, aby zaktualizować jego alias, kolejność i formatowanie.",
  "addField": "Dodaj pole",
  "visibility": "Widoczność",
  "alias": "Alias",
  "specialType": "Typ specjalny",
  "actions": "Działania",
  "none": "Brak",
  "link": "Połącz",
  "image": "Obraz",
  "noField": "Brak pola",
  "operationalLayerTip": "Dodaj wynik jako warstwę operacyjną",
  "setLayerSymbolTip": "Skonfiguruj symbol wyników zapytania: ",
  "setSelectedSymbolTip": "Skonfiguruj symbol wybranego obiektu.",
  "notUseFilter": "Nie stosuj filtrów",
  "setSourceTip": "Skonfiguruj źródło zapytania.",
  "setFilterTip": "Skonfiguruj poprawnie filtr.",
  "ok": "OK",
  "cancel": "Anuluj",
  "noFilterTip": "Jeżeli wyrażenie filtru nie zostanie zdefiniowane, zadanie zapytania zwróci wszystkie obiekty w podanym źródle danych.",
  "relationships": "Zależności",
  "addRelationshipLayer": "Dodaj nową relację",
  "relatedTo": "Powiązane z",
  "selectOption": "Wybierz...",
  "resultItemSorting": "Sortowanie elementów wynikowych",
  "field": "Pole",
  "sortingOrder": "Kolejność",
  "configureFieldsTip": "Proszę skonfigurować pola, według których sortowane będą wyniki wyszukiwania.",
  "setSortingFields": "Skonfiguruj pola sortowania",
  "ascending": "Rosnąco",
  "descending": "Malejąco",
  "sortBy": "Sortuj według",
  "thenBy": "Następnie według",
  "addTask": "Dodaj zadanie",
  "noTasksTip": "Brak skonfigurowanych zapytań. Kliknij opcję „${newQuery}”, aby dodać nowe zapytanie.",
  "infoText": "Informacje",
  "filters": "Filtry",
  "results": "Wyniki",
  "optionsText": "Opcje",
  "summaryText": "Podsumowanie",
  "attributeFilter": "Filtr atrybutów",
  "attributeFilterTip": "Zdefiniuj wyrażenia atrybutów do użytku w widżecie, aby dokonać filtrowania warstwy zapytań.",
  "defineWhereClause": "Zdefiniuj klauzulę WHERE w zapytaniu.",
  "noExpressionDefinedTip": "Nie zdefiniowano wyrażenia. Zostaną zwrócone wszystkie rekordy.",
  "setExpressions": "Skonfiguruj wyrażenia",
  "spatialFilter": "Filtry przestrzenne",
  "spatialFilterTip": "Wybierz filtry przestrzenne, które będą dostępne dla użytkowników.",
  "defaultOption": "Domyślne",
  "useCurrentExtentTip": "Zwracaj tylko obiekty w bieżącym zasięgu mapy",
  "useDrawGraphicTip": "Zwracaj tylko obiekty, które przecinają kształt narysowany na mapie",
  "useFeaturesTip": "Zwracaj tylko obiekty w zależności przestrzennej z obiektami w innej warstwie",
  "noSpatialLimitTip": "Zwracaj obiekty w pełnym zasięgu mapy",
  "drawingTools": "Wybierz narzędzia do kreślenia",
  "bufferSettings": "Włącz opcję buforowania",
  "defaultDistance": "Domyślna odległość",
  "bufferDistance": "Odległość buforowania",
  "defaultUnit": "Jednostka domyślna",
  "miles": "Mile",
  "kilometers": "Kilometry",
  "feet": "Stopy",
  "meters": "Metry",
  "yards": "Jardy",
  "nauticalMiles": "Mile morskie",
  "availableSpatialRelationships": "Wybierz zasady relacji przestrzennych",
  "setSpatialRelationships": "Skonfiguruj zależności przestrzenne",
  "availability": "Dostępność",
  "relationship": "Zależność",
  "label": "Etykieta",
  "intersect": "przecinają",
  "contain": "zawierają",
  "areContainedIn": "są zawarte w",
  "cross": "krzyżują się",
  "envelopeIntersect": "przecinają obwiednię",
  "overlap": "nachodzą",
  "areOverlapped": "są zakryte",
  "touch": "dotyk",
  "within": "w zasięgu",
  "areWithin": "są w zasięgu",
  "indexIntersect": "przecinają indeks",
  "itemTitle": "Tytuł elementu",
  "displayFields": "Pola wyświetlania",
  "sortingFields": "Sortuj elementy wynikowe",
  "setDisplayFields": "Skonfiguruj pola wyświetlania",
  "symbol": "Symbol",
  "setSymbol": "Użyj symbolu niestandardowego",
  "changeSymbolAtRuntime": "Zezwalaj na zmienianie symboli w czasie pracy",
  "serviceSymbolTip": "Użyj symboli zdefiniowanych przez warstwę",
  "exportTip": "Udostępnij wyniki do eksportowania",
  "keepResultsTip": "Utrzymuj wyniki na mapie po zamknięciu widżetu",
  "queryRelatedRecords": "Rekordy powiązane z zapytaniem",
  "createLayerForTaskTip": "Podaj sposób tworzenia warstw przez zadanie zapytania",
  "oneLayerForTaskTip": "Zastąp warstwę za każdym razem, gdy zapytanie jest wykonywane",
  "multipleLayerForTaskTip": "Utwórz nową warstwę za każdym razem, gdy zapytanie jest wykonywane",
  "makeDefault": "Ustaw jako domyślne",
  "icon": "Ikona",
  "newTask": "Nowe zadanie",
  "addTaskTip": "Dodaj do widżetu jedno zapytanie lub ich większą liczbę, aby skonfigurować parametry dla każdego z nich.",
  "webMapPopupTip": "Użyj konfiguracji z okna podręcznego warstwy na mapie internetowej",
  "customPopupTip": "Skonfiguruj zasoby niestandardowe",
  "showResultsSetActions": "Pokaż czynności dla zestawu wyników",
  "zoomTo": "Powiększ do",
  "openAttributeTable": "Wyświetl w tabeli atrybutów",
  "content": "Zawartość",
  "displaySQLTip": "Wyświetl wyrażenie języka SQL dla użytkowników końcowych",
  "useLayerDefaultSymbol": "Użyj symbolu domyślnego warstwy",
  "setCustomIcon": "Ustaw ikonę niestandardową",
  "layerDefaultSymbolTip": "Użyj symbolu domyślnego warstwy",
  "uploadImage": "Prześlij obraz",
  "attributeCriteira": "Kryteria atrybutowe",
  "specifyFilterAtRuntimeTip": "Użytkownicy muszą określić parametry dla tego wyrażenia.",
  "value": "WARTOŚĆ",
  "hideLayersTip": "Wyłącz warstwy wyników zapytania po zamknięciu widżetu.",
  "tabLabels": "Etykiety kart",
  "tasks": "Zadania",
  "queryCriteira": "Kryteria zapytania",
  "allowCustomQuery": "Zezwalaj na tworzenie zapytania niestandardowego"
});