define({
  "queries": "Consultas",
  "addNew": "Agregar nuevo",
  "newQuery": "Nueva consulta",
  "queryLayer": "Capa de consulta",
  "setSource": "Definir",
  "setDataSource": "Definir fuente de datos",
  "name": "Nombre",
  "querySource": "Fuente de datos",
  "queryName": "Nombre de tarea",
  "queryDefinition": "Definición de filtro",
  "resultsSetting": "Configuración de resultados",
  "symbolSetting": "Configuración de símbolo",
  "resultSettingTip": "Define qué se debe mostrar en los resultados de salida y cómo mostrarlo.",
  "resultItemTitle": "Título de cada elemento de resultado",
  "resultItemContent": "Se mostrarán estos atributos de campo",
  "fieldsSetTip": "Marca los campos que deseas mostrar. Selecciona un campo para actualizar su alias, su orden y su formato.",
  "addField": "Agregar campo",
  "visibility": "Visibilidad",
  "alias": "Alias",
  "specialType": "Tipo especial",
  "actions": "Acciones",
  "none": "Ninguna",
  "link": "Vínculo",
  "image": "Imagen",
  "noField": "Sin campo",
  "operationalLayerTip": "Agregar resultado como capa operativa",
  "setLayerSymbolTip": "Establecer el símbolo para los resultados de consulta: ",
  "setSelectedSymbolTip": "Establece el símbolo de la entidad seleccionada.",
  "notUseFilter": "No utilizar filtro",
  "setSourceTip": "Define la fuente de consulta.",
  "setFilterTip": "Define el filtro correctamente.",
  "ok": "Aceptar",
  "cancel": "Cancelar",
  "noFilterTip": "Sin expresión de filtro definida, esta tarea de consulta enumerará todas las entidades de la fuente de datos especificada.",
  "relationships": "Relaciones",
  "addRelationshipLayer": "Agregar nueva relación",
  "relatedTo": "Relacionado con",
  "selectOption": "Selecciona...",
  "resultItemSorting": "Ordenación de los resultados",
  "field": "Campo",
  "sortingOrder": "Orden",
  "configureFieldsTip": "Configura los campos según los cuales se debe ordenar el resultado de la consulta.",
  "setSortingFields": "Definir campos de ordenación",
  "ascending": "Ascendente",
  "descending": "Descendente",
  "sortBy": "Ordenar por",
  "thenBy": "A continuación por",
  "addTask": "Agregar tarea",
  "noTasksTip": "No hay consultas configuradas. Haga clic en \"${newQuery}\" para agregar una nueva.",
  "infoText": "Información",
  "filters": "Filtros",
  "results": "Resultados",
  "optionsText": "Opciones",
  "summaryText": "Resumen",
  "attributeFilter": "Filtro de atributos",
  "attributeFilterTip": "Define las expresiones de atributos que se deben usar en el widget para filtrar la capa de consulta.",
  "defineWhereClause": "Defina una cláusula WHERE para la consulta.",
  "noExpressionDefinedTip": "No se ha definido ninguna expresión. Se devolverán todos los registros.",
  "setExpressions": "Definir expresiones",
  "spatialFilter": "Filtros espaciales",
  "spatialFilterTip": "Elija qué filtros espaciales estarán disponibles para los usuarios finales.",
  "defaultOption": "Predeterminado",
  "useCurrentExtentTip": "Devolver solo entidades contenidas en la extensión de mapa actual",
  "useDrawGraphicTip": "Devolver solo las entidades que intersecan con la forma dibujada en el mapa",
  "useFeaturesTip": "Devolver solo entidades que tengan una relación espacial con entidades de otra capa",
  "noSpatialLimitTip": "Devolver entidades contenidas en la extensión completa del mapa",
  "drawingTools": "Elegir herramientas de dibujo",
  "bufferSettings": "Habilitar opción de zona de influencia",
  "defaultDistance": "Distancia predeterminada",
  "bufferDistance": "Distancia de zona de influencia",
  "defaultUnit": "Unidad predeterminada",
  "miles": "Millas",
  "kilometers": "Kilómetros",
  "feet": "Pies",
  "meters": "Metros",
  "yards": "Yardas",
  "nauticalMiles": "Millas náuticas",
  "availableSpatialRelationships": "Elegir reglas de relación espacial",
  "setSpatialRelationships": "Definir relaciones espaciales",
  "availability": "Disponibilidad",
  "relationship": "Relación",
  "label": "Etiqueta",
  "intersect": "intersecar",
  "contain": "contienen",
  "areContainedIn": "están contenidas en",
  "cross": "cruz",
  "envelopeIntersect": "intersección con el contorno",
  "overlap": "superponer",
  "areOverlapped": "se superponen",
  "touch": "se tocan",
  "within": "dentro de",
  "areWithin": "están dentro de",
  "indexIntersect": "con intersección de índice",
  "itemTitle": "Título del elemento",
  "displayFields": "Campos de visualización",
  "sortingFields": "Ordenar elementos de resultados",
  "setDisplayFields": "Definir campos de visualización",
  "symbol": "Símbolo",
  "setSymbol": "Utilizar símbolo personalizado",
  "changeSymbolAtRuntime": "Permitir cambiar símbolos en tiempo de ejecución",
  "serviceSymbolTip": "Usar símbolos definidos por la capa",
  "exportTip": "Permitir la exportación de resultados",
  "keepResultsTip": "Conservar resultados en el mapa después de cerrar el widget",
  "queryRelatedRecords": "Consultar registros relacionados",
  "createLayerForTaskTip": "Especifica cómo crea las capas la tarea de consulta",
  "oneLayerForTaskTip": "Sobrescribir la capa cada vez que se ejecute la consulta",
  "multipleLayerForTaskTip": "Crear una nueva capa cada vez que se ejecute la consulta",
  "makeDefault": "Definir como predeterminado",
  "icon": "Icono",
  "newTask": "Nueva tarea",
  "addTaskTip": "Agregue una o varias consultas al widget y configure los parámetros para cada una de ellas.",
  "webMapPopupTip": "Utilizar la configuración de los elementos emergentes de la capa en el mapa web",
  "customPopupTip": "Configurar contenido personalizado",
  "showResultsSetActions": "Mostrar acciones para el conjunto de resultados",
  "zoomTo": "Acercar",
  "openAttributeTable": "Ver en la tabla de atributos",
  "content": "Contenido",
  "displaySQLTip": "Mostrar expresión SQL para usuarios finales",
  "useLayerDefaultSymbol": "Usar símbolo predeterminado de capa",
  "setCustomIcon": "Definir icono personalizado",
  "layerDefaultSymbolTip": "Usar símbolo predeterminado de capa",
  "uploadImage": "Cargar una imagen",
  "attributeCriteira": "Criterios de atributos",
  "specifyFilterAtRuntimeTip": "Los usuarios tendrán que especificar parámetros para esta expresión.",
  "value": "VALOR",
  "hideLayersTip": "Desactive las capas de resultados de la consulta cuando el widget esté cerrado.",
  "tabLabels": "Etiquetas de pestaña",
  "tasks": "Tareas",
  "queryCriteira": "Criterios de consulta",
  "allowCustomQuery": "Permitir la creación de consultas personalizadas"
});