define({
  "_widgetLabel": "Distância e Direção",
  "tabLineTitle": "Linha",
  "tabCircleTitle": "Círculo",
  "tabEllipseTitle": "Elipse",
  "tabRingsTitle": "Anéis",
  "multipleNotationsMessage": " anotações que correspondem à sua entrada. Confirme o que você gostaria de utilizar:",
  "invalidCoordinateMessage": "Coordenada Inválida",
  "confirmInputNotationMessage": "Confirmar Anotação de Entrada",
  "prefixSuffixMessage": "As coordenadas de entrada foram detectadas como ambas tendo um prefixo e um sufixo do valor de latitude ou longitude, a coordenada retornada é baseada no prefixo.",
  "rememberDecisionMessage": "Lembrar de minha decisão e não perguntar novamente.<br/>",
  "majorAxisTooltipMessage": "Clique no comprimento do eixo maior",
  "minorAxisTooltipMessage": "Mova o mouse de volta para a posição inicial para definir o eixo menor e finalizar a elipse de desenho",
  "clickToFinishLineMessage": "Clique para finalizar a linha de desenho",
  "doubleClickEllipseMesage": "Clique duas vezes para finalizar o desenho dos anéis de intervalo",
  "invalidCoordinateTypeMessage": "Não foi possível determinar o tipo da coordenada de entrada. Verifique sua entrada",
  "noCenterPointSetMessage": "Nenhum ponto central configurado. Verifique sua entrada",
  "ellipseMajorAxis": "Eixo Maior",
  "ellipseMinorAxis": "Eixo Menor",
  "degreesRangeMessage": "O valor deve estar entre 0 e 360",
  "millsRangeMessage": "O valor deve estar entre 0 e 6400",
  "lengthLabel": "Comprimento",
  "angleLabel": "Ângulo",
  "startPointLabel": "Ponto Inicial",
  "endPointLabel": "Ponto Final",
  "centerPointLabel": "Ponto Central",
  "distanceTableErrorMessage": "A tabela de distância está vazia. Certifique-se de inserir algumas distâncias.",
  "setCoordFormatStringMessage": "Definir String de Formato de Coordenadas",
  "prefixMessage": "Adicionar prefixo '+/-' para números positivos e negativos",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Minutos Decimais - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Minutos Decimais - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra da Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)",
  "circleTitle": "Criar Forma de Círculo",
  "radiusLabel": "Raio",
  "diameterLabel": "Diâmetro",
  "startPointPlaceHolderLabel": "Inserir Coordenadas",
  "formatInputLabel": "Entrada de Formato",
  "drawCircleLabel": "Desenhar Círculo",
  "drawLineLabel": "Desenhar Linha",
  "createCircleInteractivelyLabel": "Criar Círculo de Forma Interativa",
  "rangeErrorMessage": "Raio ou diâmetro inválido",
  "numericInvalidMessage": "Digite um valor numérico",
  "timeLabel": "Tempo",
  "invalidTimeMessage": "Valor de tempo inválido",
  "hoursLabel": "Horas",
  "minutesLabel": "Minutos",
  "secondsLabel": "Segundos",
  "rateLabel": "Taxa",
  "invalidDistanceMessage": "Valor de distância inválido",
  "feetSecondsLabel": "Pés / segundos",
  "feetHourLabel": "Pés / hora",
  "kmSecondLabel": "Quilômetros / segundos",
  "kmHourLabel": "Quilômetro / hora",
  "metersSecondLabel": "Metros / segundos",
  "metersHourLabel": "Metros / hora",
  "milesSecondLabel": "Milhas / segundos",
  "milesHourLabel": "Milhas / hora",
  "nauticalMilesSecondLabel": "Milhas náuticas / segundos",
  "nauticalMilesHourLabel": "Milhas náuticas / hora",
  "clearGraphicsLabel": "Apagar Gráficos",
  "ellipseTypeLabel": "Tipo de Elipse",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Total",
  "drawEllipseLabel": "Desenhar Elipse",
  "createEllipseInteractively": "Criar Elipse de Forma Interativa",
  "axisLabel": "Eixo",
  "majorRadiusLabel": "Raio (Maior)",
  "axisErrorMessage": "O valor deve ser maior que 0",
  "minorRadiusLabel": "Raio (Menor)",
  "orientationLabel": "Orientação",
  "orientationErrorMessage": "O valor deve estar entre 0 e 360",
  "warningMessage": "Aviso: Os gráficos gerados com a ferramenta de elipse não são geodésicos",
  "fromLabel": "De",
  "distanceBearingLabel": "Distância e Direção",
  "pointsLabel": "Pontos",
  "createLineInteractively": "Criar Linha de Forma Interativa",
  "lineLengthErrorMessage": "Comprimento de Linha Inválido",
  "degreesLabel": "Graus",
  "milsLabel": "Milésimo",
  "lineTypeLabel": "Tipo",
  "interactiveLabel": "Interativo",
  "fixedLabel": "Fixo",
  "originLabel": "Origem",
  "cumulativeLabel": "Cumulativo",
  "numberOfRingsLabel": "Número de Anéis",
  "ringsErrorMessage": "número de anéis inválido",
  "distanceBetweenRingsLabel": "Distância Entre Anéis",
  "ringsDecimalErrorMessage": "Digite um valor numérico para 2 casas decimais",
  "distanceUnitsLabel": "Unidades de Distância",
  "distancesLabel": "Distâncias",
  "numberOfRadialsLabel": "Número de Radiais",
  "upLabel": "Para Cima",
  "downLabel": "Para Baixo",
  "deleteLabel": "Excluir",
  "radialsErrorMessage": "Número de radiais inválidos. O máximo permitido é 360",
  "addPointLabel": "Adicionar Ponto",
  "valueLabel": "Valor",
  "valueText": "Inserir Valor",
  "actionLabel": "Ação"
});