define({
  "add": "Fare clic per aggiungere nuovo",
  "title": "Titolo",
  "placeholderBookmarkName": "Nome segnalibro",
  "ok": "OK",
  "cancel": "Annulla",
  "warning": "Completare la modifica.",
  "edit": "Modifica segnalibro",
  "errorNameExist": "Segnalibro esistente.",
  "errorNameNull": "Nome segnalibro non valido.",
  "addBookmark": "Crea nuovo",
  "thumbnail": "Anteprima",
  "thumbnailHint": "Fare clic sull'immagine per aggiornare",
  "displayBookmarksAs": "Mostra segnalibri come",
  "cards": "Schede",
  "list": "Elenco",
  "cardsTips": "Vista scheda",
  "listTips": "Vista elenco",
  "makeAsDefault": "Imposta come predefinito",
  "default": "Predefinito",
  "editable": "Consenti di aggiungere segnalibri al widget.",
  "alwaysSync": "Mostra segnalibri dalla mappa Web",
  "configCustom": "Mostra segnalibri personalizzati",
  "import": "Importa",
  "create": "Crea",
  "importTitle": "Importa segnalibri",
  "importFromWeb": "Importa segnalibri dalla mappa Web attuale",
  "selectAll": "Seleziona tutto",
  "noBookmarkInConfig": "Fare clic su â€œImportaâ€ o â€œCrea nuovoâ€ per aggiungere segnalibri.",
  "noBookmarkInWebMap": "Nessun segnalibro configurato nella mappa.",
  "extent": "Estensione",
  "saveExtent": "Salva estensione della mappa in questo segnalibro",
  "savelayers": "Salva la visibilità del layer",
  "withVisibility": "Con visibilità del layer",
  "bookmark": "Segnalibro",
  "addBtn": "Aggiungi",
  "deleteBtn": "Elimina",
  "editBtn": "Modifica",
  "dragReorderTip": "Seleziona e trascina per riordinare",
  "deleteBtnTip": "Cancella segnalibro",
  "editBtnTip": "Modifica segnalibro"
});