define({
  "_widgetLabel": "Truy vấn",
  "executeQueryTip": "Bấm vào một trong các mục tác vụ sau để thực hiện truy vấn.",
  "invalidConfig": "Cấu hình không hợp lệ. Vui lòng sử dụng trang thiết lập Truy vấn để tải đúng cấu hình.",
  "queryParams": "Tùy chọn",
  "parameters": "TÙY CHỌN",
  "queries": "TRUY VẤN",
  "apply": "Áp dụng",
  "queryResults": "Kết quả",
  "clear": "Xóa",
  "noResults": "Không tìm thấy đối tượng nào.",
  "queryError": "Truy vấn thất bại!",
  "numberFound": "Số lượng đối tượng được tìm thấy",
  "mapExtentTip": "Giới hạn kết quả theo khu vực bản đồ hiện tại.",
  "noValue": "Không có giá trị nào",
  "and": "và",
  "stringOperatorIs": "là",
  "stringOperatorIsNot": "không phải là",
  "stringOperatorStartsWith": "bắt đầu với",
  "stringOperatorEndsWith": "kết thúc với",
  "stringOperatorContains": "chứa",
  "stringOperatorDoesNotContain": "không chứa",
  "stringOperatorIsBlank": "trống",
  "stringOperatorIsNotBlank": "không trống",
  "dateOperatorIsOn": "vào ngày",
  "dateOperatorIsNotOn": "không vào ngày",
  "dateOperatorIsBefore": "trước",
  "dateOperatorIsAfter": "sau",
  "dateOperatorDays": "ngày",
  "dateOperatorWeeks": "tuần",
  "dateOperatorMonths": "tháng",
  "dateOperatorInTheLast": "trong ngày cuối",
  "dateOperatorNotInTheLast": "không phải cuối cùng",
  "dateOperatorIsBetween": "ở giữa",
  "dateOperatorIsNotBetween": "không ở giữa",
  "dateOperatorIsBlank": "trống",
  "dateOperatorIsNotBlank": "không trống",
  "numberOperatorIs": "là",
  "numberOperatorIsNot": "không phải là",
  "numberOperatorIsAtLeast": "tối thiểu",
  "numberOperatorIsLessThan": "ít hơn",
  "numberOperatorIsAtMost": "tối đa",
  "numberOperatorIsGreaterThan": "nhiều hơn",
  "numberOperatorIsBetween": "ở giữa",
  "numberOperatorIsNotBetween": "không ở giữa",
  "numberOperatorIsBlank": "trống",
  "numberOperatorIsNotBlank": "không trống",
  "operationalLayerTip": "Thêm kết quả như lớp hoạt động",
  "queryResult": "Kết quả truy vấn",
  "specifyParamsTip": "Chỉ định tham số cho tác vụ này",
  "useSpatialFilter": "Sử dụng bộ lọc không gian để giới hạn các đối tượng",
  "useCurrentMapExtent": "Chỉ các đối tượng giao cắt với khu vực bản đồ hiện tại",
  "drawGraphicOnMap": "Chỉ các đối tượng liên quan đến khu vực do người dùng xác định",
  "specifySpatialFilterMsg": "Vui lòng chỉ định bộ lọc không gian cho tác vụ này.",
  "clearResults": "Xóa kết quả",
  "operationalTip": "Nếu chọn tùy chọn này, kết quả sẽ được giữ trên bản đồ cho đến khi nút \"${clearResults}\" được bấm.",
  "noneQueryTip": "Không có tác vụ truy vấn nào được cấu hình cho tiện ích này.",
  "noPermissionsMsg": "Bạn không có quyền truy cập vào dịch vụ này.",
  "attributesFromRelationship": "Thuộc tính từ bảng liên quan",
  "tasks": "Tác vụ",
  "applySpatialFilterToLimitResults": "Áp dụng bộ lọc không gian để giới hạn kết quả",
  "useCurrentExtentTip": "Chỉ trả về đối tượng trong phạm vi bản đồ hiện tại",
  "useDrawGraphicTip": "Chỉ trả về các đối tượng giao cắt với hình dạng đã được vẽ trên bản đồ",
  "useFeaturesTip": "Chỉ trả về đối tượng có mối quan hệ về không gian với đối tượng trong lớp khác",
  "noSpatialLimitTip": "Trả về đối tượng trong phạm vi đầy đủ của bản đồ",
  "applySearchDistance": "Áp dụng khoảng cách tìm kiếm",
  "spatialRelationship": "Mối quan hệ về không gian",
  "relatedLayer": "Lớp có liên quan",
  "bufferDistance": "Khoảng cách vùng đệm",
  "miles": "Dặm",
  "kilometers": "Kilômét",
  "feet": "Feet",
  "meters": "Mét",
  "yards": "Thước",
  "nauticalMiles": "Hải lý",
  "back": "Quay lại",
  "execute": "Thực hiện",
  "zoomTo": "Phóng tới",
  "openAttributeTable": "Xem trong Bảng Thuộc tính",
  "noResult": "Không có kết quả.",
  "noTask": "Không có tác vụ.",
  "removeThisResult": "Xóa kết quả Này",
  "attributeCriteira": "Tiêu chí thuộc tính",
  "spatialFilter": "Bộ lọc không gian",
  "value": "GIÁ TRỊ",
  "noAttributeSpatialFilterTip": "Không có bộ lọc nào được xác định. Tất cả đối tượng sẽ được trả về.",
  "showAllRelatedRecords": "Hiển thị tất cả các bản ghi liên quan",
  "changeSymbol": "Thay đổi ký hiệu",
  "queryCriteira": "Tiêu chuẩn truy vấn",
  "customQuery": "Truy vấn tùy chỉnh",
  "layer": "Lớp",
  "createCustomQuery": "Tạo truy vấn tùy chỉnh."
});