define({
  "queries": "Vaicājumi",
  "addNew": "Pievienot jaunu",
  "newQuery": "Jauns vaicājums",
  "queryLayer": "Vaicājuma slānis",
  "setSource": "Iestatīt",
  "setDataSource": "Iestatīt datu avotu",
  "name": "Nosaukums",
  "querySource": "Datu avots",
  "queryName": "Uzdevuma nosaukums",
  "queryDefinition": "Filtra definīcija",
  "resultsSetting": "Rezultātu iestatījums",
  "symbolSetting": "Simbola iestatījums",
  "resultSettingTip": "Definējiet parādāmos izvades rezultātus un parādīšanas veidu.",
  "resultItemTitle": "Katras rezultāta vienības virsraksts",
  "resultItemContent": "Šie lauka atribūti būs redzami",
  "fieldsSetTip": "Atzīmējiet laukus, kuri jārāda. Izvēlieties lauku, lai atjauninātu tā aizstājvārdu, kārtotu vai formatētu to.",
  "addField": "Pievienot lauku",
  "visibility": "Redzamība",
  "alias": "Aizstājvārds",
  "specialType": "Īpašais veids",
  "actions": "Darbības",
  "none": "Nav",
  "link": "Saite",
  "image": "Attēls",
  "noField": "Nav lauka",
  "operationalLayerTip": "Pievienot rezultātu kā darbības slāni",
  "setLayerSymbolTip": "Iestatiet vaicājuma rezultātu simbolu: ",
  "setSelectedSymbolTip": "Iestatiet izraudzītā elementa simbolu.",
  "notUseFilter": "Neizmantot filtru",
  "setSourceTip": "Iestatiet vaicājuma avotu.",
  "setFilterTip": "Lūdzu, pareizi iestatiet filtru.",
  "ok": "Labi",
  "cancel": "Atcelt",
  "noFilterTip": "Bez definētas filtra izteiksmes šajā vaicājuma uzdevumā būs norādīti visi elementi norādītajā datu avotā.",
  "relationships": "Attiecības",
  "addRelationshipLayer": "Pievienot jaunu attiecību",
  "relatedTo": "Saistīts ar",
  "selectOption": "Lūdzu, izvēlieties..",
  "resultItemSorting": "Rezultātu vienību kārtošana",
  "field": "Lauks",
  "sortingOrder": "Secība",
  "configureFieldsTip": "Lūdzu, konfigurējiet laukus, pēc kuriem tiks veikta vaicājuma rezultātu kārtošana.",
  "setSortingFields": "Iestatiet kārtošanas laukus",
  "ascending": "Pieaugoši",
  "descending": "Dilstošā secībā",
  "sortBy": "Kārtot pēc",
  "thenBy": "Pēc tam pēc",
  "addTask": "Pievienot uzdevumu",
  "noTasksTip": "Nav konfigurēts neviens vaicājums. Lai pievienotu jaunu, noklikšķiniet uz \"${newQuery}\".",
  "infoText": "Informācija",
  "filters": "Filtri",
  "results": "Rezultāti",
  "optionsText": "Opcijas",
  "summaryText": "Kopsavilkums",
  "attributeFilter": "Atribūtu filtrs",
  "attributeFilterTip": "Definējiet atribūtu izteiksmes izmantošanai logrīkā, lai filtrētu vaicājumu slāni.",
  "defineWhereClause": "Vaicājumam definējiet klauzulu Kur.",
  "noExpressionDefinedTip": "Nav definēta neviena izteiksme. Visi ieraksti tiks atgriezti.",
  "setExpressions": "Iestatīt izteiksmes",
  "spatialFilter": "Telpiskie filtri",
  "spatialFilterTip": "Izvēlieties, kuri telpiskie filtri būs pieejami lietotājiem.",
  "defaultOption": "Noklusējums",
  "useCurrentExtentTip": "Atgriezt elementus tikai pašreizējā kartes pārklājumā",
  "useDrawGraphicTip": "Atgriezt tikai elementus, kas šķērso kartē uzzīmēto formu",
  "useFeaturesTip": "Atgriezt tikai tos elementus, kuriem ir telpiskās attiecības ar elementiem citā slānī",
  "noSpatialLimitTip": "Atgriezt elementus pilnā kartes pārklājumā",
  "drawingTools": "Izvēlēties zīmēšanas rīkus",
  "bufferSettings": "Iespējot buferzonas opciju",
  "defaultDistance": "Noklusējuma attālums",
  "bufferDistance": "Buferzonas attālums",
  "defaultUnit": "Noklusējuma vienība",
  "miles": "Jūdzes",
  "kilometers": "Kilometri",
  "feet": "Pēdas",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Jūras jūdzes",
  "availableSpatialRelationships": "Izvēlēties telpisko attiecību noteikumus",
  "setSpatialRelationships": "Iestatīt telpiskās attiecības",
  "availability": "Pieejamība",
  "relationship": "Attiecības",
  "label": "Nosaukums",
  "intersect": "šķērso",
  "contain": "satur",
  "areContainedIn": "ietilpst",
  "cross": "krustojums",
  "envelopeIntersect": "aploksne šķērso",
  "overlap": "pārklāj",
  "areOverlapped": "ir pārklāts",
  "touch": "skāriens",
  "within": "ietver",
  "areWithin": "ietverts",
  "indexIntersect": "indekss šķērso",
  "itemTitle": "Vienības virsraksts",
  "displayFields": "Rādīt laukus",
  "sortingFields": "Kārtot rezultāta vienības",
  "setDisplayFields": "Iestatīt rādāmos laukus",
  "symbol": "Simbols",
  "setSymbol": "Izmantot pielāgotu simbolu",
  "changeSymbolAtRuntime": "Atļaut mainīt simbolus izpildlaikā",
  "serviceSymbolTip": "Izmantot slāņa definētos simbolus",
  "exportTip": "Atļaut eksportēt rezultātus",
  "keepResultsTip": "Pēc logrīka aizvēršanas paturēt rezultātus kartē",
  "queryRelatedRecords": "Izpildīt vaicājumu saistītajos ierakstos",
  "createLayerForTaskTip": "Norādīt, kā vaicājuma uzdevums izveido slāņus",
  "oneLayerForTaskTip": "Pārrakstīt slāni katru reizi, kad tiek izpildīts vaicājums",
  "multipleLayerForTaskTip": "Izveidot jaunu slāni katru reizi, kad tiek izpildīts uzdevums",
  "makeDefault": "Padarīt par noklusējumu",
  "icon": "Ikona",
  "newTask": "Jauns uzdevums",
  "addTaskTip": "Pievienojiet logrīkam vienu vai vairākus vaicājumus un konfigurējiet parametrus katram no tiem.",
  "webMapPopupTip": "Tīmekļa kartē izmantot slāņa uznirstošā loga konfigurāciju",
  "customPopupTip": "Konfigurēt pielāgotu saturu",
  "showResultsSetActions": "Rādīt rezultātu kopas darbības",
  "zoomTo": "Pietuvināt",
  "openAttributeTable": "Skatīt atribūtu tabulā",
  "content": "Saturs",
  "displaySQLTip": "Parādīt SQL izteiksmi lietotājiem",
  "useLayerDefaultSymbol": "Izmantot slāņa noklusējuma simbolu",
  "setCustomIcon": "Iestatīt pielāgotu ikonu",
  "layerDefaultSymbolTip": "Izmantot slāņa noklusējuma simbolu",
  "uploadImage": "Augšupielādēt attēlu",
  "attributeCriteira": "Atribūtu kritēriji",
  "specifyFilterAtRuntimeTip": "Lietotājiem būs jānorāda šīs izteiksmes parametri.",
  "value": "VĒRTĪBA",
  "hideLayersTip": "Izslēgt vaicājumu rezultātu slāņus, kad logrīks ir aizvērts.",
  "tabLabels": "Cilnes etiķetes",
  "tasks": "Uzdevumi",
  "queryCriteira": "Vaicājuma kritēriji",
  "allowCustomQuery": "Atļaut izveidot pielāgotu vaicājumu"
});