define({
  "chartSettingLabel": "Настройки диаграммы",
  "addNewLabel": "Добавить новое",
  "generalSettingLabel": "Общие настройки",
  "searchSourceSettingLabel": "Параметры источника поиска",
  "layerChooser": {
    "title": "Выберите слой для диаграммы",
    "selectPolygonLayerLabel": "Выбрать слой",
    "selectPolygonLayerHintText": "Подсказка: Если настроено несколько диаграмм, то слои должно быть одинакового типа геометрии",
    "selectRelatedTableLayerLabel": "Выберите таблицу, связанную со слоем",
    "selectRelatedTableLayerHintText": "Подсказка: Отображаются только таблицы с числовыми полями",
    "errorInSelectingPolygonLayer": "Выберите слой, у которого есть связанный точечный слой.",
    "errorInSelectingRelatedLayer": "Выберите для слоя допустимый связанный слой/таблицу.",
    "polygonLayerNotHavingRelationships": "Выберите слой, у которого нет связанного слоя/таблицы."
  },
  "ChartSetting": {
    "sectionTitle": "Название раздела",
    "sectionTitleHintText": "Подсказка: Отображается в заголовке названия раздела",
    "chartTitle": "Заголовок диаграммы",
    "chartTitleHintText": "Подсказка: Отображение центрируется наверху диаграммы",
    "chartDescription": "Описание",
    "chartDescriptionHintText": "Подсказка: Отображение центрируется внизу диаграммы",
    "chartType": "Тип диаграммы",
    "barChart": "Столбчатая диаграмма",
    "pieChart": "Круговая диаграмма",
    "polarChart": "Полярная диаграмма",
    "dataSeriesField": "Поле серий данных",
    "labelField": "Поле подписи",
    "chartColor": "Цвет диаграммы",
    "singleColor": "Один цвет",
    "colorByTheme": "Цвет по теме",
    "colorByFieldValue": "Цвет по значению поля",
    "xAxisTitle": "Заголовок по оси X",
    "xAxisHintText": "Подсказка: Заголовок по оси X",
    "yAxisTitle": "Заголовок по оси Y",
    "yAxisHintText": "Подсказка: Заголовок по оси Y",
    "fieldColorLabel": "Подпись",
    "fieldColorColor": "Цвет",
    "defaultFieldSelectLabel": "Выбрать",
    "errMsgFieldValuesNotFound": "Невозможно найти значения для выбранного поля",
    "errMsgSectionTitle": "Введите заголовок раздела",
    "errMsgFieldByValue": "Выберите значение поля",
    "settingTabTitle": "Параметр",
    "layoutTabTitle": "Компоновка",
    "polarChartSelectFieldsHintText": "Подсказка: Выберите поля для создания полярной диаграммы",
    "visibilityText": "Видимость",
    "fieldNameText": "Имя поля",
    "aliasNameText": "Псевдоним",
    "errMsgPolarFieldsRequired": "Выберите три или более полей для создания полярной диаграммы",
    "polarChartPolygonFillLabel": "Заполнение полигона",
    "polarChartPolygonFillHintText": "Подсказка: Установите отметку, чтобы отобразить заливку полигона в полярной диаграмме",
    "viewLayoutLabel": "Компоновка",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Общие параметры",
    "locationSymbolLabel": "Графический символ местоположения",
    "locationSymbolHintText": "Подсказка: Используется для отображения символа адресов и местоположений, на которых щелкнули",
    "refreshIntervalLabel": "Интервал обновления",
    "refreshIntervalHintText": "Подсказка: Используется для обновления диаграмм на основании этого интервала. Укажите значение от 1 до 1440 минут",
    "errMsgRefreshInterval": "Укажите интервал обновления от 0 до 1440 минут.",
    "symbolPickerPreviewText": "Просмотр:",
    "showToolToSelectLabel": "Кнопка Установить местоположение",
    "showToolToSelectHintText": "Подсказка: Предоставьте кнопки установки местоположения на карте вместо того, чтобы устанавливать местоположение щелчком на карте"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Параметры источника поиска",
    "searchSourceSettingTitle": "Параметры источника поиска",
    "searchSourceSettingTitleHintText": "Добавить и настроить сервисы геокодирования или векторные слои в качестве источников для поиска. Эти указанные источники определяют, что будет доступно для поиска в соответствующем диалоговом окне",
    "addSearchSourceLabel": "Добавить источник поиска",
    "featureLayerLabel": "Векторный слой",
    "geocoderLabel": "Геокодер",
    "nameTitle": "Имя",
    "generalSettingLabel": "Общие параметры",
    "allPlaceholderLabel": "Замещающий текст для поиска всего:",
    "allPlaceholderHintText": "Подсказка: Введите текст, который будет показан как текст-заполнитель во время поиска по всем слоям и геокодерам.",
    "generalSettingCheckboxLabel": "Показать всплывающее окно для найденного объекта или местоположения",
    "countryCode": "Коды стран или регионов",
    "countryCodeEg": "Пример ",
    "countryCodeHint": "Не заполняйте, чтобы искать по всем странам и регионам",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Искать только в пределах текущего экстента карты",
    "zoomScale": "Масштаб",
    "locatorUrl": "URL-адрес геокодера",
    "locatorName": "Имя геокодера",
    "locatorExample": "Пример",
    "locatorWarning": "Эта версия сервиса геокодирования не поддерживается. Виджет поддерживает сервис геокодирования версии 10.0 и более новые.",
    "locatorTips": "Нет предположений, так как сервис геокодирования не поддерживает возможность предположений.",
    "layerSource": "Источник слоя",
    "setLayerSource": "Установить источник слоя",
    "setGeocoderURL": "Задать URL геокодера",
    "searchLayerTips": "Нет предположений, так как сервис пространственных объектов не поддерживает возможность пагинации.",
    "placeholder": "Замещающий текст",
    "searchFields": "Поля поиска",
    "displayField": "Отображаемое поле",
    "exactMatch": "Точное совпадение",
    "maxSuggestions": "Максимум предложений",
    "maxResults": "Максимум результатов",
    "enableLocalSearch": "Включить локальный поиск",
    "minScale": "Минимальный масштаб",
    "minScaleHint": "Когда масштаб карты крупнее данного масштаба, применяется локальный поиск",
    "radius": "Радиус",
    "radiusHint": "Укажите радиус области вокруг текущего центра карты. Он будет использоваться для повышения ранга кандидатов геокодирования так, чтобы первыми возвращались кандидаты, расположенные ближе всего",
    "meters": "Метры",
    "setSearchFields": "Установить поля для поиска",
    "set": "Задать",
    "fieldName": "Имя",
    "invalidUrlTip": "URL ${URL} является недопустимым или недостижимым."
  }
});