define({
  "chartSettingLabel": "การตั้งค่าแผนภูมิ",
  "addNewLabel": "เพิ่มข้อมูลใหม่",
  "generalSettingLabel": "การคั้งค่าทั่วไป",
  "searchSourceSettingLabel": "ตั้งค่าการค้นหาแหล่งที่มา",
  "layerChooser": {
    "title": "เลือกชั้นข้อมูลเพื่อสร้างแผนภูมิ",
    "selectPolygonLayerLabel": "เลือกชั้นข้อมูล",
    "selectPolygonLayerHintText": "คำแนะนำ : หากตั้งค่าแผนภูมิมากกว่า 1 ชั้นข้อมูลจะต้องเป็นประเภทเดียวกัน",
    "selectRelatedTableLayerLabel": "เลือกตารางที่สัมพันธ์กับชั้นข้อมูล",
    "selectRelatedTableLayerHintText": "คำแนะนำ : เฉพาะตารางที่เป็นตัวเลขเท่านั้นจะถูกแสดงผล",
    "errorInSelectingPolygonLayer": "กรุณาเลือกชั้นข้อมูลที่สัมพันธ์กับจุด",
    "errorInSelectingRelatedLayer": "กรุณาเลือกค่าที่ถูกต้องสัมพันธ์กับตาราง / ชั้นข้อมูล",
    "polygonLayerNotHavingRelationships": "เลือกข้อมูลที่ไม่มีความสัมพันธ์กับตาราง / ชั้นข้อมูล"
  },
  "ChartSetting": {
    "sectionTitle": "ชื่อเซสชั่น",
    "sectionTitleHintText": "คำแนะนำ : แสดงผลในส่วนของชื่อ",
    "chartTitle": "ชื่อแผนภูมิ",
    "chartTitleHintText": "คำแนะนำ: แสดงไว้ตรงกลาง ด้านบนของแผนภูมิ",
    "chartDescription": "คำอธิบาย",
    "chartDescriptionHintText": "คำแนะนำ: แสดงด้านล่างของแผนภูมิ",
    "chartType": "ประเภทแผนภูมิ",
    "barChart": "แผนภูมิแท่ง",
    "pieChart": "แผนภูมิทรงกลม",
    "polarChart": "แผนภูมิโพล่าร์",
    "dataSeriesField": "ฟิลด์ชุดข้อมูล",
    "labelField": "ฟิลด์ป้ายชื่อ",
    "chartColor": "สีแผนภูมิ",
    "singleColor": "สีเดียว",
    "colorByTheme": "ธีมสี",
    "colorByFieldValue": "สีโดยค่าของฟิลด์",
    "xAxisTitle": "ชื่อแกน X",
    "xAxisHintText": "คำแนะนำ : ชื่อแกน X",
    "yAxisTitle": "ชื่อแกน Y",
    "yAxisHintText": "คำแนะนำ : ชื่อแกน Y",
    "fieldColorLabel": "ป้ายชื่อ",
    "fieldColorColor": "สี",
    "defaultFieldSelectLabel": "เลือก",
    "errMsgFieldValuesNotFound": "ไม่สามรถค้นหาเพื่อเลือกฟิลด์ได้",
    "errMsgSectionTitle": "กรุณากรอกชื่อส่วนย่อย",
    "errMsgFieldByValue": "กรุณาเลือกค่าในฟิลด์",
    "settingTabTitle": "การตั้งค่า",
    "layoutTabTitle": "หน้ากระดาษ",
    "polarChartSelectFieldsHintText": "คำแนะนำ: เลือกฟิลด์ที่ใช้ในการสร้างแผนภูมิโพล่าร์",
    "visibilityText": "มองเห็นได้",
    "fieldNameText": "ชื่อฟิลด์",
    "aliasNameText": "ชื่อย่อ",
    "errMsgPolarFieldsRequired": "กรุณาเลือฟิลด์อย่างน้อยกสามฟิลด์ เพื่อสร้างแผนภูมิโพล่าร์",
    "polarChartPolygonFillLabel": "แสดงสีบนพื้นที่โพล่าร์",
    "polarChartPolygonFillHintText": "คำแนะนำ: เลือกช่องทำเครื่องหมาย เพื่อแสดงสีของพื้นที่ในแผนภูมิโพล่าร์",
    "viewLayoutLabel": "หน้ากระดาษ",
    "ThemeSelector": {
      "themeAdobebricks": "สีอิฐ",
      "themeAlgae": "ตะไคร่น้ำ",
      "themeBahamation": "บาฮาเมนชั่น",
      "themeBlueDusk": "ฟ้าเข้ม",
      "themeCubanShirts": "เสื้อคิวบา",
      "themeDesert": "ทะเลทราย",
      "themeDistinctive": "เด่น",
      "themeDollar": "ดอลล่าร์",
      "themeGrasshopper": "ตั๊กแตน",
      "themeGrasslands": "ทุ่งหญ้า",
      "themeGreySkies": "สีเทาฟ้า",
      "themeHarmony": "ฮาโมนี",
      "themeIndigoNation": "สีคราม",
      "themeIreland": "ไอร์แลนด์",
      "themeMiamiNice": "ไมอามี่นีซ",
      "themeMinty": "มิ้นต์",
      "themePurpleRain": "ฝนสีม่วง",
      "themeRoyalPurples": "รอยัลม่วง",
      "themeSageToLime": "สะระแหน่ถึงมะนาว",
      "themeTufte": "จานสี",
      "themeWatersEdge": "ริมน้ำ",
      "themeWetlandText": "พื้นที่ชื้นแฉะ",
      "themePlotKitblue": "พล็อตคิต สีน้ำเงิน",
      "themePlotKitcyan": "พล็อตคิต สีฟ้า",
      "themePlotKitgreen": "พล็อตคิต สีเขียว",
      "themePlotKitorange": "พล็อตคิต สีส้ม",
      "themePlotKitpurple": "พล็อตคิต สีม่วย",
      "themePlotKitred": "พล็อตคิต สีแดง"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "ตั้งค่าทั่วไป",
    "locationSymbolLabel": "สัญลักษณ์ตำแหน่งกราฟิก",
    "locationSymbolHintText": "คำแนะนำ : ใช้เพื่อแสดงผลสัญลักษณ์สำหรับที่อยู่และการคลิกตำแหน่ง",
    "refreshIntervalLabel": "รีเฟรชอันตรภาคชั้น",
    "refreshIntervalHintText": "คำแนะนำ : ใช้เพื่อรีเฟรชแผนภูมิที่ช่วงห่างเท่ากัน ระบุค่าระหว่าง 1 – 1440 นาที",
    "errMsgRefreshInterval": "กรุณาระบุค่าเพื่อรีเฟรชช่วงห่าง ระหว่าง 0 – 1440 นาที",
    "symbolPickerPreviewText": "ดูตัวอย่าง:",
    "showToolToSelectLabel": "ตั้งค่าปุ่มกำหนดตำแหน่ง",
    "showToolToSelectHintText": "คำแนะนำ: ให้ปุ่มกำหนดตำแหน่งบนแผนที่ แทนการกำหนดตำแหน่งโดยการกดที่แผนที่ เพื่อตั้งค่าทุกครั้ง"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "ตั้งค่าการค้นหาแหล่งที่มา",
    "searchSourceSettingTitle": "ตั้งค่าการค้นหาแหล่งที่มา",
    "searchSourceSettingTitleHintText": "เพิ่ม และกำหนดค่าบริการค้นหาตำแหน่งจีโอโค้ดเซอร์วิส หรือชั้นข้อมูลเป็นข้อมูลในการค้นหา ข้อมูลที่ระบุนี้จะใช้ในการค้นหาภายในช่องค้นหา",
    "addSearchSourceLabel": "เพิ่มช่องค้นหาแหล่งที่มา",
    "featureLayerLabel": "ชั้นข้อมูลฟีเจอร์",
    "geocoderLabel": "Geocoder",
    "nameTitle": "ชื่อ",
    "generalSettingLabel": "การตั้งค่าทั่วไป",
    "allPlaceholderLabel": "ใส่ข้อความสำหรับการค้นหาทั้งหมด",
    "allPlaceholderHintText": "คำแนะนำ: ป้อนข้อความที่จะแสดงคำเริ่มต้น ในขณะที่ทำการค้นหาชั้นข้อมูลทั้งหมด และจีโอโค้ด",
    "generalSettingCheckboxLabel": "แสดงป๊อปอัพสำหรับคุณลักษณะ หรือสถานที่",
    "countryCode": "ประเทศหรือรหัสภูมิภาค(s)",
    "countryCodeEg": "ตัวอย่าง ",
    "countryCodeHint": "ปล่อยให้เป็นค่าว่างจะค้นหาทุกประเทศและภูมิภาค",
    "questionMark": "?",
    "searchInCurrentMapExtent": "ค้นหาเฉพาะในขอบเขตแผนที่ปัจจุบัน",
    "zoomScale": "ขยายมาตราส่วน",
    "locatorUrl": "URL เครื่องระบุตำแหน่ง",
    "locatorName": "ชื่อเครื่องมือระบุตำแหน่ง",
    "locatorExample": "ตัวอย่าง",
    "locatorWarning": "รุ่นของบริการรหัสเชิงพื้นที่นี้ไม่ได้รับการสนับสนุน เครื่องมือสนับสนุนบริการรหัสเชิงพื้นที่ 10.0 และสูงกว่า",
    "locatorTips": "ข้อเสนอแนะจะไม่สามารถใช้ได้เนื่องจากบริการเชิงพื้นที่ ไม่สนับสนุนความสามารถในการแนะนำ",
    "layerSource": "ชั้นข้อมูลแหล่งที่มา",
    "setLayerSource": "ตั้งชั้นข้อมูลแหล่งที่มา",
    "setGeocoderURL": "ตั้งรหัสเชิงพื้นที่ URL",
    "searchLayerTips": "ข้อเสนอแนะจะไม่สามารถใช้ได้เนื่องจากบริการคุณลักษณะไม่สนับสนุนความสามารถในการแบ่งหน้า",
    "placeholder": "ตัวอักษรที่จองที่ไว้สำหรับคำที่ใช้งานจริง",
    "searchFields": "ค้นหาฟิลด์",
    "displayField": "ฟิลด์ที่แสดง",
    "exactMatch": "สอดคล้องอย่างยิ่ง",
    "maxSuggestions": "คำแนะนำมากสุด",
    "maxResults": "ผลลัพธ์สูงสุด",
    "enableLocalSearch": "เปิดใช้งานการค้นหาในโปรแกรม",
    "minScale": "มาตราส่วน",
    "minScaleHint": "เมื่อมาตราส่วนของแผนที่มากกว่ามาตราส่วนนี้ จะสามารถใช้งานการค้นหาในโปรแกรมได้",
    "radius": "รัศมี",
    "radiusHint": "ระบุรัศมีของบริเวณโดยรอบศูนย์กลางของแผนที่ปัจจุบัน เพื่อใช้ในการเพิ่มอันดับของผลลัพธ์จากตัวเลือกในการระบุพิกัดทางภูมิศาสตร์ โดยตัวเลือกที่อยู่ใกล้ที่สุดจะถูกส่งกลับมาก่อน",
    "meters": "เมตร",
    "setSearchFields": "ตั้งการค้นหาฟิลด์",
    "set": "ตั้ง",
    "fieldName": "ชื่อ",
    "invalidUrlTip": "URL ${URL} ไม่ถูกต้อง หรือไม่สามารถเข้าถึงได้"
  }
});