define({
  "defaultAreaUnit": "Privzeta enota površine",
  "defaultLengthUnit": "Privzeta enota dolžine",
  "acres": "Akri",
  "sqMiles": "Kvadratne milje",
  "sqKilometers": "Kvadratni kilometri",
  "hectares": "Hektarji",
  "sqYards": "Kvadratni jardi",
  "sqFeet": "Kvadratni čevlji",
  "sqFeetUS": "Kvadratni čevlji (ZDA)",
  "sqMeters": "Kvadratni metri",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "feetUS": "Čevlji (ZDA)",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "showArea": "Površina",
  "showDistance": "Razdalja",
  "showLocation": "Lokacija",
  "showtools": "Pokaži orodja za merjenje:",
  "allHidedTips": "Izbrano mora biti vsaj eno orodje."
});