define({
  "add": "לחץ להוספת פריט חדש",
  "title": "כותרת",
  "placeholderBookmarkName": "שם סימניה",
  "ok": "אישור",
  "cancel": "ביטול",
  "warning": "סיים בקשה את העריכה!",
  "edit": "ערוך סימניה",
  "errorNameExist": "סימניה קיימת!",
  "errorNameNull": "שם סימניה לא חוקי!",
  "addBookmark": "צור חדש",
  "thumbnail": "תמונה ממוזערת",
  "thumbnailHint": "לחץ על התמונה לעדכון",
  "displayBookmarksAs": "הצג סימנייה בתור",
  "cards": "כרטיסים",
  "list": "רשימה",
  "cardsTips": "תצוגת כרטיס",
  "listTips": "תצוגת רשימה",
  "makeAsDefault": "הגדר כברירת מחדל",
  "default": "ברירת מחדל",
  "editable": "אפשר להוסיף סימנייה לווידג'ט.",
  "alwaysSync": "הצג סימניות מ-Web Map",
  "configCustom": "הצג סימניות מותאמות אישית",
  "import": "ייבא",
  "create": "צור",
  "importTitle": "ייבא סימניות",
  "importFromWeb": "ייבא סימניות מה-Web Map הנוכחית",
  "selectAll": "בחר הכל",
  "noBookmarkInConfig": "לחץ על â€œייבאtâ€ או על â€צור חדשהâ€ כדי להוסיף סימניות.",
  "noBookmarkInWebMap": "לא הוגדרה אף סימנייה במפה.",
  "extent": "תיחום",
  "saveExtent": "שמור את תיחום המפה בסימניה זו",
  "savelayers": "שמור את נראות השכבות",
  "withVisibility": "עם נראות שכבות",
  "bookmark": "סימנייה",
  "addBtn": "הוספה",
  "deleteBtn": "מחיקה",
  "editBtn": "ערוך",
  "dragReorderTip": "החזק וגרור כדי לשנות סדר",
  "deleteBtnTip": "מחק את הסימנייה",
  "editBtnTip": "ערוך את הסימנייה"
});