define({
  "_widgetLabel": "스마트 편집기",
  "_featureAction_SmartEditor": "스마트 편집기",
  "noEditPrivileges": "내 계정에 데이터를 만들거나 수정할 권한이 없습니다.",
  "widgetActive": "활성",
  "widgetNotActive": "비활성",
  "pressStr": "Ctrl을 ",
  "ctrlStr": " 눌러 ",
  "snapStr": " 스내핑 활성화",
  "noAvailableTempaltes": "사용 가능한 템플릿이 없음",
  "editorCache": " - 편집기 캐시",
  "presetFieldAlias": "필드",
  "presetValue": "프리셋 값",
  "usePresetValues": " 프리셋 값 사용(새 피처만)",
  "editGeometry": " 지오메트리 편집",
  "savePromptTitle": "피처 저장",
  "savePrompt": "현재 피처를 저장하시겠습니까?",
  "deletePromptTitle": "피처 삭제",
  "deletePrompt": "선택한 피처를 삭제하시겠습니까?",
  "attachmentLoadingError": "첨부 파일 업로드 오류",
  "attachmentSaveDeleteWarning": "경고: 첨부 파일 변경이 자동으로 저장됨",
  "autoSaveEdits": "편집 내용은 자동으로 저장됨",
  "addNewFeature": "새 피처 생성",
  "featureCreationFailedMsg": "새 레코드/피처를 생성할 수 없음",
  "noRelatedFeatureFoundMsg": "릴레이트 레코드/피처를 찾을 수 없음",
  "relatedItemTitle": "릴레이트 테이블/레이어",
  "invalidRelationShipMsg": "기본 키 필드 '${parentKeyField}'의 값이 올바른지 확인하세요.",
  "pendingFeatureSaveMsg": "릴레이트 피처를 생성하기 전에 피처 편집 사항을 저장하세요.",
  "attachmentsRequiredMsg": "(*) 첨부 파일이 필요합니다(필수).",
  "filterEditor": {
    "all": "모두",
    "noAvailableTempaltes": "사용 가능한 템플릿이 없음",
    "searchTemplates": "템플릿 검색"
  },
  "invalidConfiguration": "위젯이 구성되지 않았거나 구성의 레이어가 더 이상 맵에 없습니다. 빌더 모드에서 앱을 열고 위젯을 다시 구성하세요.",
  "geometryServiceURLNotFoundMSG": "지오메트리 서비스 URL을 가져올 수 없음"
});