define({
  "_widgetLabel": "距离和方向",
  "tabLineTitle": "线",
  "tabCircleTitle": "圆形",
  "tabEllipseTitle": "椭圆",
  "tabRingsTitle": "环",
  "multipleNotationsMessage": " 发现与您的输入匹配的注记。请确认您想使用的注记：",
  "invalidCoordinateMessage": "坐标无效",
  "confirmInputNotationMessage": "确认输入注记",
  "prefixSuffixMessage": "检测到输入坐标同时拥有经度或纬度值的前缀和后缀，返回的坐标以前缀为基础。",
  "rememberDecisionMessage": "记住我的决定，不再询问。<br/>",
  "majorAxisTooltipMessage": "单击长轴的长度",
  "minorAxisTooltipMessage": "将鼠标移回开始位置以设置短轴并完成椭圆的绘制",
  "clickToFinishLineMessage": "单击完成线的绘制",
  "doubleClickEllipseMesage": "双击完成距离环的绘图",
  "invalidCoordinateTypeMessage": "无法确定输入坐标类型。请检查您的输入",
  "noCenterPointSetMessage": "没有中心点设置。请检查您的输入",
  "ellipseMajorAxis": "长轴",
  "ellipseMinorAxis": "短轴",
  "degreesRangeMessage": "值必须位于 0 和 360 之间",
  "millsRangeMessage": "值必须位于 0 和 6400 之间",
  "lengthLabel": "长度",
  "angleLabel": "角度",
  "startPointLabel": "起点",
  "endPointLabel": "终点",
  "centerPointLabel": "中心点",
  "distanceTableErrorMessage": "距离表为空。请确保输入一些距离。",
  "setCoordFormatStringMessage": "设置坐标格式字符串",
  "prefixMessage": "向正数和负数添加“+/-”前缀",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "十进制度 - 纬度/经度",
  "DDLongLatNotation": "十进制度 - 经度/纬度",
  "DDMLatLongNotation": "度十进制分 - 纬度/经度",
  "DDMLongLatNotation": "度十进制分 - 经度/纬度",
  "DMSLatLongNotation": "度分秒 - 纬度/经度",
  "DMSLongLatNotation": "度分秒 - 经度/纬度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 带字母",
  "UTMHemNotation": "UTM - 半球(N/S)",
  "circleTitle": "创建圆",
  "radiusLabel": "半径",
  "diameterLabel": "直径",
  "startPointPlaceHolderLabel": "输入坐标",
  "formatInputLabel": "格式输入",
  "drawCircleLabel": "绘制圆",
  "drawLineLabel": "绘制线",
  "createCircleInteractivelyLabel": "以交互方式创建圆",
  "rangeErrorMessage": "半径或直径无效",
  "numericInvalidMessage": "请输入一个数值",
  "timeLabel": "时间",
  "invalidTimeMessage": "时间值无效",
  "hoursLabel": "小时",
  "minutesLabel": "分",
  "secondsLabel": "秒",
  "rateLabel": "速率",
  "invalidDistanceMessage": "距离值无效",
  "feetSecondsLabel": "英尺/秒",
  "feetHourLabel": "英尺/小时",
  "kmSecondLabel": "千米/秒",
  "kmHourLabel": "千米/小时",
  "metersSecondLabel": "米/秒",
  "metersHourLabel": "米/小时",
  "milesSecondLabel": "英里/秒",
  "milesHourLabel": "英里/小时",
  "nauticalMilesSecondLabel": "海里/秒",
  "nauticalMilesHourLabel": "海里/小时",
  "clearGraphicsLabel": "清除图形",
  "ellipseTypeLabel": "椭圆类型",
  "ellipseSemiLabel": "半",
  "ellipseFullLabel": "完整",
  "drawEllipseLabel": "绘制椭圆",
  "createEllipseInteractively": "以交互方式创建椭圆",
  "axisLabel": "轴",
  "majorRadiusLabel": "长半径",
  "axisErrorMessage": "值必须大于 0。",
  "minorRadiusLabel": "短半径",
  "orientationLabel": "方向",
  "orientationErrorMessage": "值必须位于 0 和 360 之间",
  "warningMessage": "警告：使用椭圆工具生成的图形不是大地测量图形",
  "fromLabel": "自",
  "distanceBearingLabel": "距离和方位角",
  "pointsLabel": "点",
  "createLineInteractively": "以交互方式创建线",
  "lineLengthErrorMessage": "线长度无效",
  "degreesLabel": "度",
  "milsLabel": "密耳",
  "lineTypeLabel": "类型",
  "interactiveLabel": "交互式",
  "fixedLabel": "固定",
  "originLabel": "原点",
  "cumulativeLabel": "累积",
  "numberOfRingsLabel": "圆环数目",
  "ringsErrorMessage": "圆环数无效",
  "distanceBetweenRingsLabel": "圆环之间的距离",
  "ringsDecimalErrorMessage": "输入一个 2 位小数的数值",
  "distanceUnitsLabel": "距离单位",
  "distancesLabel": "距离",
  "numberOfRadialsLabel": "射线数目",
  "upLabel": "向上",
  "downLabel": "向下",
  "deleteLabel": "删除",
  "radialsErrorMessage": "射线数目无效。允许的最大值为 360",
  "addPointLabel": "添加点",
  "valueLabel": "值",
  "valueText": "输入值",
  "actionLabel": "操作"
});