define({
  "add": "Noklikšķiniet, lai pievienotu jaunu",
  "title": "Nosaukums",
  "placeholderBookmarkName": "Grāmatzīmes nosaukums",
  "ok": "Labi",
  "cancel": "Atcelt",
  "warning": "Pabeidziet rediģēšanu!",
  "edit": "Rediģēt grāmatzīmi",
  "errorNameExist": "Grāmatzīme pastāv!",
  "errorNameNull": "Nederīgs grāmatzīmes nosaukums.",
  "addBookmark": "Izveidot jaunu",
  "thumbnail": "Sīktēls",
  "thumbnailHint": "Noklikšķiniet uz attēla, lai atjauninātu",
  "displayBookmarksAs": "Parādīt grāmatzīmes kā",
  "cards": "Kartītes",
  "list": "Saraksts",
  "cardsTips": "Kartītes skats",
  "listTips": "Saraksta skats",
  "makeAsDefault": "Padarīt par noklusējumu",
  "default": "Noklusējums",
  "editable": "Atļaut pievienot grāmatzīmes logrīkā.",
  "alwaysSync": "Parādīt grāmatzīmes no tīmekļa kartes",
  "configCustom": "Parādīt pielāgotas grāmatzīmes",
  "import": "Importēt",
  "create": "Izveidot",
  "importTitle": "Importēt grāmatzīmes",
  "importFromWeb": "Importēt grāmatzīmes no pašreizējās tīmekļa kartes",
  "selectAll": "Izvēlēties visas",
  "noBookmarkInConfig": "Lai pievienotu grāmatzīmi, noklikšķiniet uz Importēt vai Izveidot jaunu.",
  "noBookmarkInWebMap": "Kartē neviena grāmatzīme nav konfigurēta.",
  "extent": "Pārklājums",
  "saveExtent": "Saglabāt kartes pārklājumu šajā grāmatzīmē",
  "savelayers": "Saglabāt slāņu redzamību",
  "withVisibility": "Ar slāņu redzamību",
  "bookmark": "Grāmatzīme",
  "addBtn": "Pievienot",
  "deleteBtn": "Izdzēst",
  "editBtn": "Labot",
  "dragReorderTip": "Lai pārkārtotu, turiet un velciet",
  "deleteBtnTip": "Dzēst grāmatzīmi",
  "editBtnTip": "Labot grāmatzīmi"
});