define({
  "settings": "Asetukset",
  "titleSettings": "Tekstiasetukset",
  "imageSettings": "Kuvan asetukset",
  "backgroundColor": "Taustaväri",
  "alignment": "Kohdistus",
  "textSize": "Tekstin koko",
  "textColor": "Tekstin väri",
  "dataSource": "Aineistolähde",
  "chartSettings": "Kaavion asetukset",
  "data": "Aineisto",
  "dataLabels": "Aineiston tunnustekstit",
  "displayMode": "Näyttötila",
  "featureOption": "Näytä arvot kohteittain",
  "categoryOption": "Näytä arvot luokittain",
  "countOption": "Näytä kohdemäärät luokittain",
  "fieldOption": "Näytä ominaisuustietoarvot kaavioina",
  "categoryField": "Luokkakenttä",
  "labelField": "Tunnustekstikenttä",
  "valueFields": "Arvokentät",
  "operation": "Toiminto",
  "sumOption": "Summa",
  "averageOption": "Keskiarvo",
  "minOption": "Minimi",
  "maxOption": "Maksimi",
  "dataFormat": "Aineistomuoto",
  "decimalPlaces": "Desimaalit",
  "prefix": "Etuliite",
  "suffix": "Jälkiliite",
  "dataType": "Aineistotyyppi",
  "featureCount": "Kohteiden määrä",
  "fieldStatistics": "Kentän tilastotiedot",
  "display": "Näytä",
  "chartColor": "Kaavion väri",
  "horizontalAxis": "Vaaka-akseli",
  "verticalAxis": "Pystyakseli",
  "legend": "Selite",
  "position": "Sijainti",
  "top": "Yläosa",
  "bottom": "Alaosa",
  "useDataSourceSelection": "Käytä valintaa",
  "dataSourceFilterByExtent": "Suodata laajuuden mukaan",
  "changeTemplate": "Vaihda mallia",
  "numberSettings": "Numeroasetukset",
  "gaugeSettings": "Mittarin asetukset",
  "indicators": "Ilmaisimet",
  "ifValue": "Jos arvo",
  "and": "ja",
  "numberOperatorIsLessThan": "on vähemmän kuin",
  "numberOperatorIsGreaterThan": "on suurempi kuin",
  "numberOperatorIsBetween": "on välillä",
  "numberOperatorIsEqual": "yhtä suuri kuin",
  "numberOperatorIsNotEqual": "on erisuuri kuin",
  "then": "Sitten",
  "ratio": "Suhde",
  "trueValue": "Tosi-arvo",
  "changeValueColor": "muuta arvon väriksi",
  "changeGaugeColor": "muuta mittarin väriksi",
  "setIndicatorIcon": "määritä ilmaisinkuvakkeeksi",
  "icons": "Icons",
  "style": "Tyyli",
  "placement": "Sijoittaminen",
  "left": "Vasen",
  "replace": "Korvaa",
  "right": "Oikea",
  "color": "Väri",
  "categoryExists": "Luokka on olemassa.",
  "comboxHint": "Kirjoita tai valitse yksi",
  "comboxDisableInputHint": "Valitse yksi",
  "sortBy": "Lajitteluperuste",
  "labelAxis": "Tunnusteksti",
  "valueAxis": "Arvo",
  "minPeriod": "Vähimmäisaikaväli",
  "automatic": "Automaattinen",
  "periodsWithOutRecords": "Aikavälit ilman tietueita",
  "nullValue": "Nolla-arvo",
  "calculatedAsZero": "Lasketaan nollana",
  "ignored": "Ohitettu",
  "maxCategories": "Enimmäisluokat",
  "useLayerSymbology": "Käytä karttatason symboleja",
  "hollowsize": "Ontto koko",
  "splitField": "Jaa kenttä",
  "parsingperiodTip": "Laskenta ei onnistunut. Liian monta aikaväliä lyhyen jäsennysjakson takia.",
  "manyCategoryTip": "Kaavion näyttäminen ei onnistunut. Luokkia on liian monta.",
  "setColor": "Määritä väri",
  "setTheColorOf": "Määritä sen jälkeen väri kohteelle",
  "setTheColorAs": "Määritä sen jälkeen väriksi",
  "ifStr": "Jos",
  "as": "Muoto:",
  "is": "on",
  "isNot": "ei ole",
  "barCluster": "palkkiklusteri",
  "individualBar": "yksittäinen palkki",
  "allOthers": "Kaikki muut",
  "category": "Luokka",
  "indicatorSum": "SUMMA",
  "indicatorAve": "KA.",
  "indicatorMax": "MAX",
  "indicatorMin": "VÄHINT.",
  "setCorrectyIndicatorTip": "Määritä ilmaisimet oikein.",
  "dataRange": "Aineistoalue",
  "targetValue": "Kohdearvo",
  "currentValue": "Nykyinen arvo",
  "gaugeColor": "Mittarin arvo",
  "min": "Minimi",
  "max": "Maksimi",
  "displayValueIn": "Näytä arvo kohteessa",
  "noData": "Ei tietoja",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Varoitus",
  "noSettingWaring1": "Voit määrittää elementin ominaisuudet napsauttamalla sitä.",
  "noSettingWaring2": "Muuta elementin kokoa tai järjestä elementit uudelleen vetämällä.",
  "donNotShowAgain": "Älä näytä uudelleen",
  "changeTemplateWarning": "Tämä poistaa kaikki asetuksesi ja avaa uuden tyhjän mallin.",
  "requiredFieldWarning": "Arvo on pakollinen:",
  "dataSourceNotSet": "Määritä aineistolähde.",
  "addIndicatorTip": "Lisää ilmaisin",
  "chooseTemplatePopupTitle": "Valitse malli",
  "filterExtentTipWithaTag": "Voit poistaa suodattimen käytöstä valitsemalla Ominaisuustieto-välilehdestä <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Ylimääräinen aineistolähde</a> -vaihtoehdon.",
  "filterExtentTip": "Voit poistaa suodattimen käytöstä valitsemalla Ominaisuustieto-välilehdestä Ylimääräinen aineistolähde -vaihtoehdon.",
  "customColorByCategory": "Mukautettu väri luokan mukaan",
  "randomColor": "Satunnainen väri",
  "valueString": "Arvo",
  "fieldString": "Kenttä",
  "includeThresholdValue": "Sisällytä raja-arvo",
  "percentage": "Prosenttiosuus",
  "colorSchema": "Värimalli",
  "addCategory": "Lisää luokka",
  "clickToEdit": "Muokkaa napsauttamalla",
  "nullText": "Null",
  "others": "Muut",
  "stringsInTemplate": {
    "name_number": "Numero",
    "name_gauge": "Mittari",
    "name_vertical_gauge": "Pystysuuntainen mittari",
    "name_horizontal_gauge": "Vaakasuuntainen mittari",
    "name_pie": "Ympyrä",
    "name_donut": "Rengas",
    "name_bar": "Palkki",
    "name_stacked_bar": "Pinottu palkki",
    "name_percentage_stacked_bar": "Pinottu prosenttipalkki",
    "name_column": "Sarake",
    "name_stacked_column": "Pinottu pylväskaavio",
    "name_percentage_stacked_column": "Pinottu prosenttipylväs",
    "name_line": "Viiva",
    "name_area": "Alue",
    "name_stacked_area": "Pinottu alue",
    "name_percentage_stacked_area": "Pinottu prosenttialue",
    "titleOfTheInfographic": "INFOGRAFIIKAN OTSIKKO",
    "description": "Kuvaus: lisätietoja tästä infografiikasta."
  }
});