define({
  "_widgetLabel": "Piemērotības modelētājs",
  "general": {
    "clear": "Notīrīt",
    "cancel": "Atcelt",
    "save": "Palaist",
    "saveAs": "Eksportēt"
  },
  "saveModel": {
    "save": "Eksportēt",
    "title": "Virsraksts: ",
    "summary": "Kopsavilkums: ",
    "description": "Apraksts: ",
    "tags": "Atslēgas vārdi: ",
    "folder": "Mape: ",
    "homeFolderPattern": "{username} (sākums)",
    "failed": "Eksportēšana neizdevās."
  },
  "util": {
    "colorRamp": {
      "1": "Ārkārtīgi zems",
      "2": "Ļoti zems",
      "3": "Zems",
      "4": "Vidēji zems",
      "5": "Vidējs",
      "6": "Vidēji augsts",
      "7": "Augsts",
      "8": "Ļoti augsts",
      "9": "Ārkārtīgi augsts",
      "low": "Zems",
      "high": "Augsts",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Apmest"
    }
  },
  "wro": {
    "caption": "Piemērotības modelētājs",
    "browsePrompt": "Svērtā pārklājuma pakalpojums",
    "selectLayersCaption": "Atlasīt slāņus",
    "selectLayers": "Slāņi",
    "designModelCaption": "Noformējuma modelis",
    "designModel": "Noformējuma modelis",
    "transparency": "Caurspīdīgums",
    "visible": "Redzams",
    "total": "Kopā",
    "unableToLoad": "Nevarēja ielādēt modeli.",
    "projectNotOpen": "Projekts nav atvērts.",
    "readMore": "Lasīt vairāk",
    "validation": {
      "validating": "Notiek validācija",
      "invalidItemCaption": "Svērtā pārklājuma pakalpojuma brīdinājums",
      "notAnImageService": "Šī vienība nav Attēla serviss.",
      "notAWroService": "Šī vienība nav Svērtā pārklājuma pakalpojums.",
      "undefinedUrl": "Šīs vienības URL nav definēts.",
      "inaccessible": "Pakalpojums ir nepieejams.",
      "generalError": "Nevar atvērt vienību.",
      "missingFieldPattern": "{field} ir obligāts lauks.",
      "notAllowRasterFunction": "allowRasterFunction ir jābūt iestatītam kā patiesam",
      "notNearestResampling": "defaultResamplingMethod ir jābūt vistuvākajai",
      "notIsWeightedOverlayProp": "Atslēgas rekvizītam IsWeightedOverlay ir jābūt iestatītam uz patiesu",
      "invalidLink": "URL nav derīgs. Atlasītajam slānim vietni atrast neizdevās.",
      "unexpectedError": "Radies neparedzēts stāvoklis.",
      "rangeMessage": "Vērtībai jābūt no ${0} līdz ${1}",
      "rangeMessage100": "Vērtībai ir jābūt no 0 līdz 100",
      "maxLayers": "Pakalpojums atļauj maksimāli ${0} slāņus, pirms jauna slāņa pievienošanas ir jānoņem kāds slānis.",
      "notFound": "Slānis ${0} svērtā pārklājuma pakalpojumā nav atrasts",
      "wroServiceNotDefined": "Modelim nav definēts svērtā pārklājuma pakalpojums.",
      "overlayLayerOutputInvalid": "Pārklājuma slānis [${0}] pārkartē diapazonu [${1}], izvades vērtības nav vai tā ir nederīga",
      "overlayLayerInputInvalid": "Pārklājuma slānis [${0}] pārkartē diapazonu [${1}], ievades min./maks. nav  norādīts vai ir nederīgs",
      "overlayLayerRangesMissing": "Pārklājuma slānī [${0}] nav pārkartēšanas diapazona",
      "overlayLayerWeight": "Pārklājuma slāņa svariem ir jāpievieno vērtība līdz 100",
      "overlayLayerRequired": "Ir nepieciešams vismaz viens pārklājuma slānis",
      "overlayLayerNotDefined": "Pārklājuma slāņi nav definēti",
      "requiresColormap": "Šī rastra funkcijai ir nepieciešama krāsu karte, bet modelim nav derīgas krāsu kartes definīcijas",
      "createModelError": "Veidojot modeli, radās kļūda",
      "invalidModel": "Modelis nav derīgs",
      "imageServiceNotDefined": "Attēla pakalpojuma slānis nav definēts",
      "imageLayerNotDefined": "Attēla pakalpojuma slānis nav definēts",
      "histogramNotDefined": "Svērtā pārklājuma histogrammas funkcija nav definēta."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zaļš, dzeltens, sarkans",
      "Red Yellow Green": "Sarkans, dzeltens, zaļš",
      "Yellow to Dark Red": "No dzeltenas līdz tumši sarkanai",
      "Dark Red to Yellow": "No tumši sarkanas līdz dzeltenai",
      "Light Gray to Dark Gray": "No gaiši pelēkas līdz tumši pelēkai",
      "Dark Gray to Light Gray": "No tumši pelēkas līdz gaiši pelēkai",
      "Light Brown to Dark Brown": "No gaiši brūnas līdz tumši brūnai",
      "Dark Brown to Light Brown": "No tumši brūnas līdz gaiši brūnai",
      "Full Spectrum - Bright Red to Blue": "Pilns spektrs - no spilgti sarkana līdz zilai",
      "Full Spectrum - Bright Blue to Red": "Pilns spektrs - no spilgti zila līdz sarkanai",
      "Partial Spectrum - Yellow to Blue": "Daļējs spektrs - no dzeltenas līdz zilai",
      "Partial Spectrum - Blue to Yellow": "Daļējs spektrs - no zilas līdz dzeltenai",
      "Yellow-Green to Dark Blue": "No zaļgandzeltenas līdz tumši zilai",
      "Dark Blue to Yellow-Green": "No tumši zilas līdz zaļgandzeltenai",
      "Cold to Hot Diverging": "Plūstoša pāreja no aukstajiem līdz siltajiem toņiem",
      "Hot to Cold Diverging": "Plūstoša pāreja no siltajiem līdz aukstajiem toņiem",
      "Surface - Low to High": "Virsma - no zemas līdz augstai",
      "Surface - High to Low": "Virsma - no augstas līdz zemai"
    }
  },
  "tabs": {
    "layers": "Slāņi",
    "model": "Modelis",
    "chart": "Diagramma"
  },
  "chart": {
    "prompt": "Elementi",
    "working": "Notiek atjaunināšana...",
    "polygonTool": "Zīmēt laukumu",
    "freehandPolygonTool": "Zīmēt brīvroku laukumu",
    "selectTool": "Izvēlēties no slāņa",
    "panTool": "Pārbīdīt",
    "clearButton": "Notīrīt",
    "noModelLayer": "Nav modeļa.",
    "noSubjectLayers": "Jūsu kartei nav laukumu slāņu.",
    "tipPattern": "${Category} — ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${Category} — ${label}"
  }
});