define({
  "_widgetLabel": "Consulta",
  "executeQueryTip": "Clique em um dos seguintes itens da tarefa para executar a consulta.",
  "invalidConfig": "Configuração inválida. Utilize a página de configuração da Consulta para obter a configuração correta.",
  "queryParams": "Opções",
  "parameters": "OPÇÕES",
  "queries": "CONSULTAS",
  "apply": "Aplicar",
  "queryResults": "Resultados",
  "clear": "Limpar",
  "noResults": "Nenhuma feição encontrada.",
  "queryError": "Falha ao consultar !",
  "numberFound": "Número de feições encontradas",
  "mapExtentTip": "Limite os resultados na extensão de mapa atual.",
  "noValue": "Nenhum valor",
  "and": "e",
  "stringOperatorIs": "é",
  "stringOperatorIsNot": "não é",
  "stringOperatorStartsWith": "inicia com",
  "stringOperatorEndsWith": "finaliza com",
  "stringOperatorContains": "contém",
  "stringOperatorDoesNotContain": "não contém",
  "stringOperatorIsBlank": "está em branco",
  "stringOperatorIsNotBlank": "não está em branco",
  "dateOperatorIsOn": "está em",
  "dateOperatorIsNotOn": "não está em",
  "dateOperatorIsBefore": "está antes",
  "dateOperatorIsAfter": "está após",
  "dateOperatorDays": "dias",
  "dateOperatorWeeks": "semanas",
  "dateOperatorMonths": "meses",
  "dateOperatorInTheLast": "no último",
  "dateOperatorNotInTheLast": "não no último",
  "dateOperatorIsBetween": "está entre",
  "dateOperatorIsNotBetween": "não está entre",
  "dateOperatorIsBlank": "está em branco",
  "dateOperatorIsNotBlank": "não está em branco",
  "numberOperatorIs": "é",
  "numberOperatorIsNot": "não é",
  "numberOperatorIsAtLeast": "é pelo menos",
  "numberOperatorIsLessThan": "é menor que",
  "numberOperatorIsAtMost": "é na maioria",
  "numberOperatorIsGreaterThan": "é maior que",
  "numberOperatorIsBetween": "está entre",
  "numberOperatorIsNotBetween": "não está entre",
  "numberOperatorIsBlank": "está em branco",
  "numberOperatorIsNotBlank": "não está em branco",
  "operationalLayerTip": "Adicionar resultado como camada operacional",
  "queryResult": "Resultado da consulta",
  "specifyParamsTip": "Especificar parâmetros para esta tarefa",
  "useSpatialFilter": "Utilizar filtro espacial para limitar feições",
  "useCurrentMapExtent": "Somente as feições que interseccionam a área de mapa atual",
  "drawGraphicOnMap": "Somente as feições que interseccionam uma área definida pelo usuário",
  "specifySpatialFilterMsg": "Especifique o filtro espacial para esta tarefa.",
  "clearResults": "Limpar resultados",
  "operationalTip": "Com esta opção selecionada, os resultados serão mantidos no mapa até o botão \"${clearResults}\" ser clicado.",
  "noneQueryTip": "Nenhuma tarefa de consulta configurada para este widget.",
  "noPermissionsMsg": "Você não tem permissões para acessar este serviço.",
  "attributesFromRelationship": "Atributos da tabela relacionada",
  "tasks": "Tarefas",
  "applySpatialFilterToLimitResults": "Aplicar um filtro espacial para limitar resultados",
  "useCurrentExtentTip": "Retornar somente feições dentro da extensão de mapa atual",
  "useDrawGraphicTip": "Somente retorna feições que interseccionam com a forma desenhada no mapa",
  "useFeaturesTip": "Retornar somente feições que têm um relacionamento espacial com feições em outra camada",
  "noSpatialLimitTip": "Retornar feições dentro da extensão total do mapa",
  "applySearchDistance": "Aplicar uma distância de pesquisa",
  "spatialRelationship": "Relacionamento espacial",
  "relatedLayer": "Camada Relacionada",
  "bufferDistance": "Distância do Buffer",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "back": "Voltar",
  "execute": "Executar",
  "zoomTo": "Zoom para",
  "openAttributeTable": "Visualizar na Tabela de Atributos",
  "noResult": "Nenhum resultado.",
  "noTask": "Nenhuma tarefa.",
  "removeThisResult": "Remover este resultado",
  "attributeCriteira": "Critérios de atributos",
  "spatialFilter": "Filtro espacial",
  "value": "VALOR",
  "noAttributeSpatialFilterTip": "Nenhum filtro definido. Todas as feições serão retornadas.",
  "showAllRelatedRecords": "Mostrar todos os registros relacionados",
  "changeSymbol": "Alterar símbolo",
  "queryCriteira": "Critérios de consulta",
  "customQuery": "Consulta personalizada",
  "layer": "Camada",
  "createCustomQuery": "Cria consulta personalizada."
});