define({
  "chartTasks": "चार्ट कार्य",
  "addNew": "नया जोड़ें",
  "addNewTip": "एक नया चार्ट कार्य जोड़ें",
  "name": "नाम",
  "set": "सेट करें",
  "setDataSource": "डेटा स्रोत सेट करें",
  "generalSettingsTip": "चार्ट्स के लिए डेटा स्रोत, शीर्षक और विवरण सेट करें।",
  "chartModeSettingTip": "चार्ट्स के रूप में विश्लेषण करने और प्रदर्शित करने के लिए एक तरीके का चयन करें।",
  "detailsSettingTip": "चार्ट का प्रकार और रंग निर्दिष्ट कर इसकी उपस्थिति, और कौन से मान चार्ट किए जाने हैं, सेट करे:",
  "symbolSettingTip": "चार्ट किए गए डेटा के लिए मानचित्र प्रदर्शन सेट करें।",
  "addFilterTip": "इस डेटा के लिए फ़िल्टर जोड़ें",
  "dataSource": "डेटा स्रोत",
  "noResults": "कोई फीचर नहीं पाई गई है।",
  "chartTitle": "चार्ट शीर्षक",
  "description": "विवरण",
  "chartingMode": "चार्ट का डिस्प्ले",
  "featureOption": "फीचर दर फीचर मान प्रदर्शित करें",
  "categoryOption": "श्रेणी के अनुसार मान प्रदर्शित करें",
  "countOption": "श्रेणी के अनुसार फीचर्स की संख्या प्रदर्शित करें",
  "fieldOption": "विशेषता मानों को चार्ट के रूप में प्रदर्शित करें",
  "category": "वर्ग",
  "axisLabel": "श्रेणी का लेबल",
  "categoryField": "श्रेणी की फ़ील्ड",
  "operation": "परिचालन",
  "originalOption": "मूल मानों का प्रयोग करें",
  "sumOption": "योग",
  "averageOption": "औसत",
  "minOption": "न्यूनतम",
  "maxOption": "अधिकतम",
  "valueFields": "मान फ़ील्ड",
  "moveUp": "ऊपर जाएँ",
  "moveDown": "नीचे जाएँ",
  "sortOrder": "श्रेणी के लेबल के माध्यम से चार्ट के क्रम को क्रमबद्ध करें",
  "ascending": "आरोही",
  "descending": "अवरोही",
  "chartType": "चार्ट प्रकार",
  "column": "स्तंभ चार्ट",
  "bar": "बार चार्ट",
  "line": "रेखा चार्ट",
  "pie": "पाई चार्ट",
  "chartColor": "चार्ट रंग",
  "showDataLabels": "डेटा लेबल दिखाएँ",
  "setSymbol": "चयन प्रतीक",
  "setHighLightColor": "रंग हाइलाइट करें",
  "settings": "सेटिंग्स",
  "mapInterationOptions": "मैप इंटरेक्शन विकल्प",
  "preview": "पूर्वावलोकन करें",
  "ok": "ठीक है",
  "cancel": "रद्द करें",
  "close": "बंद करें",
  "setFilterTip": "कृपया फिल्टर को सही ढंग से निर्धारित करें। ",
  "setChartTitleTip": "चार्ट शीर्षक सेट करें।",
  "setChartTypeTip": "कृपया कम से कम एक चार्ट प्रकार का चयन करें।",
  "setDataFieldTip": "कृपया कम से कम एक मान फील्ड का चयन करें।",
  "setOutputFieldTip": "कृपया आउटपुट फील्ड सेट करें।",
  "count": "गणना",
  "label": "लेबल",
  "horizontalAxis": "क्षैतिज अक्ष",
  "verticalAxis": "ऊर्ध्वाधर अक्ष",
  "dataLabels": "डेटा लेबल",
  "color": "रंग",
  "colorful": "रंगीन",
  "monochromatic": "एकरंगा",
  "noTaskTip": "एक चार्ट कार्य जोड़ने के लिए नया जोड़ें पर क्लिक करें",
  "info": "जानकारी",
  "charts": "चार्ट",
  "options": "विकल्प",
  "taskName": "कार्य का नाम",
  "summary": "सार",
  "resultDescription": "परिणाम का विवरण",
  "spatialFilterTip": "परिणामो को सीमित करने के लिए विजेट में प्रयुक्त स्पेशियल फिल्टर का चयन करें।",
  "defaultOption": "डिफॉल्ट",
  "useCurrentExtentTip": "आंशिक रूप से या पूरी तरह से वर्तमान मानचित्र सीमा के भीतर",
  "useDrawGraphicTip": "मानचित्र पर आंशिक रूप से या पूरी तरह से बनाए गए आकार के भीतर",
  "useFeaturesTip": "अन्य लेयर में फीचर के सापेक्ष उनके स्थानों के आधार पर",
  "noSpatialLimitTip": "परिणामों को स्पेश्यिल रूप में सीमित न करें",
  "drawingTools": "ड्राइंग टूल्स",
  "bufferSettings": "बफर सेटिंग्स",
  "defaultDistance": "डिफ़ॉल्ट दूरी",
  "bufferDistance": "बफर दूरी",
  "defaultUnit": "डिफ़ॉल्ट इकाई",
  "miles": "मील",
  "kilometers": "किलोमीटर",
  "feet": "फ़ीट",
  "meters": "मीटर",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "availableSpatialRelationships": "उपलब्ध स्पेशियल संबंध",
  "setSpatialRelationships": "स्पेशियल संबंध सेट करें",
  "availability": "उपलब्धता",
  "relationship": "संबंध",
  "actions": "कार्रवाइयाँ",
  "intersect": "इंटरसेक्ट",
  "contain": "शामिल",
  "areContainedIn": "इसमें शामिल हैं",
  "cross": "क्रॉस",
  "envelopeIntersect": "एनवलप इंटरसेक्ट",
  "overlap": "ओवरलैप",
  "areOverlapped": "ओवरलैप हैं",
  "touche": "ट्च",
  "within": "भीतर",
  "areWithin": "भीतर हैं",
  "indexIntersect": "इंडेक्स इंटरसेक्ट"
});