define({
  "_widgetLabel": "适宜性建模器",
  "general": {
    "clear": "清除",
    "cancel": "取消",
    "save": "运行",
    "saveAs": "导出"
  },
  "saveModel": {
    "save": "导出",
    "title": "标题： ",
    "summary": "摘要： ",
    "description": "描述： ",
    "tags": "标签： ",
    "folder": "文件夹： ",
    "homeFolderPattern": "{username} (主页)",
    "failed": "导出失败。"
  },
  "util": {
    "colorRamp": {
      "1": "超低",
      "2": "极低",
      "3": "低",
      "4": "中低",
      "5": "中等",
      "6": "中高",
      "7": "高",
      "8": "极高",
      "9": "超高",
      "low": "低",
      "high": "高",
      "tipPattern": "{label} ({value})",
      "flipCaption": "翻转"
    }
  },
  "wro": {
    "caption": "适宜性建模器",
    "browsePrompt": "加权叠加服务",
    "selectLayersCaption": "选择图层",
    "selectLayers": "图层",
    "designModelCaption": "设计模型",
    "designModel": "设计模型",
    "transparency": "透明度",
    "visible": "可见",
    "total": "总计",
    "unableToLoad": "无法加载模型。",
    "projectNotOpen": "工程未打开。",
    "readMore": "了解更多",
    "validation": {
      "validating": "正在验证 ...",
      "invalidItemCaption": "加权叠加服务警告",
      "notAnImageService": "此项目不是影像服务。",
      "notAWroService": "此项目不是加权叠加服务。",
      "undefinedUrl": "此项目的 URL 未定义。",
      "inaccessible": "服务无法访问。",
      "generalError": "无法打开项目。",
      "missingFieldPattern": "{field} 是必填字段",
      "notAllowRasterFunction": "allowRasterFunction 必须设置为 true",
      "notNearestResampling": "defaultResamplingMethod 必须为 Nearest",
      "notIsWeightedOverlayProp": "关键属性 IsWeightedOverlay 必须设置为 true",
      "invalidLink": "URL 无效。打开所选图层的站点失败。",
      "unexpectedError": "发生意外状态。",
      "rangeMessage": "值必须位于 ${0} 和 ${1} 之间",
      "rangeMessage100": "值必须位于 0 和 100 之间",
      "maxLayers": "服务最多允许 ${0} 个图层，添加新图层前必须移除某一图层。",
      "notFound": "加权叠加服务中未找到图层 ${0}",
      "wroServiceNotDefined": "未针对模型定义加权叠加服务。",
      "overlayLayerOutputInvalid": "叠加图层 [${0}] 重映射范围 [${1}] 输出值缺失或无效",
      "overlayLayerInputInvalid": "叠加图层 [${0}] 重映射范围 [${1}] 输入最小值/最大值缺失或无效",
      "overlayLayerRangesMissing": "叠加图层 [${0}] 缺失重映射范围",
      "overlayLayerWeight": "叠加图层权重的总和必须为 100",
      "overlayLayerRequired": "至少需要一个叠加图层",
      "overlayLayerNotDefined": "叠加图层未定义",
      "requiresColormap": "栅格函数需要色彩映射表，但模型未定义有效的色彩映射表",
      "createModelError": "创建模型时出错",
      "invalidModel": "模型无效",
      "imageServiceNotDefined": "影像服务图层未定义",
      "imageLayerNotDefined": "影像服务图层未定义",
      "histogramNotDefined": "未定义加权叠加直方图函数。"
    },
    "colorRampLabel": {
      "Green Yellow Red": "绿色黄色红色",
      "Red Yellow Green": "红色黄色绿色",
      "Yellow to Dark Red": "黄色到深红色",
      "Dark Red to Yellow": "深红色到黄色",
      "Light Gray to Dark Gray": "浅灰色到深灰色",
      "Dark Gray to Light Gray": "深灰色到浅灰色",
      "Light Brown to Dark Brown": "浅棕色到深棕色",
      "Dark Brown to Light Brown": "深棕色到浅棕色",
      "Full Spectrum - Bright Red to Blue": "全光谱 - 亮红色到蓝色",
      "Full Spectrum - Bright Blue to Red": "全光谱 - 亮蓝色到红色",
      "Partial Spectrum - Yellow to Blue": "部分光谱 - 黄色到蓝色",
      "Partial Spectrum - Blue to Yellow": "部分光谱 - 蓝色到黄色",
      "Yellow-Green to Dark Blue": "黄绿色到深蓝色",
      "Dark Blue to Yellow-Green": "深蓝色到黄绿色",
      "Cold to Hot Diverging": "冷色至暖色扩散",
      "Hot to Cold Diverging": "暖色到冷色扩散",
      "Surface - Low to High": "表面 - 低到高",
      "Surface - High to Low": "表面 - 高到低"
    }
  },
  "tabs": {
    "layers": "图层",
    "model": "模型",
    "chart": "图表"
  },
  "chart": {
    "prompt": "要素",
    "working": "正在更新...",
    "polygonTool": "绘制面",
    "freehandPolygonTool": "绘制手绘面",
    "selectTool": "从图层选择",
    "panTool": "平移",
    "clearButton": "清除",
    "noModelLayer": "没有模型。",
    "noSubjectLayers": "您的地图不包含面图层。",
    "tipPattern": "${category} - ${label}：${percent}%",
    "tipPattern2": "${category}：${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});