define({
  "gridTabLabel": "Mreža",
  "labelTabLabel": "Oznake",
  "referenceSystemTabLabel": "Referentni sistem",
  "gridTabDescription": "Podesite izgled i ponašanje ćelija mreže.",
  "cellOutlineColor": "Boja kontura ćelije",
  "cellFillColor": "Boja popune ćelije",
  "transparency": "Prozirnost",
  "cellShapeDropDown": "Oblik ćelije",
  "default": "Pravougaonik",
  "hexagon": "Šestougaonik",
  "cellUnitsDropDown": "Jedinice ćelije",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nautical-miles": "Nautičke milje",
  "gridOriginDropDown": "Koordinatni početak mreže",
  "lowerLeft": "Dole levo",
  "lowerRight": "Dole desno",
  "upperLeft": "Gore levo",
  "upperRight": "Gore desno",
  "center": "Centar",
  "labelTabDescription": "Podesite izgled i ponašanje oznaka mreže.",
  "labelSettings": "Stil oznake",
  "font": "Font",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "halo": "Efekat oreola",
  "show": "Prikaži",
  "labelTypeDropDown": "Vrsta oznake",
  "alphaNumeric": "Alfanumerički",
  "alphaAlpha": "Abecedno-abecedni",
  "numeric": "Brojčano",
  "labelDirectionDropDown": "Smer oznake",
  "horizontal": "Horizontalno",
  "vertical": "Vertikalno",
  "labelOriginDropDown": "Početak oznake",
  "referenceSystemlTabDescription": "Podesite podrazumevani referentni sistem.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Zaključaj postavke – Ovo će sprečiti mogućnost promene bilo koje od konfigurisanih postavki u okviru vidžeta od strane korisnika"
});