define({
  "_widgetLabel": "Desenhar",
  "selectDrawMode": "Selecionar modo de desenho",
  "clear": "Limpar",
  "point": "Ponto",
  "line": "Linha",
  "polyline": "Polilinha",
  "freehandPolyline": "Polilinha à mão livre",
  "triangle": "Triângulo",
  "extent": "Envelope",
  "circle": "Círculo",
  "ellipse": "Elipse",
  "polygon": "Polígono",
  "freehandPolygon": "Polígono à mão livre",
  "text": "Texto",
  "style": "Estilo",
  "alpha": "Transparência",
  "width": "Largura",
  "size": "Tamanho",
  "color": "Cor",
  "markerColor": "Cor de marcador",
  "outlineColor": "Cor de contorno",
  "lineColor": "Cor da linha",
  "fillColor": "Cor de preenchimento",
  "showMeasurements": "Mostrar medições",
  "showAreaMeasurement": "Mostrar medida de área",
  "showDistanceMeasurement": "Mostrar medida de distância",
  "areaUnits": "Unidades de área",
  "distanceUnits": "Unidades de distância",
  "kilometers": "Quilômetros",
  "miles": "Milhas",
  "meters": "Metros",
  "feet": "Pés",
  "yards": "Jardas",
  "nauticalmiles": "Milhas náuticas",
  "squareKilometers": "Quilômetros quadrados",
  "squareMiles": "Milhas quadradas",
  "acres": "Acres",
  "hectares": "Hectares",
  "squareMeters": "Metros quadrados",
  "squareFeet": "Pés quadrados",
  "squareYards": "Jardas quadradas",
  "undo": "Desfazer",
  "redo": "Refazer",
  "results": "Resultados",
  "points": "Pontos",
  "lines": "Linhas",
  "areas": "Áreas",
  "areaLabel": "Área: ${value} ${unit}",
  "distanceLabel": "Distância: ${value} ${unit}"
});