define({
  "_widgetLabel": "Odległość i kierunek",
  "tabLineTitle": "Linia",
  "tabCircleTitle": "Okrąg",
  "tabEllipseTitle": "Elipsa",
  "tabRingsTitle": "Pierścienie",
  "multipleNotationsMessage": " liczba znalezionych notacji zgodnych z danymi wejściowymi. Wybierz, której notacji chcesz użyć:",
  "invalidCoordinateMessage": "Nieprawidłowa współrzędna",
  "confirmInputNotationMessage": "Potwierdź notację danych wejściowych",
  "prefixSuffixMessage": "Wykryto, że współrzędna wejściowa zawiera prefiks i sufiks wartości szerokości lub długości geograficznej. Zwracana współrzędna jest oparta na prefiksie.",
  "rememberDecisionMessage": "Zapamiętaj moją decyzję i nie pytaj ponownie.<br/>",
  "majorAxisTooltipMessage": "Kliknij długość dużej osi",
  "minorAxisTooltipMessage": "Przesuń wskaźnik myszy z powrotem do pozycji początkowej, aby ustawić małą oś i zakończyć rysowanie elipsy",
  "clickToFinishLineMessage": "Kliknij, aby zakończyć rysowanie linii",
  "doubleClickEllipseMesage": "Kliknij dwukrotnie, by zakończyć rysowanie zakresu pierścieni",
  "invalidCoordinateTypeMessage": "Nie można określić typu współrzędnych wejściowych. Sprawdź dane wejściowe",
  "noCenterPointSetMessage": "Nie ustawiono punktu środkowego. Sprawdź dane wejściowe",
  "ellipseMajorAxis": "Duża oś",
  "ellipseMinorAxis": "Mała oś",
  "degreesRangeMessage": "Wartość musi zawierać się w przedziale od 0 do 360",
  "millsRangeMessage": "Wartość musi zawierać się w przedziale od 0 do 6400",
  "lengthLabel": "Długość",
  "angleLabel": "Kąt",
  "startPointLabel": "Punkt startowy",
  "endPointLabel": "Punkt końcowy",
  "centerPointLabel": "Punkt środkowy",
  "distanceTableErrorMessage": "Tabela odległości jest pusta. Należy wprowadzić wartości odległości.",
  "setCoordFormatStringMessage": "Skonfiguruj ciąg znakowy formatu współrzędnych",
  "prefixMessage": "Dodaj prefiks '+/-' do liczb dodatnich i ujemnych",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "Stopnie-Minuty-Sekundy (DMS)",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Stopnie dziesiętne — szerokość/długość geograficzna",
  "DDLongLatNotation": "Stopnie dziesiętne — długość/szerokość geograficzna",
  "DDMLatLongNotation": "Stopnie i minuty dziesiętne — szerokość/długość geograficzna",
  "DDMLongLatNotation": "Stopnie i minuty dziesiętne — długość/szerokość geograficzna",
  "DMSLatLongNotation": "Stopnie, minuty i sekundy — szerokość/długość geograficzna",
  "DMSLongLatNotation": "Stopnie, minuty i sekundy — długość/szerokość geograficzna",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — litera pasa",
  "UTMHemNotation": "UTM — półkula (N/S)",
  "circleTitle": "Utwórz okrąg z",
  "radiusLabel": "Promień",
  "diameterLabel": "Średnica",
  "startPointPlaceHolderLabel": "Wpisz współrzędne",
  "formatInputLabel": "Formatuj dane wejściowe",
  "drawCircleLabel": "Rysuj okrąg",
  "drawLineLabel": "Rysuj linię",
  "createCircleInteractivelyLabel": "Utwórz okrąg interaktywnie",
  "rangeErrorMessage": "Nieprawidłowy promień lub średnica",
  "numericInvalidMessage": "Wprowadź wartość numeryczną",
  "timeLabel": "Czas",
  "invalidTimeMessage": "Nieprawidłowa wartość czasu",
  "hoursLabel": "Godziny",
  "minutesLabel": "Minut(y)",
  "secondsLabel": "Sekundy",
  "rateLabel": "Proporcjonalnie",
  "invalidDistanceMessage": "Niepoprawna wartość odległości",
  "feetSecondsLabel": "Stopa / sekunda",
  "feetHourLabel": "Stopa / godzina",
  "kmSecondLabel": "Kilometry / sekunda",
  "kmHourLabel": "Kilometr / godzina",
  "metersSecondLabel": "Metry / sekunda",
  "metersHourLabel": "Metry / godzina",
  "milesSecondLabel": "Mile / sekunda",
  "milesHourLabel": "Mile / godzina",
  "nauticalMilesSecondLabel": "Mile morskie / sekunda",
  "nauticalMilesHourLabel": "Mile morskie / godzina",
  "clearGraphicsLabel": "Wyczyść grafikę",
  "ellipseTypeLabel": "Typ elipsy",
  "ellipseSemiLabel": "Częściowa",
  "ellipseFullLabel": "Pełna",
  "drawEllipseLabel": "Rysuj elipsę",
  "createEllipseInteractively": "Utwórz elipsę interaktywnie",
  "axisLabel": "Oś",
  "majorRadiusLabel": "Duża (promień)",
  "axisErrorMessage": "Wartość musi być większa od 0",
  "minorRadiusLabel": "Mała (promień)",
  "orientationLabel": "Orientacja",
  "orientationErrorMessage": "Wartość musi zawierać się w przedziale od 0 do 360",
  "warningMessage": "Ostrzeżenie: Grafiki utworzone przy użyciu narzędzia elipsa nie są geodezyjne",
  "fromLabel": "Od",
  "distanceBearingLabel": "Odległość i kierunek",
  "pointsLabel": "Punkty",
  "createLineInteractively": "Utwórz linię interaktywnie",
  "lineLengthErrorMessage": "Nieprawidłowa długość linii",
  "degreesLabel": "Stopnie",
  "milsLabel": "Milsy",
  "lineTypeLabel": "Folder nie zawiera prawidłowego projektu aplikacji",
  "interactiveLabel": "Interaktywnie",
  "fixedLabel": "Stałe",
  "originLabel": "Punkt zaczepienia",
  "cumulativeLabel": "Kumulowana",
  "numberOfRingsLabel": "Liczba pierścieni",
  "ringsErrorMessage": "Nieprawidłowa liczba pierścieni",
  "distanceBetweenRingsLabel": "Odległość między pierścieniami",
  "ringsDecimalErrorMessage": "Wprowadź wartość numeryczną z dokładnością do dwóch miejsc dziesiętnych",
  "distanceUnitsLabel": "Jednostki odległości",
  "distancesLabel": "Odległości",
  "numberOfRadialsLabel": "Liczba promieni",
  "upLabel": "W górę",
  "downLabel": "W dół",
  "deleteLabel": "Usuwanie",
  "radialsErrorMessage": "Nieprawidłowa liczba promieni. Maksymalna dopuszczalna wartość to 360",
  "addPointLabel": "Dodaj punkt",
  "valueLabel": "Wartość",
  "valueText": "Wprowadź wartość",
  "actionLabel": "Działanie"
});