define({
  "_widgetLabel": "Poizvedba",
  "executeQueryTip": "Kliknite enega od naslednjih elementov nalog za izvedbo poizvedbe.",
  "invalidConfig": "Neveljavna konfiguracija. Uporabite stran nastavitve poizvedb za pravilno konfiguracijo.",
  "queryParams": "Možnosti",
  "parameters": "MOŽNOSTI",
  "queries": "POIZVEDBE",
  "apply": "Uporabi",
  "queryResults": "Rezultati",
  "clear": "Počisti",
  "noResults": "Geoobjekta ni mogoče najti.",
  "queryError": "Poizvedba ni uspela!",
  "numberFound": "Število najdenih geoobjektov",
  "mapExtentTip": "Omeji rezultate na trenutno območje karte.",
  "noValue": "Ni vrednosti",
  "and": "in",
  "stringOperatorIs": "je",
  "stringOperatorIsNot": "ni",
  "stringOperatorStartsWith": "se začne z",
  "stringOperatorEndsWith": "se konča z",
  "stringOperatorContains": "vsebuje",
  "stringOperatorDoesNotContain": "ne vsebuje",
  "stringOperatorIsBlank": "je prazno",
  "stringOperatorIsNotBlank": "ni prazno",
  "dateOperatorIsOn": "je vklopljeno",
  "dateOperatorIsNotOn": "ni vklopljeno",
  "dateOperatorIsBefore": "je pred",
  "dateOperatorIsAfter": "je po",
  "dateOperatorDays": "dnevi",
  "dateOperatorWeeks": "tedni",
  "dateOperatorMonths": "meseci",
  "dateOperatorInTheLast": "v zadnjem",
  "dateOperatorNotInTheLast": "ni v zadnjem",
  "dateOperatorIsBetween": "je med",
  "dateOperatorIsNotBetween": "ni med",
  "dateOperatorIsBlank": "je prazno",
  "dateOperatorIsNotBlank": "ni prazno",
  "numberOperatorIs": "je",
  "numberOperatorIsNot": "ni",
  "numberOperatorIsAtLeast": "je vsaj",
  "numberOperatorIsLessThan": "je manj kot",
  "numberOperatorIsAtMost": "je največ",
  "numberOperatorIsGreaterThan": "je več kot",
  "numberOperatorIsBetween": "je med",
  "numberOperatorIsNotBetween": "ni med",
  "numberOperatorIsBlank": "je prazno",
  "numberOperatorIsNotBlank": "ni prazno",
  "operationalLayerTip": "Dodaj rezultat kot operativni sloj",
  "queryResult": "Rezultat poizvedb",
  "specifyParamsTip": "Določite parametre za to nalogo",
  "useSpatialFilter": "Uporabi prostorski filter za omejitev geoobjektov",
  "useCurrentMapExtent": "Samo geoobjekti, ki sekajo trenutno območje karte",
  "drawGraphicOnMap": "Samo geoobjekti, ki sekajo uporabniško določeno območje",
  "specifySpatialFilterMsg": "Določite prostorski filter za to nalogo.",
  "clearResults": "Počisti rezultate",
  "operationalTip": "Če označite to možnost, bodo rezultati ostali na karti, dokler ne kliknete gumba »${clearResults}«.",
  "noneQueryTip": "Za ta pripomoček ni bila konfigurirana nobena naloga poizvedbe.",
  "noPermissionsMsg": "Za dostop do te storitve nimate dovoljenj.",
  "attributesFromRelationship": "Atributi iz relacijske tabele",
  "tasks": "Naloge",
  "applySpatialFilterToLimitResults": "Za omejitev rezultatov uporabi prostorski filter",
  "useCurrentExtentTip": "Vrni samo geoobjekte s trenutnega obsega karte",
  "useDrawGraphicTip": "Vrni samo geoobjekte, ki sekajo obliko, narisano na karti",
  "useFeaturesTip": "Vrni samo geoobjekte, ki imajo prostorsko relacijo z geoobjekti na drugem sloju",
  "noSpatialLimitTip": "Vrni geoobjekte, ki so znotraj polnega obsega karte",
  "applySearchDistance": "Uporabite iskalno razdaljo.",
  "spatialRelationship": "Prostorska relacija",
  "relatedLayer": "Relacijski sloj",
  "bufferDistance": "Razdalja obrisa",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "back": "Nazaj",
  "execute": "Izvedi",
  "zoomTo": "Približaj na",
  "openAttributeTable": "Poglej v atributni tabeli",
  "noResult": "Ni rezultata.",
  "noTask": "Ni naloge.",
  "removeThisResult": "Odstrani ta rezultat",
  "attributeCriteira": "Kriterij atributa",
  "spatialFilter": "Prostorski filter",
  "value": "VREDNOST",
  "noAttributeSpatialFilterTip": "Filtri niso določeni. Prikazani bodo vsi geoobjekti",
  "showAllRelatedRecords": "Pokaži vse relacijske zapise",
  "changeSymbol": "Spremeni simbol",
  "queryCriteira": "Kriteriji poizvedbe",
  "customQuery": "Poizvedba po meri",
  "layer": "Sloj",
  "createCustomQuery": "Ustvari poizvedbo po meri."
});