define({
  "tabs_section_Label": "Onglets",
  "addTab": "Ajouter un onglet",
  "layerName": "Couche",
  "layerType": "Type d'analyse",
  "layerLabel": "Etiquette",
  "actions": "Actions",
  "closest": "Entité la plus proche",
  "proximity": "Proximité",
  "summary": "Résumé",
  "select_lbl": "-- Sélectionner --",
  "general_setting_Label": "Paramètres généraux",
  "units_text_lbl": "Unités de distance",
  "maximum_distance_lbl": "Distance maximale de l'entité la plus proche",
  "buffer_text_lbl": "Etiquette de la zone tampon",
  "buffer_lbl": "Distance de la zone tampon",
  "buffer_max_lbl": "Distance maximale de la zone tampon",
  "buffer_min_lbl": "Distance minimale de la zone tampon",
  "buffer_default_lbl": "Distance de la zone tampon par défaut",
  "not_less_than_max": "La distance doit être inférieure à la distance maximale de la zone tampon",
  "not_between": "La distance doit être comprise entre la distance minimale et maximale de la zone tampon.",
  "not_more_than_min": "La distance doit être supérieure à la distance minimale de la zone tampon",
  "not_valid_number": "Doit être un nombre valide",
  "invalid_value": "La valeur ${type} n’est pas valide",
  "routing_checkBox": "Activer le calcul d'itinéraire",
  "weather_Label": "Paramètres météo",
  "weather_checkBox": "Activer la météo",
  "weather_map_layers": "Sélectionner les couches météorologiques...",
  "selected_map_layers": " couches météorologiques sélectionnées",
  "instruction_weather": "Affichez les informations météorologiques dans un volet.",
  "instruction_weather_layers": "Affichez d'autres couches météorologiques.",
  "instruction_weather_metric": "Affichez les valeurs standard/métriques.",
  "selectLayers": "Sélectionner les couches météorologiques",
  "weather_removed_message": "Les options météorologiques ne sont plus disponibles pour ce widget.",
  "currentlySelectedLayer": "Sélectionner dans les couches cartes",
  "missingTabLabel": "L'étiquette d'un onglet au moins est manquante",
  "missingLayerInWebMap": "Aucune couche opérationnelle n'a été trouvée.",
  "selectFields": "Sélectionner des champs",
  "addField": "Ajouter un champ",
  "sum": "Somme",
  "min": "Minimal",
  "max": "Maximal",
  "avg": "Moyenne",
  "count": "TOTAL",
  "area": "SURFACE",
  "length": "LONGUEUR",
  "count_checkBox": "Afficher le nombre d’entités",
  "area_checkBox": "Afficher la somme de la surface",
  "length_checkBox": "Afficher la somme des longueurs",
  "max_records": "Limite maximale atteinte",
  "save_label": "Options d'enregistrement",
  "save_checkbox": "Activer l'enregistrement",
  "report_label": "Options de rapport",
  "report_checkbox": "Activer le rapport",
  "csv_label": "Options de CSV",
  "csv_checkbox": "Exporter tous les champs",
  "display_label": "Options d'affichage",
  "display_checkbox": "Afficher les entités de synthèse",
  "snapshot_label": "Options de vue figée",
  "snapshot_checkbox": "Activer la vue figée",
  "must_select_template": "Sélectionnez un des rapports de mise à jour dans les options d'enregistrement.",
  "count_label": "Etiquette de nombre",
  "area_label": "Etiquette de zone",
  "length_label": "Etiquette de longueur",
  "invalid_string_width": "La valeur est trop longue. ",
  "layer_type_not_supported": "Type de couche non pris en charge",
  "groupedSummary": "Nombres groupés",
  "groupByField": "Champ Grouper par",
  "labelType": "Ajouter une étiquette",
  "prefix": "En tant que préfixe",
  "suffix": "En tant que suffixe",
  "need_group_field": "Utilisez l'action de mise à jour pour définir un champ Grouper par.",
  "fieldTitle": "Champ",
  "typeTitle": "Type",
  "actionsTitle": "Actions",
  "save_point_checkbox": "Enregistrer des points",
  "save_line_checkbox": "Enregistrer des lignes",
  "save_poly_checkbox": "Enregistrer des polygones",
  "no_valid_popup_fields": "Aucun champ valide dans la fenêtre contextuelle. Utilisez l'action de mise à jour pour définir un champ.",
  "no_valid_fields": "Aucun champ valide. Utilisez l'action de mise à jour pour définir des options d'affichage.",
  "incident_label": "Etiquette de l'onglet",
  "locate_incident_label": "Etiquette de la zone d'intérêt",
  "incident": "Incident",
  "locate_incident": "Localiser l'incident",
  "buffer_value": "Distance de la zone tampon",
  "tab_options": "Analyse",
  "export_options": "Sortie",
  "instruction_save": "Enregistrez le lieu dans un service d'entités.",
  "instruction_snapshot": "Créez une carte web basée sur le lieu.",
  "instruction_report": "Créez un rapport imprimé du lieu.",
  "instruction_all_fields": "Exportez tous les champs avec téléchargement de fichier CSV.",
  "data_label": "Paramètres de sortie des données",
  "layer_error": "Couche manquante ou non valide.",
  "visibility_checkBox": "Désactiver la gestion de la visibilité des couches",
  "downloadTab": {
    "reportLegend": "Paramètres du rapport",
    "textColorLabel": "Sélectionner une couleur pour les titres des colonnes",
    "setButtonLabel": "Définir",
    "printGPServiceLabel": "URL du service d'impression",
    "logoLabel": "Logo",
    "logoChooserHint": "Cliquez sur l'icône de l'image pour modifier l'image",
    "footnoteLabel": "Note de bas de page"
  }
});