define({
  "tabs_section_Label": "索引標籤",
  "addTab": "新增索引標籤",
  "layerName": "圖層",
  "layerType": "分析類型",
  "layerLabel": "標籤",
  "actions": "操作",
  "closest": "最近的圖徵",
  "proximity": "鄰域分析",
  "summary": "摘要",
  "select_lbl": "-- 選擇 --",
  "general_setting_Label": "一般設定",
  "units_text_lbl": "距離單位",
  "maximum_distance_lbl": "最近的圖徵最大距離",
  "buffer_text_lbl": "緩衝區標籤",
  "buffer_lbl": "緩衝距離",
  "buffer_max_lbl": "最大緩衝距離",
  "buffer_min_lbl": "最小緩衝距離",
  "buffer_default_lbl": "預設緩衝區距離",
  "not_less_than_max": "距離必須小於最長緩衝區距離",
  "not_between": "距離必須介於最短與最長緩衝區距離之間",
  "not_more_than_min": "距離必須大於最短緩衝區距離",
  "not_valid_number": "必須是有效數字",
  "invalid_value": "${type} 值有效",
  "routing_checkBox": "啟用路線規劃",
  "weather_Label": "天氣設定",
  "weather_checkBox": "啟用天氣",
  "weather_map_layers": "選擇天氣圖層...",
  "selected_map_layers": " 已選擇天氣圖層",
  "instruction_weather": "在面板中顯示天氣資訊。",
  "instruction_weather_layers": "顯示其他天氣圖層。",
  "instruction_weather_metric": "顯示標準/公制值。",
  "selectLayers": "選擇天氣圖層",
  "weather_removed_message": "此 widget 不再有適用的天氣選項。",
  "currentlySelectedLayer": "從地圖圖層中選擇",
  "missingTabLabel": "至少一個索引標籤缺失標籤",
  "missingLayerInWebMap": "未找到業務圖層。",
  "selectFields": "選擇欄位",
  "addField": "增加欄位",
  "sum": "總和",
  "min": "最小值",
  "max": "最大值",
  "avg": "平均",
  "count": "計數",
  "area": "區域",
  "length": "長度",
  "count_checkBox": "顯示圖徵計數",
  "area_checkBox": "顯示面積總和",
  "length_checkBox": "顯示長度總和",
  "max_records": "已達上限",
  "save_label": "儲存選項",
  "save_checkbox": "啟用儲存",
  "report_label": "報告選項",
  "report_checkbox": "啟用報告",
  "csv_label": "CSV 選項",
  "csv_checkbox": "匯出所有欄位",
  "display_label": "顯示選項",
  "display_checkbox": "顯示摘要圖徵",
  "snapshot_label": "快照集選項",
  "snapshot_checkbox": "啟用快照集",
  "must_select_template": "請在「儲存選項」中選擇其中一個編輯範本。",
  "count_label": "計數標籤",
  "area_label": "面積標籤",
  "length_label": "長度標籤",
  "invalid_string_width": "值太長。 ",
  "layer_type_not_supported": "圖層類型不受支援",
  "groupedSummary": "分組的計數",
  "groupByField": "按欄位分組",
  "labelType": "附加標籤",
  "prefix": "做為前綴",
  "suffix": "做為字尾",
  "need_group_field": "請使用編輯動作來定義「分組依據」欄位。",
  "fieldTitle": "欄位",
  "typeTitle": "類型",
  "actionsTitle": "操作",
  "save_point_checkbox": "儲存點",
  "save_line_checkbox": "儲存線條",
  "save_poly_checkbox": "儲存多邊形",
  "no_valid_popup_fields": "快顯視窗中沒有有效的欄位。請使用編輯動作來定義欄位。",
  "no_valid_fields": "沒有有效的欄位。請使用編輯動作來定義顯示選項。",
  "incident_label": "頁籤標籤",
  "locate_incident_label": "感興趣的區域標籤",
  "incident": "事件",
  "locate_incident": "尋找事件點",
  "buffer_value": "緩衝距離",
  "tab_options": "分析",
  "export_options": "輸出",
  "instruction_save": "將位置儲存到圖徵服務。",
  "instruction_snapshot": "根據位置建立 Web 地圖。",
  "instruction_report": "建立位置的列印報告。",
  "instruction_all_fields": "匯出包含 CSV 下載的所有欄位。",
  "data_label": "資料輸出設定",
  "layer_error": "圖層遺失或無效。",
  "visibility_checkBox": "停用圖層能見度管理",
  "downloadTab": {
    "reportLegend": "報告設定",
    "textColorLabel": "選擇欄標題的顏色",
    "setButtonLabel": "設定",
    "printGPServiceLabel": "列印服務 URL",
    "logoLabel": "標誌",
    "logoChooserHint": "按一下圖片圖示以變更圖片",
    "footnoteLabel": "註腳"
  }
});