define({
  "_widgetLabel": "Query",
  "executeQueryTip": "Klik op een van de volgende taakitems om de query uit te voeren.",
  "invalidConfig": "Ongeldige configuratie. Gebruik de pagina van de query-instellingen om de juiste configuratie te krijgen.",
  "queryParams": "Opties",
  "parameters": "OPTIES",
  "queries": "QUERY'S",
  "apply": "Toepassen",
  "queryResults": "Resultaten",
  "clear": "Wissen",
  "noResults": "Geen object gevonden",
  "queryError": "Query is mislukt.",
  "numberFound": "Aantal gevonden objecten",
  "mapExtentTip": "Beperk de resultaten tot het huidige kaartgebied.",
  "noValue": "Geen waarde",
  "and": "en",
  "stringOperatorIs": "is",
  "stringOperatorIsNot": "is niet",
  "stringOperatorStartsWith": "begint met",
  "stringOperatorEndsWith": "eindigt met",
  "stringOperatorContains": "bevat",
  "stringOperatorDoesNotContain": "bevat niet",
  "stringOperatorIsBlank": "is leeg",
  "stringOperatorIsNotBlank": "is niet leeg",
  "dateOperatorIsOn": "is op",
  "dateOperatorIsNotOn": "is niet op",
  "dateOperatorIsBefore": "is voor",
  "dateOperatorIsAfter": "is na",
  "dateOperatorDays": "dagen",
  "dateOperatorWeeks": "weken",
  "dateOperatorMonths": "maanden",
  "dateOperatorInTheLast": "in de afgelopen",
  "dateOperatorNotInTheLast": "niet in de afgelopen",
  "dateOperatorIsBetween": "is tussen",
  "dateOperatorIsNotBetween": "is niet tussen",
  "dateOperatorIsBlank": "is leeg",
  "dateOperatorIsNotBlank": "is niet leeg",
  "numberOperatorIs": "is",
  "numberOperatorIsNot": "is niet",
  "numberOperatorIsAtLeast": "is minimaal",
  "numberOperatorIsLessThan": "is kleiner dan",
  "numberOperatorIsAtMost": "is maximaal",
  "numberOperatorIsGreaterThan": "is groter dan",
  "numberOperatorIsBetween": "is tussen",
  "numberOperatorIsNotBetween": "is niet tussen",
  "numberOperatorIsBlank": "is leeg",
  "numberOperatorIsNotBlank": "is niet leeg",
  "operationalLayerTip": "Resultaat als operationele laag toevoegen",
  "queryResult": "Zoekresultaat",
  "specifyParamsTip": "Parameters voor deze taak specificeren",
  "useSpatialFilter": "Ruimtelijke filter gebruiken om objecten te beperken",
  "useCurrentMapExtent": "Alleen objecten die het huidige kaartgebieden kruisen",
  "drawGraphicOnMap": "Alleen objecten die het door de gebruiker gedefinieerd gebied kruisen",
  "specifySpatialFilterMsg": "Specificeer een ruimtelijke filter voor deze taak.",
  "clearResults": "Resultaten wissen",
  "operationalTip": "Als deze optie aangevinkt is, worden de resultaten op de kaart gehandhaafd totdat op de knop \"${clearResults}\" wordt geklikt.",
  "noneQueryTip": "Er is geen zoektaak geconfigureerd voor deze widget.",
  "noPermissionsMsg": "U hebt geen toestemming voor toegang tot deze service.",
  "attributesFromRelationship": "Attributen van gerelateerde tabel",
  "tasks": "Taken",
  "applySpatialFilterToLimitResults": "Een ruimtelijk filter toepassen om resultaten te beperken",
  "useCurrentExtentTip": "Alleen objecten retourneren binnen het huidige kaartextent",
  "useDrawGraphicTip": "Alleen objecten retourneren die de vorm kruisen die op de kaart getekend is",
  "useFeaturesTip": "Alleen objecten retourneren die een ruimtelijke relatie met objecten in een andere laag hebben",
  "noSpatialLimitTip": "Objecten retourneren binnen de volledige extent van de kaart",
  "applySearchDistance": "Een zoekafstand toepassen",
  "spatialRelationship": "Ruimtelijke verhouding",
  "relatedLayer": "Gerelateerde laag",
  "bufferDistance": "Bufferafstand",
  "miles": "Mijl",
  "kilometers": "Kilometer",
  "feet": "Voet",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Zeemijl",
  "back": "Vorige",
  "execute": "Uitvoeren",
  "zoomTo": "Zoomen naar",
  "openAttributeTable": "Bekijken in Attribuuttabel",
  "noResult": "Geen resultaat.",
  "noTask": "Geen taak.",
  "removeThisResult": "Dit resultaat verwijderen",
  "attributeCriteira": "Attribuutcriteria",
  "spatialFilter": "Ruimtelijk filter",
  "value": "WAARDE",
  "noAttributeSpatialFilterTip": "Geen filters gedefinieerd. Alle objecten worden geretourneerd.",
  "showAllRelatedRecords": "Alle gerelateerde records weergeven",
  "changeSymbol": "Symbool wijzigen",
  "queryCriteira": "Querycriteria",
  "customQuery": "Aangepaste query",
  "layer": "Kaartlaag",
  "createCustomQuery": "Aangepaste query maken."
});