define({
  "_widgetLabel": "Gráfico de Referência em Grelha",
  "newGRGFromAreaButtonLabel": "Definir uma Grelha a partir de uma Área",
  "newGRGFromPointButtonLabel": "Definir uma Grelha a partir de um Ponto",
  "newGRGFromAreaTitle": "Definir uma Grelha a partir de uma Área",
  "newGRGFromPointTitle": "Definir uma Grelha a partir de um Ponto",
  "newGRGBySizeButtonLabel": "Por Dimensão",
  "newGRGFromRefSystemButtonLabel": "Por Sistema de Referência",
  "newGRGByTimeLabel": "Por Tempo e Velocidade",
  "newGRGFromNonStandardButtonLabel": "Definir grelha não-padrão",
  "newGRGAreaBySizeTitle": "GRG a partir de uma Área por Dimensão",
  "newGRGAreaBySizeDefineAreaLabel": "Área CRG",
  "addGRGAreaPolygonToolTip": "Desenhar Área GRG utilizando polígono",
  "addGRGAreaExtentToolTip": "Desenhar Área GRG utilizando extensão",
  "rotation": "Rotação da Grelha",
  "numberRowsColumnsLabel": "Definir número de linhas e de colunas",
  "newGRGAreaByRefSystemTitle": "GRG a partir de um Sistema de Área por Referência",
  "gridSize": "Tamanho da Grelha",
  "UTMZoneandBand": "Zona da Grelha",
  "100000m": "100000 metros",
  "10000m": "10000 metros",
  "1000m": "1000 metros",
  "100m": "100 metros",
  "10m": "10 metros",
  "clipGrid": "Recortar Grelha para Área GRG",
  "newGRGAreaFromNonStandardTitle": "Novo NRG",
  "newGRGPointBySizeTitle": "GRG a partir de Ponto por Dimensão",
  "newGRGPointByRefSystemTitle": "GRG a partir de Sistema de Ponto por Referência",
  "newGRGPointByTimeTitle": "GRG a partir de Ponto utilizando Tempo e Velocidade",
  "time": "Tempo",
  "rate": "Velocidade",
  "hours": "Horas",
  "minutes": "Minutos",
  "seconds": "Segundos",
  "ftPerSec": "Pés / segundo",
  "ftPerHour": "Pés / hora",
  "kmPerSec": "Quilómetros / segundo",
  "kmPerHour": "Quilómetros / hora",
  "mPerSec": "Metros / segundo",
  "mPerHour": "Metros / hora",
  "miPerSec": "Milhas / segundo",
  "miPerHour": "Milhas / hora",
  "nMPerSec": "Milhas Náuticas / segundo",
  "nMPerHour": "Milhas Náuticas / hora",
  "settingsTitle": "Configurações",
  "labelSettingsLabel": "Definições de Rótulo",
  "labelSettingsButtonLabel": "Configurar Definições de Rótulo",
  "gridSettingsLabel": "Definições de Grelha",
  "gridSettingsButtonLabel": "Configurar Definições de Grelha",
  "transparency": "Transparência",
  "labelStyle": "Estilo do Rótulo",
  "font": "Fonte",
  "textSize": "Tamanho do Texto",
  "textColor": "Cor do Texto",
  "halo": "Halo",
  "show": "Exibir",
  "lockSettings": "As definições foram bloqueadas pelo proprietário da aplicação",
  "gridSettings": {
    "cellShape": "Formato de Células",
    "cellUnits": "Unidades de Células",
    "cellOutline": "Definições de Contorno de Células",
    "cellFill": "Definições de Preenchimento de Células",
    "gridReferenceSystem": "Sistema de Referência",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Origem de Rótulo",
    "labelType": "Tipo de Rótulo",
    "labelDirection": "Direção de Rótulo",
    "gridOrigin": "Origem de Rótulo",
    "default": "Retângulo",
    "hexagon": "Hexágono",
    "miles": "Milhas",
    "kilometers": "Quilómetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nautical-miles": "Milhas Náuticas",
    "lowerLeft": "Inferior Esquerda",
    "lowerRight": "Inferior Direita",
    "upperLeft": "Superior Esquerda",
    "upperRight": "Superior Direita",
    "center": "Centrar",
    "alphaNumeric": "Alfanumérico",
    "alphaAlpha": "Alfa-Alfa",
    "numeric": "Numérico",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Exibir Rótulos"
  },
  "publishTitle": "Publicar GRG no Portal",
  "publishGRGBtn": "Publicar",
  "GRGLayerName": "Nome de Camada GRG Publicada",
  "invalidGRGLayerName": "O nome da camada pode apenas conter caracteres alfanuméricos e traços inferiores.",
  "missingGRGLayerName": "Tem de introduzir um nome para o GRG",
  "publishingFailedLayerExists": "Publicação Falhou: Já possui um serviço de elementos denominado {0}. Por favor, escolha outro nome.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não é possível criar: {0}",
  "addToDefinition": "Adicionar a definição: {0}",
  "successfullyPublished": "Camada web publicada com sucesso{0}Gerir a camada web",
  "userRole": "Não é possível criar o serviço porque o utilizador não possui permissões",
  "createGRGBtn": "Criar GRG",
  "clearGRGBtn": "Apagar",
  "labelFormat": "Formato de Rótulo",
  "helpIconTooltip": "Z: Designador de Zona de Grelha (GZD)\nS: Identificação de Quadrado de Grelha de 100,000 metros (GSID)\nX: Avanço para Este (Coordenada X)\nY: Avanço para Norte (Coordenada Y)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205",
  "addPointToolTip": "Adicionar Origem GRG",
  "cellWidth": "Largura de Célula (x)",
  "cellHeight": "Altura de Célula (y)",
  "invalidNumberMessage": "O valor introduzido não é válido",
  "invalidRangeMessage": "O valor tem de ser maior do que 0",
  "gridAngleInvalidRangeMessage": "O valor tem de encontrar-se entre -89,9 e 89,9.",
  "formatIconTooltip": "Introdução de Formato",
  "coordInputLabel": "Origem GRG (DD)",
  "setCoordFormat": "Definir String de Formatação de Coordenadas",
  "prefixNumbers": "Adicionar o prefixo ‘+/-’ a números positivos e negativos",
  "cancelBtn": "Cancelar",
  "applyBtn": "Aplicar",
  "comfirmInputNotation": "Confirmar Notação de Entrada",
  "notationsMatch": "notações correspondem à sua entrada, por favor, confirme as que pretende utilizar:",
  "numberOfCellsHorizontal": "# Células Horizontais",
  "numberOfCellsVertical": "# Células Vericais",
  "gridAngle": "Rotação da Grelha",
  "tooManyCellsErrorMessage": "Está a tentar criar uma grelha que contém mais do que 2000 células. É aconselhável reduzir o número de células a criar, alterando o tamaho da grelha ou a área da grelha.",
  "missingParametersMessage": "<p>A criação do formulário GRG tem parâmetros em falta ou inválidos, Por favor, assegure que:</p><ul><li>Foi desenhada uma área GRG.</li><li>A largura e altura de célula contêm valores válidos.</li></ul>",
  "missingOriginParametersMessage": "<p>A criação do formulário GRG tem parâmetros em falta ou inválidos, Por favor, assegure que:</p><ul><li>Foi definida uma origem GRG.</li><li>As entradas de tempo, velocidade e ângulo contêm valores válidos.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>A criação do formulário GRG tem parâmetros em falta ou inválidos. Por favor, assegure que as entradas de largura e altura de célula contêm valores válidos.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>A criação do formulário GRG tem parâmetros em falta ou inválidos. Por favor, assegure que o número de entradas horizontais e verticais de células contêm valores válidos.</p>",
  "drawPointToolTip": "Clique para adicionar ponto de origem GRG",
  "missingLayerNameMessage": "Tem de introduzir um nome de camada válido antes de poder publicar",
  "parseCoordinatesError": "Não foi possível analisar as coordenadas. Por favor, verifique a entrada.",
  "grgPolarRegionError": "A extensão do GRG abrange uma região polar. As células localizadas na região polar não serão criadas.",
  "grgPolarOriginError": "O ponto de origem GRG não pode encontrar-se numa região polar ao criar um Sistema GRG por Referência.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais  - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Decimais Minutos - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Decimais Minutos - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/ Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra de Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)"
});