define({
  "gridTabLabel": "Lưới",
  "labelTabLabel": "Nhãn",
  "referenceSystemTabLabel": "Hệ Tham chiếu",
  "gridTabDescription": "Thiết lập hình thức và hành vi của các ô lưới.",
  "cellOutlineColor": "Màu của Đường nét ô",
  "cellFillColor": "Tô màu cho ô",
  "transparency": "Độ trong suốt",
  "cellShapeDropDown": "Hình dạng ô",
  "default": "Hình chữ nhật",
  "hexagon": "Hình lục giác",
  "cellUnitsDropDown": "Đơn vị ô",
  "miles": "Dặm",
  "kilometers": "Kilômét",
  "feet": "Bộ",
  "meters": "Mét",
  "yards": "Thước",
  "nautical-miles": "Hải lý",
  "gridOriginDropDown": "Điểm gốc lưới",
  "lowerLeft": "Phía dưới bên trái",
  "lowerRight": "Phía dưới bên phải",
  "upperLeft": "Phía trên bên trái",
  "upperRight": "Phía trên bên phải",
  "center": "Tâm",
  "labelTabDescription": "Thiết lập hình thức và hành vi của các nhãn lưới.",
  "labelSettings": "Kiểu nhãn",
  "font": "Phông chữ",
  "textSize": "Kích cỡ Văn bản",
  "textColor": "Màu Văn bản",
  "halo": "Hào quang",
  "show": "Hiển thị",
  "labelTypeDropDown": "Loại nhãn",
  "alphaNumeric": "Chữ-Số",
  "alphaAlpha": "Chữ-Chữ",
  "numeric": "Số",
  "labelDirectionDropDown": "Hướng nhãn",
  "horizontal": "Ngang",
  "vertical": "Dọc",
  "labelOriginDropDown": "Điểm gốc của nhãn",
  "referenceSystemlTabDescription": "Thiết lập hệ tham chiếu mặc định.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Cài đặt khóa - Cài đặt này sẽ không cho phép người dùng có thể thay đổi bất kỳ cài đặt được cấu hình nào trong tiện ích"
});