define({
  "gridTabLabel": "Grille",
  "labelTabLabel": "Etiquettes",
  "referenceSystemTabLabel": "Système de référence",
  "gridTabDescription": "Définir l’apparence et le comportement des cellules de grille.",
  "cellOutlineColor": "Couleur de contour des cellules",
  "cellFillColor": "Couleur de remplissage des cellules",
  "transparency": "Transparence",
  "cellShapeDropDown": "Forme des cellules",
  "default": "Rectangle",
  "hexagon": "Hexagone",
  "cellUnitsDropDown": "Unités des cellules",
  "miles": "Milles",
  "kilometers": "Kilomètres",
  "feet": "Pieds",
  "meters": "Mètres",
  "yards": "Yards",
  "nautical-miles": "Milles nautiques",
  "gridOriginDropDown": "Origine de la grille",
  "lowerLeft": "Inférieur gauche",
  "lowerRight": "Inférieur droit",
  "upperLeft": "Supérieur gauche",
  "upperRight": "Supérieur droit",
  "center": "Centre",
  "labelTabDescription": "Définir l’apparence et le comportement des étiquettes de grille.",
  "labelSettings": "Style des étiquettes",
  "font": "Police",
  "textSize": "Taille de texte",
  "textColor": "Couleur de texte",
  "halo": "Halo",
  "show": "Afficher",
  "labelTypeDropDown": "Type de l’étiquette",
  "alphaNumeric": "Alpha-Numérique",
  "alphaAlpha": "Alpha-Alpha",
  "numeric": "Numérique",
  "labelDirectionDropDown": "Direction de l’étiquette",
  "horizontal": "Horizontale",
  "vertical": "Verticale",
  "labelOriginDropDown": "Origine de l’étiquette",
  "referenceSystemlTabDescription": "Définir le système de référence par défaut.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Verrouiller les paramètres : ceci empêchera l’utilisateur de modifier les paramètres configurés dans le widget"
});