define({
  "_widgetLabel": "距離和方向",
  "tabLineTitle": "線",
  "tabCircleTitle": "圓形",
  "tabEllipseTitle": "橢圓形",
  "tabRingsTitle": "圓環",
  "multipleNotationsMessage": " 符合您輸入的標記法。請確定您要使用哪個標記法:",
  "invalidCoordinateMessage": "座標無效",
  "confirmInputNotationMessage": "確認輸入標記法",
  "prefixSuffixMessage": "已偵測到輸入座標的緯度或經度值皆具有字首和字尾，會根據字首傳回座標。",
  "rememberDecisionMessage": "記住我的決定且不要再提問。<br/>",
  "majorAxisTooltipMessage": "按一下長軸的長度",
  "minorAxisTooltipMessage": "將滑鼠移回開始位置以設定短軸並完成橢圓繪製",
  "clickToFinishLineMessage": "按一下以完成線條繪製",
  "doubleClickEllipseMesage": "按兩下以完成範圍環繪製",
  "invalidCoordinateTypeMessage": "無法判定輸入座標類型。請檢查您的輸入",
  "noCenterPointSetMessage": "未設定中心點。請檢查您的輸入",
  "ellipseMajorAxis": "長軸",
  "ellipseMinorAxis": "短軸",
  "degreesRangeMessage": "值必須在 0 到 360 之間",
  "millsRangeMessage": "值必須在 0 到 6400 之間",
  "lengthLabel": "長度",
  "angleLabel": "角度",
  "startPointLabel": "起點",
  "endPointLabel": "端點",
  "centerPointLabel": "中心點",
  "distanceTableErrorMessage": "距離表格空白。請確定輸入一些距離。",
  "setCoordFormatStringMessage": "設定座標格式字串",
  "prefixMessage": "新增 '+/-' 字首以變為正數和負數",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "十進位度 - 緯度/經度",
  "DDLongLatNotation": "十進位度 - 經度/緯度",
  "DDMLatLongNotation": "度十進制分 - 緯度/經度",
  "DDMLongLatNotation": "度十進制分 - 經度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/經度",
  "DMSLongLatNotation": "度分秒 - 經度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 頻段字母",
  "UTMHemNotation": "UTM - 半球 (N/S)",
  "circleTitle": "建立圓形來源",
  "radiusLabel": "半徑",
  "diameterLabel": "直徑",
  "startPointPlaceHolderLabel": "輸入坐標",
  "formatInputLabel": "格式輸入",
  "drawCircleLabel": "繪製圓形",
  "drawLineLabel": "繪製線",
  "createCircleInteractivelyLabel": "以互動方式建立圓形",
  "rangeErrorMessage": "半徑或直徑無效",
  "numericInvalidMessage": "請輸入數值",
  "timeLabel": "時間",
  "invalidTimeMessage": "時間值無效",
  "hoursLabel": "小時",
  "minutesLabel": "分鐘",
  "secondsLabel": "秒",
  "rateLabel": "比例",
  "invalidDistanceMessage": "距離值無效",
  "feetSecondsLabel": "英呎/秒",
  "feetHourLabel": "英呎/小時",
  "kmSecondLabel": "公里/秒",
  "kmHourLabel": "公里/小時",
  "metersSecondLabel": "公尺/秒",
  "metersHourLabel": "公尺/小時",
  "milesSecondLabel": "英哩/秒",
  "milesHourLabel": "英哩/小時",
  "nauticalMilesSecondLabel": "海浬/秒",
  "nauticalMilesHourLabel": "海浬/小時",
  "clearGraphicsLabel": "清除圖形",
  "ellipseTypeLabel": "橢圓類型",
  "ellipseSemiLabel": "半",
  "ellipseFullLabel": "完整",
  "drawEllipseLabel": "繪製橢圓",
  "createEllipseInteractively": "以互動方式建立橢圓",
  "axisLabel": "軸",
  "majorRadiusLabel": "長 (半徑)",
  "axisErrorMessage": "值必須大於 0",
  "minorRadiusLabel": "短 (半徑)",
  "orientationLabel": "定向",
  "orientationErrorMessage": "值必須在 0 到 360 之間",
  "warningMessage": "警告: 使用橢圓工具產生的圖形不是測地線",
  "fromLabel": "從",
  "distanceBearingLabel": "距離和方位",
  "pointsLabel": "點",
  "createLineInteractively": "以互動方式建立線條",
  "lineLengthErrorMessage": "線條長度無效",
  "degreesLabel": "度",
  "milsLabel": "密爾",
  "lineTypeLabel": "類型",
  "interactiveLabel": "互動",
  "fixedLabel": "已修正",
  "originLabel": "原點",
  "cumulativeLabel": "累計",
  "numberOfRingsLabel": "環數",
  "ringsErrorMessage": "環數無效",
  "distanceBetweenRingsLabel": "環之間的距離",
  "ringsDecimalErrorMessage": "輸入 2 個小數位數的數值",
  "distanceUnitsLabel": "距離單位",
  "distancesLabel": "距離",
  "numberOfRadialsLabel": "半徑數量",
  "upLabel": "上",
  "downLabel": "下",
  "deleteLabel": "刪除",
  "radialsErrorMessage": "半徑數字無效。允許的最大值是 360",
  "addPointLabel": "新增點",
  "valueLabel": "值",
  "valueText": "輸入值",
  "actionLabel": "操作"
});