define({
  "_widgetLabel": "Modeler vhodnosti",
  "general": {
    "clear": "Vymazat",
    "cancel": "Storno",
    "save": "Spustit",
    "saveAs": "Exportovat"
  },
  "saveModel": {
    "save": "Exportovat",
    "title": "Nadpis: ",
    "summary": "Shrnutí: ",
    "description": "Popis: ",
    "tags": "Klíčová slova: ",
    "folder": "Složka: ",
    "homeFolderPattern": "{username} (domovská stránka)",
    "failed": "Export se nezdařil."
  },
  "util": {
    "colorRamp": {
      "1": "Extrémně nízká",
      "2": "Velmi nízká",
      "3": "Nízká",
      "4": "Nízká střední",
      "5": "Střední",
      "6": "Vysoká střední",
      "7": "Vysoká",
      "8": "Velmi vysoká",
      "9": "Extrémně vysoká",
      "low": "Nízká",
      "high": "Vysoká",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Převrátit"
    }
  },
  "wro": {
    "caption": "Modeler vhodnosti",
    "browsePrompt": "Služba váženého překryvu",
    "selectLayersCaption": "Vybrat vrstvy",
    "selectLayers": "Vrstvy",
    "designModelCaption": "Navrhnout model",
    "designModel": "Navrhnout model",
    "transparency": "Průhlednost",
    "visible": "Viditelné",
    "total": "Souhrn",
    "unableToLoad": "Nelze načíst model.",
    "projectNotOpen": "Projekt není otevřen.",
    "readMore": "Přečtěte si více",
    "validation": {
      "validating": "Ověřování…",
      "invalidItemCaption": "Varování služby váženého překryvu",
      "notAnImageService": "Tato položka není obrazová služba.",
      "notAWroService": "Tato položka není služba váženého překryvu.",
      "undefinedUrl": "Adresa URL této položky není definována.",
      "inaccessible": "Služba je nedostupná.",
      "generalError": "Nelze otevřít položku.",
      "missingFieldPattern": "{field} je vyžadované pole",
      "notAllowRasterFunction": "allowRasterFunction musí být nastaveno na hodnotu true.",
      "notNearestResampling": "defaultResamplingMethod musí být nastaveno na hodnotu Nejbližší.",
      "notIsWeightedOverlayProp": "Klíčová vlastnost IsWeightedOverlay musí být nastavena na hodnotu true.",
      "invalidLink": "Adresa URL je neplatná. Nepodařilo se otevřít web pro vybranou vrstvu.",
      "unexpectedError": "Nastal neočekávaný stav.",
      "rangeMessage": "Hodnota musí být mezi ${0} a ${1}.",
      "rangeMessage100": "Hodnota musí být mezi 0 a 100.",
      "maxLayers": "Služba dovoluje maximálně ${0} vrstev, před přidáním nové vrstvy nejprve musíte vrstvu odstranit.",
      "notFound": "Vrstva ${0} nebyla nalezena ve službě váženého překryvu.",
      "wroServiceNotDefined": "Pro model není definována žádná služba váženého překryvu.",
      "overlayLayerOutputInvalid": "Výstupní hodnota rozsahů přemapování [${1}] vrstvy překryvu [${0}] chybí nebo je neplatná.",
      "overlayLayerInputInvalid": "Vstupní minimum/maximum rozsahů přemapování [${1}] vrstvy překryvu [${0}] chybí nebo je neplatné.",
      "overlayLayerRangesMissing": "Ve vrstvě překryvu [${0}] chybí rozsahy přemapování.",
      "overlayLayerWeight": "Váhy vrstvy překryvu musí dohromady dávat 100.",
      "overlayLayerRequired": "Je vyžadována alespoň jedna vrstva překryvu.",
      "overlayLayerNotDefined": "Vrstvy překryvu nejsou definovány.",
      "requiresColormap": "Tato rastrová funkce vyžaduje mapu barev, ale model nemá platnou definici mapy barev.",
      "createModelError": "Při vytváření modelu došlo k chybě.",
      "invalidModel": "Model je neplatný.",
      "imageServiceNotDefined": "Vrstva obrazové služby není definována.",
      "imageLayerNotDefined": "Vrstva obrazové služby není definována.",
      "histogramNotDefined": "Není definována žádná funkce histogramu váženého překryvu."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zelená žlutá červená",
      "Red Yellow Green": "Červená žlutá zelená",
      "Yellow to Dark Red": "Žlutá až tmavě červená",
      "Dark Red to Yellow": "Tmavě červená až žlutá",
      "Light Gray to Dark Gray": "Světle šedá až tmavě šedá",
      "Dark Gray to Light Gray": "Tmavě šedá až světle šedá",
      "Light Brown to Dark Brown": "Světle hnědá až tmavě hnědá",
      "Dark Brown to Light Brown": "Tmavě hnědá až světle hnědá",
      "Full Spectrum - Bright Red to Blue": "Plné spektrum – světle červená až modrá",
      "Full Spectrum - Bright Blue to Red": "Plné spektrum – světle modrá až červená",
      "Partial Spectrum - Yellow to Blue": "Částečné spektrum – žlutá až modrá",
      "Partial Spectrum - Blue to Yellow": "Částečné spektrum – modrá až žlutá",
      "Yellow-Green to Dark Blue": "Žlutozelená až tmavě modrá",
      "Dark Blue to Yellow-Green": "Tmavě modrá až žlutozelená",
      "Cold to Hot Diverging": "Studené až teplé barvy, divergentní",
      "Hot to Cold Diverging": "Teplé až studené barvy, divergentní",
      "Surface - Low to High": "Povrch – nízký až vysoký",
      "Surface - High to Low": "Povrch – vysoký až nízký"
    }
  },
  "tabs": {
    "layers": "Vrstvy",
    "model": "Model",
    "chart": "Graf"
  },
  "chart": {
    "prompt": "Vlastnosti",
    "working": "Probíhá aktualizace…",
    "polygonTool": "Nakreslit polygon",
    "freehandPolygonTool": "Nakreslit polygon od ruky",
    "selectTool": "Vybrat z vrstvy",
    "panTool": "Posun",
    "clearButton": "Zrušit výběr",
    "noModelLayer": "Chybí model.",
    "noSubjectLayers": "Vaše mapa neobsahuje žádné polygonové vrstvy.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});