define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "L'account non dispone dell'autorizzazione per creare o modificare dati.",
  "widgetActive": "Attivo",
  "widgetNotActive": "Non attiva",
  "pressStr": "Premere ",
  "ctrlStr": " CTRL ",
  "snapStr": " per abilitare lo snap",
  "noAvailableTempaltes": "Nessun modello disponibile",
  "editorCache": " - Cache editor",
  "presetFieldAlias": "Campo",
  "presetValue": "Valore preimpostato",
  "usePresetValues": " Utilizza valori preimpostati (Solo nuove feature)",
  "editGeometry": " Modifica geometria",
  "savePromptTitle": "Salva feature",
  "savePrompt": "Salvare la feature corrente?",
  "deletePromptTitle": "Elimina feature",
  "deletePrompt": "Eliminare la feature selezionata?",
  "attachmentLoadingError": "Errore durante il caricamento degli allegati",
  "attachmentSaveDeleteWarning": "Avviso: le modifiche agli allegati non vengono salvate automaticamente",
  "autoSaveEdits": "Salva automaticamente la modifica",
  "addNewFeature": "Crea nuova feature",
  "featureCreationFailedMsg": "Impossibile creare nuovo record/feature",
  "noRelatedFeatureFoundMsg": "Nessun record/feature correlato trovato",
  "relatedItemTitle": "Tabella/layer correlato",
  "invalidRelationShipMsg": "Verificare che il campo della chiave primaria: '${parentKeyField}' contenga un valore valido",
  "pendingFeatureSaveMsg": "Salvare le modifiche apportate alla feature prima di creare una feature correlata.",
  "attachmentsRequiredMsg": "(*) Allegati richiesti.",
  "filterEditor": {
    "all": "Tutto",
    "noAvailableTempaltes": "Nessun modello disponibile",
    "searchTemplates": "Cerca modelli"
  },
  "invalidConfiguration": "Il widget non è configurato o i layer nella configurazione non sono più presenti nella mappa. Aprire l'app nella modalità generatore e riconfigurare il widget.",
  "geometryServiceURLNotFoundMSG": "Impossibile ottenere l'URL del servizio geometria"
});