define({
  "add": "Haga clic para agregar nuevo",
  "title": "Título",
  "placeholderBookmarkName": "Nombre del marcador",
  "ok": "Aceptar",
  "cancel": "Cancelar",
  "warning": "Termina la edición.",
  "edit": "Editar marcador",
  "errorNameExist": "¡El marcador ya existe!",
  "errorNameNull": "¡Nombre del marcador no válido!",
  "addBookmark": "Crear nuevo",
  "thumbnail": "Miniatura",
  "thumbnailHint": "Haz clic en la imagen para actualizar",
  "displayBookmarksAs": "Visualizar marcadores como",
  "cards": "Tarjetas",
  "list": "Lista",
  "cardsTips": "Vista de tarjetas",
  "listTips": "Vista de lista",
  "makeAsDefault": "Definir como predeterminado",
  "default": "Predeterminado",
  "editable": "Permitir agregar marcadores en el widget.",
  "alwaysSync": "Visualizar marcadores del mapa web",
  "configCustom": "Visualizar marcadores personalizados",
  "import": "Importar",
  "create": "Crear",
  "importTitle": "Importar marcadores",
  "importFromWeb": "Importar marcadores del mapa web actual",
  "selectAll": "Seleccionar todo",
  "noBookmarkInConfig": "Haga clic en â€œImportarâ€ o en â€œCrear nuevoâ€ para agregar marcadores.",
  "noBookmarkInWebMap": "No hay ningún marcador configurado en el mapa.",
  "extent": "Extensión",
  "saveExtent": "Guardar la extensión de mapa en este marcador",
  "savelayers": "Guardar visibilidad de capa",
  "withVisibility": "Con visibilidad de capa",
  "bookmark": "Marcador",
  "addBtn": "Agregar",
  "deleteBtn": "Eliminar",
  "editBtn": "Editar",
  "dragReorderTip": "Mantener y arrastrar para volver a ordenar",
  "deleteBtnTip": "Eliminar el marcador",
  "editBtnTip": "Editar el marcador"
});