define({
  "add": "Clique para adicionar um novo",
  "title": "Título",
  "placeholderBookmarkName": "Nome do marcador",
  "ok": "Ok",
  "cancel": "Cancelar",
  "warning": "Por favor termine a edição!",
  "edit": "Editar marcador",
  "errorNameExist": "O Marcador existe!",
  "errorNameNull": "Nome de marcador inválido!",
  "addBookmark": "Criar novo",
  "thumbnail": "Miniatura",
  "thumbnailHint": "Clique na imagem para atualizar",
  "displayBookmarksAs": "Exibir marcadores como",
  "cards": "Cartões",
  "list": "Lista",
  "cardsTips": "Vista de Cartões",
  "listTips": "Vista de Lista",
  "makeAsDefault": "Criar predefinição",
  "default": "Padrão",
  "editable": "Permitir adicionar marcadores no widget.",
  "alwaysSync": "Exibir marcadores a partir do mapa web",
  "configCustom": "Exbir marcadores personalizados",
  "import": "Importar",
  "create": "Criar",
  "importTitle": "Importar Marcadores",
  "importFromWeb": "Importar marcadores do mapa web atual",
  "selectAll": "Selecionar Tudo",
  "noBookmarkInConfig": "Clique em â€œImportarâ€ ou â€œCriar Novoâ€ para adicionar marcadores.",
  "noBookmarkInWebMap": "Não se encontra configurado qualquer marcador no mapa.",
  "extent": "Extensão:",
  "saveExtent": "Guardar extensão do mapa neste marcador",
  "savelayers": "Guardar a visibilidade da camada",
  "withVisibility": "Com visibilidade de camada",
  "bookmark": "Marcador",
  "addBtn": "Adicionar",
  "deleteBtn": "Excluir",
  "editBtn": "Editar",
  "dragReorderTip": "Manter premido e arrastar para reordenar",
  "deleteBtnTip": "Eliminar o marcador",
  "editBtnTip": "Editar o marcador"
});