define({
  "_widgetLabel": "Rutnätsreferensgrafik",
  "newGRGFromAreaButtonLabel": "Definiera ett rutnät från ett område",
  "newGRGFromPointButtonLabel": "Definiera ett rutnät från en punkt",
  "newGRGFromAreaTitle": "Definiera ett rutnät från ett område",
  "newGRGFromPointTitle": "Definiera ett rutnät från en punkt",
  "newGRGBySizeButtonLabel": "Efter mått",
  "newGRGFromRefSystemButtonLabel": "Efter referenssystem",
  "newGRGByTimeLabel": "Efter tid och hastighet",
  "newGRGFromNonStandardButtonLabel": "Definiera icke-standardrutnät",
  "newGRGAreaBySizeTitle": "GRG från ett område efter mått",
  "newGRGAreaBySizeDefineAreaLabel": "GRG-område",
  "addGRGAreaPolygonToolTip": "Rita GRG-område med polygon",
  "addGRGAreaExtentToolTip": "Rita GRG-område med utbredning",
  "rotation": "Rotation för rutnät",
  "numberRowsColumnsLabel": "Definiera antal rader och kolumner",
  "newGRGAreaByRefSystemTitle": "GRG från ett område efter referenssystem",
  "gridSize": "Rutnätsstorlek",
  "UTMZoneandBand": "Rutnätszon",
  "100000m": "100 000 meter",
  "10000m": "10 000 meter",
  "1000m": "1 000 meter",
  "100m": "100 meter",
  "10m": "10 meter",
  "clipGrid": "Klipp ut rutnät till GRG-område",
  "newGRGAreaFromNonStandardTitle": "Nytt NRG",
  "newGRGPointBySizeTitle": "GRG från en punkt efter mått",
  "newGRGPointByRefSystemTitle": "GRG från en punkt efter referenssystem",
  "newGRGPointByTimeTitle": "GRG från en punkt med hjälp av tid och hastighet",
  "time": "Tid",
  "rate": "Hastighet",
  "hours": "Timmar",
  "minutes": "Minuter",
  "seconds": "Sekunder",
  "ftPerSec": "Fot/sekund",
  "ftPerHour": "Fot/timme",
  "kmPerSec": "Kilometer/sekund",
  "kmPerHour": "Kilometer/timme",
  "mPerSec": "Meter/sekund",
  "mPerHour": "Meter/timme",
  "miPerSec": "Engelska mil/sekund",
  "miPerHour": "Engelska mil/timme",
  "nMPerSec": "Nautiska mil/sekund",
  "nMPerHour": "Nautiska mil/timme",
  "settingsTitle": "Inställningar",
  "labelSettingsLabel": "Etikettinställningar",
  "labelSettingsButtonLabel": "Konfigurera etikettinställningar",
  "gridSettingsLabel": "Inställningar för rutnät",
  "gridSettingsButtonLabel": "Konfigurera rutnätsinställningar",
  "transparency": "Transparens",
  "labelStyle": "Etikettstil",
  "font": "Teckensnitt",
  "textSize": "Textstorlek",
  "textColor": "Textfärg",
  "halo": "Ring",
  "show": "Visa",
  "lockSettings": "Inställningen har låsts av applikationens ägare",
  "gridSettings": {
    "cellShape": "Cellens form",
    "cellUnits": "Cellenheter",
    "cellOutline": "Inställningar för cellens kontur",
    "cellFill": "Inställningar för cellens fyllnadsfärg",
    "gridReferenceSystem": "Referenssystem",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Etikettens ursprung",
    "labelType": "Etikettyp",
    "labelDirection": "Etikettens riktning",
    "gridOrigin": "Rutnätets origo",
    "default": "Rektangel",
    "hexagon": "Hexagon",
    "miles": "Mile",
    "kilometers": "Kilometer",
    "feet": "Fot",
    "meters": "Meter",
    "yards": "Yard",
    "nautical-miles": "Nautiska mil",
    "lowerLeft": "Nedre vänstra",
    "lowerRight": "Nedre högra",
    "upperLeft": "Övre vänstra",
    "upperRight": "Övre högra",
    "center": "Centrera",
    "alphaNumeric": "Alfanumerisk",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Numerisk",
    "horizontal": "Horisontell",
    "vertical": "Vertikal",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Visa etiketter"
  },
  "publishTitle": "Publicera GRG till portalen",
  "publishGRGBtn": "Publicera",
  "GRGLayerName": "Publicerat GRG-lagernamn",
  "invalidGRGLayerName": "Lagrets namn får endast innehålla alfanumeriska tecken och understreck",
  "missingGRGLayerName": "Du måste ange ett namn på GRG",
  "publishingFailedLayerExists": "Publiceringen misslyckades: du har redan en geoobjekttjänst som heter {0}. Välj ett annat namn.",
  "checkService": "Kontrollera tjänsten: {0}",
  "createService": "Skapa tjänst: {0}",
  "unableToCreate": "Det gick inte att skapa: {0}",
  "addToDefinition": "Lägg till i definition: {0}",
  "successfullyPublished": "Webblagret har publicerats{0}Hantera webblagret",
  "userRole": "Det går inte att skapa tjänsten eftersom användaren inte har behörighet",
  "createGRGBtn": "Skapa GRG",
  "clearGRGBtn": "Avmarkera",
  "labelFormat": "Etikettformat",
  "helpIconTooltip": "Z: Tecken för rutnätszon (GZD)\nS: 100 000 meter identifiering av rutnätskvadrat (GSID)\nX: Östlig avvikelse (X-koordinat)\nY: Nordlig avvikelse (Y-koordinat)\n\nExempel:\nZSXY är 15SWC8081751205\nZS X,Y är 15SWC 80817,51205",
  "addPointToolTip": "Lägg till GRG-ursprung",
  "cellWidth": "Cellvidd (x)",
  "cellHeight": "Cellhöjd (y)",
  "invalidNumberMessage": "Det angivna värdet är ogiltigt",
  "invalidRangeMessage": "Värdet måste vara större än 0",
  "gridAngleInvalidRangeMessage": "Värdet måste vara mellan -89,9 och 89,9",
  "formatIconTooltip": "Formatinmatning",
  "coordInputLabel": "GRG-ursprung (DD)",
  "setCoordFormat": "Ange koordinatsträng",
  "prefixNumbers": "Lägg till prefixet \"+/-\" för positiva och negativa tal",
  "cancelBtn": "Avbryt",
  "applyBtn": "Verkställ",
  "comfirmInputNotation": "Bekräfta inmatningsnotation",
  "notationsMatch": "notationer matchar inmatningen. Bekräfta vilka du vill använda:",
  "numberOfCellsHorizontal": "# Horisontella celler",
  "numberOfCellsVertical": "# Vertikala celler",
  "gridAngle": "Rotation för rutnät",
  "tooManyCellsErrorMessage": "Du försöker skapa ett rutnät som består av fler än 2 000 celler. Vi rekommenderar att du minskar antalet celler som ska skapas genom att ändra rutnätets storlek eller område.",
  "missingParametersMessage": "<p>Formuläret för att skapa GRG innehåller saknade eller ogiltiga parametrar. Säkerställ att:</p><ul><li>Ett GRG-område har ritats.</li><li>Cellens vidd och höjd innehåller giltiga värden.</li></ul>",
  "missingOriginParametersMessage": "<p>Formuläret för att skapa GRG innehåller saknade eller ogiltiga parametrar. Säkerställ att:</p><ul><li>Ett GRG-ursprung har angetts.</li><li>Inmatningarna för tid, hastighet och vinkel innehåller giltiga värden.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Formuläret för att skapa GRG innehåller saknade eller ogiltiga parametrar. Säkerställ att inmatningarna av cellens vidd och höjd innehåller giltiga värden.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Formuläret för att skapa GRG innehåller saknade eller ogiltiga parametrar. Säkerställ att inmatningarna för antalet horisontella och vertikala celler innehåller giltiga värden.</p>",
  "drawPointToolTip": "Klicka för att lägga till en GRG-ursprungspunkt",
  "missingLayerNameMessage": "Du måste ange ett giltigt lagernamn innan du kan publicera",
  "parseCoordinatesError": "Det gick inte att tolka koordinaterna. Kontrollera din inmatning.",
  "grgPolarRegionError": "GRG-utbredningen ligger inom en polarregion. Cellerna som hamnar inom polarregionen skapas inte.",
  "grgPolarOriginError": "GRG-ursprungspunkten kan inte ligga inom en polarregion när en GRG skapas av referenssystemet.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader – Latitud/longitud",
  "DDLongLatNotation": "Decimalgrader – Longitud/latitud",
  "DDMLatLongNotation": "Grader decimalminuter – Latitud/longitud",
  "DDMLongLatNotation": "Grader decimalminuter – Longitud/latitud",
  "DMSLatLongNotation": "Grader minuter sekunder – Latitud/longitud",
  "DMSLongLatNotation": "Grader minuter sekunder – Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbokstav",
  "UTMHemNotation": "UTM – Halvklot (N/S)"
});