define({
  "enableUndoRedo": "Rückgängig/Wiederholen aktivieren",
  "toolbarVisible": "Werkzeugleiste einblenden",
  "toolbarOptions": "Werkzeugleistenoptionen",
  "mergeVisible": "Zusammenführen",
  "cutVisible": "Ausschneiden",
  "reshapeVisible": "Umformen",
  "back": "Zurück",
  "label": "Layer",
  "edit": "Editierbar",
  "update": "'Geometrie aktualisieren' deaktivieren",
  "fields": "Felder",
  "actions": "Aktionen",
  "editpageName": "Name",
  "editpageAlias": "Alias",
  "editpageVisible": "Sichtbar",
  "editpageEditable": "Editierbar",
  "noLayers": "Keine editierbaren Feature-Layer verfügbar",
  "configureFields": "Layer-Felder konfigurieren",
  "useFilterEdit": "Feature-Vorlagenfilter verwenden",
  "display": "Anzeige",
  "autoApplyEditWhenGeometryIsMoved": "Die Änderung automatisch beim Verschieben der Geometrie anwenden",
  "snappingTolerance": "Die Fangtoleranz in Pixel festlegen",
  "popupTolerance": "Die Toleranz des Pop-ups für Attributbearbeitung in Pixel festlegen",
  "stickyMoveTolerance": "Die Verschiebetoleranz in Pixel festlegen",
  "usingSaveButton": "Änderungen an den Attributen erst anwenden, nachdem auf die Schaltfläche \"Speichern\" geklickt wurde"
});