define({
  "tabs_section_Label": "Καρτέλες",
  "addTab": "Προσθήκη καρτέλας",
  "layerName": "Layer",
  "layerType": "Τύπος ανάλυσης",
  "layerLabel": "Ετικέτα",
  "actions": "Ενέργειες",
  "closest": "Πλησιέστερο στοιχείο",
  "proximity": "Εγγύτητα",
  "summary": "Σύνοψη",
  "select_lbl": "-- Επιλογή --",
  "general_setting_Label": "Γενικές ρυθμίσεις",
  "units_text_lbl": "Μονάδες απόστασης",
  "maximum_distance_lbl": "Μέγιστη απόσταση πλησιέστερου στοιχείου",
  "buffer_text_lbl": "Ετικέτα ζώνης",
  "buffer_lbl": "Απόσταση ζώνης",
  "buffer_max_lbl": "Μέγιστη απόσταση ζώνης",
  "buffer_min_lbl": "Ελάχιστη απόσταση ζώνης",
  "buffer_default_lbl": "Προεπιλεγμένη απόσταση ζώνης",
  "not_less_than_max": "Η απόσταση πρέπει να είναι μικρότερη από τη μέγιστη απόσταση ζώνης.",
  "not_between": "Η απόσταση πρέπει να είναι μεταξύ της ελάχιστης και της μέγιστης απόστασης ζώνης.",
  "not_more_than_min": "Η απόσταση πρέπει να είναι μεγαλύτερη από την ελάχιστη απόσταση ζώνης.",
  "not_valid_number": "Πρέπει να είναι έγκυρος αριθμός.",
  "invalid_value": "Η τιμή ${type} δεν είναι έγκυρη.",
  "routing_checkBox": "Ενεργοποίηση δρομολόγησης",
  "weather_Label": "Ρυθμίσεις καιρού",
  "weather_checkBox": "Ενεργοποίηση καιρού",
  "weather_map_layers": "Επιλογή θεματικών επιπέδων καιρού...",
  "selected_map_layers": " θεματικά επίπεδα καιρού έχουν επιλεγεί",
  "instruction_weather": "Εμφάνιση πληροφοριών για τον καιρό σε πλαίσιο.",
  "instruction_weather_layers": "Εμφάνιση πρόσθετων θεματικών επιπέδων καιρού.",
  "instruction_weather_metric": "Εμφάνιση τυπικών/μετρικών τιμών.",
  "selectLayers": "Επιλογή θεματικών επιπέδων καιρού.",
  "weather_removed_message": "Οι επιλογές καιρού δεν είναι πλέον διαθέσιμες για το συγκεκριμένο widget.",
  "currentlySelectedLayer": "Επιλογή από θεματικά επίπεδα χάρτη",
  "missingTabLabel": "Λείπει η ετικέτα από τουλάχιστον μία καρτέλα",
  "missingLayerInWebMap": "Δεν βρέθηκαν επιχειρησιακά επίπεδα.",
  "selectFields": "Επιλογή πεδίων",
  "addField": "Προσθήκη πεδίου",
  "sum": "Άθροισμα",
  "min": "Ελάχιστο",
  "max": "Μέγιστο",
  "avg": "Μέσος όρος",
  "count": "ΠΛΗΘΟΣ",
  "area": "ΠΕΡΙΟΧΗ",
  "length": "ΜΗΚΟΣ",
  "count_checkBox": "Εμφάνιση πλήθους στοιχείων",
  "area_checkBox": "Εμφάνιση σύνοψης περιοχής",
  "length_checkBox": "Εμφάνιση σύνοψης μήκους",
  "max_records": "Το μέγιστο όριο εξαντλήθηκε",
  "save_label": "Αποθήκευση επιλογών",
  "save_checkbox": "Ενεργοποίηση αποθήκευσης",
  "report_label": "Επιλογές αναφοράς",
  "report_checkbox": "Ενεργοποίηση αναφοράς",
  "csv_label": "Επιλογές CSV",
  "csv_checkbox": "Εξαγωγή όλων των πεδίων",
  "display_label": "Επιλογές εμφάνισης",
  "display_checkbox": "Εμφάνιση στοιχείων σύνοψης",
  "snapshot_label": "Επιλογές στιγμιότυπου",
  "snapshot_checkbox": "Ενεργοποίηση στιγμιότυπου",
  "must_select_template": "Επιλέξτε ένα από τα παρακάτω πρότυπα επεξεργασίας στις Επιλογές αποθήκευσης.",
  "count_label": "Ετικέτα πλήθους",
  "area_label": "Ετικέτα περιοχής",
  "length_label": "Ετικέτα μήκους",
  "invalid_string_width": "Το μήκος της τιμής είναι πολύ μεγάλο. ",
  "layer_type_not_supported": "Ο συγκεκριμένος τύπος θεματικού επιπέδου δεν υποστηρίζεται.",
  "groupedSummary": "Ομαδοποιημένες απαριθμήσεις",
  "groupByField": "Ομαδοποίηση ανά πεδίο",
  "labelType": "Προσάρτηση ετικέτας",
  "prefix": "Ως πρόθεμα",
  "suffix": "Ως επίθημα",
  "need_group_field": "Χρησιμοποιήστε την ενέργεια επεξεργασίας, για να ορίσετε Ομαδοποίηση ανά πεδίο.",
  "fieldTitle": "Πεδίο",
  "typeTitle": "Τύπος",
  "actionsTitle": "Ενέργειες",
  "save_point_checkbox": "Αποθήκευση σημείων",
  "save_line_checkbox": "Αποθήκευση γραμμών",
  "save_poly_checkbox": "Αποθήκευση πολυγώνων",
  "no_valid_popup_fields": "Δεν υπάρχουν έγκυρα πεδία στο αναδυόμενο παράθυρο. Χρησιμοποιήστε την ενέργεια επεξεργασίας, για να ορίσετε ένα πεδίο.",
  "no_valid_fields": "Δεν υπάρχουν έγκυρα πεδία. Χρησιμοποιήστε την ενέργεια επεξεργασίας, για να ορίσετε επιλογές εμφάνισης.",
  "incident_label": "Ετικέτα καρτέλας",
  "locate_incident_label": "Ετικέτα περιοχής ενδιαφέροντος",
  "incident": "Συμβάν",
  "locate_incident": "Εντοπισμός συμβάντος",
  "buffer_value": "Απόσταση ζώνης",
  "tab_options": "Ανάλυση",
  "export_options": "Έξοδος",
  "instruction_save": "Αποθήκευση τοποθεσίας σε μελλοντική υπηρεσία.",
  "instruction_snapshot": "Δημιουργία web χάρτη με βάση την τοποθεσία.",
  "instruction_report": "Δημιουργία έντυπης αναφοράς για την τοποθεσία.",
  "instruction_all_fields": "Εξαγωγή όλων των πεδίων με εξαγωγή CSV.",
  "data_label": "Ρυθμίσεις εξόδου δεδομένων",
  "layer_error": "Το θεματικό επίπεδο λείπει ή δεν είναι έγκυρο.",
  "visibility_checkBox": "Απενεργοποιήστε τη διαχείριση ορατότητας θεματικών πεδίων",
  "downloadTab": {
    "reportLegend": "Ρυθμίσεις αναφοράς",
    "textColorLabel": "Επιλογή χρώματος για τίτλους στηλών",
    "setButtonLabel": "Ορισμός",
    "printGPServiceLabel": "Print Service URL",
    "logoLabel": "Λογότυπο",
    "logoChooserHint": "Κάντε κλικ στο εικονίδιο της εικόνας για αλλαγή της εικόνας",
    "footnoteLabel": "Υποσημείωση"
  }
});