define({
  "enableUndoRedo": "Iespējot Atsaukt/Atatsaukt",
  "toolbarVisible": "Rīkjosla redzama",
  "toolbarOptions": "Rīkjoslas opcijas",
  "mergeVisible": "Apvienot",
  "cutVisible": "Izgriezt",
  "reshapeVisible": "Pārveidot",
  "back": "Atpakaļ",
  "label": "Slānis",
  "edit": "Rediģējams",
  "update": "Atspējot Atjaunināt ģeometriju",
  "fields": "Lauki",
  "actions": "Darbības",
  "editpageName": "Nosaukums",
  "editpageAlias": "Aizstājvārds",
  "editpageVisible": "Redzams",
  "editpageEditable": "Rediģējams",
  "noLayers": "Nav pieejams neviens rediģējams elementu slānis",
  "configureFields": "Konfigurēt slāņa laukus",
  "useFilterEdit": "Izmantot elementu šablona filtru",
  "display": "Parādīt",
  "autoApplyEditWhenGeometryIsMoved": "Pārvietojot ģeometriju, automātiski lietot rediģēšanu",
  "snappingTolerance": "Iestatīt pielipšanas toleranci pikseļos",
  "popupTolerance": "Iestatīt atribūtu rediģēšanas uznirstošā loga toleranci pikseļos",
  "stickyMoveTolerance": "Iestatīt līpošās pārvietošanas toleranci pikseļos",
  "usingSaveButton": "Nelietot labojumus atribūtiem, pirms tiek noklikšķināts uz pogas Saglabāt"
});