define({
  "chartTasks": "Opravilo grafikona",
  "addNew": "Dodaj novo",
  "addNewTip": "Dodaj novo opravilo grafikona",
  "name": "Ime",
  "set": "Nastavi",
  "setDataSource": "Nastavite vir podatkov",
  "generalSettingsTip": "Nastavi vir podatkov, naslov in opis za grafikone.",
  "chartModeSettingTip": "Izberi način za analizo in prikaz podatkov v obliki grafikonov.",
  "detailsSettingTip": "Nastavi videz grafikona z določanjem njegovega tipa, barve ter vrednosti, ki bodo prikazane:",
  "symbolSettingTip": "Nastavi prikaz karte za podatke na grafikonu.",
  "addFilterTip": "Dodaj filter tem podatkom",
  "dataSource": "Vir podatkov",
  "noResults": "Geoobjekta ni mogoče najti.",
  "chartTitle": "Naslov grafikona",
  "description": "Opis",
  "chartingMode": "Prikaz grafikona",
  "featureOption": "Prikaži vrednosti po geoobjektih",
  "categoryOption": "Prikaži vrednosti po kategorijah",
  "countOption": "Prikaži število geoobjektov po kategorijah",
  "fieldOption": "Prikaži vrednosti atributov kot grafikon",
  "category": "Kategorija",
  "axisLabel": "Napis kategorije",
  "categoryField": "Polje kategorije",
  "operation": "Operacija",
  "originalOption": "Uporabi izvirne vrednosti",
  "sumOption": "Vsota",
  "averageOption": "Povprečje",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "valueFields": "Vrednosti polj",
  "moveUp": "Premakni gor",
  "moveDown": "Premakni dol",
  "sortOrder": "Razvrsti vrstni red grafikonov po napisih kategorije",
  "ascending": "Naraščajoče",
  "descending": "Padajoče",
  "chartType": "Tip grafikona",
  "column": "Stolpčni grafikon",
  "bar": "Palični grafikon",
  "line": "Linijski grafikon",
  "pie": "Tortni grafikon",
  "chartColor": "Barva grafikona",
  "showDataLabels": "Pokaži napise podatkov",
  "setSymbol": "Simbol izbire",
  "setHighLightColor": "Basrva osvetlitve",
  "settings": "Nastavitve",
  "mapInterationOptions": "Možnosti interakcije s karto",
  "preview": "Predogled",
  "ok": "V redu",
  "cancel": "Prekliči",
  "close": "Zapri",
  "setFilterTip": "Pravilno nastavite filter. ",
  "setChartTitleTip": "Določite naslov grafikona.",
  "setChartTypeTip": "Izberite vsaj en tip grafikona.",
  "setDataFieldTip": "Izberite vsaj eno polje vrednosti.",
  "setOutputFieldTip": "Nastavite izhodna polja.",
  "count": "Števec",
  "label": "Napis",
  "horizontalAxis": "Horizontalna os",
  "verticalAxis": "Vertikalna os",
  "dataLabels": "Napisi podatkov",
  "color": "Barva",
  "colorful": "Pisano",
  "monochromatic": "Enobarvno",
  "noTaskTip": "Za dodajanje opravila grafikona kliknite Dodaj novo",
  "info": "Informacije",
  "charts": "Grafikoni",
  "options": "Možnosti",
  "taskName": "Ime naloge",
  "summary": "Povzetek",
  "resultDescription": "Opis rezultata",
  "spatialFilterTip": "Izberite prostorske filtre, uporabljene v pripomočku za omejitev rezultatov.",
  "defaultOption": "Privzeto",
  "useCurrentExtentTip": "Delno ali v celoti znotraj trenutnega obsega karte",
  "useDrawGraphicTip": "Delno ali v celoti znotraj oblike, narisane na karti",
  "useFeaturesTip": "Glede na njihove lokacije, relativno na geoobjekte v drugem sloju",
  "noSpatialLimitTip": "Rezultatov ne omejuj prostorsko",
  "drawingTools": "Orodja za risanje",
  "bufferSettings": "Nastavitve obrisa",
  "defaultDistance": "Privzeta razdalja",
  "bufferDistance": "Razdalja obrisa",
  "defaultUnit": "Privzeta enota",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "availableSpatialRelationships": "Razpoložljivi prostorski odnosi",
  "setSpatialRelationships": "Nastavite prostorski odnos",
  "availability": "Razpoložljivost",
  "relationship": "Relacija",
  "actions": "Dejanja",
  "intersect": "seka",
  "contain": "vsebuje",
  "areContainedIn": "so vsebovani v",
  "cross": "križ",
  "envelopeIntersect": "seka prostorski okvir",
  "overlap": "prekriva",
  "areOverlapped": "so prekriti",
  "touche": "se dotika",
  "within": "znotraj",
  "areWithin": "so znotraj",
  "indexIntersect": "presek indeksa"
});