define({
  "settings": "Pengaturan",
  "titleSettings": "Pengaturan teks",
  "imageSettings": "Pengaturan gambar",
  "backgroundColor": "Warna latar belakang",
  "alignment": "Perataan",
  "textSize": "Ukuran teks",
  "textColor": "Warna teks",
  "dataSource": "Sumber data",
  "chartSettings": "Pengaturan grafik",
  "data": "Data",
  "dataLabels": "Label data",
  "displayMode": "Mode tampilan",
  "featureOption": "Tampilkan fitur nilai menurut fitur",
  "categoryOption": "Tampilkan nilai menurut kategori",
  "countOption": "Tampilkan jumlah fitur menurut kategori",
  "fieldOption": "Tampilkan nilai atribut sebagai grafik",
  "categoryField": "Kolom kategori",
  "labelField": "Kolom label",
  "valueFields": "Kolom nilai",
  "operation": "Operasi",
  "sumOption": "Jumlah",
  "averageOption": "Rata-rata",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Format data",
  "decimalPlaces": "Tempat desimal",
  "prefix": "Awalan",
  "suffix": "Akhiran",
  "dataType": "Jenis data",
  "featureCount": "Jumlah fitur",
  "fieldStatistics": "Statistik kolom",
  "display": "Tampilan",
  "chartColor": "Warna grafik",
  "horizontalAxis": "Sumbu horizontal",
  "verticalAxis": "Sumbu vertikal",
  "legend": "Legenda",
  "position": "Posisi",
  "top": "Atas",
  "bottom": "Bawah",
  "useDataSourceSelection": "Gunakan pilihan",
  "dataSourceFilterByExtent": "Filter menurut jangkauan",
  "changeTemplate": "Ubah template",
  "numberSettings": "Pengaturan Angka",
  "gaugeSettings": "Pengaturan gauge",
  "indicators": "Indikator",
  "ifValue": "Jika nilai",
  "and": "dan",
  "numberOperatorIsLessThan": "kurang dari",
  "numberOperatorIsGreaterThan": "lebih besar dari",
  "numberOperatorIsBetween": "di antara",
  "numberOperatorIsEqual": "sama dengan",
  "numberOperatorIsNotEqual": "tidak sama dengan",
  "then": "Kemudian",
  "ratio": "Rasio",
  "trueValue": "Nilai asli",
  "changeValueColor": "ubah nilai warna menjadi",
  "changeGaugeColor": "ubah warna gauge menjadi",
  "setIndicatorIcon": "atur ikon indikator sebagai",
  "icons": "Ikon",
  "style": "Gaya",
  "placement": "Penempatan",
  "left": "Kiri",
  "replace": "Menggantikan",
  "right": "Kanan",
  "color": "Warna",
  "categoryExists": "Kategori sudah ada!",
  "comboxHint": "Ketik atau pilih satu",
  "comboxDisableInputHint": "Pilih satu",
  "sortBy": "Urutkan berdasarkan",
  "labelAxis": "Label",
  "valueAxis": "Nilai",
  "minPeriod": "Periode minimum",
  "automatic": "Otomatis",
  "periodsWithOutRecords": "Periode tanpa catatan",
  "nullValue": "Nilai null",
  "calculatedAsZero": "Dihitung sebagai kosong",
  "ignored": "Diabaikan",
  "maxCategories": "Kategori maksimum",
  "useLayerSymbology": "Gunakan simbologi layer",
  "hollowsize": "Ukuran rongga",
  "splitField": "Pisahkan kolom",
  "parsingperiodTip": "Gagal menghitung. Terlalu banyak interval waktu karena periode pemilahan yang singkat.",
  "manyCategoryTip": "Gagal menampilkan diagram. Terlalu banyak kategori.",
  "setColor": "Atur warna",
  "setTheColorOf": "Kemudian atur warna",
  "setTheColorAs": "Kemudian atur warna sebagai",
  "ifStr": "Jika",
  "as": "sebagai",
  "is": "adalah",
  "isNot": "bukan",
  "barCluster": "gugus batang",
  "individualBar": "batang individual",
  "allOthers": "Lainnya",
  "category": "Kategori",
  "indicatorSum": "JUMLAH",
  "indicatorAve": "RATA",
  "indicatorMax": "MAKS",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Harap atur indikator dengan benar.",
  "dataRange": "Rentang data",
  "targetValue": "Nilai target",
  "currentValue": "Nilai saat ini",
  "gaugeColor": "Warna gauge",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Nilai tampilan di",
  "noData": "Tidak ada data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Peringatan",
  "noSettingWaring1": "Klik sebuah elemen untuk mengatur propertinya.",
  "noSettingWaring2": "Seret untuk mengubah ukuran atau menyusun ulang elemen.",
  "donNotShowAgain": "Jangan perlihatkan lagi",
  "changeTemplateWarning": "Ini akan menghapus semua pengaturan Anda dan membuka template kosong baru.",
  "requiredFieldWarning": "Nilai ini diperlukan:",
  "dataSourceNotSet": "Harap atur sumber data.",
  "addIndicatorTip": "Tambahkan sebuah indikator",
  "chooseTemplatePopupTitle": "Pilih template",
  "filterExtentTipWithaTag": "Anda dapat menonaktifkan filter menurut <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Sumber data ekstra</a> di bawah Tab Atribut.",
  "filterExtentTip": "Anda dapat menonaktifkan filter menurut Sumber data ekstra di bawah Tab Atribut.",
  "customColorByCategory": "Kustomisasi warna menurut kategori",
  "randomColor": "Warna Acak",
  "valueString": "Nilai",
  "fieldString": "Kolom",
  "includeThresholdValue": "Sertakan nilai ambang batas",
  "percentage": "Persentase",
  "colorSchema": "Skema warna",
  "addCategory": "Tambah kategori",
  "clickToEdit": "Klik untuk mengedit",
  "nullText": "Nol",
  "others": "Lainnya",
  "stringsInTemplate": {
    "name_number": "Nomor",
    "name_gauge": "Gauge",
    "name_vertical_gauge": "Gauge Vertikal",
    "name_horizontal_gauge": "Gauge Horizontal",
    "name_pie": "Pai",
    "name_donut": "Donat",
    "name_bar": "Batang",
    "name_stacked_bar": "Batang Bertumpuk",
    "name_percentage_stacked_bar": "Batang Bertumpuk Persentase",
    "name_column": "Kolom",
    "name_stacked_column": "Kolom bertumpuk",
    "name_percentage_stacked_column": "Kolom Bertumpuk Persentase",
    "name_line": "Garis",
    "name_area": "Area",
    "name_stacked_area": "Area Bertumpuk",
    "name_percentage_stacked_area": "Area Bertumpuk Persentase",
    "titleOfTheInfographic": "JUDUL INFOGRAFIS",
    "description": "Deskripsi: informasi tambahan tentang infografis ini."
  }
});