define({
  "queries": "שאילתות",
  "addNew": "הוסף חדש",
  "newQuery": "שאילתא חדשה",
  "queryLayer": "שכבת שאילתא",
  "setSource": "הגדר",
  "setDataSource": "הגדר מקור נתונים",
  "name": "שם",
  "querySource": "מקור הנתונים",
  "queryName": "שם משימה",
  "queryDefinition": "הגדרת סינון",
  "resultsSetting": "הגדרת תוצאות",
  "symbolSetting": "הגדרת סמל",
  "resultSettingTip": "הגדר אילו תוצאות פלט להציג ואיך להציג אותן.",
  "resultItemTitle": "הכותרת של כל תוצאה",
  "resultItemContent": "יוצגו מאפייני שדות אלה",
  "fieldsSetTip": "סמן את השדות שאתה רוצה להציג. בחר שדה כדי לעדכן את הכינוי, הסדר והתבנית שלו.",
  "addField": "הוסף שדה",
  "visibility": "ניראות",
  "alias": "כינוי",
  "specialType": "סוג מיוחד",
  "actions": "פעולות",
  "none": "ללא",
  "link": "קישור",
  "image": "תמונה",
  "noField": "אין שדה",
  "operationalLayerTip": "הוסף תוצאה כשכבה תפעולית",
  "setLayerSymbolTip": "הגדר את הסמל לתוצאת השאילתה: ",
  "setSelectedSymbolTip": "הגדר סמל לישות הנבחרת.",
  "notUseFilter": "אל תשתמש בסינון.",
  "setSourceTip": "הגדר בבקשה מקור שאילתה.",
  "setFilterTip": "הגדר בבקשה סינון תקין.",
  "ok": "אישור",
  "cancel": "ביטול",
  "noFilterTip": "מבלי להגדיר ביטוי לסינון, שאילתה זו תציג את כל הישויות במקור הנתונים שצוין.",
  "relationships": "קישורים",
  "addRelationshipLayer": "הוסף קישור חדש",
  "relatedTo": "קשור אל",
  "selectOption": "בחר אפשרות...",
  "resultItemSorting": "מיון פריטי תוצאה",
  "field": "שדה",
  "sortingOrder": "סדר",
  "configureFieldsTip": "הגדר את השדות שישמשו למיון תוצאות השאילתא.",
  "setSortingFields": "הגדר שדות מיון",
  "ascending": "עולה",
  "descending": "יורד",
  "sortBy": "מיון על ידי",
  "thenBy": "ולאחר מכן לפי",
  "addTask": "הוסף משימה",
  "noTasksTip": "לא הוגדרו שאילתות. לחץ על \"${newQuery}\" להוספת שאילתא חדשה.",
  "infoText": "מידע",
  "filters": "סינונים",
  "results": "תוצאות",
  "optionsText": "אפשרויות",
  "summaryText": "סיכום",
  "attributeFilter": "פילטר מאפיינים",
  "attributeFilterTip": "הגדר ביטויי מאפיינים לשימוש בווידג'ט כדי לסנן את שכבת השאילתא.",
  "defineWhereClause": "הגדר משפט WHERE עבור השאילתא.",
  "noExpressionDefinedTip": "לא הוגדרו ביטויים. כל הרשומות יוחזרו.",
  "setExpressions": "הגדר ביטויים",
  "spatialFilter": "פילטרים מרחביים",
  "spatialFilterTip": "בחר אילו פילטרים מרחביים יהיו זמינים למשתמשי הקצה.",
  "defaultOption": "ברירת מחדל",
  "useCurrentExtentTip": "החזר רק ישויות בתוך תיחום המפה הנוכחי",
  "useDrawGraphicTip": "החזר רק ישויות שמצטלבות עם הצורה שצוירה על המפה",
  "useFeaturesTip": "החזר רק ישויות בעלות קישור מרחבי עם ישויות בשכבה אחרת",
  "noSpatialLimitTip": "החזר ישויות בתוך התיחום המלא של המפה",
  "drawingTools": "בחר כלי שרטוט",
  "bufferSettings": "הפעל את אפשרות החיץ",
  "defaultDistance": "מרחק ברירת מחדל",
  "bufferDistance": "מרחק חיץ",
  "defaultUnit": "יחידת ברירת מחדל",
  "miles": "מיילים",
  "kilometers": "קילומטרים",
  "feet": "רגל",
  "meters": "מטרים",
  "yards": "יארד",
  "nauticalMiles": "מיילים ימיים",
  "availableSpatialRelationships": "בחר כללים לקישורים מרחביים",
  "setSpatialRelationships": "הגדר קישורים מרחביים",
  "availability": "זמינות",
  "relationship": "יחס",
  "label": "תווית",
  "intersect": "חותך",
  "contain": "מכיל",
  "areContainedIn": "כלולים בתוך",
  "cross": "חוצה",
  "envelopeIntersect": "חותך במעטפת",
  "overlap": "חפיפה",
  "areOverlapped": "חופפים",
  "touch": "נוגע",
  "within": "בתוך",
  "areWithin": "כלולים",
  "indexIntersect": "חותך באינדקס",
  "itemTitle": "כותרת פריט",
  "displayFields": "הצג שדות",
  "sortingFields": "מיין את פריטי התוצאות",
  "setDisplayFields": "קבע שדות תצוגה",
  "symbol": "סמל",
  "setSymbol": "השתמש בסמל מותאם אישית",
  "changeSymbolAtRuntime": "אפשר לשנות סמלים בזמן ריצה",
  "serviceSymbolTip": "השתמש בסמלים המוגדרים על-ידי השכבה",
  "exportTip": "אפשר לייצא תוצאות",
  "keepResultsTip": "שמור תוצאות על המפה לאחר סגירת הווידג'ט",
  "queryRelatedRecords": "רשומות המקושרות לשאילתא",
  "createLayerForTaskTip": "ציין באיזה אופן משימת שאילתא יוצרת שכבות",
  "oneLayerForTaskTip": "דרוס את השכבה בכל הפעלה של השאילתא",
  "multipleLayerForTaskTip": "צור שכבה חדשה בכל הפעלה של השאילתא",
  "makeDefault": "הפוך לברירת מחדל",
  "icon": "סמל",
  "newTask": "משימה חדשה",
  "addTaskTip": "הוסף לווידג'ט שאילתא אחת או יותר והגדר פרמטרים לכל שאילתא.",
  "webMapPopupTip": "השתמש בתצורת החלוניות הקופצות של השכבה ב-web map",
  "customPopupTip": "הגדר תוכן מותאם אישית",
  "showResultsSetActions": "הצג פעולות עבור סט התוצאות",
  "zoomTo": "התמקד אל",
  "openAttributeTable": "הצג בטבלת מאפיינים",
  "content": "תוכן",
  "displaySQLTip": "הצג ביטוי SQL למשתמשי קצה",
  "useLayerDefaultSymbol": "השתמש בסימול ברירת המחדל של השכבה",
  "setCustomIcon": "הגדר צלמית מותאמת",
  "layerDefaultSymbolTip": "השתמש בסימול ברירת המחדל של השכבה",
  "uploadImage": "טען תמונה",
  "attributeCriteira": "קריטריוני מאפיין",
  "specifyFilterAtRuntimeTip": "משתמשים יצטרכו לציין פרמטרים עבור ביטוי זה.",
  "value": "ערך",
  "hideLayersTip": "כבה שכבות של תוצאות שאילתה בעת סגירת הווידג'ט.",
  "tabLabels": "תוויות של כרטיסיות",
  "tasks": "משימות",
  "queryCriteira": "קריטריונים של שאילתא",
  "allowCustomQuery": "אפשר יצירה של שאילתה מותאמת אישית"
});