define({
  "chartSettingLabel": "चार्ट सेटिंग",
  "addNewLabel": "नया जोड़ें",
  "generalSettingLabel": "सामान्य सेटिंग्स",
  "searchSourceSettingLabel": "स्रोत सेटिंग खोजें",
  "layerChooser": {
    "title": "चार्ट करने के लिए लेयर का चयन करें",
    "selectPolygonLayerLabel": "लेयर का चयन करें",
    "selectPolygonLayerHintText": "सुझाव: यदि एक से अधिक चार्ट को कॉन्फ़िगरिंग कर रहे हैं, तो लेयर एक ही geometry प्रकार की होनी चाहिए",
    "selectRelatedTableLayerLabel": "लेयर से संबंधित तालिका का चयन करें",
    "selectRelatedTableLayerHintText": "सुझाव: केवल संख्यात्मक फ़ील्ड वाले तालिका प्रदर्शित करें",
    "errorInSelectingPolygonLayer": "कृपया एक लेयर का चयन करें है जिस पर एक संबंधित बिंदु लेयर है।",
    "errorInSelectingRelatedLayer": "कृपया लेयर करने के लिए एक वैध संबंधित तालिका/लेयर का चयन करें।",
    "polygonLayerNotHavingRelationships": "चयनित लेयर पर कोई भी संबंधित तालिका/लेयर नहीं है।"
  },
  "ChartSetting": {
    "sectionTitle": "अनुभाग का शीर्षक",
    "sectionTitleHintText": "सुझाव: अनुभाग हेडर शीर्षक में प्रदर्शित किया गया है",
    "chartTitle": "चार्ट शीर्षक",
    "chartTitleHintText": "सुझाव: चार्ट के शीर्ष पर केन्द्रित प्रदर्शित किया गया है",
    "chartDescription": "विवरण",
    "chartDescriptionHintText": "सुझाव: चार्ट के नीचे प्रदर्शित किया गया है",
    "chartType": "चार्ट प्रकार",
    "barChart": "बार चार्ट",
    "pieChart": "पाई चार्ट",
    "polarChart": "पोलर चार्ट",
    "dataSeriesField": "डेटा श्रृंखला फ़ील्ड",
    "labelField": "लेबल फ़ील्ड",
    "chartColor": "चार्ट रंग",
    "singleColor": "एकल रंग",
    "colorByTheme": "थीम से रंग",
    "colorByFieldValue": "फ़ील्ड मान द्वारा रंग",
    "xAxisTitle": "X-अक्ष शीर्षक",
    "xAxisHintText": "सुझाव: X-अक्ष शीर्षक",
    "yAxisTitle": "Y-अक्ष शीर्षक",
    "yAxisHintText": "सुझाव: Y-अक्ष शीर्षक",
    "fieldColorLabel": "लेबल",
    "fieldColorColor": "रंग",
    "defaultFieldSelectLabel": "चुनें",
    "errMsgFieldValuesNotFound": "चयनित फ़ील्ड के लिए मानों को खोजने में असमर्थ",
    "errMsgSectionTitle": "अनुभाग शीर्षक दर्ज करें",
    "errMsgFieldByValue": "कृपया फ़ील्ड मान का चयन करें",
    "settingTabTitle": "सेटिंग",
    "layoutTabTitle": "रूपरेखा",
    "polarChartSelectFieldsHintText": "सुझाव: पोलर चार्ट उत्पन्न करने के लिए फ़ील्ड का चयन करें",
    "visibilityText": "दृश्यता",
    "fieldNameText": "फ़ील्ड का नाम",
    "aliasNameText": "उपनाम",
    "errMsgPolarFieldsRequired": "पोलर चार्ट उत्पन्न करने के लिए तीन या अधिक फ़ील्ड का चयन करें",
    "polarChartPolygonFillLabel": "बहुभुज भरें",
    "polarChartPolygonFillHintText": "सुझाव: पोलर ग्राफ में बहुभुज भरने को दिखाने के लिए चेकबॉक्स का चयन करें",
    "viewLayoutLabel": "रूपरेखा",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "रेगिस्तान",
      "themeDistinctive": "विशेष",
      "themeDollar": "डॉलर",
      "themeGrasshopper": "टिड्डी",
      "themeGrasslands": "घास के मैदान",
      "themeGreySkies": "भूरा आसमान",
      "themeHarmony": "सामंजस्य",
      "themeIndigoNation": "इंडिगो नेशन",
      "themeIreland": "आयरलैंड",
      "themeMiamiNice": "मिआमिनाईस",
      "themeMinty": "मिन्टी",
      "themePurpleRain": "बैंगनी बारिश",
      "themeRoyalPurples": "रॉयल बैंगनी",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "पानी का किनारा",
      "themeWetlandText": "वेटलैंड",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "सामान्य सेटिंग",
    "locationSymbolLabel": "ग्राफिक स्थान प्रतीक",
    "locationSymbolHintText": "सुझाव: पते के लिए प्रतीक को प्रदर्शित करने और स्थान के लिए क्लिक करने के लिए इस्तेमाल किया जाता है",
    "refreshIntervalLabel": "अंतराल को ताज़ा करें",
    "refreshIntervalHintText": "सुझाव: इस अंतराल पर आधारित चार्ट ताज़ा करने के लिए इस्तेमाल किया जाता है। 1से  1440 मिनट के बीच कोई मान निर्दिष्ट करें",
    "errMsgRefreshInterval": "कृपया 0 से 1440 मिनट के बीच ताज़ा अंतराल निर्दिष्ट करें",
    "symbolPickerPreviewText": "पूर्वावलोकन करें:",
    "showToolToSelectLabel": "स्थान बटन सेट करें",
    "showToolToSelectHintText": "सुझाव: जब मानचित्र पर क्लिक किया जाता है तब हमेशा स्थान की स्थापना के बजाय मानचित्र पर स्थान निर्धारित करने के लिए एक बटन प्रदान करता है"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "स्रोत सेटिंग खोजें",
    "searchSourceSettingTitle": "स्रोत सेटिंग खोजें",
    "searchSourceSettingTitleHintText": "Geocode सर्विस या फीचर लेयरों को खोज स्रोतों के रूप में जोड़ें और कॉन्फ़िगर करें। ये निर्दिष्ट स्रोत निर्धारित करते हैं कि खोज बॉक्स के भीतर क्या खोज योग्य है",
    "addSearchSourceLabel": "खोज स्रोत जोड़ें",
    "featureLayerLabel": "फ़ीचर लेयर",
    "geocoderLabel": "Geocoding",
    "nameTitle": "नाम",
    "generalSettingLabel": "सामान्य सेटिंग",
    "allPlaceholderLabel": "सभी खोज के लिए प्लेसहोल्डर पाठ:",
    "allPlaceholderHintText": "सुझाव: सभी लेयरों और Geocoder की खोज करते समय प्लेसहोल्डर के रूप में दिखाए जाने के लिए टेक्स्ट दर्ज किया जा सकता है",
    "generalSettingCheckboxLabel": "पाई गई फीचर या स्थान के लिए पॉप-अप दिखाएं",
    "countryCode": "देश या क्षेत्र कोड",
    "countryCodeEg": "जैसे ",
    "countryCodeHint": "इस मान को खाली छोड़ने से सभी देशों और क्षेत्रों की खोज होगी",
    "questionMark": "?",
    "searchInCurrentMapExtent": "केवल वर्तमान मानचित्र सीमा में खोज करता है",
    "zoomScale": "स्केल को ज़ूम करें",
    "locatorUrl": "जियोकोडर URL",
    "locatorName": "जियोकोडर का नाम",
    "locatorExample": "उदाहरण",
    "locatorWarning": "Geocoding सेवा का यह संस्करण समर्थित नहीं है। विजेट Geocoding सेवा 10.0 और ऊपर को समर्थन करता है।",
    "locatorTips": "सुझाव उपलब्ध नहीं हैं क्योंकि Geocoding सेवा सुझाव क्षमता का का समर्थन नहीं करता है।",
    "layerSource": "लेयर स्रोत",
    "setLayerSource": "लेयर स्रोत को सेट करें",
    "setGeocoderURL": "Geocoder का URL सेट करें",
    "searchLayerTips": "सुझाव उपलब्ध नहीं हैं क्योंकि सुविधा सेवा पृष्ठ अंकन क्षमता का समर्थन नहीं करती है।",
    "placeholder": "प्लेसहोल्डर पाठ",
    "searchFields": "फ़ील्ड खोजें",
    "displayField": "प्रदर्शन फील्ड",
    "exactMatch": "सटीक मिलान",
    "maxSuggestions": "अधिकतम सुझाव",
    "maxResults": "अधिकतम परिणाम",
    "enableLocalSearch": "स्थानीय खोज को सक्षम करें",
    "minScale": "न्यूनतम स्केल",
    "minScaleHint": "जब मानचित्र स्केल इस स्केल से बड़ा होता है, तो स्थानीय खोज को लागू किया जाएगा",
    "radius": "त्रिज्या",
    "radiusHint": "मौजूदा मानचित्र केंद्र के चारों ओर एक क्षेत्रफल की त्रिज्या निर्दिष्ट करें जिसे Geocoding उम्मीदवारों के रैंक को बढ़ावा देने के लिए प्रयोग किया जाता है ताकि स्थान के निकटतम उम्मीदवार पहले प्राप्त हों",
    "meters": "मीटर",
    "setSearchFields": "खोज फ़ील्ड को सेट करें",
    "set": "सेट करें",
    "fieldName": "नाम",
    "invalidUrlTip": "URL ${URL} अवैध या दुर्गम है।"
  }
});