define({
  "chartSettingLabel": "チャート設定",
  "addNewLabel": "新規追加",
  "generalSettingLabel": "一般設定",
  "searchSourceSettingLabel": "検索ソースの設定",
  "layerChooser": {
    "title": "チャートを作成するレイヤーの選択",
    "selectPolygonLayerLabel": "レイヤーの選択",
    "selectPolygonLayerHintText": "ヒント: 複数のチャートを構成する場合、各レイヤーのジオメトリ タイプが同じである必要があります",
    "selectRelatedTableLayerLabel": "レイヤーに関連するテーブルの選択",
    "selectRelatedTableLayerHintText": "ヒント: 数値フィールドを含んでいるテーブルのみが表示されます",
    "errorInSelectingPolygonLayer": "関連するポイント レイヤーがあるレイヤーを選択してください。",
    "errorInSelectingRelatedLayer": "レイヤーに関連する有効なテーブル/レイヤーを選択してください。",
    "polygonLayerNotHavingRelationships": "選択したレイヤーには、関連するテーブル/レイヤーがありません。"
  },
  "ChartSetting": {
    "sectionTitle": "セクション タイトル",
    "sectionTitleHintText": "ヒント: セクションのヘッダー タイトルに表示されます",
    "chartTitle": "チャートのタイトル",
    "chartTitleHintText": "ヒント: チャートの上部の中央に表示されます",
    "chartDescription": "説明",
    "chartDescriptionHintText": "ヒント: チャートの下に表示されます",
    "chartType": "チャート タイプ",
    "barChart": "バー チャート",
    "pieChart": "パイ チャート",
    "polarChart": "極座標チャート",
    "dataSeriesField": "データ シリーズ フィールド",
    "labelField": "ラベル フィールド",
    "chartColor": "チャートの色",
    "singleColor": "単一色",
    "colorByTheme": "テーマ別の色",
    "colorByFieldValue": "フィールド値別の色",
    "xAxisTitle": "X 軸のタイトル",
    "xAxisHintText": "ヒント: X 軸のタイトル",
    "yAxisTitle": "Y 軸のタイトル",
    "yAxisHintText": "ヒント: Y 軸のタイトル",
    "fieldColorLabel": "ラベル",
    "fieldColorColor": "色",
    "defaultFieldSelectLabel": "選択",
    "errMsgFieldValuesNotFound": "選択したフィールドの値を検索できません",
    "errMsgSectionTitle": "セクション タイトルを入力してください",
    "errMsgFieldByValue": "フィールド値を選択してください",
    "settingTabTitle": "設定",
    "layoutTabTitle": "レイアウト",
    "polarChartSelectFieldsHintText": "ヒント: 極座標チャートを生成するためのフィールドを選択します",
    "visibilityText": "可視性",
    "fieldNameText": "フィールド名",
    "aliasNameText": "エイリアス",
    "errMsgPolarFieldsRequired": "極座標チャートを生成するには、3 つ以上のフィールドを選択してください",
    "polarChartPolygonFillLabel": "塗りつぶしポリゴン",
    "polarChartPolygonFillHintText": "ヒント: チェックボックスをオンにすると、塗りつぶしポリゴンが極座標グラフに表示されます。",
    "viewLayoutLabel": "レイアウト",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "一般設定",
    "locationSymbolLabel": "グラフィックス位置シンボル",
    "locationSymbolHintText": "ヒント: 住所のシンボルの表示および位置のクリックに使用されます",
    "refreshIntervalLabel": "更新間隔",
    "refreshIntervalHintText": "ヒント: この間隔に基づいてチャートが更新されます。1 ～ 1440 分の範囲内の値を指定します。",
    "errMsgRefreshInterval": "0 ～ 1440 分の範囲内の更新間隔を指定してください",
    "symbolPickerPreviewText": "プレビュー:",
    "showToolToSelectLabel": "[場所の設定] ボタン",
    "showToolToSelectHintText": "ヒント: 常にマップをクリックして場所を設定する代わりに、場所を設定するボタンをマップ上に提供します"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "検索ソースの設定",
    "searchSourceSettingTitle": "検索ソースの設定",
    "searchSourceSettingTitleHintText": "ジオコード サービスまたはフィーチャ レイヤーを検索ソースとして追加および構成します。指定されたこれらのソースは、検索ボックス内で検索可能な対象を決定します。",
    "addSearchSourceLabel": "検索ソースの追加",
    "featureLayerLabel": "フィーチャ レイヤー",
    "geocoderLabel": "ジオコーダー",
    "nameTitle": "名前順",
    "generalSettingLabel": "一般設定",
    "allPlaceholderLabel": "標準のプレースホルダー テキスト:",
    "allPlaceholderHintText": "ヒント: すべてのレイヤーとジオコーダーを検索するときに、プレースホルダーとして表示されるテキストを入力します",
    "generalSettingCheckboxLabel": "検出されたフィーチャまたは位置のポップアップを表示",
    "countryCode": "国コードまたは地域コード",
    "countryCodeEg": "例: ",
    "countryCodeHint": "この値を空白のままにすると、すべての国および地域を検索します",
    "questionMark": "？",
    "searchInCurrentMapExtent": "現在のマップ範囲内のみを検索",
    "zoomScale": "ズーム縮尺",
    "locatorUrl": "ジオコーダーの URL",
    "locatorName": "ジオコーダー名",
    "locatorExample": "例",
    "locatorWarning": "このジオコーディング サービスのバージョンはサポートされていません。ウィジェットは、10.0 以上のジオコーディング サービスをサポートしています。",
    "locatorTips": "ジオコーディング サービスがヒント機能をサポートしていないため、ヒントは使用できません。",
    "layerSource": "レイヤー ソース",
    "setLayerSource": "レイヤー ソースの設定",
    "setGeocoderURL": "ジオコーダーの URL の設定",
    "searchLayerTips": "フィーチャ サービスがページネーション機能をサポートしていないため、ヒントは使用できません。",
    "placeholder": "プレースホルダー テキスト",
    "searchFields": "検索フィールド",
    "displayField": "表示フィールド",
    "exactMatch": "完全一致",
    "maxSuggestions": "最大候補数",
    "maxResults": "結果の最大数",
    "enableLocalSearch": "ローカル検索の有効化",
    "minScale": "最小縮尺",
    "minScaleHint": "マップ縮尺がこの縮尺より大きい場合は、ローカル検索が適用されます。",
    "radius": "半径",
    "radiusHint": "現在のマップの中心を起点としたエリアの半径を指定します。この半径は、検索位置に最も近い候補が最初に返されるようにジオコーディング候補のランクを高めるために使用されます。",
    "meters": "メートル",
    "setSearchFields": "検索フィールドの設定",
    "set": "設定",
    "fieldName": "名前",
    "invalidUrlTip": "URL ${URL} は無効であるか、アクセスできません。"
  }
});