define({
  "chartSettingLabel": "Thiết lập biểu đồ",
  "addNewLabel": "Thêm mới",
  "generalSettingLabel": "Thiết lập tổng quan",
  "searchSourceSettingLabel": "Thiết lập nguồn tìm kiếm",
  "layerChooser": {
    "title": "Chọn lớp cho biểu đồ",
    "selectPolygonLayerLabel": "Chọn lớp",
    "selectPolygonLayerHintText": "Gợi ý: Nếu cấu hình nhiều biểu đồ thì các lớp phải thuộc cùng loại hình học",
    "selectRelatedTableLayerLabel": "Chọn bảng liên quan đến lớp",
    "selectRelatedTableLayerHintText": "Mẹo: Chỉ các bảng có trường số được hiển thị",
    "errorInSelectingPolygonLayer": "Vui lòng chọn lớp có lớp điểm liên quan.",
    "errorInSelectingRelatedLayer": "Vui lòng chọn bảng/lớp liên quan đến lớp.",
    "polygonLayerNotHavingRelationships": "Lớp được chọn không có bất kỳ bảng/lớp liên quan nào."
  },
  "ChartSetting": {
    "sectionTitle": "Tiêu đề phần",
    "sectionTitleHintText": "Mẹo: Được hiển thị trong phần tiêu đề đầu trang",
    "chartTitle": "Tiêu đề biểu đồ",
    "chartTitleHintText": "Mẹo: Được hiển thị ở giữa trên cùng của biểu đồ",
    "chartDescription": "Mô tả",
    "chartDescriptionHintText": "Mẹo: Được hiển thị bên dưới biểu đồ",
    "chartType": "Loại biểu đồ",
    "barChart": "Biểu đồ thanh",
    "pieChart": "Biểu đồ hình tròn",
    "polarChart": "Biểu đồ cực",
    "dataSeriesField": "Trường dãy dữ liệu",
    "labelField": "Trường nhãn",
    "chartColor": "Màu sắc biểu đồ",
    "singleColor": "Một màu",
    "colorByTheme": "Màu sắc theo chủ đề",
    "colorByFieldValue": "Màu sắc theo giá trị trường",
    "xAxisTitle": "Tiêu đề trục X",
    "xAxisHintText": "Mẹo: Tiêu đề trục X",
    "yAxisTitle": "Tiêu đề trục Y",
    "yAxisHintText": "Mẹo: Tiêu đề trục Y",
    "fieldColorLabel": "Nhãn",
    "fieldColorColor": "Màu sắc",
    "defaultFieldSelectLabel": "Chọn",
    "errMsgFieldValuesNotFound": "Không tìm thấy giá trị cho trường được chọn",
    "errMsgSectionTitle": "Vui lòng nhập tiêu đề phần",
    "errMsgFieldByValue": "Vui lòng chọn giá trị trường",
    "settingTabTitle": "Thiết lập",
    "layoutTabTitle": "Bố cục",
    "polarChartSelectFieldsHintText": "Mẹo: Chọn các trường để tạo biểu đồ cực",
    "visibilityText": "Khả năng hiển thị",
    "fieldNameText": "Tên trường",
    "aliasNameText": "Bí danh",
    "errMsgPolarFieldsRequired": "Hãy chọn ba trường trở lên để tạo biểu đồ cực",
    "polarChartPolygonFillLabel": "Đa giác đặc",
    "polarChartPolygonFillHintText": "Mẹo: Chọn hộp kiểm để hiện đa giác đặc trong biểu đồ cực",
    "viewLayoutLabel": "Bố cục",
    "ThemeSelector": {
      "themeAdobebricks": "Gạch không nung",
      "themeAlgae": "Tảo",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Chạng vạng",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Sa mạc",
      "themeDistinctive": "Khác biệt",
      "themeDollar": "Đô la",
      "themeGrasshopper": "Cào cào",
      "themeGrasslands": "Đồng cỏ",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Hài hòa",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Bạc hà",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Vùng đầm lầy",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Thiết lập Tổng quan",
    "locationSymbolLabel": "Ký hiệu vị trí đồ họa",
    "locationSymbolHintText": "Mẹo: Được sử dụng để hiển thị ký hiệu dành cho địa chỉ và vị trí bấm",
    "refreshIntervalLabel": "Khoảng thời gian làm mới",
    "refreshIntervalHintText": "Mẹo: Được sử dụng để làm mới biểu đồ theo khoảng thời gian này. Xác định giá trị trong khoảng từ 1 đến 1440 phút",
    "errMsgRefreshInterval": "Vui lòng xác định khoảng thời gian làm mới trong khoảng từ 0 đến 1440 phút",
    "symbolPickerPreviewText": "Xem trước:",
    "showToolToSelectLabel": "Nút Thiết lập vị trí",
    "showToolToSelectHintText": "Mẹo: Cung cấp nút để thiết lập vị trí trên bản đồ thay vì luôn phải thiết lập vị trí khi nhấp vào bản đồ"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Thiết lập Nguồn Tìm kiếm",
    "searchSourceSettingTitle": "Thiết lập Nguồn Tìm kiếm",
    "searchSourceSettingTitleHintText": "Thêm và cấu hình dịch vụ mã hóa địa lý hoặc lớp đối tượng làm nguồn tìm kiếm. Các nguồn đặc thù này xác định yếu tố nào có thể tìm kiếm được trong hộp tìm kiếm",
    "addSearchSourceLabel": "Thêm Nguồn Tìm kiếm",
    "featureLayerLabel": "Lớp đối tượng",
    "geocoderLabel": "Trình mã hóa địa lý",
    "nameTitle": "Tên",
    "generalSettingLabel": "Thiết lập Tổng quan",
    "allPlaceholderLabel": "Văn bản gợi ý để tìm kiếm tất cả:",
    "allPlaceholderHintText": "Mẹo: Nhập nội dung cần hiển thị làm văn bản gợi ý khi tìm kiếm tất cả các lớp và trình mã hóa địa lý",
    "generalSettingCheckboxLabel": "Hiển thị cửa sổ pop-up cho vị trí hoặc đối tượng được tìm thấy",
    "countryCode": "Mã Quốc gia hoặc Khu vực",
    "countryCodeEg": "ví dụ ",
    "countryCodeHint": "Để trống giá trị này sẽ tìm kiếm tất cả các quốc gia và khu vực",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Chỉ tìm kiếm trong kích thước bản đồ hiện tại",
    "zoomScale": "Tỷ lệ Thu phóng",
    "locatorUrl": "URL Bộ mã địa lý",
    "locatorName": "Tên Bộ mã địa lý",
    "locatorExample": "Ví dụ",
    "locatorWarning": "Phiên bản dịch vụ mã hóa địa lý này không được hỗ trợ. Tiện ích này hỗ trợ dịch vụ mã hóa địa lý 10.0 trở lên.",
    "locatorTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng gợi ý.",
    "layerSource": "Nguồn Lớp",
    "setLayerSource": "Thiết lập Nguồn Lớp",
    "setGeocoderURL": "Thiết lập URL Trình mã hóa địa lý",
    "searchLayerTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng phân trang.",
    "placeholder": "Văn bản trình giữ chỗ",
    "searchFields": "Trường Tìm kiếm",
    "displayField": "Hiển thị Trường",
    "exactMatch": "Kết quả khớp Chính xác",
    "maxSuggestions": "Đề xuất Tối đa",
    "maxResults": "Kết quả Tối đa",
    "enableLocalSearch": "Bật tính năng tìm kiếm nội bộ",
    "minScale": "Tỷ lệ Tối thiểu",
    "minScaleHint": "Khi tỷ lệ bản đồ lớn hơn tỷ lệ này, tìm kiếm cục bộ sẽ được áp dụng",
    "radius": "Bán kính",
    "radiusHint": "Xác định bán kính của một khu vực xung quanh trung tâm bản đồ hiện tại sẽ làm tăng thứ hạng của các đối tượng mã hóa địa lý, giúp các đối tượng ở gần nhất với vị trí được trả về đầu tiên",
    "meters": "Mét",
    "setSearchFields": "Thiết lập Trường Tìm kiếm",
    "set": "Thiết lập",
    "fieldName": "Tên",
    "invalidUrlTip": "URL ${URL} không hợp lệ hoặc không thể truy cập được."
  }
});