define({
  "gridTabLabel": "Grid",
  "labelTabLabel": "Etiketler",
  "referenceSystemTabLabel": "Referans Sistemi",
  "gridTabDescription": "Grid hücrelerinin görünümünü ve davranışını ayarlayın.",
  "cellOutlineColor": "Hücre Dış Hat rengi",
  "cellFillColor": "Hücre Doldurma rengi",
  "transparency": "Şeffaflık",
  "cellShapeDropDown": "Hücre Şekli",
  "default": "Dikdörtgen",
  "hexagon": "Altıgen",
  "cellUnitsDropDown": "Hücre Birimleri",
  "miles": "Mil",
  "kilometers": "Kilometre",
  "feet": "Fit",
  "meters": "Metre",
  "yards": "Yarda",
  "nautical-miles": "Deniz Mili",
  "gridOriginDropDown": "Grid Başlangıç Noktası",
  "lowerLeft": "Sol Alt",
  "lowerRight": "Sağ Alt",
  "upperLeft": "Sol Üst",
  "upperRight": "Sağ Üst",
  "center": "Orta",
  "labelTabDescription": "Grid etiketlerinin görünümünü ve davranışını ayarlayın.",
  "labelSettings": "Etiket Stili",
  "font": "Yazı Tipi",
  "textSize": "Metin Boyutu",
  "textColor": "Metin Rengi",
  "halo": "Hale",
  "show": "Göster",
  "labelTypeDropDown": "Etiket Türü",
  "alphaNumeric": "Alfa Sayısal",
  "alphaAlpha": "Alfa Alfa",
  "numeric": "Sayısal",
  "labelDirectionDropDown": "Etiket Yönü",
  "horizontal": "Yatay",
  "vertical": "Dikey",
  "labelOriginDropDown": "Etiket Başlangıç Noktası",
  "referenceSystemlTabDescription": "Varsayılan referans sistemini ayarlayın.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Ayarları Kilitle - Bu ayar kullanıcının araçta yapılandırılan ayarları değiştirmesini önleyecektir"
});