define({
  "_widgetLabel": "Uygunluk Modelleyicisi",
  "general": {
    "clear": "Temizle",
    "cancel": "İptal Et",
    "save": "Çalıştır",
    "saveAs": "Dışa Aktar"
  },
  "saveModel": {
    "save": "Dışa Aktar",
    "title": "Başlık: ",
    "summary": "Özet: ",
    "description": "Tanım: ",
    "tags": "Etiketler: ",
    "folder": "Klasör: ",
    "homeFolderPattern": "{username} (Ana Sayfa)",
    "failed": "Dışa aktarma başarısız."
  },
  "util": {
    "colorRamp": {
      "1": "Oldukça Düşük",
      "2": "Çok Düşük",
      "3": "Düşük",
      "4": "Düşük Orta",
      "5": "Orta",
      "6": "Yüksek Orta",
      "7": "Yüksek",
      "8": "Çok Yüksek",
      "9": "Oldukça Yüksek",
      "low": "Düşük",
      "high": "Yüksek",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Çevir"
    }
  },
  "wro": {
    "caption": "Uygunluk Modelleyicisi",
    "browsePrompt": "Ağırlıklı Örtüştürme Servisi",
    "selectLayersCaption": "Katmanları Seç",
    "selectLayers": "Katmanlar",
    "designModelCaption": "Tasarım Modeli",
    "designModel": "Tasarım Modeli",
    "transparency": "Şeffaflık",
    "visible": "Görünür",
    "total": "Toplam",
    "unableToLoad": "Model yüklenemiyor.",
    "projectNotOpen": "Açık proje yok.",
    "readMore": "Daha Fazla Bilgi",
    "validation": {
      "validating": "Doğrulanıyor...",
      "invalidItemCaption": "Ağırlıklı Örtüştürme Servisi Uyarısı",
      "notAnImageService": "Bu öge bir Görüntü Servisi değildir.",
      "notAWroService": "Bu öge bir Ağırlıklı Örtüştürme Servisi değildir.",
      "undefinedUrl": "Bu ögenin URL'si tanımlı değil.",
      "inaccessible": "Servise erişilemiyor.",
      "generalError": "Öge açılamıyor.",
      "missingFieldPattern": "{field}, zorunlu bir alandır",
      "notAllowRasterFunction": "allowRasterFunction, doğru olarak ayarlanmalıdır",
      "notNearestResampling": "defaultResamplingMethod, En Yakın olmalıdır",
      "notIsWeightedOverlayProp": "Key property IsWeightedOverlay, doğru olarak ayarlanmalıdır",
      "invalidLink": "URL geçersiz. Seçilen katman için site açılamadı.",
      "unexpectedError": "Beklenmeyen bir durum oluştu.",
      "rangeMessage": "Değer ${0} ve ${1} arasında olmalıdır",
      "rangeMessage100": "Değer 0 ile 100 arasında olmalıdır",
      "maxLayers": "Servis tarafından en çok ${0} katmana izin veriliyor, yeni bir katman ekleyebilmek için önce bir katman kaldırın.",
      "notFound": "${0} katmanı ağırlıklı örtüştürme servisinde bulunamadı",
      "wroServiceNotDefined": "Model için tanımlı ağırlıklı örtüştürme servisi yok.",
      "overlayLayerOutputInvalid": "Örtüştürme katmanı [${0}] yeniden haritalama aralıkları [${1}] çıktı değeri yok veya geçersiz",
      "overlayLayerInputInvalid": "Örtüştürme katmanı [${0}] yeniden haritalama aralıkları [${1}] giriş min/maks değeri yok veya geçersiz",
      "overlayLayerRangesMissing": "Örtüştürme katmanı [${0}] yeniden haritalama aralığı yok",
      "overlayLayerWeight": "Örtüştürme katmanı ağırlıklarının toplamı 100 olmalıdır",
      "overlayLayerRequired": "En az bir örtüştürme katmanı gereklidir",
      "overlayLayerNotDefined": "Örtüştürme katmanları tanımlı değil",
      "requiresColormap": "Bu raster işlevi için renkli harita gereklidir, ancak modelin geçerli bir renkli harita tanımı yok",
      "createModelError": "Model Oluşturma Hatası",
      "invalidModel": "Model geçerli değil",
      "imageServiceNotDefined": "Görüntü servisi katmanı tanımlı değil",
      "imageLayerNotDefined": "Görüntü servisi katmanı tanımlı değil",
      "histogramNotDefined": "Tanımlı ağırlıklı örtüştürme histogram işlevi yok."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Yeşil Sarı Kırmızı",
      "Red Yellow Green": "Kırmızı Sarı Yeşil",
      "Yellow to Dark Red": "Sarıdan Koyu Kırmızıya",
      "Dark Red to Yellow": "Koyu Kırmızıdan Sarıya",
      "Light Gray to Dark Gray": "Açık Griden Koyu Griye",
      "Dark Gray to Light Gray": "Koyu Griden Açık Griye",
      "Light Brown to Dark Brown": "Açık Kahverengiden Koyu Kahverengiye",
      "Dark Brown to Light Brown": "Koyu Kahverengiden Açık Kahverengiye",
      "Full Spectrum - Bright Red to Blue": "Tam Spektrum - Parlak Kırmızıdan Maviye",
      "Full Spectrum - Bright Blue to Red": "Tam Spektrum - Parlak Maviden Kırmızıya",
      "Partial Spectrum - Yellow to Blue": "Kısmi Spektrum - Sarıdan Maviye",
      "Partial Spectrum - Blue to Yellow": "Kısmi Spektrum - Maviden Sarıya",
      "Yellow-Green to Dark Blue": "Sarı-Yeşilden Koyu Maviye",
      "Dark Blue to Yellow-Green": "Koyu Maviden Sarı-Yeşile",
      "Cold to Hot Diverging": "Soğuktan Sıcağa Değişken",
      "Hot to Cold Diverging": "Sıcaktan Soğuğa Değişken",
      "Surface - Low to High": "Yüzey - Alçaktan Yükseğe",
      "Surface - High to Low": "Yüzey - Yüksekten Alçağa"
    }
  },
  "tabs": {
    "layers": "Katmanlar",
    "model": "Model",
    "chart": "Çizge"
  },
  "chart": {
    "prompt": "Detaylar",
    "working": "Güncelleniyor...",
    "polygonTool": "Bir Alan çiz",
    "freehandPolygonTool": "Serbest Alan çiz",
    "selectTool": "Katmandan seç",
    "panTool": "Kaydır",
    "clearButton": "Temizle",
    "noModelLayer": "Model yok.",
    "noSubjectLayers": "Haritanızda alan katmanı yok.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});