define({
  "_widgetLabel": "Ozaveščanje o incidentih",
  "locate_incident": "Lociraj incident",
  "reverse_geocoded_address": "Najbližji naslov",
  "reverse_geocoded_error": "Ni na voljo",
  "now": "ZDAJ",
  "wind": "VETER",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "TOR",
  "WED": "SRE",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SOB",
  "actionLabel": "Nastavi lokacijo",
  "drawPoint": "Nariši točko",
  "drawLine": "Nariši linijo",
  "drawPolygon": "Nariši poligon",
  "saveIncident": "Shrani",
  "clearIncident": "Začni znova",
  "noFeaturesFound": "Geoobjektov ni mogoče najti.",
  "downloadCSV": "Prenesi",
  "sum": "Vsota",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Povprečje",
  "count": "ŠTETJE",
  "area": "POVRŠINA",
  "length": "ŠTETJE",
  "update_btn": "POVRŠINA",
  "delete_btn": "Izbriši",
  "get_directions": "Pridobi navodila za pot",
  "incident": "Incident",
  "incidents": "Incidenti",
  "buffer": "Obris",
  "buffers": "Obrisi",
  "weather": "Vreme",
  "poweredBy": "Omogoča",
  "_featureAction_ActionLabel": "Nastavi lokacijo",
  "_featureAction_AddRemoveActionLabel": "Dodaj/odstrani lokacijo",
  "snapshot": "Mapo SnapShot ustvaril id aplikacije:",
  "user_credentials": "Uporabnik nima veljavnih pravic.",
  "notPolySnapShot": "Pred ustvarjanjem posnetka navedite razdaljo obrisa.",
  "notPolyReport": "Ni veljavnih rezultatov za dodajanje k prijavi.",
  "notValidDownload": "Ni veljavnih rezultatov za prenos.",
  "of_append": "od",
  "layer_append": "sloj",
  "downloadAll": "Prenesi vse",
  "createSnapshot": "Ustvari posnetek",
  "createReport": "Ustvari poročilo",
  "calculated_results": "Povzete informacije",
  "closest": "Najbližji geoobjekt",
  "proximity": "Bližina",
  "summary": "Povzetek",
  "groupedSummary": "Združeni števci",
  "_count": "Števec",
  "approximate": "približno",
  "snapshot_name": "Nastavi lastnosti posnetka",
  "report_name": "Nastavi lastnosti poročila",
  "invalid_snapshot_name": "Neveljavno ime posnetka.",
  "invalid_report_name": "Neveljavno ime poročila.",
  "orientation": "Usmerjenost",
  "pageSize": "Velikost strani",
  "comments": "Komentarji",
  "choose_group": "Skupine",
  "forecast": "Napoved",
  "select_group": "Izberi skupino",
  "select_group_instruction": "Posnetek bo ustvarjen in deljen z izbrano skupino",
  "information_append": " Informacije",
  "distance": "RAZDALJA",
  "buffer_invalid": "Vnesi veljavno število med ${min} in ${max}"
});