define({
  "symbolologyTabLabel": "Configurar Simbologia",
  "facilitiesDescription": "Camadas de Instalação",
  "demographicsDescription": "Camadas Demográficas",
  "settingsTitle": "Configurações",
  "spillLocationLabel": "Localização de Derramamento",
  "spillLocationButtonLabel": "Definir as Configurações de Localização de Derramamento",
  "IISettingsLabel": "Zona de isolamento inicial",
  "IIButtonLabel": "Definir Configurações de Isolamento Inicial",
  "PASettingsLabel": "Zona de Ação Protetiva",
  "PAButtonLabel": "Definir Configurações de Ação Protetiva",
  "downwindSettingsLabel": "Zona a favor do vento",
  "downwindButtonLabel": "Definir Configurações a favor do vento",
  "fireSettingsLabel": "Zona de Isolamento de Incêndio",
  "fireButtonLabel": "Definir Configurações de Isolamento de Incêndio",
  "bleveSettingsLabel": "Zona de Isolamento BLEVE",
  "bleveButtonLabel": "Definir Configurações de BLEVE",
  "transparency": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "style": "Estilo",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Transversal",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  }
});