define({
  "_widgetLabel": "Streaming",
  "streamControls": "Kontrol streaming",
  "streamFilter": "Filter",
  "startStreaming": "Mulai streaming",
  "stopStreaming": "Hentikan streaming",
  "streamLayers": "Layer streaming",
  "startStopStream": "Aktifkan opsi Hentikan streaming atau Mulai streaming",
  "clearStream": "Aktifkan opsi Bersihkan observasi sebelumnya",
  "attributeFilter": "Aktifkan filter atribut",
  "spatialFilter": "Aktifkan filter spasial",
  "configFilter": "Konfigurasi filter atribut streaming",
  "drawPrevious": "Aktifkan opsi Gambarkan observasi sebelumnya",
  "addNew": "Tambahkan filter",
  "setFilterName": "Atur nama filter",
  "filterNameExists": "Filter nama yang ada di tabel!",
  "invalidFilterName": "Nama harus berupa kata yang berisi a-z, A-Z, 0-9 or _.",
  "noFilterTip": "Tidak ada filter yang dikonfigurasikan",
  "addFilterFailed": "Gagal menambahkan filter",
  "filterName": "Nama filter",
  "limitMapExtent": "Batasi observasi dalam area peta saat ini",
  "limitDrawExtent": "Batasi observasi dalam area yang ditentukan pengguna",
  "newFilter": "Filter baru",
  "filterReadOnly": "Filter yang diperoleh dari webmap hanya dapat dibaca saja."
});