define({
  "chartSettingLabel": "圖表設定",
  "addNewLabel": "新增",
  "generalSettingLabel": "一般設定",
  "searchSourceSettingLabel": "搜尋來源設定",
  "layerChooser": {
    "title": "選擇要製作圖表的圖層",
    "selectPolygonLayerLabel": "選擇圖層",
    "selectPolygonLayerHintText": "提示: 如果配置多個圖表，則圖層必須屬於相同的幾何類型",
    "selectRelatedTableLayerLabel": "選擇圖層的相關表格",
    "selectRelatedTableLayerHintText": "提示: 只會顯示含數欄位的表格",
    "errorInSelectingPolygonLayer": "請選擇具有相關點圖層的圖層。",
    "errorInSelectingRelatedLayer": "請選擇要製作圖層之有效的相關表格/圖層。",
    "polygonLayerNotHavingRelationships": "選擇的圖層沒有任何相關的表格/圖層。"
  },
  "ChartSetting": {
    "sectionTitle": "章節標題",
    "sectionTitleHintText": "提示: 在區段標頭標題中顯示",
    "chartTitle": "圖表標題",
    "chartTitleHintText": "提示: 顯示於圖表上方中央",
    "chartDescription": "說明",
    "chartDescriptionHintText": "提示: 顯示於圖表下方",
    "chartType": "圖表類型",
    "barChart": "長條圖",
    "pieChart": "圓餅圖",
    "polarChart": "極區圖",
    "dataSeriesField": "資料數列欄位",
    "labelField": "標籤欄位",
    "chartColor": "圖表顏色",
    "singleColor": "單一顏色",
    "colorByTheme": "按主題分類的顏色",
    "colorByFieldValue": "按欄位值分類的顏色",
    "xAxisTitle": "X 軸標題",
    "xAxisHintText": "提示: X 軸標題",
    "yAxisTitle": "Y 軸標題",
    "yAxisHintText": "提示: Y 軸標題",
    "fieldColorLabel": "標籤",
    "fieldColorColor": "顏色",
    "defaultFieldSelectLabel": "選擇",
    "errMsgFieldValuesNotFound": "找不到所選欄位的值",
    "errMsgSectionTitle": "請輸入區段標題",
    "errMsgFieldByValue": "請選擇欄位值",
    "settingTabTitle": "設定",
    "layoutTabTitle": "版面配置",
    "polarChartSelectFieldsHintText": "提示: 選擇欄位以產生極區圖",
    "visibilityText": "能見度",
    "fieldNameText": "欄位名稱",
    "aliasNameText": "別名",
    "errMsgPolarFieldsRequired": "請選擇三個或更多欄位以產生極區圖",
    "polarChartPolygonFillLabel": "填滿多邊形",
    "polarChartPolygonFillHintText": "提示: 選擇核取方塊可在極區圖中顯示多邊形填滿",
    "viewLayoutLabel": "版面配置",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "水藻",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "沙漠",
      "themeDistinctive": "獨特",
      "themeDollar": "元",
      "themeGrasshopper": "蚱蜢",
      "themeGrasslands": "草原",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "協調",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "愛爾蘭",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "有薄荷香的",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "沼澤地",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "一般設定",
    "locationSymbolLabel": "圖形地址符號",
    "locationSymbolHintText": "提示: 用來顯示地址和按一下位置的符號",
    "refreshIntervalLabel": "重新整理間隔",
    "refreshIntervalHintText": "提示: 用來根據此間隔重新整理圖表。指定 1 到 1440 分鐘之間的值",
    "errMsgRefreshInterval": "請指定 0 到 1440 分鐘之間的重新整理間隔",
    "symbolPickerPreviewText": "預覽:",
    "showToolToSelectLabel": "設定位置按鈕",
    "showToolToSelectHintText": "提示: 按一下地圖時提供按鈕以設定地圖上的位置，而非一律設定位置"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "搜尋來源設定",
    "searchSourceSettingTitle": "搜尋來源設定",
    "searchSourceSettingTitleHintText": "新增並配置地理編碼服務或圖徵圖層為搜尋來源。這些指定的來源決定了搜尋方塊中的可搜尋內容",
    "addSearchSourceLabel": "新增搜尋來源",
    "featureLayerLabel": "圖徵圖層",
    "geocoderLabel": "地理編碼器",
    "nameTitle": "名稱",
    "generalSettingLabel": "一般設定",
    "allPlaceholderLabel": "用於全部搜尋的占位符文字:",
    "allPlaceholderHintText": "提示: 輸入在搜尋所有圖層和地理編碼器時，要顯示成佔位符的文字",
    "generalSettingCheckboxLabel": "顯示發現的圖徵或位置的快顯視窗",
    "countryCode": "國碼或地區代碼",
    "countryCodeEg": "例如 ",
    "countryCodeHint": "留空此值會搜尋所有國家和地區",
    "questionMark": "?",
    "searchInCurrentMapExtent": "僅在目前的地圖範圍中搜尋",
    "zoomScale": "縮放比例",
    "locatorUrl": "地理編碼器 URL",
    "locatorName": "地理編碼器名稱",
    "locatorExample": "範例",
    "locatorWarning": "不支援此版本的地理編碼服務。該 widget支援 10.0 及更高版本的地理編碼服務。",
    "locatorTips": "由於地理編碼服務不支援建議功能，因此建議無法使用。",
    "layerSource": "圖層來源",
    "setLayerSource": "設定圖層來源",
    "setGeocoderURL": "設定地理編碼器 URL",
    "searchLayerTips": "由於圖徵服務不支援分頁功能，因此建議無法使用。",
    "placeholder": "佔位符文字",
    "searchFields": "搜尋欄位",
    "displayField": "顯示欄位",
    "exactMatch": "完全相符",
    "maxSuggestions": "最大建議數",
    "maxResults": "最大結果數",
    "enableLocalSearch": "啟用本機搜尋",
    "minScale": "最小比例",
    "minScaleHint": "當地圖比例大於此比例時，將套用本機搜尋",
    "radius": "半徑",
    "radiusHint": "指定目前地圖中心周圍的區域半徑，可用來提升地理編碼候選者的等級，以優先傳回離位置最近的候選者",
    "meters": "公尺",
    "setSearchFields": "設定搜尋欄位",
    "set": "設定",
    "fieldName": "名稱",
    "invalidUrlTip": "URL ${URL} 無效或不可存取。"
  }
});