define({
  "routeUrl": "URL Rute",
  "locatorUrl": "URL Geocoder",
  "geocoderOptions": "Opsi Geocoder",
  "autoComplete": "Selesaikan otomatis",
  "maximumSuggestions": "Saran maksimal",
  "minCharacters": "Karakter minimal",
  "searchDelay": "Cari penangguhan",
  "placeholder": "Placeholder",
  "routeOptions": "Opsi rute",
  "directionsLanguage": "Bahasa arahan",
  "directionsLengthUnits": "Unit panjang arahan",
  "directionsOutputType": "Tipe output arahan",
  "impedanceAttribute": "Atribut impedansi",
  "kilometers": "Kilometer",
  "miles": "Mil",
  "meters": "Meter",
  "feet": "Kaki",
  "yards": "Yard",
  "nauticalMiles": "Mil laut",
  "parametersTip": "Harap tetapkan parameter dengan benar !",
  "complete": "Selesai",
  "completeNoEvents": "Tidak Menyelesaikan Acara",
  "instructionsOnly": "Khusus instruksi",
  "standard": "Standar",
  "summaryOnly": "Khusus ringkasan",
  "travelModesUrl": "URL mode perjalanan",
  "searchPlaceholder": "Temukan alamat atau tempat",
  "trafficLayerUrl": "URL layer lalu lintas",
  "presetDestinations": "Perhentian prasetel",
  "startPoint": "Titik mulai",
  "endPoint": "Titik selesai",
  "destinationHolder": "Alamat atau kordinat",
  "optional": "Opsional."
});