define({
  "_widgetLabel": "Αναγνώριση κατάστασης",
  "locate_incident": "Εντοπισμός περιστατικού",
  "reverse_geocoded_address": "Πλησιέστερη διεύθυνση",
  "reverse_geocoded_error": "Μη διαθέσιμο",
  "now": "ΤΩΡΑ",
  "wind": "ΑΝΕΜΟΣ",
  "SUN": "ΚΥΡ",
  "MON": "ΔΕΥ",
  "TUE": "ΤΡΙ",
  "WED": "ΤΕΤ",
  "THU": "ΠΕΜ",
  "FRI": "ΠΑΡ",
  "SAT": "ΣΑΒ",
  "actionLabel": "Ορισμός τοποθεσίας",
  "drawPoint": "Σχεδίαση σημείου",
  "drawLine": "Σχεδίαση γραμμής",
  "drawPolygon": "Σχεδίαση πολυγώνου",
  "saveIncident": "Αποθήκευση",
  "clearIncident": "Επανέναρξη",
  "noFeaturesFound": "Δεν βρέθηκαν στοιχεία.",
  "downloadCSV": "Λήψη",
  "sum": "Άθροισμα",
  "min": "Ελάχιστο",
  "max": "Μέγιστο",
  "avg": "Μέτριο",
  "count": "ΠΛΗΘΟΣ",
  "area": "ΠΕΡΙΟΧΗ",
  "length": "ΜΗΚΟΣ",
  "update_btn": "Τέλος",
  "delete_btn": "Διαγραφή",
  "get_directions": "Λήψη οδηγιών",
  "incident": "Συμβάν",
  "incidents": "Περιστατικά",
  "buffer": "Προσωρινή μνήμη",
  "buffers": "Ζώνες",
  "weather": "Καιρός",
  "poweredBy": "Υποστηρίζεται από το",
  "_featureAction_ActionLabel": "Ορισμός τοποθεσίας",
  "_featureAction_AddRemoveActionLabel": "Προσθήκη/κατάργηση τοποθεσίας",
  "snapshot": "Δημιουργήθηκε φάκελος στιγμιότυπου ανά αναγνωριστικό εφαρμογής:",
  "user_credentials": "Ο χρήστης δεν έχει έγκυρα δικαιώματα.",
  "notPolySnapShot": "Καθορίστε μια απόσταση ζώνης, προτού δημιουργήσετε στιγμιότυπο.",
  "notPolyReport": "Δεν υπάρχουν έγκυρα αποτελέσματα για προσθήκη στην αναφορά.",
  "notValidDownload": "Δεν υπάρχουν έγκυρα αποτελέσματα για λήψη.",
  "of_append": "από",
  "layer_append": "θεματικό επίπεδο",
  "downloadAll": "Λήψη όλων",
  "createSnapshot": "Δημιουργία στιγμιότυπου",
  "createReport": "Δημιουργία αναφοράς",
  "calculated_results": "Συνοπτικές πληροφορίες",
  "closest": "Πλησιέστερο στοιχείο",
  "proximity": "Εγγύτητα",
  "summary": "Σύνοψη",
  "groupedSummary": "Ομαδοποιημένες απαριθμήσεις",
  "_count": "Πλήθος",
  "approximate": "κατά προσέγγιση",
  "snapshot_name": "Ορισμός ιδιοτήτων στιγμιότυπου",
  "report_name": "Ορισμός ιδιοτήτων αναφοράς",
  "invalid_snapshot_name": "Μη έγκυρο όνομα στιγμιότυπου.",
  "invalid_report_name": "Μη έγκυρος τίτλος αναφοράς.",
  "orientation": "Προσανατολισμός",
  "pageSize": "Μέγεθος σελίδας",
  "comments": "Σχόλια",
  "choose_group": "Ομάδες",
  "forecast": "Πρόβλεψη",
  "select_group": "Επιλογή ομάδας",
  "select_group_instruction": "Το στιγμιότυπο θα δημιουργηθεί και θα κοινοποιηθεί στην επιλεγμένη ομάδα",
  "information_append": " Πληροφορίες",
  "distance": "ΑΠΟΣΤΑΣΗ",
  "buffer_invalid": "Καταχωρίστε έγκυρο αριθμό από το ${min} ως το ${max}."
});