define({
  "_widgetLabel": "Nhận biết Tình huống",
  "locate_incident": "Định vị Sự cố",
  "reverse_geocoded_address": "Địa chỉ Gần nhất",
  "reverse_geocoded_error": "Không khả dụng",
  "now": "BÂY GIỜ",
  "wind": "GIÓ",
  "SUN": "CN",
  "MON": "T2",
  "TUE": "T3",
  "WED": "T4",
  "THU": "T5",
  "FRI": "T6",
  "SAT": "T7",
  "actionLabel": "Thiết lập Vị trí",
  "drawPoint": "Vẽ điểm",
  "drawLine": "Vẽ đường",
  "drawPolygon": "Vẽ vùng",
  "saveIncident": "Lưu",
  "clearIncident": "Bắt đầu",
  "noFeaturesFound": "Không tìm thấy đối tượng.",
  "downloadCSV": "Tải xuống",
  "sum": "Tổng",
  "min": "Tối thiểu",
  "max": "Tối đa",
  "avg": "Trung bình",
  "count": "SỐ LƯỢNG",
  "area": "DIỆN TÍCH",
  "length": "ĐỘ DÀI",
  "update_btn": "Hoàn tất",
  "delete_btn": "Xóa",
  "get_directions": "Nhận Chỉ đường",
  "incident": "Sự cố",
  "incidents": "Sự cố",
  "buffer": "Vùng đệm",
  "buffers": "Vùng đệm",
  "weather": "Thời tiết",
  "poweredBy": "Được hỗ trợ bởi",
  "_featureAction_ActionLabel": "Thiết lập Vị trí",
  "_featureAction_AddRemoveActionLabel": "Thêm/Xóa Vị trí",
  "snapshot": "Thư mục Ảnh chụp màn hình được tạo bởi App id:",
  "user_credentials": "Người dùng không có quyền hợp lệ.",
  "notPolySnapShot": "Vui lòng xác định khoảng cách vùng đệm trước khi tạo ảnh chụp nhanh.",
  "notPolyReport": "Kết quả không hợp lệ để thêm vào báo cáo.",
  "notValidDownload": "Không có kết quả hợp lệ để tải xuống.",
  "of_append": "của",
  "layer_append": "lớp",
  "downloadAll": "Tải xuống tất cả",
  "createSnapshot": "Tạo ảnh chụp nhanh",
  "createReport": "Tạo báo cáo",
  "calculated_results": "Thông tin Tóm tắt",
  "closest": "Đối tượng Gần nhất",
  "proximity": "Vùng lân cận",
  "summary": "Tóm tắt",
  "groupedSummary": "Đã nhóm Bộ đếm",
  "_count": "Số lượng",
  "approximate": "xấp xỉ",
  "snapshot_name": "Thiết lập thuộc tính ảnh chụp nhanh",
  "report_name": "Thiết lập thuộc tính báo cáo",
  "invalid_snapshot_name": "Tên ảnh chụp nhanh không hợp lệ.",
  "invalid_report_name": "Tiêu đề báo cáo không hợp lệ",
  "orientation": "Hướng ảnh",
  "pageSize": "Kích thước trang",
  "comments": "Bình luận",
  "choose_group": "Nhóm",
  "forecast": "Dự báo",
  "select_group": "Chọn Nhóm",
  "select_group_instruction": "Ảnh chụp nhanh sẽ được tạo ra và chia sẻ với nhóm đã chọn",
  "information_append": " Thông tin",
  "distance": "KHOẢNG CÁCH",
  "buffer_invalid": "Nhập số hợp lệ trong khoảng ${min} đến ${max}"
});