define({
  "add": "クリックして新規追加",
  "title": "タイトル",
  "placeholderBookmarkName": "ブックマーク名",
  "ok": "OK",
  "cancel": "キャンセル",
  "warning": "編集を終了してください。",
  "edit": "ブックマークの編集",
  "errorNameExist": "すでに存在しているブックマーク名です",
  "errorNameNull": "無効なブックマーク名です",
  "addBookmark": "新規作成",
  "thumbnail": "サムネイル",
  "thumbnailHint": "画像をクリックすると更新されます",
  "displayBookmarksAs": "ブックマークを次で表示",
  "cards": "カード",
  "list": "リスト",
  "cardsTips": "カード表示",
  "listTips": "リスト表示",
  "makeAsDefault": "デフォルトに設定",
  "default": "既定",
  "editable": "ブックマークをウィジェットに追加することを許可",
  "alwaysSync": "ブックマークを Web マップから表示",
  "configCustom": "カスタム ブックマークの表示",
  "import": "インポート",
  "create": "作成",
  "importTitle": "ブックマークのインポート",
  "importFromWeb": "ブックマークを現在の Web マップからインポート",
  "selectAll": "すべて選択",
  "noBookmarkInConfig": "[インポート] または [新規作成] をクリックして、ブックマークを追加します。",
  "noBookmarkInWebMap": "マップでブックマークが構成されていません。",
  "extent": "範囲",
  "saveExtent": "マップ範囲をこのブックマークに保存",
  "savelayers": "レイヤーの表示設定の保存",
  "withVisibility": "レイヤーの表示設定を使用",
  "bookmark": "ブックマーク",
  "addBtn": "追加",
  "deleteBtn": "削除",
  "editBtn": "編集",
  "dragReorderTip": "クリックしたままドラッグして順序変更",
  "deleteBtnTip": "ブックマークの削除",
  "editBtnTip": "ブックマークの編集"
});