define({
  "_widgetLabel": "Đồ họa tham chiếu dạng lưới",
  "newGRGFromAreaButtonLabel": "Xác định lưới từ một Khu vực",
  "newGRGFromPointButtonLabel": "Xác định lưới từ một Điểm",
  "newGRGFromAreaTitle": "Xác định lưới từ một Khu vực",
  "newGRGFromPointTitle": "Xác định lưới từ một Điểm",
  "newGRGBySizeButtonLabel": "Theo Chiều",
  "newGRGFromRefSystemButtonLabel": "Theo Hệ Tham chiếu",
  "newGRGByTimeLabel": "Theo Thời gian và Tốc độ",
  "newGRGFromNonStandardButtonLabel": "Xác định Lưới không phải tiêu chuẩn",
  "newGRGAreaBySizeTitle": "GRG từ một Khu vực theo Chiều",
  "newGRGAreaBySizeDefineAreaLabel": "Khu vực GRG",
  "addGRGAreaPolygonToolTip": "Vẽ Khu vực GRG sử dụng dạng vùng",
  "addGRGAreaExtentToolTip": "Khu vực GRG sử dụng phạm vi",
  "rotation": "Xoay Lưới",
  "numberRowsColumnsLabel": "Xác định số hàng và cột",
  "newGRGAreaByRefSystemTitle": "GRG từ một Khu vực theo Hệ Tham chiếu",
  "gridSize": "Kích cỡ Lưới",
  "UTMZoneandBand": "Vùng Lưới",
  "100000m": "100000 mét",
  "10000m": "10000 mét",
  "1000m": "1000 mét",
  "100m": "100 mét",
  "10m": "10 mét",
  "clipGrid": "Lật Lưới sang Khu vực GRG",
  "newGRGAreaFromNonStandardTitle": "NRG mới",
  "newGRGPointBySizeTitle": "GRG từ một Điểm theo Chiều",
  "newGRGPointByRefSystemTitle": "GRG từ một Điểm theo Hệ Tham chiếu",
  "newGRGPointByTimeTitle": "GRG từ một Điểm sử dụng Thời gian và Tốc độ",
  "time": "Thời gian",
  "rate": "Tốc độ",
  "hours": "Giờ",
  "minutes": "Phút",
  "seconds": "Giây",
  "ftPerSec": "Feet / giây",
  "ftPerHour": "Feet / giờ",
  "kmPerSec": "Kilômét/ giây",
  "kmPerHour": "Kilômét/ giờ",
  "mPerSec": "Mét / giây",
  "mPerHour": "Mét / giờ",
  "miPerSec": "Dặm / giây",
  "miPerHour": "Dặm / giờ",
  "nMPerSec": "Hải lý / giây",
  "nMPerHour": "Hải lý / giờ",
  "settingsTitle": "Thiết lập",
  "labelSettingsLabel": "Cài đặt Nhãn",
  "labelSettingsButtonLabel": "Cấu hình Cài đặt Nhãn",
  "gridSettingsLabel": "Cài đặt Lưới",
  "gridSettingsButtonLabel": "Cấu hình Cài đặt Lưới",
  "transparency": "Độ trong suốt",
  "labelStyle": "Kiểu nhãn",
  "font": "Phông chữ",
  "textSize": "Kích cỡ Văn bản",
  "textColor": "Màu Văn bản",
  "halo": "Hào quang",
  "show": "Hiển thị",
  "lockSettings": "Cài đặt đã bị chủ sở hữu ứng dụng khóa lại",
  "gridSettings": {
    "cellShape": "Hình dạng ô",
    "cellUnits": "Đơn vị ô",
    "cellOutline": "Cài đặt Đường nét ô",
    "cellFill": "Cài đặt Tô màu cho ô",
    "gridReferenceSystem": "Hệ Tham chiếu",
    "gridDatum": "Hệ tham chiếu: WGS84",
    "labelStartPosition": "Điểm gốc của nhãn",
    "labelType": "Loại nhãn",
    "labelDirection": "Hướng nhãn",
    "gridOrigin": "Điểm gốc lưới",
    "default": "Hình chữ nhật",
    "hexagon": "Hình lục giác",
    "miles": "Dặm",
    "kilometers": "Kilômét",
    "feet": "Bộ",
    "meters": "Mét",
    "yards": "Thước",
    "nautical-miles": "Hải lý",
    "lowerLeft": "Phía dưới bên trái",
    "lowerRight": "Phía dưới bên phải",
    "upperLeft": "Phía trên bên trái",
    "upperRight": "Phía trên bên phải",
    "center": "Tâm",
    "alphaNumeric": "Chữ-Số",
    "alphaAlpha": "Chữ-Chữ",
    "numeric": "Số",
    "horizontal": "Ngang",
    "vertical": "Dọc",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Hiện Nhãn"
  },
  "publishTitle": "Xuất bản GRG đến Cổng",
  "publishGRGBtn": "Xuất bản",
  "GRGLayerName": "Tên Lớp GRG đã xuất bản",
  "invalidGRGLayerName": "Tên lớp chỉ được chứa các ký tự chữ số và dấu gạch dưới",
  "missingGRGLayerName": "Bạn phải nhập tên cho GRG",
  "publishingFailedLayerExists": "Xuất bản không thành công: Bạn đã có dịch vụ đối tượng có tên {0}. Vui lòng chọn tên khác.",
  "checkService": "Kiểm tra Dịch vụ: {0}.",
  "createService": "Tạo Dịch vụ: {0}",
  "unableToCreate": "Không thể tạo: {0}",
  "addToDefinition": "Thêm vào định nghĩa: {0}",
  "successfullyPublished": "Xuất bản lớp web thành công{0}Quản lý lớp web",
  "userRole": "Không thể tạo dịch vụ do người dùng không có phân quyền",
  "createGRGBtn": "Tạo GRG",
  "clearGRGBtn": "Xóa",
  "labelFormat": "Định dạng nhãn",
  "helpIconTooltip": "Z: Bộ chỉ định Vùng Lưới (GZD)\nS: Xác định Hình vuông Lưới 100.000 mét (GSID)\nX: Đi về phía đông (Tọa độ X)\nY: Đi về phía bắc  (Tọa độ Y)\n\nVí dụ:\nZSXY là 15SWC8081751205\nZS X,Y là 15SWC 80817,51205",
  "addPointToolTip": "Thêm Điểm gốc GRG",
  "cellWidth": "Chiều rộng ô (x)",
  "cellHeight": "Chiều cao ô (y)",
  "invalidNumberMessage": "Giá trị đã nhập không hợp lệ",
  "invalidRangeMessage": "Giá trị phải lớn hơn 0",
  "gridAngleInvalidRangeMessage": "Giá trị phải nằm trong khoảng từ -89,9 đến 89,9",
  "formatIconTooltip": "Định dạng đầu vào",
  "coordInputLabel": "Điểm gốc GRG (DD)",
  "setCoordFormat": "Thiết lập chuỗi định dạng tọa độ",
  "prefixNumbers": "Thêm tiền tố \"+/-\" vào số dương và số âm",
  "cancelBtn": "Hủy",
  "applyBtn": "Áp dụng",
  "comfirmInputNotation": "Xác nhận Ký hiệu đầu vào",
  "notationsMatch": "các ký hiệu khớp với thông tin của bạn. Vui lòng xác nhận ký hiệu bạn muốn sử dụng:",
  "numberOfCellsHorizontal": "# Ô ngang",
  "numberOfCellsVertical": "# Ô dọc",
  "gridAngle": "Xoay Lưới",
  "tooManyCellsErrorMessage": "Bạn đang cố gắng tạo một lưới gồm hơn 2000 ô. Bạn nên giảm số lượng ô sẽ tạo bằng cách thay đổi kích cỡ lưới hoặc diện tích lưới.",
  "missingParametersMessage": "<p>Mẫu tạo GRG bị thiếu thông số hoặc chứa thông số không hợp lệ. Vui lòng đảm bảo:</p><ul><li>Đã vẽ khu vực GRG.</li><li>Chiều rộng và chiều cao ô chứa giá trị hợp lệ.</li></ul>",
  "missingOriginParametersMessage": "<p>Mẫu tạo GRG bị thiếu thông số hoặc chứa thông số không hợp lệ. Vui lòng đảm bảo:</p><ul><li>Điểm gốc GRG được thiết lập.</li><li>Thông tin thời gian, tốc độ và góc chứa giá trị hợp lệ.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Mẫu tạo GRG bị thiếu thông số hoặc chứa thông số không hợp lệ. Vui lòng đảm bảo thông tin chiều rộng và chiều cao ô góc chứa giá trị hợp lệ.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Mẫu tạo GRG bị thiếu thông số hoặc chứa thông số không hợp lệ. Vui lòng đảm bảo thông tin về số lượng ô ngang và ô dọc chứa giá trị hợp lệ.</p>",
  "drawPointToolTip": "Bấm để thêm điểm gốc GRG",
  "missingLayerNameMessage": "Bạn phải nhập tên lớp hợp lệ trước khi có thể xuất bản",
  "parseCoordinatesError": "Không thể dán tọa độ. Vui lòng kiểm tra thông tin của bạn.",
  "grgPolarRegionError": "Phạm vi GRG nằm trong vùng cực. Các ô rơi vào vùng cực sẽ không được tạo.",
  "grgPolarOriginError": "Điểm gốc GRG không được nằm trong vùng cực khi tạo GRG theo Hệ Tham chiếu.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Độ thập phân - Vĩ độ/Kinh độ",
  "DDLongLatNotation": "Độ thập phân - Kinh độ/Vĩ độ",
  "DDMLatLongNotation": "Độ thập phân phút - Vĩ độ/Kinh độ",
  "DDMLongLatNotation": "Độ thập phân phút - Kinh độ/Vĩ độ",
  "DMSLatLongNotation": "Độ thập phân giây - Vĩ độ/Kinh độ",
  "DMSLongLatNotation": "Độ thập phân giây - Kinh độ/Vĩ độ",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Chữ cái dải sóng",
  "UTMHemNotation": "UTM - Bán cầu (Bắc/Nam)"
});