define({
  "_widgetLabel": "Interrogazione",
  "executeQueryTip": "Fare clic su uno degli elementi attività seguenti per eseguire la query.",
  "invalidConfig": "Configurazione non valida. Utilizzare la pagina delle impostazioni interrogazione per ottenere la configurazione corretta.",
  "queryParams": "Opzioni",
  "parameters": "OPZIONI",
  "queries": "INTERROGAZIONI",
  "apply": "Applica",
  "queryResults": "Risultati",
  "clear": "Cancella",
  "noResults": "Nessuna feature trovata.",
  "queryError": "Interrogazione non riuscita.",
  "numberFound": "Numero di feature trovate",
  "mapExtentTip": "Limita i risultati all'area della mappa corrente.",
  "noValue": "Valore non disponibile",
  "and": "e",
  "stringOperatorIs": "è",
  "stringOperatorIsNot": "non è",
  "stringOperatorStartsWith": "inizia con",
  "stringOperatorEndsWith": "termina con",
  "stringOperatorContains": "contiene",
  "stringOperatorDoesNotContain": "non contiene",
  "stringOperatorIsBlank": "è vuoto",
  "stringOperatorIsNotBlank": "non è vuoto",
  "dateOperatorIsOn": "ricorre il giorno",
  "dateOperatorIsNotOn": "non ricorre il giorno",
  "dateOperatorIsBefore": "ricorre prima del giorno",
  "dateOperatorIsAfter": "ricorre dopo il giorno",
  "dateOperatorDays": "giorni",
  "dateOperatorWeeks": "settimane",
  "dateOperatorMonths": "mesi",
  "dateOperatorInTheLast": "negli ultimi/nelle ultime",
  "dateOperatorNotInTheLast": "non negli ultimi/nelle ultime",
  "dateOperatorIsBetween": "è compreso tra",
  "dateOperatorIsNotBetween": "non è compreso tra",
  "dateOperatorIsBlank": "è vuoto",
  "dateOperatorIsNotBlank": "non è vuoto",
  "numberOperatorIs": "è",
  "numberOperatorIsNot": "non è",
  "numberOperatorIsAtLeast": "è almeno",
  "numberOperatorIsLessThan": "è minore di",
  "numberOperatorIsAtMost": "è al massimo",
  "numberOperatorIsGreaterThan": "è maggiore di",
  "numberOperatorIsBetween": "è compreso tra",
  "numberOperatorIsNotBetween": "non è compreso tra",
  "numberOperatorIsBlank": "è vuoto",
  "numberOperatorIsNotBlank": "non è vuoto",
  "operationalLayerTip": "Aggiungi risultato come layer operativo",
  "queryResult": "Risultato interrogazione",
  "specifyParamsTip": "Specificare i parametri per l'attività",
  "useSpatialFilter": "Usa filtro spaziale per limitare le feature",
  "useCurrentMapExtent": "Solo le feature che intersecano l'area della mappa corrente",
  "drawGraphicOnMap": "Solo le feature che intersecano l'area definita dall'utente",
  "specifySpatialFilterMsg": "Specificare il filtro spaziale per questa attività.",
  "clearResults": "Elimina risultati",
  "operationalTip": "Se questa opzione è selezionata, i risultati verranno mantenuti sulla mappa finché non si fa clic sul pulsante \"${clearResults}\".",
  "noneQueryTip": "Nessuna attività di interrogazione è stata configurata per questo widget.",
  "noPermissionsMsg": "Non si dispone delle autorizzazioni per accedere al servizio.",
  "attributesFromRelationship": "Attributi da tabella correlata",
  "tasks": "Attività",
  "applySpatialFilterToLimitResults": "Applica un filtro spaziale per limitare i risultati",
  "useCurrentExtentTip": "Restituisci solo feature all'interno dell'estensione mappa corrente",
  "useDrawGraphicTip": "Restituisci solo feature che si intersecano con la forma disegnata sulla mappa",
  "useFeaturesTip": "Restituisci solo feature caratterizzate da una relazione spaziale con le feature in un altro layer",
  "noSpatialLimitTip": "Restituisci feature all'interno dell'estensione completa della mappa",
  "applySearchDistance": "Applica a distanza di ricerca",
  "spatialRelationship": "Relazione spaziale",
  "relatedLayer": "Layer correlato",
  "bufferDistance": "Distanza di buffer",
  "miles": "Miglia",
  "kilometers": "Chilometri",
  "feet": "Piede",
  "meters": "Metri",
  "yards": "Iarde",
  "nauticalMiles": "Miglia nautiche",
  "back": "Indietro",
  "execute": "Esegui",
  "zoomTo": "Zoom a",
  "openAttributeTable": "Visualizza nella tabella degli attributi",
  "noResult": "Nessun risultato.",
  "noTask": "Nessuna attività.",
  "removeThisResult": "Rimuovi questo risultato",
  "attributeCriteira": "Criteri attributo",
  "spatialFilter": "Filtro spaziale",
  "value": "VALUE",
  "noAttributeSpatialFilterTip": "Nessun filtro definito. Tutte le feature verranno restituite.",
  "showAllRelatedRecords": "Mostra tutti i record correlati",
  "changeSymbol": "Cambia simbolo",
  "queryCriteira": "Criteri di interrogazione",
  "customQuery": "Interrogazione personalizzata",
  "layer": "Layer",
  "createCustomQuery": "Crea interrogazione personalizzata."
});