define({
  "_widgetLabel": "आपातकालीन प्रतिक्रिया मार्गदर्शिका (इमरजेंसी रिस्पांस गाइड)",
  "ergMainPageTitle": "आपातकालीन प्रतिक्रिया मार्गदर्शिका 2016 पर आधारित",
  "coordInputLabelStart": "छलकने का स्थान (DD)",
  "coordInputLabel": "छलकने का स्थान",
  "addPointToolTip": "छलकने का स्थान जोड़ें",
  "drawPointToolTip": "छलकने का स्थान जोड़ने के लिए क्लिक करें",
  "material": "सामग्री",
  "materialPlaceholder": "किसी सामग्री के लिए खोज करने के लिए टाइप करना प्रारंभ करें",
  "table3Message": "अगर आप बड़े पैमाने पर हुई छलकाव पर काम कर रहे हैं तो आपके द्वारा चुनी गई सामग्रियों को अतिरिक्त जानकारी की आवश्यकता है।\n\nकृपया सुनिश्चित करें कि आपके पास हवा की गति और परिवहन कंटेनर के लिए चुने गए सही मान हैं।",
  "table2Message": "आपके द्वारा चुनी गई सामग्री के पानी में गिरने पर बड़ी मात्रा में विषाक्त गैस उत्पन्न हो सकती है, जो सांस में जाने पर घातक हो सकती है।\n\nहो सकता है कि आप निम्न सामग्री का उपयोग करना चाहें:\n\n",
  "spillSize": "छलकाव की मात्रा",
  "small": "छोटा",
  "large": "बड़ा",
  "fireLabel": "अग्नि पृथक्करण क्षेत्र दिखाएं",
  "weatherLabel": "छलकने के स्थान पर वर्तमान मौसम",
  "weatherIntialText": "<br />एक बार छलकने के स्थान को पहचानने के बाद अपडेट किया गया",
  "temperature": "तापमान",
  "wind": "हवा",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "मौसम संबंधी जानकारी प्राप्त नहीं हुई। हवा की गति और छलकाव के समय को मैन्युअल रूप से अपडेट करें",
  "windDirection": "हवा की दिशा (बहने की दिशा)",
  "timeOfSpill": "छलकाव का समय",
  "day": "दिन",
  "night": "रात्रि",
  "windSpeed": "हवा की गति",
  "low": "निम्न",
  "moderate": "मध्यम",
  "high": "उच्च",
  "transportContainer": "परिवहन कंटेनर",
  "rail": "रेल टैंक कार",
  "semi": "राजमार्ग टैंक ट्रक या ट्रेलर",
  "mton": "एकाधिक टन सिलेंडर",
  "ston": "एकाधिक छोटे सिलेंडरों या एकल टन सिलेंडर",
  "ag": "कृषकीय नर्स टैंक",
  "msm": "एकाधिक छोटे सिलेंडर",
  "bleveLabel": "BLEVE पृथक्करण क्षेत्र दिखाएं",
  "capacity": "कंटेनर क्षमता (लीटर)",
  "bleveMessage": "जिस सामग्री के लिए आपने एक अतिरिक्त निकासी दूरी का चयन किया है, उसे BLEVE के लिए दिखाया जा सकता है।\n\nइसे सक्षम करने के लिए, सेट BLEVE पृथक्करण क्षेत्र दिखाएँ टॉगल को चालू पर सेट करें और कंटेनर की उपयुक्त क्षमता का चयन करें।",
  "noPAZoneMessage": "इस सामग्री के लिए कोई सुरक्षात्मक कार्रवाई दूरी नहीं है। केवल आरंभिक पृथक्करण और रिक्तिकरण क्षेत्र का परिकलन किया गया है",
  "settingsTitle": "सेटिंग्स",
  "spillLocationLabel": "छलकने का स्थान",
  "spillLocationButtonLabel": "छलकने के स्थान की सेटिंग कॉन्फ़िगर करें",
  "IISettingsLabel": "आरंभिक पृथक्करण क्षेत्र",
  "IIButtonLabel": "आरंभिक पृथक्करण सेटिंग कॉन्फ़िगर करें",
  "PASettingsLabel": "सुरक्षात्मक कार्रवाई क्षेत्र",
  "PAButtonLabel": "सुरक्षात्मक कार्रवाई सेटिंग कॉन्फ़िगर करें",
  "downwindSettingsLabel": "हवा के रुख वाला क्षेत्र",
  "downwindButtonLabel": "हवा के रुख की सेटिंग कॉन्फ़िगर करें",
  "fireSettingsLabel": "अग्नि पृथक्करण क्षेत्र",
  "fireButtonLabel": "अग्नि पृथक्करण सेटिंग कॉन्फ़िगर करें",
  "bleveSettingsLabel": "BLEVE पृथक्करण क्षेत्र",
  "bleveButtonLabel": "BLEVE सेटिंग कॉन्फ़िगर करें",
  "style": "शैली",
  "lineStyles": {
    "esriSLSDash": "डैश",
    "esriSLSDashDot": "डैश डॉट",
    "esriSLSDashDotDot": "डैश डॉट डॉट",
    "esriSLSDot": "बिंदु",
    "esriSLSLongDash": "लोंग डैश (लंबा डैश)",
    "esriSLSLongDashDot": "लोंग डैश डॉट (लंबा डैश डॉट)",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "शॉर्ट डैश",
    "esriSLSShortDashDot": "शॉर्ट डैश डॉट (छोटा डैश डॉट)",
    "esriSLSShortDashDotDot": "शॉर्ट डैश डॉट डॉट",
    "esriSLSShortDot": "शॉर्ट डॉट",
    "esriSLSSolid": "ठोस"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "पीछे की ओर",
    "esriSFSCross": "क्रॉस",
    "esriSFSDiagonalCross": "तिरछा/विकर्ण",
    "esriSFSForwardDiagonal": "आगे करें",
    "esriSFSHorizontal": "क्षैतिज",
    "esriSFSNull": "Null",
    "esriSFSSolid": "ठोस",
    "esriSFSVertical": "लंबवत"
  },
  "resultsTitle": "परिणाम",
  "publishERGBtn": "प्रकाशित करें",
  "ERGLayerName": "प्रकाशित ERG लेयर का नाम",
  "invalidERGLayerName": "लेयर के नाम में केवल अक्षरांकीय वर्ण और अंडरस्कोर होना चाहिए",
  "missingERGLayerName": "ERG के लिए आपको नाम दर्ज करना होगा",
  "publishingFailedLayerExists": "प्रकाशन विफल: आपके पास पहले से ही (0) नाम की एक फ़ीचर सेवा है। कृपया दूसरा नाम चुनें।",
  "checkService": "सेवा की जाँच करें: {0}",
  "createService": "सेवा बनाएँ: {0}",
  "unableToCreate": "बनाने में अक्षम: {0}",
  "addToDefinition": "परिभाषा में जोड़ें: {0}",
  "successfullyPublished": "सफलतापूर्वक प्रकाशित वेब लेयर{0}वेब लेयर प्रबंधित करें",
  "userRole": "सेवा तैयार करने में अक्षम हैं, क्योंकि उपयोगकर्ता को अनुमति नहीं है",
  "transparency": "पारदर्शिता",
  "outline": "आउटलाइन",
  "fill": "भरें (स्टाइल के ठोस पर सेट होने पर ही रंग लागू होत हैं)",
  "createERGBtn": "क्षेत्र निर्मित करें",
  "clearERGBtn": "हटाएँ",
  "labelFormat": "लेबल का फ़ॉर्मेट",
  "helpIconTooltip": "छोटे और बड़े छलकाव के आकारों के बीच थ्रेशोल्ड (चरम बिंदु) है:\nद्रव - 55 गैलन (208 लीटर)\nठोस - 60 पाउंड (300 किलोग्राम)",
  "cellWidth": "कोष्ठक की चौड़ाई (x)",
  "cellHeight": "कोष्ठक की ऊँचाई (y)",
  "invalidNumberMessage": "दर्ज की गई संख्या मान्य नहीं है",
  "invalidRangeMessage": "मान 0 से अधिक होना आवश्यक है",
  "gridAngleInvalidRangeMessage": "मान -89.9 और 89.9 के बीच होना चाहिए",
  "formatIconTooltip": "फ़ॉर्मेट आउटपुट",
  "setCoordFormat": "निर्देशांक फ़ॉर्मेट स्ट्रिंग को सेट करें",
  "prefixNumbers": "धनात्मक और ऋणात्मक संख्याओं के आगे '+/-' जोड़ें",
  "cancelBtn": "रद्द करें",
  "applyBtn": "लागू करें",
  "comfirmInputNotation": "इनपुट नोटेशन की पुष्टि करें",
  "notationsMatch": "ये नोटेशन आपके इनपुट से मेल खाते हैं, कृपया जिसका आप इस्तेमाल करना चाहते हैं, उसकी पुष्टि करें:",
  "missingLayerNameMessage": "प्रकाशित करने से पहले आपको वैध लेयर का नाम दर्ज करना होगा",
  "parseCoordinatesError": "निर्देशांकों की व्याख्या करने में सक्षम नहीं। कृपया अपना इनपुट जांचें।",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "दशमलव डिग्री - अक्षांश/देशांतर",
  "DDLongLatNotation": "दशमलव डिग्री - देशांतर/अक्षांश",
  "DDMLatLongNotation": "दशमलव डिग्री मिनट - अक्षांश/देशांतर",
  "DDMLongLatNotation": "दशमलव डिग्री मिनट - देशांतर/अक्षांश",
  "DMSLatLongNotation": "दशमलव डिग्री सेकंड - देशांतर/अक्षांश",
  "DMSLongLatNotation": "दशमलव डिग्री सेकंड - अक्षांश/देशांतर",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - बैंड लेटर",
  "UTMHemNotation": "UTM - गोलार्ध (N/S)"
});