define({
  "_widgetLabel": "المحرر الذكي",
  "_featureAction_SmartEditor": "المحرر الذكي",
  "noEditPrivileges": "لا يحتوي حسابك على أذونات لإنشاء أو تعديل البيانات.",
  "widgetActive": "نشط",
  "widgetNotActive": "غير نشط",
  "pressStr": "اضغط ",
  "ctrlStr": " CTRL ",
  "snapStr": " لتمكين الالتقاط",
  "noAvailableTempaltes": "لا توجد أي قوالب",
  "editorCache": " - ذاكرة التخزين المؤقت للمحرر",
  "presetFieldAlias": "حقل",
  "presetValue": "قيمة معينة مُسبقًا",
  "usePresetValues": " استخدم قيمة مُعينة مُسبقًا (معالم جديد فقط)",
  "editGeometry": " تحرير الشكل الهندسي",
  "savePromptTitle": "حفظ المعلم",
  "savePrompt": "هل تريد حفظ المعلم الحالي؟",
  "deletePromptTitle": "حذف المعلم",
  "deletePrompt": "هل أنت متأكد من رغبتك في حذف المعالم المحددة؟",
  "attachmentLoadingError": "خطأ في تحميل المرفقات",
  "attachmentSaveDeleteWarning": "تحذير: يتم حفظ التغييرات على المرفقات تلقائيًا",
  "autoSaveEdits": "حفظ التحرير تلقائيًا",
  "addNewFeature": "إنشاء معلم جديد",
  "featureCreationFailedMsg": "يتعذر إنشاء سجل/معلم جديد",
  "noRelatedFeatureFoundMsg": "لم يتم العثور على سجلات/معالم ذات صلة",
  "relatedItemTitle": "الطبقة/الجدول ذي الصلة",
  "invalidRelationShipMsg": "يرجى التأكد من أن حقل المفتاح الرئيسي '${parentKeyField}' يحتوي على قيمة صحيحة",
  "pendingFeatureSaveMsg": "يرجى إدخال عمليات تحرير المعلم قبل إنشاء معلم ذي صلة.",
  "attachmentsRequiredMsg": "(*) المرفقات مطلوبة.",
  "filterEditor": {
    "all": "الكل",
    "noAvailableTempaltes": "لا توجد أي قوالب",
    "searchTemplates": "البحث في القوالب"
  },
  "invalidConfiguration": "لم يتم تكوين عنصر واجهة المستخدم أو أن الطبقات التي توجد في التكوين لم تُعد موجودة في الخريطة. يرجى فتح التطبيق في وضع المُنشئ وإعادة تكوين عنصر واجهة المستخدم.",
  "geometryServiceURLNotFoundMSG": "يتعذر الحصول على عنوان URL لخدمة الشكل الهندسي"
});