define({
  "tabs_section_Label": "Вкладки",
  "addTab": "Добавить вкладку",
  "layerName": "Слой",
  "layerType": "Тип анализа",
  "layerLabel": "Надпись",
  "actions": "Действия",
  "closest": "Ближайший объект",
  "proximity": "Близость",
  "summary": "Краткие итоги",
  "select_lbl": "-- Выбрать --",
  "general_setting_Label": "Общие параметры",
  "units_text_lbl": "Единицы расстояния",
  "maximum_distance_lbl": "Максимальное расстояние до ближайшего объекта",
  "buffer_text_lbl": "Надпись буфера",
  "buffer_lbl": "Буферное расстояние",
  "buffer_max_lbl": "Максимальное буферное расстояние",
  "buffer_min_lbl": "Минимальное буферное расстояние",
  "buffer_default_lbl": "Буферное расстояние по умолчанию",
  "not_less_than_max": "Расстояние должно быть меньше максимального расстояния буфера",
  "not_between": "Расстояние должно быть между минимальным и максимальным расстоянием буфера.",
  "not_more_than_min": "Расстояние должно быть больше минимального расстояния буфера",
  "not_valid_number": "Должно быть корректным числом",
  "invalid_value": "${type} значение недопустимо",
  "routing_checkBox": "Включить маршрутизацию",
  "weather_Label": "Настройки погоды",
  "weather_checkBox": "Включить настройку погоды",
  "weather_map_layers": "Выбрать слои погоды...",
  "selected_map_layers": " слои погоды выбраны",
  "instruction_weather": "Отобразить информацию погоды на панели.",
  "instruction_weather_layers": "Отобразить дополнительные слои погоды.",
  "instruction_weather_metric": "Отобразить стандартные/метрические значения.",
  "selectLayers": "Выбрать слои погоды",
  "weather_removed_message": "Опции погоды в этом виджете более недоступны.",
  "currentlySelectedLayer": "Выбрать из слоев карты",
  "missingTabLabel": "В надписи не хватает одной вкладки",
  "missingLayerInWebMap": "Не найдено рабочих слоев.",
  "selectFields": "Выбрать поля",
  "addField": "Добавить поле",
  "sum": "Сумма",
  "min": "Минимум",
  "max": "Максимум",
  "avg": "Среднее арифметическое",
  "count": "ЧИСЛО",
  "area": "ПЛОЩАДЬ",
  "length": "ДЛИНА",
  "count_checkBox": "Показать количество объектов",
  "area_checkBox": "Показать сумму площади",
  "length_checkBox": "Показать сумму длины",
  "max_records": "Достигнуто максимальное ограничение",
  "save_label": "Опции сохранения",
  "save_checkbox": "Включить сохранение",
  "report_label": "Опции отчета",
  "report_checkbox": "Включить отчет",
  "csv_label": "Опции CSV",
  "csv_checkbox": "Экспортировать все поля",
  "display_label": "Опции отображения",
  "display_checkbox": "Отобразить суммарные объекты",
  "snapshot_label": "Опции снимка",
  "snapshot_checkbox": "Включить снимок",
  "must_select_template": "Выберите один из шаблонов редактирования в Опциях сохранения.",
  "count_label": "Подпись числа",
  "area_label": "Подпись площади",
  "length_label": "Подпись длины",
  "invalid_string_width": "Значение слишком длинное. ",
  "layer_type_not_supported": "Тип слоя не поддерживается",
  "groupedSummary": "Количество сгруппированных",
  "groupByField": "Группировать по полю",
  "labelType": "Присоединить надпись",
  "prefix": "Как префикс",
  "suffix": "Как суффикс",
  "need_group_field": "Используйте действие Редактирование для задания поля Группировать по.",
  "fieldTitle": "Поле",
  "typeTitle": "Тип",
  "actionsTitle": "Действия",
  "save_point_checkbox": "Сохранить точки",
  "save_line_checkbox": "Сохранить линии",
  "save_poly_checkbox": "Сохранить полигоны",
  "no_valid_popup_fields": "Отсутствуют корректные поля для всплывающего окна. Используйте действие Редактирование для задания поля.",
  "no_valid_fields": "Отсутствуют корректные поля. Используйте действие Редактирование для задания опций отображения.",
  "incident_label": "Подпись вкладки",
  "locate_incident_label": "Подпись области интереса",
  "incident": "Инцидент",
  "locate_incident": "Найти инцидент",
  "buffer_value": "Буферное расстояние",
  "tab_options": "Анализ",
  "export_options": "Выходные данные",
  "instruction_save": "Сохранить местоположение в сервис объектов.",
  "instruction_snapshot": "Создать веб-карту на основе местоположения.",
  "instruction_report": "Создать печатный отчет местоположения.",
  "instruction_all_fields": "Экспортировать все поля с загрузкой в формате CSV.",
  "data_label": "Установки выходных данных",
  "layer_error": "Слой отсутствует или некорректен.",
  "visibility_checkBox": "Отключить управление видимостью слоя",
  "downloadTab": {
    "reportLegend": "Настройки отчета",
    "textColorLabel": "Выберите цвет заголовка столбца",
    "setButtonLabel": "Установить",
    "printGPServiceLabel": "URL-адрес сервиса печати",
    "logoLabel": "Логотип",
    "logoChooserHint": "Щелкните на значке изображения для смены изображения",
    "footnoteLabel": "Сноска"
  }
});