define({
  "_widgetLabel": "状況認識",
  "locate_incident": "インシデントの特定",
  "reverse_geocoded_address": "最も近い住所",
  "reverse_geocoded_error": "利用不可",
  "now": "現在",
  "wind": "風",
  "SUN": "日",
  "MON": "月",
  "TUE": "火",
  "WED": "水",
  "THU": "木",
  "FRI": "金",
  "SAT": "土",
  "actionLabel": "場所の設定",
  "drawPoint": "ポイントの描画",
  "drawLine": "ラインの描画",
  "drawPolygon": "ポリゴンの描画",
  "saveIncident": "保存",
  "clearIncident": "やり直す",
  "noFeaturesFound": "フィーチャは見つかりませんでした。",
  "downloadCSV": "ダウンロード",
  "sum": "合計",
  "min": "最小",
  "max": "最大",
  "avg": "平均",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "完了",
  "delete_btn": "削除",
  "get_directions": "ルート案内の取得",
  "incident": "インシデント",
  "incidents": "インシデント",
  "buffer": "バッファー",
  "buffers": "バッファー",
  "weather": "天気",
  "poweredBy": "利用アプリケーション:",
  "_featureAction_ActionLabel": "場所の設定",
  "_featureAction_AddRemoveActionLabel": "位置の追加/削除",
  "snapshot": "アプリケーション ID によって作成されたスナップショット フォルダー:",
  "user_credentials": "有効な権限をユーザーが持っていません。",
  "notPolySnapShot": "バッファー距離を指定してからスナップショットを作成してください。",
  "notPolyReport": "レポートに追加する有効な結果がありません。",
  "notValidDownload": "ダウンロードする有効な結果がありません。",
  "of_append": "/",
  "layer_append": "レイヤー",
  "downloadAll": "すべてをダウンロード",
  "createSnapshot": "スナップショットの作成",
  "createReport": "レポートの作成",
  "calculated_results": "集計情報",
  "closest": "最近隣フィーチャ",
  "proximity": "近接",
  "summary": "サマリー",
  "groupedSummary": "グループ化された数",
  "_count": "個数",
  "approximate": "概算",
  "snapshot_name": "スナップショット プロパティを設定",
  "report_name": "レポート プロパティを設定",
  "invalid_snapshot_name": "無効なスナップショット名です。",
  "invalid_report_name": "無効なレポート タイトルです。",
  "orientation": "方向",
  "pageSize": "ページ サイズ",
  "comments": "コメント",
  "choose_group": "グループ",
  "forecast": "予測",
  "select_group": "グループの選択",
  "select_group_instruction": "スナップショットが作成され、選択したグループで共有されます",
  "information_append": " 情報",
  "distance": "距離",
  "buffer_invalid": "${Min} ～ ${max} の範囲の有効な数値を入力してください。"
});