define({
  "tabs_section_Label": "Pestañas",
  "addTab": "Agregar pestaña",
  "layerName": "Capa",
  "layerType": "Tipo de análisis",
  "layerLabel": "Etiqueta",
  "actions": "Acciones",
  "closest": "Entidad más próxima",
  "proximity": "Proximidad",
  "summary": "Resumen",
  "select_lbl": "-- Seleccionar --",
  "general_setting_Label": "Configuración general",
  "units_text_lbl": "Unidades de distancia",
  "maximum_distance_lbl": "Distancia máxima a la entidad más próxima",
  "buffer_text_lbl": "Etiqueta de zona de influencia",
  "buffer_lbl": "Distancia de zona de influencia",
  "buffer_max_lbl": "Distancia de zona de influencia máxima",
  "buffer_min_lbl": "Distancia de zona de influencia mínima",
  "buffer_default_lbl": "Distancia de zona de influencia predeterminada",
  "not_less_than_max": "La distancia debe ser menor que la distancia de zona de influencia máxima",
  "not_between": "La distancia debe estar entre la distancia de zona de influencia mínima y la máxima",
  "not_more_than_min": "La distancia debe ser mayor que la distancia de zona de influencia mínima",
  "not_valid_number": "Debe ser un número válido",
  "invalid_value": "El valor ${type} no es válido",
  "routing_checkBox": "Habilitar enrutamiento",
  "weather_Label": "Configuración de tiempo meteorológico",
  "weather_checkBox": "Habilitar tiempo meteorológico",
  "weather_map_layers": "Seleccionar capas de tiempo meteorológico...",
  "selected_map_layers": " capas de tiempo meteorológico seleccionadas",
  "instruction_weather": "Visualice la información del tiempo meteorológico en el panel.",
  "instruction_weather_layers": "Visualice las capas adicionales de tiempo meteorológico.",
  "instruction_weather_metric": "Visualice valores estándar/métricos.",
  "selectLayers": "Seleccionar capas de tiempo meteorológico",
  "weather_removed_message": "Las opciones del tiempo ya no están disponibles para este widget.",
  "currentlySelectedLayer": "Seleccionar en capas de mapas",
  "missingTabLabel": "Falta la etiqueta en una pestaña al menos",
  "missingLayerInWebMap": "No se ha encontrado ninguna capa operativa.",
  "selectFields": "Selecciona campos",
  "addField": "Agregar campo",
  "sum": "Suma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Media",
  "count": "TOTAL",
  "area": "ÁREA",
  "length": "LONGITUD",
  "count_checkBox": "Mostrar recuento de entidades",
  "area_checkBox": "Mostrar suma de área",
  "length_checkBox": "Mostrar suma de longitud",
  "max_records": "Se ha alcanzado el límite máximo",
  "save_label": "Opciones para guardar",
  "save_checkbox": "Habilitar guardar",
  "report_label": "Opciones de informe",
  "report_checkbox": "Habilitar informe",
  "csv_label": "Opciones de CSV",
  "csv_checkbox": "Exportar todos los campos",
  "display_label": "Opciones de visualización",
  "display_checkbox": "Mostrar entidades de resumen",
  "snapshot_label": "Opciones de instantánea",
  "snapshot_checkbox": "Habilitar instantánea",
  "must_select_template": "Selecciona una de las plantillas de edición en Opciones para guardar.",
  "count_label": "Etiqueta de recuento",
  "area_label": "Etiqueta de área",
  "length_label": "Etiqueta de longitud",
  "invalid_string_width": "El valor es demasiado largo. ",
  "layer_type_not_supported": "Tipo de capa no compatible",
  "groupedSummary": "Recuentos agrupados",
  "groupByField": "Agrupar por campo",
  "labelType": "Adjuntar etiqueta",
  "prefix": "Como prefijo",
  "suffix": "Como sufijo",
  "need_group_field": "Use la acción Editar para definir Agrupar por campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Acciones",
  "save_point_checkbox": "Guardar puntos",
  "save_line_checkbox": "Guardar líneas",
  "save_poly_checkbox": "Guardar polígonos",
  "no_valid_popup_fields": "No hay campos válidos en el elemento emergente. Utilice la acción editar para definir un campo.",
  "no_valid_fields": "No hay campos válidos. Utilice la acción editar para definir las opciones de visualización.",
  "incident_label": "Etiqueta de pestaña",
  "locate_incident_label": "Etiqueta de área de interés",
  "incident": "Incidente",
  "locate_incident": "Localizar incidente",
  "buffer_value": "Distancia de zona de influencia",
  "tab_options": "Análisis",
  "export_options": "Salida",
  "instruction_save": "Guarde la ubicación en un servicio de entidades.",
  "instruction_snapshot": "Cree un mapa web basado en la ubicación.",
  "instruction_report": "Cree un informe impreso de la ubicación.",
  "instruction_all_fields": "Exporte todos los campos con una descarga de CSV.",
  "data_label": "Configuración de salida de datos",
  "layer_error": "La capa falta o no es válida.",
  "visibility_checkBox": "Deshabilitar la administración de la visibilidad de la capa",
  "downloadTab": {
    "reportLegend": "Ajustes de informe",
    "textColorLabel": "Seleccionar color para los títulos de las columnas",
    "setButtonLabel": "Establecer",
    "printGPServiceLabel": "Dirección URL del servicio de impresión",
    "logoLabel": "Logo",
    "logoChooserHint": "Haga clic en el icono de la imagen para cambiar la imagen",
    "footnoteLabel": "Nota a pie de página"
  }
});