define({
  "gridTabLabel": "Tinklelis",
  "labelTabLabel": "Žymės",
  "referenceSystemTabLabel": "Atskaitos sistema",
  "gridTabDescription": "Nustatykite tinklelio gardelių sluoksnio atvaizdavimą ir elgseną.",
  "cellOutlineColor": "Gardelės kontūro spalva",
  "cellFillColor": "Gardelės užpildo spalva",
  "transparency": "Permatomumas",
  "cellShapeDropDown": "Gardelės forma",
  "default": "Stačiakampė",
  "hexagon": "Šešiakampė",
  "cellUnitsDropDown": "Gardelės matavimo vienetai",
  "miles": "Mylios",
  "kilometers": "Kilometrai",
  "feet": "Pėdos",
  "meters": "Metrai",
  "yards": "Jardai",
  "nautical-miles": "Jūrmylės",
  "gridOriginDropDown": "Tinklelio pradžia",
  "lowerLeft": "Apačioje kairėje",
  "lowerRight": "Apačioje dešinėje",
  "upperLeft": "Viršuje kairėje",
  "upperRight": "Viršuje dešinėje",
  "center": "Centre",
  "labelTabDescription": "Nustatykite tinklelio žymių sluoksnio atvaizdavimą ir elgseną.",
  "labelSettings": "Žymės stilius",
  "font": "Šriftas",
  "textSize": "Teksto dydis",
  "textColor": "Teksto spalva",
  "halo": "Aureolė",
  "show": "Rodyti",
  "labelTypeDropDown": "Žymės tipas",
  "alphaNumeric": "Raidinis-skaitinis",
  "alphaAlpha": "Raidinis-raidinis",
  "numeric": "Skaitinis",
  "labelDirectionDropDown": "Žymės kryptis",
  "horizontal": "Horizontali",
  "vertical": "Vertikali",
  "labelOriginDropDown": "Žymės kilmė",
  "referenceSystemlTabDescription": "Nustatykite numatytąją koordinačių sistemą.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Užfiksuoti nustatymus – Ši parinktis neleis vartotojui keisti sukonfigūruotų valdiklio nustatymų."
});