define({
  "settings": "Instellingen",
  "titleSettings": "Tekstinstellingen",
  "imageSettings": "Afbeeldingsinstellingen",
  "backgroundColor": "Achtergrondkleur",
  "alignment": "Uitlijning",
  "textSize": "Tekstgrootte",
  "textColor": "Tekstkleur",
  "dataSource": "Gegevensbron",
  "chartSettings": "Grafiekinstellingen",
  "data": "Gegevens",
  "dataLabels": "Datalabels",
  "displayMode": "Weergavemodus",
  "featureOption": "Waarden object per object weergeven",
  "categoryOption": "Waarden op categorie weergeven",
  "countOption": "Objectaantallen op categorie weergeven",
  "fieldOption": "Attribuutwaarden weergeven als diagrammen",
  "categoryField": "Categorieveld",
  "labelField": "Labelveld",
  "valueFields": "Waardevelden",
  "operation": "Werk",
  "sumOption": "Som",
  "averageOption": "Gemiddelde",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "dataFormat": "Datumnotatie",
  "decimalPlaces": "Aantal decimalen",
  "prefix": "Voorvoegsel",
  "suffix": "Achtervoegsel",
  "dataType": "Gegevenstype",
  "featureCount": "Objecttelling",
  "fieldStatistics": "Veldstatistieken",
  "display": "Weergeven",
  "chartColor": "Grafiekkleur",
  "horizontalAxis": "Horizontale as",
  "verticalAxis": "Verticale as",
  "legend": "Legenda",
  "position": "Positie",
  "top": "Boven",
  "bottom": "Onder",
  "useDataSourceSelection": "Gebruik selectie",
  "dataSourceFilterByExtent": "Filter op extent",
  "changeTemplate": "Template wijzigen",
  "numberSettings": "Cijferinstellingen",
  "gaugeSettings": "Meterinstellingen",
  "indicators": "Indicatoren",
  "ifValue": "Als-waarde",
  "and": "en",
  "numberOperatorIsLessThan": "is minder dan",
  "numberOperatorIsGreaterThan": "is meer dan",
  "numberOperatorIsBetween": "is tussen",
  "numberOperatorIsEqual": "is gelijk aan",
  "numberOperatorIsNotEqual": "is niet gelijk aan",
  "then": "Dan",
  "ratio": "Verhouding",
  "trueValue": "Waar-waarde",
  "changeValueColor": "waardekleur wijzigen naar",
  "changeGaugeColor": "meterkleur wijzigen naar",
  "setIndicatorIcon": "indicatorpictogram instellen als",
  "icons": "Icons",
  "style": "Stijl",
  "placement": "Plaatsing",
  "left": "Links",
  "replace": "Vervangen",
  "right": "Rechts",
  "color": "Kleur",
  "categoryExists": "Categorie bestaat!",
  "comboxHint": "Typ of selecteer één",
  "comboxDisableInputHint": "Kies één",
  "sortBy": "Sorteren op",
  "labelAxis": "Label",
  "valueAxis": "Waarde",
  "minPeriod": "Minimale periode",
  "automatic": "Automatisch",
  "periodsWithOutRecords": "Periodes zonder records",
  "nullValue": "Null-waarde",
  "calculatedAsZero": "Berekend als nul",
  "ignored": "Ignored",
  "maxCategories": "Maximale categorieën",
  "useLayerSymbology": "Gebruik de symbologie van de laag",
  "hollowsize": "Holle maat",
  "splitField": "Veld splitsen",
  "parsingperiodTip": "Kan niet berekenen. Te veel tijdsintervallen vanwege de korte parseerperiode.",
  "manyCategoryTip": "Kan diagram niet weergeven. Te veel categorieën.",
  "setColor": "Kleur instellen",
  "setTheColorOf": "Stel dan kleur in van",
  "setTheColorAs": "Stel dan kleur in als",
  "ifStr": "Als",
  "as": "als",
  "is": "is",
  "isNot": "is niet",
  "barCluster": "Staafcluster",
  "individualBar": "Individuele staaf",
  "allOthers": "Alle andere",
  "category": "Categorie",
  "indicatorSum": "SOM",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Stel de indicators correct in.",
  "dataRange": "Databereik",
  "targetValue": "Doelwaarde",
  "currentValue": "Huidige waarde",
  "gaugeColor": "Meterkleur",
  "min": "Minimum",
  "max": "Maximum",
  "displayValueIn": "Data weergeven in",
  "noData": "Geen gegevens",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Waarschuwing",
  "noSettingWaring1": "Klik op een element om de eigenschappen ervan in te stellen.",
  "noSettingWaring2": "Sleep om een element te vergroten/verkleinen of de volgorde ervan aan te passen.",
  "donNotShowAgain": "Niet meer tonen",
  "changeTemplateWarning": "Hierdoor worden al uw instellingen gewist en wordt er een nieuwe en lege template geopend.",
  "requiredFieldWarning": "Deze waarde is vereist:",
  "dataSourceNotSet": "Stel de gegevensbron in.",
  "addIndicatorTip": "Een indicator toevoegen",
  "chooseTemplatePopupTitle": "Een template kiezen",
  "filterExtentTipWithaTag": "U kunt het filter deactiveren d.m.v. <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Extra databron</a> onder tabblad Attribuut.",
  "filterExtentTip": "U kunt het filter deactiveren d.m.v. Extra databron onder tabblad Attribuut.",
  "customColorByCategory": "Aangepaste kleur per categorie",
  "randomColor": "Willekeurige kleur",
  "valueString": "Waarde",
  "fieldString": "Veld",
  "includeThresholdValue": "Drempelwaarde opnemen",
  "percentage": "Percentage",
  "colorSchema": "Kleurenschema",
  "addCategory": "Categorie toevoegen",
  "clickToEdit": "Klik om te bewerken",
  "nullText": "Null",
  "others": "Overig",
  "stringsInTemplate": {
    "name_number": "Nummer",
    "name_gauge": "Meter",
    "name_vertical_gauge": "Verticale meter",
    "name_horizontal_gauge": "Horizontale meter",
    "name_pie": "Taart",
    "name_donut": "Donut",
    "name_bar": "Verticale streep",
    "name_stacked_bar": "Gestapelde staaf",
    "name_percentage_stacked_bar": "Percentage Gestapelde staaf",
    "name_column": "Kolom",
    "name_stacked_column": "Gestapelde kolom",
    "name_percentage_stacked_column": "Percentage gestapelde kolom",
    "name_line": "Lijn",
    "name_area": "Gebied",
    "name_stacked_area": "Gestapeld gebied",
    "name_percentage_stacked_area": "Percentage gestapeld gebied",
    "titleOfTheInfographic": "TITEL VAN DE INFOGRAPHIC",
    "description": "Beschrijving: bijkomende informatie over deze infographic."
  }
});