define({
  "enableUndoRedo": "Ongedaan maken/opnieuw uitvoeren inschakelen",
  "toolbarVisible": "Werkbalk zichtbaar",
  "toolbarOptions": "Werkbalkopties",
  "mergeVisible": "Samenvoegen",
  "cutVisible": "Knippen",
  "reshapeVisible": "Vorm wijzigen",
  "back": "Vorige",
  "label": "Kaartlaag",
  "edit": "Bewerkbaar",
  "update": "Geometrie bijwerken uitschakelen",
  "fields": "Velden",
  "actions": "Acties",
  "editpageName": "Naam",
  "editpageAlias": "Alias",
  "editpageVisible": "Zichtbaar",
  "editpageEditable": "Bewerkbaar",
  "noLayers": "Er zijn geen bewerkbare objectlagen beschikbaar",
  "configureFields": "Laagvelden configureren",
  "useFilterEdit": "Gebruik objecttemplatefilter",
  "display": "Weergeven",
  "autoApplyEditWhenGeometryIsMoved": "Pas de bewerking automatisch toe als de geometrie wordt verplaatst",
  "snappingTolerance": "Stel de snappingtolerantie in in pixels",
  "popupTolerance": "Stel de tolerantie van bewerkingspop-up van het attribuut in in pixels",
  "stickyMoveTolerance": "Stel de sticky movetolerantie in in pixels",
  "usingSaveButton": "Pas geen bewerkingen van attributen toe totdat u op de knop Opslaan geklikt hebt"
});