define({
  "symbolologyTabLabel": "Konfiguriraj simbologiju",
  "facilitiesDescription": "Slojevi mjesta usluge",
  "demographicsDescription": "Demografski sloj",
  "settingsTitle": "Postavke",
  "spillLocationLabel": "Lokacija izljeva",
  "spillLocationButtonLabel": "Konfiguriraj postavke lokacije izljeva",
  "IISettingsLabel": "Zona početne izolacije",
  "IIButtonLabel": "Konfiguriraj postavke početne izolacije",
  "PASettingsLabel": "Zona zaštitnih mjera",
  "PAButtonLabel": "Konfiguriraj postavke zaštitnih mjera",
  "downwindSettingsLabel": "Zona niz vjetar",
  "downwindButtonLabel": "Konfiguriraj postavke niz vjetar",
  "fireSettingsLabel": "Zona izolacije požara",
  "fireButtonLabel": "Konfiguriraj postavke izolacije požara",
  "bleveSettingsLabel": "Zona izolacije BLEVE",
  "bleveButtonLabel": "Konfiguriraj postavke BLEVE",
  "transparency": "Prozirnost",
  "outline": "Obris",
  "fill": "Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Linija s crticom",
    "esriSLSDashDot": "Linija s crticom i točkom",
    "esriSLSDashDotDot": "Linija s crticom i dvije točke",
    "esriSLSDot": "Točka",
    "esriSLSLongDash": "Duga crtica",
    "esriSLSLongDashDot": "Duga crtica i točka",
    "esriSLSNull": "Nema vrijednosti",
    "esriSLSShortDash": "Kratka crtica",
    "esriSLSShortDashDot": "Kratka crtica i točka",
    "esriSLSShortDashDotDot": "Kratka crtica i dvije točke",
    "esriSLSShortDot": "Kratka točka",
    "esriSLSSolid": "Puna linija"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unatrag",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Naprijed",
    "esriSFSHorizontal": "Vodoravni",
    "esriSFSNull": "Nema vrijednosti",
    "esriSFSSolid": "Puna linija",
    "esriSFSVertical": "Uspravno"
  }
});