define({
  "_widgetLabel": "Анализ инцидентов",
  "_featureAction_SetAsIncident": "Установить как инцидент",
  "incident": "Инцидент",
  "weather": "Погода",
  "locate_incident": "Найти инцидент",
  "clear_incidents": "Очистить инциденты",
  "reverse_geocoded_address": "Ближайший адрес",
  "reverse_geocoded_error": "Не доступно",
  "miles": "Мили",
  "kilometers": "Километры",
  "feet": "Футы",
  "meters": "Метры",
  "yards": "Ярды",
  "nauticalMiles": "Морские мили",
  "now": "Сейчас",
  "wind": "ВЕТЕР",
  "SUN": "ВС",
  "MON": "ПН",
  "TUE": "ВТ",
  "WED": "СР",
  "THU": "ЧТ",
  "FRI": "ПТ",
  "SAT": "СБ",
  "defaultTabMsg": "Нет идентифицированных инцидентов.",
  "useMapExtent": "Использовать текущий экстент карты",
  "noFeaturesFound": "Объекты не найдены.",
  "downloadCSV": "ЗАГРУЗИТЬ CSV",
  "sum": "SUM",
  "min": "MIN",
  "max": "MAX",
  "avg": "AVG",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH"
});