define({
  "serviceUrl": "Angi URL for tjeneste:",
  "minIntSpacingLabel": "Minimum rutenettstørrelse",
  "lineOpacityLabel": "Gjennomsiktighet for linje",
  "labelOpacityLabel": "Gjennomsiktighet for etikett",
  "centerLabelOpacityLabel": "Gjennomsiktighet midten av etikett",
  "gridZonePlacementLabel": "Plassering av etiketter i rutenettsonen",
  "verticalLineLabels": "Etiketter for vertikal linje",
  "styleHeaderLabel": "Stil",
  "indexHeaderLabel": "Rutenettkomponent",
  "colorHeaderLabel": "Farge",
  "fontSizeHeaderLabel": "Skriftstørrelse",
  "lineWidthHeaderLabel": "Linjebredde",
  "horizontalLabel": "Vannrett",
  "verticalLabel": "Loddrett",
  "upperLeftLabel": "Øvre venstre",
  "upperRightLabel": "Øvre høyre",
  "lowerLeftLabel": "Nedre venstre",
  "lowerRightLabel": "Nedre høyre",
  "centerLabel": "Senter",
  "errorMessage": "Konfigurasjonssiden inneholder feil som må rettes opp før lagring.",
  "checkBoxLabel": "Vis rutenett når widgeten er lukket",
  "checkBoxLabelDashboard": "Vis rutenett",
  "gzd": "ID for rutenettsone (GZD)",
  "gsid": "100000 meter identifisering av rutenettrute (GSID)",
  "grid10k": "10000 meter rutenettlinjer",
  "grid1k": "1 000 meter rutenettlinjer",
  "grid100m": "100 meter rutenettlinjer",
  "grid10m": "10 meter rutenettlinjer",
  "switchBasemap": "Bytt bakgrunnskart"
});