define({
  "symbolologyTabLabel": "Konfigurovat systém symbolů",
  "facilitiesDescription": "Vrstvy zařízení",
  "demographicsDescription": "Demografická vrstva",
  "settingsTitle": "Nastavení",
  "spillLocationLabel": "Poloha znečištění",
  "spillLocationButtonLabel": "Konfigurovat nastavení polohy znečištění",
  "IISettingsLabel": "Počáteční zóna izolace",
  "IIButtonLabel": "Konfigurovat nastavení počáteční izolace",
  "PASettingsLabel": "Ochranná akční zóna",
  "PAButtonLabel": "Konfigurovat nastavení ochranných opatření",
  "downwindSettingsLabel": "Zóna ve směru větru",
  "downwindButtonLabel": "Konfigurovat nastavení směru větru",
  "fireSettingsLabel": "Protipožární izolační zóna",
  "fireButtonLabel": "Konfigurovat nastavení protipožární izolační zóny",
  "bleveSettingsLabel": "Izolační zóna BLEVE",
  "bleveButtonLabel": "Konfigurovat nastavení BLEVE",
  "transparency": "Průhlednost",
  "outline": "Obrys",
  "fill": "Výplň (barva se použije, pouze pokud je styl nastaven jako plný)",
  "style": "Styl",
  "lineStyles": {
    "esriSLSDash": "Čárkovaná",
    "esriSLSDashDot": "Čerchovaná",
    "esriSLSDashDotDot": "Dvojčerchovaná",
    "esriSLSDot": "Tečka",
    "esriSLSLongDash": "Čárkovaná s dlouhými čárkami",
    "esriSLSLongDashDot": "Čerchovaná s dlouhými čárkami",
    "esriSLSNull": "Prázdný",
    "esriSLSShortDash": "Krátké čárky",
    "esriSLSShortDashDot": "Čerchovaná s krátkými čárkami",
    "esriSLSShortDashDotDot": "Dvojitě čerchovaná s krátkými čárkami",
    "esriSLSShortDot": "Tečkovaná",
    "esriSLSSolid": "Plný"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Dozadu",
    "esriSFSCross": "Křížek",
    "esriSFSDiagonalCross": "Diagonální",
    "esriSFSForwardDiagonal": "Dopředu",
    "esriSFSHorizontal": "Vodorovně",
    "esriSFSNull": "Prázdný",
    "esriSFSSolid": "Plný",
    "esriSFSVertical": "Svisle"
  }
});