define({
  "_widgetLabel": "Преобразование координат",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десятичные градусы – Широта/Долгота",
  "DDLongLatNotation": "Десятичные градусы – Широта/Долгота",
  "DDMLatLongNotation": "Градусы, десятичные минуты – Широта/Долгота",
  "DDMLongLatNotation": "Градусы, десятичные минуты – Широта/Долгота",
  "DMSLatLongNotation": "Градусы минуты секунды – Широта/Долгота",
  "DMSLongLatNotation": "Градусы минуты секунды – Широта/Долгота",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Буква пояса",
  "UTMHemNotation": "UTM  – Полушарие (N/S)",
  "formatInput": "Входной формат",
  "copyAll": "Копировать все",
  "copySuccessful": "Скопировано успешно",
  "copyFailed": "Не удалось скопировать. Используйте ctrl+c в качестве альтернативы.",
  "parseCoordinatesError": "Невозможно обработать координаты. Проверьте входные данные.",
  "comfirmInputNotation": "Подтвердите входное уведомление",
  "latLongWarningMessage": "Выявлено, что значения входных координат для широты и долготы содержат и префикс и суффикс, возвращены значения координат на основе префикса.",
  "inputLabel": "Входные данные",
  "outputLabel": "Выходные данные",
  "cancelButtonLabel": "Отмена",
  "applyButtonLabel": "Применить",
  "posNegPrefixLabel": "Добавьте префикс \"+/-\" для положительных и отрицательных чисел",
  "editCoordinateDialogTitle": "Строка настройки формата координат",
  "rememberDecisionLabel": "Запомнить мой выбор и больше не спрашивать.<br/>",
  "coordinateInputLabel": "Введите координаты или щелкните карту",
  "zoomLabel": "Масштабировать",
  "multipleNotationLabel": "найдены уведомления, соответствующие входным данным. Выберите, что вы хотите использовать:",
  "copyToClipboard": "Копировать в буфер обмена",
  "formatOutput": "Выходной формат",
  "addNewNotation": "Добавить новое уведомление",
  "notationAddedMessage": "Новое обозначение добавлено",
  "addLabel": "Добавить",
  "removeCoordinate": "Удалить координату",
  "expandOutput": "Развернуть выходные данные.",
  "latitudeLabel": "Широта",
  "longitudeLabel": "Долгота",
  "quadrantLabel": "Квадранты",
  "keyLabel": "Ключ",
  "fifteenDegreeLabel": "15Â° Quad",
  "oneDegreeLabel": "1Â° Quad",
  "eastingLabel": "По долготе",
  "northingLabel": "По широте",
  "zoneLabel": "Зона",
  "bandLabel": "Канал",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Grid Sq",
  "hemisphereLabel": "Полушарие"
});