define({
  "_widgetLabel": "Przewodnik reagowania kryzysowego",
  "ergMainPageTitle": "Na podstawie Emergency Response Guidebook 2016",
  "coordInputLabelStart": "Lokalizacja wycieku (DD)",
  "coordInputLabel": "Lokalizacja wycieku",
  "addPointToolTip": "Dodaj lokalizację wycieku",
  "drawPointToolTip": "Kliknij, aby dodać lokalizację wycieku",
  "material": "Materiał",
  "materialPlaceholder": "Rozpocznij wpisywanie, aby wyszukać materiał",
  "table3Message": "Wybrany materiał wymaga podania dodatkowych informacji w przypadku dużych wycieków.\n\nUpewnij się, że zostały wybrane prawidłowe wartości dotyczące prędkości wiatru i pojemnika służącego do transportu.",
  "table2Message": "Wybrany materiał może być źródłem dużej ilości gazów niebezpiecznych dla układu oddechowego w przypadku rozlania go na powierzchni wody.\n\nWarto rozważyć użycie następujących materiałów:\n\n",
  "spillSize": "Rozmiar wycieku",
  "small": "Mały",
  "large": "Duży",
  "fireLabel": "Pokaż pożarową strefę bezpieczeństwa",
  "weatherLabel": "Aktualna pogoda na obszarze wycieku",
  "weatherIntialText": "<br />Aktualizowane po zidentyfikowaniu lokalizacji wycieku",
  "temperature": "Temperatura",
  "wind": "Wiatr",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Nie uzyskano informacji pogodowych. Uaktualnij wartości prędkości wiatru i terminu wycieku ręcznie",
  "windDirection": "Kierunek wiatru (dokąd)",
  "timeOfSpill": "Termin wycieku",
  "day": "Dzień",
  "night": "Noc",
  "windSpeed": "Prędkość wiatru",
  "low": "Niski",
  "moderate": "Umiarkowany",
  "high": "Wysoki",
  "transportContainer": "Pojemnik służący do transportu",
  "rail": "Cysterna kolejowa",
  "semi": "Cysterna ciężarowa lub naczepa",
  "mton": "Zbiorniki wielotonowe",
  "ston": "Kilka małych zbiorników lub zbiornik do jednej tony",
  "ag": "Rolnicze zbiorniki przewożone",
  "msm": "Kilka małych zbiorników",
  "bleveLabel": "Pokaż strefę bezpieczeństwa BLEVE",
  "capacity": "Pojemność zbiornika (litry)",
  "bleveMessage": "Dla wybranego materiału może być pokazana dodatkowa odległość ewakuacji dla strefy BLEVE.\n\nW tym celu zaznacz opcję Pokaż strefę bezpieczeństwa BLEVE i wybierz odpowiednią pojemność zbiornika.",
  "noPAZoneMessage": "Dla tego materiału nie zostały określone odległości działań ochronnych. Zostały wyliczone tylko strefy zagrożenia i strefy ewakuacji",
  "settingsTitle": "Parametry",
  "spillLocationLabel": "Lokalizacja wycieku",
  "spillLocationButtonLabel": "Konfiguruj ustawienia lokalizacji wycieku",
  "IISettingsLabel": "Strefa zagrożenia",
  "IIButtonLabel": "Konfiguruj ustawienia strefy zagrożenia",
  "PASettingsLabel": "Strefa działań ochronnych",
  "PAButtonLabel": "Konfiguruj ustawienia strefy działań ochronnych",
  "downwindSettingsLabel": "Strefa w kierunku wiatru",
  "downwindButtonLabel": "Konfiguruj ustawienia kierunku wiatru",
  "fireSettingsLabel": "Pożarowa strefa bezpieczeństwa",
  "fireButtonLabel": "Konfiguruj ustawienia pożarowej strefy bezpieczeństwa",
  "bleveSettingsLabel": "Strefa bezpieczeństwa BLEVE",
  "bleveButtonLabel": "Konfiguruj ustawienia strefy BLEVE",
  "style": "Nadaj styl",
  "lineStyles": {
    "esriSLSDash": "Przerywana",
    "esriSLSDashDot": "Kreska-kropka",
    "esriSLSDashDotDot": "Kreska-kropka-kropka",
    "esriSLSDot": "Kropka",
    "esriSLSLongDash": "Długa kreska",
    "esriSLSLongDashDot": "Długa kreska-kropka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krótka kreska",
    "esriSLSShortDashDot": "Krótka kreska-kropka",
    "esriSLSShortDashDotDot": "Krótka kreska-kropka-kropka",
    "esriSLSShortDot": "Krótka kropka",
    "esriSLSSolid": "Stały"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Cofnij",
    "esriSFSCross": "Krzyż",
    "esriSFSDiagonalCross": "Po przekątnej",
    "esriSFSForwardDiagonal": "Do przodu",
    "esriSFSHorizontal": "Poziomo",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Stały",
    "esriSFSVertical": "Pionowo"
  },
  "resultsTitle": "Wyniki",
  "publishERGBtn": "Publikuj",
  "ERGLayerName": "Nazwa opublikowanej warstwy ERG",
  "invalidERGLayerName": "Nazwa warstwy może zawierać tylko znaki alfanumeryczne i znaki podkreślenia",
  "missingERGLayerName": "Należy podać nazwę ERG",
  "publishingFailedLayerExists": "Publikowanie nie powiodło się: masz tylko usługę serwisową o nazwie {0}. Wybierz inną nazwę.",
  "checkService": "Sprawdź usługę: {0}",
  "createService": "Utwórz usługę: {0}",
  "unableToCreate": "Nie można utworzyć: {0}",
  "addToDefinition": "Dodaj do definicji: {0}",
  "successfullyPublished": "Pomyślnie opublikowano warstwę internetową{0}Zarządzaj warstwą internetową",
  "userRole": "Nie można utworzyć usługi, ponieważ użytkownik nie ma uprawnień",
  "transparency": "Przezroczystość",
  "outline": "Obrys",
  "fill": "Wypełnienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pełny)",
  "createERGBtn": "Utwórz strefy",
  "clearERGBtn": "Wyczyść",
  "labelFormat": "Format etykiety",
  "helpIconTooltip": "Wartość graniczna między rozmiarem małego i dużego wycieku to:\nciecze — 208 litrów (55 galonów)\nmateriały stałe — 300 kilogramów (60 funtów)",
  "cellWidth": "Szerokość komórki (x)",
  "cellHeight": "Wysokość komórki (y)",
  "invalidNumberMessage": "Wprowadzona wartość nie jest prawidłowa",
  "invalidRangeMessage": "Wartość musi być większa od 0",
  "gridAngleInvalidRangeMessage": "Wartość musi zawierać się w przedziale od -89,9 do 89,9",
  "formatIconTooltip": "Formatuj dane wejściowe",
  "setCoordFormat": "Skonfiguruj ciąg znakowy formatu współrzędnych",
  "prefixNumbers": "Dodaj prefiks '+/-' do liczb dodatnich i ujemnych",
  "cancelBtn": "Anuluj",
  "applyBtn": "Zastosuj",
  "comfirmInputNotation": "Potwierdź notację danych wejściowych",
  "notationsMatch": "liczba znalezionych notacji zgodnych z danymi wejściowymi. Wybierz, której notacji chcesz użyć:",
  "missingLayerNameMessage": "Przed opublikowaniem warstwy należy wprowadzić jej prawidłową nazwę",
  "parseCoordinatesError": "Nie można przeanalizować współrzędnych. Sprawdź dane wejściowe.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Stopnie-Minuty-Sekundy (DMS)",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Stopnie dziesiętne — szerokość/długość geograficzna",
  "DDLongLatNotation": "Stopnie dziesiętne — długość/szerokość geograficzna",
  "DDMLatLongNotation": "Stopnie i minuty dziesiętne — szerokość/długość geograficzna",
  "DDMLongLatNotation": "Stopnie i minuty dziesiętne — długość/szerokość geograficzna",
  "DMSLatLongNotation": "Stopnie, minuty i sekundy — szerokość/długość geograficzna",
  "DMSLongLatNotation": "Stopnie, minuty i sekundy — długość/szerokość geograficzna",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — litera pasa",
  "UTMHemNotation": "UTM — półkula (N/S)"
});