define({
  "enableUndoRedo": "Aktivér Fortryd/Annuller fortryd",
  "toolbarVisible": "Værktøjslinje synlig",
  "toolbarOptions": "Indstillinger for værktøjslinje",
  "mergeVisible": "Sammenlæg",
  "cutVisible": "Klip",
  "reshapeVisible": "Omform",
  "back": "Tilbage",
  "label": "Lag",
  "edit": "Redigérbar",
  "update": "Deaktiver Opdatér geomatri",
  "fields": "Felter",
  "actions": "Handlinger",
  "editpageName": "Navn",
  "editpageAlias": "Alias",
  "editpageVisible": "Synlig",
  "editpageEditable": "Redigérbar",
  "noLayers": "Ingen redigérbare vektorlag er tilgængelige",
  "configureFields": "Konfigurér lagfelter",
  "useFilterEdit": "Brug objektskabelonfilter",
  "display": "Visning",
  "autoApplyEditWhenGeometryIsMoved": "Anvend redigeringen automatisk, når geometrien flyttes",
  "snappingTolerance": "Indstil snapping-tolerancen i pixels",
  "popupTolerance": "Indstil tolerancen for attributredigerings-pop-up'en i pixels",
  "stickyMoveTolerance": "Indstil sticky move-tolerancen i pixels",
  "usingSaveButton": "Anvend ikke redigeringer på attributter, før der klikkes på knappen Gem"
});