define({
  "drsSOEURL": "URL des Data Reviewer-Servers",
  "chartSection": "Anzahl der Ausschnitte/Balken im Diagramm",
  "selectByGeography": "Filter nach Geographie einbeziehen",
  "selectUrl": "Service-Layer für Filter nach Geographie",
  "selectMapUrl": "Service für Filter nach Geographie",
  "geometryServiceURL": "URL des Geometrieservice",
  "includeFieldNames": "Felder auswählen",
  "fieldNames": "Feldnamen",
  "lifecyclePhaseFieldName": "LEBENSZYKLUSPHASE",
  "setSource": "Festlegen",
  "defaultFieldName": "Gewichtung",
  "warning": "Falsche Eingabe",
  "includeDefaultFieldName": "Standardfeldname muss ausgewählt sein",
  "selectFieldWarning": "Mindestens ein Feld muss sichtbar sein",
  "defaultFieldNotVisible": "Standardfeld muss sichtbar sein",
  "batchJobCheckGroup": "batchjobcheckgroup",
  "defaultColumn": "Standard",
  "visibleColumn": "Sichtbar",
  "fieldNameColumn": "Name des Dashboard-Feldes",
  "aliasColumn": "Alias"
});