define({
  "_widgetLabel": "Situatsiooniteadlikkus",
  "locate_incident": "Paiguta juhtum",
  "reverse_geocoded_address": "Lähim aadress",
  "reverse_geocoded_error": "Ei ole kättesaadav",
  "now": "KOHE",
  "wind": "WIND",
  "SUN": "P",
  "MON": "E",
  "TUE": "T",
  "WED": "K",
  "THU": "N",
  "FRI": "R",
  "SAT": "L",
  "actionLabel": "Määra asukoht",
  "drawPoint": "Joonista punkt",
  "drawLine": "Joonista joon",
  "drawPolygon": "Joonista polügoon",
  "saveIncident": "Salvesta",
  "clearIncident": "Alusta uuesti",
  "noFeaturesFound": "Objekte ei leitud.",
  "downloadCSV": "Allalaadimine",
  "sum": "Summa",
  "min": "Miinimum",
  "max": "Maksimum",
  "avg": "Keskmine",
  "count": "KOGUARV",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "Valmis",
  "delete_btn": "Kustuta",
  "get_directions": "Hangi juhised",
  "incident": "Juhtum",
  "incidents": "Juhtumid",
  "buffer": "Puhver",
  "buffers": "Puhvrid",
  "weather": "Ilm",
  "poweredBy": "Platvorm:",
  "_featureAction_ActionLabel": "Määra asukoht",
  "_featureAction_AddRemoveActionLabel": "Lisa/eemalda asukoht",
  "snapshot": "Hetktõmmise on loonud rakenduse id:",
  "user_credentials": "Kasutajal puuduvad sobivad õigused.",
  "notPolySnapShot": "Enne hetktõmmise loomist peate määrama puhvri ulatuse.",
  "notPolyReport": "Aruandele pole lisada ühtegi sobivat tulemust.",
  "notValidDownload": "Allalaadimiseks pole ühtegi sobivat tulemust.",
  "of_append": "/",
  "layer_append": "kiht",
  "downloadAll": "Laadi kõik alla",
  "createSnapshot": "Loo hetktõmmis",
  "createReport": "Koosta aruanne",
  "calculated_results": "Kokkuvõtlik teave",
  "closest": "Lähim objekt",
  "proximity": "Lähedus",
  "summary": "Kokkuvõte",
  "groupedSummary": "Rühmitatud koguarvud",
  "_count": "Kogus",
  "approximate": "ligikaudne",
  "snapshot_name": "Määra hetktõmmise atribuudid",
  "report_name": "Määra aruande atribuudid",
  "invalid_snapshot_name": "Hetktõmmise nimi ei sobi.",
  "invalid_report_name": "Vigane aruande pealkiri.",
  "orientation": "Orientatsioon",
  "pageSize": "Lehe suurus",
  "comments": "Kommentaarid",
  "choose_group": "Grupid",
  "forecast": "Prognoos",
  "select_group": "Vali rühm",
  "select_group_instruction": "Luuakse hetktõmmis ja seda jagatakse valitud rühmaga",
  "information_append": " Info",
  "distance": "VAHEMAA",
  "buffer_invalid": "Sisestage sobiv arv vahemikus ${min} kuni ${max}"
});