define({
  "drsSOEURL": "URL strežnika recenzenta podatkov",
  "chartSection": "Število izsekov/stolpcev na grafikonu",
  "selectByGeography": "Vključi filter po prostoru",
  "selectUrl": "Storitveni sloj prostorskega filtra",
  "selectMapUrl": "Storitev prostorskega filtra",
  "geometryServiceURL": "URL geometrijske storitve",
  "includeFieldNames": "Izberite polja",
  "fieldNames": "Imena polj",
  "lifecyclePhaseFieldName": "FAZA ŽIVLJENJSKEGA CIKLA",
  "setSource": "Nastavi",
  "defaultFieldName": "resnost",
  "warning": "Nepravilen vnos",
  "includeDefaultFieldName": "Privzeto ime polja mora biti izbrano",
  "selectFieldWarning": "Vidno mora biti vsaj eno polje",
  "defaultFieldNotVisible": "Privzeto polje mora biti vidno",
  "batchJobCheckGroup": "opravilo množičnega preverjanja po skupinah",
  "defaultColumn": "Privzeto",
  "visibleColumn": "Vidno",
  "fieldNameColumn": "Ime polja nadzorne plošče",
  "aliasColumn": "Vzdevek"
});