define({
  "serviceUrl": "Définir l'URL du service :",
  "minIntSpacingLabel": "Taille de grille minimale",
  "lineOpacityLabel": "Opacité des lignes",
  "labelOpacityLabel": "Opacité des étiquettes",
  "centerLabelOpacityLabel": "Opacité du centre des étiquettes",
  "gridZonePlacementLabel": "Placement des étiquettes dans la zone de la grille",
  "verticalLineLabels": "Etiquettes de lignes verticales",
  "styleHeaderLabel": "Style",
  "indexHeaderLabel": "Composant de grille",
  "colorHeaderLabel": "Couleur",
  "fontSizeHeaderLabel": "Taille de police",
  "lineWidthHeaderLabel": "Largeur de la ligne",
  "horizontalLabel": "Horizontale",
  "verticalLabel": "Verticale",
  "upperLeftLabel": "Supérieur gauche",
  "upperRightLabel": "Supérieur droit",
  "lowerLeftLabel": "Inférieur gauche",
  "lowerRightLabel": "Inférieur droit",
  "centerLabel": "Centre",
  "errorMessage": "La page de configuration contient des erreurs. Corrigez-les avant de l’appliquer.",
  "checkBoxLabel": "Afficher la grille lorsque le widget est fermé",
  "checkBoxLabelDashboard": "Afficher la grille",
  "gzd": "Indicateur de zone de grille",
  "gsid": "Identifiant du carré de 100 000 mètres",
  "grid10k": "Lignes de la grille de 10 000 mètres",
  "grid1k": "Lignes de la grille de 1 000 mètres",
  "grid100m": "Lignes de la grille de 100 mètres",
  "grid10m": "Lignes de la grille de 10 mètres",
  "switchBasemap": "Changer de fond de carte"
});