define({
  "gridTabLabel": "Rutenett",
  "labelTabLabel": "Etiketter",
  "referenceSystemTabLabel": "Referansesystem",
  "gridTabDescription": "Angi utseende og virkemåte for rutenettcellene.",
  "cellOutlineColor": "Omrissfarge for celle",
  "cellFillColor": "Fyllfarge for celle",
  "transparency": "Gjennomsiktighet",
  "cellShapeDropDown": "Celleform",
  "default": "Rektangel",
  "hexagon": "Heksagon",
  "cellUnitsDropDown": "Celleenheter",
  "miles": "Miles",
  "kilometers": "Kilometer",
  "feet": "Fot",
  "meters": "Meter",
  "yards": "Yard",
  "nautical-miles": "Nautiske mil",
  "gridOriginDropDown": "Rutenettopprinnelse",
  "lowerLeft": "Nedre-venstre",
  "lowerRight": "Nedre-høyre",
  "upperLeft": "Øvre-venstre",
  "upperRight": "Øvre-høyre",
  "center": "Senter",
  "labelTabDescription": "Angi utseende og virkemåte for rutenettetiketter.",
  "labelSettings": "Etikettstil",
  "font": "Skrifttype",
  "textSize": "Tekststørrelse",
  "textColor": "Tekstfarge",
  "halo": "Glorie",
  "show": "Vis",
  "labelTypeDropDown": "Etiketttype",
  "alphaNumeric": "Alfa-numerisk",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Numerisk",
  "labelDirectionDropDown": "Etikettretning",
  "horizontal": "Vannrett",
  "vertical": "Loddrett",
  "labelOriginDropDown": "Etikettopprinnelse",
  "referenceSystemlTabDescription": "Angi standard referansesystem",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Lås innstillinger – dette hindrer at brukerne ender noen av de konfigurerte innstillingene i miniprogrammet"
});