define({
  "_widgetLabel": "Prijava nadzorniku",
  "select": "Izberi",
  "draw": "Nariši",
  "chooseALayer": "Izberi sloj",
  "clickAFeature": "Za izbiro geoobjekta na karti kliknite nanj.",
  "loadingFeatures": "Pridobivanje podrobnosti o izbranem geoobjektu...",
  "errorTitle": "Napaka",
  "errorIdentify": "Prepoznajte napake geoobjekta. Za podrobnosti preverite dnevnik konzole.",
  "infoWindowTitle": "Podrobnosti",
  "layerLabel": "Ime sloja",
  "reviewStatusLabel": "Preglej stanje",
  "selectReviewStatusAdd": "Dodaj geoobjekt",
  "selectReviewStatusDelete": "Izbriši geoobjekt",
  "selectReviewStatusMove": "Premakni geoobjekt",
  "selectReviewStatusReshape": "Preoblikuj geoobjekt",
  "drawReviewStatusMissing": "Manjkajoči geoobjekti",
  "drawReviewStatusPosition": "Položajna napaka",
  "drawReviewStatusShape": "Napaka oblike",
  "drawReviewStatusAttribute": "Napaka atributa",
  "notesLabel": "Opombe",
  "severityLabel": "Resnost",
  "reportedByLabel": "Prijavil",
  "reportedByDefault": "anonimno",
  "reportButton": "Prijava",
  "reportMessage": "Prijava prejeta",
  "errorReportMessage": "Pri prijavi vašega geoobjekta je prišlo do napake",
  "drawErrorInstructions": "Izberite točko, linijo ali poligon in narišite geometrijo napake na karti:",
  "errorMapService": "Pri pridobivanju informacij o kartni storitvi je prišlo do napake.",
  "noFeatureSelected": "Na lokaciji klika geoobjekti niso bili najdeni",
  "selectFeatureMapPoint": "Kliknite, da izberete geoobjekt",
  "drawFeatureMapPoint": "Kliknite, da dodate točko",
  "popupMessage": "Sporočilo",
  "popupError": "Napaka",
  "manyFeaturesSelected": "Najden je več kot eden geoobjekt. Povečajte in izberite geoobjekt za prijavo."
});