define({
  "chartSettingLabel": "차트 설정",
  "addNewLabel": "새로 추가",
  "generalSettingLabel": "일반 설정",
  "searchSourceSettingLabel": "원본 설정 검색",
  "layerChooser": {
    "title": "차트를 만들 레이어 선택",
    "selectPolygonLayerLabel": "레이어 선택",
    "selectPolygonLayerHintText": "힌트: 여러 차트를 구성하는 경우에는 레이어의 지오메트리 유형이 같아야 함",
    "selectRelatedTableLayerLabel": "레이어와 관련된 테이블 선택",
    "selectRelatedTableLayerHintText": "힌트: 숫자 필드가 있는 테이블만 보임",
    "errorInSelectingPolygonLayer": "릴레이트 포인트 레이어가 있는 레이어를 선택하세요.",
    "errorInSelectingRelatedLayer": "올바른 릴레이트 테이블/레이어를 선택하세요.",
    "polygonLayerNotHavingRelationships": "선택한 레이어에는 릴레이트 테이블/레이어가 없습니다."
  },
  "ChartSetting": {
    "sectionTitle": "섹션 제목",
    "sectionTitleHintText": "힌트: 섹션 헤더 제목에 보임",
    "chartTitle": "차트 제목",
    "chartTitleHintText": "힌트: 차트 상단 가운데 표시됨",
    "chartDescription": "설명",
    "chartDescriptionHintText": "힌트: 차트 아래 표시됨",
    "chartType": "차트 유형",
    "barChart": "막대형 차트",
    "pieChart": "원형 차트",
    "polarChart": "극좌표형 차트",
    "dataSeriesField": "데이터 시리즈 필드",
    "labelField": "레이블 필드",
    "chartColor": "차트 색상",
    "singleColor": "단일 색상",
    "colorByTheme": "테마별 색상",
    "colorByFieldValue": "필드 값별 색상",
    "xAxisTitle": "X축 제목",
    "xAxisHintText": "힌트: X축 제목",
    "yAxisTitle": "Y축 제목",
    "yAxisHintText": "힌트: Y축 제목",
    "fieldColorLabel": "레이블",
    "fieldColorColor": "색상",
    "defaultFieldSelectLabel": "선택",
    "errMsgFieldValuesNotFound": "선택한 필드의 값을 찾을 수 없음",
    "errMsgSectionTitle": "섹션 제목을 입력하세요.",
    "errMsgFieldByValue": "필드 값을 선택하세요.",
    "settingTabTitle": "설정",
    "layoutTabTitle": "레이아웃",
    "polarChartSelectFieldsHintText": "힌트: 극좌표형 차트를 생성할 필드 선택",
    "visibilityText": "가시성",
    "fieldNameText": "필드 이름",
    "aliasNameText": "별칭",
    "errMsgPolarFieldsRequired": "극좌표형 차트를 생성하려면 3개 이상의 필드를 선택하세요.",
    "polarChartPolygonFillLabel": "폴리곤 채우기",
    "polarChartPolygonFillHintText": "힌트: 극좌표형 그래프에 폴리곤 채우기를 표시하려면 체크 박스 선택",
    "viewLayoutLabel": "레이아웃",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "일반 설정",
    "locationSymbolLabel": "그래픽 위치 심볼",
    "locationSymbolHintText": "힌트: 주소와 클릭 위치의 심볼을 나타내는 데 사용됨",
    "refreshIntervalLabel": "새로 고침 간격",
    "refreshIntervalHintText": "힌트: 차트를 새로 고침하는 간격으로 사용됩니다. 1~1440분 사이의 값을 지정하세요.",
    "errMsgRefreshInterval": "1~1440분 사이의 새로 고침 간격을 지정하세요.",
    "symbolPickerPreviewText": "미리 보기:",
    "showToolToSelectLabel": "위치 버튼 설정",
    "showToolToSelectHintText": "힌트: 맵을 클릭할 때 위치를 항상 설정하는 대신 맵에서 위치를 설정하는 버튼을 제공합니다."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "원본 설정 검색",
    "searchSourceSettingTitle": "원본 설정 검색",
    "searchSourceSettingTitleHintText": "지오코드 서비스 또는 피처 레이어를 추가하여 검색 원본으로 구성합니다. 이와 같은 지정된 원본에 따라 검색 상자 내에서 검색 가능한 항목이 결정됩니다.",
    "addSearchSourceLabel": "검색 원본 추가",
    "featureLayerLabel": "피처 레이어",
    "geocoderLabel": "지오코더",
    "nameTitle": "이름",
    "generalSettingLabel": "일반 설정",
    "allPlaceholderLabel": "모두 검색하기 위한 플레이스 홀더 텍스트:",
    "allPlaceholderHintText": "힌트: 모든 레이어와 지오코더를 검색하는 동안 플레이스 홀더로 나타낼 텍스트를 입력합니다.",
    "generalSettingCheckboxLabel": "발견한 피처 또는 위치에 대해 팝업 보기",
    "countryCode": "국가 또는 지역 코드",
    "countryCodeEg": "예시: ",
    "countryCodeHint": "이 값을 비워 두면 모든 국가와 지역이 검색됩니다.",
    "questionMark": "?",
    "searchInCurrentMapExtent": "현재 맵 범위에서만 검색",
    "zoomScale": "확대 축척",
    "locatorUrl": "지오코더 URL",
    "locatorName": "지오코더 이름",
    "locatorExample": "사례",
    "locatorWarning": "이 지오코딩 서비스 버전은 지원되지 않습니다. 위젯은 지오코딩 서비스 10.0 이상을 지원합니다.",
    "locatorTips": "지오코딩 서비스에서 추천 기능을 지원하지 않기 때문에 추천을 사용할 수 없습니다.",
    "layerSource": "레이어 원본",
    "setLayerSource": "레이어 원본 설정",
    "setGeocoderURL": "지오코더 URL 설정",
    "searchLayerTips": "피처 서비스에서 페이지 매김 기능을 지원하지 않기 때문에 제안 사항을 사용할 수 없습니다.",
    "placeholder": "플레이스 홀더 텍스트",
    "searchFields": "검색 필드",
    "displayField": "디스플레이 필드",
    "exactMatch": "정확히 일치",
    "maxSuggestions": "최대 추천 수",
    "maxResults": "최대 결과",
    "enableLocalSearch": "로컬 검색 사용",
    "minScale": "최소 축척",
    "minScaleHint": "맵 축척이 이 축척보다 큰 경우 로컬 검색이 적용됨",
    "radius": "반경",
    "radiusHint": "위치와 가장 가까운 후보가 제일 먼저 반환되도록 지오코딩 후보의 순위를 올리는 데 사용되는 현재 맵 중심 주변 영역의 반경을 지정함",
    "meters": "미터",
    "setSearchFields": "검색 필드 설정",
    "set": "설정",
    "fieldName": "이름",
    "invalidUrlTip": "${URL} URL이 잘못되었거나 접근할 수 없습니다."
  }
});