define({
  "labelBookmarkName": "Marcar a visualização atual",
  "labelPlay": "Reproduzir todos",
  "labelStop": "Parar",
  "labelDelete": "Excluir",
  "placeholderBookmarkName": "Nome do marcador",
  "errorNameExist": "O marcador existe!",
  "errorNameNull": "Nome de marcador inválido!",
  "editTip": "Editar marcadores",
  "exitEditTip": "Sair do modo de edição",
  "syncTip": "Sincronizar",
  "cardsTips": "Visualização da grade",
  "listTips": "Visualização da lista",
  "addBtn": "Adicionar",
  "deleteBtn": "Excluir",
  "changeThumbnailTip": "Alterar miniatura",
  "dragReorderTip": "Segurar e arrastar para reordenar",
  "deleteBtnTip": "Excluir o marcador",
  "editBtnTip": "Editar o marcador",
  "withVisibility": "Com visibilidade de camada",
  "searchBookmark": "Pesquisar",
  "bookmarksFromConfig": "Marcadores pré-configurados",
  "bookmarksFromCache": "Marcadores temporários locais",
  "notice": "Aviso",
  "changeNoticeTips": "As alterações serão salvas somente no cache do seu navegador. A sincronização entre o widget e a sua configuração é desconectada quando você faz modificações.",
  "syncNoticeTips": "Isto irá apagar todas as suas modificações e restaurar os marcadores configurados.",
  "dontShowAgain": "Não mostrar novamente",
  "saveVisibility": "Salvar visibilidade da camada",
  "_widgetLabel": "Marcador"
});