define({
  "layerSelect": "Vælg billedlaget",
  "displayMeasureResultInPopup": "Vis måleresultater i en pop-up",
  "angularUnitSelect": "Standardenhed for vinkel",
  "linearUnitSelect": "Standardenhed for linje",
  "areaUnitSelect": "Standardenhed for område",
  "displayOperationSelect": "Vælg målehandlinger",
  "errorSectionMessage": "Ingen af lagene understøtter målefunktioner",
  "unitLabel": {
    "esriInches": "Tommer",
    "esriFeet": "Fod",
    "esriYards": "Yards",
    "esriMiles": "Miles",
    "esriNauticalMiles": "Sømil",
    "esriMillimeters": "Millimeter",
    "esriCentimeters": "Centimeter",
    "esriDecimeters": "Decimeter",
    "esriMeters": "Meter",
    "esriKilometers": "Kilometer",
    "esriDURadians": "Radianer",
    "esriDUDecimalDegrees": "Grader",
    "esriSquareInches": "Kvadrattommer",
    "esriSquareFeet": "Kvadratfod",
    "esriSquareYards": "Kvadrat-yards",
    "esriAcres": "Acres",
    "esriSquareMiles": "Kvadrat-miles",
    "esriSquareMillimeters": "Kvadratmillimeter",
    "esriSquareCentimeters": "Kvadratcentimeter",
    "esriSquareDecimeters": "Kvadratdecimeter",
    "esriSquareMeters": "Kvadratmeter",
    "esriAres": "Acres",
    "esriHectares": "Hektarer",
    "esriSquareKilometers": "Kvadratkilometer"
  },
  "operationLabel": {
    "esriMensurationPoint": "Position",
    "esriMensurationDistanceAndAngle": "Afstand og vinkel",
    "esriMensurationAreaAndPerimeter": "Område og omkreds",
    "esriMensurationHeightFromBaseAndTop": "Højde: Base til top",
    "esriMensurationHeightFromBaseAndTopShadow": "Højde: Base til top-Skygge",
    "esriMensurationHeightFromTopAndTopShadow": "Højde: Top til top-Skygge",
    "esriMensurationCentroid": "Geometrisk centrum",
    "esriMensurationPoint3D": "Position (3D)",
    "esriMensurationDistanceAndAngle3D": "Afstand og vinkel (3D)",
    "esriMensurationAreaAndPerimeter3D": "Område og omkreds (3D)",
    "esriMensurationCentroid3D": "Geometrisk centrum (3D)"
  }
});