define({
  "queries": "Abfragen",
  "addNew": "Neue hinzufügen",
  "newQuery": "Neue Abfrage",
  "queryLayer": "Abfrage-Layer",
  "setSource": "Festlegen",
  "setDataSource": "Datenquelle festlegen",
  "name": "Name",
  "querySource": "Datenquelle",
  "queryName": "Task-Name",
  "queryDefinition": "Filterdefinition",
  "resultsSetting": "Ergebniseinstellung",
  "symbolSetting": "Symboleinstellung",
  "resultSettingTip": "Definieren Sie, welche Ausgabeergebnisse und wie sie angezeigt werden sollen.",
  "resultItemTitle": "Titel der einzelnen Ergebniselemente",
  "resultItemContent": "Folgende Feldattribute werden angezeigt",
  "fieldsSetTip": "Aktivieren Sie die Felder, die angezeigt werden sollen. Wählen Sie ein Feld aus, um dessen Alias zu aktualisieren, es zu sortieren und zu formatieren.",
  "addField": "Feld hinzufügen",
  "visibility": "Sichtbarkeit",
  "alias": "Alias",
  "specialType": "Besonderer Typ",
  "actions": "Aktionen",
  "none": "Kein",
  "link": "Link",
  "image": "Bild",
  "noField": "Kein Feld",
  "operationalLayerTip": "Ergebnis als operationalen Layer hinzufügen",
  "setLayerSymbolTip": "Legen Sie das Symbol für die Abfrageergebnisse fest: ",
  "setSelectedSymbolTip": "Legen Sie das Symbol des ausgewählten Features fest.",
  "notUseFilter": "Keinen Filter verwenden",
  "setSourceTip": "Legen Sie die Abfragequelle fest.",
  "setFilterTip": "Legen Sie den Filter ordnungsgemäß fest.",
  "ok": "OK",
  "cancel": "Abbrechen",
  "noFilterTip": "Dieser Abfrage-Task listet alle Features in der angegebenen Datenquelle ohne definierten Filterausdruck auf.",
  "relationships": "Beziehungen",
  "addRelationshipLayer": "Neue Beziehung hinzufügen",
  "relatedTo": "Bezieht sich auf",
  "selectOption": "Wählen Sie..",
  "resultItemSorting": "Sortierung von Ergebniselementen",
  "field": "Feld",
  "sortingOrder": "Reihenfolge",
  "configureFieldsTip": "Konfigurieren Sie die Felder, nach denen das Abfrageergebnis sortiert wird.",
  "setSortingFields": "Sortierfelder festlegen",
  "ascending": "Aufsteigend",
  "descending": "Absteigend",
  "sortBy": "Sortieren nach",
  "thenBy": "Dann nach",
  "addTask": "Task hinzufügen",
  "noTasksTip": "Keine Abfragen konfiguriert. Klicken Sie auf \"${newQuery}\", um eine neue hinzuzufügen.",
  "infoText": "Info",
  "filters": "Filter",
  "results": "Ergebnisse",
  "optionsText": "Optionen",
  "summaryText": "Zusammenfassung",
  "attributeFilter": "Attributfilter",
  "attributeFilterTip": "Definieren Sie Attributausdrücke für die Verwendung in Widgets, um den Abfrage-Layer zu filtern.",
  "defineWhereClause": "Definieren Sie eine WHERE-Klausel für die Abfrage.",
  "noExpressionDefinedTip": "Kein Ausdruck definiert. Alle Datensätze werden zurückgegeben.",
  "setExpressions": "Ausdrücke festlegen",
  "spatialFilter": "Räumliche Filter",
  "spatialFilterTip": "Wählen Sie, welche räumlichen Filter Endbenutzern zur Verfügung gestellt werden sollen.",
  "defaultOption": "Standard",
  "useCurrentExtentTip": "Nur Features in der aktuellen Kartenausdehnung zurückgeben",
  "useDrawGraphicTip": "Nur Features zurückgeben, die die auf der Karte gezeichnete Form schneiden",
  "useFeaturesTip": "Nur Features zurückgeben, die eine räumliche Beziehung mit Features in einem anderen Layer aufweisen",
  "noSpatialLimitTip": "Features in der vollen Ausdehnung der Karte zurückgeben",
  "drawingTools": "Zeichenwerkzeuge auswählen",
  "bufferSettings": "Pufferoption aktivieren",
  "defaultDistance": "Standardentfernung",
  "bufferDistance": "Pufferabstand",
  "defaultUnit": "Standardeinheit",
  "miles": "Meilen",
  "kilometers": "Kilometer",
  "feet": "Fuß",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Seemeilen",
  "availableSpatialRelationships": "Regeln für räumliche Beziehungen auswählen",
  "setSpatialRelationships": "Räumliche Beziehungen festlegen",
  "availability": "Verfügbarkeit",
  "relationship": "Beziehung",
  "label": "Beschriftung",
  "intersect": "Überschneiden",
  "contain": "Enthalten",
  "areContainedIn": "Sind enthalten",
  "cross": "Kreuzen",
  "envelopeIntersect": "Envelope-Überschneidung",
  "overlap": "Überlappen",
  "areOverlapped": "Werden überlappt",
  "touch": "Berühren",
  "within": "Innerhalb",
  "areWithin": "Befinden sich in",
  "indexIntersect": "Index-Überschneidung",
  "itemTitle": "Elementtitel",
  "displayFields": "Felder anzeigen",
  "sortingFields": "Ergebniselemente sortieren",
  "setDisplayFields": "Anzeigefelder festlegen",
  "symbol": "Symbol",
  "setSymbol": "Benutzerdefiniertes Symbol verwenden",
  "changeSymbolAtRuntime": "Symboländerung zur Laufzeit zulassen",
  "serviceSymbolTip": "Vom Layer definierte Symbole verwenden",
  "exportTip": "Exportieren von Ergebnissen zulassen",
  "keepResultsTip": "Ergebnisse auf der Karte beibehalten, nachdem das Widget geschlossen wurde",
  "queryRelatedRecords": "Zugehörige Datensätze abfragen",
  "createLayerForTaskTip": "Festlegen, wie Layer mit dem Abfrage-Task erstellt werden",
  "oneLayerForTaskTip": "Den Layer bei jeder Ausführung der Abfrage überschreiben",
  "multipleLayerForTaskTip": "Bei jeder Ausführung der Abfrage einen neuen Layer erstellen",
  "makeDefault": "Als Standard definieren",
  "icon": "Symbol",
  "newTask": "Neuer Task",
  "addTaskTip": "Fügen Sie dem Widget mindestens eine Abfrage hinzu, und konfigurieren Sie Parameter für jede von ihnen.",
  "webMapPopupTip": "Pop-up-Konfiguration des Layers in der Webkarte verwenden",
  "customPopupTip": "Benutzerdefinierten Inhalt konfigurieren",
  "showResultsSetActions": "Aktionen für den Ergebnissatz anzeigen",
  "zoomTo": "Zoomen auf",
  "openAttributeTable": "In Attributtabelle anzeigen",
  "content": "Inhalt",
  "displaySQLTip": "SQL-Ausdruck für Endbenutzer anzeigen",
  "useLayerDefaultSymbol": "Standardsymbol des Layers verwenden",
  "setCustomIcon": "Benutzerdefiniertes Symbol festlegen",
  "layerDefaultSymbolTip": "Standardsymbol des Layers verwenden",
  "uploadImage": "Ein Bild hochladen",
  "attributeCriteira": "Attributkriterien",
  "specifyFilterAtRuntimeTip": "Benutzer müssen Parameter für diesen Ausdruck festlegen.",
  "value": "WERT",
  "hideLayersTip": "Layer mit Abfrageergebnissen deaktivieren, wenn das Widget geschlossen wird",
  "tabLabels": "Registerkartenbeschriftungen",
  "tasks": "Tasks",
  "queryCriteira": "Abfragekriterien",
  "allowCustomQuery": "Erstellung benutzerdefinierter Abfragen zulassen"
});