define({
  "_widgetLabel": "Analiza incidenta",
  "_featureAction_SetAsIncident": "Postavi kao incident",
  "incident": "Incident",
  "weather": "Vreme",
  "locate_incident": "Lociraj incident",
  "clear_incidents": "Obriši incidente",
  "reverse_geocoded_address": "Najbliža adresa",
  "reverse_geocoded_error": "Nije dostupno",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "now": "SADA",
  "wind": "VETAR",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "UTO",
  "WED": "SRE",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SUB",
  "defaultTabMsg": "Nema identifikovanih incidenata.",
  "useMapExtent": "Koristi trenutni obuhvat mape",
  "noFeaturesFound": "Nema pronađenih geoobjekata.",
  "downloadCSV": "PREUZMI CSV",
  "sum": "ZBIR",
  "min": "MIN",
  "max": "MAKS",
  "avg": "PROS.",
  "count": "BROJAČ",
  "area": "POVRŠINA",
  "length": "DUŽINA"
});