define({
  "_widgetLabel": "Vzdálenost a směr",
  "tabLineTitle": "Spojnicový",
  "tabCircleTitle": "Kruh",
  "tabEllipseTitle": "Elipsa",
  "tabRingsTitle": "Kružnice",
  "multipleNotationsMessage": " označení, která odpovídají vašemu vstupu. Potvrďte, která chcete použít:",
  "invalidCoordinateMessage": "Neplatná souřadnice",
  "confirmInputNotationMessage": "Potvrďte označení vstupu",
  "prefixSuffixMessage": "Vstupní souřadnice má předponu i příponu pro hodnotu zeměpisné šířky nebo zeměpisné délky, vrácená souřadnice je založena na předponě.",
  "rememberDecisionMessage": "Zapamatovat mou volbu a znovu se již neptat.<br/>",
  "majorAxisTooltipMessage": "Klikněte na délku hlavní osy",
  "minorAxisTooltipMessage": "Přesuňte myš zpátky na startovní pozici, nastavte vedlejší osu a dokončete kresbu elipsy.",
  "clickToFinishLineMessage": "Kliknutím dokončete kresbu linie",
  "doubleClickEllipseMesage": "Dvojklikem dokončete kresbu kružnic k měření vzdálenosti",
  "invalidCoordinateTypeMessage": "Typ vstupních souřadnic nelze určit. Zkontrolujte zadané hodnoty",
  "noCenterPointSetMessage": "Není nastaven středový bod. Zkontrolujte zadané hodnoty",
  "ellipseMajorAxis": "Hlavní osa",
  "ellipseMinorAxis": "Vedlejší osa",
  "degreesRangeMessage": "Hodnota musí být mezi 0 a 360.",
  "millsRangeMessage": "Hodnota musí být mezi 0 a 6 400.",
  "lengthLabel": "Délka",
  "angleLabel": "Úhel",
  "startPointLabel": "Počáteční bod",
  "endPointLabel": "Koncový bod",
  "centerPointLabel": "Středový bod",
  "distanceTableErrorMessage": "Tabulka vzdáleností je prázdná. Vložte nějaké hodnoty vzdálenosti.",
  "setCoordFormatStringMessage": "Nastavit řetězec formátu souřadnic",
  "prefixMessage": "Ke kladným a záporným číslům přidejte předponu +/-",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "Vojenská hlásná síť (MGRS)",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Desetinné stupně – Zeměpisná šířka / zeměpisná délka",
  "DDLongLatNotation": "Desetinné stupně – Zeměpisná délka / zeměpisná šířka",
  "DDMLatLongNotation": "Stupně a desetinné minuty – Zeměpisná šířka / zeměpisná délka",
  "DDMLongLatNotation": "Stupně a desetinné minuty – Zeměpisná délka / zeměpisná šířka",
  "DMSLatLongNotation": "Stupně minuty vteřiny – Zeměpisná šířka / zeměpisná délka",
  "DMSLongLatNotation": "Stupně minuty vteřiny – Zeměpisná délka / zeměpisná šířka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "Vojenská hlásná síť (MGRS)",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – písmeno pásma",
  "UTMHemNotation": "UTM – polokoule (S/J)",
  "circleTitle": "Vytvořit kružnici z",
  "radiusLabel": "Poloměr",
  "diameterLabel": "Průměr",
  "startPointPlaceHolderLabel": "Zadat souřadnice",
  "formatInputLabel": "Formátovat vstup",
  "drawCircleLabel": "Keslit kruh",
  "drawLineLabel": "Nakreslit linii",
  "createCircleInteractivelyLabel": "Vytvořit kružnici interaktivně",
  "rangeErrorMessage": "Neplatný poloměr či průměr",
  "numericInvalidMessage": "Zadejte prosím číselnou hodnotu.",
  "timeLabel": "Čas",
  "invalidTimeMessage": "Neplatný časový údaj",
  "hoursLabel": "hodiny",
  "minutesLabel": "minuty",
  "secondsLabel": "sekundy",
  "rateLabel": "Poměr",
  "invalidDistanceMessage": "Neplatná hodnota vzdálenosti",
  "feetSecondsLabel": "Stopy / sekunda",
  "feetHourLabel": "Stopy / hodina",
  "kmSecondLabel": "Kilometry / sekunda",
  "kmHourLabel": "Kilometry / hodina",
  "metersSecondLabel": "Metry / sekunda",
  "metersHourLabel": "Metry / hodina",
  "milesSecondLabel": "Míle / sekunda",
  "milesHourLabel": "Míle / hodina",
  "nauticalMilesSecondLabel": "Námořní míle / sekunda",
  "nauticalMilesHourLabel": "Námořní míle / hodina",
  "clearGraphicsLabel": "Vymazat grafiku",
  "ellipseTypeLabel": "Typ elipsy",
  "ellipseSemiLabel": "Polo",
  "ellipseFullLabel": "Obě strany",
  "drawEllipseLabel": "Keslit elipsu",
  "createEllipseInteractively": "Vytvořit elipsu interaktivně",
  "axisLabel": "Osa",
  "majorRadiusLabel": "Hlavní (poloměr)",
  "axisErrorMessage": "Hodnota musí být větší než 0",
  "minorRadiusLabel": "Vedlejší (poloměr)",
  "orientationLabel": "Orientace",
  "orientationErrorMessage": "Hodnota musí být mezi 0 a 360.",
  "warningMessage": "Varování: Grafika vytvořená pomocí nástroje elipsy není geodetická",
  "fromLabel": "Od",
  "distanceBearingLabel": "Vzdálenost a azimut",
  "pointsLabel": "Body",
  "createLineInteractively": "Vytvořit linii interaktivně",
  "lineLengthErrorMessage": "Neplatná délka linie",
  "degreesLabel": "Stupně",
  "milsLabel": "Miliradiány",
  "lineTypeLabel": "Typ",
  "interactiveLabel": "Interaktivní",
  "fixedLabel": "Fixní",
  "originLabel": "Počátek",
  "cumulativeLabel": "Kumulativní",
  "numberOfRingsLabel": "Počet kružnic",
  "ringsErrorMessage": "Neplatný počet kružnic",
  "distanceBetweenRingsLabel": "Vzdálenost mezi kružnicemi",
  "ringsDecimalErrorMessage": "Vložte číselnou hodnotu se dvěma desetinnými místy",
  "distanceUnitsLabel": "Jednotky vzdálenosti",
  "distancesLabel": "Vzdálenosti",
  "numberOfRadialsLabel": "Počet radiál",
  "upLabel": "Nahoru",
  "downLabel": "Dolů",
  "deleteLabel": "Smazat",
  "radialsErrorMessage": "Neplatný počet radiál. Maximální povolený počet je 360",
  "addPointLabel": "Přidat bod",
  "valueLabel": "Hodnota",
  "valueText": "Vložit hodnotu",
  "actionLabel": "Akce"
});