define({
  "labelBookmarkName": "Dodaj zakładkę do bieżącego widoku",
  "labelPlay": "Odtwórz wszystko",
  "labelStop": "Zatrzymaj",
  "labelDelete": "Usuń",
  "placeholderBookmarkName": "Nazwa zakładki",
  "errorNameExist": "Zakładka już istnieje!",
  "errorNameNull": "Nieprawidłowa nazwa zakładki!",
  "editTip": "Edytuj zakładki",
  "exitEditTip": "Wyjdź z trybu edycji",
  "syncTip": "Synchronizuj",
  "cardsTips": "Widok siatki",
  "listTips": "Widok listy",
  "addBtn": "Dodaj",
  "deleteBtn": "Usuwanie",
  "changeThumbnailTip": "Zmień miniaturę",
  "dragReorderTip": "Przytrzymaj i przeciągnij, aby zmienić kolejność",
  "deleteBtnTip": "Usuń zakładkę",
  "editBtnTip": "Edytuj zakładkę",
  "withVisibility": "Z widocznością warstwy",
  "searchBookmark": "Wyszukaj",
  "bookmarksFromConfig": "Wstępnie skonfigurowane zakładki",
  "bookmarksFromCache": "Lokalne zakładki tymczasowe",
  "notice": "Uwaga",
  "changeNoticeTips": "Zmiany zostaną zapisane tylko w pamięci podręcznej przeglądarki. Po wprowadzeniu modyfikacji synchronizacja między widżetem a jego konfiguracją zostanie wyłączona.",
  "syncNoticeTips": "Spowoduje to usunięcie wszystkich zmian i przywrócenie skonfigurowanych zakładek.",
  "dontShowAgain": "Nie pokazuj ponownie",
  "saveVisibility": "Zapisz widoczność warstwy",
  "_widgetLabel": "Zakładka"
});