define({
  "_widgetLabel": "Model de adecvare",
  "general": {
    "clear": "Golire",
    "cancel": "Anulare",
    "save": "Executare",
    "saveAs": "Export"
  },
  "saveModel": {
    "save": "Export",
    "title": "Titlu: ",
    "summary": "Rezumat: ",
    "description": "Descriere: ",
    "tags": "Etichete: ",
    "folder": "Director: ",
    "homeFolderPattern": "{username} (Pornire)",
    "failed": "Export eşuat."
  },
  "util": {
    "colorRamp": {
      "1": "Extrem de redus",
      "2": "Foarte redus",
      "3": "Redus",
      "4": "Redus mediu",
      "5": "Medie",
      "6": "Ridicat mediu",
      "7": "Ridicat",
      "8": "Foarte ridicat",
      "9": "Extrem de ridicat",
      "low": "Redus",
      "high": "Ridicat",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Inversare"
    }
  },
  "wro": {
    "caption": "Model de adecvare",
    "browsePrompt": "Serviciu suprapus ponderat",
    "selectLayersCaption": "Selectare straturi tematice",
    "selectLayers": "Straturi tematice",
    "designModelCaption": "Model design",
    "designModel": "Model design",
    "transparency": "Transparenţă",
    "visible": "Vizibil",
    "total": "Total",
    "unableToLoad": "Imposibil de încărcat modelul.",
    "projectNotOpen": "Un proiect nu este deschis.",
    "readMore": "Citiţi mai mult",
    "validation": {
      "validating": "În curs de validare...",
      "invalidItemCaption": "Avertisment serviciu suprapus ponderat",
      "notAnImageService": "Acest element nu este un serviciu de imagini.",
      "notAWroService": "Acest element nu este un serviciu suprapus ponderat.",
      "undefinedUrl": "URL-ul acestui element nu este definit.",
      "inaccessible": "Serviciul este inaccesibil.",
      "generalError": "Nu se poate deschide elementul.",
      "missingFieldPattern": "{field} este un câmp obligatoriu",
      "notAllowRasterFunction": "allowRasterFunction trebuie setat la valoarea true",
      "notNearestResampling": "defaultResamplingMethod trebuie să fie Cel mai apropiat",
      "notIsWeightedOverlayProp": "Proprietatea cheie IsWeightedOverlay trebuie setată la valoarea true",
      "invalidLink": "Adresa URL nu este validă. Nu s-a reuşit deschiderea site-ului pentru stratul tematic selectat.",
      "unexpectedError": "A survenit o stare neaşteptată.",
      "rangeMessage": "Valoarea trebuie să fie între ${0} şi ${1}",
      "rangeMessage100": "Valoarea trebuie să fie între 0 şi 100",
      "maxLayers": "Maximum ${0} straturi tematice permise de serviciu, trebuie ca mai întâi să eliminaţi un strat tematic înainte de a adăuga unul nou.",
      "notFound": "Stratul tematic ${0} nu a fost găsit în serviciul suprapus ponderat",
      "wroServiceNotDefined": "Nu a fost definit niciun serviciu suprapus ponderat pentru model.",
      "overlayLayerOutputInvalid": "Valoarea de ieşire [${1}] a intervalelor stratului tematic suprapus [${0}] lipseşte sau nu este validă",
      "overlayLayerInputInvalid": "Valoarea minimă/maximă de intrare [${1}] a intervalelor stratului tematic suprapus [${0}] lipseşte sau nu este validă",
      "overlayLayerRangesMissing": "Stratul tematic suprapus [${0}] nu are intervalele de remapare",
      "overlayLayerWeight": "Valorile ponderate ale stratului tematic suprapus au o valoare totală de până la 100",
      "overlayLayerRequired": "Este necesar cel puţin un strat tematic suprapus",
      "overlayLayerNotDefined": "Straturile tematice suprapuse nu sunt definite",
      "requiresColormap": "Funcţia raster necesită o hartă color, însă modelul nu are o definiţie validă a hărţii color",
      "createModelError": "Eroare la crearea modelului",
      "invalidModel": "Modelul nu este valid",
      "imageServiceNotDefined": "Stratul tematic de imagini nu este definit",
      "imageLayerNotDefined": "Stratul tematic de imagini nu este definit",
      "histogramNotDefined": "Nu a fost definită nicio funcţie de histogramă ponderată suprapusă."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Verde Galben Roşu",
      "Red Yellow Green": "Roşu Galben Verde",
      "Yellow to Dark Red": "De la galben la roşu închis",
      "Dark Red to Yellow": "De la roşu închis la galben",
      "Light Gray to Dark Gray": "De la gri deschis la gri închis",
      "Dark Gray to Light Gray": "De la gri închis la gri deschis",
      "Light Brown to Dark Brown": "De la maro deschis la maro închis",
      "Dark Brown to Light Brown": "De la maro închis la maro deschis",
      "Full Spectrum - Bright Red to Blue": "Spectru complet - de la roşu deschis la albastru",
      "Full Spectrum - Bright Blue to Red": "Spectru complet - de la albastru deschis la roşu",
      "Partial Spectrum - Yellow to Blue": "Spectru parţial - de la galben la albastru",
      "Partial Spectrum - Blue to Yellow": "Spectru parţial - de la albastru la galben",
      "Yellow-Green to Dark Blue": "De la galben-verde la albastru închis",
      "Dark Blue to Yellow-Green": "De la albastru închis la galben-verde",
      "Cold to Hot Diverging": "Divergenţă de la rece la cald",
      "Hot to Cold Diverging": "Divergenţă de la cald la rece",
      "Surface - Low to High": "Suprafaţă - de la redus la ridicat",
      "Surface - High to Low": "Suprafaţă - de la ridicat la redus"
    }
  },
  "tabs": {
    "layers": "Straturi tematice",
    "model": "Model",
    "chart": "Diagramă"
  },
  "chart": {
    "prompt": "Obiecte spaţiale",
    "working": "Se actualizează...",
    "polygonTool": "Desenaţi un poligon",
    "freehandPolygonTool": "Trasare poligon liber",
    "selectTool": "Selectare dintr-un strat tematic",
    "panTool": "Panoramare",
    "clearButton": "Golire",
    "noModelLayer": "Fără model.",
    "noSubjectLayers": "Harta dvs. nu are niciun strat tematic de poligoane.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});