define({
  "tabs_section_Label": "แท็ป",
  "addTab": "เพิ่มแท็ป",
  "layerName": "ชั้นข้อมูล",
  "layerType": "ประเภทการวิเคราะห์",
  "layerLabel": "ป้ายชื่อ",
  "actions": "การดำเนินการ",
  "closest": "ฟีเจอร์ที่ใกล้ที่สุด",
  "proximity": "ความใกล้ชิด",
  "summary": "สรุป",
  "select_lbl": "-- เลือก --",
  "general_setting_Label": "ตั้งค่าทั่วไป",
  "units_text_lbl": "หน่วยระยะทาง",
  "maximum_distance_lbl": "ฟีเจอร์ที่อยู่ใกล้ที่สุดภายในระยะสูงสุด",
  "buffer_text_lbl": "ป้ายแสดงบัฟเฟอร์",
  "buffer_lbl": "ระยะทางบัฟเฟอร์",
  "buffer_max_lbl": "ระยะบัฟเฟอร์สูงสุด",
  "buffer_min_lbl": "ระยะบัฟเฟอร์ขั้นต่ำ",
  "buffer_default_lbl": "ระยะทางบัฟเฟอร์เริ่มต้น",
  "not_less_than_max": "ระยะทางต้องน้อยกว่าระยะทางบัฟเฟอร์สูงสุด",
  "not_between": "ระยะทางต้องอยู่ระหว่างระยะทางบัฟเฟอร์ต่ำสุดและสูงสุด",
  "not_more_than_min": "ระยะทางต้องมากกว่าระยะทางบัฟเฟอร์ต่ำสุด",
  "not_valid_number": "ต้องเป็นตัวเลขที่ถูกต้อง",
  "invalid_value": "ค่า ${type} ไม่ถูกต้อง",
  "routing_checkBox": "เปิดใช้งานการกำหนดเส้นทาง",
  "weather_Label": "การตั้งค่าสภาพอากาศ",
  "weather_checkBox": "เปิดใช้งานสภาพอากาศ",
  "weather_map_layers": "เลือกเลเยอร์สภาพอากาศ",
  "selected_map_layers": " เลือกเลเยอร์สภาพอากาศแล้ว",
  "instruction_weather": "แสดงข้อมูลสภาพอากาศในแผงควบคุม",
  "instruction_weather_layers": "แสดงเลเยอร์สภาพอากาศเพิ่มเติม",
  "instruction_weather_metric": "แสดงค่ามาตรฐาน / เมตริก",
  "selectLayers": "เลือกเลเยอร์สภาพอากาศ",
  "weather_removed_message": "ตัวเลือกสภาพอากาศไม่สามารถใช้ได้สำหรับวิดเจ็ตนี้อีกต่อไป",
  "currentlySelectedLayer": "เลือกจากเลเยอร์แผนที่",
  "missingTabLabel": "ตัวอักษาหายไปอย่างน้อยหนึ่งในแท็บ",
  "missingLayerInWebMap": "ไม่พบชั้นข้อมูลการดำเนินงาน",
  "selectFields": "เลือกฟิลด์",
  "addField": "เพิ่มฟิลด์",
  "sum": "รวม",
  "min": "น้อยสุด",
  "max": "สูงสุด",
  "avg": "เฉลี่ย",
  "count": "จำนวน",
  "area": "พื้นที่",
  "length": "ความยาว",
  "count_checkBox": "แสดงการนับข้อมูล",
  "area_checkBox": "แสดงการรวมพื้นที่",
  "length_checkBox": "แสดงการรวความยาว",
  "max_records": "วงเงินสูงสุด",
  "save_label": "ตัวเลือกการบันทึก",
  "save_checkbox": "เปิดใช้การบันทึก",
  "report_label": "ตัวเลือกรายงาน",
  "report_checkbox": "เปิดใช้งานรายงาน",
  "csv_label": "ตัวเลือก CSV",
  "csv_checkbox": "ส่งออกฟิลด์ทั้งหมด",
  "display_label": "แสดงตัวเลือก",
  "display_checkbox": "การแสดงผลสรุปฟีเจอร์",
  "snapshot_label": "ตัวเลือกสแนปซ็อต",
  "snapshot_checkbox": "เปิดใช้งานสแนปซ็อต",
  "must_select_template": "กรุณาเลือกหนึ่งในแม่แบบเพื่อการแก้ไขในตัวเลือกการบันทึก",
  "count_label": "นัดจำนวนป้าย",
  "area_label": "ป้ายข้อความของพื้นที่",
  "length_label": "ป้ายข้อความของความยาว",
  "invalid_string_width": "ค่ายาวมากเกินไป ",
  "layer_type_not_supported": "ไม่รองรับประเภทเลเยอร์",
  "groupedSummary": "นับจำนวนกลุ่ม",
  "groupByField": "จัดกลุ่มด้วยฟิลด์",
  "labelType": "รวมป้ายชื่อ",
  "prefix": "เป็นคำนำหน้า",
  "suffix": "เป็นคำต่อท้าย",
  "need_group_field": "โปรดใช้การแก้ไข เพื่อกำหนดกลุ่มโดยฟิลด์",
  "fieldTitle": "ฟิลด์",
  "typeTitle": "ชนิด",
  "actionsTitle": "การดำเนินการ",
  "save_point_checkbox": "บันทึกจุด",
  "save_line_checkbox": "บันทึกเส้น",
  "save_poly_checkbox": "บันทึกพื้นที่",
  "no_valid_popup_fields": "ไม่มีฟิลด์ข้อมูลที่ถูกต้องในป๊อปอัพ ให้ใช้การแก้ไขเพื่อกำหนดฟิลด์ข้อมูล",
  "no_valid_fields": "ไม่มีฟิลด์ข้อมูลที่ถูกต้อง ให้ใช้การแก้ไขเพื่อกำหนดฟิลด์ตัวเลือกการแสดง",
  "incident_label": "ป้ายแท็บ",
  "locate_incident_label": "ป้ายของพื้นที่ที่น่าสนใจ",
  "incident": "เหตุการณ์",
  "locate_incident": "ค้นหาเหตุการณ์",
  "buffer_value": "ระยะทางขยายออกไป",
  "tab_options": "การวิเคราะห์",
  "export_options": "ผลลัพธ์",
  "instruction_save": "บันทึกตำแหน่งไปยังฟีเจอร์เซอร์วิส",
  "instruction_snapshot": "สร้างเว็ปแผนที่ตามสถานที่",
  "instruction_report": "สร้างรายงานฉบับพิมพ์ของสถานที่",
  "instruction_all_fields": "ส่งออกทุกฟิลด์ด้วยการดาวโหลด CSV",
  "data_label": "การตั้งค่าการส่งข้อมูล",
  "layer_error": "เลเยอร์หายไปหรือไม่ถูกต้อง",
  "visibility_checkBox": "ปิดการใช้งานการจัดการแสดงผลชั้นข้อมูล",
  "downloadTab": {
    "reportLegend": "การตั้งค่ารายงาน",
    "textColorLabel": "เลือกสีสำหรับชื่อคอลัมน์",
    "setButtonLabel": "ตั้ง",
    "printGPServiceLabel": "พิมพ์เซอร์วิส URL",
    "logoLabel": "โลโก้",
    "logoChooserHint": "คลิกบนไอคอนรูปภาพเพื่อเปลี่ยนรูป",
    "footnoteLabel": "เชิงอรรถ"
  }
});