define({
  "labelBookmarkName": "Kirjamerkitse nykyinen näkymä",
  "labelPlay": "Toista kaikki",
  "labelStop": "Lopeta",
  "labelDelete": "Poista",
  "placeholderBookmarkName": "Kirjanmerkin nimi",
  "errorNameExist": "Kirjanmerkki on olemassa!",
  "errorNameNull": "Kirjanmerkin nimi on virheellinen!",
  "editTip": "Muokkaa kirjanmerkkejä",
  "exitEditTip": "Poistu muokkaustilasta",
  "syncTip": "Synkronoi",
  "cardsTips": "Ruudukkonäkymä",
  "listTips": "Luettelonäkymä",
  "addBtn": "Lisää",
  "deleteBtn": "Poista",
  "changeThumbnailTip": "Vaihda pikkukuva",
  "dragReorderTip": "Järjestä uudelleen vetämällä ja pudottamalla",
  "deleteBtnTip": "Poista kirjanmerkki",
  "editBtnTip": "Muokkaa kirjanmerkkiä",
  "withVisibility": "Karttatason näkyvyyden kanssa",
  "searchBookmark": "Etsi",
  "bookmarksFromConfig": "Etukäteen määritetyt kirjanmerkit",
  "bookmarksFromCache": "Paikalliset väliaikaiset kirjanmerkit",
  "notice": "Huomautus",
  "changeNoticeTips": "Muutokset tallennetaan vain selaimesi välimuistiin. Pienoisohjelman ja sen määritysten välinen synkronointi katkaistaan, kun teet muutoksia.",
  "syncNoticeTips": "Tämä poistaa kaikki tekemäsi muutokset ja palauttaa määritetyt kirjanmerkit.",
  "dontShowAgain": "Älä näytä uudelleen",
  "saveVisibility": "Tallenna karttatason näkyvyys",
  "_widgetLabel": "Kirjanmerkki"
});