define({
  "symbolologyTabLabel": "配置符號系統",
  "facilitiesDescription": "設施圖層",
  "demographicsDescription": "人口統計圖層",
  "settingsTitle": "設定",
  "spillLocationLabel": "洩露位置",
  "spillLocationButtonLabel": "配置洩露位置設定",
  "IISettingsLabel": "初始隔離區",
  "IIButtonLabel": "配置初始隔離設定",
  "PASettingsLabel": "保護行動區域",
  "PAButtonLabel": "配置保護行動設定",
  "downwindSettingsLabel": "順風區",
  "downwindButtonLabel": "配置順風設定",
  "fireSettingsLabel": "防火隔離區",
  "fireButtonLabel": "配置防火隔離設定",
  "bleveSettingsLabel": "BLEVE 隔離區域",
  "bleveButtonLabel": "配置 BLEVE 設定",
  "transparency": "幻燈片",
  "outline": "清單",
  "fill": "填充 (將樣式設為實心時所套用的顏色)",
  "style": "樣式",
  "lineStyles": {
    "esriSLSDash": "虛線",
    "esriSLSDashDot": "虛線點",
    "esriSLSDashDotDot": "虛線點點",
    "esriSLSDot": "點",
    "esriSLSLongDash": "長虛線",
    "esriSLSLongDashDot": "長虛線點",
    "esriSLSNull": "空",
    "esriSLSShortDash": "短虛線",
    "esriSLSShortDashDot": "短虛線點",
    "esriSLSShortDashDotDot": "短雙虛線點",
    "esriSLSShortDot": "短點",
    "esriSLSSolid": "實心"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向後",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "對角線",
    "esriSFSForwardDiagonal": "轉寄",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "空",
    "esriSFSSolid": "實心",
    "esriSFSVertical": "垂直"
  }
});