define({
  "_widgetLabel": "Fråga",
  "executeQueryTip": "Klicka på något av följande uppgiftsobjekt för att köra frågan.",
  "invalidConfig": "Ogiltig konfiguration. Ställ in korrekt konfiguration på frågeinställningssidan.",
  "queryParams": "Alternativ",
  "parameters": "ALTERNATIV",
  "queries": "FRÅGOR",
  "apply": "Verkställ",
  "queryResults": "Resultat",
  "clear": "Rensa",
  "noResults": "Inget geoobjekt hittades.",
  "queryError": "Frågan misslyckades!",
  "numberFound": "Antal geoobjekt som hittades",
  "mapExtentTip": "Begränsa resultaten till det aktuella kartområdet.",
  "noValue": "Inget värde",
  "and": "och",
  "stringOperatorIs": "är",
  "stringOperatorIsNot": "är inte",
  "stringOperatorStartsWith": "börjar med",
  "stringOperatorEndsWith": "slutar med",
  "stringOperatorContains": "innehåller",
  "stringOperatorDoesNotContain": "innehåller inte",
  "stringOperatorIsBlank": "är tomt",
  "stringOperatorIsNotBlank": "är inte tomt",
  "dateOperatorIsOn": "är",
  "dateOperatorIsNotOn": "är inte",
  "dateOperatorIsBefore": "är före",
  "dateOperatorIsAfter": "är efter",
  "dateOperatorDays": "dagar",
  "dateOperatorWeeks": "veckor",
  "dateOperatorMonths": "månader",
  "dateOperatorInTheLast": "i den sista",
  "dateOperatorNotInTheLast": "inte i den sista",
  "dateOperatorIsBetween": "är mellan",
  "dateOperatorIsNotBetween": "är inte mellan",
  "dateOperatorIsBlank": "är tomt",
  "dateOperatorIsNotBlank": "är inte tomt",
  "numberOperatorIs": "är",
  "numberOperatorIsNot": "är inte",
  "numberOperatorIsAtLeast": "är minst",
  "numberOperatorIsLessThan": "är mindre än",
  "numberOperatorIsAtMost": "är som mest",
  "numberOperatorIsGreaterThan": "är större än",
  "numberOperatorIsBetween": "är mellan",
  "numberOperatorIsNotBetween": "är inte mellan",
  "numberOperatorIsBlank": "är tomt",
  "numberOperatorIsNotBlank": "är inte tomt",
  "operationalLayerTip": "Lägg till resultat som funktionslager",
  "queryResult": "Frågeresultat",
  "specifyParamsTip": "Ange parametrar för den här uppgiften",
  "useSpatialFilter": "Använd geografiskt filter för att begränsa geoobjekt",
  "useCurrentMapExtent": "Endast geoobjekt som korsar det aktuella kartområdet",
  "drawGraphicOnMap": "Endast geoobjekt som korsar det användardefinierade området",
  "specifySpatialFilterMsg": "Ange ett geografiskt filter för den här uppgiften.",
  "clearResults": "Rensa resultat",
  "operationalTip": "När det här alternativet har markerats behålls resultaten på kartan tills du klickar på knappen \"${clearResults}\".",
  "noneQueryTip": "Ingen frågeuppgift har konfigurerats för denna widget.",
  "noPermissionsMsg": "Du saknar behörighet för att få åtkomst till denna tjänst.",
  "attributesFromRelationship": "Attribut från relaterad tabell",
  "tasks": "Uppgifter",
  "applySpatialFilterToLimitResults": "Lägg på ett geografiskt filter så att resultaten begränsas",
  "useCurrentExtentTip": "Returnera bara geoobjekt i den aktuella kartutbredningen",
  "useDrawGraphicTip": "Returnera bara geoobjekt som korsar den form som ritats på kartan",
  "useFeaturesTip": "Returnera bara geoobjekt som har en geografisk relation med geoobjekt i ett annat lager",
  "noSpatialLimitTip": "Returnera geoobjekt i hela kartutbredningen",
  "applySearchDistance": "Använd en sökdistans",
  "spatialRelationship": "Geografisk relation",
  "relatedLayer": "Relaterat lager",
  "bufferDistance": "Buffertavstånd",
  "miles": "Engelska mil",
  "kilometers": "Kilometer",
  "feet": "Fot",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Nautiska mil",
  "back": "Bakom",
  "execute": "Utför",
  "zoomTo": "Zooma till",
  "openAttributeTable": "Visa i attributtabell",
  "noResult": "Inget resultat.",
  "noTask": "Ingen uppgift.",
  "removeThisResult": "Ta bort det här resultatet",
  "attributeCriteira": "Attributkriterier",
  "spatialFilter": "Geografiskt filter",
  "value": "VÄRDE",
  "noAttributeSpatialFilterTip": "Inga filter har definierats. Alla geoobjekt kommer att returneras.",
  "showAllRelatedRecords": "Visa alla relaterade poster",
  "changeSymbol": "Byta symbol",
  "queryCriteira": "Frågekriterier",
  "customQuery": "Anpassad fråga",
  "layer": "Lager",
  "createCustomQuery": "Skapa anpassad fråga."
});