define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Ihrem Konto sind keine Berechtigungen zum Erstellen oder Ändern von Daten zugewiesen.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Nicht aktiv",
  "pressStr": "Drücken Sie ",
  "ctrlStr": " STRG ",
  "snapStr": " , um die Fangfunktion zu aktivieren.",
  "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
  "editorCache": " - Editor-Cache",
  "presetFieldAlias": "Feld",
  "presetValue": "Voreingestellter Wert",
  "usePresetValues": " Voreingestellte Werte verwenden (nur neue Features)",
  "editGeometry": " Geometrie bearbeiten",
  "savePromptTitle": "Feature speichern",
  "savePrompt": "Möchten Sie das aktuelle Feature speichern?",
  "deletePromptTitle": "Feature löschen",
  "deletePrompt": "Soll das ausgewählte Feature tatsächlich gelöscht werden?",
  "attachmentLoadingError": "Fehler beim Hochladen der Anlagen",
  "attachmentSaveDeleteWarning": "Warnung: Änderungen an Anlagen werden automatisch gespeichert.",
  "autoSaveEdits": "Änderung automatisch speichern",
  "addNewFeature": "Neues Feature erstellen",
  "featureCreationFailedMsg": "Neuer Datensatz/neues Feature kann nicht erstellt werden",
  "noRelatedFeatureFoundMsg": "Keine zugehörigen Datensätze/Features gefunden",
  "relatedItemTitle": "Zugehörige(r) Tabelle/Layer",
  "invalidRelationShipMsg": "Stellen Sie sicher, dass der Wert des Primärschlüsselfeldes '${parentKeyField}' gültig ist.",
  "pendingFeatureSaveMsg": "Speichern Sie die Feature-Änderungen, bevor Sie ein zugehöriges Feature erstellen.",
  "attachmentsRequiredMsg": "(*) Anlagen sind erforderlich.",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
    "searchTemplates": "Vorlagen durchsuchen"
  },
  "invalidConfiguration": "Das Widget wurde nicht konfiguriert oder die Layer in der Konfiguration sind nicht mehr in der Karte enthalten.  Öffnen Sie die App im Builder-Modus, und konfigurieren Sie das Widget neu.",
  "geometryServiceURLNotFoundMSG": "URL des Geometrieservice kann nicht abgerufen werden"
});