define({
  "layerSelect": "เลือกชั้ลข้อมูลรูปภาพ",
  "displayMeasureResultInPopup": "แสดงผลลัพท์ของการวัดระยะด้วยป๊อปอัพ",
  "angularUnitSelect": "ค่าเริ่มต้นหน่วยเชิงมุม",
  "linearUnitSelect": "ค่าเริ่มต้นหน่วยเชิงเส้น",
  "areaUnitSelect": "หน่วยพื้นที่ตั้งต้น",
  "displayOperationSelect": "เลือกวิธีการในการวัดระยะ",
  "errorSectionMessage": "ไม่มีชั้นข้อมูลที่สนับสุนความสามารถในการวัด",
  "unitLabel": {
    "esriInches": "นิ้ว",
    "esriFeet": "ฟุต",
    "esriYards": "หลา",
    "esriMiles": "ไมล์",
    "esriNauticalMiles": "ไมล์ทะเล",
    "esriMillimeters": "มิลลิเมตร",
    "esriCentimeters": "เซ็นติเมตร",
    "esriDecimeters": "เดซิเมตร",
    "esriMeters": "เมตร",
    "esriKilometers": "กิโลเมตร",
    "esriDURadians": "เรเดียน",
    "esriDUDecimalDegrees": "องศา",
    "esriSquareInches": "ตร. นิ้ว",
    "esriSquareFeet": "ตร. ฟุต",
    "esriSquareYards": "ตร. หลา",
    "esriAcres": "เอเคอร์",
    "esriSquareMiles": "ตร. ไมล์",
    "esriSquareMillimeters": "ตร. มิลลิเมตร",
    "esriSquareCentimeters": "ตร. เซนติลิเมตร",
    "esriSquareDecimeters": "ตร. เดซิเมตร",
    "esriSquareMeters": "ตร. เมตร",
    "esriAres": "Ares",
    "esriHectares": "เฮคเตอร์",
    "esriSquareKilometers": "ตร. กิโลเมตร"
  },
  "operationLabel": {
    "esriMensurationPoint": "ตำแหน่ง",
    "esriMensurationDistanceAndAngle": "ระยะทางและมุม",
    "esriMensurationAreaAndPerimeter": "พื้นที่และเส้นรอบวง",
    "esriMensurationHeightFromBaseAndTop": "ความสูง: ฐานถึงยอด",
    "esriMensurationHeightFromBaseAndTopShadow": "ความสูง: ฐานถึงเงาบนยอด",
    "esriMensurationHeightFromTopAndTopShadow": "ความสูง: ยอดถึงเงาบนยอด",
    "esriMensurationCentroid": "จุดศูนย์กลาง",
    "esriMensurationPoint3D": "ตำแหน่ง (3 มิติ)",
    "esriMensurationDistanceAndAngle3D": "ระยะทางและมุม (3 มิติ)",
    "esriMensurationAreaAndPerimeter3D": "พื้นที่และเส้นรอบวง(3 มิติ)",
    "esriMensurationCentroid3D": "จุดศูนย์กลาง (3 มิติ)"
  }
});