define({
  "_widgetLabel": "Analisis Insiden",
  "_featureAction_SetAsIncident": "Tetapkan Sebagai Insiden",
  "incident": "Insiden",
  "weather": "Cuaca",
  "locate_incident": "Cari Lokasi Insiden",
  "clear_incidents": "Kosongkan Insiden",
  "reverse_geocoded_address": "Alamat terdekat",
  "reverse_geocoded_error": "Tidak tersedia",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil Laut",
  "now": "SEKARANG",
  "wind": "ANGIN",
  "SUN": "MIN",
  "MON": "SEN",
  "TUE": "SEL",
  "WED": "RAB",
  "THU": "KAM",
  "FRI": "JUM",
  "SAT": "SAB",
  "defaultTabMsg": "Tidak ada insiden teridentifikasi.",
  "useMapExtent": "Gunakan jangkauan peta saat ini",
  "noFeaturesFound": "Fitur tidak ditemukan.",
  "downloadCSV": "UNDUH CSV",
  "sum": "SUM",
  "min": "MIN",
  "max": "MAKS",
  "avg": "AVG",
  "count": "COUNT",
  "area": "AREA",
  "length": "PANJANG"
});