define({
  "enableUndoRedo": "Habilitar deshacer/rehacer",
  "toolbarVisible": "Barra de herramientas visible",
  "toolbarOptions": "Opciones de barra de herramientas",
  "mergeVisible": "Fusionar",
  "cutVisible": "Cortar",
  "reshapeVisible": "Cambiar de forma",
  "back": "Atrás",
  "label": "Capa",
  "edit": "Editable",
  "update": "Deshabilitar actualizar geometría",
  "fields": "Campos",
  "actions": "Acciones",
  "editpageName": "Nombre",
  "editpageAlias": "Alias",
  "editpageVisible": "Visible",
  "editpageEditable": "Editable",
  "noLayers": "No hay disponibles capas de entidades editables",
  "configureFields": "Configurar campos de capa",
  "useFilterEdit": "Usar filtro de plantilla de entidad",
  "display": "Mostrar",
  "autoApplyEditWhenGeometryIsMoved": "Aplicar la edición automáticamente cuando se mueva la geometría",
  "snappingTolerance": "Definir la tolerancia de alineación en píxeles",
  "popupTolerance": "Definir la tolerancia del elemento emergente de edición de atributos en píxeles",
  "stickyMoveTolerance": "Definir la tolerancia de movimiento en píxeles",
  "usingSaveButton": "No aplicar ediciones a los atributos hasta hacer clic en el botón Guardar"
});