define({
  "layerSelect": "इमेज लेयर का चयन करें",
  "displayMeasureResultInPopup": "एक पॉप-अप में परिमाण परिणामों को प्रदर्शित करें",
  "angularUnitSelect": "डिफ़ॉल्ट कोणीय इकाई",
  "linearUnitSelect": "डिफ़ॉल्ट रैखिक इकाई",
  "areaUnitSelect": "क्षेत्रफल की डिफ़ॉल्ट इकाई",
  "displayOperationSelect": "परिमाण ऑपरेशन का चयन करें",
  "errorSectionMessage": "लेयरस में से कोई भी क्षेत्रमिति क्षमताओं का समर्थन नहीं करती हैं।",
  "unitLabel": {
    "esriInches": "इंच",
    "esriFeet": "फ़ीट",
    "esriYards": "गज",
    "esriMiles": "मील",
    "esriNauticalMiles": "समुद्री मील",
    "esriMillimeters": "मिलीमीटर",
    "esriCentimeters": "सेंटीमीटर",
    "esriDecimeters": "डेसीमीटर",
    "esriMeters": "मीटर",
    "esriKilometers": "किलोमीटर",
    "esriDURadians": "रेडियन",
    "esriDUDecimalDegrees": "डिग्री",
    "esriSquareInches": "वर्ग इंच",
    "esriSquareFeet": "वर्ग फीट",
    "esriSquareYards": "वर्ग गज़",
    "esriAcres": "एकड़",
    "esriSquareMiles": "वर्ग मील",
    "esriSquareMillimeters": "वर्ग मिलीमीटर",
    "esriSquareCentimeters": "वर्ग सेंटीमीटर",
    "esriSquareDecimeters": "वर्ग डेसीमीटर",
    "esriSquareMeters": "वर्ग मीटर",
    "esriAres": "एकड़",
    "esriHectares": "हेक्टेयर",
    "esriSquareKilometers": "वर्ग किलोमीटर"
  },
  "operationLabel": {
    "esriMensurationPoint": "स्थान",
    "esriMensurationDistanceAndAngle": "दूरी और कोण",
    "esriMensurationAreaAndPerimeter": "क्षेत्रफल और परिमाप",
    "esriMensurationHeightFromBaseAndTop": "ऊँचाई: आधार से शीर्ष तक",
    "esriMensurationHeightFromBaseAndTopShadow": "ऊँचाई: आधार से शीर्ष-छाया तक",
    "esriMensurationHeightFromTopAndTopShadow": "ऊँचाई: शीर्ष से शीर्ष-छाया तक",
    "esriMensurationCentroid": "केन्द्रक",
    "esriMensurationPoint3D": "स्थान (3D)",
    "esriMensurationDistanceAndAngle3D": "दूरी और कोण (3D)",
    "esriMensurationAreaAndPerimeter3D": "क्षेत्रफल और परिमाप (3D)",
    "esriMensurationCentroid3D": "केन्द्रक (3D)"
  }
});