define({
  "_widgetLabel": "Tinklelio atskaitiniai grafiniai elementai",
  "newGRGFromAreaButtonLabel": "Apibrėžti tinklelį iš ploto",
  "newGRGFromPointButtonLabel": "Apibrėžti tinklelį iš taško",
  "newGRGFromAreaTitle": "Apibrėžti tinklelį iš ploto",
  "newGRGFromPointTitle": "Apibrėžti tinklelį iš taško",
  "newGRGBySizeButtonLabel": "Pagal matmenį",
  "newGRGFromRefSystemButtonLabel": "Pagal atskaitos sistemą",
  "newGRGByTimeLabel": "Pagal laiką ir greitį",
  "newGRGFromNonStandardButtonLabel": "Apibrėžti nestandartinį tinklelį",
  "newGRGAreaBySizeTitle": "GRG iš ploto pagal matmenį",
  "newGRGAreaBySizeDefineAreaLabel": "GRG sritis",
  "addGRGAreaPolygonToolTip": "Brėžti GRG naudojant poligoną",
  "addGRGAreaExtentToolTip": "Brėžti GRG naudojant aprėptį",
  "rotation": "Tinklelio pasukimas",
  "numberRowsColumnsLabel": "Apibrėžti eilučių ir stulpelių skaičių",
  "newGRGAreaByRefSystemTitle": "GRG iš ploto pagal atskaitos sistemą",
  "gridSize": "Tinklelio dydis",
  "UTMZoneandBand": "Tinklelio zona",
  "100000m": "100 000 metrų",
  "10000m": "10 000 metrų",
  "1000m": "1 000 metrų",
  "100m": "100 metrų",
  "10m": "10 metrų",
  "clipGrid": "Apkirpti pagal GRG plotą",
  "newGRGAreaFromNonStandardTitle": "Naujas NRG",
  "newGRGPointBySizeTitle": "GRG iš taško pagal matmenį",
  "newGRGPointByRefSystemTitle": "GRG iš taško pagal atskaitos sistemą",
  "newGRGPointByTimeTitle": "GRG iš taško naudojant laiką ir greitį",
  "time": "Laikas",
  "rate": "Greitis",
  "hours": "Valandos",
  "minutes": "Minutės",
  "seconds": "Sekundės",
  "ftPerSec": "Pėdos / sekundę",
  "ftPerHour": "Pėdos / valandą",
  "kmPerSec": "Kilometrai / sekundę",
  "kmPerHour": "Kilometrai / valandą",
  "mPerSec": "Metrai / sekundę",
  "mPerHour": "Metrai / valandą",
  "miPerSec": "Mylios / sekundę",
  "miPerHour": "Mylios / valandą",
  "nMPerSec": "Jūrmylės / sekundę",
  "nMPerHour": "Jūrmylės / valandą",
  "settingsTitle": "Parametrai",
  "labelSettingsLabel": "Žymės nustatymai",
  "labelSettingsButtonLabel": "Konfigūruoti žymės nustatymus",
  "gridSettingsLabel": "Tinklelio parametrai",
  "gridSettingsButtonLabel": "Konfigūruoti tinklelio nustatymus",
  "transparency": "Permatomumas",
  "labelStyle": "Žymės stilius",
  "font": "Šriftas",
  "textSize": "Teksto dydis",
  "textColor": "Teksto spalva",
  "halo": "Aureolė",
  "show": "Rodyti",
  "lockSettings": "Nustatymus užrakino aplikacijos savininkas",
  "gridSettings": {
    "cellShape": "Gardelės forma",
    "cellUnits": "Gardelės matavimo vienetai",
    "cellOutline": "Gardelės kontūro nustatymai",
    "cellFill": "Gardelės užpildo nustatymai",
    "gridReferenceSystem": "Atskaitos sistema",
    "gridDatum": "Duomenys: WGS84",
    "labelStartPosition": "Žymės pradžia",
    "labelType": "Žymės tipas",
    "labelDirection": "Žymės kryptis",
    "gridOrigin": "Tinklelio pradžia",
    "default": "Stačiakampė",
    "hexagon": "Šešiakampė",
    "miles": "Mylios",
    "kilometers": "Kilometrai",
    "feet": "Pėdos",
    "meters": "Metrai",
    "yards": "Jardai",
    "nautical-miles": "Jūrmylės",
    "lowerLeft": "Apačioje kairėje",
    "lowerRight": "Apačioje dešinėje",
    "upperLeft": "Viršuje kairėje",
    "upperRight": "Viršuje dešinėje",
    "center": "Centre",
    "alphaNumeric": "Raidinis-skaitinis",
    "alphaAlpha": "Raidinis-raidinis",
    "numeric": "Skaitinis",
    "horizontal": "Horizontali",
    "vertical": "Vertikali",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Rodyti žymes"
  },
  "publishTitle": "Publikuoti GRG portale",
  "publishGRGBtn": "Publikuoti",
  "GRGLayerName": "Publikuotas GRG sluoksnio pavadinimas",
  "invalidGRGLayerName": "Sluoksnio pavadinime gali būti tik raidės, skaičiai ir pabraukimo brūkšniai",
  "missingGRGLayerName": "Būtina įvesti GRG pavadinimą",
  "publishingFailedLayerExists": "Publikuoti nepavyko: jau turite elementų paslaugą, kurios pavadinimas {0}. Pasirinkite kita pavadinimą.",
  "checkService": "Patikrinti paslaugą: {0}.",
  "createService": "Kurti paslaugą: {0}",
  "unableToCreate": "Nepavyko sukurti: {0}",
  "addToDefinition": "Įtraukti į aprašą: {0}",
  "successfullyPublished": "Sėkmingai publikuotas žiniatinklio sluoksnis{0}Tvarkyti žiniatinklio sluoksnį",
  "userRole": "Nepavyksta sukurti paslaugos, nes vartotojas neturi teisių",
  "createGRGBtn": "Kurti GRG",
  "clearGRGBtn": "Valyti",
  "labelFormat": "Žymės formatas",
  "helpIconTooltip": "Z: tinklelio zonos žymuo (GZD)\nS: 100 000 metrų tinklelio kvadrato identifikacija (GSID)\nX: Į rytus (X koordinatė)\nY: Į šiaurę (Y koordinatė)\n\nPavyzdžiai:\nZSXY yra 15SWC8081751205\nZS X,Y yra 15SWC 80817,51205",
  "addPointToolTip": "Įtraukti GRG pradžią",
  "cellWidth": "Gardelės plotis (x)",
  "cellHeight": "Gardelės aukštis (y)",
  "invalidNumberMessage": "Įvesta reikšmė yra netinkama",
  "invalidRangeMessage": "Reikšmė turi būti didesnė nei 0.",
  "gridAngleInvalidRangeMessage": "Reikšmė turi būti tarp -89,9 ir 89,9",
  "formatIconTooltip": "Formato įvestis",
  "coordInputLabel": "GRG pradžia (DD)",
  "setCoordFormat": "Nustatyti koordinačių formato eilutę",
  "prefixNumbers": "Pridėti „+/-“ prefiksą prie teigiamų ir neigiamų skaičių",
  "cancelBtn": "Atšaukti",
  "applyBtn": "Taikyti",
  "comfirmInputNotation": "Patvirtinkite įvesties žymėjimą",
  "notationsMatch": "žymėjimai atitinka įvestį, patvirtinkite, kurį norite naudoti:",
  "numberOfCellsHorizontal": "# Horizontalios gardelės",
  "numberOfCellsVertical": "# Vertikalios gardelės",
  "gridAngle": "Tinklelio pasukimas",
  "tooManyCellsErrorMessage": "Bandote sukurti tinklelį, kurį sudaro 2 000 gardelių. Rekomenduojama sumažinti kuriamų gardelių skaičių, pakeičiant tinklelio dydį arba tinklelio plotą.",
  "missingParametersMessage": "<p>Nėra GRG kūrimo formos arba jos parametrai netinkami, Patikrinkite:</p><ul><li>Ar nubrėžtas GRG plotas.</li><li>Ar tinkamos gardelės pločio ir aukščio vertės.</li></ul>",
  "missingOriginParametersMessage": "<p>Nėra GRG kūrimo formos arba jos parametrai netinkami, Patikrinkite:</p><ul><li>Ar nustatyta GRG pradžia.</li><li>Ar tinkamos laiko, greičio ir kampo įvesties vertės.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Nėra GRG kūrimo formos arba jos parametrai netinkami. Patikrinkite, ar tinkamos gardelės pločio ir aukščio įvesties vertės.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Nėra GRG kūrimo formos arba jos parametrai netinkami. Patikrinkite, ar tinkamos horizontalių ir vertikalių gardelių skaičiaus įvesties vertės.</p>",
  "drawPointToolTip": "Spustelėkite GRG pradžios taškui pridėti",
  "missingLayerNameMessage": "Prieš publikuojant reikia įvesti tinkamą sluoksnio pavadinimą",
  "parseCoordinatesError": "Negalima analizuoti koordinačių. Patikrinkite savo įvestį.",
  "grgPolarRegionError": "GRG aprėptis išsitenka poliariniame regione. Į šį regioną patenkančios gardelės nebus kuriamos.",
  "grgPolarOriginError": "GRG pradžios taškas negali būti poliariniame regione, kai kuriama GRG pagal nuorodinę sistemą.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Laipsniai, Minutės, Sekundės",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dešimtainiai laipsniai – platuma / ilguma",
  "DDLongLatNotation": "Dešimtainiai laipsniai – ilguma / platuma",
  "DDMLatLongNotation": "Dešimtainių laipsnių minutės – platuma / ilguma",
  "DDMLongLatNotation": "Dešimtainių laipsnių minutės – ilguma / platuma",
  "DMSLatLongNotation": "Dešimtainių laipsnių sekundės – platuma / ilguma",
  "DMSLongLatNotation": "Dešimtainių laipsnių sekundės – ilguma / platuma",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - dažnio raidė",
  "UTMHemNotation": "UTM – pusrutulis (Š/P)"
});