define({
  "_widgetLabel": "Pametni uređivač",
  "_featureAction_SmartEditor": "Pametni uređivač",
  "noEditPrivileges": "Vaš nalog nema dozvolu za kreiranje ili izmenu podataka.",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Nije aktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL ",
  "snapStr": " da biste omogućili snapovanje",
  "noAvailableTempaltes": "Nema dostupnih šablona",
  "editorCache": " - Keš uređivača",
  "presetFieldAlias": "Polje",
  "presetValue": "Unapred postavljena vrednost",
  "usePresetValues": " Koristi unapred postavljene vrednosti (samo za nove geoobjekte)",
  "editGeometry": " Uredi geometriju",
  "savePromptTitle": "Sačuvaj geoobjekat",
  "savePrompt": "Želite li da sačuvate trenutni geoobjekat?",
  "deletePromptTitle": "Obriši geoobjekat",
  "deletePrompt": "Želite li zaista da obrišete izabrani geoobjekat?",
  "attachmentLoadingError": "Greška pri otpremanju priloga",
  "attachmentSaveDeleteWarning": "Upozorenje: izmene na prilozima se automatski čuvaju",
  "autoSaveEdits": "Automatski čuva izmene",
  "addNewFeature": "Kreiraj novi geoobjekat",
  "featureCreationFailedMsg": "Kreiranje novog zapisa/geoobjekta nije moguće",
  "noRelatedFeatureFoundMsg": "Nema pronađenih povezanih zapisa/geoobjekata",
  "relatedItemTitle": "Povezana tabela/sloj",
  "invalidRelationShipMsg": "Vodite računa da primarno ključno polje: '${parentKeyField}' ima važeću vrednost",
  "pendingFeatureSaveMsg": "Sačuvajte izmene geoobjekta pre kreiranja povezanog geoobjekta.",
  "attachmentsRequiredMsg": "(*) Prilozi su obavezni.",
  "filterEditor": {
    "all": "Sve",
    "noAvailableTempaltes": "Nema dostupnih šablona",
    "searchTemplates": "Pretraži šablone"
  },
  "invalidConfiguration": "Vidžet nije konfigurisan ili slojevi u konfiguraciji više nisu na mapi. Otvorite aplikaciju u graditeljskom režimu i ponovo konfigurišite vidžet.",
  "geometryServiceURLNotFoundMSG": "Dobijanje URL servisa geometrije nije moguće"
});