define({
  "_widgetLabel": "क्वेरी",
  "executeQueryTip": "क्वेरी को निष्पादित करने के लिए निम्न कार्य आइटम में से एक पर क्लिक करें।",
  "invalidConfig": "अमान्य कॉन्फ़िगरेशन। कृपया सही कॉन्फ़िगरेशन प्राप्त करने के लिए क्वेरी सेटिंग पृष्ठ का उपयोग करें।",
  "queryParams": "विकल्प",
  "parameters": "विकल्प",
  "queries": "क्वेरीज़",
  "apply": "लागू करें",
  "queryResults": "परिणाम",
  "clear": "हटाएं",
  "noResults": "कोई फीचर नहीं पाई गई है।",
  "queryError": "क्वेरी विफल रही!",
  "numberFound": "मिली फीचर्स की संख्या",
  "mapExtentTip": "परिणामों को वर्तमान मानचित्र क्षेत्र तक सीमित करें।",
  "noValue": "कोई मान नहीं",
  "and": "और",
  "stringOperatorIs": "है",
  "stringOperatorIsNot": "नहीं है",
  "stringOperatorStartsWith": "इससे प्रारंभ होने वाला",
  "stringOperatorEndsWith": "इस पर समाप्त होने वाला",
  "stringOperatorContains": "शामिल करता है",
  "stringOperatorDoesNotContain": "इसमें शामिल नहीं",
  "stringOperatorIsBlank": "खाली है",
  "stringOperatorIsNotBlank": "खाली नहीं है",
  "dateOperatorIsOn": "पर है",
  "dateOperatorIsNotOn": "पर नहीं है",
  "dateOperatorIsBefore": "पहले का है",
  "dateOperatorIsAfter": "बाद का है",
  "dateOperatorDays": "दिन",
  "dateOperatorWeeks": "सप्ताह",
  "dateOperatorMonths": "महीने",
  "dateOperatorInTheLast": "अंतिम में",
  "dateOperatorNotInTheLast": "अंतिम में नहीं",
  "dateOperatorIsBetween": "बीच में",
  "dateOperatorIsNotBetween": "बीच का नहीं है",
  "dateOperatorIsBlank": "खाली है",
  "dateOperatorIsNotBlank": "खाली नहीं है",
  "numberOperatorIs": "है",
  "numberOperatorIsNot": "नहीं है",
  "numberOperatorIsAtLeast": "कम से कम",
  "numberOperatorIsLessThan": "से कम",
  "numberOperatorIsAtMost": "अधिकतम है",
  "numberOperatorIsGreaterThan": "से अधिक है",
  "numberOperatorIsBetween": "बीच में",
  "numberOperatorIsNotBetween": "बीच का नहीं है",
  "numberOperatorIsBlank": "खाली है",
  "numberOperatorIsNotBlank": "खाली नहीं है",
  "operationalLayerTip": "परिचालन लेयर के रूप में परिणाम जोड़े",
  "queryResult": "क्वेरी के परिणाम",
  "specifyParamsTip": "इस कार्य के लिए पैरामीटर निर्दिष्ट करें",
  "useSpatialFilter": "फीचर को सीमित करने के लिए स्पेश्यिल फिल्टर का प्रयोग करें",
  "useCurrentMapExtent": "वर्तमान मानचित्र क्षेत्र को केवल पारस्परिक फीचर",
  "drawGraphicOnMap": "केवल उपयोगकर्ता निर्धारित क्षेत्र को इंटरसेक्ट करते फीचर्स",
  "specifySpatialFilterMsg": "इस कार्य के लिए स्पेश्यिल फिल्टर निर्दिष्ट करें।",
  "clearResults": "परिणाम साफ करें",
  "operationalTip": "इस विकल्प के चयनित होने के साथ, \"${clearResults}\" बटन क्लिक होनें तक परिणामों को मानचित्र पर रखा जाएगा।",
  "noneQueryTip": "इस विजेट के लिए कोई क्वेरी कार्य कॉन्फ़िगर नहीं किया गया था।",
  "noPermissionsMsg": "आप को इस सेवा का उपयोग करने की अनुमति नहीं है।",
  "attributesFromRelationship": "संबंधित तालिका से विशेषताएं",
  "tasks": "कार्य",
  "applySpatialFilterToLimitResults": "परिणामों को सीमित करने के लिए एक स्पेश्यिल फिल्टर लागू करें",
  "useCurrentExtentTip": "केवल वर्तमान मानचित्र सीमा के भीतर फीचर लौटाता है",
  "useDrawGraphicTip": "केवल मानचित्र पर बनाई गई आकृति को इंटरसेक्ट करती फीचर्स लौटाता है",
  "useFeaturesTip": "केवल वही फीचर लौटाता है जिसके दूसरी लेयर में स्पेशियल संबंध वाली फीचर है",
  "noSpatialLimitTip": "मानचित्र की पूर्ण सीमा के भीतर फीचर लौटाता है",
  "applySearchDistance": "एक खोज दूरी लागू करें",
  "spatialRelationship": "स्पेशियल संबंध",
  "relatedLayer": "संबंधित लेयर",
  "bufferDistance": "बफर दूरी",
  "miles": "मील",
  "kilometers": "किलोमीटर",
  "feet": "फ़ीट",
  "meters": "मीटर",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "back": "पीछे जाएँ",
  "execute": "निष्पादित करें",
  "zoomTo": "जूम करें",
  "openAttributeTable": "विशेषता तालिका में दिखाएँ",
  "noResult": "कोई परिणाम नही।",
  "noTask": "कोई कार्य नहीं।",
  "removeThisResult": "इस परिणाम को निकालें",
  "attributeCriteira": "विशेषताओं के मानदंड",
  "spatialFilter": "विशेषता के मानदंड",
  "value": "मान",
  "noAttributeSpatialFilterTip": "कोई फिल्टर परिभाषित नहीं हैं। सभी फीचर्स लौटाई जाएंगी।",
  "showAllRelatedRecords": "सभी संबंधित रिकॉर्ड दिखाएँ",
  "changeSymbol": "चिन्ह बदलें",
  "queryCriteira": "क्वेरी मापदंड",
  "customQuery": "कस्टम क्वेरी",
  "layer": "लेयर",
  "createCustomQuery": "कस्टम क्वेरी बनाएँ।"
});