define({
  "layerSelect": "Izaberite sloj snimka",
  "displayMeasureResultInPopup": "Prikaži rezultate merenja u iskačućem prozoru",
  "angularUnitSelect": "Podrazumevana jedinica za merenje ugla",
  "linearUnitSelect": "Podrazumevana linearna jedinica",
  "areaUnitSelect": "Podrazumevana jedinica površine",
  "displayOperationSelect": "Izaberi radnje merenja",
  "errorSectionMessage": "Nijedan od slojeva ne podržava mogućnost premeravanja.",
  "unitLabel": {
    "esriInches": "Inči",
    "esriFeet": "Stope",
    "esriYards": "Jardi",
    "esriMiles": "Milje",
    "esriNauticalMiles": "Nautičke milje",
    "esriMillimeters": "Milimetri",
    "esriCentimeters": "Centimetri",
    "esriDecimeters": "Decimetri",
    "esriMeters": "Metri",
    "esriKilometers": "Kilometri",
    "esriDURadians": "Radijani",
    "esriDUDecimalDegrees": "Stepeni",
    "esriSquareInches": "Kvadratni inči",
    "esriSquareFeet": "Kvadratne stope",
    "esriSquareYards": "Kvadratni jardi",
    "esriAcres": "Ari",
    "esriSquareMiles": "Kvadratne milje",
    "esriSquareMillimeters": "Kvadratni milimetri",
    "esriSquareCentimeters": "Kvadratni centimetri",
    "esriSquareDecimeters": "Kvadratni decimetri",
    "esriSquareMeters": "Kvadratni metri",
    "esriAres": "Ari",
    "esriHectares": "Hektari",
    "esriSquareKilometers": "Kvadratni kilometri"
  },
  "operationLabel": {
    "esriMensurationPoint": "Lokacija",
    "esriMensurationDistanceAndAngle": "Rastojanje i ugao",
    "esriMensurationAreaAndPerimeter": "Ugao i opseg",
    "esriMensurationHeightFromBaseAndTop": "Visina: od osnove do vrha",
    "esriMensurationHeightFromBaseAndTopShadow": "Visina: od osnove do vrha senke",
    "esriMensurationHeightFromTopAndTopShadow": "Visina: od vrha do vrha senke",
    "esriMensurationCentroid": "Težište",
    "esriMensurationPoint3D": "Lokacija (3D)",
    "esriMensurationDistanceAndAngle3D": "Rastojanje i ugao (3D)",
    "esriMensurationAreaAndPerimeter3D": "Površina i obim (3D)",
    "esriMensurationCentroid3D": "Težište (3D)"
  }
});