define({
  "_widgetLabel": "スマート エディター",
  "_featureAction_SmartEditor": "スマート エディター",
  "noEditPrivileges": "ご使用のアカウントには、データを作成/変更する権限がありません。",
  "widgetActive": "アクティブ",
  "widgetNotActive": "アクティブではない",
  "pressStr": "押す ",
  "ctrlStr": " Ctrl キー ",
  "snapStr": " スナップを有効にします",
  "noAvailableTempaltes": "利用可能なテンプレートがありません",
  "editorCache": " - エディターのキャッシュ",
  "presetFieldAlias": "フィールド",
  "presetValue": "設定済みの値",
  "usePresetValues": " 設定済みの値の使用 (新規フィーチャのみ)",
  "editGeometry": " ジオメトリの編集",
  "savePromptTitle": "フィーチャの保存",
  "savePrompt": "現在のフィーチャを保存しますか？",
  "deletePromptTitle": "フィーチャの削除",
  "deletePrompt": "選択フィーチャを削除しますか？",
  "attachmentLoadingError": "アタッチメントのアップロード中にエラーが発生しました",
  "attachmentSaveDeleteWarning": "警告: アタッチメントへの変更は自動的に保存されます",
  "autoSaveEdits": "編集内容を自動的に保存",
  "addNewFeature": "新しいフィーチャの作成",
  "featureCreationFailedMsg": "新しいレコード/フィーチャを作成できません。",
  "noRelatedFeatureFoundMsg": "関連するレコード/フィーチャが見つかりませんでした。",
  "relatedItemTitle": "関連テーブル/レイヤー",
  "invalidRelationShipMsg": "主キー フィールドを確認してください: '${parentKeyField}' に有効な値があります。",
  "pendingFeatureSaveMsg": "関連フィーチャを作成する前に、フィーチャの編集を保存してください。",
  "attachmentsRequiredMsg": "(*) アタッチメントが必要です。",
  "filterEditor": {
    "all": "すべて",
    "noAvailableTempaltes": "利用可能なテンプレートがありません",
    "searchTemplates": "テンプレートの検索"
  },
  "invalidConfiguration": "ウィジェットが構成されていないか、構成で指定されたレイヤーがマップ内に存在しません。アプリをビルダー モードで開き、ウィジェットを再構成してください。",
  "geometryServiceURLNotFoundMSG": "ジオメトリ サービスの URL を取得できません"
});