define({
  "_widgetLabel": "Suitability Modeler",
  "general": {
    "clear": "Očisti",
    "cancel": "Odustani",
    "save": "Pokreni",
    "saveAs": "Izvezi"
  },
  "saveModel": {
    "save": "Izvezi",
    "title": "Naziv: ",
    "summary": "Sažetak: ",
    "description": "Opis: ",
    "tags": "Oznake: ",
    "folder": "Mapa: ",
    "homeFolderPattern": "{username} (početno)",
    "failed": "Izvoz nije uspio."
  },
  "util": {
    "colorRamp": {
      "1": "Iznimno nisko",
      "2": "Vrlo nisko",
      "3": "Nisko",
      "4": "Nisko srednje",
      "5": "Srednja",
      "6": "Visoko srednje",
      "7": "Visoko",
      "8": "Vrlo visoko",
      "9": "Iznimno visoko",
      "low": "Nisko",
      "high": "Visoko",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Zamijeni"
    }
  },
  "wro": {
    "caption": "Suitability Modeler",
    "browsePrompt": "Usluga ponderiranog preklapanja",
    "selectLayersCaption": "Odaberi slojeve",
    "selectLayers": "Slojevi",
    "designModelCaption": "Model dizajna",
    "designModel": "Model dizajna",
    "transparency": "Prozirnost",
    "visible": "Vidljivo",
    "total": "Ukupno",
    "unableToLoad": "Nije moguće učitati model.",
    "projectNotOpen": "Projekt nije otvoren.",
    "readMore": "Pročitajte više",
    "validation": {
      "validating": "Provjera valjanosti...",
      "invalidItemCaption": "Upozorenje usluge ponderiranog preklapanja",
      "notAnImageService": "Ova stavka nije usluga slike.",
      "notAWroService": "Ova stavka nije usluga ponderiranog preklapanja.",
      "undefinedUrl": "URL ove stavke nije definiran.",
      "inaccessible": "Usluga nije dostupna.",
      "generalError": "Nije moguće otvoriti stavku.",
      "missingFieldPattern": "{field} je obvezno polje",
      "notAllowRasterFunction": "Funkcija allowRasterFunction mora se postaviti kao istinita",
      "notNearestResampling": "Funkcija defaultResamplingMethod mora biti najbliža",
      "notIsWeightedOverlayProp": "Ključno svojstvo IsWeightedOverlay mora se postaviti kao istinito",
      "invalidLink": "URL nije važeći. Otvaranje web-mjesta za odabrani sloj nije uspjelo.",
      "unexpectedError": "Došlo je do neočekivanog stanja.",
      "rangeMessage": "Vrijednost mora biti između ${0} i ${1}",
      "rangeMessage100": "Vrijednost mora biti između 0 i 100",
      "maxLayers": "Uslugom je dopušteno maksimalno ${0} sloj(ev)a, prije dodavanja novog, prvo morate ukloniti sloj.",
      "notFound": "Sloj ${0} nije pronađen u usluzi ponderiranog preklapanja",
      "wroServiceNotDefined": "Nema definirane usluge ponderiranog preklapanja za model.",
      "overlayLayerOutputInvalid": "Izlazna vrijednost raspona ponovnog kartiranja [${1}] sloja preklapanja [${0}] nedostaje ili nije važeća",
      "overlayLayerInputInvalid": "Ulazna min./maks. vrijednost raspona ponovnog kartiranja [${1}] sloja preklapanja [${0}] nedostaje ili nije važeća",
      "overlayLayerRangesMissing": "Sloju preklapanja [${0}] nedostaju rasponi ponovnog kartiranja",
      "overlayLayerWeight": "Ponderi sloja preklapanja moraju zbrajanjem dati 100",
      "overlayLayerRequired": "Potreban je barem jedan sloj preklapanja",
      "overlayLayerNotDefined": "Slojevi preklapanja nisu definirani",
      "requiresColormap": "Za funkciju rastera potrebna je karta boja, no za model nije definirana važeća karta boja",
      "createModelError": "Pogreška pri stvaranju modela",
      "invalidModel": "Model nije važeći",
      "imageServiceNotDefined": "Sloj usluge slike nije definiran",
      "imageLayerNotDefined": "Sloj usluge slike nije definiran",
      "histogramNotDefined": "Nije definirana funkcija ponderiranog histograma preklapanja."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zelena Žuta Crvena",
      "Red Yellow Green": "Crvena Žuta Zelena",
      "Yellow to Dark Red": "Žuta do tamnocrvena",
      "Dark Red to Yellow": "Tamno crvena do žuta",
      "Light Gray to Dark Gray": "Svijetlo siva do tamno siva",
      "Dark Gray to Light Gray": "Tamno siva do svijetlo siva",
      "Light Brown to Dark Brown": "Svijetlo smeđa do tamno smeđa",
      "Dark Brown to Light Brown": "Tamno smeđa do svijetlo smeđa",
      "Full Spectrum - Bright Red to Blue": "Puni spektar – Jarko crvena do plava",
      "Full Spectrum - Bright Blue to Red": "Puni spektar – Jarko plava do crvena",
      "Partial Spectrum - Yellow to Blue": "Djelomični spektar – Žuto do plavo",
      "Partial Spectrum - Blue to Yellow": "Djelomični spektar – Plavo do žuto",
      "Yellow-Green to Dark Blue": "Žuto-zeleno do tamno plavo",
      "Dark Blue to Yellow-Green": "Tamno plavo do žuto-zeleno",
      "Cold to Hot Diverging": "Širenje od hladnog do vrućeg",
      "Hot to Cold Diverging": "Širenje od vrućeg do hladnog",
      "Surface - Low to High": "Površina – nisko do visoko",
      "Surface - High to Low": "Površina – visoko do nisko"
    }
  },
  "tabs": {
    "layers": "Slojevi",
    "model": "Model",
    "chart": "Grafikon"
  },
  "chart": {
    "prompt": "Geoobjekti",
    "working": "Ažuriranje...",
    "polygonTool": "Nacrtaj poligon",
    "freehandPolygonTool": "Nacrtaj poligon prostoručno",
    "selectTool": "Odaberi iz sloja",
    "panTool": "Kreći se po slici",
    "clearButton": "Očisti",
    "noModelLayer": "Nema modela.",
    "noSubjectLayers": "Karta nema poligonske slojeve.",
    "tipPattern": "${category} - ${label}: ${percent} %",
    "tipPattern2": "${category}: ${percent} %",
    "labelPattern": "${category} - ${label}"
  }
});