define({
  "tabs_section_Label": "Faner",
  "addTab": "Tilføj fane",
  "layerName": "Lag",
  "layerType": "Analysetype",
  "layerLabel": "Mærke",
  "actions": "Handlinger",
  "closest": "Nærmeste objekt",
  "proximity": "Nærhed",
  "summary": "Resumé",
  "select_lbl": "-- Vælg --",
  "general_setting_Label": "Generelle indstillinger",
  "units_text_lbl": "Afstandsenheder",
  "maximum_distance_lbl": "Maksimal afstand til nærmeste objekt",
  "buffer_text_lbl": "Buffermærkat",
  "buffer_lbl": "Bufferafstand",
  "buffer_max_lbl": "Maksimal bufferafstand",
  "buffer_min_lbl": "Minimal bufferafstand",
  "buffer_default_lbl": "Standardbufferafstand",
  "not_less_than_max": "Afstanden skal være mindre end den maksimale bufferafstand",
  "not_between": "Afstanden skal være mellem den minimale og den maksimale bufferafstand",
  "not_more_than_min": "Afstanden skal være større end den minimale bufferafstand",
  "not_valid_number": "Skal være et gyldigt tal",
  "invalid_value": "${type}-værdien er ugyldig",
  "routing_checkBox": "Aktivér kørselsvejledninger",
  "weather_Label": "Vejrindstillnger",
  "weather_checkBox": "Aktivér vejr",
  "weather_map_layers": "Vælg vejrlag...",
  "selected_map_layers": " vejrlag valgt",
  "instruction_weather": "Vis vejroplysninger i panelet.",
  "instruction_weather_layers": "Vis flere vejrlag.",
  "instruction_weather_metric": "Vis standard-/metriske værdier.",
  "selectLayers": "Vælg vejrlag",
  "weather_removed_message": "Vejrindstillinger er ikke længere tilgængelige for denne widget.",
  "currentlySelectedLayer": "Vælg fra kortlag",
  "missingTabLabel": "Mindst én fane mangler sin mærkat",
  "missingLayerInWebMap": "Ingen operationelle lag fundet.",
  "selectFields": "Vælg felter",
  "addField": "Tilføj felt",
  "sum": "Sum",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Gennemsnit",
  "count": "OPTÆLLING",
  "area": "OMRÅDE",
  "length": "LÆNGDE",
  "count_checkBox": "Vis objekttælling",
  "area_checkBox": "Vis sum af område",
  "length_checkBox": "Vis sum af længde",
  "max_records": "Maksimumgrænse nået",
  "save_label": "Gem indstillinger",
  "save_checkbox": "Aktivér lagring",
  "report_label": "Rapportindstillinger",
  "report_checkbox": "Aktivér rapport",
  "csv_label": "Tillad eksport af resultater",
  "csv_checkbox": "Eksportér alle felter",
  "display_label": "Indstillinger for visning",
  "display_checkbox": "Vis opsummerede objekter",
  "snapshot_label": "Snapshot-indstillinger",
  "snapshot_checkbox": "Aktivér snapshot",
  "must_select_template": "Vælg en af redigeringsskabelonerne under Gem indstillinger.",
  "count_label": "Optællingsmærke",
  "area_label": "Områdemærke",
  "length_label": "Længdemærke",
  "invalid_string_width": "Værdien er for lang. ",
  "layer_type_not_supported": "Lagtype understøttes ikke",
  "groupedSummary": "Grupperede optællinger",
  "groupByField": "Gruppér efter felt",
  "labelType": "Tilknyt etiket",
  "prefix": "Som præfiks",
  "suffix": "Som suffiks",
  "need_group_field": "Brug redigeringshandlingen til at definere en gruppe efter felt.",
  "fieldTitle": "Felt",
  "typeTitle": "Type",
  "actionsTitle": "Handlinger",
  "save_point_checkbox": "Gem punkter",
  "save_line_checkbox": "Gem linjer",
  "save_poly_checkbox": "Gem polygoner",
  "no_valid_popup_fields": "Ingen gyldige felter i popup'en. Brug redigeringshandlingen til at definere et felt.",
  "no_valid_fields": "Ingen gyldige felter. Brug redigeringshandlingen til at vise indstillinger.",
  "incident_label": "Fanemærke",
  "locate_incident_label": "Mærke for interesseområde",
  "incident": "Hændelse",
  "locate_incident": "Find hændelse",
  "buffer_value": "Bufferafstand",
  "tab_options": "Analysis",
  "export_options": "Output",
  "instruction_save": "Gem position til en featuretjeneste.",
  "instruction_snapshot": "Opret et webkort ud fra en position.",
  "instruction_report": "Opret en udskrevet rapport for positionen.",
  "instruction_all_fields": "Eksportér alle felter med CSV-download.",
  "data_label": "Dataoutputindstillinger",
  "layer_error": "Lag mangler eller er ugyldigt.",
  "visibility_checkBox": "Deaktivér styring af lagsynlighed",
  "downloadTab": {
    "reportLegend": "Rapportindstillinger",
    "textColorLabel": "Vælg farve til kolonnetitler",
    "setButtonLabel": "Indstil",
    "printGPServiceLabel": "Udskriv tjeneste-URL",
    "logoLabel": "Logo",
    "logoChooserHint": "Klik på billedikonet for at redigere billedet",
    "footnoteLabel": "Fodnote"
  }
});