define({
  "_widgetLabel": "Distancia y dirección",
  "tabLineTitle": "Línea",
  "tabCircleTitle": "Círculo",
  "tabEllipseTitle": "Elipse",
  "tabRingsTitle": "Anillos",
  "multipleNotationsMessage": " notaciones que coinciden con su entrada. Confirme cuál desea usar:",
  "invalidCoordinateMessage": "Coordenada no válida",
  "confirmInputNotationMessage": "Confirmar notación de entrada",
  "prefixSuffixMessage": "Se ha detectado que la coordenada de entrada tiene un prefijo y un sufijo para el valor de la latitud o la longitud y la coordenada devuelta se basa en el prefijo.",
  "rememberDecisionMessage": "Recordar mi decisión y no volver a preguntar.<br/>",
  "majorAxisTooltipMessage": "Haga clic en la longitud del eje mayor",
  "minorAxisTooltipMessage": "Mueva el ratón hacia atrás hasta la posición de inicio para establecer el eje menor y terminar de dibujar la elipse",
  "clickToFinishLineMessage": "Haga clic para terminar de dibujar la línea",
  "doubleClickEllipseMesage": "Haga doble clic para terminar de dibujar los anillos de rango",
  "invalidCoordinateTypeMessage": "Imposible determinar su tipo de coordenadas de entrada. Compruebe la entrada",
  "noCenterPointSetMessage": "No hay ningún punto central definido. Compruebe la entrada",
  "ellipseMajorAxis": "Eje mayor",
  "ellipseMinorAxis": "Eje menor",
  "degreesRangeMessage": "El valor debe estar comprendido entre 0 y 360",
  "millsRangeMessage": "El valor debe estar comprendido entre 0 y 6400",
  "lengthLabel": "Longitud",
  "angleLabel": "Angle",
  "startPointLabel": "Punto inicial",
  "endPointLabel": "Extremo",
  "centerPointLabel": "Punto central",
  "distanceTableErrorMessage": "La tabla de distancias está vacía. Asegúrese de introducir algunas distancias.",
  "setCoordFormatStringMessage": "Definir cadena de caracteres de formato de coordenadas",
  "prefixMessage": "Agregar prefijo '+/-' a los números positivos y negativos",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Grados decimales - Latitud/longitud",
  "DDLongLatNotation": "Grados decimales - Longitud/latitud",
  "DDMLatLongNotation": "Grados minutos decimales - Latitud/longitud",
  "DDMLongLatNotation": "Grados minutos decimales - Longitud/latitud",
  "DMSLatLongNotation": "Grados minutos segundos - Latitud/longitud",
  "DMSLongLatNotation": "Grados minutos segundos - Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra de banda",
  "UTMHemNotation": "UTM - Hemisferio (N/S)",
  "circleTitle": "Crear círculo desde",
  "radiusLabel": "Radio",
  "diameterLabel": "Diámetro",
  "startPointPlaceHolderLabel": "Introducir coordenadas",
  "formatInputLabel": "Formato de entrada",
  "drawCircleLabel": "Dibujar círculo",
  "drawLineLabel": "Dibujar línea",
  "createCircleInteractivelyLabel": "Crear círculo interactivamente",
  "rangeErrorMessage": "Radio o diámetro no válido",
  "numericInvalidMessage": "Introduzca un valor numérico",
  "timeLabel": "Hora",
  "invalidTimeMessage": "Valor de hora no válido",
  "hoursLabel": "Horas",
  "minutesLabel": "Minutos",
  "secondsLabel": "Segundos",
  "rateLabel": "Velocidad",
  "invalidDistanceMessage": "Valor de distancia no válido",
  "feetSecondsLabel": "Pies / segundo",
  "feetHourLabel": "Pies / hora",
  "kmSecondLabel": "Kilómetros / segundo",
  "kmHourLabel": "Kilómetros / hora",
  "metersSecondLabel": "Metros / segundo",
  "metersHourLabel": "Metros / hora",
  "milesSecondLabel": "Millas / segundo",
  "milesHourLabel": "Millas / hora",
  "nauticalMilesSecondLabel": "Millas náuticas / segundo",
  "nauticalMilesHourLabel": "Millas náuticas / hora",
  "clearGraphicsLabel": "Borrar gráficos",
  "ellipseTypeLabel": "Tipo de elipse",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Completo",
  "drawEllipseLabel": "Dibujar elipse",
  "createEllipseInteractively": "Crear elipse interactivamente",
  "axisLabel": "Eje",
  "majorRadiusLabel": "Mayor (radio)",
  "axisErrorMessage": "El valor debe ser mayor que 0",
  "minorRadiusLabel": "Menor (radio)",
  "orientationLabel": "Orientación",
  "orientationErrorMessage": "El valor debe estar comprendido entre 0 y 360",
  "warningMessage": "Advertencia: Los gráficos generados con la herramienta de elipse no son geodésicos",
  "fromLabel": "Desde",
  "distanceBearingLabel": "Distancia y rumbo",
  "pointsLabel": "Puntos",
  "createLineInteractively": "Crear línea interactivamente",
  "lineLengthErrorMessage": "Longitud de línea no válida",
  "degreesLabel": "Grados",
  "milsLabel": "Mili-radianes",
  "lineTypeLabel": "Tipo",
  "interactiveLabel": "Interactiva",
  "fixedLabel": "Fijo",
  "originLabel": "Origen",
  "cumulativeLabel": "Acumulativo",
  "numberOfRingsLabel": "Número de anillos",
  "ringsErrorMessage": "Número de anillos no válido",
  "distanceBetweenRingsLabel": "Distancia entre anillos",
  "ringsDecimalErrorMessage": "Introduzca un valor numérico con 2 posiciones decimales",
  "distanceUnitsLabel": "Unidades de distancia",
  "distancesLabel": "Distancias",
  "numberOfRadialsLabel": "Número de radiales",
  "upLabel": "Subir",
  "downLabel": "Abajo",
  "deleteLabel": "Eliminar",
  "radialsErrorMessage": "Número no válido de radiales. El máximo permitido es de 360",
  "addPointLabel": "Agregar punto",
  "valueLabel": "Valor",
  "valueText": "Introducir un valor",
  "actionLabel": "Acción"
});