define({
  "_widgetLabel": "Akıllı Düzenleyici",
  "_featureAction_SmartEditor": "Akıllı Düzenleyici",
  "noEditPrivileges": "Hesabınızın veri oluşturma veya değiştirme izni yok.",
  "widgetActive": "Etkin",
  "widgetNotActive": "Etkin Değil",
  "pressStr": "Basılacak Tuş ",
  "ctrlStr": " CTRL ",
  "snapStr": " yakalamayı etkinleştirmek için",
  "noAvailableTempaltes": "Kullanılabilir şablon yok",
  "editorCache": " - Düzenleyici Önbelleği",
  "presetFieldAlias": "Alan",
  "presetValue": "Ön Ayar Değeri",
  "usePresetValues": " Ön Ayar Değerlerini Kullan (Yalnızca yeni detaylar)",
  "editGeometry": " Geometriyi Düzenle",
  "savePromptTitle": "Detayı kaydet",
  "savePrompt": "Geçerli detayı kaydetmek ister misiniz?",
  "deletePromptTitle": "Detayı sil",
  "deletePrompt": "Seçili detayı silmek istediğinizden emin misiniz?",
  "attachmentLoadingError": "Ek yükleme hatası",
  "attachmentSaveDeleteWarning": "Uyarı: Ekler üzerinde yapılan değişiklikler otomatik olarak kaydedilir",
  "autoSaveEdits": "Düzenlemeyi otomatik olarak kaydeder",
  "addNewFeature": "Yeni detay oluştur",
  "featureCreationFailedMsg": "Yeni bir kayıt/detay oluşturulamıyor",
  "noRelatedFeatureFoundMsg": "İlgili Kayıt/Detay bulunamadı",
  "relatedItemTitle": "İlgili Tablo/Katman",
  "invalidRelationShipMsg": "Lütfen ‘${parentKeyField}’ birincil anahtar alanda geçerli bir değer bulunduğundan emin olun",
  "pendingFeatureSaveMsg": "Lütfen ilgili bir detay oluşturmadan önce detay düzenlemelerini kaydedin.",
  "attachmentsRequiredMsg": "(*) Ekler gereklidir.",
  "filterEditor": {
    "all": "Tümü",
    "noAvailableTempaltes": "Kullanılabilir şablon yok",
    "searchTemplates": "Şablon Ara"
  },
  "invalidConfiguration": "Araç yapılandırılmamış veya yapılandırmadaki katmanlar artık haritada değil. Uygulamayı oluşturucu modda açın ve aracı yeniden yapılandırın.",
  "geometryServiceURLNotFoundMSG": "Geometri Servisi URL’si alınamıyor"
});