define({
  "layerSelect": "Selecteer de beeldlaag",
  "displayMeasureResultInPopup": "Meetresultaten weergeven in een pop-up",
  "angularUnitSelect": "Standaard hoekeenheid",
  "linearUnitSelect": "Standaard lineaire eenheid",
  "areaUnitSelect": "Standaard oppervlakte-eenheid",
  "displayOperationSelect": "Selecteer meetopdrachten",
  "errorSectionMessage": "Geen van de lagen ondersteunen mensuratiemogelijkheden.",
  "unitLabel": {
    "esriInches": "Inch",
    "esriFeet": "Voet",
    "esriYards": "Yard",
    "esriMiles": "Mijl",
    "esriNauticalMiles": "Zeemijl",
    "esriMillimeters": "Millimeter",
    "esriCentimeters": "Centimeter",
    "esriDecimeters": "Decimeter",
    "esriMeters": "Meter",
    "esriKilometers": "Kilometer",
    "esriDURadians": "Radialen",
    "esriDUDecimalDegrees": "Graden",
    "esriSquareInches": "Vierkante inch",
    "esriSquareFeet": "Vierkante voet",
    "esriSquareYards": "Vierkante yard",
    "esriAcres": "Acres",
    "esriSquareMiles": "Vierkante mile",
    "esriSquareMillimeters": "Viekante millimeter",
    "esriSquareCentimeters": "Vierkante centimeter",
    "esriSquareDecimeters": "Vierkante decimeters",
    "esriSquareMeters": "Vierkante meter",
    "esriAres": "Are",
    "esriHectares": "Hectare",
    "esriSquareKilometers": "Vierkante kilometer"
  },
  "operationLabel": {
    "esriMensurationPoint": "Locatie",
    "esriMensurationDistanceAndAngle": "Afstand en hoek",
    "esriMensurationAreaAndPerimeter": "Oppervlakte en omtrek",
    "esriMensurationHeightFromBaseAndTop": "Hoogte: Basis naar boven",
    "esriMensurationHeightFromBaseAndTopShadow": "Hoogte: Basis naar boven-schaduw",
    "esriMensurationHeightFromTopAndTopShadow": "Hoogte: Boven naar boven-schaduw",
    "esriMensurationCentroid": "Zwaartepunt",
    "esriMensurationPoint3D": "Locatie (3D)",
    "esriMensurationDistanceAndAngle3D": "Afstand en hoek (3D)",
    "esriMensurationAreaAndPerimeter3D": "Oppervlakte en omtrek (3D)",
    "esriMensurationCentroid3D": "Zwaartepunt (3D)"
  }
});