define({
  "queries": "Užklausos",
  "addNew": "Pridėti naują",
  "newQuery": "Nauja užklausa",
  "queryLayer": "Užklausos sluoksnis",
  "setSource": "Nustatyti",
  "setDataSource": "Nustatykite duomenų šaltinį",
  "name": "Pavadinimas",
  "querySource": "Duomenų šaltinis",
  "queryName": "Užduoties pavadinimas",
  "queryDefinition": "Filtro apibrėžimas",
  "resultsSetting": "Rezultatų nustatymai",
  "symbolSetting": "Simbolio nustatymas",
  "resultSettingTip": "Nustatykite, ką ir kaip rodyti išvesties rezultatuose.",
  "resultItemTitle": "Kiekvieno rezultato elemento pavadinimas",
  "resultItemContent": "Bus rodomi šie laukų atributai",
  "fieldsSetTip": "Pažymėkite, kurie laukai turi būti rodomi. Pasirinkite laukus ir galėsite atnaujinti jų pseudonimus, išdėstymo tvarką ir formatavimą.",
  "addField": "Pridėti lauką",
  "visibility": "Matomumas",
  "alias": "Pseudonimas",
  "specialType": "Specialus tipas",
  "actions": "Veiksmai",
  "none": "Nėra",
  "link": "Nuoroda",
  "image": "Paveikslėliai",
  "noField": "Lauko nėra",
  "operationalLayerTip": "Pridėti rezultatus kaip darbinį sluoksnį",
  "setLayerSymbolTip": "Nustatykite užklausos rezultatų simbolį: ",
  "setSelectedSymbolTip": "Nustatykite pasirinkto elemento simbolį.",
  "notUseFilter": "Nenaudoti filtro",
  "setSourceTip": "Nustatykite užklausos šaltinį.",
  "setFilterTip": "Nustatykite filtrą tinkamai.",
  "ok": "Gerai",
  "cancel": "Atšaukti",
  "noFilterTip": "Nenustačius filtro sąlygos, ši užklausos užduotis nurodys visus nurodyto duomenų šaltinio elementus.",
  "relationships": "Ryšys",
  "addRelationshipLayer": "Pridėti naują ryšį",
  "relatedTo": "Susiję su",
  "selectOption": "Pasirinkite..",
  "resultItemSorting": "Gautų elementų rūšiavimas",
  "field": "Laukas",
  "sortingOrder": "Tvarka",
  "configureFieldsTip": "Sukonfigūruokite laukus, pagal kuriuos bus rūšiuojami užklausos rezultatai.",
  "setSortingFields": "Nustatyti rūšiavimo laukus",
  "ascending": "didėjančia tvarka",
  "descending": "Mažėjimo tvarka",
  "sortBy": "Rūšiuoti pagal",
  "thenBy": "Tada pagal",
  "addTask": "Įtraukti užduotį",
  "noTasksTip": "Nesukonfigūruota jokių užklausų. Norėdami pridėti naują, spustelėkite \"${newQuery}\".",
  "infoText": "Informacija",
  "filters": "Filtrai",
  "results": "Rezultatai",
  "optionsText": "Parinktys",
  "summaryText": "Santrauka",
  "attributeFilter": "Atributų filtras",
  "attributeFilterTip": "Apibrėžkite atributų išraišką, skirtą užklausos sluoksniams filtruoti valdiklyje.",
  "defineWhereClause": "Nurodykite užklausos \"where\" sąlygą.",
  "noExpressionDefinedTip": "Nenurodyta jokių sąlygų. Visi įrašai bus grąžinti.",
  "setExpressions": "Nustatyti išraiškas",
  "spatialFilter": "Erdviniai filtrai",
  "spatialFilterTip": "Pasirinkite, kuriuos erdvinius filtrus galės naudoti galutiniai vartotojai.",
  "defaultOption": "Numatytasis",
  "useCurrentExtentTip": "Grąžinti elementus tik šio žemėlapio aprėptyje",
  "useDrawGraphicTip": "Tik grąžinimo elementai, kurie susikerta su žemėlapyje nubrėžta figūra",
  "useFeaturesTip": "Grąžinti elementus, kurie turi erdvinį ryšį su kito sluoksnio elementais",
  "noSpatialLimitTip": "Grąžinti elementus viso žemėlapio aprėptyje",
  "drawingTools": "Pasirinkite braižymo įrankius",
  "bufferSettings": "Įgalinti buferio parinktį",
  "defaultDistance": "Numatytasis atstumas",
  "bufferDistance": "Buferio atstumas",
  "defaultUnit": "Numatytasis vienetas",
  "miles": "Mylios",
  "kilometers": "Kilometrai",
  "feet": "Pėdos",
  "meters": "Metrai",
  "yards": "Jardai",
  "nauticalMiles": "Jūrmylės",
  "availableSpatialRelationships": "Pasirinkite erdvinių ryšių taisykles",
  "setSpatialRelationships": "Nustatyti erdvinius ryšius",
  "availability": "Prieinamumas",
  "relationship": "Ryšys",
  "label": "Žymė",
  "intersect": "sukirsti",
  "contain": "aprėpti",
  "areContainedIn": "yra aprėpti",
  "cross": "kryžius",
  "envelopeIntersect": "apgaubų susikirtimas",
  "overlap": "persikloti",
  "areOverlapped": "yra užkloti",
  "touch": "paliesti",
  "within": "viduje",
  "areWithin": "yra viduje",
  "indexIntersect": "indeksų susikirtimas",
  "itemTitle": "Elemento antraštė",
  "displayFields": "Rodyti laukus",
  "sortingFields": "Rūšiuoti rezultatų elementus",
  "setDisplayFields": "Nustatyti rodomus laukus",
  "symbol": "Simbolis",
  "setSymbol": "Naudoti adaptuotą simbolį",
  "changeSymbolAtRuntime": "Leisti keisti simbolius vykdymo metu",
  "serviceSymbolTip": "Naudoti simbolius, apibrėžtus pagal sluoksnį",
  "exportTip": "Leisti eksportuoti rezultatus",
  "keepResultsTip": "Uždarius valdiklį palikti rezultatus ant žemėlapio",
  "queryRelatedRecords": "Ieškoti susijusiuose įrašuose",
  "createLayerForTaskTip": "Nurodyti, kaip užklausos užduotis kuria sluoksnius",
  "oneLayerForTaskTip": "Perrašyti sluoksnį kaskart, kai įvykdoma užklausa",
  "multipleLayerForTaskTip": "Kurti naują sluoksnį kaskart, kai įvykdoma užklausa",
  "makeDefault": "Nustatyti kaip numatytąjį",
  "icon": "Piktograma",
  "newTask": "Nauja užduotis",
  "addTaskTip": "Pridėti vieną arba daugiau užklausų į valdiklį ir konfigūruoti kiekvieno iš jų parametrus.",
  "webMapPopupTip": "Naudoti sluoksnių iškylančio lango konfigūraciją internetiniame žemėlapyje",
  "customPopupTip": "Konfigūruoti pasirinktą turinį",
  "showResultsSetActions": "Rodyti rezultatų rinkinio veiksmus",
  "zoomTo": "Pritraukti iki",
  "openAttributeTable": "Peržiūrėti atributų lentelėje",
  "content": "Turinys",
  "displaySQLTip": "Rodyti SQL užklausą galutiniams vartotojams",
  "useLayerDefaultSymbol": "Naudoti sluoksnio numatytąjį simbolį",
  "setCustomIcon": "Nustatyti pasirinktą piktogramą",
  "layerDefaultSymbolTip": "Naudoti sluoksnio numatytąjį simbolį",
  "uploadImage": "Įkelti paveikslėlį",
  "attributeCriteira": "Atributo kriterijai",
  "specifyFilterAtRuntimeTip": "Vartotojai turės nurodyti šios sąlygos parametrus.",
  "value": "REIKŠMĖ",
  "hideLayersTip": "Išjungti užklausos rezultatų sluoksnius, kai valdiklis uždarytas.",
  "tabLabels": "Skirtukų žymės",
  "tasks": "Užduotys",
  "queryCriteira": "Užklausos kriterijai",
  "allowCustomQuery": "Leisti kuri pasirinktinę užklausą"
});