define({
  "add": "Kliknutím přidáte nový",
  "title": "Nadpis",
  "placeholderBookmarkName": "Název záložky",
  "ok": "OK",
  "cancel": "Zrušit",
  "warning": "Dokončete úpravu!",
  "edit": "Upravit záložku",
  "errorNameExist": "Záložka již existuje!",
  "errorNameNull": "Neplatný název záložky!",
  "addBookmark": "Vytvořit nový",
  "thumbnail": "Miniatura",
  "thumbnailHint": "Kliknutím na obrázek jej aktualizujete.",
  "displayBookmarksAs": "Zobrazit záložky jako",
  "cards": "Karty",
  "list": "Seznam",
  "cardsTips": "Zobrazení karet",
  "listTips": "Zobrazení seznamu",
  "makeAsDefault": "Nastavit jako výchozí",
  "default": "Výchozí",
  "editable": "Povolit přidávání záložek ve widgetu.",
  "alwaysSync": "Zobrazit záložky z webové mapy",
  "configCustom": "Zobrazit vlastní záložky",
  "import": "Importovat",
  "create": "Vytvořit",
  "importTitle": "Importovat záložky",
  "importFromWeb": "Importovat záložky z aktuální webové mapy",
  "selectAll": "Vybrat vše",
  "noBookmarkInConfig": "Pro přidání záložek klikněte na Importovat nebo Vytvořit novou.",
  "noBookmarkInWebMap": "V mapě není nakonfigurovaná žádná záložka.",
  "extent": "Rozsah",
  "saveExtent": "Uložit rozsah mapy do této záložky",
  "savelayers": "Uložit viditelnost vrstev",
  "withVisibility": "S viditelností vrstev",
  "bookmark": "Záložka",
  "addBtn": "Přidat",
  "deleteBtn": "Smazat",
  "editBtn": "Upravit",
  "dragReorderTip": "Přidržením a tažením změníte pořadí",
  "deleteBtnTip": "Smazat záložku",
  "editBtnTip": "Upravit záložku"
});