define({
  "gridTabLabel": "Grid",
  "labelTabLabel": "Label",
  "referenceSystemTabLabel": "Sistem Referensi",
  "gridTabDescription": "Atur tampakan dan perilaku sel grid.",
  "cellOutlineColor": "Warna Kerangka Sel",
  "cellFillColor": "Warna Isi Sel",
  "transparency": "Transparansi",
  "cellShapeDropDown": "Bentuk Sel",
  "default": "Persegi Empat",
  "hexagon": "Heksagon",
  "cellUnitsDropDown": "Unit Sel",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nautical-miles": "Mil Laut",
  "gridOriginDropDown": "Asal Grid",
  "lowerLeft": "Kiri-Bawah",
  "lowerRight": "Kanan-Bawah",
  "upperLeft": "Kiri-Atas",
  "upperRight": "Kanan-Atas",
  "center": "Tengah",
  "labelTabDescription": "Atur tampakan dan perilaku label grid.",
  "labelSettings": "Gaya Label",
  "font": "Font",
  "textSize": "Ukuran Teks",
  "textColor": "Warna Teks",
  "halo": "Halo",
  "show": "Tampilkan",
  "labelTypeDropDown": "Jenis Label",
  "alphaNumeric": "Alfa-Numerik",
  "alphaAlpha": "Alfa-Alfa",
  "numeric": "Numerik",
  "labelDirectionDropDown": "Arah Label",
  "horizontal": "Horizontal",
  "vertical": "Vertikal",
  "labelOriginDropDown": "Asal Label",
  "referenceSystemlTabDescription": "Atur sistem referensi default.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Pengaturan Kunci - Ini akan mencegah pengguna dapat mengubah apa pun dari pengaturan terkonfigurasi dalam widget"
});