define({
  "symbolologyTabLabel": "Configura simbologia",
  "facilitiesDescription": "Layer del servizio",
  "demographicsDescription": "Layer dei dati demografici",
  "settingsTitle": "Impostazioni",
  "spillLocationLabel": "Posizione della perdita",
  "spillLocationButtonLabel": "Configurare le impostazioni della posizione della perdita",
  "IISettingsLabel": "Zona di isolamento iniziale",
  "IIButtonLabel": "Configurare le impostazioni di isolamento iniziale",
  "PASettingsLabel": "Zona di azione protettiva",
  "PAButtonLabel": "Configurare le impostazioni dell’azione protettiva",
  "downwindSettingsLabel": "Zona sottovento",
  "downwindButtonLabel": "Configurare le impostazioni della zona sottovento",
  "fireSettingsLabel": "Zona di isolamento antincendio",
  "fireButtonLabel": "Configurare le impostazioni dell’isolamento antincendio",
  "bleveSettingsLabel": "Zona di isolamento BLEVE",
  "bleveButtonLabel": "Configurare le impostazioni dell’isolamento BLEVE",
  "transparency": "Trasparenza",
  "outline": "Bordo",
  "fill": "Riempimento (Il colore si applica solo quando lo stile è impostato su tinta unita)",
  "style": "Stile",
  "lineStyles": {
    "esriSLSDash": "Trattino",
    "esriSLSDashDot": "Trattino punto",
    "esriSLSDashDotDot": "Trattino Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Trattino lungo",
    "esriSLSLongDashDot": "Trattino lungo punto",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trattino corto",
    "esriSLSShortDashDot": "Trattino corto punto",
    "esriSLSShortDashDotDot": "Trattino corto punto punto",
    "esriSLSShortDot": "Punto corto",
    "esriSLSSolid": "Tinta unita"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Indietro",
    "esriSFSCross": "Croce",
    "esriSFSDiagonalCross": "Diagonale",
    "esriSFSForwardDiagonal": "Avanti",
    "esriSFSHorizontal": "Orizzontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Tinta unita",
    "esriSFSVertical": "Verticale"
  }
});