define({
  root: ({
    add: "Click to add new",
    title: "Title",
    placeholderBookmarkName: "Bookmark name",
    ok: "OK",
    cancel: "Cancel",
    warning: "Please finish the edit!",
    edit: "Edit bookmark",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!",
    addBookmark: "Create new",
    thumbnail: "Thumbnail",
    thumbnailHint: "Click the image to update",

    displayBookmarksAs: "Display bookmarks as",
    cards: "Cards",
    list: "List",
    cardsTips: "Card view",
    listTips: "List view",
    makeAsDefault: "Make as default",
    default: "Default",
    editable: "Allow to add bookmarks in the widget.",
    alwaysSync: "Display bookmarks from web map",
    configCustom: "Display custom bookmarks",

    import: "Import",
    create: "Create",
    importTitle: "Import Bookmarks",
    importFromWeb: "Import bookmarks from current web map",
    selectAll: "Select All",
    noBookmarkInConfig: "Click “Import” or “Create New” to add bookmarks.",
    noBookmarkInWebMap: "No bookmark is configured in the map.",

    extent: "Extent",
    saveExtent: "Save map extent to this bookmark",
    savelayers: "Save layer visibility",
    withVisibility: "With layer visibility",
    bookmark:"Bookmark",

    addBtn: "Add",
    deleteBtn: "Delete",
    editBtn: "Edit",
    dragReorderTip: "Hold and drag to reorder",
    deleteBtnTip: "Delete the bookmark",
    editBtnTip: "Edit the bookmark"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
