define({
  "_widgetLabel": "Grafika mrežnih referenci",
  "newGRGFromAreaButtonLabel": "Definiraj mrežu s područja",
  "newGRGFromPointButtonLabel": "Definiraj mrežu s točke",
  "newGRGFromAreaTitle": "Definiraj mrežu s područja",
  "newGRGFromPointTitle": "Definiraj mrežu s točke",
  "newGRGBySizeButtonLabel": "Prema dimenziji",
  "newGRGFromRefSystemButtonLabel": "Prema referentnom sustavu",
  "newGRGByTimeLabel": "Prema vremenu i brzini",
  "newGRGFromNonStandardButtonLabel": "Definiraj nestandardnu mrežu",
  "newGRGAreaBySizeTitle": "GRG s područja prema dimenziji",
  "newGRGAreaBySizeDefineAreaLabel": "GRG područja",
  "addGRGAreaPolygonToolTip": "Nacrtaj GRG područje pomoću poligona",
  "addGRGAreaExtentToolTip": "Nacrtaj GRG područje pomoću obuhvata",
  "rotation": "Rotacija mreže",
  "numberRowsColumnsLabel": "Definiraj broj redaka i stupaca",
  "newGRGAreaByRefSystemTitle": "GRG s područja prema referentnom sustavu",
  "gridSize": "Veličina mreže",
  "UTMZoneandBand": "Zona mreže",
  "100000m": "100000 metara",
  "10000m": "10000 metara",
  "1000m": "1000 metara",
  "100m": "100 metara",
  "10m": "10 metara",
  "clipGrid": "Pripoji mrežu na GRG područje",
  "newGRGAreaFromNonStandardTitle": "Novi URL",
  "newGRGPointBySizeTitle": "GRG s točke prema dimenziji",
  "newGRGPointByRefSystemTitle": "GRG s točke prema referentnom sustavu",
  "newGRGPointByTimeTitle": "GRG s točke pomoću vremena i brzine",
  "time": "Vrijeme",
  "rate": "Brzina",
  "hours": "Sati",
  "minutes": "Minute",
  "seconds": "Sekunde",
  "ftPerSec": "Stopa / sekunda",
  "ftPerHour": "Stopa / sat",
  "kmPerSec": "Kilometri / sekunda",
  "kmPerHour": "Kilometri / sat",
  "mPerSec": "Metri / sekunda",
  "mPerHour": "Metri / sat",
  "miPerSec": "Milje / sekunda",
  "miPerHour": "Milje / sat",
  "nMPerSec": "Nautičke milje / sekunda",
  "nMPerHour": "Nautičke milje / sat",
  "settingsTitle": "Postavke",
  "labelSettingsLabel": "Postavke oznake",
  "labelSettingsButtonLabel": "Konfiguriraj postavke oznake",
  "gridSettingsLabel": "Postavke mreže",
  "gridSettingsButtonLabel": "Konfiguriraj postavke mreže",
  "transparency": "Prozirnost",
  "labelStyle": "Stil oznake",
  "font": "Font",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "halo": "Halo",
  "show": "Prikaži",
  "lockSettings": "Vlasnik aplikacije zaključao je postavke",
  "gridSettings": {
    "cellShape": "Oblik ćelije",
    "cellUnits": "Jedinice ćelije",
    "cellOutline": "Postavke obrisa ćelije",
    "cellFill": "Postavke za ispunjenje ćelija",
    "gridReferenceSystem": "Referentni sustav",
    "gridDatum": "Podatak: WGS84",
    "labelStartPosition": "Podrijetlo oznake",
    "labelType": "Vrsta oznake",
    "labelDirection": "Smjer oznake",
    "gridOrigin": "Podrijetlo mreže",
    "default": "Pravokutnik",
    "hexagon": "Šesterokut",
    "miles": "Milje",
    "kilometers": "Kilometri",
    "feet": "Stope",
    "meters": "Metri",
    "yards": "Jardi",
    "nautical-miles": "Nautičke milje",
    "lowerLeft": "Donja lijeva strana",
    "lowerRight": "Donja desna strana",
    "upperLeft": "Gornja lijeva strana",
    "upperRight": "Gornja desna strana",
    "center": "Sredina",
    "alphaNumeric": "Alfa-brojčano",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Brojčano",
    "horizontal": "Vodoravni",
    "vertical": "Uspravno",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Prikaži oznake"
  },
  "publishTitle": "Objavi GRG na portal",
  "publishGRGBtn": "Objavi",
  "GRGLayerName": "Objavljen naziv sloja GRG",
  "invalidGRGLayerName": "Naziv sloja mora sadržavati samo alfanumeričke znakove i podvlake",
  "missingGRGLayerName": "Morate navesti naziv za GRG",
  "publishingFailedLayerExists": "Objavljivanje nije uspjelo: već imate uslugu geoobjekata s nazivom {0}. Odaberite drugi naziv.",
  "checkService": "Provjeri uslugu: {0}",
  "createService": "Stvori uslugu: {0}",
  "unableToCreate": "Nije moguće stvoriti: {0}",
  "addToDefinition": "Dodaj definiciji: {0}",
  "successfullyPublished": "Uspješno objavljen web-sloj{0}Upravljaj web-slojem",
  "userRole": "Nije moguće stvoriti uslugu jer korisnik nema dopuštenja",
  "createGRGBtn": "Stvori GRG",
  "clearGRGBtn": "Očisti",
  "labelFormat": "Format oznake",
  "helpIconTooltip": "Z: Određivanje zone mreže (GZD)\nS: Identifikacija četverokuta mreže od 100.000 metara (GSID)\nX: Istočno (X koordinata)\nY: Sjeverno (Y koordinata)\n\nPrimjeri:\nZSXY je 15SWC8081751205\nZS X, Y je 15SWC 80817,51205",
  "addPointToolTip": "Dodaj podrijetlo GRG-a",
  "cellWidth": "Širina ćelije (x)",
  "cellHeight": "Visina ćelije (y)",
  "invalidNumberMessage": "Unesena vrijednost nije valjana",
  "invalidRangeMessage": "Vrijednost mora biti veća od 0",
  "gridAngleInvalidRangeMessage": "Vrijednost mora biti između -89,9 i 89,9",
  "formatIconTooltip": "Format unosa",
  "coordInputLabel": "Podrijetlo GRG-a (DD)",
  "setCoordFormat": "Postavi niz formata koordinata",
  "prefixNumbers": "Dodajte prefiks „+/-” pozitivnim i negativnim brojevima",
  "cancelBtn": "Odustani",
  "applyBtn": "Primijeni",
  "comfirmInputNotation": "Notacija potvrde unosa",
  "notationsMatch": "bilješke se podudaraju s vašim unosom, potvrdite što biste htjeli upotrijebiti:",
  "numberOfCellsHorizontal": "Br. vodoravnih ćelija",
  "numberOfCellsVertical": "Br. okomitih ćelija",
  "gridAngle": "Rotacija mreže",
  "tooManyCellsErrorMessage": "Pokušavate stvoriti mrežu koja sadrži više od 2000 ćelija. Preporučuje se smanjiti broj ćelija koji se stvara mijenjanjem veličine mreže ili područja mreže.",
  "missingParametersMessage": "<p>U obrascu za stvaranje GRG-a nedostaju parametri ili nisu valjani, osigurajte sljedeće:</p><ul><li>Nacrtano je GRG područje.</li><li>Širina i visina ćelije sadrže valjane vrijednosti.</li></ul>",
  "missingOriginParametersMessage": "<p>U obrascu za stvaranje GRG-a nedostaju parametri ili nisu valjani, osigurajte sljedeće:</p><ul><li>Postavljeno je podrijetlo GRG-a.</li><li>Unosi vremena, brzine i kutova sadrže valjane vrijednosti.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>U obrascu za stvaranje GRG-a nedostaju parametri ili nisu valjani. Osigurajte da unosi širine i visine sadrže valjane vrijednosti.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>U obrascu za stvaranje GRG-a nedostaju parametri ili nisu valjani. Osigurajte da unosi broja vodoravnih i okomitih ćelija sadrže valjane vrijednosti.</p>",
  "drawPointToolTip": "Kliknite da biste dodali točku podrijetla GRG-a",
  "missingLayerNameMessage": "Morate unijeti važeći naziv sloja prije objavljivanja",
  "parseCoordinatesError": "Nije moguće parsirati koordinate. Provjerite unos.",
  "grgPolarRegionError": "Obuhvat GRG-a jest u polarnoj regiji. Ćelije koje spadaju u polarnu regiju neće se stvoriti.",
  "grgPolarOriginError": "Točka podrijetla GRG-a ne može biti unutar polarne regije pri stvaranju GRG pomoću referentnog sustava.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stupnjevi - geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stupnjevi - geografska dužina/širina",
  "DDMLatLongNotation": "Stupnjevi decimalne minute - geografska širina/dužina",
  "DDMLongLatNotation": "Stupnjevi decimalne minute - geografska dužina/širina",
  "DMSLatLongNotation": "Stupnjevi minute sekunde - geografska širina/dužina",
  "DMSLongLatNotation": "Stupnjevi minute sekunde - geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - slovo retka",
  "UTMHemNotation": "UTM - hemisfera (N/S)"
});