define({
  "_widgetLabel": "적합성 모델러",
  "general": {
    "clear": "선택 해제",
    "cancel": "취소",
    "save": "실행",
    "saveAs": "내보내기"
  },
  "saveModel": {
    "save": "내보내기",
    "title": "제목: ",
    "summary": "요약: ",
    "description": "설명: ",
    "tags": "태그: ",
    "folder": "폴더: ",
    "homeFolderPattern": "{username}(홈)",
    "failed": "내보내기에 실패했습니다."
  },
  "util": {
    "colorRamp": {
      "1": "극히 낮음",
      "2": "매우 낮음",
      "3": "낮음",
      "4": "약간 낮음",
      "5": "중간",
      "6": "약간 높음",
      "7": "높음",
      "8": "매우 높음",
      "9": "극히 높음",
      "low": "낮음",
      "high": "높음",
      "tipPattern": "{label} ({value})",
      "flipCaption": "뒤집기(Flip)"
    }
  },
  "wro": {
    "caption": "적합성 모델러",
    "browsePrompt": "가중치 중첩 서비스",
    "selectLayersCaption": "레이어 선택",
    "selectLayers": "레이어",
    "designModelCaption": "디자인 모델",
    "designModel": "디자인 모델",
    "transparency": "투명도",
    "visible": "가시적",
    "total": "전체",
    "unableToLoad": "모델을 불러올 수 없습니다.",
    "projectNotOpen": "프로젝트가 열리지 않았습니다.",
    "readMore": "추가 읽기",
    "validation": {
      "validating": "유효성 검사 중...",
      "invalidItemCaption": "가중치 중첩 서비스 경고",
      "notAnImageService": "이 항목은 이미지 서비스가 아닙니다.",
      "notAWroService": "이 항목은 가중치 중첩 서비스가 아닙니다.",
      "undefinedUrl": "이 항목의 URL이 정의되지 않았습니다.",
      "inaccessible": "서비스에 접근할 수 없습니다.",
      "generalError": "항목을 열 수 없습니다.",
      "missingFieldPattern": "{field}이(가) 필요함(필수)",
      "notAllowRasterFunction": "allowRasterFunction은 true로 설정되어야 함",
      "notNearestResampling": "defaultResamplingMethod는 최인접이어야 함",
      "notIsWeightedOverlayProp": "주요 등록정보 IsWeightedOverlay는 true로 설정되어야 함",
      "invalidLink": "URL이 잘못되었습니다. 선택한 레이어의 사이트를 여는 데 실패했습니다.",
      "unexpectedError": "예상치 못한 상태가 발생했습니다.",
      "rangeMessage": "값은 ${0}에서 ${1} 사이여야 합니다.",
      "rangeMessage100": "값은 0에서 100 사이여야 합니다.",
      "maxLayers": "서비스에는 레이어가 ${0}개까지 허용되므로 새 레이어를 추가하기 전에 레이어를 먼저 제거해야 합니다.",
      "notFound": "가중치 중첩 서비스에서 ${0} 레이어를 찾을 수 없음",
      "wroServiceNotDefined": "모델의 가중치 중첩 서비스가 정의되지 않았습니다.",
      "overlayLayerOutputInvalid": "중첩 레이어 [${0}]의 리맵 범위 [${1}] 결과 값이 누락되었거나 잘못됨",
      "overlayLayerInputInvalid": "중첩 레이어 [${0}]의 리맵 범위 [${1}] 입력 최소/최대 값이 누락되었거나 잘못됨",
      "overlayLayerRangesMissing": "중첩 레이어 [${0}]의 리맵 범위가 누락됨",
      "overlayLayerWeight": "중첩 레이어 가중치를 최대 100개 추가해야 함",
      "overlayLayerRequired": "중첩 레이어가 하나 이상 있어야 함",
      "overlayLayerNotDefined": "중첩 레이어가 정의되지 않음",
      "requiresColormap": "이 래스터 함수의 경우 컬러맵이 있어야 하는데 모델에 올바른 컬러맵 정의가 없음",
      "createModelError": "모델 생성 오류",
      "invalidModel": "모델이 올바르지 않음",
      "imageServiceNotDefined": "이미지 서비스 레이어가 정의되지 않음",
      "imageLayerNotDefined": "이미지 서비스 레이어가 정의되지 않음",
      "histogramNotDefined": "가중치 중첩 히스토그램 함수가 정의되지 않았습니다."
    },
    "colorRampLabel": {
      "Green Yellow Red": "녹색 노란색 빨간색",
      "Red Yellow Green": "빨간색 노란색 녹색",
      "Yellow to Dark Red": "노란색 - 진한 빨간색",
      "Dark Red to Yellow": "진한 빨간색 - 노란색",
      "Light Gray to Dark Gray": "연한 회색 - 진한 회색",
      "Dark Gray to Light Gray": "진한 회색 - 연한 회색",
      "Light Brown to Dark Brown": "연한 갈색 - 진한 갈색",
      "Dark Brown to Light Brown": "진한 갈색 - 연한 갈색",
      "Full Spectrum - Bright Red to Blue": "전체 스펙트럼 - 밝은 빨간색 - 파란색",
      "Full Spectrum - Bright Blue to Red": "전체 스펙트럼 - 밝은 파란색 - 빨간색",
      "Partial Spectrum - Yellow to Blue": "부분 스펙트럼 - 노란색 - 파란색",
      "Partial Spectrum - Blue to Yellow": "부분 스펙트럼 - 파란색 - 노란색",
      "Yellow-Green to Dark Blue": "노란색-녹색 - 진한 파란색",
      "Dark Blue to Yellow-Green": "진한 파란색 - 노란색-녹색",
      "Cold to Hot Diverging": "차가운 색 - 따뜻한 색(발산)",
      "Hot to Cold Diverging": "따뜻한 색 - 차가운 색(발산)",
      "Surface - Low to High": "표면 - 낮음 -> 높음",
      "Surface - High to Low": "표면 - 높음 -> 낮음"
    }
  },
  "tabs": {
    "layers": "레이어",
    "model": "모델",
    "chart": "차트"
  },
  "chart": {
    "prompt": "피처",
    "working": "업데이트 중...",
    "polygonTool": "폴리곤 그리기",
    "freehandPolygonTool": "자유곡선 폴리곤 그리기",
    "selectTool": "레이어에서 선택",
    "panTool": "이동",
    "clearButton": "지우기",
    "noModelLayer": "모델이 없습니다.",
    "noSubjectLayers": "맵에 폴리곤 레이어가 없습니다.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});