define({
  "symbolologyTabLabel": "Настроить условные обозначения",
  "facilitiesDescription": "Слой пунктов обслуживания",
  "demographicsDescription": "Слой демографии",
  "settingsTitle": "Настройки",
  "spillLocationLabel": "Местоположение разлива",
  "spillLocationButtonLabel": "Настроить параметры местоположения разлива",
  "IISettingsLabel": "Исходная зона изоляции",
  "IIButtonLabel": "Настроить параметры исходной изоляции",
  "PASettingsLabel": "Зона защитных действий",
  "PAButtonLabel": "Настроить параметры защитных действий",
  "downwindSettingsLabel": "Подветренная зона",
  "downwindButtonLabel": "Настроить параметры подветренной зоны",
  "fireSettingsLabel": "Зона изоляции пожара",
  "fireButtonLabel": "Настроить параметры изоляции пожара",
  "bleveSettingsLabel": "Зона изоляции BLEVE",
  "bleveButtonLabel": "Настроить параметры BLEVE",
  "transparency": "Прозрачность",
  "outline": "Контур",
  "fill": "Заливка (Цвет применяется, только если задан сплошной)",
  "style": "Стиль",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире – точка",
    "esriSLSDashDotDot": "Тире – точка – точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Длинное тире",
    "esriSLSLongDashDot": "Длинное тире – точка",
    "esriSLSNull": "Пустой",
    "esriSLSShortDash": "Короткое тире",
    "esriSLSShortDashDot": "Короткое тире – точка",
    "esriSLSShortDashDotDot": "Короткое тире – точка – точка",
    "esriSLSShortDot": "Короткая точка",
    "esriSLSSolid": "Сплошная"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Перекрестный",
    "esriSFSDiagonalCross": "Диагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "Горизонтально",
    "esriSFSNull": "Пустой",
    "esriSFSSolid": "Сплошная",
    "esriSFSVertical": "Вертикальная"
  }
});