define({
  "symbolologyTabLabel": "Konfigurišite simbologiju",
  "facilitiesDescription": "Slojevi objekta",
  "demographicsDescription": "Demografski sloj",
  "settingsTitle": "Postavke",
  "spillLocationLabel": "Lokacija prolivanja",
  "spillLocationButtonLabel": "Konfigurišite postavke za lokaciju prolivanja",
  "IISettingsLabel": "Zona početne izolacije",
  "IIButtonLabel": "Konfigurišite postavke za početnu izolaciju",
  "PASettingsLabel": "Zona zaštitne radnje",
  "PAButtonLabel": "Konfigurišite postavke za zaštitnu radnju",
  "downwindSettingsLabel": "Zona niz vetar",
  "downwindButtonLabel": "Konfigurišite postavke za niz vetar",
  "fireSettingsLabel": "Zona za izolaciju požara",
  "fireButtonLabel": "Konfigurišite postavke za izolaciju požara",
  "bleveSettingsLabel": "BLEVE zona za izolaciju",
  "bleveButtonLabel": "Konfigurišite BLEVE postavke",
  "transparency": "Prozirnost",
  "outline": "Kontura",
  "fill": "Popuna (boja se primenjuje samo kada je stil podešen da bude neproziran)",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Crta",
    "esriSLSDashDot": "Crta tačka",
    "esriSLSDashDotDot": "Crta tačka tačka",
    "esriSLSDot": "Tačka",
    "esriSLSLongDash": "Duga crta",
    "esriSLSLongDashDot": "Duga crta tačka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kratka crta",
    "esriSLSShortDashDot": "Kratka crta tačka",
    "esriSLSShortDashDotDot": "Kratka crta tačka tačka",
    "esriSLSShortDot": "Kratka tačka",
    "esriSLSSolid": "Neprozirno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unazad",
    "esriSFSCross": "Krst",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Unapred",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Neprozirno",
    "esriSFSVertical": "Vertikalno"
  }
});