define({
  "_widgetLabel": "Coordinate Conversion",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Degrés décimaux - Latitude/Longitude",
  "DDLongLatNotation": "Degrés décimaux - Longitude/Latitude",
  "DDMLatLongNotation": "Degrés minutes décimales - Latitude/Longitude",
  "DDMLongLatNotation": "Degrés minutes décimales - Longitude/Latitude",
  "DMSLatLongNotation": "Degrés minutes secondes - Latitude/Longitude",
  "DMSLongLatNotation": "Degrés minutes secondes - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Lettre du canal",
  "UTMHemNotation": "UTM - Hémisphère (N/S)",
  "formatInput": "Format d'entrée",
  "copyAll": "Copier tout",
  "copySuccessful": "Copie réussie",
  "copyFailed": "Impossible de copier. Utilisez CTRL+C comme alternative.",
  "parseCoordinatesError": "Impossible d'analyser les coordonnées. Vérifiez votre entrée.",
  "comfirmInputNotation": "Confirmer la notation entrée",
  "latLongWarningMessage": "La coordonnée entrée a été détectée comme étant pourvue d'un préfixe et d'un suffixe pour la valeur de la latitude ou de la longitude ; la coordonnée retournée est basée sur le préfixe.",
  "inputLabel": "Entrée",
  "outputLabel": "Sortie",
  "cancelButtonLabel": "Annuler",
  "applyButtonLabel": "Appliquer",
  "posNegPrefixLabel": "Ajouter le préfixe \"+/-\" aux nombres positifs et négatifs",
  "editCoordinateDialogTitle": "Définir une chaîne de format des coordonnées",
  "rememberDecisionLabel": "Mémoriser ma décision et ne pas me la demander à nouveau.<br/>",
  "coordinateInputLabel": "Entrez des coordonnées ou cliquez sur une carte",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notations trouvées qui correspondent à votre entrée. Confirmez celle que vous souhaitez utiliser :",
  "copyToClipboard": "Copier dans le Presse-papiers",
  "formatOutput": "Format de sortie",
  "addNewNotation": "Ajouter une nouvelle notation",
  "notationAddedMessage": "Nouvelle notation ajoutée",
  "addLabel": "Ajouter",
  "removeCoordinate": "Supprimer la coordonnée",
  "expandOutput": "Développer la sortie",
  "latitudeLabel": "Lat",
  "longitudeLabel": "Lon",
  "quadrantLabel": "Quadrant",
  "keyLabel": "Clé",
  "fifteenDegreeLabel": "15Â° Quad",
  "oneDegreeLabel": "1Â° Quad",
  "eastingLabel": "Abscisse",
  "northingLabel": "Ordonnée",
  "zoneLabel": "Zone",
  "bandLabel": "Bande",
  "gzdLabel": "Indicateur de zone de grille",
  "gridSquareLabel": "Grille carrée",
  "hemisphereLabel": "Hémisphère"
});