define({
  "queries": "Poizvedbe",
  "addNew": "Dodaj novo",
  "newQuery": "Nova poizvedba",
  "queryLayer": "Sloj poizvedbe",
  "setSource": "Nastavi",
  "setDataSource": "Nastavite vir podatkov",
  "name": "Ime",
  "querySource": "Vir podatkov",
  "queryName": "Ime naloge",
  "queryDefinition": "Določitev filtra",
  "resultsSetting": "Nastavitve rezultatov",
  "symbolSetting": "Nastavitve simbolov",
  "resultSettingTip": "Določite kaj in kako prikazati izhodne rezultate.",
  "resultItemTitle": "Naslov vsakega elementa rezultata",
  "resultItemContent": "Prikazani bodo ti atributi polj",
  "fieldsSetTip": "Označite polja, ki jih želite prikazati. Izberite polje, za katerega želite posodobiti vzdevek, vrstni red in obliko.",
  "addField": "Dodaj polje",
  "visibility": "Vidnost",
  "alias": "Vzdevek",
  "specialType": "Posebni tip",
  "actions": "Dejanja",
  "none": "Brez",
  "link": "Povezava",
  "image": "Slika",
  "noField": "Brez polj",
  "operationalLayerTip": "Dodaj rezultat kot operativni sloj",
  "setLayerSymbolTip": "Nastavi simbol za rezultate poizvedb: ",
  "setSelectedSymbolTip": "Nastavi simbol izbranega geoobjekta.",
  "notUseFilter": "Ne uporabi filtra",
  "setSourceTip": "Nastavi vir poizvedb.",
  "setFilterTip": "Pravilno nastavite filter.",
  "ok": "V redu",
  "cancel": "Prekliči",
  "noFilterTip": "Če filter ni določen, bo ta naloga poizvedbe prikazala vse geoobjekte v navedenih virih podatkov.",
  "relationships": "Relacije",
  "addRelationshipLayer": "Dodaj novo relacijo",
  "relatedTo": "V relaciji z",
  "selectOption": "Izberite...",
  "resultItemSorting": "Razvrščanje elementov rezultatov",
  "field": "Polje",
  "sortingOrder": "Vrstni red",
  "configureFieldsTip": "Konfigurirajte polja, po katerih bo razvrščen rezultat poizvedb.",
  "setSortingFields": "Nastavite polja za razvrščanje",
  "ascending": "Naraščajoče",
  "descending": "Padajoče",
  "sortBy": "Razvrsti po",
  "thenBy": "Nato po",
  "addTask": "Dodaj nalogo",
  "noTasksTip": "Nobena poizvedba ni bila konfigurirana. Kliknite »${newQuery}« za dodajanje nove.",
  "infoText": "Informacije",
  "filters": "Filtri",
  "results": "Rezultati",
  "optionsText": "Možnosti",
  "summaryText": "Povzetek",
  "attributeFilter": "Filter atributov",
  "attributeFilterTip": "Določi atributne izraze za uporabo v pripomočku za filtriranje po sloju poizvedb.",
  "defineWhereClause": "Določite KJER stavek poizvedbe",
  "noExpressionDefinedTip": "Izrazi poizvedbe niso določeni. Vrnjeni bodo vsi zapisi",
  "setExpressions": "Nastavi izraze poizvedbe",
  "spatialFilter": "Prostorski filtri",
  "spatialFilterTip": "Izberite, kateri prostorski filtri bodo na razpolago končnim uporabnikom.",
  "defaultOption": "Privzeto",
  "useCurrentExtentTip": "Vrni samo geoobjekte s trenutnega obsega karte",
  "useDrawGraphicTip": "Vrni samo geoobjekte, ki sekajo obliko, narisano na karti",
  "useFeaturesTip": "Vrni samo geoobjekte, ki imajo prostorsko relacijo z geoobjekti drugega sloja",
  "noSpatialLimitTip": "Vrni geoobjekte, ki so znotraj polnega obsega karte",
  "drawingTools": "Izberite orodja za risanje",
  "bufferSettings": "Omogoči možnost obrisa",
  "defaultDistance": "Privzeta razdalja",
  "bufferDistance": "Razdalja obrisa",
  "defaultUnit": "Privzeta enota",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "availableSpatialRelationships": "Izberite pravila prostorske relacije",
  "setSpatialRelationships": "Nastavite prostorsko relacijo",
  "availability": "Razpoložljivost",
  "relationship": "Relacija",
  "label": "Napis",
  "intersect": "seka",
  "contain": "vsebuje",
  "areContainedIn": "so vsebovani v",
  "cross": "križa",
  "envelopeIntersect": "seka prostorski okvir",
  "overlap": "prekriva",
  "areOverlapped": "so prekriti",
  "touch": "se dotika",
  "within": "znotraj",
  "areWithin": "so znotraj",
  "indexIntersect": "indeksni presek",
  "itemTitle": "Naslov elementa",
  "displayFields": "Prikaži polja",
  "sortingFields": "Razvrsti elemente rezultatov",
  "setDisplayFields": "Nastavi polja za prikaz",
  "symbol": "Simbol",
  "setSymbol": "Uporabi simbol po meri",
  "changeSymbolAtRuntime": "Dovoli spreminjanje simbolov med izvajanjem",
  "serviceSymbolTip": "Uporabi simbole, določene s slojem",
  "exportTip": "Dovoli izvoz rezultatov",
  "keepResultsTip": "Ohrani rezultate na karti po zaprtju pripomočka",
  "queryRelatedRecords": "Poizvedba relacijskih zapisov",
  "createLayerForTaskTip": "Določi, kako poizvedba ustvari sloje",
  "oneLayerForTaskTip": "Po vsaki poizvedbi prepiši sloj",
  "multipleLayerForTaskTip": "Ob izvedbi poizvedbe ustvari nov sloj",
  "makeDefault": "Naredi privzeto",
  "icon": "Ikona",
  "newTask": "Novo opravilo",
  "addTaskTip": "Dodajte eno ali več poizvedb in za vsako konfigurirajte parametre.",
  "webMapPopupTip": "Uporabite konfiguracijo pojavnega okna sloja na spletni karti",
  "customPopupTip": "Konfiguriraj vsebino po meri",
  "showResultsSetActions": "Pokaži dejanja za nabor rezultatov",
  "zoomTo": "Približaj na",
  "openAttributeTable": "Poglej v atributni tabeli",
  "content": "Vsebina",
  "displaySQLTip": "Prikaži izraze SQL za končne uporabnike",
  "useLayerDefaultSymbol": "Uporabi privzeti simbol sloja",
  "setCustomIcon": "Nastavite ikono po meri",
  "layerDefaultSymbolTip": "Uporabi privzeti simbol sloja",
  "uploadImage": "Naloži sliko",
  "attributeCriteira": "Kriteriji poizvedbe",
  "specifyFilterAtRuntimeTip": "Uporabniki bodo morali določiti parametre za ta izraz.",
  "value": "VREDNOST",
  "hideLayersTip": "Izklopi sloje rezultatov poizvedb, ko je pripomoček zaprt.",
  "tabLabels": "Napisi zavihkov",
  "tasks": "Opravila",
  "queryCriteira": "Kriteriji poizvedbe",
  "allowCustomQuery": "Dovoli ustvarjanje poizvedbe po meri"
});