define({
  "queries": "Query's",
  "addNew": "Nieuwe toevoegen",
  "newQuery": "Nieuwe query",
  "queryLayer": "Querylaag",
  "setSource": "Instellen",
  "setDataSource": "Gegevensbron instellen",
  "name": "Naam",
  "querySource": "Gegevensbron",
  "queryName": "Naam taak",
  "queryDefinition": "Definitie filter",
  "resultsSetting": "Instelling resultaten",
  "symbolSetting": "Symboolinstelling",
  "resultSettingTip": "Definieer welke uitvoerresultaten u wilt weergeven en hoe.",
  "resultItemTitle": "Titel van elk resultaatitem",
  "resultItemContent": "Deze veldattributen worden weergegeven",
  "fieldsSetTip": "Selecteer de velden die u wilt weergeven. Selecteer een veld om de alias, de volgorde en opmaak ervan bij te werken.",
  "addField": "Veld toevoegen",
  "visibility": "Zichtbaarheid",
  "alias": "Alias",
  "specialType": "Speciaal type",
  "actions": "Acties",
  "none": "Geen",
  "link": "Koppeling",
  "image": "Afbeelding",
  "noField": "Geen veld",
  "operationalLayerTip": "Resultaat als operationele laag toevoegen",
  "setLayerSymbolTip": "Stel het symbool voor queryresultaten in: ",
  "setSelectedSymbolTip": "Stel het symbool van geselecteerde objecten in.",
  "notUseFilter": "Geen filter gebruiken",
  "setSourceTip": "Stel de querybron in.",
  "setFilterTip": "Stel het filter correct in.",
  "ok": "OK",
  "cancel": "Annuleren",
  "noFilterTip": "Zonder filterexpressie zal deze querytaak alle functies in de opgegeven gegevensbron weergeven.",
  "relationships": "Relaties",
  "addRelationshipLayer": "Nieuwe relatie toevoegen",
  "relatedTo": "Met betrekking tot",
  "selectOption": "Selecteren.",
  "resultItemSorting": "Sorteren resultaatitem",
  "field": "Veld",
  "sortingOrder": "Volgorde",
  "configureFieldsTip": "Configureer de velden waarop het queryresultaat wordt gesorteerd.",
  "setSortingFields": "Sorteervelden instellen",
  "ascending": "Oplopend",
  "descending": "Aflopend",
  "sortBy": "Sorteren op",
  "thenBy": "Vervolgens op",
  "addTask": "Taak toevoegen",
  "noTasksTip": "Geen queries geconfigureerd. Klik op \"${newQuery}\" om een nieuwe toe te voegen.",
  "infoText": "Info",
  "filters": "Filters",
  "results": "Resultaten",
  "optionsText": "Opties",
  "summaryText": "Samenvatting",
  "attributeFilter": "Attribuutfilter",
  "attributeFilterTip": "Bepaal attrivuutexpressies voor gebruik in de widget om de querylaag te filteren.",
  "defineWhereClause": "Definieer een WHERE-clausule voor de zoekopdracht.",
  "noExpressionDefinedTip": "Geen expressie gedefinieerd. Alle records worden geretourneerd.",
  "setExpressions": "Expressies instellen",
  "spatialFilter": "Ruimtelijke filters",
  "spatialFilterTip": "Kies welke ruimtelijke filters beschikbaar zijn voor eindgebruikers.",
  "defaultOption": "Standaard",
  "useCurrentExtentTip": "Alleen objecten retourneren binnen het huidige kaartextent",
  "useDrawGraphicTip": "Alleen objecten retourneren die de vorm kruisen die op de kaart getekend is",
  "useFeaturesTip": "Alleen objecten retourneren die een ruimtelijke relatie met objecten in een andere laag hebben",
  "noSpatialLimitTip": "Objecten retourneren binnen de volledige extent van de kaart",
  "drawingTools": "Tekenhulpmiddel kiezen",
  "bufferSettings": "Bufferoptie inschakelen",
  "defaultDistance": "Standaardafstand",
  "bufferDistance": "Bufferafstand",
  "defaultUnit": "Standaardeenheid",
  "miles": "Mijl",
  "kilometers": "Kilometer",
  "feet": "Voet",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Zeemijl",
  "availableSpatialRelationships": "Kies de ruimtelijke relatieregels",
  "setSpatialRelationships": "Ruimtelijke relaties instellen",
  "availability": "Beschikbaarheid",
  "relationship": "Verhouding",
  "label": "Label",
  "intersect": "kruisen",
  "contain": "bevatten",
  "areContainedIn": "zijn omvat in",
  "cross": "kruis",
  "envelopeIntersect": "kruisingenvelop",
  "overlap": "overlappen",
  "areOverlapped": "zijn overlapt",
  "touch": "aanraking",
  "within": "in",
  "areWithin": "bevinden zich in",
  "indexIntersect": "index kruising",
  "itemTitle": "Itemtitel",
  "displayFields": "Weergavevelden",
  "sortingFields": "Resultaatitems sorteren",
  "setDisplayFields": "Weergavevelden instellen",
  "symbol": "Symbool",
  "setSymbol": "Aangepast symbool gebruiken",
  "changeSymbolAtRuntime": "Toestaan om symbolen te wijzigen tijdens de uitvoering",
  "serviceSymbolTip": "Gebruik de symbolen die door de laag zijn gedefinieerd",
  "exportTip": "Resultaten exporteren",
  "keepResultsTip": "Houd resultaten op de kaart nadat de widget gesloten is",
  "queryRelatedRecords": "Gerelateerde records zoeken",
  "createLayerForTaskTip": "Specificeer hoe de opdrachttaak lagen creëert",
  "oneLayerForTaskTip": "Overschrijf de laag als de zoekopdracht wordt uitgevoerd",
  "multipleLayerForTaskTip": "Creëer een nieuwe laag als de zoekopdracht wordt uitgevoerd",
  "makeDefault": "Standaard maken",
  "icon": "Pictogram",
  "newTask": "Nieuwe taak",
  "addTaskTip": "Voeg één of meer zoekopdrachten toe aan de widget en configureer de parameters voor elke zoekopdracht.",
  "webMapPopupTip": "Gebruik de pop-upconfiguratie van de laag in de webmap",
  "customPopupTip": "Aangepaste content configureren",
  "showResultsSetActions": "Acties weergeven voor de resultaten",
  "zoomTo": "Zoomen naar",
  "openAttributeTable": "Bekijken in Attribuuttabel",
  "content": "Content",
  "displaySQLTip": "Toon SQL expressie voor eindgebruikers",
  "useLayerDefaultSymbol": "Gebruik het standaardsymbool van de laag",
  "setCustomIcon": "Aangepast pictogram instellen",
  "layerDefaultSymbolTip": "Gebruik het standaardsymbool van de laag",
  "uploadImage": "Een afbeelding uploaden",
  "attributeCriteira": "Attribuutcriteria",
  "specifyFilterAtRuntimeTip": "Gebruikers moeten parameters opgeven voor deze expressie.",
  "value": "WAARDE",
  "hideLayersTip": "Schakel zoekresultaatlagen uit als de widget wordt gesloten.",
  "tabLabels": "Tabbladlabels",
  "tasks": "Taken",
  "queryCriteira": "Querycriteria",
  "allowCustomQuery": "Toestaan om een aangepaste query te maken"
});