define({
  "serviceUrl": "Configurar url de serviço:",
  "minIntSpacingLabel": "Tamanho Mínimo da Grade",
  "lineOpacityLabel": "Opacidade da Linha",
  "labelOpacityLabel": "Opacidade do Rótulo",
  "centerLabelOpacityLabel": "Opacidade do Rótulo Central",
  "gridZonePlacementLabel": "Posicionamento de Rótulo na Zona da Grade",
  "verticalLineLabels": "Rótulos de Linha Vertical",
  "styleHeaderLabel": "Estilo",
  "indexHeaderLabel": "Componente da Grade",
  "colorHeaderLabel": "Cor",
  "fontSizeHeaderLabel": "Tamanho da Fonte",
  "lineWidthHeaderLabel": "Largura da Linha",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertical",
  "upperLeftLabel": "Superior Esquerdo",
  "upperRightLabel": "Superior Direito",
  "lowerLeftLabel": "Inferior Esquerdo",
  "lowerRightLabel": "Inferior Direito",
  "centerLabel": "Centralizar",
  "errorMessage": "A página de configuração contém erros. Repare antes de salvar.",
  "checkBoxLabel": "Grade de exibição quando o widget está fechado",
  "checkBoxLabelDashboard": "Grade de Visualização",
  "gzd": "Designador de Zona da Grade (GZD)",
  "gsid": "Identificação de Quadrícula da Grade de 100.000 metros (GSID)",
  "grid10k": "Linhas de Grade de 10.000 metros",
  "grid1k": "Linhas de Grade de 1.000 metros",
  "grid100m": "Linhas de Grade de 100 metros",
  "grid10m": "Linhas de Grade de 10 metros",
  "switchBasemap": "Trocar Mapa Base"
});