define({
  "labelBookmarkName": "Lisa praegune vaade järjehoidjasse",
  "labelPlay": "Esita kõik",
  "labelStop": "Lõpeta",
  "labelDelete": "Kustuta",
  "placeholderBookmarkName": "Järjehoidja nimi",
  "errorNameExist": "Järjehoidja on olemas!",
  "errorNameNull": "Vigane järjehoidja nimi!",
  "editTip": "Muuda järjehoidjat",
  "exitEditTip": "Välju muutmisrežiimist",
  "syncTip": "Sünkroniseeri",
  "cardsTips": "Ruudustikuvaade",
  "listTips": "Loendivaade",
  "addBtn": "Lisa",
  "deleteBtn": "Kustuta",
  "changeThumbnailTip": "Vaheta pisipilt",
  "dragReorderTip": "Ümberjärjestamiseks hoidke all ja lohistage",
  "deleteBtnTip": "Kustuta järjehoidja",
  "editBtnTip": "Muuda järjehoidjat",
  "withVisibility": "Kihi nähtavusega",
  "searchBookmark": "Otsi",
  "bookmarksFromConfig": "Eelkonfigureeritud järjehoidjad",
  "bookmarksFromCache": "Kohalikud ajutised järjehoidjad",
  "notice": "Teade",
  "changeNoticeTips": "Muudatused salvestatakse ainult brauseri vahemälus. Muudatuste tegemisel katkestatakse vidina ja selle konfiguratsiooni vaheline sünkroonimine.",
  "syncNoticeTips": "See kustutab kõik muudatused ja taastab konfigureeritud järjehoidjad.",
  "dontShowAgain": "Ära näita enam",
  "saveVisibility": "Salvesta kihi nähtavus",
  "_widgetLabel": "Järjehoidja"
});