define({
  "routeUrl": "Adres URL trasy",
  "locatorUrl": "Adres URL geokodera",
  "geocoderOptions": "Opcje geokodera",
  "autoComplete": "Autouzupełnianie",
  "maximumSuggestions": "Maksymalna liczba sugestii",
  "minCharacters": "Minimalna liczba znaków",
  "searchDelay": "Opóźnienie wyszukiwania",
  "placeholder": "Symbol zastępczy",
  "routeOptions": "Opcje trasy",
  "directionsLanguage": "Język wskazówek",
  "directionsLengthUnits": "Jednostki długości używane we wskazówkach",
  "directionsOutputType": "Typ wynikowych wskazówek",
  "impedanceAttribute": "Atrybut impedancji",
  "kilometers": "Kilometry",
  "miles": "Mile",
  "meters": "Metry",
  "feet": "Stopy",
  "yards": "Jardy",
  "nauticalMiles": "Mile morskie",
  "parametersTip": "Skonfiguruj poprawnie atrybuty!",
  "complete": "Zakończone",
  "completeNoEvents": "Zakończone brakiem zdarzeń",
  "instructionsOnly": "Tylko instrukcje",
  "standard": "Standard",
  "summaryOnly": "Tylko podsumowanie",
  "travelModesUrl": "Adres URL trybów podróżowania",
  "searchPlaceholder": "Znajdź adres lub miejsce",
  "trafficLayerUrl": "Adres URL warstwy ruchu drogowego",
  "presetDestinations": "Przystanki ustawione wstępnie",
  "startPoint": "Punkt początkowy",
  "endPoint": "Punkt końcowy",
  "destinationHolder": "Adres lub współrzędne",
  "optional": "Opcjonalne."
});