define({
  "_widgetLabel": "Koordinat Dönüştürme",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Ondalık Dereceleri - Enlem/Boylam",
  "DDLongLatNotation": "Ondalık Dereceleri  - Boylam/Enlem",
  "DDMLatLongNotation": "Dereceler Ondalık Dakikalar - Enlem/Boylam",
  "DDMLongLatNotation": "Dereceler Ondalık Dakikalar - Boylam/Enlem",
  "DMSLatLongNotation": "Dereceler Ondalık Saniyeler - Enlem/Boylam",
  "DMSLongLatNotation": "Dereceler Ondalık Saniyeler - Boylam/Enlem",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bant Harf",
  "UTMHemNotation": "UTM - Yarıküre (N/S)",
  "formatInput": "Biçim Girdisi",
  "copyAll": "Tümünü Kopyala",
  "copySuccessful": "Kopyalama Başarılı",
  "copyFailed": "Kopyalanamıyor. Alternatif olarak ctrl+c seçeneğini kullanın.",
  "parseCoordinatesError": "Koordinatlar ayrıştırılamıyor. Girdinizi denetleyin.",
  "comfirmInputNotation": "Girdi Notasyonunu Onayla",
  "latLongWarningMessage": "Girdi koordinatında enlem ve boylam değeri için hem ön hem de son ek olduğu algılandı, döndürülen koordinat ön eke göredir.",
  "inputLabel": "Girdi",
  "outputLabel": "Çıktı",
  "cancelButtonLabel": "İptal Et",
  "applyButtonLabel": "Uygula",
  "posNegPrefixLabel": "Artı ve eksi sayıların önüne \"+/-\" işareti ekleyin",
  "editCoordinateDialogTitle": "Koordinat Biçimi Dizesini Ayarla",
  "rememberDecisionLabel": "Tercihimi anımsa ve bir daha sorma.<br/>",
  "coordinateInputLabel": "Koordinatları girin veya haritaya tıklayın",
  "zoomLabel": "Yakınlaştır",
  "multipleNotationLabel": "notasyon bulundu, tümü girdinizle eşleşiyor. Hangisini kullanmak istediğinizi belirtin:",
  "copyToClipboard": "Panoya kopyala",
  "formatOutput": "Biçim çıktısı",
  "addNewNotation": "Yeni Notasyon Ekle",
  "notationAddedMessage": "Yeni Gösterim Eklendi",
  "addLabel": "Ekle",
  "removeCoordinate": "Koordinatı Kaldır",
  "expandOutput": "Çıktıyı Genişlet",
  "latitudeLabel": "Enlem",
  "longitudeLabel": "Boylam",
  "quadrantLabel": "Dörtlük",
  "keyLabel": "Anahtar",
  "fifteenDegreeLabel": "15Â° Dörtlü",
  "oneDegreeLabel": "1Â° Dörtlü",
  "eastingLabel": "Doğuya Yöneltme",
  "northingLabel": "Kuzeye Yöneltme",
  "zoneLabel": "Bölge",
  "bandLabel": "Bant",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Grid kare",
  "hemisphereLabel": "Yarıküre"
});