define({
  "_widgetLabel": "Spørring",
  "executeQueryTip": "Klikk på ett av disse oppgaveelementene for å utføre spørringen.",
  "invalidConfig": "Ugyldig konfigurasjon. Bruk innstillingssiden for spørringer til å hente riktig konfigurasjon.",
  "queryParams": "Alternativer",
  "parameters": "ALTERNATIVER",
  "queries": "SPØRRINGER",
  "apply": "Bruk",
  "queryResults": "Resultater",
  "clear": "Fjern",
  "noResults": "Fant ingen geoobjekter.",
  "queryError": "Spørringen mislyktes.",
  "numberFound": "Antall geoobjekter som ble funnet:",
  "mapExtentTip": "Begrens resultatene til det gjeldende kartområdet.",
  "noValue": "Ingen verdi",
  "and": "og",
  "stringOperatorIs": "er",
  "stringOperatorIsNot": "er ikke",
  "stringOperatorStartsWith": "begynner på",
  "stringOperatorEndsWith": "slutter på",
  "stringOperatorContains": "inneholder",
  "stringOperatorDoesNotContain": "inneholder ikke",
  "stringOperatorIsBlank": "er tomt",
  "stringOperatorIsNotBlank": "er ikke tomt",
  "dateOperatorIsOn": "er den",
  "dateOperatorIsNotOn": "er ikke den",
  "dateOperatorIsBefore": "er før",
  "dateOperatorIsAfter": "er etter",
  "dateOperatorDays": "dagene",
  "dateOperatorWeeks": "ukene",
  "dateOperatorMonths": "månedene",
  "dateOperatorInTheLast": "i de/den siste",
  "dateOperatorNotInTheLast": "ikke i de/den siste",
  "dateOperatorIsBetween": "er mellom",
  "dateOperatorIsNotBetween": "er ikke mellom",
  "dateOperatorIsBlank": "er tomt",
  "dateOperatorIsNotBlank": "er ikke tomt",
  "numberOperatorIs": "er",
  "numberOperatorIsNot": "er ikke",
  "numberOperatorIsAtLeast": "er minst",
  "numberOperatorIsLessThan": "er mindre enn",
  "numberOperatorIsAtMost": "er maksimalt",
  "numberOperatorIsGreaterThan": "er større enn",
  "numberOperatorIsBetween": "er mellom",
  "numberOperatorIsNotBetween": "er ikke mellom",
  "numberOperatorIsBlank": "er tomt",
  "numberOperatorIsNotBlank": "er ikke tomt",
  "operationalLayerTip": "Legg til resultat som operativt kartlag",
  "queryResult": "Spørringsresultat",
  "specifyParamsTip": "Angi parametere for denne oppgaven",
  "useSpatialFilter": "Bruk geografisk filter til å begrense geoobjekter",
  "useCurrentMapExtent": "Bare geoobjekter som krysser det gjeldende kartområdet",
  "drawGraphicOnMap": "Bare geoobjekter som krysser det brukerdefinerte området",
  "specifySpatialFilterMsg": "Angi et romlig filter for denne oppgaven.",
  "clearResults": "Fjern resultater",
  "operationalTip": "Når dette alternativet er merket av, beholdes resultatene på kartet frem til det klikkes på knappen ${clearResults}.",
  "noneQueryTip": "Ingen spørringsoppgave er konfigurert for denne widgeten.",
  "noPermissionsMsg": "Du har ikke tillatelse til å bruke denne tjenesten.",
  "attributesFromRelationship": "Attributter fra relatert tabell",
  "tasks": "Oppgaver",
  "applySpatialFilterToLimitResults": "Bruk et romlig filter til å begrense resultatene",
  "useCurrentExtentTip": "Returner kun geoobjekter innenfor gjeldende kartutstrekning",
  "useDrawGraphicTip": "Returner kun geoobjekter som krysser formen som er tegnet på kartet",
  "useFeaturesTip": "Returner kun geoobjekter som har en romlig relasjon med geoobjekter i et annet lag",
  "noSpatialLimitTip": "Returner geoobjekter innenfor kartets fulle utstrekning",
  "applySearchDistance": "Bruk en søkeavstand",
  "spatialRelationship": "Romlig relasjon",
  "relatedLayer": "Relatert lag",
  "bufferDistance": "Bufferavstand",
  "miles": "Miles",
  "kilometers": "kilometer",
  "feet": "fot",
  "meters": "meter",
  "yards": "Yards",
  "nauticalMiles": "Nautiske mil",
  "back": "Tilbake",
  "execute": "Utfør",
  "zoomTo": "Zoom til",
  "openAttributeTable": "Vis i attributtabell",
  "noResult": "Ingen resultater.",
  "noTask": "Ingen oppgave.",
  "removeThisResult": "Fjern dette resultatet",
  "attributeCriteira": "Attributtvilkår",
  "spatialFilter": "Romlig filter",
  "value": "VERDI",
  "noAttributeSpatialFilterTip": "Det er ikke definert et filter. Alle poster blir returnert.",
  "showAllRelatedRecords": "Vis alle relaterte poster",
  "changeSymbol": "Endre symbol",
  "queryCriteira": "Spørringskriterier",
  "customQuery": "Egendefinert spørring",
  "layer": "Lag",
  "createCustomQuery": "Opprett egendefinert spørring."
});