define({
  "_widgetLabel": "Distância e Direção",
  "tabLineTitle": "Linha",
  "tabCircleTitle": "Círculo",
  "tabEllipseTitle": "Elipse",
  "tabRingsTitle": "Anéis",
  "multipleNotationsMessage": " notações que correspondem à sua entrada. Por favor, confirme aqueles que pretende utilizar:",
  "invalidCoordinateMessage": "Coordenada Inválida",
  "confirmInputNotationMessage": "Confirmar Notação de Entrada",
  "prefixSuffixMessage": "A coordenada introduzida foi detetada como tendo tanto um prefixo como um sufixo para o valor de latitude ou longitude, a coordenada devolvida baseia-se no prefixo.",
  "rememberDecisionMessage": "Lembrar a minha decisão e não voltar a perguntar.<br/>",
  "majorAxisTooltipMessage": "Clicar no comprimento do eixo principal",
  "minorAxisTooltipMessage": "Mover o rato para trás para posição inicial para definir o eixo secundário & concluir desenho de elipse",
  "clickToFinishLineMessage": "Clicar para concluir desenho de linha",
  "doubleClickEllipseMesage": "Duplo clique para concluir desenho de anéis de intervalo",
  "invalidCoordinateTypeMessage": "Não foi possível determinar o tipo de coordenadas de entrada. Por favor, verifique a entrada.",
  "noCenterPointSetMessage": "Não foi definido um ponto central. Por favor, verifique a entrada.",
  "ellipseMajorAxis": "Eixo Principal",
  "ellipseMinorAxis": "Eixo Secundário",
  "degreesRangeMessage": "O valor tem de encontrar-se entre 0 e 360.",
  "millsRangeMessage": "O valor tem de encontrar-se entre 0 e 6400.",
  "lengthLabel": "Comprimento",
  "angleLabel": "Ângulo",
  "startPointLabel": "Ponto Inicial",
  "endPointLabel": "Ponto de Chegada",
  "centerPointLabel": "Ponto Central",
  "distanceTableErrorMessage": "A tabela de distância encontra-se vazia. Por favor, introduza algumas distâncias.",
  "setCoordFormatStringMessage": "Definir String de Formatação de Coordenadas",
  "prefixMessage": "Adicionar o prefixo ‘+/-’ a números positivos e negativos",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais  - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Decimais Minutos - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Decimais Minutos - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/ Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra de Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)",
  "circleTitle": "Criar Círculo A Partir De:",
  "radiusLabel": "Raio",
  "diameterLabel": "Diâmetro",
  "startPointPlaceHolderLabel": "Introduzir Coordenadas",
  "formatInputLabel": "Introdução de Formato",
  "drawCircleLabel": "Desenhar Círculo",
  "drawLineLabel": "Desenhar Linha",
  "createCircleInteractivelyLabel": "Criar Círculo Interativamente",
  "rangeErrorMessage": "Raio ou diâmetro inválido",
  "numericInvalidMessage": "Por favor, introduza um valor numérico",
  "timeLabel": "Tempo",
  "invalidTimeMessage": "Valor de hora inválido",
  "hoursLabel": "Horas",
  "minutesLabel": "Minutos",
  "secondsLabel": "Segundos",
  "rateLabel": "Taxa",
  "invalidDistanceMessage": "Valor de distância inválido",
  "feetSecondsLabel": "Pés / segundo",
  "feetHourLabel": "Pés / hora",
  "kmSecondLabel": "Quilómetros / segundo",
  "kmHourLabel": "Quilómetro / hora",
  "metersSecondLabel": "Metros / segundo",
  "metersHourLabel": "Metros / hora",
  "milesSecondLabel": "Milhas / segundo",
  "milesHourLabel": "Milhas / hora",
  "nauticalMilesSecondLabel": "Milhas Náuticas / segundo",
  "nauticalMilesHourLabel": "Milhas Náuticas / hora",
  "clearGraphicsLabel": "Limpar Gráficos",
  "ellipseTypeLabel": "Tipo de Elipse",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Cheio",
  "drawEllipseLabel": "Desenhar Elipse",
  "createEllipseInteractively": "Criar Elipse Interativamente",
  "axisLabel": "Eixo",
  "majorRadiusLabel": "Major (Raio)",
  "axisErrorMessage": "O valor tem de ser maior do que 0",
  "minorRadiusLabel": "Minor (Raio)",
  "orientationLabel": "Orientação",
  "orientationErrorMessage": "O valor tem de encontrar-se entre 0 e 360.",
  "warningMessage": "Aviso: Os gráficos gerados utilizando a ferramenta elipse não são geodésicos",
  "fromLabel": "A partir de",
  "distanceBearingLabel": "Distância e Suporte",
  "pointsLabel": "Pontos",
  "createLineInteractively": "Criar Linha Interativamente",
  "lineLengthErrorMessage": "Comprimento de Linha inválido",
  "degreesLabel": "Degress",
  "milsLabel": "Mils",
  "lineTypeLabel": "Tipo",
  "interactiveLabel": "Interativo",
  "fixedLabel": "Corrigido",
  "originLabel": "Origem",
  "cumulativeLabel": "Cumulativo",
  "numberOfRingsLabel": "Número de Anéis",
  "ringsErrorMessage": "Número de anéis inválido",
  "distanceBetweenRingsLabel": "Distância Entre Anéis",
  "ringsDecimalErrorMessage": "Introduzir um valor numérico com duas casas decimais",
  "distanceUnitsLabel": "Unidades de Distância",
  "distancesLabel": "Distâncias",
  "numberOfRadialsLabel": "Número de Radiais",
  "upLabel": "Para Cima",
  "downLabel": "Para Baixo",
  "deleteLabel": "Excluir",
  "radialsErrorMessage": "Número de radiais inválido. O número máximo permitido é 360",
  "addPointLabel": "Adicionar Ponto",
  "valueLabel": "Valor",
  "valueText": "Introduzir Valor",
  "actionLabel": "Acção"
});