define({
  "_widgetLabel": "การแปลงระบบพิกัด",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "องศาทศนิยม - ละติจูด / ลองจิจูด",
  "DDLongLatNotation": "องศาทศนิยม - ละติจูด / ลองจิจูด",
  "DDMLatLongNotation": "องศา ทศนิยม นาที – ละติจูด / ลองจิจูด",
  "DDMLongLatNotation": "องศา ทศนิยม นาที – ละติจูด / ลองจิจูด",
  "DMSLatLongNotation": "องศา ลิปดา ฟิลิปดา - ละติจูด / ลองจิจูด",
  "DMSLongLatNotation": "องศา ลิปดา ฟิลิปดา - ละติจูด / ลองจิจูด",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisphere (N/S)",
  "formatInput": "รูปแบบข้อมูลนำเข้า",
  "copyAll": "คัดลอกทั้งหมด",
  "copySuccessful": "การคัดลอกเสร็จสมบูรณ์",
  "copyFailed": "ไม่สามารถคัดลอก โปรดใช้ ctrl + c เป็นทางเลือก",
  "parseCoordinatesError": "ไม่สามารถแยกวิเคราะห์พิกัดได้ โปรดตรวจสอบข้อมูลนำเข้าของคุณ",
  "comfirmInputNotation": "ยืนยันการป้อนข้อมูล",
  "latLongWarningMessage": "ค่าพิกัดนำเข้าถูกตรวจพบว่ามีทั้งคำนำหน้าและคำต่อท้ายสำหรับค่าละติจูดหรือลองจิจูด ค่าพิกัดที่ส่งคืนจะขึ้นอยู่กับคำนำหน้า",
  "inputLabel": "ข้อมูลนำเข้า",
  "outputLabel": "ผลลัพธ์",
  "cancelButtonLabel": "ยกเลิก",
  "applyButtonLabel": "ใช้",
  "posNegPrefixLabel": "เพิ่มคำนำหน้า \"+/-\" เป็นตัวเลขบวกและลบ",
  "editCoordinateDialogTitle": "ตั้งค่าระบบพิกัดรูปแบบสตริง",
  "rememberDecisionLabel": "โปรดจำการตัดสินใจของฉันและไม่ต้องถามอีก <br/>",
  "coordinateInputLabel": "กรอกค่าพิกัดหรือคลิกบนแผนที่",
  "zoomLabel": "ขยาย",
  "multipleNotationLabel": "พบข้อความที่ตรงกับข้อมูลนำเข้าของคุณ โปรดยืนยันว่าคุณต้องการใช้",
  "copyToClipboard": "คัดลอกไปยังคลิปบอร์ด",
  "formatOutput": "รูปแบบผลลัพท์",
  "addNewNotation": "เพิ่มข้อความใหม่",
  "notationAddedMessage": "เพิ่มโน้ตใหม่แล้ว",
  "addLabel": "เพิ่ม",
  "removeCoordinate": "ลบค่าพิกัด",
  "expandOutput": "สำรวจผลลัพท์",
  "latitudeLabel": "ละติจูด",
  "longitudeLabel": "ลองจิจูด",
  "quadrantLabel": "ค่าควอแดรนท์",
  "keyLabel": "สำคัญ",
  "fifteenDegreeLabel": "15Â° ควอด",
  "oneDegreeLabel": "1Â° ควอด",
  "eastingLabel": "ทิศตะวันออก",
  "northingLabel": "ทิศเหนือ",
  "zoneLabel": "โซน",
  "bandLabel": "คณะ",
  "gzdLabel": "GZD",
  "gridSquareLabel": "กริด",
  "hemisphereLabel": "ซีกโลก:"
});