define({
  "gridTabLabel": "Πλέγμα",
  "labelTabLabel": "Ετικέτες",
  "referenceSystemTabLabel": "Σύστημα αναφοράς",
  "gridTabDescription": "Καθορίστε την εμφάνιση και τη συμπεριφορά των κελιών του πλέγματος.",
  "cellOutlineColor": "Χρώμα περιγράμματος κελιών",
  "cellFillColor": "Χρώμα γεμίσματος κελιών",
  "transparency": "Διαφάνεια",
  "cellShapeDropDown": "Σχήμα κελιών",
  "default": "Ορθογώνιο",
  "hexagon": "Εξάγωνο",
  "cellUnitsDropDown": "Μονάδες κελιών",
  "miles": "Μίλια",
  "kilometers": "Χιλιόμετρα",
  "feet": "Πόδια",
  "meters": "Μέτρα",
  "yards": "Γιάρδες",
  "nautical-miles": "Ναυτικά μίλια",
  "gridOriginDropDown": "Προέλευση πλέγματος",
  "lowerLeft": "Κάτω αριστερά",
  "lowerRight": "Κάτω δεξιά",
  "upperLeft": "Επάνω αριστερά",
  "upperRight": "Επάνω δεξιά",
  "center": "Κέντρο",
  "labelTabDescription": "Καθορίστε την εμφάνιση και τη συμπεριφορά των ετικετών του πλέγματος.",
  "labelSettings": "Στιλ ετικετών",
  "font": "Γραμματοσειρά",
  "textSize": "Μέγεθος κειμένου",
  "textColor": "Χρώμα κειμένου",
  "halo": "Μάσκα σκίασης",
  "show": "Εμφάνιση",
  "labelTypeDropDown": "Τύπος ετικετών",
  "alphaNumeric": "Αλφαριθμική τιμή",
  "alphaAlpha": "Αλφαβητική τιμή",
  "numeric": "Αριθμητική",
  "labelDirectionDropDown": "Κατεύθυνση ετικετών",
  "horizontal": "Οριζόντια",
  "vertical": "Κατακόρυφα",
  "labelOriginDropDown": "Προέλευση ετικετών",
  "referenceSystemlTabDescription": "Καθορίστε το προεπιλεγμένο σύστημα αναφοράς.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Ρυθμίσεις κλειδώματος - Δεν θα επιτρέπουν στον χρήστη να αλλάξει οποιαδήποτε από τις διαμορφωμένες ρυθμίσεις εντός του widget."
});