define({
	root: ({
		chartTasks: "Chart tasks",
		addNew: "Add new",
		addNewTip: "Add a new chart task",
		name: "Name",
		set: "Set",
		setDataSource: "Set data source",
		generalSettingsTip: "Set data source, title and description for charts.",
		chartModeSettingTip: "Select a way to analyze and display data as charts.",
		detailsSettingTip: "Set chart appearance by specifying its types and color, and what values to be charted:",
		symbolSettingTip: "Set the map display for charted data.",
		addFilterTip: "Add filter to this data",
		dataSource: "Data Source",
		noResults: "No feature found.",
		chartTitle: "Chart title",
		description: "Description",
		chartingMode: "Chart display",
		featureOption: "Display values feature by feature",
		categoryOption: "Display values by category",
		countOption: "Display feature counts by category",
		fieldOption: "Display attribute values as charts",
		category: "Category",
		axisLabel: "Category label",
		categoryField: "Category field",
		operation: "Operation",
		originalOption: "Use original values",
		sumOption: "Sum",
		averageOption: "Average",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Value fields",
		moveUp: "Move up",
		moveDown: "Move down",
		sortOrder: "Sort charts order by category labels",
		ascending: "Ascending",
		descending: "Descending",
		chartType: "Chart type",
		column: "Column chart",
		bar: "Bar chart",
		line: "Line chart",
		pie: "Pie chart",
		chartColor: "Chart color",
		showDataLabels: "Show data labels",
		setSymbol: "Selection symbol",
		setHighLightColor: "Highlight color",
		settings: "Settings",
		mapInterationOptions: "Map interaction options",
		preview: "Preview",
		ok: "OK",
		cancel: "Cancel",
		close: "Close",
		setFilterTip: "Please set filter correctly. ",
		setChartTitleTip: "Please set chart title.",
		setChartTypeTip: "Please select one chart type at least.",
		setDataFieldTip: "Please select one value field at least.",
		setOutputFieldTip: "Please set output fields.",
		count: "Count",
		label: "Label",
		horizontalAxis: "Horizontal axis",
		verticalAxis: "Vertical axis",
		dataLabels: "Data labels",
		color: "Color",
		colorful: "Colorful",
		monochromatic: "Monochromatic",
    noTaskTip: "Click Add new to add a chart task",
    info: "Info",
    charts: "Charts",
    options: "Options",
    taskName: "Task name",
    summary: "Summary",
    resultDescription: "Result description",
    spatialFilterTip: "Choose the spatial filter(s) used in the widget to limit results.",
    defaultOption: "Default",
    useCurrentExtentTip: "Partially or completely within current map extent",
    useDrawGraphicTip: "Partially or completely within the shape drawn on the map",
    useFeaturesTip: "Based on their locations relative to features in another layer",
    noSpatialLimitTip: "Do not spatially limit results",
    drawingTools: "Drawing tools",
    bufferSettings: "Buffer settings",
    defaultDistance: "Default distance",
    bufferDistance: "Buffer distance",
    defaultUnit: "Default unit",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical miles",
    availableSpatialRelationships: "Available spatial relationships",
    setSpatialRelationships: "Set spatial relationships",
    availability: "Availability",
    relationship: "Relationship",
    actions: "Actions",
    intersect: "intersect",
    contain: "contain",
    areContainedIn: "are contained in",
    cross: "cross",
    envelopeIntersect: "envelope intersect",
    overlap: "overlap",
    areOverlapped: "are overlapped",
    touche: "touche",
    within: "within",
    areWithin: "are within",
    indexIntersect: "index intersect"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
