define({
  "labelBookmarkName": "Đánh dấu tầm nhìn hiện tại",
  "labelPlay": "Phát tất cả",
  "labelStop": "Dừng",
  "labelDelete": "Xóa",
  "placeholderBookmarkName": "Tên đánh dấu",
  "errorNameExist": "Đánh dấu đã tồn tại!",
  "errorNameNull": "Tên đánh dấu không hợp lệ!",
  "editTip": "Chỉnh sửa đánh dấu",
  "exitEditTip": "Thoát khỏi chế độ chỉnh sửa",
  "syncTip": "Đồng bộ hóa",
  "cardsTips": "Chế độ xem dạng lưới",
  "listTips": "Chế độ xem dạng danh sách",
  "addBtn": "Thêm",
  "deleteBtn": "Xóa",
  "changeThumbnailTip": "Thay đổi hình thu nhỏ",
  "dragReorderTip": "Giữ và kéo thả để sắp xếp lại",
  "deleteBtnTip": "Xóa đánh dấu",
  "editBtnTip": "Chỉnh sửa đánh dấu",
  "withVisibility": "Với khả năng hiển thị lớp",
  "searchBookmark": "Tìm kiếm",
  "bookmarksFromConfig": "Các đánh dấu đã được cấu hình",
  "bookmarksFromCache": "Các đánh dấu cục bộ tạm thời",
  "notice": "Lưu ý",
  "changeNoticeTips": "Những thay đổi sẽ chỉ được lưu vào trong bộ nhớ cache trình duyệt của bạn. Việc đồng bộ hóa giữa tiện ích và cấu hình của nó sẽ bị ngắt kết nối khi bạn bắt đầu thực hiện chỉnh sửa.",
  "syncNoticeTips": "Điều này sẽ xóa mọi chỉnh sửa của bạn và khôi phục lại đánh dấu đã được cấu hình.",
  "dontShowAgain": "Không hiển thị lại",
  "saveVisibility": "Lưu khả năng hiển thị lớp",
  "_widgetLabel": "Đánh dấu"
});