define({
  "_widgetLabel": "Carregar",
  "streamControls": "Cotroles de reprodução",
  "streamFilter": "Filtro",
  "startStreaming": "Iniciar reprodução",
  "stopStreaming": "Parar reprodução",
  "streamLayers": "Camadas de reprodução",
  "startStopStream": "Habilitar opção Parar reprodução ou Iniciar reprodução",
  "clearStream": "Habilitar opção Apagar observações anteriores",
  "attributeFilter": "Habilitar filtro de atributo",
  "spatialFilter": "Habilitar filtro espacial",
  "configFilter": "Configurar filtro do atributo de reprodução",
  "drawPrevious": "Habilitar opção Desenhar observações anteriores",
  "addNew": "Adicionar filtro",
  "setFilterName": "Configurar nome de filtro",
  "filterNameExists": "O nome do filtro existe na tabela!",
  "invalidFilterName": "O nome deve ser uma palavra contendo a-z, A-Z, 0-9 ou _.",
  "noFilterTip": "Nenhum filtro configurado",
  "addFilterFailed": "Falha ao adicionar filtro",
  "filterName": "Nome de filtro",
  "limitMapExtent": "Limitar observações na área do mapa atual",
  "limitDrawExtent": "Limitar observações na área definida pelo usuário",
  "newFilter": "Novo filtro",
  "filterReadOnly": "O filtro herdado do mapa da web é somente para leitura."
});