define({
  "tabs_section_Label": "Cilnes",
  "addTab": "Pievienot cilni",
  "layerName": "Slānis",
  "layerType": "Analīzes veids",
  "layerLabel": "Nosaukums",
  "actions": "Darbības",
  "closest": "Tuvākais elements",
  "proximity": "Tuvums",
  "summary": "Kopsavilkums",
  "select_lbl": "-- Atlasīt --",
  "general_setting_Label": "Vispārīgie iestatījumi",
  "units_text_lbl": "Attāluma mērvienības",
  "maximum_distance_lbl": "Tuvākā elementa maksimālais attālums",
  "buffer_text_lbl": "Buferzonas nosaukums",
  "buffer_lbl": "Buferzonas attālums",
  "buffer_max_lbl": "Maksimālais buferzonas attālums",
  "buffer_min_lbl": "Minimālais buferzonas attālums",
  "buffer_default_lbl": "Noklusējuma buferzonas attālums",
  "not_less_than_max": "Attālumam ir jābūt mazākam par maksimālo buferzonas attālumu",
  "not_between": "Attālumam ir jābūt starp minimālo un maksimālo buferzonas attālumu",
  "not_more_than_min": "Attālumam ir jābūt lielākam par minimālo buferzonas attālumu",
  "not_valid_number": "Jābūt derīgam skaitlim",
  "invalid_value": "${type} vērtība ir nederīga",
  "routing_checkBox": "Aktivizēt maršrutēšanu",
  "weather_Label": "Laikapstākļu iestatījumi",
  "weather_checkBox": "Aktivizēt laikapstākļus",
  "weather_map_layers": "Atlasīt laikapstākļu slāņus...",
  "selected_map_layers": " (atlasīti laikapstākļu slāņi)",
  "instruction_weather": "Skatiet laikapstākļu informāciju panelī.",
  "instruction_weather_layers": "Skatiet papildu laikapstākļu slāņus.",
  "instruction_weather_metric": "Skatiet standarta/metriskās vērtības.",
  "selectLayers": "Atlasīt laikapstākļu slāņus",
  "weather_removed_message": "Laikapstākļu opcijas šim logrīkam vairs nav pieejamas.",
  "currentlySelectedLayer": "Izvēlēties no kartes slāņiem",
  "missingTabLabel": "Vismaz vienai cilnei trūkst nosaukuma",
  "missingLayerInWebMap": "Nav atrasti darbības slāņi.",
  "selectFields": "Atlasīt laukus",
  "addField": "Pievienot lauku",
  "sum": "Summa",
  "min": "Minimums",
  "max": "Maksimums",
  "avg": "Vidējais",
  "count": "SKAITS",
  "area": "APGABALS",
  "length": "GARUMS",
  "count_checkBox": "Rādīt elementu skaitu",
  "area_checkBox": "Rādīt laukuma summu",
  "length_checkBox": "Rādīt garuma summu",
  "max_records": "Sasniegts maksimālais skaits",
  "save_label": "Saglabāšanas opcijas",
  "save_checkbox": "Aktivizēt saglabāšanu",
  "report_label": "Pārskatu opcijas",
  "report_checkbox": "Aktivizēt pārskatu",
  "csv_label": "CSV opcijas",
  "csv_checkbox": "Eksportēt visus laukus",
  "display_label": "Parādīšanas opcijas",
  "display_checkbox": "Parādīt kopsavilkuma elementus",
  "snapshot_label": "Momentuzņēmumu opcijas",
  "snapshot_checkbox": "Aktivizēt momentuzņēmumu",
  "must_select_template": "Lūdzu, sadaļā Saglabāšanas opcijas izvēlieties vienu no rediģēšanas veidnēm.",
  "count_label": "Skaita nosaukums",
  "area_label": "Laukuma nosaukums",
  "length_label": "Garuma apzīmējuma nosaukums",
  "invalid_string_width": "Vērtība ir pārāk gara. ",
  "layer_type_not_supported": "Slāņa tips netiek atbalstīts",
  "groupedSummary": "Grupētie rezultāti",
  "groupByField": "Grupēt pēc lauka",
  "labelType": "Pievienot kartes tekstu",
  "prefix": "Kā prefikss",
  "suffix": "Kā sufikss",
  "need_group_field": "Izmantojiet darbību Rediģēt, lai definētu grupu pēc lauka.",
  "fieldTitle": "Lauks",
  "typeTitle": "Veids",
  "actionsTitle": "Darbības",
  "save_point_checkbox": "Saglabāt punktus",
  "save_line_checkbox": "Saglabāt līnijas",
  "save_poly_checkbox": "Saglabāt laukumus",
  "no_valid_popup_fields": "Uznirstošajā logā nav derīgu lauku. Izmantojiet darbību Rediģēt, lai definētu lauku.",
  "no_valid_fields": "Nav derīgu lauku. Izmantojiet darbību Rediģēt, lai definētu parādīšanas opcijas.",
  "incident_label": "Cilnes nosaukums",
  "locate_incident_label": "Interešu apgabala nosaukums",
  "incident": "Negadījums",
  "locate_incident": "Atrast negadījumu",
  "buffer_value": "Buferzonas attālums",
  "tab_options": "Analīze",
  "export_options": "Izvade",
  "instruction_save": "Saglabāt šo vietu elementu servisam.",
  "instruction_snapshot": "Izveidojiet tīmekļa karti, kuras pamatā ir šis novietojums.",
  "instruction_report": "Izveidojiet izdrukātu pārskatu par šo novietojumu.",
  "instruction_all_fields": "Eksportējiet visus laukus ar CSV lejupielādi.",
  "data_label": "Datu izvades iestatījumi",
  "layer_error": "Trūkst slāņa, vai tas ir nederīgs.",
  "visibility_checkBox": "Deaktivizēt slāņa redzamības pārvaldību",
  "downloadTab": {
    "reportLegend": "Pārskata iestatījumi",
    "textColorLabel": "Izvēlēties krāsu kolonnu virsrakstiem",
    "setButtonLabel": "Iestatīt",
    "printGPServiceLabel": "Drukas servisa URL",
    "logoLabel": "Logotips",
    "logoChooserHint": "Noklikšķiniet uz attēla, lai mainītu attēlu",
    "footnoteLabel": "Vēre"
  }
});