define({
  "layerSelect": "Pilih Layer Gambar",
  "displayMeasureResultInPopup": "Tampilkan Hasil Pengukuran dalam Jendela Sembul",
  "angularUnitSelect": "Unit Bersudut Default",
  "linearUnitSelect": "Unit Linear Default",
  "areaUnitSelect": "Unit Area Default",
  "displayOperationSelect": "Pilih Operasi Pengukuran",
  "errorSectionMessage": "Tidak ada dari layer yang mendukung kemampuan pengukuran.",
  "unitLabel": {
    "esriInches": "Inci",
    "esriFeet": "Kaki",
    "esriYards": "Yard",
    "esriMiles": "Mil",
    "esriNauticalMiles": "Mil Laut",
    "esriMillimeters": "Milimeter",
    "esriCentimeters": "Sentimeter",
    "esriDecimeters": "Desimeter",
    "esriMeters": "Meter",
    "esriKilometers": "Kilometer",
    "esriDURadians": "Radian",
    "esriDUDecimalDegrees": "Derajat",
    "esriSquareInches": "Inci Persegi",
    "esriSquareFeet": "Kaki Persegi",
    "esriSquareYards": "Yard Persegi",
    "esriAcres": "Acre",
    "esriSquareMiles": "Mil Persegi",
    "esriSquareMillimeters": "Milimeter Persegi",
    "esriSquareCentimeters": "Sentimeter Persegi",
    "esriSquareDecimeters": "Desimeter Persegi",
    "esriSquareMeters": "Meter Persegi",
    "esriAres": "Are",
    "esriHectares": "Hektare",
    "esriSquareKilometers": "Kilometer Persegi"
  },
  "operationLabel": {
    "esriMensurationPoint": "Lokasi",
    "esriMensurationDistanceAndAngle": "Jarak dan Sudut",
    "esriMensurationAreaAndPerimeter": "Luas dan Keliling",
    "esriMensurationHeightFromBaseAndTop": "Tinggi: Dasar ke Puncak",
    "esriMensurationHeightFromBaseAndTopShadow": "Tinggi: Dasar ke Bayangan Puncak",
    "esriMensurationHeightFromTopAndTopShadow": "Tinggi: Puncak ke Bayangan Puncak",
    "esriMensurationCentroid": "Titik Berat",
    "esriMensurationPoint3D": "Lokasi (3D)",
    "esriMensurationDistanceAndAngle3D": "Jarak dan Sudut (3D)",
    "esriMensurationAreaAndPerimeter3D": "Luas dan Keliling (3D)",
    "esriMensurationCentroid3D": "Titik Berat (3D)"
  }
});