define({
  "_widgetLabel": "Trình biên tập Thông minh",
  "_featureAction_SmartEditor": "Trình biên tập Thông minh",
  "noEditPrivileges": "Tài khoản của bạn không có quyền tạo hoặc sửa đổi dữ liệu.",
  "widgetActive": "Hoạt động",
  "widgetNotActive": "Không Hoạt động",
  "pressStr": "Nhấn ",
  "ctrlStr": " CTRL ",
  "snapStr": " để bật tính năng chụp ảnh nhanh",
  "noAvailableTempaltes": "Không có mẫu khả dụng",
  "editorCache": " - Bộ nhớ cache Trình biên tập",
  "presetFieldAlias": "Trường",
  "presetValue": "Giá trị Đặt trước",
  "usePresetValues": " Sử dụng Giá trị Đặt trước (Chỉ các đối tượng mới)",
  "editGeometry": " Chỉnh sửa Hình học",
  "savePromptTitle": "Lưu đối tượng",
  "savePrompt": "Bạn có muốn lưu đối tượng hiện tại không?",
  "deletePromptTitle": "Xóa đối tượng",
  "deletePrompt": "Bạn có chắc chắn muốn xóa đối tượng được chọn không?",
  "attachmentLoadingError": "Đã xảy ra lỗi khi tải lên tệp đính kèm",
  "attachmentSaveDeleteWarning": "Cảnh báo: Tự động lưu các thay đổi với tệp đính kèm",
  "autoSaveEdits": "Tự động lưu chỉnh sửa",
  "addNewFeature": "Tạo đối tượng mới",
  "featureCreationFailedMsg": "Không thể tạo bản ghi/đối tượng mới",
  "noRelatedFeatureFoundMsg": "Không tìm thấy bản ghi/đối tượng liên quan",
  "relatedItemTitle": "Bảng/lớp liên quan",
  "invalidRelationShipMsg": "Vui lòng đảm bảo trường khóa chính: '${parentKeyField}’ chứa giá trị hợp lệ",
  "pendingFeatureSaveMsg": "Vui lòng lưu các chỉnh sửa đối tượng trước khi tạo đối tượng liên quan.",
  "attachmentsRequiredMsg": "(*) Yêu cầu tệp đính kèm.",
  "filterEditor": {
    "all": "Tất cả",
    "noAvailableTempaltes": "Không có mẫu khả dụng",
    "searchTemplates": "Mẫu Tìm kiếm"
  },
  "invalidConfiguration": "Tiện ích chưa được cấu hình hoặc lớp trong cấu hình không còn trong bản đồ. Vui lòng mở ứng dụng trong chế độ bộ thiết lập và cấu hình lại tiện ích.",
  "geometryServiceURLNotFoundMSG": "Không thể nhận URL Dịch vụ hình học"
});