define({
  "layerSelect": "Chọn Lớp Hình ảnh",
  "displayMeasureResultInPopup": "Hiển thị Kết quả Đo lường trong Cửa sổ pop-up",
  "angularUnitSelect": "Đơn vị Góc Mặc định",
  "linearUnitSelect": "Đơn vị Tuyến tính Mặc định",
  "areaUnitSelect": "Đơn vị Diện tích Mặc định",
  "displayOperationSelect": "Chọn Hoạt động Đo lường",
  "errorSectionMessage": "Không có lớp nào hỗ trợ tính năng đo lường.",
  "unitLabel": {
    "esriInches": "Inch",
    "esriFeet": "Feet",
    "esriYards": "Thước",
    "esriMiles": "Dặm",
    "esriNauticalMiles": "Hải lý",
    "esriMillimeters": "Milimét",
    "esriCentimeters": "Xentimét",
    "esriDecimeters": "Đềximét",
    "esriMeters": "Mét",
    "esriKilometers": "Kilômét",
    "esriDURadians": "Radian",
    "esriDUDecimalDegrees": "Độ",
    "esriSquareInches": "Inch Vuông",
    "esriSquareFeet": "Feet vuông",
    "esriSquareYards": "Thước vuông",
    "esriAcres": "Acre",
    "esriSquareMiles": "Dặm vuông",
    "esriSquareMillimeters": "Milimét Vuông",
    "esriSquareCentimeters": "Xentimét Vuông",
    "esriSquareDecimeters": "Đềximét Vuông",
    "esriSquareMeters": "Mét vuông",
    "esriAres": "Are",
    "esriHectares": "Hecta",
    "esriSquareKilometers": "Kilômét vuông"
  },
  "operationLabel": {
    "esriMensurationPoint": "Vị trí",
    "esriMensurationDistanceAndAngle": "Khoảng cách và Góc",
    "esriMensurationAreaAndPerimeter": "Khu vực và Chu vi",
    "esriMensurationHeightFromBaseAndTop": "Chiều cao: Từ Đế đến Đỉnh",
    "esriMensurationHeightFromBaseAndTopShadow": "Chiều cao: Từ Đế đến Đỉnh-Bóng",
    "esriMensurationHeightFromTopAndTopShadow": "Chiều cao: Từ Đỉnh đến Đỉnh-Bóng",
    "esriMensurationCentroid": "Trọng tâm",
    "esriMensurationPoint3D": "Vị trí (3D)",
    "esriMensurationDistanceAndAngle3D": "Khoảng cách và Góc (3D)",
    "esriMensurationAreaAndPerimeter3D": "Diện tích và Chu vi (3D)",
    "esriMensurationCentroid3D": "Trọng tâm (3D)"
  }
});