define({
  "gridTabLabel": "Mřížka",
  "labelTabLabel": "Popisky",
  "referenceSystemTabLabel": "Referenční systém",
  "gridTabDescription": "Nastavte vzhled a chování buněk mřížky.",
  "cellOutlineColor": "Barva ohraničení buněk",
  "cellFillColor": "Barva výplně buněk",
  "transparency": "Průhlednost",
  "cellShapeDropDown": "Tvar buněk",
  "default": "Obdélník",
  "hexagon": "Šestiúhelník",
  "cellUnitsDropDown": "Jednotky buněk",
  "miles": "míle",
  "kilometers": "kilometry",
  "feet": "stopy",
  "meters": "metry",
  "yards": "yardy",
  "nautical-miles": "námořní míle",
  "gridOriginDropDown": "Počátek mřížky",
  "lowerLeft": "Levý dolní",
  "lowerRight": "Pravý dolní",
  "upperLeft": "Levý horní",
  "upperRight": "Pravý horní",
  "center": "Střed",
  "labelTabDescription": "Nastavte vzhled a chování popisků mřížky.",
  "labelSettings": "Styl popisku",
  "font": "Písmo",
  "textSize": "Velikost textu",
  "textColor": "Barva textu",
  "halo": "Aureola",
  "show": "Zobrazit",
  "labelTypeDropDown": "Typ popisku",
  "alphaNumeric": "Alfanumerický",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Číselné",
  "labelDirectionDropDown": "Směr popisku",
  "horizontal": "Vodorovně",
  "vertical": "Svisle",
  "labelOriginDropDown": "Počátek popisku",
  "referenceSystemlTabDescription": "Nastavit výchozí referenční systém.",
  "MGRS": "Vojenská hlásná síť (MGRS)",
  "USNG": "USNG",
  "lockSettings": "Nastavení zámku – zabrání uživateli měnit jakákoliv konfigurovaná nastavení widgetu"
});