define({
  "_widgetLabel": "Gitternetz-Referenzgrafik",
  "newGRGFromAreaButtonLabel": "Gitternetz aus einer Fläche definieren",
  "newGRGFromPointButtonLabel": "Gitternetz aus einem Punkt definieren",
  "newGRGFromAreaTitle": "Gitternetz aus einer Fläche definieren",
  "newGRGFromPointTitle": "Gitternetz aus einem Punkt definieren",
  "newGRGBySizeButtonLabel": "Nach Dimension",
  "newGRGFromRefSystemButtonLabel": "Nach Bezugssystem",
  "newGRGByTimeLabel": "Nach Zeit und Geschwindigkeit",
  "newGRGFromNonStandardButtonLabel": "Nicht standardmäßiges Gitternetz definieren",
  "newGRGAreaBySizeTitle": "GRG aus einer Fläche nach Dimension",
  "newGRGAreaBySizeDefineAreaLabel": "GRG-Fläche",
  "addGRGAreaPolygonToolTip": "GRG-Fläche mit Polygon zeichnen",
  "addGRGAreaExtentToolTip": "GRG-Fläche mit Ausdehnung zeichnen",
  "rotation": "Gitterdrehung",
  "numberRowsColumnsLabel": "Anzahl der Zeilen und Spalten festlegen",
  "newGRGAreaByRefSystemTitle": "GRG aus einer Fläche nach Bezugssystem",
  "gridSize": "Gittergröße",
  "UTMZoneandBand": "Gitter-Zone",
  "100000m": "100000 Meter",
  "10000m": "10000 Meter",
  "1000m": "1000 Meter",
  "100m": "100 Meter",
  "10m": "10 Meter",
  "clipGrid": "Gitter auf GRG-Fläche zuschneiden",
  "newGRGAreaFromNonStandardTitle": "Neues GRG",
  "newGRGPointBySizeTitle": "GRG aus Punkt nach Dimension",
  "newGRGPointByRefSystemTitle": "GRG aus Punkt nach Bezugssystem",
  "newGRGPointByTimeTitle": "GRG aus Punkt mit Zeit und Geschwindigkeit",
  "time": "Zeit",
  "rate": "Geschwindigkeit",
  "hours": "Stunden",
  "minutes": "Minuten",
  "seconds": "Sekunden",
  "ftPerSec": "Fuß/Sekunde",
  "ftPerHour": "Fuß/Stunde",
  "kmPerSec": "Kilometer/Sekunde",
  "kmPerHour": "Kilometer/Stunde",
  "mPerSec": "Meter/Sekunde",
  "mPerHour": "Meter/Stunde",
  "miPerSec": "Meilen/Sekunde",
  "miPerHour": "Meilen/Stunde",
  "nMPerSec": "Seemeilen/Sekunde",
  "nMPerHour": "Seemeilen/Stunde",
  "settingsTitle": "Einstellungen",
  "labelSettingsLabel": "Beschriftungseinstellungen",
  "labelSettingsButtonLabel": "Beschriftungseinstellungen konfigurieren",
  "gridSettingsLabel": "Gitter-Einstellungen",
  "gridSettingsButtonLabel": "Gitter-Einstellungen konfigurieren",
  "transparency": "Transparenz",
  "labelStyle": "Beschriftungs-Style",
  "font": "Schriftart",
  "textSize": "Textgröße",
  "textColor": "Textfarbe",
  "halo": "Halo",
  "show": "Einblenden",
  "lockSettings": "Einstellungen wurden vom Anwendungsbesitzer gesperrt",
  "gridSettings": {
    "cellShape": "Zellenform",
    "cellUnits": "Zelleneinheiten",
    "cellOutline": "Zellenumrisslinien-Einstellungen",
    "cellFill": "Zellenfüllungs-Einstellungen",
    "gridReferenceSystem": "Bezugssystem",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Beschriftungsursprung",
    "labelType": "Beschriftungstyp",
    "labelDirection": "Beschriftungsrichtung",
    "gridOrigin": "Grid-Ursprung",
    "default": "Rechteck",
    "hexagon": "Hexagon",
    "miles": "Meilen",
    "kilometers": "Kilometer",
    "feet": "Fuß",
    "meters": "Meter",
    "yards": "Yards",
    "nautical-miles": "Seemeilen",
    "lowerLeft": "Unten links",
    "lowerRight": "Unten rechts",
    "upperLeft": "Oben links",
    "upperRight": "Oben rechts",
    "center": "Zentriert",
    "alphaNumeric": "Alphanumerisch",
    "alphaAlpha": "Alpha-Alpha",
    "numeric": "Numerisch",
    "horizontal": "Horizontal",
    "vertical": "Vertikal",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Beschriftungen anzeigen"
  },
  "publishTitle": "GRG in Portal veröffentlichen",
  "publishGRGBtn": "Veröffentlichen",
  "GRGLayerName": "Name des veröffentlichten GRG-Layers",
  "invalidGRGLayerName": "Der Layer-Name darf nur alphanumerische Zeichen und Unterstriche enthalten.",
  "missingGRGLayerName": "Sie müssen einen Namen für die GRG eingeben.",
  "publishingFailedLayerExists": "Fehler beim Veröffentlichen: Sie verfügen bereits über einen Service mit dem Namen {0}. Wählen Sie einen anderen Namen aus.",
  "checkService": "Service {0} überprüfen",
  "createService": "Service {0} erstellen",
  "unableToCreate": "{0} kann nicht erstellt werden",
  "addToDefinition": "Zur Definition {0} hinzufügen",
  "successfullyPublished": "Web-Layer wurde erfolgreich veröffentlicht{0}Web-Layer verwalten",
  "userRole": "Der Service kann nicht erstellt werden, da dem Benutzer nicht die entsprechenden Berechtigungen zugewiesen sind.",
  "createGRGBtn": "GRG erstellen",
  "clearGRGBtn": "Auswahl aufheben",
  "labelFormat": "Beschriftungsformat",
  "helpIconTooltip": "Z: Gitter-Zoneneinteilung (Grid Zone Designation, GZD)\nS: Identifikator für 100.000-Meter-Gitternetzquadrate\nX: Ostwert (X-Koordinate)\nY: Nordwert (Y-Koordinate)\n\nBeispiele:\nZSXY ist 15SWC8081751205\nZS X,Y ist 15SWC 80817,51205",
  "addPointToolTip": "GRG-Ursprung hinzufügen",
  "cellWidth": "Zellenbreite (x)",
  "cellHeight": "Zellenhöhe (y)",
  "invalidNumberMessage": "Der eingegebene Wert ist ungültig",
  "invalidRangeMessage": "Wert muss größer als 0 sein",
  "gridAngleInvalidRangeMessage": "Wert muss zwischen -89,9 und 89,9 liegen",
  "formatIconTooltip": "Eingabe formatieren",
  "coordInputLabel": "GRG-Ursprung (DD)",
  "setCoordFormat": "Zeichenfolge für Koordinatenformat festlegen",
  "prefixNumbers": "Positiven und negativen Zahlen ein \"+/-\"-Präfix hinzufügen",
  "cancelBtn": "Abbrechen",
  "applyBtn": "Anwenden",
  "comfirmInputNotation": "Eingegebene Schreibweise bestätigen",
  "notationsMatch": "Die Schreibweisen entsprechen Ihrer Eingabe. Geben Sie an, welche Sie verwenden möchten:",
  "numberOfCellsHorizontal": "Anz. der horizontalen Zellen",
  "numberOfCellsVertical": "Anz. der vertikalen Zellen",
  "gridAngle": "Gitterdrehung",
  "tooManyCellsErrorMessage": "Sie möchten ein Gitternetz aus mehr als 2000 Zellen erstellen. Sie sollten die Anzahl der erstellten Zellen durch Ändern der Gittergröße oder -fläche reduzieren.",
  "missingParametersMessage": "<p>Das GRG-Erstellungsformular enthält keine oder ungültige Parameter. Stellen Sie Folgendes sicher:</p><ul><li>Es wurde eine GRG-Fläche gezeichnet.</li><li>Die Zellenbreite und -höhe enthalten jeweils gültige Werte.</li></ul>",
  "missingOriginParametersMessage": "<p>Das GRG-Erstellungsformular enthält keine oder ungültige Parameter. Stellen Sie Folgendes sicher:</p><ul><li>Es wurde ein GRG-Ursprung festgelegt.</li><li>Die Zeit, Geschwindigkeit und Winkeleingaben enthalten gültige Werte.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Das GRG-Erstellungsformular enthält keine oder ungültige Parameter. Stellen Sie sicher, dass die Eingaben für die Zellenbreite und -höhe gültige Werte enthalten.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Das GRG-Erstellungsformular enthält keine oder ungültige Parameter. Stellen Sie sicher, dass die Eingaben für die Anzahl der horizontalen und vertikalen Zellen gültige Werte enthalten.</p>",
  "drawPointToolTip": "Klicken Sie, um den GRG-Ursprungspunkt hinzuzufügen.",
  "missingLayerNameMessage": "Sie müssen einen gültigen Layer-Namen eingeben, bevor Sie ihn veröffentlichen können.",
  "parseCoordinatesError": "Koordinaten können nicht geparst werden. Überprüfen Sie Ihre Eingabe.",
  "grgPolarRegionError": "Die GRG-Ausdehnung befindet sich in einer Polarregion. Zellen, die in der Polarregion liegen, werden nicht erstellt.",
  "grgPolarOriginError": "Der GRG-Ursprungspunkt darf nicht in einer Polarregion liegen, wenn eine GRG nach Bezugssystem erstellt wird.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dezimalgrad – Breitengrad/Längengrad",
  "DDLongLatNotation": "Dezimalgrad – Längengrad/Breitengrad",
  "DDMLatLongNotation": "Grad Dezimalminuten – Breitengrad/Längengrad",
  "DDMLongLatNotation": "Grad Dezimalminuten – Längengrad/Breitengrad",
  "DMSLatLongNotation": "Grad, Minuten, Sekunden – Breitengrad/Längengrad",
  "DMSLongLatNotation": "Grad, Minuten, Sekunden – Längengrad/Breitengrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbuchstabe",
  "UTMHemNotation": "UTM – Hemisphäre (N/S)"
});