define({
  "enableUndoRedo": "Включить Отмена/Повтор",
  "toolbarVisible": "Видимость панели инструментов",
  "toolbarOptions": "Параметры панели инструментов",
  "mergeVisible": "Слияние",
  "cutVisible": "Вырезать",
  "reshapeVisible": "Изменить форму",
  "back": "Назад",
  "label": "Слой",
  "edit": "Редактируемый",
  "update": "Не обновлять геометрию",
  "fields": "Поля",
  "actions": "Действия",
  "editpageName": "Имя",
  "editpageAlias": "Псевдоним",
  "editpageVisible": "Видимый",
  "editpageEditable": "Редактируемый",
  "noLayers": "Нет доступных для редактирования объектов",
  "configureFields": "Настройка полей слоя",
  "useFilterEdit": "Использовать фильтр шаблонов объектов",
  "display": "Отображение",
  "autoApplyEditWhenGeometryIsMoved": "Автоматически применить редактирование при перемещении геометрии",
  "snappingTolerance": "Настройка допуска замыкания в пикселах",
  "popupTolerance": "Задайте допуск замыкания всплывающего окна редактирования атрибутов в пикселах",
  "stickyMoveTolerance": "Настройка допуска замыкания курсора в пикселах",
  "usingSaveButton": "Не применять изменения к атрибутам, пока не нажмете кнопку Сохранить"
});