define({
  "_widgetLabel": "Svjesnost o situaciji",
  "locate_incident": "Pronađi incident",
  "reverse_geocoded_address": "Najbliža adresa",
  "reverse_geocoded_error": "Nije dostupno",
  "now": "SADA",
  "wind": "VJETAR",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "UTO",
  "WED": "SRI",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SUB",
  "actionLabel": "Postavi lokaciju",
  "drawPoint": "Nacrtaj točku",
  "drawLine": "Nacrtaj liniju",
  "drawPolygon": "Nacrtaj poligon",
  "saveIncident": "Spremi",
  "clearIncident": "Kreni ispočetka",
  "noFeaturesFound": "Nema geoobjekata.",
  "downloadCSV": "Preuzmi",
  "sum": "Zbroj",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Prosječno",
  "count": "BROJ",
  "area": "POVRŠINA",
  "length": "DULJINA",
  "update_btn": "Gotovo",
  "delete_btn": "Izbriši",
  "get_directions": "Dobivanje uputa za vožnju",
  "incident": "Incident",
  "incidents": "Incidenti",
  "buffer": "Pojas",
  "buffers": "Pojasevi",
  "weather": "Vrijeme",
  "poweredBy": "Omogućuje",
  "_featureAction_ActionLabel": "Postavi lokaciju",
  "_featureAction_AddRemoveActionLabel": "Dodaj/ukloni lokaciju",
  "snapshot": "Mapa SnapShot koju je stvorio App id:",
  "user_credentials": "Korisnik nema valjane privilegije.",
  "notPolySnapShot": "Odredite udaljenost pojasa prije stvaranja snimke.",
  "notPolyReport": "Nema valjanih rezultata za dodavanje izvješću.",
  "notValidDownload": "Nema valjanih rezultata za preuzimanje.",
  "of_append": "od",
  "layer_append": "sloj",
  "downloadAll": "Preuzmi sve",
  "createSnapshot": "Stvori snimku",
  "createReport": "Stvori izvješće",
  "calculated_results": "Sažete informacije",
  "closest": "Najbliži geoobjekt",
  "proximity": "Blizina",
  "summary": "Sažetak",
  "groupedSummary": "Grupirani zbrojevi",
  "_count": "Broj",
  "approximate": "približno",
  "snapshot_name": "Postavi svojstva snimke",
  "report_name": "Postavi svojstva izvješća",
  "invalid_snapshot_name": "Nevažeći naziv snimke.",
  "invalid_report_name": "Nevažeći naziv izvješća.",
  "orientation": "Orijentacija",
  "pageSize": "Veličina stranice",
  "comments": "Komentari",
  "choose_group": "Grupe",
  "forecast": "Prognoza",
  "select_group": "Odaberi grupu",
  "select_group_instruction": "Snimka će se stvoriti i podijeliti s odabranog grupom",
  "information_append": " Informacije",
  "distance": "UDALJENOST",
  "buffer_invalid": "Unesite valjani broj između ${min} i ${max}"
});