define({
  "add": "Klikk for å legge til ny",
  "title": "Tittel",
  "placeholderBookmarkName": "Bokmerkenavn",
  "ok": "OK",
  "cancel": "Avbryt",
  "warning": "Fullfør redigeringen!",
  "edit": "Rediger bokmerke",
  "errorNameExist": "Bokmerket eksisterer.",
  "errorNameNull": "Ugyldig bokmerkenavn.",
  "addBookmark": "Opprett ny",
  "thumbnail": "Miniatyrbilde",
  "thumbnailHint": "Klikk på bildet for å oppdatere",
  "displayBookmarksAs": "Vis bokmerker som",
  "cards": "Kort",
  "list": "Liste",
  "cardsTips": "Kortvisning",
  "listTips": "Listevisning",
  "makeAsDefault": "Angi som standard",
  "default": "Standard",
  "editable": "Tillat å legge til bokmerker i widgeten.",
  "alwaysSync": "Vis bokmerker fra webkartet",
  "configCustom": "Vis egendefinerte bokmerker",
  "import": "Importer",
  "create": "Opprett",
  "importTitle": "Importer bokmerker",
  "importFromWeb": "Importer bokmerker fra gjeldende webkart",
  "selectAll": "Merk alle",
  "noBookmarkInConfig": "Klikk på Importer eller Opprett nyt for å legge til bokmerker.",
  "noBookmarkInWebMap": "Ingen bokmerker er konfigurert i kartet.",
  "extent": "Omfang",
  "saveExtent": "Lagre kartutstrekningen til dette bokmerket",
  "savelayers": "Lagre synligheten for lag",
  "withVisibility": "Med lagsynlighet",
  "bookmark": "Bokmerke",
  "addBtn": "Legg til",
  "deleteBtn": "Slett",
  "editBtn": "Rediger",
  "dragReorderTip": "Hold og dra for å endre rekkefølgen",
  "deleteBtnTip": "Slett bokmerket",
  "editBtnTip": "Rediger bokmerket"
});