define({
  "_widgetLabel": "Контроль за ситуацией",
  "locate_incident": "Найти инцидент",
  "reverse_geocoded_address": "Ближайший адрес",
  "reverse_geocoded_error": "Не доступно",
  "now": "Сейчас",
  "wind": "WIND",
  "SUN": "ВС",
  "MON": "ПН",
  "TUE": "ВТ",
  "WED": "СР",
  "THU": "ЧТ",
  "FRI": "ПТ",
  "SAT": "СБ",
  "actionLabel": "Задать местоположение",
  "drawPoint": "Нарисовать точку",
  "drawLine": "Нарисовать линию",
  "drawPolygon": "Нарисовать полигон",
  "saveIncident": "Сохранить",
  "clearIncident": "Начать сначала",
  "noFeaturesFound": "Объекты не найдены.",
  "downloadCSV": "Загрузка",
  "sum": "Сумма",
  "min": "Минимум",
  "max": "Максимум",
  "avg": "Среднее",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "Готово",
  "delete_btn": "Удалить",
  "get_directions": "Построить маршрут",
  "incident": "Инцидент",
  "incidents": "Инциденты",
  "buffer": "Буфер",
  "buffers": "Буферы",
  "weather": "Погода",
  "poweredBy": "Работает на",
  "_featureAction_ActionLabel": "Задать местоположение",
  "_featureAction_AddRemoveActionLabel": "Добавить/удалить местоположение",
  "snapshot": "Папке SnapShot, созданная приложением с id:",
  "user_credentials": "Пользователь не имеет соответствующих права доступа",
  "notPolySnapShot": "Перед созданием снимка необходимо указать буферное расстояние.",
  "notPolyReport": "Нет корректных результатов для добавления в отчет.",
  "notValidDownload": "Нет корректных результатов для загрузки",
  "of_append": "из",
  "layer_append": "слой",
  "downloadAll": "Загрузить все",
  "createSnapshot": "Создать снимок",
  "createReport": "Создать отчет",
  "calculated_results": "Суммированная информация",
  "closest": "Ближайший объект",
  "proximity": "Близость",
  "summary": "Краткая информация",
  "groupedSummary": "Количество сгруппированных",
  "_count": "Количество",
  "approximate": "апроксимация",
  "snapshot_name": "Задать свойства снимка",
  "report_name": "Задать свойства отчета",
  "invalid_snapshot_name": "Недопустимое имя снимка.",
  "invalid_report_name": "Некорректный заголовок отчета.",
  "orientation": "Ориентация",
  "pageSize": "Размер страницы",
  "comments": "Комментарии",
  "choose_group": "Группы",
  "forecast": "Прогноз",
  "select_group": "Выбрать группу",
  "select_group_instruction": "Снимок будет создан и опубликован для выбранной группы.",
  "information_append": " Информация",
  "distance": "РАССТОЯНИЕ",
  "buffer_invalid": "Введите корректное число между ${min} и ${max}"
});