define({
  "_widgetLabel": "Užklausos",
  "executeQueryTip": "Norėdami vykdyti užklausą, paspauskite vieną iš šių užduoties elementų.",
  "invalidConfig": "Neleistina konfigūracija. Užklausos nustatymo puslapyje nustatykite tinkamą konfigūraciją.",
  "queryParams": "Parinktys",
  "parameters": "PARINKTYS",
  "queries": "UŽKLAUSOS",
  "apply": "Taikyti",
  "queryResults": "Rezultatai",
  "clear": "Valyti",
  "noResults": "Elementų nerasta.",
  "queryError": "Užklausos įvykdyti nepavyko!",
  "numberFound": "Rastų elementų skaičius",
  "mapExtentTip": "Apribokite rezultatus iki esamo žemėlapio ploto.",
  "noValue": "Reikšmių nėra",
  "and": "ir",
  "stringOperatorIs": "yra",
  "stringOperatorIsNot": "nėra",
  "stringOperatorStartsWith": "prasideda su",
  "stringOperatorEndsWith": "baigiasi su",
  "stringOperatorContains": "įraše yra",
  "stringOperatorDoesNotContain": "įraše nėra",
  "stringOperatorIsBlank": "yra tuščias",
  "stringOperatorIsNotBlank": "nėra tuščias",
  "dateOperatorIsOn": "yra ant",
  "dateOperatorIsNotOn": "yra ne ant",
  "dateOperatorIsBefore": "yra prieš",
  "dateOperatorIsAfter": "yra po",
  "dateOperatorDays": "dienos",
  "dateOperatorWeeks": "savaitės",
  "dateOperatorMonths": "mėnesiai",
  "dateOperatorInTheLast": "yra paskutinis",
  "dateOperatorNotInTheLast": "nėra paskutinis",
  "dateOperatorIsBetween": "yra tarp",
  "dateOperatorIsNotBetween": "nėra tarp",
  "dateOperatorIsBlank": "yra tuščias",
  "dateOperatorIsNotBlank": "nėra tuščias",
  "numberOperatorIs": "yra",
  "numberOperatorIsNot": "nėra",
  "numberOperatorIsAtLeast": "yra mažiausia (bent)",
  "numberOperatorIsLessThan": "yra mažiau nei",
  "numberOperatorIsAtMost": "yra daugiausia",
  "numberOperatorIsGreaterThan": "yra daugiau nei",
  "numberOperatorIsBetween": "yra tarp",
  "numberOperatorIsNotBetween": "nėra tarp",
  "numberOperatorIsBlank": "yra tuščias",
  "numberOperatorIsNotBlank": "nėra tuščias",
  "operationalLayerTip": "Pridėti rezultatus kaip darbinį sluoksnį",
  "queryResult": "Užklausos rezultatas",
  "specifyParamsTip": "Nurodyti užduoties parametrus",
  "useSpatialFilter": "Naudoti erdvinį filtrą elementų apribojimui",
  "useCurrentMapExtent": "Tik elementai, besikertantys su esamu žemėlapio plotu",
  "drawGraphicOnMap": "Tik elementai, besikertantys su vartotojo apibrėžtu plotu",
  "specifySpatialFilterMsg": "Nurodykite šios užduoties erdvinį filtrą.",
  "clearResults": "Išvalyti rezultatus",
  "operationalTip": "Pažymėjus šią parinktį, rezultatai bus saugomi žemėlapyje, kol paspausite mygtuką „${clearResults}“.",
  "noneQueryTip": "Šiam valdikliui nesukonfigūruota nė viena užklausos užduotis.",
  "noPermissionsMsg": "Neturite teisės pasiekti šią paslaugą.",
  "attributesFromRelationship": "Atributai iš susijusios lentelės",
  "tasks": "Užduotys",
  "applySpatialFilterToLimitResults": "Taikyti erdvinį filtrą, kad būtų apriboti rezultatai",
  "useCurrentExtentTip": "Grąžinti elementus tik šio žemėlapio aprėptyje",
  "useDrawGraphicTip": "Tik grąžinimo elementai, kurie susikerta su žemėlapyje nubrėžta figūra",
  "useFeaturesTip": "Grąžinti tik elementus, kurie turi erdvinį ryšį su kito sluoksnio elementais",
  "noSpatialLimitTip": "Grįžimo elementai visoje žemėlapio aprėptyje",
  "applySearchDistance": "Taikyti paieškos nuotolį",
  "spatialRelationship": "Erdviniai ryšiai",
  "relatedLayer": "Susijęs sluoksnis",
  "bufferDistance": "Buferio atstumas",
  "miles": "Mylios",
  "kilometers": "Kilometrai",
  "feet": "Pėdos",
  "meters": "Metrai",
  "yards": "Jardai",
  "nauticalMiles": "Jūrmylės",
  "back": "Atgal",
  "execute": "Vykdyti",
  "zoomTo": "Pritraukti iki",
  "openAttributeTable": "Peržiūrėti atributų lentelėje",
  "noResult": "Nėra rezultato.",
  "noTask": "Nėra užduoties.",
  "removeThisResult": "Pašalinti šį rezultatą",
  "attributeCriteira": "Atributo kriterijai",
  "spatialFilter": "Erdvinis filtras",
  "value": "REIKŠMĖ",
  "noAttributeSpatialFilterTip": "Nenurodyta jokių filtrų. Visi elementai bus grąžinti.",
  "showAllRelatedRecords": "Rodyti visus susijusius įrašus",
  "changeSymbol": "Pakeisti simbolį",
  "queryCriteira": "Užklausos kriterijai",
  "customQuery": "Pasirinktinė užklausa",
  "layer": "Sluoksnis",
  "createCustomQuery": "Kurti pasirinktinę užklausą."
});