define({
  "gridTabLabel": "Grilă",
  "labelTabLabel": "Etichete",
  "referenceSystemTabLabel": "Sistem referinţă",
  "gridTabDescription": "Setați aspectul și comportamentul celulelor de grilă.",
  "cellOutlineColor": "Culoarea conturului celulei",
  "cellFillColor": "Culoare de umplere a celulei",
  "transparency": "Transparenţă",
  "cellShapeDropDown": "Forma celulei",
  "default": "Dreptunghi",
  "hexagon": "Hexagon",
  "cellUnitsDropDown": "Unități de celulă",
  "miles": "Mile",
  "kilometers": "Kilometri",
  "feet": "Ft",
  "meters": "Metri",
  "yards": "Yarzi",
  "nautical-miles": "Mile marine",
  "gridOriginDropDown": "Originea grilei",
  "lowerLeft": "Stânga jos",
  "lowerRight": "Dreapta jos",
  "upperLeft": "Stânga sus",
  "upperRight": "Dreapta sus",
  "center": "Centru",
  "labelTabDescription": "Setați aspectul și comportamentul etichetelor de grilă.",
  "labelSettings": "Stil etichetă",
  "font": "Font",
  "textSize": "Dimensiune text",
  "textColor": "Culoare text",
  "halo": "Bună",
  "show": "Afişează",
  "labelTypeDropDown": "Tipul etichetei",
  "alphaNumeric": "Alfanumeric",
  "alphaAlpha": "Alfa-Alfa",
  "numeric": "Numeric",
  "labelDirectionDropDown": "Direcția etichetei",
  "horizontal": "Orizontal",
  "vertical": "Vertical",
  "labelOriginDropDown": "Originea etichetei",
  "referenceSystemlTabDescription": "Setați sistemul de referinţă implicit.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Blocarea Setărilor - Acest lucru va împiedica utilizatorul să schimbe oricare dintre setările configurate în cadrul widgetului."
});