define({
  "_widgetLabel": "Conversión de coordenada",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Grados decimales - Latitud/longitud",
  "DDLongLatNotation": "Grados decimales - Longitud/latitud",
  "DDMLatLongNotation": "Grados minutos decimales - Latitud/longitud",
  "DDMLongLatNotation": "Grados minutos decimales - Longitud/latitud",
  "DMSLatLongNotation": "Grados minutos segundos - Latitud/longitud",
  "DMSLongLatNotation": "Grados minutos segundos - Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra de banda",
  "UTMHemNotation": "UTM - Hemisferio (N/S)",
  "formatInput": "Formato de entrada",
  "copyAll": "Copiar todo",
  "copySuccessful": "Copia realizada correctamente",
  "copyFailed": "No se puede copiar. Use Ctrl+C como alternativa.",
  "parseCoordinatesError": "No se pueden analizar las coordenadas. Compruebe la entrada.",
  "comfirmInputNotation": "Confirmar notación de entrada",
  "latLongWarningMessage": "Se ha detectado que la coordenada de entrada tiene un prefijo y un sufijo para el valor de la latitud o la longitud y la coordenada devuelta se basa en el prefijo.",
  "inputLabel": "Entrada",
  "outputLabel": "Salida",
  "cancelButtonLabel": "Cancelar",
  "applyButtonLabel": "Aplicar",
  "posNegPrefixLabel": "Agregar prefijo \"+/-\" a los números positivos y negativos",
  "editCoordinateDialogTitle": "Definir cadena de caracteres de formato de coordenadas",
  "rememberDecisionLabel": "Recordar mi decisión y no volver a preguntar.<br/>",
  "coordinateInputLabel": "Introduzca las coordenadas o haga clic en el mapa",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notaciones encontradas que coinciden con su entrada. Confirme cuál desea usar:",
  "copyToClipboard": "Copiar al portapapeles",
  "formatOutput": "Formato de salida",
  "addNewNotation": "Agregar nueva notación",
  "notationAddedMessage": "Nueva notación agregada",
  "addLabel": "Agregar",
  "removeCoordinate": "Eliminar coordenada",
  "expandOutput": "Expandir salida",
  "latitudeLabel": "Lat",
  "longitudeLabel": "Long",
  "quadrantLabel": "Cuadrante",
  "keyLabel": "Clave",
  "fifteenDegreeLabel": "Cuadrante 15Â°",
  "oneDegreeLabel": "Cuadrante 1Â°",
  "eastingLabel": "Este",
  "northingLabel": "Norte",
  "zoneLabel": "Zona",
  "bandLabel": "Banda",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Cuadrado de cuadrícula",
  "hemisphereLabel": "Hemisferio"
});