define({
  "routeUrl": "เส้นทาง URL",
  "locatorUrl": "Geocoder URL",
  "geocoderOptions": "ตัวเลือก Geocoder",
  "autoComplete": "Autocomplete",
  "maximumSuggestions": "ข้อเสนอแนะสูงสุด",
  "minCharacters": "ตัวอักษรขั้นต่ำ",
  "searchDelay": "ค้นหาล่าช้า",
  "placeholder": "ตัวยึด",
  "routeOptions": "ตัวเลือกเส้นทาง",
  "directionsLanguage": "ทิศทางภาษา",
  "directionsLengthUnits": "ทิศทางหน่วยความยาว",
  "directionsOutputType": "ทิศทางประเภทผลลัพธ์",
  "impedanceAttribute": "การต้านทานข้อมูล",
  "kilometers": "กิโลเมตร",
  "miles": "ไมล์",
  "meters": "เมตร",
  "feet": "ฟุต",
  "yards": "หลา",
  "nauticalMiles": "ไมล์ทะเล",
  "parametersTip": "กรุณากำหนดพารามิเตอร์ให้ถูกต้อง",
  "complete": "สมบูรณ์",
  "completeNoEvents": "สมบูรณ์โดยไม่มีเหตุการณ์ใดใด",
  "instructionsOnly": "คำแนะนำเท่านั้น",
  "standard": "มาตรฐาน",
  "summaryOnly": "การสรุปเท่านั้น",
  "travelModesUrl": "URL โหมดการเดินทาง",
  "searchPlaceholder": "ค้นหาที่อยู่หรือสถานที่",
  "trafficLayerUrl": "URL ชั้นการจราจร",
  "presetDestinations": "ตั้งตำแหน่งไว้",
  "startPoint": "จุดเริ่มต้น",
  "endPoint": "จุดสิ้นสุด",
  "destinationHolder": "ที่อยู่หรือพิกัด",
  "optional": "ทางเลือก"
});