define({
  "symbolologyTabLabel": "सिम्बोलॉजी (प्रतीक-विद्या) कॉन्फ़िगर करें",
  "facilitiesDescription": "सुविधाओं की लेयर",
  "demographicsDescription": "जनसांख्यिकीय लेयर",
  "settingsTitle": "सेटिंग्स",
  "spillLocationLabel": "छलकने का स्थान",
  "spillLocationButtonLabel": "छलकने के स्थान की सेटिंग कॉन्फ़िगर करें",
  "IISettingsLabel": "आरंभिक पृथक्करण क्षेत्र",
  "IIButtonLabel": "आरंभिक पृथक्करण सेटिंग कॉन्फ़िगर करें",
  "PASettingsLabel": "सुरक्षात्मक कार्रवाई क्षेत्र",
  "PAButtonLabel": "सुरक्षात्मक कार्रवाई सेटिंग कॉन्फ़िगर करें",
  "downwindSettingsLabel": "हवा के रुख वाला क्षेत्र",
  "downwindButtonLabel": "हवा के रुख की सेटिंग कॉन्फ़िगर करें",
  "fireSettingsLabel": "अग्नि पृथक्करण क्षेत्र",
  "fireButtonLabel": "अग्नि पृथक्करण सेटिंग कॉन्फ़िगर करें",
  "bleveSettingsLabel": "BLEVE पृथक्करण क्षेत्र",
  "bleveButtonLabel": "BLEVE सेटिंग कॉन्फ़िगर करें",
  "transparency": "पारदर्शिता",
  "outline": "आउटलाइन",
  "fill": "भरें (स्टाइल के ठोस पर सेट होने पर ही रंग लागू होत हैं)",
  "style": "शैली",
  "lineStyles": {
    "esriSLSDash": "डैश",
    "esriSLSDashDot": "डैश डॉट",
    "esriSLSDashDotDot": "डैश डॉट डॉट",
    "esriSLSDot": "बिंदु",
    "esriSLSLongDash": "लोंग डैश (लंबा डैश)",
    "esriSLSLongDashDot": "लोंग डैश डॉट (लंबा डैश डॉट)",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "शॉर्ट डैश",
    "esriSLSShortDashDot": "शॉर्ट डैश डॉट (छोटा डैश डॉट)",
    "esriSLSShortDashDotDot": "शॉर्ट डैश डॉट डॉट",
    "esriSLSShortDot": "शॉर्ट डॉट",
    "esriSLSSolid": "ठोस"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "पीछे की ओर",
    "esriSFSCross": "क्रॉस",
    "esriSFSDiagonalCross": "तिरछा/विकर्ण",
    "esriSFSForwardDiagonal": "आगे करें",
    "esriSFSHorizontal": "क्षैतिज",
    "esriSFSNull": "Null",
    "esriSFSSolid": "ठोस",
    "esriSFSVertical": "लंबवत"
  }
});