define({
  "chartTasks": "Zadaci grafikona",
  "addNew": "Dodaj novi",
  "addNewTip": "Dodaj novi zadatak grafikona",
  "name": "Naziv",
  "set": "Postavi",
  "setDataSource": "Postavi izvor podataka",
  "generalSettingsTip": "Postavite izvor podataka, naslov i opis za grafikone.",
  "chartModeSettingTip": "Izaberite način analize i prikaza podataka kao grafikona.",
  "detailsSettingTip": "Postavite izgled grafikona određivanjem njegovog tipa i boje i toga koje vrednosti će biti u njemu:",
  "symbolSettingTip": "Postavi prikaz mape za podatke grafikona.",
  "addFilterTip": "Dodaj filter ovim podacima",
  "dataSource": "Izvor podataka",
  "noResults": "Nije pronađen nijedan geoobjekat.",
  "chartTitle": "Naslov grafikona",
  "description": "Opis",
  "chartingMode": "Prikaz grafikona",
  "featureOption": "Prikaži vrednosti geoobjekat po geoobjekat",
  "categoryOption": "Prikaži vrednosti po kategoriji",
  "countOption": "Prikaži broj geoobjekata po kategoriji",
  "fieldOption": "Prikaži vrednosti atributa kao grafikon",
  "category": "Kategorija",
  "axisLabel": "Oznaka kategorije",
  "categoryField": "Polje kategorije",
  "operation": "Radnja",
  "originalOption": "Koristi prvobitne vrednosti",
  "sumOption": "Zbir",
  "averageOption": "Prosečno",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "valueFields": "Polje vrednosti",
  "moveUp": "Pomeri se na gore",
  "moveDown": "Pomeri se na dole",
  "sortOrder": "Sortiraj redosled grafikona po oznakama kategorije",
  "ascending": "Rastuće",
  "descending": "Opadajuće",
  "chartType": "Tip grafikona",
  "column": "Stubičasti grafikon",
  "bar": "Trakasti grafikon",
  "line": "Linijski grafikon",
  "pie": "Kružni grafikon",
  "chartColor": "Boja grafikona",
  "showDataLabels": "Pokaži oznake podataka",
  "setSymbol": "Simbol selekcije",
  "setHighLightColor": "Istakni boju",
  "settings": "Postavke",
  "mapInterationOptions": "Opcije interakcije mape",
  "preview": "Pregledaj",
  "ok": "U redu",
  "cancel": "Otkaži",
  "close": "Zatvori",
  "setFilterTip": "Pravilno postavite filter. ",
  "setChartTitleTip": "Postavite naslov grafikona.",
  "setChartTypeTip": "Izaberite najmanje jedan tip grafikona.",
  "setDataFieldTip": "Izaberite najmanje jedno polje vrednosti.",
  "setOutputFieldTip": "Postavite polja izlaznih rezultata.",
  "count": "Brojač",
  "label": "Oznaka",
  "horizontalAxis": "Horizontalna osa",
  "verticalAxis": "Vertikalna osa",
  "dataLabels": "Oznake podataka",
  "color": "Boja",
  "colorful": "Šareno",
  "monochromatic": "Monohromatsko",
  "noTaskTip": "Kliknite na „Dodaj novi“ da biste dodali zadatak grafikona",
  "info": "Informacije",
  "charts": "Grafikoni",
  "options": "Opcije",
  "taskName": "Ime zadatka",
  "summary": "Rezime",
  "resultDescription": "Opis rezultata",
  "spatialFilterTip": "Izaberite prostorni filter/prostorne filtere koji će biti korišćeni u vidžetu da biste ograničili rezultate.",
  "defaultOption": "Podrazumevano",
  "useCurrentExtentTip": "Delimično ili potpuno unutar trenutnog obuhvata mape",
  "useDrawGraphicTip": "Delimično ili potpuno unutar oblika nacrtanog na mapi",
  "useFeaturesTip": "Na osnovu njihovih lokacija u odnosu na geoobjekte u drugom sloju",
  "noSpatialLimitTip": "Nemoj prostorno da ograničavaš rezultate",
  "drawingTools": "Alati za crtanje",
  "bufferSettings": "Postavke zone bliskosti",
  "defaultDistance": "Podrazumevano rastojanje",
  "bufferDistance": "Rastojanje zone bliskosti",
  "defaultUnit": "Podrazumevana jedinica",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "availableSpatialRelationships": "Dostupne prostorne veze",
  "setSpatialRelationships": "Postavi prostorne veze",
  "availability": "Dostupnost",
  "relationship": "Veza",
  "actions": "Radnje",
  "intersect": "presecanje",
  "contain": "sadrži",
  "areContainedIn": "sadržani su u",
  "cross": "ukrštanje",
  "envelopeIntersect": "presek pravougaonika",
  "overlap": "preklapanje",
  "areOverlapped": "su preklopljeni",
  "touche": "dodirivanje",
  "within": "unutar",
  "areWithin": "su unutar",
  "indexIntersect": "presecanje indeksa"
});