define({
  "tabs_section_Label": "Kartice",
  "addTab": "Dodaj karticu",
  "layerName": "Sloj",
  "layerType": "Tip analize",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "closest": "Najbliži geoobjekat",
  "proximity": "Blizina",
  "summary": "Rezime",
  "select_lbl": "-- Izaberi --",
  "general_setting_Label": "Opšte postavke",
  "units_text_lbl": "Jedinice rastojanja",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "maximum_distance_lbl": "Maksimalna udaljenost najbližeg geoobjekta",
  "buffer_text_lbl": "Oznaka zone bliskosti",
  "buffer_lbl": "Rastojanje zone bliskosti",
  "buffer_max_lbl": "Maksimalno rastojanje zone bliskosti",
  "buffer_min_lbl": "Minimalno rastojanje zone bliskosti",
  "routing_checkBox": "Omogući rutiranje",
  "weather_Label": "Opcije vremena",
  "weather_checkBox": "Uključi informacije o vremenu",
  "weather_celsius": "Celzijusi-kilometri",
  "selectLayers": "Izaberite slojeve vremena",
  "currentlySelectedLayer": "Trenutno izabrani slojevi vremena",
  "missingTabLabel": "Bar jednoj kartici nedostaje oznaka",
  "cancel": "Otkaži",
  "ok": "U redu",
  "missingLayerInWebMap": "Nema pronađenih operativnih slojeva.",
  "selectFields": "Izaberi polja",
  "addField": "Dodaj polje",
  "sum": "ZBIR",
  "min": "MIN",
  "max": "MAKS",
  "avg": "PROS.",
  "count": "BROJAČ",
  "area": "POVRŠINA",
  "length": "DUŽINA",
  "count_checkBox": "Prikaži izbrojano",
  "area_checkBox": "Prikaži površinu",
  "length_checkBox": "Prikaži dužinu",
  "max_records": "Maksimalno ograničenje je dostignuto",
  "disable_checkBox": "Onemogući upravljanje vidljivošću sloja",
  "optional_lbl": "Opcione oznake",
  "incident_lbl": "Incident",
  "locate_lbl": "Lociraj incident"
});