define({
  "_widgetLabel": "Afstand en richting",
  "tabLineTitle": "Lijn",
  "tabCircleTitle": "Cirkel",
  "tabEllipseTitle": "Ellips",
  "tabRingsTitle": "Ringen",
  "multipleNotationsMessage": " notaties gevonden die overeenstemmen met uw input. Bevestig welke u wenst te gebruiken:",
  "invalidCoordinateMessage": "Ongeldige coördinaat",
  "confirmInputNotationMessage": "Bevestig inputnotatie",
  "prefixSuffixMessage": "De inputcoördinaat is gedetecteerd met een prefix en suffix voor de lengte- en breedtegraadwaarde, geretourneerde coördinaat is gebaseerd op de prefix.",
  "rememberDecisionMessage": "Mijn keuze onthouden en niet meer vragen.<br/>",
  "majorAxisTooltipMessage": "Controleer de lengte van de grote as",
  "minorAxisTooltipMessage": "Verplaats de muis terug naar de startpositie om de kleine as in te stellen & het tekenen van de ovaal af te ronden",
  "clickToFinishLineMessage": "Klik om tekenen van lijn af te ronden",
  "doubleClickEllipseMesage": "Dubbelklik om het tekenen van bereikringen af te ronden",
  "invalidCoordinateTypeMessage": "Kan inputcoördinaattype niet bepalen. Controleer uw input",
  "noCenterPointSetMessage": "Geen middelpunt ingesteld. Controleer uw input",
  "ellipseMajorAxis": "Grote as",
  "ellipseMinorAxis": "Kleine as",
  "degreesRangeMessage": "De waarde moet tussen 0 en 360 liggen",
  "millsRangeMessage": "De waarde moet tussen 0 en 6400 liggen",
  "lengthLabel": "Lengte",
  "angleLabel": "Hoek",
  "startPointLabel": "Startpunt",
  "endPointLabel": "Eindpunt",
  "centerPointLabel": "Middenpunt",
  "distanceTableErrorMessage": "Afstandtabel is leeg. Zorg ervoor dat u wat afstanden invoert.",
  "setCoordFormatStringMessage": "Coördinaatindelingtekst",
  "prefixMessage": "Voeg \"+/-\" prefix toe aan positieve en negatieve cijfers",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Decimale graden - Breedtegraad/Lengtegraad",
  "DDLongLatNotation": "Decimale graden - Lengtegraad/Breedtegraad",
  "DDMLatLongNotation": "Graden decimale minuten - Breedtegraad/Lengtegraad",
  "DDMLongLatNotation": "Graden decimale minuten - Lengtegraad/Breedtegraad",
  "DMSLatLongNotation": "Graden decimale seconden - Breedtegraad/Lengtegraad",
  "DMSLongLatNotation": "Graden decimale seconden - Lengtegraad/Breedtegraad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisfeer (N/S)",
  "circleTitle": "Cirkel maken vanuit",
  "radiusLabel": "Straal",
  "diameterLabel": "Diameter",
  "startPointPlaceHolderLabel": "Coördinaten invoeren",
  "formatInputLabel": "Indeling invoer",
  "drawCircleLabel": "Cirkel tekenen",
  "drawLineLabel": "Lijn tekenen",
  "createCircleInteractivelyLabel": "Cirkel interactief maken",
  "rangeErrorMessage": "Ongeldige straal of diameter",
  "numericInvalidMessage": "Voer een numerieke waarde in",
  "timeLabel": "Tijd",
  "invalidTimeMessage": "Ongeldige tijdwaarde",
  "hoursLabel": "Uren",
  "minutesLabel": "Minuten",
  "secondsLabel": "Seconden",
  "rateLabel": "Beoordeling",
  "invalidDistanceMessage": "Ongeldige afstandswaarde",
  "feetSecondsLabel": "Voet / seconde",
  "feetHourLabel": "Voet / uur",
  "kmSecondLabel": "Kilometer / seconde",
  "kmHourLabel": "Kilometer / uur",
  "metersSecondLabel": "Meter / seconde",
  "metersHourLabel": "Meter / uur",
  "milesSecondLabel": "Mijl / seconde",
  "milesHourLabel": "Mijl / uur",
  "nauticalMilesSecondLabel": "Zeemijl / seconde",
  "nauticalMilesHourLabel": "Zeemijl / uur",
  "clearGraphicsLabel": "Graphics wissen",
  "ellipseTypeLabel": "Ovaaltype",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Volledig",
  "drawEllipseLabel": "Ellips tekenen",
  "createEllipseInteractively": "Ovaal interactief maken",
  "axisLabel": "As",
  "majorRadiusLabel": "Grote (straal)",
  "axisErrorMessage": "Waarde moet groter zijn dan 0",
  "minorRadiusLabel": "Kleine (straal)",
  "orientationLabel": "Oriëntatie",
  "orientationErrorMessage": "De waarde moet tussen 0 en 360 liggen",
  "warningMessage": "Waarschuwing: Graphics die gemaakt zijn met het ovaalgereedschap zijn niet geodetisch",
  "fromLabel": "van",
  "distanceBearingLabel": "Afstand en koers",
  "pointsLabel": "Punten",
  "createLineInteractively": "Lijn interactief maken",
  "lineLengthErrorMessage": "Ongeldige lijnlengte",
  "degreesLabel": "Graden",
  "milsLabel": "Mijl",
  "lineTypeLabel": "Type",
  "interactiveLabel": "Interactief",
  "fixedLabel": "Vast",
  "originLabel": "Oorsprong",
  "cumulativeLabel": "Cumulatief",
  "numberOfRingsLabel": "Aantal ringen",
  "ringsErrorMessage": "Ongeldig aantal ringen",
  "distanceBetweenRingsLabel": "Afstand tussen ringen",
  "ringsDecimalErrorMessage": "Voer een numerieke waarde in tot 2 cijfers na de komma",
  "distanceUnitsLabel": "Afstandseenheden",
  "distancesLabel": "Afstanden",
  "numberOfRadialsLabel": "Aantal radialen",
  "upLabel": "Bovenkant",
  "downLabel": "Naar beneden",
  "deleteLabel": "Verwijderen",
  "radialsErrorMessage": "Ongeldig aantal radialen. Het maximum toegelaten aantal is 360",
  "addPointLabel": "Punt toevoegen",
  "valueLabel": "Waarde",
  "valueText": "Waarde invoeren",
  "actionLabel": "Actie"
});