define({
  "_widgetLabel": "Katastrofeberedskabsvejledning",
  "ergMainPageTitle": "Baseret på Katastrofeberedskabsvejledningsbogen 2016",
  "coordInputLabelStart": "Udslippets placering (DD)",
  "coordInputLabel": "Udslippets placering",
  "addPointToolTip": "Tilføj udslipsposition",
  "drawPointToolTip": "Klik for at tilføje udslipsposition",
  "material": "Materiale",
  "materialPlaceholder": "Begynd at skrive for at søge efter et materiale",
  "table3Message": "Materialet, du har valgt, kræver yderligere oplysninger, hvis der er tale om et stort udslip.\n\nKontrollér, at du har valgt de korrekte værdier for vindhastighed og transportbeholder.",
  "table2Message": "Materialet, du har valgt, kan producere en stor mængde gasser, der er giftige at indånding, når de udledes i vand.\n\nDu kan evt. overveje at bruge følgende materiale(r):\n\n",
  "spillSize": "Udslippets størrelse",
  "small": "Lille",
  "large": "Stor",
  "fireLabel": "Vis brandisoleringszone",
  "weatherLabel": "Aktuelt vejr på udslipspositionen",
  "weatherIntialText": "<br />Opdateres, når der er identificeret en udslipsposition",
  "temperature": "Temperatur",
  "wind": "Vind",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Der er ikke modtaget oplysninger om vejret. Opdater værdier for vindhastighed og tidspunkt for udslip manuelt",
  "windDirection": "Vindretning (blæser mod)",
  "timeOfSpill": "Tidspunkt for udslip",
  "day": "Dag",
  "night": "Nat",
  "windSpeed": "Vindhastighed",
  "low": "Lav",
  "moderate": "Moderat",
  "high": "Høj",
  "transportContainer": "Transportbeholder",
  "rail": "Tanktogvogn",
  "semi": "Tankvogn eller anhænger",
  "mton": "Flertons cylindre",
  "ston": "Flere små cylindre eller enkelt ton-cylinder",
  "ag": "Gødningstank",
  "msm": "Flere små cylindre",
  "bleveLabel": "Vis BLEVE-isolationszone",
  "capacity": "Beholderens kapacitet (liter)",
  "bleveMessage": "For det materiale du har valgt, kan der vises en yderligere evakueringsafstand for BLEVE.\n\nHvis du vil aktivere dette, skal du slå Vis BLEVE-isolationszone til og vælge den rigtige beholderkapacitet.",
  "noPAZoneMessage": "Der er ingen beskyttelsesafstand for dette materiale. Kun de første isolations- og evakueringszoner er beregnet",
  "settingsTitle": "Indstillinger",
  "spillLocationLabel": "Udslippets placering",
  "spillLocationButtonLabel": "Konfigurér indstillinger for udslipsposition",
  "IISettingsLabel": "Første isolationszone",
  "IIButtonLabel": "Konfigurér indstillinger for første isolation",
  "PASettingsLabel": "Beskyttelseszone",
  "PAButtonLabel": "Konfigurér indstillinger for beskyttelsesforanstaltninger",
  "downwindSettingsLabel": "Medvindszone",
  "downwindButtonLabel": "Konfigurer medvindsindstillinger",
  "fireSettingsLabel": "Brandisolationszone",
  "fireButtonLabel": "Konfigurér indstillinger for brandisolation",
  "bleveSettingsLabel": "BLEVE-isolationszone",
  "bleveButtonLabel": "Konfigurer BLEVE-indstillinger",
  "style": "Type",
  "lineStyles": {
    "esriSLSDash": "Streg",
    "esriSLSDashDot": "Streg-prik",
    "esriSLSDashDotDot": "Streg-prik-prik",
    "esriSLSDot": "Prik",
    "esriSLSLongDash": "Lang streg",
    "esriSLSLongDashDot": "Lang streg-prik",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Kort streg",
    "esriSLSShortDashDot": "Kort streg-prik",
    "esriSLSShortDashDotDot": "Kort streg-prik-prik",
    "esriSLSShortDot": "Kort prik",
    "esriSLSSolid": "Udfyldt"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Baglæns",
    "esriSFSCross": "Kryds",
    "esriSFSDiagonalCross": "Diagonalt",
    "esriSFSForwardDiagonal": "Frem",
    "esriSFSHorizontal": "Vandret",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Udfyldt",
    "esriSFSVertical": "Lodret"
  },
  "resultsTitle": "Resultater",
  "publishERGBtn": "Publicér",
  "ERGLayerName": "Navn på publiceret ERG-lag",
  "invalidERGLayerName": "Lagnavnet må kun indeholde alfanumeriske tegn og understregninger",
  "missingERGLayerName": "Du skal indtaste et navn til ERG’en",
  "publishingFailedLayerExists": "Publicering mislykkedes: Du har allerede en featuretjeneste med navnet {0}. Vælg et andet navn.",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opret tjeneste: {0}",
  "unableToCreate": "Kan ikke oprette: {0}",
  "addToDefinition": "Tilføj til definition: {0}",
  "successfullyPublished": "Weblag er oprettet{0}Administrér weblaget",
  "userRole": "Kan ikke oprette tjenesten, fordi brugeren ikke har tilladelser",
  "transparency": "Gennemsigtighed",
  "outline": "Kontur",
  "fill": "Fyld (farve anvendes kun, når typografien er indstillet til massiv)",
  "createERGBtn": "Opret zoner",
  "clearERGBtn": "Ryd",
  "labelFormat": "Etiketformat",
  "helpIconTooltip": "Grænsen mellem små og store udslip er:\nVæsker - 55 gallons (208 liter)\nFaste stoffer - 60 pounds (300 kilogram)",
  "cellWidth": "Cellebredde (x)",
  "cellHeight": "Cellehøjde (y)",
  "invalidNumberMessage": "Den indtastede værdi er ikke gyldig",
  "invalidRangeMessage": "Værdien skal være større end 0",
  "gridAngleInvalidRangeMessage": "Værdi skal være mellem -89,9 og 89,9",
  "formatIconTooltip": "Formatangivelse",
  "setCoordFormat": "Indstil koordinatformat-streng",
  "prefixNumbers": "Tilføj ’+/-’ præfikset til positive og negative tal",
  "cancelBtn": "Annuller",
  "applyBtn": "Anvend",
  "comfirmInputNotation": "Bekræft input-notation",
  "notationsMatch": "notationer matcher dit input. Bekræft, hvilken du vil bruge:",
  "missingLayerNameMessage": "Du skal indtaste et gyldigt lag-navn, før du kan publicere.",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Kontrollér dit input.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader - Breddegrad/Længdegrad",
  "DDLongLatNotation": "Decimalgrader - Længdegrad/Breddegrad",
  "DDMLatLongNotation": "Grader Decimal Minutter - Breddegrad/Længdegrad",
  "DDMLongLatNotation": "Grader Decimal Minutter - Længdegrad/Breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/Længdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Længdegrad/Breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bånd Bogstav",
  "UTMHemNotation": "UTM - Hemisfære (N/S)"
});