define({
  "_widgetLabel": "Pretvarjanje koordinat",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalne stopinje – geografska širina/geografska dolžina",
  "DDLongLatNotation": "Decimalne stopinje – geografska dolžina/geografska širina",
  "DDMLatLongNotation": "Stopinje decimalne minute – geografska širina/geografska dolžina",
  "DDMLongLatNotation": "Stopinje decimalne minute – geografska dolžina/geografska širina",
  "DMSLatLongNotation": "Stopinje Minute Sekunde – geografska širina/geografska dolžina",
  "DMSLongLatNotation": "Stopinje Minute Sekunde – geografska dolžina/geografska širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – črka pasu",
  "UTMHemNotation": "UTM – hemisfera (S/J)",
  "formatInput": "Vhodni format",
  "copyAll": "Kopiraj vse",
  "copySuccessful": "Kopiranje je bilo uspešno",
  "copyFailed": "Kopiranje ni mogoče. Uporabite ctrl+c.",
  "parseCoordinatesError": "Koordinat ni mogoče razčleniti. Preverite svoj vnos.",
  "comfirmInputNotation": "Potrdite zapis vnosa",
  "latLongWarningMessage": "Zaznano je bilo, da ima vhodna koordinata tako predpono kot pripono za vrednosti geografske širine in geografske dolžine, vrnjena je koordinata na osnovi predpone.",
  "inputLabel": "Vnos",
  "outputLabel": "Izhod",
  "cancelButtonLabel": "Prekliči",
  "applyButtonLabel": "Uporabi",
  "posNegPrefixLabel": "Pozitivnim in negativnim številkam dodaj predpono »+/–«",
  "editCoordinateDialogTitle": "Nastavi format niza koordinat",
  "rememberDecisionLabel": "Zapomni si mojo odločitev in me ne sprašuj več.<br/>",
  "coordinateInputLabel": "Vnesite koordinate ali kliknite na karto",
  "zoomLabel": "Povečava",
  "multipleNotationLabel": "Najden je zapis, ki se ujema z vašim vnosom. Potrdite, katerega želite uporabiti:",
  "copyToClipboard": "Kopiraj v odložišče",
  "formatOutput": "Izhodni format",
  "addNewNotation": "Dodaj novi zapis",
  "notationAddedMessage": "Novi zapis dodan",
  "addLabel": "Dodaj",
  "removeCoordinate": "Odstrani koordinato",
  "expandOutput": "Razširi rezultat",
  "latitudeLabel": "g.š.",
  "longitudeLabel": "g.d.",
  "quadrantLabel": "Kvadrant",
  "keyLabel": "Ključ",
  "fifteenDegreeLabel": "Kvadrant 15°",
  "oneDegreeLabel": "Kvadrant 1°",
  "eastingLabel": "Pomik proti vzhodu",
  "northingLabel": "Pomik proti severu",
  "zoneLabel": "Cona",
  "bandLabel": "Pas",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Mrežni kvadrat",
  "hemisphereLabel": "Hemisfera"
});