define({
  "_widgetLabel": "Pretoči",
  "streamControls": "Nadzor pretakanja",
  "streamFilter": "Filter",
  "startStreaming": "Začni pretakanje",
  "stopStreaming": "Ustavi pretakanje",
  "streamLayers": "Pretočni sloji",
  "startStopStream": "Omogoči možnost Ustavi pretakanje ali Začni pretakanje",
  "clearStream": "Omogoči možnost Počisti prejšnja opazovanja",
  "attributeFilter": "Omogoči atributni filter",
  "spatialFilter": "Omogoči prostorski filter",
  "configFilter": "Konfiguriraj atributni filter pretakanja",
  "drawPrevious": "Omogoči možnost Izriši prejšnja opazovanja",
  "addNew": "Dodaj filter",
  "setFilterName": "Nastavi ime filtra",
  "filterNameExists": "Ime filtra obstaja v preglednici!",
  "invalidFilterName": "Ime mora biti beseda, ki vsebuje a–z, A–Z, 0–9 ali _.",
  "noFilterTip": "Noben filter ni konfiguriran",
  "addFilterFailed": "Filtra ni mogoče dodati",
  "filterName": "Ime filtra",
  "limitMapExtent": "Omeji opazovanja na trenutni obseg karte",
  "limitDrawExtent": "Omeji opazovanja na uporabniško določeno območje",
  "newFilter": "Nov filter",
  "filterReadOnly": "Filter, podedovan od spletne karte, je samo za branje"
});