define({
  "serviceUrl": "تعيين عنوان url للخدمة:",
  "minIntSpacingLabel": "أدنى حجم للشبكة",
  "lineOpacityLabel": "معدل شفافية الخط",
  "labelOpacityLabel": "معدل شفافية لافتة التسمية",
  "centerLabelOpacityLabel": "معدل شفافية لافتة تسمية المركز",
  "gridZonePlacementLabel": "موضع لافتة تسمية منطقة الشبكة",
  "verticalLineLabels": "لافتات تسمية الخط الرأسي",
  "styleHeaderLabel": "نمط",
  "indexHeaderLabel": "مُكوِّن الشبكة",
  "colorHeaderLabel": "لون",
  "fontSizeHeaderLabel": "حجم الخط",
  "lineWidthHeaderLabel": "عرض الخط",
  "horizontalLabel": "أفقياً",
  "verticalLabel": "عمودي",
  "upperLeftLabel": "أعلى اليسار",
  "upperRightLabel": "أعلى اليمين",
  "lowerLeftLabel": "أدنى اليسار",
  "lowerRightLabel": "أدنى اليمين",
  "centerLabel": "المركز",
  "errorMessage": "تحتوي صفحة التكوين على أخطاء. يرجى إصلاحها قبل الحفظ.",
  "checkBoxLabel": "عرض الشبكة عند إغلاق عنصر واجهة المستخدم",
  "checkBoxLabelDashboard": "عرض الشبكة",
  "gzd": "متخصص منطقة الشبكة (GZD)",
  "gsid": "100,000 متر تعريف مربع الشبكة (GSID)",
  "grid10k": "10.000 متر خطوط شبكة",
  "grid1k": "1.000 متر خطوط شبكة",
  "grid100m": "100 متر خطوط شبكة",
  "grid10m": "10 أمتار خطوط شبكة",
  "switchBasemap": "تبديل خريطة الأساس"
});