define({
  "chartSettingLabel": "Kaavion asetukset",
  "addNewLabel": "Lisää uusi",
  "generalSettingLabel": "Yleiset asetukset",
  "searchSourceSettingLabel": "Haun lähteen asetukset",
  "layerChooser": {
    "title": "Valitse kaavion lisättävä karttataso",
    "selectPolygonLayerLabel": "Valitse karttataso",
    "selectPolygonLayerHintText": "Vihje: jos määrität useita kaavioita, karttatasojen on oltava samaa geometriatyyppiä",
    "selectRelatedTableLayerLabel": "Valitse karttatasoon liittyvä taulukko",
    "selectRelatedTableLayerHintText": "Vihje: vain numerokenttiä sisältävä taulukot näytetään",
    "errorInSelectingPolygonLayer": "Valitse karttataso, jossa on siihen liittyvä pistekarttataso.",
    "errorInSelectingRelatedLayer": "Valitse kelvollinen karttatasoon liittyvä taulukko tai karttataso.",
    "polygonLayerNotHavingRelationships": "Valitussa karttatasossa ei ole yhtään liittyvää taulukkoa tai karttatasoa."
  },
  "ChartSetting": {
    "sectionTitle": "Osan otsikko",
    "sectionTitleHintText": "Vihje: näytetään osan ylätunnisteen otsikossa",
    "chartTitle": "Kaavion otsikko",
    "chartTitleHintText": "Vihje: näytetään keskitettynä kaavion yläreunassa",
    "chartDescription": "Kuvaus",
    "chartDescriptionHintText": "Vihje: näytetään kaavion alapuolella",
    "chartType": "Kaavion tyyppi",
    "barChart": "Palkkikaavio",
    "pieChart": "Ympyräkaavio",
    "polarChart": "Napakaavio",
    "dataSeriesField": "Aineistosarjakenttä",
    "labelField": "Tunnustekstikenttä",
    "chartColor": "Kaavion väri",
    "singleColor": "Yksittäinen väri",
    "colorByTheme": "Väritä teemoittain",
    "colorByFieldValue": "Väritä kentän arvon mukaan",
    "xAxisTitle": "X-akselin otsikko",
    "xAxisHintText": "Vihje: X-akselin otsikko",
    "yAxisTitle": "Y-akselin otsikko",
    "yAxisHintText": "Vihje: Y-akselin otsikko",
    "fieldColorLabel": "Tunnusteksti",
    "fieldColorColor": "Väri",
    "defaultFieldSelectLabel": "Valitse",
    "errMsgFieldValuesNotFound": "Valitun kentän arvoja ei löydy",
    "errMsgSectionTitle": "Anna osan otsikko",
    "errMsgFieldByValue": "Valitse kentän arvo",
    "settingTabTitle": "Asetus",
    "layoutTabTitle": "Asettelu",
    "polarChartSelectFieldsHintText": "Vihje: valitse kentät napakaavion luomista varten",
    "visibilityText": "Näkyvyys",
    "fieldNameText": "Kentän nimi",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Valitse vähintään kolme kenttää napakaavion luomista varten",
    "polarChartPolygonFillLabel": "Täyttöalue",
    "polarChartPolygonFillHintText": "Vihje: näytä aluekohteilla täytetty napakaavio valitsemalla valintaruutu",
    "viewLayoutLabel": "Asettelu",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Levä",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Autiomaa",
      "themeDistinctive": "Erikoislaatuinen",
      "themeDollar": "Dollari",
      "themeGrasshopper": "Heinäsirkka",
      "themeGrasslands": "Ruohotasanko",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmonia",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minttu",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Kosteikko",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Yleiset asetukset",
    "locationSymbolLabel": "Graafinen sijainnin symboli",
    "locationSymbolHintText": "Vihje: käytetään osoitteen symbolin näyttämiseen ja sijainnin napsauttamiseen",
    "refreshIntervalLabel": "Päivitysväli",
    "refreshIntervalHintText": "Vihje: Käytetään kaavioiden päivittämiseen tämän aikavälin perusteella. Määritä arvo väliltä 1–1 440 minuuttia",
    "errMsgRefreshInterval": "Määritä päivitysväliksi 0–1 440 minuuttia",
    "symbolPickerPreviewText": "Esikatselu:",
    "showToolToSelectLabel": "Määritä sijainti -painike",
    "showToolToSelectHintText": "Vinkki: Ota käyttöön painike sijainnin määrittämiseksi kartalla sen sijaan, että sijainti määritetään aina karttaa napsautettaessa"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Hakulähteen asetukset",
    "searchSourceSettingTitle": "Hakulähteen asetukset",
    "searchSourceSettingTitleHintText": "Lisää ja määritä geokoodauspalveluja tai kohdekarttatasoja haun lähteiksi. Nämä määritetyt lähteet määrittävät, mitä hakuruudussa voi hakea",
    "addSearchSourceLabel": "Lisää haun lähde",
    "featureLayerLabel": "Kohdekarttataso",
    "geocoderLabel": "Geokooderi",
    "nameTitle": "Nimi",
    "generalSettingLabel": "Yleinen asetus",
    "allPlaceholderLabel": "Paikkamerkkiteksti haulle kaikkialta:",
    "allPlaceholderHintText": "Vinkki: Anna teksti, joka näytetään paikkamerkkinä kaikista karttatasoista ja geokooderista haettaessa",
    "generalSettingCheckboxLabel": "Näytä löydetyn kohteen tai sijainnin ponnahdusikkuna",
    "countryCode": "Maa- tai aluekoodit",
    "countryCodeEg": "esim. ",
    "countryCodeHint": "Jos jätät tämän arvon tyhjäksi, ohjelma etsii kaikista maista ja kaikilta alueilta",
    "questionMark": "tulisi käyttää?",
    "searchInCurrentMapExtent": "Etsi vain nykyisestä karttalaajuudesta",
    "zoomScale": "Tarkennustaso",
    "locatorUrl": "Geokooderin URL-osoite",
    "locatorName": "Geokooderin nimi",
    "locatorExample": "Esimerkki",
    "locatorWarning": "Tätä geokoodauspalvelun versiota ei tueta. Pienoisohjelma tukee geokoodauspalvelua 10.0 ja sitä uudempia versioita.",
    "locatorTips": "Ehdotukset eivät ole käytettävissä, koska geokoodauspalvelu ei tue ehdotustoimintoa.",
    "layerSource": "Karttatason lähde",
    "setLayerSource": "Määritä karttatason lähde",
    "setGeocoderURL": "Määritä geokooderin URL-osoite",
    "searchLayerTips": "Ehdotukset eivät ole käytettävissä, koska kohdepalvelu ei tue sivutustoimintoa.",
    "placeholder": "Muuttujan teksti",
    "searchFields": "Hakukentät",
    "displayField": "Näyttökenttä",
    "exactMatch": "Tarkka vastine",
    "maxSuggestions": "Ehdotusten enimmäismäärä",
    "maxResults": "Tulosten enimmäismäärä",
    "enableLocalSearch": "Ota käyttöön paikallinen haku",
    "minScale": "Vähimmäismittakaava",
    "minScaleHint": "Kun kartan mittakaava on suurempi kuin tämä mittakaava, käytetään paikallista hakua",
    "radius": "Säde",
    "radiusHint": "Määrittää nykyisen kartan keskikohdan ympärillä olevan alueen säteen. Säteen avulla arvioidaan geokoodausehdokkaiden sijoitusta, jotta sijaintia lähinnä olevat ehdokkaat palautetaan ensin",
    "meters": "Metriä",
    "setSearchFields": "Määritä hakukentät",
    "set": "Aseta",
    "fieldName": "Nimi",
    "invalidUrlTip": "Syötetty URL-osoite ${URL} on virheellinen, tai se ei ole käytettävissä."
  }
});