define({
  "_widgetLabel": "Guida alle emergenze",
  "ergMainPageTitle": "Basata sulla Guida alle emergenze 2016",
  "coordInputLabelStart": "Posizione della perdita (DD)",
  "coordInputLabel": "Posizione della perdita",
  "addPointToolTip": "Aggiungi posizione della perdita",
  "drawPointToolTip": "Fare clic per aggiungere posizione della perdita",
  "material": "Materiale",
  "materialPlaceholder": "Iniziare a digitare per cercare un materiale",
  "table3Message": "Il materiale selezionato richiede informazioni aggiuntive se si sta affrontando una perdita di dimensioni notevoli.\n\nVerificare che siano stati selezionati i valori corretto per la velocità del vento e il contenitore di trasporto.",
  "table2Message": "Il materiale selezionato può produrre grandi quantità di gas tossici in caso di contatto con l’acqua.\n\nSi consiglia di considerare l'utilizzo dei seguenti materiali:\n\n",
  "spillSize": "Dimensione della perdita",
  "small": "Piccolo",
  "large": "Grande",
  "fireLabel": "Mostra zona di isolamento antincendio",
  "weatherLabel": "Condizioni meteo attuali nella posizione della perdita",
  "weatherIntialText": "<br />Aggiornate una volta identificata la posizione della perdita",
  "temperature": "Temperatura",
  "wind": "Vento",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informazioni meteorologiche non ottenute. Aggiornare i valori di velocità del vento e durata della perdita manualmente.",
  "windDirection": "Direzione del vento (soffia verso)",
  "timeOfSpill": "Durata della perdita",
  "day": "Giorno",
  "night": "Notte",
  "windSpeed": "Velocità vento",
  "low": "Bassa",
  "moderate": "Moderato",
  "high": "Alta",
  "transportContainer": "Contenitore di trasporto",
  "rail": "Vagone cisterna",
  "semi": "Autocisterna o rimorchio",
  "mton": "Vari fusti da una tonnellata",
  "ston": "Vari fusti di piccole dimensioni o un unico fusto da una tonnellata",
  "ag": "Cisterne per uso agricolo",
  "msm": "Vari fusti di piccole dimensioni",
  "bleveLabel": "Mostra zona di isolamento BLEVE",
  "capacity": "Capacità del contenitore (litri)",
  "bleveMessage": "Per il materiale selezionato è possibile mostrare un’ulteriore distanza di isolamento BLEVE.\n\nPer abilitarla, attivare la funzione Mostra zona di isolamento BLEVE e selezionare la capacità del contenitore.",
  "noPAZoneMessage": "Non sono presenti distanze per la zona di azione protettiva per questo materiale. Sono state calcolate soltanto le zone di evacuazione e di isolamento iniziale.",
  "settingsTitle": "Impostazioni",
  "spillLocationLabel": "Posizione della perdita",
  "spillLocationButtonLabel": "Configurare le impostazioni della posizione della perdita",
  "IISettingsLabel": "Zona di isolamento iniziale",
  "IIButtonLabel": "Configurare le impostazioni di isolamento iniziale",
  "PASettingsLabel": "Zona di azione protettiva",
  "PAButtonLabel": "Configurare le impostazioni dell’azione protettiva",
  "downwindSettingsLabel": "Zona sottovento",
  "downwindButtonLabel": "Configurare le impostazioni della zona sottovento",
  "fireSettingsLabel": "Zona di isolamento antincendio",
  "fireButtonLabel": "Configurare le impostazioni dell’isolamento antincendio",
  "bleveSettingsLabel": "Zona di isolamento BLEVE",
  "bleveButtonLabel": "Configurare le impostazioni dell’isolamento BLEVE",
  "style": "Stile",
  "lineStyles": {
    "esriSLSDash": "Trattino",
    "esriSLSDashDot": "Trattino punto",
    "esriSLSDashDotDot": "Trattino punto punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Trattino lungo",
    "esriSLSLongDashDot": "Trattino lungo punto",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trattino corto",
    "esriSLSShortDashDot": "Trattino corto punto",
    "esriSLSShortDashDotDot": "Trattino corto punto punto",
    "esriSLSShortDot": "Punto corto",
    "esriSLSSolid": "Tinta unita"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Indietro",
    "esriSFSCross": "Croce",
    "esriSFSDiagonalCross": "Diagonale",
    "esriSFSForwardDiagonal": "Avanti",
    "esriSFSHorizontal": "Orizzontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Tinta unita",
    "esriSFSVertical": "Verticale"
  },
  "resultsTitle": "Risultati",
  "publishERGBtn": "Pubblica",
  "ERGLayerName": "Nome del layer ERG pubblicato",
  "invalidERGLayerName": "Il nome del layer deve contenere soltanto caratteri alfanumerici e sottolineature",
  "missingERGLayerName": "È necessario inserire un nome per il layer ERG",
  "publishingFailedLayerExists": "Pubblicazione non riuscita: esiste già un Feature Service chiamato {0}. Scegliere un altro nome.",
  "checkService": "Verifica servizio: {0}",
  "createService": "Crea servizio: {0}",
  "unableToCreate": "Creazione non riuscita: {0}",
  "addToDefinition": "Aggiungi a definizione: {0}",
  "successfullyPublished": "Web Layer pubblicato con successo{0}Gestisci Web Layer",
  "userRole": "Impossibile creare il servizio poiché l’utente non dispone delle autorizzazioni.",
  "transparency": "Trasparenza",
  "outline": "Bordo",
  "fill": "Riempimento (Il colore si applica solo quando lo stile è impostato su tinta unita)",
  "createERGBtn": "Crea zone",
  "clearERGBtn": "Cancella",
  "labelFormat": "Formato etichetta",
  "helpIconTooltip": "La soglia tra perdite di grandi e piccole dimensioni è:\nLiquidi - 55 galloni (208 litri)\nSolidi - 60 libbre (300 chilogrammi)",
  "cellWidth": "Larghezza cella (x)",
  "cellHeight": "Altezza cella (x)",
  "invalidNumberMessage": "Il valore immesso non è valido",
  "invalidRangeMessage": "Il valore deve essere maggiore di 0",
  "gridAngleInvalidRangeMessage": "Il valore deve essere compreso tra -89,9 e 89,9",
  "formatIconTooltip": "Input formato",
  "setCoordFormat": "Imposta stringa di formato coordinata",
  "prefixNumbers": "Aggiungere il prefisso '+/-' ai numeri positivi e negativi",
  "cancelBtn": "Annulla",
  "applyBtn": "Applica",
  "comfirmInputNotation": "Confermare l'input annotato.",
  "notationsMatch": "Notazioni corrispondenti all'input. Confermare quale si desidera utilizzare:",
  "missingLayerNameMessage": "È necessario inserire un nome valido per il layer prima della pubblicazione",
  "parseCoordinatesError": "Impossibile analizzare le coordinate. Controllare l'input.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Gradi decimali - Latitudine/Longitudine",
  "DDLongLatNotation": "Gradi decimali - Longitudine/Latitudine",
  "DDMLatLongNotation": "(DDM) Degrees Decimal Minutes - Latitude/Longitude",
  "DDMLongLatNotation": "(DDM) Degrees Decimal Minutes - Longitude/Latitude",
  "DMSLatLongNotation": "(DDS) Degrees Minutes Seconds - Latitude/Longitude",
  "DMSLongLatNotation": "(DDS) Degrees Minutes Seconds - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisphere (N/S)"
});