define({
  "symbolologyTabLabel": "Konfiguruj symbolizację",
  "facilitiesDescription": "Warstwy placówek",
  "demographicsDescription": "Warstwa danych demograficznych",
  "settingsTitle": "Parametry",
  "spillLocationLabel": "Lokalizacja wycieku",
  "spillLocationButtonLabel": "Konfiguruj ustawienia lokalizacji wycieku",
  "IISettingsLabel": "Strefa zagrożenia",
  "IIButtonLabel": "Konfiguruj ustawienia strefy zagrożenia",
  "PASettingsLabel": "Strefa działań ochronnych",
  "PAButtonLabel": "Konfiguruj ustawienia strefy działań ochronnych",
  "downwindSettingsLabel": "Strefa w kierunku wiatru",
  "downwindButtonLabel": "Konfiguruj ustawienia kierunku wiatru",
  "fireSettingsLabel": "Pożarowa strefa bezpieczeństwa",
  "fireButtonLabel": "Konfiguruj ustawienia pożarowej strefy bezpieczeństwa",
  "bleveSettingsLabel": "Strefa bezpieczeństwa BLEVE",
  "bleveButtonLabel": "Konfiguruj ustawienia strefy BLEVE",
  "transparency": "Przezroczystość",
  "outline": "Obrys",
  "fill": "Wypełnienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pełny)",
  "style": "Nadaj styl",
  "lineStyles": {
    "esriSLSDash": "Przerywana",
    "esriSLSDashDot": "Kreska-kropka",
    "esriSLSDashDotDot": "Kreska-kropka-kropka",
    "esriSLSDot": "Kropka",
    "esriSLSLongDash": "Długa kreska",
    "esriSLSLongDashDot": "Długa kreska-kropka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Krótka kreska",
    "esriSLSShortDashDot": "Krótka kreska-kropka",
    "esriSLSShortDashDotDot": "Krótka kreska-kropka-kropka",
    "esriSLSShortDot": "Krótka kropka",
    "esriSLSSolid": "Stały"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Cofnij",
    "esriSFSCross": "Krzyż",
    "esriSFSDiagonalCross": "Po przekątnej",
    "esriSFSForwardDiagonal": "Do przodu",
    "esriSFSHorizontal": "Poziomo",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Stały",
    "esriSFSVertical": "Pionowo"
  }
});