define({
  "add": "जोड़ने के लिए क्लिक करें",
  "title": "शीर्षक",
  "placeholderBookmarkName": "बुकमार्क का नाम",
  "ok": "ठीक है",
  "cancel": "रद्द करें",
  "warning": "कृपया संपादन पूरा करें!",
  "edit": "बुकमार्क को संपादित करें",
  "errorNameExist": "बुकमार्क मौजूद है!",
  "errorNameNull": "अमान्य बुकमार्क नाम!",
  "addBookmark": "नया बदलाव करें",
  "thumbnail": "थंबनेल",
  "thumbnailHint": "अपडेट करने के लिए छवि पर क्लिक करें",
  "displayBookmarksAs": "बुकमार्क इस रूप में प्रदर्शित करें",
  "cards": "कार्ड",
  "list": "सूची",
  "cardsTips": "कार्ड दृश्य",
  "listTips": "सूची दृश्य",
  "makeAsDefault": "डिफ़ॉल्ट बनाएँ",
  "default": "डिफॉल्ट",
  "editable": "विजेट में बुकमार्क जोड़ने दें।",
  "alwaysSync": "वेब मानचित्र से बुकमार्क प्रदर्शित करें",
  "configCustom": "कस्टम बुकमार्क प्रदर्शित करें",
  "import": "इंपोर्ट करें",
  "create": "बनाएँ",
  "importTitle": "बुकमार्क आयात करें",
  "importFromWeb": "वर्तमान वेब मानचित्र से बुकमार्क आयात करें",
  "selectAll": "सभी का चयन करें",
  "noBookmarkInConfig": "बुकमार्क जोड़ने के लिए â€œImportâ€ या â€œCreate Newâ€ पर क्लिक करें।",
  "noBookmarkInWebMap": "मानचित्र में कोई बुकमार्क कॉन्फ़िगर नहीं किया गया है।",
  "extent": "सीमा",
  "saveExtent": "मानचित्र की सीमा इस बुकमार्क तक सहेजें",
  "savelayers": "लेयर दृश्यता सहेजें",
  "withVisibility": "लेयर दृश्यता के साथ",
  "bookmark": "बुकमार्क",
  "addBtn": "जोड़ें",
  "deleteBtn": "हटाएँ",
  "editBtn": "संपादित करें",
  "dragReorderTip": "पकड़कर रखें और रिकॉर्डर तक खींचें",
  "deleteBtnTip": "बुकमार्क हटाएँ",
  "editBtnTip": "बुकमार्क संपादित करें"
});