define({
  "labelBookmarkName": "Adicionar a vista atual aos marcadores",
  "labelPlay": "Reproduzir todos",
  "labelStop": "Parar",
  "labelDelete": "Eliminar",
  "placeholderBookmarkName": "Nome do marcador",
  "errorNameExist": "O Marcador existe!",
  "errorNameNull": "Nome de marcador inválido!",
  "editTip": "Editar marcadores",
  "exitEditTip": "Sair do modo de edição",
  "syncTip": "Sincronizar",
  "cardsTips": "Vista de Grelha",
  "listTips": "Vista de Lista",
  "addBtn": "Adicionar",
  "deleteBtn": "Excluir",
  "changeThumbnailTip": "Alterar miniatura",
  "dragReorderTip": "Manter premido e arrastar para reordenar",
  "deleteBtnTip": "Eliminar o marcador",
  "editBtnTip": "Editar o marcador",
  "withVisibility": "Com visibilidade de camada",
  "searchBookmark": "Pesquisar",
  "bookmarksFromConfig": "Marcadores preconfigurados",
  "bookmarksFromCache": "Marcadores locais temporários",
  "notice": "Aviso",
  "changeNoticeTips": "As alterações serão guardadas apenas na cache do seu navegador. A sincronização entre o widget e a respetiva configuração é desligada após efetuar modificações.",
  "syncNoticeTips": "Esta ação irá apagar as suas modificações e restaurar os marcadores configurados.",
  "dontShowAgain": "Não voltar a exibir",
  "saveVisibility": "Guardar a visibilidade da camada",
  "_widgetLabel": "Marcador"
});