define({
  "settings": "Innstillinger",
  "titleSettings": "Tekstinnstillinger",
  "imageSettings": "Bildeinnstillinger",
  "backgroundColor": "Bakgrunnsfarge",
  "alignment": "Justering",
  "textSize": "Tekststørrelse",
  "textColor": "Tekstfarge",
  "dataSource": "Datakilde",
  "chartSettings": "Diagraminnstillinger",
  "data": "Data",
  "dataLabels": "Dataetikketter",
  "displayMode": "Visningsmodus",
  "featureOption": "Vis verdier geoobjekt for geoobjekt",
  "categoryOption": "Vis verdier etter kategori",
  "countOption": "Vis antall geoobjekter etter kategori",
  "fieldOption": "Vis attributtverdier som diagrammer",
  "categoryField": "Kategorifelt",
  "labelField": "Påskriftfelt",
  "valueFields": "Verdifelter",
  "operation": "Operasjon",
  "sumOption": "Summer",
  "averageOption": "Gjennomsnitt",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Datoformat",
  "decimalPlaces": "Desimaler",
  "prefix": "Prefiks",
  "suffix": "Suffiks",
  "dataType": "Datatype",
  "featureCount": "Geoobjektantall",
  "fieldStatistics": "Feltstatistikk",
  "display": "Vis",
  "chartColor": "Diagramfarge",
  "horizontalAxis": "Horisontal akse",
  "verticalAxis": "Vertikal akse",
  "legend": "Tegnforklaring",
  "position": "Posisjon",
  "top": "Topp",
  "bottom": "Bunn",
  "useDataSourceSelection": "Bruk utvalg",
  "dataSourceFilterByExtent": "Filtrer etter utstrekning",
  "changeTemplate": "Endre mal",
  "numberSettings": "Tallinnstillinger",
  "gaugeSettings": "Målerinnstillinger",
  "indicators": "Indikatorer",
  "ifValue": "Verdien Hvis",
  "and": "og",
  "numberOperatorIsLessThan": "er mindre enn",
  "numberOperatorIsGreaterThan": "er større enn",
  "numberOperatorIsBetween": "er mellom",
  "numberOperatorIsEqual": "er lik",
  "numberOperatorIsNotEqual": "er ikke lik",
  "then": "Så",
  "ratio": "Forhold",
  "trueValue": "Verdien Sann",
  "changeValueColor": "endre verdifarge til",
  "changeGaugeColor": "endre målerfarge til",
  "setIndicatorIcon": "angi indikatorikon som",
  "icons": "Ikoner",
  "style": "Stil",
  "placement": "Plassering",
  "left": "Venstre",
  "replace": "Erstatt",
  "right": "Høyre",
  "color": "Farge",
  "categoryExists": "Kategorien finnes",
  "comboxHint": "Skriv inn eller velg en",
  "comboxDisableInputHint": "Velg én",
  "sortBy": "Sorter etter",
  "labelAxis": "Etikett",
  "valueAxis": "Verdi",
  "minPeriod": "Minimumsperiode",
  "automatic": "Automatisk",
  "periodsWithOutRecords": "Perioder uten poster",
  "nullValue": "Null verdi",
  "calculatedAsZero": "Beregnet som null",
  "ignored": "Ignorert",
  "maxCategories": "Maksimalt antall kategorier",
  "useLayerSymbology": "Bruk lagens symboler",
  "hollowsize": "Hulhetsstørrelse",
  "splitField": "Del felt",
  "parsingperiodTip": "Kan ikke beregne. For mange tidsintervaller på grunn av den korte analyseperioden.",
  "manyCategoryTip": "Kan ikke vise diagram. For mange kategorier.",
  "setColor": "Angi farge",
  "setTheColorOf": "Angi deretter fargen for",
  "setTheColorAs": "Angi deretter fargen som",
  "ifStr": "Hvis",
  "as": "som",
  "is": "er",
  "isNot": "er ikke",
  "barCluster": "stolpediagramklynge",
  "individualBar": "enkelt stolpediagram",
  "allOthers": "Alle andre",
  "category": "Kategori",
  "indicatorSum": "SUM",
  "indicatorAve": "MIDDEL",
  "indicatorMax": "MAKS.",
  "indicatorMin": "MIN.",
  "setCorrectyIndicatorTip": "Angi indikatorene på riktig måte.",
  "dataRange": "Dataområde",
  "targetValue": "Målverdi",
  "currentValue": "Gjeldende verdi",
  "gaugeColor": "Målerfarge",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Vis verdi i",
  "noData": "Ingen data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Advarsel",
  "noSettingWaring1": "Klikk på et element for å angi egenskaper for elementet.",
  "noSettingWaring2": "Dra for å endre størrelsen eller rekkefølgen for et element.",
  "donNotShowAgain": "Ikke vis igjen",
  "changeTemplateWarning": "Dette fjerner alle innstillinger og åpner en ny tom mal.",
  "requiredFieldWarning": "Denne verdien er obligatorisk:",
  "dataSourceNotSet": "Angi datakilde.",
  "addIndicatorTip": "Legg til en indikator",
  "chooseTemplatePopupTitle": "Velg en mal",
  "filterExtentTipWithaTag": "Du kan deaktivere filteret med <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Ekstra datakilde</a> i Attributt-fanen.",
  "filterExtentTip": "Du kan deaktivere filteret med Ekstra datakilde i Attributt-fanen.",
  "customColorByCategory": "Egendefinert farge etter kategori",
  "randomColor": "Tilfeldig farge",
  "valueString": "Verdi",
  "fieldString": "Felt",
  "includeThresholdValue": "Inkluder terskelverdi",
  "percentage": "Prosentandel",
  "colorSchema": "Fargevalg",
  "addCategory": "Legg til kategori",
  "clickToEdit": "Klikk for å redigere",
  "nullText": "Null",
  "others": "Andre",
  "stringsInTemplate": {
    "name_number": "Tall",
    "name_gauge": "Måler",
    "name_vertical_gauge": "Vertikal måler",
    "name_horizontal_gauge": "Horisontal måler",
    "name_pie": "Sektor",
    "name_donut": "Hjuldiagram",
    "name_bar": "Linjal",
    "name_stacked_bar": "Stablet liggende stolpediagram",
    "name_percentage_stacked_bar": "Stablet liggende stolpediagram med prosentfordeling",
    "name_column": "Søyle",
    "name_stacked_column": "Stablet liggende søylediagram",
    "name_percentage_stacked_column": "Stablet liggende søylediagram med prosentfordeling",
    "name_line": "Linje",
    "name_area": "Areal",
    "name_stacked_area": "Stablet arealdiagram",
    "name_percentage_stacked_area": "Stablet arealdiagram med prosentfordeling",
    "titleOfTheInfographic": "TITTEL PÅ INFOGRAFIKK",
    "description": "Beskrivelse: tilleggsinformasjon om denne infografikken."
  }
});