define({
  "symbolologyTabLabel": "Konfigurer symboler",
  "facilitiesDescription": "Fasilitetslag",
  "demographicsDescription": "Demografilag",
  "settingsTitle": "Innstillinger",
  "spillLocationLabel": "Utslippssted",
  "spillLocationButtonLabel": "Konfigurer innstillinger for utslippssted",
  "IISettingsLabel": "Opprinnelig isolasjonssone",
  "IIButtonLabel": "Konfigurer innstillinger for opprinnelig isolasjonssone",
  "PASettingsLabel": "Sone for beskyttelsestiltak",
  "PAButtonLabel": "Konfigurer innstillinger for beskyttelsestiltak",
  "downwindSettingsLabel": "Medvindssone",
  "downwindButtonLabel": "Konfigurer innstillinger for medvind",
  "fireSettingsLabel": "Brannisoleringssone",
  "fireButtonLabel": "Konfigurer innstillinger for brannisolering",
  "bleveSettingsLabel": "BLEVE-isoleringssone",
  "bleveButtonLabel": "Konfigurer innstillinger for BLEVE",
  "transparency": "Gjennomsiktighet",
  "outline": "Omriss",
  "fill": "Fyll (farge brukes bare når heldekkende er valgt som stil)",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Strek",
    "esriSLSDashDot": "Strek prikk",
    "esriSLSDashDotDot": "Strek prikk prikk",
    "esriSLSDot": "Prikk",
    "esriSLSLongDash": "Lang strek",
    "esriSLSLongDashDot": "Lang strek-prikk",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort strek",
    "esriSLSShortDashDot": "Kort strek-prikk",
    "esriSLSShortDashDotDot": "Kort strek-prikk-prikk",
    "esriSLSShortDot": "Kort prikk",
    "esriSLSSolid": "Heltrukken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakover",
    "esriSFSCross": "Kryss",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Fremover",
    "esriSFSHorizontal": "Vannrett",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Heltrukken",
    "esriSFSVertical": "Loddrett"
  }
});