define({
  "_widgetLabel": "Σχεδιαστής καταλληλότητας",
  "general": {
    "clear": "Εκκαθάριση",
    "cancel": "Ακύρωση",
    "save": "Εκτέλεση",
    "saveAs": "Εξαγωγή"
  },
  "saveModel": {
    "save": "Εξαγωγή",
    "title": "Τίτλος: ",
    "summary": "Σύνοψη: ",
    "description": "Περιγραφή: ",
    "tags": "Ετικέτες: ",
    "folder": "Φάκελος: ",
    "homeFolderPattern": "{username} (Αρχικός)",
    "failed": "Η εξαγωγή απέτυχε."
  },
  "util": {
    "colorRamp": {
      "1": "Εξαιρετικά χαμηλή",
      "2": "Πολύ χαμηλή",
      "3": "Χαμηλή",
      "4": "Μεσαία προς χαμηλή",
      "5": "Μεσαία",
      "6": "Μεσαία προς υψηλή",
      "7": "Υψηλή",
      "8": "Πολύ υψηλή",
      "9": "Εξαιρετικά υψηλή",
      "low": "Χαμηλή",
      "high": "Υψηλή",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Αντιστροφή"
    }
  },
  "wro": {
    "caption": "Σχεδιαστής καταλληλότητας",
    "browsePrompt": "Weighted overlay service",
    "selectLayersCaption": "Επιλογή θεματικών επιπέδων",
    "selectLayers": "Θεμ. επίπ.",
    "designModelCaption": "Σχεδίαση μοντέλου",
    "designModel": "Σχεδίαση μοντέλου",
    "transparency": "Διαφάνεια",
    "visible": "Ορατό",
    "total": "Συνολικά",
    "unableToLoad": "Δεν είναι δυνατή η φόρτωση του μοντέλου.",
    "projectNotOpen": "Δεν υπάρχει ανοιχτό έργο.",
    "readMore": "Διαβάστε περισσότερα",
    "validation": {
      "validating": "Επικύρωση...",
      "invalidItemCaption": "Προειδοποίηση Weighted overlay service",
      "notAnImageService": "Αυτό το αντικείμενο δεν είναι Image service.",
      "notAWroService": "Αυτό το αντικείμενο δεν είναι Weighted overlay service.",
      "undefinedUrl": "Δεν έχει οριστεί το URL αυτού του αντικειμένου.",
      "inaccessible": "Η υπηρεσία δεν είναι προσβάσιμη.",
      "generalError": "Δεν είναι δυνατό το άνοιγμα του αντικειμένου.",
      "missingFieldPattern": "Το {field} είναι απαιτούμενο πεδίο",
      "notAllowRasterFunction": "Το allowRasterFunction πρέπει να οριστεί σε τιμή true",
      "notNearestResampling": "Το defaultResamplingMethod πρέπει να είναι Πλησιέστερο",
      "notIsWeightedOverlayProp": "Η βασική ιδιότητα IsWeightedOverlay πρέπει να οριστεί σε τιμή true",
      "invalidLink": "Το URL δεν είναι έγκυρο. Το άνοιγμα της τοποθεσίας απέτυχε για το επιλεγμένο θεματικό επίπεδο.",
      "unexpectedError": "Προέκυψε μη αναμενόμενη κατάσταση.",
      "rangeMessage": "Η τιμή πρέπει να βρίσκεται μεταξύ ${0} και ${1}",
      "rangeMessage100": "Η τιμή πρέπει να βρίσκεται μεταξύ 0 και 100",
      "maxLayers": "Επιτρέπονται μέχρι ${0} θεματικά επίπεδα ανά υπηρεσία, πρέπει πρώτα να καταργήσετε ένα θεματικό επίπεδο πριν προσθέσετε ένα νέο.",
      "notFound": "Το θεματικό επίπεδο ${0} δεν βρέθηκε στο weighted overlay service",
      "wroServiceNotDefined": "Δεν έχει οριστεί weighted overlay service για το μοντέλο.",
      "overlayLayerOutputInvalid": "Η τιμή εξόδου των [${0}] ευρών νέας αντιστοίχισης [${1}] του θεματικού επιπέδου υπέρθεσης λείπει ή δεν είναι έγκυρη",
      "overlayLayerInputInvalid": "Η ελάχιστη/μέγιστη τιμή εισόδου των [${0}] ευρών νέας αντιστοίχισης [${1}] του θεματικού επιπέδου υπέρθεσης λείπει ή δεν είναι έγκυρη",
      "overlayLayerRangesMissing": "Από το θεματικό επίπεδο υπέρθεσης [${0}] λείπουν τα εύρη νέας αντιστοίχισης",
      "overlayLayerWeight": "Οι δείκτες στάθμισης του θεματικού επιπέδου υπέρθεσης πρέπει να έχουν άθροισμα 100",
      "overlayLayerRequired": "Απαιτείται τουλάχιστον ένα θεματικό επίπεδο υπέρθεσης",
      "overlayLayerNotDefined": "Δεν έχει οριστεί θεματικό επίπεδο υπέρθεσης",
      "requiresColormap": "Αυτή η λειτουργία raster απαιτεί έναν έγχρωμο χάρτη, αλλά το μοντέλο δεν έχει έγκυρο ορισμό έγχρωμου χάρτη",
      "createModelError": "Σφάλμα κατά τη δημιουργία του μοντέλου",
      "invalidModel": "Το μοντέλο δεν είναι έγκυρο",
      "imageServiceNotDefined": "Δεν έχει οριστεί το θεματικό επίπεδο Image service",
      "imageLayerNotDefined": "Δεν έχει οριστεί το θεματικό επίπεδο Image service",
      "histogramNotDefined": "Δεν έχει οριστεί λειτουργία ιστογράμματος σταθμισμένης υπέρθεσης."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Πράσινο κίτρινο κόκκινο",
      "Red Yellow Green": "Κόκκινο κίτρινο πράσινο",
      "Yellow to Dark Red": "Κίτρινο προς κόκκινο σκούρο",
      "Dark Red to Yellow": "Κόκκινο σκούρο προς κίτρινο",
      "Light Gray to Dark Gray": "Γκρι ανοιχτό προς γκρι σκούρο",
      "Dark Gray to Light Gray": "Γκρι σκούρο προς γκρι ανοιχτό",
      "Light Brown to Dark Brown": "Καφέ ανοιχτό προς καφέ σκούρο",
      "Dark Brown to Light Brown": "Καφέ σκούρο προς καφέ ανοιχτό",
      "Full Spectrum - Bright Red to Blue": "Πλήρες φάσμα - Κόκκινο φωτεινό προς μπλε",
      "Full Spectrum - Bright Blue to Red": "Πλήρες φάσμα - Μπλε φωτεινό προς κόκκινο",
      "Partial Spectrum - Yellow to Blue": "Μερικό φάσμα - Κίτρινο προς μπλε",
      "Partial Spectrum - Blue to Yellow": "Μερικό φάσμα - Μπλε προς κίτρινο",
      "Yellow-Green to Dark Blue": "Κίτρινο-πράσινο προς μπλε σκούρο",
      "Dark Blue to Yellow-Green": "Μπλε σκούρο προς κίτρινο-πράσινο",
      "Cold to Hot Diverging": "Ψυχρό προς θερμό αποκλίνον",
      "Hot to Cold Diverging": "Θερμό προς ψυχρό αποκλίνον",
      "Surface - Low to High": "Επιφάνεια - Χαμηλό προς υψηλό",
      "Surface - High to Low": "Επιφάνεια - Υψηλό προς χαμηλό"
    }
  },
  "tabs": {
    "layers": "Θεματικά επίπεδα",
    "model": "Μοντέλο",
    "chart": "Γράφημα"
  },
  "chart": {
    "prompt": "Στοιχεία",
    "working": "Ενημέρωση...",
    "polygonTool": "Σχεδίαση πολυγώνου",
    "freehandPolygonTool": "Σχεδίαση πολυγώνου ελεύθερης σχεδίασης",
    "selectTool": "Επιλογή από θεματικό επίπεδο",
    "panTool": "Μετατόπιση",
    "clearButton": "Απαλοιφή",
    "noModelLayer": "Κανένα μοντέλο.",
    "noSubjectLayers": "Ο χάρτης σας δεν έχει θεματικά επίπεδα πολυγώνων.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});