define({
  "symbolologyTabLabel": "Configurar simbología",
  "facilitiesDescription": "Capas de instalaciones",
  "demographicsDescription": "Capa de demografía",
  "settingsTitle": "Ajustes",
  "spillLocationLabel": "Ubicación de vertido",
  "spillLocationButtonLabel": "Configurar ajustes de ubicación de vertido",
  "IISettingsLabel": "Zona de aislamiento inicial",
  "IIButtonLabel": "Configurar ajustes de aislamiento inicial",
  "PASettingsLabel": "Zona de acción protectora",
  "PAButtonLabel": "Configurar ajustes de acción protectora",
  "downwindSettingsLabel": "Zona de sotavento",
  "downwindButtonLabel": "Configurar los ajustes de sotavento",
  "fireSettingsLabel": "Zona de aislamiento de incendios",
  "fireButtonLabel": "Configurar ajustes de aislamiento de incendios",
  "bleveSettingsLabel": "Zona de aislamiento BLEVE",
  "bleveButtonLabel": "Configurar ajustes de BLEVE",
  "transparency": "Transparencia",
  "outline": "Lista",
  "fill": "Relleno (el color solo se aplica si el estilo es sólido)",
  "style": "Estilo",
  "lineStyles": {
    "esriSLSDash": "Guion",
    "esriSLSDashDot": "Guion Punto",
    "esriSLSDashDotDot": "Guion Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Guion largo",
    "esriSLSLongDashDot": "Guion largo, Punto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Guion corto",
    "esriSLSShortDashDot": "Guion corto Punto",
    "esriSLSShortDashDotDot": "Guion corto Punto Punto",
    "esriSLSShortDot": "Corto Punto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atrás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Hacia delante",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  }
});