define({
  "labelBookmarkName": "הוסף את התצוגה הנוכחית למועדפים",
  "labelPlay": "נגן הכל",
  "labelStop": "עצור",
  "labelDelete": "מחק",
  "placeholderBookmarkName": "שם סימניה",
  "errorNameExist": "סימניה קיימת!",
  "errorNameNull": "שם סימניה לא חוקי!",
  "editTip": "ערוך סימניות",
  "exitEditTip": "מבוצעת יציאה ממצב עריכה",
  "syncTip": "סנכרן",
  "cardsTips": "תצוגת רשת",
  "listTips": "תצוגת רשימה",
  "addBtn": "הוספה",
  "deleteBtn": "מחיקה",
  "changeThumbnailTip": "שנה תמונה ממוזערת",
  "dragReorderTip": "החזק וגרור כדי לשנות סדר",
  "deleteBtnTip": "מחק את הסימנייה",
  "editBtnTip": "ערוך את הסימנייה",
  "withVisibility": "עם נראות שכבות",
  "searchBookmark": "חיפוש",
  "bookmarksFromConfig": "סימניות מוגדרות מראש",
  "bookmarksFromCache": "סימניות מקומיות זמניות",
  "notice": "שים לב",
  "changeNoticeTips": "השינויים יישמרו רק במטמון הדפדפן. סנכרון בין הווידג'ט לתצורה שלו מנותק לאחר שמבצעים שינויים.",
  "syncNoticeTips": "כתוצאה מכך יימחקו כל השינויים שלך וישוחזרו הסימניות שהוגדרו.",
  "dontShowAgain": "אל תציג שוב",
  "saveVisibility": "שמור את נראות השכבות",
  "_widgetLabel": "סימנייה"
});