define({
  "settings": "הגדרות",
  "titleSettings": "הגדרות טקסט",
  "imageSettings": "הגדרות תמונה",
  "backgroundColor": "צבע רקע",
  "alignment": "יישור",
  "textSize": "גודל טקסט",
  "textColor": "צבע טקסט",
  "dataSource": "מקור הנתונים",
  "chartSettings": "הגדרות תרשים",
  "data": "נתונים",
  "dataLabels": "תוויות נתונים",
  "displayMode": "מצב תצוגה",
  "featureOption": "הצג ערכים עבור כל ישות בנפרד",
  "categoryOption": "הצג ערכים לפי קטגוריות",
  "countOption": "הצג מספרי ישויות לפי קטגוריות",
  "fieldOption": "הצג ערכי מאפיינים כתרשימים",
  "categoryField": "שדה קטגוריה",
  "labelField": "שדה תווית",
  "valueFields": "שדות ערך",
  "operation": "תפעולי",
  "sumOption": "סכום",
  "averageOption": "ממוצע",
  "minOption": "מינימום",
  "maxOption": "מקסימום",
  "dataFormat": "פורמט נתונים",
  "decimalPlaces": "ספרות עשרוניות",
  "prefix": "קידומת",
  "suffix": "סיומת",
  "dataType": "סוג נתונים",
  "featureCount": "ספירת יישויות",
  "fieldStatistics": "סטטיסטיקת שדה",
  "display": "תצוגה",
  "chartColor": "צבע תרשים",
  "horizontalAxis": "ציר אופקי",
  "verticalAxis": "ציר אנכי",
  "legend": "מקרא",
  "position": "מיקום",
  "top": "עליון",
  "bottom": "תחתון",
  "useDataSourceSelection": "השתמש בבחירה",
  "dataSourceFilterByExtent": "סינון לפי תיחום",
  "changeTemplate": "שנה תבנית",
  "numberSettings": "הגדרות מספר",
  "gaugeSettings": "הגדרות מדיד",
  "indicators": "מחוונים",
  "ifValue": "ערך 'אם'",
  "and": "וגם",
  "numberOperatorIsLessThan": "הוא פחות מ-",
  "numberOperatorIsGreaterThan": "הוא גדול מ-",
  "numberOperatorIsBetween": "הוא בין",
  "numberOperatorIsEqual": "שווה ל-",
  "numberOperatorIsNotEqual": "לא שווה ל-",
  "then": "אז",
  "ratio": "יחס",
  "trueValue": "ערך True",
  "changeValueColor": "שנה צבע ערך ל",
  "changeGaugeColor": "שנה צבע מדיד ל",
  "setIndicatorIcon": "הגדר סמל מחוון כ",
  "icons": "סמלים",
  "style": "סגנון",
  "placement": "מיקום",
  "left": "שמאל",
  "replace": "החלף",
  "right": "ימין",
  "color": "צבע",
  "categoryExists": "הקטגוריה קיימת!",
  "comboxHint": "הקלד או בחר אפשרות אחת",
  "comboxDisableInputHint": "בחר אפשרות אחת",
  "sortBy": "מיון על ידי",
  "labelAxis": "תווית",
  "valueAxis": "ערך",
  "minPeriod": "תקופה מינימלית",
  "automatic": "אוטומטי",
  "periodsWithOutRecords": "תקופות ללא רשומות",
  "nullValue": "‏ערך Null",
  "calculatedAsZero": "מחושב כמו אפס",
  "ignored": "התעלם",
  "maxCategories": "מספר מקסימלי של קטגוריות",
  "useLayerSymbology": "השתמש בסימבולוגיה של השכבות",
  "hollowsize": "גודל חלול",
  "splitField": "פצל שדה",
  "parsingperiodTip": "החישוב נכשל. קיימים מרווחי זמן רבים מדי משום שפרק הזמן של הניתוח קצר מדי.",
  "manyCategoryTip": "הצגת התרשים נכשלה. קטגוריות רבות מדי.",
  "setColor": "הגדר צבע",
  "setTheColorOf": "לאחר מכן הגדר את הצבע של",
  "setTheColorAs": "לאחר מכן הגדר את הצבע כ-",
  "ifStr": "אם משתמשים באפשרות",
  "as": "כמו",
  "is": "הוא",
  "isNot": "אינו",
  "barCluster": "אשכול עמודות",
  "individualBar": "עמודה בודדת",
  "allOthers": "כל האחרים",
  "category": "קטגוריה",
  "indicatorSum": "סכום",
  "indicatorAve": "AVE",
  "indicatorMax": "מקסימום",
  "indicatorMin": "מינימום",
  "setCorrectyIndicatorTip": "הגדר אינדיקטורים תקינים.",
  "dataRange": "טווח נתונים",
  "targetValue": "ערך יעד",
  "currentValue": "ערך נוכחי",
  "gaugeColor": "צבע מדיד",
  "min": "מינימום",
  "max": "מקסימום",
  "displayValueIn": "הצג ערך ב",
  "noData": "אין נתונים",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "אזהרה",
  "noSettingWaring1": "לחץ על אלמנט כדי להגדיר את המאפיינים שלו.",
  "noSettingWaring2": "גרור כדי לשנות גודל או לסדר מחדש אלמנט.",
  "donNotShowAgain": "אל תציג שוב",
  "changeTemplateWarning": "פעולה זו תמחק את כל ההגדרות שלך ותפתח תבנית ריקה חדשה.",
  "requiredFieldWarning": "חובה להכניס ערך זה:",
  "dataSourceNotSet": "הגדר מקור נתונים.",
  "addIndicatorTip": "הוסף מחוון",
  "chooseTemplatePopupTitle": "בחר תבנית",
  "filterExtentTipWithaTag": "תוכל להשבית את הסינון לפי <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>מקור נתונים חיצוני</a> בכרטיסייה 'מאפיין'.",
  "filterExtentTip": "תוכל להשבית את הסינון לפי מקור נתונים חיצוני בכרטיסייה 'מאפיין'.",
  "customColorByCategory": "צבע מותאם אישית לפי קטגוריה",
  "randomColor": "צבע אקראי",
  "valueString": "ערך",
  "fieldString": "שדה",
  "includeThresholdValue": "כלול ערך סף",
  "percentage": "אחוז",
  "colorSchema": "סכמת צבעים",
  "addCategory": "הוסף קטגוריה",
  "clickToEdit": "לחץ לעריכה",
  "nullText": "ריק",
  "others": "אחרים",
  "stringsInTemplate": {
    "name_number": "מספר",
    "name_gauge": "מדיד",
    "name_vertical_gauge": "מדיד אנכי",
    "name_horizontal_gauge": "מדיד אופקי",
    "name_pie": "עוגה",
    "name_donut": "ביגלה",
    "name_bar": "גרף טורים",
    "name_stacked_bar": "טורים מוערם",
    "name_percentage_stacked_bar": "טורים מוערם עם אחוזים",
    "name_column": "גרף עמודות",
    "name_stacked_column": "עמודות מוערם",
    "name_percentage_stacked_column": "עמודות מוערם עם אחוזים",
    "name_line": "קו",
    "name_area": "שטח",
    "name_stacked_area": "שטח מוערם",
    "name_percentage_stacked_area": "שטח מוערם עם אחוזים",
    "titleOfTheInfographic": "כותרת האינפוגרפיקה",
    "description": "תיאור: מידע נוסף על אינפוגרפיקה זו."
  }
});