define({
  "_widgetLabel": "Editor Inteligente",
  "_featureAction_SmartEditor": "Editor Inteligente",
  "noEditPrivileges": "A sua conta não tem permissão para criar ou modificar dados.",
  "widgetActive": "Ativo",
  "widgetNotActive": "Não Ativo",
  "pressStr": "Pressione ",
  "ctrlStr": " CTRL ",
  "snapStr": " para ativar o ajuste automático",
  "noAvailableTempaltes": "Modelos não disponíveis",
  "editorCache": " - Cache de Editor",
  "presetFieldAlias": "Campo",
  "presetValue": "Valor Predefinido",
  "usePresetValues": " Utilizar Valores Predefinidos (Novos elementos apenas)",
  "editGeometry": " Editar Geometria",
  "savePromptTitle": "Guardar elemento",
  "savePrompt": "Pretende guardar o elemento atual?",
  "deletePromptTitle": "Eliminar elemento",
  "deletePrompt": "Tem a certeza que pretende eliminar o elemento selecionado?",
  "attachmentLoadingError": "Erro ao carregar anexos",
  "attachmentSaveDeleteWarning": "Aviso: As alterações aplicadas a anexos são guardadas automaticamente",
  "autoSaveEdits": "Guarda a edição automaticamente",
  "addNewFeature": "Criar novo elemento",
  "featureCreationFailedMsg": "Não é possível criar novo registo/elemento",
  "noRelatedFeatureFoundMsg": "Não foram encontrados quaisquer Registos/Elementos.",
  "relatedItemTitle": "Tabela/Camada Relacionada",
  "invalidRelationShipMsg": "Por favor, assegure que o campo chave primário: '${parentKeyField}' tem um valor válido",
  "pendingFeatureSaveMsg": "Por favpr, guarde as edições ao elemento antes de criar um elemento relacionado.",
  "attachmentsRequiredMsg": "(*) Os anexos são necessários.",
  "filterEditor": {
    "all": "Todas",
    "noAvailableTempaltes": "Modelos não disponíveis",
    "searchTemplates": "Modelos Pesquisáveis"
  },
  "invalidConfiguration": "O widget não se encontra configurado ou as camadas da configuração já não se encontram no mapa.  Por favor, abra a aplicação no modo de builder e reconfigure o widget.",
  "geometryServiceURLNotFoundMSG": "Não é possível obter o URL do Serviço de Geometria"
});