define({
  "_widgetLabel": "رسم إسناد الشبكة",
  "newGRGFromAreaButtonLabel": "تحديد شبكة من منطقة",
  "newGRGFromPointButtonLabel": "تحديد شبكة من نقطة",
  "newGRGFromAreaTitle": "تحديد شبكة من منطقة",
  "newGRGFromPointTitle": "تحديد شبكة من نقطة",
  "newGRGBySizeButtonLabel": "بواسطة البُعد",
  "newGRGFromRefSystemButtonLabel": "بواسطة نظام الإسناد",
  "newGRGByTimeLabel": "بواسطة الوقت والسرعة",
  "newGRGFromNonStandardButtonLabel": "تحديد شبكة غير قياسية",
  "newGRGAreaBySizeTitle": "GRG من منطقة بواسطة البُعد",
  "newGRGAreaBySizeDefineAreaLabel": "منطقة GRG",
  "addGRGAreaPolygonToolTip": "رسم منطقة GRG باستخدام مضلع",
  "addGRGAreaExtentToolTip": "رسم منطقة GRG باستخدام مدى",
  "rotation": "استدارة GRG",
  "numberRowsColumnsLabel": "تحديد عدد الصفوف والأعمدة",
  "newGRGAreaByRefSystemTitle": "GRG من منطقة بواسطة نظام الإسناد",
  "gridSize": "حجم الشبكة",
  "UTMZoneandBand": "منطقة الشبكة",
  "100000m": "100000 متر",
  "10000m": "10000 متر",
  "1000m": "1000 متر",
  "100m": "100 متر",
  "10m": "10 متر",
  "clipGrid": "قص الشبكة إلى منطقة GRG",
  "newGRGAreaFromNonStandardTitle": "NRG جديد",
  "newGRGPointBySizeTitle": "GRG من نقطة بواسطة البُعد",
  "newGRGPointByRefSystemTitle": "GRG من نطقة بواسطة نظام الإسناد",
  "newGRGPointByTimeTitle": "GRG من نقطة باستخدام الوقت والسرعة",
  "time": "الوقت",
  "rate": "سرعة",
  "hours": "ساعات",
  "minutes": "دقائق",
  "seconds": "ثواني",
  "ftPerSec": "قدم/ثانية",
  "ftPerHour": "قدم/ساعة",
  "kmPerSec": "كم/ثانية",
  "kmPerHour": "كم/ساعة",
  "mPerSec": "متر/ثانية",
  "mPerHour": "متر/ساعة",
  "miPerSec": "ميل/ثانية",
  "miPerHour": "ميل/ساعة",
  "nMPerSec": "ميل بحري/ثانية",
  "nMPerHour": "ميل بحري/ساعة",
  "settingsTitle": "إعدادات",
  "labelSettingsLabel": "إعدادات التعليق المتصل بالبيان",
  "labelSettingsButtonLabel": "تكوين إعدادات التسمية",
  "gridSettingsLabel": "إعدادات الشبكة",
  "gridSettingsButtonLabel": "تكوين إعدادات الشبكة",
  "transparency": "الشفافية",
  "labelStyle": "نمط التسمية",
  "font": "الخط",
  "textSize": "حجم النص",
  "textColor": "لون النص",
  "halo": "هالة",
  "show": "عرض",
  "lockSettings": "تم تأمين الإعدادات بواسطة مالك التطبيق",
  "gridSettings": {
    "cellShape": "شكل الخلية",
    "cellUnits": "وحدات الخلية",
    "cellOutline": "إعدادات المخطط التفصيلي للخلية",
    "cellFill": "إعدادات تعبئة الخلية",
    "gridReferenceSystem": "نظام المرجع",
    "gridDatum": "مرجع الإسناد: WGS84",
    "labelStartPosition": "أصل التسمية",
    "labelType": "نوع التسمية",
    "labelDirection": "اتجاه التسمية",
    "gridOrigin": "أصل الشبكة",
    "default": "مستطيل",
    "hexagon": "مسدس",
    "miles": "أميال",
    "kilometers": "كيلومتر",
    "feet": "قدم",
    "meters": "أمتار",
    "yards": "ياردة",
    "nautical-miles": "أميال محايدة",
    "lowerLeft": "أدنى اليسار",
    "lowerRight": "أدنى اليمين",
    "upperLeft": "أعلى اليسار",
    "upperRight": "أعلى اليمين",
    "center": "المركز",
    "alphaNumeric": "أبجدي رقمي",
    "alphaAlpha": "أبجدي أبجدي",
    "numeric": "رقمي",
    "horizontal": "أفقياً",
    "vertical": "عمودي",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "عرض التسميات"
  },
  "publishTitle": "نشر GRG إلى البوابة الإلكترونية",
  "publishGRGBtn": "نشر",
  "GRGLayerName": "اسم طبقة GRG المنشور",
  "invalidGRGLayerName": "يجب ألا يحتوي اسم الطبقة إلا على أحرف أبجدية رقمية وتسطير سفلي",
  "missingGRGLayerName": "يجب عليك إدخال اسم GRG",
  "publishingFailedLayerExists": "فشل النشر: لديك خدمة معالم باسم {0}. يرجى اختيار اسم آخر.",
  "checkService": "فحص الخدمة: {0}.",
  "createService": "إنشاء الخدمة: {0}.",
  "unableToCreate": "يتعذر إنشاء: {0}",
  "addToDefinition": "إضافة إلى تعريف: {0}",
  "successfullyPublished": "تم نشر طبقة الويب بشكل ناجح{0}إدارة طبقة الويب",
  "userRole": "تحديث إنشاء الخدمة لأن المستخدم لا يتمتع بأذونات",
  "createGRGBtn": "إنشاء GRG",
  "clearGRGBtn": "مسح",
  "labelFormat": "تنسيق التسمية",
  "helpIconTooltip": "Z: متخصص منطقة الشبكة (GZD)\nS: 100,000 متر تعريف مربع شبكة (GSID)\nX: تجاه الشرق (إحداثيات X)\nY: لا شيء (إحداثيات Y)\n\nأمثلة:\nZSXY هو 15SWC8081751205\nZS X، كما أن Y هو 15SWC 80817,51205",
  "addPointToolTip": "إضافة أصل GRG",
  "cellWidth": "عرض الخلية (x)",
  "cellHeight": "ارتفاع الخلية (y)",
  "invalidNumberMessage": "القيمة الافتراضية غير صحيحة",
  "invalidRangeMessage": "يجب أن تكون القيمة أكبر من 0",
  "gridAngleInvalidRangeMessage": "يجب أن تكون القيمة بين -89.9 و89.9",
  "formatIconTooltip": "مدخلات التنسيق",
  "coordInputLabel": "أصل GRG (DD)",
  "setCoordFormat": "تعيين سلسلة تنسيق الإحداثيات",
  "prefixNumbers": "أضف البادئة '+/-' إلى الأرقام السالبة والموجبة",
  "cancelBtn": "إلغاء الأمر",
  "applyBtn": "تطبيق",
  "comfirmInputNotation": "تأكيد علامة المدخلات",
  "notationsMatch": "التعليقات التي تطابق المدخلات. يرجى تأكيد ما تريد استخدامه:",
  "numberOfCellsHorizontal": "# الخلايا الأفقية",
  "numberOfCellsVertical": "# الخلايا الرأسية",
  "gridAngle": "استدارة GRG",
  "tooManyCellsErrorMessage": "أنت تحاول إنشاء شبكة تتكون من أكثر من 2000 خلية، ويُوصَى بتخفيض عدد الخلايات التي تم إنشاؤها بواسطة تغيير حجم الشبكة أو منطقة الشبكة.",
  "missingParametersMessage": "<p>يفتقد نموذج إنشاء GRG إلى بعض المعلمات أو أنه يحتوي على معلمات غير صحيحة، يرجى التأكد من:</p><ul><li>رسم منطقة GRG.</li><li>يحتوي عرض وارتفاع الخلية على قيم صحيحة.</li></ul>",
  "missingOriginParametersMessage": "<p>يفتقد نموذج إنشاء GRG إلى بعض المعلمات أو أنه يحتوي على معلمات غير صحيحة، يرجى التأكد من:</p><ul><li>تعيين أصل GRG.</li><li>تحتوي مدخلات الوقت والسرعة والزاوية على قيم صحيحة.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>يفتقد نموذج إنشاء GRG إلى بعض المعلمات أو أنه يحتوي على معلمات غير صحيحة، يرجى التأكد من أن مدخلات عرض وارتفاع الخلية على قيم صحيحة.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>يفتقد نموذج إنشاء GRG إلى بعض المعلمات أو أنه يحتوي على معلمات غير صحيحة، يرجى التأكد من أن عدد المدخلات الأفقية والرأسية للخلايا يحتوي على قيم صحيحة.</p>",
  "drawPointToolTip": "انقر لإضافة نقطة أصل GRG",
  "missingLayerNameMessage": "يجب إدخال اسم طبقة صحيح قبل النشر",
  "parseCoordinatesError": "يتعذر توزيع الإحداثيات. الرجاء فحص المدخلات.",
  "grgPolarRegionError": "يوجد مدى GRG ضمن منطقة قطبية، ولن يتم إنشاء الخلايات التي تقع في نطاق المنطقة القطبية.",
  "grgPolarOriginError": "يتعذر أن تكون نقطة أصل GRG ضمن منطقة قطبية عند إنشاء GRG بواسطة نظام إسناد.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "درجة دقيقة ثانية",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "الدرجات العشرية - دائرة العرض/خط الطول",
  "DDLongLatNotation": "الدرجات العشرية - خط الطول/دائرة العرض",
  "DDMLatLongNotation": "دقائق عشرية درجات - دائرة العرض/خط الطول",
  "DDMLongLatNotation": "دقائق عشرية درجات - خط الطول/دائرة العرض",
  "DMSLatLongNotation": "ثواني دقائق درجات - دائرة العرض/خط الطول",
  "DMSLongLatNotation": "ثواني دقائق درجات - خط الطول/دائرة العرض",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - حرف الحزمة",
  "UTMHemNotation": "UTM - نصف الكرة (N/S)"
});