define({
  "_widgetLabel": "Smart redigerare",
  "_featureAction_SmartEditor": "Smart redigerare",
  "noEditPrivileges": "Ditt konto har inte behörighet att skapa eller ändra data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Inte aktiv",
  "pressStr": "Tryck på ",
  "ctrlStr": " CTRL ",
  "snapStr": " när du vill aktivera snappning",
  "noAvailableTempaltes": "Inga tillgängliga mallar",
  "editorCache": " – redigerarens cache",
  "presetFieldAlias": "Fält",
  "presetValue": "Förinställt värde",
  "usePresetValues": " Använd förinställda värden (endast nya geoobjekt)",
  "editGeometry": " Redigera geometri",
  "savePromptTitle": "Spara geoobjekt",
  "savePrompt": "Vill du spara det aktuella geoobjektet?",
  "deletePromptTitle": "Ta bort objekt",
  "deletePrompt": "Är du säker på att du vill ta bort det valda geoobjektet?",
  "attachmentLoadingError": "Ett fel uppstod vid överföring av bilagor",
  "attachmentSaveDeleteWarning": "Varning! Ändringar i bilagor sparas automatiskt",
  "autoSaveEdits": "Sparar ändringen automatiskt",
  "addNewFeature": "Skapa nytt geoobjekt",
  "featureCreationFailedMsg": "Det går inte att skapa ny post/nytt geoobjekt",
  "noRelatedFeatureFoundMsg": "Inga relaterade poster/geoobjekt hittades",
  "relatedItemTitle": "Relaterad tabell/relaterade lager",
  "invalidRelationShipMsg": "Kontrollera att primärnyckelfältet: '${parentKeyField}' har ett giltigt värde",
  "pendingFeatureSaveMsg": "Spara ändringarna av geoobjektet innan ett relaterat geoobjekt skapas.",
  "attachmentsRequiredMsg": "(*) Bilagor krävs.",
  "filterEditor": {
    "all": "Alla",
    "noAvailableTempaltes": "Inga tillgängliga mallar",
    "searchTemplates": "Sök efter mallar"
  },
  "invalidConfiguration": "Widgeten är antingen inte konfigurerad eller så finns lagren i konfigurationen inte längre i kartan. Öppna appen i byggläge och konfigurera om widgeten.",
  "geometryServiceURLNotFoundMSG": "Det gick inte att hämta webbadress till geometritjänst"
});