define({
  "gridTabLabel": "Mreža",
  "labelTabLabel": "Napisi",
  "referenceSystemTabLabel": "Koordinatni sistem",
  "gridTabDescription": "Nastavite videz in vedenje mrežnih celic.",
  "cellOutlineColor": "Barva obrobe celice",
  "cellFillColor": "Barva polnila celice",
  "transparency": "Prosojnost",
  "cellShapeDropDown": "Oblika celice",
  "default": "Pravokotnik",
  "hexagon": "Šestkotnik",
  "cellUnitsDropDown": "Enote celice",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "meters": "Metri",
  "yards": "Jardi",
  "nautical-miles": "Navtične milje",
  "gridOriginDropDown": "Izhodišče mreže",
  "lowerLeft": "Spodaj levo",
  "lowerRight": "Spodaj desno",
  "upperLeft": "Zgoraj levo",
  "upperRight": "Zgoraj desno",
  "center": "Na sredino",
  "labelTabDescription": "Nastavite videz in vedenje mrežnih napisov.",
  "labelSettings": "Slog napisa",
  "font": "Pisava",
  "textSize": "Velikost besedila",
  "textColor": "Barva besedila",
  "halo": "Žarenje",
  "show": "Prikaži",
  "labelTypeDropDown": "Tip napisa",
  "alphaNumeric": "Alfanumerično",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Številsko",
  "labelDirectionDropDown": "Smer napisa",
  "horizontal": "Horizontalno",
  "vertical": "Vertikalno",
  "labelOriginDropDown": "Izhodišče napisa",
  "referenceSystemlTabDescription": "Nastavite privzeti koordinatni sistem.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Nastavitve zaklepanja – uporabniku bo preprečeno spreminjanje konfiguriranih nastavitev v pripomočku"
});