define({
  "chartSettingLabel": "Postavke grafikona",
  "addNewLabel": "Dodaj novi",
  "generalSettingLabel": "Opće postavke",
  "searchSourceSettingLabel": "Postavke izvora pretraživanja",
  "layerChooser": {
    "title": "Odaberi sloj za grafikon",
    "selectPolygonLayerLabel": "Odaberi sloj",
    "selectPolygonLayerHintText": "Podsjetnik: ako konfigurirate više grafikona, tada slojevi moraju imati istu vrstu geometrije",
    "selectRelatedTableLayerLabel": "Odaberi tablicu povezanu sa slojem",
    "selectRelatedTableLayerHintText": "Podsjetnik: prikazane su samo tablice s brojčanim poljima",
    "errorInSelectingPolygonLayer": "Odredite sloj koji ima povezani točkasti sloj.",
    "errorInSelectingRelatedLayer": "Odaberite važeću povezanu tablicu/sloj za sloj.",
    "polygonLayerNotHavingRelationships": "Odabrani sloj nema povezanu tablicu/sloj."
  },
  "ChartSetting": {
    "sectionTitle": "Naslov odjeljka",
    "sectionTitleHintText": "Podsjetnik: prikazano u naslovu zaglavlja odjeljka",
    "chartTitle": "Naslov grafikona",
    "chartTitleHintText": "Podsjetnik: prikazano centrirano na vrhu grafikona",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Podsjetnik: prikazano ispod grafikona",
    "chartType": "Vrsta grafikona",
    "barChart": "Trakasti grafikon",
    "pieChart": "Tortni grafikon",
    "polarChart": "Polarni grafikon",
    "dataSeriesField": "Polje serije podataka",
    "labelField": "Polje oznake",
    "chartColor": "Boja grafikona",
    "singleColor": "Jedna boja",
    "colorByTheme": "Boja prema temi",
    "colorByFieldValue": "Boja prema vrijednosti polja",
    "xAxisTitle": "Naslov X-osi",
    "xAxisHintText": "Podsjetnik: naslov X-osi",
    "yAxisTitle": "Naslov Y-osi",
    "yAxisHintText": "Podsjetnik: naslov Y-osi",
    "fieldColorLabel": "Oznaka",
    "fieldColorColor": "Boja",
    "defaultFieldSelectLabel": "Odaberi",
    "errMsgFieldValuesNotFound": "Nije moguće pronaći vrijednosti za odabrano polje",
    "errMsgSectionTitle": "Unesite naslov odjeljka",
    "errMsgFieldByValue": "Odaberite vrijednost polja",
    "settingTabTitle": "Postavka",
    "layoutTabTitle": "Izgled",
    "polarChartSelectFieldsHintText": "Podsjetnik: odaberite polja za generiranje polarnog grafikona",
    "visibilityText": "Vidljivost",
    "fieldNameText": "Naziv polja",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Odaberite tri ili više polja za generiranje polarnog grafikona",
    "polarChartPolygonFillLabel": "Ispuni poligon",
    "polarChartPolygonFillHintText": "Podsjetnik: odaberite potvrdni okvir za prikaz polarnog grafikona ispunjenog poligona",
    "viewLayoutLabel": "Razmještaj",
    "ThemeSelector": {
      "themeAdobebricks": "Ćerpič",
      "themeAlgae": "Alge",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Plavi sumrak",
      "themeCubanShirts": "Kubanske košulje",
      "themeDesert": "Pustinja",
      "themeDistinctive": "Izrazito",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Skakavac",
      "themeGrasslands": "Pašnjaci",
      "themeGreySkies": "Sivo nebo",
      "themeHarmony": "Sklad",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irska",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Vlažno područje",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Opće postavke",
    "locationSymbolLabel": "Grafički simbol lokacije",
    "locationSymbolHintText": "Posjetnik: upotrebljava se za prikaz simbola za adresu i lokaciju na koju ste kliknuli",
    "refreshIntervalLabel": "Interval osvježavanja",
    "refreshIntervalHintText": "Posjetnik: upotrebljava se za osvježavanje grafikona na temelju ovog intervala. Odredite vrijednost između 1 do 1440 minuta",
    "errMsgRefreshInterval": "Odredite interval osvježavanja između 0 do 1440 minuta",
    "symbolPickerPreviewText": "Pretpregled:",
    "showToolToSelectLabel": "Postavi gumb lokacije",
    "showToolToSelectHintText": "Savjet: pruža gumb za postavljanje lokacije na karti umjesto postavljanja lokacije kad se klikne na kartu"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Postavke izvora pretraživanja",
    "searchSourceSettingTitle": "Postavke izvora pretraživanja",
    "searchSourceSettingTitleHintText": "Dodajte i konfigurirajte usluge geokodiranja ili slojeve s geoobjektima kao izvorima pretraživanja. Ti određeni izvori određuju što se može pretražiti u okviru za pretraživanje",
    "addSearchSourceLabel": "Dodaj izvor pretraživanja",
    "featureLayerLabel": "Sloj geoobjekta",
    "geocoderLabel": "Geokoder",
    "nameTitle": "Naziv",
    "generalSettingLabel": "Opće postavke",
    "allPlaceholderLabel": "Mjesto za unos teksta za pretraživanje svega:",
    "allPlaceholderHintText": "Savjet: unesite tekst koji će se prikazati kao mjesto za unos prilikom pretraživanja svih slojeva i geokodera",
    "generalSettingCheckboxLabel": "Prikaži skočni prozor za pronađeni geoobjekt ili lokaciju",
    "countryCode": "Pozivni broj za državu ili regiju",
    "countryCodeEg": "npr. ",
    "countryCodeHint": "Ako ostavite ovu vrijednost praznom, pretražit će se sve države i regije",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Pretraži samo trenutačni obuhvat karte",
    "zoomScale": "Mjerilo uvećanja",
    "locatorUrl": "URL geokodera",
    "locatorName": "Naziv geokodera",
    "locatorExample": "Primjer",
    "locatorWarning": "Ova verzija usluge geokodiranja nije podržana. Widget podržava verziju usluge geokodiranja 10.0 i novije verzije.",
    "locatorTips": "Prijedlozi nisu dostupni jer usluga geokodiranja ne podržava mogućnost predlaganja.",
    "layerSource": "Izvor sloja",
    "setLayerSource": "Postavi izvor sloja",
    "setGeocoderURL": "Postavi URL geokodera",
    "searchLayerTips": "Prijedlozi nisu dostupni jer usluga geoobjekata ne podržava mogućnost numeriranja stranica.",
    "placeholder": "Mjesto za unos teksta",
    "searchFields": "Polja za pretraživanje",
    "displayField": "Polja za prikaz",
    "exactMatch": "Točno podudaranje",
    "maxSuggestions": "Maksimalni broj prijedloga",
    "maxResults": "Maksimalni rezultati",
    "enableLocalSearch": "Omogući lokalno pretraživanje",
    "minScale": "Min. mjerilo",
    "minScaleHint": "Kad je mjerilo karte veće od ovog mjerila, primijenit će se lokalno pretraživanje",
    "radius": "Polumjer",
    "radiusHint": "Određuje polumjer područja oko trenutačnog središta karte koje se upotrebljava za povećanje broja kandidata za geokodiranje kako bi se prvi prikazali kandidati koji su najbliži lokaciji",
    "meters": "Metri",
    "setSearchFields": "Postavi polja za pretraživanje",
    "set": "Postavi",
    "fieldName": "Naziv",
    "invalidUrlTip": "URL ${URL} nije valjan ili dostupan."
  }
});