define({
  "_widgetLabel": "Tīklota atskaites grafika",
  "newGRGFromAreaButtonLabel": "Definēt tīklu no platības",
  "newGRGFromPointButtonLabel": "Definēt tīklu no punkta",
  "newGRGFromAreaTitle": "Definēt tīklu no platības",
  "newGRGFromPointTitle": "Definēt tīklu no punkta",
  "newGRGBySizeButtonLabel": "Pēc izmēra",
  "newGRGFromRefSystemButtonLabel": "Pēc atskaites sistēmas",
  "newGRGByTimeLabel": "Pēc laika un ātruma",
  "newGRGFromNonStandardButtonLabel": "Definēt nestandarta tīklu",
  "newGRGAreaBySizeTitle": "GRG no platības pēc izmēra",
  "newGRGAreaBySizeDefineAreaLabel": "GRG platība",
  "addGRGAreaPolygonToolTip": "Zīmēt GRG platību, izmantojot laukumu",
  "addGRGAreaExtentToolTip": "Zīmēt GRG platību, izmantojot pārklājumu",
  "rotation": "Tīkla pagriešana",
  "numberRowsColumnsLabel": "Definēt rindu un kolonnu skaitu",
  "newGRGAreaByRefSystemTitle": "GRG no platības pēc atskaites sistēmas",
  "gridSize": "Tīkla izmērs",
  "UTMZoneandBand": "Tīkla zona",
  "100000m": "100 000 metri",
  "10000m": "10 000 metri",
  "1000m": "1000 metri",
  "100m": "100 metri",
  "10m": "10 metri",
  "clipGrid": "Izgriezt tīklu no GRG platības",
  "newGRGAreaFromNonStandardTitle": "Jauna NRG",
  "newGRGPointBySizeTitle": "GRG no punkta pēc izmēra",
  "newGRGPointByRefSystemTitle": "GRG no punkta pēc atskaites sistēmas",
  "newGRGPointByTimeTitle": "GRG no punkta, izmantojot laiku un ātrumu",
  "time": "Laiks",
  "rate": "Ātrums",
  "hours": "Stundas",
  "minutes": "Minūtes",
  "seconds": "Sekundes",
  "ftPerSec": "Pēdas/sekunde",
  "ftPerHour": "Pēdas/stunda",
  "kmPerSec": "Kilometri/sekunde",
  "kmPerHour": "Kilometri/stunda",
  "mPerSec": "Metri/sekunde",
  "mPerHour": "Metri/stunda",
  "miPerSec": "Jūdzes/sekunde",
  "miPerHour": "Jūdzes/stunda",
  "nMPerSec": "Jūras jūdzes/sekunde",
  "nMPerHour": "Jūras jūdzes/stunda",
  "settingsTitle": "Iestatījumi",
  "labelSettingsLabel": "Kartes teksta iestatījumi",
  "labelSettingsButtonLabel": "Konfigurēt kartes teksta iestatījumus",
  "gridSettingsLabel": "Tīkla iestatījumi",
  "gridSettingsButtonLabel": "Konfigurēt tīkla iestatījumus",
  "transparency": "Caurspīdīgums",
  "labelStyle": "Kartes teksta stils",
  "font": "Fonts",
  "textSize": "Teksta lielums",
  "textColor": "Teksta krāsa",
  "halo": "Oreols",
  "show": "Rādīt",
  "lockSettings": "Iestatījumus ir bloķējis lietotnes īpašnieks",
  "gridSettings": {
    "cellShape": "Šūnas forma",
    "cellUnits": "Šūnas mērvienības",
    "cellOutline": "Šūnas kontūras iestatījumi",
    "cellFill": "Šūnas pildījuma iestatījumi",
    "gridReferenceSystem": "Atsauču sistēma",
    "gridDatum": "Bāze: WGS84",
    "labelStartPosition": "Kartes teksta koordinātu sākuma punkts",
    "labelType": "Kartes teksta veids",
    "labelDirection": "Kartes teksta virziens",
    "gridOrigin": "Tīkla koordinātu sākuma punkts",
    "default": "Taisnstūris",
    "hexagon": "Sešstūris",
    "miles": "Jūdzes",
    "kilometers": "Kilometri",
    "feet": "Pēdas",
    "meters": "Metri",
    "yards": "Jardi",
    "nautical-miles": "Jūras jūdzes",
    "lowerLeft": "Apakšējā kreisajā",
    "lowerRight": "Apakšējā labajā",
    "upperLeft": "Augšējā kreisajā",
    "upperRight": "Augšējā labajā",
    "center": "Centrā",
    "alphaNumeric": "Burtu-ciparu",
    "alphaAlpha": "Burtu-burtu",
    "numeric": "Skaitlisks",
    "horizontal": "Horizontāli",
    "vertical": "Vertikāli",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Rādīt kartes tekstus"
  },
  "publishTitle": "Publicēt GRG portālā",
  "publishGRGBtn": "Publicēt",
  "GRGLayerName": "Publicētā GRG slāņa nosaukums",
  "invalidGRGLayerName": "Slāņa nosaukums var saturēt tikai burtu un ciparu rakstzīmes, kā arī pasvītrojumus.",
  "missingGRGLayerName": "Ievadiet GRG nosaukumu",
  "publishingFailedLayerExists": "Publicēšanas neveiksme: jums jau ir elementu serviss ar nosaukumu {0}. Lūdzu, izvēlieties citu nosaukumu.",
  "checkService": "Kontrolēt servisu: {0}.",
  "createService": "Izveidot servisu: {0}",
  "unableToCreate": "Nevar izveidot: {0}",
  "addToDefinition": "Pievienot definīcijai: {0}",
  "successfullyPublished": "Veiksmīgi publicēts tīmekļa slānis{0}Pārvaldīt tīmekļa slāni",
  "userRole": "Nevar izveidot servisu, jo lietotājam nav atļauju",
  "createGRGBtn": "Izveidot GRG",
  "clearGRGBtn": "Notīrīt",
  "labelFormat": "Kartes teksta formāts",
  "helpIconTooltip": "Z: tīkla zonas rādītājs (GZD)\nS: 100 000 metru tīkla laukuma identifikācija (GSID)\nX: austrumu virzienā (X koordināta)\nY: ziemeļu virzienā (Y koordināta)\n\nPiemēri:\nZSXY ir 15SWC8081751205\nZS X,Y ir 15SWC 80817,51205",
  "addPointToolTip": "Pievienot GRG koordinātu sākuma punktu",
  "cellWidth": "Šūnas platums (x)",
  "cellHeight": "Šūnas augstums (y)",
  "invalidNumberMessage": "Ievadītā vērtība nav derīga",
  "invalidRangeMessage": "Vērtībai jābūt lielākai par 0",
  "gridAngleInvalidRangeMessage": "Vērtībai ir jābūt no -89,9 līdz 89,9",
  "formatIconTooltip": "Formatēt ievadi",
  "coordInputLabel": "GRG koordinātu sākuma punkts (DD)",
  "setCoordFormat": "Iestatīt koordinātu formātu virkni",
  "prefixNumbers": "Pievienot prefiksu '+/-' pozitīviem un negatīviem skaitļiem",
  "cancelBtn": "Atcelt",
  "applyBtn": "Lietot",
  "comfirmInputNotation": "Apstiprināt ievades notāciju",
  "notationsMatch": "notācijas atbilst jūsu ievadei. Lūdzu, apstipriniet, kuras vēlaties izmantot:",
  "numberOfCellsHorizontal": "# horizontālās šūnas",
  "numberOfCellsVertical": "# vertikālās šūnas",
  "gridAngle": "Tīkla pagriešana",
  "tooManyCellsErrorMessage": "Jūs mēģināt izveidot tīklu, kas sastāv no vairāk nekā 2000 šūnām. Ieteicams samazināt veidojamo šūnu skaitu, mainot tīkla izmēru vai tīkla platību.",
  "missingParametersMessage": "<p>GRG izveides veidlapai trūkst parametru vai ir nederīgi parametri. Lūdzu, pārliecinieties, vai:</p><ul><li>GRG platība ir uzzīmēta.</li><li>Šūnas platums un augstums satur derīgas vērtības.</li></ul>",
  "missingOriginParametersMessage": "<p>GRG izveides veidlapai trūkst parametru vai ir nederīgi parametri. Lūdzu, pārliecinieties, vai:</p><ul><li>GRG koordinātu sākuma punkts ir iestatīts.</li><li>Laika, ātruma un leņķa ievades satur derīgas vērtības.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG izveides veidlapai trūkst parametru vai ir nederīgi parametri. Lūdzu, pārliecinieties, vai šūnas platuma un augstuma ievades satur derīgas vērtības.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG izveides veidlapai trūkst parametru vai ir nederīgi parametri. Lūdzu, pārliecinieties, vai šūnu skaita horizontālās un vertikālās ievades satur derīgas vērtības.</p>",
  "drawPointToolTip": "Noklikšķiniet, lai pievienotu GRG koordinātu sākuma punktu",
  "missingLayerNameMessage": "Lai varētu publicēt, ir jāievada derīgs slāņa nosaukums",
  "parseCoordinatesError": "Nevar parsēt koordinātas. Lūdzu, pārbaudiet ievadi.",
  "grgPolarRegionError": "GRG pārklājums ir polārajā reģionā. Šūnas, kas ietilpst polārajā reģionā, netiks izveidotas.",
  "grgPolarOriginError": "Veidojot GRG pēc atskaites sistēmas, GRG koordinātu sākuma punkts nevar būt polārajā reģionā.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "GMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimālgrādi — platums/garums",
  "DDLongLatNotation": "Decimālgrādi — garums/platums",
  "DDMLatLongNotation": "Grādi, decimālminūtes — platums/garums",
  "DDMLongLatNotation": "Grādi, decimālminūtes — garums/platums",
  "DMSLatLongNotation": "Grādi, minūtes, sekundes — platums/garums",
  "DMSLongLatNotation": "Grādi, minūtes, sekundes — garums/platums",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — joslas burts",
  "UTMHemNotation": "UTM — puslode (Z/D)"
});