define({
  "_widgetLabel": "Запрос",
  "executeQueryTip": "Выберите одну из следующих задач для выполнения запроса.",
  "invalidConfig": "Недопустимая конфигурация. Используйте страницу настройки запроса для получения правильной конфигурации.",
  "queryParams": "Опции",
  "parameters": "ОПЦИИ",
  "queries": "ЗАПРОСЫ",
  "apply": "Применить",
  "queryResults": "Результаты",
  "clear": "Очистить",
  "noResults": "Объекты не найдены.",
  "queryError": "Сбой запроса!",
  "numberFound": "Число найденных объектов",
  "mapExtentTip": "Ограничить результаты текущей областью карты.",
  "noValue": "Нет значения",
  "and": "и",
  "stringOperatorIs": "соответствует",
  "stringOperatorIsNot": "не соответствует",
  "stringOperatorStartsWith": "начинается с",
  "stringOperatorEndsWith": "заканчивается",
  "stringOperatorContains": "содержит",
  "stringOperatorDoesNotContain": "не содержит",
  "stringOperatorIsBlank": "является пустым",
  "stringOperatorIsNotBlank": "не является пустым",
  "dateOperatorIsOn": "соответствует",
  "dateOperatorIsNotOn": "не соответствует",
  "dateOperatorIsBefore": "перед",
  "dateOperatorIsAfter": "после",
  "dateOperatorDays": "дней",
  "dateOperatorWeeks": "недель",
  "dateOperatorMonths": "месяцев",
  "dateOperatorInTheLast": "в последние",
  "dateOperatorNotInTheLast": "не в последние",
  "dateOperatorIsBetween": "между",
  "dateOperatorIsNotBetween": "не между",
  "dateOperatorIsBlank": "является пустым",
  "dateOperatorIsNotBlank": "не является пустым",
  "numberOperatorIs": "соответствует",
  "numberOperatorIsNot": "не соответствует",
  "numberOperatorIsAtLeast": "больше или равно",
  "numberOperatorIsLessThan": "меньше чем",
  "numberOperatorIsAtMost": "меньше или равно",
  "numberOperatorIsGreaterThan": "больше чем",
  "numberOperatorIsBetween": "между",
  "numberOperatorIsNotBetween": "не между",
  "numberOperatorIsBlank": "является пустым",
  "numberOperatorIsNotBlank": "не является пустым",
  "operationalLayerTip": "Добавить результат как операционный слой",
  "queryResult": "Результат выполнения запроса",
  "specifyParamsTip": "Укажите параметры для этой задачи",
  "useSpatialFilter": "Использовать пространственный фильтр для ограничения объектов",
  "useCurrentMapExtent": "Только объекты, пересекающие область текущей карты",
  "drawGraphicOnMap": "Только объекты, пересекающие заданную пользователем область",
  "specifySpatialFilterMsg": "Укажите пространственный фильтр для этой задачи.",
  "clearResults": "Очистка результатов",
  "operationalTip": "Когда включена эта опция, результаты остаются на карте до тех пор, пока не будет нажата кнопка \"${clearResults}\".",
  "noneQueryTip": "Для данного виджета не настроена задача запроса.",
  "noPermissionsMsg": "У вас нет разрешения на доступ к этому сервису.",
  "attributesFromRelationship": "Атрибуты из связанной таблицы",
  "tasks": "Задачи",
  "applySpatialFilterToLimitResults": "Применить пространственный фильтр для ограничения результатов",
  "useCurrentExtentTip": "Возвращать объекты только в текущем экстенте карты",
  "useDrawGraphicTip": "Возвращать объекты, которые пересекают геометрию, нарисованную на карте",
  "useFeaturesTip": "Возвращать только объекты, которые имеют пространственные отношения с объектами другого слоя",
  "noSpatialLimitTip": "Возвращать объекты в полном экстенте карты",
  "applySearchDistance": "Применить расстояние поиска",
  "spatialRelationship": "Пространственное отношение",
  "relatedLayer": "Связанный слой",
  "bufferDistance": "Буферное расстояние",
  "miles": "Мили",
  "kilometers": "Километры",
  "feet": "Футы",
  "meters": "Метры",
  "yards": "Ярды",
  "nauticalMiles": "Морские мили",
  "back": "Назад",
  "execute": "Выполнить",
  "zoomTo": "Приблизить к",
  "openAttributeTable": "Просмотреть в таблице атрибутов",
  "noResult": "Нет результата.",
  "noTask": "Нет задачи.",
  "removeThisResult": "Удалить этот результат",
  "attributeCriteira": "Критерий атрибута",
  "spatialFilter": "Пространственный фильтр",
  "value": "ЗНАЧЕНИЕ",
  "noAttributeSpatialFilterTip": "Фильтры не заданы. Будут возвращены все объекты.",
  "showAllRelatedRecords": "Показать все связанные записи",
  "changeSymbol": "Изменить символ",
  "queryCriteira": "Критерии запроса",
  "customQuery": "Пользовательский запрос",
  "layer": "Слой",
  "createCustomQuery": "Создать пользовательский запрос."
});