define({
  "_widgetLabel": "Reagavimo į ekstremalias situacijas vadovas",
  "ergMainPageTitle": "Sudaryta pagal 2016 m reagavimo į ekstremalias situacijas vadovą",
  "coordInputLabelStart": "Išsiliejimo vieta (DD)",
  "coordInputLabel": "Išsiliejimo vieta",
  "addPointToolTip": "Pridėti išsiliejimo vietą",
  "drawPointToolTip": "Spustelėkite norėdami pridėti išsiliejimo vietą",
  "material": "Medžiaga",
  "materialPlaceholder": "Pradėkite vesti tekstą, kad rastumėte medžiagą",
  "table3Message": "Pasirinktai medžiagai būtina papildoma informacija, jei išsiliejo didelis jos kiekis.\n\nĮsitikinkite, kad pasirinktos teisingos vėjo greičio ir gabenimo talpyklos reikšmės.",
  "table2Message": "Pasirinkta medžiaga patekusi į vandenį gali išskirti didelį kiekį toksiškų dujų.\n\nGalite panaudoti šią medžiagą (-as):\n\n",
  "spillSize": "Išsiliejimo dydis",
  "small": "Mažas",
  "large": "Didelis",
  "fireLabel": "Rodyti gaisro lokalizavimo zoną",
  "weatherLabel": "Esamos oro sąlygos išsiliejimo vietoje",
  "weatherIntialText": "<br />Atnaujinamos, kai nustatoma išsiliejimo vieta",
  "temperature": "Temperatūra",
  "wind": "Vėjas",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informacija apie oro sąlygas negauta. Atnaujinkite vėjo greičio ir išsiliejimo laiko reikšmes rankiniu būdu",
  "windDirection": "Vėjo kryptis (į kurią pučia)",
  "timeOfSpill": "Išsiliejimo laikas",
  "day": "Diena",
  "night": "Naktis",
  "windSpeed": "Vėjo greitis",
  "low": "Mažas",
  "moderate": "Vidutinis",
  "high": "Didelis",
  "transportContainer": "Gabenimo talpykla",
  "rail": "Geležinkelio cisterna",
  "semi": "Sunkvežimis su cisterna arba vilkiko cisterna",
  "mton": "Keli tonos cilindrai",
  "ston": "Keli maži cilindrai arba vienas tonos cilindras",
  "ag": "Žemės ūkio talpykla",
  "msm": "Keli maži cilindrai",
  "bleveLabel": "Rodyti BLEVE lokalizavimo zoną",
  "capacity": "Talpyklos talpa (litrais)",
  "bleveMessage": "Pasirinktai medžiagai galima rodyti papildomą evakuacijos atstumą, skirtą BLEVE.\n\nNorėdami įjungti šią funkciją, įjunkite Rodyti BLEVE lokalizacijos zoną ir pasirinkite atitinkamą talpyklos talpą.",
  "noPAZoneMessage": "Ši medžiaga neturi apsauginių veiksmų atstumo. Apskaičiuota tik pirminė lokalizacija ir evakuacijos zonos.",
  "settingsTitle": "Parametrai",
  "spillLocationLabel": "Išsiliejimo vieta",
  "spillLocationButtonLabel": "Konfigūruoti išsiliejimo vietos nustatymus",
  "IISettingsLabel": "Pradinė lokalizacijos zona",
  "IIButtonLabel": "Konfigūruoti pradinės lokalizacijos zonos nustatymus",
  "PASettingsLabel": "Apsaugos zona",
  "PAButtonLabel": "Konfigūruoti apsauginio veiksmo nustatymus",
  "downwindSettingsLabel": "Pavėjinė zona",
  "downwindButtonLabel": "Konfigūruoti pavėjinės zonos nustatymus",
  "fireSettingsLabel": "Gaisro lokalizavimo zona",
  "fireButtonLabel": "Konfigūruoti gaisro lokalizacijos zonos nustatymus",
  "bleveSettingsLabel": "BLEVE lokalizavimo zona",
  "bleveButtonLabel": "Konfigūruoti BLEVE zonos nustatymus",
  "style": "Stilius",
  "lineStyles": {
    "esriSLSDash": "Brūkšnys",
    "esriSLSDashDot": "Brūkšnys taškas",
    "esriSLSDashDotDot": "Brūkšnys taškas taškas",
    "esriSLSDot": "Taškas",
    "esriSLSLongDash": "Ilgas brūkšnys",
    "esriSLSLongDashDot": "Ilgas brūkšnys taškas",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trumpas brūkšnys",
    "esriSLSShortDashDot": "Trumpas brūkšnys taškas",
    "esriSLSShortDashDotDot": "Trumpas brūkšnys taškas taškas",
    "esriSLSShortDot": "Trumpas taškas",
    "esriSLSSolid": "Vientisas"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atgal",
    "esriSFSCross": "Skersai",
    "esriSFSDiagonalCross": "Įstrižai",
    "esriSFSForwardDiagonal": "Pirmyn",
    "esriSFSHorizontal": "Horizontali",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vientisas",
    "esriSFSVertical": "Vertikali"
  },
  "resultsTitle": "Rezultatai",
  "publishERGBtn": "Publikuoti",
  "ERGLayerName": "Publikuotas ERG sluoksnio pavadinimas",
  "invalidERGLayerName": "Sluoksnio pavadinime gali būti tik raidės, skaičiai ir pabraukimo brūkšniai",
  "missingERGLayerName": "Būtina įvesti ERG pavadinimą",
  "publishingFailedLayerExists": "Publikuoti nepavyko: jau turite elementų paslaugą, kurios pavadinimas {0}. Pasirinkite kita pavadinimą.",
  "checkService": "Tikrinti paslaugą: {0}",
  "createService": "Kurti paslaugą: {0}",
  "unableToCreate": "Nepavyko sukurti: {0}",
  "addToDefinition": "Įtraukti į aprašą: {0}",
  "successfullyPublished": "Sėkmingai publikuotas žiniatinklio sluoksnis{0}Tvarkyti žiniatinklio sluoksnį",
  "userRole": "Nepavyksta sukurti paslaugos, nes vartotojas neturi teisių",
  "transparency": "Permatomumas",
  "outline": "Kontūras",
  "fill": "Užpildas (spalva taikoma, tik kai pasirinktas vientisas stilius)",
  "createERGBtn": "Kurti zonas",
  "clearERGBtn": "Valyti",
  "labelFormat": "Žymės formatas",
  "helpIconTooltip": "Riba tarp mažo ir didelio išsiliejimo yra:\nSkysčiai – 55 galonai (208 litrai)\nSausosios medžiagos – 60 svarų (300 kilogramų)",
  "cellWidth": "Gardelės plotis (x)",
  "cellHeight": "Gardelės aukštis (y)",
  "invalidNumberMessage": "Įvesta reikšmė yra netinkama",
  "invalidRangeMessage": "Reikšmė turi būti didesnė nei 0",
  "gridAngleInvalidRangeMessage": "Reikšmė turi būti tarp -89,9 ir 89,9",
  "formatIconTooltip": "Formato įvestis",
  "setCoordFormat": "Nustatyti koordinačių formato eilutę",
  "prefixNumbers": "Pridėti „+/-“ prefiksą prie teigiamų ir neigiamų skaičių",
  "cancelBtn": "Atšaukti",
  "applyBtn": "Taikyti",
  "comfirmInputNotation": "Patvirtinkite įvesties žymėjimą",
  "notationsMatch": "žymėjimai atitinka įvestį, patvirtinkite, kurį norite naudoti:",
  "missingLayerNameMessage": "Prieš publikuojant reikia įvesti tinkamą sluoksnio pavadinimą",
  "parseCoordinatesError": "Negalima analizuoti koordinačių. Patikrinkite savo įvestį.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Laipsniai, Minutės, Sekundės",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dešimtainiai laipsniai – platuma / ilguma",
  "DDLongLatNotation": "Dešimtainiai laipsniai – ilguma / platuma",
  "DDMLatLongNotation": "Dešimtainių laipsnių minutės – platuma / ilguma",
  "DDMLongLatNotation": "Dešimtainių laipsnių minutės – ilguma / platuma",
  "DMSLatLongNotation": "Dešimtainių laipsnių sekundės – platuma / ilguma",
  "DMSLongLatNotation": "Dešimtainių laipsnių sekundės – ilguma / platuma",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - dažnio raidė",
  "UTMHemNotation": "UTM – pusrutulis (Š/P)"
});