define({
  "_widgetLabel": "격자 참조 그래픽",
  "newGRGFromAreaButtonLabel": "영역에서 격자 정의",
  "newGRGFromPointButtonLabel": "포인트에서 격자 정의",
  "newGRGFromAreaTitle": "영역에서 격자 정의",
  "newGRGFromPointTitle": "포인트에서 격자 정의",
  "newGRGBySizeButtonLabel": "크기 기준",
  "newGRGFromRefSystemButtonLabel": "참조 체계 기준",
  "newGRGByTimeLabel": "시간 및 속도 기준",
  "newGRGFromNonStandardButtonLabel": "비표준 격자 정의",
  "newGRGAreaBySizeTitle": "크기를 기준으로 영역에서 정의된 GRG",
  "newGRGAreaBySizeDefineAreaLabel": "GRG 영역",
  "addGRGAreaPolygonToolTip": "폴리곤을 사용하여 GRG 영역 그리기",
  "addGRGAreaExtentToolTip": "범위를 사용하여 GRG 영역 그리기",
  "rotation": "격자 회전",
  "numberRowsColumnsLabel": "행 및 열의 개수 정의",
  "newGRGAreaByRefSystemTitle": "참조 체계를 기준으로 영역에서 정의된 GRG",
  "gridSize": "그리드 크기",
  "UTMZoneandBand": "격자 구역",
  "100000m": "100,000미터",
  "10000m": "10,000미터",
  "1000m": "1000미터",
  "100m": "100미터",
  "10m": "10미터",
  "clipGrid": "GRG 영역에 격자 클립(Clip)",
  "newGRGAreaFromNonStandardTitle": "새 NRG",
  "newGRGPointBySizeTitle": "크기를 기준으로 포인트에서 정의된 GRG",
  "newGRGPointByRefSystemTitle": "참조 체계를 기준으로 포인트에서 정의된 GRG",
  "newGRGPointByTimeTitle": "시간 및 속도를 기준으로 포인트에서 정의된 GRG",
  "time": "Time(시간)",
  "rate": "속도",
  "hours": "시",
  "minutes": "분",
  "seconds": "초",
  "ftPerSec": "피트/초",
  "ftPerHour": "피트/시간",
  "kmPerSec": "킬로미터/초",
  "kmPerHour": "킬로미터/시간",
  "mPerSec": "미터/초",
  "mPerHour": "미터/시간",
  "miPerSec": "마일/초",
  "miPerHour": "마일/시간",
  "nMPerSec": "해리/초",
  "nMPerHour": "해리/시간",
  "settingsTitle": "설정",
  "labelSettingsLabel": "레이블 설정",
  "labelSettingsButtonLabel": "레이블 설정 구성",
  "gridSettingsLabel": "격자 설정",
  "gridSettingsButtonLabel": "격자 설정 구성",
  "transparency": "투명도",
  "labelStyle": "레이블 스타일",
  "font": "글꼴",
  "textSize": "텍스트 크기",
  "textColor": "텍스트 색상",
  "halo": "후광",
  "show": "보기",
  "lockSettings": "응용프로그램 소유자가 설정을 잠금",
  "gridSettings": {
    "cellShape": "셀 모양",
    "cellUnits": "셀 단위",
    "cellOutline": "셀 윤곽선 설정",
    "cellFill": "셀 채우기 설정",
    "gridReferenceSystem": "기준 체계",
    "gridDatum": "좌표: WGS84",
    "labelStartPosition": "레이블 원점",
    "labelType": "레이블 유형",
    "labelDirection": "레이블 방향",
    "gridOrigin": "격자 원점",
    "default": "직사각형",
    "hexagon": "육각형",
    "miles": "마일",
    "kilometers": "킬로미터",
    "feet": "피트",
    "meters": "m",
    "yards": "야드",
    "nautical-miles": "해리",
    "lowerLeft": "왼쪽 하단",
    "lowerRight": "오른쪽 하단",
    "upperLeft": "왼쪽 상단",
    "upperRight": "오른쪽 하단",
    "center": "가운데 맞춤",
    "alphaNumeric": "영숫자",
    "alphaAlpha": "영자",
    "numeric": "숫자",
    "horizontal": "수평",
    "vertical": "수직",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "레이블 표시"
  },
  "publishTitle": "포털에 GRG 발행",
  "publishGRGBtn": "발행",
  "GRGLayerName": "발행된 GRG 레이어 이름",
  "invalidGRGLayerName": "레이어 이름에는 영숫자 문자와 밑줄만 포함해야 함",
  "missingGRGLayerName": "GRG의 이름을 입력해야 함",
  "publishingFailedLayerExists": "발행에 실패함: 이름이 {0}인 피처 서비스가 이미 있습니다. 다른 이름을 선택하세요.",
  "checkService": "서비스 확인: [0]",
  "createService": "서비스 생성: [0]",
  "unableToCreate": "생성할 수 없음: {0}",
  "addToDefinition": "정의에 추가: {0}",
  "successfullyPublished": "웹 레이어가 발행되었음{0}웹 레이어 관리",
  "userRole": "사용자에게 권한이 없어 서비스를 생성할 수 없음",
  "createGRGBtn": "GRG 생성",
  "clearGRGBtn": "지우기",
  "labelFormat": "레이블 형식",
  "helpIconTooltip": "Z: Grid Zone Designator(GZD)\nS: 100,000미터 Grid Square Identification(GSID)\nX: 동향(X 좌표)\nY: 북향(Y 좌표)\n\n예시:\nZSXY는 15SWC8081751205이며\nZS X,Y는 15SWC 80817,51205임",
  "addPointToolTip": "GRG 원점 추가",
  "cellWidth": "셀 너비(x)",
  "cellHeight": "셀 높이(y)",
  "invalidNumberMessage": "입력한 값이 올바르지 않음",
  "invalidRangeMessage": "값은 0보다 커야 함",
  "gridAngleInvalidRangeMessage": "값은 -89.9에서 89.9 사이여야 함",
  "formatIconTooltip": "입력 형식 지정",
  "coordInputLabel": "GRG 원점(DD)",
  "setCoordFormat": "좌표 형식 문자열 설정",
  "prefixNumbers": "양수와 음수에 '+/-' 접두사 추가",
  "cancelBtn": "취소",
  "applyBtn": "적용",
  "comfirmInputNotation": "입력 표기 확인",
  "notationsMatch": "입력과 일치하는 표기입니다. 사용할 항목을 확인하세요.",
  "numberOfCellsHorizontal": "수평 셀 개수",
  "numberOfCellsVertical": "수직 셀 개수",
  "gridAngle": "격자 회전",
  "tooManyCellsErrorMessage": "2000개보다 많은 셀로 구성된 격자를 생성하려고 합니다. 격자 크기 또는 격자 영역을 변경하여 생성하려는 셀의 수를 줄이는 것이 좋습니다.",
  "missingParametersMessage": "<p>GRG 생성 양식의 매개변수가 누락되었거나 올바르지 않습니다. 다음을 확인하세요.</p><ul><li>GRG 영역이 그려져 있습니다.</li><li>셀 너비 및 높이의 값이 올바릅니다.</li></ul>",
  "missingOriginParametersMessage": "<p>GRG 생성 양식의 매개변수가 누락되었거나 올바르지 않습니다. 다음을 확인하세요.</p><ul><li>GRG 원점이 설정되었습니다.</li><li>입력한 시간, 속도 및 각도의 값이 올바릅니다.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG 생성 양식의 매개변수가 누락되었거나 올바르지 않습니다. 입력한 셀 너비 및 높이의 값이 올바른지 확인하세요.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG 생성 양식의 매개변수가 누락되었거나 올바르지 않습니다. 입력한 수평 및 수직 셀 개수의 값이 올바른지 확인하세요.</p>",
  "drawPointToolTip": "GRG 원점을 추가하려면 클릭",
  "missingLayerNameMessage": "발행하려면 먼저 올바른 레이어 이름을 입력해야 함",
  "parseCoordinatesError": "좌표를 구문 분석할 수 없습니다. 입력을 확인하세요.",
  "grgPolarRegionError": "GRG 범위가 극지방에 속해 있습니다. 극지방에 속한 셀은 생성되지 않습니다.",
  "grgPolarOriginError": "참조 체계를 기준으로 GRG를 생성하는 경우 GRG 원점은 극지방 내에 있을 수 없습니다.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM(H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "십진수(DD) - 위도/경도",
  "DDLongLatNotation": "십진수(DD) - 경도/위도",
  "DDMLatLongNotation": "도-소수-분 - 위도/경도",
  "DDMLongLatNotation": "도-소수-분 - 경도/위도",
  "DMSLatLongNotation": "도-분-초 - 위도/경도",
  "DMSLongLatNotation": "도-분-초 - 경도/위도",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 밴드 문자",
  "UTMHemNotation": "UTM - 반구(N/S)"
});