define({
  "_widgetLabel": "Consulta",
  "executeQueryTip": "Haz clic en uno de los siguientes elementos de tarea para ejecutar la consulta.",
  "invalidConfig": "Configuración no válida. Utiliza la página de configuración de consulta para obtener la configuración correcta.",
  "queryParams": "Opciones",
  "parameters": "OPCIONES",
  "queries": "CONSULTAS",
  "apply": "Aplicar",
  "queryResults": "Resultados",
  "clear": "Borrar",
  "noResults": "Ninguna entidad encontrada.",
  "queryError": "Error en la consulta",
  "numberFound": "Número de entidades encontradas",
  "mapExtentTip": "Limita los resultados al área de mapa actual.",
  "noValue": "Sin valor",
  "and": "y",
  "stringOperatorIs": "es",
  "stringOperatorIsNot": "no es",
  "stringOperatorStartsWith": "comienza por",
  "stringOperatorEndsWith": "termina en",
  "stringOperatorContains": "contiene",
  "stringOperatorDoesNotContain": "no contiene",
  "stringOperatorIsBlank": "está vacío",
  "stringOperatorIsNotBlank": "no está vacío",
  "dateOperatorIsOn": "es el",
  "dateOperatorIsNotOn": "no es el",
  "dateOperatorIsBefore": "es anterior a",
  "dateOperatorIsAfter": "es posterior a",
  "dateOperatorDays": "días",
  "dateOperatorWeeks": "semanas",
  "dateOperatorMonths": "meses",
  "dateOperatorInTheLast": "es el último",
  "dateOperatorNotInTheLast": "no es el último",
  "dateOperatorIsBetween": "está entre",
  "dateOperatorIsNotBetween": "no está entre",
  "dateOperatorIsBlank": "está vacío",
  "dateOperatorIsNotBlank": "no está vacío",
  "numberOperatorIs": "es",
  "numberOperatorIsNot": "no es",
  "numberOperatorIsAtLeast": "es como mínimo",
  "numberOperatorIsLessThan": "es menos que",
  "numberOperatorIsAtMost": "es como máximo",
  "numberOperatorIsGreaterThan": "es mayor que",
  "numberOperatorIsBetween": "está entre",
  "numberOperatorIsNotBetween": "no está entre",
  "numberOperatorIsBlank": "está vacío",
  "numberOperatorIsNotBlank": "no está vacío",
  "operationalLayerTip": "Agregar resultado como capa operativa",
  "queryResult": "Resultado de la consulta",
  "specifyParamsTip": "Especificar parámetros para esta tarea",
  "useSpatialFilter": "Usar filtro espacial para limitar las entidades",
  "useCurrentMapExtent": "Solo entidades que intersequen el área de mapa actual",
  "drawGraphicOnMap": "Solo entidades que intersequen el área definida por el usuario",
  "specifySpatialFilterMsg": "Especifica un filtro espacial para esta tarea.",
  "clearResults": "Borrar los resultados",
  "operationalTip": "Con esta opción seleccionada, los resultados se conservarán en el mapa hasta que se haga clic en el botón \"${clearResults}\".",
  "noneQueryTip": "No se ha configurado ninguna tarea de consulta para este widget.",
  "noPermissionsMsg": "No tienes permisos para acceder a este servicio.",
  "attributesFromRelationship": "Atributos de la tabla asociada",
  "tasks": "Tareas",
  "applySpatialFilterToLimitResults": "Aplicar un filtro espacial para limitar los resultados",
  "useCurrentExtentTip": "Devolver solo entidades contenidas en la extensión de mapa actual",
  "useDrawGraphicTip": "Devolver solo las entidades que intersecan con la forma dibujada en el mapa",
  "useFeaturesTip": "Devolver solo entidades que tengan una relación espacial con entidades de otra capa",
  "noSpatialLimitTip": "Devolver entidades contenidas en la extensión completa del mapa",
  "applySearchDistance": "Aplicar una distancia de búsqueda",
  "spatialRelationship": "Relación espacial",
  "relatedLayer": "Capa relacionada",
  "bufferDistance": "Distancia de zona de influencia",
  "miles": "Millas",
  "kilometers": "Kilómetros",
  "feet": "Pies",
  "meters": "Metros",
  "yards": "Yardas",
  "nauticalMiles": "Millas náuticas",
  "back": "Atrás",
  "execute": "Ejecutar",
  "zoomTo": "Acercar",
  "openAttributeTable": "Ver en la tabla de atributos",
  "noResult": "No hay ningún resultado.",
  "noTask": "No hay ninguna tarea.",
  "removeThisResult": "Eliminar este resultado",
  "attributeCriteira": "Criterios de atributos",
  "spatialFilter": "Filtro espacial",
  "value": "VALOR",
  "noAttributeSpatialFilterTip": "No se ha definido ningún filtro. Se devolverán todas las entidades.",
  "showAllRelatedRecords": "Mostrar todos los registros relacionados",
  "changeSymbol": "Cambiar símbolo",
  "queryCriteira": "Criterios de consulta",
  "customQuery": "Consulta personalizada",
  "layer": "Capa",
  "createCustomQuery": "Crear consulta personalizada."
});