define({
  "selectAnalysisTools": "בחר כלי ניתוח לשימוש בווידג'ט.",
  "graphicalDisplay": "תצוגה גרפית",
  "toolSetting": "הגדרת פרטי כלי",
  "toolLabel": "השם לתצוגה של הכלי",
  "showHelpTip": "הצג קישורים לעזרה בווידג'ט",
  "showCurrentMapExtent": "הצג אפשרות להשתמש בתיחום המפה הנוכחי",
  "showCredits": "הצג את האפשרות <b>הצג קרדיט</b>",
  "saveAsFeatureService": "שמור את התוצאה בחשבון של המשתמש",
  "showReadyToUseLayers": "הצג שכבות מוכנות לשימוש מתוך האטלס החי של העולם ב-ArcGIS Online",
  "toolNotAvailable": "כלי זה אינו זמין כיוון שהמפה אינה כוללת את שכבות הישויות הנדרשות.",
  "aggregatePoints": "קבץ נקודות",
  "aggregatePointsUsage": "קבץ נקודות בפוליגונים שבהם הן נמצאות.",
  "calculateDensity": "חשב צפיפות",
  "calculateDensityUsage": "צור מפת צפיפות מישויות נקודתיות או קוויות באמצעות פיזור כמותי של תופעה מסוימת (המיוצגת במאפיינים של הנקודות או הקווים) על המפה.",
  "connectOriginsToDestinations": "קשר נקודות מוצא לנקודות יעד",
  "connectOriginsToDestinationsUsage": "מדוד את זמן הנסיעה או את המרחק בין צמדי נקודות.",
  "createBuffers": "צור חייצים",
  "createBuffersUsage": "צור פוליגונים שיתחמו ישויות קלט",
  "createDriveTimeAreas": "צור אזורי זמן נסיעה",
  "createDriveTimeAreasUsage": "צור פוליגונים של זמן נסיעה (או מרחק נסיעה) סביב נקודות הקלט של ערכי זמן הנסיעה הנתונים.",
  "createViewshed": "צור שטחים נצפים",
  "createViewshedUsage": "יוצר אזורים נצפים בהתבסס על מיקומים שתגדיר.",
  "createWatersheds": "צור אגני ניקוז",
  "createWatershedsUsage": "יוצר אזורי אגני היקוות בהתבסס על מיקומים שתגדיר.",
  "deriveNewLocations": "גזור מיקומים חדשים",
  "deriveNewLocationsUsage": "מפיק ישויות חדשות משכבות הקלט העומדות בתנאי שאילתא שתגדיר",
  "dissolveBoundaries": "מזג גבולות",
  "dissolveBoundariesUsage": "מזג פוליגונים חופפים או בעלי גבול משותף.",
  "enrichLayer": "העשר שכבה",
  "enrichLayerUsage": "העשר ישויות קלט בנתוני אנשים ומקומות ובנתונים עסקיים על אזורים סמוכים",
  "extractData": "חלץ נתונים",
  "extractDataDesc": "חלץ נתונים משכבה אחת או יותר בתיחום נתון",
  "findExistingLocations": "מצא מיקומים קיימים",
  "findExistingLocationsUsage": "בחר ישויות בשכבת הקלט שיעמדו בתנאי שאילתת מאפיינים ו/או שאילתא מרחבית שתציין",
  "findHotSpots": "מצא נקודות חמות",
  "findHotSpotsUsage": "מצא אשכולות של ישויות קלט בעלי חשיבות סטטיסטית או ערכים גבוהים/נמוכים.",
  "findNearest": "מציאת המיקום הקרוב ביותר",
  "findNearestUsage": "עבור כל ישות בשכבת הקלט, מצא את הישות הקרובה אליה ביותר בשכבה אחרת",
  "findSimilarLocations": "מצא מיקומים דומים",
  "findSimilarLocationsUsage": "מדוד את הדמיון בין מיקומים מועמדים לבין אחד או יותר מיקומי יחוס",
  "interpolatePoints": "‏‫בצע אינטרפולציה לנקודות",
  "interpolatePointsUsage": "חזה ערכים במיקומים חדשים בהתבסס על מדידות מאוסף נקודות",
  "mergeLayers": "מיזוג שכבות",
  "mergeLayersUsage": "מזג ישויות משכבות רבות לשכבה חדשה",
  "overlayLayers": "כסה שכבות",
  "overlayLayersUsage": "שלב שכבות רבות לשכבה יחידה תוך שמירה על מידע מהשכבות המקוריות",
  "planRoutes": "תכנן מסלולים",
  "planRoutesUsage": "קבע כיצד לחלק משימות לכוח עבודה נייד ביעילות.",
  "summarizeNearby": "סכם סמיכויות",
  "summarizeNearbyUsage": "עבור כל ישות בשכבת קלט, סכם נתונים הנמצאים במרחק מסוים מישויות בשכבה אחרת.",
  "summarizeWithin": "סיכום פנימי",
  "summarizeWithinUsage": "עבור כל פוליגון בשכבת הקלט הפוליגונאלית, סכם את הנתונים שהתקבלו מישויות הנמצאות בתוכה בשכבה אחרת.",
  "traceDownstream": "עקוב במורד הזרם",
  "traceDownstreamUsage": "מצא נתיבי זרימה לכיוון המורד ממיקומים שתגדיר",
  "allowToExport": "אפשר לייצא תוצאות",
  "joinFeatures": "צרף ישויות",
  "joinFeaturesUsage": "הכלי 'צרף ישויות' יעביר מאפיינים משכבה או מטבלה אחת לשנייה על סמך קישורים מרחביים וקישורי מאפיינים. ניתן לבחור לחשב נתונים סטטיסטיים של הישויות המצורפות.",
  "includeRouteLayer": "כלול שכבות מסלול",
  "findOutliers": "חפש חריגים",
  "findOutliersUsage": "הכלי 'חפש חריגים' יקבע אם קיימים חריגים בעלי מובהקות סטטיסטית בדפוס המרחבי של הנתונים."
});