define({
  "settings": "Postavke",
  "titleSettings": "Postavke teksta",
  "imageSettings": "Postavke snimka",
  "backgroundColor": "Boja pozadine",
  "alignment": "Poravnanje",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "dataSource": "Izvor podataka",
  "chartSettings": "Postavke grafikona",
  "data": "Podaci",
  "dataLabels": "Oznake podataka",
  "displayMode": "Režim prikaza",
  "featureOption": "Prikaži vrednosti geoobjekat po geoobjekat",
  "categoryOption": "Prikaži vrednosti po kategoriji",
  "countOption": "Prikaži broj geoobjekata po kategoriji",
  "fieldOption": "Prikaži vrednosti atributa kao grafikon",
  "categoryField": "Polje kategorije",
  "labelField": "Polje oznake",
  "valueFields": "Polje vrednosti",
  "operation": "Radnja",
  "sumOption": "Zbir",
  "averageOption": "Prosečno",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Format podataka",
  "decimalPlaces": "Decimale",
  "prefix": "Prefiks",
  "suffix": "Sufiks",
  "dataType": "Tip podataka",
  "featureCount": "Brojač geoobjekata",
  "fieldStatistics": "Statistika polja",
  "display": "Prikaz",
  "chartColor": "Boja grafikona",
  "horizontalAxis": "Horizontalna osa",
  "verticalAxis": "Vertikalna osa",
  "legend": "Legenda",
  "position": "Pozicija",
  "top": "Vrh",
  "bottom": "Dno",
  "useDataSourceSelection": "Koristite selekciju",
  "dataSourceFilterByExtent": "Filtriraj po obuhvatu",
  "changeTemplate": "Promeni šablon",
  "numberSettings": "Postavke broja",
  "gaugeSettings": "Postavke merača",
  "indicators": "Indikatori",
  "ifValue": "Ako je vrednost",
  "and": "i",
  "numberOperatorIsLessThan": "je manje od",
  "numberOperatorIsGreaterThan": "je veće od",
  "numberOperatorIsBetween": "je između",
  "numberOperatorIsEqual": "je jednako",
  "numberOperatorIsNotEqual": "nije jednako",
  "then": "Onda",
  "ratio": "Odnos",
  "trueValue": "Prava vrednost",
  "changeValueColor": "promeni boju vrednosti na",
  "changeGaugeColor": "promeni boju merača na",
  "setIndicatorIcon": "postavi ikonu indikatora kao",
  "icons": "Ikone",
  "style": "Stil",
  "placement": "Položaj",
  "left": "Levo",
  "replace": "Zameni",
  "right": "Desno",
  "color": "Boja",
  "categoryExists": "Kategorija postoji!",
  "comboxHint": "Upišite ili izaberite jednu",
  "comboxDisableInputHint": "Izaberite",
  "sortBy": "Sortiraj po",
  "labelAxis": "Oznaka",
  "valueAxis": "Vrednost",
  "minPeriod": "Minimalni period",
  "automatic": "Automatski",
  "periodsWithOutRecords": "Periodi bez zapisa",
  "nullValue": "Bez vrednosti",
  "calculatedAsZero": "Izračunato kao nula",
  "ignored": "Zanemareno",
  "maxCategories": "Maksimalne kategorije",
  "useLayerSymbology": "Koristi simbologiju sloja",
  "hollowsize": "Šuplja veličina",
  "splitField": "Podeli polje",
  "parsingperiodTip": "Izračunavanje nije uspelo. Previše je vremenskih intervala zbog kratkog perioda raščlanjavanja.",
  "manyCategoryTip": "Prikazivanje tabele nije uspelo. Previše kategorija.",
  "setColor": "Postavi boju",
  "setTheColorOf": "Zatim podesite boju",
  "setTheColorAs": "Zatim podesite boju kao",
  "ifStr": "Ako",
  "as": "kao",
  "is": "je",
  "isNot": "nije",
  "barCluster": "klaster trake",
  "individualBar": "pojedinačna traka",
  "allOthers": "Sve ostalo",
  "category": "Kategorija",
  "indicatorSum": "ZBIR",
  "indicatorAve": "PROS",
  "indicatorMax": "MAKS",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Pravilno postavite indikatore.",
  "dataRange": "Opseg datuma",
  "targetValue": "Ciljna vrednost",
  "currentValue": "Trenutna vrednost",
  "gaugeColor": "Boja merača",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Prikaži vrednost u",
  "noData": "Nema podataka",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "S",
  "billionAbbreviation": "G",
  "warning": "Upozorenje",
  "noSettingWaring1": "Kliknite na element kako biste postavili njegova svojstva.",
  "noSettingWaring2": "Prevucite da biste promenili veličinu ili preuredili element.",
  "donNotShowAgain": "Ne prikazuj ponovo",
  "changeTemplateWarning": "Ovo će obrisati sve vaše postavke i otvoriti nov prazan šablon.",
  "requiredFieldWarning": "Ova vrednost je obavezna:",
  "dataSourceNotSet": "Postavite izvor podataka.",
  "addIndicatorTip": "Dodaj indikator",
  "chooseTemplatePopupTitle": "Odaberite šablon",
  "filterExtentTipWithaTag": "Možete da onemogućite filter pomoću <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Dodatnog izvora podataka</a> u okviru kartice Atribut.",
  "filterExtentTip": "Možete da onemogućite filter pomoću Dodatnog izvora podataka u okviru kartice Atribut.",
  "customColorByCategory": "Prilagođena boja po kategoriji",
  "randomColor": "Nasumična boja",
  "valueString": "Vrednost",
  "fieldString": "Polje",
  "includeThresholdValue": "Uključi graničnu vrednost",
  "percentage": "Procenat",
  "colorSchema": "Šema boja",
  "addCategory": "Dodaj kategoriju",
  "clickToEdit": "Kliknite da biste izmenili",
  "nullText": "Null",
  "others": "Ostalo",
  "stringsInTemplate": {
    "name_number": "Broj",
    "name_gauge": "Merač",
    "name_vertical_gauge": "Vertikalni merač",
    "name_horizontal_gauge": "Horizontalni merač",
    "name_pie": "Kružni",
    "name_donut": "Prstenasti",
    "name_bar": "Traka",
    "name_stacked_bar": "Naslagana traka",
    "name_percentage_stacked_bar": "Naslagana traka s procentima",
    "name_column": "Kolona",
    "name_stacked_column": "Naslagana kolona",
    "name_percentage_stacked_column": "Naslagana kolona s procentima",
    "name_line": "Linija",
    "name_area": "Površina",
    "name_stacked_area": "Naslagana površina",
    "name_percentage_stacked_area": "Naslagana površina s procentima",
    "titleOfTheInfographic": "NASLOV INFOGRAFIKE",
    "description": "Opis: dodatne informacije u vezi sa ovom infografikom."
  }
});