define({
  "chartSettingLabel": "Postavke grafikona",
  "addNewLabel": "Dodaj novi",
  "generalSettingLabel": "Opšte postavke",
  "searchSourceSettingLabel": "Postavke pretrage izvora",
  "layerChooser": {
    "title": "Izaberite sloj za grafikon",
    "selectPolygonLayerLabel": "Izaberite sloj",
    "selectPolygonLayerHintText": "Napomena: ako konfigurišete nekoliko grafikona, slojevi moraju da budu istog geometrijskog tipa",
    "selectRelatedTableLayerLabel": "Izaberite tabelu povezanu sa slojem",
    "selectRelatedTableLayerHintText": "Napomena: samo tabele sa numeričkim poljima su prikazane",
    "errorInSelectingPolygonLayer": "Izaberite sloj koji ima povezan sloj tačke.",
    "errorInSelectingRelatedLayer": "Izaberite važeći povezan sloj/važeću povezanu tabelu za sloj.",
    "polygonLayerNotHavingRelationships": "Izabrani sloj ne mora da bude povezan sa tabelom/slojem."
  },
  "ChartSetting": {
    "sectionTitle": "Odeljak naslova",
    "sectionTitleHintText": "Napomena: prikazuje se u odeljku naslova zaglavlja",
    "chartTitle": "Naslov grafikona",
    "chartTitleHintText": "Napomena: prikazuje se centrirano na vrhu grafikona",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Napomena: prikazuje se ispod grafikona",
    "chartType": "Tip grafikona",
    "barChart": "Trakasti grafikon",
    "pieChart": "Kružni grafikon",
    "polarChart": "Polarni grafikon",
    "dataSeriesField": "Polje serije podataka",
    "labelField": "Polje oznake",
    "chartColor": "Boja grafikona",
    "singleColor": "Jedna boja",
    "colorByTheme": "Oboji po temi",
    "colorByFieldValue": "Oboji po vrednostima polja",
    "xAxisTitle": "Naslov X ose",
    "xAxisHintText": "Napomena: naslov X ose",
    "yAxisTitle": "Naslov Y ose",
    "yAxisHintText": "Napomena: naslov Y ose",
    "fieldColorLabel": "Oznaka",
    "fieldColorColor": "Boja",
    "defaultFieldSelectLabel": "Izaberi",
    "errMsgFieldValuesNotFound": "Pronalaženje vrednosti za izabrana polja nije moguće",
    "errMsgSectionTitle": "Unesite naslov odeljka",
    "errMsgFieldByValue": "Izaberite vrednost polja",
    "settingTabTitle": "Postavka",
    "layoutTabTitle": "Raspored",
    "polarChartSelectFieldsHintText": "Napomena: izaberite polja da biste generisali polarni grafikon",
    "visibilityText": "Vidljivost",
    "fieldNameText": "Ime polja",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Izaberite tri ili više polja da biste generisali polarni grafikon",
    "polarChartPolygonFillLabel": "Popuni poligon",
    "polarChartPolygonFillHintText": "Napomena: izaberite polje za potvrdu da biste prikazali punjenje poligona u polarnom grafikonu",
    "viewLayoutLabel": "Priprema za štampu",
    "ThemeSelector": {
      "themeAdobebricks": "Čerpić",
      "themeAlgae": "Alge",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "PlaviSuton",
      "themeCubanShirts": "KubanskeKošulje",
      "themeDesert": "Pustinja",
      "themeDistinctive": "Osobeno",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Skakavac",
      "themeGrasslands": "Pašnjaci",
      "themeGreySkies": "SivaNeba",
      "themeHarmony": "Harmonija",
      "themeIndigoNation": "IndigoNarod",
      "themeIreland": "Irska",
      "themeMiamiNice": "MajamiFino",
      "themeMinty": "Minti",
      "themePurpleRain": "GrimiznaKiša",
      "themeRoyalPurples": "KraljevskiGrimizne",
      "themeSageToLime": "ŽalfijaDoLimuna",
      "themeTufte": "Tufte",
      "themeWatersEdge": "RubVode",
      "themeWetlandText": "Močvara",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Opšte postavke",
    "locationSymbolLabel": "Simbol lokacije grafike",
    "locationSymbolHintText": "Napomena: koristi se za prikazivanje simbola adrese i lokacije na koju je kliknuto",
    "refreshIntervalLabel": "Interval osvežavanja",
    "refreshIntervalHintText": "Napomena: koristi se za osvežavanje grafikona na osnovu ovog intervala. Navedite vrednost između 1 i 1440 minuta",
    "errMsgRefreshInterval": "Navedite interval osvežavanja između 0 i 1440 minuta",
    "symbolPickerPreviewText": "Pregledaj:",
    "showToolToSelectLabel": "Dugme za podešavanje lokacije",
    "showToolToSelectHintText": "Savet: Pruža dugme za postavljanje lokacije na mapi umesto postavljanja lokacije klikom na mapu"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Pretraži postavke izvora",
    "searchSourceSettingTitle": "Pretraži postavke izvora",
    "searchSourceSettingTitleHintText": "Dodajte i konfigurišite servise za geokodiranje ili slojeve geoobjekata kao izvora pretrage. Ovi navedeni izvori određuju šta može da se pretražuje unutar trake za pretragu.",
    "addSearchSourceLabel": "Dodaj izvor pretrage",
    "featureLayerLabel": "Sloj geoobjekata",
    "geocoderLabel": "Geokoder",
    "nameTitle": "Naziv",
    "generalSettingLabel": "Opšte postavke",
    "allPlaceholderLabel": "Tekst čuvara mesta za pretragu svega:",
    "allPlaceholderHintText": "Savet: Unesite tekst koji će se prikazati kao čuvar mesta tokom pretrage svih slojeva i geokodera",
    "generalSettingCheckboxLabel": "Prikaži iskačući prozor za pronađeni geoobjekat ili lokaciju",
    "countryCode": "Kôd(ovi) zemlje ili regiona",
    "countryCodeEg": "npr. ",
    "countryCodeHint": "Ako ova vrednost ostane prazna, pretražuju se sve zemlje i regioni",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Pretraži samo u trenutnom obuhvatu mape",
    "zoomScale": "Skala zumiranja",
    "locatorUrl": "URL adresa geokodera",
    "locatorName": "Ime geokodera",
    "locatorExample": "Primer",
    "locatorWarning": "Ova verzija servisa geokôdiranja nije podržana. Vidžet podržava samo servis geokôdiranja 10.0 i novije.",
    "locatorTips": "Predlozi nisu dostupni jer servis geokôdiranja ne podržava predloženu mogućnost.",
    "layerSource": "Izvor sloja",
    "setLayerSource": "Postavi izvor sloja",
    "setGeocoderURL": "Postavi URL adresu geokôdera",
    "searchLayerTips": "Predlozi nisu dostupni jer servis geoobjekata ne podržava mogućnost paginacije.",
    "placeholder": "Tekst čuvara mesta",
    "searchFields": "Polja za pretragu",
    "displayField": "Prikaži polje",
    "exactMatch": "Potpuno podudaranje",
    "maxSuggestions": "Maksimalno predloga",
    "maxResults": "Maksimalno rezultata",
    "enableLocalSearch": "Omogući lokalnu pretragu",
    "minScale": "Min. razmera",
    "minScaleHint": "Kada je razmera mape veća od ove razmere, primenjuje se lokalna pretraga",
    "radius": "Poluprečnik",
    "radiusHint": "Definiše poluprečnik oblasti oko trenutnog centra mape koja se koristi za poboljšavanje rangiranja kandidata za geokodiranje kako bi se prvo vraćali kandidati najbliži lokaciji",
    "meters": "Metri",
    "setSearchFields": "Postavi polja pretrage",
    "set": "Postavi",
    "fieldName": "Naziv",
    "invalidUrlTip": "URL adresa ${URL} nije validna ili nije dostupna."
  }
});