define({
  "tabs_section_Label": "टैब",
  "addTab": "टैब जोड़ें",
  "layerName": "लेयर",
  "layerType": "विश्लेषण का प्रकार",
  "layerLabel": "लेबल",
  "actions": "कार्रवाइयाँ",
  "closest": "निकटतम फीचर",
  "proximity": "निकटता",
  "summary": "सार",
  "select_lbl": "-- चयन करें --",
  "general_setting_Label": "सामान्य सेटिंग",
  "units_text_lbl": "दूरी इकाइयाँ",
  "miles": "मील",
  "kilometers": "किलोमीटर",
  "feet": "फ़ीट",
  "meters": "मीटर",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "maximum_distance_lbl": "निकटम फीचर अधिकतम दूरी",
  "buffer_text_lbl": "बफर लेबल",
  "buffer_lbl": "बफर दूरी",
  "buffer_max_lbl": "अधिकतम बफर दूरी",
  "buffer_min_lbl": "न्यूनतम बफर दूरी",
  "routing_checkBox": "रूटिंग को सक्षम करें",
  "weather_Label": "मौसम विकल्प",
  "weather_checkBox": "मौसम की जानकारी शामिल करें",
  "weather_celsius": "सेल्सियस-किलोमीटर",
  "selectLayers": "मौसम लेयर का चयन करें",
  "currentlySelectedLayer": "वर्तमान में चयनित मौसम लेयरस",
  "missingTabLabel": "कम से कम एक टैब का लेबल उपलब्ध नहीं है",
  "cancel": "रद्द करें",
  "ok": "ठीक है",
  "missingLayerInWebMap": "कोई भी परिचालन लेयर नहीं मिली।",
  "selectFields": "फील्ड्स का चयन करें",
  "addField": "क्षेत्र जोडें",
  "sum": "योग",
  "min": "न्यूनतम",
  "max": "अधिकतम",
  "avg": "औसत",
  "count": "गणना",
  "area": "क्षेत्रफल",
  "length": "लंबाई",
  "count_checkBox": "संख्या दिखाएँ",
  "area_checkBox": "क्षेत्र दिखाएँ",
  "length_checkBox": "लंबाई दिखाएँ",
  "max_records": "अधिकतम सीमा पूरी हो गई है",
  "disable_checkBox": "लेयर दृश्यता प्रबंधन को अक्षम करें",
  "optional_lbl": "वैकल्पिक लेबल",
  "incident_lbl": "घटना",
  "locate_lbl": "घटना का पता लगाएं"
});