define({
  "queries": "Frågor",
  "addNew": "Lägg till ny",
  "newQuery": "Ny fråga",
  "queryLayer": "Frågelager",
  "setSource": "Ange",
  "setDataSource": "Ange datakälla",
  "name": "Namn",
  "querySource": "Datakälla",
  "queryName": "Uppgiftsnamn",
  "queryDefinition": "Filterdefinition",
  "resultsSetting": "Resultatinställning",
  "symbolSetting": "Symbolinställning",
  "resultSettingTip": "Definiera vad som ska visas i resultaten och hur det ska visas.",
  "resultItemTitle": "Namn på varje resultatobjekt",
  "resultItemContent": "De här fältattributen visas",
  "fieldsSetTip": "Markera de fält du vill visa. Välj ett fält om du vill uppdatera dess alias, ändra ordning och formatera det.",
  "addField": "Lägg till fält",
  "visibility": "Synlighet",
  "alias": "Alias",
  "specialType": "Särskild typ",
  "actions": "Åtgärder",
  "none": "Inga",
  "link": "Länk",
  "image": "Bild",
  "noField": "Inget fält",
  "operationalLayerTip": "Lägg till resultat som funktionslager",
  "setLayerSymbolTip": "Ange en symbol för frågeresultat: ",
  "setSelectedSymbolTip": "Ange en symbol för det valda geoobjektet.",
  "notUseFilter": "Använd inte filter",
  "setSourceTip": "Ange en frågekälla.",
  "setFilterTip": "Ange filtret korrekt.",
  "ok": "OK",
  "cancel": "Avbryt",
  "noFilterTip": "Om inget filteruttryck definierats visar denna frågeuppgift en lista med alla geoobjekt i den angivna datakällan.",
  "relationships": "Relationer",
  "addRelationshipLayer": "Lägg till ny relation",
  "relatedTo": "Relaterat till",
  "selectOption": "Välj...",
  "resultItemSorting": "Sortering av resultatobjekt",
  "field": "Fält",
  "sortingOrder": "Ordning",
  "configureFieldsTip": "Konfigurera de fält som frågeresultatet ska sorteras efter.",
  "setSortingFields": "Ange sorteringsfält",
  "ascending": "Stigande",
  "descending": "Fallande",
  "sortBy": "Sortera efter",
  "thenBy": "Sedan efter",
  "addTask": "Lägg till uppgift",
  "noTasksTip": "Inga frågor har konfigurerats. Klicka på ${newQuery} om du vill lägga till en ny.",
  "infoText": "Info",
  "filters": "Filter",
  "results": "Resultat",
  "optionsText": "Alternativ",
  "summaryText": "Sammanfattning",
  "attributeFilter": "Attributfilter",
  "attributeFilterTip": "Definiera attribututtryck som kan användas i widgeten för att filtrera frågelagret.",
  "defineWhereClause": "Definiera en Where-sats för frågan.",
  "noExpressionDefinedTip": "Inget uttryck har definierats. Alla poster kommer att returneras.",
  "setExpressions": "Ange uttryck",
  "spatialFilter": "Geografiska filter",
  "spatialFilterTip": "Välj vilka geografiska filter som ska vara tillgängliga för slutanvändare.",
  "defaultOption": "Standard",
  "useCurrentExtentTip": "Returnera bara geoobjekt i den aktuella kartutbredningen",
  "useDrawGraphicTip": "Returnera bara geoobjekt som korsar den form som ritats på kartan",
  "useFeaturesTip": "Returnera bara geoobjekt som har en geografisk relation med geoobjekt i ett annat lager",
  "noSpatialLimitTip": "Returnera geoobjekt i hela kartutbredningen",
  "drawingTools": "Välj ritverktyg",
  "bufferSettings": "Aktivera buffertalternativ",
  "defaultDistance": "Standarddistans",
  "bufferDistance": "Buffertavstånd",
  "defaultUnit": "Standardenhet",
  "miles": "Engelska mil",
  "kilometers": "Kilometer",
  "feet": "Fot",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Nautiska mil",
  "availableSpatialRelationships": "Välj regler för geografisk relation",
  "setSpatialRelationships": "Ange geografiska relationer",
  "availability": "Tillgänglighet",
  "relationship": "Relation",
  "label": "Etikett",
  "intersect": "korsa",
  "contain": "innehålla",
  "areContainedIn": "ingår i",
  "cross": "kors",
  "envelopeIntersect": "områdesskärning",
  "overlap": "överlappning",
  "areOverlapped": "överlappar varandra",
  "touch": "vidrör",
  "within": "inom",
  "areWithin": "är inom",
  "indexIntersect": "indexskärning",
  "itemTitle": "Titel på objektet",
  "displayFields": "Visningsfält",
  "sortingFields": "Sortera resultat",
  "setDisplayFields": "Ange visningsfält.",
  "symbol": "Symbol",
  "setSymbol": "Använd anpassad symbol",
  "changeSymbolAtRuntime": "Tillåt att symboler ändras vid körning",
  "serviceSymbolTip": "Använd symbolerna som definieras av lagret",
  "exportTip": "Tillåt export av resultat",
  "keepResultsTip": "Behåll resultaten på kartan när widgeten stängs",
  "queryRelatedRecords": "Frågerelaterade poster",
  "createLayerForTaskTip": "Ange hur frågeuppgiften ska skapa lager",
  "oneLayerForTaskTip": "Skriv över lagret varje gång frågan körs",
  "multipleLayerForTaskTip": "Skapa ett nytt lager varje gång frågan körs",
  "makeDefault": "Utse till standard",
  "icon": "Ikon",
  "newTask": "Ny åtgärd",
  "addTaskTip": "Lägg till en eller flera frågor i widgeten och ställ in parametrar för var och en.",
  "webMapPopupTip": "Använd lagrets popupkonfiguration i webbkartan",
  "customPopupTip": "Konfigurera anpassat innehåll",
  "showResultsSetActions": "Visa åtgärder för resultatuppsättningen",
  "zoomTo": "Zooma till",
  "openAttributeTable": "Visa i attributtabell",
  "content": "Innehåll",
  "displaySQLTip": "Visa SQL-uttryck för slutanvändare",
  "useLayerDefaultSymbol": "Använd standardsymbolen för lagret",
  "setCustomIcon": "Ange anpassad ikon",
  "layerDefaultSymbolTip": "Använd standardsymbolen för lagret",
  "uploadImage": "Överför en bild",
  "attributeCriteira": "Attributkriterier",
  "specifyFilterAtRuntimeTip": "Användarna måste ange parametrar för det här uttrycket.",
  "value": "VÄRDE",
  "hideLayersTip": "Stäng av frågeresultatlager när widgeten stängs.",
  "tabLabels": "Fliketiketter",
  "tasks": "Uppgifter",
  "queryCriteira": "Frågekriterier",
  "allowCustomQuery": "Tillåt om du vill skapa anpassade frågor"
});