define({
  "serviceUrl": "Iestatīt servisa URL:",
  "minIntSpacingLabel": "Minimālais tīkla izmērs",
  "lineOpacityLabel": "Līniju necaurredzamība",
  "labelOpacityLabel": "Kartes teksta necaurredzamība",
  "centerLabelOpacityLabel": "Centrālā kartes nosaukuma necaurredzamība",
  "gridZonePlacementLabel": "Tīkla zonu nosaukumu izvietojums",
  "verticalLineLabels": "Vertikālo līniju nosaukums",
  "styleHeaderLabel": "Stils",
  "indexHeaderLabel": "Tīkla komponents",
  "colorHeaderLabel": "Krāsa",
  "fontSizeHeaderLabel": "Fonta izmērs",
  "lineWidthHeaderLabel": "Līnijas platums",
  "horizontalLabel": "Horizontāls",
  "verticalLabel": "Vertikāls",
  "upperLeftLabel": "Augšējais kreisais",
  "upperRightLabel": "Augšējais labais",
  "lowerLeftLabel": "Apakšējais kreisais",
  "lowerRightLabel": "Apakšējais labais",
  "centerLabel": "Centrs",
  "errorMessage": "Konfigurēšanas lapa satur kļūdas. Pirms saglabāšanas novērsiet kļūdas.",
  "checkBoxLabel": "Rādīt tīklu, ja logrīks ir aizvērts",
  "checkBoxLabelDashboard": "Rādīt tīklu",
  "gzd": "Tīkla zonas rādītājs (GZD)",
  "gsid": "100 000 metru tīkla laukuma identifikācija (GSID)",
  "grid10k": "10 000 metru tīkla līnijas",
  "grid1k": "1000 metru tīkla līnijas",
  "grid100m": "100 metru tīkla līnijas",
  "grid10m": "10 metru tīkla līnijas",
  "switchBasemap": "Pārslēgt pamatkarti"
});