define({
  "_widgetLabel": "Editor inteligent",
  "_featureAction_SmartEditor": "Editor inteligent",
  "noEditPrivileges": "Contul dumneavoastră nu are permisiunea de a crea sau modifica date.",
  "widgetActive": "Activ",
  "widgetNotActive": "Inactiv",
  "pressStr": "Apăsaţi pe ",
  "ctrlStr": " CTRL ",
  "snapStr": " pentru a activa fixarea",
  "noAvailableTempaltes": "Nu există şabloane disponibile",
  "editorCache": " - Cache editor",
  "presetFieldAlias": "Câmp",
  "presetValue": "Valoare presetată",
  "usePresetValues": " Utilizare valori presetate (numai pentru obiectele spaţiale noi)",
  "editGeometry": " Editare geometrie",
  "savePromptTitle": "Salvare obiect spaţial",
  "savePrompt": "Doriţi să salvaţi obiectul spaţial curent?",
  "deletePromptTitle": "Ştergere obiect spaţial",
  "deletePrompt": "Sigur doriţi să ştergeţi obiectul spaţial selectat?",
  "attachmentLoadingError": "Eroare la încărcarea fişierelor ataşate",
  "attachmentSaveDeleteWarning": "Avertisment: Modificările fişierelor ataşate sunt salvate automat",
  "autoSaveEdits": "Salvează automat editarea",
  "addNewFeature": "Creează caracteristică nouă",
  "featureCreationFailedMsg": "Nu se poate crea o nouă înregistrare/caracteristică",
  "noRelatedFeatureFoundMsg": "Nu s-au găsit Înregistrări/Caracteristici corelate",
  "relatedItemTitle": "Tabel/Strat tematic corelat",
  "invalidRelationShipMsg": "Asigurați-vă că există o valoare valabilă a câmpului cheii primare: '${parentKeyField}’",
  "pendingFeatureSaveMsg": "Vă rugăm să salvați editările caracteristicii înainte de a crea o caracteristică corelată.",
  "attachmentsRequiredMsg": "(*) Sunt necesare anexe.",
  "filterEditor": {
    "all": "Toate",
    "noAvailableTempaltes": "Nu există şabloane disponibile",
    "searchTemplates": "Căutare şabloane"
  },
  "invalidConfiguration": "Widgetul nu este configurat sau straturile tematice din configuraţie nu se mai află pe hartă.  Deschideţi aplicaţia în modul de creare şi reconfiguraţi widgetul.",
  "geometryServiceURLNotFoundMSG": "Imposibil de obţinut URL-ul serviciului de geometrie"
});