define({
  "_widgetLabel": "Udaljenost i smjer",
  "tabLineTitle": "Linija",
  "tabCircleTitle": "Krug",
  "tabEllipseTitle": "Elipsa",
  "tabRingsTitle": "Prsteni",
  "multipleNotationsMessage": " bilješke koje se podudaraju s vašim unosom. Potvrdite što biste htjeli upotrijebiti:",
  "invalidCoordinateMessage": "Nevaljana koordinata",
  "confirmInputNotationMessage": "Notacija potvrde unosa",
  "prefixSuffixMessage": "Otkriveno je da unesene koordinate imaju prefiks i sufiks za vrijednosti geografske širine i dužine, vraćene koordinate temelje se na prefiksu.",
  "rememberDecisionMessage": "Zapamti moju odluku i nemoj me pitati ponovo.<br/>",
  "majorAxisTooltipMessage": "Kliknite duljinu glavne osi",
  "minorAxisTooltipMessage": "Pomaknite miš natrag u početni položaj da biste postavili manje osi i završili crtanje elipse",
  "clickToFinishLineMessage": "Kliknite da biste dovršili crtanje linije",
  "doubleClickEllipseMesage": "Dvaput kliknite da biste dovršili crtanje prstena raspona",
  "invalidCoordinateTypeMessage": "Nije moguće utvrditi vrstu unesene koordinate. Provjerite unos",
  "noCenterPointSetMessage": "Nije postavljena središnja točka. Provjerite unos",
  "ellipseMajorAxis": "Glavna os",
  "ellipseMinorAxis": "Manja os",
  "degreesRangeMessage": "Vrijednost mora biti između 0 i 360",
  "millsRangeMessage": "Vrijednost mora biti između 0 i 6400",
  "lengthLabel": "Duljina",
  "angleLabel": "Kut",
  "startPointLabel": "Početna točka",
  "endPointLabel": "Završna točka",
  "centerPointLabel": "Središnja točka",
  "distanceTableErrorMessage": "Tablica udaljenosti je prazna. Provjerite jeste li unijeli neke udaljenosti.",
  "setCoordFormatStringMessage": "Postavi niz formata koordinata",
  "prefixMessage": "Dodajte prefiks „+/-” pozitivnim i negativnim brojevima",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Decimalni stupnjevi - geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stupnjevi - geografska dužina/širina",
  "DDMLatLongNotation": "Stupnjevi decimalne minute - geografska širina/dužina",
  "DDMLongLatNotation": "Stupnjevi decimalne minute - geografska dužina/širina",
  "DMSLatLongNotation": "Stupnjevi minute sekunde - geografska širina/dužina",
  "DMSLongLatNotation": "Stupnjevi minute sekunde - geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - slovo retka",
  "UTMHemNotation": "UTM - hemisfera (N/S)",
  "circleTitle": "Stvori krug iz",
  "radiusLabel": "Polumjer",
  "diameterLabel": "Promjer",
  "startPointPlaceHolderLabel": "Unesi koordinate",
  "formatInputLabel": "Format unosa",
  "drawCircleLabel": "Nacrtaj krug",
  "drawLineLabel": "Nacrtaj liniju",
  "createCircleInteractivelyLabel": "Interaktivno stvori krug",
  "rangeErrorMessage": "Nevažeći polumjer ili promjer",
  "numericInvalidMessage": "Unesite brojčanu vrijednost",
  "timeLabel": "Vrijeme",
  "invalidTimeMessage": "Nevažeća vremenska vrijednost",
  "hoursLabel": "Sati",
  "minutesLabel": "Minute",
  "secondsLabel": "Sekunde",
  "rateLabel": "Brzina",
  "invalidDistanceMessage": "Nevažeća vrijednost udaljenosti",
  "feetSecondsLabel": "Stopa / sekunda",
  "feetHourLabel": "Stopa / sat",
  "kmSecondLabel": "Kilometri / sekunda",
  "kmHourLabel": "Kilometar / sat",
  "metersSecondLabel": "Metri / sekunda",
  "metersHourLabel": "Metri / sat",
  "milesSecondLabel": "Milje / sekunda",
  "milesHourLabel": "Milje / sat",
  "nauticalMilesSecondLabel": "Nautičke milje / sekunda",
  "nauticalMilesHourLabel": "Nautičke milje / sat",
  "clearGraphicsLabel": "Izbriši grafike",
  "ellipseTypeLabel": "Vrsta elipse",
  "ellipseSemiLabel": "Polovična",
  "ellipseFullLabel": "Cijela",
  "drawEllipseLabel": "Nacrtaj elipsu",
  "createEllipseInteractively": "Interaktivno stvori elipsu",
  "axisLabel": "Os",
  "majorRadiusLabel": "Glavna (polumjer)",
  "axisErrorMessage": "Vrijednost mora biti veća od 0",
  "minorRadiusLabel": "Manja (polumjer)",
  "orientationLabel": "Orijentacija",
  "orientationErrorMessage": "Vrijednost mora biti između 0 i 360",
  "warningMessage": "Upozorenje: grafike generirane pomoću elipse alata nisu geodetske",
  "fromLabel": "Od",
  "distanceBearingLabel": "Udaljenost i usmjerenje",
  "pointsLabel": "Točke",
  "createLineInteractively": "Interaktivno stvori liniju",
  "lineLengthErrorMessage": "Nevažeća duljina linije",
  "degreesLabel": "Stupnjevi",
  "milsLabel": "Mil",
  "lineTypeLabel": "Vrsta",
  "interactiveLabel": "Interaktivno",
  "fixedLabel": "Popravljeno",
  "originLabel": "Podrijetlo",
  "cumulativeLabel": "Kumulativno",
  "numberOfRingsLabel": "Broj prstena",
  "ringsErrorMessage": "Nevažeći broj prstena",
  "distanceBetweenRingsLabel": "Udaljenost između prstena",
  "ringsDecimalErrorMessage": "Unesite brojčanu vrijednost na 2 decimalna mjesta",
  "distanceUnitsLabel": "Jedinice udaljenosti",
  "distancesLabel": "Udaljenosti",
  "numberOfRadialsLabel": "Broj radijala",
  "upLabel": "Gore",
  "downLabel": "Dolje",
  "deleteLabel": "Izbriši",
  "radialsErrorMessage": "Nevažeći broj radijala. Maksimalno dopušteno je 360",
  "addPointLabel": "Dodaj točku",
  "valueLabel": "Vrijednost",
  "valueText": "Unesite vrijednost",
  "actionLabel": "Radnja"
});