define({
  "_widgetLabel": "Avstånd och riktning",
  "tabLineTitle": "Linje",
  "tabCircleTitle": "Cirkel",
  "tabEllipseTitle": "Ellips",
  "tabRingsTitle": "Ringar",
  "multipleNotationsMessage": " notationer som matchar inmatningen. Bekräfta vilka du vill använda:",
  "invalidCoordinateMessage": "Ogiltig koordinat",
  "confirmInputNotationMessage": "Bekräfta inmatningsnotation",
  "prefixSuffixMessage": "Inmatningskoordinaten har både ett prefix och ett suffix för latitud- och longitudvärdet. Den returnerade koordinaten bygger på prefixet.",
  "rememberDecisionMessage": "Kom ihåg mitt beslut och fråga inte igen.<br/>",
  "majorAxisTooltipMessage": "Klicka på storaxelns längd",
  "minorAxisTooltipMessage": "Flytta musen tillbaka till startpositionen för att ställa in lillaxeln och slutföra ellipsens ritning",
  "clickToFinishLineMessage": "Klicka för att slutföra linjens ritning",
  "doubleClickEllipseMesage": "Slutför ritningen av utbredningens ringar genom att dubbelklicka",
  "invalidCoordinateTypeMessage": "Det gick inte att fastställa typen av inmatningskoordinat. Kontrollera inmatningen",
  "noCenterPointSetMessage": "Ingen mittpunkt har angetts. Kontrollera inmatningen",
  "ellipseMajorAxis": "Storaxel",
  "ellipseMinorAxis": "Lillaxel",
  "degreesRangeMessage": "Värdet måste vara mellan 0 och 360",
  "millsRangeMessage": "Värdet måste vara mellan 0 och 6 400",
  "lengthLabel": "Längd",
  "angleLabel": "Vinkel",
  "startPointLabel": "Startpunkt",
  "endPointLabel": "Slutpunkt",
  "centerPointLabel": "Mittpunkt",
  "distanceTableErrorMessage": "Avståndstabellen är tom. Se till att du anger några avstånd.",
  "setCoordFormatStringMessage": "Ange koordinatsträng",
  "prefixMessage": "Lägg till prefixet \"+/-\" för positiva och negativa tal",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Decimalgrader – Latitud/longitud",
  "DDLongLatNotation": "Decimalgrader – Longitud/latitud",
  "DDMLatLongNotation": "Grader decimalminuter – Latitud/longitud",
  "DDMLongLatNotation": "Grader decimalminuter – Longitud/latitud",
  "DMSLatLongNotation": "Grader minuter sekunder – Latitud/longitud",
  "DMSLongLatNotation": "Grader minuter sekunder – Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbokstav",
  "UTMHemNotation": "UTM – Halvklot (N/S)",
  "circleTitle": "Skapa cirkel från",
  "radiusLabel": "Radie",
  "diameterLabel": "Diameter",
  "startPointPlaceHolderLabel": "Ange koordinater",
  "formatInputLabel": "Formatinmatning",
  "drawCircleLabel": "Rita cirkel",
  "drawLineLabel": "Rita linje",
  "createCircleInteractivelyLabel": "Skapa cirkel interaktivt",
  "rangeErrorMessage": "Ogiltig radie eller diameter",
  "numericInvalidMessage": "Ange ett numeriskt värde",
  "timeLabel": "Tid",
  "invalidTimeMessage": "Ogiltigt tidsvärde",
  "hoursLabel": "Timmar",
  "minutesLabel": "Minuter",
  "secondsLabel": "Sekunder",
  "rateLabel": "Frekvens",
  "invalidDistanceMessage": "Ogiltigt avståndsvärde",
  "feetSecondsLabel": "Fot/sekund",
  "feetHourLabel": "Fot/timme",
  "kmSecondLabel": "Kilometer/sekund",
  "kmHourLabel": "Kilometer/timme",
  "metersSecondLabel": "Meter/sekund",
  "metersHourLabel": "Meter/timme",
  "milesSecondLabel": "Engelska mil/sekund",
  "milesHourLabel": "Engelska mil/timme",
  "nauticalMilesSecondLabel": "Nautiska mil/sekund",
  "nauticalMilesHourLabel": "Nautiska mil/timme",
  "clearGraphicsLabel": "Rensa grafik",
  "ellipseTypeLabel": "Ellipstyp",
  "ellipseSemiLabel": "Halv",
  "ellipseFullLabel": "Hel",
  "drawEllipseLabel": "Rita ellips",
  "createEllipseInteractively": "Skapa ellips interaktivt",
  "axisLabel": "Axel",
  "majorRadiusLabel": "Stor (radie)",
  "axisErrorMessage": "Värdet måste vara större än 0",
  "minorRadiusLabel": "Liten (radie)",
  "orientationLabel": "Riktning",
  "orientationErrorMessage": "Värdet måste vara mellan 0 och 360",
  "warningMessage": "Varning: Grafik som genereras med ellipsverktyget är inte geodetisk",
  "fromLabel": "Från",
  "distanceBearingLabel": "Avstånd och bäring",
  "pointsLabel": "Punkter",
  "createLineInteractively": "Skapa linje interaktivt",
  "lineLengthErrorMessage": "Ogiltig linjelängd",
  "degreesLabel": "Grader",
  "milsLabel": "Mils",
  "lineTypeLabel": "Mappen innehåller inte ett giltigt app-projekt",
  "interactiveLabel": "Interaktiv",
  "fixedLabel": "Fast",
  "originLabel": "Origo",
  "cumulativeLabel": "Kumulativ",
  "numberOfRingsLabel": "Antal ringar",
  "ringsErrorMessage": "Ogiltigt antal ringar",
  "distanceBetweenRingsLabel": "Avstånd mellan ringar",
  "ringsDecimalErrorMessage": "Ange ett numeriskt värde för två decimaler",
  "distanceUnitsLabel": "Distansenheter",
  "distancesLabel": "Distanser",
  "numberOfRadialsLabel": "Antal radiella",
  "upLabel": "Upp",
  "downLabel": "Ned",
  "deleteLabel": "Ta bort",
  "radialsErrorMessage": "Ogiltigt antal radiella. Det maximala antalet som tillåts är 360",
  "addPointLabel": "Lägg till punkt",
  "valueLabel": "Värde",
  "valueText": "Ange värde",
  "actionLabel": "Åtgärd"
});