define({
  "_widgetLabel": "Consulta",
  "executeQueryTip": "Clique num dos seguintes itens de tarefas para executar a consulta.",
  "invalidConfig": "Configuração inválida. Por favor utilize a página de definições de Consulta para obter a configuração correta.",
  "queryParams": "Parâmetros de Consulta",
  "parameters": "Parâmetros",
  "queries": "Consultas",
  "apply": "Aplicar",
  "queryResults": "Resultados de Consulta",
  "clear": "Limpar",
  "noResults": "Nenhum resultado",
  "queryError": "Consulta falhou !",
  "numberFound": "Número de elementos encontrados",
  "mapExtentTip": "Limitar os resultados da área de mapa actual.",
  "noValue": "Sem valores",
  "and": "e",
  "stringOperatorIs": "é",
  "stringOperatorIsNot": "não é",
  "stringOperatorStartsWith": "começa por",
  "stringOperatorEndsWith": "acaba em",
  "stringOperatorContains": "contém",
  "stringOperatorDoesNotContain": "não contém",
  "stringOperatorIsBlank": "está vazio",
  "stringOperatorIsNotBlank": "não está vazio",
  "dateOperatorIsOn": "é em",
  "dateOperatorIsNotOn": "não é em",
  "dateOperatorIsBefore": "é anterior a",
  "dateOperatorIsAfter": "é posterior a",
  "dateOperatorDays": "dias",
  "dateOperatorWeeks": "semanas",
  "dateOperatorMonths": "meses",
  "dateOperatorInTheLast": "nos(as) últimos(as)",
  "dateOperatorNotInTheLast": "não nos(as) últimos(as)",
  "dateOperatorIsBetween": "é entre",
  "dateOperatorIsNotBetween": "não é entre",
  "dateOperatorIsBlank": "está vazio",
  "dateOperatorIsNotBlank": "não está vazio",
  "numberOperatorIs": "é",
  "numberOperatorIsNot": "não é",
  "numberOperatorIsAtLeast": "é no mínimo",
  "numberOperatorIsLessThan": "é inferior a",
  "numberOperatorIsAtMost": "é no máximo",
  "numberOperatorIsGreaterThan": "é superior a",
  "numberOperatorIsBetween": "é entre",
  "numberOperatorIsNotBetween": "não é entre",
  "numberOperatorIsBlank": "está vazio",
  "numberOperatorIsNotBlank": "não está vazio",
  "operationalLayerTip": "Adicionar resultado como camada operacional",
  "queryResult": "Resultado de consulta",
  "specifyParamsTip": "Especificar parâmetros para esta tarefa",
  "useSpatialFilter": "Utilizar filtro espacial para limitar elementos",
  "useCurrentMapExtent": "Apenas elementos intersectam área de mapa actual",
  "drawGraphicOnMap": "Apenas elementos intersectam a área definida por utilizador",
  "specifySpatialFilterMsg": "Por favor especifique um filtro espacial para esta tarefa.",
  "clearResults": "Limpar resultados",
  "operationalTip": "Com esta opcção validada, os resultados serão mantidos no mapa até o botão \"${clearResults}\" ser clicado.",
  "noneQueryTip": "Não foi configurada qualquer tarefa de consulta para este widget.",
  "noPermissionsMsg": "Não possui permissões para aceder a este serviço.",
  "attributesFromRelationship": "Atributos de tabela relacionada",
  "tasks": "Tarefas",
  "applySpatialFilterToLimitResults": "Aplique um filtro espacial para limitar os resultados",
  "useCurrentExtentTip": "Apenas apresenta elementos contidos na extensão de mapa atual",
  "useDrawGraphicTip": "Apenas devolver elementos que intersectam a forma desenhada no mapa",
  "useFeaturesTip": "Apenas apresenta elementos que tenham uma relação espacial com elementos noutra camada",
  "noSpatialLimitTip": "Apresentar elementos contidos na extensão total do mapa",
  "applySearchDistance": "Aplique uma distância de pesquisa",
  "spatialRelationship": "Relação espacial",
  "relatedLayer": "Camada relacionada",
  "bufferDistance": "Distância do buffer",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas Náuticas",
  "back": "Retroceder",
  "execute": "Executar",
  "zoomTo": "Efectuar zoom para",
  "openAttributeTable": "Visualizar em Tabela de Atributos",
  "noResult": "Não existe resultado.",
  "noTask": "Não existe tarefa.",
  "removeThisResult": "Remover este resultado",
  "attributeCriteira": "Critério de atributos",
  "spatialFilter": "Filtro espacial",
  "value": "VALOR",
  "noAttributeSpatialFilterTip": "Não se encontram definidos quaisquer filtros. Todos os elementos serão apresentados.",
  "showAllRelatedRecords": "Exibir todos os registos relacionados",
  "changeSymbol": "Alterar Símbolo",
  "queryCriteira": "Critérios de consulta",
  "customQuery": "Consulta personalizada",
  "layer": "Camada",
  "createCustomQuery": "Criar consulta personalizada"
});