define({
  "_widgetLabel": "Smart-redigering",
  "_featureAction_SmartEditor": "Smart-redigering",
  "noEditPrivileges": "Din konto har ikke rettigheder til at oprette eller redigere data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Ikke aktiv",
  "pressStr": "Tryk ",
  "ctrlStr": " CTRL ",
  "snapStr": " for at aktivere snapping",
  "noAvailableTempaltes": "Ingen tilgængelige skabeloner",
  "editorCache": " - Editor-cache",
  "presetFieldAlias": "Mark",
  "presetValue": "Foruddefineret værdi",
  "usePresetValues": " Brug foruddefinerede værdier (kun for nye objekter)",
  "editGeometry": " Redigér geometri",
  "savePromptTitle": "Gem objekt",
  "savePrompt": "Vil du gemme det aktuelle objekt?",
  "deletePromptTitle": "Slet objekt",
  "deletePrompt": "Er du sikker på, at du vil slette det valgte objekt?",
  "attachmentLoadingError": "Fejl ved overførsel af vedhæftninger",
  "attachmentSaveDeleteWarning": "Advarsel: Ændringer i vedhæftninger gemmes automatisk",
  "autoSaveEdits": "Gemmer ændringerne automatisk",
  "addNewFeature": "Opret et nyt objekt",
  "featureCreationFailedMsg": "Kan ikke oprette en ny post/et nyt objekt",
  "noRelatedFeatureFoundMsg": "Ingen relaterede poster/objekter fundet.",
  "relatedItemTitle": "Tilknyttede tabeller/lag",
  "invalidRelationShipMsg": "Kontrollér, at det primære nøglefelt: '${parentKeyField}' har en gyldig værdi",
  "pendingFeatureSaveMsg": "Gem ændringerne i objektet, før du opretter et tilknyttet objekt.",
  "attachmentsRequiredMsg": "(*) Vedhæftninger er påkrævet.",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Ingen tilgængelige skabeloner",
    "searchTemplates": "Søgeskabeloner"
  },
  "invalidConfiguration": "Widget'en er enten ikke konfigureret, eller lagene i konfigurationen findes ikke længere i kortet. Åbn app'en i builder-tilstand, og omkonfigurér widget'en.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente geometritjeneste-URL"
});