define({
  "_widgetLabel": "Element grafic de referință cu grilă",
  "newGRGFromAreaButtonLabel": "Definiți o Grilă dintr-o Zonă",
  "newGRGFromPointButtonLabel": "Definiți o Grilă dintr-un Punct",
  "newGRGFromAreaTitle": "Definiți o Grilă dintr-o Zonă",
  "newGRGFromPointTitle": "Definiți o Grilă dintr-un Punct",
  "newGRGBySizeButtonLabel": "După Dimensiune",
  "newGRGFromRefSystemButtonLabel": "După Sistemul de Referinţă",
  "newGRGByTimeLabel": "După Timp și Viteză",
  "newGRGFromNonStandardButtonLabel": "Definiți Grila Non-Standard",
  "newGRGAreaBySizeTitle": "GRG dintr-o Zonă după Dimensiune",
  "newGRGAreaBySizeDefineAreaLabel": "Suprafaţă GRG",
  "addGRGAreaPolygonToolTip": "Desenați Zona GRG folosind un poligon",
  "addGRGAreaExtentToolTip": "Desenați Zona GRG folosind o extindere",
  "rotation": "Rotația grilei",
  "numberRowsColumnsLabel": "Definiți numărul de rânduri și coloane",
  "newGRGAreaByRefSystemTitle": "GRG dintr-o Zonă după Sistem de referinţă",
  "gridSize": "Dimensiune grilă",
  "UTMZoneandBand": "Zonă grilă",
  "100000m": "100000 metri",
  "10000m": "10000 metri",
  "1000m": "1000 metri",
  "100m": "100 metri",
  "10m": "10 metri",
  "clipGrid": "Decupați Grila după Zona GRG",
  "newGRGAreaFromNonStandardTitle": "NRG nou",
  "newGRGPointBySizeTitle": "GRG dintr-un Punct după Dimensiune",
  "newGRGPointByRefSystemTitle": "GRG dintr-un Punct după Sistem de referinţă",
  "newGRGPointByTimeTitle": "GRG dintr-un Punct folosind Timpul și Viteza",
  "time": "Oră",
  "rate": "Viteză",
  "hours": "Ore",
  "minutes": "Minute",
  "seconds": "Secunde",
  "ftPerSec": "Picioare / secundă",
  "ftPerHour": "Picioare / oră",
  "kmPerSec": "Kilometri / secundă",
  "kmPerHour": "Kilometri / oră",
  "mPerSec": "Metri / secundă",
  "mPerHour": "Metri / oră",
  "miPerSec": "Mile / secundă",
  "miPerHour": "Mile / oră",
  "nMPerSec": "Mile nautice / secundă",
  "nMPerHour": "Mile nautice / oră",
  "settingsTitle": "Setările",
  "labelSettingsLabel": "Setări etichetă",
  "labelSettingsButtonLabel": "Configurare setări pentru etichetă",
  "gridSettingsLabel": "Setări grilă",
  "gridSettingsButtonLabel": "Configurare setări pentru grilă",
  "transparency": "Transparenţă",
  "labelStyle": "Stil etichetă",
  "font": "Corp de literă",
  "textSize": "Dimensiune text",
  "textColor": "Culoare text",
  "halo": "Bună",
  "show": "Afişează",
  "lockSettings": "Setările au fost blocate de proprietarul aplicației",
  "gridSettings": {
    "cellShape": "Forma celulei",
    "cellUnits": "Unități de celulă",
    "cellOutline": "Setările conturului celulei",
    "cellFill": "Setările de umplere a celulei",
    "gridReferenceSystem": "Sistem referinţă",
    "gridDatum": "Cotă inițială: WGS84",
    "labelStartPosition": "Originea etichetei",
    "labelType": "Tipul etichetei",
    "labelDirection": "Direcția etichetei",
    "gridOrigin": "Originea grilei",
    "default": "Dreptunghi",
    "hexagon": "Hexagon",
    "miles": "Mile",
    "kilometers": "Kilometri",
    "feet": "Ft",
    "meters": "Metri",
    "yards": "Yarzi",
    "nautical-miles": "Mile marine",
    "lowerLeft": "Stânga jos",
    "lowerRight": "Dreapta jos",
    "upperLeft": "Stânga sus",
    "upperRight": "Dreapta sus",
    "center": "Centru",
    "alphaNumeric": "Alfanumeric",
    "alphaAlpha": "Alfa-Alfa",
    "numeric": "Numeric",
    "horizontal": "Orizontal",
    "vertical": "Vertical",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Afişare etichete"
  },
  "publishTitle": "Publică GRG pe Portal",
  "publishGRGBtn": "Publicare",
  "GRGLayerName": "Nume strat tematic GRG publicat",
  "invalidGRGLayerName": "Numele stratului tematic trebuie să includă doar caractere alfanumerice și de subliniere",
  "missingGRGLayerName": "Trebuie să introduceți un nume pentru GRG",
  "publishingFailedLayerExists": "Publicarea a eșuat: Aveți deja un serviciu de obiecte spaţiale denumit {0}. Alegeți alt nume.",
  "checkService": "Bifaţi serviciu: {0}",
  "createService": "Creați serviciu: {0}",
  "unableToCreate": "Nu se poate crea: {0}",
  "addToDefinition": "Adăugați la definiție: {0}",
  "successfullyPublished": "Publicarea cu succes a stratului tematic web{0}Administrare strat tematic web",
  "userRole": "Nu se poate crea serviciu deoarece utilizatorul nu are permisiunile",
  "createGRGBtn": "Creați GRG",
  "clearGRGBtn": "Golire",
  "labelFormat": "Format etichetă",
  "helpIconTooltip": "Z: Indicator de zonă a grilei (GZD)\nS: Identificarea pătratului de grilă de 100.000 metri (GSID)\nX: Navigare spre est (Coordonata X)\nY: Navigare spre nord (Coordonate Y)\n\nExemple:\nZSXY este 15SWC8081751205\nZS X,Y este 15SWC 80817,51205",
  "addPointToolTip": "Adaugă origine GRG",
  "cellWidth": "Lățime celulă (x)",
  "cellHeight": "Înălțime celulă (y)",
  "invalidNumberMessage": "Valoarea introdusă nu este valabilă",
  "invalidRangeMessage": "Valoarea trebuie să fie mai mare decât 0",
  "gridAngleInvalidRangeMessage": "Valoarea trebuie să fie între -89,9 şi 89,9",
  "formatIconTooltip": "Intrare format",
  "coordInputLabel": "Origine GRG (DD)",
  "setCoordFormat": "Setare şir format coordonate",
  "prefixNumbers": "Adăugaţi prefixul \"+/-\" la numere pozitive şi negative",
  "cancelBtn": "Anulare",
  "applyBtn": "Aplicare",
  "comfirmInputNotation": "Confirmare notare intrare",
  "notationsMatch": "notaţii se potrivesc cu introducerea dvs. Confirmaţi ce doriţi să folosiţi:",
  "numberOfCellsHorizontal": "# Celule orizontale",
  "numberOfCellsVertical": "# Celule verticale",
  "gridAngle": "Rotația grilei",
  "tooManyCellsErrorMessage": "Încercați să creați o grilă alcătuită din peste 2000 celule. Se poate reduce numărul celulelor create prin schimbarea dimensiunii grilei sau suprafeței grilei.",
  "missingParametersMessage": "<p>Formularul de creare GRG are parametri lipsă sau nevalabili, Vă rugăm să vă asigurați că:</p><ul><li>A fost trasată o suprafață GRG.</li><li>Lățimea și înălțimea celulei conțin valori valabile.</li></ul>",
  "missingOriginParametersMessage": "<p>Formularul de creare GRG are parametri lipsă sau nevalabili, Vă rugăm să vă asigurați că:</p><ul><li>A fost setată o suprafață GRG.</li><li>Valorile introduse pentru oră, viteză și unghi sunt valabile.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Formularul de creare GRG are parametri lipsă sau nevalabili. Vă rugăm să vă asigurați că valorile introduse pentru lățimea și înălțimea celulei sunt valabile.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Formularul de creare GRG are parametri lipsă sau nevalabili. Vă rugăm să vă asigurați că valorile introduse pentru numărul de celule orizontale și verticale sunt valabile.</p>",
  "drawPointToolTip": "Faceţi clic pentru a adăuga un punct de origine GRG",
  "missingLayerNameMessage": "Trebuie să introduceți un nume valabil al stratului tematic înainte de a putea publica",
  "parseCoordinatesError": "Imposibil de analizat coordonatele. Verificaţi intrarea.",
  "grgPolarRegionError": "Anvergura GRG este într-o zonă polară. Celulele care corespund regiunii polare nu vor fi create.",
  "grgPolarOriginError": "Punctul de origine GRG nu poate fi într-o regiune polară la crearea unui GRG prin Sistemul de Referință.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Grade zecimale - latitudine/longitudine",
  "DDLongLatNotation": "Grade zecimale - longitudine/latitudine",
  "DDMLatLongNotation": "Grade zecimale minute - latitudine/longitudine",
  "DDMLongLatNotation": "Grade zecimale minute - longitudine/latitudine",
  "DMSLatLongNotation": "Grade minute secunde - latitudine/longitudine",
  "DMSLongLatNotation": "Grade minute secunde - longitudine/latitudine",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - literă bandă",
  "UTMHemNotation": "UTM - emisferă (N/S)"
});