define({
  "_widgetLabel": "العارض الملائم",
  "general": {
    "clear": "مسح",
    "cancel": "إلغاء الأمر",
    "save": "تشغيل",
    "saveAs": "تصدير"
  },
  "saveModel": {
    "save": "تصدير",
    "title": "العنوان: ",
    "summary": "الملخص: ",
    "description": "الوصف: ",
    "tags": "علامات: ",
    "folder": "المجلد: ",
    "homeFolderPattern": "{username} (الرئيسية)",
    "failed": "فشل التصدير."
  },
  "util": {
    "colorRamp": {
      "1": "منخفض للغاية",
      "2": "منخفض جدًا",
      "3": "منخفض",
      "4": "متوسط منخفض",
      "5": "متوسط",
      "6": "متوسط مرتفع",
      "7": "ارتفاع",
      "8": "مرتفع جدًا",
      "9": "مرتفع للغاية",
      "low": "منخفض",
      "high": "ارتفاع",
      "tipPattern": "{label} ({value})",
      "flipCaption": "عكس"
    }
  },
  "wro": {
    "caption": "العارض الملائم",
    "browsePrompt": "خدمة التراكب المُرجّح",
    "selectLayersCaption": "تحديد الطبقات",
    "selectLayers": "الطبقات",
    "designModelCaption": "نموذج التصميم",
    "designModel": "نموذج التصميم",
    "transparency": "الشفافية",
    "visible": "مرئي",
    "total": "إجمالي",
    "unableToLoad": "يتعذّر تحميل النموذج.",
    "projectNotOpen": "لا يوجد أي مشروع مفتوح.",
    "readMore": "قراءة المزيد",
    "validation": {
      "validating": "جار التحقق...",
      "invalidItemCaption": "تحذير بشأن خدمة التراكب المُرجّح",
      "notAnImageService": "هذا العنصر ليس خدمة صور.",
      "notAWroService": "هذا العنصر ليس خدمة تراكب مُرجّح.",
      "undefinedUrl": "عنوان URL للعنصر غير مُعرّف.",
      "inaccessible": "لا يمكن الوصول إلى الخدمة.",
      "generalError": "يتعذر فتح العنصر.",
      "missingFieldPattern": "مطلوب حقل {field}.",
      "notAllowRasterFunction": "يجب تعيين allowRasterFunction ليكون \"صحيح\"",
      "notNearestResampling": "يجب أن يكون defaultResamplingMethod \"الأقرب\"",
      "notIsWeightedOverlayProp": "يجب تعيين خاصية IsWeightedOverlay الرئيسية لتكون \"صحيح\"",
      "invalidLink": "عنوان URL غير صحيح. فشل فتح الموقع للطبقة المحددة.",
      "unexpectedError": "حدثت حالة غير مُتوقعة.",
      "rangeMessage": "يجب أن تكون القيمة بين ${0} و${1}",
      "rangeMessage100": "يجب أن تكون القيمة بين 0 و100",
      "maxLayers": "تسمح الخدمة بـ ${0} طبقة بحد أقصى، ويجب إزالة طبقة أولاً قبل إضافة طبقة جديدة.",
      "notFound": "لم يتم العثور على طبقة ${0} في خدمة التراكب المرجّح",
      "wroServiceNotDefined": "لم يتم تعريف أي خدمة تراكب مُرجّح للنموذج.",
      "overlayLayerOutputInvalid": "قيمة نطاقات إعادة تعيين تراكب طبقة [${0}] لناتج [${1}] مفقودة أو غير صحيحة",
      "overlayLayerInputInvalid": "قيمة نطاقات إعادة تعيين تراكب طبقة [${0}] لأقصى/أدنى مُدخل [${1}] مفقودة أو غير صحيحة",
      "overlayLayerRangesMissing": "تفتقد طبقة تراكب [${0}] لنطاقات تعيين الخريطة",
      "overlayLayerWeight": "يجب أن تضيف أوزان طبقة التراكب حتى 100",
      "overlayLayerRequired": "مطلوب طبقة تراكب واحدة على الأقل",
      "overlayLayerNotDefined": "تراكب الطبقات غير مُعرّف",
      "requiresColormap": "تتطلب وظيفة البيانات النقطية خريطة ألوان، ولكن لا يحتوي النموذج على تعريف خريطة ألوان صحيحة.",
      "createModelError": "خطأ في إنشاء النموذج",
      "invalidModel": "النموذج غير صحيح",
      "imageServiceNotDefined": "طبقة خدمة الصورة غير مُعرفة",
      "imageLayerNotDefined": "طبقة خدمة الصورة غير مُعرفة",
      "histogramNotDefined": "لم يتم تعريف أي وظيفة للمدرج التكراري لخدمة تراكب مُرجّح."
    },
    "colorRampLabel": {
      "Green Yellow Red": "أخضر أصفر أحمر",
      "Red Yellow Green": "أحمر أصفر أخضر",
      "Yellow to Dark Red": "أصفر إلى أحمر داكن",
      "Dark Red to Yellow": "أحمر داكن إلى أصفر",
      "Light Gray to Dark Gray": "رمادي فاتح إلى رمادي داكن",
      "Dark Gray to Light Gray": "رمادي داكن إلى رمادي فاتح",
      "Light Brown to Dark Brown": "بني فاتح إلى بني داكن",
      "Dark Brown to Light Brown": "بني داكن إلى بني فاتح",
      "Full Spectrum - Bright Red to Blue": "طيف كامل - أحمر زاهي إلى أزرق",
      "Full Spectrum - Bright Blue to Red": "طيف كامل - أزرق زاهي إلى أحمر",
      "Partial Spectrum - Yellow to Blue": "طيف جزئي - أصفر إلى أزرق",
      "Partial Spectrum - Blue to Yellow": "طيف جزئي - أزرق إلى أصفر",
      "Yellow-Green to Dark Blue": "أصفر-أخضر فاتح إلى أزرق داكن",
      "Dark Blue to Yellow-Green": "أزرق داكن إلى أصفر-أخضر",
      "Cold to Hot Diverging": "تشعب أزرق إلى حار",
      "Hot to Cold Diverging": "تشعُّب ساخن إلى بارد",
      "Surface - Low to High": "سطح - منخفض إلى مرتفع",
      "Surface - High to Low": "سطح - مرتفع إلى منخفض"
    }
  },
  "tabs": {
    "layers": "الطبقات",
    "model": "النموذج",
    "chart": "الرسم البياني"
  },
  "chart": {
    "prompt": "المعالم",
    "working": "جارِ التحديث...",
    "polygonTool": "رسم مضلع",
    "freehandPolygonTool": "رسم مضلع يدويًا",
    "selectTool": "حدد من طبقة",
    "panTool": "تحريك",
    "clearButton": "مسح",
    "noModelLayer": "لا يوجد نموذج.",
    "noSubjectLayers": "لا تحتوي الخريطة على طبقات مضلع.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});