define({
  "_widgetLabel": "網格化參考圖形",
  "newGRGFromAreaButtonLabel": "從區域定義網格",
  "newGRGFromPointButtonLabel": "從點定義網格",
  "newGRGFromAreaTitle": "從區域定義網格",
  "newGRGFromPointTitle": "從點定義網格",
  "newGRGBySizeButtonLabel": "按維度",
  "newGRGFromRefSystemButtonLabel": "按參考系統",
  "newGRGByTimeLabel": "按時間和速度",
  "newGRGFromNonStandardButtonLabel": "定義非標準網格",
  "newGRGAreaBySizeTitle": "來自按維度之區域的 GRG",
  "newGRGAreaBySizeDefineAreaLabel": "GRG 區域",
  "addGRGAreaPolygonToolTip": "使用多邊形繪製 GRG 區域",
  "addGRGAreaExtentToolTip": "使用範圍繪製 GRG 區域",
  "rotation": "網格旋轉",
  "numberRowsColumnsLabel": "定義列數和欄數",
  "newGRGAreaByRefSystemTitle": "來自按參考系統之區域的 GRG",
  "gridSize": "網格大小",
  "UTMZoneandBand": "網格區域",
  "100000m": "100000 公尺",
  "10000m": "10000 公尺",
  "1000m": "1000 公尺",
  "100m": "100 公尺",
  "10m": "10 公尺",
  "clipGrid": "將網格裁剪至 GRG 區域",
  "newGRGAreaFromNonStandardTitle": "新增 NRG",
  "newGRGPointBySizeTitle": "來自按維度之點的 GRG",
  "newGRGPointByRefSystemTitle": "來自按參考系統之點的 GRG",
  "newGRGPointByTimeTitle": "來自使用時間和速度之點的 GRG",
  "time": "時間",
  "rate": "速度",
  "hours": "小時",
  "minutes": "分鐘",
  "seconds": "秒",
  "ftPerSec": "英呎/秒",
  "ftPerHour": "英呎/小時",
  "kmPerSec": "公里/秒",
  "kmPerHour": "公里/小時",
  "mPerSec": "公尺/秒",
  "mPerHour": "公尺/小時",
  "miPerSec": "英哩/秒",
  "miPerHour": "英哩/小時",
  "nMPerSec": "海浬/秒",
  "nMPerHour": "海浬/小時",
  "settingsTitle": "設定",
  "labelSettingsLabel": "標籤設定",
  "labelSettingsButtonLabel": "配置標籤設定",
  "gridSettingsLabel": "網格設定",
  "gridSettingsButtonLabel": "配置網格設定",
  "transparency": "幻燈片",
  "labelStyle": "標籤樣式",
  "font": "字型",
  "textSize": "文字大小",
  "textColor": "文字顏色",
  "halo": "暈圈",
  "show": "顯示",
  "lockSettings": "應用程式擁有者已鎖定的設定",
  "gridSettings": {
    "cellShape": "儲存格形狀",
    "cellUnits": "儲存格單位",
    "cellOutline": "儲存格輪廓設定",
    "cellFill": "儲存格填充設定",
    "gridReferenceSystem": "參考系統",
    "gridDatum": "基準面: WGS84",
    "labelStartPosition": "標籤原點",
    "labelType": "標籤類型",
    "labelDirection": "標籤方向",
    "gridOrigin": "網格原點",
    "default": "矩形",
    "hexagon": "六角形",
    "miles": "英里",
    "kilometers": "公里",
    "feet": "英呎",
    "meters": "公尺",
    "yards": "碼",
    "nautical-miles": "海浬",
    "lowerLeft": "左下",
    "lowerRight": "右下",
    "upperLeft": "左上",
    "upperRight": "右上",
    "center": "居中對齊",
    "alphaNumeric": "字母-數字",
    "alphaAlpha": "字母-字母",
    "numeric": "數字",
    "horizontal": "水平",
    "vertical": "垂直",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "顯示標籤"
  },
  "publishTitle": "將 GRG 發佈到入口網站",
  "publishGRGBtn": "發佈",
  "GRGLayerName": "發佈的 GRG 圖層名稱",
  "invalidGRGLayerName": "圖層名稱只能包含英數字元和底線",
  "missingGRGLayerName": "您必須輸入 GRG 的名稱",
  "publishingFailedLayerExists": "發佈失敗: 您已擁有名為 {0} 的圖徵服務。請選擇其他名稱。",
  "checkService": "檢查服務: {0}",
  "createService": "建立服務: {0}",
  "unableToCreate": "無法建立: {0}",
  "addToDefinition": "新增至定義: {0}",
  "successfullyPublished": "已成功發佈 Web 圖層{0}管理 Web 圖層",
  "userRole": "無法建立服務，因為使用者沒有權限",
  "createGRGBtn": "建立 GRG",
  "clearGRGBtn": "清除",
  "labelFormat": "標籤格式",
  "helpIconTooltip": "Z: 網格區域指定器 (GZD)\nS: 100,000 公尺網格方形識別 (GSID)\nX: 東移 (X 座標)\nY: 北移 (Y 座標)\n\n範例:\nZSXY 是 15SWC8081751205\nZS X,Y 是 15SWC 80817,51205",
  "addPointToolTip": "新增 GRG 原點",
  "cellWidth": "儲存格寬度 (x)",
  "cellHeight": "儲存格高度 (y)",
  "invalidNumberMessage": "輸入的值無效",
  "invalidRangeMessage": "值必須大於 0",
  "gridAngleInvalidRangeMessage": "值必須在 -89.9 到 89.9 之間",
  "formatIconTooltip": "格式輸入",
  "coordInputLabel": "GRG 原點 (DD)",
  "setCoordFormat": "設定座標格式字串",
  "prefixNumbers": "新增 '+/-' 字首以變為正數和負數",
  "cancelBtn": "取消",
  "applyBtn": "套用",
  "comfirmInputNotation": "確認輸入標記法",
  "notationsMatch": "符合您輸入的標記法，請確認您要使用哪個標記法:",
  "numberOfCellsHorizontal": "水平儲存格數量",
  "numberOfCellsVertical": "垂直儲存格數量",
  "gridAngle": "網格旋轉",
  "tooManyCellsErrorMessage": "您正在嘗試建立一個網格，其中包含 2000 個以上的儲存格。建議您變更網格大小或網格面積來減少正在建立的儲存格數量。",
  "missingParametersMessage": "<p>GRG 建立表單具有無效參數或缺少參數，請確定:</p><ul><li>已繪製 GRG 區域。</li><li>儲存格寬度和高度包含有效值。</li></ul>",
  "missingOriginParametersMessage": "<p>GRG 建立表單具有無效參數或缺少參數，請確定:</p><ul><li>已設定 GRG 原點。</li><li>時間、速度和角度輸入包含有效值。</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG 建立表單具有無效參數或缺少參數。請確定儲存格寬度和高度輸入包含有效值。</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG 建立表單具有無效參數或缺少參數。請確定儲存格水平和垂直數目輸入包含有效值。</p>",
  "drawPointToolTip": "按一下以新增 GRG 原點",
  "missingLayerNameMessage": "您必須先輸入有效的圖層名稱，之後才能發佈",
  "parseCoordinatesError": "無法剖析座標。請檢查您的輸入。",
  "grgPolarRegionError": "GRG 範圍位於極地內。無法建立位於極地內的儲存格。",
  "grgPolarOriginError": "按參考系統建立 GRG 時，GRG 原點不可位於極地內。",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十進位度 - 緯度/經度",
  "DDLongLatNotation": "十進位度 - 經度/緯度",
  "DDMLatLongNotation": "度十進制分 - 緯度/經度",
  "DDMLongLatNotation": "度十進制分 - 經度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/經度",
  "DMSLongLatNotation": "度分秒 - 經度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 頻段字母",
  "UTMHemNotation": "UTM - 半球 (N/S)"
});