define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Váš online účet nemá přístupová práva k vytváření nebo úpravě dat.",
  "widgetActive": "Aktivní",
  "widgetNotActive": "Neaktivní",
  "pressStr": "Stisknutím ",
  "ctrlStr": " CTRL ",
  "snapStr": " aktivujete přichytávání.",
  "noAvailableTempaltes": "Žádné šablony nejsou k dispozici.",
  "editorCache": " – cache editoru",
  "presetFieldAlias": "Pole",
  "presetValue": "Přednastavená hodnota",
  "usePresetValues": " Použít přednastavené hodnoty (pouze nové prvky)",
  "editGeometry": " Upravit geometrii",
  "savePromptTitle": "Uložit prvek",
  "savePrompt": "Přejete si uložit aktuální prvek?",
  "deletePromptTitle": "Odstranit prvek",
  "deletePrompt": "Určitě chcete odstranit vybraný prvek?",
  "attachmentLoadingError": "Při nahrávání příloh došlo k chybě.",
  "attachmentSaveDeleteWarning": "Varování: Změny příloh se automaticky uloží.",
  "autoSaveEdits": "Automaticky uloží úpravu",
  "addNewFeature": "Vytvořit novou funkci",
  "featureCreationFailedMsg": "Nelze vytvořit nový záznam/funkci",
  "noRelatedFeatureFoundMsg": "Nebyly nalezeny žádné související záznamy/funkce",
  "relatedItemTitle": "Související tabulka/vrstva",
  "invalidRelationShipMsg": "Ujistěte se prosím, že primární klíčové pole: ‚${parentKeyField}‘ obsahuje platnou hodnotu",
  "pendingFeatureSaveMsg": "Před tím, než vytvoříte související funkci, prosím uložte úpravy funkce.",
  "attachmentsRequiredMsg": "(*) Jsou vyžadovány přílohy.",
  "filterEditor": {
    "all": "Všechny",
    "noAvailableTempaltes": "Žádné šablony nejsou k dispozici.",
    "searchTemplates": "Vyhledávání šablon"
  },
  "invalidConfiguration": "Widget není nakonfigurován nebo se vrstvy v konfiguraci již nenacházejí v mapě. Spusťte aplikaci v režimu tvorby a upravte konfiguraci widgetu.",
  "geometryServiceURLNotFoundMSG": "Nelze načíst adresu URL služby geometrie"
});