define({
  "chartTasks": "Zadaci grafikona",
  "addNew": "Dodaj novi",
  "addNewTip": "Dodaj novi zadatak grafikona",
  "name": "Naziv",
  "set": "Postavi",
  "setDataSource": "Postavite izvor podataka",
  "generalSettingsTip": "Postavite izvor podataka, naslov i opis za grafikone.",
  "chartModeSettingTip": "Odaberite način analiziranja i prikazivanja podataka putem grafikona.",
  "detailsSettingTip": "Postavite izgled grafikona određivanjem vrsta i boje i vrijednosti koje treba prikazati:",
  "symbolSettingTip": "Postavite prikaz karte za podatke grafikona.",
  "addFilterTip": "Dodaj filtar ovim podacima",
  "dataSource": "Izvor podataka",
  "noResults": "Nema geoobjekta.",
  "chartTitle": "Naslov grafikona",
  "description": "Opis",
  "chartingMode": "Prikaz grafikona",
  "featureOption": "Prikaži vrijednosti geoobjekata po geoobjektu",
  "categoryOption": "Prikaži vrijednosti po kategoriji",
  "countOption": "Prikaži broj geoobjekata po kategoriji",
  "fieldOption": "Prikaži atributne vrijednosti kao grafikone",
  "category": "Kategorija",
  "axisLabel": "Oznaka kategorije",
  "categoryField": "Polje kategorije",
  "operation": "Radnja",
  "originalOption": "Upotrijebi izvorne vrijednosti",
  "sumOption": "Zbroj",
  "averageOption": "Prosjek",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "valueFields": "Polja vrijednosti",
  "moveUp": "Premjesti gore",
  "moveDown": "Premjesti dolje",
  "sortOrder": "Sortiraj grafikone prema oznakama kategorija",
  "ascending": "Uzlazno",
  "descending": "Silazno",
  "chartType": "Vrsta grafikona",
  "column": "Stupčasti grafikon",
  "bar": "Trakasti grafikon",
  "line": "Linijski grafikon",
  "pie": "Tortni grafikon",
  "chartColor": "Boja grafikona",
  "showDataLabels": "Prikaži oznake podataka",
  "setSymbol": "Simbol za odabir",
  "setHighLightColor": "Boja isticanja",
  "settings": "Postavke",
  "mapInterationOptions": "Opcije interakcije s kartom",
  "preview": "Pretpregled",
  "ok": "U redu",
  "cancel": "Odustani",
  "close": "Zatvori",
  "setFilterTip": "Ispravno postavite filtar. ",
  "setChartTitleTip": "Postavite naslov grafikona.",
  "setChartTypeTip": "Odaberite barem jednu vrstu grafikona.",
  "setDataFieldTip": "Odaberite barem jedno polje vrijednosti.",
  "setOutputFieldTip": "Postavite izlazna polja.",
  "count": "Broj",
  "label": "Oznaka",
  "horizontalAxis": "Vodoravna os",
  "verticalAxis": "Okomita os",
  "dataLabels": "Oznake podataka",
  "color": "Boja",
  "colorful": "Raznobojno",
  "monochromatic": "Monokromatski",
  "noTaskTip": "Kliknite Dodaj novi za dodavanje zadatka grafikona",
  "info": "Informacije",
  "charts": "Grafikoni",
  "options": "Opcije",
  "taskName": "Naziv zadatka",
  "summary": "Sažetak",
  "resultDescription": "Opis rezultata",
  "spatialFilterTip": "Odaberite prostorne filtre iz widgeta za ograničavanje rezultata.",
  "defaultOption": "Zadano",
  "useCurrentExtentTip": "Djelomično ili potpuno unutar trenutačnog obuhvata karte",
  "useDrawGraphicTip": "Djelomično ili potpuno unutar oblika nacrtanog na karti",
  "useFeaturesTip": "Na temelju njihovih lokacija u odnosu na geoobjekte u drugom sloju",
  "noSpatialLimitTip": "Nemoj prostorno ograničiti rezultate",
  "drawingTools": "Alati za crtanje",
  "bufferSettings": "Postavke pojasa",
  "defaultDistance": "Zadana udaljenost",
  "bufferDistance": "Veličina pojasa",
  "defaultUnit": "Zadana jedinica",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "availableSpatialRelationships": "Dostupne prostorne relacije",
  "setSpatialRelationships": "Postavi prostorne relacije",
  "availability": "Dostupnost",
  "relationship": "Relacija",
  "actions": "Radnje",
  "intersect": "presjek",
  "contain": "sadrži",
  "areContainedIn": "sadržano u",
  "cross": "križanje",
  "envelopeIntersect": "presjek omotnicom",
  "overlap": "preklapanje",
  "areOverlapped": "preklapaju se",
  "touche": "dodiruju se",
  "within": "unutar",
  "areWithin": "unutar su",
  "indexIntersect": "presjek indeksa"
});