define({
  "tabs_section_Label": "Guias",
  "addTab": "Adicionar Guia",
  "layerName": "Camada",
  "layerType": "Tipo de Análise",
  "layerLabel": "Rótulo",
  "actions": "Ações",
  "closest": "Feição Mais Próxima",
  "proximity": "Proximidade",
  "summary": "Resumo",
  "select_lbl": "-- Selecionar --",
  "general_setting_Label": "Configurações Gerais",
  "units_text_lbl": "Unidades de distância",
  "maximum_distance_lbl": "Distância máxima da feição mais próxima",
  "buffer_text_lbl": "Rótulo de buffer",
  "buffer_lbl": "Distância do Buffer",
  "buffer_max_lbl": "Distância de buffer máxima",
  "buffer_min_lbl": "Distância de buffer mínima",
  "buffer_default_lbl": "Distância de buffer padrão",
  "not_less_than_max": "A distância deve ser inferior à distância máxima do buffer",
  "not_between": "A distância deve estar entre a distância mínima e máxima do buffer",
  "not_more_than_min": "A distância deve ser maior que a distância mínima do buffer",
  "not_valid_number": "Deve ser um número válido",
  "invalid_value": "O valor ${type} é inválido",
  "routing_checkBox": "Ativar roteamento",
  "weather_Label": "Configurações de Tempo",
  "weather_checkBox": "Habilitar tempo",
  "weather_map_layers": "Selecionar camadas de tempo...",
  "selected_map_layers": " camadas de tempo selecionadas",
  "instruction_weather": "Exibir informações de tempo no painel.",
  "instruction_weather_layers": "Exibir camadas de tempo adicionais.",
  "instruction_weather_metric": "Exibir valores de métrica/padrão.",
  "selectLayers": "Selecionar camadas de tempo",
  "weather_removed_message": "As opções de tempo não estão mais disponíveis para este widget.",
  "currentlySelectedLayer": "Selecionar de camadas do mapa",
  "missingTabLabel": "Pelo menos uma guia está sem rótulo",
  "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
  "selectFields": "Selecionar Campos",
  "addField": "Adicionar Campo",
  "sum": "Soma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Média",
  "count": "CONTAGEM",
  "area": "ÁREA",
  "length": "COMPRIMENTO",
  "count_checkBox": "Exibir contagem da feição",
  "area_checkBox": "Exibir soma da área",
  "length_checkBox": "Exibir soma do comprimento",
  "max_records": "Limite máximo alcançado",
  "save_label": "Opções de Salvar",
  "save_checkbox": "Habilitar salvar",
  "report_label": "Opções do Relatório",
  "report_checkbox": "Habilitar relatório",
  "csv_label": "Opções do CSV",
  "csv_checkbox": "Exportar todos os campos",
  "display_label": "Opções de Visualização",
  "display_checkbox": "Exibir feições de resumo",
  "snapshot_label": "Opções de imagem instantânea",
  "snapshot_checkbox": "Habilitar imagem instantânea",
  "must_select_template": "Selecione um dos modelos de edição em Opções de Salvar.",
  "count_label": "Contagem de rótulo",
  "area_label": "Rótulo de área",
  "length_label": "Rótulo de comprimento",
  "invalid_string_width": "O valor é muito longo. ",
  "layer_type_not_supported": "Tipo de Camada Não Suportado",
  "groupedSummary": "Contagens Agrupadas",
  "groupByField": "Agrupar por Campo",
  "labelType": "Anexar Rótulo",
  "prefix": "Como Prefixo",
  "suffix": "Como Sufixo",
  "need_group_field": "Utilize a ação editar para definir a opção Agrupar Por Campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Ações",
  "save_point_checkbox": "Salvar pontos",
  "save_line_checkbox": "Salvar linhas",
  "save_poly_checkbox": "Salvar polígonos",
  "no_valid_popup_fields": "Nenhum campo válido no pop-up. Utilize a ação de edição para definir um campo.",
  "no_valid_fields": "Nenhum campo válido. Utilize a ação de edição para definir as opções de visualização.",
  "incident_label": "Rótulo de guia",
  "locate_incident_label": "Rótulo de área de interesse",
  "incident": "Incidente",
  "locate_incident": "Localizar Incidente",
  "buffer_value": "Distância do Buffer",
  "tab_options": "Análise",
  "export_options": "Saída",
  "instruction_save": "Salva o local para um serviço da feição.",
  "instruction_snapshot": "Cria um mapa da web com base na localização.",
  "instruction_report": "Cria um relatório impresso da localização.",
  "instruction_all_fields": "Exporta todos os campos com download do CSV.",
  "data_label": "Configurações da Saída de Dados",
  "layer_error": "Camada ausente ou inválida.",
  "visibility_checkBox": "Desabilitar gerenciamento de visibilidade da camada",
  "downloadTab": {
    "reportLegend": "Configurações do Relatório",
    "textColorLabel": "Selecionar cor para títulos de coluna",
    "setButtonLabel": "Configurar",
    "printGPServiceLabel": "Imprimir URL do Serviço",
    "logoLabel": "Logotipo",
    "logoChooserHint": "Clique no ícone de imagem para alterar a imagem",
    "footnoteLabel": "Nota de rodapé"
  }
});