define({
  "enableUndoRedo": "Włącz opcje Cofnij/Ponów",
  "toolbarVisible": "Widoczny pasek narzędziowy",
  "toolbarOptions": "Opcje paska narzędziowego",
  "mergeVisible": "Połącz",
  "cutVisible": "Wytnij",
  "reshapeVisible": "Przekształć",
  "back": "Wstecz",
  "label": "Warstwa",
  "edit": "Edytowalne",
  "update": "Wyłącz aktualizację geometrii",
  "fields": "Pola",
  "actions": "Operacje",
  "editpageName": "Nazwa",
  "editpageAlias": "Alias",
  "editpageVisible": "Widoczne",
  "editpageEditable": "Edytowalne",
  "noLayers": "Brak warstw obiektu możliwych do edycji",
  "configureFields": "Skonfiguruj pola warstwy",
  "useFilterEdit": "Użyj szablonu filtrów obiektu",
  "display": "Wyświetl",
  "autoApplyEditWhenGeometryIsMoved": "Zastosuj zmianę automatycznie, gdy geometria zostanie przesunięta",
  "snappingTolerance": "Ustaw tolerancję dociągania w pikselach",
  "popupTolerance": "Ustaw tolerancję okna podręcznego edycji atrybutów w pikselach",
  "stickyMoveTolerance": "Ustaw tolerancję przenoszenia z opóźnieniem",
  "usingSaveButton": "Nie stosuj zmian do atrybutów przed kliknięciem przycisku Zapisz"
});