define({
  "_widgetLabel": "Koordinatenkonvertierung",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dezimalgrad – Breitengrad/Längengrad",
  "DDLongLatNotation": "Dezimalgrad – Längengrad/Breitengrad",
  "DDMLatLongNotation": "Grad Dezimalminuten – Breitengrad/Längengrad",
  "DDMLongLatNotation": "Grad Dezimalminuten – Längengrad/Breitengrad",
  "DMSLatLongNotation": "Grad, Minuten, Sekunden – Breitengrad/Längengrad",
  "DMSLongLatNotation": "Grad, Minuten, Sekunden – Längengrad/Breitengrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbuchstabe",
  "UTMHemNotation": "UTM – Hemisphäre (N/S)",
  "formatInput": "Eingabe formatieren",
  "copyAll": "Alle kopieren",
  "copySuccessful": "Kopieren erfolgreich",
  "copyFailed": "Kopiervorgang kann nicht ausgeführt werden. Verwenden Sie alternativ dazu die Tasten Strg+C.",
  "parseCoordinatesError": "Koordinaten können nicht geparst werden. Überprüfen Sie Ihre Eingabe.",
  "comfirmInputNotation": "Eingegebene Bezeichnung bestätigen",
  "latLongWarningMessage": "Die eingegebene Koordinate weist sowohl einen Präfix als auch einen Suffix für den Wert des Breiten- und Längengrads auf. Die ausgegebene Koordinate basiert auf dem Präfix.",
  "inputLabel": "Eingabe",
  "outputLabel": "Ausgabe",
  "cancelButtonLabel": "Abbrechen",
  "applyButtonLabel": "Übernehmen",
  "posNegPrefixLabel": "Positiven und negativen Zahlen ein \"+/-\"-Präfix hinzufügen",
  "editCoordinateDialogTitle": "Zeichenfolge für Koordinatenformat festlegen",
  "rememberDecisionLabel": "Meine Eingabe speichern und nicht erneut abfragen.<br/>",
  "coordinateInputLabel": "Geben Sie Koordinaten ein oder klicken Sie auf die Karte.",
  "zoomLabel": "Zoomen",
  "multipleNotationLabel": "Es wurden Bezeichnungen gefunden, die Ihrer Eingabe entsprechen. Bitte bestätigen Sie, welche Sie verwenden möchten:",
  "copyToClipboard": "In Zwischenablage kopieren",
  "formatOutput": "Formatausgabe",
  "addNewNotation": "Neue Notation hinzufügen",
  "notationAddedMessage": "Neue Notation hinzugefügt",
  "addLabel": "Hinzufügen",
  "removeCoordinate": "Koordinate entfernen",
  "expandOutput": "Ausgabe erweitern",
  "latitudeLabel": "Breitengrad",
  "longitudeLabel": "Längengrad",
  "quadrantLabel": "Quadrant",
  "keyLabel": "Schlüssel",
  "fifteenDegreeLabel": "15° Quadrant",
  "oneDegreeLabel": "1° Quadrant",
  "eastingLabel": "Rechtswert",
  "northingLabel": "Hochwert",
  "zoneLabel": "Zone",
  "bandLabel": "Band",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Gitternetzquadrat",
  "hemisphereLabel": "Hemisphäre"
});