define({
  "_widgetLabel": "Editor inteligente",
  "_featureAction_SmartEditor": "Editor inteligente",
  "noEditPrivileges": "Su cuenta no tiene permiso para crear o modificar datos.",
  "widgetActive": "Activa",
  "widgetNotActive": "No activa",
  "pressStr": "Pulsar ",
  "ctrlStr": " CTRL ",
  "snapStr": " para activar la alineación",
  "noAvailableTempaltes": "No hay plantillas disponibles",
  "editorCache": " - Caché del editor",
  "presetFieldAlias": "Campo",
  "presetValue": "Valor predefinido",
  "usePresetValues": " Usar valores predefinidos (solo nuevas entidades)",
  "editGeometry": " Editar geometría",
  "savePromptTitle": "Guardar entidad",
  "savePrompt": "¿Desea guardar la entidad actual?",
  "deletePromptTitle": "Eliminar entidad",
  "deletePrompt": "¿Está seguro de que desea eliminar la entidad seleccionada?",
  "attachmentLoadingError": "Error al cargar adjuntos",
  "attachmentSaveDeleteWarning": "Advertencia: los cambios realizados en los adjuntos se guardan automáticamente",
  "autoSaveEdits": "Guarda la edición automáticamente",
  "addNewFeature": "Crear entidad nueva",
  "featureCreationFailedMsg": "Imposible crear un nuevo registro/entidad",
  "noRelatedFeatureFoundMsg": "No se encontró ningún registro/entidad relacionado",
  "relatedItemTitle": "Tabla/capa relacionada",
  "invalidRelationShipMsg": "Asegúrese de que el campo clave principal: '${parentKeyField}' tenga un valor válido",
  "pendingFeatureSaveMsg": "Guarde las ediciones de las entidades antes de crear una entidad relacionada.",
  "attachmentsRequiredMsg": "(*) Se requieren adjuntos.",
  "filterEditor": {
    "all": "Todo",
    "noAvailableTempaltes": "No hay plantillas disponibles",
    "searchTemplates": "Buscar plantillas"
  },
  "invalidConfiguration": "El widget no está configurado o las capas de la configuración ya no están en el mapa. Abra la aplicación en el modo de builder y vuelva a configurar el widget.",
  "geometryServiceURLNotFoundMSG": "No se puede obtener la dirección URL del servicio de geometría"
});