define({
  "_widgetLabel": "Prijavi geoobjekat",
  "select": "Selektuj",
  "draw": "Nacrtaj",
  "chooseALayer": "Izaberite sloj",
  "clickAFeature": "Kliknite na geoobjekat na mapi da biste ga selektovali.",
  "loadingFeatures": "Dobijanje detalja selektovanog geoobjekta...",
  "errorTitle": "Greška",
  "errorIdentify": "Identifikacija greške geoobjekata. Proverite log konzole za detalje.",
  "infoWindowTitle": "Detalji",
  "layerLabel": "Ime sloja",
  "reviewStatusLabel": "Status pregledanja",
  "selectReviewStatusAdd": "Dodaj geoobjekat",
  "selectReviewStatusDelete": "Obriši geoobjekat",
  "selectReviewStatusMove": "Pomeri geoobjekat",
  "selectReviewStatusReshape": "Preoblikuj geoobjekat",
  "drawReviewStatusMissing": "Nedostajući geoobjekat/geoobjekti",
  "drawReviewStatusPosition": "Greška pozicioniranja",
  "drawReviewStatusShape": "Greška oblika",
  "drawReviewStatusAttribute": "Greška atributa",
  "notesLabel": "Napomene",
  "severityLabel": "Ozbiljnost",
  "reportedByLabel": "Prijavljeno od strane",
  "reportedByDefault": "anonimno",
  "reportButton": "Prijava",
  "reportMessage": "Prijava primljena",
  "errorReportMessage": "Došlo je do greške prilikom prijavljivanja geoobjekta",
  "drawErrorInstructions": "Izaberite tačku, liniju ili poligon i nacrtajte geometriju greške na mapi:",
  "errorMapService": "Došlo je do greške pri dobijanju informacija servisa mape",
  "noFeatureSelected": "Nema pronađenih geoobjekata na lokaciji na koju ste kliknuli",
  "selectFeatureMapPoint": "Kliknite da biste selektovali geoobjekat",
  "drawFeatureMapPoint": "Kliknite da biste dodali tačku",
  "popupMessage": "Poruka",
  "popupError": "Greška",
  "manyFeaturesSelected": "Pronađeno je više od jednog geoobjekta. Uveličajte i selektujte geoobjekat za prijavljivanje."
});