define({
  root: ({
    _widgetLabel: "Smart Editor",
    _featureAction_SmartEditor: "Smart Editor",
    noEditPrivileges: "Your account does not have permission to create or modify data.",
    widgetActive:"Active",
    widgetNotActive:"Not Active",
    pressStr: "Press ",
    ctrlStr: " CTRL ",
    snapStr: " to enable snapping",
    noAvailableTempaltes: "No available templates",
    editorCache: " - Editor Cache",
    presetFieldAlias: "Field",
    presetValue: "Preset Value",
    usePresetValues: " Use Preset Values (New features only)",
    editGeometry: " Edit Geometry",
    savePromptTitle: "Save feature",
    savePrompt: "Would you like to save the current feature?",
    deletePromptTitle: "Delete feature",
    deletePrompt: "Are you sure you want to delete the selected feature?",
    attachmentLoadingError: "Error uploading attachments",
    attachmentSaveDeleteWarning: "Warning: Changes to attachments are saved automatically",
    autoSaveEdits: "Saves the edit automatically",
    addNewFeature : "Create new feature",
    featureCreationFailedMsg : "Cannot create a new record/feature",
    noRelatedFeatureFoundMsg : "No Related Records/Features found",
    relatedItemTitle: "Related Table/Layer",
    invalidRelationShipMsg: "Please make sure the primary key field: \'${parentKeyField}\' has a valid value",
    pendingFeatureSaveMsg : "Please save the feature edits before creating a related feature.",
    attachmentsRequiredMsg :"(*) Attachments are required.",
    filterEditor:{
      all: "All",
      noAvailableTempaltes: "No available templates",
      searchTemplates: "Search Templates"
    },
    invalidConfiguration: "Widget is either not configured or the layers in the configuration are no longer in the map.  Please open the app in the builder mode and reconfigure the widget.",
    geometryServiceURLNotFoundMSG: "Unable to get Geometry Service URL"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});