define({
  "_widgetLabel": "Chuyển đổi tọa độ",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Độ thập phân - Vĩ độ/Kinh độ",
  "DDLongLatNotation": "Độ thập phân - Kinh độ/Vĩ độ",
  "DDMLatLongNotation": "Độ thập phân phút - Vĩ độ/Kinh độ",
  "DDMLongLatNotation": "Độ thập phân phút - Kinh độ/Vĩ độ",
  "DMSLatLongNotation": "Độ thập phân giây - Vĩ độ/Kinh độ",
  "DMSLongLatNotation": "Độ thập phân giây - Kinh độ/Vĩ độ",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Chữ cái dải sóng",
  "UTMHemNotation": "UTM - Bán cầu (Bắc/Nam)",
  "formatInput": "Định dạng đầu vào",
  "copyAll": "Sao chép tất cả",
  "copySuccessful": "Sao chép thành công",
  "copyFailed": "Không thể sao chép. Xin hãy sử dụng ctrl+c để thay thế.",
  "parseCoordinatesError": "Không thể dán tọa độ. Vui lòng kiểm tra thông tin của bạn.",
  "comfirmInputNotation": "Xác nhận Ký hiệu đầu vào",
  "latLongWarningMessage": "Tọa độ đầu vào đã được phát hiện vì có cả tiền tố và hậu tố cho giá trị vĩ độ hoặc kinh độ, tọa độ trả lại dựa trên tiền tố.",
  "inputLabel": "Đầu vào",
  "outputLabel": "Đầu ra",
  "cancelButtonLabel": "Hủy",
  "applyButtonLabel": "Áp dụng",
  "posNegPrefixLabel": "Thêm tiền tố \"+/-\" vào số dương và số âm",
  "editCoordinateDialogTitle": "Thiết lập chuỗi định dạng tọa độ",
  "rememberDecisionLabel": "Nhớ quyết định của tôi và không thông báo nữa.<br/>",
  "coordinateInputLabel": "Nhập tọa độ hoặc nhấp vào bản đồ",
  "zoomLabel": "Thu phóng",
  "multipleNotationLabel": "tìm thấy các ký hiệu khớp với thông tin của bạn. Vui lòng xác nhận thông tin mà bạn muốn sử dụng:",
  "copyToClipboard": "Sao chép vào bảng tạm",
  "formatOutput": "Định dạng đầu ra",
  "addNewNotation": "Thêm ký hiệu mới",
  "notationAddedMessage": "Chú thích mới được thêm",
  "addLabel": "Thêm",
  "removeCoordinate": "Xóa tọa độ",
  "expandOutput": "Mở rộng đầu ra",
  "latitudeLabel": "Vĩ độ",
  "longitudeLabel": "Kinh độ",
  "quadrantLabel": "Góc tọa độ",
  "keyLabel": "Chính",
  "fifteenDegreeLabel": "15Â° Quad",
  "oneDegreeLabel": "1Â° Quad",
  "eastingLabel": "Hướng đông",
  "northingLabel": "Hướng bắc",
  "zoneLabel": "Khu vực",
  "bandLabel": "Dải sóng",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Lưới vuông",
  "hemisphereLabel": "Bán cầu"
});