define({
  "layerSelect": "Valige pildikiht",
  "displayMeasureResultInPopup": "Kuva mõõtmise tulemused hüpikaknas",
  "angularUnitSelect": "Vaikimisi mõõtühik nurkadele",
  "linearUnitSelect": "Vaikimisi lineaarne mõõtühik",
  "areaUnitSelect": "Pindala vaikeühik",
  "displayOperationSelect": "Vali mõõtmistoimingud",
  "errorSectionMessage": "Ükski kiht ei toeta mõõtmise funktsioone.",
  "unitLabel": {
    "esriInches": "Tollid",
    "esriFeet": "Jalad",
    "esriYards": "Jardid",
    "esriMiles": "Miilid",
    "esriNauticalMiles": "Meremiilid",
    "esriMillimeters": "millimeeter",
    "esriCentimeters": "Sentimeetrid",
    "esriDecimeters": "detsimeetrit",
    "esriMeters": "Meetrid",
    "esriKilometers": "Kilomeetrid",
    "esriDURadians": "Radiaanid",
    "esriDUDecimalDegrees": "Kraadi",
    "esriSquareInches": "Ruuttollides",
    "esriSquareFeet": "Ruutjalga",
    "esriSquareYards": "Ruutjardi",
    "esriAcres": "Aakrid",
    "esriSquareMiles": "Ruutmiili",
    "esriSquareMillimeters": "Ruutmillimeetrites",
    "esriSquareCentimeters": "Ruutsentimeetrites",
    "esriSquareDecimeters": "Ruutdetsimeetrites",
    "esriSquareMeters": "Ruutmeetrit",
    "esriAres": "Aarides",
    "esriHectares": "Hektarid",
    "esriSquareKilometers": "Ruutkilomeetrit"
  },
  "operationLabel": {
    "esriMensurationPoint": "Asukoht",
    "esriMensurationDistanceAndAngle": "Vahekaugus ja nurk",
    "esriMensurationAreaAndPerimeter": "Pindala ja ümbermõõt",
    "esriMensurationHeightFromBaseAndTop": "Kõrgus: alt tipuni",
    "esriMensurationHeightFromBaseAndTopShadow": "Kõrgus: alt tipu varjuni",
    "esriMensurationHeightFromTopAndTopShadow": "Kõrgus: tipust tipu varjuni",
    "esriMensurationCentroid": "Tsentroid",
    "esriMensurationPoint3D": "Asukoht (3D)",
    "esriMensurationDistanceAndAngle3D": "Vahekaugus ja nurk (3D)",
    "esriMensurationAreaAndPerimeter3D": "Pindala ja ümbermõõt (3D)",
    "esriMensurationCentroid3D": "Tsentroid (3D)"
  }
});