define({
  "serviceUrl": "Establecer dirección URL del servicio:",
  "minIntSpacingLabel": "Tamaño mínimo de cuadrícula",
  "lineOpacityLabel": "Opacidad de línea",
  "labelOpacityLabel": "Opacidad de etiqueta",
  "centerLabelOpacityLabel": "Opacidad de etiqueta central",
  "gridZonePlacementLabel": "Colocación de etiqueta en zona de cuadrícula",
  "verticalLineLabels": "Etiquetas de línea vertical",
  "styleHeaderLabel": "Estilo",
  "indexHeaderLabel": "Componente de cuadrícula",
  "colorHeaderLabel": "Color",
  "fontSizeHeaderLabel": "Tamaño de fuente",
  "lineWidthHeaderLabel": "Ancho de línea",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertical",
  "upperLeftLabel": "Superior izquierda",
  "upperRightLabel": "Superior derecha",
  "lowerLeftLabel": "Inferior izquierda",
  "lowerRightLabel": "Inferior derecha",
  "centerLabel": "Centro",
  "errorMessage": "La página de configuración contiene errores. Arréglela antes de guardar.",
  "checkBoxLabel": "Visualizar la cuadrícula al cerrar el widget",
  "checkBoxLabelDashboard": "Visualizar cuadrícula",
  "gzd": "Designador de zona de cuadrícula (GZD)",
  "gsid": "Identificación de cuadrado de cuadrícula de 100.000 metros (GSID)",
  "grid10k": "Líneas de cuadrícula de 10.000 metros",
  "grid1k": "Líneas de cuadrícula de 1.000 metros",
  "grid100m": "Líneas de cuadrícula de 100 metros",
  "grid10m": "Líneas de cuadrícula de 10 metros",
  "switchBasemap": "Cambiar mapa base"
});