define({
  "symbolologyTabLabel": "Konfigūruoti simbolizaciją",
  "facilitiesDescription": "Paslaugų sluoksniai",
  "demographicsDescription": "Demografiniai sluoksniai",
  "settingsTitle": "Parametrai",
  "spillLocationLabel": "Išsiliejimo vieta",
  "spillLocationButtonLabel": "Konfigūruoti išsiliejimo vietos nustatymus",
  "IISettingsLabel": "Pradinė lokalizacijos zona",
  "IIButtonLabel": "Konfigūruoti pradinės lokalizacijos zonos nustatymus",
  "PASettingsLabel": "Apsaugos zona",
  "PAButtonLabel": "Konfigūruoti apsauginio veiksmo nustatymus",
  "downwindSettingsLabel": "Pavėjinė zona",
  "downwindButtonLabel": "Konfigūruoti pavėjinės zonos nustatymus",
  "fireSettingsLabel": "Gaisro lokalizavimo zona",
  "fireButtonLabel": "Konfigūruoti gaisro lokalizacijos zonos nustatymus",
  "bleveSettingsLabel": "BLEVE lokalizavimo zona",
  "bleveButtonLabel": "Konfigūruoti BLEVE zonos nustatymus",
  "transparency": "Permatomumas",
  "outline": "Kontūras",
  "fill": "Užpildas (spalva taikoma, tik kai pasirinktas vientisas stilius)",
  "style": "Stilius",
  "lineStyles": {
    "esriSLSDash": "Brūkšnys",
    "esriSLSDashDot": "Brūkšnys taškas",
    "esriSLSDashDotDot": "Brūkšnys taškas taškas",
    "esriSLSDot": "Taškas",
    "esriSLSLongDash": "Ilgas brūkšnys",
    "esriSLSLongDashDot": "Ilgas brūkšnys taškas",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trumpas brūkšnys",
    "esriSLSShortDashDot": "Trumpas brūkšnys taškas",
    "esriSLSShortDashDotDot": "Trumpas brūkšnys taškas taškas",
    "esriSLSShortDot": "Trumpas taškas",
    "esriSLSSolid": "Vientisas"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atgal",
    "esriSFSCross": "Kryžius",
    "esriSFSDiagonalCross": "Įstrižai",
    "esriSFSForwardDiagonal": "Pirmyn",
    "esriSFSHorizontal": "Horizontali",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vientisas",
    "esriSFSVertical": "Vertikali"
  }
});