define({
  "labelBookmarkName": "वर्तमान व्यू को बुकमार्क करें",
  "labelPlay": "सभी को चलाएँ",
  "labelStop": "रुकें",
  "labelDelete": "हटाएँ",
  "placeholderBookmarkName": "बुकमार्क का नाम",
  "errorNameExist": "बुकमार्क मौजूद है!",
  "errorNameNull": "अमान्य बुकमार्क नाम!",
  "editTip": "बुकमार्क संपादित करें",
  "exitEditTip": "संपादन मोड से बाहर निकलें",
  "syncTip": "समन्वयित करें",
  "cardsTips": "ग्रिड दृश्य",
  "listTips": "सूची दृश्य",
  "addBtn": "जोड़ें",
  "deleteBtn": "हटाएँ",
  "changeThumbnailTip": "थंबनेल बदलें",
  "dragReorderTip": "पकड़कर रखें और रिकॉर्डर तक खींचें",
  "deleteBtnTip": "बुकमार्क हटाएँ",
  "editBtnTip": "बुकमार्क संपादित करें",
  "withVisibility": "लेयर दृश्यता के साथ",
  "searchBookmark": "खोजें",
  "bookmarksFromConfig": "पूर्व निर्मित बुकमार्क",
  "bookmarksFromCache": "स्थानीय अस्थाई बूकमार्क",
  "notice": "सूचना",
  "changeNoticeTips": "बदलावों को केवल आपके ब्राउज़र के संचय में सहेजा जाएगा। विजेट के बीच समन्वयित करें और जैसे ही आप संशोधन कर लेते हैं, उसका कॉन्फ़िगरेशन डिस्कनेक्ट कर दिया जाता है।",
  "syncNoticeTips": "इससे आपके सभी संशोधन मिट जाएँगे और कॉन्फ़िगर किए गए बुकमार्क बहाल हो जाएँगे।",
  "dontShowAgain": "फिर से न दिखाएँ",
  "saveVisibility": "लेयर दृश्यता सहेजें",
  "_widgetLabel": "बुकमार्क"
});