define({
  "serviceUrl": "서비스 URL 설정:",
  "minIntSpacingLabel": "최소 격자 크기",
  "lineOpacityLabel": "라인 불투명도",
  "labelOpacityLabel": "레이블 불투명도",
  "centerLabelOpacityLabel": "가운데 레이블 불투명도",
  "gridZonePlacementLabel": "그리드 구역 레이블 배치",
  "verticalLineLabels": "수직 라인 레이블",
  "styleHeaderLabel": "스타일",
  "indexHeaderLabel": "격자 컴포넌트",
  "colorHeaderLabel": "색상",
  "fontSizeHeaderLabel": "글꼴 크기",
  "lineWidthHeaderLabel": "라인 너비",
  "horizontalLabel": "수평",
  "verticalLabel": "수직",
  "upperLeftLabel": "왼쪽 상단",
  "upperRightLabel": "오른쪽 상단",
  "lowerLeftLabel": "왼쪽 하단",
  "lowerRightLabel": "오른쪽 하단",
  "centerLabel": "가운데",
  "errorMessage": "구성 페이지에 오류가 포함되어 있습니다. 오류를 수정한 후에 저장하세요.",
  "checkBoxLabel": "위젯이 닫히면 그리드 표시",
  "checkBoxLabelDashboard": "디스플레이 격자",
  "gzd": "Grid Zone Designator(GZD)",
  "gsid": "100,000미터 Grid Square Identification(GSID)",
  "grid10k": "10,000미터 격자 라인",
  "grid1k": "1,000미터 격자 라인",
  "grid100m": "100미터 격자 라인",
  "grid10m": "10미터 격자 라인",
  "switchBasemap": "베이스맵 전환"
});