define({
  "_widgetLabel": "Modelador de Adequação",
  "general": {
    "clear": "Limpar",
    "cancel": "Cancelar",
    "save": "Executar",
    "saveAs": "Exportar"
  },
  "saveModel": {
    "save": "Exportar",
    "title": "Título: ",
    "summary": "Resumo: ",
    "description": "Descrição: ",
    "tags": "Palavras-chave: ",
    "folder": "Pasta: ",
    "homeFolderPattern": "{username} (Home)",
    "failed": "Exportar falhou."
  },
  "util": {
    "colorRamp": {
      "1": "Extremamente Baixo",
      "2": "Muito Baixo",
      "3": "Baixo",
      "4": "Médio-Baixo",
      "5": "Média",
      "6": "Médio-Alto",
      "7": "Alto",
      "8": "Muito Alto",
      "9": "Extremamente Alto",
      "low": "Baixo",
      "high": "Alto",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Inverter"
    }
  },
  "wro": {
    "caption": "Modelador de Adequação",
    "browsePrompt": "Serviço de Sobreposição Ponderada",
    "selectLayersCaption": "Selecionar Camadas",
    "selectLayers": "Camadas",
    "designModelCaption": "Modelo de Design",
    "designModel": "Modelo de Design",
    "transparency": "Transparência",
    "visible": "Visível",
    "total": "Total",
    "unableToLoad": "Não foi possível carregar o modelo.",
    "projectNotOpen": "Não se encontra aberto qualquer projeto.",
    "readMore": "Ler Mais",
    "validation": {
      "validating": "A validar...",
      "invalidItemCaption": "Aviso de Serviço de Sobreposição Ponderada",
      "notAnImageService": "Este item não é um Serviço de Imagem",
      "notAWroService": "Este item não é um Serviço de Sobreposição Ponderada",
      "undefinedUrl": "O URL deste item não está definido.",
      "inaccessible": "O serviço encontra-se inacessível.",
      "generalError": "Impossível abrir o item.",
      "missingFieldPattern": "{field} é um campo obrigatório",
      "notAllowRasterFunction": "allowRasterFunction tem de ser definido como verdadeiro",
      "notNearestResampling": "defaultResamplingMethod tem de ser O Mais Próximo",
      "notIsWeightedOverlayProp": "A propriedade-chave IsWeightedOverlay tem de ser definida como verdadeira",
      "invalidLink": "O URL é inválido. Ocorreu uma falha ao abrir o site para a camada selecionada.",
      "unexpectedError": "Ocorreu um estado inesperado.",
      "rangeMessage": "O valor tem de encontrar-se entre ${0} e ${1}.",
      "rangeMessage100": "O valor tem de encontrar-se entre 0 e 100.",
      "maxLayers": "Máximo de ${0} camadas permitidas por serviço, primeiro tem de remover uma camada antes de adicionar uma nova.",
      "notFound": "Camada ${0} não encontrada no serviço de sobreposição ponderada",
      "wroServiceNotDefined": "Não se encontra definido qualquer serviço de sobreposição ponderada para o modelo.",
      "overlayLayerOutputInvalid": "Camada de sobreposição [${0}] voltar a cartografar intervalos [${1}] valor de saída em falta ou inválido",
      "overlayLayerInputInvalid": "Camada de sobreposição [${0}] voltar a cartografar intervalos [${1}] máx/min de saída em falta ou inválido",
      "overlayLayerRangesMissing": "Camada de sobreposição [${0}] intervalos para nova cartografia em falta",
      "overlayLayerWeight": "As ponderações da camada de sobreposição têm de  perfazer 100",
      "overlayLayerRequired": "É necessária pelo menos uma camada de sobreposição",
      "overlayLayerNotDefined": "As camadas de sobreposição não estão definidas",
      "requiresColormap": "Esta função de raster requer um mapa de cores (colormap), mas o modelo não tem uma definição de mapa de cores (colormap) definida",
      "createModelError": "Erro ao Criar Modelo",
      "invalidModel": "O modelo não é válido",
      "imageServiceNotDefined": "A camada de serviço de imagem não está definida",
      "imageLayerNotDefined": "A camada de serviço de imagem não está definida",
      "histogramNotDefined": "Não está definida qualquer função de histograma de sobreposição ponderada."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Verde Amarelo Vermelho",
      "Red Yellow Green": "Vermelho Amarelo Verde",
      "Yellow to Dark Red": "De Amarelo a Vermelho Escuro",
      "Dark Red to Yellow": "De Vermelho Escuro a Amarelo",
      "Light Gray to Dark Gray": "De Cinza Claro a Cinza Escuro",
      "Dark Gray to Light Gray": "De Cinza Escuro a Cinza Claro",
      "Light Brown to Dark Brown": "De Castanho Claro a Castanho Escuro",
      "Dark Brown to Light Brown": "De Castanho Escuro a Castanho Claro",
      "Full Spectrum - Bright Red to Blue": "Gama Completa - de Vermelho Vivo a Azul",
      "Full Spectrum - Bright Blue to Red": "Gama Completa - de Azul Vivo a Vermelho",
      "Partial Spectrum - Yellow to Blue": "Gama Parcial - de Amarelo a Azul",
      "Partial Spectrum - Blue to Yellow": "Gama Parcial - de Azul a Amarelo",
      "Yellow-Green to Dark Blue": "De Amarelo-Verde a Azul Escuro",
      "Dark Blue to Yellow-Green": "De Azul Escuro a Amarelo-Verde",
      "Cold to Hot Diverging": "A Divergir entre Frio e Quente",
      "Hot to Cold Diverging": "A Divergir entre Quente e Frio",
      "Surface - Low to High": "Superfície - de Baixo a Alto",
      "Surface - High to Low": "Superfície - de Alto a Baixo"
    }
  },
  "tabs": {
    "layers": "Camadas",
    "model": "Modelo",
    "chart": "Gráfico"
  },
  "chart": {
    "prompt": "Elementos",
    "working": "A atualizar...",
    "polygonTool": "Desenhar um Polígono",
    "freehandPolygonTool": "Desenhar um Polígono à Mão Livre",
    "selectTool": "Selecionar de uma Camada",
    "panTool": "Mover",
    "clearButton": "Apagar",
    "noModelLayer": "Sem modelo.",
    "noSubjectLayers": "O seu mapa não possui camadas de polígonos.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});