define({
  "_widgetLabel": "Guia de Resposta a Emergências",
  "ergMainPageTitle": "Baseado no Guia de Resposta a Emergências 2016",
  "coordInputLabelStart": "Localização de Derramamento (DD)",
  "coordInputLabel": "Localização de Derramamento",
  "addPointToolTip": "Adicionar Localização de Derramamento",
  "drawPointToolTip": "Clicar para adicionar localização de derramamento",
  "material": "Material",
  "materialPlaceholder": "Comece a digitar para pesquisar um material",
  "table3Message": "O material que selecionou requer informações adicionais caso esteja a lidar com um derramamento de grandes dimensões.\n\nPor favor, assegure que tem os valores corretos selecionados para velocidade do vento e contentor de transporte.",
  "table2Message": "O material que selecionou pode produzir uma grande quantidade de gases com Risco de Inalação Tóxica quando é derramado na água.\n\nPoderá pretender considerar a utilização do(s) seguinte(s) material(ais):\n\n",
  "spillSize": "Dimensão do Derramamento",
  "small": "Pequeno",
  "large": "Grande",
  "fireLabel": "Exibir Zona de Isolamento de Fogo",
  "weatherLabel": "Condições Meteorológicas Atuais no Local do Derramamento",
  "weatherIntialText": "<br />Atualizadas após um local de derramamento ter sido identificado",
  "temperature": "Temperatura",
  "wind": "Vento",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informação meteorológica não obtida. Atualize os valores Velocidade do Vento e Hora do Derramamento manualmente",
  "windDirection": "Direção do Vento (a soprar para)",
  "timeOfSpill": "Hora do Derramamento",
  "day": "Dia",
  "night": "Noite",
  "windSpeed": "Velocidade do Vento",
  "low": "Baixo",
  "moderate": "Moderado",
  "high": "Alto",
  "transportContainer": "Contentor de Transporte",
  "rail": "Vagão cisterna",
  "semi": "Camiãi cisterna ou reboque",
  "mton": "Cilindros de múltiplas toneladas",
  "ston": "Múltiplos cilindros pequenos ou cilindro de uma tonelada",
  "ag": "Cisterna Agrícola",
  "msm": "Múltiplos cilindros pequenos",
  "bleveLabel": "Exibir Zona de Isolamento BLEVE",
  "capacity": "Capacidade do Contentor (litros)",
  "bleveMessage": "Para o material que selecionou, pode ser exibida uma distância de evacuação adicional para BLEVE.\n\nPara ativar, ligue o interruptor Exibir Zona de Isolamento BLEVE e selecione a capacidade de contentor adequada.",
  "noPAZoneMessage": "Não existem distâncias de Ação de Proteção para este material. Apenas foram calculadas as zonas de Isolamento Inicial e de evacuação",
  "settingsTitle": "Configurações",
  "spillLocationLabel": "Localização de Derramamento",
  "spillLocationButtonLabel": "Configurar Definições de Local de Derramamento",
  "IISettingsLabel": "Zona de Isolamento Inicial",
  "IIButtonLabel": "Configurar Definições de Isolamento Inicial",
  "PASettingsLabel": "Zona de Ação de Proteção",
  "PAButtonLabel": "Configurar Definições de Ação de Proteção",
  "downwindSettingsLabel": "Zona Sotavento",
  "downwindButtonLabel": "Configurar Definições Sotavento",
  "fireSettingsLabel": "Zona de Isolamento de Fogo",
  "fireButtonLabel": "Configurar Definições de Isolamento de Fogo",
  "bleveSettingsLabel": "Zona de Isolamento BLEVE",
  "bleveButtonLabel": "Configurar definições BLEVE",
  "style": "Estilo",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço e Ponto",
    "esriSLSDashDotDot": "Traço, Ponto e Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo e Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Traço Curto e Ponto",
    "esriSLSShortDashDotDot": "Traço Curto, Ponto e Ponto",
    "esriSLSShortDot": "Traço Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Ao Contrário",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para a frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultados",
  "publishERGBtn": "Publicar",
  "ERGLayerName": "Nome de Camada ERG Publicada",
  "invalidERGLayerName": "O nome da camada pode apenas conter caracteres alfanuméricos e traços inferiores.",
  "missingERGLayerName": "Tem de introduzir um nome para o ERG",
  "publishingFailedLayerExists": "Publicação Falhou: Já possui um serviço de elementos denominado {0}. Por favor, escolha outro nome.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não é possível criar: {0}",
  "addToDefinition": "Adicionar a definição: {0}",
  "successfullyPublished": "Camada web publicada com sucesso{0}Gerir a camada web",
  "userRole": "Não é possível criar o serviço porque o utilizador não possui permissões",
  "transparency": "Transparência",
  "outline": "Contorno",
  "fill": "Preenchimento (Apenas é aplicada cor quando o estilo é definido como sólido)",
  "createERGBtn": "Criar Zonas",
  "clearERGBtn": "Apagar",
  "labelFormat": "Formato de Rótulo",
  "helpIconTooltip": "O limiar entre grandes e pequenas dimensões de derramamento são:\nLíquidos - 55 galões (208 litros)\nSólids - 60 libras (300 quilogramas)",
  "cellWidth": "Largura de Célula (x)",
  "cellHeight": "Altura de Célula (y)",
  "invalidNumberMessage": "O valor introduzido não é válido",
  "invalidRangeMessage": "O valor tem de ser maior do que 0",
  "gridAngleInvalidRangeMessage": "O valor tem de encontrar-se entre -89,9 e 89,9.",
  "formatIconTooltip": "Introdução de Formato",
  "setCoordFormat": "Definir String de Formatação de Coordenadas",
  "prefixNumbers": "Adicionar o prefixo ‘+/-’ a números positivos e negativos",
  "cancelBtn": "Cancelar",
  "applyBtn": "Aplicar",
  "comfirmInputNotation": "Confirmar Notação de Entrada",
  "notationsMatch": "notações correspondem à sua entrada, por favor, confirme as que pretende utilizar:",
  "missingLayerNameMessage": "Tem de introduzir um nome de camada válido antes de poder publicar",
  "parseCoordinatesError": "Não foi possível analisar as coordenadas. Por favor, verifique a entrada.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais  - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Decimais Minutos - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Decimais Minutos - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/ Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra de Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)"
});