define({
  "selectAnalysisTools": "Odaberi alate za analizu za uporabu u widgetu.",
  "graphicalDisplay": "Grafički prikaz",
  "toolSetting": "Postavi pojedinosti alata",
  "toolLabel": "Naslov prikaza alata",
  "showHelpTip": "Prikaži poveznice za pomoć u widgetu",
  "showCurrentMapExtent": "Prikaži opciju za uporabu trenutačnog obuhvata karte",
  "showCredits": "Prikaži opciju <b>Prikaži kredite</b>",
  "saveAsFeatureService": "Spremi rezultat na korisnički račun",
  "showReadyToUseLayers": "Prikaži slojeve spremne za uporabu iz ArcGIS Online atlasa svijeta Living Atlas",
  "toolNotAvailable": "Taj alat nije dostupan jer karta ne sadrži sloj(eve) geoobjekta.",
  "aggregatePoints": "Agregiraj točke",
  "aggregatePointsUsage": "Agregira točke u poligone gdje se točke nalaze.",
  "calculateDensity": "Izračunaj gustoću",
  "calculateDensityUsage": "Stvara kartu gustoće od točaka ili linija širenjem poznatih količina neke pojave (predstavljeno kao atributi točaka ili linija) na karti.",
  "connectOriginsToDestinations": "Spojite ishodišta s odredištima",
  "connectOriginsToDestinationsUsage": "Mjeri vrijeme putovanja ili udaljenosti između dviju točaka.",
  "createBuffers": "Izradi pojas",
  "createBuffersUsage": "Izrađuje poligone pojasa od uvezenih geoobjekata.",
  "createDriveTimeAreas": "Stvori područja vremena vožnje",
  "createDriveTimeAreasUsage": "Stvara poligone vremena vožnje (ili udaljenosti vožnje) oko unesenih točaka za dane vrijednosti vremena vožnje.",
  "createViewshed": "Stvori vidljivost",
  "createViewshedUsage": "Stvara područja koja su vidljiva na temelju lokacija koje odredite.",
  "createWatersheds": "Stvori sliv",
  "createWatershedsUsage": "Stvara područja razvođa na temelju lokacija koje odredite.",
  "deriveNewLocations": "Izvođenje novih lokacija",
  "deriveNewLocationsUsage": "Izvodi nove geoobjekte iz slojeva unosa koji zadovoljavaju upit koji odredite",
  "dissolveBoundaries": "Ukloni granice",
  "dissolveBoundariesUsage": "Spaja poligone koji se preklapaju ili koji dijele zajedničku granicu.",
  "enrichLayer": "Obogati sloj",
  "enrichLayerUsage": "Obogaćuje unesene geoobjekte ljudima, mjestima i poslovnim činjenicama o okolnim područjima.",
  "extractData": "Izdvoji podatke",
  "extractDataDesc": "Izdvaja podataka iz jednog ili više slojeva u danom obuhvatu",
  "findExistingLocations": "Pronađi postojeće lokacije",
  "findExistingLocationsUsage": "Odabir geoobjekata iz sloja unosa koji ispunjavaju atributni ili prostorni upit koji odredite",
  "findHotSpots": "Pronađi žarišne točke",
  "findHotSpotsUsage": "Pronalazi statistički značajne klastere unesenih geoobjekata ili visokih/niskih vrijednosti.",
  "findNearest": "Pronađi najbliže",
  "findNearestUsage": "Za svaki geoobjekt na sloju unosa pronalazi najbliži geoobjekt na drugom sloju",
  "findSimilarLocations": "Pronađi slične lokacije",
  "findSimilarLocationsUsage": "Mjeri sličnost potencijalnih lokacija do jedne ili više referentnih lokacija.",
  "interpolatePoints": "Interpolacija točaka",
  "interpolatePointsUsage": "Predviđa vrijednosti na novim lokacijama na temelju mjera iz skupa točaka.",
  "mergeLayers": "Spoji slojeve",
  "mergeLayersUsage": "Spaja geoobjekate iz više slojeva u novi sloj",
  "overlayLayers": "Preklapanje slojeva",
  "overlayLayersUsage": "Stapa više slojeva u jedan sloj sa sačuvanim informacijama iz izvornih slojeva.",
  "planRoutes": "Planiranje ruta",
  "planRoutesUsage": "Određuje kako učinkovito podijeliti zadatke među terenskim radnicima.",
  "summarizeNearby": "Sažmi u blizini",
  "summarizeNearbyUsage": "Za svaki geoobjekt na sloju unosa sažima podatke unutar udaljenosti od geoobjekata na drugom sloju.",
  "summarizeWithin": "Sažmi unutar",
  "summarizeWithinUsage": "Za svaki poligon na sloju unosa sažima podatke koji se nalaze unutar njega od geoobjekata na drugom sloju.",
  "traceDownstream": "Prati nizvodno",
  "traceDownstreamUsage": "Određuje putanju nizvodnog protoka od lokacija koje odredite.",
  "allowToExport": "Omogući izvoz rezultata",
  "joinFeatures": "Pridruži geoobjekte",
  "joinFeaturesUsage": "Alat Pridruži geoobjekte prenijet će atribute iz jednog sloja li tablice u drugi na temelju prostornih i atributnih relacija. Ako želite, mogu se izračunati statistike za pridružene geoobjekte.",
  "includeRouteLayer": "Uključi slojeve rute",
  "findOutliers": "Pronađi odstupanja",
  "findOutliersUsage": "Alat Pronađi odstupanja odredit će ima li statistički značajnih odstupanja u prostornom obrascu vaših podataka."
});