define({
  "layerSelect": "Selectaţi stratul tematic de imagini",
  "displayMeasureResultInPopup": "Afişare rezultate măsurare într-o fereastră pop-up",
  "angularUnitSelect": "Unitate unghiulară implicită",
  "linearUnitSelect": "Unitate liniară implicită",
  "areaUnitSelect": "Unitate de suprafaţă implicită",
  "displayOperationSelect": "Selectare operaţiuni măsurare",
  "errorSectionMessage": "Niciunul din straturile tematice nu acceptă capacităţi de măsurare",
  "unitLabel": {
    "esriInches": "Inci",
    "esriFeet": "Ft",
    "esriYards": "Iarzi",
    "esriMiles": "Mile",
    "esriNauticalMiles": "Mile marine",
    "esriMillimeters": "Milimetri",
    "esriCentimeters": "Centimetri",
    "esriDecimeters": "Decimetri",
    "esriMeters": "Metri",
    "esriKilometers": "Kilometri",
    "esriDURadians": "Radiani",
    "esriDUDecimalDegrees": "Grade",
    "esriSquareInches": "Inci pătraţi",
    "esriSquareFeet": "Ft pătraţi",
    "esriSquareYards": "Iarzi pătraţi",
    "esriAcres": "Acri",
    "esriSquareMiles": "Mile pătrate",
    "esriSquareMillimeters": "Milimetri pătraţi",
    "esriSquareCentimeters": "Centimetri pătraţi",
    "esriSquareDecimeters": "Decimetri pătraţi",
    "esriSquareMeters": "Metri pătraţi",
    "esriAres": "Ari",
    "esriHectares": "Hectare",
    "esriSquareKilometers": "Kilometri pătraţi"
  },
  "operationLabel": {
    "esriMensurationPoint": "Locaţie",
    "esriMensurationDistanceAndAngle": "Distanţă şi unghi",
    "esriMensurationAreaAndPerimeter": "Suprafaţă şi perimetru",
    "esriMensurationHeightFromBaseAndTop": "Înălţime: De la bază la vârf",
    "esriMensurationHeightFromBaseAndTopShadow": "Înălţime: Umbră de la bază la vârf",
    "esriMensurationHeightFromTopAndTopShadow": "Înălţime: Umbră de la vârf la vârf",
    "esriMensurationCentroid": "Centroid",
    "esriMensurationPoint3D": "Locaţie (3D)",
    "esriMensurationDistanceAndAngle3D": "Distanţă şi unghi (3D)",
    "esriMensurationAreaAndPerimeter3D": "Suprafaţă şi perimetru (3D)",
    "esriMensurationCentroid3D": "Centroid (3D)"
  }
});