define({
  "add": "Zum Hinzufügen hier klicken",
  "title": "Titel",
  "placeholderBookmarkName": "Lesezeichenname",
  "ok": "OK",
  "cancel": "Abbrechen",
  "warning": "Beenden Sie die Bearbeitung!",
  "edit": "Lesezeichen bearbeiten",
  "errorNameExist": "Lesezeichen ist vorhanden!",
  "errorNameNull": "Ungültiger Lesezeichenname!",
  "addBookmark": "Neue erstellen",
  "thumbnail": "Miniaturansicht",
  "thumbnailHint": "Zum Aktualisieren auf das Bild klicken",
  "displayBookmarksAs": "Lesezeichen anzeigen als",
  "cards": "Kacheln",
  "list": "Liste",
  "cardsTips": "Kachelansicht",
  "listTips": "Listenansicht",
  "makeAsDefault": "Als Standard festlegen",
  "default": "Standardeinstellung",
  "editable": "Das Hinzufügen von Lesezeichen im Widget zulassen",
  "alwaysSync": "Lesezeichen der Webkarte anzeigen",
  "configCustom": "Benutzerdefinierte Lesezeichen anzeigen",
  "import": "Importieren",
  "create": "Erstellen",
  "importTitle": "Lesezeichen importieren",
  "importFromWeb": "Lesezeichen aus der aktuellen Webkarte anzeigen",
  "selectAll": "Alles auswählen",
  "noBookmarkInConfig": "Klicken Sie auf â€œImportierenâ€ oder â€œNeu erstellenâ€, um Lesezeichen hinzuzufügen.",
  "noBookmarkInWebMap": "Auf der Karte ist kein Lesezeichen konfiguriert.",
  "extent": "Ausdehnung",
  "saveExtent": "Kartenausdehnung in diesem Lesezeichen speichern",
  "savelayers": "Layer-Sichtbarkeit speichern",
  "withVisibility": "Mit Layer-Sichtbarkeit",
  "bookmark": "Lesezeichen",
  "addBtn": "Hinzufügen",
  "deleteBtn": "Löschen",
  "editBtn": "Bearbeiten",
  "dragReorderTip": "Zur Neuanordnung halten und ziehen",
  "deleteBtnTip": "Das Lesezeichen löschen",
  "editBtnTip": "Das Lesezeichen bearbeiten"
});