define({
  "serviceUrl": "Nastavi url storitve:",
  "minIntSpacingLabel": "Minimalna velikost mreže",
  "lineOpacityLabel": "Prosojnost linije",
  "labelOpacityLabel": "Prosojnost napisa",
  "centerLabelOpacityLabel": "Postavi prosojnost napisa na sredino",
  "gridZonePlacementLabel": "Postavitev napisa mrežne cone",
  "verticalLineLabels": "Usmerjenost napisa na mreži",
  "styleHeaderLabel": "Slog",
  "indexHeaderLabel": "Mrežna komponenta",
  "colorHeaderLabel": "Barva",
  "fontSizeHeaderLabel": "Velikost pisave",
  "lineWidthHeaderLabel": "Debelina obrobe linije",
  "horizontalLabel": "Horizontalno",
  "verticalLabel": "Vertikalno",
  "upperLeftLabel": "Zgoraj levo",
  "upperRightLabel": "Zgoraj desno",
  "lowerLeftLabel": "Spodaj levo",
  "lowerRightLabel": "Spodaj desno",
  "centerLabel": "Na sredino",
  "errorMessage": "Konfiguracijska stran vsebuje napake. Popravite, preden shranite.",
  "checkBoxLabel": "Prikaži mrežo, ko je pripomoček zaprt",
  "checkBoxLabelDashboard": "Prikaži mrežo",
  "gzd": "Označevalec mrežne cone (GZD)",
  "gsid": "100.000-metrska identifikacija mrežnega kvadrata (GSID)",
  "grid10k": "10.000-metrske mrežne linije",
  "grid1k": "1.000-metrske mrežne linije",
  "grid100m": "100-metrske mrežne linije",
  "grid10m": "10-metrske mrežne linije",
  "switchBasemap": "Preklopi temeljno karto"
});