define({
  "serviceUrl": "Indstil tjeneste-URL:",
  "minIntSpacingLabel": "Minimal gitterstørrelse",
  "lineOpacityLabel": "Linje-gennemsigtighed",
  "labelOpacityLabel": "Etiket-gennemsigtighed",
  "centerLabelOpacityLabel": "Central etikets gennemsigtighed",
  "gridZonePlacementLabel": "Placering af gitterzoneetiket",
  "verticalLineLabels": "Vertikale linjeetiketter",
  "styleHeaderLabel": "Type",
  "indexHeaderLabel": "Gitterkomponent",
  "colorHeaderLabel": "Farve",
  "fontSizeHeaderLabel": "Skriftstørrelse",
  "lineWidthHeaderLabel": "Linjebredde",
  "horizontalLabel": "Vandret",
  "verticalLabel": "Lodret",
  "upperLeftLabel": "Øverst til venstre",
  "upperRightLabel": "Øverst til højre",
  "lowerLeftLabel": "Nederst til venstre",
  "lowerRightLabel": "Nederst til højre",
  "centerLabel": "Midt",
  "errorMessage": "Konfigurationssiden indeholder fejl. Ret dem, før du gemmer.",
  "checkBoxLabel": "Vis gitter, når widget lukkes",
  "checkBoxLabelDashboard": "Vis gitter",
  "gzd": "Gitterzonebetegnelse (GZD - Grid Zone Designator)",
  "gsid": "100.000-meter identifikation af gitterfirkant (GSID - Grid Square Identification)",
  "grid10k": "10.000-meter gitterlinjer",
  "grid1k": "1.000-meter gitterlinjer",
  "grid100m": "100-meter gitterlinjer",
  "grid10m": "10-meter gitterlinjer",
  "switchBasemap": "Skift baggrundskort"
});