define({
  "enableUndoRedo": "تمكين التراجع/الإعادة",
  "toolbarVisible": "شريط الأدوات المرئي",
  "toolbarOptions": "خيارات شريط الأدوات",
  "mergeVisible": "دمج",
  "cutVisible": "قص",
  "reshapeVisible": "إعادة تشكيل",
  "back": "السابق",
  "label": "طبقة",
  "edit": "يمكن تحريره",
  "update": "تعطيل تحديث هندسة الشكل",
  "fields": "حقول",
  "actions": "الأفعال",
  "editpageName": "الاسم",
  "editpageAlias": "اسم مستعار",
  "editpageVisible": "مرئي",
  "editpageEditable": "يمكن تحريره",
  "noLayers": "لا تتوفر أي طبقات معالم يمكن تحريرها",
  "configureFields": "تكوين حقول الطبقة",
  "useFilterEdit": "استخدم عامل تصفية قالب المعلم",
  "display": "العرض",
  "autoApplyEditWhenGeometryIsMoved": "طبّق التحرير تلقائيًا عند نقل الشكل الهندسي",
  "snappingTolerance": "قم بتعيين سماحية الالتقاط بوحدة البكسل",
  "popupTolerance": "قم بتعيين سماحية العنصر المنبثق لتحرير البيانات الجدولية بوحدة البكسل",
  "stickyMoveTolerance": "قم بتعيين سماحية نقل اللاصق بوحدة البكسل",
  "usingSaveButton": "لا تطبق التحريرات على البيانات الجدولية حتى النقر على زر حفظ"
});