define({
  "enableUndoRedo": "สามารถ ยกเลิกและย้อนการกระทำได้",
  "toolbarVisible": "มองเห็นแถบเครื่องมือ",
  "toolbarOptions": "ตัวเลือกแถบเครื่องมือ",
  "mergeVisible": "ผสม",
  "cutVisible": "ตัด",
  "reshapeVisible": "แก้ไขรูป",
  "back": "กลับ",
  "label": "ชั้นข้อมูล",
  "edit": "ที่สามารถแก้ไขได้",
  "update": "ไม่สามารถอัพเดทเชิงเรขาคณิตได้",
  "fields": "ฟิลด์",
  "actions": "กระทำ",
  "editpageName": "ชื่อ",
  "editpageAlias": "นามแฝง",
  "editpageVisible": "มองเห็น",
  "editpageEditable": "ที่สามารถแก้ไขได้",
  "noLayers": "ไม่สามารถแก้ไขชั้นข้อมูลฟีเจอร์ที่ปรากฏได้",
  "configureFields": "กำหนดค่าฟิลด์ของชั้นข้อมูล",
  "useFilterEdit": "ใช้แม่แบบตัวกรองฟีเจอร์",
  "display": "แสดงผล",
  "autoApplyEditWhenGeometryIsMoved": "บันทึกการแก้ไขอัตโนมัติ เมื่อมีการย้ายฟีเจอร์",
  "snappingTolerance": "ตั้งค่าระยะสเนป ด้วยหน่วยเป็นพิกเซล",
  "popupTolerance": "ตั้งค่าระยะห่างของหน้าต่างป๊อปอัพสำหรับแก้ไขแอตทริบิวต์ ด้วยหน่วยเป็นพิกเซล",
  "stickyMoveTolerance": "ตั้งระยะในการย้ายข้อมูลให้ติดกับข้อมูลเดิม ด้วยหน่วยเป็นพิกเซล",
  "usingSaveButton": "อย่าใช้การแก้ไขแอตทริบิวต์จนกว่าจะคลิกปุ่มบันทึก"
});