define({
  "settings": "Seaded",
  "titleSettings": "Tekstiseaded",
  "imageSettings": "Pildiseaded",
  "backgroundColor": "Taustvärv",
  "alignment": "Joondus",
  "textSize": "Teksti suurus",
  "textColor": "Teksti värv",
  "dataSource": "Andmeallikas",
  "chartSettings": "Diagrammi seaded",
  "data": "Andmed",
  "dataLabels": "Andmete märgised",
  "displayMode": "Kuvarežiim",
  "featureOption": "Kuva väärtused objektide kaupa",
  "categoryOption": "Kuva väärtused kategooriate kaupa",
  "countOption": "Kuva objektide kogused kategooriate kaupa",
  "fieldOption": "Kuva atribuutide väärtused diagrammidena",
  "categoryField": "Kategooria väli",
  "labelField": "Märgise väli",
  "valueFields": "Väärtuse väljad",
  "operation": "Toiming",
  "sumOption": "Summa",
  "averageOption": "Keskmine",
  "minOption": "Miinimum",
  "maxOption": "Maksimum",
  "dataFormat": "Andmevorming",
  "decimalPlaces": "Kümnendkohad",
  "prefix": "Eesliide",
  "suffix": "Sufiks",
  "dataType": "Andmete tüüp",
  "featureCount": "Objektide arv",
  "fieldStatistics": "Välja statistika",
  "display": "Kuva",
  "chartColor": "Diagrammi värv",
  "horizontalAxis": "Horisontaaltelg",
  "verticalAxis": "Vertikaaltelg",
  "legend": "Legendiga kaart",
  "position": "Asukoht",
  "top": "Ülemine",
  "bottom": "Alumine",
  "useDataSourceSelection": "Kasuta valikut",
  "dataSourceFilterByExtent": "Filtreeri ulatuse alusel",
  "changeTemplate": "Muuda malli",
  "numberSettings": "Numbriseaded",
  "gaugeSettings": "Mõõdikuseaded",
  "indicators": "Indikaatorid",
  "ifValue": "Kui väärtus",
  "and": "ja",
  "numberOperatorIsLessThan": "on väiksem kui",
  "numberOperatorIsGreaterThan": "on suurem kui",
  "numberOperatorIsBetween": "on vahemikus",
  "numberOperatorIsEqual": "on võrdne",
  "numberOperatorIsNotEqual": "ei võrdu",
  "then": "Siis",
  "ratio": "Suhe",
  "trueValue": "Tegelik väärtus",
  "changeValueColor": "muuda väärtuse värviks",
  "changeGaugeColor": "muuda mõõdiku värviks",
  "setIndicatorIcon": "määra indikaatori ikooniks",
  "icons": "Ikoonid",
  "style": "Laad",
  "placement": "Paigutus",
  "left": "Vasak",
  "replace": "Asenda",
  "right": "Parem",
  "color": "Värv",
  "categoryExists": "Kategooria on olemas!",
  "comboxHint": "Sisestage või valige olemasolevast",
  "comboxDisableInputHint": "Tehke mõni valik",
  "sortBy": "Sorteeri:",
  "labelAxis": "Märgis",
  "valueAxis": "Väärtus",
  "minPeriod": "Miinimumperiood",
  "automatic": "Automaatne",
  "periodsWithOutRecords": "Kirjeteta perioodid",
  "nullValue": "Tühiväärtus",
  "calculatedAsZero": "Arvutatud nullina",
  "ignored": "Eiratud",
  "maxCategories": "Maksimaalselt kategooriaid",
  "useLayerSymbology": "Kasuta kihi sümboolikat",
  "hollowsize": "Tühi suurus",
  "splitField": "Tükelda väli",
  "parsingperiodTip": "Arvutamine nurjus. Liiga palju ajaintervalle lühikese sõelumisperioodi tõttu.",
  "manyCategoryTip": "Diagrammi kuvamine nurjus. Liiga palju kategooriaid.",
  "setColor": "Määra värv",
  "setTheColorOf": "Seejärel määrake objekti värv:",
  "setTheColorAs": "Seejärel määrake värviks",
  "ifStr": "Kui",
  "as": "kui",
  "is": "on",
  "isNot": "ei ole",
  "barCluster": "lindi klaster",
  "individualBar": "üksik lint",
  "allOthers": "Kõik teised",
  "category": "Kategooria",
  "indicatorSum": "SUM",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Määrake indikaatorid õigesti.",
  "dataRange": "Kuupäevavahemik",
  "targetValue": "Sihtväärtus",
  "currentValue": "Praegune väärtus",
  "gaugeColor": "Mõõdiku värv",
  "min": "Miinimum",
  "max": "Maksimum",
  "displayValueIn": "Kuva väärtust",
  "noData": "Andmed puuduvad",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Hoiatus",
  "noSettingWaring1": "Elemendi atribuutide määramiseks klõpsake seda.",
  "noSettingWaring2": "Elemendi suuruse muutmiseks või ümberjärjestamiseks lohistage seda.",
  "donNotShowAgain": "Ära seda enam kuva",
  "changeTemplateWarning": "See kustutab kõik teie seadistused ja avab uue malli.",
  "requiredFieldWarning": "Väärtus on nõutud:",
  "dataSourceNotSet": "Määra andmeallikas.",
  "addIndicatorTip": "Lisa indikaator",
  "chooseTemplatePopupTitle": "Vali mall",
  "filterExtentTipWithaTag": "Filtri keelamiseks saate vahekaardil „Atribuut“ valida nupu <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Täiendav andmeallikas</a>.",
  "filterExtentTip": "Filtri keelamiseks saate vahekaardil „Atribuut“ valida nupu Täiendav andmeallikas.",
  "customColorByCategory": "Kohandatud värv kategooria järgi",
  "randomColor": "Juhuslik värv",
  "valueString": "Väärtus",
  "fieldString": "Välitöödele",
  "includeThresholdValue": "Kaasa lävendi väärtus",
  "percentage": "Protsent",
  "colorSchema": "Värviskeem",
  "addCategory": "Lisa kategooria",
  "clickToEdit": "Muutmiseks klõpsake",
  "nullText": "Null",
  "others": "Muu",
  "stringsInTemplate": {
    "name_number": "Number",
    "name_gauge": "Mõõdik",
    "name_vertical_gauge": "Vertikaalne mõõdik",
    "name_horizontal_gauge": "Horisontaalne mõõdik",
    "name_pie": "Sektordiagramm",
    "name_donut": "Sõõrdiagramm",
    "name_bar": "Lintdiagramm",
    "name_stacked_bar": "Virnlintdiagramm",
    "name_percentage_stacked_bar": "Protsendi virnlintdiagramm",
    "name_column": "Tulpdiagramm",
    "name_stacked_column": "Virntulpdiagramm",
    "name_percentage_stacked_column": "Protsendi virntulpdiagramm",
    "name_line": "Joon",
    "name_area": "Kihtdiagramm",
    "name_stacked_area": "Virnkihtdiagramm",
    "name_percentage_stacked_area": "Protsendi virnkihtdiagramm",
    "titleOfTheInfographic": "INFOGRAAFIKA PEALKIRI",
    "description": "Kirjeldus: täiendav teave selle infograafika kohta."
  }
});