define({
  "_widgetLabel": "Povědomí o situaci",
  "locate_incident": "Vyhledat událost",
  "reverse_geocoded_address": "Nejbližší adresa",
  "reverse_geocoded_error": "Nedostupné",
  "now": "NYNÍ",
  "wind": "OKNO",
  "SUN": "NE",
  "MON": "PO",
  "TUE": "ÚT",
  "WED": "ST",
  "THU": "ČT",
  "FRI": "PÁ",
  "SAT": "SO",
  "actionLabel": "Nastavit polohu",
  "drawPoint": "Nakreslit bod",
  "drawLine": "Nakreslit linii",
  "drawPolygon": "Nakreslit polygon",
  "saveIncident": "Uložit",
  "clearIncident": "Začít znovu",
  "noFeaturesFound": "Nebyly nalezeny žádné prvky.",
  "downloadCSV": "Stáhnout",
  "sum": "Suma",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Průměr",
  "count": "POČET",
  "area": "PLOCHA",
  "length": "DÉLKA",
  "update_btn": "Hotovo",
  "delete_btn": "Smazat",
  "get_directions": "Vyhledat trasy",
  "incident": "Událost",
  "incidents": "Události",
  "buffer": "Obalová zóna (Buffer).",
  "buffers": "Obalové zóny",
  "weather": "Počasí",
  "poweredBy": "Využívá technologii",
  "_featureAction_ActionLabel": "Nastavit polohu",
  "_featureAction_AddRemoveActionLabel": "Přidat/odstranit umístění",
  "snapshot": "Složku snímku vytvořila aplikace s ID:",
  "user_credentials": "Uživatel nemá platná oprávnění.",
  "notPolySnapShot": "Před vytvořením snímku zadejte šířku obalové zóny.",
  "notPolyReport": "Žádné platné výsledky pro přidání do zprávy.",
  "notValidDownload": "Nejsou k dispozici žádné platné výsledky ke stažení.",
  "of_append": "z",
  "layer_append": "souboru vrstev.",
  "downloadAll": "Stáhnout vše",
  "createSnapshot": "Vytvořit snímek",
  "createReport": "Vytvořit zprávu",
  "calculated_results": "Souhrn informací",
  "closest": "Nejbližší prvek",
  "proximity": "Obalové zóny, vzdálenost",
  "summary": "Souhrn",
  "groupedSummary": "Počty seskupených",
  "_count": "Počet",
  "approximate": "přibližně",
  "snapshot_name": "Nastavit vlastnosti snímku",
  "report_name": "Nastavit vlastnosti zprávy",
  "invalid_snapshot_name": "Název snímku není platný.",
  "invalid_report_name": "Neplatný název zprávy",
  "orientation": "Orientace",
  "pageSize": "Velikost stránky",
  "comments": "Komentáře",
  "choose_group": "Skupiny",
  "forecast": "Předpověď",
  "select_group": "Vybrat skupinu",
  "select_group_instruction": "Snímek bude vytvořen a sdílen s vybranou skupinou.",
  "information_append": " Informace",
  "distance": "VZDÁLENOST",
  "buffer_invalid": "Vložte platnou číselnou hodnotu od ${min} do ${max}"
});