define({
  "tabs_section_Label": "Kartice",
  "addTab": "Dodaj karticu",
  "layerName": "Sloj",
  "layerType": "Tip analize",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "closest": "Najbliži geoobjekat",
  "proximity": "Blizina",
  "summary": "Rezime",
  "select_lbl": "-- Izaberi --",
  "general_setting_Label": "Opšte postavke",
  "units_text_lbl": "Jedinice rastojanja",
  "maximum_distance_lbl": "Maksimalna udaljenost najbližeg geoobjekta",
  "buffer_text_lbl": "Oznaka zone bliskosti",
  "buffer_lbl": "Rastojanje zone bliskosti",
  "buffer_max_lbl": "Maksimalno rastojanje zone bliskosti",
  "buffer_min_lbl": "Minimalno rastojanje zone bliskosti",
  "buffer_default_lbl": "Podrazumevano rastojanje zone bliskosti",
  "not_less_than_max": "Rastojanje mora da bude manje od maksimalnog rastojanja zone bliskosti",
  "not_between": "Rastojanje mora da bude između minimalnog i maksimalnog rastojanja zone bliskosti",
  "not_more_than_min": "Rastojanje mora da bude veće od minimalnog rastojanja zone bliskosti",
  "not_valid_number": "Mora da bude važeći broj",
  "invalid_value": "${type} vrednost je nevažeća",
  "routing_checkBox": "Omogući rutiranje",
  "weather_Label": "Postavke vremenskih prilika",
  "weather_checkBox": "Omogući vremenske prilike",
  "weather_map_layers": "Izaberite slojeve vremena...",
  "selected_map_layers": " izabrani slojevi vremena",
  "instruction_weather": "Prikaži informacije o vremenu u tabeli.",
  "instruction_weather_layers": "Prikaži dodatne slojeve vremena.",
  "instruction_weather_metric": "Prikaži standardne/metričke vrednosti.",
  "selectLayers": "Izaberite slojeve vremena",
  "weather_removed_message": "Za ovaj vidžet nisu više dostupne opcije vremena.",
  "currentlySelectedLayer": "Izaberite iz slojeva mape",
  "missingTabLabel": "Bar jednoj kartici nedostaje oznaka",
  "missingLayerInWebMap": "Nema pronađenih operativnih slojeva.",
  "selectFields": "Izaberi polja",
  "addField": "Dodaj polje",
  "sum": "Zbir",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Prosečno",
  "count": "BROJAČ",
  "area": "POVRŠINA",
  "length": "DUŽINA",
  "count_checkBox": "Prikaži izbrojane geoobjekte",
  "area_checkBox": "Prikaži sumu površina",
  "length_checkBox": "Prikaži sumu dužina",
  "max_records": "Maksimalno ograničenje je dostignuto",
  "save_label": "Opcije čuvanja",
  "save_checkbox": "Omogući čuvanje",
  "report_label": "Opcije izveštaja",
  "report_checkbox": "Omogući izveštaj",
  "csv_label": "Opcije CSV datoteke",
  "csv_checkbox": "Izvezi sva polja",
  "display_label": "Opcije prikaza",
  "display_checkbox": "Prikaži sumu geoobjekata",
  "snapshot_label": "Snapshot opcije",
  "snapshot_checkbox": "Omogući Snapshot",
  "must_select_template": "Izaberite jedan od šablona izmena u opcijama čuvanja.",
  "count_label": "Oznaka brojača",
  "area_label": "Oznaka oblasti",
  "length_label": "Oznaka dužine",
  "invalid_string_width": "Vrednost je suviše duga. ",
  "layer_type_not_supported": "Tip sloja nije podržan.",
  "groupedSummary": "Grupisani brojači",
  "groupByField": "Polje „Grupiši na osnovu“",
  "labelType": "Dodaj oznaku",
  "prefix": "Kao prefiks",
  "suffix": "Kao sufiks",
  "need_group_field": "Koristite radnju Izmeni kako biste definisali polje „Grupiši na osnovu“.",
  "fieldTitle": "Polje",
  "typeTitle": "Tip",
  "actionsTitle": "Radnje",
  "save_point_checkbox": "Sačuvaj tačke",
  "save_line_checkbox": "Sačuvaj linije",
  "save_poly_checkbox": "Sačuvaj poligone",
  "no_valid_popup_fields": "Nema važećih polja u iskačućem prozoru. Upotrebite radnju za uređivanje da biste definisali polje.",
  "no_valid_fields": "Nema važećih polja. Upotrebite radnju za uređivanje da biste definisali opcije za prikaz.",
  "incident_label": "Oznaka kartice",
  "locate_incident_label": "Oznaka oblasti interesovanja",
  "incident": "Incident",
  "locate_incident": "Lociraj incident",
  "buffer_value": "Rastojanje zone bliskosti",
  "tab_options": "Analiza",
  "export_options": "Izlaz",
  "instruction_save": "Sačuvaj lokaciju u servis geoobjekata.",
  "instruction_snapshot": "Kreiraj veb mapu na osnovu lokacije.",
  "instruction_report": "Kreiraj štampani izveštaj lokacije.",
  "instruction_all_fields": "Izvezi sva polja sa CSV preuzimanjem.",
  "data_label": "Postavke izlaznih podataka",
  "layer_error": "Sloj nedostaje ili je nevažeći.",
  "visibility_checkBox": "Onemogući upravljanje vidljivošću sloja",
  "downloadTab": {
    "reportLegend": "Postavke izveštaja",
    "textColorLabel": "Izaberite boju za naslove kolona",
    "setButtonLabel": "Postavi",
    "printGPServiceLabel": "Štampaj URL adresu servisa",
    "logoLabel": "Logotip",
    "logoChooserHint": "Kliknite na ikonu sličice kako biste promenili sličicu",
    "footnoteLabel": "Fusnota"
  }
});