define({
  "layerSelect": "Выберите слой изображений",
  "displayMeasureResultInPopup": "Отображать результаты измерения во всплывающем окне",
  "angularUnitSelect": "Угловые единицы измерения по умолчанию",
  "linearUnitSelect": "Линейные единицы измерения по умолчанию",
  "areaUnitSelect": "Единицы площади по умолчанию",
  "displayOperationSelect": "Выбрать операции измерения",
  "errorSectionMessage": "Ни один из слоев не поддерживает возможность измерения.",
  "unitLabel": {
    "esriInches": "Дюймы",
    "esriFeet": "Футы",
    "esriYards": "Ярды",
    "esriMiles": "Мили",
    "esriNauticalMiles": "Морские мили",
    "esriMillimeters": "Миллиметры",
    "esriCentimeters": "Сантиметры",
    "esriDecimeters": "Дециметры",
    "esriMeters": "Метры",
    "esriKilometers": "Километры",
    "esriDURadians": "Радианы",
    "esriDUDecimalDegrees": "Градусы",
    "esriSquareInches": "Кв. дюйм",
    "esriSquareFeet": "Кв. Футы",
    "esriSquareYards": "Кв. Ярды",
    "esriAcres": "Акры",
    "esriSquareMiles": "Кв. Мили",
    "esriSquareMillimeters": "Кв. миллиметр",
    "esriSquareCentimeters": "Кв. сантиметр",
    "esriSquareDecimeters": "Кв. дециметр",
    "esriSquareMeters": "Кв. Метры",
    "esriAres": "Ары",
    "esriHectares": "Гектары",
    "esriSquareKilometers": "Кв. Километры"
  },
  "operationLabel": {
    "esriMensurationPoint": "Местоположение",
    "esriMensurationDistanceAndAngle": "Расстояние и угол",
    "esriMensurationAreaAndPerimeter": "Площадь и периметр",
    "esriMensurationHeightFromBaseAndTop": "Высота: от основания до вершины",
    "esriMensurationHeightFromBaseAndTopShadow": "Высота: от основания до верхней точки тени",
    "esriMensurationHeightFromTopAndTopShadow": "Высота: от вершины до верхней точки тени",
    "esriMensurationCentroid": "Центроид",
    "esriMensurationPoint3D": "Местоположение (3D)",
    "esriMensurationDistanceAndAngle3D": "Расстояние и угол (3D)",
    "esriMensurationAreaAndPerimeter3D": "Площадь и периметр (3D)",
    "esriMensurationCentroid3D": "Центроид (3D)"
  }
});