define({
  "layerSelect": "Vyberte vrstvu obrazu",
  "displayMeasureResultInPopup": "Zobrazit výsledky měření ve vyskakovacím okně",
  "angularUnitSelect": "Výchozí úhlová jednotka",
  "linearUnitSelect": "Výchozí délková jednotka",
  "areaUnitSelect": "Výchozí plošná jednotka",
  "displayOperationSelect": "Vybrat operace měření",
  "errorSectionMessage": "Žádná z vrstev nepodporuje funkcionalitu měření.",
  "unitLabel": {
    "esriInches": "Palce",
    "esriFeet": "Stopy",
    "esriYards": "Yardy",
    "esriMiles": "Míle",
    "esriNauticalMiles": "Námořní míle",
    "esriMillimeters": "Milimetry",
    "esriCentimeters": "Centimetry",
    "esriDecimeters": "Decimetry",
    "esriMeters": "Metry",
    "esriKilometers": "Kilometry",
    "esriDURadians": "radiány",
    "esriDUDecimalDegrees": "Stupně",
    "esriSquareInches": "Čtver. palce",
    "esriSquareFeet": "Čtv. stopy",
    "esriSquareYards": "Čtv. yardy",
    "esriAcres": "Akry",
    "esriSquareMiles": "Čtv. míle",
    "esriSquareMillimeters": "Čtver. milimetry",
    "esriSquareCentimeters": "Čtver. centimetry",
    "esriSquareDecimeters": "Čtver. decimetry",
    "esriSquareMeters": "Čtv. metry",
    "esriAres": "Ary",
    "esriHectares": "Hektary",
    "esriSquareKilometers": "Čtv. kilometry"
  },
  "operationLabel": {
    "esriMensurationPoint": "Umístění",
    "esriMensurationDistanceAndAngle": "Vzdálenost a úhel",
    "esriMensurationAreaAndPerimeter": "Plocha a obvod",
    "esriMensurationHeightFromBaseAndTop": "Výška: Od nejnižšího k nejvyššímu",
    "esriMensurationHeightFromBaseAndTopShadow": "Výška: Od nejnižšího ke stínu nejvyššího",
    "esriMensurationHeightFromTopAndTopShadow": "Výška: Od nejvyššího ke stínu nejvyššího",
    "esriMensurationCentroid": "Geografické těžiště",
    "esriMensurationPoint3D": "Umístění (3D)",
    "esriMensurationDistanceAndAngle3D": "Vzdálenost a úhel (3D)",
    "esriMensurationAreaAndPerimeter3D": "Plocha a obvod (3D)",
    "esriMensurationCentroid3D": "Geografické těžiště (3D)"
  }
});