define({
  "routeUrl": "मार्ग का URL",
  "locatorUrl": "जियोकोडर URL",
  "geocoderOptions": "Geocoder विकल्प",
  "autoComplete": "स्वत:पूर्ण",
  "maximumSuggestions": "अधिकतम सुझाव",
  "minCharacters": "न्यूनतम वर्ण",
  "searchDelay": "खोज में देरी",
  "placeholder": "प्लेसहोल्डर",
  "routeOptions": "मार्ग विकल्प",
  "directionsLanguage": "दिशाओं की भाषा",
  "directionsLengthUnits": "दिशाओं की लंबाई की इकाइयाँ",
  "directionsOutputType": "दिशाओं की आउटपुट का प्रकार",
  "impedanceAttribute": "प्रतिक्रिया विशेषता",
  "kilometers": "किलोमीटर",
  "miles": "मील",
  "meters": "मीटर",
  "feet": "फ़ीट",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "parametersTip": "कृपया सही ढंग से पैरामीटर सेट करें!",
  "complete": "पूर्ण हुआ",
  "completeNoEvents": "कोई इवेंट नहीं को पूर्ण करें",
  "instructionsOnly": "केवल निर्देश",
  "standard": "मानक",
  "summaryOnly": "केवल सारांश",
  "travelModesUrl": "यात्रा साधन का URL",
  "searchPlaceholder": "पता या स्थान खोजें",
  "trafficLayerUrl": "ट्रैफिक लेयर का URL",
  "presetDestinations": "वतर्मान स्टॉप",
  "startPoint": "प्रारंभ बिंदु",
  "endPoint": "समाप्ति बिंदु",
  "destinationHolder": "पता या निर्देशांक",
  "optional": "वैकल्पिक."
});