define({
  "_widgetLabel": "Emergency Response Guide",
  "ergMainPageTitle": "Basiert auf dem Emergency Response Guidebook 2016",
  "coordInputLabelStart": "Kontaminationsgebiet (DD)",
  "coordInputLabel": "Kontaminationsgebiet",
  "addPointToolTip": "Kontaminationsgebiet hinzufügen",
  "drawPointToolTip": "Klicken Sie hier, um ein Kontaminationsgebiet hinzuzufügen.",
  "material": "Stoff",
  "materialPlaceholder": "Beginnen Sie mit der Eingabe, um nach einem Stoff zu suchen.",
  "table3Message": "Für den ausgewählten Stoff sind zusätzliche Informationen erforderlich, falls es um eine Kontamination von großem Umfang geht.\n\nStellen Sie sicher, dass Sie die richtigen Werte für Windgeschwindigkeit und Transportbehälter ausgewählt haben.",
  "table2Message": "Der ausgewählte Stoff kann bei der Vermischung mit Wasser eine große Menge an Atemgift produzieren.\n\nSie können den/die folgenden Stoff(e) verwenden:\n\n",
  "spillSize": "Umfang der Kontamination",
  "small": "Klein",
  "large": "Groß",
  "fireLabel": "Brandschutzzone anzeigen",
  "weatherLabel": "Aktuelle Wetterlage im Kontaminationsgebiet",
  "weatherIntialText": "<br />Wird aktualisiert, sobald ein Kontaminationsgebiet identifiziert wurde",
  "temperature": "Temperatur",
  "wind": "Wind",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Keine Wetterinformationen abgerufen. Aktualisieren Sie die Werte für die Windgeschwindigkeit und die Uhrzeit der Kontamination manuell.",
  "windDirection": "Windzugrichtung",
  "timeOfSpill": "Zeit der Kontamination",
  "day": "Tag",
  "night": "Nacht",
  "windSpeed": "Windgeschwindigkeit",
  "low": "Niedrig",
  "moderate": "Mittel",
  "high": "Hoch",
  "transportContainer": "Transportbehälter",
  "rail": "Schienentankwagen",
  "semi": "Tanklastzug oder -auflieger",
  "mton": "Mehrtonnenzylinder",
  "ston": "Mehrere kleine Zylinder oder Einzeltonnenzylinder",
  "ag": "Zubringertank",
  "msm": "Mehrere kleine Zylinder",
  "bleveLabel": "BLEVE-Gefahrenbereich anzeigen",
  "capacity": "Containerkapazität (Liter)",
  "bleveMessage": "Für den ausgewählten Stoff kann für BLEVE ein zusätzlicher Evakuierungsabstand angezeigt werden.\n\nAktivieren Sie hierzu die Umschaltfläche \"BLEVE-Gefahrenbereich anzeigen\", und wählen Sie die entsprechende Containerkapazität aus.",
  "noPAZoneMessage": "Für diesen Stoff sind keine Abstände für Schutzmaßnahmen verfügbar. Es wurden lediglich initiale Schutz- und Evakuierungszonen berechnet.",
  "settingsTitle": "Einstellungen",
  "spillLocationLabel": "Kontaminationsgebiet",
  "spillLocationButtonLabel": "Einstellungen für Kontaminationsgebiete konfigurieren",
  "IISettingsLabel": "Initiale Schutzzone",
  "IIButtonLabel": "Einstellungen für initialen Schutz konfigurieren",
  "PASettingsLabel": "Schutzmaßnahmenzone",
  "PAButtonLabel": "Einstellungen für Schutzmaßnahmen konfigurieren",
  "downwindSettingsLabel": "Windzugrichtungszone",
  "downwindButtonLabel": "Einstellungen für Windzugrichtungen konfigurieren",
  "fireSettingsLabel": "Brandschutzzone",
  "fireButtonLabel": "Einstellungen für Brandschutzzonen konfigurieren",
  "bleveSettingsLabel": "BLEVE-Gefahrenbereich",
  "bleveButtonLabel": "BLEVE-Einstellungen konfigurieren",
  "style": "Style",
  "lineStyles": {
    "esriSLSDash": "Strich",
    "esriSLSDashDot": "Strich-Punkt",
    "esriSLSDashDotDot": "Strich-Punkt-Punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Langer Strich",
    "esriSLSLongDashDot": "Langer Strich-Punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kurzer Strich",
    "esriSLSShortDashDot": "Kurzer Strich-Punkt",
    "esriSLSShortDashDotDot": "Kurzer Strich-Punkt-Punkt",
    "esriSLSShortDot": "Kurzer Punkt",
    "esriSLSSolid": "Durchgezogen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Rückwärts",
    "esriSFSCross": "Kreuzförmig",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Vorwärts",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vollfarbe",
    "esriSFSVertical": "Vertikal"
  },
  "resultsTitle": "Ergebnisse",
  "publishERGBtn": "Veröffentlichen",
  "ERGLayerName": "Name des veröffentlichten ERG-Layers",
  "invalidERGLayerName": "Der Layer-Name darf nur alphanumerische Zeichen und Unterstriche enthalten.",
  "missingERGLayerName": "Sie müssen einen Namen für die ERG eingeben.",
  "publishingFailedLayerExists": "Fehler beim Veröffentlichen: Sie verfügen bereits über einen Service mit dem Namen {0}. Wählen Sie einen anderen Namen aus.",
  "checkService": "Service {0} überprüfen",
  "createService": "Service {0} erstellen",
  "unableToCreate": "{0} kann nicht erstellt werden",
  "addToDefinition": "Zur Definition {0} hinzufügen",
  "successfullyPublished": "Web-Layer wurde erfolgreich veröffentlicht{0}Web-Layer verwalten",
  "userRole": "Der Service kann nicht erstellt werden, da dem Benutzer nicht die entsprechenden Berechtigungen zugewiesen sind.",
  "transparency": "Transparenz",
  "outline": "Umrisslinie",
  "fill": "Füllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",
  "createERGBtn": "Zonen erstellen",
  "clearERGBtn": "Löschen",
  "labelFormat": "Beschriftungsformat",
  "helpIconTooltip": "Die Schwellenwerte zwischen Kontaminationen von kleinem und großem Umfang lauten:\nFlüssigkeiten - 208 Liter\nFeststoffe - 300 Kilogramm",
  "cellWidth": "Zellenbreite (x)",
  "cellHeight": "Zellenhöhe (y)",
  "invalidNumberMessage": "Der eingegebene Wert ist ungültig",
  "invalidRangeMessage": "Wert muss größer als 0 sein",
  "gridAngleInvalidRangeMessage": "Wert muss zwischen -89,9 und 89,9 liegen",
  "formatIconTooltip": "Eingabe formatieren",
  "setCoordFormat": "Zeichenfolge für Koordinatenformat festlegen",
  "prefixNumbers": "Positiven und negativen Zahlen ein \"+/-\"-Präfix hinzufügen",
  "cancelBtn": "Abbrechen",
  "applyBtn": "Anwenden",
  "comfirmInputNotation": "Eingegebene Schreibweise bestätigen",
  "notationsMatch": "Die Schreibweisen entsprechen Ihrer Eingabe. Geben Sie an, welche Sie verwenden möchten:",
  "missingLayerNameMessage": "Sie müssen einen gültigen Layer-Namen eingeben, bevor Sie ihn veröffentlichen können.",
  "parseCoordinatesError": "Koordinaten können nicht geparst werden. Überprüfen Sie Ihre Eingabe.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dezimalgrad – Breitengrad/Längengrad",
  "DDLongLatNotation": "Dezimalgrad – Längengrad/Breitengrad",
  "DDMLatLongNotation": "Grad Dezimalminuten – Breitengrad/Längengrad",
  "DDMLongLatNotation": "Grad Dezimalminuten – Längengrad/Breitengrad",
  "DMSLatLongNotation": "Grad, Minuten, Sekunden – Breitengrad/Längengrad",
  "DMSLongLatNotation": "Grad, Minuten, Sekunden – Längengrad/Breitengrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbuchstabe",
  "UTMHemNotation": "UTM – Hemisphäre (N/S)"
});