define({
  "_widgetLabel": "Inteligentny edytor",
  "_featureAction_SmartEditor": "Inteligentny edytor",
  "noEditPrivileges": "Twoje konto nie ma uprawnień do tworzenia ani modyfikowania danych.",
  "widgetActive": "Aktywny",
  "widgetNotActive": "Nieaktywny",
  "pressStr": "Naciśnij ",
  "ctrlStr": " CTRL, ",
  "snapStr": " aby włączyć dociąganie",
  "noAvailableTempaltes": "Brak dostępnych szablonów",
  "editorCache": " — bufor edytora",
  "presetFieldAlias": "Pole",
  "presetValue": "Wartość ustawiona wstępnie",
  "usePresetValues": " Użyj wartości ustawionych wstępnie (tylko nowe obiekty)",
  "editGeometry": " Edytuj geometrię",
  "savePromptTitle": "Zapisz obiekt",
  "savePrompt": "Czy chcesz zapisać bieżący obiekt?",
  "deletePromptTitle": "Usuń obiekt",
  "deletePrompt": "Czy na pewno chcesz usunąć wybrany obiekt?",
  "attachmentLoadingError": "Błąd przesyłania załączników",
  "attachmentSaveDeleteWarning": "Ostrzeżenie: zmiany w załącznikach są zapisywane automatycznie",
  "autoSaveEdits": "Automatycznie zapisuje modyfikacje",
  "addNewFeature": "Utwórz nowy obiekt",
  "featureCreationFailedMsg": "Nie można utworzyć nowego rekordu/obiektu",
  "noRelatedFeatureFoundMsg": "Nie znaleziono powiązanych rekordów/obiektów.",
  "relatedItemTitle": "Powiązana tabela/warstwa",
  "invalidRelationShipMsg": "Upewnij się, że pole klucza podstawowego: '${parentKeyField}' ma prawidłową wartość",
  "pendingFeatureSaveMsg": "Zapisz edycje obiektów przed utworzeniem powiązanego obiektu.",
  "attachmentsRequiredMsg": "(*) Wymagane są załączniki.",
  "filterEditor": {
    "all": "Wszystkie",
    "noAvailableTempaltes": "Brak dostępnych szablonów",
    "searchTemplates": "Szablony wyszukiwania"
  },
  "invalidConfiguration": "Widżet nie został skonfigurowany lub warstwy w tej konfiguracji nie znajdują się już na mapie. Otwórz aplikację w trybie kreatora i ponownie skonfiguruj widżet.",
  "geometryServiceURLNotFoundMSG": "Nie można uzyskać adresu URL usługi geometrii"
});