define({
  "_widgetLabel": "Руководство по действиям в условиях чрезвычайных ситуаций",
  "ergMainPageTitle": "Основано на Руководстве к действиям в чрезвычайных ситуациях 2016",
  "coordInputLabelStart": "Местоположение разлива (DD)",
  "coordInputLabel": "Местоположение разлива",
  "addPointToolTip": "Добавить местоположение разлива",
  "drawPointToolTip": "Щелкните, чтобы добавить местоположение разлива",
  "material": "Вещество",
  "materialPlaceholder": "Начать печатать, чтобы найти вещество",
  "table3Message": "Для выбранного вами вещества необходима дополнительная информация, если имеется большой разлив.\n\nПроверьте, что для скорости ветра и транспортного контейнера выбраны корректные значения.",
  "table2Message": "При разливе в воду, выбранное вещество может производить большой объем ядовитых, вредных для дыхания газов.\n\nВы можете рассмотреть использование следующих веществ:\n\n",
  "spillSize": "Размер разлива",
  "small": "Малый",
  "large": "Большой",
  "fireLabel": "Показать зону изоляции пожара",
  "weatherLabel": "Текущая погода в местоположении разлива",
  "weatherIntialText": "<br />Обновлено, как только указано местоположение разлива",
  "temperature": "Температура",
  "wind": "Ветер",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Сведения о погоде не получены. Обновите значения скорости ветра и времени разлива вручную",
  "windDirection": "Направление ветра (куда дует)",
  "timeOfSpill": "Время разлива",
  "day": "День",
  "night": "Ночь",
  "windSpeed": "Скорость ветра",
  "low": "Низкая",
  "moderate": "Средняя",
  "high": "Высокая",
  "transportContainer": "Транспортный контейнер",
  "rail": "Железнодорожная цистерна",
  "semi": "Автоцистерна или трейлер",
  "mton": "Несколько баллонов по тонне",
  "ston": "Несколько малых баллонов или один баллон на тонну",
  "ag": "Сельскохозяйственная заправочная цистерна",
  "msm": "Несколько малых баллонов",
  "bleveLabel": "Показать зону изоляции BLEVE",
  "capacity": "Емкость контейнера (литры)",
  "bleveMessage": "Для выбранного вещества для BLEVE можно показать дополнительное расстояние эвакуации.\n\nДля этого включите переключатель Показать зону изоляции BLEVE и выберите соответствующую емкость контейнера.",
  "noPAZoneMessage": "Для этого вещества нет расстояний защитных действий. Можно вычислить только зоны исходной изоляции и эвакуации",
  "settingsTitle": "Настройки",
  "spillLocationLabel": "Местоположение разлива",
  "spillLocationButtonLabel": "Настроить параметры местоположения разлива",
  "IISettingsLabel": "Исходная зона изоляции",
  "IIButtonLabel": "Настроить параметры исходной изоляции",
  "PASettingsLabel": "Зона защитных действий",
  "PAButtonLabel": "Настроить параметры защитных действий",
  "downwindSettingsLabel": "Подветренная зона",
  "downwindButtonLabel": "Настроить параметры подветренной зоны",
  "fireSettingsLabel": "Зона изоляции пожара",
  "fireButtonLabel": "Настроить параметры изоляции пожара",
  "bleveSettingsLabel": "Зона изоляции BLEVE",
  "bleveButtonLabel": "Настроить параметры BLEVE",
  "style": "Стиль",
  "lineStyles": {
    "esriSLSDash": "Тире",
    "esriSLSDashDot": "Тире-точка",
    "esriSLSDashDotDot": "Тире-точка-точка",
    "esriSLSDot": "Точка",
    "esriSLSLongDash": "Длинное тире",
    "esriSLSLongDashDot": "Длинное тире – Точка",
    "esriSLSNull": "Пустой",
    "esriSLSShortDash": "Короткое тире",
    "esriSLSShortDashDot": "Короткое тире – точка",
    "esriSLSShortDashDotDot": "Короткое тире – точка – точка",
    "esriSLSShortDot": "Короткая точка",
    "esriSLSSolid": "Сплошная"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Перекрестный",
    "esriSFSDiagonalCross": "Диагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "Горизонтально",
    "esriSFSNull": "Пустой",
    "esriSFSSolid": "Сплошной",
    "esriSFSVertical": "Вертикально"
  },
  "resultsTitle": "Результаты",
  "publishERGBtn": "Опубликовать",
  "ERGLayerName": "Имя опубликованного слоя ERG",
  "invalidERGLayerName": "Имя слоя должно содержать только буквы, цифры и подчеркивания.",
  "missingERGLayerName": "Необходимо ввести имя для ERG",
  "publishingFailedLayerExists": "Публикация не удалась: У вас уже имеется сервис объектов с именем {0}. Выберите другое имя.",
  "checkService": "Проверить сервис: {0}",
  "createService": "Создать сервис: {0}",
  "unableToCreate": "Невозможно создать: {0}",
  "addToDefinition": "Добавить в определение: {0}",
  "successfullyPublished": "Успешно опубликовать веб-слой{0}Управлять веб-слоем",
  "userRole": "Не удается создать сервис, так как у пользователя нет прав",
  "transparency": "Прозрачность",
  "outline": "Контур",
  "fill": "Заливка (Цвет применяется, только если задан сплошной)",
  "createERGBtn": "Создать зоны",
  "clearERGBtn": "Сброс",
  "labelFormat": "Формат подписи",
  "helpIconTooltip": "Граница между размерами малого и большого разлива:\nЖидкость – 55 галлонов (208 литров)\nТвердое вещество – 60 фунтов (300 килограмм)",
  "cellWidth": "Ширина ячейки (x)",
  "cellHeight": "Высота ячейки (y)",
  "invalidNumberMessage": "Введенное значение некорректно",
  "invalidRangeMessage": "Значение должно быть больше 0",
  "gridAngleInvalidRangeMessage": "Значение должно быть между -89,9 и 89,9.",
  "formatIconTooltip": "Входной формат",
  "setCoordFormat": "Строка настройки формата координат",
  "prefixNumbers": "Добавьте префикс \"+/–\" для положительных и отрицательных чисел",
  "cancelBtn": "Отмена",
  "applyBtn": "Применить",
  "comfirmInputNotation": "Подтвердите входное уведомление",
  "notationsMatch": "уведомления,соответствуют входным данным Выберите, что вы хотите использовать:",
  "missingLayerNameMessage": "Перед публикацией необходимо ввести корректное имя слоя",
  "parseCoordinatesError": "Невозможно обработать координаты. Проверьте входные данные.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десятичные градусы – Широта/Долгота",
  "DDLongLatNotation": "Десятичные градусы – Широта/Долгота",
  "DDMLatLongNotation": "Градусы, десятичные минуты – Широта/Долгота",
  "DDMLongLatNotation": "Градусы, десятичные минуты – Широта/Долгота",
  "DMSLatLongNotation": "Градусы минуты секунды – Широта/Долгота",
  "DMSLongLatNotation": "Градусы минуты секунды – Широта/Долгота",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Буква пояса",
  "UTMHemNotation": "UTM  – Полушарие (N/S)"
});