define({
  "tabs_section_Label": "탭",
  "addTab": "탭 추가",
  "layerName": "레이어",
  "layerType": "분석 유형",
  "layerLabel": "레이블",
  "actions": "작업",
  "closest": "가장 가까운 피처",
  "proximity": "인접도",
  "summary": "요약",
  "select_lbl": "-- 선택 --",
  "general_setting_Label": "일반 설정",
  "units_text_lbl": "거리 단위",
  "maximum_distance_lbl": "가장 가까운 피처 최대 거리",
  "buffer_text_lbl": "버퍼 레이블",
  "buffer_lbl": "버퍼 거리",
  "buffer_max_lbl": "최대 버퍼 거리",
  "buffer_min_lbl": "최소 버퍼 거리",
  "buffer_default_lbl": "기본 버퍼 거리",
  "not_less_than_max": "거리는 최대 버퍼 거리보다 작아야 함",
  "not_between": "거리는 최소 버퍼 거리와 최대 버퍼 거리 사이에 속해야 함",
  "not_more_than_min": "거리는 최소 버퍼 거리보다 커야 함",
  "not_valid_number": "올바른 숫자여야 함",
  "invalid_value": "${type} 값이 올바르지 않음",
  "routing_checkBox": "경로 지정 활성화",
  "weather_Label": "날씨 설정",
  "weather_checkBox": "날씨 활성화",
  "weather_map_layers": "날씨 레이어 선택...",
  "selected_map_layers": " 날씨 레이어가 선택됨",
  "instruction_weather": "패널에서 날씨 정보를 봅니다.",
  "instruction_weather_layers": "추가 날씨 레이어를 봅니다.",
  "instruction_weather_metric": "표준/미터법 값을 봅니다.",
  "selectLayers": "날씨 레이어 선택",
  "weather_removed_message": "이 위젯에는 날씨 옵션이 더 이상 제공되지 않습니다.",
  "currentlySelectedLayer": "맵 레이어에서 선택",
  "missingTabLabel": "하나 이상의 탭에 레이블이 누락됨",
  "missingLayerInWebMap": "운영 레이어를 찾을 수 없습니다.",
  "selectFields": "필드 선택",
  "addField": "필드 추가",
  "sum": "합계",
  "min": "최소값",
  "max": "최대값",
  "avg": "평균",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "피처 개수 보기",
  "area_checkBox": "영역의 합 보기",
  "length_checkBox": "길이의 합 보기",
  "max_records": "최대 제한 도달",
  "save_label": "옵션 저장",
  "save_checkbox": "저장 활성화",
  "report_label": "보고서 옵션",
  "report_checkbox": "보고서 활성화",
  "csv_label": "CSV 옵션",
  "csv_checkbox": "모든 필드 내보내기",
  "display_label": "디스플레이 옵션",
  "display_checkbox": "요약 피처 보기",
  "snapshot_label": "스냅샷 옵션",
  "snapshot_checkbox": "스냅샷 활성화",
  "must_select_template": "저장 옵션에서 편집 템플릿 중 하나를 선택하세요.",
  "count_label": "개수 레이블",
  "area_label": "영역 레이블",
  "length_label": "길이 레이블",
  "invalid_string_width": "값이 너무 깁니다. ",
  "layer_type_not_supported": "레이어 유형이 지원되지 않음",
  "groupedSummary": "그룹화된 개수",
  "groupByField": "필드를 기준으로 그룹화",
  "labelType": "레이블 추가",
  "prefix": "접두사로",
  "suffix": "접미사로",
  "need_group_field": "필드를 기준으로 그룹을 정의하려면 편집 작업을 사용하세요.",
  "fieldTitle": "필드",
  "typeTitle": "유형",
  "actionsTitle": "작업",
  "save_point_checkbox": "포인트 저장",
  "save_line_checkbox": "라인 저장",
  "save_poly_checkbox": "폴리곤 저장",
  "no_valid_popup_fields": "팝업에 올바른 필드가 없습니다. 필드를 정의하려면 편집 작업을 사용하세요.",
  "no_valid_fields": "올바른 필드가 없습니다. 디스플레이 옵션을 정의하려면 편집 작업을 사용하세요.",
  "incident_label": "탭 레이블",
  "locate_incident_label": "관심영역(레이블)",
  "incident": "사건",
  "locate_incident": "사건 찾기",
  "buffer_value": "버퍼 거리",
  "tab_options": "분석",
  "export_options": "결과",
  "instruction_save": "피처 서비스에 위치를 저장합니다.",
  "instruction_snapshot": "위치를 기반으로 웹 맵을 생성합니다.",
  "instruction_report": "위치의 인쇄된 보고서를 생성합니다.",
  "instruction_all_fields": "CSV를 다운로드하여 모든 필드를 내보냅니다.",
  "data_label": "데이터 결과 설정",
  "layer_error": "레이어가 누락되었거나 잘못되었습니다.",
  "visibility_checkBox": "레이어 가시성 관리 비활성화",
  "downloadTab": {
    "reportLegend": "보고서 설정",
    "textColorLabel": "열 제목의 색상 선택",
    "setButtonLabel": "설정",
    "printGPServiceLabel": "인쇄 서비스 URL",
    "logoLabel": "로고",
    "logoChooserHint": "이미지를 변경하려면 이미지 아이콘 클릭",
    "footnoteLabel": "각주"
  }
});