define({
  "serviceUrl": "Nustatyti paslaugos URL:",
  "minIntSpacingLabel": "Mažiausias tinklelio dydis",
  "lineOpacityLabel": "Linijos permatomumas",
  "labelOpacityLabel": "Žymės permatomumas",
  "centerLabelOpacityLabel": "Centro žymės permatomumas",
  "gridZonePlacementLabel": "Tinklelio srities žymės vieta",
  "verticalLineLabels": "Vertikalios linijos žymės",
  "styleHeaderLabel": "Stilius",
  "indexHeaderLabel": "Tinklelio komponentas",
  "colorHeaderLabel": "Spalva",
  "fontSizeHeaderLabel": "Šrifto dydis",
  "lineWidthHeaderLabel": "Linijos plotis",
  "horizontalLabel": "Horizontalus",
  "verticalLabel": "Vertikalus",
  "upperLeftLabel": "Viršuje kairėje",
  "upperRightLabel": "Viršuje dešinėje",
  "lowerLeftLabel": "Apačioje kairėje",
  "lowerRightLabel": "Apačioje dešinėje",
  "centerLabel": "Centre",
  "errorMessage": "Konfigūracijos puslapyje yra klaidų. Prieš įrašydami, ištaisykite klaidas.",
  "checkBoxLabel": "Rodyti tinklelį, kai valdiklis uždarytas",
  "checkBoxLabelDashboard": "Rodyti tinklelį",
  "gzd": "Tinklelio zonos žymuo (GZD)",
  "gsid": "100 000 metrų tinklelio kvadrato identifikacija (GSID)",
  "grid10k": "10 000 metrų tinklelio linijos",
  "grid1k": "1 000 metrų tinklelio linijos",
  "grid100m": "100 metrų tinklelio linijos",
  "grid10m": "10 metrų tinklelio linijos",
  "switchBasemap": "Pakeisti pagrindo žemėlapį"
});