define({
  "add": "Cliquez pour procéder à l'ajout",
  "title": "Titre",
  "placeholderBookmarkName": "Nom du géosignet",
  "ok": "OK",
  "cancel": "Annuler",
  "warning": "Terminez la modification !",
  "edit": "Modifier le géosignet",
  "errorNameExist": "Le géosignet existe !",
  "errorNameNull": "Nom de géosignet non valide !",
  "addBookmark": "Créer",
  "thumbnail": "Miniature",
  "thumbnailHint": "Cliquez sur l'image pour la mettre à jour",
  "displayBookmarksAs": "Afficher les géosignets comme",
  "cards": "Fiches",
  "list": "Liste",
  "cardsTips": "Vue Carte",
  "listTips": "Vue Liste",
  "makeAsDefault": "Définir par défaut",
  "default": "Par défaut",
  "editable": "Autorisez l’ajout de géosignets dans le widget.",
  "alwaysSync": "Afficher les géosignets de la carte Web",
  "configCustom": "Afficher les géosignets personnalisés",
  "import": "Importer",
  "create": "Créer",
  "importTitle": "Importer des géosignets",
  "importFromWeb": "Importer des géosignets depuis la carte Web actuelle",
  "selectAll": "Sélectionner tout",
  "noBookmarkInConfig": "Cliquez sur Importer ou Créer pour ajouter des géosignets.",
  "noBookmarkInWebMap": "Aucun géosignet n’est configuré dans la carte.",
  "extent": "Etendue",
  "saveExtent": "Enregistrer l’étendue de la carte dans ce géosignet",
  "savelayers": "Enregistrer la visibilité des couches",
  "withVisibility": "Avec la visibilité des couches",
  "bookmark": "Géosignet",
  "addBtn": "Ajouter",
  "deleteBtn": "Effacer",
  "editBtn": "Modifie",
  "dragReorderTip": "Maintenir enfoncé et faire glisser pour réorganiser",
  "deleteBtnTip": "Supprimer le géosignet",
  "editBtnTip": "Modifier le géosignet"
});