define({
  root: ({
    layerSelect: "Select the Image Layer",
    displayMeasureResultInPopup: "Display Measure Results in a Pop-up",
    angularUnitSelect: "Default Angular Unit",
    linearUnitSelect: "Default Linear Unit",
    areaUnitSelect: "Default Area Unit",
    displayOperationSelect: "Select Measure Operations",
    errorSectionMessage: "None of the layers support mensuration capabilites.",
    unitLabel: {
      esriInches: "Inches",
      esriFeet: "Feet",
      esriYards: "Yards",
      esriMiles: "Miles",
      esriNauticalMiles: "Nautical Miles",
      esriMillimeters: "Millimeters",
      esriCentimeters: "Centimeters",
      esriDecimeters: "Decimeters",
      esriMeters: "Meters",
      esriKilometers: "Kilometers",
      esriDURadians: "Radians",
      esriDUDecimalDegrees: "Degrees",
      esriSquareInches: "Sq Inches",
      esriSquareFeet: "Sq Feet",
      esriSquareYards: "Sq Yards",
      esriAcres: "Acres",
      esriSquareMiles: "Sq Miles",
      esriSquareMillimeters: "Sq Millimeters",
      esriSquareCentimeters: "Sq Centimeters",
      esriSquareDecimeters: "Sq Decimeters",
      esriSquareMeters: "Sq Meters",
      esriAres: "Ares",
      esriHectares: "Hectares",
      esriSquareKilometers: "Sq Kilometers"
    },
    operationLabel: {
      esriMensurationPoint: "Location",
      esriMensurationDistanceAndAngle: "Distance and Angle",
      esriMensurationAreaAndPerimeter: "Area and Perimeter",
      esriMensurationHeightFromBaseAndTop: "Height: Base to Top",
      esriMensurationHeightFromBaseAndTopShadow: "Height: Base to Top-Shadow",
      esriMensurationHeightFromTopAndTopShadow: "Height: Top to Top-Shadow",
      esriMensurationCentroid: "Centroid",
      esriMensurationPoint3D: "Location (3D)",
      esriMensurationDistanceAndAngle3D: "Distance and Angle (3D)",
      esriMensurationAreaAndPerimeter3D: "Area and Perimeter (3D)",
      esriMensurationCentroid3D: "Centroid (3D)"
    }
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});