define({
  "_widgetLabel": "Zabilježi geoobjekt",
  "select": "Odaberi",
  "draw": "Crtaj",
  "chooseALayer": "Odaberi sloj",
  "clickAFeature": "Kliknite na geoobjekt na karti da biste ga odabrali.",
  "loadingFeatures": "Dobivanje pojedinosti o odabranim geoobjektima...",
  "errorTitle": "Pogreška",
  "errorIdentify": "Utvrdite pogrešku geobjekata. Provjerite zapis konzole za pojedinosti.",
  "infoWindowTitle": "Pojedinosti",
  "layerLabel": "Naziv sloja",
  "reviewStatusLabel": "Status pregleda",
  "selectReviewStatusAdd": "Dodaj geoobjekt",
  "selectReviewStatusDelete": "Izbriši geoobjekt",
  "selectReviewStatusMove": "Premjesti geoobjekt",
  "selectReviewStatusReshape": "Preoblikuj geoobjekt",
  "drawReviewStatusMissing": "Geoobjekt(i) koji nedostaje/u",
  "drawReviewStatusPosition": "Pogreška položaja",
  "drawReviewStatusShape": "Pogreška oblika",
  "drawReviewStatusAttribute": "Pogreška atributa",
  "notesLabel": "Bilješke",
  "severityLabel": "Ozbiljnost",
  "reportedByLabel": "Izvijestio",
  "reportedByDefault": "anonimna osoba",
  "reportButton": "Izvješće",
  "reportMessage": "Izvješće primljeno",
  "errorReportMessage": "Došlo je do pogreške pri izvještavanju o vašem geoobjektu",
  "drawErrorInstructions": "Odaberite točku, liniju ili poligon te nacrtajte geometriju pogreške na karti:",
  "errorMapService": "Došlo je do pogreške pri dobivanju informacija o usluzi karte",
  "noFeatureSelected": "Nema pronađenih geoobjekata na lokaciji na koju ste kliknuli",
  "selectFeatureMapPoint": "Kliknite da biste odabrali geoobjekt",
  "drawFeatureMapPoint": "Kliknite da biste dodali točku",
  "popupMessage": "Poruka",
  "popupError": "Pogreška",
  "manyFeaturesSelected": "Pronađeno je više od jednog geoobjekta. Uvećajte prikaz i odaberite geoobjekt za izvješće."
});