define({
  "symbolologyTabLabel": "Configurer la symbologie",
  "facilitiesDescription": "Couches des ressources",
  "demographicsDescription": "Couche démographique",
  "settingsTitle": "Réglages",
  "spillLocationLabel": "Point de déversement",
  "spillLocationButtonLabel": "Configurer les paramètres du point de déversement",
  "IISettingsLabel": "Zone d’isolation initiale",
  "IIButtonLabel": "Configurer les paramètres de l’isolation initiale",
  "PASettingsLabel": "Zone d’action de protection",
  "PAButtonLabel": "Configurer les paramètres d’action de protection",
  "downwindSettingsLabel": "Zone dans la direction du vent",
  "downwindButtonLabel": "Configurer les paramètres de la direction du vent",
  "fireSettingsLabel": "Zone d’isolation d’incendie",
  "fireButtonLabel": "Configurer les paramètres d’isolation d’incendie",
  "bleveSettingsLabel": "Zone d’isolation du BLEVE",
  "bleveButtonLabel": "Configurer les paramètres du BLEVE",
  "transparency": "Transparence",
  "outline": "Contour",
  "fill": "Remplissage (La couleur s’applique uniquement lorsque le style est uni)",
  "style": "Style",
  "lineStyles": {
    "esriSLSDash": "Tiret",
    "esriSLSDashDot": "Tiret-point",
    "esriSLSDashDotDot": "Tiret-point-point",
    "esriSLSDot": "Point",
    "esriSLSLongDash": "Tiret long",
    "esriSLSLongDashDot": "Tiret-point long",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Tiret court",
    "esriSLSShortDashDot": "Tiret court-point",
    "esriSLSShortDashDotDot": "Tiret court-point-point",
    "esriSLSShortDot": "Point court",
    "esriSLSSolid": "Solide"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Arrière",
    "esriSFSCross": "Croiser",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Avant",
    "esriSFSHorizontal": "Horizontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solide",
    "esriSFSVertical": "Verticale"
  }
});