define({
  "add": "按一下以新增",
  "title": "標題",
  "placeholderBookmarkName": "書籤名稱",
  "ok": "確定",
  "cancel": "取消",
  "warning": "請完成此編輯！",
  "edit": "編輯書籤",
  "errorNameExist": "書籤已存在！",
  "errorNameNull": "書籤名稱無效！",
  "addBookmark": "新建",
  "thumbnail": "縮圖",
  "thumbnailHint": "按一下圖片進行更新",
  "displayBookmarksAs": "將書籤顯示為",
  "cards": "卡",
  "list": "清單",
  "cardsTips": "卡片視圖",
  "listTips": "清單視圖",
  "makeAsDefault": "設為預設值",
  "default": "預設",
  "editable": "允許在 widget 中新增書籤。",
  "alwaysSync": "從 Web 地圖顯示書籤",
  "configCustom": "顯示自訂書簽",
  "import": "匯入",
  "create": "建立",
  "importTitle": "匯入書籤",
  "importFromWeb": "從目前的 Web 地圖中匯入書籤",
  "selectAll": "全選",
  "noBookmarkInConfig": "按一下「匯入」或「新建」以新增書籤。",
  "noBookmarkInWebMap": "地圖中未配置書籤。",
  "extent": "範圍",
  "saveExtent": "將地圖範圍儲存到此書籤",
  "savelayers": "儲存圖層可見性",
  "withVisibility": "包含圖層可見性",
  "bookmark": "書籤",
  "addBtn": "新增",
  "deleteBtn": "刪除",
  "editBtn": "編輯",
  "dragReorderTip": "按住並拖曳以重新排序",
  "deleteBtnTip": "刪除書籤",
  "editBtnTip": "編輯書籤"
});