define({
  "_widgetLabel": "स्मार्ट एडिटर",
  "_featureAction_SmartEditor": "स्मार्ट एडिटर",
  "noEditPrivileges": "आपके खाते को बनाने या डेटा संशोधित करने की अनुमति नहीं है।",
  "widgetActive": "सक्रिय",
  "widgetNotActive": "निष्क्रिय करें",
  "pressStr": "दबाएँ ",
  "ctrlStr": " CTRL ",
  "snapStr": " तड़क सक्षम करने के लिए",
  "noAvailableTempaltes": "कोई उपलब्ध टेम्पलेट्स",
  "editorCache": " - एडिटर कैश",
  "presetFieldAlias": "फ़ील्ड",
  "presetValue": "पूर्व निर्धारित मान",
  "usePresetValues": " पूर्व निर्धारित मानों का उपयोग करें (केवल नई फीचर्स)",
  "editGeometry": " Geometry संपादित करें",
  "savePromptTitle": "फीचर सहेजें",
  "savePrompt": "क्या आप वर्तमान फीचर को सहेजना चाहेंगे?",
  "deletePromptTitle": "फीचर मिटाएँ",
  "deletePrompt": "क्या आप वाकई चयनित फीचर को मिटाना चाहते हैं?",
  "attachmentLoadingError": "अनुलग्नक अपलोड करने में त्रुटि",
  "attachmentSaveDeleteWarning": "चेतावनी: संलग्नक में परिवर्तन स्वचालित रूप से सहेजें जाते हैं",
  "autoSaveEdits": "संपादन अपने आप सहेज लेता है",
  "addNewFeature": "नया फीचर बनाएं",
  "featureCreationFailedMsg": "नया रिकॉर्ड/फीचर नहीं बनाया जा सकता",
  "noRelatedFeatureFoundMsg": "कोई संबंधित रिकॉर्ड/फीचर नहीं मिला",
  "relatedItemTitle": "संबंधित तालिका/लेयर",
  "invalidRelationShipMsg": "कृपया सुनिश्चित करें कि प्राथमिक कुंजी क्षेत्र: '${parentKeyField}' का कोई वैध मान हो",
  "pendingFeatureSaveMsg": "कृपया संबंधित फीचर बनाने से पहले फीचर संपादन को सहेजें।",
  "attachmentsRequiredMsg": "(*) अनुलग्नक आवश्यक हैं।",
  "filterEditor": {
    "all": "सभी",
    "noAvailableTempaltes": "कोई उपलब्ध टेम्पलेट्स",
    "searchTemplates": "टेम्पलेट्स खोजें"
  },
  "invalidConfiguration": "विजेट या तो कॉन्फ़िगर नहीं है या कॉन्फ़िगर में लेयर अब मानचित्र में नहीं हैं। कृपया ऐप को बिल्डर मोड में खोलें और विजेट को फिर से कॉन्फ़िगर करें।",
  "geometryServiceURLNotFoundMSG": "ज्यामितीय सेवा URL पाने में सक्षम नहीं"
});