define({
  "add": "새 항목을 추가하려면 클릭",
  "title": "제목",
  "placeholderBookmarkName": "책갈피 이름",
  "ok": "확인",
  "cancel": "취소",
  "warning": "편집을 완료하세요.",
  "edit": "책갈피 편집",
  "errorNameExist": "책갈피가 있습니다.",
  "errorNameNull": "잘못된 책갈피 이름입니다.",
  "addBookmark": "새로 생성",
  "thumbnail": "섬네일",
  "thumbnailHint": "업데이트할 이미지 클릭",
  "displayBookmarksAs": "책갈피 표시",
  "cards": "카드",
  "list": "목록",
  "cardsTips": "카드 뷰",
  "listTips": "목록 뷰",
  "makeAsDefault": "기본으로 설정",
  "default": "기본",
  "editable": "위젯에 책갈피를 추가할 수 있습니다.",
  "alwaysSync": "웹 맵의 책갈피 표시",
  "configCustom": "사용자 정의 책갈피 표시",
  "import": "가져오기",
  "create": "생성",
  "importTitle": "책갈피 가져오기",
  "importFromWeb": "현재 웹 맵의 책갈피 가져오기",
  "selectAll": "모두 선택",
  "noBookmarkInConfig": "책갈피를 추가하려면 â€œ가져오기â€ 또는 â€œ새로 생성â€을 클릭하세요.",
  "noBookmarkInWebMap": "맵에 구성된 책갈피가 없습니다.",
  "extent": "범위(Extent)",
  "saveExtent": "맵 범위를 이 책갈피에 저장",
  "savelayers": "레이어 가시성 저장",
  "withVisibility": "레이어 가시성 포함",
  "bookmark": "책갈피",
  "addBtn": "추가",
  "deleteBtn": "삭제",
  "editBtn": "편집",
  "dragReorderTip": "누른 상태로 드래그하여 순서 바꾸기",
  "deleteBtnTip": "책갈피 삭제",
  "editBtnTip": "책갈피 편집"
});