define({
  "layerSelect": "Izberite slikovni sloj",
  "displayMeasureResultInPopup": "Prikaži rezultate merjenja v pojavnem oknu",
  "angularUnitSelect": "Privzeta kotna enota",
  "linearUnitSelect": "Privzeta linearna enota",
  "areaUnitSelect": "Privzeta površinska enota",
  "displayOperationSelect": "Izberi operacije merjenja",
  "errorSectionMessage": "Noben sloj ne podpira metričnih zmožnosti.",
  "unitLabel": {
    "esriInches": "Palci",
    "esriFeet": "Čevlji",
    "esriYards": "Jardi",
    "esriMiles": "Milje",
    "esriNauticalMiles": "Morske milje",
    "esriMillimeters": "Milimetri",
    "esriCentimeters": "Centimetri",
    "esriDecimeters": "Decimetri",
    "esriMeters": "Metri",
    "esriKilometers": "Kilometri",
    "esriDURadians": "Radiani",
    "esriDUDecimalDegrees": "Stopinje",
    "esriSquareInches": "Kvadratni palci",
    "esriSquareFeet": "Kvadratni čevlji",
    "esriSquareYards": "Kvadratni jardi",
    "esriAcres": "Akri",
    "esriSquareMiles": "Kvadratne milje",
    "esriSquareMillimeters": "Kvadratni milimetri",
    "esriSquareCentimeters": "Kvadratni centimetri",
    "esriSquareDecimeters": "Kvadratni decimetri",
    "esriSquareMeters": "Kvadratni metri",
    "esriAres": "Ari",
    "esriHectares": "Hektarji",
    "esriSquareKilometers": "Kvadratni kilometri"
  },
  "operationLabel": {
    "esriMensurationPoint": "Lokacija",
    "esriMensurationDistanceAndAngle": "Razdalja in kot",
    "esriMensurationAreaAndPerimeter": "Površina in obseg",
    "esriMensurationHeightFromBaseAndTop": "Višina: od tal do vrha",
    "esriMensurationHeightFromBaseAndTopShadow": "Višina: od tal do vrhnje sence",
    "esriMensurationHeightFromTopAndTopShadow": "Višina: od vrha do vrhnje sence",
    "esriMensurationCentroid": "Centroid",
    "esriMensurationPoint3D": "Lokacija (3D)",
    "esriMensurationDistanceAndAngle3D": "Razdalja in kot (3D)",
    "esriMensurationAreaAndPerimeter3D": "Površina in obseg (3D)",
    "esriMensurationCentroid3D": "Centroid (3D)"
  }
});