define({
  "settings": "Configuración",
  "titleSettings": "Configuración de texto",
  "imageSettings": "Configuración de imagen",
  "backgroundColor": "Color de fondo",
  "alignment": "Alineación",
  "textSize": "Tamaño de texto",
  "textColor": "Color de texto",
  "dataSource": "Fuente de datos",
  "chartSettings": "Configuración de gráfico",
  "data": "Datos",
  "dataLabels": "Etiquetas de datos",
  "displayMode": "Modo de visualización",
  "featureOption": "Mostrar valores entidad por entidad",
  "categoryOption": "Mostrar valores por categoría",
  "countOption": "Mostrar recuentos de entidades por categoría",
  "fieldOption": "Mostrar valores de atributos como gráficos",
  "categoryField": "Campo de categoría",
  "labelField": "Campo de etiquetado",
  "valueFields": "Campos de valores",
  "operation": "Operación",
  "sumOption": "Suma",
  "averageOption": "Media",
  "minOption": "Mínimo",
  "maxOption": "Máximo",
  "dataFormat": "Formato de datos",
  "decimalPlaces": "Posiciones decimales",
  "prefix": "Prefijo",
  "suffix": "Sufijo",
  "dataType": "Tipo de datos",
  "featureCount": "Recuento de entidades",
  "fieldStatistics": "Estadísticas de campo",
  "display": "Vista",
  "chartColor": "Color de gráfico",
  "horizontalAxis": "Eje horizontal",
  "verticalAxis": "Eje vertical",
  "legend": "Leyenda",
  "position": "Posición",
  "top": "Superior",
  "bottom": "Inferior",
  "useDataSourceSelection": "Usar selección",
  "dataSourceFilterByExtent": "Filtrar por extensión",
  "changeTemplate": "Cambiar plantilla",
  "numberSettings": "Configuración de número",
  "gaugeSettings": "Configuración de medidor",
  "indicators": "Indicadores",
  "ifValue": "Valor If",
  "and": "y",
  "numberOperatorIsLessThan": "es menos que",
  "numberOperatorIsGreaterThan": "es mayor que",
  "numberOperatorIsBetween": "está entre",
  "numberOperatorIsEqual": "es igual que",
  "numberOperatorIsNotEqual": "no es igual que",
  "then": "Antes",
  "ratio": "Relación",
  "trueValue": "Valor True",
  "changeValueColor": "cambiar color de valor a",
  "changeGaugeColor": "cambiar color de medidor a",
  "setIndicatorIcon": "definir icono de indicador como",
  "icons": "Iconos",
  "style": "Estilo",
  "placement": "Ubicación",
  "left": "Izquierda",
  "replace": "Reemplazar",
  "right": "Derecha",
  "color": "Color",
  "categoryExists": "¡Categoría existente!",
  "comboxHint": "Escribir o seleccionar uno",
  "comboxDisableInputHint": "Selección única",
  "sortBy": "Ordenar por",
  "labelAxis": "Etiqueta",
  "valueAxis": "Valor",
  "minPeriod": "Periodo mínimo",
  "automatic": "Automático",
  "periodsWithOutRecords": "Periodos sin registros",
  "nullValue": "Valor nulo",
  "calculatedAsZero": "Calculado como cero",
  "ignored": "Ignorado",
  "maxCategories": "Categorías máximas",
  "useLayerSymbology": "Usar simbología de la capa",
  "hollowsize": "Tamaño de hueco",
  "splitField": "Campo dividido",
  "parsingperiodTip": "Error de cómputo. Demasiados intervalos de tiempo debido al breve periodo de análisis.",
  "manyCategoryTip": "Error al mostrar el gráfico. Demasiadas categorías.",
  "setColor": "Establecer color",
  "setTheColorOf": "A continuación, definir color de",
  "setTheColorAs": "A continuación, definir color como",
  "ifStr": "Si",
  "as": "como",
  "is": "es",
  "isNot": "no es",
  "barCluster": "clúster de barras",
  "individualBar": "barra individual",
  "allOthers": "Todos los demás",
  "category": "Categoría",
  "indicatorSum": "SUMA",
  "indicatorAve": "MED",
  "indicatorMax": "MÁX",
  "indicatorMin": "MÍN",
  "setCorrectyIndicatorTip": "Defina los indicadores correctamente.",
  "dataRange": "Rango de datos",
  "targetValue": "Valor de destino",
  "currentValue": "Valor actual",
  "gaugeColor": "Color de medidor",
  "min": "Mínimo",
  "max": "Máximo",
  "displayValueIn": "Mostrar valor en",
  "noData": "Sin datos",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "Metro(s)",
  "billionAbbreviation": "G",
  "warning": "Advertencia",
  "noSettingWaring1": "Haga clic en un elemento para definir sus propiedades.",
  "noSettingWaring2": "Arrastre para ajustar el tamaño de un elemento o reordenarlo.",
  "donNotShowAgain": "No volver a mostrar",
  "changeTemplateWarning": "Esto borrará toda la configuración y abrirá una nueva plantilla vacía.",
  "requiredFieldWarning": "Este valor es obligatorio:",
  "dataSourceNotSet": "Establezca la fuente de datos.",
  "addIndicatorTip": "Agregar un indicador",
  "chooseTemplatePopupTitle": "Elija una plantilla",
  "filterExtentTipWithaTag": "Puede deshabilitar el filtro con <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Origen de datos adicional</a> en la pestaña Atributo.",
  "filterExtentTip": "Puede deshabilitar el filtro con Origen de datos adicional en la pestaña Atributo.",
  "customColorByCategory": "Color personalizado por categoría",
  "randomColor": "Color aleatorio",
  "valueString": "Valor",
  "fieldString": "Campo",
  "includeThresholdValue": "Incluir valor de umbral",
  "percentage": "Porcentaje",
  "colorSchema": "Esquema de color",
  "addCategory": "Agregar categoría",
  "clickToEdit": "Clic para editar",
  "nullText": "Nulo",
  "others": "Otros",
  "stringsInTemplate": {
    "name_number": "Número",
    "name_gauge": "Calibre",
    "name_vertical_gauge": "Medidor vertical",
    "name_horizontal_gauge": "Medidor horizontal",
    "name_pie": "Circular",
    "name_donut": "Donut",
    "name_bar": "Barra",
    "name_stacked_bar": "Barra apilada",
    "name_percentage_stacked_bar": "Barra apilada de porcentajes",
    "name_column": "Columna",
    "name_stacked_column": "Columna apilada",
    "name_percentage_stacked_column": "Columna apilada de porcentajes",
    "name_line": "Línea",
    "name_area": "Área",
    "name_stacked_area": "Área apilada",
    "name_percentage_stacked_area": "Área apilada de porcentajes",
    "titleOfTheInfographic": "TÍTULO DE LA INFOGRAFÍA",
    "description": "Descripción: información adicional sobre esta infografía."
  }
});