define({
  "_widgetLabel": "Modelo de Adequação",
  "general": {
    "clear": "Apagar",
    "cancel": "Cancelar",
    "save": "Executar",
    "saveAs": "Exportar"
  },
  "saveModel": {
    "save": "Exportar",
    "title": "Título: ",
    "summary": "Resumo: ",
    "description": "Descrição: ",
    "tags": "Tags: ",
    "folder": "Pasta: ",
    "homeFolderPattern": "{username} (Home)",
    "failed": "Não foi possível exportar."
  },
  "util": {
    "colorRamp": {
      "1": "Extremamente Baixo",
      "2": "Muito Baixo",
      "3": "Baixo",
      "4": "Médio Baixo",
      "5": "Médio",
      "6": "Médio Alto",
      "7": "Alto",
      "8": "Muito Alto",
      "9": "Extremamente Alto",
      "low": "Baixo",
      "high": "Alto",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Inverter"
    }
  },
  "wro": {
    "caption": "Modelo de Adequação",
    "browsePrompt": "Serviço de Sobreposição Ponderada",
    "selectLayersCaption": "Selecionar Camadas",
    "selectLayers": "Camadas",
    "designModelCaption": "Modelo de Projeto",
    "designModel": "Modelo de Projeto",
    "transparency": "Transparência",
    "visible": "Visível",
    "total": "Total",
    "unableToLoad": "Não foi possível carregar o modelo.",
    "projectNotOpen": "Um projeto não está aberto.",
    "readMore": "Leia Mais",
    "validation": {
      "validating": "Validando...",
      "invalidItemCaption": "Aviso do Serviço de Sobreposição Ponderada",
      "notAnImageService": "Este item não é um Serviço de Imagem.",
      "notAWroService": "Este item não é um Serviço de Sobreposição Ponderada.",
      "undefinedUrl": "Esta URL do item não está definida.",
      "inaccessible": "O serviço está inacessível.",
      "generalError": "Não foi possível abrir o item.",
      "missingFieldPattern": "{field} é um campo exigido",
      "notAllowRasterFunction": "allowRasterFunction deve ser configurado para verdadeiro",
      "notNearestResampling": "defaultResamplingMethod deve ser Mais Próximo",
      "notIsWeightedOverlayProp": "A propriedade-chave IsWeightedOverlay deve ser configurada para verdadeiro",
      "invalidLink": "A URL é inválida. Falha ao abrir o site para camada selecionada.",
      "unexpectedError": "Ocorreu um status inesperado.",
      "rangeMessage": "O valor deve estar entre ${0} e ${1}",
      "rangeMessage100": "O valor deve estar entre 0 e 100.",
      "maxLayers": "Máximo de ${0} camadas permitidas por serviço, você deve primeiro remover uma camada antes de adicionar uma nova.",
      "notFound": "Camada ${0} não localizada no serviço de sobreposição ponderada",
      "wroServiceNotDefined": "Nenhum serviço de sobreposição ponderada definido para o modelo.",
      "overlayLayerOutputInvalid": "Valor de saída [${1}] dos intervalos de remapeamento da camada de sobreposição [${0}] ausente ou inválido",
      "overlayLayerInputInvalid": "Máx/mín de entrada [${1}] dos intervalos de remapeamento da camada de sobreposição [${0}] ausente ou inválido",
      "overlayLayerRangesMissing": "Intervalos de remapeamento ausentes na camada de sobreposição [${0}]",
      "overlayLayerWeight": "Os pesos da camada de sobreposição devem adicionar até 100",
      "overlayLayerRequired": "Pelo menos uma camada de sobreposição é exigida",
      "overlayLayerNotDefined": "As camadas de sobreposição não estão definidas",
      "requiresColormap": "Esta função do raster exige um mapa de cores, mas o modelo não tem uma definição do mapa de cores válida",
      "createModelError": "Erro ao Criar Modelo",
      "invalidModel": "O modelo não é válido",
      "imageServiceNotDefined": "A camada do serviço de imagem não está definida",
      "imageLayerNotDefined": "A camada do serviço de imagem não está definida",
      "histogramNotDefined": "Nenhuma função do histograma de sobreposição ponderada definida."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Verde Amarelo Vermelho",
      "Red Yellow Green": "Vermelho Amarelo Verde",
      "Yellow to Dark Red": "Amarelo para Vermelho Escuro",
      "Dark Red to Yellow": "Vermelho Escuro para Amarelo",
      "Light Gray to Dark Gray": "Cinza Claro para Cinza Escuro",
      "Dark Gray to Light Gray": "Cinza Escuro para Cinza Claro",
      "Light Brown to Dark Brown": "Marrom Claro para Marron Escuro",
      "Dark Brown to Light Brown": "Marrom Escuro para Marron Claro",
      "Full Spectrum - Bright Red to Blue": "Espectro Total - Vermelho Claro para Azul",
      "Full Spectrum - Bright Blue to Red": "Espectro Total - Azul Claro para Vermelho",
      "Partial Spectrum - Yellow to Blue": "Espectro Parcial - Amarelo para Azul",
      "Partial Spectrum - Blue to Yellow": "Espectro Parcial - Azul para Amarelo",
      "Yellow-Green to Dark Blue": "Amarelo-Verde para Azul Escuro",
      "Dark Blue to Yellow-Green": "Azul Escuro para Amarelo-Verde",
      "Cold to Hot Diverging": "Divergência de Frio para Quente",
      "Hot to Cold Diverging": "Divergência de Valor Baixo para Alto",
      "Surface - Low to High": "Superfície - Baixo para Alto",
      "Surface - High to Low": "Superfície - Alto para Baixo"
    }
  },
  "tabs": {
    "layers": "Camadas",
    "model": "Modelo",
    "chart": "Gráfico"
  },
  "chart": {
    "prompt": "Recursos",
    "working": "Atualizando...",
    "polygonTool": "Desenhar um Polígono",
    "freehandPolygonTool": "Desenhar um Polígono à Mão Livre",
    "selectTool": "Selecionar da Camada",
    "panTool": "Mover",
    "clearButton": "Apagar",
    "noModelLayer": "Nenhum modelo.",
    "noSubjectLayers": "Seu mapa não tem camadas de polígono.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});