define({
  "labelBookmarkName": "Obeleži trenutni prikaz",
  "labelPlay": "Reprodukuj sve",
  "labelStop": "Zaustavi",
  "labelDelete": "Obriši",
  "placeholderBookmarkName": "Ime obeleživača",
  "errorNameExist": "Obeleživač postoji!",
  "errorNameNull": "Nevažeće ime obeleživača!",
  "editTip": "Uredi obeleživače",
  "exitEditTip": "Izađi iz režima za uređivanje",
  "syncTip": "Sinhronizuj",
  "cardsTips": "Prikaz u vidu mreže",
  "listTips": "Prikaz u vidu liste",
  "addBtn": "Dodaj",
  "deleteBtn": "Izbriši",
  "changeThumbnailTip": "Promeni sličicu",
  "dragReorderTip": "Zadržite i prevucite radi preuređivanja",
  "deleteBtnTip": "Izbriši obeleživač",
  "editBtnTip": "Izmeni obeleživač",
  "withVisibility": "Sa vidljivošću sloja",
  "searchBookmark": "Pretraži",
  "bookmarksFromConfig": "Unapred konfigurisani obeleživači",
  "bookmarksFromCache": "Lokalni privremeni obeleživači",
  "notice": "Obaveštenje",
  "changeNoticeTips": "Promene će biti sačuvane samo u kešu vašeg pregledača. Sinhronizacija između vidžeta i njegove konfiguracije je prekinuta kada izvršite izmene.",
  "syncNoticeTips": "To će izbrisati sve vaše izmene i vratiti konfigurisane obeleživače.",
  "dontShowAgain": "Ne prikazuj ponovo",
  "saveVisibility": "Sačuvaj vidljivost sloja",
  "_widgetLabel": "Obeleživač"
});