define({
  "routeUrl": "Rotalama URL'si",
  "locatorUrl": "Coğrafi Kodlayıcı URL'si",
  "geocoderOptions": "Coğrafi kodlayıcı seçenekleri",
  "autoComplete": "Otomatik Tamamla",
  "maximumSuggestions": "Maksimum öneri sayısı",
  "minCharacters": "Minimum karakter sayısı",
  "searchDelay": "Arama gecikmesi",
  "placeholder": "Yer Tutucu",
  "routeOptions": "Rota seçenekleri",
  "directionsLanguage": "Yol tarifi dili",
  "directionsLengthUnits": "Yol tarifi uzunluk birimi",
  "directionsOutputType": "Yol tarifi çıktı türü",
  "impedanceAttribute": "Empedans özniteliği",
  "kilometers": "Kilometre",
  "miles": "Mil",
  "meters": "Metre",
  "feet": "Fit",
  "yards": "Yarda",
  "nauticalMiles": "Deniz mili",
  "parametersTip": "Parametreleri doğru ayarlayın!",
  "complete": "Tamam",
  "completeNoEvents": "Hiçbir Olayı Tamamlama",
  "instructionsOnly": "Yalnızca talimatlar",
  "standard": "Standart",
  "summaryOnly": "Yalnızca özet",
  "travelModesUrl": "Seyahat modları URL'si",
  "searchPlaceholder": "Adres veya yer bul",
  "trafficLayerUrl": "Trafik katmanı URL'si",
  "presetDestinations": "Önceden ayarlanan duraklar",
  "startPoint": "Başlangıç noktası",
  "endPoint": "Bitiş noktası",
  "destinationHolder": "Adres veya koordinatlar",
  "optional": "İsteğe bağlıdır."
});