define({
  "routeUrl": "URL de l’itinéraire",
  "locatorUrl": "URL du géocodeur",
  "geocoderOptions": "Options du géocodeur",
  "autoComplete": "Terminer automatiquement",
  "maximumSuggestions": "Nombre maximal de suggestions",
  "minCharacters": "Nombre minimum de caractères",
  "searchDelay": "Délai de recherche",
  "placeholder": "Espace réservé",
  "routeOptions": "Options de l’itinéraire",
  "directionsLanguage": "Langue de la feuille de route",
  "directionsLengthUnits": "Unités de distance de la feuille de route",
  "directionsOutputType": "Type de sortie de la feuille de route",
  "impedanceAttribute": "Attribut d’impédance",
  "kilometers": "Kilomètres",
  "miles": "Miles",
  "meters": "Mètres",
  "feet": "Pieds",
  "yards": "Yards",
  "nauticalMiles": "Milles marins",
  "parametersTip": "Définissez les paramètres correctement.",
  "complete": "Complet",
  "completeNoEvents": "Complet sans événements",
  "instructionsOnly": "Instructions uniquement",
  "standard": "Standard",
  "summaryOnly": "Résumé uniquement",
  "travelModesUrl": "URL des modes de déplacement",
  "searchPlaceholder": "Rechercher une adresse ou un lieu",
  "trafficLayerUrl": "URL de la couche de trafic",
  "presetDestinations": "Arrêts prédéfinis",
  "startPoint": "Point de départ",
  "endPoint": "Point d'arrivée",
  "destinationHolder": "Adresse ou coordonnées",
  "optional": "Facultatif."
});