define({
  "_widgetLabel": "좌표 변환",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM(H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "십진수(DD) - 위도/경도",
  "DDLongLatNotation": "십진수(DD) - 경도/위도",
  "DDMLatLongNotation": "도-소수-분 - 위도/경도",
  "DDMLongLatNotation": "도-소수-분 - 경도/위도",
  "DMSLatLongNotation": "도-분-초 - 위도/경도",
  "DMSLongLatNotation": "도-분-초 - 경도/위도",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 밴드 문자",
  "UTMHemNotation": "UTM - 반구(N/S)",
  "formatInput": "입력 형식 지정",
  "copyAll": "모두 복사",
  "copySuccessful": "복사 완료",
  "copyFailed": "복사할 수 없습니다. 대신 Ctrl+C를 사용하세요.",
  "parseCoordinatesError": "좌표를 구문 분석할 수 없습니다. 입력을 확인하세요.",
  "comfirmInputNotation": "입력 표기 확인",
  "latLongWarningMessage": "입력 좌표에 위도 또는 경도 값의 접두사와 접미사가 모두 있는 것으로 감지되었습니다. 반환되는 좌표는 접두사를 기반으로 합니다.",
  "inputLabel": "입력",
  "outputLabel": "결과",
  "cancelButtonLabel": "취소",
  "applyButtonLabel": "적용",
  "posNegPrefixLabel": "양수와 음수에 \"+/-\" 접두사 추가",
  "editCoordinateDialogTitle": "좌표 형식 문자열 설정",
  "rememberDecisionLabel": "결정 사항을 저장하고 다시 묻지 않음<br/>",
  "coordinateInputLabel": "좌표를 입력하거나 맵 클릭",
  "zoomLabel": "확대",
  "multipleNotationLabel": "입력과 일치하는 표기를 찾았습니다. 사용할 항목을 확인하세요.",
  "copyToClipboard": "클립보드에 복사",
  "formatOutput": "결과 형식 지정",
  "addNewNotation": "새 표기 추가",
  "notationAddedMessage": "추가된 새 표기",
  "addLabel": "추가",
  "removeCoordinate": "좌표 제거",
  "expandOutput": "결과 확장",
  "latitudeLabel": "위도",
  "longitudeLabel": "경도",
  "quadrantLabel": "사분면",
  "keyLabel": "키",
  "fifteenDegreeLabel": "15Â° 쿼드",
  "oneDegreeLabel": "1Â° 쿼드",
  "eastingLabel": "동부",
  "northingLabel": "북부",
  "zoneLabel": "구역",
  "bandLabel": "밴드",
  "gzdLabel": "GZD",
  "gridSquareLabel": "격자 사각형",
  "hemisphereLabel": "반구"
});