define({
  "tabs_section_Label": "टैब",
  "addTab": "टैब जोड़ें",
  "layerName": "लेयर",
  "layerType": "विश्लेषण का प्रकार",
  "layerLabel": "लेबल",
  "actions": "कार्रवाइयाँ",
  "closest": "निकटतम फीचर",
  "proximity": "निकटता",
  "summary": "सारांश",
  "select_lbl": "-- चयन करें --",
  "general_setting_Label": "सामान्य सेटिंग",
  "units_text_lbl": "दूरी की इकाइयां",
  "maximum_distance_lbl": "निकटतम फीचर अधिकतम दूरी",
  "buffer_text_lbl": "बफर लेबल",
  "buffer_lbl": "बफर दूरी",
  "buffer_max_lbl": "अधिकतम बफर दूरी",
  "buffer_min_lbl": "न्यूनतम बफर दूरी",
  "buffer_default_lbl": "डिफ़ॉल्ट बफर दूरी",
  "not_less_than_max": "दूरी अधिकतम बफ़र दूरी से कम होनी चाहिए",
  "not_between": "दूरी न्यूनतम और अधिकतम बफ़र दूरी के बीच होनी चाहिए",
  "not_more_than_min": "दूरी न्यूनतम बफ़र दूरी से अधिक होनी चाहिए",
  "not_valid_number": "संख्या वैध होनी चाहिए",
  "invalid_value": "${type} मान अमान्य है",
  "routing_checkBox": "रूटिंग को सक्षम करें",
  "weather_Label": "मौसम संबंधी सेटिंग",
  "weather_checkBox": "मौसम सक्षम करें",
  "weather_map_layers": "मौसम लेयरों का चयन करें…",
  "selected_map_layers": " मौसम लेयरों का चयन किया गया",
  "instruction_weather": "पैनल में मौसम संबंधी जानकारी प्रदर्शित करें।",
  "instruction_weather_layers": "अतिरिक्त मौसम लेयरों को प्रदर्शित करें।",
  "instruction_weather_metric": "मानक/मीट्रिक मान प्रदर्शित करें।",
  "selectLayers": "मौसम लेयरों का चयन करें",
  "weather_removed_message": "इस विजेट के लिए अब मौसम के विकल्प उपलब्ध नहीं हैं।",
  "currentlySelectedLayer": "मैप लेयरों से चयन करें",
  "missingTabLabel": "कम से कम एक टैब का लेबल उपलब्ध नहीं है",
  "missingLayerInWebMap": "कोई भी परिचालन लेयर नहीं मिली।",
  "selectFields": "फील्ड्स का चयन करें",
  "addField": "क्षेत्र जोडें",
  "sum": "योग",
  "min": "न्यूनतम",
  "max": "अधिकतम",
  "avg": "औसत",
  "count": "गणना",
  "area": "क्षेत्रफल",
  "length": "लंबाई",
  "count_checkBox": "फीचर संख्या प्रदर्शित करें",
  "area_checkBox": "क्षेत्रफल के योग का प्रदर्शन करता है",
  "length_checkBox": "लंबाई के योग का प्रदर्शन करता है",
  "max_records": "अधिकतम सीमा पूरी हो गई है",
  "save_label": "विकल्प सहेजें",
  "save_checkbox": "सहेजें को सक्षम करें",
  "report_label": "रिपोर्ट विकल्प",
  "report_checkbox": "रिपोर्ट सक्षम करें",
  "csv_label": "CSV विकल्प",
  "csv_checkbox": "सभी फ़ील्ड निर्यात करें",
  "display_label": "विकल्प को प्रदर्शित करता है",
  "display_checkbox": "सारांश फीचर को प्रदर्शित करता है",
  "snapshot_label": "स्नैपशॉट विकल्प",
  "snapshot_checkbox": "स्नैपशॉट को सक्षम करें",
  "must_select_template": "सहेजें विकल्प में टेम्पलेट्स संपादन में से एक का चयन करें।",
  "count_label": "गणना लेबल",
  "area_label": "क्षेत्रफल लेबल",
  "length_label": "लंबाई लेबल",
  "invalid_string_width": "मान बहुत लंबा है। ",
  "layer_type_not_supported": "लेयर प्रकार समर्थित नहीं है",
  "groupedSummary": "समूहित गणना",
  "groupByField": "फील्ड द्वारा समूह",
  "labelType": "लेबल सलंग्न करें",
  "prefix": "उपसर्ग के रूप में",
  "suffix": "प्रत्यय के रूप में",
  "need_group_field": "फील्ड द्वारा समूह को परिभाषित करने के लिए संपादित कार्रवाई का उपयोग करें।",
  "fieldTitle": "फ़ील्ड",
  "typeTitle": "प्रकार",
  "actionsTitle": "कार्रवाइयाँ",
  "save_point_checkbox": "बिंदु सहेजें",
  "save_line_checkbox": "रेखाओं को सहेजें",
  "save_poly_checkbox": "बहुभुज को सहेजें",
  "no_valid_popup_fields": "पॉपअप में कोई मान्य फ़ील्ड नहीं है। एक फ़ील्ड को परिभाषित करने के लिए संपादित कार्रवाई का उपयोग करें।",
  "no_valid_fields": "कोई मान्य फ़ील्ड नहीं हैं। प्रदर्शन विकल्पों को परिभाषित करने के लिए संपादित कार्रवाई का उपयोग करें।",
  "incident_label": "टैब लेबल",
  "locate_incident_label": "पसंदीदा लेबल",
  "incident": "घटना",
  "locate_incident": "घटना का पता लगाएं",
  "buffer_value": "बफर दूरी",
  "tab_options": "विश्लेषण",
  "export_options": "आउटपुट",
  "instruction_save": "स्थान को सुविधा सेवा में सहेजें।",
  "instruction_snapshot": "स्थान आधारित वेबमैप बनाएँ।",
  "instruction_report": "स्थान की प्रिंट की गई रिपोर्ट बनाएँ।",
  "instruction_all_fields": "CSV डाउनलोड वाली सभी फ़ील्ड निर्यात करें।",
  "data_label": "डेटा आउटपुट सेटिंग्स",
  "layer_error": "लेयर अनुपलब्ध है या अमान्य है।",
  "visibility_checkBox": "लेयर दृश्यता प्रबंधन को अक्षम करें",
  "downloadTab": {
    "reportLegend": "रिपोर्ट सेटिंग्स",
    "textColorLabel": "स्तंभ शीर्षकों के लिए रंग का चयन करें",
    "setButtonLabel": "सेट करें",
    "printGPServiceLabel": "प्रिंट सर्विस URL",
    "logoLabel": "लोगो",
    "logoChooserHint": "चित्र बदलने के लिए इमेज आइकन पर क्लिक करें",
    "footnoteLabel": "फ़ुटनोट"
  }
});