define({
  "chartSettingLabel": "Configurações do gráfico",
  "addNewLabel": "Adicionar novo",
  "generalSettingLabel": "Configurações gerais",
  "searchSourceSettingLabel": "Configurações da Fonte de Pesquisa",
  "layerChooser": {
    "title": "Selecionar camada para criar gráfico",
    "selectPolygonLayerLabel": "Selecionar camada",
    "selectPolygonLayerHintText": "Sugestão: Se configurar múltiplos gráficos, então as camadas terão que ser do mesmo tipo de geometria",
    "selectRelatedTableLayerLabel": "Selecionar tabela relacionada à camada",
    "selectRelatedTableLayerHintText": "Sugestão: Somente tabelas com campos numéricos são exibidas",
    "errorInSelectingPolygonLayer": "Selecione uma camada que tenha uma camada de ponto relacionada.",
    "errorInSelectingRelatedLayer": "Selecione uma tabela/camada relacionada válida para camada.",
    "polygonLayerNotHavingRelationships": "A camada selecionada não tem nenhuma tabela/camada relacionada."
  },
  "ChartSetting": {
    "sectionTitle": "Título da seção",
    "sectionTitleHintText": "Sugestão: Exibido no título de cabeçalho da seção",
    "chartTitle": "Título do gráfico",
    "chartTitleHintText": "Sugestão: Exibido no centro superior do gráfico",
    "chartDescription": "Descrição",
    "chartDescriptionHintText": "Sugestão: Exibido abaixo do gráfico",
    "chartType": "Tipo de gráfico",
    "barChart": "Gráfico de barra",
    "pieChart": "Gráfico de pizza",
    "polarChart": "Gráfico polar",
    "dataSeriesField": "Campo da série de dados",
    "labelField": "Campo de rótulo",
    "chartColor": "Cor do gráfico",
    "singleColor": "Cor única",
    "colorByTheme": "Cor por tema",
    "colorByFieldValue": "Cor por valor de campo",
    "xAxisTitle": "Título do eixo X",
    "xAxisHintText": "Sugestão: Título do eixo X",
    "yAxisTitle": "Título do eixo Y",
    "yAxisHintText": "Sugestão: Título do eixo Y",
    "fieldColorLabel": "Rótulo",
    "fieldColorColor": "Cor",
    "defaultFieldSelectLabel": "Selecionar",
    "errMsgFieldValuesNotFound": "Não foi possível localizar valores para o campo selecionado",
    "errMsgSectionTitle": "Insira o título da seção",
    "errMsgFieldByValue": "Selecione o valor de campo",
    "settingTabTitle": "Configurações",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Sugestão: Selecione campos para gerar gráfico polar",
    "visibilityText": "Visibilidade",
    "fieldNameText": "Nome do Campo",
    "aliasNameText": "Nome Alternativo",
    "errMsgPolarFieldsRequired": "Selecione três ou mais campos para gerar gráfico polar",
    "polarChartPolygonFillLabel": "Preencher polígono",
    "polarChartPolygonFillHintText": "Sugestão: Marque a caixa de seleção para mostrar o preenchimento de polígono no gráfico polar",
    "viewLayoutLabel": "Layout",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Deserto",
      "themeDistinctive": "Distintivo",
      "themeDollar": "Dólar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmonia",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Pântano",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Configurações Gerais",
    "locationSymbolLabel": "Símbolo de local do gráfico",
    "locationSymbolHintText": "Sugestão: Utilizado para exibir símbolo de endereço e clicar no local",
    "refreshIntervalLabel": "Intervalo de atualização",
    "refreshIntervalHintText": "Sugestão: Utilizado para atualizar gráficos baseado neste intervalo. Especifique um valor entre 1 a 1440 minutos",
    "errMsgRefreshInterval": "Especifique o intervalo de atualização entre 0 a 1440 minutos",
    "symbolPickerPreviewText": "Visualizar:",
    "showToolToSelectLabel": "Configurar botão de localização",
    "showToolToSelectHintText": "Sugestão: Forneça um botão para configurar a localização no mapa em vez de sempre configurar a localização quando o mapa for clicado"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Configurações da Fonte de Pesquisa",
    "searchSourceSettingTitle": "Configurações da Fonte de Pesquisa",
    "searchSourceSettingTitleHintText": "Adicione e configure serviços de geocódigo ou camadas de feição como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
    "addSearchSourceLabel": "Adicionar Fonte de Pesquisa",
    "featureLayerLabel": "Camada de Feição",
    "geocoderLabel": "Geocodificador",
    "nameTitle": "Nome",
    "generalSettingLabel": "Configurações Gerais",
    "allPlaceholderLabel": "Texto de local reservado para pesquisar todos:",
    "allPlaceholderHintText": "Sugestão: Insira o texto a ser mostrado como reservado ao pesquisar todas as camadas e geocodificador",
    "generalSettingCheckboxLabel": "Mostrar pop-up do local ou feição localizada",
    "countryCode": "Códigos de Região e País",
    "countryCodeEg": "por exemplo ",
    "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Somente pesquisar na extensão de mapa atual",
    "zoomScale": "Escala de Zoom",
    "locatorUrl": "URL do Geocodificador",
    "locatorName": "Nome do Geocodificador",
    "locatorExample": "Exemplo",
    "locatorWarning": "Esta versão do serviço de geocodificação não é suportado. O widget suporta serviço de geocodificação 10.0 e superior.",
    "locatorTips": "As sugestões não estão disponíveis, pois o serviço de geocodificação não suporta o recursos de sugestão.",
    "layerSource": "Origem da Camada",
    "setLayerSource": "Configurar Origem da Camada",
    "setGeocoderURL": "Configurar URL do Geocodificador",
    "searchLayerTips": "As sugestões não estão disponíveis, pois o serviço da feição não suporta o recursos de paginação.",
    "placeholder": "Texto do Placeholder",
    "searchFields": "Pesquisar Campos",
    "displayField": "Exibir Campo",
    "exactMatch": "Combinação Exata",
    "maxSuggestions": "Máximo de Sugestões",
    "maxResults": "Máximo de Resultados",
    "enableLocalSearch": "Habilitar pesquisa de local",
    "minScale": "Escala Mín",
    "minScaleHint": "Quando a escala do mapa for maior que esta escala, a pesquisa de local será aplicada",
    "radius": "Raio",
    "radiusHint": "Especifica o raio de uma área ao redor do centro do mapa atual que é utilizado para impulsionar o grau de candidatos de geocodificação de forma que os candidatos mais próximos ao local sejam retornados primeiro",
    "meters": "Metros",
    "setSearchFields": "Configurar Campos de Pesquisa",
    "set": "Configurar",
    "fieldName": "Nome",
    "invalidUrlTip": "A URL ${URL} é inválida ou inacessível."
  }
});