define({
  "_widgetLabel": "格网化参考图形",
  "newGRGFromAreaButtonLabel": "通过面积定义格网",
  "newGRGFromPointButtonLabel": "通过点定义格网",
  "newGRGFromAreaTitle": "通过面积定义格网",
  "newGRGFromPointTitle": "通过点定义格网",
  "newGRGBySizeButtonLabel": "按尺寸",
  "newGRGFromRefSystemButtonLabel": "按参考系统",
  "newGRGByTimeLabel": "按时间和速度",
  "newGRGFromNonStandardButtonLabel": "定义非标准格网",
  "newGRGAreaBySizeTitle": "通过区域并按尺寸定义 GRG",
  "newGRGAreaBySizeDefineAreaLabel": "GRG 区域",
  "addGRGAreaPolygonToolTip": "使用多边形绘制 GRG 区域",
  "addGRGAreaExtentToolTip": "使用范围绘制 GRG 区域",
  "rotation": "格网旋转",
  "numberRowsColumnsLabel": "定义行数和列数",
  "newGRGAreaByRefSystemTitle": "通过区域并按参考系统定义 GRG",
  "gridSize": "格网大小",
  "UTMZoneandBand": "格网区域",
  "100000m": "100000 米",
  "10000m": "10000 米",
  "1000m": "1000 米",
  "100m": "100 米",
  "10m": "10 米",
  "clipGrid": "将格网裁剪至 GRG 区域",
  "newGRGAreaFromNonStandardTitle": "新建 NRG",
  "newGRGPointBySizeTitle": "通过点并按尺寸新建 GRG",
  "newGRGPointByRefSystemTitle": "通过点并按参考系统新建 GRG",
  "newGRGPointByTimeTitle": "通过点并使用时间和速度新建 GRG",
  "time": "时间",
  "rate": "速度",
  "hours": "小时",
  "minutes": "分",
  "seconds": "秒",
  "ftPerSec": "英尺/秒",
  "ftPerHour": "英尺/小时",
  "kmPerSec": "千米/秒",
  "kmPerHour": "千米/小时",
  "mPerSec": "米/秒",
  "mPerHour": "米/小时",
  "miPerSec": "英里/秒",
  "miPerHour": "英里/小时",
  "nMPerSec": "海里/秒",
  "nMPerHour": "海里/小时",
  "settingsTitle": "设置",
  "labelSettingsLabel": "标注设置",
  "labelSettingsButtonLabel": "配置标注设置",
  "gridSettingsLabel": "格网设置",
  "gridSettingsButtonLabel": "配置格网设置",
  "transparency": "透明度",
  "labelStyle": "标注样式",
  "font": "字体",
  "textSize": "文本大小",
  "textColor": "文本颜色",
  "halo": "晕圈",
  "show": "显示",
  "lockSettings": "设置已被应用程序所有者锁定",
  "gridSettings": {
    "cellShape": "像元形状",
    "cellUnits": "像元单位",
    "cellOutline": "像元轮廓设置",
    "cellFill": "像元填充设置",
    "gridReferenceSystem": "参考系统",
    "gridDatum": "基准：WGS84",
    "labelStartPosition": "标注源",
    "labelType": "标注类型",
    "labelDirection": "标注方向",
    "gridOrigin": "格网原点",
    "default": "矩形",
    "hexagon": "六边形",
    "miles": "英里",
    "kilometers": "千米",
    "feet": "英尺",
    "meters": "米",
    "yards": "码",
    "nautical-miles": "海里",
    "lowerLeft": "左下",
    "lowerRight": "右下",
    "upperLeft": "左上",
    "upperRight": "右上",
    "center": "中心",
    "alphaNumeric": "字母-数字",
    "alphaAlpha": "字母-字母",
    "numeric": "数值",
    "horizontal": "水平",
    "vertical": "竖直",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "显示标注"
  },
  "publishTitle": "将 GRG 发布到门户",
  "publishGRGBtn": "发布",
  "GRGLayerName": "发布的 GRG 图层名称",
  "invalidGRGLayerName": "图层名称只能包含字母数字字符和下划线",
  "missingGRGLayerName": "您必须输入 GRG 的名称",
  "publishingFailedLayerExists": "发布失败：您已拥有名为 {0} 的要素服务。请选择其他名称。",
  "checkService": "检查服务：{0}",
  "createService": "创建服务：{0}",
  "unableToCreate": "无法创建：{0}",
  "addToDefinition": "添加到定义：{0}",
  "successfullyPublished": "已成功发布 web 图层{0}管理 web 图层",
  "userRole": "用户没有权限，因此无法创建服务",
  "createGRGBtn": "创建 GRG",
  "clearGRGBtn": "清除",
  "labelFormat": "标注格式",
  "helpIconTooltip": "Z：格网区域指示符(GZD)\nS：100,000 米网格识别(GSID)\nX：Easting (X 坐标)\nY：Northing (Y 坐标)\n\n示例：\nZSXY 为 15SWC8081751205\nZS X,Y 为 15SWC 80817,51205",
  "addPointToolTip": "添加 GRG 原点",
  "cellWidth": "像元宽度(x)",
  "cellHeight": "像元高度(y)",
  "invalidNumberMessage": "输入的值无效",
  "invalidRangeMessage": "值必须大于 0",
  "gridAngleInvalidRangeMessage": "值必须位于 -89.9 和 89.9 之间",
  "formatIconTooltip": "格式输入",
  "coordInputLabel": "GRG 原点(DD)",
  "setCoordFormat": "设置坐标格式字符串",
  "prefixNumbers": "向正数和负数添加“+/-”前缀",
  "cancelBtn": "取消",
  "applyBtn": "应用",
  "comfirmInputNotation": "确认输入注记",
  "notationsMatch": "发现与您的输入匹配的注记。请确认您想使用的注记：",
  "numberOfCellsHorizontal": "＃ 水平像元",
  "numberOfCellsVertical": "＃ 垂直像元",
  "gridAngle": "格网旋转",
  "tooManyCellsErrorMessage": "您正在尝试创建一个包含 2000 多个像元的格网。建议通过更改格网大小或格网面积来减少正在创建的像元数量。",
  "missingParametersMessage": "<p>GRG 创建表单缺少参数或包含无效参数，请确保：</p><ul><li>已绘制 GRG 区域。</li><li>像元宽度和高度为有效值。</li></ul>",
  "missingOriginParametersMessage": "<p>GRG 创建表单缺少参数或包含无效参数，请确保：</p><ul><li>已设置 GRG 原点。</li><li>时间、速度和角度输入为有效值。</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG 创建表单缺少参数或包含无效参数。请确保像元宽度和高度输入为有效值。</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG 创建表单缺少参数或包含无效参数。请确保像元的水平和垂直输入数量为有效值。</p>",
  "drawPointToolTip": "单击添加 GRG 原点",
  "missingLayerNameMessage": "发布之前，您必须输入有效的图层名称",
  "parseCoordinatesError": "无法解析坐标。请检查您的输入。",
  "grgPolarRegionError": "GRG 范围位于极点区域内。不会创建落入极点区域的像元。",
  "grgPolarOriginError": "按参考系统创建 GRG 时，GRG 原点不能位于极点区域内。",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十进制度 - 纬度/经度",
  "DDLongLatNotation": "十进制度 - 经度/纬度",
  "DDMLatLongNotation": "度十进制分 - 纬度/经度",
  "DDMLongLatNotation": "度十进制分 - 经度/纬度",
  "DMSLatLongNotation": "度分秒 - 纬度/经度",
  "DMSLongLatNotation": "度分秒 - 经度/纬度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 带字母",
  "UTMHemNotation": "UTM - 半球(N/S)"
});