define({
  "chartSettingLabel": "Diagramindstillinger",
  "addNewLabel": "Tilføj nyt",
  "generalSettingLabel": "Generelle indstillinger",
  "searchSourceSettingLabel": "Søgekildeindstillinger",
  "layerChooser": {
    "title": "Vælg lag, der skal oprettes diagram over",
    "selectPolygonLayerLabel": "Vælg lag",
    "selectPolygonLayerHintText": "Tip: Hvis du konfigurerer flere diagrammer, skal lagene være af samme geometritype",
    "selectRelatedTableLayerLabel": "Vælg den tabel, der er knyttet til laget",
    "selectRelatedTableLayerHintText": "Tip: Kun tabeller med numeriske felter vises",
    "errorInSelectingPolygonLayer": "Vælg et lag med et tilknyttet punktlag.",
    "errorInSelectingRelatedLayer": "Vælg en gyldig tilknyttet tabel/lag til laget.",
    "polygonLayerNotHavingRelationships": "Det valgte lag har ikke nogen tilknyttede tabeller/lag."
  },
  "ChartSetting": {
    "sectionTitle": "Sektionstitel",
    "sectionTitleHintText": "Tip: Vises i sektionsheader-titlen",
    "chartTitle": "Diagramtitel",
    "chartTitleHintText": "Tip: Vises centreret øverst i diagrammet",
    "chartDescription": "Beskrivelse",
    "chartDescriptionHintText": "Tip: Vises under diagrammet",
    "chartType": "Diagramtype",
    "barChart": "Søjlediagram",
    "pieChart": "Cirkeldiagram",
    "polarChart": "Polardiagram",
    "dataSeriesField": "Dataseriefelt",
    "labelField": "Etiketfelt",
    "chartColor": "Diagramfarve",
    "singleColor": "Enkelt farve",
    "colorByTheme": "Farve efter tema",
    "colorByFieldValue": "Farve efter feltværdi",
    "xAxisTitle": "X-aksetitel",
    "xAxisHintText": "Tip: X-aksetitel",
    "yAxisTitle": "Y-aksetitel",
    "yAxisHintText": "Tip: Y-aksetitel",
    "fieldColorLabel": "Mærke",
    "fieldColorColor": "Farve",
    "defaultFieldSelectLabel": "Vælg",
    "errMsgFieldValuesNotFound": "Kan ikke finde værdier for det valgte felt",
    "errMsgSectionTitle": "Angiv sektionstitlen",
    "errMsgFieldByValue": "Vælg feltværdi",
    "settingTabTitle": "Indstilling",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Tip: Vælg felter for at generere et polardiagram",
    "visibilityText": "Synlighed",
    "fieldNameText": "Feltnavn",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Vælg tre eller flere felter for at generere et polardiagram",
    "polarChartPolygonFillLabel": "Udfyld polygon",
    "polarChartPolygonFillHintText": "Tip: Markér afkrydsningsfeltet for at vise polygonfyld i polardiagrammet",
    "viewLayoutLabel": "Layout",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Alger",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Ørken",
      "themeDistinctive": "Karakteristisk",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Græshoppe",
      "themeGrasslands": "Græsmarker",
      "themeGreySkies": "GråSkyer",
      "themeHarmony": "Harmoni",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Vådområde",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Generelle indstillinger",
    "locationSymbolLabel": "Grafisk positionssymbol",
    "locationSymbolHintText": "Tip: Bruges til at vise symbol for adressen og position, der er klikket på",
    "refreshIntervalLabel": "Opdateringsinterval",
    "refreshIntervalHintText": "Tip: Bruges til at opdatere diagrammer baseret på dette interval. Angiv en værdi mellem 1 og 1440 minutter",
    "errMsgRefreshInterval": "Angiv opdateringsinterval mellem 0 og 1440 minutter",
    "symbolPickerPreviewText": "Forhåndsvisning:",
    "showToolToSelectLabel": "Knap til angivelse af placering",
    "showToolToSelectHintText": "Tip: Opretter en knap til angivelse af placering på kortet i stedet for altid at skulle angive placeringen, når der klikkes på kortet"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Søgekildeindstillinger",
    "searchSourceSettingTitle": "Søgekildeindstillinger",
    "searchSourceSettingTitleHintText": "Tilføj og konfigurér geokodningstjenester eller vektorlag som søgekilder. Disse specificerede kilder bestemmer, hvad der kan søges efter i søgeboksen.",
    "addSearchSourceLabel": "Tilføj søgekilde",
    "featureLayerLabel": "Vektorlag",
    "geocoderLabel": "Geokoder",
    "nameTitle": "Navn",
    "generalSettingLabel": "Generel indstilling",
    "allPlaceholderLabel": "Pladsholdertekst for søgning efter alle:",
    "allPlaceholderHintText": "Tip: Indtast den tekst, der skal vises som pladsholder, mens der søges i alle lag og geokoder",
    "generalSettingCheckboxLabel": "Vis pop-up for det fundne objekt eller den fundne position",
    "countryCode": "Lande- eller regionskode(r)",
    "countryCodeEg": "f.eks. ",
    "countryCodeHint": "Hvis denne værdi er tom, bliver der søgt efter alle lande og regioner",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Søg kun inden for den aktuelle kortudstrækning",
    "zoomScale": "Zoom-skala",
    "locatorUrl": "Geokodnings-URL",
    "locatorName": "Navn på geokodningsfunktion",
    "locatorExample": "Eksempel",
    "locatorWarning": "Denne version af geokodningstjenesten understøttes ikke. Widget'en understøtter Geokodningstjeneste version 10.0 og nyere.",
    "locatorTips": "Forslag er ikke tilgængelige, fordi geokodningstjenesten ikke understøtter forslagsfunktionen.",
    "layerSource": "Lagkilde",
    "setLayerSource": "Angiv lagkilde",
    "setGeocoderURL": "Angiv geokodnings-URL",
    "searchLayerTips": "Forslag er ikke tilgængelige, fordi featuretjenesten ikke understøtter forslagsfunktionen.",
    "placeholder": "Pladsholdertekst",
    "searchFields": "Søgefelter",
    "displayField": "Visningsfelt:",
    "exactMatch": "Nøjagtigt match",
    "maxSuggestions": "Maksimalt antal forslag",
    "maxResults": "Maksimalt antal resultater",
    "enableLocalSearch": "Aktivér lokal søgning",
    "minScale": "Min. målestok",
    "minScaleHint": "Når kortmålestokken er større end denne målstok, anvendes lokal søgning",
    "radius": "Radius",
    "radiusHint": "Angiver radius for et område omkring det aktuelle kortcentrum, der benyttes til at booste rangordningen af geokodningsforslag, så de forslag, der ligger tættest på placeringen, returneres først",
    "meters": "Meter",
    "setSearchFields": "Indstil søgefelter",
    "set": "Indstil",
    "fieldName": "Navn",
    "invalidUrlTip": "URL’en ${URL} er ugyldig eller utilgængelig."
  }
});