define({
  "_widgetLabel": "Etäisyys ja suunta",
  "tabLineTitle": "Viiva",
  "tabCircleTitle": "Ympyrä",
  "tabEllipseTitle": "Ellipsi",
  "tabRingsTitle": "Renkaat",
  "multipleNotationsMessage": " lähtöaineistoasi vastaavia esitystapoja. Vahvista käytettävä esitystapa:",
  "invalidCoordinateMessage": "Virheellinen koordinaatti",
  "confirmInputNotationMessage": "Vahvista lähtöaineiston esitysmuoto",
  "prefixSuffixMessage": "Lähtöaineiston koordinaatissa on havaittu olevan pituusasteen tai leveysasteen sekä etu- että jälkiliite. Palautettu koordinaatti perustuu etuliitteeseen.",
  "rememberDecisionMessage": "Muista valintani äläkä kysy tietoja uudelleen.<br/>",
  "majorAxisTooltipMessage": "Napsauta pääakselin pituutta",
  "minorAxisTooltipMessage": "Määritä pikkuakseli ja lopeta ellipsin piirto siirtämällä hiiri takaisin aloituskohtaan",
  "clickToFinishLineMessage": "Lopeta viivan piirto napsauttamalla",
  "doubleClickEllipseMesage": "Lopeta aluerenkaiden piirto kaksoisnapsauttamalla",
  "invalidCoordinateTypeMessage": "Lähtöaineiston koordinaattien tyyppiä ei voi määrittää. Tarkista lähtöaineistosi.",
  "noCenterPointSetMessage": "Keskipistettä ei ole määritetty. Tarkista lähtöaineistosi.",
  "ellipseMajorAxis": "Pääakseli",
  "ellipseMinorAxis": "Pikkuakseli",
  "degreesRangeMessage": "Arvon on oltava välillä 0 ja 360.",
  "millsRangeMessage": "Arvon on oltava välillä 0 ja 6400.",
  "lengthLabel": "Pituus",
  "angleLabel": "Kulma",
  "startPointLabel": "Aloituspiste",
  "endPointLabel": "Loppupiste",
  "centerPointLabel": "Keskipiste",
  "distanceTableErrorMessage": "Etäisyystaulukko on tyhjä. Varmista, että syötät joitakin etäisyyksiä.",
  "setCoordFormatStringMessage": "Määritä koordinaatin muotomerkkijono",
  "prefixMessage": "Lisää etuliite +/- positiivisiin ja negatiivisiin numeroihin",
  "ddLabel": "da",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Desimaaliasteet – leveys-/pituusaste",
  "DDLongLatNotation": "Desimaaliasteet – pituus-/leveysaste",
  "DDMLatLongNotation": "Asteet, desimaaliminuutit – leveys-/pituusaste",
  "DDMLongLatNotation": "Asteet, desimaaliminuutit – pituus-/leveysaste",
  "DMSLatLongNotation": "Asteet, minuutit, sekunnit – leveys-/pituusaste",
  "DMSLongLatNotation": "Asteet, minuutit, sekunnit – pituus-/leveysaste",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – kaistan kirjain",
  "UTMHemNotation": "UTM – pallonpuolisko (P/E)",
  "circleTitle": "Luo ympyrä kohteesta",
  "radiusLabel": "Säde",
  "diameterLabel": "Läpimitta",
  "startPointPlaceHolderLabel": "Kirjoita koordinaatit",
  "formatInputLabel": "Muodon lähtöaineisto",
  "drawCircleLabel": "Piirrä ympyrä",
  "drawLineLabel": "Piirrä viiva",
  "createCircleInteractivelyLabel": "Luo ympyrä vuorovaikutteisesti",
  "rangeErrorMessage": "Virheellinen säde tai halkaisija",
  "numericInvalidMessage": "Anna numeroarvo",
  "timeLabel": "kellonaika",
  "invalidTimeMessage": "Virheellinen aika-arvo",
  "hoursLabel": "Tuntia",
  "minutesLabel": "Minuuttia",
  "secondsLabel": "Sekuntia",
  "rateLabel": "Nopeus",
  "invalidDistanceMessage": "Virheellinen etäisyysarvo",
  "feetSecondsLabel": "Jalkaa/sekunti",
  "feetHourLabel": "Jalkaa/tunti",
  "kmSecondLabel": "Kilometriä/sekunti",
  "kmHourLabel": "Kilometriä/tunti",
  "metersSecondLabel": "Metriä/sekunti",
  "metersHourLabel": "Metriä/tunti",
  "milesSecondLabel": "Mailia/sekunti",
  "milesHourLabel": "Mailia/tunti",
  "nauticalMilesSecondLabel": "Merimailia/sekunti",
  "nauticalMilesHourLabel": "Merimailia/tunti",
  "clearGraphicsLabel": "Tyhjennä grafiikka",
  "ellipseTypeLabel": "Ellipsin tyyppi",
  "ellipseSemiLabel": "Puoli-",
  "ellipseFullLabel": "Täydellinen",
  "drawEllipseLabel": "Piirrä ellipsi",
  "createEllipseInteractively": "Luo ellipsi vuorovaikutteisesti",
  "axisLabel": "Akseli",
  "majorRadiusLabel": "Pää(säde)",
  "axisErrorMessage": "Arvon on oltava suurempi kuin 0",
  "minorRadiusLabel": "Ali(säde)",
  "orientationLabel": "Suunta",
  "orientationErrorMessage": "Arvon on oltava välillä 0 ja 360.",
  "warningMessage": "Varoitus: ellipsityökalulla luodut grafiikat eivät ole geodeettisiä",
  "fromLabel": "Alkaen",
  "distanceBearingLabel": "Etäisyys ja suuntima",
  "pointsLabel": "Pisteet",
  "createLineInteractively": "Luo viiva vuorovaikutteisesti",
  "lineLengthErrorMessage": "Virheellinen viivan pituus",
  "degreesLabel": "Asteet",
  "milsLabel": "Millimetriä",
  "lineTypeLabel": "Tyyppi",
  "interactiveLabel": "Vuorovaikutteinen",
  "fixedLabel": "Kiinteä",
  "originLabel": "Alkupiste",
  "cumulativeLabel": "Kumulatiivinen",
  "numberOfRingsLabel": "Renkaiden määrä",
  "ringsErrorMessage": "Virheellinen renkaiden määrä",
  "distanceBetweenRingsLabel": "Renkaiden välinen etäisyys",
  "ringsDecimalErrorMessage": "Anna numeroarvo kahdelle desimaalille",
  "distanceUnitsLabel": "Etäisyyden yksiköt",
  "distancesLabel": "Etäisyydet",
  "numberOfRadialsLabel": "Säteiden määrä",
  "upLabel": "Ylös",
  "downLabel": "Alas",
  "deleteLabel": "Poista",
  "radialsErrorMessage": "Virheellinen säteiden määrä. Suurin sallittu määrä on 360",
  "addPointLabel": "Lisää piste",
  "valueLabel": "Arvo",
  "valueText": "Syötä arvo",
  "actionLabel": "Toiminto"
});