define({
  "_widgetLabel": "Koordinatkonvertering",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader – Latitud/longitud",
  "DDLongLatNotation": "Decimalgrader – Longitud/latitud",
  "DDMLatLongNotation": "Grader decimalminuter – Latitud/longitud",
  "DDMLongLatNotation": "Grader decimalminuter – Longitud/latitud",
  "DMSLatLongNotation": "Grader minuter sekunder – Latitud/longitud",
  "DMSLongLatNotation": "Grader minuter sekunder – Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbokstav",
  "UTMHemNotation": "UTM – Halvklot (N/S)",
  "formatInput": "Formatinmatning",
  "copyAll": "Kopiera alla",
  "copySuccessful": "Kopieringen lyckades",
  "copyFailed": "Kopieringen misslyckades. Använd Ctrl+C som ett alternativ.",
  "parseCoordinatesError": "Det gick inte att tolka koordinaterna. Kontrollera din inmatning.",
  "comfirmInputNotation": "Bekräfta inmatningsnotation",
  "latLongWarningMessage": "Inmatningskoordinaten har både ett prefix och ett suffix för latitud- och longitudvärdet. Den returnerade koordinaten bygger på prefixet.",
  "inputLabel": "Indata",
  "outputLabel": "Utdata",
  "cancelButtonLabel": "Avbryt",
  "applyButtonLabel": "Verkställ",
  "posNegPrefixLabel": "Lägg till prefixet \"+/-\" för positiva och negativa tal",
  "editCoordinateDialogTitle": "Ange koordinatsträng",
  "rememberDecisionLabel": "Kom ihåg mitt beslut och fråga inte igen.<br/>",
  "coordinateInputLabel": "Ange koordinater eller klicka på kartan",
  "zoomLabel": "Zooma",
  "multipleNotationLabel": "notationer hittades som matchar inmatningen. Bekräfta att du vill använda:",
  "copyToClipboard": "Kopiera till urklipp",
  "formatOutput": "Formatera utdata",
  "addNewNotation": "Lägg till ny notation",
  "notationAddedMessage": "Ny notation har lagts till",
  "addLabel": "Lägg till",
  "removeCoordinate": "Ta bort koordinat",
  "expandOutput": "Expandera utdata",
  "latitudeLabel": "Lat",
  "longitudeLabel": "Lon",
  "quadrantLabel": "Kvadrant",
  "keyLabel": "Nyckel",
  "fifteenDegreeLabel": "15Â° kvad",
  "oneDegreeLabel": "1Â° kvad",
  "eastingLabel": "Östlig",
  "northingLabel": "Nordlig",
  "zoneLabel": "Zon",
  "bandLabel": "Band",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Rutnätskvadrat",
  "hemisphereLabel": "Hemisfär"
});