define({
  "_widgetLabel": "Rastojanje i smer",
  "tabLineTitle": "Linija",
  "tabCircleTitle": "Krug",
  "tabEllipseTitle": "Elipsa",
  "tabRingsTitle": "Prstenovi",
  "multipleNotationsMessage": " oznake koje se podudaraju sa unosom. Potvrdite koje biste želeli da koristite:",
  "invalidCoordinateMessage": "Nevažeća koordinata",
  "confirmInputNotationMessage": "Proverite unesenu oznaku",
  "prefixSuffixMessage": "Detektovao je da unesena koordinata ima i prefiks i sufiks za vrednosti geografske širine i dužine, povratna koordinata se zasniva samo na prefiksu.",
  "rememberDecisionMessage": "Zapamti moj izbor i ne pitaj me ponovo.<br/>",
  "majorAxisTooltipMessage": "Kliknite na dužinu velike ose",
  "minorAxisTooltipMessage": "Vratite miša na početni položaj da podesite malu osu i završite crtanje elipse",
  "clickToFinishLineMessage": "Kliknite da završite crtanje linije",
  "doubleClickEllipseMesage": "Dvaput kliknite da završite crtanje prstenova opsega",
  "invalidCoordinateTypeMessage": "Utvrđivanje tipa unesene koordinate nije moguće. Proverite unos",
  "noCenterPointSetMessage": "Nema podešene središnje tačke. Proverite unos",
  "ellipseMajorAxis": "Velika osa",
  "ellipseMinorAxis": "Mala osa",
  "degreesRangeMessage": "Vrednost mora da bude između 0 i 360",
  "millsRangeMessage": "Vrednost mora da bude između 0 i 6400",
  "lengthLabel": "Dužina",
  "angleLabel": "Ugao",
  "startPointLabel": "Početna tačka",
  "endPointLabel": "Krajnja tačka",
  "centerPointLabel": "Središnja tačka",
  "distanceTableErrorMessage": "Tabela rastojanja je prazna. Vodite računa da unesete neka rastojanja.",
  "setCoordFormatStringMessage": "Postavi nisku formata koordinata",
  "prefixMessage": "Dodajte prefiks '+/-' pozitivnim i negativnim brojevima",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "Univerzalni Transverzalni Merkatorov koordinatni sistem (UTM)",
  "utmhLabel": "Univerzalni Transverzalni Merkatorov koordinatni sistem (H)",
  "DDLatLongNotation": "Decimalni stepeni – geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stepeni – geografska dužina/širina",
  "DDMLatLongNotation": "Decimalni stepeni minuti – geografska širina/dužina",
  "DDMLongLatNotation": "Decimalni stepeni minuti – geografska dužina/širina",
  "DMSLatLongNotation": "Decimalni stepeni sekundi – geografska širina/dužina",
  "DMSLongLatNotation": "Decimalni stepeni sekundi – geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – slovo opsega",
  "UTMHemNotation": "UTM – hemisfera (S/J)",
  "circleTitle": "Kreiraj krug iz",
  "radiusLabel": "Poluprečnik",
  "diameterLabel": "Prečnik",
  "startPointPlaceHolderLabel": "Unesite koordinate",
  "formatInputLabel": "Unos formata",
  "drawCircleLabel": "Nacrtaj krug",
  "drawLineLabel": "Nacrtaj liniju",
  "createCircleInteractivelyLabel": "Kreiraj krug interaktivno",
  "rangeErrorMessage": "Nevažeći poluprečnik ili prečnik",
  "numericInvalidMessage": "Unesite brojčanu vrednost",
  "timeLabel": "Vreme",
  "invalidTimeMessage": "Nevažeća vrednost vremena",
  "hoursLabel": "Sati",
  "minutesLabel": "Minuti",
  "secondsLabel": "Sekunde",
  "rateLabel": "Stopa",
  "invalidDistanceMessage": "Nevažeća vrednost udaljenosti",
  "feetSecondsLabel": "Stopa/sekundi",
  "feetHourLabel": "Stopa/sat",
  "kmSecondLabel": "Kilometara/sekundi",
  "kmHourLabel": "Kilometara/sat",
  "metersSecondLabel": "Metara/sekundi",
  "metersHourLabel": "Metara/sat",
  "milesSecondLabel": "Milja/sekundi",
  "milesHourLabel": "Milja/sat",
  "nauticalMilesSecondLabel": "Nautičkih milja/sekundi",
  "nauticalMilesHourLabel": "Nautičkih milja/sat",
  "clearGraphicsLabel": "Obriši grafiku",
  "ellipseTypeLabel": "Vrsta elipse",
  "ellipseSemiLabel": "Polu",
  "ellipseFullLabel": "Cela",
  "drawEllipseLabel": "Nacrtaj elipsu",
  "createEllipseInteractively": "Kreiraj elipsu interaktivno",
  "axisLabel": "Osa",
  "majorRadiusLabel": "Velika (poluprečnik)",
  "axisErrorMessage": "Vrednost mora da bude veća od 0",
  "minorRadiusLabel": "Mala (poluprečnik)",
  "orientationLabel": "Orijentacija",
  "orientationErrorMessage": "Vrednost mora da bude između 0 i 360",
  "warningMessage": "Upozorenje: Grafika generisana pomoću alatke za elipsu nije geodetska",
  "fromLabel": "Od",
  "distanceBearingLabel": "Rastojanje i direkcioni ugao",
  "pointsLabel": "Tačke",
  "createLineInteractively": "Kreiraj liniju interaktivno",
  "lineLengthErrorMessage": "Nevažeća dužina linije",
  "degreesLabel": "Stepeni",
  "milsLabel": "Miliradijani",
  "lineTypeLabel": "Tip",
  "interactiveLabel": "Interaktivno",
  "fixedLabel": "Nepromenljivo",
  "originLabel": "Koordinatni početak",
  "cumulativeLabel": "Kumulativno",
  "numberOfRingsLabel": "Broj prstenova",
  "ringsErrorMessage": "Nevažeći broj prstenova",
  "distanceBetweenRingsLabel": "Rastojanje između prstenova",
  "ringsDecimalErrorMessage": "Unesite brojčanu vrednost u 2 decimalna mesta",
  "distanceUnitsLabel": "Jedinice rastojanja",
  "distancesLabel": "Rastojanja",
  "numberOfRadialsLabel": "Broj radijalnih linija",
  "upLabel": "Gore",
  "downLabel": "Dole",
  "deleteLabel": "Izbriši",
  "radialsErrorMessage": "Nevažeći broj radijalnih linija. Maksimalno je dozvoljeno 360",
  "addPointLabel": "Dodaj tačku",
  "valueLabel": "Vrednost",
  "valueText": "Unesite vrednost",
  "actionLabel": "Radnja"
});