define({
  "gridTabLabel": "Mreža",
  "labelTabLabel": "Oznake",
  "referenceSystemTabLabel": "Referentni sustav",
  "gridTabDescription": "Postavite izgled i ponašanje ćelija mreže.",
  "cellOutlineColor": "Boja obrisa ćelije",
  "cellFillColor": "Boja cijele ćelije",
  "transparency": "Prozirnost",
  "cellShapeDropDown": "Oblik ćelije",
  "default": "Pravokutnik",
  "hexagon": "Šesterokut",
  "cellUnitsDropDown": "Jedinice ćelije",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nautical-miles": "Nautičke milje",
  "gridOriginDropDown": "Podrijetlo mreže",
  "lowerLeft": "Donja lijeva strana",
  "lowerRight": "Donja desna strana",
  "upperLeft": "Gornja lijeva strana",
  "upperRight": "Gornja desna strana",
  "center": "Sredina",
  "labelTabDescription": "Postavite izgled i ponašanje oznaka mreže.",
  "labelSettings": "Stil oznake",
  "font": "Font",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "halo": "Halo",
  "show": "Prikaži",
  "labelTypeDropDown": "Vrsta oznake",
  "alphaNumeric": "Alfa-brojčano",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Brojčano",
  "labelDirectionDropDown": "Smjer oznake",
  "horizontal": "Vodoravni",
  "vertical": "Uspravno",
  "labelOriginDropDown": "Podrijetlo oznake",
  "referenceSystemlTabDescription": "Postavite zadani referentni sustav.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Postavke zaključavanja – to će spriječiti korisnika od mijenjanja bilo koje konfigurirane postavke unutar widgeta"
});