define({
  "labelBookmarkName": "현재 뷰에 책갈피 설정",
  "labelPlay": "모두 재생",
  "labelStop": "중지",
  "labelDelete": "삭제",
  "placeholderBookmarkName": "책갈피 이름",
  "errorNameExist": "책갈피가 있습니다.",
  "errorNameNull": "잘못된 책갈피 이름입니다.",
  "editTip": "책갈피 편집",
  "exitEditTip": "편집 모드 종료",
  "syncTip": "동기화",
  "cardsTips": "그리드 뷰",
  "listTips": "목록 뷰",
  "addBtn": "추가",
  "deleteBtn": "삭제",
  "changeThumbnailTip": "섬네일 변경",
  "dragReorderTip": "누른 상태로 드래그하여 순서 바꾸기",
  "deleteBtnTip": "책갈피 삭제",
  "editBtnTip": "책갈피 편집",
  "withVisibility": "레이어 가시성 포함",
  "searchBookmark": "검색",
  "bookmarksFromConfig": "미리 설정된 책갈피",
  "bookmarksFromCache": "로컬 임시 책갈피",
  "notice": "주의",
  "changeNoticeTips": "변경 내용은 브라우저의 캐시에만 저장됩니다. 수정이 완료되면 위젯과 해당 구성 간의 동기화가 차단됩니다.",
  "syncNoticeTips": "이 경우 모든 수정 사항이 지워지고, 구성된 책갈피가 복원됩니다.",
  "dontShowAgain": "다시 표시 안 함",
  "saveVisibility": "레이어 가시성 저장",
  "_widgetLabel": "책갈피"
});