define({
  "tabs_section_Label": "Sekmeler",
  "addTab": "Sekme Ekle",
  "layerName": "Katman",
  "layerType": "Analiz Türü",
  "layerLabel": "Etiket",
  "actions": "İşlemler",
  "closest": "En Yakın Detay",
  "proximity": "Yakınlık",
  "summary": "Özet",
  "select_lbl": "-- Seç --",
  "general_setting_Label": "Genel Ayarlar",
  "units_text_lbl": "Mesafe birimleri",
  "maximum_distance_lbl": "En yakın detayın maksimum mesafesi",
  "buffer_text_lbl": "Tampon etiketi",
  "buffer_lbl": "Tampon mesafesi",
  "buffer_max_lbl": "Maksimum tampon mesafesi",
  "buffer_min_lbl": "Minimum tampon mesafesi",
  "buffer_default_lbl": "Varsayılan tampon mesafesi",
  "not_less_than_max": "Mesafe maksimum tampon mesafesinden az olmalıdır",
  "not_between": "Mesafe minimum ve maksimum tampon mesafesi arasında olmalıdır",
  "not_more_than_min": "Mesafe minimum tampon mesafesinden fazla olmalıdır",
  "not_valid_number": "Geçerli bir sayı olmalıdır",
  "invalid_value": "${type} değeri geçersiz",
  "routing_checkBox": "Rota oluşturmayı etkinleştir",
  "weather_Label": "Hava Durumu Ayarları",
  "weather_checkBox": "Hava durumunu etkinleştir",
  "weather_map_layers": "Hava durumu katmanlarını seç...",
  "selected_map_layers": " Hava durumu katmanı seçildi",
  "instruction_weather": "Hava durumu bilgilerini panelde görüntüleyin.",
  "instruction_weather_layers": "Ek hava durumu katmanlarını görüntüleyin.",
  "instruction_weather_metric": "Standart/metrik değerleri görüntüleyin.",
  "selectLayers": "Hava durumu katmanları seç",
  "weather_removed_message": "Bu araç için hava durumu seçenekleri artık mevcut değil.",
  "currentlySelectedLayer": "Harita katmanlarından seç",
  "missingTabLabel": "En az bir sekmenin etiketi yok",
  "missingLayerInWebMap": "Hiçbir işlem katmanı bulunamadı.",
  "selectFields": "Alanları Seç",
  "addField": "Alan Ekle",
  "sum": "Toplam",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Ortalama",
  "count": "SAYIM",
  "area": "ALAN",
  "length": "UZUNLUK",
  "count_checkBox": "Detay sayısını görüntüle",
  "area_checkBox": "Alan toplamını görüntüle",
  "length_checkBox": "Uzunluk toplamını görüntüle",
  "max_records": "Maksimum sınıra ulaşıldı",
  "save_label": "Seçenekleri Kaydet",
  "save_checkbox": "Kaydetmeyi etkinleştir",
  "report_label": "Rapor Seçenekleri",
  "report_checkbox": "Raporu etkinleştir",
  "csv_label": "CSV Seçenekleri",
  "csv_checkbox": "Tüm alanları dışa aktar",
  "display_label": "Görüntüleme Seçenekleri",
  "display_checkbox": "Özet detaylarını görüntüle",
  "snapshot_label": "Ekran Görüntüsü Alma Seçenekleri",
  "snapshot_checkbox": "Ekran görüntüsü almayı etkinleştir",
  "must_select_template": "Kaydetme Seçeneklerindeki düzenleme şablonlarından birini seçin.",
  "count_label": "Sayı etiketi",
  "area_label": "Alan etiketi",
  "length_label": "Uzunluk etiketi",
  "invalid_string_width": "Değer çok uzun. ",
  "layer_type_not_supported": "Katman Türü Desteklenmiyor",
  "groupedSummary": "Gruplanan Sayısı",
  "groupByField": "Alana göre grupla",
  "labelType": "Etiket Ekle",
  "prefix": "Ön Ek Olarak",
  "suffix": "Son Ek Olarak",
  "need_group_field": "Bir Gruplandırma Ölçütü Alanı tanımlamak için düzenle eylemini kullanın.",
  "fieldTitle": "Alan",
  "typeTitle": "Tür",
  "actionsTitle": "İşlemler",
  "save_point_checkbox": "Noktaları kaydet",
  "save_line_checkbox": "Çizgileri kaydet",
  "save_poly_checkbox": "Alanları kaydet",
  "no_valid_popup_fields": "Açılan pencerede geçerli alan yok. Bir alan tanımlamak için düzenle eylemini kullanın.",
  "no_valid_fields": "Geçerli alan yok. Görüntüleme seçeneklerini tanımlamak için düzenle eylemini kullanın.",
  "incident_label": "Sekme etiketi",
  "locate_incident_label": "İlgi alanı etiketi",
  "incident": "Olay",
  "locate_incident": "Olay Bul",
  "buffer_value": "Tampon Mesafesi",
  "tab_options": "Analiz",
  "export_options": "Çıktı",
  "instruction_save": "Konumu bir detay servisine kaydedin.",
  "instruction_snapshot": "Konuma bağlı olarak bir web haritası oluşturun.",
  "instruction_report": "Konumun basılı bir raporunu oluşturun.",
  "instruction_all_fields": "CSV indirme ile tüm alanları dışa aktarın.",
  "data_label": "Veri Çıktı Ayarları",
  "layer_error": "Katman yok veya geçersiz.",
  "visibility_checkBox": "Katman görünürlüğü yönetimini devre dışı bırak",
  "downloadTab": {
    "reportLegend": "Rapor Ayarları",
    "textColorLabel": "Sütun başlığı rengi seç",
    "setButtonLabel": "Ayarla",
    "printGPServiceLabel": "Servis URL'sini Yazdır",
    "logoLabel": "Logo",
    "logoChooserHint": "Görüntüyü değiştirmek için görüntü simgesine tıklayın",
    "footnoteLabel": "Altbilgi"
  }
});