define({
  "serviceUrl": "Definir url de serviço:",
  "minIntSpacingLabel": "Tamanho Mínimo de Grelha",
  "lineOpacityLabel": "Opacidade de Linha",
  "labelOpacityLabel": "Opacidade de Rótulo",
  "centerLabelOpacityLabel": "Opacidade de Rótulo Central",
  "gridZonePlacementLabel": "Colocação de Rótulo de Zona de Grelha",
  "verticalLineLabels": "Rótulos de Linhas Verticais",
  "styleHeaderLabel": "Estilo",
  "indexHeaderLabel": "Componente de Grelha",
  "colorHeaderLabel": "Cor",
  "fontSizeHeaderLabel": "Tamanho de letra",
  "lineWidthHeaderLabel": "Largura de Linha",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertical",
  "upperLeftLabel": "Superior Esquerdo",
  "upperRightLabel": "Superior Direito",
  "lowerLeftLabel": "Inferior Esquerdo",
  "lowerRightLabel": "Inferior Direito",
  "centerLabel": "Centrar",
  "errorMessage": "A página de configuração contém erros. Por favor, corrija-os antes de guardar.",
  "checkBoxLabel": "Exibir grelha quando o widget está encerrado",
  "checkBoxLabelDashboard": "Exibir grelha",
  "gzd": "Grid Zone Designator (GZD)",
  "gsid": "Grid Square Identification (GSID) de 100,000 metros",
  "grid10k": "Linhas de Grelha de 10,000 metros",
  "grid1k": "Linhas de Grelha de 1,000 metros",
  "grid100m": "Linhas de Grelha de 100 metros",
  "grid10m": "Linhas de Grelha de 10 metros",
  "switchBasemap": "Mudar Mapa Base"
});