define({
  "_widgetLabel": "Räddningstjänstguide",
  "ergMainPageTitle": "Baserat på Räddningstjänstguiden 2016",
  "coordInputLabelStart": "Spillplats (DD)",
  "coordInputLabel": "Spillplats",
  "addPointToolTip": "Lägg till spillplats",
  "drawPointToolTip": "Klicka för att lägga till spillplats",
  "material": "Material",
  "materialPlaceholder": "Börja skriva för att söka efter ett material",
  "table3Message": "Det material du har valt kräver ytterligare information om det handlar om omfattande spill.\n\nSäkerställ att du har valt rätt värden för vindhastighet och transportbehållare.",
  "table2Message": "Det material du har valt kan producera stora mängder gaser som är giftiga vid inandning om de spills i vatten.\n\nDu kan istället välja att använda följande material:\n\n",
  "spillSize": "Spillstorlek",
  "small": "Liten",
  "large": "Stor",
  "fireLabel": "Visa eldisoleringszon",
  "weatherLabel": "Aktuellt väder på spillplats",
  "weatherIntialText": "<br />Uppdateras när en spillplats har identifieras",
  "temperature": "Temperatur",
  "wind": "Vind",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Väderinfo kan inte hämtas. Uppdatera värden för vindhastighet och spilltid manuellt",
  "windDirection": "Vindriktning (blåser mot)",
  "timeOfSpill": "Spilltid",
  "day": "Dag",
  "night": "Natt",
  "windSpeed": "Vindhastighet",
  "low": "Låg",
  "moderate": "Måttligt",
  "high": "Hög",
  "transportContainer": "Transportbehållare",
  "rail": "Järnvägstankvagn",
  "semi": "Tankbil eller släpvagn",
  "mton": "Cylindrar på flera ton",
  "ston": "Många små cylindrar eller cylinder på ett ton",
  "ag": "Tank som används i jordbruk",
  "msm": "Många små cylindrar",
  "bleveLabel": "Visa BLEVE-isoleringszon",
  "capacity": "Behållarens kapacitet (liter)",
  "bleveMessage": "För materialet du valt kan ett ytterligare evakueringsavstånd visas för BLEVE.\n\nOm du vill aktivera det slår du på Visa BLEVE-isoleringszonen och väljer lämplig kapacitet för behållaren.",
  "noPAZoneMessage": "Det finns inga avstånd för skyddsåtgärder för detta material. Enbart ursprungliga isoleringszoner och evakueringszoner har beräknats",
  "settingsTitle": "Inställningar",
  "spillLocationLabel": "Spillplats",
  "spillLocationButtonLabel": "Konfigurera inställningar för spillplats",
  "IISettingsLabel": "Ursprunglig isoleringszon",
  "IIButtonLabel": "Konfigurera ursprungliga inställningar för isolering",
  "PASettingsLabel": "Zon för skyddsåtgärd",
  "PAButtonLabel": "Konfigurera inställningar för skyddsåtgärd",
  "downwindSettingsLabel": "Zon i medvind",
  "downwindButtonLabel": "Konfigurera inställningar för medvind",
  "fireSettingsLabel": "Eldisoleringszon",
  "fireButtonLabel": "Konfigurera inställningar för eldisolering",
  "bleveSettingsLabel": "BLEVE-isoleringszon",
  "bleveButtonLabel": "Konfigurera BLEVE-inställningar",
  "style": "Format",
  "lineStyles": {
    "esriSLSDash": "Streck",
    "esriSLSDashDot": "Streck punkt",
    "esriSLSDashDotDot": "Streck punkt punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Långt streck",
    "esriSLSLongDashDot": "Lång streck-punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort streck",
    "esriSLSShortDashDot": "Kort streck-punkt",
    "esriSLSShortDashDotDot": "Kort streck-punkt-punkt",
    "esriSLSShortDot": "Kort punkt",
    "esriSLSSolid": "Solid"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakåt",
    "esriSFSCross": "Kors",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Framåt",
    "esriSFSHorizontal": "Horisontell",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solid",
    "esriSFSVertical": "Vertikal"
  },
  "resultsTitle": "Resultat",
  "publishERGBtn": "Publicera",
  "ERGLayerName": "Publicerat ERG-lagernamn",
  "invalidERGLayerName": "Lagrets namn får endast innehålla alfanumeriska tecken och understreck",
  "missingERGLayerName": "Du måste ange ett namn på ERG",
  "publishingFailedLayerExists": "Publiceringen misslyckades: du har redan en geoobjekttjänst som heter {0}. Välj ett annat namn.",
  "checkService": "Kontrollera tjänst: {0}",
  "createService": "Skapa tjänst: {0}",
  "unableToCreate": "Det gick inte att skapa: {0}",
  "addToDefinition": "Lägg till i definition: {0}",
  "successfullyPublished": "Webblagret har publicerats{0}Hantera webblagret",
  "userRole": "Det går inte att skapa tjänsten eftersom användaren inte har behörighet",
  "transparency": "Transparens",
  "outline": "Kontur",
  "fill": "Fyllningsfärg (Färgen tillämpas enbart när stilen anges till solid)",
  "createERGBtn": "Skapa zoner",
  "clearERGBtn": "Avmarkera",
  "labelFormat": "Etikettformat",
  "helpIconTooltip": "Tröskeln mellan stora och små spillstorlekar är:\nVätskor 208 liter\nFasta material – 300 kg",
  "cellWidth": "Cellvidd (x)",
  "cellHeight": "Cellhöjd (y)",
  "invalidNumberMessage": "Det angivna värdet är ogiltigt",
  "invalidRangeMessage": "Värdet måste vara större än 0",
  "gridAngleInvalidRangeMessage": "Värdet måste vara mellan -89,9 och 89,9",
  "formatIconTooltip": "Formatinmatning",
  "setCoordFormat": "Ange koordinatsträng",
  "prefixNumbers": "Lägg till prefixet \"+/-\" för positiva och negativa tal",
  "cancelBtn": "Avbryt",
  "applyBtn": "Verkställ",
  "comfirmInputNotation": "Bekräfta inmatningsnotation",
  "notationsMatch": "notationer matchar inmatningen. Bekräfta vilka du vill använda:",
  "missingLayerNameMessage": "Du måste ange ett giltigt lagernamn innan du kan publicera",
  "parseCoordinatesError": "Det gick inte att tolka koordinaterna. Kontrollera din inmatning.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader – Latitud/longitud",
  "DDLongLatNotation": "Decimalgrader – Longitud/latitud",
  "DDMLatLongNotation": "Grader decimalminuter – Latitud/longitud",
  "DDMLongLatNotation": "Grader decimalminuter – Longitud/latitud",
  "DMSLatLongNotation": "Grader minuter sekunder – Latitud/longitud",
  "DMSLongLatNotation": "Grader minuter sekunder – Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbokstav",
  "UTMHemNotation": "UTM – Halvklot (N/S)"
});