define({
  "chartSettingLabel": "Setări diagramă",
  "addNewLabel": "Adăugare nou",
  "generalSettingLabel": "Setări generale",
  "searchSourceSettingLabel": "Setări sursă căutare",
  "layerChooser": {
    "title": "Selectare strat tematic pentru diagramă",
    "selectPolygonLayerLabel": "Selectare strat tematic",
    "selectPolygonLayerHintText": "Sugestie: Dacă realizaţi configurarea mai multor diagrame, atunci straturile tematice trebuie să fie de acelaşi tip de geometrie",
    "selectRelatedTableLayerLabel": "Selectare tabel corelat stratului tematic",
    "selectRelatedTableLayerHintText": "Sugestie: Numai tabelele cu câmpuri numerice sunt afişate",
    "errorInSelectingPolygonLayer": "Vă rugăm să selectaţi un strat tematic care are un strat tematic de puncte corelat.",
    "errorInSelectingRelatedLayer": "Vă rugăm să selectaţi un tabel/strat tematic corelat stratului tematic.",
    "polygonLayerNotHavingRelationships": "Stratul tematic selectat nu are niciun tabel/strat tematic corelat."
  },
  "ChartSetting": {
    "sectionTitle": "Titlu secţiune",
    "sectionTitleHintText": "Sugestie: Afişat în titlul antetului secţiunii",
    "chartTitle": "Titlu diagramă",
    "chartTitleHintText": "Sugestie: Afişat centrat deasupra diagramei",
    "chartDescription": "Descriere",
    "chartDescriptionHintText": "Sugestie: Afişat sub diagramă",
    "chartType": "Tip diagramă",
    "barChart": "Diagramă cu bare",
    "pieChart": "Diagramă radială",
    "polarChart": "Diagramă polară",
    "dataSeriesField": "Câmp şiruri de date",
    "labelField": "Câmp etichetă",
    "chartColor": "Culoare diagramă",
    "singleColor": "O singură culoare",
    "colorByTheme": "Culoare în funcţie de temă",
    "colorByFieldValue": "Culoare în funcţie de valoarea câmpului",
    "xAxisTitle": "Titlu axa X",
    "xAxisHintText": "Sugestie: Titlu axa X",
    "yAxisTitle": "Titlu axa Y",
    "yAxisHintText": "Sugestie: Titlu axa Y",
    "fieldColorLabel": "Etichetă",
    "fieldColorColor": "Culoare",
    "defaultFieldSelectLabel": "Selectare",
    "errMsgFieldValuesNotFound": "Nu s-au putut găsi valori pentru câmpul selectat",
    "errMsgSectionTitle": "Vă rugăm să introduceţi un titlu de secţiune",
    "errMsgFieldByValue": "Vă rugăm să selectaţi valoarea câmpului",
    "settingTabTitle": "Configurare",
    "layoutTabTitle": "Configuraţie",
    "polarChartSelectFieldsHintText": "Sugestie: Selectaţi câmpurile pentru a genera diagrama polară",
    "visibilityText": "Vizibilitate",
    "fieldNameText": "Nume câmp",
    "aliasNameText": "Pseudonim",
    "errMsgPolarFieldsRequired": "Selectaţi trei sau mai multe câmpuri pentru a genera diagrama polară",
    "polarChartPolygonFillLabel": "Umplere poligon",
    "polarChartPolygonFillHintText": "Sugestie: Selectaţi caseta de bifare pentru a afişa umplerea poligonului în diagrama polară",
    "viewLayoutLabel": "Configuraţie",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Deşert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Zonă umedă",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Setări generale",
    "locationSymbolLabel": "Simbol grafic locaţie",
    "locationSymbolHintText": "Sugestie: Utilizat pentru afişarea simbolului pentru adresă şi locaţia apăsării",
    "refreshIntervalLabel": "Interval de reîmprospătare",
    "refreshIntervalHintText": "Sugestie: Utilizat pentru reîmprospătarea diagramelor pe baza acestui interval. Specificaţi o valoare între 1 şi 1440 minute",
    "errMsgRefreshInterval": "Vă rugăm să specificaţi intervalul de reîmprospătare de la 0 la 1440 minute",
    "symbolPickerPreviewText": "Previzualizare:",
    "showToolToSelectLabel": "Setare buton locaţie",
    "showToolToSelectHintText": "Sugestie: Furnizează un buton pentru a seta locaţia pe hartă în loc să seteze întotdeauna locaţia atunci când se face clic pe hartă"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Setări sursă căutare",
    "searchSourceSettingTitle": "Setări sursă căutare",
    "searchSourceSettingTitleHintText": "Adăugaţi şi configuraţi servicii de geocodificare sau straturi tematice de obiecte spaţiale ca surse de căutare. Aceste surse specificate stabilesc ce este căutabil în cadrul casetei de căutare",
    "addSearchSourceLabel": "Adăugare sursă căutare",
    "featureLayerLabel": "Strat tematic de obiecte spaţiale",
    "geocoderLabel": "Geocodificator",
    "nameTitle": "Nume",
    "generalSettingLabel": "Setare generală",
    "allPlaceholderLabel": "Text substituent pentru căutarea tuturor:",
    "allPlaceholderHintText": "Sugestie: Introduceţi textul care va fi afişat ca substituent în timp ce căutaţi în toate straturile tematice şi în geocodificator",
    "generalSettingCheckboxLabel": "Afişaţi fereastra pop-up pentru obiectul spaţial sau locul găsit",
    "countryCode": "Cod(uri) ţară sau regiune",
    "countryCodeEg": "de ex. ",
    "countryCodeHint": "Dacă lăsaţi această valoare necompletată, vor fi căutate toate ţările şi regiunile",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Căutaţi doar în extinderea de hartă curentă",
    "zoomScale": "Scară de transfocare",
    "locatorUrl": "URL geocodificator",
    "locatorName": "Nume geocodificator",
    "locatorExample": "Exemplu",
    "locatorWarning": "Această versiune de serviciu de geocodificare nu este acceptată. Widgetul acceptă serviciul de geocodificare versiunea 10.0 sau ulterioară.",
    "locatorTips": "Sugestiile nu sunt disponibile, deoarece serviciul de geocodificare nu acceptă capacitatea de sugestie.",
    "layerSource": "Sursă straturi tematice",
    "setLayerSource": "Setare sursă straturi tematice",
    "setGeocoderURL": "Setare URL geocodificator",
    "searchLayerTips": "Sugestiile nu sunt disponibile, deoarece serviciul de obiecte spaţiale nu acceptă capacitatea de paginare.",
    "placeholder": "Text substituent",
    "searchFields": "Câmpuri de căutare",
    "displayField": "Câmp de afişare",
    "exactMatch": "Potrivire exactă",
    "maxSuggestions": "Sugestii de maxime",
    "maxResults": "Număr maxim de rezultate",
    "enableLocalSearch": "Activare căutare locală",
    "minScale": "Scară minimă",
    "minScaleHint": "Dacă scara hărţii este mai mare decât această scară, va fi aplicată căutarea locală",
    "radius": "Rază",
    "radiusHint": "Specifică raza unei suprafeţe din jurul centrului actual al hărţii, utilizată pentru a creşte clasificarea candidaţilor de geocodificare, astfel încât candidaţii cei mai apropiaţi de locaţie să fie returnaţi primii",
    "meters": "Metri",
    "setSearchFields": "Setare câmpuri de căutare",
    "set": "Setare",
    "fieldName": "Nume",
    "invalidUrlTip": "Adresa URL ${URL} este nevalidă sau inaccesibilă."
  }
});