define({
  "_widgetLabel": "الوعي الموقفي",
  "locate_incident": "تحديد موقع الحادث",
  "reverse_geocoded_address": "أقرب عنوان",
  "reverse_geocoded_error": "غير متاح",
  "now": "الآن",
  "wind": "رياح",
  "SUN": "الأحد",
  "MON": "الأثنين",
  "TUE": "الثلاثاء",
  "WED": "الأربعاء",
  "THU": "الخميس",
  "FRI": "الجمعة",
  "SAT": "السبت",
  "actionLabel": "تعيين الموقع",
  "drawPoint": "رسم نقطة",
  "drawLine": "رسم خط",
  "drawPolygon": "رسم مضلع",
  "saveIncident": "حفظ",
  "clearIncident": "البدء من جديد",
  "noFeaturesFound": "لم يتم العثور على معالم.",
  "downloadCSV": "تحميل",
  "sum": "مجموع",
  "min": "الحد الأدنى",
  "max": "الحد الأقصى",
  "avg": "المتوسط",
  "count": "عدد",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "تم",
  "delete_btn": "حذف",
  "get_directions": "الحصول على الاتجاهات",
  "incident": "طارئ",
  "incidents": "احداث عرضية",
  "buffer": "نطاق",
  "buffers": "نطاقات",
  "weather": "الطقس",
  "poweredBy": "مشغل بواسطة",
  "_featureAction_ActionLabel": "تعيين الموقع",
  "_featureAction_AddRemoveActionLabel": "إضافة/إزالة موقع",
  "snapshot": "مجلد لقطة الشاشة المُنشأ بواسطة معرف التطبيق:",
  "user_credentials": "لا يحتوي المستخدم على امتيازات صالحة.",
  "notPolySnapShot": "يرجى تحديد مسافة النطاق قبل إنشاء لقطة الشاشة.",
  "notPolyReport": "لا توجد نتائج صحيحة لإضافتها إلى التقرير.",
  "notValidDownload": "لا يوجد نتائج صحيحة للتنزيل.",
  "of_append": "من",
  "layer_append": "الطبقة",
  "downloadAll": "تنزيل الكل",
  "createSnapshot": "إنشاء لقطة الشاشة",
  "createReport": "إنشاء تقرير",
  "calculated_results": "معلومات ملخصة",
  "closest": "أقرب معلم",
  "proximity": "المقاربة",
  "summary": "ملخص",
  "groupedSummary": "أعداد مُجمّعَة",
  "_count": "عدد",
  "approximate": "تقريبي",
  "snapshot_name": "تعيين خصائص لقطة الشاشة",
  "report_name": "تعيين خصائص التقرير",
  "invalid_snapshot_name": "اسم لقطة الشاشة غير صحيح.",
  "invalid_report_name": "عنوان التقرير غير صحيح.",
  "orientation": "توجيه",
  "pageSize": "حجم الصفحة",
  "comments": "التعليقات",
  "choose_group": "مجموعات",
  "forecast": "التنبؤ",
  "select_group": "حدد مجموعة",
  "select_group_instruction": "سيتم إنشاء لقطة الشاشة ومشاركتها مع المجموعة المحددة",
  "information_append": " معلومات",
  "distance": "المسافة",
  "buffer_invalid": "أدخل قيمة صحيحة بين ${min} و${max}"
});