define({
  "_widgetLabel": "緊急時応急措置指針",
  "ergMainPageTitle": "北米 緊急時応急措置指針 2016 に基づく",
  "coordInputLabelStart": "流出位置 (DD)",
  "coordInputLabel": "流出位置",
  "addPointToolTip": "流出位置の追加",
  "drawPointToolTip": "クリックして流出位置を追加",
  "material": "物質名",
  "materialPlaceholder": "マテリアル検索のための入力を開始",
  "table3Message": "大規模の流出を処理する場合、選択したマテリアルには追加情報が必要です。\n\n風速と輸送コンテナーに対して正しい値が選択されていることを確認してください。",
  "table2Message": "選択したマテリアルでは、水中へ流出した場合に吸入すると危険な有毒ガスが大量に発生する可能性があります。\n\n次のマテリアルの使用を検討することをお勧めします。\n\n",
  "spillSize": "流出サイズ",
  "small": "小",
  "large": "大",
  "fireLabel": "火炎隔離ゾーンの表示",
  "weatherLabel": "流出位置の現在の天候",
  "weatherIntialText": "<br />流出位置の特定後に更新済み",
  "temperature": "気温",
  "wind": "風",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "天候情報を取得していません。風速と流出時間の値を手動で更新してください。",
  "windDirection": "風向 (風の進行方向)",
  "timeOfSpill": "流出時間",
  "day": "日中",
  "night": "夜間",
  "windSpeed": "風速",
  "low": "短",
  "moderate": "中",
  "high": "高",
  "transportContainer": "輸送コンテナー",
  "rail": "タンク車",
  "semi": "ハイウェイ タンクローリー/トレーラー",
  "mton": "複数のトン ボンベ",
  "ston": "複数の小型ボンベまたは単一のトン ボンベ",
  "ag": "農業用ナース タンク",
  "msm": "複数の小型ボンベ",
  "bleveLabel": "BLEVE 隔離ゾーンの表示",
  "capacity": "コンテナーの容量 (リットル)",
  "bleveMessage": "選択したマテリアルでは、BLEVE に対する追加の避難距離を表示できます。\n\nこのためには、[BLEVE 隔離ゾーンの表示] をオンに設定し、適切なコンテナー容量を選択してください。",
  "noPAZoneMessage": "このマテリアルには防護措置の距離がありません。初期の隔離および避難ゾーンのみが計算されています。",
  "settingsTitle": "設定",
  "spillLocationLabel": "流出位置",
  "spillLocationButtonLabel": "流出位置設定の構成",
  "IISettingsLabel": "初期隔離ゾーン",
  "IIButtonLabel": "初期隔離設定の構成",
  "PASettingsLabel": "防護措置ゾーン",
  "PAButtonLabel": "防護措置設定の構成",
  "downwindSettingsLabel": "風下ゾーン",
  "downwindButtonLabel": "風下設定の構成",
  "fireSettingsLabel": "火炎隔離ゾーン",
  "fireButtonLabel": "火炎隔離設定の構成",
  "bleveSettingsLabel": "BLEVE 隔離ゾーン",
  "bleveButtonLabel": "BLEVE 設定の構成",
  "style": "スタイル",
  "lineStyles": {
    "esriSLSDash": "破線",
    "esriSLSDashDot": "1 点鎖線",
    "esriSLSDashDotDot": "2 点鎖線",
    "esriSLSDot": "ドット",
    "esriSLSLongDash": "長い破線",
    "esriSLSLongDashDot": "長い 1 点鎖線",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "短い破線",
    "esriSLSShortDashDot": "短い 1 点鎖線",
    "esriSLSShortDashDotDot": "短い 2 点鎖線",
    "esriSLSShortDot": "短いドット",
    "esriSLSSolid": "実線"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "逆方向",
    "esriSFSCross": "クロス",
    "esriSFSDiagonalCross": "対角線",
    "esriSFSForwardDiagonal": "正方向",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "実線",
    "esriSFSVertical": "鉛直方向"
  },
  "resultsTitle": "結果",
  "publishERGBtn": "公開",
  "ERGLayerName": "公開された ERG レイヤー名",
  "invalidERGLayerName": "レイヤー名は、英数字とアンダースコア (_) だけを含むようにする必要があります。",
  "missingERGLayerName": "ERG の名前を入力する必要があります。",
  "publishingFailedLayerExists": "公開に失敗しました: フィーチャ サービス名 {0} はすでに存在しています。別の名前を選択してください。",
  "checkService": "次のサービスを確認: {0}",
  "createService": "次のサービスを作成: {0}",
  "unableToCreate": "次のものを作成できません: {0}",
  "addToDefinition": "定義に追加: {0}",
  "successfullyPublished": "Web レイヤー {0} を正常に公開できました。Web レイヤーの管理",
  "userRole": "ユーザーにアクセス権限がないため、サービスを作成できません。",
  "transparency": "透過表示",
  "outline": "アウトライン",
  "fill": "塗りつぶし (スタイルを実線に設定した場合のみ色を適用)",
  "createERGBtn": "ゾーンの作成",
  "clearERGBtn": "解除",
  "labelFormat": "ラベル形式",
  "helpIconTooltip": "小規模および大規模の流出サイズ間の閾値は次のとおりです。\n液体 - 55 ガロン (208 リットル)\n個体 - 60 ポンド (300 キログラム)",
  "cellWidth": "セルの幅 (x)",
  "cellHeight": "セルの高さ (y)",
  "invalidNumberMessage": "入力された値が有効ではありません。",
  "invalidRangeMessage": "値は 0 より大きくなければなりません。",
  "gridAngleInvalidRangeMessage": "値は -89.9 ～ 89.9 の間でなければなりません",
  "formatIconTooltip": "入力の書式設定",
  "setCoordFormat": "座標形式の文字列の設定",
  "prefixNumbers": "正と負の数値に '+/-' の接頭辞を追加",
  "cancelBtn": "キャンセル",
  "applyBtn": "申請",
  "comfirmInputNotation": "入力表記の確認",
  "notationsMatch": "入力と一致する表記。使用する内容を確認してください。",
  "missingLayerNameMessage": "公開の前に、有効なレイヤー名を入力する必要があります。",
  "parseCoordinatesError": "座標を解析できません。 入力を確認してください。",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "度 (10進) - 緯度/経度",
  "DDLongLatNotation": "度 (10進) - 経度/緯度",
  "DDMLatLongNotation": "度分 (10進) - 緯度/経度",
  "DDMLongLatNotation": "度分 (10進) - 経度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/経度",
  "DMSLongLatNotation": "度分秒 - 経度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - バンド文字",
  "UTMHemNotation": "UTM - 半球 (N/S)"
});