define({
  "_widgetLabel": "Hướng dẫn Phản ứng Khẩn cấp",
  "ergMainPageTitle": "Dựa trên Sách hướng dẫn Phản ứng Khẩn cấp 2016",
  "coordInputLabelStart": "Vị trí Tràn (DD)",
  "coordInputLabel": "Vị trí Tràn",
  "addPointToolTip": "Thêm Vị trí Tràn",
  "drawPointToolTip": "Bấm vào để thêm vị trí tràn",
  "material": "Vật liệu",
  "materialPlaceholder": "Bắt đầu nhập để tìm kiếm vật liệu",
  "table3Message": "Vật liệu bạn đã chọn yêu cầu thông tin bổ sung nếu bạn đang xử lý  một điểm tràn lớn.\n\nHãy chắc chắn bạn đã chọn giá trị chính xác cho tốc độ gió và thùng vận chuyển.",
  "table2Message": "Vật liệu bạn đã chọn có thể sản sinh ra lượng lớn khí Độc gây nguy hiểm khi hít phải khi bị đổ tràn vào nước.\n\nBạn nên xem xét sử dụng vật liệu sau:\n\n",
  "spillSize": "Kích thước Tràn",
  "small": "Nhỏ",
  "large": "Lớn",
  "fireLabel": "Hiển thị Vùng Cô lập Hỏa hoạn",
  "weatherLabel": "Thời tiết hiện tại ở Vị trí Tràn",
  "weatherIntialText": "<br />Được cập nhật sau khi phát hiện một vị trí tràn",
  "temperature": "Nhiệt độ",
  "wind": "Gió",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Không có thông tin thời tiết. Cập nhật thủ công các giá trị Tốc độ Gió và Thời gian Tràn",
  "windDirection": "Hướng Gió (thổi tới)",
  "timeOfSpill": "Thời gian Tràn",
  "day": "Ngày",
  "night": "Đêm",
  "windSpeed": "Tốc độ Gió",
  "low": "Thấp",
  "moderate": "Vừa phải",
  "high": "Cao",
  "transportContainer": "Thùng Vận chuyển",
  "rail": "Xe bồn kéo",
  "semi": "Xe bồn hoặc xe kéo chạy cao tốc",
  "mton": "Xy-lanh đa trọng",
  "ston": "Xy-lanh nhỏ đa trọng hoặc xy-lanh một tấn",
  "ag": "Bồn ủ nông sản",
  "msm": "Xy-lanh nhỏ đa trọng",
  "bleveLabel": "Hiển thị Vùng Cô lập BLEVE",
  "capacity": "Dung tích thùng chứa (lít)",
  "bleveMessage": "Để vật liệu bạn đã chọn thêm một khoảng cách sơ tán có thể hiển thị cho BLEVE.\n\nĐể thực hiện điều này, hãy bật Hiển thị Vùng Cô lập BLEVE và chọn dung tích thùng chứa phù hợp.",
  "noPAZoneMessage": "Không có khoảng cách Hành động Bảo vệ cho vật liệu này. Chỉ có thể tính toán vùng Cô lập Ban đầu và vùng sơ tán",
  "settingsTitle": "Thiết lập",
  "spillLocationLabel": "Vị trí Tràn",
  "spillLocationButtonLabel": "Cấu hình Cài đặt Vị trí Tràn",
  "IISettingsLabel": "Vùng Cô lập Ban đầu",
  "IIButtonLabel": "Cấu hình Cài đặt Cô lập Ban đầu",
  "PASettingsLabel": "Vùng Hành động Bảo vệ",
  "PAButtonLabel": "Cấu hình Cài đặt Hành động Bảo vệ",
  "downwindSettingsLabel": "Vùng Xuôi gió",
  "downwindButtonLabel": "Cấu hình Cài đặt Xuôi gió",
  "fireSettingsLabel": "Vùng Cô lập Hỏa hoạn",
  "fireButtonLabel": "Cấu hình Cài đặt Cô lập Hỏa hoạn",
  "bleveSettingsLabel": "Vùng Cô lập BLEVE",
  "bleveButtonLabel": "Cấu hình Cài đặt BLEVE",
  "style": "Kiểu",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  },
  "resultsTitle": "Kết quả",
  "publishERGBtn": "Xuất bản",
  "ERGLayerName": "Tên Lớp ERG đã xuất bản",
  "invalidERGLayerName": "Tên lớp chỉ được chứa các ký tự chữ số và dấu gạch dưới",
  "missingERGLayerName": "Bạn phải nhập tên cho ERG",
  "publishingFailedLayerExists": "Xuất bản không thành công: Bạn đã có dịch vụ đối tượng có tên {0}. Vui lòng chọn tên khác.",
  "checkService": "Kiểm tra Dịch vụ: {0}.",
  "createService": "Tạo Dịch vụ: {0}",
  "unableToCreate": "Không thể tạo: {0}",
  "addToDefinition": "Thêm vào định nghĩa: {0}",
  "successfullyPublished": "Xuất bản lớp web thành công{0}Quản lý lớp web",
  "userRole": "Không thể tạo dịch vụ do người dùng không có phân quyền",
  "transparency": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô kín (Màu chỉ áp dụng khi kiểu được đặt thành đồng màu)",
  "createERGBtn": "Tạo Vùng",
  "clearERGBtn": "Xóa",
  "labelFormat": "Định dạng nhãn",
  "helpIconTooltip": "Ngưỡng trong khoảng kích thước tràn lớn và nhỏ là:\nChất lỏng - 55 gallon (208 lít)\nChất rắn - 60 pound (300 kilogram)",
  "cellWidth": "Chiều rộng ô (x)",
  "cellHeight": "Chiều cao ô (y)",
  "invalidNumberMessage": "Giá trị đã nhập không hợp lệ",
  "invalidRangeMessage": "Giá trị phải lớn hơn 0",
  "gridAngleInvalidRangeMessage": "Giá trị phải nằm trong khoảng từ -89,9 đến 89,9",
  "formatIconTooltip": "Định dạng đầu vào",
  "setCoordFormat": "Thiết lập chuỗi định dạng tọa độ",
  "prefixNumbers": "Thêm tiền tố \"+/-\" vào số dương và số âm",
  "cancelBtn": "Hủy",
  "applyBtn": "Áp dụng",
  "comfirmInputNotation": "Xác nhận Ký hiệu đầu vào",
  "notationsMatch": "các ký hiệu khớp với thông tin của bạn. Vui lòng xác nhận ký hiệu bạn muốn sử dụng:",
  "missingLayerNameMessage": "Bạn phải nhập tên lớp hợp lệ trước khi có thể xuất bản",
  "parseCoordinatesError": "Không thể dán tọa độ. Vui lòng kiểm tra thông tin của bạn.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Độ thập phân - Vĩ độ/Kinh độ",
  "DDLongLatNotation": "Độ thập phân - Kinh độ/Vĩ độ",
  "DDMLatLongNotation": "Độ thập phân phút - Vĩ độ/Kinh độ",
  "DDMLongLatNotation": "Độ thập phân phút - Kinh độ/Vĩ độ",
  "DMSLatLongNotation": "Độ thập phân giây - Vĩ độ/Kinh độ",
  "DMSLongLatNotation": "Độ thập phân giây - Kinh độ/Vĩ độ",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Chữ cái dải sóng",
  "UTMHemNotation": "UTM - Bán cầu (Bắc/Nam)"
});