define({
  "serviceUrl": "Thiết lập url dịch vụ:",
  "minIntSpacingLabel": "Kích cỡ Lưới Tối thiểu",
  "lineOpacityLabel": "Độ mờ đục của dòng",
  "labelOpacityLabel": "Độ mờ đục của nhãn",
  "centerLabelOpacityLabel": "Độ mờ đục của nhãn trung tâm",
  "gridZonePlacementLabel": "Đặt nhãn vùng lưới",
  "verticalLineLabels": "Nhãn dòng thẳng đứng",
  "styleHeaderLabel": "Kiểu",
  "indexHeaderLabel": "Thành phần Lưới",
  "colorHeaderLabel": "Màu sắc",
  "fontSizeHeaderLabel": "Cỡ Chữ",
  "lineWidthHeaderLabel": "Chiều rộng đường",
  "horizontalLabel": "Ngang",
  "verticalLabel": "Dọc",
  "upperLeftLabel": "Phía trên Bên trái",
  "upperRightLabel": "Phía trên Bên phải",
  "lowerLeftLabel": "Phía dưới Bên trái",
  "lowerRightLabel": "Phía dưới Bên phải",
  "centerLabel": "Tâm",
  "errorMessage": "Trang cấu hình có một số lỗi. Vui lòng khắc phục trước khi lưu.",
  "checkBoxLabel": "Hiển thị lưới khi tiện ích được đóng",
  "checkBoxLabelDashboard": "Hiển thị lưới",
  "gzd": "Bộ chỉ định Vùng Lưới (GZD)",
  "gsid": "Xác định Hình vuông Lưới 100.000 mét (GSID)",
  "grid10k": "Đường thẳng Lưới 10.000 mét",
  "grid1k": "Đường thẳng Lưới 1.000 mét",
  "grid100m": "Đường thẳng Lưới 100 mét",
  "grid10m": "Đường thẳng Lưới 10 mét",
  "switchBasemap": "Chuyển đổi Bản đồ nền"
});