define({
  "enableUndoRedo": "Abilita Annulla/Ripeti",
  "toolbarVisible": "Barra degli strumenti visibile",
  "toolbarOptions": "Opzioni barra degli strumenti",
  "mergeVisible": "Unisci",
  "cutVisible": "Taglia",
  "reshapeVisible": "Rimodella",
  "back": "Indietro",
  "label": "Layer",
  "edit": "Modificabile",
  "update": "Disabilita aggiornamento geometria",
  "fields": "Campi",
  "actions": "Azioni",
  "editpageName": "Nome",
  "editpageAlias": "Alias",
  "editpageVisible": "Visibile",
  "editpageEditable": "Modificabile",
  "noLayers": "Non sono disponibili feature layer modificabili",
  "configureFields": "Configura campi layer",
  "useFilterEdit": "Utilizza filtro modello di feature",
  "display": "Visualizza",
  "autoApplyEditWhenGeometryIsMoved": "Applica automaticamente la modifica quando la geometria viene spostata",
  "snappingTolerance": "Imposta la tolleranza snap in pixel",
  "popupTolerance": "Imposta la tolleranza del popup di modifica dell'attributo in pixel",
  "stickyMoveTolerance": "Imposta la tolleranza spostamento permanente in pixel",
  "usingSaveButton": "Le modifiche apportate agli attributi non vengono applicate finché non si clicca il pulsante Salva"
});