define({
  "_widgetLabel": "Võrguruudustikuga viitepilt (GRG)",
  "newGRGFromAreaButtonLabel": "Määratle ruudustik ala põhjal",
  "newGRGFromPointButtonLabel": "Määratle ruudustik punkti põhjal",
  "newGRGFromAreaTitle": "Määratle ruudustik ala põhjal",
  "newGRGFromPointTitle": "Määratle ruudustik punkti põhjal",
  "newGRGBySizeButtonLabel": "Dimensiooni järgi",
  "newGRGFromRefSystemButtonLabel": "Referentssüsteemi järgi",
  "newGRGByTimeLabel": "Aja ja kiiruse järgi",
  "newGRGFromNonStandardButtonLabel": "Määratle mittestandardne ruudustik",
  "newGRGAreaBySizeTitle": "GRG ala põhjal dimensiooni järgi",
  "newGRGAreaBySizeDefineAreaLabel": "GRG ala",
  "addGRGAreaPolygonToolTip": "Joonista GRG ala polügooni abil",
  "addGRGAreaExtentToolTip": "Joonista GRG ala ulatuse abil",
  "rotation": "Ruudustiku pööramine",
  "numberRowsColumnsLabel": "Määratle ridade ja veergude arv",
  "newGRGAreaByRefSystemTitle": "GRG ala põhjal referentssüsteemi järgi",
  "gridSize": "Ruudustiku suurus",
  "UTMZoneandBand": "Ruudustiku tsoon",
  "100000m": "100 000 meetrit",
  "10000m": "10 000 meetrit",
  "1000m": "1000 meetrit",
  "100m": "100 meetrit",
  "10m": "10 meetrit",
  "clipGrid": "Kinnita ruudustik GRG ala külge",
  "newGRGAreaFromNonStandardTitle": "Uus NRG",
  "newGRGPointBySizeTitle": "GRG punkti põhjal dimensiooni järgi",
  "newGRGPointByRefSystemTitle": "GRG punkti põhjal referentssüsteemi järgi",
  "newGRGPointByTimeTitle": "GRG punkti põhjal aja ja kiiruse abil",
  "time": "Aeg",
  "rate": "Kiirus",
  "hours": "Tunnid",
  "minutes": "Minutid",
  "seconds": "Sekundid",
  "ftPerSec": "Jalga sekundis",
  "ftPerHour": "Jalga tunnis",
  "kmPerSec": "Kilomeetrit sekundis",
  "kmPerHour": "Kilomeetrit tunnis",
  "mPerSec": "Meetrit sekundis",
  "mPerHour": "Meetrit tunnis",
  "miPerSec": "Miili sekundis",
  "miPerHour": "Miili tunnis",
  "nMPerSec": "Meremiili sekundis",
  "nMPerHour": "Meremiili tunnis",
  "settingsTitle": "Sätted",
  "labelSettingsLabel": "Sildisätted",
  "labelSettingsButtonLabel": "Konfigureeri märgiste seaded",
  "gridSettingsLabel": "Ruudustiku sätted",
  "gridSettingsButtonLabel": "Konfigureeri ruudustiku seaded",
  "transparency": "Läbipaistvus",
  "labelStyle": "Märgise laad",
  "font": "Font",
  "textSize": "Teksti suurus",
  "textColor": "Teksti värv",
  "halo": "Halo",
  "show": "Kuva",
  "lockSettings": "Rakenduse omanik on seaded lukustanud",
  "gridSettings": {
    "cellShape": "Ruudu kuju",
    "cellUnits": "Ruudu mõõtühikud",
    "cellOutline": "Ruudu kontuuri sätted",
    "cellFill": "Ruudu täite sätted",
    "gridReferenceSystem": "Referentssüsteem",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Sildi päritolu",
    "labelType": "Sildi tüüp",
    "labelDirection": "Sildi suund",
    "gridOrigin": "Ruudu päritolu",
    "default": "Nelinurk",
    "hexagon": "Kuusnurk",
    "miles": "Miilid",
    "kilometers": "Kilomeetrid",
    "feet": "Jalad",
    "meters": "Meetrid",
    "yards": "Jardid",
    "nautical-miles": "Meremiilid",
    "lowerLeft": "All vasakul",
    "lowerRight": "All paremal",
    "upperLeft": "Üleval vasakul",
    "upperRight": "Üleval paremal",
    "center": "Keskel",
    "alphaNumeric": "Tähed ja numbrid",
    "alphaAlpha": "Tähed ja tähed",
    "numeric": "Numbriline",
    "horizontal": "Horisontaalne",
    "vertical": "Vertikaalne",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Näita silte"
  },
  "publishTitle": "Avalda GRG portaalis",
  "publishGRGBtn": "Avalda",
  "GRGLayerName": "Avaldatud GRG kihi nimi",
  "invalidGRGLayerName": "Kihi nimi tohib sisaldada ainult tähe- ja numbrimärke ning allkriipse",
  "missingGRGLayerName": "Peate sisestama GRG nime",
  "publishingFailedLayerExists": "Avaldamine nurjus: objektiteenus nimega {0} on juba olemas. Valige mõni muu nimi.",
  "checkService": "Kontrolli teenust: {0}",
  "createService": "Loo teenus: {0}",
  "unableToCreate": "Ei saa luua: {0}",
  "addToDefinition": "Lisa definitsiooni: {0}",
  "successfullyPublished": "Veebikiht on avaldatud{0}Halda veebikihti",
  "userRole": "Teenust ei saa luua, kuna kasutajal pole nõutavaid õigusi",
  "createGRGBtn": "Loo GRG",
  "clearGRGBtn": "Tühjenda",
  "labelFormat": "Sildi vorming",
  "helpIconTooltip": "Z: ruudustikutsooni designaator (GZD)\nS: 100 000-meetrise ruudustikuruudu identifikaator (GSID)\nX: X-koordinaat\nY: Y-koordinaat\n\nNäited:\nZSXY on 15SWC8081751205\nZS X,Y on 15SWC 80817,51205",
  "addPointToolTip": "Lisa GRG päritolu",
  "cellWidth": "Ruudu laius (x)",
  "cellHeight": "Ruudu kõrgus (y)",
  "invalidNumberMessage": "Sisestatud väärtus ei sobi",
  "invalidRangeMessage": "Väärtus peab olema suurem kui 0",
  "gridAngleInvalidRangeMessage": "Väärtus peab olema vahemikus -89,9 kuni 89,9",
  "formatIconTooltip": "Vormingu sisestus",
  "coordInputLabel": "GRG päritolu (DD)",
  "setCoordFormat": "Määra koordinaatide vormingu string",
  "prefixNumbers": "Lisa positiivsetele ja negatiivsetele arvudele eesliide „+/-”",
  "cancelBtn": "Loobu",
  "applyBtn": "Rakenda",
  "comfirmInputNotation": "Kinnita sisestatud tähistus",
  "notationsMatch": "tähistust vastab teie sisestusele; palun kinnitage, millist soovite kasutada:",
  "numberOfCellsHorizontal": "Horisontaallahtrite arv",
  "numberOfCellsVertical": "Vertikaallahtrite arv",
  "gridAngle": "Ruudustiku pööramine",
  "tooManyCellsErrorMessage": "Proovite luua ruudustikku, mis sisaldab rohkem kui 2000 ruutu. Soovitatav on loodavate ruutude arvu vähendada, muutes ruudustiku suurust või ala.",
  "missingParametersMessage": "<p>GRG loomise vormil on parameetreid puudu või mõni parameeter ei sobi. Veenduge, et:</p><ul><li>GRG ala oleks joonistatud;</li><li>ruudu laiuse ja kõrguse väärtused oleksid sobivad.</li></ul>",
  "missingOriginParametersMessage": "<p>GRG loomise vormil on parameetreid puudu või mõni parameeter ei sobi. Veenduge, et:</p><ul><li>GRG päritolu oleks määratud;</li><li>aja, kiiruse ja nurga jaoks oleksid sisestatud sobivad väärtused.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG loomise vormil on parameetreid puudu või mõni parameeter ei sobi. Veenduge, et ruudu laiuse ja kõrguse väärtused oleksid sobivad.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG loomise vormil on parameetreid puudu või mõni parameeter ei sobi. Veenduge, et horisontaal- ja vertikaalruutude arvu väärtused oleksid sobivad.</p>",
  "drawPointToolTip": "Klõpsake GRG päritolupunkti lisamiseks",
  "missingLayerNameMessage": "Avaldamiseks peate esmalt sisestama sobiva kihinime",
  "parseCoordinatesError": "Ei saa koordinaate sõeluda. Kontrollige sisendit.",
  "grgPolarRegionError": "GRG ulatus asub polaarpiirkonnas. Ruute, mis jäävad polaarpiirkonda, ei looda.",
  "grgPolarOriginError": "GRG päritolupunkt ei tohi GRG loomisel referentssüsteemi põhjal jääda polaarpiirkonda.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Kümnendkraadid – laiuskraad/pikkuskraad",
  "DDLongLatNotation": "Kümnendkraadid  – pikkuskraad/laiuskraad",
  "DDMLatLongNotation": "Kraadid-kümnendminutid – laiuskraad/pikkuskraad",
  "DDMLongLatNotation": "Kraadid-kümnendminutid – pikkuskraad/laiuskraad",
  "DMSLatLongNotation": "Kraadid-kümnendsekundid – laiuskraad/pikkuskraad",
  "DMSLongLatNotation": "Kraadid-kümnendsekundid – pikkuskraad/laiuskraad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – vahemiku täht",
  "UTMHemNotation": "UTM – poolkera (N/S)"
});