define({
  "_widgetLabel": "Modelirnik primernosti",
  "general": {
    "clear": "Počisti",
    "cancel": "Prekliči",
    "save": "Zaženi",
    "saveAs": "Izvozi"
  },
  "saveModel": {
    "save": "Izvozi",
    "title": "Naslov: ",
    "summary": "Povzetek: ",
    "description": "Opis: ",
    "tags": "Oznake: ",
    "folder": "Mapa: ",
    "homeFolderPattern": "{username} (Domov)",
    "failed": "Izvoz ni uspel."
  },
  "util": {
    "colorRamp": {
      "1": "Izjemno nizko",
      "2": "Zelo nizko",
      "3": "Nizko",
      "4": "Srednje nizko",
      "5": "Srednje",
      "6": "Srednje visoko",
      "7": "Visoko",
      "8": "Zelo visoko",
      "9": "Izjemno visoko",
      "low": "Nizko",
      "high": "Visoko",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Obrni"
    }
  },
  "wro": {
    "caption": "Modelirnik primernosti",
    "browsePrompt": "Obtežena storitev prekrivanja",
    "selectLayersCaption": "Izberi sloje",
    "selectLayers": "Sloji",
    "designModelCaption": "Oblikuj model",
    "designModel": "Oblikuj model",
    "transparency": "Prosojnost",
    "visible": "Vidno",
    "total": "Skupno",
    "unableToLoad": "Modela ni mogoče naložiti.",
    "projectNotOpen": "Projekt ni odprt.",
    "readMore": "Preberi več",
    "validation": {
      "validating": "Potrjevanje...",
      "invalidItemCaption": "Storitev obteženega prekrivanja javlja opozorilo",
      "notAnImageService": "Ta element ni slikovna storitev.",
      "notAWroService": "Ta element ni storitev obteženega prekrivanja",
      "undefinedUrl": "URL tega elementa ni določen.",
      "inaccessible": "Storitev ni dostopna.",
      "generalError": "Elementa ni mogoče odpreti.",
      "missingFieldPattern": "{field} je obvezno polje",
      "notAllowRasterFunction": "Možnost DovoliRastrskoFunkcijo mora biti nastavljena na resnično",
      "notNearestResampling": "PrivzetaMetodaPrevzorčenja mora biti Najbližji",
      "notIsWeightedOverlayProp": "Ključna lastnost JeObteženoPrekrivanje mora biti nastavljena na resnično",
      "invalidLink": "URL ni veljaven. Strani za izbrani sloj ni mogoče odpreti.",
      "unexpectedError": "Prišlo je do nepričakovanega stanja.",
      "rangeMessage": "Vrednost mora biti med ${0} in ${1}",
      "rangeMessage100": "Vrednost mora biti med 0 in 100",
      "maxLayers": "Storitev dovoljuje maksimalno ${0} slojev. Preden dodate novega, morate sloj odstraniti.",
      "notFound": "Sloj ${0} ni bil najden v storitvi obteženega prekrivanja",
      "wroServiceNotDefined": "Za model ni določene storitve obteženega prekrivanja.",
      "overlayLayerOutputInvalid": "Izhodna vrednost razpona preslikave [${1}] sloja prekrivanja [${0}] manjka ali ni veljavna",
      "overlayLayerInputInvalid": "Vhodna minimalna/maksimalna vrednost razpona preslikave [${1}] sloja prekrivanja [${0}] manjka ali ni veljavna",
      "overlayLayerRangesMissing": "Manjkajoči razponi preslikave sloja prekrivanja [${0}]",
      "overlayLayerWeight": "Vrednosti obteževanja morajo skupaj znašati 100",
      "overlayLayerRequired": "Zahtevan je vsaj en sloj prekrivanja",
      "overlayLayerNotDefined": "Sloji prekrivanja niso določeni",
      "requiresColormap": "Ta funkcija rastra zahteva barvno paleto, vendar model nima veljavne določitve barvne palete",
      "createModelError": "Napaka pri ustvarjanju modela",
      "invalidModel": "Model ni veljaven",
      "imageServiceNotDefined": "Sloj slikovne storitve ni določen",
      "imageLayerNotDefined": "Sloj slikovne storitve ni določen",
      "histogramNotDefined": "Funkcija histograma obteženega prekrivanja ni določena"
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zelena rumena rdeča",
      "Red Yellow Green": "Rdeča Rumena Zelena",
      "Yellow to Dark Red": "Rumena do temno rdeča",
      "Dark Red to Yellow": "Temno rdeča do rumena",
      "Light Gray to Dark Gray": "Svetlo siva do temno siva",
      "Dark Gray to Light Gray": "Temno siva do svetlo siva",
      "Light Brown to Dark Brown": "Svetlo rjava do temno rjava",
      "Dark Brown to Light Brown": "Temno rjava do svetlo rjava",
      "Full Spectrum - Bright Red to Blue": "Celoten spekter – živo rdeča do modra",
      "Full Spectrum - Bright Blue to Red": "Celoten spekter – živo modra do rdeča",
      "Partial Spectrum - Yellow to Blue": "Delni spekter – Rumena do modra",
      "Partial Spectrum - Blue to Yellow": "Delni spekter – modra do rumena",
      "Yellow-Green to Dark Blue": "Rumeno-zelena do temno modra",
      "Dark Blue to Yellow-Green": "Temno modra do rumeno-zelena",
      "Cold to Hot Diverging": "Premikanje od mrzlega do vročega",
      "Hot to Cold Diverging": "Premikanje od vročega do mrzlega",
      "Surface - Low to High": "Površina – nizko do visoko",
      "Surface - High to Low": "Površina – visoko do nizko"
    }
  },
  "tabs": {
    "layers": "Sloji",
    "model": "Model",
    "chart": "Grafikon"
  },
  "chart": {
    "prompt": "Geoobjekti",
    "working": "Posodabljanje...",
    "polygonTool": "Nariši poligon",
    "freehandPolygonTool": "Nariši prostoročni poligon",
    "selectTool": "Izberi iz sloja",
    "panTool": "Pomik",
    "clearButton": "Počisti",
    "noModelLayer": "Ni modela.",
    "noSubjectLayers": "Vaša karta nima poligonskih slojev.",
    "tipPattern": "${category} – ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} – ${label}"
  }
});