define({
  "settings": "Ρυθμίσεις",
  "titleSettings": "Ρυθμίσεις κειμένου",
  "imageSettings": "Ρυθμίσεις εικόνας",
  "backgroundColor": "Χρώμα φόντου",
  "alignment": "Στοίχιση",
  "textSize": "Μέγεθος κειμένου",
  "textColor": "Χρώμα κειμένου",
  "dataSource": "Προέλευση δεδομένων",
  "chartSettings": "Ρυθμίσεις γραφημάτων",
  "data": "Δεδομένα",
  "dataLabels": "Ετικέτες δεδομένων",
  "displayMode": "Λειτουργία εμφάνισης",
  "featureOption": "Εμφάνιση τιμών ανά στοιχείο",
  "categoryOption": "Εμφάνιση τιμών ανά κατηγορία",
  "countOption": "Εμφάνιση πλήθους στοιχείων ανά κατηγορία",
  "fieldOption": "Εμφάνιση τιμών στοιχείων ως γραφήματα",
  "categoryField": "Πεδίο κατηγορίας",
  "labelField": "Πεδίο ετικέτας",
  "valueFields": "Πεδία τιμών",
  "operation": "Λειτουργία",
  "sumOption": "Άθροισμα",
  "averageOption": "Μέσος όρος",
  "minOption": "Ελάχιστο",
  "maxOption": "Μέγιστο",
  "dataFormat": "Μορφή δεδομένων",
  "decimalPlaces": "Δεκαδικά ψηφία",
  "prefix": "Πρόθεμα",
  "suffix": "Επίθημα",
  "dataType": "Τύπος δεδομένων",
  "featureCount": "Πλήθος στοιχείων",
  "fieldStatistics": "Στατιστικά στοιχεία πεδίου",
  "display": "Εμφάνιση",
  "chartColor": "Χρώμα γραφήματος",
  "horizontalAxis": "Οριζόντιος άξονας",
  "verticalAxis": "Κατακόρυφος άξονας",
  "legend": "Υπόμνημα",
  "position": "Θέση",
  "top": "Επάνω",
  "bottom": "Κάτω",
  "useDataSourceSelection": "Χρήση επιλογής",
  "dataSourceFilterByExtent": "Φιλτράρισμα ανά έκταση",
  "changeTemplate": "Αλλαγή προτύπου",
  "numberSettings": "Ρυθμίσεις αριθμού",
  "gaugeSettings": "Ρυθμίσεις μέτρησης",
  "indicators": "Δείκτες",
  "ifValue": "Αν η τιμή",
  "and": "και",
  "numberOperatorIsLessThan": "είναι λιγότερο από",
  "numberOperatorIsGreaterThan": "είναι μεγαλύτερο από",
  "numberOperatorIsBetween": "είναι μεταξύ",
  "numberOperatorIsEqual": "είναι ίσο με",
  "numberOperatorIsNotEqual": "δεν είναι ίσο με",
  "then": "Τότε",
  "ratio": "Αναλογία",
  "trueValue": "Πραγματική τιμή",
  "changeValueColor": "αλλαγή χρώματος τιμής σε",
  "changeGaugeColor": "αλλαγή χρώματος μέτρησης σε",
  "setIndicatorIcon": "ορισμός εικονιδίου δείκτη σε",
  "icons": "Εικονίδια",
  "style": "Style",
  "placement": "Τοποθέτηση",
  "left": "Αριστερά",
  "replace": "Αντικατάσταση",
  "right": "Δεξιά",
  "color": "Χρώμα",
  "categoryExists": "Η κατηγορία υπάρχει!",
  "comboxHint": "Πληκτρολογήστε ή επιλέξτε μία.",
  "comboxDisableInputHint": "Επιλέξτε μία.",
  "sortBy": "Ταξινόμηση κατά",
  "labelAxis": "Ετικέτα",
  "valueAxis": "Τιμή",
  "minPeriod": "Ελάχιστη περίοδος",
  "automatic": "Αυτόματα",
  "periodsWithOutRecords": "Περίοδοι χωρίς εγγραφές",
  "nullValue": "Μηδενική τιμή",
  "calculatedAsZero": "Με υπολογισμό ως μηδέν",
  "ignored": "Με παράβλεψη",
  "maxCategories": "Ανώτατος αριθμός κατηγοριών",
  "useLayerSymbology": "Χρήση συμβόλων θεματικού επιπέδου",
  "hollowsize": "Μέγεθος κοιλώματος",
  "splitField": "Διαιρεμένο πεδίο",
  "parsingperiodTip": "Αποτυχία υπολογιστικής λειτουργίας. Πάρα πολλά χρονικά διαστήματα λόγω σύντομης περιόδου ανάλυσης.",
  "manyCategoryTip": "Αποτυχία προβολής γραφήματος. Πάρα πολλές κατηγορίες.",
  "setColor": "Ορισμός χρώματος",
  "setTheColorOf": "Ύστερα καθορίστε το χρώμα για",
  "setTheColorAs": "Ύστερα καθορίστε το χρώμα ως",
  "ifStr": "Εάν",
  "as": "Ως",
  "is": "είναι",
  "isNot": "δεν είναι",
  "barCluster": "συστάδα από ράβδους",
  "individualBar": "μεμονωμένη ράβδος",
  "allOthers": "Όλα τα άλλα",
  "category": "Κατηγορία",
  "indicatorSum": "ΑΘΡ.",
  "indicatorAve": "Μ.Ο.",
  "indicatorMax": "ΜΕΓ.",
  "indicatorMin": "ΕΛΑΧ.",
  "setCorrectyIndicatorTip": "Καθορίστε σωστά τους δείκτες.",
  "dataRange": "Εύρος δεδομένων",
  "targetValue": "Τιμή προορισμού",
  "currentValue": "Τρέχουσα τιμή",
  "gaugeColor": "Χρώμα μέτρησης",
  "min": "Ελάχιστο",
  "max": "Μέγιστο",
  "displayValueIn": "Εμφάνιση τιμής σε",
  "noData": "Δεν υπάρχουν δεδομένα",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "Μ",
  "billionAbbreviation": "G",
  "warning": "Προειδοποίηση",
  "noSettingWaring1": "Κάντε κλικ σε ένα στοιχείο, για να ορίσετε τις ιδιότητές του.",
  "noSettingWaring2": "Σύρετε για αλλαγή μεγέθους ή ανακατάταξή ενός στοιχείου.",
  "donNotShowAgain": "Να μην εμφανιστεί ξανά",
  "changeTemplateWarning": "Θα διαγραφούν όλες οι ρυθμίσεις σας και θα ανοίξει ένα νέο, κενό πρότυπο.",
  "requiredFieldWarning": "Αυτή η τιμή είναι απαιτούμενη:",
  "dataSourceNotSet": "Ορίστε προέλευση δεδομένων.",
  "addIndicatorTip": "Προσθήκη δείκτη",
  "chooseTemplatePopupTitle": "Επιλέξτε πρότυπο",
  "filterExtentTipWithaTag": "Μπορείτε να απενεργοποιήσετε το φίλτρο κατά <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Πηγή πρόσθετων δεδομένων</a> κάτω από την καρτέλα «Γνωρίσματα».",
  "filterExtentTip": "Μπορείτε να απενεργοποιήσετε το φίλτρο κατά Πηγή πρόσθετων δεδομένων κάτω από την καρτέλα «Γνωρίσματα».",
  "customColorByCategory": "Προσαρμοσμένο χρώμα κατά κατηγορία",
  "randomColor": "Τυχαίο χρώμα",
  "valueString": "Τιμή",
  "fieldString": "Πεδίο",
  "includeThresholdValue": "Συμπερίληψη τιμής ορίου",
  "percentage": "Ποσοστό",
  "colorSchema": "Χρωματικό σχήμα",
  "addCategory": "Προσθήκη κατηγορίας",
  "clickToEdit": "Κάντε κλικ για επεξεργασία.",
  "nullText": "Null",
  "others": "Άλλα",
  "stringsInTemplate": {
    "name_number": "Αριθμός",
    "name_gauge": "Μέτρηση",
    "name_vertical_gauge": "Κατακόρυφη μέτρηση",
    "name_horizontal_gauge": "Οριζόντια μέτρηση",
    "name_pie": "Πίτα",
    "name_donut": "Ντόνατ",
    "name_bar": "Ράβδος",
    "name_stacked_bar": "Σωρευμένη ράβδος",
    "name_percentage_stacked_bar": "Ποσοστό σωρευμένης ράβδου",
    "name_column": "Στήλη",
    "name_stacked_column": "Σωρευμένη στήλη",
    "name_percentage_stacked_column": "Ποσοστό σωρευμένης στήλης",
    "name_line": "Γραμμή",
    "name_area": "Εμβαδόν",
    "name_stacked_area": "Σωρευμένη περιοχή",
    "name_percentage_stacked_area": "Ποσοστό σωρευμένης περιοχής",
    "titleOfTheInfographic": "ΤΙΤΛΟΣ ΓΡΑΦΙΚΗΣ ΑΝΑΠΑΡΑΣΤΑΣΗΣ ΔΕΔΟΜΕΝΩΝ",
    "description": "Περιγραφή: πρόσθετες πληροφορίες για αυτό το γράφημα πληροφοριών."
  }
});