define({
  "tabs_section_Label": "Zavihki",
  "addTab": "Dodaj zavihek",
  "layerName": "Sloj",
  "layerType": "Tip analize",
  "layerLabel": "Napis",
  "actions": "Dejanja",
  "closest": "Najbližji geoobjekt",
  "proximity": "Bližina",
  "summary": "Povzetek",
  "select_lbl": "-- Izberite --",
  "general_setting_Label": "Splošne nastavitve",
  "units_text_lbl": "Enote razdalje",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "maximum_distance_lbl": "Maksimalna razdalja najbližjega geoobjekta",
  "buffer_text_lbl": "Napis obrisa",
  "buffer_lbl": "Razdalja obrisa",
  "buffer_max_lbl": "Maksimalna razdalja obrisa",
  "buffer_min_lbl": "Minimalna razdalja obrisa",
  "routing_checkBox": "Omogoči usmerjanje",
  "weather_Label": "Možnosti vremena",
  "weather_checkBox": "Vključite vremenske podatke",
  "weather_celsius": "Celziji-Kilometri",
  "selectLayers": "Izberite vremenske sloje",
  "currentlySelectedLayer": "Trenutno izbrani vremenski sloji",
  "missingTabLabel": "Vsaj enemu zavihku manjka napis",
  "cancel": "Prekliči",
  "ok": "V redu",
  "missingLayerInWebMap": "Operativnih slojev ni mogoče najti.",
  "selectFields": "Izberite polja",
  "addField": "Dodaj polje",
  "sum": "VSOTA",
  "min": "MIN",
  "max": "MAKS",
  "avg": "POVPREČJE",
  "count": "ŠTEVEC",
  "area": "OBMOČJE",
  "length": "DOLŽINA",
  "count_checkBox": "Pokaži število",
  "area_checkBox": "Pokaži površino",
  "length_checkBox": "Pokaži dolžino",
  "max_records": "Dosežena maksimalna omejitev",
  "disable_checkBox": "Onemogoči upravljanje vidnosti sloja",
  "optional_lbl": "Napisi po meri",
  "incident_lbl": "Incident",
  "locate_lbl": "Lociraj incident"
});