define({
  "queries": "استعلامات",
  "addNew": "إضافة جديد",
  "newQuery": "استعلام جديد",
  "queryLayer": "طبقة الطبقة",
  "setSource": "تعيين",
  "setDataSource": "تعيين مصدر البيانات",
  "name": "الاسم",
  "querySource": "مصدر البيانات",
  "queryName": "اسم المهمة",
  "queryDefinition": "تعريف عامل التصفية",
  "resultsSetting": "إعداد النتائج",
  "symbolSetting": "إعداد الرمز",
  "resultSettingTip": "تعريف ماهية وكيفية عرض النتائج المُخرَجة.",
  "resultItemTitle": "عنوان كل عنصر من العناصر الناتجة",
  "resultItemContent": "ستُعرض البيانات الجدولية للحقل",
  "fieldsSetTip": "قم بالتأشير على الحقول المُراد عرضها. حدد الحقل لتحديث اسمه المستعار وترتيبه وتنسيقه.",
  "addField": "إضافة حقل",
  "visibility": "إمكانية الرؤية",
  "alias": "الاسم المستعار",
  "specialType": "نوع خاص",
  "actions": "إجراءات",
  "none": "لا شيء",
  "link": "ارتباط",
  "image": "صورة",
  "noField": "لا توجد حقول",
  "operationalLayerTip": "إضافة النتيجة كطبقة تشغيلية",
  "setLayerSymbolTip": "تعيين الرمز لنتائج الاستعلام: ",
  "setSelectedSymbolTip": "حدد رمز المعالم المحددة.",
  "notUseFilter": "لا يتم استخدام عوامل التصفية",
  "setSourceTip": "يرجى تعيين مصدر الاستعلام.",
  "setFilterTip": "يرجى تعيين عامل التصفية بشكل صحيح.",
  "ok": "موافق",
  "cancel": "إلغاء الأمر",
  "noFilterTip": "بدون تعريف تعبير عوامل التصفية، ستقوم هذه المهمة بإدراج جميع المعالم في مصدر البيانات المًحدد.",
  "relationships": "علاقات",
  "addRelationshipLayer": "إضافة علاقة جديدة",
  "relatedTo": "متصل بـ",
  "selectOption": "يرجى تحديد...",
  "resultItemSorting": "فرز العنصر الناتج",
  "field": "حقل",
  "sortingOrder": "ترتيب",
  "configureFieldsTip": "يرجى تكوين الحقول التي سيتم فرز الاستعلام حسبها.",
  "setSortingFields": "تعيين فرز الحقول",
  "ascending": "تصاعدي",
  "descending": "تنازليًا",
  "sortBy": "الفرز حسب",
  "thenBy": "بعد ذلك",
  "addTask": "إضافة مهمة",
  "noTasksTip": "لم يتم تكوين أي استعلامات. انقر على \"${newQuery}\" لإضافة استعلام جديد.",
  "infoText": "معلومات",
  "filters": "عوامل تصفية",
  "results": "النتائج",
  "optionsText": "خيارات",
  "summaryText": "الملخص",
  "attributeFilter": "عامل تصفية البيانات الجدولية",
  "attributeFilterTip": "تعريف تعبيرات البيانات الجدولية للاستخدام في عنصر واجهة الاستخدام لتصفية طبقة الاستعلام.",
  "defineWhereClause": "عرّف عبارة where للاستعلام.",
  "noExpressionDefinedTip": "لم يتم تعريف أي تعبير، وسيتم إرجاع كل السجلات.",
  "setExpressions": "تعيين التعبيرات",
  "spatialFilter": "عوامل التصفية المكانية",
  "spatialFilterTip": "اختر عوامل التصفية المكانية التي ستتوفر للمستخدمين النهائيين.",
  "defaultOption": "الافتراضي",
  "useCurrentExtentTip": "قم فقط بإرجاع المعالم ضمن مدى الخريطة الحالي",
  "useDrawGraphicTip": "لا يُرجِع إلا المعالم التي تتقاطع مع الشكل المرسوم على الخريطة",
  "useFeaturesTip": "قم فقط بإرجاع المعالم ذات العلاقة المكانية مع المعالم في طبقة أخرى",
  "noSpatialLimitTip": "قم بإرجاع المعالم ضمن المدى الكامل للخريطة",
  "drawingTools": "اختر أدوات الرسم",
  "bufferSettings": "تمكين خيار المخزن الاحتياطي",
  "defaultDistance": "المسافة الافتراضية",
  "bufferDistance": "مسافة النطاق",
  "defaultUnit": "الوحدة الافتراضية",
  "miles": "ميل",
  "kilometers": "كيلومترات",
  "feet": "قدم",
  "meters": "متر",
  "yards": "ياردة",
  "nauticalMiles": "أميال بحرية",
  "availableSpatialRelationships": "اختر قواعد العلاقة المكانية",
  "setSpatialRelationships": "تعيين العلاقات المكانية",
  "availability": "التوفر",
  "relationship": "علاقة",
  "label": "التسمية",
  "intersect": "intersect",
  "contain": "contain",
  "areContainedIn": "يتم تضمينها في",
  "cross": "تقاطع",
  "envelopeIntersect": "تقاطع المُغلف",
  "overlap": "تراكب",
  "areOverlapped": "تم التراكب",
  "touch": "لمس",
  "within": "ضمن",
  "areWithin": "ضمن",
  "indexIntersect": "تقاطع الفهرس",
  "itemTitle": "عنوان العنصر",
  "displayFields": "عرض الحقول",
  "sortingFields": "فزر العناصر الناتجة",
  "setDisplayFields": "تعيين حقول العرض",
  "symbol": "رمز",
  "setSymbol": "استخدام رمز مخصص",
  "changeSymbolAtRuntime": "السماح بتغيير الرمز في وقت التشغيل",
  "serviceSymbolTip": "استخدام الرموز المُعرفة بواسطة الطبقة",
  "exportTip": "السماح بتصدير النتائج",
  "keepResultsTip": "الحفاظ على نتائج الخريطة بعد غلق عنصر واجهة الاستخدام",
  "queryRelatedRecords": "الاستعلام عن التسجيلات المرتبطة",
  "createLayerForTaskTip": "حدد كيف تقوم مهمة الاستعلام بإنشاء طبقات",
  "oneLayerForTaskTip": "استبدل الطبقة في كل مرة يتم فيها تنفيذ الاستعلام",
  "multipleLayerForTaskTip": "أنشئ طبقة جديدة في كل مرة يتم فيها تنفيذ الاستعلام",
  "makeDefault": "اجعلها افتراضية",
  "icon": "أيقونة",
  "newTask": "مهمة جديدة",
  "addTaskTip": "أضف استعلام أو أكثر إلى عنصر واجهة المستخدم وقم بتكوين معلمات كل منها.",
  "webMapPopupTip": "استخدم تكوين العنصر المنبثق للطبقة في خريطة الويب",
  "customPopupTip": "قم بتكوين المحتوى المُخصص",
  "showResultsSetActions": "اعرض أحداث مجموعة النتائج",
  "zoomTo": "تكبير/تصغير إلى",
  "openAttributeTable": "عرض في جدول البيانات",
  "content": "المحتوى",
  "displaySQLTip": "اعرض تعبير SQL للمستخدمين النهائيين",
  "useLayerDefaultSymbol": "استخدم رمز افتراضي للطبقة",
  "setCustomIcon": "قم بتعيين أيقونة مُخصصة",
  "layerDefaultSymbolTip": "استخدم رمز افتراضي للطبقة",
  "uploadImage": "قم بتحميل صورة",
  "attributeCriteira": "معايير البيانات الجدولية",
  "specifyFilterAtRuntimeTip": "سيحتاج المستخدمون إلى تحديد معلمات لهذا التعبير.",
  "value": "قيمة",
  "hideLayersTip": "إيقاف تشغيل الطبقات الناتجة للاستعلام عند إغلاق عنصر واجهة المستخدم.",
  "tabLabels": "تسميات علامة التبويب",
  "tasks": "المهام",
  "queryCriteira": "معايير الاستعلام",
  "allowCustomQuery": "السماح بإنشاء استعلام مخصص"
});