define({
  "_widgetLabel": "निर्देशांक रूपांतरण",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "दशमलव डिग्री - अक्षांश/देशांतर",
  "DDLongLatNotation": "दशमलव डिग्री - देशांतर/अक्षांश",
  "DDMLatLongNotation": "दशमलव डिग्री मिनट - अक्षांश/देशांतर",
  "DDMLongLatNotation": "दशमलव डिग्री मिनट - देशांतर/अक्षांश",
  "DMSLatLongNotation": "दशमलव डिग्री सेकंड - देशांतर/अक्षांश",
  "DMSLongLatNotation": "दशमलव डिग्री सेकंड - अक्षांश/देशांतर",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - बैंड लेटर",
  "UTMHemNotation": "UTM - गोलार्ध (N/S)",
  "formatInput": "फ़ॉर्मेट आउटपुट",
  "copyAll": "सभी की प्रति बनाएं",
  "copySuccessful": "सफलतापूर्वक प्रति बनाया गया",
  "copyFailed": "प्रति बनाने में सक्षम नहीं। ctrl+c को विकल्प के तौर पर इस्तेमाल करें।",
  "parseCoordinatesError": "निर्देशांकों की व्याख्या करने में सक्षम नहीं। कृपया अपना इनपुट जांचें।",
  "comfirmInputNotation": "इनपुट नोटेशन की पुष्टि करें",
  "latLongWarningMessage": "इनपुट निर्देशांक को अक्षांश या अक्षांश मान के लिए उपसर्ग और प्रत्यय दोनों के रूप में पाया गया है, वापसी निर्देशांक उपसर्ग पर आधारित है।",
  "inputLabel": "इनपुट",
  "outputLabel": "आउटपुट",
  "cancelButtonLabel": "रद्द करें",
  "applyButtonLabel": "लागू करें",
  "posNegPrefixLabel": "धनात्मक और ऋणात्मक संख्याओं में उपसर्ग के तौर पर \"+/-\" जोड़ें",
  "editCoordinateDialogTitle": "निर्देशांक फ़ॉर्मेट स्ट्रिंग को सेट करें",
  "rememberDecisionLabel": "मेरा निर्णय याद रखें और दोबारा न पूछें।<br/>",
  "coordinateInputLabel": "निर्देशांक दर्ज करने या मानचित्र पर क्लिक करें",
  "zoomLabel": "ज़ूम करें",
  "multipleNotationLabel": "वे नोटेशन मिले जो आपके इनपुट से मेल खाते हैं। कृपया जिसका आप इस्तेमाल करना चाहते हैं उसकी पुष्टि करें:",
  "copyToClipboard": "क्लिपबोर्ड पर कॉपी करें",
  "formatOutput": "फ़ॉर्मेट आउटपुट",
  "addNewNotation": "नया नोटेशन जोड़ें",
  "notationAddedMessage": "नए नोटेशन जोड़े गए",
  "addLabel": "जोड़ें",
  "removeCoordinate": "निर्देशांक हटाएं",
  "expandOutput": "आउटपुट विस्तारित करें",
  "latitudeLabel": "अक्षांश",
  "longitudeLabel": "देशांतर",
  "quadrantLabel": "चतुर्थांश",
  "keyLabel": "कुंजी",
  "fifteenDegreeLabel": "15Â° का चतुष्कोण",
  "oneDegreeLabel": "1Â° का चतुष्कोण",
  "eastingLabel": "पूर्व की ओर",
  "northingLabel": "उत्तर की ओर",
  "zoneLabel": "क्षेत्र",
  "bandLabel": "बैंड",
  "gzdLabel": "GZD",
  "gridSquareLabel": "ग्रिड का वर्ग",
  "hemisphereLabel": "गोलार्ध"
});