define({
  "tabs_section_Label": "Tab",
  "addTab": "Tambahkan Tab",
  "layerName": "Layer",
  "layerType": "Tipe Analisis",
  "layerLabel": "Label",
  "actions": "Tindakan",
  "closest": "Fitur Terdekat",
  "proximity": "Kedekatan",
  "summary": "Ringkasan",
  "select_lbl": "-- Pilih --",
  "general_setting_Label": "Pengaturan Umum",
  "units_text_lbl": "Unit Jarak",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil Laut",
  "maximum_distance_lbl": "Jarak Maksimal Fitur Terdekat",
  "buffer_text_lbl": "Label Buffer",
  "buffer_lbl": "Jarak Buffer",
  "buffer_max_lbl": "Jarak Buffer Maksimal",
  "buffer_min_lbl": "Jarak Buffer Minimal",
  "routing_checkBox": "Aktifkan Perutean",
  "weather_Label": "Opsi Cuaca",
  "weather_checkBox": "Sertakan Informasi Cuaca",
  "weather_celsius": "Celsius-Kilometer",
  "selectLayers": "Pilih Layer Cuaca",
  "currentlySelectedLayer": "Layer cuaca yang saat ini dipilih",
  "missingTabLabel": "Setidaknya satu tab tidak mempunyai label",
  "cancel": "Batal",
  "ok": "Ya",
  "missingLayerInWebMap": "Tidak ditemukan layer operasional.",
  "selectFields": "Pilih Kolom",
  "addField": "Tambahkan Kolom",
  "sum": "SUM",
  "min": "MIN",
  "max": "MAKS",
  "avg": "AVG",
  "count": "COUNT",
  "area": "AREA",
  "length": "PANJANG",
  "count_checkBox": "Tampilkan Jumlah",
  "area_checkBox": "Tampilkan Area",
  "length_checkBox": "Tampilkan Panjang",
  "max_records": "Batas maksimal tercapai",
  "disable_checkBox": "Nonaktifkan manajemen visibilitas layer",
  "optional_lbl": "Label Opsional",
  "incident_lbl": "Insiden",
  "locate_lbl": "Cari Lokasi Insiden"
});