define({
  "chartTasks": "Grafik görevleri",
  "addNew": "Yeni ekle",
  "addNewTip": "Yeni bir grafik görevi ekle",
  "name": "Ad",
  "set": "Ayarla",
  "setDataSource": "Veri kaynağını ayarla",
  "generalSettingsTip": "Grafikler için veri kaynağı, başlık ve açıklama belirtin.",
  "chartModeSettingTip": "Veriyi grafik olarak analiz edip görüntüleme yöntemini belirleyin.",
  "detailsSettingTip": "Türünü, rengini ve hangi değerlerin grafiğe döküleceğini belirterek grafik görünümünü ayarlayın:",
  "symbolSettingTip": "Grafiğe dökülen veri için harita gösterimini ayarlayın.",
  "addFilterTip": "Bu verilere filtre ekle",
  "dataSource": "Veri Kaynağı",
  "noResults": "Detay bulunamadı.",
  "chartTitle": "Grafik başlığı",
  "description": "Açıklama",
  "chartingMode": "Grafik gösterimi",
  "featureOption": "Değerleri özelliğe göre görüntüle",
  "categoryOption": "Değerleri kategoriye göre görüntüle",
  "countOption": "Özellik sayımlarını kategoriye göre görüntüle",
  "fieldOption": "Öznitelik değerlerini grafik olarak görüntüle",
  "category": "Kategori",
  "axisLabel": "Kategori etiketi",
  "categoryField": "Kategori alanı",
  "operation": "İşlem",
  "originalOption": "Orijinal değerleri kullan",
  "sumOption": "Toplam",
  "averageOption": "Ortalama",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "valueFields": "Değer alanları",
  "moveUp": "Yukarı taşı",
  "moveDown": "Aşağı taşı",
  "sortOrder": "Grafik sırasını kategori etiketleriyle sırala",
  "ascending": "Artan",
  "descending": "Azalan",
  "chartType": "Grafik türü",
  "column": "Sütun grafiği",
  "bar": "Çubuk grafik",
  "line": "Çizgi grafik",
  "pie": "Pasta grafik",
  "chartColor": "Grafik rengi",
  "showDataLabels": "Veri etiketlerini göster",
  "setSymbol": "Seçim sembolü",
  "setHighLightColor": "Rengi vurgula",
  "settings": "Ayarlar",
  "mapInterationOptions": "Harita etkileşim seçenekleri",
  "preview": "Önizleme",
  "ok": "Tamam",
  "cancel": "İptal",
  "close": "Kapat",
  "setFilterTip": "Filtreyi düzgün ayarlayın. ",
  "setChartTitleTip": "Grafik başlığını ayarlayın.",
  "setChartTypeTip": "En az bir grafik türü seçin.",
  "setDataFieldTip": "En az bir değer alanı seçin.",
  "setOutputFieldTip": "Çıktı alanlarını belirtin.",
  "count": "Sayım",
  "label": "Etiket",
  "horizontalAxis": "Yatay eksen",
  "verticalAxis": "Dikey eksen",
  "dataLabels": "Veri etiketleri",
  "color": "Renk",
  "colorful": "Renkli",
  "monochromatic": "Monokromatik",
  "noTaskTip": "Grafik görevi eklemek için Yeni ekle ögesine tıklayın.",
  "info": "Bilgi",
  "charts": "Grafikler",
  "options": "Seçenekler",
  "taskName": "Görev adı",
  "summary": "Özet",
  "resultDescription": "Sonuç açıklaması",
  "spatialFilterTip": "Sonuçları daraltmak için araçta kullanılacak mekansal filtreleri seçin.",
  "defaultOption": "Varsayılan",
  "useCurrentExtentTip": "Kısmen veya tamamen geçerli harita yayılımında",
  "useDrawGraphicTip": "Kısmen veya tamamen haritada çizilen şekil içinde",
  "useFeaturesTip": "Başka bir katmandaki detaylara göre konumlarına dayanarak",
  "noSpatialLimitTip": "Sonuçları mekansal olarak sınırlama",
  "drawingTools": "Çizim araçları",
  "bufferSettings": "Tampon ayarları",
  "defaultDistance": "Varsayılan mesafe",
  "bufferDistance": "Tampon mesafesi",
  "defaultUnit": "Varsayılan birim",
  "miles": "Mil",
  "kilometers": "Kilometre",
  "feet": "Fit",
  "meters": "Metre",
  "yards": "Yarda",
  "nauticalMiles": "Deniz mili",
  "availableSpatialRelationships": "Kullanılabilir mekansal ilişkiler",
  "setSpatialRelationships": "Mekansal ilişkileri ayarla",
  "availability": "Yararlanırlık",
  "relationship": "İlişki",
  "actions": "İşlemler",
  "intersect": "kesişen",
  "contain": "içeren",
  "areContainedIn": "içinde bulunuyor",
  "cross": "çapraz",
  "envelopeIntersect": "zarf kesişmesi",
  "overlap": "örtüşme",
  "areOverlapped": "örtüşüyor",
  "touche": "dokunma",
  "within": "birliktelik",
  "areWithin": "birlikte",
  "indexIntersect": "dizin kesişmesi"
});