define({
  "enableUndoRedo": "Aktivera Ångra/Upprepa",
  "toolbarVisible": "Verktygsfält synligt",
  "toolbarOptions": "Alternativ för verktygsfält",
  "mergeVisible": "Sammanfoga",
  "cutVisible": "Beskär",
  "reshapeVisible": "Omforma",
  "back": "Bakåt",
  "label": "Lager",
  "edit": "Redigerbar",
  "update": "Inaktivera Uppdatera geometri",
  "fields": "Fält",
  "actions": "Åtgärder",
  "editpageName": "Namn",
  "editpageAlias": "Alias",
  "editpageVisible": "Synlig",
  "editpageEditable": "Redigerbar",
  "noLayers": "Inga redigerbara geoobjektslager är tillgängliga",
  "configureFields": "Konfigurera lagerfält",
  "useFilterEdit": "Använd mallfilter för geoobjekt",
  "display": "Visa",
  "autoApplyEditWhenGeometryIsMoved": "Använd redigeringen automatiskt när geometrin flyttas",
  "snappingTolerance": "Ange snappningstoleransen i pixlar",
  "popupTolerance": "Ange toleransen för attributredigeringspopupen i pixlar",
  "stickyMoveTolerance": "Ange toleransen för klistrig flytt i pixlar",
  "usingSaveButton": "Tillämpa inte redigeringar på attributen förrän du klickar på knappen Spara"
});