define({
  "_widgetLabel": "घटना विश्लेषण",
  "_featureAction_SetAsIncident": "घटना के रूप में सेट करें",
  "incident": "घटना",
  "weather": "मौसम",
  "locate_incident": "घटना का पता लगाएं",
  "clear_incidents": "घटनाओं को साफ करें",
  "reverse_geocoded_address": "निकटतम पता",
  "reverse_geocoded_error": "उपलब्ध नहीं है",
  "miles": "मील",
  "kilometers": "किलोमीटर",
  "feet": "फ़ीट",
  "meters": "मीटर",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "now": "अब",
  "wind": "हवा",
  "SUN": "रवि",
  "MON": "सोम",
  "TUE": "मंगल",
  "WED": "बुध",
  "THU": "गुरु",
  "FRI": "शुक्र",
  "SAT": "शनि",
  "defaultTabMsg": "किसी घटना को पहचाना नहीं गया है।",
  "useMapExtent": "वर्तमान मानचित्र सीमा का उपयोग करें।",
  "noFeaturesFound": "किसी भी फीचर को खोजा नहीं गया है।",
  "downloadCSV": "CSV डाउनलोड करें",
  "sum": "योग",
  "min": "न्यूनतम",
  "max": "अधिकतम",
  "avg": "औसत",
  "count": "गणना",
  "area": "क्षेत्रफल",
  "length": "लंबाई"
});