define({
  "add": "Faceţi clic pentru a adăuga nou",
  "title": "Titlu",
  "placeholderBookmarkName": "Nume marcaj",
  "ok": "OK",
  "cancel": "Anulare",
  "warning": "Finalizaţi editarea!",
  "edit": "Editare semn de carte",
  "errorNameExist": "Marcajul există!",
  "errorNameNull": "Nume marcaj nevalid!",
  "addBookmark": "Creare nouă",
  "thumbnail": "Miniatură",
  "thumbnailHint": "Faceţi clic pe imagine pentru a o actualiza",
  "displayBookmarksAs": "Afișare semne de carte drept",
  "cards": "Cartele",
  "list": "Listare",
  "cardsTips": "Vizualizare card",
  "listTips": "Vizualizare tip listă",
  "makeAsDefault": "Setare ca implicit",
  "default": "Implicit",
  "editable": "Permite adăugarea de semne de carte în widget.",
  "alwaysSync": "Afișare semne de carte de pe harta web",
  "configCustom": "Afișare semne de carte personalizate",
  "import": "Import",
  "create": "Creare",
  "importTitle": "Importare semne de carte",
  "importFromWeb": "Importare semne de carte de pe harta web curentă",
  "selectAll": "Selectare toate",
  "noBookmarkInConfig": "Faceți clic pe â€œImportâ€ sau pe â€œCreate Newâ€ pentru a adăuga semne de carte.",
  "noBookmarkInWebMap": "Nu este configurat niciun semn de carte pe hartă.",
  "extent": "Extindere",
  "saveExtent": "Salvare extindere hartă pentru acest semn de carte",
  "savelayers": "Salvaţi vizibilitatea stratului tematic",
  "withVisibility": "Cu vizibilitatea stratului tematic",
  "bookmark": "Semn de carte",
  "addBtn": "Adăugare",
  "deleteBtn": "Ştergere",
  "editBtn": "Editare",
  "dragReorderTip": "Menținere și decalare pentru reordonare",
  "deleteBtnTip": "Ștergere semn de carte",
  "editBtnTip": "Editare semn de carte"
});