define({
  "_widgetLabel": "Grafikon",
  "executeChartTip": "Kliknite enega od naslednjih elementov nalog za izvedbo grafikona.",
  "invalidConfig": "Neveljavna konfiguracija.",
  "noneChartTip": "Opravilo grafikona ni konfigurirano za ta pripomoček",
  "chartParams": "Možnosti",
  "charts": "GRAFIKONI",
  "apply": "UPORABI",
  "useSpatialFilter": "Uporabi prostorski filter za omejitev geoobjektov",
  "useCurrentMapExtent": "Samo geoobjekti, ki sekajo trenutno območje karte",
  "drawGraphicOnMap": "Samo geoobjekti, ki sekajo območje, ki ga je določil uporabnik",
  "chartResults": "Rezultati grafikona",
  "clearResults": "Počisti rezultate",
  "noPermissionsMsg": "Za dostop do te storitve nimate dovoljenj.",
  "specifySpatialFilterMsg": "Določite prostorski filter za to nalogo.",
  "queryError": "Poizvedba ni uspela.",
  "noResults": "Geoobjekta ni mogoče najti.",
  "category": "Kategorija",
  "count": "Števec",
  "label": "Napis",
  "horizontalAxis": "Horizontalna os",
  "verticalAxis": "Vertikalna os",
  "dataLabels": "Napisi podatkov",
  "color": "Barva",
  "colorful": "Pisano",
  "monochromatic": "Enobarvno",
  "tasks": "Opravila",
  "results": "Rezultati",
  "applySpatialFilterToLimitResults": "Za omejitev rezultatov uporabi prostorski filter",
  "useCurrentExtentTip": "Delno ali v celoti znotraj trenutnega obsega karte",
  "useDrawGraphicTip": "Delno ali v celoti znotraj oblike, narisane na karti",
  "useFeaturesTip": "Glede na njihove lokacije, relativno na geoobjekte v drugem sloju",
  "noSpatialLimitTip": "Rezultatov ne omejuj prostorsko",
  "applySearchDistance": "Uporabite iskalno razdaljo.",
  "spatialRelationship": "Prostorska relacija",
  "relatedLayer": "Relacijski sloj",
  "clear": "Počisti",
  "bufferDistance": "Razdalja obrisa",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Čevlji",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Morske milje",
  "back": "Nazaj",
  "execute": "Uporabi"
});