define({
  root: ({
    labelBookmarkName: "Bookmark the current view",
    labelPlay: "Play all",
    labelStop: "Stop",
    labelDelete: "Delete",
    placeholderBookmarkName: "Bookmark name",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!",

    editTip: "Edit bookmarks",
    exitEditTip: "Exit editing mode",
    syncTip: "Synchronize",
    cardsTips: "Grid view",
    listTips: "List view",

    addBtn: "Add",
    deleteBtn: "Delete",
    changeThumbnailTip: "Change thumbnail",
    dragReorderTip: "Hold and drag to reorder",
    deleteBtnTip: "Delete the bookmark",
    editBtnTip: "Edit the bookmark",
    withVisibility: "With layer visibility",

    searchBookmark: "Search",

    bookmarksFromConfig: "Preconfigured bookmarks",
    bookmarksFromCache: "Local temporary bookmarks",

    notice: "Notice",
    changeNoticeTips: "Changes will be saved only in your browser’s cache. Sync between the widget and its configuration is disconnected once you make modifications.",
    syncNoticeTips: "This will erase all your modifications and restore the configured bookmarks.",    
    dontShowAgain: "Don’t show again",

    saveVisibility: "Save layer visibility",

    _widgetLabel: "Bookmark"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
