define({
  "serviceUrl": "Задать URL сервиса:",
  "minIntSpacingLabel": "Минимальный размер сетки",
  "lineOpacityLabel": "Непрозрачность линии",
  "labelOpacityLabel": "Непрозрачность подписи",
  "centerLabelOpacityLabel": "Непрозрачность центральной подписи",
  "gridZonePlacementLabel": "Размещение подписи зоны сетки",
  "verticalLineLabels": "Подписи вертикальных линий",
  "styleHeaderLabel": "Стиль",
  "indexHeaderLabel": "Компонент сетки",
  "colorHeaderLabel": "Цвет",
  "fontSizeHeaderLabel": "Размер шрифта",
  "lineWidthHeaderLabel": "Ширина линии",
  "horizontalLabel": "Горизонтальная",
  "verticalLabel": "Вертикальная",
  "upperLeftLabel": "Верхний левый",
  "upperRightLabel": "Верхний правый",
  "lowerLeftLabel": "Нижний левый",
  "lowerRightLabel": "Нижний правый",
  "centerLabel": "По центру",
  "errorMessage": "Страница настройки содержит ошибки. Исправьте их перед сохранением.",
  "checkBoxLabel": "Показать сетку, когда виджет закрыт",
  "checkBoxLabelDashboard": "Показать сетку",
  "gzd": "Указатель зоны сетки (GZD)",
  "gsid": "Идентификация 100 000-метрового квадрата сетки (GSID)",
  "grid10k": "Линии 10 000-метровой сетки",
  "grid1k": "Линии 1 000-метровой сетки",
  "grid100m": "Линии 100-метровой сетки",
  "grid10m": "Линии 10-метровой сетки",
  "switchBasemap": "Переключить базовую карту"
});