define({
  "_widgetLabel": "Guide d’intervention d’urgence",
  "ergMainPageTitle": "Basé sur le guide d’intervention d’urgence de 2016",
  "coordInputLabelStart": "Point de déversement (DD)",
  "coordInputLabel": "Point de déversement",
  "addPointToolTip": "Ajouter un point de déversement",
  "drawPointToolTip": "Cliquer pour ajouter un point de déversement",
  "material": "Matériel",
  "materialPlaceholder": "Commencez à taper pour rechercher un matériau",
  "table3Message": "Le matériau que vous avez sélectionné requiert des informations complémentaires si vous gérez un déversement de grande taille.\n\nVérifiez que vous avez sélectionné les valeurs appropriées pour la vitesse du vent et le container de transport.",
  "table2Message": "Le matériau que vous avez sélectionné peut provoquer une forte quantité de gaz toxique une fois déversé dans l’eau.\n\nVous pouvez utiliser les matériaux suivants :\n\n",
  "spillSize": "Taille du déversement",
  "small": "Petite",
  "large": "Grande",
  "fireLabel": "Afficher la zone d’isolation d’incendie",
  "weatherLabel": "Météo actuelle au point de déversement",
  "weatherIntialText": "<br />Mise à jour une fois le déversement géolocalisé",
  "temperature": "Température",
  "wind": "Vent",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informations météo non obtenues. Mettre à jour manuellement les valeurs Vitesse du vent et Heure du déversement",
  "windDirection": "Direction du vent (direction dans laquelle le vent souffle)",
  "timeOfSpill": "Heure du déversement",
  "day": "Jour",
  "night": "Nuit",
  "windSpeed": "Vitesse du vent",
  "low": "Basse",
  "moderate": "Modéré",
  "high": "Elevée",
  "transportContainer": "Container de transport",
  "rail": "Wagon-citerne",
  "semi": "Camion-citerne",
  "mton": "Cuves de plusieurs tonnes",
  "ston": "Plusieurs cuves de petite taille ou une cuve d’une capacité d’une tonne",
  "ag": "Réservoir ravitailleur agricole",
  "msm": "Plusieurs cuves de petite taille",
  "bleveLabel": "Afficher la zone d’isolation du BLEVE",
  "capacity": "Capacité du container (litres)",
  "bleveMessage": "Pour le matériau que vous avez sélectionné, une distance d’évacuation supplémentaire peut apparaître pour le BLEVE.\n\nPour ce faire, activez le commutateur Afficher la zone d’isolation du BLEVE et sélectionnez la capacité appropriée du container.",
  "noPAZoneMessage": "Aucune distance Action de protection n’est définie pour ce matériau. Seules les zones d’isolation et d’évacuation initiales ont été calculées",
  "settingsTitle": "Réglages",
  "spillLocationLabel": "Point de déversement",
  "spillLocationButtonLabel": "Configurer les paramètres du point de déversement",
  "IISettingsLabel": "Zone d’isolation initiale",
  "IIButtonLabel": "Configurer les paramètres de l’isolation initiale",
  "PASettingsLabel": "Zone d’action de protection",
  "PAButtonLabel": "Configurer les paramètres d’action de protection",
  "downwindSettingsLabel": "Zone dans la direction du vent",
  "downwindButtonLabel": "Configurer les paramètres de la direction du vent",
  "fireSettingsLabel": "Zone d’isolation d’incendie",
  "fireButtonLabel": "Configurer les paramètres d’isolation d’incendie",
  "bleveSettingsLabel": "Zone d’isolation du BLEVE",
  "bleveButtonLabel": "Configurer les paramètres du BLEVE",
  "style": "Style",
  "lineStyles": {
    "esriSLSDash": "Tiret",
    "esriSLSDashDot": "Tiret-point",
    "esriSLSDashDotDot": "Tiret-point-point",
    "esriSLSDot": "Point",
    "esriSLSLongDash": "Tiret long",
    "esriSLSLongDashDot": "Tiret-point long",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Tiret court",
    "esriSLSShortDashDot": "Tiret court-point",
    "esriSLSShortDashDotDot": "Tiret court-point-point",
    "esriSLSShortDot": "Point court",
    "esriSLSSolid": "Solide"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Arrière",
    "esriSFSCross": "Croiser",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Avant",
    "esriSFSHorizontal": "Horizontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solide",
    "esriSFSVertical": "Verticale"
  },
  "resultsTitle": "Résultats",
  "publishERGBtn": "Publier",
  "ERGLayerName": "Nom de la couche publiée du guide d’intervention d’urgence",
  "invalidERGLayerName": "Le nom de la couche ne doit contenir que des caractères alphanumériques et des tirets du bas",
  "missingERGLayerName": "Vous devez attribuer un nom au guide d’intervention d’urgence",
  "publishingFailedLayerExists": "Échec de la publication : un service d’entités nommé {0} existe déjà. Choisissez un autre nom.",
  "checkService": "Vérifier le service : {0}.",
  "createService": "Créer le service : {0}",
  "unableToCreate": "Impossible de créer : {0}",
  "addToDefinition": "Ajouter à la définition : {0}",
  "successfullyPublished": "La couche web a été publiée{0}Gérer la couche web",
  "userRole": "Impossible de créer le service car l’utilisateur ne dispose pas des autorisations appropriées",
  "transparency": "Transparence",
  "outline": "Contour",
  "fill": "Remplissage (La couleur s’applique uniquement lorsque le style est uni)",
  "createERGBtn": "Créer des zones",
  "clearERGBtn": "Effacer",
  "labelFormat": "Format d’étiquette",
  "helpIconTooltip": "Le seuil entre les petites et grandes tailles de déversement sont :\nLiquides - 55 gallons (208 litres)\nSolides - 60 livres (300 kilogrammes)",
  "cellWidth": "Largeur de cellule (x)",
  "cellHeight": "Hauteur de cellule (y)",
  "invalidNumberMessage": "La valeur saisie n’est pas valide",
  "invalidRangeMessage": "La valeur doit être supérieure à 0",
  "gridAngleInvalidRangeMessage": "La valeur doit être comprise entre -89,9 et 89,9",
  "formatIconTooltip": "Format d'entrée",
  "setCoordFormat": "Définir la chaîne de format des coordonnées",
  "prefixNumbers": "Ajouter le préfixe '+/-' aux nombres positifs et négatifs",
  "cancelBtn": "Annuler",
  "applyBtn": "Appliquer",
  "comfirmInputNotation": "Confirmer la notation entrée",
  "notationsMatch": "notations correspondent à votre entrée. Confirmez celle que vous souhaitez utiliser :",
  "missingLayerNameMessage": "Vous devez saisir un nom de couche valide avant la publication",
  "parseCoordinatesError": "Impossible d'analyser les coordonnées. Vérifiez votre entrée.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Degrés décimaux - Latitude/Longitude",
  "DDLongLatNotation": "Degrés décimaux - Longitude/Latitude",
  "DDMLatLongNotation": "Degrés minutes décimales - Latitude/Longitude",
  "DDMLongLatNotation": "Degrés minutes décimales - Longitude/Latitude",
  "DMSLatLongNotation": "Degrés minutes secondes - Latitude/Longitude",
  "DMSLongLatNotation": "Degrés minutes secondes - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Lettre du canal",
  "UTMHemNotation": "UTM - Hémisphère (N/S)"
});