define({
  "_widgetLabel": "Grafika Gridded Reference Graphic (GRG)",
  "newGRGFromAreaButtonLabel": "Definiuj siatkę na podstawie obszaru",
  "newGRGFromPointButtonLabel": "Definiuj siatkę na podstawie punktu",
  "newGRGFromAreaTitle": "Definiuj siatkę na podstawie obszaru",
  "newGRGFromPointTitle": "Definiuj siatkę na podstawie punktu",
  "newGRGBySizeButtonLabel": "Według wymiaru",
  "newGRGFromRefSystemButtonLabel": "Według systemu odniesienia",
  "newGRGByTimeLabel": "Według czasu i prędkości",
  "newGRGFromNonStandardButtonLabel": "Definiuj siatkę niestandardową",
  "newGRGAreaBySizeTitle": "Grafika GRG na podstawie obszaru według wymiaru",
  "newGRGAreaBySizeDefineAreaLabel": "Obszar grafiki GRG",
  "addGRGAreaPolygonToolTip": "Rysuj obszar grafiki GRG przy użyciu poligonu",
  "addGRGAreaExtentToolTip": "Rysuj obszar grafiki GRG przy użyciu zasięgu",
  "rotation": "Obrót siatki",
  "numberRowsColumnsLabel": "Definiuj liczbę wierszy i kolumn",
  "newGRGAreaByRefSystemTitle": "Grafika GRG na podstawie obszaru według systemu odniesienia",
  "gridSize": "Rozmiar siatki",
  "UTMZoneandBand": "Strefa siatki",
  "100000m": "100 000 metrów",
  "10000m": "10 000 metrów",
  "1000m": "1000 metrów",
  "100m": "100 metrów",
  "10m": "10 metrów",
  "clipGrid": "Przytnij siatkę do obszaru grafiki GRG",
  "newGRGAreaFromNonStandardTitle": "Nowy NRG",
  "newGRGPointBySizeTitle": "Grafika GRG na podstawie punktu według wymiaru",
  "newGRGPointByRefSystemTitle": "Grafika GRG na podstawie punktu według systemu odniesienia",
  "newGRGPointByTimeTitle": "Grafika GRG na podstawie punktu według czasu i prędkości",
  "time": "Czas",
  "rate": "Prędkość",
  "hours": "Godziny",
  "minutes": "Minut(y)",
  "seconds": "Sekundy",
  "ftPerSec": "Stopa / sekunda",
  "ftPerHour": "Stopa / godzina",
  "kmPerSec": "Kilometry / sekunda",
  "kmPerHour": "Kilometry / godzina",
  "mPerSec": "Metry / sekunda",
  "mPerHour": "Metry / godzina",
  "miPerSec": "Mile / sekunda",
  "miPerHour": "Mile / godzina",
  "nMPerSec": "Mile morskie / sekunda",
  "nMPerHour": "Mile morskie / godzina",
  "settingsTitle": "Parametry",
  "labelSettingsLabel": "Ustawienia etykiety",
  "labelSettingsButtonLabel": "Konfiguruj ustawienia etykiety",
  "gridSettingsLabel": "Ustawienia siatki",
  "gridSettingsButtonLabel": "Konfiguruj ustawienia siatki",
  "transparency": "Przezroczystość",
  "labelStyle": "Styl etykiety",
  "font": "Czcionka",
  "textSize": "Wielkość tekstu",
  "textColor": "Kolor tekstu",
  "halo": "Otoczka",
  "show": "Pokaż",
  "lockSettings": "Ustawienia zostały zablokowane przez właściciela aplikacji",
  "gridSettings": {
    "cellShape": "Kształt komórki",
    "cellUnits": "Jednostki komórki",
    "cellOutline": "Ustawienia obrysu komórki",
    "cellFill": "Ustawienia wypełnienia komórki",
    "gridReferenceSystem": "System referencyjny",
    "gridDatum": "Układ odniesienia: WGS84",
    "labelStartPosition": "Punkt zaczepienia etykiety",
    "labelType": "Typ etykiety",
    "labelDirection": "Kierunek etykiety",
    "gridOrigin": "Punkt zaczepienia siatki",
    "default": "Prostokąt",
    "hexagon": "Sześciokąt",
    "miles": "Mile",
    "kilometers": "Kilometry",
    "feet": "Stopy",
    "meters": "Metry",
    "yards": "Jardy",
    "nautical-miles": "Mile morskie",
    "lowerLeft": "Dolny lewy",
    "lowerRight": "Dolny prawy",
    "upperLeft": "Górny lewy",
    "upperRight": "Górny prawy",
    "center": "Środek",
    "alphaNumeric": "Alfanumeryczny",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Numeryczne",
    "horizontal": "Poziomo",
    "vertical": "Pionowo",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Pokaż etykiety"
  },
  "publishTitle": "Publikuj grafikę GRG w portalu",
  "publishGRGBtn": "Publikuj",
  "GRGLayerName": "Nazwa opublikowanej warstwy grafiki GRG",
  "invalidGRGLayerName": "Nazwa pola może zawierać tylko znaki alfanumeryczne i znaki podkreślenia.",
  "missingGRGLayerName": "Należy podać nazwę grafiki GRG",
  "publishingFailedLayerExists": "Publikowanie nie powiodło się: Masz tylko usługę serwisową o nazwie {0}. Wybierz inną nazwę.",
  "checkService": "Sprawdź usługę: {0}",
  "createService": "Utwórz usługę: {0}",
  "unableToCreate": "Nie można utworzyć: {0}",
  "addToDefinition": "Dodaj do definicji: {0}",
  "successfullyPublished": "Pomyślnie opublikowano warstwę internetową{0}Zarządzaj warstwą internetową",
  "userRole": "Nie można utworzyć usługi, ponieważ użytkownik nie ma uprawnień",
  "createGRGBtn": "Utwórz grafikę GRG",
  "clearGRGBtn": "Wyczyść",
  "labelFormat": "Format etykiety",
  "helpIconTooltip": "Z: wyznacznik stref siatki (GZD)\nS: identyfikacja kwadratu siatki o boku 100 000 metrów (GSID)\nX: współrzędna wschodnia (współrzędna X)\nY: współrzędna północna (współrzędna Y)\n\nPrzykłady:\nZSXY ma postać 15SWC8081751205\nZS X,Y ma postać 15SWC 80817,51205",
  "addPointToolTip": "Dodaj punkt zaczepienia grafiki GRG",
  "cellWidth": "Szerokość komórki (x)",
  "cellHeight": "Wysokość komórki (y)",
  "invalidNumberMessage": "Wprowadzona wartość nie jest prawidłowa",
  "invalidRangeMessage": "Wartość musi być większa od 0",
  "gridAngleInvalidRangeMessage": "Wartość musi zawierać się w przedziale od -89,9 do 89,9",
  "formatIconTooltip": "Formatuj dane wejściowe",
  "coordInputLabel": "Punkt zaczepienia grafiki GRG (DD)",
  "setCoordFormat": "Skonfiguruj ciąg znakowy formatu współrzędnych",
  "prefixNumbers": "Dodaj prefiks '+/-' do liczb dodatnich i ujemnych",
  "cancelBtn": "Anuluj",
  "applyBtn": "Zastosuj",
  "comfirmInputNotation": "Potwierdź notację danych wejściowych",
  "notationsMatch": "liczba znalezionych notacji zgodnych z danymi wejściowymi. Wybierz, której notacji chcesz użyć:",
  "numberOfCellsHorizontal": "# Komórki poziome",
  "numberOfCellsVertical": "# Komórki pionowe",
  "gridAngle": "Obrót siatki",
  "tooManyCellsErrorMessage": "Próbujesz utworzyć siatkę składającą się z ponad 2000 komórek. Radzimy zmniejszyć liczbę tworzonych komórek, zmieniając rozmiar siatki lub jej obszar.",
  "missingParametersMessage": "<p>W formularzu tworzenia grafiki GRG brakuje niektórych parametrów lub są one nieprawidłowe. Upewnij się, że:</p><ul><li>Obszar grafiki GRG został wyświetlony.</li><li>Wartości szerokości i wysokości komórki są prawidłowe.</li></ul>",
  "missingOriginParametersMessage": "<p>W formularzu tworzenia grafiki GRG brakuje niektórych parametrów lub są one nieprawidłowe. Upewnij się, że:</p><ul><li>Został ustawiony punkt zaczepienia grafiki GRG.</li><li>Wprowadzone dane czasu, prędkości i kąta zawierają prawidłowe wartości.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>W formularzu tworzenia grafiki GRG brakuje niektórych parametrów lub są one nieprawidłowe. Upewnij się, że wprowadzone dane szerokości i wysokości komórki zawierają prawidłowe wartości.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>W formularzu tworzenia grafiki GRG brakuje niektórych parametrów lub są one nieprawidłowe. Upewnij się, że wprowadzone wartości dla liczby poziomych i pionowych komórek są prawidłowe.</p>",
  "drawPointToolTip": "Kliknij, aby dodać punkt zaczepienia grafiki GRG",
  "missingLayerNameMessage": "Przed opublikowaniem warstwy należy wprowadzić jej prawidłową nazwę",
  "parseCoordinatesError": "Nie można przeanalizować współrzędnych. Sprawdź dane wejściowe.",
  "grgPolarRegionError": "Zasięg grafiki GRG obejmuje region polarny. Komórki znajdujące się w tym regionie nie zostaną utworzone.",
  "grgPolarOriginError": "Punkt zaczepienia grafiki GRG nie może znajdować się w regionie polarnym w przypadku tworzenia grafiki GRG na podstawie układu odniesienia.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Stopnie-Minuty-Sekundy (DMS)",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Stopnie dziesiętne — szerokość/długość geograficzna",
  "DDLongLatNotation": "Stopnie dziesiętne — długość/szerokość geograficzna",
  "DDMLatLongNotation": "Stopnie i minuty dziesiętne — szerokość/długość geograficzna",
  "DDMLongLatNotation": "Stopnie i minuty dziesiętne — długość/szerokość geograficzna",
  "DMSLatLongNotation": "Stopnie, minuty i sekundy — szerokość/długość geograficzna",
  "DMSLongLatNotation": "Stopnie, minuty i sekundy — długość/szerokość geograficzna",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — litera pasa",
  "UTMHemNotation": "UTM — półkula (N/S)"
});