define({
  "symbolologyTabLabel": "Configureer symbologie",
  "facilitiesDescription": "Faciliteitlagen",
  "demographicsDescription": "Demografielaag",
  "settingsTitle": "Instellingen",
  "spillLocationLabel": "Leklocatie",
  "spillLocationButtonLabel": "Leklocatie-instellingen configureren",
  "IISettingsLabel": "Initiële isolatiezone",
  "IIButtonLabel": "Initiële isolatiezone-instellingen configureren",
  "PASettingsLabel": "Beschermende actiezone",
  "PAButtonLabel": "Beschermende actie-instellingen configureren",
  "downwindSettingsLabel": "Benedenwindse zone",
  "downwindButtonLabel": "Benedenwindse zone-instellingen configureren",
  "fireSettingsLabel": "Brandisolatiezone",
  "fireButtonLabel": "Brandisolatie-instellingen configureren",
  "bleveSettingsLabel": "BLEVE isolatiezone",
  "bleveButtonLabel": "BLEVE isolatie-instellingen configureren",
  "transparency": "Transparant",
  "outline": "Omtreklijn",
  "fill": "Vullen (kleur wordt alleen toegepast als stijl ingesteld is al solid)",
  "style": "Stijl",
  "lineStyles": {
    "esriSLSDash": "Streep",
    "esriSLSDashDot": "Streep punt",
    "esriSLSDashDotDot": "Streep punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Lange streep",
    "esriSLSLongDashDot": "Lange streep punt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Korte streep",
    "esriSLSShortDashDot": "Korte streep punt",
    "esriSLSShortDashDotDot": "Korte streep punt punt",
    "esriSLSShortDot": "Korte punt",
    "esriSLSSolid": "Ononderbroken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Achterwaarts",
    "esriSFSCross": "Kruis",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Voorwaarts",
    "esriSFSHorizontal": "Horizontaal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Ononderbroken",
    "esriSFSVertical": "Verticaal"
  }
});