define({
  "queries": "Kyselyt",
  "addNew": "Lisää uusi",
  "newQuery": "Uusi kysely",
  "queryLayer": "Kyselytaso",
  "setSource": "Aseta",
  "setDataSource": "Määritä aineistolähde",
  "name": "Nimi",
  "querySource": "Aineistolähde",
  "queryName": "Tehtävän nimi",
  "queryDefinition": "Suodatinmääritys",
  "resultsSetting": "Tulosten asetus",
  "symbolSetting": "Symboliasetus",
  "resultSettingTip": "Määritä, mitä tuloksesta näytetään ja miten.",
  "resultItemTitle": "Kunkin tuloskohteen otsikko",
  "resultItemContent": "Nämä kenttäominaisuudet tulevat näyttöön",
  "fieldsSetTip": "Valitse näytettävät kentät. Valitse tietty kenttä, kun haluat päivittää sen aliaksen, järjestyksen tai muodon.",
  "addField": "Lisää kenttä",
  "visibility": "Näkyvyys",
  "alias": "Alias",
  "specialType": "Erikoistyyppi",
  "actions": "Toimet",
  "none": "Ei mitään",
  "link": "Linkki",
  "image": "Kuva",
  "noField": "Ei kenttää",
  "operationalLayerTip": "Lisää tulos toiminnalliseksi karttatasoksi",
  "setLayerSymbolTip": "Määritä kyselytulosten symboli: ",
  "setSelectedSymbolTip": "Määritä valitun kohteen symboli.",
  "notUseFilter": "Älä käytä suodatinta",
  "setSourceTip": "Määritä kyselyn lähde.",
  "setFilterTip": "Määritä suodatin oikein.",
  "ok": "OK",
  "cancel": "Peruuta",
  "noFilterTip": "Jos suodatinlauseketta ei määritetä, kyselytehtävä luetteloi kaikki määritetyn tietolähteen kohteet.",
  "relationships": "Suhteet",
  "addRelationshipLayer": "Lisää uusi suhde",
  "relatedTo": "Liittyy kohteeseen",
  "selectOption": "Valitse...",
  "resultItemSorting": "Tuloskohteen lajittelu",
  "field": "Kenttä",
  "sortingOrder": "Järjestä",
  "configureFieldsTip": "Määritä kentät,  joiden perusteella kyselyn tulokset lajitellaan.",
  "setSortingFields": "Määritä lajittelukentät",
  "ascending": "Nouseva",
  "descending": "Laskeva",
  "sortBy": "Lajitteluperuste",
  "thenBy": "Seuraava lajitteluperuste",
  "addTask": "Lisää tehtävä",
  "noTasksTip": "Kyselyitä ei ole määritetty. Lisää uusi valitsemalla ${newQuery}.",
  "infoText": "Tiedot",
  "filters": "Suodattimet",
  "results": "Tulokset",
  "optionsText": "Valinnat",
  "summaryText": "Yhteenveto",
  "attributeFilter": "Määritesuodatin",
  "attributeFilterTip": "Määritä määritelausekkeet, joita käytetään pienoisohjelmassa kyselytason suodattamiseen.",
  "defineWhereClause": "Määritä kyselylle Where-lause.",
  "noExpressionDefinedTip": "Lauseketta ei ole määritetty. Kaikki tietueet palautetaan.",
  "setExpressions": "Määritä lausekkeet",
  "spatialFilter": "Sijaintisuodattimet",
  "spatialFilterTip": "Valitse, mitkä sijaintisuodattimet ovat loppukäyttäjien käytettävissä.",
  "defaultOption": "Oletus",
  "useCurrentExtentTip": "Palauta kohteet vain nykyisestä karttalaajuudesta",
  "useDrawGraphicTip": "Palauta vain kohteet, jotka leikkaavat karttaan piirretyn muodon kanssa",
  "useFeaturesTip": "Palauta vain kohteet, joilla on sijaintisuhde toisessa karttatasossa olevien kohteiden kanssa",
  "noSpatialLimitTip": "Palauta kohteet kartan koko laajuudesta",
  "drawingTools": "Valitse piirtotyökalut",
  "bufferSettings": "Ota käyttöön puskurointitoiminto",
  "defaultDistance": "Oletusetäisyys",
  "bufferDistance": "Puskurin etäisyys",
  "defaultUnit": "Oletusyksikkö",
  "miles": "Mailia",
  "kilometers": "Kilometriä",
  "feet": "Jalkaa",
  "meters": "Metriä",
  "yards": "Jaardia",
  "nauticalMiles": "Meripeninkulmaa",
  "availableSpatialRelationships": "Valitse sijaintisuhdesäännöt",
  "setSpatialRelationships": "Määritä sijaintisuhteet",
  "availability": "Saatavuus",
  "relationship": "Suhde",
  "label": "Tunnusteksti",
  "intersect": "leikkaa",
  "contain": "sisältää",
  "areContainedIn": "sisältyvät",
  "cross": "risti",
  "envelopeIntersect": "rajojen leikkaus",
  "overlap": "limittyy",
  "areOverlapped": "on päällekkäin",
  "touch": "kosketa",
  "within": "sisässä",
  "areWithin": "on sisässä",
  "indexIntersect": "indeksin leikkaus",
  "itemTitle": "Kohteen otsikko",
  "displayFields": "Näyttökentät",
  "sortingFields": "Lajittele tuloskohteet",
  "setDisplayFields": "Määritä näyttökentät",
  "symbol": "Symboli",
  "setSymbol": "Käytä mukautettua symbolia",
  "changeSymbolAtRuntime": "Salli symbolien muuttaminen käytön aikana",
  "serviceSymbolTip": "Käytä karttatason määrittämiä symboleja",
  "exportTip": "Salli tulosten vienti",
  "keepResultsTip": "Näytä tulokset kartassa pienoisohjelman sulkemisen jälkeen",
  "queryRelatedRecords": "Kyselyyn liittyvät tietueet",
  "createLayerForTaskTip": "Määritä, miten kyselytehtävä luo karttatasot",
  "oneLayerForTaskTip": "Korvaa karttataso joka kerta, kun kysely suoritetaan",
  "multipleLayerForTaskTip": "Luo uusi karttataso joka kerta, kun kysely suoritetaan",
  "makeDefault": "Aseta oletukseksi",
  "icon": "Kuvake",
  "newTask": "Uusi tehtävä",
  "addTaskTip": "Lisää vähintään yksi kysely pienoisohjelmaan ja määritä kunkin parametrit.",
  "webMapPopupTip": "Käytä karttatason ponnahdusikkunan määrityksiä web-kartassa",
  "customPopupTip": "Määritä mukautettu sisältö",
  "showResultsSetActions": "Näytä toiminnot tulosjoukolle",
  "zoomTo": "Tarkenna kohteeseen",
  "openAttributeTable": "Näytä ominaisuustaulukossa",
  "content": "Sisältö",
  "displaySQLTip": "Näytä loppukäyttäjille SQL-lauseke",
  "useLayerDefaultSymbol": "Käytä karttatason oletussymbolia",
  "setCustomIcon": "Aseta mukautettu kuvake",
  "layerDefaultSymbolTip": "Käytä karttatason oletussymbolia",
  "uploadImage": "Lataa kuva",
  "attributeCriteira": "Ominaisuusehdot",
  "specifyFilterAtRuntimeTip": "Käyttäjien pitää määrittää parametrit tälle lausekkeelle.",
  "value": "ARVO",
  "hideLayersTip": "Poista kyselytulosten karttatasot käytöstä, kun pienoisohjelma on suljettuna.",
  "tabLabels": "Välilehden tunnustekstit",
  "tasks": "Tehtävät",
  "queryCriteira": "Kyselyehdot",
  "allowCustomQuery": "Salli mukautetun kyselyn luonti"
});