define({
  "_widgetLabel": "Distance et direction",
  "tabLineTitle": "Ligne",
  "tabCircleTitle": "Cercle",
  "tabEllipseTitle": "Ellipse",
  "tabRingsTitle": "Anneaux",
  "multipleNotationsMessage": " notations qui correspondent à votre entrée. Confirmez celle que vous souhaitez utiliser :",
  "invalidCoordinateMessage": "Coordonnée non valide",
  "confirmInputNotationMessage": "Confirmer la notation entrée",
  "prefixSuffixMessage": "La coordonnée entrée a été détectée comme étant pourvue d'un préfixe et d'un suffixe pour la valeur de la latitude ou de la longitude ; la coordonnée retournée est basée sur le préfixe.",
  "rememberDecisionMessage": "Mémoriser ma décision et ne pas me la demander à nouveau.<br/>",
  "majorAxisTooltipMessage": "Cliquer sur la longueur du grand axe",
  "minorAxisTooltipMessage": "Replacer la souris sur la position de début pour définir le petit axe et terminer le dessin de l’ellipse",
  "clickToFinishLineMessage": "Cliquer pour terminer le dessin de la ligne",
  "doubleClickEllipseMesage": "Double-cliquer pour terminer le dessin des anneaux de portée",
  "invalidCoordinateTypeMessage": "Impossible de déterminer le type de coordonnées en entrée. Vérifiez votre entrée.",
  "noCenterPointSetMessage": "Aucun point central défini. Vérifiez votre entrée.",
  "ellipseMajorAxis": "Grand axe",
  "ellipseMinorAxis": "Petit axe",
  "degreesRangeMessage": "La valeur doit être comprise entre 0 et 360",
  "millsRangeMessage": "La valeur doit être comprise entre 0 et 6 400",
  "lengthLabel": "Longueur",
  "angleLabel": "Angle",
  "startPointLabel": "Choisir le départ",
  "endPointLabel": "Extrémité",
  "centerPointLabel": "Point central",
  "distanceTableErrorMessage": "La table des distances est vide. Saisissez des distances.",
  "setCoordFormatStringMessage": "Définir une chaîne de format des coordonnées",
  "prefixMessage": "Ajouter le préfixe '+/-' aux nombres positifs et négatifs",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Degrés décimaux - Latitude/Longitude",
  "DDLongLatNotation": "Degrés décimaux - Longitude/Latitude",
  "DDMLatLongNotation": "Degrés minutes décimales - Latitude/Longitude",
  "DDMLongLatNotation": "Degrés minutes décimales - Longitude/Latitude",
  "DMSLatLongNotation": "Degrés minutes secondes - Latitude/Longitude",
  "DMSLongLatNotation": "Degrés minutes secondes - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Lettre du canal",
  "UTMHemNotation": "UTM - Hémisphère (N/S)",
  "circleTitle": "Créer un cercle depuis",
  "radiusLabel": "Rayon",
  "diameterLabel": "Diamètre",
  "startPointPlaceHolderLabel": "Entrer des coordonnées",
  "formatInputLabel": "Format d'entrée",
  "drawCircleLabel": "Dessiner un cercle",
  "drawLineLabel": "Dessiner une ligne",
  "createCircleInteractivelyLabel": "Créer un cercle interactivement",
  "rangeErrorMessage": "Rayon ou diamètre non valide",
  "numericInvalidMessage": "Entrer une valeur numérique",
  "timeLabel": "Durée",
  "invalidTimeMessage": "Valeur temporelle non valide",
  "hoursLabel": "Heures",
  "minutesLabel": "Minutes",
  "secondsLabel": "Secondes",
  "rateLabel": "Taux",
  "invalidDistanceMessage": "Valeur de distance non valide",
  "feetSecondsLabel": "Pieds / seconde",
  "feetHourLabel": "Pieds / heure",
  "kmSecondLabel": "Kilomètres / seconde",
  "kmHourLabel": "Kilomètres / heure",
  "metersSecondLabel": "Mètres / seconde",
  "metersHourLabel": "Mètres / heure",
  "milesSecondLabel": "Miles / seconde",
  "milesHourLabel": "Miles / heure",
  "nauticalMilesSecondLabel": "Milles nautiques / seconde",
  "nauticalMilesHourLabel": "Milles nautiques / heure",
  "clearGraphicsLabel": "Effacer les graphiques",
  "ellipseTypeLabel": "Type d’ellipse",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Complet",
  "drawEllipseLabel": "Dessiner une ellipse",
  "createEllipseInteractively": "Créer une ellipse interactivement",
  "axisLabel": "Axe",
  "majorRadiusLabel": "Demi-grand axe",
  "axisErrorMessage": "La valeur doit être supérieure à 0",
  "minorRadiusLabel": "Demi-petit axe",
  "orientationLabel": "Orientation",
  "orientationErrorMessage": "La valeur doit être comprise entre 0 et 360",
  "warningMessage": "Avertissement : les graphiques générés avec l’outil Ellipse ne sont pas géodésiques",
  "fromLabel": "Depuis",
  "distanceBearingLabel": "Distance et relèvement",
  "pointsLabel": "Points",
  "createLineInteractively": "Créer une ligne interactivement",
  "lineLengthErrorMessage": "Longueur de ligne non valide",
  "degreesLabel": "Degrés",
  "milsLabel": "Mils",
  "lineTypeLabel": "Type",
  "interactiveLabel": "Interactif",
  "fixedLabel": "Constant",
  "originLabel": "Origine",
  "cumulativeLabel": "Cumul",
  "numberOfRingsLabel": "Nombre d’anneaux",
  "ringsErrorMessage": "Nombre d’anneaux non valide",
  "distanceBetweenRingsLabel": "Distance entre les anneaux",
  "ringsDecimalErrorMessage": "Saisir une valeur numérique à deux décimales",
  "distanceUnitsLabel": "Unités de distance",
  "distancesLabel": "Distances",
  "numberOfRadialsLabel": "Nombre de lignes radiales",
  "upLabel": "+",
  "downLabel": "-",
  "deleteLabel": "Effacer",
  "radialsErrorMessage": "Nombre de lignes radiales non valide. Le nombre maximal autorisé est de 360",
  "addPointLabel": "Ajouter un point",
  "valueLabel": "Valeur",
  "valueText": "Saisir une valeur",
  "actionLabel": "Opération"
});