define({
  "queries": "ตั้งเงื่อนไข",
  "addNew": "เพิ่มข้อมูลใหม่",
  "newQuery": "สืบค้นใหม่",
  "queryLayer": "สืบค้นชั้นข้อมูล",
  "setSource": "ตั้ง",
  "setDataSource": "ตั้งค่าแหล่งข้อมูล",
  "name": "ชื่อ",
  "querySource": "แหล่งข้อมูล",
  "queryName": "ชื่องาน",
  "queryDefinition": "นิยามของตัวกรอง",
  "resultsSetting": "การตั้งค่าผลลัพธ์",
  "symbolSetting": "การตั้งค่าสัญลักษณ์",
  "resultSettingTip": "ระบุความหมายและวิธีการแสดงผลลัพธ์",
  "resultItemTitle": "ชื่อของผลลัพธ์แต่ละรายการ",
  "resultItemContent": "จะแสดงฟิลด์ของแอตทริบิวต์เหล่านี้",
  "fieldsSetTip": "เลือกฟิลด์ที่คุณต้องการแสดง เลือกฟิลด์ที่จะเปลี่ยนชื่อแฝง ลำดับ หรือรูปแบบ",
  "addField": "เพิ่มฟิลด์",
  "visibility": "มองเห็นได้",
  "alias": "ชื่อย่อ",
  "specialType": "ประเภทพิเศษ",
  "actions": "การดำเนินการ",
  "none": "ไม่มีเลย",
  "link": "ลิงค์",
  "image": "รูปภาพ",
  "noField": "ไม่มีฟิลด์",
  "operationalLayerTip": "เพิ่มผลลัพธ์เป็นชั้นข้อมูลการทำงาน",
  "setLayerSymbolTip": "ตั้งค่าสัญลักษณ์สำหรับผลลัพธ์การตั้งคำถาม ",
  "setSelectedSymbolTip": "ตั้งค่าสัญลักษณ์ของฟีเจอร์ที่เลือก",
  "notUseFilter": "ห้ามใช้ตัวกรอง",
  "setSourceTip": "โปรดตั้งค่าที่มาของคำถาม",
  "setFilterTip": "โปรดตั้งค่าตัวกรองให้ถูกต้อง",
  "ok": "ตกลง",
  "cancel": "ยกเลิก",
  "noFilterTip": "หากไม่กำหนดตัวกรอง  แบบสอบถามนี้จะแสดงรายการคุณลักษณะทั้งหมดในแหล่งข้อมูลที่ระบุ",
  "relationships": "ความสัมพันธ์",
  "addRelationshipLayer": "เพิ่มความสัมพันธ์ใหม่",
  "relatedTo": "เกี่ยวข้องกับ",
  "selectOption": "กรุณาเลือก..",
  "resultItemSorting": "การเรียงลำดับผลลัพธ์",
  "field": "ฟิลด์",
  "sortingOrder": "ลำดับ",
  "configureFieldsTip": "กรุณาตั้งค่าฟิลด์ซึ่งผลลัพธ์การค้นหาจะเรียงลำดับตาม",
  "setSortingFields": "ตั้งค่าฟิลด์การเรียงลำดับ",
  "ascending": "เรียงจากน้อยไปมาก",
  "descending": "เรียงจากมากไปน้อย",
  "sortBy": "จัดลำดับตาม",
  "thenBy": "แล้วตามด้วย",
  "addTask": "เพิ่มงาน",
  "noTasksTip": "ไม่มีการตั้งค่าเงื่อนไข คลิก {สอบถามข้อมูลใหม่} เพื่อเพิ่มข้อมูล",
  "infoText": "ข้อมูล",
  "filters": "ตัวกรองข้อมูล",
  "results": "ผลลัพธ์",
  "optionsText": "ตัวเลือก",
  "summaryText": "สรุป",
  "attributeFilter": "ตัวกรองแอตทริบิวต์",
  "attributeFilterTip": "กำหนดสมการในการเลือกตามแอตทริบิวต์ สำหรับใช้งานในเครื่องมือวิจเก็ต เพื่อกรองข้อมูลจากชั้นข้อมูลที่ต้องการสอบถาม",
  "defineWhereClause": "กำหนดเงื่อนไขสำหรับการค้นหา",
  "noExpressionDefinedTip": "ไม่มีการกำหนดสมการ ผลลัพธ์จะได้เป็นข้อมูลทั้งหมด",
  "setExpressions": "ตั้งค่าเงื่อนไข",
  "spatialFilter": "ตัวกรองเชิงพื้นที่",
  "spatialFilterTip": "การเลือกตัวกรองเชิงพื้นที่จะสามารถใช้ได้โดยผู้ใช้",
  "defaultOption": "ค่าตั้งต้น",
  "useCurrentExtentTip": "ให้ผลลัพธ์เฉพาะข้อมูลที่อยู่ในขอบเขตแผนที่ปัจจุบัน",
  "useDrawGraphicTip": "คุณสมบัติที่ตัดกับรูปร่างรูปทรงบนแผนที่",
  "useFeaturesTip": "ให้ผลลัพธ์เฉพาะข้อมูลที่มีความสัมพันธ์เชิงพื้นที่กับข้อมูลในชั้นข้อมูลอื่น",
  "noSpatialLimitTip": "ให้ผลลัพธ์จากข้อมูลที่อยู่ในขอบเขตแผนที่ทั้งหมดของแผนที่",
  "drawingTools": "เลือกเครื่องมือวาด",
  "bufferSettings": "เปิดใช้ตัวเลือกสำหรับการบัฟเฟอร์",
  "defaultDistance": "ระยะตั้งต้น",
  "bufferDistance": "ระยะทางบัฟเฟอร์",
  "defaultUnit": "หน่วยตั้งต้น",
  "miles": "ไมล์",
  "kilometers": "กิโลเมตร",
  "feet": "ฟุต",
  "meters": "เมตร",
  "yards": "หลา",
  "nauticalMiles": "ไมล์ทะเล",
  "availableSpatialRelationships": "เลือกกฎความสัมพันธ์ข้อมูลเชิงพื้นที่",
  "setSpatialRelationships": "ตั้งค่าความสัมพันธ์เชิงพื้นที่",
  "availability": "สภาพพร้อมใช้งาน",
  "relationship": "ความสัมพันธ์",
  "label": "ป้ายชื่อ",
  "intersect": "พื้นที่ร่วมกัน",
  "contain": "ประกอบด้วย",
  "areContainedIn": "ที่ประกอบด้วย",
  "cross": "กากบาท",
  "envelopeIntersect": "การตัดขวาง",
  "overlap": "ซ้อนทับ",
  "areOverlapped": "ที่ซ้อนทับกัน",
  "touch": "แตะ",
  "within": "ภายใน",
  "areWithin": "ที่อยู่ภายใน",
  "indexIntersect": "ค่าที่ intersect",
  "itemTitle": "ชื่อรายการ",
  "displayFields": "แสดงผลฟิลด์",
  "sortingFields": "เรียงลำดับรายการผลลัพธ์ที่ได้",
  "setDisplayFields": "ตั้งค่าการแสดงผลฟิลด์",
  "symbol": "สัญลักษณ์",
  "setSymbol": "ใช้สัญลักษณ์ที่กำหนดเอง",
  "changeSymbolAtRuntime": "อนุญาตให้มีการเปลี่ยนสัญลักษณ์ที่รันไทม์",
  "serviceSymbolTip": "ใช้สัญลักษณ์ที่กำหนดโดยชั้นของข้อมูล",
  "exportTip": "ยอมให้ส่งผลลัพธ์ออกไปได้",
  "keepResultsTip": "เก็บผลลัพธ์บนแผนที่หลังจากเครื่องมือถูกปิด",
  "queryRelatedRecords": "สอบถามความสัมพันธ์ของ records",
  "createLayerForTaskTip": "กำหนดวิธีการในการสร้างชั้นข้อมูลด้วยการสอบถาม",
  "oneLayerForTaskTip": "เขียนทับชั้นข้อมูลทุกครั้ง ที่มีการส่งคำสั่งสอบถาม",
  "multipleLayerForTaskTip": "สร้างชั้นข้อมูลใหม่ทุกครั้ง ที่มีการส่งคำสั่งสอบถาม",
  "makeDefault": "กำหนดให้เป็นค่าเริ่มต้น",
  "icon": "ไอค่อน",
  "newTask": "การทำงานใหม่",
  "addTaskTip": "เพิ่มหนึ่งหรือมากกว่าการสืบคนและการตั้งค่าตัวแปรเหล่านั้น",
  "webMapPopupTip": "ใช้เการปรับครื่องมือป๊อปอัพของชั้นข้อมูลในเว็บแม็พ",
  "customPopupTip": "ตั้งค่าเนื้อหาที่กำหนดเอง",
  "showResultsSetActions": "แสดงการกระทำสำหรับชุดของผลลัพธ์",
  "zoomTo": "ขยายไปยัง",
  "openAttributeTable": "ดูในตารางแอตทริบิวต์",
  "content": "เนื้อหา",
  "displaySQLTip": "แสดงสมการ SQL ให้ผู้ใช้เห็น",
  "useLayerDefaultSymbol": "ใช้สัญลักษณ์ตั้งต้นของชั้นข้อมูล",
  "setCustomIcon": "กำหนดชุดไอคอนเอง",
  "layerDefaultSymbolTip": "ใช้สัญลักษณ์ตั้งต้นของชั้นข้อมูล",
  "uploadImage": "อัปโหลดภาพ",
  "attributeCriteira": "เงื่อนไขข้อมูลตาราง",
  "specifyFilterAtRuntimeTip": "ผู้ใช้จะต้องระบุพารามิเตอร์สำหรับสมการนี้",
  "value": "ค่า",
  "hideLayersTip": "ปิดชั้นข้อมูลผลลัพธ์จากการค้นหา เมื่อวิดเจ็ตถูกปิด",
  "tabLabels": "แท็บป้ายกำกับ",
  "tasks": "งานที่ต้องทำ",
  "queryCriteira": "เกณฑ์การสืบค้น",
  "allowCustomQuery": "อนุญาตให้สร้างการสอบถามที่กำหนดเอง"
});