define({
  "_widgetLabel": "应急响应指南",
  "ergMainPageTitle": "基于 2016 年应急响应指南",
  "coordInputLabelStart": "泄漏位置(DD)",
  "coordInputLabel": "泄漏位置",
  "addPointToolTip": "添加泄漏位置",
  "drawPointToolTip": "单击添加泄漏位置",
  "material": "资料",
  "materialPlaceholder": "开始输入以搜索材料",
  "table3Message": "如果您正在处理大量泄漏事故，则需要了解有关所选材料的更多信息。\n\n请确保您为风速和运输容器选择了正确值。",
  "table2Message": "您选择的材料在洒入水中时可能会产生大量吸入毒性危害气体。\n\n您最好考虑使用以下材料：\n\n",
  "spillSize": "泄漏量",
  "small": "小型",
  "large": "大型",
  "fireLabel": "显示防火隔离区",
  "weatherLabel": "泄漏位置的当前天气",
  "weatherIntialText": "<br />识别泄漏位置即会更新",
  "temperature": "温度",
  "wind": "风向/风",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "未获得天气信息。手动更新风速和泄露时间值",
  "windDirection": "风向(吹向)",
  "timeOfSpill": "泄露时间",
  "day": "白天",
  "night": "夜晚",
  "windSpeed": "风速",
  "low": "低",
  "moderate": "中",
  "high": "高",
  "transportContainer": "运输集装箱",
  "rail": "铁路油罐车",
  "semi": "公路油罐车或拖车",
  "mton": "多吨缸",
  "ston": "多个小缸或一吨缸",
  "ag": "农业加油槽车",
  "msm": "多个小缸",
  "bleveLabel": "显示 BLEVE 隔离区",
  "capacity": "集装箱容量(升)",
  "bleveMessage": "对于您选择的材料，可以针对 BLEVE 显示额外的疏散距离。\n\n要启用此功能，请将“显示 BLEVE 隔离区”开关设置为打开状态并选择适当的容器容量。",
  "noPAZoneMessage": "对于这种材料，没有防护行动距离。只计算初始隔离区和疏散区",
  "settingsTitle": "设置",
  "spillLocationLabel": "泄漏位置",
  "spillLocationButtonLabel": "配置泄漏位置设置",
  "IISettingsLabel": "初始隔离区",
  "IIButtonLabel": "配置初始隔离设置",
  "PASettingsLabel": "防护行动区",
  "PAButtonLabel": "配置防护行动设置",
  "downwindSettingsLabel": "顺风区",
  "downwindButtonLabel": "配置顺风设置",
  "fireSettingsLabel": "隔火区",
  "fireButtonLabel": "配置隔火设置",
  "bleveSettingsLabel": "BLEVE 隔离区",
  "bleveButtonLabel": "配置 BLEVE 设置",
  "style": "样式",
  "lineStyles": {
    "esriSLSDash": "虚线",
    "esriSLSDashDot": "点划线",
    "esriSLSDashDotDot": "双点划线",
    "esriSLSDot": "点",
    "esriSLSLongDash": "长划线",
    "esriSLSLongDashDot": "长点划线",
    "esriSLSNull": "空",
    "esriSLSShortDash": "短虚线",
    "esriSLSShortDashDot": "短点划线",
    "esriSLSShortDashDotDot": "短双点划线",
    "esriSLSShortDot": "短点线",
    "esriSLSSolid": "实线"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向后",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "对角线",
    "esriSFSForwardDiagonal": "向前",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "空",
    "esriSFSSolid": "实线",
    "esriSFSVertical": "竖直"
  },
  "resultsTitle": "结果",
  "publishERGBtn": "发布",
  "ERGLayerName": "发布的 ERG 图层名称",
  "invalidERGLayerName": "图层名称只能包含字母数字字符和下划线",
  "missingERGLayerName": "您必须输入 ERG 的名称",
  "publishingFailedLayerExists": "发布失败：您已拥有名为 {0} 的要素服务。请选择其他名称。",
  "checkService": "检查服务：{0}",
  "createService": "创建服务：{0}",
  "unableToCreate": "无法创建：{0}",
  "addToDefinition": "添加到定义：{0}",
  "successfullyPublished": "已成功发布 web 图层{0}管理 web 图层",
  "userRole": "用户没有权限，因此无法创建服务",
  "transparency": "透明度",
  "outline": "轮廓",
  "fill": "填充(仅在将样式设置为单色时应用颜色)",
  "createERGBtn": "创建区域",
  "clearERGBtn": "清除",
  "labelFormat": "标注格式",
  "helpIconTooltip": "最小泄露量与最大泄露量阈值：\n液体 - 55 加仑(208 升)\n固体 - 60 磅(300 千克)",
  "cellWidth": "像元宽度(x)",
  "cellHeight": "像元高度(y)",
  "invalidNumberMessage": "输入的值无效",
  "invalidRangeMessage": "值必须大于 0",
  "gridAngleInvalidRangeMessage": "值必须位于 -89.9 和 89.9 之间",
  "formatIconTooltip": "格式输入",
  "setCoordFormat": "设置坐标格式字符串",
  "prefixNumbers": "向正数和负数添加“+/-”前缀",
  "cancelBtn": "取消",
  "applyBtn": "应用",
  "comfirmInputNotation": "确认输入注记",
  "notationsMatch": "发现与您的输入匹配的注记。请确认您想使用的注记：",
  "missingLayerNameMessage": "发布之前，您必须输入有效的图层名称",
  "parseCoordinatesError": "无法解析坐标。请检查您的输入。",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十进制度 - 纬度/经度",
  "DDLongLatNotation": "十进制度 - 经度/纬度",
  "DDMLatLongNotation": "度十进制分 - 纬度/经度",
  "DDMLongLatNotation": "度十进制分 - 经度/纬度",
  "DMSLatLongNotation": "度分秒 - 纬度/经度",
  "DMSLongLatNotation": "度分秒 - 经度/纬度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 带字母",
  "UTMHemNotation": "UTM - 半球(N/S)"
});