define({
  "symbolologyTabLabel": "Cấu hình Biểu tượng",
  "facilitiesDescription": "Lớp Cơ sở",
  "demographicsDescription": "Lớp Nhân khẩu học",
  "settingsTitle": "Thiết lập",
  "spillLocationLabel": "Vị trí Tràn",
  "spillLocationButtonLabel": "Cấu hình Cài đặt Vị trí Tràn",
  "IISettingsLabel": "Vùng Cô lập Ban đầu",
  "IIButtonLabel": "Cấu hình Cài đặt Cô lập Ban đầu",
  "PASettingsLabel": "Vùng Hành động Bảo vệ",
  "PAButtonLabel": "Cấu hình Cài đặt Hành động Bảo vệ",
  "downwindSettingsLabel": "Vùng Xuôi gió",
  "downwindButtonLabel": "Cấu hình Cài đặt Xuôi gió",
  "fireSettingsLabel": "Vùng Cô lập Hỏa hoạn",
  "fireButtonLabel": "Cấu hình Cài đặt Cô lập Hỏa hoạn",
  "bleveSettingsLabel": "Vùng Cô lập BLEVE",
  "bleveButtonLabel": "Cấu hình Cài đặt BLEVE",
  "transparency": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô kín (Màu chỉ áp dụng khi kiểu được đặt thành đồng màu)",
  "style": "Kiểu",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  }
});