define({
  "_widgetLabel": "Tilannekuva",
  "locate_incident": "Paikanna tapahtuma",
  "reverse_geocoded_address": "Lähin osoite",
  "reverse_geocoded_error": "Ei käytettävissä",
  "now": "NYT",
  "wind": "TUULI",
  "SUN": "SU",
  "MON": "MA",
  "TUE": "TI",
  "WED": "KE",
  "THU": "TO",
  "FRI": "PE",
  "SAT": "LA",
  "actionLabel": "Määritä sijainti",
  "drawPoint": "Piirrä piste",
  "drawLine": "Piirrä viiva",
  "drawPolygon": "Piirrä alue",
  "saveIncident": "Tallenna",
  "clearIncident": "Aloita alusta",
  "noFeaturesFound": "Kohteita ei löytynyt.",
  "downloadCSV": "Lataa",
  "sum": "Summa",
  "min": "Minimi",
  "max": "Maksimi",
  "avg": "Keskiarvo",
  "count": "MÄÄRÄ",
  "area": "ALUE",
  "length": "PITUUS",
  "update_btn": "Valmis",
  "delete_btn": "Poista",
  "get_directions": "Hae reittiohjeet",
  "incident": "Tapahtuma",
  "incidents": "Tapahtumat",
  "buffer": "Puskuri",
  "buffers": "Puskurit",
  "weather": "Sää",
  "poweredBy": "Palvelun tarjoaa",
  "_featureAction_ActionLabel": "Määritä sijainti",
  "_featureAction_AddRemoveActionLabel": "Lisää tai poista sijainti",
  "snapshot": "Seuraavan sovellustunnuksen luoma SnapShot-kansio:",
  "user_credentials": "Käyttäjällä ei ole kelvollisia oikeuksia.",
  "notPolySnapShot": "Määritä puskurin etäisyys ennen tilannevedoksen luomista.",
  "notPolyReport": "Raporttiin lisättäviä kelvollisia tuloksia ei ole.",
  "notValidDownload": "Ei ladattavia kelvollisia tuloksia.",
  "of_append": "/",
  "layer_append": "karttataso",
  "downloadAll": "Lataa kaikki",
  "createSnapshot": "Luo tilannevedos",
  "createReport": "Luo raportti",
  "calculated_results": "Yhteenvetotiedot",
  "closest": "Lähin kohde",
  "proximity": "Läheisyys",
  "summary": "Yhteenveto",
  "groupedSummary": "Ryhmitellyt määrät",
  "_count": "Lukumäärä",
  "approximate": "noin",
  "snapshot_name": "Määritä tilannevedoksen ominaisuudet",
  "report_name": "Määritä raportin ominaisuudet",
  "invalid_snapshot_name": "Virheellinen tilannevedoksen nimi.",
  "invalid_report_name": "Virheellinen raportin otsikko.",
  "orientation": "Suunta",
  "pageSize": "Sivun koko",
  "comments": "Kommentit",
  "choose_group": "Ryhmät",
  "forecast": "Ennuste",
  "select_group": "Valitse ryhmä",
  "select_group_instruction": "Tilannevedos luodaan ja jaetaan valitun ryhmän kanssa",
  "information_append": " Tiedot",
  "distance": "ETÄISYYS",
  "buffer_invalid": "Anna kelvollinen arvo väliltä ${min}–${max}"
});