define({
  "_widgetLabel": "Suitability Modeler",
  "general": {
    "clear": "Tøm",
    "cancel": "Avbryt",
    "save": "Kjør",
    "saveAs": "Eksporter"
  },
  "saveModel": {
    "save": "Eksporter",
    "title": "Tittel: ",
    "summary": "Sammendrag: ",
    "description": "Beskrivelse: ",
    "tags": "Merker: ",
    "folder": "Mappe: ",
    "homeFolderPattern": "{username} (Hjem)",
    "failed": "Eksporten mislyktes."
  },
  "util": {
    "colorRamp": {
      "1": "Ekstremt lav",
      "2": "Svært lav",
      "3": "Lav",
      "4": "Lav middels",
      "5": "Middels",
      "6": "Høy middels",
      "7": "Høy",
      "8": "Svært høy",
      "9": "Ekstremt høy",
      "low": "Lav",
      "high": "Høy",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Vend"
    }
  },
  "wro": {
    "caption": "Suitability Modeler",
    "browsePrompt": "Vektet overleggstjeneste",
    "selectLayersCaption": "Velg lag",
    "selectLayers": "Lag",
    "designModelCaption": "Designmodell",
    "designModel": "Designmodell",
    "transparency": "Gjennomsiktighet",
    "visible": "Synlig",
    "total": "Totalt",
    "unableToLoad": "Kan ikke laste inn modell.",
    "projectNotOpen": "Et prosjekt er ikke åpen.",
    "readMore": "Les mer",
    "validation": {
      "validating": "Validerer...",
      "invalidItemCaption": "Vektet overleggstjenesteadvarsel",
      "notAnImageService": "Dette elementet er ikke en bildetjeneste.",
      "notAWroService": "Dette elementet er ikke en vektet overleggstjeneste.",
      "undefinedUrl": "Dette elementets URL er ikke definert.",
      "inaccessible": "Tjenesten er utilgjengelig.",
      "generalError": "Kan ikke åpne elementet.",
      "missingFieldPattern": "{field} er et obligatorisk felt",
      "notAllowRasterFunction": "allowRasterFunction må settes til true",
      "notNearestResampling": "defaultResamplingMethod må være Nærmest",
      "notIsWeightedOverlayProp": "Nøkkelegenskapen IsWeightedOverlay må settes til true",
      "invalidLink": "URL-en er ugyldig. Klarte ikke å åpne området for det valgte laget.",
      "unexpectedError": "Det oppstod en uventet tilstand.",
      "rangeMessage": "Verdien må være mellom ${0} and ${1}",
      "rangeMessage100": "Verdien må være mellom 0 og 100",
      "maxLayers": "Maksimalt ${0} lag tillates av tjenesten, så du må først fjerne et lag før du legger til et nytt.",
      "notFound": "Laget ${0} ble ikke funnet i den vektede overleggstjenesten",
      "wroServiceNotDefined": "Det er ikke definert noen vektet overleggstjeneste for modellen.",
      "overlayLayerOutputInvalid": "Overleggslagets [${0}] tilordnede områder [${1}] mangler eller har ugyldige utgangsverdier",
      "overlayLayerInputInvalid": "Overleggslagets [${0}] tilordnede områder [${1}] mangler eller har ugyldige min/maksverdier",
      "overlayLayerRangesMissing": "Overleggslag [$ {0}] mangler tilordnede områder",
      "overlayLayerWeight": "Overleggslagvekting må til sammen bli 100",
      "overlayLayerRequired": "Minst ett overleggslag er påkrevd.",
      "overlayLayerNotDefined": "Overleggslag er ikke definert",
      "requiresColormap": "Denne rasterfunksjonen krever et fargekart, men modellen har ingen gyldig fargekartdefinisjon",
      "createModelError": "Feil ved oppretting av modell",
      "invalidModel": "Modellen er ugyldig",
      "imageServiceNotDefined": "Bildetjenestelaget ble ikke definert",
      "imageLayerNotDefined": "Bildetjenestelaget ble ikke definert",
      "histogramNotDefined": "Ingen funksjon for vektet overleggshistogram er definert."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Grønn Gul Rød",
      "Red Yellow Green": "Rød Gul Grønn",
      "Yellow to Dark Red": "Gul til Mørk rød",
      "Dark Red to Yellow": "Mørk rød til Gul",
      "Light Gray to Dark Gray": "Lys grå til Mørkegrå",
      "Dark Gray to Light Gray": "Mørkegrå til Lysegrå",
      "Light Brown to Dark Brown": "Lys brun til Mørk brun",
      "Dark Brown to Light Brown": "Mørk brun til Lys brun",
      "Full Spectrum - Bright Red to Blue": "Fullt spektrum - Lys rød til Blå",
      "Full Spectrum - Bright Blue to Red": "Fullt spektrum - Lys blå til Rød",
      "Partial Spectrum - Yellow to Blue": "Delvis spektrum - Gul til Blå",
      "Partial Spectrum - Blue to Yellow": "Delvis spektrum - Blå til Gul",
      "Yellow-Green to Dark Blue": "Gulgrønn til Mørk blå",
      "Dark Blue to Yellow-Green": "Mørk blå til Gulgrønn",
      "Cold to Hot Diverging": "Kaldt til Varmt divergerende",
      "Hot to Cold Diverging": "Varmt til Kald divergerende",
      "Surface - Low to High": "Overflate - Lav til Høy",
      "Surface - High to Low": "Overflate - Høy til Lav"
    }
  },
  "tabs": {
    "layers": "Lag",
    "model": "Modell",
    "chart": "Diagram"
  },
  "chart": {
    "prompt": "Geoobjekter",
    "working": "Oppdaterer...",
    "polygonTool": "Tegn en polygon",
    "freehandPolygonTool": "Tegn frihåndspolygon",
    "selectTool": "Velg fra et lag",
    "panTool": "Panorer",
    "clearButton": "Tøm",
    "noModelLayer": "Ingen modell.",
    "noSubjectLayers": "Kartet har ingen polygonlag.",
    "tipPattern": "${category} - ${label}: ${percent} %",
    "tipPattern2": "${category}: ${percent} %",
    "labelPattern": "${category} - ${label}"
  }
});