define({
  "symbolologyTabLabel": "تكوين الرموز",
  "facilitiesDescription": "طبقات المرافق",
  "demographicsDescription": "طبقات الديموغرافية",
  "settingsTitle": "إعدادات",
  "spillLocationLabel": "موقع الإخراج",
  "spillLocationButtonLabel": "تكوين إعدادات موقع الإخراج",
  "IISettingsLabel": "منطقة العزل الأوَّلي",
  "IIButtonLabel": "تكوين إعدادات العزل الأوَّلي",
  "PASettingsLabel": "منطقة الإجراء الوقائي",
  "PAButtonLabel": "تكوين إعدادات الإجراء الوقائي",
  "downwindSettingsLabel": "منطقة اتجاه الريح",
  "downwindButtonLabel": "تكوين إعدادات اتجاه الريح",
  "fireSettingsLabel": "منطقة عزل الحريق",
  "fireButtonLabel": "تكوين إعدادات عزل الحريق",
  "bleveSettingsLabel": "منطقة عزل BLEVE",
  "bleveButtonLabel": "تكوين إعدادات BLEVE",
  "transparency": "الشفافية",
  "outline": "الحدود",
  "fill": "تعبئة (لا ينطبق اللون إلا عند تعيين النمط إلى مُصمَت)",
  "style": "نمط",
  "lineStyles": {
    "esriSLSDash": "شَرطَة",
    "esriSLSDashDot": "شَرطَة ونقطة",
    "esriSLSDashDotDot": "شرطة ونقطتين",
    "esriSLSDot": "نقطة",
    "esriSLSLongDash": "شرطة طويلة",
    "esriSLSLongDashDot": "شرطة ونقطة طويلين",
    "esriSLSNull": "خالِ",
    "esriSLSShortDash": "شَرطَة قصيرة",
    "esriSLSShortDashDot": "نقطة شرطة قصيرة",
    "esriSLSShortDashDotDot": "نقطة نقطة شرطة قصيرة",
    "esriSLSShortDot": "منطقة صغيرة",
    "esriSLSSolid": "متصل"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "للخلف",
    "esriSFSCross": "شكل متصالب",
    "esriSFSDiagonalCross": "قطري",
    "esriSFSForwardDiagonal": "للأمام",
    "esriSFSHorizontal": "أفقياً",
    "esriSFSNull": "خالِ",
    "esriSFSSolid": "متصل",
    "esriSFSVertical": "عمودي"
  }
});