define({
  "_widgetLabel": "Suitability Modeler",
  "general": {
    "clear": "Ryd",
    "cancel": "Annuller",
    "save": "Kør",
    "saveAs": "Eksportér"
  },
  "saveModel": {
    "save": "Eksportér",
    "title": "Titel: ",
    "summary": "Beskrivelse: ",
    "description": "Beskrivelse: ",
    "tags": "Nøgleord: ",
    "folder": "Mappe: ",
    "homeFolderPattern": "{username} (Hjem)",
    "failed": "Eksport mislykkedes."
  },
  "util": {
    "colorRamp": {
      "1": "Ekstremt lav",
      "2": "Meget lav",
      "3": "Lav",
      "4": "Lav - mellem",
      "5": "Mellem",
      "6": "Høj - mellem",
      "7": "Høj",
      "8": "Meget høj",
      "9": "Ekstremt høj",
      "low": "Lav",
      "high": "Høj",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Vend"
    }
  },
  "wro": {
    "caption": "Suitability Modeler",
    "browsePrompt": "Vægtet overlay-tjeneste",
    "selectLayersCaption": "Vælg lag",
    "selectLayers": "Lag",
    "designModelCaption": "Designmodel",
    "designModel": "Designmodel",
    "transparency": "Gennemsigtighed",
    "visible": "Synlig",
    "total": "I alt",
    "unableToLoad": "Kan ikke indlæse model.",
    "projectNotOpen": "Der er ikke noget åbent projekt.",
    "readMore": "Læs mere",
    "validation": {
      "validating": "Validerer...",
      "invalidItemCaption": "Advarsel om vægtet overlay-tjeneste",
      "notAnImageService": "Dette element er ikke en billedtjeneste.",
      "notAWroService": "Dette element er ikke en vægtet overlay-tjeneste.",
      "undefinedUrl": "Dette elements URL er ikke defineret.",
      "inaccessible": "Denne tjeneste er utilgængelig.",
      "generalError": "Kan ikke åbne element.",
      "missingFieldPattern": "{field} er et obligatorisk felt",
      "notAllowRasterFunction": "allowRasterFunction skal være sat til sand",
      "notNearestResampling": "defaultResamplingMethod må ikke være Nærmeste",
      "notIsWeightedOverlayProp": "Nøgleegenskaben IsWeightedOverlay skal være sat til sand",
      "invalidLink": "URL'en er ugyldig. Kunne ikke åbne stedet for det valgte lag.",
      "unexpectedError": "Der opstod en uventet tilstand.",
      "rangeMessage": "Værdi skal være mellem ${0} og ${1}",
      "rangeMessage100": "Værdi skal være mellem 0 og 100",
      "maxLayers": "Da et maksimum på ${0} lag er tilladt for denne tjeneste, skal du fjerne et lag, før du tilføjer et nyt.",
      "notFound": "Laget ${0} findes ikke i den vægtede overlay-tjeneste",
      "wroServiceNotDefined": "Ingen vægtet overlay-tjeneste er defineret for modellen.",
      "overlayLayerOutputInvalid": "Overlay-laget [${0}] genberegn områder [${1}] outputværdi mangler eller er ugyldig",
      "overlayLayerInputInvalid": "Overlay-laget [${0}] genberegn områder [${1}] input-min./maks.-værdi mangler eller er ugyldig",
      "overlayLayerRangesMissing": "Overlay-laget [${0}] mangler genberegningsområder",
      "overlayLayerWeight": "De vægtede overlay-lag skal tilsammen være 100",
      "overlayLayerRequired": "Der kræves mindst ét overlay-lag",
      "overlayLayerNotDefined": "Overlay-lag er ikke defineret",
      "requiresColormap": "Denne rasterfunktion kræver et farvekort, men modellen har ikke nogen gyldig farvekortdefinition",
      "createModelError": "Fejl under oprettelse af model",
      "invalidModel": "Modellen er ikke gyldig",
      "imageServiceNotDefined": "Billedtjenestelag er ikke defineret",
      "imageLayerNotDefined": "Billedtjenestelag er ikke defineret",
      "histogramNotDefined": "Der er ikke defineret nogen vægtet overlay-histogramfunktion."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Grøn Gul Rød",
      "Red Yellow Green": "Rød Gul Grøn",
      "Yellow to Dark Red": "Gul til mørkerød",
      "Dark Red to Yellow": "Mørkerød til Gul",
      "Light Gray to Dark Gray": "Lysegrå til mørkegrå",
      "Dark Gray to Light Gray": "Mørkegrå til lysegrå",
      "Light Brown to Dark Brown": "Lysebrun til mørkebrun",
      "Dark Brown to Light Brown": "Mørkebrun til lysebrun",
      "Full Spectrum - Bright Red to Blue": "Fuldt spektrum - Lyserød til blå",
      "Full Spectrum - Bright Blue to Red": "Fuldt spektrum - Lyseblå til rød",
      "Partial Spectrum - Yellow to Blue": "Delvist spektrum - Gul til blå",
      "Partial Spectrum - Blue to Yellow": "Delvist spektrum - Blå til gul",
      "Yellow-Green to Dark Blue": "Gul-Grøn til mørkeblå",
      "Dark Blue to Yellow-Green": "Mørkeblå til Gul-Grøn",
      "Cold to Hot Diverging": "Kold divergerende til varm",
      "Hot to Cold Diverging": "Varm divergerende til kold",
      "Surface - Low to High": "Overflade - Lav til høj",
      "Surface - High to Low": "Overflade - Høj til lav"
    }
  },
  "tabs": {
    "layers": "Lag",
    "model": "Model",
    "chart": "Diagram"
  },
  "chart": {
    "prompt": "Objekter",
    "working": "Opdaterer...",
    "polygonTool": "Tegn en polygon",
    "freehandPolygonTool": "Tegn en frihåndspolygon",
    "selectTool": "Vælg fra et lag",
    "panTool": "Panorér",
    "clearButton": "Ryd",
    "noModelLayer": "Ingen model.",
    "noSubjectLayers": "Dit kort har ingen polygonlag.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});