define({
  "_widgetLabel": "Situasjonsbevissthet",
  "locate_incident": "Lokaliser hendelsen",
  "reverse_geocoded_address": "Nærmeste adresse",
  "reverse_geocoded_error": "Not available",
  "now": "NÅ",
  "wind": "VIND",
  "SUN": "SØN",
  "MON": "MAN",
  "TUE": "TIR",
  "WED": "ONS",
  "THU": "TOR",
  "FRI": "FRE",
  "SAT": "LØR",
  "actionLabel": "Angi lokasjon",
  "drawPoint": "Tegn punkt",
  "drawLine": "Tegn linje",
  "drawPolygon": "Tegn polygon",
  "saveIncident": "Lagre",
  "clearIncident": "Start på nytt",
  "noFeaturesFound": "Fant ingen geoobjekter.",
  "downloadCSV": "Last ned",
  "sum": "Summer",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Gjennomsnitt",
  "count": "ANTALL",
  "area": "OMRÅDE",
  "length": "LENGDE",
  "update_btn": "Fullført",
  "delete_btn": "Slett",
  "get_directions": "Hent veibeskrivelser",
  "incident": "Hendelse",
  "incidents": "Hendelser",
  "buffer": "Lag buffer",
  "buffers": "Buffere",
  "weather": "Vær",
  "poweredBy": "Levert av",
  "_featureAction_ActionLabel": "Angi lokasjon",
  "_featureAction_AddRemoveActionLabel": "Legg til / fjern lokasjon",
  "snapshot": "SnapShot-mappe opprettet av app-ID:",
  "user_credentials": "Brukeren har ikke gyldige rettigheter.",
  "notPolySnapShot": "Angi en bufferavstand før du oppretter et snapshot.",
  "notPolyReport": "Ingen gyldige resultater å legge til i rapporten.",
  "notValidDownload": "Ingen gyldige resultater som kan lastes ned.",
  "of_append": "av",
  "layer_append": "lag",
  "downloadAll": "Last ned alt",
  "createSnapshot": "Opprett snapshot",
  "createReport": "Opprett rapport",
  "calculated_results": "Oppsummert informasjon",
  "closest": "Nærmeste geoobjekt",
  "proximity": "Nærhet",
  "summary": "Sammendrag",
  "groupedSummary": "Gruppert antall",
  "_count": "Antall",
  "approximate": "omtrentlig",
  "snapshot_name": "Angi egenskaper for øyeblikksbilde",
  "report_name": "Angi rapportegenskaper",
  "invalid_snapshot_name": "Ugyldig navn på snapshot.",
  "invalid_report_name": "Ugyldig rapporttittel.",
  "orientation": "Retning",
  "pageSize": "Sidestørrelse",
  "comments": "Kommentarer",
  "choose_group": "Grupper",
  "forecast": "Prognose",
  "select_group": "Velg gruppe",
  "select_group_instruction": "Øyeblikksbildet opprettes og deles med den valgte gruppen",
  "information_append": " Informasjon",
  "distance": "AVSTAND",
  "buffer_invalid": "Angi et gyldig tall mellom ${min} og ${max}"
});