define({
  "_widgetLabel": "Panduan Tanggap Darurat",
  "ergMainPageTitle": "Berdasarkan Buku Panduan Tanggap Darurat 2016",
  "coordInputLabelStart": "Lokasi Tumpahan (DD)",
  "coordInputLabel": "Lokasi Tumpahan",
  "addPointToolTip": "Tambah Lokasi Tumpahan",
  "drawPointToolTip": "Klik untuk menambah lokasi tumpahan",
  "material": "Materi",
  "materialPlaceholder": "Mulai mengetik untuk mencari bahan",
  "table3Message": "Bahan yang Anda pilih memerlukan informasi tambahan jika Anda berurusan dengan tumpahan besar.\n\nHarap pastikan Anda memiliki nilai yang tepat dipilih untuk kecepatan angin dan kontainer pengangkut.",
  "table2Message": "Bahan yang Anda pilih mungkin menghasilkan gas Bahaya Inhalasi Beracun dalam jumlah besar jika tumpah ke air.\n\nAnda mungkin perlu mempertimbangkan penggunaan bahan berikut(s):\n\n",
  "spillSize": "Ukuran Tumpahan",
  "small": "Kecil",
  "large": "Besar",
  "fireLabel": "Perlihatkan Zona Isolasi Kebakaran",
  "weatherLabel": "Cuaca Saat Ini di Lokasi Tumpahan",
  "weatherIntialText": "<br />Diperbarui setelah lokasi tumpahan teridentifikasi",
  "temperature": "Suhu",
  "wind": "Angin",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Info cuaca tidak diperoleh. Perbarui nilai Kecepatan Angin dan Waktu Tumpahan secara manual",
  "windDirection": "Arah Angin (berembus ke)",
  "timeOfSpill": "Waktu Tumpahan",
  "day": "Hari",
  "night": "Malam",
  "windSpeed": "Kecepatan Angin",
  "low": "Rendah",
  "moderate": "Sedang",
  "high": "Tinggi",
  "transportContainer": "Kontainer Pengangkut",
  "rail": "Mobil tangki rel",
  "semi": "Truk atau trailer tangki jalan raya",
  "mton": "Silinder ton ganda",
  "ston": "Silinder kecil ganda atau silinder ton tunggal",
  "ag": "Tangki semaian pertanian",
  "msm": "Silinder kecil ganda",
  "bleveLabel": "Perlihatkan Zona Isolasi BLEVE",
  "capacity": "Kapasitas Kontainer (liter)",
  "bleveMessage": "Untuk bahan yang Anda pilih, jarak evakuasi tambahan dapat diperlihatkan untuk BLEVE.\n\nUntuk mengaktifkan ini, atur tombol Perlihatkan Zona Isolasi BLEVE ke aktif dan pilih kapasitas kontainer yang sesuai.",
  "noPAZoneMessage": "Tidak ada jarak Tindakan Protektif untuk bahan ini. Hanya Isolasi Awal dan zona evakuasi yang sudah dihitung",
  "settingsTitle": "Pengaturan",
  "spillLocationLabel": "Lokasi Tumpahan",
  "spillLocationButtonLabel": "Konfigurasikan Pengaturan Lokasi Tumpahan",
  "IISettingsLabel": "Zona Isolasi Awal",
  "IIButtonLabel": "Konfigurasikan Pengaturan Isolasi Awal",
  "PASettingsLabel": "Zona Tindakan Protektif",
  "PAButtonLabel": "Konfigurasikan Pengaturan Tindakan Protektif",
  "downwindSettingsLabel": "Zona Searah Angin",
  "downwindButtonLabel": "Konfigurasikan Pengaturan Searah Angin",
  "fireSettingsLabel": "Zona Isolasi Kebakaran",
  "fireButtonLabel": "Konfigurasikan Pengaturan Isolasi Kebakaran",
  "bleveSettingsLabel": "Zona Isolasi BLEVE",
  "bleveButtonLabel": "Konfigurasikan Pengaturan BLEVE",
  "style": "Gaya",
  "lineStyles": {
    "esriSLSDash": "Garis datar",
    "esriSLSDashDot": "Garis Datar Titik",
    "esriSLSDashDotDot": "Garis Datar Titik Titik",
    "esriSLSDot": "Titik",
    "esriSLSLongDash": "Garis Datar Panjang",
    "esriSLSLongDashDot": "Garis Datar Panjang Titik",
    "esriSLSNull": "Nol",
    "esriSLSShortDash": "Garis Datar Pendek",
    "esriSLSShortDashDot": "Garis Datar Pendek Titik",
    "esriSLSShortDashDotDot": "Garis Datar Pendek Titik Titik",
    "esriSLSShortDot": "Titik Pendek",
    "esriSLSSolid": "Padat"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Belakang",
    "esriSFSCross": "Silang",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Maju",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nol",
    "esriSFSSolid": "Padat",
    "esriSFSVertical": "Vertikal"
  },
  "resultsTitle": "Hasil",
  "publishERGBtn": "Publikasikan",
  "ERGLayerName": "Nama Layer ERG yang Dipublikasikan",
  "invalidERGLayerName": "Nama layer tidak boleh mengandung karakter alfa-numerik atau garis bawah",
  "missingERGLayerName": "Anda harus memasukkan nama untuk ERG",
  "publishingFailedLayerExists": "Publikasi Gagal: Anda telah memiliki feature service bernama {0}. Harap pilih nama lain.",
  "checkService": "Periksa Layanan: {0}",
  "createService": "Buat Layanan: {0}",
  "unableToCreate": "Tidak dapat membuat: {0}",
  "addToDefinition": "Tambahkan ke definisi: {0}",
  "successfullyPublished": "Berhasil memublikasikan layer web{0}Kelola layer web",
  "userRole": "Tidak dapat membuat layanan karena pengguna tidak memiliki izin",
  "transparency": "Transparansi",
  "outline": "Kerangka",
  "fill": "Isi (Warna hanya berlaku jika gaya diatur ke padat)",
  "createERGBtn": "Buat Zona",
  "clearERGBtn": "Hapus",
  "labelFormat": "Format Label",
  "helpIconTooltip": "Ambang batas antara ukuran tumpahan besar dan kecil adalah:\nCairan - 55 galon (208 liter)\nPadatan - 60 pon (300 kilogram)",
  "cellWidth": "Lebar Sel (x)",
  "cellHeight": "Tinggi Sel (y)",
  "invalidNumberMessage": "Nilai yang dimasukkan tidak valid",
  "invalidRangeMessage": "Nilai harus lebih besar dari 0",
  "gridAngleInvalidRangeMessage": "Nilai harus di antara -89,9 dan 89,9",
  "formatIconTooltip": "Format Input",
  "setCoordFormat": "Atur Format Koordinat String",
  "prefixNumbers": "Tambahkan awalan '+/-' untuk nomor positif dan negatif",
  "cancelBtn": "Batal",
  "applyBtn": "Terapkan",
  "comfirmInputNotation": "Konfirmasikan Notasi Input",
  "notationsMatch": "notasi sesuai dengan input Anda, harap konfirmasikan yang ingin Anda gunakan:",
  "missingLayerNameMessage": "Anda harus memasukkan nama layer yang valid sebelum publikasi dapat dilakukan",
  "parseCoordinatesError": "Tidak dapat mengurai koordinat. Harap periksa input Anda.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Derajat Desimal - Garis Lintang/Garis Bujur",
  "DDLongLatNotation": "Derajat Desimal - Garis Bujur/Garis Lintang",
  "DDMLatLongNotation": "Menit Derajat Desimal - Garis Lintang/Garis Bujur",
  "DDMLongLatNotation": "Menit Derajat Desimal - Garis Bujur/Garis Lintang",
  "DMSLatLongNotation": "Detik Derajat Desimal - Garis Lintang/Garis Bujur",
  "DMSLongLatNotation": "Detik Derajat Desimal - Garis Bujur/Garis Lintang",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisfer (N/S)"
});