define({
  "serviceUrl": "הגדר URL של שירות:",
  "minIntSpacingLabel": "גודל רשת מינימלי",
  "lineOpacityLabel": "אטימות קו",
  "labelOpacityLabel": "אטימות תווית",
  "centerLabelOpacityLabel": "אטימות תווית מרכזית",
  "gridZonePlacementLabel": "מיקום תווית באזורי רשת",
  "verticalLineLabels": "תוויות קו מאונכות",
  "styleHeaderLabel": "סגנון",
  "indexHeaderLabel": "רכיב רשת",
  "colorHeaderLabel": "צבע",
  "fontSizeHeaderLabel": "גודל גופן",
  "lineWidthHeaderLabel": "רוחב קו",
  "horizontalLabel": "אופקי",
  "verticalLabel": "אנכי",
  "upperLeftLabel": "שמאלית עליונה",
  "upperRightLabel": "ימנית עליונה",
  "lowerLeftLabel": "שמאלית תחתונה",
  "lowerRightLabel": "ימנית תחתונה",
  "centerLabel": "מרכז",
  "errorMessage": "דף התצורה מכיל שגיאות. יש לתקן אותן לפני השמירה.",
  "checkBoxLabel": "הצג גריד כאשר הווידג'ט סגור",
  "checkBoxLabelDashboard": "הצג רשת",
  "gzd": "מציין אזור רשת (GZD)",
  "gsid": "זיהוי ריבוע רשת (GSID) של 100,000 מטר",
  "grid10k": "קווי רשת של 10,000 מטר",
  "grid1k": "קווי רשת של 1,000 מטר",
  "grid100m": "קווי רשת של 100 מטר",
  "grid10m": "קווי רשת של 10 מטר",
  "switchBasemap": "החלף מפת בסיס"
});