define({
  "_widgetLabel": "緊急應變指南",
  "ergMainPageTitle": "根據緊急應變指南 2016",
  "coordInputLabelStart": "洩露位置 (DD)",
  "coordInputLabel": "洩露位置",
  "addPointToolTip": "新增洩露位置",
  "drawPointToolTip": "按一下以新增洩露位置",
  "material": "材料",
  "materialPlaceholder": "開始輸入以搜尋材質",
  "table3Message": "若是處理大型洩露，則已選擇的材質需要其他資訊。\n\n請確定為風速和運輸容器選擇正確值。",
  "table2Message": "您選擇的材料接觸到水份時可能會產生大量的「吸入中毒危險」氣體。\n\n您可能需要考慮使用下列材質:\n\n",
  "spillSize": "洩露大小",
  "small": "小",
  "large": "大",
  "fireLabel": "顯示防火隔離區",
  "weatherLabel": "洩露位置目前的天氣",
  "weatherIntialText": "<br />識別洩露位置後更新",
  "temperature": "溫度",
  "wind": "風",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "未取得天氣資訊。請手動更新「風速」和「洩露時間」值",
  "windDirection": "風向 (吹向)",
  "timeOfSpill": "洩露時間",
  "day": "天",
  "night": "夜晚",
  "windSpeed": "風速",
  "low": "低",
  "moderate": "中度",
  "high": "高",
  "transportContainer": "運輸容器",
  "rail": "鐵罐車",
  "semi": "公路油罐車或拖車",
  "mton": "多噸氣缸",
  "ston": "多個小氣缸或單噸氣缸",
  "ag": "農業儲罐",
  "msm": "多個小氣缸",
  "bleveLabel": "顯示 BLEVE 隔離區",
  "capacity": "容器容量 (公升)",
  "bleveMessage": "對於已選擇的材質，可針對 BLEVE 顯示其他疏散距離。\n\n要啟用此功能，請將「顯示 BLEVE 隔離區」開關設為開啟，然後選擇適當的容器容量。",
  "noPAZoneMessage": "此材質沒有「保護行動」距離。只有初始隔離和疏散區完成計算",
  "settingsTitle": "設定",
  "spillLocationLabel": "洩露位置",
  "spillLocationButtonLabel": "配置洩露位置設定",
  "IISettingsLabel": "初始隔離區",
  "IIButtonLabel": "配置初始隔離設定",
  "PASettingsLabel": "保護行動區域",
  "PAButtonLabel": "配置保護行動設定",
  "downwindSettingsLabel": "順風區",
  "downwindButtonLabel": "配置順風設定",
  "fireSettingsLabel": "防火隔離區",
  "fireButtonLabel": "配置防火隔離設定",
  "bleveSettingsLabel": "BLEVE 隔離區域",
  "bleveButtonLabel": "配置 BLEVE 設定",
  "style": "樣式",
  "lineStyles": {
    "esriSLSDash": "虛線",
    "esriSLSDashDot": "虛線點",
    "esriSLSDashDotDot": "虛線點點",
    "esriSLSDot": "點",
    "esriSLSLongDash": "長虛線",
    "esriSLSLongDashDot": "長虛線點",
    "esriSLSNull": "空",
    "esriSLSShortDash": "短虛線",
    "esriSLSShortDashDot": "短虛線點",
    "esriSLSShortDashDotDot": "短雙虛線點",
    "esriSLSShortDot": "短點",
    "esriSLSSolid": "實心"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向後",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "對角線",
    "esriSFSForwardDiagonal": "轉寄",
    "esriSFSHorizontal": "水平",
    "esriSFSNull": "空",
    "esriSFSSolid": "實心",
    "esriSFSVertical": "垂直"
  },
  "resultsTitle": "結果",
  "publishERGBtn": "發佈",
  "ERGLayerName": "發佈的 ERG 圖層名稱",
  "invalidERGLayerName": "圖層名稱只能包含英數字元和底線",
  "missingERGLayerName": "您必須輸入 ERG 的名稱",
  "publishingFailedLayerExists": "發佈失敗: 您已擁有名為 {0} 的圖徵服務。請選擇其他名稱。",
  "checkService": "檢查服務: {0}",
  "createService": "建立服務: {0}",
  "unableToCreate": "無法建立: {0}",
  "addToDefinition": "新增至定義: {0}",
  "successfullyPublished": "已成功發佈 Web 圖層{0}管理 Web 圖層",
  "userRole": "無法建立服務，因為使用者沒有權限",
  "transparency": "幻燈片",
  "outline": "清單",
  "fill": "填充 (將樣式設為實心時所套用的顏色)",
  "createERGBtn": "建立區域",
  "clearERGBtn": "清除",
  "labelFormat": "標籤格式",
  "helpIconTooltip": "少量洩漏和大量洩漏之間的閾值為：\n液體 - 55 加侖 (208 公升)\n固體 - 60 磅 (300 公斤)",
  "cellWidth": "儲存格寬度 (x)",
  "cellHeight": "儲存格高度 (y)",
  "invalidNumberMessage": "輸入的值無效",
  "invalidRangeMessage": "值必須大於 0",
  "gridAngleInvalidRangeMessage": "值必須在 -89.9 到 89.9 之間",
  "formatIconTooltip": "格式輸入",
  "setCoordFormat": "設定座標格式字串",
  "prefixNumbers": "新增 '+/-' 字首以變為正數和負數",
  "cancelBtn": "取消",
  "applyBtn": "套用",
  "comfirmInputNotation": "確認輸入標記法",
  "notationsMatch": "符合您輸入的標記法，請確認您要使用哪個標記法:",
  "missingLayerNameMessage": "您必須先輸入有效的圖層名稱，之後才能發佈",
  "parseCoordinatesError": "無法剖析座標。請檢查您的輸入。",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十進位度 - 緯度/經度",
  "DDLongLatNotation": "十進位度 - 經度/緯度",
  "DDMLatLongNotation": "度十進制分 - 緯度/經度",
  "DDMLongLatNotation": "度十進制分 - 經度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/經度",
  "DMSLongLatNotation": "度分秒 - 經度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 頻段字母",
  "UTMHemNotation": "UTM - 半球 (N/S)"
});