define({
  "chartSettingLabel": "Diagrammeinstellungen",
  "addNewLabel": "Neue hinzufügen",
  "generalSettingLabel": "Allgemeine Einstellungen",
  "searchSourceSettingLabel": "Einstellungen der Suchquellen",
  "layerChooser": {
    "title": "Layer zur Darstellung auswählen",
    "selectPolygonLayerLabel": "Layer auswählen",
    "selectPolygonLayerHintText": "Hinweis: Wenn Sie mehrere Diagramme darstellen, müssen die Layer denselben Geometrietyp aufweisen",
    "selectRelatedTableLayerLabel": "Mit Layer in Beziehung stehende Tabelle auswählen",
    "selectRelatedTableLayerHintText": "Hinweis: Nur Tabellen mit numerischen Feldern können angezeigt werden",
    "errorInSelectingPolygonLayer": "Wählen Sie einen Layer aus, der einen zugehörigen Punkt-Layer aufweist",
    "errorInSelectingRelatedLayer": "Wählen Sie eine(n) gültige(n) Tabelle/Layer aus, die/der mit dem Layer in Beziehung steht",
    "polygonLayerNotHavingRelationships": "Der ausgewählte Layer weist keine(n) zugehörige(n) Tabelle/Layer auf."
  },
  "ChartSetting": {
    "sectionTitle": "Abschnittstitel",
    "sectionTitleHintText": "Hinweis: Wird in der Überschrift (im Titel) des Abschnitts angezeigt",
    "chartTitle": "Diagrammtitel",
    "chartTitleHintText": "Hinweis: Wird zentriert über dem Diagramm angezeigt",
    "chartDescription": "Beschreibung",
    "chartDescriptionHintText": "Hinweis: Wird unter dem Diagramm angezeigt.",
    "chartType": "Diagrammtyp",
    "barChart": "Balkendiagramm",
    "pieChart": "Kreisdiagramm",
    "polarChart": "Polardiagramm",
    "dataSeriesField": "Datenreihenfeld",
    "labelField": "Beschriftungsfeld",
    "chartColor": "Diagrammfarbe",
    "singleColor": "Einzelfarbe",
    "colorByTheme": "Farbe nach Design",
    "colorByFieldValue": "Farbe nach Feldwert",
    "xAxisTitle": "Titel der X-Achse",
    "xAxisHintText": "Hinweis: Titel der X-Achse",
    "yAxisTitle": "Titel der Y-Achse",
    "yAxisHintText": "Hinweis: Titel der Y-Achse",
    "fieldColorLabel": "Beschriftung",
    "fieldColorColor": "Farbe",
    "defaultFieldSelectLabel": "Auswählen",
    "errMsgFieldValuesNotFound": "Für das ausgewählte Feld konnten keine Werte gefunden werden.",
    "errMsgSectionTitle": "Geben Sie den Abschnittstitel ein.",
    "errMsgFieldByValue": "Wählen Sie den Feldwert aus.",
    "settingTabTitle": "Einstellung",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Hinweis: Wählen Sie zum Erstellen des Polardiagramms Felder aus.",
    "visibilityText": "Sichtbarkeit",
    "fieldNameText": "Feldname",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Wählen Sie mindestens drei Felder zum Erstellen des Polardiagramms aus.",
    "polarChartPolygonFillLabel": "Füllpolygon",
    "polarChartPolygonFillHintText": "Hinweis: Aktivieren Sie das Kontrollkästchen, um die Polygonfüllung im Polardiagramm anzuzeigen.",
    "viewLayoutLabel": "Layout",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Allgemeine Einstellungen",
    "locationSymbolLabel": "Symbol für grafische Position",
    "locationSymbolHintText": "Hinweis: Wird zum Anzeigen eines Symbols für die Adresse und aktivierte Position verwendet",
    "refreshIntervalLabel": "Aktualisierungsintervall",
    "refreshIntervalHintText": "Hinweis: Wird zum Aktualisieren von Diagrammen basierend auf diesem Intervall verwendet. Geben Sie einen Wert zwischen 1 und 1440 Minuten ein.",
    "errMsgRefreshInterval": "Legen Sie das Aktualisierungsintervall auf einen Wert zwischen 0 und 1440 Minuten fest.",
    "symbolPickerPreviewText": "Vorschau:",
    "showToolToSelectLabel": "Schaltfläche \"Position festlegen\"",
    "showToolToSelectHintText": "Hinweis: Stellt eine Schaltfläche zum Festlegen der Position auf der Karte bereit, statt die Position bei jedem Klicken auf die Karte festzulegen."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Einstellungen der Suchquellen",
    "searchSourceSettingTitle": "Einstellungen der Suchquellen",
    "searchSourceSettingTitleHintText": "Fügen Sie Geokodierungsservices oder Feature-Layer als Suchquellen hinzu, und konfigurieren Sie diese. Anhand dieser angegebenen Quellen wird bestimmt, welche Elemente im Suchfeld durchsucht werden können.",
    "addSearchSourceLabel": "Suchquelle hinzufügen",
    "featureLayerLabel": "Feature-Layer",
    "geocoderLabel": "Geocoder",
    "nameTitle": "Name",
    "generalSettingLabel": "Allgemeine Einstellung",
    "allPlaceholderLabel": "Platzhaltertext für die Suche in allen Quellen:",
    "allPlaceholderHintText": "Hinweis: Geben Sie den Platzhaltertext für die Suche in allen Layern und Geocodern ein.",
    "generalSettingCheckboxLabel": "Pop-up für das gefundene Feature oder die gefundene Position anzeigen",
    "countryCode": "Länder- oder Regionscode(s)",
    "countryCodeEg": "z. B. ",
    "countryCodeHint": "Wenn dieser Wert leer gelassen wird, werden alle Länder und Regionen durchsucht.",
    "questionMark": "verwendet werden?",
    "searchInCurrentMapExtent": "Nur in der aktuellen Kartenausdehnung suchen",
    "zoomScale": "Zoom-Maßstab",
    "locatorUrl": "Geocoder-URL",
    "locatorName": "Geocoder-Name",
    "locatorExample": "Beispiel",
    "locatorWarning": "Diese Version des Geokodierungsservice wird nicht unterstützt. Das Widget unterstützt Geokodierungsservices der Version 10.0 und höher.",
    "locatorTips": "Es sind keine Vorschläge verfügbar, da der Geokodierungsservice die Vorschlagsfunktion nicht unterstützt.",
    "layerSource": "Layer-Quelle",
    "setLayerSource": "Layer-Quelle festlegen",
    "setGeocoderURL": "Geocoder-URL festlegen",
    "searchLayerTips": "Es sind keine Vorschläge verfügbar, da der Feature-Service die Paginierungsfunktion nicht unterstützt.",
    "placeholder": "Platzhaltertext",
    "searchFields": "Suchfelder",
    "displayField": "Anzeigefeld",
    "exactMatch": "Exakte Übereinstimmung",
    "maxSuggestions": "Maximale Anzahl von Vorschlägen",
    "maxResults": "Maximale Anzahl von Ergebnissen",
    "enableLocalSearch": "Lokale Suche aktivieren",
    "minScale": "Min. Maßstab",
    "minScaleHint": "Wenn der Kartenmaßstab größer ist als dieser Maßstab, wird die lokale Suche angewendet.",
    "radius": "Radius",
    "radiusHint": "Ermöglicht die Festlegung des Radius einer Fläche um den aktuellen Kartenmittelpunkt, der dazu dient, die Rangfolge von Geokodierungskandidaten zu optimieren. Die Kandidaten, die der Position am nächsten liegen, werden auf diese Weise zuerst ausgegeben.",
    "meters": "Meter",
    "setSearchFields": "Suchfelder festlegen",
    "set": "Festlegen",
    "fieldName": "Name",
    "invalidUrlTip": "Die URL ${URL} ist ungültig oder es kann nicht darauf zugegriffen werden."
  }
});