define({
  "layerSelect": "Atlasīt attēla slāni",
  "displayMeasureResultInPopup": "Mērīšanas rezultātus rādīt uznirstošajā logā",
  "angularUnitSelect": "Noklusējuma leņķveida vienība",
  "linearUnitSelect": "Noklusējuma lineārā vienība",
  "areaUnitSelect": "Noklusējuma laukuma vienība",
  "displayOperationSelect": "Izvēlēties mērīšanas darbības",
  "errorSectionMessage": "Neviens slānis neatbalsta mērīšanas iespējas.",
  "unitLabel": {
    "esriInches": "Collas",
    "esriFeet": "Pēdas",
    "esriYards": "Jardi",
    "esriMiles": "Jūdzes",
    "esriNauticalMiles": "Jūras jūdzes",
    "esriMillimeters": "Milimetri",
    "esriCentimeters": "Centimetri",
    "esriDecimeters": "Decimetri",
    "esriMeters": "Metri",
    "esriKilometers": "Kilometri",
    "esriDURadians": "Radiāni",
    "esriDUDecimalDegrees": "Grādi",
    "esriSquareInches": "Kvadrātcollas",
    "esriSquareFeet": "Kv. pēdas",
    "esriSquareYards": "Kv. jardi",
    "esriAcres": "Akri",
    "esriSquareMiles": "Kv. jūdzes",
    "esriSquareMillimeters": "Kvadrātmilimetri",
    "esriSquareCentimeters": "Kvadrātcentimetri",
    "esriSquareDecimeters": "Kvadrātdecimetri",
    "esriSquareMeters": "Kv. metri",
    "esriAres": "Laukumi",
    "esriHectares": "Hektāri",
    "esriSquareKilometers": "Kv. kilometri"
  },
  "operationLabel": {
    "esriMensurationPoint": "Novietojums",
    "esriMensurationDistanceAndAngle": "Attālums un leņķis",
    "esriMensurationAreaAndPerimeter": "Laukums un perimetrs",
    "esriMensurationHeightFromBaseAndTop": "Augstums: no pamatnes līdz augšai",
    "esriMensurationHeightFromBaseAndTopShadow": "Augstums: no pamatnes līdz augšas ēnai",
    "esriMensurationHeightFromTopAndTopShadow": "Augstums: no augšas līdz augšas ēnai",
    "esriMensurationCentroid": "Centroīds",
    "esriMensurationPoint3D": "Novietojums (3D)",
    "esriMensurationDistanceAndAngle3D": "Attālums un leņķis (3D)",
    "esriMensurationAreaAndPerimeter3D": "Laukums un perimetrs (3D)",
    "esriMensurationCentroid3D": "Centroīds (3D)"
  }
});