define({
  "_widgetLabel": "Rīcības ārkārtas situācijās norādījumi",
  "ergMainPageTitle": "Pamatojoties uz rīcības ārkārtas situācijās ceļvedi 2016",
  "coordInputLabelStart": "Noplūdes novietojums (DD)",
  "coordInputLabel": "Noplūdes novietojums",
  "addPointToolTip": "Pievienot noplūdes novietojumu",
  "drawPointToolTip": "Noklikšķiniet, lai pievienotu noplūdes novietojumu",
  "material": "Materiāls",
  "materialPlaceholder": "Sāciet rakstīt, lai meklētu materiālu",
  "table3Message": "Izvēlētajam materiālam ir nepieciešama papildinformācija, ja ir radusies liela noplūde.\n\nLūdzu, pārliecinieties, vai izvēlējāties pareizās vēja ātruma un transporta tvertnes vērtības.",
  "table2Message": "Izvēlētais materiāls var radīt liela apjoma toksiskas ieelpošanas bīstamības gāzes, ja tas noplūst ūdenī.\n\nIespējams, vēlēsities apsvērt iespēju izmantot šādus materiālus:\n\n",
  "spillSize": "Noplūdes izmērs",
  "small": "Maza",
  "large": "Liela",
  "fireLabel": "Rādīt uguns izolācijas zonu",
  "weatherLabel": "Pašreizējie laika apstākļi noplūdes novietojumā",
  "weatherIntialText": "<br />Atjaunots, tiklīdz ir noteikts noplūdes novietojums",
  "temperature": "Temperatūra",
  "wind": "Vējš",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Laika apstākļu informācija nav iegūta. Atjaunojiet vēja ātruma un noplūdes laika vērtības manuāli",
  "windDirection": "Vēja virziens (uz kurieni pūš)",
  "timeOfSpill": "Noplūdes laiks",
  "day": "Diena",
  "night": "Nakts",
  "windSpeed": "Vēja ātrums",
  "low": "Mazs",
  "moderate": "Vidējs",
  "high": "Liels",
  "transportContainer": "Transporta tvertne",
  "rail": "Dzelzceļa cisterna",
  "semi": "Cisternas automašīna vai piekabe",
  "mton": "Vairāki tonnas cilindri",
  "ston": "Vairāki mazi cilindri vai viens tonnas cilindrs",
  "ag": "Lauksaimniecības cisterna",
  "msm": "Vairāki mazi cilindri",
  "bleveLabel": "Rādīt BLEVE izolācijas zonu",
  "capacity": "Tvertnes ietilpība (litri)",
  "bleveMessage": "Izvēlētajam materiālam BLEVE vajadzībām var rādīt papildu evakuācijas attālumu.\n\nLai to aktivizētu, ieslēdziet pārslēgu Rādīt BLEVE izolācijas zonu un izvēlieties atbilstošo tvertnes ietilpību.",
  "noPAZoneMessage": "Šim materiālam nav aizsardzības darbību attālumu. Var aprēķināt tikai sākotnējās izolācijas un evakuācijas zonu",
  "settingsTitle": "Iestatījumi",
  "spillLocationLabel": "Noplūdes novietojums",
  "spillLocationButtonLabel": "Konfigurēt noplūdes novietojuma iestatījumus",
  "IISettingsLabel": "Sākotnējās izolācijas zona",
  "IIButtonLabel": "Konfigurēt sākotnējās izolācijas iestatījumus",
  "PASettingsLabel": "Aizsardzības darbību zona",
  "PAButtonLabel": "Konfigurēt aizsardzības darbību iestatījumus",
  "downwindSettingsLabel": "Zona vēja virzienā",
  "downwindButtonLabel": "Konfigurēt vēja virziena iestatījumus",
  "fireSettingsLabel": "Uguns izolācijas zona",
  "fireButtonLabel": "Konfigurēt uguns izolācijas iestatījumus",
  "bleveSettingsLabel": "BLEVE izolācijas zona",
  "bleveButtonLabel": "Konfigurēt BLEVE iestatījumus",
  "style": "Stils",
  "lineStyles": {
    "esriSLSDash": "Svītra",
    "esriSLSDashDot": "Svītra punkts",
    "esriSLSDashDotDot": "Svītra punkts punkts",
    "esriSLSDot": "Punkts",
    "esriSLSLongDash": "Gara svītra",
    "esriSLSLongDashDot": "Gara svītra punkts",
    "esriSLSNull": "Nulle",
    "esriSLSShortDash": "Īsa svītra",
    "esriSLSShortDashDot": "Īsa svītra punkts",
    "esriSLSShortDashDotDot": "Īsa svītra punkts punkts",
    "esriSLSShortDot": "Īsa svītra",
    "esriSLSSolid": "Tīrtoņa"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atpakaļvērsts",
    "esriSFSCross": "Krusts",
    "esriSFSDiagonalCross": "Diagonāls",
    "esriSFSForwardDiagonal": "Uz priekšu",
    "esriSFSHorizontal": "Horizontāli",
    "esriSFSNull": "Nulle",
    "esriSFSSolid": "Tīrtoņa",
    "esriSFSVertical": "Vertikāli"
  },
  "resultsTitle": "Rezultāti",
  "publishERGBtn": "Publicēt",
  "ERGLayerName": "Publicētā ERG slāņa nosaukums",
  "invalidERGLayerName": "Slāņa nosaukums var saturēt tikai burtu un ciparu rakstzīmes, kā arī pasvītrojumus.",
  "missingERGLayerName": "Ievadiet ERG nosaukumu",
  "publishingFailedLayerExists": "Publicēšanas neveiksme: jums jau ir elementu serviss ar nosaukumu {0}. Lūdzu, izvēlieties citu nosaukumu.",
  "checkService": "Pārbaudīt servisu: {0}.",
  "createService": "Izveidot servisu: {0}",
  "unableToCreate": "Nevar izveidot: {0}",
  "addToDefinition": "Pievienot definīcijai: {0}",
  "successfullyPublished": "Veiksmīgi publicēts tīmekļa slānis{0}Pārvaldīt tīmekļa slāni",
  "userRole": "Nevar izveidot servisu, jo lietotājam nav atļauju",
  "transparency": "Caurspīdīgums",
  "outline": "Kontūra",
  "fill": "Pildījums (krāsa tiek lietota tikai tad, ja iestatīts tīrtoņa stils)",
  "createERGBtn": "Izveidot zonas",
  "clearERGBtn": "Notīrīt",
  "labelFormat": "Nosaukuma formāts",
  "helpIconTooltip": "Sliekšņvērtība starp mazu un lielu noplūdi ir:\nŠķidrumiem — 55 galoni (208 litri)\nCietām vielām — 60 mārciņas (300 kilogrami)",
  "cellWidth": "Šūnas platums (x)",
  "cellHeight": "Šūnas augstums (y)",
  "invalidNumberMessage": "Ievadītā vērtība nav derīga",
  "invalidRangeMessage": "Vērtībai jābūt lielākai par 0",
  "gridAngleInvalidRangeMessage": "Vērtībai ir jābūt no -89,9 līdz 89,9",
  "formatIconTooltip": "Formatēt ievadi",
  "setCoordFormat": "Iestatīt koordinātu formātu virkni",
  "prefixNumbers": "Pievienot prefiksu '+/-' pozitīviem un negatīviem skaitļiem",
  "cancelBtn": "Atcelt",
  "applyBtn": "Lietot",
  "comfirmInputNotation": "Apstiprināt ievades notāciju",
  "notationsMatch": "notācijas atbilst jūsu ievadei. Lūdzu, apstipriniet, kuras vēlaties izmantot:",
  "missingLayerNameMessage": "Lai varētu publicēt, ir jāievada derīgs slāņa nosaukums",
  "parseCoordinatesError": "Nevar parsēt koordinātas. Lūdzu, pārbaudiet ievadi.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "GMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimālgrādi — platums/garums",
  "DDLongLatNotation": "Decimālgrādi — garums/platums",
  "DDMLatLongNotation": "Grādi, decimālminūtes — platums/garums",
  "DDMLongLatNotation": "Grādi, decimālminūtes — garums/platums",
  "DMSLatLongNotation": "Grādi, minūtes, sekundes — platums/garums",
  "DMSLongLatNotation": "Grādi, minūtes, sekundes — garums/platums",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — joslas burts",
  "UTMHemNotation": "UTM — puslode (Z/D)"
});