define({
  "add": "Klik untuk menambahkan baru",
  "title": "Judul",
  "placeholderBookmarkName": "Nama penanda lokasi",
  "ok": "Ya",
  "cancel": "Batal",
  "warning": "Harap selesaikan edit!",
  "edit": "Edit penanda lokasi",
  "errorNameExist": "Penanda Lokasi ada!",
  "errorNameNull": "Nama penanda lokasi tidak valid!",
  "addBookmark": "Buat baru",
  "thumbnail": "Thumbnail",
  "thumbnailHint": "Klik gambar untuk memperbarui",
  "displayBookmarksAs": "Tampilkan penanda lokasi sebagai",
  "cards": "Kartu",
  "list": "Daftar",
  "cardsTips": "Tampilan kartu",
  "listTips": "Tampilan daftar",
  "makeAsDefault": "Jadikan sebagai default",
  "default": "Default",
  "editable": "Izinkan untuk menambahkan penanda lokasi di widget.",
  "alwaysSync": "Tampilkan penanda lokasi dari peta web",
  "configCustom": "Tampilkan penanda lokasi kustom",
  "import": "Impor",
  "create": "Buat",
  "importTitle": "Impor Penanda Lokasi",
  "importFromWeb": "Impor Penanda Lokasi dari peta web saat ini",
  "selectAll": "Pilih Semua",
  "noBookmarkInConfig": "Klik â€œImporâ€ atau â€œBuat Baruâ€ untuk menambahkan penanda lokasi.",
  "noBookmarkInWebMap": "Tidak ada penanda lokasi yang dikonfigurasi di peta.",
  "extent": "Jangkauan",
  "saveExtent": "Simpan jangkauan peta ke penanda lokasi ini",
  "savelayers": "Simpan visibilitas layer",
  "withVisibility": "Dengan visibilitas layer",
  "bookmark": "Penanda Lokasi",
  "addBtn": "Tambah",
  "deleteBtn": "Hapus",
  "editBtn": "Edit",
  "dragReorderTip": "Tahan dan seret untuk mengurutkan ulang",
  "deleteBtnTip": "Hapus penanda lokasi",
  "editBtnTip": "Edit penanda lokasi"
});