define({
  "labelBookmarkName": "Označi trenuten pogled",
  "labelPlay": "Predvajaj vse",
  "labelStop": "Ustavi",
  "labelDelete": "Izbriši",
  "placeholderBookmarkName": "Ime zaznamka",
  "errorNameExist": "Zaznamek obstaja!",
  "errorNameNull": "Neveljavno ime zaznamka!",
  "editTip": "Uredi zaznamke",
  "exitEditTip": "Zapri način urejanja",
  "syncTip": "Sinhroniziraj",
  "cardsTips": "Mrežni pogled",
  "listTips": "Pogled seznama",
  "addBtn": "Dodaj dvojnik izbrane drsnice k predstavitvi.",
  "deleteBtn": "Izbriši",
  "changeThumbnailTip": "Spremeni sličico",
  "dragReorderTip": "Drži in povleci za spremembo vrstnega reda",
  "deleteBtnTip": "Izbriši zaznamek",
  "editBtnTip": "Uredi zaznamek",
  "withVisibility": "Z vidnostjo sloja",
  "searchBookmark": "Išči",
  "bookmarksFromConfig": "Predkonfigurirani zaznamki",
  "bookmarksFromCache": "Lokalni začasni zaznamki",
  "notice": "Obvestilo",
  "changeNoticeTips": "Spremembe bodo shranjene samo v predpomnilniku vašega brskalnika. Sinhronizacija med pripomočkom in njegovo konfiguracijo se prekine, ko izvedete spremembe.",
  "syncNoticeTips": "To bo izbrisalo vse vaše spremembe in obnovilo konfigurirane zaznamke.",
  "dontShowAgain": "Ne prikaži znova",
  "saveVisibility": "Shrani vidnost sloja",
  "_widgetLabel": "Zaznamek"
});