define({
  "tabs_section_Label": "选项卡",
  "addTab": "添加选项卡",
  "layerName": "图层",
  "layerType": "分析类型",
  "layerLabel": "标注",
  "actions": "操作",
  "closest": "最近要素",
  "proximity": "邻近",
  "summary": "汇总",
  "select_lbl": "-- 选择 --",
  "general_setting_Label": "常规设置",
  "units_text_lbl": "距离单位",
  "maximum_distance_lbl": "最近要素的最大距离",
  "buffer_text_lbl": "缓冲标注",
  "buffer_lbl": "缓冲距离",
  "buffer_max_lbl": "最大缓冲距离",
  "buffer_min_lbl": "最小缓冲距离",
  "buffer_default_lbl": "默认缓冲距离",
  "not_less_than_max": "距离必须小于最大缓冲距离",
  "not_between": "距离必须介于最小和最大缓冲距离之间",
  "not_more_than_min": "距离必须大于最小缓冲距离",
  "not_valid_number": "必须为有效数字",
  "invalid_value": "${type} 值无效",
  "routing_checkBox": "启用路径查找",
  "weather_Label": "天气设置",
  "weather_checkBox": "启用天气",
  "weather_map_layers": "选择天气图层...",
  "selected_map_layers": " 所选天气图层",
  "instruction_weather": "在面板中显示天气信息。",
  "instruction_weather_layers": "显示其他天气图层。",
  "instruction_weather_metric": "显示标准/公制值。",
  "selectLayers": "选择天气图层",
  "weather_removed_message": "天气选项不再可用于此微件。",
  "currentlySelectedLayer": "从地图图层选择",
  "missingTabLabel": "至少一个选项卡缺失标注",
  "missingLayerInWebMap": "未找到业务图层。",
  "selectFields": "选择字段",
  "addField": "添加字段",
  "sum": "总和",
  "min": "最小值",
  "max": "最大值",
  "avg": "平均值",
  "count": "计数",
  "area": "面积",
  "length": "长度",
  "count_checkBox": "显示要素计数",
  "area_checkBox": "显示面积总和",
  "length_checkBox": "显示长度总和",
  "max_records": "已达到最大限制",
  "save_label": "保存选项",
  "save_checkbox": "启用保存",
  "report_label": "报表选项",
  "report_checkbox": "启用报表",
  "csv_label": "CSV 选项",
  "csv_checkbox": "导出所有字段",
  "display_label": "显示选项",
  "display_checkbox": "显示汇总要素",
  "snapshot_label": "快照选项",
  "snapshot_checkbox": "启用快照",
  "must_select_template": "请在保存选项中选择一个编辑模板。",
  "count_label": "计数标注",
  "area_label": "面积标注",
  "length_label": "长度标注",
  "invalid_string_width": "值过长。 ",
  "layer_type_not_supported": "不支持图层类型",
  "groupedSummary": "已分组计数",
  "groupByField": "按字段分组",
  "labelType": "追加标注",
  "prefix": "作为前缀",
  "suffix": "作为后缀",
  "need_group_field": "请使用编辑操作来定义按字段分组。",
  "fieldTitle": "字段",
  "typeTitle": "类型",
  "actionsTitle": "操作",
  "save_point_checkbox": "保存点",
  "save_line_checkbox": "保存线",
  "save_poly_checkbox": "保存面",
  "no_valid_popup_fields": "弹出窗口中无有效字段。请使用编辑操作定义字段。",
  "no_valid_fields": "无有效字段。请使用编辑操作定义显示选项。",
  "incident_label": "选项卡标注",
  "locate_incident_label": "感兴趣区标注",
  "incident": "事件点",
  "locate_incident": "查找事件点",
  "buffer_value": "缓冲距离",
  "tab_options": "分析",
  "export_options": "输出",
  "instruction_save": "将位置保存到要素服务。",
  "instruction_snapshot": "基于位置创建 webmap。",
  "instruction_report": "创建位置的打印报表。",
  "instruction_all_fields": "使用 CSV 下载导出所有字段。",
  "data_label": "数据输出设置",
  "layer_error": "图层丢失或无效。",
  "visibility_checkBox": "禁用图层可见性管理",
  "downloadTab": {
    "reportLegend": "报告设置",
    "textColorLabel": "选择列标题的颜色",
    "setButtonLabel": "设置",
    "printGPServiceLabel": "打印服务 URL",
    "logoLabel": "徽标",
    "logoChooserHint": "单击图像图标可更改图像",
    "footnoteLabel": "脚注"
  }
});