define({
  "_widgetLabel": "Neprekidan protok podataka",
  "streamControls": "Kontrole striminga",
  "streamFilter": "Filter",
  "startStreaming": "Pokreni striming",
  "stopStreaming": "Zaustavi striming",
  "streamLayers": "Slojevi sa neprekidnim protokom podataka",
  "startStopStream": "Omogući opciju „Pokreni striming“ ili „Zaustavi striming“",
  "clearStream": "Omogući opciju „Obriši prethodne opservacije“",
  "attributeFilter": "Omogući filter po atributima",
  "spatialFilter": "Omogući prostorni filter",
  "configFilter": "Konfiguriši filter po atributima sa neprekidnim protokom podataka",
  "drawPrevious": "Omogući opciju „Crtaj prethodne opservacije“",
  "addNew": "Dodaj filter",
  "setFilterName": "Postavi ime filtera",
  "filterNameExists": "Ime filtera postoji u tabeli!",
  "invalidFilterName": "Ime treba da bude reč koja sadrži a-z, A-Z, 0-9 ili _.",
  "noFilterTip": "Nema konfigurisanog filtera",
  "addFilterFailed": "Dodavanje filtera nije uspelo",
  "filterName": "Ime filtera",
  "limitMapExtent": "Ograniči opservacije u površini trenutne mape",
  "limitDrawExtent": "Ograniči opservacije u površini definisanoj od strane korisnika",
  "newFilter": "Novi filter",
  "filterReadOnly": "Filter preuzet iz veb mape je samo za čitanje."
});