define({
  "settings": "Einstellungen",
  "titleSettings": "Texteinstellungen",
  "imageSettings": "Bildeinstellungen",
  "backgroundColor": "Hintergrundfarbe",
  "alignment": "Ausrichtung",
  "textSize": "Textgröße",
  "textColor": "Textfarbe",
  "dataSource": "Datenquelle",
  "chartSettings": "Diagrammeinstellungen",
  "data": "Daten",
  "dataLabels": "Datenbeschriftungen",
  "displayMode": "Anzeigemodus",
  "featureOption": "Werte auf Feature-Ebene anzeigen",
  "categoryOption": "Werte nach Kategorie anzeigen",
  "countOption": "Feature-Anzahl nach Kategorie anzeigen",
  "fieldOption": "Attributwerte als Diagramme anzeigen",
  "categoryField": "Kategoriefeld",
  "labelField": "Beschriftungsfeld",
  "valueFields": "Wertefelder",
  "operation": "Operation",
  "sumOption": "Summe",
  "averageOption": "Durchschnitt",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "dataFormat": "Datenformat",
  "decimalPlaces": "Dezimalstellen",
  "prefix": "Präfix",
  "suffix": "Suffix",
  "dataType": "Datentyp",
  "featureCount": "Feature-Anzahl",
  "fieldStatistics": "Feldstatistik",
  "display": "Anzeige",
  "chartColor": "Diagrammfarbe",
  "horizontalAxis": "Horizontale Achse",
  "verticalAxis": "Vertikale Achse",
  "legend": "Legende",
  "position": "Position",
  "top": "Oben",
  "bottom": "Unten",
  "useDataSourceSelection": "Auswahl verwenden",
  "dataSourceFilterByExtent": "Nach Ausdehnung filtern",
  "changeTemplate": "Vorlage ändern",
  "numberSettings": "Einstellungen für Zahlen",
  "gaugeSettings": "Skaleneinstellungen",
  "indicators": "Indikatoren",
  "ifValue": "Wenn Wert",
  "and": "und",
  "numberOperatorIsLessThan": "ist kleiner als",
  "numberOperatorIsGreaterThan": "ist größer als",
  "numberOperatorIsBetween": "liegt zwischen",
  "numberOperatorIsEqual": "ist gleich",
  "numberOperatorIsNotEqual": "ist nicht gleich",
  "then": "Dann",
  "ratio": "Verhältnis",
  "trueValue": "Wahrer Wert",
  "changeValueColor": "Farbe des Werts ändern in",
  "changeGaugeColor": "Farbe der Skala ändern in",
  "setIndicatorIcon": "Indikatorsymbol festlegen als",
  "icons": "Symbole",
  "style": "Style",
  "placement": "Platzierung",
  "left": "Links",
  "replace": "Ersetzen",
  "right": "Rechts",
  "color": "Farbe",
  "categoryExists": "Kategorie ist vorhanden!",
  "comboxHint": "Eine eingeben oder auswählen",
  "comboxDisableInputHint": "Eine auswählen",
  "sortBy": "Sortieren nach",
  "labelAxis": "Beschriftung",
  "valueAxis": "Wert",
  "minPeriod": "Mindestzeitraum",
  "automatic": "Automatisch",
  "periodsWithOutRecords": "Zeiträume ohne Datensätze",
  "nullValue": "NULL-Wert",
  "calculatedAsZero": "Als Null berechnet",
  "ignored": "Ignoriert",
  "maxCategories": "Maximale Kategorien",
  "useLayerSymbology": "Layer-Symbolisierung verwenden",
  "hollowsize": "Größe des ungefüllten Bereichs",
  "splitField": "Split-Feld",
  "parsingperiodTip": "Konnte nicht berechnet werden. Zu viele Zeitintervalle aufgrund des kurzen Analysezeitraums.",
  "manyCategoryTip": "Das Diagramm konnte nicht angezeigt werden. Zu viele Kategorien.",
  "setColor": "Farbe festlegen",
  "setTheColorOf": "Dann Farbe festlegen für",
  "setTheColorAs": "Dann Farbe festlegen als",
  "ifStr": "Wenn",
  "as": "als",
  "is": "ist",
  "isNot": "ist nicht",
  "barCluster": "Balken-Cluster",
  "individualBar": "einzelner Balken",
  "allOthers": "Alle anderen",
  "category": "Kategorie",
  "indicatorSum": "SUM",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Legen Sie die Indikatoren ordnungsgemäß fest.",
  "dataRange": "Datenbereich",
  "targetValue": "Zielwert",
  "currentValue": "Aktueller Wert",
  "gaugeColor": "Farbe der Skala",
  "min": "Minimum",
  "max": "Maximum",
  "displayValueIn": "Wert anzeigen als",
  "noData": "Keine Daten",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Warnung",
  "noSettingWaring1": "Klicken Sie auf ein Element, um dessen Eigenschaften festzulegen.",
  "noSettingWaring2": "Zum Anpassen der Größe oder Neuanordnen eines Elements ziehen.",
  "donNotShowAgain": "Nicht erneut anzeigen",
  "changeTemplateWarning": "Damit werden alle Ihre Einstellungen gelöscht und es wird eine neue, leere Vorlage geöffnet.",
  "requiredFieldWarning": "Dieser Wert ist erforderlich:",
  "dataSourceNotSet": "Legen Sie die Datenquelle fest.",
  "addIndicatorTip": "Indikator hinzufügen",
  "chooseTemplatePopupTitle": "Vorlage auswählen",
  "filterExtentTipWithaTag": "Sie können die Option zum Filtern nach <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Zusätzliche Datenquelle</a> auf der Registerkarte \"Attribut\" deaktivieren.",
  "filterExtentTip": "Sie können die Option zum Filtern nach \"Zusätzliche Datenquelle\" auf der Registerkarte \"Attribut\" deaktivieren.",
  "customColorByCategory": "Benutzerdefinierte Farbe nach Kategorie",
  "randomColor": "Zufällige Farbe",
  "valueString": "Wert",
  "fieldString": "Feld",
  "includeThresholdValue": "Grenzwert einbeziehen",
  "percentage": "Prozentsatz",
  "colorSchema": "Farbschema",
  "addCategory": "Kategorie hinzufügen",
  "clickToEdit": "Zum Bearbeiten klicken",
  "nullText": "Null",
  "others": "Andere",
  "stringsInTemplate": {
    "name_number": "Zahl",
    "name_gauge": "Skala",
    "name_vertical_gauge": "Vertikale Skala",
    "name_horizontal_gauge": "Horizontale Skala",
    "name_pie": "Kreis",
    "name_donut": "Kreisring",
    "name_bar": "Balken",
    "name_stacked_bar": "Gestapelter Balken",
    "name_percentage_stacked_bar": "Prozentsatz gestapelter Balken",
    "name_column": "Spalte",
    "name_stacked_column": "Gestapelte Spalte",
    "name_percentage_stacked_column": "Prozentsatz gestapelte Spalte",
    "name_line": "Linie",
    "name_area": "Fläche",
    "name_stacked_area": "Gestapelte Fläche",
    "name_percentage_stacked_area": "Prozentsatz gestapelte Fläche",
    "titleOfTheInfographic": "TITEL DER INFOGRAFIK",
    "description": "Beschreibung: zusätzliche Informationen über diese Infografik."
  }
});