define({
  "_widgetLabel": "Akıt",
  "streamControls": "Akış kontrolleri",
  "streamFilter": "Filtrele",
  "startStreaming": "Akışı başlat",
  "stopStreaming": "Akışı durdur",
  "streamLayers": "Akış katmanları",
  "startStopStream": "Akışı durdur veya Akışı başlat seçeneklerini etkinleştir",
  "clearStream": "Önceki gözlemleri temizle seçeneğini etkinleştir",
  "attributeFilter": "Öznitelik filtresini etkinleştir",
  "spatialFilter": "Mekansal filtreyi etkinleştir",
  "configFilter": "Akış özniteliği filtresini yapılandır",
  "drawPrevious": "Önceki gözlemleri çiz seçeneğini etkinleştir",
  "addNew": "Filtre ekle",
  "setFilterName": "Filtre adını ayarla",
  "filterNameExists": "Filtre adı tabloda mevcut!",
  "invalidFilterName": "Ad a-z, A-Z, 0-9 veya _ içeren bir sözcük olmalıdır.",
  "noFilterTip": "Yapılandırılan filtre yok",
  "addFilterFailed": "Filtre eklenemedi",
  "filterName": "Filtre adı",
  "limitMapExtent": "Gözlemleri geçerli harita alanında sınırla",
  "limitDrawExtent": "Gözlemleri kullanıcı tanımlı alanda sınırla",
  "newFilter": "Yeni filtre",
  "filterReadOnly": "We haritasından devralınan filtre salt okunur."
});