define({
  "queries": "Upiti",
  "addNew": "Dodaj novi",
  "newQuery": "Novi upit",
  "queryLayer": "Sloj upita",
  "setSource": "Postavi",
  "setDataSource": "Postavite izvor podataka",
  "name": "Naziv",
  "querySource": "Izvor podataka",
  "queryName": "Naziv zadatka",
  "queryDefinition": "Definicija filtra",
  "resultsSetting": "Postavka rezultata",
  "symbolSetting": "Postavka simbola",
  "resultSettingTip": "Definirajte što i kako prikazati izlazne rezultate.",
  "resultItemTitle": "Naslov svake stavke rezultata",
  "resultItemContent": "Ovi atributi polja prikazat će",
  "fieldsSetTip": "Provjerite polja koja želite prikazati. Odaberite polje kako biste ažurirali njegov alias, redoslijed i format.",
  "addField": "Dodaj polje",
  "visibility": "Vidljivost",
  "alias": "Alias",
  "specialType": "Posebna vrsta",
  "actions": "Radnje",
  "none": "Nema",
  "link": "Poveznica",
  "image": "Slika",
  "noField": "Nema polja",
  "operationalLayerTip": "Dodaj rezultat kao operativni sloj",
  "setLayerSymbolTip": "Postavi simbol za rezultate upita: ",
  "setSelectedSymbolTip": "Postavi simbol odabranog geoobjekta.",
  "notUseFilter": "Nemoj upotrijebiti filtar",
  "setSourceTip": "Postavite izvor upita.",
  "setFilterTip": "Ispravno postavite filtar.",
  "ok": "U redu",
  "cancel": "Odustani",
  "noFilterTip": "Ako izraz za filtar nije definiran, ovaj zadatak upita izlistat će sve geoobjekte u određenom izvoru podataka.",
  "relationships": "Relacije",
  "addRelationshipLayer": "Dodaj novu relaciju",
  "relatedTo": "Povezano s",
  "selectOption": "Odaberite...",
  "resultItemSorting": "Sortiranje stavki rezultata",
  "field": "Polje",
  "sortingOrder": "Redoslijed",
  "configureFieldsTip": "Konfigurirajte polja po kojima će se sortirati rezultati upita.",
  "setSortingFields": "Postavi polja za sortiranje",
  "ascending": "Uzlazno",
  "descending": "Silazno",
  "sortBy": "Sortiraj prema",
  "thenBy": "Zatim prema",
  "addTask": "Dodaj zadatak",
  "noTasksTip": "Nema konfiguriranih upita. Kliknite na „${newQuery}” da biste dodali novi.",
  "infoText": "Informacije",
  "filters": "Filtri",
  "results": "Rezultati",
  "optionsText": "Opcije",
  "summaryText": "Sažetak",
  "attributeFilter": "Filtar atributa",
  "attributeFilterTip": "Definirajte izraze atributa za upotrebu u widgetu kako biste filtrirali sloj upita.",
  "defineWhereClause": "Definirajte uvjet gdje za upit.",
  "noExpressionDefinedTip": "Nema definiranih filtara. Vratit će se svi zapisi.",
  "setExpressions": "Postavi izraze",
  "spatialFilter": "Prostorni filtri",
  "spatialFilterTip": "Izaberite koji će prostorni filtri biti dostupni krajnjim korisnicima.",
  "defaultOption": "Zadano",
  "useCurrentExtentTip": "Vrati geoobjekte samo unutar trenutačnog obuhvata karte",
  "useDrawGraphicTip": "Vrati samo one geoobjekte koji presijecaju oblik nacrtan na karti",
  "useFeaturesTip": "Vrati samo one geoobjekte koji imaju prostorni odnos s geoobjektima u drugom sloju",
  "noSpatialLimitTip": "Vrati geoobjekte unutar punog obuhvata karte",
  "drawingTools": "Izaberi alate za crtanje",
  "bufferSettings": "Omogući opciju pojasa",
  "defaultDistance": "Zadana udaljenost",
  "bufferDistance": "Udaljenost pojasa",
  "defaultUnit": "Zadana jedinica",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "availableSpatialRelationships": "Izaberite pravila prostornih relacija",
  "setSpatialRelationships": "Postavi prostorne relacije",
  "availability": "Dostupnost",
  "relationship": "Relacija",
  "label": "Oznaka",
  "intersect": "presjek",
  "contain": "sadrži",
  "areContainedIn": "sadržano u",
  "cross": "križaju se",
  "envelopeIntersect": "presjek omotnicom",
  "overlap": "preklapanje",
  "areOverlapped": "preklapaju se",
  "touch": "dodir",
  "within": "unutar",
  "areWithin": "unutar su",
  "indexIntersect": "presjek indeksa",
  "itemTitle": "Naslov stavke",
  "displayFields": "Polja za prikaz",
  "sortingFields": "Sortiraj stavke rezultata",
  "setDisplayFields": "Postavi polja za prikaz",
  "symbol": "Simbol",
  "setSymbol": "Upotrijebi prilagođeni simbol",
  "changeSymbolAtRuntime": "Omogući promjenu simbola pri izvođenju",
  "serviceSymbolTip": "Upotrijebite simbole definirane slojem",
  "exportTip": "Omogući izvoz rezultata",
  "keepResultsTip": "Sačuvaj rezultate na karti nakon što se widget zatvori",
  "queryRelatedRecords": "Zapisi povezani s upitom",
  "createLayerForTaskTip": "Odredite kako zadatak upita stvara slojeve",
  "oneLayerForTaskTip": "Prebriši sloj svaki put kad se izvrši upit",
  "multipleLayerForTaskTip": "Stvori novi sloj svaki put kad se izvrši upit",
  "makeDefault": "Učini zadanim",
  "icon": "Ikona",
  "newTask": "Novi zadatak",
  "addTaskTip": "Dodajte jedan ili više upita widgetu i konfigurirajte parametre za svaki od njih.",
  "webMapPopupTip": "Upotrijebite konfiguraciju skočnog prozora sloja na web-karti",
  "customPopupTip": "Konfiguriraj prilagođeni sadržaj",
  "showResultsSetActions": "Prikaži radnje za skup rezultata",
  "zoomTo": "Povećaj na",
  "openAttributeTable": "Prikaži u atributnoj tablici",
  "content": "Sadržaj",
  "displaySQLTip": "Prikaži SQL izraz za krajnje korisnike",
  "useLayerDefaultSymbol": "Upotrijebi zadani simbol sloja",
  "setCustomIcon": "Postavi prilagođenu ikonu",
  "layerDefaultSymbolTip": "Upotrijebi zadani simbol sloja",
  "uploadImage": "Učitaj sliku",
  "attributeCriteira": "Atributni kriterij",
  "specifyFilterAtRuntimeTip": "Korisnici će trebati odrediti parametre za ovaj izraz.",
  "value": "VRIJEDNOST",
  "hideLayersTip": "Isključite slojeve rezultata upita kad je widget zatvoren.",
  "tabLabels": "Oznake kartice",
  "tasks": "Zadaci",
  "queryCriteira": "Kriteriji upita",
  "allowCustomQuery": "Omogući stvaranje prilagođenog upita"
});