define({
  "chartSettingLabel": "Pengaturan grafik",
  "addNewLabel": "Tambah baru",
  "generalSettingLabel": "Pengaturan umum",
  "searchSourceSettingLabel": "Pengaturan Sumber Pencarian",
  "layerChooser": {
    "title": "Pilih layer untuk grafik",
    "selectPolygonLayerLabel": "Pilih layer",
    "selectPolygonLayerHintText": "Petunjuk: Jika mengonfigurasi beberapa grafik, layer harus berjenis geometri yang sama",
    "selectRelatedTableLayerLabel": "Pilih tabel yang terkait dengan layer",
    "selectRelatedTableLayerHintText": "Petunjuk: Hanya tabel dengan kolom angka yang ditampilkan",
    "errorInSelectingPolygonLayer": "Pilihlah layer yang memiliki layer titik terkait.",
    "errorInSelectingRelatedLayer": "Pilihlah tabel/layer terkait yang valid untuk layer.",
    "polygonLayerNotHavingRelationships": "Layer terpilih tidak mempunyai tabel/layer terkait apa pun."
  },
  "ChartSetting": {
    "sectionTitle": "Judul bagian",
    "sectionTitleHintText": "Petunjuk: Ditampilkan pada judul kepala bagian",
    "chartTitle": "Judul grafik",
    "chartTitleHintText": "Petunjuk: Ditampilkan di tengah atas grafik",
    "chartDescription": "Deskripsi",
    "chartDescriptionHintText": "Petunjuk: Ditampilkan di bawah grafik",
    "chartType": "Jenis grafik",
    "barChart": "Bar chart",
    "pieChart": "Pie chart",
    "polarChart": "Polar chart",
    "dataSeriesField": "Kolom rangkaian data",
    "labelField": "Kolom label",
    "chartColor": "Warna grafik",
    "singleColor": "Warna tunggal",
    "colorByTheme": "Warna menurut tema",
    "colorByFieldValue": "Warna menurut nilai kolom",
    "xAxisTitle": "Judul sumbu X",
    "xAxisHintText": "Petunjuk: Judul sumbu X",
    "yAxisTitle": "Judul sumbu Y",
    "yAxisHintText": "Petunjuk: Judul sumbu Y",
    "fieldColorLabel": "Label",
    "fieldColorColor": "Warna",
    "defaultFieldSelectLabel": "Pilih",
    "errMsgFieldValuesNotFound": "Tidak dapat menemukan nilai untuk kolom terpilih",
    "errMsgSectionTitle": "Masukkan judul bagian",
    "errMsgFieldByValue": "Pilihlah nilai kolom",
    "settingTabTitle": "Pengaturan",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Petunjuk: Pilih kolom untuk menghasilkan polar chart",
    "visibilityText": "Visibilitas",
    "fieldNameText": "Nama Kolom",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Pilihlah tiga atau lebih kolom untuk menghasilkan polar chart",
    "polarChartPolygonFillLabel": "Isi poligon",
    "polarChartPolygonFillHintText": "Petunjuk: Pilih kotak centang untuk memperlihatkan poligon mengisi bagan polar",
    "viewLayoutLabel": "Tata Letak",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Pengaturan Umum",
    "locationSymbolLabel": "Simbol lokasi grafik",
    "locationSymbolHintText": "Petunjuk: Digunakan untuk menampilkan simbol untuk alamat dan lokasi klik",
    "refreshIntervalLabel": "Interval penyegaran",
    "refreshIntervalHintText": "Petunjuk: Digunakan untuk menyegarkan bagan berdasarkan interval ini. Tentukan nilai antara 1 hingga 1440 menit",
    "errMsgRefreshInterval": "Tentukan interval penyegaran antara 0 hingga 1440 menit",
    "symbolPickerPreviewText": "Pratinjau:",
    "showToolToSelectLabel": "Atur tombol lokasi",
    "showToolToSelectHintText": "Petunjuk: Berikan tombol untuk menetapkan lokasi pada peta alih-alih selalu mengatur lokasi ketika peta diklik"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Pengaturan Sumber Pencarian",
    "searchSourceSettingTitle": "Pengaturan Sumber Pencarian",
    "searchSourceSettingTitleHintText": "Tambah dan konfigurasikan service geocode atau feature layer sebagai sumber pencarian. Sumber yang ditentukan ini akan menentukan apa saja yang dapat dicari dalam kotak pencarian",
    "addSearchSourceLabel": "Tambah Sumber Pencarian",
    "featureLayerLabel": "Feature layer",
    "geocoderLabel": "Geocoder",
    "nameTitle": "Nama",
    "generalSettingLabel": "Pengaturan Umum",
    "allPlaceholderLabel": "Teks placeholder untuk mencari semua:",
    "allPlaceholderHintText": "Petunjuk: Masukkan teks untuk ditampilkan sebagai placeholder ketika mencari semua layer dan geocoder",
    "generalSettingCheckboxLabel": "Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",
    "countryCode": "Kode Negara atau Wilayah",
    "countryCodeEg": "mis., ",
    "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Cari hanya dalam jangkauan peta saat ini",
    "zoomScale": "Skala Zoom",
    "locatorUrl": "URL Geocoder",
    "locatorName": "Nama Geocoder",
    "locatorExample": "Contoh",
    "locatorWarning": "Versi service geocode tidak didukung. Widget mendukung service geocode versi 10.0 dan lebih tinggi.",
    "locatorTips": "Saran tidak tersedia karena service geocode tidak mendukung kemampuan saran.",
    "layerSource": "Sumber Layer",
    "setLayerSource": "Atur Sumber Layer",
    "setGeocoderURL": "Atur URL Geocoder",
    "searchLayerTips": "Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",
    "placeholder": "Teks Placeholder",
    "searchFields": "Kolom Pencarian",
    "displayField": "Kolom Tampilan",
    "exactMatch": "Benar-Benar Cocok",
    "maxSuggestions": "Saran Maksimum",
    "maxResults": "Hasil Maksimum",
    "enableLocalSearch": "Aktifkan pencarian lokal",
    "minScale": "Skala Min",
    "minScaleHint": "Apabila skala peta lebih besar daripada skala ini, pencarian lokal akan diterapkan",
    "radius": "Radius",
    "radiusHint": "Menentukan radius dari area di sekitar pusat peta saat ini yang digunakan untuk mendorong peringkat calon geocoding sehingga calon yang terdekat dengan lokasi akan dimunculkan terlebih dahulu",
    "meters": "Meter",
    "setSearchFields": "Atur Kolom Pencarian",
    "set": "Atur",
    "fieldName": "Nama",
    "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses."
  }
});