define({
  "labelBookmarkName": "Žymėti dabartinį vaizdą",
  "labelPlay": "Leisti viską",
  "labelStop": "Stabdyti",
  "labelDelete": "Pašalinti",
  "placeholderBookmarkName": "Erdvinės žymos pavadinimas",
  "errorNameExist": "Žymė yra!",
  "errorNameNull": "Neleistinas žymės pavadinimas!",
  "editTip": "Redaguoti žymas",
  "exitEditTip": "Išjungti redagavimo režimą",
  "syncTip": "Sinchronizuoti",
  "cardsTips": "Tinklelio vaizdas",
  "listTips": "Sąrašo vaizdas",
  "addBtn": "Pridėti",
  "deleteBtn": "Ištrinti",
  "changeThumbnailTip": "Keisti miniatiūrą",
  "dragReorderTip": "Norėdami pertvarkyti, paspauskite ir vilkite",
  "deleteBtnTip": "Naikinti žymą",
  "editBtnTip": "Redaguoti žymą",
  "withVisibility": "Su sluoksnio matomumu",
  "searchBookmark": "Ieškoti",
  "bookmarksFromConfig": "Iš anksto sukonfigūruotos žymos",
  "bookmarksFromCache": "Vietinės laikinos žymos",
  "notice": "Įspėjimas",
  "changeNoticeTips": "Keitimai bus įrašyti tik į jūsų naršyklės podėlį. Atlikus keitimus, valdiklio ir jo konfigūracijos sinchronizavimas bus išjungtas.",
  "syncNoticeTips": "Visi jūsų keitimai bus ištrinti ir bus atkurtos sukonfigūruotos žymos.",
  "dontShowAgain": "Daugiau nerodyti",
  "saveVisibility": "Įrašyti sluoksnio matomumą",
  "_widgetLabel": "Žymės"
});