define({
  "_widgetLabel": "Guia de Resposta de Emergência",
  "ergMainPageTitle": "Baseado no Guia de Resposta de Emergência de 2016",
  "coordInputLabelStart": "Localização de Derramamento (DD)",
  "coordInputLabel": "Localização de Derramamento",
  "addPointToolTip": "Adicionar Localização de Derramamento",
  "drawPointToolTip": "Clique para adicionar localização de derramamento",
  "material": "Material",
  "materialPlaceholder": "Inicie digitando para procurar por um material",
  "table3Message": "O material que você selecionou requer informações adicionais se você estiver lidando com um derramamento grande.\n\nAssegure que você tenha os valores corretos selecionados para velocidade do vento e contêiner de transporte.",
  "table2Message": "O material que você selecionou pode produzir uma quantia grande de gases de Perigo de Inalação de Tóxicos quando derramados na água.\n\nVocê pode desejar considerar a utilização dos seguintes materiais:\n\n",
  "spillSize": "Tamanho do Derramamento",
  "small": "Pequeno",
  "large": "Grande",
  "fireLabel": "Mostrar Zona de Isolamento de Incêndio",
  "weatherLabel": "Tempo Atual na Localização de Derramamento",
  "weatherIntialText": "<br />Atualizado após uma localização de derramamento ter sido identificada",
  "temperature": "Temperatura",
  "wind": "Vento",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informação de tempo não obtida. Atualizar valores de Velocidade de Vento e de Tempo de Derramamento manualmente",
  "windDirection": "Direção do Vento (soprando para)",
  "timeOfSpill": "Tempo de Derramamento",
  "day": "Dia",
  "night": "Noite",
  "windSpeed": "Velocidade do Vento",
  "low": "Baixo",
  "moderate": "Moderado",
  "high": "Alto",
  "transportContainer": "Contêiner de Transporte",
  "rail": "Carro de tanque de ferrovia",
  "semi": "Caminhão de tanque de estrada ou reboque",
  "mton": "Cilindros de toneladas múltiplas",
  "ston": "Cilindros pequenos múltiplos ou cilindro de tonelada único",
  "ag": "Tanque de enfermagem agrícola",
  "msm": "Cilindros pequenos múltiplos",
  "bleveLabel": "Mostrar Zona de Isolamento BLEVE",
  "capacity": "Capacidade de Contêiner (litros)",
  "bleveMessage": "Para o material que você selecionou uma distância de evacuação adicional pode ser mostrado para BLEVE.\n\nPara ativar isto, configure o botão de alternar Mostrar Zona de Isolamento BLEVE para ativo e selecione a capacidade do contêiner apropriada.",
  "noPAZoneMessage": "Não há nenhuma distância de Ação Protetiva para este material. Somente o Isolamento Inicial e as zonas de evacuação foram calculadas",
  "settingsTitle": "Configurações",
  "spillLocationLabel": "Localização de Derramamento",
  "spillLocationButtonLabel": "Definir as Configurações de Localização de Derramamento",
  "IISettingsLabel": "Zona de isolamento inicial",
  "IIButtonLabel": "Definir Configurações de Isolamento Inicial",
  "PASettingsLabel": "Zona de Ação Protetiva",
  "PAButtonLabel": "Definir Configurações de Ação Protetiva",
  "downwindSettingsLabel": "Zona a favor do vento",
  "downwindButtonLabel": "Definir Configurações a favor do vento",
  "fireSettingsLabel": "Zona de Isolamento de Incêndio",
  "fireButtonLabel": "Definir Configurações de Isolamento de Incêndio",
  "bleveSettingsLabel": "Zona de Isolamento BLEVE",
  "bleveButtonLabel": "Definir Configurações de BLEVE",
  "style": "Estilo",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Transversal",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultados",
  "publishERGBtn": "Publicar",
  "ERGLayerName": "Nome de Camada ERG Publicada",
  "invalidERGLayerName": "O nome da camada deve conter somente caracteres alfanuméricos e underscores",
  "missingERGLayerName": "Você deve inserir um nome para ERG",
  "publishingFailedLayerExists": "Falha na publicação: Você já tem um serviço de feição nomeado {0}. Escolha outro nome.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não foi possível criar: {0}",
  "addToDefinition": "Adicionar à definição: {0}",
  "successfullyPublished": "Camada da web publicada com sucesso{0}Gerenciar a camada da web",
  "userRole": "Não foi possível criar serviço pois o usuário não tem permissões",
  "transparency": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "createERGBtn": "Criar Zonas",
  "clearERGBtn": "Apagar",
  "labelFormat": "Formato do Rótulo",
  "helpIconTooltip": "O limite entre os tamanhos de derramamento pequeno e grande são:\nLíquidos - 55 galões (208 litros)\nSólidos - 60 libras (300 quilogramas)",
  "cellWidth": "Largura da Célula (x)",
  "cellHeight": "Altura da Célula (y)",
  "invalidNumberMessage": "Os valores inseridos não são válidos",
  "invalidRangeMessage": "O valor deve ser maior que 0",
  "gridAngleInvalidRangeMessage": "O valor deve estar entre -89,9 e 89,9.",
  "formatIconTooltip": "Entrada de formato",
  "setCoordFormat": "Definir String de Formato de Coordenadas",
  "prefixNumbers": "Adicione o prefixo '+/-' para números positivos e negativos",
  "cancelBtn": "Cancelar",
  "applyBtn": "Aplicar",
  "comfirmInputNotation": "Confirmar Notação de Entrada",
  "notationsMatch": "notações correspondem sua entrada, confirme que deseja utilizar:",
  "missingLayerNameMessage": "Você deve inserir um nome de camada válida antes de poder publicar",
  "parseCoordinatesError": "Não é possível analisar coordenadas. Verifique sua entrada.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Minutos Decimais - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Minutos Decimais - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra da Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)"
});