define({
  "settings": "Definições",
  "titleSettings": "Definições de texto",
  "imageSettings": "Definições de imagem",
  "backgroundColor": "Cor de fundo",
  "alignment": "Alinhamento",
  "textSize": "Tamanho do texto",
  "textColor": "Cor do texto",
  "dataSource": "Fonte de Dados",
  "chartSettings": "Definições de gráficos",
  "data": "Dados",
  "dataLabels": "Rótulos de dados",
  "displayMode": "Modo de exibição",
  "featureOption": "Exibir valores elemento a elemento",
  "categoryOption": "Exibir valores por categoria",
  "countOption": "Exibir contagens de elementos por categoria",
  "fieldOption": "Exibir valores de atributos como gráficos",
  "categoryField": "Campo de categoria",
  "labelField": "Campo de rótulo",
  "valueFields": "Campos de valor",
  "operation": "Operação",
  "sumOption": "Soma",
  "averageOption": "Média",
  "minOption": "Mínimo",
  "maxOption": "Máximo",
  "dataFormat": "Formato de dados",
  "decimalPlaces": "Casas decimais",
  "prefix": "Prefixo",
  "suffix": "Sufixo",
  "dataType": "Tipo de Dados",
  "featureCount": "Contagem de elementos",
  "fieldStatistics": "Estatísticas de campos",
  "display": "Exibir",
  "chartColor": "Cor do gráfico",
  "horizontalAxis": "Eixo horizontal",
  "verticalAxis": "Eixo vertical",
  "legend": "Legenda",
  "position": "Posição",
  "top": "Superior",
  "bottom": "Inferior",
  "useDataSourceSelection": "Utilizar seleção",
  "dataSourceFilterByExtent": "Filtrar por extensão",
  "changeTemplate": "Alterar modelo",
  "numberSettings": "Definições de números",
  "gaugeSettings": "Definições de medidor",
  "indicators": "Indicadores",
  "ifValue": "Valor If",
  "and": "e",
  "numberOperatorIsLessThan": "é inferior a",
  "numberOperatorIsGreaterThan": "é superior a",
  "numberOperatorIsBetween": "é entre",
  "numberOperatorIsEqual": "é igual a",
  "numberOperatorIsNotEqual": "não é igual a",
  "then": "Portanto",
  "ratio": "Rácio",
  "trueValue": "Valor real",
  "changeValueColor": "Alterar cor do valor para",
  "changeGaugeColor": "Alterar cor do medidor para",
  "setIndicatorIcon": "Definir ícone de indicador como",
  "icons": "Ícones",
  "style": "Estilo",
  "placement": "Colocação",
  "left": "Esquerda",
  "replace": "Substituir",
  "right": "Direita",
  "color": "Cor",
  "categoryExists": "A categoria existe!",
  "comboxHint": "Digite ou selecione uma",
  "comboxDisableInputHint": "Selecionar um",
  "sortBy": "Ordenar por",
  "labelAxis": "Rótulo",
  "valueAxis": "Valor",
  "minPeriod": "Período mínimo",
  "automatic": "Automático",
  "periodsWithOutRecords": "Períodos sem registos",
  "nullValue": "Valor nulo",
  "calculatedAsZero": "Calculado como zero",
  "ignored": "Ignorado",
  "maxCategories": "Máximo de categorias",
  "useLayerSymbology": "Utilizar simbologia da camada",
  "hollowsize": "Tamanho vazio",
  "splitField": "Dividir campo",
  "parsingperiodTip": "Ocorreu uma falha ao computar. Demasiados intervalos temporais devido ao curto período de análise.",
  "manyCategoryTip": "Ocorreu uma falha ao exibir o gráfico. Demasiadas categorias.",
  "setColor": "Definir cor",
  "setTheColorOf": "Depois defina a cor de",
  "setTheColorAs": "Depois defina a cor como",
  "ifStr": "Se",
  "as": "como",
  "is": "é",
  "isNot": "não é",
  "barCluster": "cluster de barras",
  "individualBar": "barra individual",
  "allOthers": "Todos os Outros",
  "category": "Categoria",
  "indicatorSum": "SOMA",
  "indicatorAve": "MÉDIA",
  "indicatorMax": "MÁXIMO",
  "indicatorMin": "MÍNIMO",
  "setCorrectyIndicatorTip": "Por favor, defina os indicadores corretamente.",
  "dataRange": "Intervalo de datas",
  "targetValue": "Valor alvo",
  "currentValue": "Valor atual",
  "gaugeColor": "Cor do medidor",
  "min": "Mínimo",
  "max": "Máximo",
  "displayValueIn": "Exibir valor em",
  "noData": "Sem dados",
  "thousandAbbreviation": "q",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Aviso",
  "noSettingWaring1": "Clique num elemento para definir as respetivas propriedades.",
  "noSettingWaring2": "Arraste para redimensionar ou reordenar um elemento.",
  "donNotShowAgain": "Não exibir novamente",
  "changeTemplateWarning": "Esta ação irá apagar todas as suas definições e abrirá um novo modelo vazio",
  "requiredFieldWarning": "Este valor é exigido:",
  "dataSourceNotSet": "Por favor, defina a fonte de dados.",
  "addIndicatorTip": "Adicionar um indicador",
  "chooseTemplatePopupTitle": "Seleccione um modelo",
  "filterExtentTipWithaTag": "Pode desativar o filtro por <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Fonte de dados extra</a> no Separador Atributo.",
  "filterExtentTip": "Pode desativar o filtro por Fonte de dados extra no Separador Atributo.",
  "customColorByCategory": "Cor personalizada por categoria",
  "randomColor": "Cor Aleatória",
  "valueString": "Valor",
  "fieldString": "Campo",
  "includeThresholdValue": "Incluir valor de limiar",
  "percentage": "Percentagem",
  "colorSchema": "Esquema de cores",
  "addCategory": "Adicionar categoria",
  "clickToEdit": "Clicar para editar",
  "nullText": "Nulo",
  "others": "Outros",
  "stringsInTemplate": {
    "name_number": "Número",
    "name_gauge": "Medidor",
    "name_vertical_gauge": "Medidor Vertical",
    "name_horizontal_gauge": "Medidor Horizontal",
    "name_pie": "Circular",
    "name_donut": "Donut",
    "name_bar": "Barra",
    "name_stacked_bar": "Barra Empilhada",
    "name_percentage_stacked_bar": "Barra Empilhada de Percentagem",
    "name_column": "Coluna",
    "name_stacked_column": "Coluna empilhada",
    "name_percentage_stacked_column": "Coluna Empilhada de Percentagem",
    "name_line": "Linha",
    "name_area": "Área",
    "name_stacked_area": "Área Empilhada",
    "name_percentage_stacked_area": "Área Empilhada de Percentagem",
    "titleOfTheInfographic": "TÍTULO DA INFOGRAFIA",
    "description": "Descrição: informações adicionais sobre esta infografia."
  }
});