define({
  "_widgetLabel": "स्थिति संबंधी जागरुकता",
  "locate_incident": "घटना का पता लगाएं",
  "reverse_geocoded_address": "निकटतम पता",
  "reverse_geocoded_error": "उपलब्ध नहीं है",
  "now": "अब",
  "wind": "हवा",
  "SUN": "रवि",
  "MON": "सोम",
  "TUE": "मंगल",
  "WED": "बुध",
  "THU": "गुरु",
  "FRI": "शुक्र",
  "SAT": "शनि",
  "actionLabel": "स्थान सेट करें",
  "drawPoint": "बिंदु बनाएं",
  "drawLine": "रेखा बनाएं",
  "drawPolygon": "बहुभुज बनाएं",
  "saveIncident": "सहेजें",
  "clearIncident": "फिर से शुरू करें",
  "noFeaturesFound": "किसी भी फीचर को खोजा नहीं गया है।",
  "downloadCSV": "डाउनलोड करें",
  "sum": "योग",
  "min": "न्यूनतम",
  "max": "अधिकतम",
  "avg": "औसत",
  "count": "गणना",
  "area": "क्षेत्रफल",
  "length": "लंबाई",
  "update_btn": "संपन्न",
  "delete_btn": "हटाएँ",
  "get_directions": "दिशा-निर्देश प्राप्त करें",
  "incident": "घटना",
  "incidents": "घटनाएं",
  "buffer": "बफर",
  "buffers": "बफर्स",
  "weather": "मौसम",
  "poweredBy": "द्वारा संचालित",
  "_featureAction_ActionLabel": "स्थान सेट करें",
  "_featureAction_AddRemoveActionLabel": "स्थान जोड़ें/हटाएं",
  "snapshot": "स्नैपशॉट फ़ोल्डर ऐप्लिकेशन id द्वारा बनाया गया है:",
  "user_credentials": "उपयोगकर्ता के पास वैध विशेषाधिकार नहीं है।",
  "notPolySnapShot": "एक स्नैपशॉट बनाने से पहले एक बफर दूरी निर्दिष्ट करें।",
  "notPolyReport": "रिपोर्ट जोड़ने के लिए कोई मान्य परिणाम नहीं है।",
  "notValidDownload": "डाउनलोड करने के लिए कोई वैध परिणाम नहीं है।",
  "of_append": "का",
  "layer_append": "स्नैपशॉट",
  "downloadAll": "सभी डाउनलोड करें",
  "createSnapshot": "स्नैपशॉट बनाएं",
  "createReport": "रिपोर्ट बनाएँ",
  "calculated_results": "संक्षेपित जानकारी",
  "closest": "निकटतम फीचर",
  "proximity": "निकटता",
  "summary": "सार",
  "groupedSummary": "समूहित गणना",
  "_count": "गणना",
  "approximate": "अनुमानित",
  "snapshot_name": "स्नैपशॉट गुण सेट करें",
  "report_name": "रिपोर्ट गुण सेट करें",
  "invalid_snapshot_name": "अवैध स्नैपशॉट नाम।",
  "invalid_report_name": "अमान्य रिपोर्ट शीर्षक।",
  "orientation": "विन्यास",
  "pageSize": "पृष्ठ का आकार",
  "comments": "टिप्पणियाँ",
  "choose_group": "समूह",
  "forecast": "फ़ोरकास्ट",
  "select_group": "समूह चुनें",
  "select_group_instruction": "स्नैपशॉट को चयनित समूह के साथ बनाकर साझा किया जाएगा",
  "information_append": " सूचना",
  "distance": "दूरी",
  "buffer_invalid": "${min} और ${max} के बीच की कोई वैध संख्या दर्ज करें"
});