define({
  "tabs_section_Label": "Kartice",
  "addTab": "Dodaj karticu",
  "layerName": "Sloj",
  "layerType": "Vrsta analize",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "closest": "Najbliži geoobjekt",
  "proximity": "Blizina",
  "summary": "Sažetak",
  "select_lbl": "-- Odaberi --",
  "general_setting_Label": "Opće postavke",
  "units_text_lbl": "Jedinice udaljenosti",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "maximum_distance_lbl": "Maksimalna udaljenost najbližeg geoobjekta",
  "buffer_text_lbl": "Oznaka pojasa",
  "buffer_lbl": "Veličina pojasa",
  "buffer_max_lbl": "Maksimalna veličina pojasa",
  "buffer_min_lbl": "Minimalna veličina pojasa",
  "routing_checkBox": "Omogući rutiranje",
  "weather_Label": "Opcije vremena",
  "weather_checkBox": "Uključi informacije o vremenu",
  "weather_celsius": "Celzijevi-Kilometri",
  "selectLayers": "Odaberi slojeve s vremenom",
  "currentlySelectedLayer": "Slojevi s vremenom koji su trenutačno odabrani",
  "missingTabLabel": "Barem jedna kartica nema svoju oznaku",
  "cancel": "Odustani",
  "ok": "U redu",
  "missingLayerInWebMap": "Nema operativnih slojeva.",
  "selectFields": "Odaberi polja",
  "addField": "Dodaj polje",
  "sum": "ZBROJ",
  "min": "MIN.",
  "max": "MAKS.",
  "avg": "PROSJEK",
  "count": "BROJ",
  "area": "POVRŠINA",
  "length": "DULJINA",
  "count_checkBox": "Prikaži zbroj",
  "area_checkBox": "Prikaži površinu",
  "length_checkBox": "Prikaži duljinu",
  "max_records": "Dosegnuto je maksimalno ograničenje",
  "disable_checkBox": "Onemogući upravljanje vidljivosti sloja",
  "optional_lbl": "Dodatne oznake",
  "incident_lbl": "Incident",
  "locate_lbl": "Pronađi incident"
});