define({
  "settings": "Configurações",
  "titleSettings": "Configurações de texto",
  "imageSettings": "Configurações de imagem",
  "backgroundColor": "Cor do plano de fundo",
  "alignment": "Alinhamento",
  "textSize": "Tamanho de texto",
  "textColor": "Cor de texto",
  "dataSource": "Fonte de dados",
  "chartSettings": "Configurações do gráfico",
  "data": "Dados",
  "dataLabels": "Rótulos de dados",
  "displayMode": "Modo de Visualização",
  "featureOption": "Exibir valores feição por feição",
  "categoryOption": "Exibir valores por categoria",
  "countOption": "Exibir contagem de feição por categoria",
  "fieldOption": "Exibir valores de atributo como gráficos",
  "categoryField": "Campo de Categoria",
  "labelField": "Campo de rótulo",
  "valueFields": "Campos de valores",
  "operation": "Operação",
  "sumOption": "Soma",
  "averageOption": "Média",
  "minOption": "Mínimo",
  "maxOption": "Máximo",
  "dataFormat": "Formato dos dados",
  "decimalPlaces": "Casas decimais",
  "prefix": "Prefixo",
  "suffix": "Sufixo",
  "dataType": "Tipo de dados",
  "featureCount": "Contagem de feições",
  "fieldStatistics": "Estatística de campo",
  "display": "Exibir",
  "chartColor": "Cor do gráfico",
  "horizontalAxis": "Eixo horizontal",
  "verticalAxis": "Eixo vertical",
  "legend": "Legenda",
  "position": "Posição",
  "top": "Superior",
  "bottom": "Inferior",
  "useDataSourceSelection": "Utilizar seleção",
  "dataSourceFilterByExtent": "Filtrar por extensão",
  "changeTemplate": "Alterar modelo",
  "numberSettings": "Configurações de número",
  "gaugeSettings": "Configurações do Medidor",
  "indicators": "Indicadores",
  "ifValue": "Se valor",
  "and": "l",
  "numberOperatorIsLessThan": "é menor que",
  "numberOperatorIsGreaterThan": "é maior que",
  "numberOperatorIsBetween": "está entre",
  "numberOperatorIsEqual": "é igual a",
  "numberOperatorIsNotEqual": "não é igual a",
  "then": "Então",
  "ratio": "Taxa",
  "trueValue": "Valor verdadeiro",
  "changeValueColor": "altera cor de valor para",
  "changeGaugeColor": "altere cor de medidor para",
  "setIndicatorIcon": "configurar ícone de indicador como",
  "icons": "Ícones",
  "style": "Estilo",
  "placement": "Disposição",
  "left": "Esquerda",
  "replace": "Substituir",
  "right": "Direita",
  "color": "Cor",
  "categoryExists": "A categoria existe!",
  "comboxHint": "Digitar ou selecionar um",
  "comboxDisableInputHint": "Selecionar um",
  "sortBy": "Classificar por",
  "labelAxis": "Rótulo",
  "valueAxis": "Valor",
  "minPeriod": "Período mínimo",
  "automatic": "Automático",
  "periodsWithOutRecords": "Períodos sem registros",
  "nullValue": "Valor nulo",
  "calculatedAsZero": "Calculado como zero",
  "ignored": "Ignorado",
  "maxCategories": "Máximo de categorias",
  "useLayerSymbology": "Utilizar simbologia da camada",
  "hollowsize": "Tamanho do vácuo",
  "splitField": "Dividir campo",
  "parsingperiodTip": "Falha ao calcular. Muitos intervalos de tempo devido ao curto período de análise.",
  "manyCategoryTip": "Falha ao exibir gráfico. Muitas categorias.",
  "setColor": "Definir cor",
  "setTheColorOf": "Então configurar cor de",
  "setTheColorAs": "Então configurar cor como",
  "ifStr": "Se",
  "as": "como",
  "is": "é",
  "isNot": "não é",
  "barCluster": "agrupamento de barra",
  "individualBar": "barra individual",
  "allOthers": "Todos os outros",
  "category": "Categoria",
  "indicatorSum": "SOMA",
  "indicatorAve": "MÉDIA",
  "indicatorMax": "MÁX",
  "indicatorMin": "MÍN",
  "setCorrectyIndicatorTip": "Ajuste os indicadores corretamente.",
  "dataRange": "Faixa de dados",
  "targetValue": "Valor de alvo",
  "currentValue": "Valor atual",
  "gaugeColor": "Cor do medidor",
  "min": "Mínimo",
  "max": "Máximo",
  "displayValueIn": "Exibe o valor em",
  "noData": "Sem dados",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Aviso",
  "noSettingWaring1": "Clique em um elemento para configurar suas propriedades.",
  "noSettingWaring2": "Arraste para dimensionar ou reordenar um elemento.",
  "donNotShowAgain": "Não mostrar novamente",
  "changeTemplateWarning": "Isto apagará todas suas configurações e abre um novo modelo vazio.",
  "requiredFieldWarning": "Este valor é exigido:",
  "dataSourceNotSet": "Configure a fonte de dados.",
  "addIndicatorTip": "Adicionar um indicador",
  "chooseTemplatePopupTitle": "Escolher um modelo",
  "filterExtentTipWithaTag": "Você pode desativar o filtro por <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Fonte de dados extra</a> na guia Atributos.",
  "filterExtentTip": "Você pode desativar o filtro por Fonte de dados extra na guia Atributos.",
  "customColorByCategory": "Cor personalizada por categoria",
  "randomColor": "Cor Aleatória",
  "valueString": "Valor",
  "fieldString": "Campo",
  "includeThresholdValue": "Incluir valor de limite",
  "percentage": "Porcentagem",
  "colorSchema": "Esquema de cores",
  "addCategory": "Adicionar categoria",
  "clickToEdit": "Clique para editar",
  "nullText": "Nulo",
  "others": "Outros",
  "stringsInTemplate": {
    "name_number": "Número",
    "name_gauge": "Medidor",
    "name_vertical_gauge": "Medidor Vertical",
    "name_horizontal_gauge": "Medidor Horizontal",
    "name_pie": "Pizza",
    "name_donut": "Círculo",
    "name_bar": "Barra",
    "name_stacked_bar": "Barras Empilhadas",
    "name_percentage_stacked_bar": "Porcentagem de Barras Empilhadas",
    "name_column": "Coluna",
    "name_stacked_column": "Coluna empilhada",
    "name_percentage_stacked_column": "Porcentagem de Colunas Empilhadas",
    "name_line": "Linha",
    "name_area": "Área",
    "name_stacked_area": "Área Empilhada",
    "name_percentage_stacked_area": "Porcentagem de Áreas Empilhadas",
    "titleOfTheInfographic": "TÍTULO DO INFOGRÁFICO",
    "description": "Descrição: informações adicionais sobre este infográfico."
  }
});