define({
  "chartSettingLabel": "הגדרות תרשים",
  "addNewLabel": "הוסף חדש",
  "generalSettingLabel": "הגדרות כלליות",
  "searchSourceSettingLabel": "הגדרות מקור חיפוש",
  "layerChooser": {
    "title": "בחר שכבה לתרשים",
    "selectPolygonLayerLabel": "בחר שכבה",
    "selectPolygonLayerHintText": "רמז: אם אתה מגדיר תרשימים מרובים, סוג הגיאומטריה של השכבות חייב להיות זהה",
    "selectRelatedTableLayerLabel": "בחר טבלה מקושרת לשכבה",
    "selectRelatedTableLayerHintText": "רמז: רק טבלאות עם שדות מספריים מוצגות",
    "errorInSelectingPolygonLayer": "בחר שכבה שיש לה שכבת נקודות מקושרת.",
    "errorInSelectingRelatedLayer": "בחר טבלה/שכבה מקושרת חוקית לשכבה.",
    "polygonLayerNotHavingRelationships": "לשכבה שנבחרה אין טבלה/שכבה מקושרת."
  },
  "ChartSetting": {
    "sectionTitle": "כותרת מקטע",
    "sectionTitleHintText": "רמז: מוצג בכותרת הקטע",
    "chartTitle": "כותרת תרשים",
    "chartTitleHintText": "רמז: מוצג באופן ממורכז בתרשים",
    "chartDescription": "תיאור",
    "chartDescriptionHintText": "רמז: מוצג מתחת לתרשים",
    "chartType": "סוג תרשים",
    "barChart": "תרשים עמודות",
    "pieChart": "תרשים עוגה",
    "polarChart": "תרשים קוטבי",
    "dataSeriesField": "שדה סדרת נתונים",
    "labelField": "שדה תווית",
    "chartColor": "צבע תרשים",
    "singleColor": "צבע אחד",
    "colorByTheme": "צבע לפי ערכת נושא",
    "colorByFieldValue": "צבע לפי ערך שדה",
    "xAxisTitle": "כותרת ציר X",
    "xAxisHintText": "רמז: כותרת ציר X",
    "yAxisTitle": "כותרת ציר Y",
    "yAxisHintText": "רמז: כותרת ציר Y",
    "fieldColorLabel": "תווית",
    "fieldColorColor": "צבע",
    "defaultFieldSelectLabel": "בחירה",
    "errMsgFieldValuesNotFound": "לא ניתן למצוא ערכים עבור השדה שנבחר",
    "errMsgSectionTitle": "הזן את כותרת הקטע",
    "errMsgFieldByValue": "בחר ערך שדה",
    "settingTabTitle": "הגדרה",
    "layoutTabTitle": "פריסת עמוד",
    "polarChartSelectFieldsHintText": "רמז: בחר שדות כדי ליצור תרשים קוטבי",
    "visibilityText": "ניראות",
    "fieldNameText": "שם שדה",
    "aliasNameText": "כינוי",
    "errMsgPolarFieldsRequired": "בחר לפחות שלושה שדות כדי ליצור תרשים קוטבי",
    "polarChartPolygonFillLabel": "מלא פוליגון",
    "polarChartPolygonFillHintText": "רמז: בחר תיבת סימון כדי להציג מילוי פוליגונים בגרף קוטבי",
    "viewLayoutLabel": "פריסת עמוד",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "מדבר",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "אירלנד",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "ביצה",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "הגדרות כלליות",
    "locationSymbolLabel": "סמל מיקום גרפי",
    "locationSymbolHintText": "רמז: משמש להצגת סמל עבור כתובת ומיקום לחיצה",
    "refreshIntervalLabel": "מרווח רענון",
    "refreshIntervalHintText": "רמז: משמש לרענון תרשימים בהתבסס על מרווח זה. ציין ערך בין 1 ל-1440 דקות.",
    "errMsgRefreshInterval": "ציין את מרווח הרענון בין 0 ל-1440 דקות",
    "symbolPickerPreviewText": "תצוגה מקדימה:",
    "showToolToSelectLabel": "הגדר לחצן מיקום",
    "showToolToSelectHintText": "רמז: מספק לחצן כדי להגדיר מיקום במפה במקום להגדיר תמיד את המיקום כאשר מתבצעת לחיצה על המפה"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "חפש הגדרות מקור",
    "searchSourceSettingTitle": "חפש הגדרות מקור",
    "searchSourceSettingTitleHintText": "הוסף והגדר שירותי עיגון כתובות או שכבות ישויות כמקורות חיפוש. מקורות אלה שמצוינים קובעים מה ניתן לחיפוש בתוך תיבת החיפוש",
    "addSearchSourceLabel": "הוסף מקור חיפוש",
    "featureLayerLabel": "שכבת ישויות",
    "geocoderLabel": "מעגן כתובות",
    "nameTitle": "שם",
    "generalSettingLabel": "הגדרה כללית",
    "allPlaceholderLabel": "טקסט מציין מיקום לחיפוש מלא:",
    "allPlaceholderHintText": "רמז: הקלד טקסט שיוצג כממלא מקום בעת חיפוש בכל השכבות ומעגן הכתובות",
    "generalSettingCheckboxLabel": "הצג חלון קופץ עבור הישות או המיקום שנמצאו",
    "countryCode": "קוד/ים של ארצות או אזורים",
    "countryCodeEg": "לדוגמה ",
    "countryCodeHint": "השארת הערך הזה ריק תפעיל חיפוש בכל הארצות והאזורים",
    "questionMark": "?",
    "searchInCurrentMapExtent": "חפש רק בתיחום המפה הנוכחי",
    "zoomScale": "קנה מידה להתמקדות",
    "locatorUrl": "URL של מעגן הכתובות",
    "locatorName": "שם מעגן הכתובות",
    "locatorExample": "דוגמה",
    "locatorWarning": "גרסה זו של שירות עיגון הכתובות אינה נתמכת. הווידג'ט תומך בשירות עיגון הכתובות בגרסה 10.0 ואילך.",
    "locatorTips": "אין הצעות זמינות מפני ששירות עיגון הכתובות אינו תומך ביכולת הצעה.",
    "layerSource": "מקור שכבה",
    "setLayerSource": "הגדר מקור שכבה",
    "setGeocoderURL": "הגדר URL של מעגן הכתובות",
    "searchLayerTips": "אין הצעות זמינות מפני ששירות התמיכה אינו תומך ביכולת עימוד.",
    "placeholder": "טקסט מציין מיקום (Placeholder)",
    "searchFields": "שדות חיפוש",
    "displayField": "שדה תצוגה",
    "exactMatch": "התאמה מדויקת",
    "maxSuggestions": "מקסימום הצעות",
    "maxResults": "מקסימום תוצאות",
    "enableLocalSearch": "הפעל חיפוש מקומי",
    "minScale": "קנ\"מ מינימלי",
    "minScaleHint": "כאשר קנה המידה גדול יותר מקנה מידה זה, החיפוש המקומי יבוצע",
    "radius": "רדיוס",
    "radiusHint": "מציין את רדיוס האזור מסביב למרכז המפה הנוכחית שמשמש להגדלת הדירוג של מועמדים לעיגון כתובות, כך שהמועמדים הקרובים ביותר למיקום יוחזרו ראשונים.",
    "meters": "מטרים",
    "setSearchFields": "הגדר שדות חיפוש",
    "set": "הגדר",
    "fieldName": "שם",
    "invalidUrlTip": "ה-URL ‏${URL} שגוי או אינו נגיש."
  }
});