define({
  "_widgetLabel": "दूरी और दिशा",
  "tabLineTitle": "रेखा",
  "tabCircleTitle": "वृत्त",
  "tabEllipseTitle": "अंडाकार",
  "tabRingsTitle": "छल्ले",
  "multipleNotationsMessage": " आपके इनपुट से मेल खाने वाले नोटेशन। कृपया जिसका आप इस्तेमाल करना चाहते हैं, उसकी पुष्टि करें:",
  "invalidCoordinateMessage": "अमान्य निर्देशांक",
  "confirmInputNotationMessage": "इनपुट नोटेशन की पुष्टि करें",
  "prefixSuffixMessage": "इनपुट निर्देशांक को अक्षांश या अक्षांश मान के लिए उपसर्ग और प्रत्यय दोनों के रूप में पाया गया है, वापसी निर्देशांक उपसर्ग पर आधारित है।",
  "rememberDecisionMessage": "मेरा निर्णय याद रखें और दोबारा न पूछें।<br/>",
  "majorAxisTooltipMessage": "बड़े अक्ष की लंबाई पर क्लिक करें",
  "minorAxisTooltipMessage": "छोटे अक्ष को सेट करने और दीर्घ वृत्त का आरेखण पूर्ण करने के लिए स्थिति निर्धारण शुरू करने हेतु माउस को पीछे ले जाएँ",
  "clickToFinishLineMessage": "रेखा खींचने के लिए क्लिक करें",
  "doubleClickEllipseMesage": "छल्लों की सीमा का आरेखण पूरा करने के लिए डबल-क्लिक करें",
  "invalidCoordinateTypeMessage": "इनपुट निर्देशांक प्रकार निर्धारित करने में असमर्थ हैं। कृपया अपना इनपुट देखें",
  "noCenterPointSetMessage": "कोई केंद्रबिंदु निर्धारित नहीं है। कृपया अपना इनपुट देखें",
  "ellipseMajorAxis": "बड़ा अक्ष",
  "ellipseMinorAxis": "छोटा अक्ष",
  "degreesRangeMessage": "मान 0 और 360 के बीच होना चाहिए",
  "millsRangeMessage": "मान 0 और 6400 के बीच होना चाहिए",
  "lengthLabel": "लंबाई",
  "angleLabel": "कोण",
  "startPointLabel": "प्रारंभ बिंदु",
  "endPointLabel": "समाप्ति बिंदु",
  "centerPointLabel": "केंद्र बिंदु",
  "distanceTableErrorMessage": "दूरी तालिका रिक्त है। कृपया सुनिश्चित करें कि आपने कुछ दूरियाँ दर्ज की है।",
  "setCoordFormatStringMessage": "निर्देशांक फ़ॉर्मेट स्ट्रिंग को सेट करें",
  "prefixMessage": "धनात्मक और ऋणात्मक संख्याओं के आगे '+/-' जोड़ें",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "दशमलव डिग्री - अक्षांश/देशांतर",
  "DDLongLatNotation": "दशमलव डिग्री - देशांतर/अक्षांश",
  "DDMLatLongNotation": "दशमलव डिग्री मिनट - अक्षांश/देशांतर",
  "DDMLongLatNotation": "दशमलव डिग्री मिनट - देशांतर/अक्षांश",
  "DMSLatLongNotation": "दशमलव डिग्री सेकंड - देशांतर/अक्षांश",
  "DMSLongLatNotation": "दशमलव डिग्री सेकंड - अक्षांश/देशांतर",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - बैंड लेटर",
  "UTMHemNotation": "UTM - गोलार्ध (N/S)",
  "circleTitle": "इसका व्यास बनाएँ",
  "radiusLabel": "त्रिज्या",
  "diameterLabel": "व्यास",
  "startPointPlaceHolderLabel": "गुणांक दर्ज करें",
  "formatInputLabel": "फ़ॉर्मेट आउटपुट",
  "drawCircleLabel": "वृत्त बनाएँ",
  "drawLineLabel": "रेखा खींचे",
  "createCircleInteractivelyLabel": "संवादपरक रूप से वृत्त बनाएँ",
  "rangeErrorMessage": "अमान्य त्रिज्या या व्यास",
  "numericInvalidMessage": "कृपया कोई संख्यात्मक मान दर्ज करें",
  "timeLabel": "समय",
  "invalidTimeMessage": "समय का अमान्य मान",
  "hoursLabel": "घंटे",
  "minutesLabel": "मिनट",
  "secondsLabel": "सेकंड",
  "rateLabel": "रेट/मूल्यांकन",
  "invalidDistanceMessage": "दूरी का अमान्य मान",
  "feetSecondsLabel": "फीट / सेकंड",
  "feetHourLabel": "फीट / घंटा",
  "kmSecondLabel": "किलोमीटर / सेकंड",
  "kmHourLabel": "किलोमीटर / घंटा",
  "metersSecondLabel": "मीटर / सेकंड",
  "metersHourLabel": "मीटर / घंटा",
  "milesSecondLabel": "मील / सेकंड",
  "milesHourLabel": "मील / घंटा",
  "nauticalMilesSecondLabel": "नॉटिकल मील / सेकंड",
  "nauticalMilesHourLabel": "नॉटिकल मील / घंटा",
  "clearGraphicsLabel": "ग्राफ़िक्स हटाएँ",
  "ellipseTypeLabel": "दीर्घ वृत्त का प्रकार",
  "ellipseSemiLabel": "अर्द्ध",
  "ellipseFullLabel": "पूर्ण",
  "drawEllipseLabel": "दीर्घ वृत्त बनाएँ",
  "createEllipseInteractively": "संवादपरक तरीके से दीर्घ वृत्त बनाएँ",
  "axisLabel": "अक्ष",
  "majorRadiusLabel": "मेज़र (त्रिज्या)",
  "axisErrorMessage": "मान 0 से अधिक होना चाहिए",
  "minorRadiusLabel": "माइनर (त्रिज्या)",
  "orientationLabel": "विन्यास",
  "orientationErrorMessage": "मान 0 और 360 के बीच होना चाहिए",
  "warningMessage": "चेतावनी: दीर्घ वृत्ताकार (अंडाकार) टूल का उपयोग करके बनाए गए ग्राफ़िक भूगणितीय नहीं होते हैं",
  "fromLabel": "से",
  "distanceBearingLabel": "दूरी और बीयरिंग (सीमा)",
  "pointsLabel": "बिंदु",
  "createLineInteractively": "लाइन को संवादपरक तरीके से बनाएँ",
  "lineLengthErrorMessage": "लाइन की अमान्य लंबाई",
  "degreesLabel": "डिग्रेस",
  "milsLabel": "मील",
  "lineTypeLabel": "टाइप करें",
  "interactiveLabel": "संवादपरक",
  "fixedLabel": "ठीक किया गया",
  "originLabel": "उत्पत्ति",
  "cumulativeLabel": "सामूहिक",
  "numberOfRingsLabel": "छल्लों की संख्या",
  "ringsErrorMessage": "छल्लों की संख्या अमान्य है",
  "distanceBetweenRingsLabel": "छल्लों के बीच की दूरी",
  "ringsDecimalErrorMessage": "2 दशमलव स्थानों के लिए अंकीय मान दर्ज करें",
  "distanceUnitsLabel": "दूरी इकाइयाँ",
  "distancesLabel": "दूरी",
  "numberOfRadialsLabel": "रेडियल की संख्या",
  "upLabel": "ऊपर",
  "downLabel": "नीचे",
  "deleteLabel": "हटाएँ",
  "radialsErrorMessage": "रेडियल की अमान्य संख्या। अधिकतम अनुमत 360 है",
  "addPointLabel": "पॉइंट जोड़ें",
  "valueLabel": "मान",
  "valueText": "मान दर्ज करें",
  "actionLabel": "कार्रवाई"
});