define({
  "gridTabLabel": "Grelha",
  "labelTabLabel": "Rótulos",
  "referenceSystemTabLabel": "Sistema de Referência",
  "gridTabDescription": "Defina a aparência e comportamento das células da grelha.",
  "cellOutlineColor": "Cor de Contorno de Célula",
  "cellFillColor": "Cor de Preenchimento de Célula",
  "transparency": "Transparência",
  "cellShapeDropDown": "Formato de Células",
  "default": "Retângulo",
  "hexagon": "Hexágono",
  "cellUnitsDropDown": "Unidades de Células",
  "miles": "Milhas",
  "kilometers": "Quilómetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nautical-miles": "Milhas Náuticas",
  "gridOriginDropDown": "Origem de Rótulo",
  "lowerLeft": "Inferior Esquerda",
  "lowerRight": "Inferior Direita",
  "upperLeft": "Superior Esquerda",
  "upperRight": "Superior Direita",
  "center": "Centrar",
  "labelTabDescription": "Defina a aparência e comportamento dos rótulos da grelha.",
  "labelSettings": "Estilo do Rótulo",
  "font": "Fonte",
  "textSize": "Tamanho do Texto",
  "textColor": "Cor do Texto",
  "halo": "Halo",
  "show": "Exibir",
  "labelTypeDropDown": "Tipo de Rótulo",
  "alphaNumeric": "Alfanumérico",
  "alphaAlpha": "Alfa-Alfa",
  "numeric": "Numérico",
  "labelDirectionDropDown": "Direção de Rótulo",
  "horizontal": "Horizontal",
  "vertical": "Vertical",
  "labelOriginDropDown": "Origem de Rótulo",
  "referenceSystemlTabDescription": "Defina o sistema de referência padrão.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Bloquear Definições - Irá impedir que o utilizador altere quaisquer das definições configuradas no widget"
});