define({
  "add": "Klik om nieuwe toe te voegen",
  "title": "Titel",
  "placeholderBookmarkName": "Naam van bladwijzer",
  "ok": "OK",
  "cancel": "Afbreken",
  "warning": "Bewerking voltooien!",
  "edit": "Bladwijzer bewerken",
  "errorNameExist": "Bladwijzer bestaat al.",
  "errorNameNull": "Ongeldige naam van bladwijzer.",
  "addBookmark": "Maak nieuwe",
  "thumbnail": "Thumbnail",
  "thumbnailHint": "Klik op de afbeelding om deze te bewerken",
  "displayBookmarksAs": "Bladwijzers weergeven als",
  "cards": "Kaarten",
  "list": "Lijst",
  "cardsTips": "Cardweergave",
  "listTips": "Lijstweergave",
  "makeAsDefault": "Standaard maken",
  "default": "Standaard",
  "editable": "Laat het toevoegen van bladwijzers toe in de widget.",
  "alwaysSync": "Toon bladwijzers uit de webmap",
  "configCustom": "Toon aangepaste bladwijzers",
  "import": "Importeren",
  "create": "Maken",
  "importTitle": "Bladwijzers importeren",
  "importFromWeb": "Importeer bladwijzers uit de huidige webmap",
  "selectAll": "Alles selecteren",
  "noBookmarkInConfig": "Klik op â€œImporterenâ€ of â€œNieuw makenâ€ om bladwijzers toe te voegen.",
  "noBookmarkInWebMap": "Er is geen bladwijzer in de kaart geconfigureerd.",
  "extent": "Extent",
  "saveExtent": "Sla kaartextent op voor deze bladwijzer",
  "savelayers": "Laagzichtbaarheid opslaan",
  "withVisibility": "Met laagzichtbaarheid",
  "bookmark": "Bladwijzer",
  "addBtn": "Toevoegen",
  "deleteBtn": "Verwijderen",
  "editBtn": "Bewerken",
  "dragReorderTip": "Vasthouden en slepen om opnieuw te rangschikken",
  "deleteBtnTip": "De bladwijzer verwijderen",
  "editBtnTip": "De bladwijzer bewerken"
});