define({
  "serviceUrl": "Service-URL festlegen:",
  "minIntSpacingLabel": "Minimale Gittergröße",
  "lineOpacityLabel": "Linientransparenz",
  "labelOpacityLabel": "Beschriftungstransparenz",
  "centerLabelOpacityLabel": "Transparenz der mittigen Beschriftung",
  "gridZonePlacementLabel": "Platzierung der Gitter-Zonenbeschriftung",
  "verticalLineLabels": "Beschriftungen für vertikale Linien",
  "styleHeaderLabel": "Style",
  "indexHeaderLabel": "Gitternetzkomponente",
  "colorHeaderLabel": "Farbe",
  "fontSizeHeaderLabel": "Schriftgröße",
  "lineWidthHeaderLabel": "Linienbreite",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertikal",
  "upperLeftLabel": "Oben links",
  "upperRightLabel": "Oben rechts",
  "lowerLeftLabel": "Unten links",
  "lowerRightLabel": "Unten rechts",
  "centerLabel": "Zentriert",
  "errorMessage": "Die Konfigurationsseite enthält Fehler. Beheben Sie sie vor dem Speichern.",
  "checkBoxLabel": "Gitternetz anzeigen, wenn das Widget geschlossen wird",
  "checkBoxLabelDashboard": "Gitternetz anzeigen",
  "gzd": "Gitter-Zoneneinteilung (Grid Zone Designation, GZD)",
  "gsid": "100.000-Meter-Gitternetzquadrat",
  "grid10k": "10.000-Meter-Gitternetzlinien",
  "grid1k": "1.000-Meter-Gitternetzlinien",
  "grid100m": "100-Meter-Gitternetzlinien",
  "grid10m": "10-Meter-Gitternetzlinien",
  "switchBasemap": "Grundkarte wechseln"
});