define({
  "serviceUrl": "サービス URL の設定:",
  "minIntSpacingLabel": "最小グリッド サイズ",
  "lineOpacityLabel": "ラインの不透明度",
  "labelOpacityLabel": "ラベルの不透明度",
  "centerLabelOpacityLabel": "中央ラベルの不透明度",
  "gridZonePlacementLabel": "グリッド ゾーン ラベルの配置",
  "verticalLineLabels": "縦軸のラベル",
  "styleHeaderLabel": "スタイル",
  "indexHeaderLabel": "グリッド コンポーネント",
  "colorHeaderLabel": "色",
  "fontSizeHeaderLabel": "フォント サイズ",
  "lineWidthHeaderLabel": "ライン幅",
  "horizontalLabel": "水平方向",
  "verticalLabel": "垂直方向",
  "upperLeftLabel": "左上",
  "upperRightLabel": "右上",
  "lowerLeftLabel": "左下",
  "lowerRightLabel": "右下",
  "centerLabel": "中央",
  "errorMessage": "構成ページにエラーが含まれています。修正してから保存してください。",
  "checkBoxLabel": "ウィジェットを閉じたときにグリッドを表示します",
  "checkBoxLabelDashboard": "グリッドの表示",
  "gzd": "グリッド ゾーン指定 (GZD)",
  "gsid": "100,000 メートル正方形 ID (GSID)",
  "grid10k": "10,000 メートル グリッド ライン",
  "grid1k": "1,000 メートル グリッド ライン",
  "grid100m": "100 メートル グリッド ライン",
  "grid10m": "10 メートル グリッド ライン",
  "switchBasemap": "ベースマップの切り替え"
});