define({
  "_widgetLabel": "Koordinačių konversija",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Laipsniai, Minutės, Sekundės",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dešimtainiai laipsniai – platuma / ilguma",
  "DDLongLatNotation": "Dešimtainiai laipsniai – ilguma / platuma",
  "DDMLatLongNotation": "Dešimtainių laipsnių minutės – platuma / ilguma",
  "DDMLongLatNotation": "Dešimtainių laipsnių minutės – ilguma / platuma",
  "DMSLatLongNotation": "Dešimtainių laipsnių sekundės – platuma / ilguma",
  "DMSLongLatNotation": "Dešimtainių laipsnių sekundės – ilguma / platuma",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - dažnio raidė",
  "UTMHemNotation": "UTM – pusrutulis (Š/P)",
  "formatInput": "Formato įvestis",
  "copyAll": "Kopijuoti viską",
  "copySuccessful": "Nukopijuota sėkmingai",
  "copyFailed": "Nepavyko nukopijuoti. Kaip alternatyvą naudokite Ctrl + C.",
  "parseCoordinatesError": "Negalima analizuoti koordinačių. Patikrinkite savo įvestį.",
  "comfirmInputNotation": "Patvirtinkite įvesties žymėjimą",
  "latLongWarningMessage": "Įvesties koordinatė buvo nustatyta, nes turimos platumos ir ilgumos prefikso ir sufikso reikšmės pateikė prefiksu pagrįstą koordinatę.",
  "inputLabel": "Įvestis",
  "outputLabel": "Išvestis",
  "cancelButtonLabel": "Atšaukti",
  "applyButtonLabel": "Taikyti",
  "posNegPrefixLabel": "Pridėti „+/-“ prefiksą prie teigiamų ir neigiamų skaičių",
  "editCoordinateDialogTitle": "Nustatyti koordinačių formato eilutę",
  "rememberDecisionLabel": "Prisiminti prisijungimo duomenis ir daugiau nebeklausti.<br/>",
  "coordinateInputLabel": "Įveskite koordinates arba paspauskite žemėlapyje",
  "zoomLabel": "Artinti",
  "multipleNotationLabel": "rasti įvestį atitinkantys žymėjimai. Patvirtinkite, kurį norite naudoti:",
  "copyToClipboard": "Kopijuoti į iškarpinę",
  "formatOutput": "Formato išvestis",
  "addNewNotation": "Pridėti naują žymėjimą",
  "notationAddedMessage": "Pridėtas naujas žymėjimas",
  "addLabel": "Pridėti",
  "removeCoordinate": "Pašalinti koordinatę",
  "expandOutput": "Išplėsti išvestį",
  "latitudeLabel": "Platuma",
  "longitudeLabel": "Ilguma",
  "quadrantLabel": "Kvadrantas",
  "keyLabel": "Raktas",
  "fifteenDegreeLabel": "15Â° kvad.",
  "oneDegreeLabel": "1Â° kvad.",
  "eastingLabel": "Platumos poslinkis",
  "northingLabel": "Ilgumos poslinkis",
  "zoneLabel": "Sritis",
  "bandLabel": "Matuoklio spalva",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Tinklelio kvadratas",
  "hemisphereLabel": "Pusrutulis"
});