define({
  "enableUndoRedo": "Omogućite opozivanje/ponavljanje radnje",
  "toolbarVisible": "Vidljiva traka sa alatkama",
  "toolbarOptions": "Opcije trake sa alatkama",
  "mergeVisible": "Objedini",
  "cutVisible": "Iseci",
  "reshapeVisible": "Preoblikuj",
  "back": "Nazad",
  "label": "Sloj",
  "edit": "Može da se izmeni",
  "update": "Onemogući ažuriranje geometrije",
  "fields": "Polja",
  "actions": "Radnje",
  "editpageName": "Naziv",
  "editpageAlias": "Pseudonim",
  "editpageVisible": "Vidljivo",
  "editpageEditable": "Može da se izmeni",
  "noLayers": "Nema dostupnih slojeva geoobjekata koji mogu da se izmene",
  "configureFields": "Konfigurišite polja sloja",
  "useFilterEdit": "Koristi filter šablona geoobjekta",
  "display": "Prikaz",
  "autoApplyEditWhenGeometryIsMoved": "Automatski primeni izmenu kada se geometrija pomeri",
  "snappingTolerance": "Podesi toleranciju snapovanja u pikselima",
  "popupTolerance": "Podesi toleranciju iskačućeg prozora za izmenu atributa u pikselima",
  "stickyMoveTolerance": "Podesi toleranciju lepljivog pomeranja u pikselima",
  "usingSaveButton": "Ne primenjuj izmene na atributima pre nego što se klikne na dugme Sačuvaj"
});