define({
  "routeUrl": "URL adresa usmeravanja",
  "locatorUrl": "URL adresa geokodera",
  "geocoderOptions": "Opcije geokodera",
  "autoComplete": "Automatsko popunjavanje",
  "maximumSuggestions": "Maksimalno predloga",
  "minCharacters": "Minimalno karaktera",
  "searchDelay": "Odlaganje pretrage",
  "placeholder": "Čuvar mesta",
  "routeOptions": "Opcije usmeravanja",
  "directionsLanguage": "Jezik uputstava",
  "directionsLengthUnits": "Jedinice dužine u uputstvima za navigaciju",
  "directionsOutputType": "Tip izlaznih rezultata uputstva za navigaciju",
  "impedanceAttribute": "Atributi otpora",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "parametersTip": "Pravilno postavite parametre!",
  "complete": "Završi",
  "completeNoEvents": "Završi bez događaja",
  "instructionsOnly": "Samo instrukcije",
  "standard": "Standardna verzija",
  "summaryOnly": "Samo rezime",
  "travelModesUrl": "URL adresa režima putovanja",
  "searchPlaceholder": "Pronađi adresu ili mesto",
  "trafficLayerUrl": "URL adresa sloja saobraćaja",
  "presetDestinations": "Unapred podešena zaustavljanja",
  "startPoint": "Početna tačka",
  "endPoint": "Krajnja tačka",
  "destinationHolder": "Adresa ili koordinate",
  "optional": "Opcionalno."
});