define({
  "_widgetLabel": "Gráfico de referencia con cuadrícula",
  "newGRGFromAreaButtonLabel": "Definir una cuadrícula con un área",
  "newGRGFromPointButtonLabel": "Definir una cuadrícula con un punto",
  "newGRGFromAreaTitle": "Definir una cuadrícula con un área",
  "newGRGFromPointTitle": "Definir una cuadrícula con un punto",
  "newGRGBySizeButtonLabel": "Mediante dimensión",
  "newGRGFromRefSystemButtonLabel": "Mediante sistema de referencia",
  "newGRGByTimeLabel": "Mediante tiempo y velocidad",
  "newGRGFromNonStandardButtonLabel": "Definir cuadrícula no estándar",
  "newGRGAreaBySizeTitle": "GRG de un área mediante dimensiones",
  "newGRGAreaBySizeDefineAreaLabel": "Área GRG",
  "addGRGAreaPolygonToolTip": "Dibujar área GRG mediante un polígono",
  "addGRGAreaExtentToolTip": "Dibujar área GRG mediante una extensión",
  "rotation": "Rotación de cuadrícula",
  "numberRowsColumnsLabel": "Definir número de filas y columnas",
  "newGRGAreaByRefSystemTitle": "GRG de un área mediante sistema de referencia",
  "gridSize": "Tamaño de cuadrícula",
  "UTMZoneandBand": "Zona de cuadrícula",
  "100000m": "100.000 metros",
  "10000m": "10.000 metros",
  "1000m": "1.000 metros",
  "100m": "100 metros",
  "10m": "10 metros",
  "clipGrid": "Clip de cuadrícula a área GRG",
  "newGRGAreaFromNonStandardTitle": "Nueva NRG",
  "newGRGPointBySizeTitle": "GRG de un punto mediante dimensión",
  "newGRGPointByRefSystemTitle": "GRG de un punto mediante sistema de referencia",
  "newGRGPointByTimeTitle": "GRG de un punto usando tiempo y velocidad",
  "time": "Tiempo",
  "rate": "Velocidad",
  "hours": "Horas",
  "minutes": "Minutos",
  "seconds": "Segundos",
  "ftPerSec": "Pies / segundo",
  "ftPerHour": "Pies / hora",
  "kmPerSec": "Kilómetros / segundo",
  "kmPerHour": "Kilómetros / hora",
  "mPerSec": "Metros / segundo",
  "mPerHour": "Metros / hora",
  "miPerSec": "Millas / segundo",
  "miPerHour": "Millas / hora",
  "nMPerSec": "Millas náuticas / segundo",
  "nMPerHour": "Millas náuticas / hora",
  "settingsTitle": "Ajustes",
  "labelSettingsLabel": "Configuración de etiqueta",
  "labelSettingsButtonLabel": "Configurar ajustes de etiquetas",
  "gridSettingsLabel": "Configuración de la cuadrícula",
  "gridSettingsButtonLabel": "Configurar ajustes de cuadrícula",
  "transparency": "Transparencia",
  "labelStyle": "Estilo de etiqueta",
  "font": "Fuente",
  "textSize": "Tamaño de texto",
  "textColor": "Color del texto",
  "halo": "Halo",
  "show": "Mostrar",
  "lockSettings": "Los ajustes han sido bloqueados por el propietario de la aplicación",
  "gridSettings": {
    "cellShape": "Forma de celda",
    "cellUnits": "Unidades de celda",
    "cellOutline": "Ajustes de contorno de celda",
    "cellFill": "Ajustes de relleno de celda",
    "gridReferenceSystem": "Sistema de referencia",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Origen de la etiqueta",
    "labelType": "Tipo de etiqueta",
    "labelDirection": "Dirección de la etiqueta",
    "gridOrigin": "Origen de la cuadrícula",
    "default": "Rectángulo",
    "hexagon": "Hexágono",
    "miles": "Millas",
    "kilometers": "Kilómetros",
    "feet": "Pies",
    "meters": "Metros",
    "yards": "Yardas",
    "nautical-miles": "Millas náuticas",
    "lowerLeft": "Inferior izquierda",
    "lowerRight": "Inferior derecha",
    "upperLeft": "Superior izquierda",
    "upperRight": "Superior derecha",
    "center": "Centro",
    "alphaNumeric": "Alfanumérico",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Numérico",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Mostrar etiquetas"
  },
  "publishTitle": "Publicar GRG en portal",
  "publishGRGBtn": "Publicar",
  "GRGLayerName": "Nombre de capa GRG publicada",
  "invalidGRGLayerName": "El nombre de la capa solo debe contener caracteres alfanuméricos y guiones bajos",
  "missingGRGLayerName": "Debe indicar un nombre para el GRG",
  "publishingFailedLayerExists": "Fallo de publicación: ya tiene un servicio de entidades denominado {0}. Elija otro nombre.",
  "checkService": "Comprobar servicio: {0}",
  "createService": "Crear servicio: {0}",
  "unableToCreate": "Imposible crear: {0}",
  "addToDefinition": "Agregar a definición: {0}",
  "successfullyPublished": "Capa web publicada correctamente{0}Administar la capa web",
  "userRole": "Imposible crear el servicio porque el usuario no tiene permisos",
  "createGRGBtn": "Crear GRG",
  "clearGRGBtn": "Borrar",
  "labelFormat": "Formato de etiqueta",
  "helpIconTooltip": "Z: Designador de zona de cuadrícula (GZD)\nS: Identificación de cuadrado de cuadrícula de 100.000 metros (GSID)\nX: Valor Este (coordenada X)\nY: Valor Norte (coordinada Y)\n\nEjemplos:\nZSXY es 15SWC8081751205\nZS X,Y es 15SWC 80817,51205",
  "addPointToolTip": "Agregar origen de GRG",
  "cellWidth": "Ancho de celda (x)",
  "cellHeight": "Altura de celda (y)",
  "invalidNumberMessage": "El valor introducido no es válido",
  "invalidRangeMessage": "El valor debe ser mayor que 0",
  "gridAngleInvalidRangeMessage": "El valor debe estar comprendido entre -89,9 y 89,9",
  "formatIconTooltip": "Formato de entrada",
  "coordInputLabel": "Origen de GRG (DD)",
  "setCoordFormat": "Definir cadena de caracteres de formato de coordenadas",
  "prefixNumbers": "Agregar prefijo '+/-' a los números positivos y negativos",
  "cancelBtn": "Cancelar",
  "applyBtn": "Solicitar participación",
  "comfirmInputNotation": "Confirmar notación de entrada",
  "notationsMatch": "notaciones que coinciden con su entrada. Confirme cuál desea usar:",
  "numberOfCellsHorizontal": "N.º de celdas horizontales",
  "numberOfCellsVertical": "N.º de celdas verticales",
  "gridAngle": "Rotación de cuadrícula",
  "tooManyCellsErrorMessage": "Está intentando crear una cuadrícula que consta de más de 2.000 celdas. Es recomendable reducir el número de celdas creadas, cambiando para ello el tamaño de la cuadrícula o su área.",
  "missingParametersMessage": "<p>El formulario de creación de GRG tiene parámetros no válidos o ausentes. Asegúrese de que:</p><ul><li>Se haya trazado un área de GRG.</li><li>El ancho y la altura de celda contengan valores válidos.</li></ul>",
  "missingOriginParametersMessage": "<p>El formulario de creación de GRG tiene parámetros no válidos o ausentes. Asegúrese de que:</p><ul><li>Se haya definido un origen de GRG.</li><li>El tiempo, la velocidad y los ángulos introducidos contengan valores válidos.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>El formulario de creación de GRG tiene parámetros no válidos o ausentes. Asegúrese de que el ancho y la altura de celda introducidos contengan valores válidos.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>El formulario de creación de GRG tiene parámetros no válidos o ausentes. Asegúrese de que los números de celdas horizontales y verticales introducidos contengan valores válidos.</p>",
  "drawPointToolTip": "Haga clic para agregar un punto de origen de GRG",
  "missingLayerNameMessage": "Debe introducir un nombre de capa válido antes de publicar",
  "parseCoordinatesError": "No se pueden analizar las coordenadas. Compruebe la entrada.",
  "grgPolarRegionError": "La extensión de GRG está dentro de una zona polar. Las celdas que caigan dentro de la región polar no se crearán.",
  "grgPolarOriginError": "El punto de origen de GRG no puede estar dentro de una región polar al crear un GRG mediante un sistema de referencia.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Grados decimales - Latitud/longitud",
  "DDLongLatNotation": "Grados decimales - Longitud/latitud",
  "DDMLatLongNotation": "Grados minutos decimales - Latitud/longitud",
  "DDMLongLatNotation": "Grados minutos decimales - Longitud/latitud",
  "DMSLatLongNotation": "Grados minutos segundos - Latitud/longitud",
  "DMSLongLatNotation": "Grados minutos segundos - Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra de banda",
  "UTMHemNotation": "UTM - Hemisferio (N/S)"
});