///////////////////////////////////////////////////////////////////////////
// Copyright © 2016 Esri. All Rights Reserved.
//
// Licensed under the Apache License Version 2.0 (the 'License');
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
///////////////////////////////////////////////////////////////////////////
define({
  "units": {
    "feetUnit": "Čevlji/Kvadratni čevlji",
    "milesUnit": "Milje/Akri",
    "metersUnit": "Metri/Kvadratni metri",
    "kilometersUnit": "Kilometri/Kvadratni kilometri",
    "hectaresUnit": "Kilometri/Hektarji"
  },
  "analysisTab": {
    "analysisTabLabel": "Analiza",
    "selectAnalysisLayerLabel": "Izberite sloje analize",
    "addLayerLabel": "Dodaj sloje",
    "noValidLayersForAnalysis": "V izbrani spletni karti ni najdenih veljavnih slojev.",
    "noValidFieldsForAnalysis": "V izbrani spletni karti ni najdenih veljavnih slojev. Odstranite izbrani sloj.",
    "addLayersHintText": "Namig: Izberite sloje in polja za analizo in prikaz v poročilu",
    "addLayerNameTitle": "Ime sloja",
    "addFieldsLabel": "Dodaj polje",
    "addFieldsPopupTitle": "Izberi polja",
    "addFieldsNameTitle": "Imena polj",
    "aoiToolsLegendLabel": "Orodja interesnih območij (AOI)",
    "aoiToolsDescriptionLabel": "Omogočite orodja za ustvarjanje interesnega območja in določite njihove napise",
    "placenameLabel": "Ime mesta",
    "drawToolsLabel": "Orodja za risanje",
    "uploadShapeFileLabel": "Naloži shapefile",
    "coordinatesLabel": "Koordinate",
    "coordinatesDrpDwnHintText": "Namig: Izberite enoto za prikaz vnesenih traverz",
    "coordinatesBearingDrpDwnHintText": "Namig: Izberite smerni kot za prikaz vnesenih traverz",
    "allowShapefilesUploadLabel": "Naloži shapefile za analizo",
    "allowShapefilesUploadLabelHintText": "Namig: Prikaži »Naloži shapefile za analizo« v zavihku Poročilo",
    "allowVisibleLayerAnalysisLabel": "Ne analiziraj ali poročaj o rezultatih za sloje, ki niso vidni",
    "allowVisibleLayerAnalysisHintText": "Namig: Sloji, ki so bili izklopljeni ali niso vidni zaradi nastavitev vidnosti merila, ne bodo analizirani ali vključeni v natisnjenih ali prenesenih rezultatih.",
    "areaUnitsLabel": "Pokaži rezultate analize v",
    "maxFeatureForAnalysisLabel": "Maksimalno geoobjektov za analizo",
    "maxFeatureForAnalysisHintText": "Namig: Nastavite maksimalno število geoobjektov za analizo",
    "searchToleranceLabelText": "Toleranca iskanja",
    "searchToleranceHint": "Namig: Odstopanje pri iskanju se uporablja samo za analiziranje točkovnih in linijskih vhodnih podatkov",
    "placenameButtonText": "Ime mesta",
    "drawToolsButtonText": "Riši",
    "shapefileButtonText": "Shapefile",
    "coordinatesButtonText": "Koordinate",
    "invalidLayerErrorMsg": "Konfiguriraj polja za"
  },
  "downloadTab": {
    "downloadLegend": "Prenesi nastavitve",
    "reportLegend": "Nastavitve poročila",
    "downloadTabLabel": "Prenesi",
    "syncEnableOptionLabel": "Geoobjektni sloji",
    "syncEnableOptionHint": "Namig: Uporablja se za prenos geoobjektnih informacij za geoobjekte, ki sekajo interesno območje v prikazanih formatih.",
    "syncEnableOptionNote": "Opomba: Sinhronizacija geoobjektnih storitev je obvezna za datoteke File Geodatabase in shapefile. Format shapefile je podprt samo pri gostujočih geoobjektnih slojih ArcGIS Online.",
    "extractDataTaskOptionLabel": "Opravilo ekstrakcije podatkov geoprocesne storitve",
    "extractDataTaskOptionHint": "Namig: Uporabite opravilo ekstrakcije geoobjektov geoprocesne storitve za prenos geoobjektov, ki sekajo interesno območje, v formatu shapefile ali File Geodatabase.",
    "cannotDownloadOptionLabel": "Onemogoči prenos",
    "syncEnableTableHeaderTitle": {
      "layerNameLabel": "Ime sloja",
      "csvFileFormatLabel": "CSV",
      "fileGDBFormatLabel": "File Geodatabase",
      "ShapefileFormatLabel": "Shapefile",
      "allowDownloadLabel": "Dovoli prenos"
    },
    "setButtonLabel": "Nastavi",
    "GPTaskLabel": "Določite url za geoprocesno storitev",
    "printGPServiceLabel": "URL storitve tiskanja",
    "setGPTaskTitle": "Določi zahtevan URL geoprocesne storitve",
    "logoLabel": "Logotip",
    "logoChooserHint": "Namig: Kliknite ikono za zamenjavo slike",
    "footnoteLabel": "Sprotna opomba",
    "columnTitleColorPickerLabel": "Barva za naslove stolpcev",
    "reportTitleLabel": "Naslov poročila",
    "errorMessages": {
      "invalidGPTaskURL": "Neveljavna geoprocesna storitev. Izberite geoprocesno storitev, ki vsebuje Opravilo ekstrakcije podatkov.",
      "noExtractDataTaskURL": "Izberite katerokoli geoprocesno storitev, ki vsebuje Opravilo ekstrakcije podatkov.",
      "duplicateCustomOption": "Za ${duplicateValueSizeName} obstaja podvojen vnos.",
      "invalidLayoutWidth": "Vnesena je neveljavna širina za ${customLayoutOptionValue}.",
      "invalidLayoutHeight": "Vnesena je neveljavna višina za ${customLayoutOptionValue}.",
      "invalidLayoutPageUnits": "Za ${customLayoutOptionValue} je izbrana neveljavna merska enota strani.",
      "failtofetchbuddyTaskDimension": "Napaka pri pridobivanju informacij o dimenziji povezanega opravila. Poskusite znova.",
      "failtofetchbuddyTaskName": "Napaka pri pridobivanju imena povezanega opravila. Poskusite znova.",
      "failtofetchChoiceList": "Napaka pri pridobivanju seznama za izbiro iz storitve tiskanja. Poskusite znova.",
      "invalidWidth": "Neveljavna širina.",
      "invalidHeight": "Neveljavna višina."
    },
    "addCustomLayoutTitle": "Dodaj postavitev po meri",
    "customLayoutOptionHint": "Namig: V možnosti tiskanja dodajte možnost postavitve po meri iz storitve tiskanja.",
    "reportDefaultOptionLabel": "Privzeta postavitev",
    "pageSizeUnits": {
      "millimeters": "Milimetri",
      "points": "Točke"
    }
  },
  "generalTab": {
    "generalTabLabel": "Splošno",
    "tabLabelsLegend": "Napisi plošče",
    "tabLabelsHint": "Namig: Določi napise",
    "AOITabLabel": "Plošča interesnega območja",
    "ReportTabLabel": "Plošča poročila",
    "bufferSettingsLegend": "Nastavitve obrisa",
    "defaultBufferDistanceLabel": "Privzeta razdalja obrisa",
    "defaultBufferUnitsLabel": "Enote obrisa",
    "generalBufferSymbologyHint": "Namig: Nastavi simbologijo za prikaz obrisov okrog določenih interesnih območjih",
    "aoiGraphicsSymbologyLegend": "Simbologija grafike interesnega območja",
    "aoiGraphicsSymbologyHint": "Namig: Nastavi simbologijo točkovnim, linijskim in poligonskim interesnim območjem",
    "pointSymbologyLabel": "Točka",
    "previewLabel": "Predogled",
    "lineSymbologyLabel": "Linija",
    "polygonSymbologyLabel": "Poligon",
    "aoiBufferSymbologyLabel": "Simbologija obrisa",
    "pointSymbolChooserPopupTitle": "Simbol naslova ali lokacije",
    "polygonSymbolChooserPopupTitle": "Izberite simbol, da osvetlite poligon",
    "lineSymbolChooserPopupTitle": "Izberite simbol za osvetljevanje linije",
    "aoiSymbolChooserPopupTitle": "Nastavite simbol obrisa",
    "aoiTabText": "Interesno območje",
    "reportTabText": "Poročilo",
    "invalidSymbolValue": "Neveljavna vrednost simbola."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Nastavitve vira iskanja",
    "searchSourceSettingTitle": "Nastavitve vira iskanja",
    "searchSourceSettingTitleHintText": "Dodajte in konfigurirajte geokodirne storitve ali geoobjektne sloje kot vire iskanja. Ti viri določajo, kaj je mogoče iskati znotraj iskalnega polja.",
    "addSearchSourceLabel": "Dodajte vir iskanja",
    "featureLayerLabel": "Geoobjektni sloj",
    "geocoderLabel": "Geokodirnik",
    "generalSettingLabel": "Splošna nastavitev",
    "allPlaceholderLabel": "Nadomestno besedilo za iskanje:",
    "allPlaceholderHintText": "Namig: Vnesite besedilo, ki bo prikazano kot nadomestno besedilo med iskanjem po vseh slojih in geokodirniku",
    "generalSettingCheckboxLabel": "Pokaži pojavno okno za najdeni geoobjekt ali lokacijo",
    "countryCode": "Šifre države ali regije",
    "countryCodeEg": "npr. ",
    "countryCodeHint": "Če to vrednost pustite prazno, bo iskanje potekalo po vseh državah in regijah",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Išči samo v trenutnem obsegu karte",
    "zoomScale": "Povečava merila",
    "locatorUrl": "URL geokodirnika",
    "locatorName": "Ime geokodirnika",
    "locatorExample": "Primer",
    "locatorWarning": "Ta različica geokodirnih storitev ni podprta. Pripomoček podpira različico geokodirne storitve 10.0 in novejšo.",
    "locatorTips": "Priporočila niso na voljo, ker geokodirna storitev ne podpira predlagane zmožnosti.",
    "layerSource": "Vir sloja",
    "setLayerSource": "Nastavi vir sloja",
    "setGeocoderURL": "Nastavi URL geokodirnika",
    "searchLayerTips": "Priporočila niso na voljo, ker geoobjektna storitev ne podpira zmožnosti številčenja strani.",
    "placeholder": "Nadomestno besedilo",
    "searchFields": "Iskalna polja",
    "displayField": "Prikaži polje",
    "exactMatch": "Natančno ujemanje",
    "maxSuggestions": "Maksimalno predlogov",
    "maxResults": "Maksimalno rezultatov",
    "enableLocalSearch": "Omogoči lokalno iskanje",
    "minScale": "Minimalno merilo",
    "minScaleHint": "Ko je merilo karte večje od tega merila, bo uporabljeno lokalno iskanje",
    "radius": "Polmer",
    "radiusHint": "Določa polmer območja okrog trenutnega središča karte, ki je uporabljeno za povečanje števila kandidatov za geokodiranje, tako da so najprej prikazani kandidati, ki so najbližji lokaciji",
    "setSearchFields": "Nastavi iskalna polja",
    "set": "Nastavi",
    "invalidUrlTip": "URL ${URL} ni veljaven ali dostopen.",
    "invalidSearchSources": "Neveljavne nastavitve vira iskanja"
  },
  "errorMsg": {
    "textboxFieldsEmptyErrorMsg": "Izpolnite obvezna polja",
    "bufferDistanceFieldsErrorMsg": "Vnesite veljavne vrednosti",
    "invalidSearchToleranceErrorMsg": "Vnesite veljavno vrednost odstopanja pri iskanju",
    "atLeastOneCheckboxCheckedErrorMsg": "Neveljavna konfiguracija: zahtevano je vsaj eno orodje interesnega območja.",
    "noLayerAvailableErrorMsg": "Sloji niso na voljo",
    "layerNotSupportedErrorMsg": "Ni podprto ",
    "noFieldSelected": "Uporabite dejanje urejanja za izbiro polja za analizo",
    "duplicateFieldsLabels": "Podvoji napis »${labelText}«, dodan za : »${itemNames}«",
    "noLayerSelected": "Izberite vsaj en sloj za analizo",
    "errorInSelectingLayer": "Operacije izbire sloja ni mogoče dokončati. Poskusite znova.",
    "errorInMaxFeatureCount": "Vnesite maksimalno veljavno število geoobjektov za analizo."
  }
});