define({
  root: ({
    showLayerLabels: "Display time-aware layer names on the widget",
    autoPlay: "Automatically play the slider",
    dateAndTimeFormat: "Date and time format",
    mapDefault: "Map default",
    custom: "Custom",
    formatInstruction: "Format instruction",
    playback: "playback position saved with map",

    MMMMYYYY: "July 2015",
    MMMYYYY: "Jul 2015",
    MMMMDYYYY: "July 21,2015",
    dddMMMDDYYYY: "Tue Jul 21,2015",
    MDDYYYY: "7/21/2015",
    YYYYMDD: "2015/7/21",
    MDDYY: "7/21/15",
    YYYY: "2015",
    MDDYYYYhmma: "7/21/2015 8:00 am",
    dddMMMDDhmma: "Tue Jul 21 8:00 am"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});