define({
  "_widgetLabel": "Vodič za hitni odgovor",
  "ergMainPageTitle": "Temelji se na Vodiču za hitni odgovor iz 2016.",
  "coordInputLabelStart": "Lokacija izljeva (DD)",
  "coordInputLabel": "Lokacija izljeva",
  "addPointToolTip": "Dodaj lokaciju izljeva",
  "drawPointToolTip": "Kliknite da biste dodali lokaciju izljeva",
  "material": "Materijal",
  "materialPlaceholder": "Počnite tipkati za traženje materijala",
  "table3Message": "Za materijal koji ste odabrali potrebne su dodatne informacije ako se radi o velikom izljevu.\n\nProvjerite jeste li odabrali ispravne vrijednosti za brzinu vjetra i spremnik za transport.",
  "table2Message": "Materijal koji ste odabrali može proizvesti veliku količinu otrovnih plinova za udisanje pri izlijevanju u vodu.\n\nMožete razmisliti o upotrebi sljedećih materijala:\n\n",
  "spillSize": "Veličina izljeva",
  "small": "Mala",
  "large": "Velika",
  "fireLabel": "Prikaži zonu izolacije požara",
  "weatherLabel": "Trenutačno vrijeme na lokaciji izljeva",
  "weatherIntialText": "<br />Ažurirat će se kad se utvrdi lokacija izljeva",
  "temperature": "Temperatura",
  "wind": "Vjetar",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Podaci o vremenu nisu dobiveni. Ručno ažurirajte vrijednosti brzine vjetra i vremena izlijeva",
  "windDirection": "Smjer vjetra (puše u smjeru)",
  "timeOfSpill": "Vrijeme izljeva",
  "day": "Dan",
  "night": "Noć",
  "windSpeed": "Brzina vjetra",
  "low": "Nisko",
  "moderate": "Umjereno",
  "high": "Visoko",
  "transportContainer": "Spremnik za transport",
  "rail": "Vagon sa spremnikom",
  "semi": "Kamion ili prikolica sa spremnikom za autocestu",
  "mton": "Cilindri s kapacitetom od više tona",
  "ston": "Više malih cilindara ili cilindar s kapacitetom od jedne tone",
  "ag": "Spremnik za poljoprivredne svrhe",
  "msm": "Više malih cilindara",
  "bleveLabel": "Prikaži zonu izolacije BLEVE",
  "capacity": "Kapacitet spremnika (litre)",
  "bleveMessage": "Za materijal koji ste odabrali dodatna udaljenost evakuacije može se prikazati za BLEVE.\n\nDa biste to omogućili, postavite postavku Prikaži zonu izolacije BLEVE na uključeno i odaberite odgovarajući kapacitet spremnika.",
  "noPAZoneMessage": "Nema udaljenosti za zaštitne mjere za ovaj materijal. Izračunate su samo zone početne izolacije i evakuacije",
  "settingsTitle": "Postavke",
  "spillLocationLabel": "Lokacija izljeva",
  "spillLocationButtonLabel": "Konfiguriraj postavke lokacije izljeva",
  "IISettingsLabel": "Zona početne izolacije",
  "IIButtonLabel": "Konfiguriraj postavke početne izolacije",
  "PASettingsLabel": "Zona zaštitnih mjera",
  "PAButtonLabel": "Konfiguriraj postavke zaštitnih mjera",
  "downwindSettingsLabel": "Zona niz vjetar",
  "downwindButtonLabel": "Konfiguriraj postavke niz vjetar",
  "fireSettingsLabel": "Zona izolacije požara",
  "fireButtonLabel": "Konfiguriraj postavke izolacije požara",
  "bleveSettingsLabel": "Zona izolacije BLEVE",
  "bleveButtonLabel": "Konfiguriraj postavke BLEVE",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Linija s crticom",
    "esriSLSDashDot": "Linija s crticom i točkom",
    "esriSLSDashDotDot": "Linija s crticom i dvije točke",
    "esriSLSDot": "Točka",
    "esriSLSLongDash": "Duga crtica",
    "esriSLSLongDashDot": "Duga crtica i točka",
    "esriSLSNull": "Nema vrijednosti",
    "esriSLSShortDash": "Kratka crtica",
    "esriSLSShortDashDot": "Kratka crtica i točka",
    "esriSLSShortDashDotDot": "Kratka crtica i dvije točke",
    "esriSLSShortDot": "Kratka točka",
    "esriSLSSolid": "Puna linija"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unatrag",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Naprijed",
    "esriSFSHorizontal": "Vodoravni",
    "esriSFSNull": "Nema vrijednosti",
    "esriSFSSolid": "Puna linija",
    "esriSFSVertical": "Uspravno"
  },
  "resultsTitle": "Rezultati",
  "publishERGBtn": "Objavi",
  "ERGLayerName": "Objavljen naziv sloja ERG",
  "invalidERGLayerName": "Naziv sloja mora sadržavati samo alfanumeričke znakove i podvlake",
  "missingERGLayerName": "Morate navesti naziv za ERG",
  "publishingFailedLayerExists": "Objavljivanje nije uspjelo: već imate uslugu geoobjekata s nazivom {0}. Odaberite drugi naziv.",
  "checkService": "Provjeri uslugu: {0}",
  "createService": "Stvori uslugu: {0}",
  "unableToCreate": "Nije moguće stvoriti: {0}",
  "addToDefinition": "Dodaj definiciji: {0}",
  "successfullyPublished": "Uspješno objavljen web-sloj{0}Upravljaj web-slojem",
  "userRole": "Nije moguće stvoriti uslugu jer korisnik nema dopuštenja",
  "transparency": "Prozirnost",
  "outline": "Obris",
  "fill": "Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",
  "createERGBtn": "Stvori zone",
  "clearERGBtn": "Očisti",
  "labelFormat": "Format oznake",
  "helpIconTooltip": "Prag između malih i velikih veličina izljeva iznosi:\nTekućine - 55 galona (208 litara)\nČvrste tvari - 60 funti (300 kilograma)",
  "cellWidth": "Širina ćelije (x)",
  "cellHeight": "Visina ćelije (y)",
  "invalidNumberMessage": "Unesena vrijednost nije valjana",
  "invalidRangeMessage": "Vrijednost mora biti veća od 0",
  "gridAngleInvalidRangeMessage": "Vrijednost mora biti između -89,9 i 89,9",
  "formatIconTooltip": "Format unosa",
  "setCoordFormat": "Postavi niz formata koordinata",
  "prefixNumbers": "Dodajte prefiks „+/-” pozitivnim i negativnim brojevima",
  "cancelBtn": "Odustani",
  "applyBtn": "Primijeni",
  "comfirmInputNotation": "Notacija potvrde unosa",
  "notationsMatch": "bilješke se podudaraju s vašim unosom, potvrdite što biste htjeli upotrijebiti:",
  "missingLayerNameMessage": "Morate unijeti važeći naziv sloja prije objavljivanja",
  "parseCoordinatesError": "Nije moguće parsirati koordinate. Provjerite unos.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stupnjevi - geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stupnjevi - geografska dužina/širina",
  "DDMLatLongNotation": "Stupnjevi decimalne minute - geografska širina/dužina",
  "DDMLongLatNotation": "Stupnjevi decimalne minute - geografska dužina/širina",
  "DMSLatLongNotation": "Stupnjevi minute sekunde - geografska širina/dužina",
  "DMSLongLatNotation": "Stupnjevi minute sekunde - geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - slovo retka",
  "UTMHemNotation": "UTM - hemisfera (N/S)"
});