define({
  "labelBookmarkName": "Bladwijzer maken voor de huidige weergave",
  "labelPlay": "Alles afspelen",
  "labelStop": "Stoppen",
  "labelDelete": "Verwijderen",
  "placeholderBookmarkName": "Naam van bladwijzer",
  "errorNameExist": "Bladwijzer bestaat al.",
  "errorNameNull": "Ongeldige naam van bladwijzer.",
  "editTip": "Bladwijzers bewerken",
  "exitEditTip": "Bewerkingsmodus afsluiten",
  "syncTip": "Synchroniseren",
  "cardsTips": "Rasterweergave",
  "listTips": "Lijstweergave",
  "addBtn": "Toevoegen",
  "deleteBtn": "Verwijderen",
  "changeThumbnailTip": "Miniatuur wijzigen",
  "dragReorderTip": "Vasthouden en slepen om opnieuw te rangschikken",
  "deleteBtnTip": "De bladwijzer verwijderen",
  "editBtnTip": "De bladwijzer bewerken",
  "withVisibility": "Met laagzichtbaarheid",
  "searchBookmark": "Zoeken",
  "bookmarksFromConfig": "Voorgeconfigureerde bladwijzers",
  "bookmarksFromCache": "Plaatselijke tijdelijke bladwijzers",
  "notice": "Mededeling",
  "changeNoticeTips": "Wijzigingen worden alleen opgeslagen in de cache van uw browser. Synchronisatie tussen de widget en de configuratie ervan is losgekoppeld zodra u wijzigingen aanbrengt.",
  "syncNoticeTips": "Dit zal alle wijzigingen wissen en de geconfigureerde bladwijzers herstellen.",
  "dontShowAgain": "Niet meer tonen",
  "saveVisibility": "Laagzichtbaarheid opslaan",
  "_widgetLabel": "Bladwijzer"
});