define({
  "queries": "Consultas",
  "addNew": "Adicionar novo",
  "newQuery": "Nova consulta",
  "queryLayer": "Consultar camada",
  "setSource": "Configurar",
  "setDataSource": "Configurar fonte de dados",
  "name": "Nome",
  "querySource": "Fonte de dados",
  "queryName": "Nome da tarefa",
  "queryDefinition": "Definição de filtro",
  "resultsSetting": "Configuração de resultados",
  "symbolSetting": "Configuração de símbolo",
  "resultSettingTip": "Defina quais e como exibir os resultados de saída.",
  "resultItemTitle": "Título de cada item do resultado",
  "resultItemContent": "Estes atributos do campo aparecerão",
  "fieldsSetTip": "Verifique os campos que você deseja exibir. Selecione um campo para atualizar seu nome alternativo, ordem e formato.",
  "addField": "Adicionar campo",
  "visibility": "Visibilidade",
  "alias": "Nome Alternativo",
  "specialType": "Tipo especial",
  "actions": "Ações",
  "none": "Nenhum",
  "link": "Link",
  "image": "Imagem",
  "noField": "Nenhum campo",
  "operationalLayerTip": "Adicionar resultado como camada operacional",
  "setLayerSymbolTip": "Configure o símbolo para resultados da consulta: ",
  "setSelectedSymbolTip": "Configurar símbolo da feição selecionada.",
  "notUseFilter": "Não utilizar filtro",
  "setSourceTip": "Configure a origem da consulta.",
  "setFilterTip": "Configure o filtro corretamente.",
  "ok": "Ok",
  "cancel": "Cancelar",
  "noFilterTip": "Sem expressão de filtro definida, esta tarefa de consulta listará todas as feições na fonte de dados especificada.",
  "relationships": "Relacionamentos",
  "addRelationshipLayer": "Adicionar novo relacionamento",
  "relatedTo": "Relacionado à",
  "selectOption": "Selecione..",
  "resultItemSorting": "Classificação de item do resultado",
  "field": "Campo",
  "sortingOrder": "Ordenar",
  "configureFieldsTip": "Configure os campos que o resultado da consulta será classificado.",
  "setSortingFields": "Definir campos de classificação",
  "ascending": "Crescente",
  "descending": "Descendente",
  "sortBy": "Classificar por",
  "thenBy": "Então por",
  "addTask": "Adicionar tarefa",
  "noTasksTip": "Nenhuma consulta configurada. Clique em \"${newQuery}\" para adicionar uma nova.",
  "infoText": "Info",
  "filters": "Filtros",
  "results": "Resultados",
  "optionsText": "Opções",
  "summaryText": "Resumo",
  "attributeFilter": "Filtro de atributos",
  "attributeFilterTip": "Defina expressões de atributo para utilizar no widget para filtrar a camada de consulta.",
  "defineWhereClause": "Defina uma cláusula 'where' para a consulta.",
  "noExpressionDefinedTip": "Nenhuma expressão definida. Todos os registros serão retornados.",
  "setExpressions": "Definir expressões",
  "spatialFilter": "Filtros espaciais",
  "spatialFilterTip": "Escolha quais filtros espaciais estarão disponíveis para usuários finais.",
  "defaultOption": "Padrão",
  "useCurrentExtentTip": "Retornar somente feições dentro da extensão de mapa atual",
  "useDrawGraphicTip": "Somente retorna feições que interseccionam com a forma desenhada no mapa",
  "useFeaturesTip": "Retornar somente feições que têm um relacionamento espacial com feições em outra camada",
  "noSpatialLimitTip": "Retornar feições dentro da extensão total do mapa",
  "drawingTools": "Escolher ferramentas de desenho",
  "bufferSettings": "Habilitar opção de buffer",
  "defaultDistance": "Distância Padrão",
  "bufferDistance": "Distância do Buffer",
  "defaultUnit": "Unidade Padrão",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "availableSpatialRelationships": "Escolha as regras de relacionamento espacial",
  "setSpatialRelationships": "Configurar relacionamentos espaciais",
  "availability": "Disponibilidade",
  "relationship": "Relacionamento",
  "label": "Rótulo",
  "intersect": "interseccionar",
  "contain": "contém",
  "areContainedIn": "estão contidos em",
  "cross": "cruz",
  "envelopeIntersect": "intersecção de envelope",
  "overlap": "sobreposição",
  "areOverlapped": "estão sobrepostos",
  "touch": "tocar",
  "within": "dentro",
  "areWithin": "estão dentro",
  "indexIntersect": "intersecção de índice",
  "itemTitle": "Título do item",
  "displayFields": "Campos de visualização",
  "sortingFields": "Classificar itens resultantes",
  "setDisplayFields": "Definir campos de visualização",
  "symbol": "Símbolo",
  "setSymbol": "Utilizar símbolo personalizado",
  "changeSymbolAtRuntime": "Permite alterar símbolos no runtime",
  "serviceSymbolTip": "Utilizar símbolos definidos pela camada",
  "exportTip": "Permitir exportar os resultados",
  "keepResultsTip": "Manter resultados no mapa após o widget ser fechado",
  "queryRelatedRecords": "Consultar registros relacionados",
  "createLayerForTaskTip": "Especifique como a tarefa de consulta cria camadas",
  "oneLayerForTaskTip": "Substituir a camada cada vez que a consulta for executada",
  "multipleLayerForTaskTip": "Criar uma nova camada cada vez que a consulta for executada",
  "makeDefault": "Tornar padrão",
  "icon": "Ícone",
  "newTask": "Nova tarefa",
  "addTaskTip": "Adicione uma ou mais consultas ao widget e configure os parâmetros de cada uma delas.",
  "webMapPopupTip": "Utilizar configuração de pop-up da camada no mapa da web",
  "customPopupTip": "Configurar conteúdo personalizado",
  "showResultsSetActions": "Mostrar ações para o conjunto de resultados",
  "zoomTo": "Zoom para",
  "openAttributeTable": "Visualizar na Tabela de Atributos",
  "content": "Conteúdo",
  "displaySQLTip": "Exibir expressão SQL para usuários finais",
  "useLayerDefaultSymbol": "Utilizar símbolo padrão da camada",
  "setCustomIcon": "Definir ícone personalizado",
  "layerDefaultSymbolTip": "Utilizar símbolo padrão da camada",
  "uploadImage": "Carregar uma Imagem",
  "attributeCriteira": "Critérios de atributos",
  "specifyFilterAtRuntimeTip": "Os usuários precisarão especificar parâmetros para esta expressão.",
  "value": "VALOR",
  "hideLayersTip": "Desative as camadas de resultado da consulta quando o widget estiver fechado.",
  "tabLabels": "Rótulos da tabela",
  "tasks": "Tarefas",
  "queryCriteira": "Critérios de consulta",
  "allowCustomQuery": "Permitir a criação de consulta personalizada"
});