define({
  "addLayer": "Dodaj sloj",
  "layerName": "Sloj",
  "layerRefresh": "Osveži",
  "layerLabel": "Napis",
  "actions": "Dejanja",
  "mainPanelTextPlaceholder": "npr. Nazadnje posodobljeno:",
  "invalidInterval": "Dovoljena so samo pozitivna cela števila",
  "uploadImage": "Naloži sliko",
  "iconColumnText": "Prikaz",
  "refreshInterval": "Čas v minutah",
  "refreshIntervalTitle": "Ocenjeno kot čas v minutah",
  "mainPanelText": "Besedilo glavne plošče",
  "mainPanelIcon": "Slika glavne plošče",
  "refreshIntervalInstruction": "Osveži sloje na:",
  "optionsText": "Možnosti",
  "symbolOptionsText": "Simbologija karte",
  "iconOptionsText": "Simbologija plošče",
  "sympolPopupTitle": "Nastavitve prikaza",
  "rdoLayer": "Privzeti simbol",
  "rdoCustom": "Uporabi sliko",
  "chkCluster": "Omogoči gručenje",
  "defineClusterSymbol": "Določi simbol gruče",
  "rdoEsri": "Izberi simbol",
  "rdoLayerIcon": "Uporabi kartni simbol",
  "rdoCustomIcon": "Uporabi sliko",
  "editCustomSymbol": "Uredi simbol po meri",
  "editCustomIcon": "Uredi ikono po meri",
  "missingRefreshValue": "Navedite osveženo vrednost intervala.",
  "panelIconOption": "Prikaži sliko logotipa",
  "enableRefresh": "Omogoči osvežitev sloja",
  "disableRefresh": "Osvežitev sloja je podprta samo za zbirke geoobjektov.",
  "refreshUnit": "minute.",
  "symbolOptions": "Simbol",
  "panelFeatureDisplay": "Plošča",
  "chkGroup": "Skupinski geoobjekti",
  "selectField": "Polje",
  "fieldLabel": "Napis",
  "addField": "Dodaj polje",
  "featureOptionsText": "Možnosti sloja",
  "groupOptionsText": "Možnosti skupine",
  "panelCountOption": "Prikaz števila geoobjektov",
  "missingLayerInWebMap": "Operativnih slojev ni mogoče najti.",
  "displayClusterCnt": "Prikaz števila geoobjektov",
  "defineClusterFont": "Določi barvo pisave",
  "max_records": "Dosežena maksimalna omejitev polja",
  "hidePanel": "Skrij ploščo",
  "hidePanelHelp": "Omogoči/onemogoči prikaz glavne plošče.",
  "continuousRefreshHelp": "Opomba: Osvežitev zbirke geoobjektov bo potekala neprekinjeno.",
  "panelCountOptionHelp": "Omogoči/onemogoči prikaz števila geoobjektov.",
  "panelIconOptionHelp": "Omogoči/onemogoči prikaz logotipa na glavni plošči.",
  "rdoGroupByField": "po polju",
  "rdoGroupByRenderer": "po upodabljalniku",
  "expandList": "Razširi seznam pri zagonu",
  "expandListHelp": "Omogoči/onemogoči privzeto širitev seznama.",
  "chkFeatureDisplay": "Onemogoči seznam geoobjektov",
  "showAllFeaturesHelp": "Omogoči/onemogoči prikaz vseh geoobjektov, ne glede na obseg.",
  "showAllFeatures": "Prikaži vse geoobjekte",
  "fieldsWarning": "V pojavnem oknu ni določenih polj. Izbirno: Uporabi urejanje za določanje možnosti prikaza plošče."
});