define({
  "_widgetLabel": "Grafikon",
  "executeChartTip": "Kliknite na jedan od sledećih zadataka da biste izvršili grafikon.",
  "invalidConfig": "Nevažeća konfiguracija.",
  "noneChartTip": "Zadatak grafikona nije konfigurisan za ovaj vidžet.",
  "chartParams": "Opcije",
  "charts": "GRAFIKONI",
  "apply": "PRIMENI",
  "useSpatialFilter": "Koristite prostorni filter da biste ograničili geoobjekte",
  "useCurrentMapExtent": "Samo geoobjekti koji presecaju trenutnu površinu mape",
  "drawGraphicOnMap": "Samo geoobjekti koji presecaju površinu koju korisnik odredi",
  "chartResults": "Rezultati grafikona",
  "clearResults": "Obriši rezultate",
  "noPermissionsMsg": "Nemate dozvole da pristupite ovom servisu.",
  "specifySpatialFilterMsg": "Definišite prostorni filter za ovaj zadatak.",
  "queryError": "Neuspeo upit.",
  "noResults": "Nije pronađen nijedan geoobjekat.",
  "category": "Kategorija",
  "count": "Brojač",
  "label": "Oznaka",
  "horizontalAxis": "Horizontalna osa",
  "verticalAxis": "Vertikalna osa",
  "dataLabels": "Oznake podataka",
  "color": "Boja",
  "colorful": "Šareno",
  "monochromatic": "Monohromatsko",
  "tasks": "Zadaci",
  "results": "Rezultati",
  "applySpatialFilterToLimitResults": "Primenite prostorni filter da biste ograničili rezultate",
  "useCurrentExtentTip": "Delimično ili potpuno unutar trenutnog obuhvata mape",
  "useDrawGraphicTip": "Delimično ili potpuno unutar oblika nacrtanog na mapi",
  "useFeaturesTip": "Na osnovu lokacija u vezi sa geoobjektima u drugom sloju",
  "noSpatialLimitTip": "Nemoj prostorno da ograničavaš rezultate",
  "applySearchDistance": "Primeni rastojanje pretrage",
  "spatialRelationship": "Prostorna veza",
  "relatedLayer": "Povezani sloj",
  "clear": "Izbriši",
  "bufferDistance": "Rastojanje zone bliskosti",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "back": "Nazad",
  "execute": "Primeni"
});