define({
  "_widgetLabel": "Älykäs muokkausohjelma",
  "_featureAction_SmartEditor": "Älykäs muokkausohjelma",
  "noEditPrivileges": "Tililläsi ei ole tietojen luonti- tai muokkausoikeuksia.",
  "widgetActive": "Aktiivinen",
  "widgetNotActive": "Ei aktiivinen",
  "pressStr": "Paina ",
  "ctrlStr": " CTRL ",
  "snapStr": " tartunnan käyttöön ottamiseksi",
  "noAvailableTempaltes": "Yhtään mallia ei ole käytettävissä",
  "editorCache": " - Muokkausohjelman välimuisti",
  "presetFieldAlias": "Kenttä",
  "presetValue": "Esiasetettu arvo",
  "usePresetValues": " Käytä esiasetettuja arvoja (vain uudet kohteet)",
  "editGeometry": " Muokkaa geometriaa",
  "savePromptTitle": "Tallenna kohde",
  "savePrompt": "Haluatko tallentaa nykyisen kohteen?",
  "deletePromptTitle": "Poista kohde",
  "deletePrompt": "Haluatko varmasti poistaa valitun kohteen?",
  "attachmentLoadingError": "Virhe ladattaessa liitteitä",
  "attachmentSaveDeleteWarning": "Varoitus: liitteiden muutokset tallennetaan automaattisesti",
  "autoSaveEdits": "Tallentaa muokkauksen automaattisesti",
  "addNewFeature": "Luo uusi kohde",
  "featureCreationFailedMsg": "Uutta tietuetta tai kohdetta ei voi luoda",
  "noRelatedFeatureFoundMsg": "Liittyviä tietueita tai kohteita ei löytynyt",
  "relatedItemTitle": "Liittyvä taulukko tai karttataso",
  "invalidRelationShipMsg": "Varmista, että ensisijaisen avainkentän ${parentKeyField} arvo on kelvollinen",
  "pendingFeatureSaveMsg": "Tallenna kohteen muokkaukset ennen liittyvän kohteen luontia.",
  "attachmentsRequiredMsg": "(*) Liitteet ovat pakollisia.",
  "filterEditor": {
    "all": "Kaikki",
    "noAvailableTempaltes": "Yhtään mallia ei ole käytettävissä",
    "searchTemplates": "Hae malleja"
  },
  "invalidConfiguration": "Pienoisohjelmaa ei ole joko määritetty tai määrityksen karttatasoja ei ole enää kartassa. Avaa sovellus luontitilassa ja määritä pienoisohjelma uudelleen.",
  "geometryServiceURLNotFoundMSG": "Geometriapalvelun URL-osoitetta ei voi noutaa"
});