define({
  "serviceUrl": "ตั้งค่าเซอร์วิส URL",
  "minIntSpacingLabel": "ขนาดกริดต่ำสุด",
  "lineOpacityLabel": "ความทึบของสาย",
  "labelOpacityLabel": "ความทึบของป้ายกำกับ",
  "centerLabelOpacityLabel": "ความทึบของป้ายศูนย์",
  "gridZonePlacementLabel": "ตำแหน่งป้ายตารางของตาราง",
  "verticalLineLabels": "ป้ายข้อความแนวตั้ง",
  "styleHeaderLabel": "สไตล์",
  "indexHeaderLabel": "ส่วนประกอบกริด",
  "colorHeaderLabel": "สี",
  "fontSizeHeaderLabel": "ขนาดตัวอักษร",
  "lineWidthHeaderLabel": "ความหนาของเส้น",
  "horizontalLabel": "แนวนอน",
  "verticalLabel": "ตั้งฉาก",
  "upperLeftLabel": "ด้านบนซ้าย",
  "upperRightLabel": "ด้านบนขวา",
  "lowerLeftLabel": "ด้านล่างซ้าย",
  "lowerRightLabel": "ด้านล่างขวา",
  "centerLabel": "ศูนย์กลาง",
  "errorMessage": "หน้าการตั้งค่ามีข้อผิดพลาด โปรดแก้ไขก่อนบันทึก",
  "checkBoxLabel": "แสดงตารางกริดเมื่อปิดวิดเจ็ต",
  "checkBoxLabelDashboard": "แสดงกริด",
  "gzd": "ตัวกำหนดโซนของกริด (GZD)",
  "gsid": "การกำหนดกริดสี่เหลี่ยมจัตุรัส (GSID) 100,000 เมตร",
  "grid10k": "เส้นกริด 10,000 เมตร",
  "grid1k": "เส้นกริด 1,000 เมตร",
  "grid100m": "เส้นกริด 100 เมตร",
  "grid10m": "เส้นกริด 10 เมตร",
  "switchBasemap": "เปลี่ยนแผนที่ฐาน"
});