define({
  "_widgetLabel": "智能编辑器",
  "_featureAction_SmartEditor": "智能编辑器",
  "noEditPrivileges": "您的帐户不具备创建或修改数据的权限。",
  "widgetActive": "激活",
  "widgetNotActive": "不激活",
  "pressStr": "按 ",
  "ctrlStr": " Ctrl 键 ",
  "snapStr": " 以启用捕捉",
  "noAvailableTempaltes": "无可用模板",
  "editorCache": " - 编辑器缓存",
  "presetFieldAlias": "字段",
  "presetValue": "预设值",
  "usePresetValues": " 使用预设值(仅适用于新要素)",
  "editGeometry": " 编辑几何",
  "savePromptTitle": "保存要素",
  "savePrompt": "是否保存当前要素?",
  "deletePromptTitle": "删除要素",
  "deletePrompt": "确定要删除所选要素?",
  "attachmentLoadingError": "上传附件时出错",
  "attachmentSaveDeleteWarning": "警告 :将自动保存对附件进行的更改",
  "autoSaveEdits": "自动保存编辑内容",
  "addNewFeature": "创建新要素",
  "featureCreationFailedMsg": "无法创建新记录/要素",
  "noRelatedFeatureFoundMsg": "找不到相关记录/要素",
  "relatedItemTitle": "相关表/图层",
  "invalidRelationShipMsg": "请确保主键字段：“${parentKeyField}”具有有效值",
  "pendingFeatureSaveMsg": "请在创建相关要素之前保存要素编辑内容。",
  "attachmentsRequiredMsg": "(*)需要附件。",
  "filterEditor": {
    "all": "全部",
    "noAvailableTempaltes": "无可用模板",
    "searchTemplates": "搜索模板"
  },
  "invalidConfiguration": "微件尚未配置或配置中的图层已不在地图中。请在构建器模式下打开应用程序，然后重新配置微件。",
  "geometryServiceURLNotFoundMSG": "无法获取几何服务 URL"
});