define({
  "_widgetLabel": "Referenční grafika mřížky (GRG)",
  "newGRGFromAreaButtonLabel": "Definovat mřížku z oblasti",
  "newGRGFromPointButtonLabel": "Definovat mřížku z bodu",
  "newGRGFromAreaTitle": "Definovat mřížku z oblasti",
  "newGRGFromPointTitle": "Definovat mřížku z bodu",
  "newGRGBySizeButtonLabel": "Dle rozměru",
  "newGRGFromRefSystemButtonLabel": "Dle referenčního systému",
  "newGRGByTimeLabel": "Dle času a rychlosti",
  "newGRGFromNonStandardButtonLabel": "Definovat nestandardní mřížku",
  "newGRGAreaBySizeTitle": "GRG z oblasti dle rozměru",
  "newGRGAreaBySizeDefineAreaLabel": "Oblast GRG",
  "addGRGAreaPolygonToolTip": "Nakreslit oblast GRG pomocí polygonu",
  "addGRGAreaExtentToolTip": "Nakreslit oblast GRG pomocí rozsahu",
  "rotation": "Rotace mřížky",
  "numberRowsColumnsLabel": "Definovat počet řádků a sloupců",
  "newGRGAreaByRefSystemTitle": "GRG z oblasti dle referenčního systému",
  "gridSize": "Velikost mřížky",
  "UTMZoneandBand": "Zóna mřížky",
  "100000m": "100 000 metrů",
  "10000m": "10 000 metrů",
  "1000m": "1 000 metrů",
  "100m": "100 metrů",
  "10m": "10 metrů",
  "clipGrid": "Oříznout mřížku na oblast GRG",
  "newGRGAreaFromNonStandardTitle": "Nová NRG",
  "newGRGPointBySizeTitle": "GRG z bodu dle rozměru",
  "newGRGPointByRefSystemTitle": "GRG z bodu dle referenčního systému",
  "newGRGPointByTimeTitle": "GRG z bodu pomocí času a rychlosti",
  "time": "Čas",
  "rate": "Rychlost",
  "hours": "hodiny",
  "minutes": "minuty",
  "seconds": "sekundy",
  "ftPerSec": "Stopy / sekunda",
  "ftPerHour": "Stopy / hodina",
  "kmPerSec": "Kilometry / sekunda",
  "kmPerHour": "Kilometry / hodina",
  "mPerSec": "Metry / sekunda",
  "mPerHour": "Metry / hodina",
  "miPerSec": "Míle / sekunda",
  "miPerHour": "Míle / hodina",
  "nMPerSec": "Námořní míle / sekunda",
  "nMPerHour": "Námořní míle / hodina",
  "settingsTitle": "Nastavení",
  "labelSettingsLabel": "Nastavení popisků",
  "labelSettingsButtonLabel": "Konfigurovat nastavení popisků",
  "gridSettingsLabel": "Nastavení mřížky",
  "gridSettingsButtonLabel": "Konfigurovat nastavení mřížky",
  "transparency": "Průhlednost",
  "labelStyle": "Styl popisku",
  "font": "Písmo",
  "textSize": "Velikost textu",
  "textColor": "Barva textu",
  "halo": "Aureola",
  "show": "Zobrazit",
  "lockSettings": "Nastavení jsou zamknuta vlastníkem aplikace",
  "gridSettings": {
    "cellShape": "Tvar buněk",
    "cellUnits": "Jednotky buněk",
    "cellOutline": "Nastavení ohraničení buněk",
    "cellFill": "Nastavení výplně buněk",
    "gridReferenceSystem": "Referenční systém",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Počátek popisku",
    "labelType": "Typ popisku",
    "labelDirection": "Směr popisku",
    "gridOrigin": "Počátek mřížky",
    "default": "Obdélník",
    "hexagon": "Šestiúhelník",
    "miles": "míle",
    "kilometers": "kilometry",
    "feet": "stopy",
    "meters": "metry",
    "yards": "yardy",
    "nautical-miles": "námořní míle",
    "lowerLeft": "Levý dolní",
    "lowerRight": "Pravý dolní",
    "upperLeft": "Levý horní",
    "upperRight": "Pravý horní",
    "center": "Střed",
    "alphaNumeric": "Alfanumerický",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Číselné",
    "horizontal": "Vodorovně",
    "vertical": "Svisle",
    "MGRS": "Vojenská hlásná síť (MGRS)",
    "USNG": "USNG",
    "showLabels": "Zobrazit popisky"
  },
  "publishTitle": "Zveřejnit GRG na portále",
  "publishGRGBtn": "Publikovat",
  "GRGLayerName": "Zveřejněný název vrstvy GRG",
  "invalidGRGLayerName": "Jméno vrstvy smí obsahovat pouze alfanumerické znaky a podtržítka",
  "missingGRGLayerName": "Musíte zadat název GRG",
  "publishingFailedLayerExists": "Zveřejnění se nezdařilo: Název služby funkce {0} již existuje. Zvolte prosím jiný název.",
  "checkService": "Zkontrolovat službu: {0}",
  "createService": "Vytvořit službu: {0}",
  "unableToCreate": "Nelze vytvořit: {0}",
  "addToDefinition": "Přidat do definice: {0}",
  "successfullyPublished": "Webová vrstva {0} úspěšně zveřejněna. Spravovat webovou vrstvu",
  "userRole": "Nelze vytvořit službu, protože uživatel nemá oprávnění",
  "createGRGBtn": "Vytvořit GRG",
  "clearGRGBtn": "Zrušit výběr",
  "labelFormat": "Formát popisku",
  "helpIconTooltip": "Z: Označení zóny mřížky (Grid Zone Designator – GZD)\nS: Velikost čtverce mřížky 100 000 metrů (Grid Square Identification – GSID)\nX: Východní směr (Souřadnice X)\nY: Severní směr (Souřadnice Y)\n\nPříklady:\nZSXY je 15SWC8081751205\nZS X,Y je 15SWC 80817,51205",
  "addPointToolTip": "Přidat počátek GRG",
  "cellWidth": "Šířka buňky (x)",
  "cellHeight": "Výška buňky (y)",
  "invalidNumberMessage": "Zadaná hodnota je neplatná",
  "invalidRangeMessage": "Hodnota musí být větší než 0",
  "gridAngleInvalidRangeMessage": "Hodnota musí být mezi -89,9 a 89,9",
  "formatIconTooltip": "Formátovat vstup",
  "coordInputLabel": "Počátek GRG (DD)",
  "setCoordFormat": "Nastavit řetězec formátu souřadnic",
  "prefixNumbers": "Ke kladným a záporným číslům přidejte předponu +/-",
  "cancelBtn": "Storno",
  "applyBtn": "Použít",
  "comfirmInputNotation": "Potvrďte označení vstupu",
  "notationsMatch": "označení odpovídají vašemu vstupu. Potvrďte prosím, která chcete použít:",
  "numberOfCellsHorizontal": "# Horizontální buňky",
  "numberOfCellsVertical": "# Vertikální buňky",
  "gridAngle": "Rotace mřížky",
  "tooManyCellsErrorMessage": "Pokoušíte se vytvořit mřížku obsahující více než 2 000 buněk. Doporučujeme vám snížit počet vytvářených buněk tak, že změníte velikost nebo oblast mřížky.",
  "missingParametersMessage": "<p>Ve formuláři vytvoření GRG chybí nebo jsou neplatné parametry. Ujistěte se prosím, že:</p><ul><li>Je nakreslena oblast GRG.</li><li>Šířka a výška buněk obsahuje platné hodnoty.</li></ul>",
  "missingOriginParametersMessage": "<p>Ve formuláři vytvoření GRG chybí nebo jsou neplatné parametry. Ujistěte se prosím, že:</p><ul><li>Je nastaven počátek GRG.</li><li>Vstupy času, rychlosti a úhlů obsahují platné hodnoty.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Ve formuláři vytvoření GRG chybí nebo jsou neplatné parametry. Ujistěte se prosím, že šířka a výška buněk obsahuje platné hodnoty.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Ve formuláři vytvoření GRG chybí nebo jsou neplatné parametry. Ujistěte se prosím, že počet horizontálních a vertikálních buněk obsahuje platné hodnoty.</p>",
  "drawPointToolTip": "Kliknutím přidáte počáteční bod GRG",
  "missingLayerNameMessage": "Před zveřejněním musíte zadat platný název vrstvy",
  "parseCoordinatesError": "Souřadnice nelze analyzovat. Zkontrolujte zadané hodnoty.",
  "grgPolarRegionError": "GRG zasahuje do polární oblasti. Buňky, které spadají do polární oblasti, nebudou vytvořeny.",
  "grgPolarOriginError": "Pokud vytváříte GRG pomocí referenčního systému, počáteční bod GRG se nesmí nacházet v polární oblasti.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "Vojenská hlásná síť (MGRS)",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desetinné stupně – Zeměpisná šířka / zeměpisná délka",
  "DDLongLatNotation": "Desetinné stupně – Zeměpisná délka / zeměpisná šířka",
  "DDMLatLongNotation": "Stupně a desetinné minuty – Zeměpisná šířka / zeměpisná délka",
  "DDMLongLatNotation": "Stupně a desetinné minuty – Zeměpisná délka / zeměpisná šířka",
  "DMSLatLongNotation": "Stupně minuty vteřiny – Zeměpisná šířka / zeměpisná délka",
  "DMSLongLatNotation": "Stupně minuty vteřiny – Zeměpisná délka / zeměpisná šířka",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "Vojenská hlásná síť (MGRS)",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – písmeno pásma",
  "UTMHemNotation": "UTM – polokoule (S/J)"
});