define({
  "layerSelect": "Selezionare il layer immagine",
  "displayMeasureResultInPopup": "Visualizza risultati misurazioni in un popup",
  "angularUnitSelect": "Unità angolare predefinita",
  "linearUnitSelect": "Unità lineare predefinita",
  "areaUnitSelect": "Unità di superficie predefinita",
  "displayOperationSelect": "Seleziona operazioni di misurazione",
  "errorSectionMessage": "Nessuno dei layer supporta funzionalità di misurazione.",
  "unitLabel": {
    "esriInches": "Pollici",
    "esriFeet": "Piede",
    "esriYards": "Iarde",
    "esriMiles": "Miglia",
    "esriNauticalMiles": "Miglia nautiche",
    "esriMillimeters": "Millimetri",
    "esriCentimeters": "Centimetri",
    "esriDecimeters": "Decimetri",
    "esriMeters": "Metri",
    "esriKilometers": "Chilometri",
    "esriDURadians": "Radianti",
    "esriDUDecimalDegrees": "Gradi",
    "esriSquareInches": "Pollici quadrati",
    "esriSquareFeet": "Piedi quadrati",
    "esriSquareYards": "Iarde quadrate",
    "esriAcres": "Acri",
    "esriSquareMiles": "Miglia quadrate",
    "esriSquareMillimeters": "Millimetri quadrati",
    "esriSquareCentimeters": "Centimetri quadrati",
    "esriSquareDecimeters": "Decimetri quadrati",
    "esriSquareMeters": "Metri quadrati",
    "esriAres": "Are",
    "esriHectares": "Ettari",
    "esriSquareKilometers": "Chilometri quadrati"
  },
  "operationLabel": {
    "esriMensurationPoint": "Posizione",
    "esriMensurationDistanceAndAngle": "Distanza e angolo",
    "esriMensurationAreaAndPerimeter": "Area e perimetro",
    "esriMensurationHeightFromBaseAndTop": "Altezza: da base a cima",
    "esriMensurationHeightFromBaseAndTopShadow": "Altezza: ombra da base a cima",
    "esriMensurationHeightFromTopAndTopShadow": "Altezza: ombra da cima a cima",
    "esriMensurationCentroid": "Centroide",
    "esriMensurationPoint3D": "Posizione (3D)",
    "esriMensurationDistanceAndAngle3D": "Distanza e angolo (3D)",
    "esriMensurationAreaAndPerimeter3D": "Area e perimetro (3D)",
    "esriMensurationCentroid3D": "Centroide (3D)"
  }
});