define({
  "symbolologyTabLabel": "심볼 구성",
  "facilitiesDescription": "시설 레이어",
  "demographicsDescription": "인구 통계 레이어",
  "settingsTitle": "설정",
  "spillLocationLabel": "유출 위치",
  "spillLocationButtonLabel": "유출 위치 설정 구성",
  "IISettingsLabel": "초기 격리 구역",
  "IIButtonLabel": "초기 격리 설정 구성",
  "PASettingsLabel": "보호 조치 구역",
  "PAButtonLabel": "보호 조치 설정 구성",
  "downwindSettingsLabel": "순풍 구역",
  "downwindButtonLabel": "순풍 설정 구성",
  "fireSettingsLabel": "화재 격리 구역",
  "fireButtonLabel": "화재 격리 설정 구성",
  "bleveSettingsLabel": "블레비(BLEVE) 격리 구역",
  "bleveButtonLabel": "블레비(BLEVE) 설정 구성",
  "transparency": "투명도",
  "outline": "윤곽선",
  "fill": "채우기(스타일이 솔리드로 설정된 경우에만 색상이 적용됨)",
  "style": "스타일",
  "lineStyles": {
    "esriSLSDash": "대시",
    "esriSLSDashDot": "대시 점",
    "esriSLSDashDotDot": "대시 점 점",
    "esriSLSDot": "점",
    "esriSLSLongDash": "긴 대시",
    "esriSLSLongDashDot": "긴 대시 점",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "짧은 대시",
    "esriSLSShortDashDot": "짧은 대시 점",
    "esriSLSShortDashDotDot": "짧은 대시 점 점",
    "esriSLSShortDot": "짧은 점",
    "esriSLSSolid": "실선"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "뒤로",
    "esriSFSCross": "십자모양",
    "esriSFSDiagonalCross": "대각선",
    "esriSFSForwardDiagonal": "순방향",
    "esriSFSHorizontal": "수평",
    "esriSFSNull": "Null",
    "esriSFSSolid": "실선",
    "esriSFSVertical": "수직"
  }
});