define({
  "_widgetLabel": "बैच विशेषता संशोधक",
  "widgetIntroSelectByArea": "अपडेट करने के लिए फीचर का एक चयनित सेट बनाने के लिए नीचे दिए गए टूल्स में से एक का प्रयोग करें। यदि पंक्ति <font class='maxRecordInIntro'>highlighted</font> है, तो रिकार्डों की अधिकतम संख्या पूरी हो गई है।",
  "widgetIntroSelectByFeature": "<font class='layerInIntro'>${0}</font> लेयर से फीचर का चयन करने के लिए निम्न टूल का इस्तेमाल करें। इस फीचर का इस्तेमाल सभी पारस्परिक फीचर का चयन करने और उन्हें अपडेट करने के लिए किया जाएगा। यदि पंक्ति<font class='maxRecordInIntro'>highlighted</font>, तो रिकार्डों की अधिकतम संख्या पूरी हो गई है।",
  "widgetIntroSelectByFeatureQuery": "<font class='layerInIntro'>${0}</font>से फीचर का चयन करने के लिए निम्न टूल का इस्तेमाल करें। इस फीचर की <font class='layerInIntro'>${1}</font> विशेषता नीचे दी गई लेयरों की क्वेरी करने और परिणामस्वरूप फीचर को अपडेट करने के लिए इस्तेमाल की जाएगी। यदि पंक्ति<font class='maxRecordInIntro'>highlighted</font>, तो रिकार्डों की अधिकतम संख्या पूरी हो गई है।",
  "widgetIntroSelectByQuery": "चयनित सेट बनाने के लिए मान दर्ज करें। यदि पंक्ति <font class='maxRecordInIntro'>highlighted</font>, तो रिकार्डों की अधिकतम संख्या पूरी हो गई है।",
  "layerTable": {
    "colLabel": "लेयर का नाम",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "संशोधन योग्य किसी भी लेयर को कॉन्फ़िगर नहीं किया गया है",
  "editorPopupTitle": "बैच विशेषता संशोधक",
  "editorPopupSaveBtn": "सहेजें",
  "editorPopupMultipleValues": "",
  "clear": "हटाएं",
  "featuresUpdated": "${0}/${1} फीचर को अपडेट कर दिया गया है",
  "featuresSelected": "${0} फीचर का चयन किया गया है",
  "featuresSkipped": "नजरअंदाज करें",
  "search": "खोजें",
  "queryInput": "क्वेरी करने के लिए मान दर्ज करें",
  "noFilterTip": "बिना फिल्टर समीकरण निर्धारित किए, यह क्वेरी कार्य निर्दिष्ट डेटा स्रोत में सभी फीचर की सूची बनाएगा।",
  "setFilterTip": "कृपया फिल्टर को सही ढंग से निर्धारित करें।",
  "filterPopup": "लेयर फिल्टर करें",
  "cancel": "रद्द करें",
  "noValue": "कोई मान नहीं है",
  "emptyString": "खाली स्ट्रिंग",
  "existingValue": "मौजूदा मान रखें",
  "newDate": "नई तिथि",
  "valueChooser": "मान का चयन करें/लिखें",
  "ok": "ठीक है",
  "drawBox": {
    "point": "बिन्दु",
    "line": "रेखा",
    "polyline": "बहुरेखा",
    "freehandPolyline": "मुक्तहस्त बहुरेखा",
    "extent": "सीमा",
    "polygon": "बहुभुज",
    "freehandPolygon": "मुक्तहस्त बहुभुज",
    "clear": "हटाएं",
    "addPointToolTip": "इस क्षेत्र में चुनने के लिए क्लिक करें",
    "addShapeToolTip": "फीचर का चयन करने के लिए आकार बनाएं",
    "freehandToolTip": "फीचर का चयन करने के लिए आकार बनाने के लिए दबाएं और पकड़ कर रखें",
    "startToolTip": "फीचर का चयन करने के लिए आकार बनाएं"
  },
  "errors": {
    "layerNotFound": "ID ${1}के साथ लेयर${0} को मानचित्र में खोजा नहीं गया, शायद विजेट्स कॉन्फ़िगर के बाद से मानचित्र परिवर्तित हो गया है",
    "queryNullID": "${0} से फीचर ने गलत ID लौटाई है",
    "noSelectedLayers": "अपडेट करने के लिए रिकॉर्ड के साथ कोई चयनित लेयर नहीं है",
    "inputValueError": "फार्म में अमान्य मान",
    "saveError": "${0} फीचर सहेजने में असमर्थ, विवरण कंसोल में जोड़ दिए गए हैं",
    "requiredValue": "अपेक्षित मान"
  }
});