define({
  "_widgetLabel": "Tinkamumo modeliavimo priemonė",
  "general": {
    "clear": "Valyti",
    "cancel": "Atšaukti",
    "save": "Vykdyti",
    "saveAs": "Eksportuoti"
  },
  "saveModel": {
    "save": "Eksportuoti",
    "title": "Pavadinimas: ",
    "summary": "Santrauka: ",
    "description": "Aprašymas: ",
    "tags": "Raktažodžiai: ",
    "folder": "Aplankas: ",
    "homeFolderPattern": "{username} (Pagrindinis)",
    "failed": "Eksportuoti nepavyko."
  },
  "util": {
    "colorRamp": {
      "1": "Itin žema",
      "2": "Labai žema",
      "3": "Žema",
      "4": "Vidutiniškai žema",
      "5": "Vidutiniškas",
      "6": "Vidutiniškai aukšta",
      "7": "Aukšta",
      "8": "Labai aukšta",
      "9": "Itin aukšta",
      "low": "Žema",
      "high": "Aukšta",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Apversti"
    }
  },
  "wro": {
    "caption": "Tinkamumo modeliavimo priemonė",
    "browsePrompt": "Svorinių perdangų paslauga",
    "selectLayersCaption": "Pasirinkite sluoksnius",
    "selectLayers": "Sluoksniai",
    "designModelCaption": "Kurti modelį",
    "designModel": "Kurti modelį",
    "transparency": "Permatomumas",
    "visible": "Matoma",
    "total": "Iš viso",
    "unableToLoad": "Modelio įkelti nepavyko.",
    "projectNotOpen": "Projektas neatidarytas.",
    "readMore": "Skaityti daugiau",
    "validation": {
      "validating": "Tikrinama...",
      "invalidItemCaption": "Svorinių perdangų paslaugos įspėjimas",
      "notAnImageService": "Šis elementas nėra atvaizdo paslauga.",
      "notAWroService": "Šis elementas nėra svorinių perdangų paslauga.",
      "undefinedUrl": "Šio elemento URL neapibrėžtas.",
      "inaccessible": "Paslauga nepasiekiama.",
      "generalError": "Nepavyksta atidaryti elemento.",
      "missingFieldPattern": "{field} yra būtinas laukas",
      "notAllowRasterFunction": "allowRasterFunction turi būti nustatyta kaip teisinga",
      "notNearestResampling": "defaultResamplingMethod turi būti Nearest",
      "notIsWeightedOverlayProp": "Pagrindinė savybė IsWeightedOverlay turi būti nustatyta kaip teisinga",
      "invalidLink": "URL neleistinas. Nepavyko atidaryti pasirinkto sluoksnio svetainės.",
      "unexpectedError": "Pasirodė netikėta būsena.",
      "rangeMessage": "Reikšmė turi būti tarp ${0} ir ${1}",
      "rangeMessage100": "Reikšmė turi būti tarp 0 ir 100",
      "maxLayers": "Paslauga daugiausia leidžia tiek sluoksnių: ${0}, prieš pridėdami sluoksnį turite kurį nors pašalinti.",
      "notFound": "Sluoksnis ${0} nerastas svorinių perdangų paslaugoje",
      "wroServiceNotDefined": "Neapibrėžta svorinių perdangų paslauga, skirta modeliui.",
      "overlayLayerOutputInvalid": "Perdangos sluoksnio [${0}] susiejimo iš naujo intervalų [${1}] išvesties reikšmės trūksta arba ji neleistina",
      "overlayLayerInputInvalid": "Perdangos sluoksnio [${0}] susiejimo iš naujo intervalų [${1}] įvesties min. / maks. reikšmės trūksta arba ji neleistina",
      "overlayLayerRangesMissing": "Perdangos sluoksnyje [${0}] trūksta susiejimo iš naujo intervalų",
      "overlayLayerWeight": "Perdangos sluoksnių svoriai turi pridėti iki 100",
      "overlayLayerRequired": "Reikalingas bent vienas perdangos sluoksnis",
      "overlayLayerNotDefined": "Perdangos sluoksniai neapibrėžti",
      "requiresColormap": "Rastro elementas reikalauja spalvoto žemėlapio, tačiau modelis neturi leistino spalvoto žemėlapio apibrėžimo",
      "createModelError": "Kuriant modelį įvyko klaida",
      "invalidModel": "Modelis neleistinas",
      "imageServiceNotDefined": "Vaizdo paslaugos sluoksnis neapibrėžtas",
      "imageLayerNotDefined": "Vaizdo paslaugos sluoksnis neapibrėžtas",
      "histogramNotDefined": "Neapibrėžtas svorinių perdangų histogramos elementas"
    },
    "colorRampLabel": {
      "Green Yellow Red": "Žalia geltona raudona",
      "Red Yellow Green": "Raudona geltona žalia",
      "Yellow to Dark Red": "Nuo geltonos iki tamsiai raudonos",
      "Dark Red to Yellow": "Nuo tamsiai raudonos iki geltonos",
      "Light Gray to Dark Gray": "Nuo šviesiai pilkos iri tamsiai pilkos",
      "Dark Gray to Light Gray": "Nuo tamsiai pilkos iki šviesiai pilkos",
      "Light Brown to Dark Brown": "Nuo šviesiai rudos iki tamsiai rudos",
      "Dark Brown to Light Brown": "Nuo tamsiai rudos iki šviesiai rudos",
      "Full Spectrum - Bright Red to Blue": "Visas spektras – nuo ryškiai raudonos iki mėlynos",
      "Full Spectrum - Bright Blue to Red": "Visas spektras – nuo ryškiai mėlynos iki raudonos",
      "Partial Spectrum - Yellow to Blue": "Dalinis spektras – nuo geltonos iki mėlynos",
      "Partial Spectrum - Blue to Yellow": "Dalinis spektras – nuo mėlynos iki geltonos",
      "Yellow-Green to Dark Blue": "Nuo geltonai žalios iki tamsiai mėlynos",
      "Dark Blue to Yellow-Green": "Nuo tamsiai mėlynos iki geltonai žalios",
      "Cold to Hot Diverging": "Išskyrimas nuo šalto iki karšto",
      "Hot to Cold Diverging": "Išskyrimas nuo karšto iki šalto",
      "Surface - Low to High": "Paviršius – nuo žemo iki aukšto",
      "Surface - High to Low": "Paviršius – nuo aukšto iki žemo"
    }
  },
  "tabs": {
    "layers": "Sluoksniai",
    "model": "Modelis",
    "chart": "Diagrama"
  },
  "chart": {
    "prompt": "Elementai",
    "working": "Atnaujinama...",
    "polygonTool": "Brėžti poligoną",
    "freehandPolygonTool": "Laisvai brėžti poligoną",
    "selectTool": "Pasirinkti iš sluoksnio",
    "panTool": "Stumti",
    "clearButton": "Valyti",
    "noModelLayer": "Nėra modelio.",
    "noSubjectLayers": "Jūsų žemėlapyje nėra poligonų sluoksnių.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});