define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Akun Anda tidak memiliki izin untuk membuat atau mengubah data.",
  "widgetActive": "Aktif",
  "widgetNotActive": "Tidak Aktif",
  "pressStr": "Tekan ",
  "ctrlStr": " CTRL ",
  "snapStr": " untuk mengaktifkan snapping",
  "noAvailableTempaltes": "Template tidak tersedia",
  "editorCache": " - Editor Cache",
  "presetFieldAlias": "Kolom",
  "presetValue": "Nilai Preset",
  "usePresetValues": " Gunakan Nilai Preset (hanya fitur baru)",
  "editGeometry": " Edit Geometri",
  "savePromptTitle": "Simpan fitur",
  "savePrompt": "Anda ingin menyimpan fitur saat ini?",
  "deletePromptTitle": "Hapus fitur",
  "deletePrompt": "Anda yakin ingin menghapus fitur terpilih?",
  "attachmentLoadingError": "Kesalahan mengunggah lampiran",
  "attachmentSaveDeleteWarning": "Peringatan: Perubahan pada lampiran disimpan secara otomatis",
  "autoSaveEdits": "Menyimpan pengeditan secara otomatis",
  "addNewFeature": "Buat fitur baru",
  "featureCreationFailedMsg": "Tidak dapat membuat catatan/fitur baru",
  "noRelatedFeatureFoundMsg": "Tidak Ada Catatan/Fitur Terkait ditemukan",
  "relatedItemTitle": "Tabel/Layer Terkait",
  "invalidRelationShipMsg": "Harap pastikan kolom kunci utama: '${parentKeyField}' memiliki nilai valid",
  "pendingFeatureSaveMsg": "Harap simpan editan fitur sebelum membuat fitur terkait.",
  "attachmentsRequiredMsg": "(*) Lampiran harus ada.",
  "filterEditor": {
    "all": "Semua",
    "noAvailableTempaltes": "Template tidak tersedia",
    "searchTemplates": "Pencarian Template"
  },
  "invalidConfiguration": "Widget tidak dikonfigurasi atau layer dalam konfigurasi tidak ada lagi di peta. Harap buka aplikasi dengan mode pembangun (builder) dan konfigurasi ulang widget.",
  "geometryServiceURLNotFoundMSG": "Tidak dapat memperoleh URL Service Geometri"
});