define({
  "serviceUrl": "Imposta url servizio:",
  "minIntSpacingLabel": "Dimensione minima griglia",
  "lineOpacityLabel": "Opacità linea",
  "labelOpacityLabel": "Opacità etichetta",
  "centerLabelOpacityLabel": "Opacità etichetta al centro",
  "gridZonePlacementLabel": "Posizione etichetta zona griglia",
  "verticalLineLabels": "Etichette linee verticali",
  "styleHeaderLabel": "Stile",
  "indexHeaderLabel": "Componente griglia",
  "colorHeaderLabel": "Colore",
  "fontSizeHeaderLabel": "Dimensione carattere",
  "lineWidthHeaderLabel": "Larghezza linea",
  "horizontalLabel": "Orizzontale",
  "verticalLabel": "Verticale",
  "upperLeftLabel": "Sopra a sinistra",
  "upperRightLabel": "Superiore Destra",
  "lowerLeftLabel": "In basso a sinistra",
  "lowerRightLabel": "Inferiore destra",
  "centerLabel": "Al centro",
  "errorMessage": "La pagina di configurazione contiene errori. Risolvere prima di salvare.",
  "checkBoxLabel": "Mostra griglia se il widget è chiuso",
  "checkBoxLabelDashboard": "Visualizza griglia",
  "gzd": "Grid Zone Designator (GZD)",
  "gsid": "100,000-meter Grid Square Identification (GSID)",
  "grid10k": "Linee griglia di 10.000 metri",
  "grid1k": "Linee griglia di 1.000 metri",
  "grid100m": "Linee griglia di 100 metri",
  "grid10m": "Linee griglia di 10 metri",
  "switchBasemap": "Cambia Basemap"
});