define({
  "enableUndoRedo": "Annuler/Répéter",
  "toolbarVisible": "Barre d'outils visible",
  "toolbarOptions": "Options de la barre d'outils",
  "mergeVisible": "Combiner",
  "cutVisible": "Couper",
  "reshapeVisible": "Remodeler",
  "back": "Retour",
  "label": "Couche",
  "edit": "Modifiable",
  "update": "Désactiver la mise à jour de la géométrie",
  "fields": "Champs",
  "actions": "Actions",
  "editpageName": "Nom",
  "editpageAlias": "Alias",
  "editpageVisible": "Visible",
  "editpageEditable": "Modifiable",
  "noLayers": "Aucune couche d'entités modifiable n'est disponible",
  "configureFields": "Configurer les champs de couche",
  "useFilterEdit": "Utiliser le filtre des modèles d'entités",
  "display": "Affichage",
  "autoApplyEditWhenGeometryIsMoved": "Appliquer la mise à jour automatiquement lors du déplacement de la géométrie",
  "snappingTolerance": "Définir la tolérance de capture en pixels",
  "popupTolerance": "Définir la tolérance de la fenêtre de mise à jour des attributs en pixels",
  "stickyMoveTolerance": "Définir la tolérance de déplacement en pixels",
  "usingSaveButton": "Ne pas appliquer les mises à jour aux attributs tant que vous n’avez pas cliqué sur le bouton Enregistrer"
});