define({
  "layerSelect": "Pasirinkti atvaizdo sluoksnį",
  "displayMeasureResultInPopup": "Matavimo rezultatus pateikti iškylančiame lange",
  "angularUnitSelect": "Numatytasis kampinis vienetas",
  "linearUnitSelect": "Numatytasis linijinis vienetas",
  "areaUnitSelect": "Numatytasis ploto vienetas",
  "displayOperationSelect": "Pasirinkti matavimo operacijas",
  "errorSectionMessage": "Nė vienas sluoksnis nepalaiko matavimo funkcionalumo.",
  "unitLabel": {
    "esriInches": "Coliai",
    "esriFeet": "Pėdos",
    "esriYards": "Jardai",
    "esriMiles": "Mylios",
    "esriNauticalMiles": "Jūrmylės",
    "esriMillimeters": "Milimetrai",
    "esriCentimeters": "Centimetrai",
    "esriDecimeters": "Decimetrai",
    "esriMeters": "Metrai",
    "esriKilometers": "Kilometrai",
    "esriDURadians": "Radianai",
    "esriDUDecimalDegrees": "Laipsniai",
    "esriSquareInches": "Kv. col.",
    "esriSquareFeet": "Kv. pėdos",
    "esriSquareYards": "Kv. jardai",
    "esriAcres": "Akrai",
    "esriSquareMiles": "Kv. mylios",
    "esriSquareMillimeters": "Kv. mm",
    "esriSquareCentimeters": "Kv. cm",
    "esriSquareDecimeters": "Kv. dm",
    "esriSquareMeters": "Kv. metrai",
    "esriAres": "Arai",
    "esriHectares": "Hektarai",
    "esriSquareKilometers": "Kv. kilometrai"
  },
  "operationLabel": {
    "esriMensurationPoint": "Vieta",
    "esriMensurationDistanceAndAngle": "Atstumas ir kampas",
    "esriMensurationAreaAndPerimeter": "Plotas ir perimetras",
    "esriMensurationHeightFromBaseAndTop": "Aukštis: nuo pagrindo iki viršaus",
    "esriMensurationHeightFromBaseAndTopShadow": "Aukštis: nuo pagrindo iki šešėlio viršaus",
    "esriMensurationHeightFromTopAndTopShadow": "Aukštis: nuo viršaus iki šešėlio viršaus",
    "esriMensurationCentroid": "Centroidas",
    "esriMensurationPoint3D": "Vieta (3D)",
    "esriMensurationDistanceAndAngle3D": "Atstumas ir kampas (3D)",
    "esriMensurationAreaAndPerimeter3D": "Plotas ir perimetras (3D)",
    "esriMensurationCentroid3D": "Centroidas (3D)"
  }
});