define({
  "chartSettingLabel": "Nastavitve grafikona",
  "addNewLabel": "Dodaj novo",
  "generalSettingLabel": "Splošne nastavitve",
  "searchSourceSettingLabel": "Nastavitve vira iskanja",
  "layerChooser": {
    "title": "Izberite sloj za izdelavo grafikona",
    "selectPolygonLayerLabel": "Izberi sloj",
    "selectPolygonLayerHintText": "Namig: Če konfigurirate več grafikonov, morajo biti sloji istega geometrijskega tipa",
    "selectRelatedTableLayerLabel": "Izberite tabelo, ki je v relaciji s slojem",
    "selectRelatedTableLayerHintText": "Namig: Prikazane so samo tabele z numeričnimi polji",
    "errorInSelectingPolygonLayer": "Izberite sloj, ki je v relaciji s točkovnim slojem.",
    "errorInSelectingRelatedLayer": "Izberite veljavno tabelo/sloj s slojem.",
    "polygonLayerNotHavingRelationships": "Izbrani sloj nima relacijskih tabel/slojev."
  },
  "ChartSetting": {
    "sectionTitle": "Naslov razdelka",
    "sectionTitleHintText": "Namig: Prikazano v naslovu glave razdelka",
    "chartTitle": "Naslov grafikona",
    "chartTitleHintText": "Namig: Prikazano na sredini na vrhu grafikona",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Namig: Prikazano pod grafikonom",
    "chartType": "Tip grafikona",
    "barChart": "Palični grafikon",
    "pieChart": "Tortni grafikon",
    "polarChart": "Polarni grafikon",
    "dataSeriesField": "Polje serije podatkov",
    "labelField": "Polje napisa",
    "chartColor": "Barva grafikona",
    "singleColor": "Enojna barva",
    "colorByTheme": "Barva po temi",
    "colorByFieldValue": "Barva po vrednosti polja",
    "xAxisTitle": "Naslov osi X",
    "xAxisHintText": "Namig: Naslov osi X",
    "yAxisTitle": "Naslov osi Y",
    "yAxisHintText": "Namig: Naslov osi Y",
    "fieldColorLabel": "Napis",
    "fieldColorColor": "Barva",
    "defaultFieldSelectLabel": "Izberi",
    "errMsgFieldValuesNotFound": "Za izbrano polje ni mogoče najti vrednosti",
    "errMsgSectionTitle": "Vnesite naslov razdelka",
    "errMsgFieldByValue": "Izberite vrednost polja",
    "settingTabTitle": "Nastavitev",
    "layoutTabTitle": "Postavitev",
    "polarChartSelectFieldsHintText": "Namig: Izberite polja, da generirate polarni grafikon",
    "visibilityText": "Vidnost",
    "fieldNameText": "Ime polja",
    "aliasNameText": "Vzdevek",
    "errMsgPolarFieldsRequired": "Izberite tri ali več polj, da generirate polarni grafikon",
    "polarChartPolygonFillLabel": "Zapolni poligon",
    "polarChartPolygonFillHintText": "Namig: Izberite potrditveno polje za prikaz polnila poligona v polarnem grafikonu",
    "viewLayoutLabel": "Postavitev",
    "ThemeSelector": {
      "themeAdobebricks": "Glinene opeke",
      "themeAlgae": "Alge",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Modri mrak",
      "themeCubanShirts": "Kubanske srajce",
      "themeDesert": "Puščava",
      "themeDistinctive": "Značilno",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Kobilica",
      "themeGrasslands": "Pašnik",
      "themeGreySkies": "Sivo nebo",
      "themeHarmony": "Harmonija",
      "themeIndigoNation": "Indigo Nation",
      "themeIreland": "Irska",
      "themeMiamiNice": "Miami Nice",
      "themeMinty": "Mentolova",
      "themePurpleRain": "Škrlatni dež",
      "themeRoyalPurples": "Kraljevo škrlatna",
      "themeSageToLime": "Žajbelj do limete",
      "themeTufte": "Tufte",
      "themeWatersEdge": "Rob vode",
      "themeWetlandText": "Mokrišče",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Splošne nastavitve",
    "locationSymbolLabel": "Grafični simbol lokacije",
    "locationSymbolHintText": "Namig: Uporablja se za prikaz simbola za naslov in klik lokacije",
    "refreshIntervalLabel": "Osveži interval",
    "refreshIntervalHintText": "Namig: Uporablja se za osveževanje grafikonov na podlagi tega intervala. Navedite vrednost med 1 in 1440 minut",
    "errMsgRefreshInterval": "Navedite interval osveževanja med 0 in 1440 minut.",
    "symbolPickerPreviewText": "Predogled:",
    "showToolToSelectLabel": "Nastavite gumb lokacije",
    "showToolToSelectHintText": "Namig: Ponudi gumb za nastavitev lokacije na karti v izogib vsakokratnem klikanju in nastavljanju lokacije na karti"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Nastavitve vira iskanja",
    "searchSourceSettingTitle": "Nastavitve vira iskanja",
    "searchSourceSettingTitleHintText": "Dodajte in konfigurirajte geokodirne storitve ali geoobjektne sloje kot vire iskanja. Ti viri določajo, kaj je mogoče iskati znotraj iskalnega polja",
    "addSearchSourceLabel": "Dodajte vir iskanja",
    "featureLayerLabel": "Geoobjektni sloj",
    "geocoderLabel": "Geokodirnik",
    "nameTitle": "Ime",
    "generalSettingLabel": "Splošna nastavitev",
    "allPlaceholderLabel": "Nadomestno besedilo za iskanje:",
    "allPlaceholderHintText": "Namig: Vnesite besedilo, ki bo prikazano kot nadomestno besedilo med iskanjem po vseh slojih in geokodirniku",
    "generalSettingCheckboxLabel": "Pokaži pojavno okno za najdeni geoobjekt ali lokacijo",
    "countryCode": "Šifre države ali regije",
    "countryCodeEg": "npr. ",
    "countryCodeHint": "Če to vrednost pustite prazno, bo iskanje potekalo po vseh državah in regijah",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Išči samo v trenutnem obsegu karte",
    "zoomScale": "Merilo povečave",
    "locatorUrl": "URL geokodirnika",
    "locatorName": "Ime geokodirnika",
    "locatorExample": "Primer",
    "locatorWarning": "Ta različica geokodirnih storitev ni podprta. Pripomoček podpira različico geokodirne storitve 10.0 in novejšo.",
    "locatorTips": "Predlogi niso na voljo, ker geokodirna storitev ne podpira zmožnosti predlogov.",
    "layerSource": "Vir sloja",
    "setLayerSource": "Nastavi vir sloja",
    "setGeocoderURL": "Nastavi URL geokodirnika",
    "searchLayerTips": "Predlogi niso na voljo, ker geoobjektna storitev ne podpira možnost številčenje strani.",
    "placeholder": "Nadomestno besedilo",
    "searchFields": "Iskalna polja",
    "displayField": "Prikazno polje",
    "exactMatch": "Natančno ujemanje",
    "maxSuggestions": "Maksimalno predlogov",
    "maxResults": "Maksimalno rezultatov",
    "enableLocalSearch": "Omogoči lokalno iskanje",
    "minScale": "Minimalno merilo",
    "minScaleHint": "Ko je merilo karte večje od tega merila, bo uporabljeno lokalno iskanje",
    "radius": "Polmer",
    "radiusHint": "Določa polmer območja okrog trenutnega središča karte, ki je uporabljeno za povečanje števila kandidatov za geokodiranje, tako da so najprej prikazani kandidati, ki so najbližji lokaciji",
    "meters": "Metri",
    "setSearchFields": "Nastavi iskalna polja",
    "set": "Nastavi",
    "fieldName": "Ime",
    "invalidUrlTip": "URL ${URL} je neveljaven ali nedostopen."
  }
});