define({
  "_widgetLabel": "Conocimiento de la situación",
  "locate_incident": "Localizar incidente",
  "reverse_geocoded_address": "Dirección más próxima",
  "reverse_geocoded_error": "No disponible",
  "now": "AHORA",
  "wind": "VIENTO",
  "SUN": "DOM",
  "MON": "LUN",
  "TUE": "MAR",
  "WED": "MIÉ",
  "THU": "JUE",
  "FRI": "VIE",
  "SAT": "SÁB",
  "actionLabel": "Definir ubicación",
  "drawPoint": "Dibujar punto",
  "drawLine": "Dibujar línea",
  "drawPolygon": "Dibujar polígono",
  "saveIncident": "Guardar",
  "clearIncident": "Empezar de nuevo",
  "noFeaturesFound": "No se encontraron entidades.",
  "downloadCSV": "Descargar",
  "sum": "Suma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Media",
  "count": "TOTAL",
  "area": "ÁREA",
  "length": "LONGITUD",
  "update_btn": "Hecho",
  "delete_btn": "Eliminar",
  "get_directions": "Obtener instrucciones",
  "incident": "Incidente",
  "incidents": "Incidentes",
  "buffer": "Zona de influencia",
  "buffers": "Zonas de influencia",
  "weather": "Tiempo",
  "poweredBy": "Con tecnología de",
  "_featureAction_ActionLabel": "Definir ubicación",
  "_featureAction_AddRemoveActionLabel": "Agregar/Quitar ubicación",
  "snapshot": "Carpeta SnapShot creada por el id. de la aplicación:",
  "user_credentials": "El usuario no tiene privilegios válidos.",
  "notPolySnapShot": "Especifique una distancia de zona de influencia antes de crear una instantánea.",
  "notPolyReport": "No hay resultados válidos para agregarlos al informe.",
  "notValidDownload": "No hay resultados válidos para descargar.",
  "of_append": "de",
  "layer_append": "capa",
  "downloadAll": "Descargar todo",
  "createSnapshot": "Crear instantánea",
  "createReport": "Crear informe",
  "calculated_results": "Información resumida",
  "closest": "Entidad más próxima",
  "proximity": "Proximidad",
  "summary": "Resumen",
  "groupedSummary": "Recuentos agrupados",
  "_count": "Calcular",
  "approximate": "aproximado",
  "snapshot_name": "Definir propiedades de instantánea",
  "report_name": "Definir propiedades de informe",
  "invalid_snapshot_name": "Nombre de instantánea no válido.",
  "invalid_report_name": "Título de informe no válido.",
  "orientation": "Orientación",
  "pageSize": "Tamaño de página",
  "comments": "Comentarios",
  "choose_group": "Grupos",
  "forecast": "Previsión",
  "select_group": "Seleccionar grupo",
  "select_group_instruction": "La instantánea se creará y se compartirá con el grupo seleccionado",
  "information_append": " Información",
  "distance": "DISTANCE",
  "buffer_invalid": "Introduzca un número válido de entre ${min} y ${max}"
});