define({
  "_widgetLabel": "लेखा चित्र",
  "executeChartTip": "चार्ट को निष्पादित करने के लिए निम्न कार्य आइटम में से एक पर क्लिक करें।",
  "invalidConfig": "अमान्य कॉन्फ़िगरेशन।",
  "noneChartTip": "इस विजेट के लिए कोई चार्ट कार्य कॉन्फ़िगर नहीं किया गया था।",
  "chartParams": "विकल्प",
  "charts": "चार्ट",
  "apply": "लागू करें",
  "useSpatialFilter": "फीचर को सीमित करने के लिए स्पेश्यिल फिल्टर का प्रयोग करें",
  "useCurrentMapExtent": "वर्तमान मानचित्र क्षेत्र को केवल पारस्परिक फीचर",
  "drawGraphicOnMap": "उपयोगकर्ता निर्धारित क्षेत्र को इंटरसेक्ट करते केवल फीचर",
  "chartResults": "चार्ट परिणाम",
  "clearResults": "परिणाम साफ करें",
  "noPermissionsMsg": "आप को इस सेवा का उपयोग करने की अनुमति नहीं है।",
  "specifySpatialFilterMsg": "इस कार्य के लिए स्पेश्यिल फिल्टर निर्दिष्ट करें।",
  "queryError": "क्वेरी विफल रही है।",
  "noResults": "कोई फीचर नहीं पाई गई है।",
  "category": "वर्ग",
  "count": "गणना",
  "label": "लेबल",
  "horizontalAxis": "क्षैतिज अक्ष",
  "verticalAxis": "ऊर्ध्वाधर अक्ष",
  "dataLabels": "डेटा लेबल",
  "color": "रंग",
  "colorful": "रंगीन",
  "monochromatic": "एकरंगा",
  "tasks": "कार्य",
  "results": "परिणाम",
  "applySpatialFilterToLimitResults": "परिणामों को सीमित करने के लिए एक स्पेश्यिल फिल्टर लागू करें",
  "useCurrentExtentTip": "आंशिक रूप से या पूरी तरह से वर्तमान मानचित्र सीमा के भीतर",
  "useDrawGraphicTip": "मानचित्र पर आंशिक रूप से या पूरी तरह से बनाए गए आकार के भीतर",
  "useFeaturesTip": "अन्य लेयर में फीचर के सापेक्ष उनके स्थानों के आधार पर",
  "noSpatialLimitTip": "परिणामों को स्पेश्यिल रूप में सीमित न करें",
  "applySearchDistance": "एक खोज दूरी लागू करें",
  "spatialRelationship": "स्पेश्यिल संबंध",
  "relatedLayer": "संबंधित लेयर",
  "clear": "हटाएं",
  "bufferDistance": "बफर दूरी",
  "miles": "मील",
  "kilometers": "किलोमीटर",
  "feet": "फ़ीट",
  "meters": "मीटर",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "back": "पीछे जाएँ",
  "execute": "लागू करें"
});