define({
  "_widgetLabel": "Kesadaran Situasi",
  "locate_incident": "Cari Lokasi Insiden",
  "reverse_geocoded_address": "Alamat Terdekat",
  "reverse_geocoded_error": "Tidak tersedia",
  "now": "SEKARANG",
  "wind": "ANGIN",
  "SUN": "MIN",
  "MON": "SEN",
  "TUE": "SEL",
  "WED": "RAB",
  "THU": "KAM",
  "FRI": "JUM",
  "SAT": "SAB",
  "actionLabel": "Atur Lokasi",
  "drawPoint": "Gambar titik",
  "drawLine": "Gambar garis",
  "drawPolygon": "Gambar poligon",
  "saveIncident": "Simpan",
  "clearIncident": "Mulai Ulang",
  "noFeaturesFound": "Fitur tidak ditemukan.",
  "downloadCSV": "Unduh",
  "sum": "Jumlah",
  "min": "Minimal",
  "max": "Maksimal",
  "avg": "Rata-rata",
  "count": "COUNT",
  "area": "AREA",
  "length": "PANJANG",
  "update_btn": "Selesai",
  "delete_btn": "Hapus",
  "get_directions": "Dapatkan Arah",
  "incident": "Insiden",
  "incidents": "Insiden",
  "buffer": "Buffer",
  "buffers": "Buffer",
  "weather": "Cuaca",
  "poweredBy": "Dipersembahkan oleh",
  "_featureAction_ActionLabel": "Atur Lokasi",
  "_featureAction_AddRemoveActionLabel": "Tambah/Buang Lokasi",
  "snapshot": "Folder SnapShot dibuat menurut id Aplikasi:",
  "user_credentials": "Pengguna tidak memiliki hak istimewa yang valid.",
  "notPolySnapShot": "Harap tentukan jarak buffer sebelum membuat snapshot.",
  "notPolyReport": "Tidak ada hasil yang valid untuk ditambahkan ke laporan.",
  "notValidDownload": "Tidak ada hasil valid untuk diunduh.",
  "of_append": "dari",
  "layer_append": "layer",
  "downloadAll": "Unduh semua",
  "createSnapshot": "Buat snapshot.",
  "createReport": "Buat laporan",
  "calculated_results": "Informasi Ringkas",
  "closest": "Fitur Terdekat",
  "proximity": "Kedekatan",
  "summary": "Ringkasan",
  "groupedSummary": "Jumlah yang Dikelompokkan",
  "_count": "Jumlah",
  "approximate": "mendekati",
  "snapshot_name": "Atur Properti Snapshot",
  "report_name": "Atur Properti Laporan",
  "invalid_snapshot_name": "Nama snapshot tidak valid.",
  "invalid_report_name": "Judul laporan tidak valid.",
  "orientation": "Orientasi",
  "pageSize": "Ukuran Halaman",
  "comments": "Komentar",
  "choose_group": "Grup",
  "forecast": "Ramalan",
  "select_group": "Pilih Grup",
  "select_group_instruction": "Snapshot akan dibuat dan dibagikan dengan grup yang dipilih",
  "information_append": " Informasi",
  "distance": "JARAK",
  "buffer_invalid": "Masukkan angka valid antara ${min} dan ${max}"
});