define({
  "settings": "Impostazioni",
  "titleSettings": "Impostazioni del testo",
  "imageSettings": "Impostazioni immagine",
  "backgroundColor": "Colore di sfondo",
  "alignment": "Allineamento",
  "textSize": "Dimensione testo",
  "textColor": "Colore testo",
  "dataSource": "Origine dati",
  "chartSettings": "Impostazioni grafico",
  "data": "Dati",
  "dataLabels": "Etichette dati",
  "displayMode": "Modalità visualizzazione",
  "featureOption": "Visualizza valori feature per feature",
  "categoryOption": "Visualizza valori per categoria",
  "countOption": "Visualizza conteggi feature per categoria",
  "fieldOption": "Visualizza valori attributi come grafici",
  "categoryField": "Campo categoria",
  "labelField": "Campo etichetta",
  "valueFields": "Campi valore",
  "operation": "Operazione",
  "sumOption": "Somma",
  "averageOption": "Media",
  "minOption": "Minimo",
  "maxOption": "Massimo",
  "dataFormat": "Formato dati",
  "decimalPlaces": "Posizioni decimali",
  "prefix": "Prefisso",
  "suffix": "Suffisso",
  "dataType": "Tipo di dati",
  "featureCount": "Conteggio feature",
  "fieldStatistics": "Statistiche di campo",
  "display": "Visualizza",
  "chartColor": "Colore grafico",
  "horizontalAxis": "Asse orizzontale",
  "verticalAxis": "Asse verticale",
  "legend": "Legenda",
  "position": "Posizione",
  "top": "In alto",
  "bottom": "In basso",
  "useDataSourceSelection": "Usa selezione",
  "dataSourceFilterByExtent": "Filtra per estensione",
  "changeTemplate": "Cambia modello",
  "numberSettings": "Impostazioni numero",
  "gaugeSettings": "Impostazioni indicatore",
  "indicators": "Indicatori",
  "ifValue": "Valore If",
  "and": "and",
  "numberOperatorIsLessThan": "è minore di",
  "numberOperatorIsGreaterThan": "è maggiore di",
  "numberOperatorIsBetween": "è tra",
  "numberOperatorIsEqual": "è uguale a",
  "numberOperatorIsNotEqual": "è diversa da",
  "then": "Then",
  "ratio": "Percentuale",
  "trueValue": "Valore True",
  "changeValueColor": "modifica colore valore in",
  "changeGaugeColor": "modifica colore indicatore in",
  "setIndicatorIcon": "imposta icona indicatore come",
  "icons": "Icone",
  "style": "Stile",
  "placement": "Posizionamento",
  "left": "A sinistra",
  "replace": "Sostituisci",
  "right": "A destra",
  "color": "Colore",
  "categoryExists": "La categoria esiste!",
  "comboxHint": "Digitare il nome o selezionarne una",
  "comboxDisableInputHint": "Una selezione",
  "sortBy": "Ordina per",
  "labelAxis": "Etichetta",
  "valueAxis": "Valore",
  "minPeriod": "Periodo minimo",
  "automatic": "Automatico",
  "periodsWithOutRecords": "Periodi senza record",
  "nullValue": "Valore nullo",
  "calculatedAsZero": "Calcolato come zero",
  "ignored": "Ignorato",
  "maxCategories": "Categorie massime",
  "useLayerSymbology": "Utilizza simbologia del layer",
  "hollowsize": "Dimensione vuota",
  "splitField": "Dividi campo",
  "parsingperiodTip": "Calcolo non riuscito. Troppi intervalli di tempo in un periodo di analisi breve.",
  "manyCategoryTip": "Visualizzazione del grafico non riuscita. Troppe categorie.",
  "setColor": "Imposta colore",
  "setTheColorOf": "In seguito, impostare il colore di",
  "setTheColorAs": "In seguito, impostare il colore come",
  "ifStr": "If",
  "as": "come",
  "is": "è",
  "isNot": "non è",
  "barCluster": "bar cluster",
  "individualBar": "individual bar",
  "allOthers": "Tutte le altre",
  "category": "Categoria",
  "indicatorSum": "SOMMA",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Impostare gli indicatori correttamente.",
  "dataRange": "Gamma dati",
  "targetValue": "Valore target",
  "currentValue": "Valore corrente",
  "gaugeColor": "Colore indicatore",
  "min": "Minimo",
  "max": "Massimo",
  "displayValueIn": "Visualizza valore in",
  "noData": "Nessun dato",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Avviso",
  "noSettingWaring1": "Fare click su un elemento per impostarne le proprietà.",
  "noSettingWaring2": "Trascinare per ridimensionare o riordinare un elemento.",
  "donNotShowAgain": "Non mostrare più",
  "changeTemplateWarning": "Così facendo si annulleranno tutte le impostazioni e si aprirà un nuovo modello vuoto.",
  "requiredFieldWarning": "Questo valore è obbligatorio:",
  "dataSourceNotSet": "Impostare l'origine dati.",
  "addIndicatorTip": "Aggiungi indicatore",
  "chooseTemplatePopupTitle": "Scegliere un modello",
  "filterExtentTipWithaTag": "È possibile disabilitare il filtro per <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Origine dati extra</a> nella scheda Attributo.",
  "filterExtentTip": "È possibile disabilitare il filtro per “Origine dati extra” nella scheda Attributo.",
  "customColorByCategory": "Personalizza colore per categoria",
  "randomColor": "Colore casuale",
  "valueString": "Valore",
  "fieldString": "Campo",
  "includeThresholdValue": "Includi valore soglia",
  "percentage": "Percentuale",
  "colorSchema": "Schema colori",
  "addCategory": "Aggiungi categoria",
  "clickToEdit": "Fare clic per modificare",
  "nullText": "Null",
  "others": "Altri",
  "stringsInTemplate": {
    "name_number": "Numero",
    "name_gauge": "Indicatore di livello",
    "name_vertical_gauge": "Indicatore verticale",
    "name_horizontal_gauge": "Indicatore orizzontale",
    "name_pie": "Torta",
    "name_donut": "Anello",
    "name_bar": "Barra",
    "name_stacked_bar": "Stacked Bar",
    "name_percentage_stacked_bar": "Percentage Stacked Bar",
    "name_column": "Colonna",
    "name_stacked_column": "Stacked column",
    "name_percentage_stacked_column": "Percentage Stacked Column",
    "name_line": "Linea",
    "name_area": "Area",
    "name_stacked_area": "Stacked Area",
    "name_percentage_stacked_area": "Percentage Stacked Area",
    "titleOfTheInfographic": "TITOLO INFOGRAFICA",
    "description": "Descrizione: informazioni aggiuntive su quest'infografica."
  }
});