define({
  "_widgetLabel": "Conversão de Coordenadas",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Minutos Decimais - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Minutos Decimais - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra da Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)",
  "formatInput": "Entrada de formato",
  "copyAll": "Copiar Tudo",
  "copySuccessful": "Cópia bem sucedida",
  "copyFailed": "Não é possível Copiar. Utilize ctrl+c como uma alternativa.",
  "parseCoordinatesError": "Não é possível analisar coordenadas. Verifique sua entrada.",
  "comfirmInputNotation": "Confirmar Notação de Entrada",
  "latLongWarningMessage": "As coordenadas de entrada foram detectadas como ambas tendo um prefixo e um sufixo do valor de latitude ou longitude, a coordenada retornada é baseada no prefixo.",
  "inputLabel": "Entrada",
  "outputLabel": "Saída",
  "cancelButtonLabel": "Cancelar",
  "applyButtonLabel": "Aplicar",
  "posNegPrefixLabel": "Adicione o prefixo \"+/-\" para números positivos e negativos",
  "editCoordinateDialogTitle": "Definir String de Formato de Coordenadas",
  "rememberDecisionLabel": "Lembrar de minha decisão e não perguntar novamente.<br/>",
  "coordinateInputLabel": "Insira as coordenadas ou clique no mapa",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notações localizadas que correspondem sua entrada. Confirme que deseja utilizar:",
  "copyToClipboard": "Copiar para área de transferência",
  "formatOutput": "Saída de formato",
  "addNewNotation": "Adicionar Nova Notação",
  "notationAddedMessage": "Nova Anotação Adicionada",
  "addLabel": "Adicionar",
  "removeCoordinate": "Remover Coordenadas",
  "expandOutput": "Expandir Saída",
  "latitudeLabel": "Lat",
  "longitudeLabel": "Long",
  "quadrantLabel": "Quadrante",
  "keyLabel": "Chave",
  "fifteenDegreeLabel": "15Â° Quadrante",
  "oneDegreeLabel": "1Â° Quadrante",
  "eastingLabel": "Deslocar para Leste",
  "northingLabel": "Deslocar para Norte",
  "zoneLabel": "Zona",
  "bandLabel": "Banda",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Grade quadrada",
  "hemisphereLabel": "Hemisfério"
});