define({
  "_widgetLabel": "Modélisateur d'aptitude",
  "general": {
    "clear": "Effacer",
    "cancel": "Annuler",
    "save": "Exécuter",
    "saveAs": "Exporter"
  },
  "saveModel": {
    "save": "Exporter",
    "title": "Titre : ",
    "summary": "Résumé : ",
    "description": "Description : ",
    "tags": "Balises : ",
    "folder": "Dossier : ",
    "homeFolderPattern": "{username} (Home)",
    "failed": "Erreur d'export."
  },
  "util": {
    "colorRamp": {
      "1": "Extrêmement faible",
      "2": "Très faible",
      "3": "Basse",
      "4": "Moyen faible",
      "5": "Moyenne",
      "6": "Moyen élevé",
      "7": "Elevée",
      "8": "Très élevé",
      "9": "Extrêmement élevé",
      "low": "Basse",
      "high": "Elevée",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Inverser"
    }
  },
  "wro": {
    "caption": "Modélisateur d'aptitude",
    "browsePrompt": "Service de superposition pondérée",
    "selectLayersCaption": "Sélectionner des couches",
    "selectLayers": "Couches",
    "designModelCaption": "Modèle de conception",
    "designModel": "Modèle de conception",
    "transparency": "Transparence",
    "visible": "Visibles",
    "total": "Total",
    "unableToLoad": "Impossible de charger le modèle.",
    "projectNotOpen": "Aucun projet n'est ouvert.",
    "readMore": "En savoir plus",
    "validation": {
      "validating": "Validation...",
      "invalidItemCaption": "Avertissement du service de superposition pondérée",
      "notAnImageService": "Cet élément n'est pas un service d'imagerie.",
      "notAWroService": "Cet élément n'est pas un service de superposition pondérée.",
      "undefinedUrl": "L'URL de cet élément n'est pas définie.",
      "inaccessible": "Le service est inaccessible.",
      "generalError": "Impossible d'ouvrir l'élément.",
      "missingFieldPattern": "{field} est un champ obligatoire",
      "notAllowRasterFunction": "La propriété allowRasterFunction doit être définie sur True",
      "notNearestResampling": "La propriété defaultResamplingMethod doit être définie sur La plus proche",
      "notIsWeightedOverlayProp": "La propriété clé IsWeightedOverlay doit être définie sur True",
      "invalidLink": "L'URL n'est pas valide. Echec de l'ouverture du site pour la couche sélectionnée.",
      "unexpectedError": "Un état inattendu s'est produit.",
      "rangeMessage": "La valeur doit être comprise entre ${0} et ${1}",
      "rangeMessage100": "La valeur doit être comprise entre 0 et 100",
      "maxLayers": "Un maximum de ${0} couches est autorisé par service. Vous devez d'abord supprimer une couche avant d'en ajouter une nouvelle.",
      "notFound": "La couche ${0} est introuvable dans le service de superposition pondérée",
      "wroServiceNotDefined": "Aucun service de superposition pondérée n'est défini pour le modèle.",
      "overlayLayerOutputInvalid": "La valeur en sortie des plages de classification [${1}] de la couche de superposition [${0}] est manquante ou non valide",
      "overlayLayerInputInvalid": "La valeur min/max en entrée des plages de classification [${1}] de la couche de superposition [${0}] est manquante ou non valide",
      "overlayLayerRangesMissing": "Aucune plage de classification n'est présente dans la couche de superposition [${0}]",
      "overlayLayerWeight": "Les pondérations des couches de superposition doivent correspondre à un total de 100",
      "overlayLayerRequired": "Au moins une couche de superposition est requise",
      "overlayLayerNotDefined": "Les couches de superposition ne sont pas définies",
      "requiresColormap": "Cette fonction raster requiert une palette de couleurs, mais le modèle ne comporte pas de définition de palette de couleurs valide.",
      "createModelError": "Erreur de création du modèle",
      "invalidModel": "Le modèle n'est pas valide",
      "imageServiceNotDefined": "Aucune couche de service d'imagerie n'est définie",
      "imageLayerNotDefined": "Aucune couche de service d'imagerie n'est définie",
      "histogramNotDefined": "Aucune fonction d'histogramme de superposition pondérée n'est définie."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Rouge Jaune Rouge",
      "Red Yellow Green": "Rouge Jaune Vert",
      "Yellow to Dark Red": "Jaune -> rouge foncé",
      "Dark Red to Yellow": "Rouge foncé à Jaune",
      "Light Gray to Dark Gray": "Gris clair à gris foncé",
      "Dark Gray to Light Gray": "Gris foncé à gris clair",
      "Light Brown to Dark Brown": "Marron clair à marron foncé",
      "Dark Brown to Light Brown": "Marron foncé à marron clair",
      "Full Spectrum - Bright Red to Blue": "Spectre complet - Rouge vif à bleu",
      "Full Spectrum - Bright Blue to Red": "Spectre complet - Bleu vif à rouge",
      "Partial Spectrum - Yellow to Blue": "Spectre partiel - Jaune à bleu",
      "Partial Spectrum - Blue to Yellow": "Spectre partiel - Bleu à jaune",
      "Yellow-Green to Dark Blue": "Jaune-vert à bleu foncé",
      "Dark Blue to Yellow-Green": "Bleu foncé à jaune-vert",
      "Cold to Hot Diverging": "Divergence froid vers chaud",
      "Hot to Cold Diverging": "Divergence chaud vers froid",
      "Surface - Low to High": "Surface - Basse à élevée",
      "Surface - High to Low": "Surface - Elevée à basse"
    }
  },
  "tabs": {
    "layers": "Couches",
    "model": "Modèle",
    "chart": "Diagramme"
  },
  "chart": {
    "prompt": "Caractéristiques",
    "working": "Mise à jour...",
    "polygonTool": "Dessiner un polygone",
    "freehandPolygonTool": "Dessiner un polygone à main levée",
    "selectTool": "Sélectionner dans une couche",
    "panTool": "Pan",
    "clearButton": "Effacer",
    "noModelLayer": "Aucun modèle.",
    "noSubjectLayers": "Votre carte ne comporte aucune couche surfacique.",
    "tipPattern": "${category} - ${label} : ${percent}%",
    "tipPattern2": "${category} : ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});