define({
  "_widgetLabel": "Analiza incidenta",
  "_featureAction_SetAsIncident": "Postavi kao incident",
  "incident": "Incident",
  "weather": "Vrijeme",
  "locate_incident": "Pronađi incident",
  "clear_incidents": "Izbriši incidente",
  "reverse_geocoded_address": "Najbliže adrese",
  "reverse_geocoded_error": "Nije dostupno",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "now": "SADA",
  "wind": "VJETAR",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "UTO",
  "WED": "SRI",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SUB",
  "defaultTabMsg": "Nema identificiranih incidenata.",
  "useMapExtent": "Upotrijebi trenutačni obuhvat karte",
  "noFeaturesFound": "Nema geoobjekata.",
  "downloadCSV": "PREUZMI CSV",
  "sum": "ZBROJ",
  "min": "MIN.",
  "max": "MAKS.",
  "avg": "PROSJEK",
  "count": "BROJ",
  "area": "POVRŠINA",
  "length": "DULJINA"
});