define({
  "tabs_section_Label": "Separadores",
  "addTab": "Adicionar Separador",
  "layerName": "Camada",
  "layerType": "Tipo de Análise",
  "layerLabel": "Rótulo",
  "actions": "Ações",
  "closest": "Elemento Mais Próximo",
  "proximity": "Proximidade",
  "summary": "Resumo",
  "select_lbl": "-- Seleccionar --",
  "general_setting_Label": "Configurações Gerais",
  "units_text_lbl": "Unidades de distância",
  "maximum_distance_lbl": "Distância máxima do elemento mais próximo",
  "buffer_text_lbl": "Rótulo do buffer",
  "buffer_lbl": "Distância do buffer",
  "buffer_max_lbl": "Distância máxima do buffer",
  "buffer_min_lbl": "Distância mínima do buffer",
  "buffer_default_lbl": "Distância predefinida do buffer",
  "not_less_than_max": "A distância tem de ser inferior à distância máxima de buffer",
  "not_between": "A distância tem de encontrar-se entre as distâncias mínima e máxima de buffer",
  "not_more_than_min": "A distância tem de ser superior à distância mínima de buffer",
  "not_valid_number": "Tem de ser um número válido",
  "invalid_value": "O valor ${type} é inválido",
  "routing_checkBox": "Ativar rotas",
  "weather_Label": "Definições Meteorológicas",
  "weather_checkBox": "Ativar metereologia",
  "weather_map_layers": "Selecionar camadas meteorológicas...",
  "selected_map_layers": " camadas meteorológicas selecionadas",
  "instruction_weather": "Exibir informações meteorológicas no painel.",
  "instruction_weather_layers": "Exibir camadas meteorológicas adicionais.",
  "instruction_weather_metric": "Exibir valores padrão/métricos",
  "selectLayers": "Selecionar camadas meteorológicas",
  "weather_removed_message": "As opções de meteorologia já não se encontram disponíveis para este widget.",
  "currentlySelectedLayer": "Selecionar a partir de camadas do mapa",
  "missingTabLabel": "Falta uma etiqueta em, pelo menos, um separador",
  "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
  "selectFields": "Selecionar Campos",
  "addField": "Adicionar Campo",
  "sum": "Soma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Média",
  "count": "CONTAGEM",
  "area": "ÁREA",
  "length": "LENGTH",
  "count_checkBox": "Exibir contagem de elementos",
  "area_checkBox": "Exibir soma de área",
  "length_checkBox": "Exibir soma de comprimento",
  "max_records": "Limite máximo atingido",
  "save_label": "Guardar Opções",
  "save_checkbox": "Ativar guardar",
  "report_label": "Opções de Relatório",
  "report_checkbox": "Ativar relatório",
  "csv_label": "Opções CSV",
  "csv_checkbox": "Exportar todos os campos",
  "display_label": "Opções de Exibição",
  "display_checkbox": "Exibir elementos resumidos",
  "snapshot_label": "Opções de Imagem Instantânea",
  "snapshot_checkbox": "Ativar imagem instantânea",
  "must_select_template": "Por favor, selecione um dos modelos de edição em Guardar Opções.",
  "count_label": "Rótulo de contagem",
  "area_label": "Rótulo de área",
  "length_label": "Rótulo de comprimento",
  "invalid_string_width": "O valor é demasiado extenso. ",
  "layer_type_not_supported": "Tipo de Camada Não Suportado.",
  "groupedSummary": "Contagens Agrupadas",
  "groupByField": "Agrupar por Campo",
  "labelType": "Incluir Rótulo",
  "prefix": "Como Prefixo",
  "suffix": "Como Sufixo",
  "need_group_field": "Por favor, utilize a ação editar para definir um Grupo Por Campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Acções",
  "save_point_checkbox": "Guardar pontos",
  "save_line_checkbox": "Guardar linhas",
  "save_poly_checkbox": "Guardar polígonos",
  "no_valid_popup_fields": "Não existem quaisquer campos válidos na janela pop-up. Por favor, utilize a ação editar para definir um campo.",
  "no_valid_fields": "Não existem campos válidos. Por favor, utilize a ação editar para definir opções de visualização.",
  "incident_label": "Rótulo de separador",
  "locate_incident_label": "Rótulo de área de interesse",
  "incident": "Incidente",
  "locate_incident": "Localizar Incidente",
  "buffer_value": "Distância do Buffer",
  "tab_options": "Análise",
  "export_options": "Saída",
  "instruction_save": "Guardar a localização num serviço de elementos.",
  "instruction_snapshot": "Criar um mapa base baseado na localização",
  "instruction_report": "Criar um relatório impresso da localização.",
  "instruction_all_fields": "Exportar todos os campos com transferência de CSV.",
  "data_label": "Definições de Saída de Dados",
  "layer_error": "Camada em falta ou inválida.",
  "visibility_checkBox": "Desativar gestão de visibilidade da camada",
  "downloadTab": {
    "reportLegend": "Definições de Relatório",
    "textColorLabel": "Selecionar cor para títulos de colunas",
    "setButtonLabel": "Definir",
    "printGPServiceLabel": "Imprimir URL de Serviço",
    "logoLabel": "Logo",
    "logoChooserHint": "Clicar no ícone da imagem para alterar a imagem",
    "footnoteLabel": "Nota de Rodapé"
  }
});