define({
  "_widgetLabel": "Gráfico de Referência em Grade",
  "newGRGFromAreaButtonLabel": "Definir uma Grade de uma Área",
  "newGRGFromPointButtonLabel": "Definir uma Grade de um Ponto",
  "newGRGFromAreaTitle": "Definir uma Grade de uma Área",
  "newGRGFromPointTitle": "Definir uma Grade de um Ponto",
  "newGRGBySizeButtonLabel": "Por Dimensão",
  "newGRGFromRefSystemButtonLabel": "Por Sistema de Referência",
  "newGRGByTimeLabel": "Por tempo e Velocidade",
  "newGRGFromNonStandardButtonLabel": "Definir Grade Não Padrão",
  "newGRGAreaBySizeTitle": "GRG a partir de uma Área por Dimensão",
  "newGRGAreaBySizeDefineAreaLabel": "Área GRG",
  "addGRGAreaPolygonToolTip": "Desenhar Área GRG utilizando polígono",
  "addGRGAreaExtentToolTip": "Desenhar Área GRG utilizando extensão",
  "rotation": "Rotação da Grade",
  "numberRowsColumnsLabel": "Definir número de linhas e colunas",
  "newGRGAreaByRefSystemTitle": "GRG a partir de uma Área por Sistema de Referência",
  "gridSize": "Tamanho da Grade",
  "UTMZoneandBand": "Zona da Grade",
  "100000m": "100000 metro",
  "10000m": "10000 metro",
  "1000m": "1000 metro",
  "100m": "100 metro",
  "10m": "10 metro",
  "clipGrid": "Recortar Grade para Área GRG",
  "newGRGAreaFromNonStandardTitle": "Novo NRG",
  "newGRGPointBySizeTitle": "GRG a partir de Ponto por Dimensão",
  "newGRGPointByRefSystemTitle": "GRG a partir de Ponto por Sistema de Referência",
  "newGRGPointByTimeTitle": "GRG a partir de Ponto utilizando Tempo e Velocidade",
  "time": "Tempo",
  "rate": "Velocidade",
  "hours": "Horas",
  "minutes": "Minutos",
  "seconds": "Segundos",
  "ftPerSec": "Pés / segundo",
  "ftPerHour": "Pés / hora",
  "kmPerSec": "Quilômetros / segundo",
  "kmPerHour": "Quilômetros / hora",
  "mPerSec": "Metros / segundo",
  "mPerHour": "Metros / hora",
  "miPerSec": "Milhas / segundo",
  "miPerHour": "Milhas / hora",
  "nMPerSec": "Milhas Náuticas / segundo",
  "nMPerHour": "Milhas Náuticas / hora",
  "settingsTitle": "Configurações",
  "labelSettingsLabel": "Configurações de Rótulo",
  "labelSettingsButtonLabel": "Definir Configurações de Rótulo",
  "gridSettingsLabel": "Configurações da Grade",
  "gridSettingsButtonLabel": "Definir Configurações de Grade",
  "transparency": "Transparência",
  "labelStyle": "Estilo do Rótulo",
  "font": "Fonte",
  "textSize": "Tamanho do Texto",
  "textColor": "Cor do Texto",
  "halo": "Halo",
  "show": "Mostrar",
  "lockSettings": "As configurações foram bloqueadas pelo proprietário do aplicativo",
  "gridSettings": {
    "cellShape": "Forma da Célula",
    "cellUnits": "Unidades da Célula",
    "cellOutline": "Configurações de Contorno da Célula",
    "cellFill": "Configurações de Preenchimento da Célula",
    "gridReferenceSystem": "Sistema de Referência",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Origem do Rótulo",
    "labelType": "Tipo do Rótulo",
    "labelDirection": "Direção de Rótulo",
    "gridOrigin": "Origem da Grade",
    "default": "Retângulo",
    "hexagon": "Hexágono",
    "miles": "Milhas",
    "kilometers": "Quilômetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nautical-miles": "Milhas Náuticas",
    "lowerLeft": "Inferior Esquerdo",
    "lowerRight": "Inferior Direito",
    "upperLeft": "Superior Esquerdo",
    "upperRight": "Superior Direito",
    "center": "Centralizar",
    "alphaNumeric": "Alfa Numérico",
    "alphaAlpha": "Alfa-Alfa",
    "numeric": "Numérico",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Mostrar Rótulos"
  },
  "publishTitle": "Publicar GRG no Portal",
  "publishGRGBtn": "Publicar",
  "GRGLayerName": "Nome de Camada GRG Publicada",
  "invalidGRGLayerName": "O nome da camada deve conter somente caracteres alfanuméricos e underscores",
  "missingGRGLayerName": "Você deve inserir um nome para GRG",
  "publishingFailedLayerExists": "Falha na publicação: Você já tem um serviço de feição nomeado {0}. Escolha outro nome.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não foi possível criar: {0}",
  "addToDefinition": "Adicionar à definição: {0}",
  "successfullyPublished": "Camada da web publicada com sucesso{0}Gerenciar a camada da web",
  "userRole": "Não é possível criar serviço porque o usuário não tem permissões",
  "createGRGBtn": "Criar GRG",
  "clearGRGBtn": "Apagar",
  "labelFormat": "Formato do Rótulo",
  "helpIconTooltip": "Z: Designador de Zona de Grade (GZD)\nS: 100.000-metro Identificação Quadrada de Grade (GSID)\nX: Ao Leste (coordenadas X)\nY: Ao Note (coordenadas Y)\n\nExemplos:\nZSXY é 15SWC8081751205\nZS X,Y é 15SWC 80817,51205",
  "addPointToolTip": "Adicionar Origem GRG",
  "cellWidth": "Largura da Célula (x)",
  "cellHeight": "Altura da Célula (y)",
  "invalidNumberMessage": "Os valores inseridos não são válidos",
  "invalidRangeMessage": "O valor deve ser maior que 0",
  "gridAngleInvalidRangeMessage": "O valor deve estar entre -89,9 e 89,9.",
  "formatIconTooltip": "Entrada de formato",
  "coordInputLabel": "Origem GRG (DD)",
  "setCoordFormat": "Definir String de Formato de Coordenadas",
  "prefixNumbers": "Adicione o prefixo '+/-' para números positivos e negativos",
  "cancelBtn": "Cancelar",
  "applyBtn": "Aplicar",
  "comfirmInputNotation": "Confirmar Notação de Entrada",
  "notationsMatch": "notações correspondem sua entrada, confirme que deseja utilizar:",
  "numberOfCellsHorizontal": "# Células Horizontais",
  "numberOfCellsVertical": "# Células Verticais",
  "gridAngle": "Rotação da Grade",
  "tooManyCellsErrorMessage": "Você está tentando criar uma grade incluindo mais de 2000 células. É aconselhável reduzir o número de células sendo criadas alterando o tamanho da grade ou área da grade.",
  "missingParametersMessage": "<p>O formulário de criação de GRG tem parâmetros inválidos ou ausentes, assegure que:</p><ul><li>Uma área de GRG tenha sido desenhada.</li><li>A largura da célula e altura contém valores válidos.</li></ul>",
  "missingOriginParametersMessage": "<p>O formulário de criação de GRG tem parâmetros inválidos ou ausentes, assegure que:</p><ul><li>Uma origem de GRG tenha sido configurada.</li><li>O tempo, velocidade e entradas de ângulo contém valores válidos.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>O formulário de criação de GRG tem parâmetros inválidos ou ausentes. Assegure que a largura de célula e entradas de altura contenham valores válidos.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>O formulário de criação de GRG tem parâmetros inválidos ou ausentes. Assegure que o número de entradas de células horizontais e verticais contenham valores válidos.</p>",
  "drawPointToolTip": "Clique para adicionar ponto de origem de GRG",
  "missingLayerNameMessage": "Você deve inserir um nome de camada válida antes de poder publicar",
  "parseCoordinatesError": "Não é possível analisar coordenadas. Verifique sua entrada.",
  "grgPolarRegionError": "A extensão de GRG está dentro de uma região polar. As células que caem dentro da região polar não serão criadas.",
  "grgPolarOriginError": "O ponto de origem de GRG não pode estar dentro de uma região polar ao criar um GRG por Sistema de Referência.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus Decimais - Latitude/Longitude",
  "DDLongLatNotation": "Graus Decimais - Longitude/Latitude",
  "DDMLatLongNotation": "Graus Minutos Decimais - Latitude/Longitude",
  "DDMLongLatNotation": "Graus Minutos Decimais - Longitude/Latitude",
  "DMSLatLongNotation": "Graus Minutos Segundos - Latitude/Longitude",
  "DMSLongLatNotation": "Graus Minutos Segundos - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Letra da Banda",
  "UTMHemNotation": "UTM - Hemisfério (N/S)"
});