define({
  "layerSelect": "Den Image-Layer auswählen",
  "displayMeasureResultInPopup": "Messergebnisse in einem Pop-up anzeigen",
  "angularUnitSelect": "Standardwinkeleinheit",
  "linearUnitSelect": "Lineare Standardeinheit",
  "areaUnitSelect": "Standardflächeneinheit",
  "displayOperationSelect": "Messvorgänge auswählen",
  "errorSectionMessage": "Keiner der Layer unterstützt Messfunktionen.",
  "unitLabel": {
    "esriInches": "Zoll",
    "esriFeet": "Fuß",
    "esriYards": "Yard",
    "esriMiles": "Meilen",
    "esriNauticalMiles": "Seemeilen",
    "esriMillimeters": "Millimeter",
    "esriCentimeters": "Zentimeter",
    "esriDecimeters": "Dezimeter",
    "esriMeters": "Meter",
    "esriKilometers": "Kilometer",
    "esriDURadians": "Bogenmaß",
    "esriDUDecimalDegrees": "Grad",
    "esriSquareInches": "Quadratinch",
    "esriSquareFeet": "Quadratfuß",
    "esriSquareYards": "Quadratyard",
    "esriAcres": "Acres",
    "esriSquareMiles": "Quadratmeilen",
    "esriSquareMillimeters": "Quadratmillimeter",
    "esriSquareCentimeters": "Quadratzentimeter",
    "esriSquareDecimeters": "Quadratdezimeter",
    "esriSquareMeters": "Quadratmeter",
    "esriAres": "Ar",
    "esriHectares": "Hektar",
    "esriSquareKilometers": "Quadratkilometer"
  },
  "operationLabel": {
    "esriMensurationPoint": "Position",
    "esriMensurationDistanceAndAngle": "Entfernung und Winkel",
    "esriMensurationAreaAndPerimeter": "Fläche und Umfang",
    "esriMensurationHeightFromBaseAndTop": "Höhe: Basis bis Spitze",
    "esriMensurationHeightFromBaseAndTopShadow": "Höhe: Basis zur Schattenspitze",
    "esriMensurationHeightFromTopAndTopShadow": "Höhe: Spitze zur Schattenspitze",
    "esriMensurationCentroid": "Schwerpunkt",
    "esriMensurationPoint3D": "Position (3D)",
    "esriMensurationDistanceAndAngle3D": "Entfernung und Winkel (3D)",
    "esriMensurationAreaAndPerimeter3D": "Fläche und Umfang (3D)",
    "esriMensurationCentroid3D": "Schwerpunkt (3D)"
  }
});