define({
  "gridTabLabel": "格子線",
  "labelTabLabel": "ラベル",
  "referenceSystemTabLabel": "参照系",
  "gridTabDescription": "グリッド セルの表示設定および振舞いを設定します。",
  "cellOutlineColor": "セルのアウトライン色",
  "cellFillColor": "セルの塗りつぶし色",
  "transparency": "透過表示",
  "cellShapeDropDown": "セルの形状",
  "default": "矩形",
  "hexagon": "六角形",
  "cellUnitsDropDown": "セルの単位",
  "miles": "マイル",
  "kilometers": "キロメートル",
  "feet": "フィート",
  "meters": "メートル",
  "yards": "ヤード",
  "nautical-miles": "海里",
  "gridOriginDropDown": "グリッドの原点",
  "lowerLeft": "左下",
  "lowerRight": "右下",
  "upperLeft": "左上",
  "upperRight": "右上",
  "center": "中央配置",
  "labelTabDescription": "グリッド ラベルの表示設定および振舞いを設定します。",
  "labelSettings": "ラベル スタイル",
  "font": "フォント",
  "textSize": "テキスト サイズ",
  "textColor": "テキスト色",
  "halo": "ハロー",
  "show": "表示",
  "labelTypeDropDown": "ラベル タイプ",
  "alphaNumeric": "英数字",
  "alphaAlpha": "英字",
  "numeric": "数値",
  "labelDirectionDropDown": "ラベルの方向",
  "horizontal": "水平",
  "vertical": "鉛直方向",
  "labelOriginDropDown": "ラベルの起点",
  "referenceSystemlTabDescription": "デフォルトの参照系を設定します。",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "ロック設定 - ユーザーがウィジェット内の構成済みの設定を変更できないようになります。"
});