define({
  "settings": "Paramètres",
  "titleSettings": "Paramètres de texte",
  "imageSettings": "Paramètres d'image",
  "backgroundColor": "Couleur d'arrière-plan",
  "alignment": "Alignement",
  "textSize": "Taille de texte",
  "textColor": "Couleur du texte",
  "dataSource": "Source de données",
  "chartSettings": "Paramètres de diagramme",
  "data": "Données",
  "dataLabels": "Etiquettes de données",
  "displayMode": "Mode Affichage",
  "featureOption": "Afficher les valeurs entité par entité",
  "categoryOption": "Afficher les valeurs par catégorie",
  "countOption": "Afficher le nombre d’entités par catégorie",
  "fieldOption": "Afficher les valeurs attributaires sous forme de diagrammes",
  "categoryField": "Champ de catégorie",
  "labelField": "Champ d’étiquette",
  "valueFields": "Champs de valeur",
  "operation": "Opération",
  "sumOption": "Somme",
  "averageOption": "Moyenne",
  "minOption": "Minimal",
  "maxOption": "Maximal",
  "dataFormat": "Format des données",
  "decimalPlaces": "Décimales",
  "prefix": "Préfixe",
  "suffix": "Suffixe",
  "dataType": "Type de données",
  "featureCount": "Nombre d'entités",
  "fieldStatistics": "Statistiques du champ",
  "display": "Affichage",
  "chartColor": "Couleur du diagramme",
  "horizontalAxis": "Axe horizontal",
  "verticalAxis": "Axe vertical",
  "legend": "Légende",
  "position": "Position",
  "top": "Haut",
  "bottom": "Bas",
  "useDataSourceSelection": "Utiliser la sélection",
  "dataSourceFilterByExtent": "Filtrer selon l'étendue",
  "changeTemplate": "Changer de modèle",
  "numberSettings": "Paramètres de numérotation",
  "gaugeSettings": "Paramètres de jauge",
  "indicators": "Indicateurs",
  "ifValue": "Si la valeur",
  "and": "et",
  "numberOperatorIsLessThan": "est inférieur à",
  "numberOperatorIsGreaterThan": "est supérieur à",
  "numberOperatorIsBetween": "est entre",
  "numberOperatorIsEqual": "est égal à",
  "numberOperatorIsNotEqual": "est différent de",
  "then": "Avant",
  "ratio": "Ratio",
  "trueValue": "Valeur true",
  "changeValueColor": "remplacer la couleur de valeur par",
  "changeGaugeColor": "remplacer la couleur de jauge par",
  "setIndicatorIcon": "définir l'icône de l'indicateur comme",
  "icons": "Icônes",
  "style": "Style",
  "placement": "Placement",
  "left": "Gauche",
  "replace": "Remplacer",
  "right": "Droite",
  "color": "Couleur",
  "categoryExists": "La catégorie existe !",
  "comboxHint": "Saisir ou sélectionner une valeur",
  "comboxDisableInputHint": "Choix unique",
  "sortBy": "Trier par",
  "labelAxis": "Etiquette",
  "valueAxis": "Valeur",
  "minPeriod": "Période minimale",
  "automatic": "Automatique",
  "periodsWithOutRecords": "Périodes sans enregistrements",
  "nullValue": "Valeur nulle",
  "calculatedAsZero": "Calculé(e) comme zéro",
  "ignored": "Ignoré",
  "maxCategories": "Catégories maximum",
  "useLayerSymbology": "Utiliser la symbologie de la couche",
  "hollowsize": "Taille de vide",
  "splitField": "Champ de fractionnement",
  "parsingperiodTip": "Échec du calcul. Trop d’intervalles de temps en raison de la période d’analyse brève.",
  "manyCategoryTip": "Échec de l’affichage du diagramme. Trop de catégories.",
  "setColor": "Définir la couleur",
  "setTheColorOf": "Puis définir la couleur de",
  "setTheColorAs": "Puis définir la couleur comme",
  "ifStr": "Si",
  "as": "as",
  "is": "is",
  "isNot": "n'est pas",
  "barCluster": "agrégat de barre",
  "individualBar": "barre individuelle",
  "allOthers": "Tous les autres",
  "category": "Catégorie",
  "indicatorSum": "SOMME",
  "indicatorAve": "MOY",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Définissez les indicateurs correctement.",
  "dataRange": "Plage de données",
  "targetValue": "Valeur cible",
  "currentValue": "Valeur actuelle",
  "gaugeColor": "Couleur de jauge",
  "min": "Minimal",
  "max": "Maximal",
  "displayValueIn": "Afficher la valeur dans",
  "noData": "Aucune donnée",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "V",
  "billionAbbreviation": "V",
  "warning": "Avertissement",
  "noSettingWaring1": "Cliquez sur un élément pour en définir les propriétés.",
  "noSettingWaring2": "Faites glisser pour redimensionner ou réorganiser un élément.",
  "donNotShowAgain": "Ne plus afficher",
  "changeTemplateWarning": "Cette action va effacer l'ensemble de vos paramètres et ouvrir un nouveau modèle vide.",
  "requiredFieldWarning": "Cette valeur est obligatoire :",
  "dataSourceNotSet": "Définissez une source de données.",
  "addIndicatorTip": "Ajouter un indicateur",
  "chooseTemplatePopupTitle": "Choisir un modèle",
  "filterExtentTipWithaTag": "Vous pouvez désactiver le filtre par <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>source de données supplémentaire</a> sous l’onglet Attribut.",
  "filterExtentTip": "Vous pouvez désactiver le filtre par source de données supplémentaire sous l’onglet Attribut.",
  "customColorByCategory": "Couleur personnalisée par catégorie",
  "randomColor": "Couleur aléatoire",
  "valueString": "Valeur",
  "fieldString": "Terrain",
  "includeThresholdValue": "Inclure la valeur de seuil",
  "percentage": "Pourcentage",
  "colorSchema": "Combinaison de couleurs",
  "addCategory": "Ajouter une catégorie",
  "clickToEdit": "Cliquer pour mettre à jour",
  "nullText": "Null",
  "others": "Autres",
  "stringsInTemplate": {
    "name_number": "Nombre",
    "name_gauge": "Jauge",
    "name_vertical_gauge": "Jauge verticale",
    "name_horizontal_gauge": "Jauge horizontale",
    "name_pie": "Secteur",
    "name_donut": "Anneau",
    "name_bar": "Barre",
    "name_stacked_bar": "Barre empilée",
    "name_percentage_stacked_bar": "Barre empilée de pourcentage",
    "name_column": "Colonne",
    "name_stacked_column": "Colonne empilée",
    "name_percentage_stacked_column": "Colonne empilée de pourcentage",
    "name_line": "Ligne",
    "name_area": "Surface",
    "name_stacked_area": "Zone empilée",
    "name_percentage_stacked_area": "Zone empilée de pourcentage",
    "titleOfTheInfographic": "TITLE OF THE INFOGRAPHIC",
    "description": "Description : informations supplémentaires sur cette infographie."
  }
});