define({
  "_widgetLabel": "坐标转换",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十进制度 - 纬度/经度",
  "DDLongLatNotation": "十进制度 - 经度/纬度",
  "DDMLatLongNotation": "度十进制分 - 纬度/经度",
  "DDMLongLatNotation": "度十进制分 - 经度/纬度",
  "DMSLatLongNotation": "度十进制秒 - 纬度/经度",
  "DMSLongLatNotation": "度十进制秒 - 经度/纬度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 带字母",
  "UTMHemNotation": "UTM - 半球(N/S)",
  "formatInput": "格式输入",
  "copyAll": "全部复制",
  "copySuccessful": "复制成功",
  "copyFailed": "无法复制。请使用 ctrl+c 作为替代方法。",
  "parseCoordinatesError": "无法解析坐标。请检查您的输入。",
  "comfirmInputNotation": "确认输入注记",
  "latLongWarningMessage": "检测到输入坐标同时拥有经度或纬度值的前缀和后缀，返回的坐标以前缀为基础。",
  "inputLabel": "输入",
  "outputLabel": "输出",
  "cancelButtonLabel": "取消",
  "applyButtonLabel": "应用",
  "posNegPrefixLabel": "向正数和负数添加“+/-”前缀",
  "editCoordinateDialogTitle": "设置坐标格式字符串",
  "rememberDecisionLabel": "记住我的决定，不再询问。<br/>",
  "coordinateInputLabel": "输入坐标或单击地图",
  "zoomLabel": "缩放",
  "multipleNotationLabel": "发现与您的输入匹配的注记。请确认您想使用的注记：",
  "copyToClipboard": "复制到剪贴板",
  "formatOutput": "格式输出",
  "addNewNotation": "添加新注记",
  "notationAddedMessage": "已添加新注记",
  "addLabel": "添加",
  "removeCoordinate": "移除坐标",
  "expandOutput": "扩展输出",
  "latitudeLabel": "纬度",
  "longitudeLabel": "经度",
  "quadrantLabel": "象限",
  "keyLabel": "键",
  "fifteenDegreeLabel": "15Â° Quad",
  "oneDegreeLabel": "1Â° Quad",
  "eastingLabel": "东移",
  "northingLabel": "北移",
  "zoneLabel": "分度带",
  "bandLabel": "带",
  "gzdLabel": "GZD",
  "gridSquareLabel": "格网方格",
  "hemisphereLabel": "半球"
});