define({
  "_widgetLabel": "Ruudukkomuotoinen viitegrafiikka",
  "newGRGFromAreaButtonLabel": "Määritä ruudukko alueesta",
  "newGRGFromPointButtonLabel": "Määritä ruudukko pisteestä",
  "newGRGFromAreaTitle": "Määritä ruudukko alueesta",
  "newGRGFromPointTitle": "Määritä ruudukko pisteestä",
  "newGRGBySizeButtonLabel": "Ulottuvuuden perusteella",
  "newGRGFromRefSystemButtonLabel": "Viitejärjestelmän perusteella",
  "newGRGByTimeLabel": "Ajan ja nopeuden perusteella",
  "newGRGFromNonStandardButtonLabel": "Määritä muu kuin vakiomuotoinen ruudukko",
  "newGRGAreaBySizeTitle": "GRG alueesta ulottuvuuden perusteella",
  "newGRGAreaBySizeDefineAreaLabel": "GRG-alue",
  "addGRGAreaPolygonToolTip": "Piirrä GRG-alue aluekohteen avulla",
  "addGRGAreaExtentToolTip": "Piirrä GRG-alue kartan näkymän laajuudelle",
  "rotation": "Ruudukon kierto",
  "numberRowsColumnsLabel": "Määritä rivien ja sarakkeiden määrä",
  "newGRGAreaByRefSystemTitle": "GRG alueesta viitejärjestelmän perusteella",
  "gridSize": "Ruudukon koko",
  "UTMZoneandBand": "Ruudukon vyöhyke",
  "100000m": "100 000 metriä",
  "10000m": "10 000 metriä",
  "1000m": "1 000 metriä",
  "100m": "100 metriä",
  "10m": "10 metriä",
  "clipGrid": "Leikkaa ruudukko GRG-alueeseen",
  "newGRGAreaFromNonStandardTitle": "Uusi NRG",
  "newGRGPointBySizeTitle": "GRG pisteestä ulottuvuuden perusteella",
  "newGRGPointByRefSystemTitle": "GRG pisteestä viitejärjestelmän perusteella",
  "newGRGPointByTimeTitle": "GRG pisteestä ajan ja nopeuden avulla",
  "time": "Kellonaika",
  "rate": "Nopeus",
  "hours": "Tuntia",
  "minutes": "Minuuttia",
  "seconds": "Sekuntia",
  "ftPerSec": "Jalkaa/sekunti",
  "ftPerHour": "Jalkaa/tunti",
  "kmPerSec": "Kilometriä/sekunti",
  "kmPerHour": "Kilometriä/tunti",
  "mPerSec": "Metriä/sekunti",
  "mPerHour": "Metriä/tunti",
  "miPerSec": "Mailia/sekunti",
  "miPerHour": "Mailia/tunti",
  "nMPerSec": "Merimailia/sekunti",
  "nMPerHour": "Merimailia/tunti",
  "settingsTitle": "Asetukset",
  "labelSettingsLabel": "Tunnustekstien asetukset",
  "labelSettingsButtonLabel": "Määritä tunnustekstien asetukset",
  "gridSettingsLabel": "Ruudukkoasetukset",
  "gridSettingsButtonLabel": "Määritä ruudukkoasetukset",
  "transparency": "Läpinäkyvyys",
  "labelStyle": "Tunnustekstin tyyli",
  "font": "Fontti",
  "textSize": "Tekstin koko",
  "textColor": "Tekstin väri",
  "halo": "Reunus",
  "show": "Näytä",
  "lockSettings": "Sovelluksen omistaja on lukinnut asetukset",
  "gridSettings": {
    "cellShape": "Solun muoto",
    "cellUnits": "Solun yksiköt",
    "cellOutline": "Solun ääriviiva-asetukset",
    "cellFill": "Solun täyttöasetukset",
    "gridReferenceSystem": "Viitejärjestelmä",
    "gridDatum": "Datumi: WGS84",
    "labelStartPosition": "Tunnustekstin alkupiste",
    "labelType": "Tunnustekstin tyyppi",
    "labelDirection": "Tunnustekstin suunta",
    "gridOrigin": "Ruudukon alkupiste",
    "default": "Suorakulmio",
    "hexagon": "Kuusikulmio",
    "miles": "Mailia",
    "kilometers": "Kilometriä",
    "feet": "Jalkaa",
    "meters": "Metriä",
    "yards": "Jaardia",
    "nautical-miles": "Meripeninkulmaa",
    "lowerLeft": "Alavasen",
    "lowerRight": "Alaoikea",
    "upperLeft": "Ylävasen",
    "upperRight": "Yläoikea",
    "center": "Keskitä",
    "alphaNumeric": "Aakkosnumeerinen",
    "alphaAlpha": "Vain kirjaimia",
    "numeric": "Numeerinen",
    "horizontal": "Vaaka",
    "vertical": "Pysty",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Näytä tunnustekstit"
  },
  "publishTitle": "Julkaise GRG portaaliin",
  "publishGRGBtn": "Julkaise",
  "GRGLayerName": "Julkaistun GRG-karttatason nimi",
  "invalidGRGLayerName": "Karttatason nimi voi sisältää vain aakkosnumeerisia merkkejä ja alaviivoja",
  "missingGRGLayerName": "GRG:n nimi on annettava",
  "publishingFailedLayerExists": "Julkaisu epäonnistui: Sinulla on jo kohdepalvelu nimeltä {0}. Valitse toinen nimi.",
  "checkService": "Tarkista palvelu: {0}",
  "createService": "Luo palvelu: {0}",
  "unableToCreate": "Kohteen {0} tuonti ei onnistu",
  "addToDefinition": "Lisää määritykseen: {0}",
  "successfullyPublished": "Web-karttatason julkaisu onnistui{0}Web-karttatason hallinta",
  "userRole": "Palvelun luonti ei onnistu, koska käyttäjällä ei ole käyttöoikeuksia",
  "createGRGBtn": "Luo GRG",
  "clearGRGBtn": "Tyhjennä",
  "labelFormat": "Tunnustekstin muoto",
  "helpIconTooltip": "Z: ruudukon vyöhykemääritys (GZD)\nS: ruudukon 100 000 metrin neliön tunnus (GSID)\nX: itäinen (X-koordinaatti)\nY: pohjoinen (Y-koordinaatti)\n\nEsimerkit:\nZSXY on 15SWC8081751205\nZS X,Y on 15SWC 80817,51205",
  "addPointToolTip": "Lisää GRG:n alkupiste",
  "cellWidth": "Solun leveys (x)",
  "cellHeight": "Solun korkeus (y)",
  "invalidNumberMessage": "Annettu arvo ei kelpaa",
  "invalidRangeMessage": "Arvon on oltava suurempi kuin 0",
  "gridAngleInvalidRangeMessage": "Arvon on oltava välillä -89,9 ja 89,9.",
  "formatIconTooltip": "Muodon lähtöaineisto",
  "coordInputLabel": "GRG:n alkupiste (DD)",
  "setCoordFormat": "Määritä koordinaatin muotomerkkijono",
  "prefixNumbers": "Lisää etuliite +/- positiivisiin ja negatiivisiin numeroihin",
  "cancelBtn": "Peruuta",
  "applyBtn": "Käytä",
  "comfirmInputNotation": "Vahvista lähtöaineiston esitysmuoto",
  "notationsMatch": "lähtöaineistoasi vastaavia esitystapoja. Vahvista käytettävä esitystapa:",
  "numberOfCellsHorizontal": "Vaakasuuntaisten solujen määrä",
  "numberOfCellsVertical": "Pystysuuntaisten solujen määrä",
  "gridAngle": "Ruudukon kierto",
  "tooManyCellsErrorMessage": "Yrität luoda ruudukkoa, joka koostuu yli 2 000 solusta. On suositeltavaa pienentää luotavien solujen määrää muuttamalla ruudukon kokoa tai ruudukkoaluetta.",
  "missingParametersMessage": "<p>GRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisiä. Varmista seuraavat asiat:</p><ul><li>GRG-alue on piirretty.</li><li>Solun leveys ja korkeus sisältävät kelvolliset arvot.</li></ul>",
  "missingOriginParametersMessage": "<p>GRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisiä. Varmista seuraavat asiat:</p><ul><li>GRG:n alkupiste on määritetty.</li><li>Aika-, nopeus- ja kulmasyötteet sisältävät kelvolliset arvot.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>GRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisiä. Varmista, että solun leveys- ja korkeussyötteet sisältävät kelvolliset arvot.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>GRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisiä. Varmista, että vaaka- ja pystysyötteiden solujen määrät sisältävät kelvolliset arvot.<>",
  "drawPointToolTip": "Lisää GRG:n alkupiste napsauttamalla",
  "missingLayerNameMessage": "Kelvollinen karttatason nimi on annettava ennen julkaisua",
  "parseCoordinatesError": "Koordinaattien jäsennys ei onnistu. Tarkista lähtöaineistosi.",
  "grgPolarRegionError": "GRG:n laajuus on napa-alueella. Soluja, jotka osuvat napa-alueille, ei luoda.",
  "grgPolarOriginError": "GRG:n alkupiste ei voi olla napa-alueella, kun GRG:tä luodaan viitejärjestelmän perusteella.",
  "DD": "da",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desimaaliasteet – leveys-/pituusaste",
  "DDLongLatNotation": "Desimaaliasteet – pituus-/leveysaste",
  "DDMLatLongNotation": "Asteet, desimaaliminuutit – leveys-/pituusaste",
  "DDMLongLatNotation": "Asteet, desimaaliminuutit – pituus-/leveysaste",
  "DMSLatLongNotation": "Asteet, minuutit, sekunnit – leveys-/pituusaste",
  "DMSLongLatNotation": "Asteet, minuutit, sekunnit – pituus-/leveysaste",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – kaistan kirjain",
  "UTMHemNotation": "UTM – pallonpuolisko (P/E)"
});