define({
  "_widgetLabel": "Расстояние и направление",
  "tabLineTitle": "Линия",
  "tabCircleTitle": "Окружность",
  "tabEllipseTitle": "Эллипс",
  "tabRingsTitle": "Кольца",
  "multipleNotationsMessage": " уведомления соответствуют входным данным. Выберите, что вы хотите использовать:",
  "invalidCoordinateMessage": "Недопустимая координата",
  "confirmInputNotationMessage": "Подтвердите входное уведомление",
  "prefixSuffixMessage": "Выявлено, что значения входных координат для широты и долготы содержат и префикс и суффикс, возвращены значения координат на основе префикса.",
  "rememberDecisionMessage": "Запомнить мой выбор и больше не спрашивать.<br/>",
  "majorAxisTooltipMessage": "Щелкните длину большой оси",
  "minorAxisTooltipMessage": "Переместите мышь на исходную позицию, чтобы задать малую ось и завершить рисование эллипса",
  "clickToFinishLineMessage": "Щелкните, чтобы завершить рисование линии",
  "doubleClickEllipseMesage": "Дважды щелкните, чтобы завершить рисование колец диапазона",
  "invalidCoordinateTypeMessage": "Невозможно определить тип входных координат. Проверьте входные данные",
  "noCenterPointSetMessage": "Не задана центральная точка. Проверьте входные данные",
  "ellipseMajorAxis": "Большая ось",
  "ellipseMinorAxis": "Малая ось",
  "degreesRangeMessage": "Значение должно быть между 0 и 360.",
  "millsRangeMessage": "Значение должно быть между 0 и 6400.",
  "lengthLabel": "Длина",
  "angleLabel": "Угол",
  "startPointLabel": "Точка старта",
  "endPointLabel": "Конечная точка",
  "centerPointLabel": "Центральная точка",
  "distanceTableErrorMessage": "Таблица расстояний пуста. Проверьте, что вы ввели расстояния.",
  "setCoordFormatStringMessage": "Строка настройки формата координат",
  "prefixMessage": "Добавьте префикс \"+/–\" для положительных и отрицательных чисел",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Десятичные градусы – Широта/Долгота",
  "DDLongLatNotation": "Десятичные градусы – Широта/Долгота",
  "DDMLatLongNotation": "Градусы, десятичные минуты – Широта/Долгота",
  "DDMLongLatNotation": "Градусы, десятичные минуты – Широта/Долгота",
  "DMSLatLongNotation": "Градусы минуты секунды – Широта/Долгота",
  "DMSLongLatNotation": "Градусы минуты секунды – Широта/Долгота",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Буква пояса",
  "UTMHemNotation": "UTM  – Полушарие (N/S)",
  "circleTitle": "Создать окружность из",
  "radiusLabel": "Радиус",
  "diameterLabel": "Диаметр",
  "startPointPlaceHolderLabel": "Введите координаты",
  "formatInputLabel": "Входной формат",
  "drawCircleLabel": "Нарисовать окружность",
  "drawLineLabel": "Нарисовать линию",
  "createCircleInteractivelyLabel": "Создать окружность интерактивно",
  "rangeErrorMessage": "Недопустимый радиус или диаметр",
  "numericInvalidMessage": "Введите числовое значение",
  "timeLabel": "Время",
  "invalidTimeMessage": "Недопустимое значение времени",
  "hoursLabel": "Часы",
  "minutesLabel": "Минуты",
  "secondsLabel": "Секунды",
  "rateLabel": "Диапазон",
  "invalidDistanceMessage": "Недопустимое значение расстояния",
  "feetSecondsLabel": "Футы /  секунду",
  "feetHourLabel": "Футы /  час",
  "kmSecondLabel": "Километры /   секунду",
  "kmHourLabel": "Километр / час",
  "metersSecondLabel": "Метры / секунду",
  "metersHourLabel": "Метры / час",
  "milesSecondLabel": "Мили / секунду",
  "milesHourLabel": "Мили / час",
  "nauticalMilesSecondLabel": "Морские мили / секунду",
  "nauticalMilesHourLabel": "Морские мили / час",
  "clearGraphicsLabel": "Очистить графику",
  "ellipseTypeLabel": "Тип эллипса",
  "ellipseSemiLabel": "Половина",
  "ellipseFullLabel": "Полный",
  "drawEllipseLabel": "Нарисовать эллипс",
  "createEllipseInteractively": "Создать эллипс интерактивно",
  "axisLabel": "Ось",
  "majorRadiusLabel": "Большая (Радиус)",
  "axisErrorMessage": "Значение должно быть больше 0",
  "minorRadiusLabel": "Малая (Радиус)",
  "orientationLabel": "Ориентация",
  "orientationErrorMessage": "Значение должно быть между 0 и 360.",
  "warningMessage": "Предупреждение: Графика, созданная при помощи инструмента",
  "fromLabel": "От",
  "distanceBearingLabel": "Расстояние и дирекционный угол",
  "pointsLabel": "Точки",
  "createLineInteractively": "Создать линию интерактивно",
  "lineLengthErrorMessage": "Недопустимая длина линии",
  "degreesLabel": "Градусы",
  "milsLabel": "Mils",
  "lineTypeLabel": "Тип",
  "interactiveLabel": "Интерактивный",
  "fixedLabel": "Фиксированный",
  "originLabel": "Начало отсчета",
  "cumulativeLabel": "С накоплением",
  "numberOfRingsLabel": "Число колец",
  "ringsErrorMessage": "Недопустимое число колец",
  "distanceBetweenRingsLabel": "Расстояние между кольцами",
  "ringsDecimalErrorMessage": "Введите числовое значение до 2 десятичных знаков",
  "distanceUnitsLabel": "Единицы расстояния",
  "distancesLabel": "Расстояние",
  "numberOfRadialsLabel": "Число радиусов",
  "upLabel": "Вверх",
  "downLabel": "Вниз",
  "deleteLabel": "Удалить",
  "radialsErrorMessage": "Некорректное число радиусов. Максимально допускается 360",
  "addPointLabel": "Добавить точку",
  "valueLabel": "Значение",
  "valueText": "Введите значение",
  "actionLabel": "Действие"
});