define({
  "_widgetLabel": "फीचर की रिपोर्ट करें",
  "select": "चुनें",
  "draw": "खींचना",
  "chooseALayer": "कोई लेयर चुनें",
  "clickAFeature": "इसे चयन करने के लिए मानचित्र पर एक फीचर पर क्लिक करें।",
  "loadingFeatures": "चयनित फीचर का विवरण प्राप्त किया जा रहा है...",
  "errorTitle": "त्रुटि",
  "errorIdentify": "फीचर की त्रुटि की पहचान की गई है। कृपया जानकारी के लिए कंसोल लॉग की जाँच करें।",
  "infoWindowTitle": "विवरण",
  "layerLabel": "लेयर का नाम",
  "reviewStatusLabel": "स्थिति की समीक्षा करें",
  "selectReviewStatusAdd": "फीचर जोड़ें",
  "selectReviewStatusDelete": "फीचर मिटाएं",
  "selectReviewStatusMove": "फ़ीचर को मूव करें",
  "selectReviewStatusReshape": "फ़ीचर को रीशेप करें",
  "drawReviewStatusMissing": "अनउपलब्ध फीचर",
  "drawReviewStatusPosition": "स्थितीय त्रुटि",
  "drawReviewStatusShape": "आकार त्रुटि",
  "drawReviewStatusAttribute": "विशेषता त्रुटि",
  "notesLabel": "टिप्पणियाँ",
  "severityLabel": "तीव्रता",
  "reportedByLabel": "इसके द्वारा रिपोर्ट की गई है",
  "reportedByDefault": "गुमनाम",
  "reportButton": "रिपोर्ट",
  "reportMessage": "रिपोर्ट प्राप्त हो गई है",
  "errorReportMessage": "आपकी फीचर की रिपोर्टिंग में कोई त्रुटि थी",
  "drawErrorInstructions": "बिंदु, रेखा या बहुभुज का चयन करें और मानचित्र पर त्रुटि जिओमेट्री बनाएं:",
  "errorMapService": "मानचित्र सेवा जानकारी प्राप्त करने में त्रुटि थी",
  "noFeatureSelected": "क्लिक किए स्थान पर कोई फीचर नहीं पाई गई है",
  "selectFeatureMapPoint": "फीचर का चयन करने के लिए क्लिक करें",
  "drawFeatureMapPoint": "एक बिंदु जोड़ने के लिए क्लिक करें",
  "popupMessage": "संदेश",
  "popupError": "त्रुटि",
  "manyFeaturesSelected": "एक से अधिक फीचर पाई गई है। कृपया रिपोर्ट करने के लिए जूम इन और फीचर का चयन करें।"
});