define({
  "_widgetLabel": "Tok podataka",
  "streamControls": "Kontrole za tok podataka",
  "streamFilter": "Filtar",
  "startStreaming": "Pokreni tok podataka",
  "stopStreaming": "Zaustavi tok podataka",
  "streamLayers": "Slojevi s tokom podataka",
  "startStopStream": "Omogući opciju zaustavljanja toka podataka ili pokretanja toka podataka",
  "clearStream": "Omogući opciju brisanja prethodnih opservacija",
  "attributeFilter": "Omogući atributni filtar",
  "spatialFilter": "Omogući prostorni filtar",
  "configFilter": "Konfiguriraj atributni filtar toka podataka",
  "drawPrevious": "Omogući opciju crtanja prethodnih opservacija",
  "addNew": "Dodaj filtar",
  "setFilterName": "Postavi naziv filtra",
  "filterNameExists": "Naziv filtra postoji u tablici!",
  "invalidFilterName": "Naziv bi trebao biti riječ koja sadrži a-z, A-Z, 0-9 ili _.",
  "noFilterTip": "Nema konfiguriranog filtra",
  "addFilterFailed": "Dodavanje filtra nije uspjelo",
  "filterName": "Naziv filtra",
  "limitMapExtent": "Ograničite opservacije na trenutačno područje na karti",
  "limitDrawExtent": "Ograničite opservacije na područje koje je definirao korisnik",
  "newFilter": "Novi filtar",
  "filterReadOnly": "Filtar naslijeđen s web-karte samo je za čitanje."
});