define({
  "gridTabLabel": "Tīkls",
  "labelTabLabel": "Nosaukumi",
  "referenceSystemTabLabel": "Atsauces sistēma",
  "gridTabDescription": "Iestatīt tīkla šūnu izskatu un darbību.",
  "cellOutlineColor": "Šūnas kontūras krāsa",
  "cellFillColor": "Šūnas pildījuma krāsa",
  "transparency": "Caurspīdīgums",
  "cellShapeDropDown": "Šūnas forma",
  "default": "Taisnstūris",
  "hexagon": "Sešstūris",
  "cellUnitsDropDown": "Šūnas mērvienības",
  "miles": "Jūdzes",
  "kilometers": "Kilometri",
  "feet": "Pēdas",
  "meters": "Metri",
  "yards": "Jardi",
  "nautical-miles": "Jūras jūdzes",
  "gridOriginDropDown": "Tīkla sākuma punkts",
  "lowerLeft": "Apakšējā kreisajā",
  "lowerRight": "Apakšējā labajā",
  "upperLeft": "Augšējā kreisajā",
  "upperRight": "Augšējā labajā",
  "center": "Centrā",
  "labelTabDescription": "Iestatīt tīkla nosaukumu izskatu un darbību",
  "labelSettings": "Nosaukuma stils",
  "font": "Fonts",
  "textSize": "Teksta lielums",
  "textColor": "Teksta krāsa",
  "halo": "Oreols",
  "show": "Rādīt",
  "labelTypeDropDown": "Nosaukuma veids",
  "alphaNumeric": "Burtu-ciparu",
  "alphaAlpha": "Burtu-burtu",
  "numeric": "Skaitlisks",
  "labelDirectionDropDown": "Nosaukuma virziens",
  "horizontal": "Horizontāli",
  "vertical": "Vertikāli",
  "labelOriginDropDown": "Nosaukuma sākuma punkts",
  "referenceSystemlTabDescription": "Iestatīt noklusējuma atskaites sistēmu.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Bloķēt iestatījumus — tas lietotājam logrīkā neļaus mainīt nevienu konfigurēto iestatījumu"
});