define({
  "_widgetLabel": "คู่มือการตอบสนองเหตุฉุกเฉิน",
  "ergMainPageTitle": "ตามคู่มือการตอบสนองเหตุฉุกเฉิน 2016",
  "coordInputLabelStart": "ตำแหน่งการรั่วไหล (DD)",
  "coordInputLabel": "ตำแหน่งการรั่วไหล",
  "addPointToolTip": "เพิ่มตำแหน่งการรั่วไหล",
  "drawPointToolTip": "คลิกเพื่อเพิ่มตำแหน่งการรั่วไหล",
  "material": "วัสดุ",
  "materialPlaceholder": "เริ่มพิมพ์เพื่อค้นหาวัสดุ",
  "table3Message": "วัสดุที่คุณเลือกต้องใช้ข้อมูลเพิ่มเติมหากคุณกำลังรับมือกับการรั่วไหลขนาดใหญ่ \n\nโปรดตรวจสอบว่าคุณมีค่าที่ถูกต้องที่เลือกสำหรับความเร็วลมและตู้ขนส่ง",
  "table2Message": "วัสดุที่คุณเลือกอาจทำให้เกิดก๊าซพิษที่เป็นอันตรายจำนวนมากเมื่อไหลลงในน้ำ \n\nคุณอาจต้องพิจารณาใช้วัสดุต่อไปนี้:\n\n",
  "spillSize": "ขนาดการรั่วไล",
  "small": "เล็ก",
  "large": "ใหญ่",
  "fireLabel": "แสดงโซนการแยกไฟ",
  "weatherLabel": "สภาพอากาศปัจจุบันในสถานที่ที่มีการรั่วไหล",
  "weatherIntialText": "<br />อัปเดตเมื่อมีการระบุตำแหน่งการรั่วไหล",
  "temperature": "อุณหภูมิ",
  "wind": "ลม",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "ไม่ได้รับข้อมูลสภาพอากาศ อัปเดตค่าความเร็วลมและเวลาของการรั่วไหลด้วยตนเอง",
  "windDirection": "ทิศทางลม (พัดไป)",
  "timeOfSpill": "เวลาของการรั่วไหล",
  "day": "วัน",
  "night": "กลางคืน",
  "windSpeed": "ความเร็วลม",
  "low": "ต่ำ",
  "moderate": "ปานกลาง",
  "high": "สูง",
  "transportContainer": "ตู้ขนส่ง",
  "rail": "รถไฟบรรทุกถัง",
  "semi": "รถบรรทุกหรือรถพ่วงทางหลวง",
  "mton": "กระบอกสูบตันหลายอัน",
  "ston": "กระบอกสูบเล็กหลายอันหรือกระบอกสูบตันหนึ่งอัน",
  "ag": "ถังพยาบาลเกษตร",
  "msm": "กระบอกสูบเล็กหลายอัน",
  "bleveLabel": "แสดงโซนการแยก BLEVE",
  "capacity": "ความจุของตู้ขนส่ง (ลิตร)",
  "bleveMessage": "สำหรับวัสดุที่คุณเลือกระยะการอพยพเพิ่มเติมสามารถแสดงได้สำหรับ BLEVE\n\nหากต้องการเปิดใช้งาน ให้ตั้งค่าแสดงโซนการแยก BLEVE เป็นเปิดและเลือกความจุตู้ขนส่งที่เหมาะสม",
  "noPAZoneMessage": "ไม่มีระยะทางในการดำเนินการป้องกันสำหรับวัสดุนี้ มีเฉพาะการคำนวณโซนการแยกและการอพยพครั้งแรกเท่านั้น",
  "settingsTitle": "การตั้งค่า",
  "spillLocationLabel": "ตำแหน่งการรั่วไหล",
  "spillLocationButtonLabel": "กำหนดค่าตำแหน่งการรั่วไหล",
  "IISettingsLabel": "โซนการแยกเริ่มต้น",
  "IIButtonLabel": "กำหนดค่าการแยกเริ่มต้น",
  "PASettingsLabel": "โซนการดำเนินการป้องกัน",
  "PAButtonLabel": "กำหนดค่าการดำเนินการป้องกัน",
  "downwindSettingsLabel": "โซนตามทิศทางลม",
  "downwindButtonLabel": "กำหนดค่าตามทิศทางลม",
  "fireSettingsLabel": "โซนการแยกไฟ",
  "fireButtonLabel": "กำหนดค่าการแยกไฟ",
  "bleveSettingsLabel": "โซนการแยก BLEVE",
  "bleveButtonLabel": "กำหนดค่า BLEVE",
  "style": "สไตล์",
  "lineStyles": {
    "esriSLSDash": "เส้นขีด",
    "esriSLSDashDot": "เส้นขีด จุด",
    "esriSLSDashDotDot": "เส้นขีด จุด จุด",
    "esriSLSDot": "จุด",
    "esriSLSLongDash": "เส้นขีดยาว",
    "esriSLSLongDashDot": "เส้นจุดยาว",
    "esriSLSNull": "ไม่มีค่า",
    "esriSLSShortDash": "เส้นขีดสั้น",
    "esriSLSShortDashDot": "เส้นจุดสั้น",
    "esriSLSShortDashDotDot": "เส้นขีดและจุดสั้น",
    "esriSLSShortDot": "จุดสั้น",
    "esriSLSSolid": "สีเดียว"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "ย้อนกลับ",
    "esriSFSCross": "กากบาท",
    "esriSFSDiagonalCross": "เส้นทแยงมุม",
    "esriSFSForwardDiagonal": "ส่งต่อ",
    "esriSFSHorizontal": "แนวนอน",
    "esriSFSNull": "ไม่มีค่า",
    "esriSFSSolid": "สีเดียว",
    "esriSFSVertical": "ตั้งฉาก"
  },
  "resultsTitle": "ผลลัพธ์",
  "publishERGBtn": "เผยแพร่",
  "ERGLayerName": "ชื่อชั้นข้อมูล ERG ที่เผยแพร่แล้ว",
  "invalidERGLayerName": "ชื่อชั้นข้อมูลต้องประกอบด้วยอักษรและตัวเลขและขีดล่างเท่านั้น",
  "missingERGLayerName": "คุณต้องป้อนชื่อสำหรับ ERG",
  "publishingFailedLayerExists": "ไม่สามารถเผยแพร่: คุณมีฟีเจอร์เซอร์วิสชื่อ {0} แล้ว โปรดเลือกชื่ออื่น",
  "checkService": "ตรวจสอบบริการ: {0}.",
  "createService": "สร้างบริการ: {0}.",
  "unableToCreate": "ไม่สามารถสร้าง: {0}",
  "addToDefinition": "เพิ่มในคำนิยาม: {0}",
  "successfullyPublished": "เผยแพร่ชั้นข้อมูลเว็บเรียบร้อยแล้ว{0}จัดการชั้นข้อมูลเว็บ",
  "userRole": "ไม่สามารถสร้างบริการเนื่องจากผู้ใช้ไม่มีสิทธิ์",
  "transparency": "โปร่งแสง",
  "outline": "โครงร่าง",
  "fill": "พื้น (ใช้สีเฉพาะเมื่อรูปแบบถูกตั้งค่าเป็นแบบทึบ)",
  "createERGBtn": "สร้างโซน",
  "clearERGBtn": "เคลียร์",
  "labelFormat": "รูปแบบป้าย",
  "helpIconTooltip": "เกณฑ์มาตรฐานระหว่างขนาดการรั่วไหลขนาดเล็กและขนาดใหญ่คือ:\nของเหลว - 55 แกลลอน (208 ลิตร)\nของแข็ง - 60 ปอนด์ (300 กิโลกรัม)",
  "cellWidth": "ความกว้างของเซลล์ (x)",
  "cellHeight": "ความสูงของเซลล์ (y)",
  "invalidNumberMessage": "ค่าที่ป้อนไม่ถูกต้อง",
  "invalidRangeMessage": "ค่าต้องมากกว่า 0",
  "gridAngleInvalidRangeMessage": "จะต้องมีค่าระหว่าง -89.9 และ 89.9",
  "formatIconTooltip": "รูปแบบข้อมูลนำเข้า",
  "setCoordFormat": "ตั้งค่าระบบพิกัดรูปแบบสตริง",
  "prefixNumbers": "เพิ่มคำนำหน้า '+/-' เป็นตัวเลขบวกและลบ",
  "cancelBtn": "ยกเลิก",
  "applyBtn": "ใช้",
  "comfirmInputNotation": "ยืนยันการป้อนข้อมูล",
  "notationsMatch": "สัญกรณ์ตรงกับข้อมูลนำเข้าของคุณ โปรดยืนยันว่าคุณต้องการใช้รายการใด:",
  "missingLayerNameMessage": "คุณต้องป้อนชื่อชั้นข้อมูลที่ถูกต้องก่อนจึงจะสามารถเผยแพร่ได้",
  "parseCoordinatesError": "ไม่สามารถแยกวิเคราะห์พิกัดได้ โปรดตรวจสอบข้อมูลนำเข้าของคุณ",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "องศาทศนิยม - ละติจูด / ลองจิจูด",
  "DDLongLatNotation": "องศาทศนิยม - ละติจูด / ลองจิจูด",
  "DDMLatLongNotation": "องศา ทศนิยม นาที – ละติจูด / ลองจิจูด",
  "DDMLongLatNotation": "องศา ทศนิยม นาที – ละติจูด / ลองจิจูด",
  "DMSLatLongNotation": "องศา ลิปดา ฟิลิปดา - ละติจูด / ลองจิจูด",
  "DMSLongLatNotation": "องศา ลิปดา ฟิลิปดา - ละติจูด / ลองจิจูด",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisphere (N/S)"
});