define({
  "chartSettingLabel": "Diagrammas iestatījumi",
  "addNewLabel": "Pievienot jaunu",
  "generalSettingLabel": "Vispārīgi iestatījumi",
  "searchSourceSettingLabel": "Meklēšanas avota iestatījumi",
  "layerChooser": {
    "title": "Izvēlieties diagrammā attēlojamo slāni",
    "selectPolygonLayerLabel": "Izvēlēties slāni",
    "selectPolygonLayerHintText": "Padoms. Ja tiek konfigurētas vairākas diagrammas, tad slāņiem jābūt viena ģeometrijas tipa slāņiem.",
    "selectRelatedTableLayerLabel": "Izvēlieties ar slāni saistīto tabulu",
    "selectRelatedTableLayerHintText": "Padoms. Tiek rādītas tikai tabulas ar skaitliskiem laukiem",
    "errorInSelectingPolygonLayer": "Izvēlieties slāni, kam ir saistīts punktu slānis.",
    "errorInSelectingRelatedLayer": "Izvēlieties derīgu ar slāni saistīto tabulu/slāni.",
    "polygonLayerNotHavingRelationships": "Izvēlētajam slānim nav nevienas saistītas tabulas/slāņa."
  },
  "ChartSetting": {
    "sectionTitle": "Sadaļas virsraksts",
    "sectionTitleHintText": "Padoms. Rādīts sadaļas galvenes virsrakstā",
    "chartTitle": "Diagrammas virsraksts",
    "chartTitleHintText": "Padoms. Rādīts diagrammas augšdaļas centrā",
    "chartDescription": "Apraksts",
    "chartDescriptionHintText": "Padoms. Rādīts zem diagrammas",
    "chartType": "Digarammas tips",
    "barChart": "Joslu diagramma",
    "pieChart": "Sektoru diagramma",
    "polarChart": "Polārā diagramma",
    "dataSeriesField": "Datu sērijas lauks",
    "labelField": "Kartes teksta lauks",
    "chartColor": "Diagrammas krāsa",
    "singleColor": "Vienkrāsaina",
    "colorByTheme": "Tēmas krāsa",
    "colorByFieldValue": "Lauka vērtības krāsa",
    "xAxisTitle": "X ass virsraksts",
    "xAxisHintText": "Padoms. X ass virsraksts",
    "yAxisTitle": "Y ass virsraksts",
    "yAxisHintText": "Padoms. Y ass virsraksts",
    "fieldColorLabel": "Kartes teksts",
    "fieldColorColor": "Krāsa",
    "defaultFieldSelectLabel": "Izvēlēties",
    "errMsgFieldValuesNotFound": "Nevar atrast vērtības izvēlētajam laukam",
    "errMsgSectionTitle": "Ievadiet sadaļas virsrakstu",
    "errMsgFieldByValue": "Izvēlieties lauka vērtību",
    "settingTabTitle": "Iestatījums",
    "layoutTabTitle": "Izkārtojums",
    "polarChartSelectFieldsHintText": "Padoms. Atlasiet laukus, lai ģenerētu polāro diagrammu",
    "visibilityText": "Redzamība",
    "fieldNameText": "Lauka nosaukums",
    "aliasNameText": "Aizstājvārds",
    "errMsgPolarFieldsRequired": "Izvēlieties trīs vai vairāk laukus, lai ģenerētu polāro diagrammu",
    "polarChartPolygonFillLabel": "Aizpildīt laukumu",
    "polarChartPolygonFillHintText": "Padoms. Atlasiet izvēles rūtiņu, lai polārajā diagrammā rādītu laukuma aizpildījumu",
    "viewLayoutLabel": "Izkārtojums",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Vispārīgie iestatījumi",
    "locationSymbolLabel": "Grafiskais novietojuma simbols",
    "locationSymbolHintText": "Padoms. Izmanto, lai parādītu adresi un noklikšķinātu uz izvietojuma",
    "refreshIntervalLabel": "Atjaunošanas intervāls",
    "refreshIntervalHintText": "Padoms. Izmanto diagrammu atjaunošanai norādītajā intervālā. Norādiet vērtību no 1 līdz 1440 minūtēm",
    "errMsgRefreshInterval": "Norādiet atjaunošanas intervālu no 0 līdz 1440 minūtēm",
    "symbolPickerPreviewText": "Priekšskatījums:",
    "showToolToSelectLabel": "Iestatīt novietojuma pogu",
    "showToolToSelectHintText": "Uzvedne: nodrošina pogu novietojuma iestatīšanai kartē tā vietā, lai iestatītu novietojumu ikreiz, kad tiek noklikšķināts uz kartes"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Meklēšanas avota iestatījumi",
    "searchSourceSettingTitle": "Meklēšanas avota iestatījumi",
    "searchSourceSettingTitleHintText": "Pievienojiet un konfigurējiet ģeokodēšanas servisus vai elementu slāņus kā meklēšanas avotus. Šie norādītie avoti nosaka, ko var meklēt meklēšanas lodziņā.",
    "addSearchSourceLabel": "Pievienot meklēšanas avotu",
    "featureLayerLabel": "Elementu slānis",
    "geocoderLabel": "Ģeokodētājs",
    "nameTitle": "Vārds/nosaukums",
    "generalSettingLabel": "Vispārīgs iestatījums",
    "allPlaceholderLabel": "Viettura teksts visu vērtību meklēšanai:",
    "allPlaceholderHintText": "Uzvedne: ievadiet tekstu, kas tiks rādīts kā vietturis, kad meklēsit visus slāņus un ģeokodētāju",
    "generalSettingCheckboxLabel": "Rādīt atrastā elementa vai novietojuma uznirstošo logu",
    "countryCode": "Valsts vai reģiona kods(-i)",
    "countryCodeEg": "piemēram, ",
    "countryCodeHint": "Ja šī vērtība tiks atstāta tukša, tiks meklētas visas valstis un reģioni.",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Meklēt tikai pašreizējā kartes pārklājumā",
    "zoomScale": "Mērogmaiņas skala",
    "locatorUrl": "Ģeokodētāja URL",
    "locatorName": "Ģeokodētāja nosaukums",
    "locatorExample": "Piemērs",
    "locatorWarning": "Šī ģeokodēšanas servisa versija netiek atbalstīta. Šis logrīks atbalsta ģeokodēšanas servisa versiju 10.0 un jaunākas versijas.",
    "locatorTips": "Ieteikumi nav pieejami, jo ģeokodēšanas serviss neatbalsta ieteikšanas iespēju.",
    "layerSource": "Slāņa avots",
    "setLayerSource": "Iestatīt slāņa avotu",
    "setGeocoderURL": "Iestatīt ģeokodētāja vietrādi URL",
    "searchLayerTips": "Ieteikumi nav pieejami, jo elementu serviss neatbalsta lappušu numerācijas iespēju.",
    "placeholder": "Viettura teksts",
    "searchFields": "Meklēšanas lauki",
    "displayField": "Rādīt lauku",
    "exactMatch": "Precīza atbilstība",
    "maxSuggestions": "Ieteikumu maksimums",
    "maxResults": "Maks. rezultātu skaits",
    "enableLocalSearch": "Aktivizēt lokālo meklēšanu",
    "minScale": "Minimālo vērtību mērogs",
    "minScaleHint": "Ja kartes mērogs ir lielāks par šo mērogu, tiks lietota lokālā meklēšana",
    "radius": "Rādiuss",
    "radiusHint": "Norāda teritorijas rādiusu ap kartes centru, kas tiek izmantots, lai uzlabotu ģeokodēšanas kandidātu rangu un tādējādi vispirms tiktu atgriezti novietojumam tuvākie kandidāti",
    "meters": "Metri",
    "setSearchFields": "Iestatīt meklēšanas laukus",
    "set": "Uzstādīt",
    "fieldName": "Vārds/nosaukums",
    "invalidUrlTip": "URL ${URL} ir nederīgs vai tam nevar piekļūt."
  }
});