define({
  "_widgetLabel": "クエリ",
  "executeQueryTip": "以下のタスク アイテムのいずれかをクリックしてクエリを実行します。",
  "invalidConfig": "構成が無効です。クエリ設定ページで構成を修正してください。",
  "queryParams": "オプション",
  "parameters": "オプション",
  "queries": "クエリ",
  "apply": "適用",
  "queryResults": "結果",
  "clear": "消去",
  "noResults": "フィーチャは見つかりませんでした。",
  "queryError": "クエリが失敗しました",
  "numberFound": "検出されたフィーチャの数",
  "mapExtentTip": "結果を現在のマップ エリアに制限します。",
  "noValue": "値がありません",
  "and": "から",
  "stringOperatorIs": "に等しい",
  "stringOperatorIsNot": "に等しくない",
  "stringOperatorStartsWith": "で始まる",
  "stringOperatorEndsWith": "で終わる",
  "stringOperatorContains": "を含む",
  "stringOperatorDoesNotContain": "を含まない",
  "stringOperatorIsBlank": "空である",
  "stringOperatorIsNotBlank": "空でない",
  "dateOperatorIsOn": "である",
  "dateOperatorIsNotOn": "でない",
  "dateOperatorIsBefore": "より前である",
  "dateOperatorIsAfter": "より後である",
  "dateOperatorDays": "日中",
  "dateOperatorWeeks": "週",
  "dateOperatorMonths": "月",
  "dateOperatorInTheLast": "以内である",
  "dateOperatorNotInTheLast": "以内でない",
  "dateOperatorIsBetween": "の間にある",
  "dateOperatorIsNotBetween": "の間にない",
  "dateOperatorIsBlank": "空である",
  "dateOperatorIsNotBlank": "空でない",
  "numberOperatorIs": "に等しい",
  "numberOperatorIsNot": "に等しくない",
  "numberOperatorIsAtLeast": "以上",
  "numberOperatorIsLessThan": "より小さい",
  "numberOperatorIsAtMost": "以下",
  "numberOperatorIsGreaterThan": "より大きい",
  "numberOperatorIsBetween": "の間にある",
  "numberOperatorIsNotBetween": "の間にない",
  "numberOperatorIsBlank": "空である",
  "numberOperatorIsNotBlank": "空でない",
  "operationalLayerTip": "操作レイヤーとして結果を追加",
  "queryResult": "クエリ結果",
  "specifyParamsTip": "このタスクのパラメーターを指定",
  "useSpatialFilter": "空間フィルターを使用してフィーチャを制限",
  "useCurrentMapExtent": "現在のマップ エリアと交差するフィーチャのみ",
  "drawGraphicOnMap": "ユーザー指定エリアと交差するフィーチャのみ",
  "specifySpatialFilterMsg": "このタスクの空間フィルターを指定してください。",
  "clearResults": "結果の消去",
  "operationalTip": "このオプションをオンにすると、結果は、\"${clearResults}\" ボタンがクリックされるまでマップ上に維持されます。",
  "noneQueryTip": "このウィジェット用のクエリ タスクが構成されていません。",
  "noPermissionsMsg": "このサービスにアクセスできる権限がありません。",
  "attributesFromRelationship": "関連テーブルの属性",
  "tasks": "タスク",
  "applySpatialFilterToLimitResults": "空間フィルターを適用して結果を制限する",
  "useCurrentExtentTip": "現在のマップ範囲に含まれるフィーチャのみを返す",
  "useDrawGraphicTip": "マップに描画された図形と交差するフィーチャのみを返す",
  "useFeaturesTip": "別のレイヤー内のフィーチャとの空間リレーションシップのあるフィーチャのみを返す",
  "noSpatialLimitTip": "マップの全範囲に含まれるフィーチャを返す",
  "applySearchDistance": "検索距離の適用",
  "spatialRelationship": "空間リレーションシップ",
  "relatedLayer": "関連レイヤー",
  "bufferDistance": "バッファー距離",
  "miles": "マイル",
  "kilometers": "キロメートル",
  "feet": "フィート",
  "meters": "メートル",
  "yards": "ヤード",
  "nauticalMiles": "海里",
  "back": "戻る",
  "execute": "実行",
  "zoomTo": "ズーム",
  "openAttributeTable": "属性テーブルの表示",
  "noResult": "結果がありません。",
  "noTask": "タスクがありません。",
  "removeThisResult": "この結果を削除",
  "attributeCriteira": "属性条件",
  "spatialFilter": "空間フィルター",
  "value": "値",
  "noAttributeSpatialFilterTip": "フィルターが定義されていません。すべてのフィーチャが返されます。",
  "showAllRelatedRecords": "すべての関連レコードを表示",
  "changeSymbol": "シンボルの変更",
  "queryCriteira": "クエリ条件",
  "customQuery": "カスタム クエリ",
  "layer": "レイヤー",
  "createCustomQuery": "カスタム クエリを作成します。"
});