define({
  "add": "Lisää uusi napsauttamalla",
  "title": "Otsikko",
  "placeholderBookmarkName": "Kirjanmerkin nimi",
  "ok": "OK",
  "cancel": "Peruuta",
  "warning": "Viimeistele muokkaus.",
  "edit": "Muokkaa kirjanmerkkiä",
  "errorNameExist": "Kirjanmerkki on olemassa!",
  "errorNameNull": "Kirjanmerkin nimi on virheellinen!",
  "addBookmark": "Luo uusi",
  "thumbnail": "Pikkukuva",
  "thumbnailHint": "Päivitä napsauttamalla kuvaa",
  "displayBookmarksAs": "Näytä kirjanmerkit muodossa",
  "cards": "Kortit",
  "list": "Luettelo",
  "cardsTips": "Korttinäkymä",
  "listTips": "Luettelonäkymä",
  "makeAsDefault": "Määritä oletusarvoksi",
  "default": "Oletusarvo",
  "editable": "Salli kirjanmerkkien lisäys pienoisohjelmaan.",
  "alwaysSync": "Näytä kirjanmerkit web-kartasta",
  "configCustom": "Näytä mukautetut kirjanmerkit",
  "import": "Tuo",
  "create": "Luo",
  "importTitle": "Tuo kirjanmerkit",
  "importFromWeb": "Tuo kirjanmerkit nykyisestä web-kartasta",
  "selectAll": "Valitse kaikki",
  "noBookmarkInConfig": "Lisää kirjanmerkkejä valitsemalla Tuo tai Luo uusi.",
  "noBookmarkInWebMap": "Karttaan ei ole määritetty kirjanmerkkejä.",
  "extent": "Laajuus",
  "saveExtent": "Tallenna kartan laajuus tähän kirjanmerkkiin",
  "savelayers": "Tallenna karttatason näkyvyys",
  "withVisibility": "Karttatason näkyvyyden kanssa",
  "bookmark": "Kirjanmerkki",
  "addBtn": "Lisää",
  "deleteBtn": "Poista",
  "editBtn": "Muokkaa",
  "dragReorderTip": "Järjestä uudelleen vetämällä ja pudottamalla",
  "deleteBtnTip": "Poista kirjanmerkki",
  "editBtnTip": "Muokkaa kirjanmerkkiä"
});