define({
  "serviceUrl": "Ορισμός URL υπηρεσίας:",
  "minIntSpacingLabel": "Ελάχιστο μέγεθος πλέγματος",
  "lineOpacityLabel": "Διαφάνεια γραμμής",
  "labelOpacityLabel": "Διαφάνεια ετικέτας",
  "centerLabelOpacityLabel": "Διαφάνεια κεντρικής ετικέτας",
  "gridZonePlacementLabel": "Τοποθέτηση ετικέτας ζώνης πλέγματος",
  "verticalLineLabels": "Ετικέτες κατακόρυφων γραμμών",
  "styleHeaderLabel": "Στυλ",
  "indexHeaderLabel": "Στοιχείο πλέγματος",
  "colorHeaderLabel": "Χρώμα",
  "fontSizeHeaderLabel": "Μέγεθος γραμματοσειράς",
  "lineWidthHeaderLabel": "Πλάτος γραμμής",
  "horizontalLabel": "Οριζόντια",
  "verticalLabel": "Κατακόρυφα",
  "upperLeftLabel": "Πάνω αριστερά",
  "upperRightLabel": "Πάνω δεξιά",
  "lowerLeftLabel": "Κάτω αριστερά",
  "lowerRightLabel": "Κάτω δεξιά",
  "centerLabel": "Κέντρο",
  "errorMessage": "Η σελίδα διαμόρφωσης των ρυθμίσεων περιέχει σφάλματα. Διορθώστε τα πριν την αποθηκεύσετε.",
  "checkBoxLabel": "Παρουσίαση πλέγματος κατά το κλείσιμο του widget",
  "checkBoxLabelDashboard": "Παρουσίαση πλέγματος",
  "gzd": "Προσδιοριστικό ζώνης πλέγματος (GZD)",
  "gsid": "Αναγνώριση τετραγώνων 100.000 μέτρων στο πλέγμα (GSID)",
  "grid10k": "Γραμμές 10.000 μέτρων στο πλέγμα",
  "grid1k": "Γραμμές 1.000 μέτρων στο πλέγμα",
  "grid100m": "Γραμμές 100 μέτρων στο πλέγμα",
  "grid10m": "Γραμμές 10 μέτρων στο πλέγμα",
  "switchBasemap": "Αλλαγή υποβάθρου"
});