define({
  "chartSettingLabel": "Configuración de gráfico",
  "addNewLabel": "Agregar nuevo",
  "generalSettingLabel": "Configuración general",
  "searchSourceSettingLabel": "Configuración de origen de búsqueda",
  "layerChooser": {
    "title": "Seleccionar capa para gráfico",
    "selectPolygonLayerLabel": "Seleccionar capa",
    "selectPolygonLayerHintText": "Sugerencia: si vas a configurar varios gráficos, las capas tienen que tener el mismo tipo de geometría",
    "selectRelatedTableLayerLabel": "Seleccionar tabla relacionada con capa",
    "selectRelatedTableLayerHintText": "Sugerencia: solo se muestran las tablas que tienen campos numéricos",
    "errorInSelectingPolygonLayer": "Selecciona una capa que tenga una capa de puntos relacionada.",
    "errorInSelectingRelatedLayer": "Selecciona una tabla o capa válida relacionada con la capa.",
    "polygonLayerNotHavingRelationships": "La capa seleccionada no tiene ninguna tabla o capa relacionada."
  },
  "ChartSetting": {
    "sectionTitle": "Título de la sección",
    "sectionTitleHintText": "Sugerencia: se muestra en el título del encabezado de la sección",
    "chartTitle": "Título de gráfico",
    "chartTitleHintText": "Sugerencia: se muestra centrado en la parte superior del gráfico",
    "chartDescription": "Descripción",
    "chartDescriptionHintText": "Sugerencia: se muestra debajo del gráfico",
    "chartType": "Tipo de gráfico",
    "barChart": "Gráfico de barras",
    "pieChart": "Gráfico circular",
    "polarChart": "Gráfico polar",
    "dataSeriesField": "Campo de serie de datos",
    "labelField": "Campo de etiquetado",
    "chartColor": "Color de gráfico",
    "singleColor": "Color único",
    "colorByTheme": "Color por tema",
    "colorByFieldValue": "Color por valor de campo",
    "xAxisTitle": "Título de eje x",
    "xAxisHintText": "Sugerencia: título del eje x",
    "yAxisTitle": "Título de eje y",
    "yAxisHintText": "Sugerencia: título del eje y",
    "fieldColorLabel": "Etiqueta",
    "fieldColorColor": "Color",
    "defaultFieldSelectLabel": "Seleccionar",
    "errMsgFieldValuesNotFound": "No se pueden encontrar valores para el campo seleccionado",
    "errMsgSectionTitle": "Introduce el título de la sección",
    "errMsgFieldByValue": "Selecciona el valor del campo",
    "settingTabTitle": "Configuración",
    "layoutTabTitle": "Diseño",
    "polarChartSelectFieldsHintText": "Sugerencia: seleccione los campos para generar el gráfico polar",
    "visibilityText": "Visibilidad",
    "fieldNameText": "Nombre de campo",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Seleccione tres o más campos para generar el gráfico polar",
    "polarChartPolygonFillLabel": "Rellenar polígono",
    "polarChartPolygonFillHintText": "Sugerencia: active la casilla de verificación para mostrar el relleno de polígonos en el gráfico polar",
    "viewLayoutLabel": "Diseño",
    "ThemeSelector": {
      "themeAdobebricks": "LadrillosAdobe",
      "themeAlgae": "Algas",
      "themeBahamation": "Bahamas",
      "themeBlueDusk": "OcasoAzul",
      "themeCubanShirts": "CamisasCubanas",
      "themeDesert": "Desierto",
      "themeDistinctive": "Distintivo",
      "themeDollar": "Dólar",
      "themeGrasshopper": "Saltamontes",
      "themeGrasslands": "Praderas",
      "themeGreySkies": "CielosGrises",
      "themeHarmony": "Armonía",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "BonitoMiami",
      "themeMinty": "Mentolado",
      "themePurpleRain": "LluviaMorada",
      "themeRoyalPurples": "PúrpurasReales",
      "themeSageToLime": "SalviaACal",
      "themeTufte": "Mechón",
      "themeWatersEdge": "BordeAgua",
      "themeWetlandText": "Humedal",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Configuración general",
    "locationSymbolLabel": "Símbolo de ubicación de gráfico",
    "locationSymbolHintText": "Sugerencia: se utiliza para visualizar el símbolo para la dirección y ubicación en la que se hace clic",
    "refreshIntervalLabel": "Intervalo de actualización",
    "refreshIntervalHintText": "Sugerencia: se utiliza para actualizar los gráficos según este intervalo. Especifica un valor entre 1 y 1440 minutos",
    "errMsgRefreshInterval": "Especifica el intervalo de actualización entre 0 y 1440 minutos.",
    "symbolPickerPreviewText": "Vista previa:",
    "showToolToSelectLabel": "Seleccionar botón de ubicación",
    "showToolToSelectHintText": "Sugerencia: proporciona un botón para establecer una ubicación en el mapa en vez de establecer siempre la ubicación cuando se ha hecho clic en el mapa"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Configuración de fuente de búsqueda",
    "searchSourceSettingTitle": "Configuración de fuente de búsqueda",
    "searchSourceSettingTitleHintText": "Agrega y configura servicios de geocodificación o capas de entidades como fuentes de búsqueda. Estas fuentes especificadas determinan qué se puede buscar en el cuadro de búsqueda",
    "addSearchSourceLabel": "Agregar origen de búsqueda",
    "featureLayerLabel": "Capa de entidades",
    "geocoderLabel": "Geocodificador",
    "nameTitle": "Nombre",
    "generalSettingLabel": "Configuración general",
    "allPlaceholderLabel": "Texto del marcador de posición para buscar en todo:",
    "allPlaceholderHintText": "Sugerencia: escriba el texto que se va a mostrar como marcador de posición mientras busca todas las capas y el geocodificador",
    "generalSettingCheckboxLabel": "Mostrar ventana emergente de la entidad o la ubicación encontrada",
    "countryCode": "Código(s) de país o región",
    "countryCodeEg": "p. ej., ",
    "countryCodeHint": "Si se deja este valor en blanco, se buscará en todos los países y regiones",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Buscar solo en la extensión de mapa actual",
    "zoomScale": "Aplicar zoom a escala",
    "locatorUrl": "Dirección URL del geocodificador",
    "locatorName": "Nombre del geocodificador",
    "locatorExample": "Ejemplo",
    "locatorWarning": "No se admite esta versión del servicio de geocodificación. El widget admite servicios de geocodificación 10.0 y superiores.",
    "locatorTips": "No hay sugerencias disponibles porque el servicio de geocodificación no admite la opción de sugerencias.",
    "layerSource": "Origen de capa",
    "setLayerSource": "Establecer origen de capa",
    "setGeocoderURL": "Establecer dirección URL de geocodificador",
    "searchLayerTips": "No hay sugerencias disponibles porque el servicio de entidades no admite la opción de paginación.",
    "placeholder": "Texto del marcador de posición",
    "searchFields": "Campos de búsqueda",
    "displayField": "Mostrar campo",
    "exactMatch": "Coincidencia exacta",
    "maxSuggestions": "Máximo de sugerencias",
    "maxResults": "Resultados máximos",
    "enableLocalSearch": "Habilitar búsqueda local",
    "minScale": "Escala Mínima",
    "minScaleHint": "Si la escala del mapa es mayor que esta escala, se aplicará la búsqueda local",
    "radius": "Radio",
    "radiusHint": "Permite especificar el radio de un área alrededor del centro del mapa actual que se utilizará para mejorar la clasificación de los candidatos de geocodificación a fin de que se devuelvan primero aquellos más cercanos a la ubicación",
    "meters": "Metros",
    "setSearchFields": "Establecer campos de búsqueda",
    "set": "Establecer",
    "fieldName": "Nombre",
    "invalidUrlTip": "No se puede acceder a la dirección URL ${URL} o bien no es válida."
  }
});