define({
  "enableUndoRedo": "अनडू/रीडू को सक्षम करें",
  "toolbarVisible": "दृश्यमान टूलबार",
  "toolbarOptions": "टूलबार विकल्प",
  "mergeVisible": "मिलाएँ",
  "cutVisible": "काटें",
  "reshapeVisible": "पुनःआकार दें",
  "back": "पीछे जाएँ",
  "label": "लेयर",
  "edit": "संशोधन योग्य",
  "update": "Geometry अपडेट को अक्षम करें",
  "fields": "फ़ील्ड्स",
  "actions": "कार्रवाइयाँ",
  "editpageName": "नाम",
  "editpageAlias": "उपनाम",
  "editpageVisible": "दृश्य",
  "editpageEditable": "संशोधन योग्य",
  "noLayers": "संशोधन योग्य कोई फीचर लेयर उपलब्ध नहीं है",
  "configureFields": "लेयर फ़ील्ड कॉन्फ़िगर करें",
  "useFilterEdit": "फीचर टेम्पलेट फिल्टर का प्रयोग करें",
  "display": "प्रदर्शित करें",
  "autoApplyEditWhenGeometryIsMoved": "जब geometry मूव करे तो संपादन स्वचालित रूप से लागू करें",
  "snappingTolerance": "पिक्सल में स्नैपिंग सीमा सेट करें",
  "popupTolerance": "पिक्सल में विशेषता संपादन पॉपअप की सीमा सेट करें",
  "stickyMoveTolerance": "पिक्सल में स्टिकी मूव सीमा सेट करें",
  "usingSaveButton": "सहेजें बटन पर क्लिक करने से पहले विशेषताओं पर संपादन लागू न करें"
});