define({
  "_widgetLabel": "Vaicājums",
  "executeQueryTip": "Noklikšķiet uz kādas no tālāk esošajām uzdevuma vienībām, lai izpildītu vaicājumu.",
  "invalidConfig": "Nederīga konfigurācija. Izmantojiet vaicājumu iestatījumu lapu, lai iegūtu pareizu konfigurāciju.",
  "queryParams": "Opcijas",
  "parameters": "OPCIJAS",
  "queries": "VAICĀJUMI",
  "apply": "Lietot",
  "queryResults": "Rezultāti",
  "clear": "Notīrīt",
  "noResults": "Nav atrasts neviens elements.",
  "queryError": "Vaicājums neizdevās.",
  "numberFound": "Atrasto elementu skaits",
  "mapExtentTip": "Ierobežojiet rezultātus līdz pašreizējam kartes apgabalam.",
  "noValue": "Nav vērtības",
  "and": "un",
  "stringOperatorIs": "ir",
  "stringOperatorIsNot": "nav",
  "stringOperatorStartsWith": "sākas ar",
  "stringOperatorEndsWith": "beidzas ar",
  "stringOperatorContains": "ietver",
  "stringOperatorDoesNotContain": "neietver",
  "stringOperatorIsBlank": "ir tukšs",
  "stringOperatorIsNotBlank": "nav tukšs",
  "dateOperatorIsOn": "ir šajā datumā",
  "dateOperatorIsNotOn": "nav šajā datumā",
  "dateOperatorIsBefore": "ir pirms",
  "dateOperatorIsAfter": "ir pēc",
  "dateOperatorDays": "dienas",
  "dateOperatorWeeks": "nedēļas",
  "dateOperatorMonths": "mēneši",
  "dateOperatorInTheLast": "pēdējā",
  "dateOperatorNotInTheLast": "nav pēdējā",
  "dateOperatorIsBetween": "ir starp",
  "dateOperatorIsNotBetween": "nav starp",
  "dateOperatorIsBlank": "ir tukšs",
  "dateOperatorIsNotBlank": "nav tukšs",
  "numberOperatorIs": "ir",
  "numberOperatorIsNot": "nav",
  "numberOperatorIsAtLeast": "ir vismaz",
  "numberOperatorIsLessThan": "ir mazāks nekā",
  "numberOperatorIsAtMost": "ir visvairāk",
  "numberOperatorIsGreaterThan": "ir lielāks nekā",
  "numberOperatorIsBetween": "ir starp",
  "numberOperatorIsNotBetween": "nav starp",
  "numberOperatorIsBlank": "ir tukšs",
  "numberOperatorIsNotBlank": "nav tukšs",
  "operationalLayerTip": "Pievienot rezultātu kā darbības slāni",
  "queryResult": "Vaicājuma rezultāts",
  "specifyParamsTip": "Norādiet šī uzdevuma parametrus",
  "useSpatialFilter": "Izmantot telpisko filtru, lai ierobežotu elementus",
  "useCurrentMapExtent": "Tikai elementi, kas krustojas ar pašreizējās kartes pārklājumu",
  "drawGraphicOnMap": "Tikai elementi, kas krustojas ar lietotāja definēto teritoriju",
  "specifySpatialFilterMsg": "Norādiet šī uzdevuma telpisko filtru.",
  "clearResults": "Notīrīt rezultātus",
  "operationalTip": "Ja šī opcija ir atzīmēta, rezultāti paliek kartē, līdz tiek noklikšķināts uz pogas \"${clearResults}\".",
  "noneQueryTip": "Šim logrīkam nav konfigurēts neviens vaicājuma uzdevums.",
  "noPermissionsMsg": "Jums nav atļauju piekļūt šim pakalpojumam.",
  "attributesFromRelationship": "Atribūti no saistītās tabulas",
  "tasks": "Uzdevumi",
  "applySpatialFilterToLimitResults": "Lietot telpisko filtru, lai ierobežotu rezultātus",
  "useCurrentExtentTip": "Atgriezt elementus tikai pašreizējā kartes pārklājumā",
  "useDrawGraphicTip": "Atgriezt tikai elementus, kas šķērso kartē uzzīmēto formu",
  "useFeaturesTip": "Atgriezt tikai tos elementus, kuriem ir telpiskās attiecības ar elementiem citā slānī",
  "noSpatialLimitTip": "Atgriezt elementus pilnā kartes pārklājumā",
  "applySearchDistance": "Lietot meklēšanas attālumu",
  "spatialRelationship": "Telpiskās attiecības",
  "relatedLayer": "Saistītais slānis",
  "bufferDistance": "Buferzonas attālums",
  "miles": "Jūdzes",
  "kilometers": "Kilometri",
  "feet": "Pēdas",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Jūras jūdzes",
  "back": "Atpakaļ",
  "execute": "Izpildīt",
  "zoomTo": "Pietuvināt",
  "openAttributeTable": "Skatīt atribūtu tabulā",
  "noResult": "Nav rezultāta.",
  "noTask": "Nav uzdevuma.",
  "removeThisResult": "Noņemt šo rezultātu",
  "attributeCriteira": "Atribūtu kritēriji",
  "spatialFilter": "Telpiskais filtrs",
  "value": "VĒRTĪBA",
  "noAttributeSpatialFilterTip": "Nav definēts neviens filtrs. Visi elementi tiks atgriezti.",
  "showAllRelatedRecords": "Rādīt visus saistītos ierakstus",
  "changeSymbol": "Mainīt simbolu",
  "queryCriteira": "Vaicājuma kritēriji",
  "customQuery": "Pielāgots vaicājums",
  "layer": "Slānis",
  "createCustomQuery": "Izveidojiet pielāgotu vaicājumu."
});