define({
  "_widgetLabel": "Grafisk rutenettreferanse",
  "newGRGFromAreaButtonLabel": "Definer et rutenett ut fra et område",
  "newGRGFromPointButtonLabel": "Definer et rutenett ut fra et punkt",
  "newGRGFromAreaTitle": "Definer et rutenett ut fra et område",
  "newGRGFromPointTitle": "Definer et rutenett ut fra et punkt",
  "newGRGBySizeButtonLabel": "Etter dimensjon",
  "newGRGFromRefSystemButtonLabel": "Etter referansesystem",
  "newGRGByTimeLabel": "Etter tid og hastighet",
  "newGRGFromNonStandardButtonLabel": "Definer ikke-standard rutenett",
  "newGRGAreaBySizeTitle": "GRG fra et område etter dimensjon",
  "newGRGAreaBySizeDefineAreaLabel": "GRG-område",
  "addGRGAreaPolygonToolTip": "Tegn GRG-område ved hjelp av polygon",
  "addGRGAreaExtentToolTip": "Tegn GRG-område ved hjelp av utstrekning",
  "rotation": "Rutenettrotasjon",
  "numberRowsColumnsLabel": "Definer antall rader og kolonner",
  "newGRGAreaByRefSystemTitle": "GRG fra et område etter referansesystem",
  "gridSize": "Rutenettstørrelse",
  "UTMZoneandBand": "Rutenettsone",
  "100000m": "100000 meter",
  "10000m": "10000 meter",
  "1000m": "1000 meter",
  "100m": "100 meter",
  "10m": "10 meter",
  "clipGrid": "Klipp rutenett til GRG-område",
  "newGRGAreaFromNonStandardTitle": "Ny NRG",
  "newGRGPointBySizeTitle": "GRG fra punkt etter dimensjon",
  "newGRGPointByRefSystemTitle": "GRG fra punkt etter referansesystem",
  "newGRGPointByTimeTitle": "GRG fra punkt ved hjelp av tid og hastighet",
  "time": "Tid",
  "rate": "Hastighet",
  "hours": "Timer",
  "minutes": "Minutter",
  "seconds": "Sekunder",
  "ftPerSec": "Fot/sekund",
  "ftPerHour": "Fot/time",
  "kmPerSec": "Kilometer / sekund",
  "kmPerHour": "Kilometer / time",
  "mPerSec": "Meter / sekund",
  "mPerHour": "Meter / time",
  "miPerSec": "Miles / sekund",
  "miPerHour": "Miles / time",
  "nMPerSec": "Nautiske mil / sekund",
  "nMPerHour": "Nautiske mil / time",
  "settingsTitle": "Innstillinger",
  "labelSettingsLabel": "Etikettinnstillinger",
  "labelSettingsButtonLabel": "Konfigurer etikettinnstillinger",
  "gridSettingsLabel": "Rutenettinnstillinger",
  "gridSettingsButtonLabel": "Konfigurer rutenettinnstillinger",
  "transparency": "Gjennomsiktighet",
  "labelStyle": "Etikettstil",
  "font": "Skrifttype",
  "textSize": "Tekststørrelse",
  "textColor": "Tekstfarge",
  "halo": "Glorie",
  "show": "Vis",
  "lockSettings": "Innstillingene er låst av programeieren",
  "gridSettings": {
    "cellShape": "Celleform",
    "cellUnits": "Celleenheter",
    "cellOutline": "Innstillinger for celleomriss",
    "cellFill": "Innstillinger for cellefyll",
    "gridReferenceSystem": "Referansesystem",
    "gridDatum": "Datum: WGS84",
    "labelStartPosition": "Etikettopprinnelse",
    "labelType": "Etiketttype",
    "labelDirection": "Etikettretning",
    "gridOrigin": "Rutenettopprinnelse",
    "default": "Rektangel",
    "hexagon": "Heksagon",
    "miles": "Miles",
    "kilometers": "Kilometer",
    "feet": "Fot",
    "meters": "Meter",
    "yards": "Yard",
    "nautical-miles": "Nautiske mil",
    "lowerLeft": "Nedre-venstre",
    "lowerRight": "Nedre-høyre",
    "upperLeft": "Øvre-venstre",
    "upperRight": "Øvre-høyre",
    "center": "Senter",
    "alphaNumeric": "Alfa-numerisk",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Numerisk",
    "horizontal": "Vannrett",
    "vertical": "Loddrett",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Vis etiketter"
  },
  "publishTitle": "Publiser GRG til portal",
  "publishGRGBtn": "Publiser",
  "GRGLayerName": "Publisert GRG-lagnavn",
  "invalidGRGLayerName": "Lagnavn kan bare inneholde alfanumeriske tegn og understrekingstegn",
  "missingGRGLayerName": "Du må oppgi et navn for GRG",
  "publishingFailedLayerExists": "Publiseringen mislyktes: Du har allerede en geoobjektstjeneste med navnet {0}. Velg et annet navn.",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opprett tjeneste {0}",
  "unableToCreate": "Kan ikke opprette: {0}",
  "addToDefinition": "Legg til definisjon: {0}",
  "successfullyPublished": "Vellykket publisering av weblag{0}Administrer weblaget",
  "userRole": "Kan ikke opprette tjeneste fordi brukeren ikke har tillatelser",
  "createGRGBtn": "Opprett GRG",
  "clearGRGBtn": "Tøm",
  "labelFormat": "Etikettformat",
  "helpIconTooltip": "Z: ID for rutenettsone (GZD)\nS: 100000 meter identifikasjon av rutenettsrute (GSID)\nX: Forandret østlig lengde (X-koordinat)\nY: Forandret nordlig bredde (Y-koordinat)\n\nEksempel:\nZSXY er 15SWC8081751205\nZS X,Y er 15SWC 80817,51205",
  "addPointToolTip": "Legg til GRG-opprinnelse",
  "cellWidth": "Cellebredde (x)",
  "cellHeight": "Cellehøyde (y)",
  "invalidNumberMessage": "Den angitte verdien er ugyldig",
  "invalidRangeMessage": "Verdien må være større enn 0",
  "gridAngleInvalidRangeMessage": "Verdien må være mellom -89,9 og 89,9",
  "formatIconTooltip": "Formater inndata",
  "coordInputLabel": "GRG-opprinnelse (DD)",
  "setCoordFormat": "Angi koordinatformatstreng",
  "prefixNumbers": "Legg til prefikset \"+/-\" for positive og negative tall",
  "cancelBtn": "Avbryt",
  "applyBtn": "Bruk",
  "comfirmInputNotation": "Bekreft inndatanotasjon",
  "notationsMatch": "notasjoner samsvarer med inndataene. Bekreft hvilke du vil bruke:",
  "numberOfCellsHorizontal": "# vannrette celler",
  "numberOfCellsVertical": "# loddrette celler",
  "gridAngle": "Rutenettrotasjon",
  "tooManyCellsErrorMessage": "Du prøver å opprette et rutenett som består av over 2000 celler. Du bør redusere antallet celler som opprettes, ved å endre rutenettstørrelsen eller rutenettområdet.",
  "missingParametersMessage": "<p>Skjemaet for å opprette GRG har manglende eller ugyldige parametere. Kontroller at:</p><ul><li>Det er tegnet opp et GRG-område.</li><li>Det er angitt gyldige verdier for cellebredde og cellehøyde.</li></ul>",
  "missingOriginParametersMessage": "<p>Skjemaet for å opprette GRG har manglende eller ugyldige parametere. Kontroller at:</p><ul><li>Det er angitt en GRG-opprinnelse.</li><li>Det er angitt gyldige verdier for tid, hastighet og vinkel.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>Skjemaet for å opprette GRG har manglende eller ugyldige parametere. Kontroller at det er angitt gyldige verdier for cellebredde og cellehøyde.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>Skjemaet for å opprette GRG har manglende eller ugyldige parametere. Kontroller at det er angitt gyldige verdier for antall celler vannrett og loddrett.</p>",
  "drawPointToolTip": "Klikk for å legge til GRG-opprinnelsespunkt",
  "missingLayerNameMessage": "Du må angi et gyldig lagnavn før du kan publisere",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Sjekk inndataene.",
  "grgPolarRegionError": "GRG-utstrekningen ligger innenfor et polarområde. Celler som havner innenfor polarområdet, blir ikke opprettet.",
  "grgPolarOriginError": "GRG-opprinnelsespunktet kan ikke være i et polarområde når en GRG opprettes av referansesystemet.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desimalgrader - Breddegrad/lengdegrad",
  "DDLongLatNotation": "Desimalgrader - Lengdegrad/breddegrad",
  "DDMLatLongNotation": "Grader og desimalminutter - Breddegrad/lengdegrad",
  "DDMLongLatNotation": "Grader og desimalminutter - Lengdegrad/breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/lengdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Lengdegrad/breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Båndbokstav",
  "UTMHemNotation": "UTM - Halvkule (N/S)"
});