define({
  "serviceUrl": "Määritä palvelun URL-osoite:",
  "minIntSpacingLabel": "Ruudukon vähimmäiskoko",
  "lineOpacityLabel": "Viivan peittävyys",
  "labelOpacityLabel": "Tunnustekstin peittävyys",
  "centerLabelOpacityLabel": "Keskitunnustekstin peittävyys",
  "gridZonePlacementLabel": "Ruudukon alueen tunnustekstin paikka",
  "verticalLineLabels": "Pystyviivan tunnustekstit",
  "styleHeaderLabel": "Tyyli",
  "indexHeaderLabel": "Ruudukkokomponentti",
  "colorHeaderLabel": "Väri",
  "fontSizeHeaderLabel": "Fontin koko",
  "lineWidthHeaderLabel": "Viivan leveys",
  "horizontalLabel": "Vaaka",
  "verticalLabel": "Pysty",
  "upperLeftLabel": "Ylhäällä vasemmalla",
  "upperRightLabel": "Ylhäällä oikealla",
  "lowerLeftLabel": "Alhaalla vasemmalla",
  "lowerRightLabel": "Alhaalla oikealla",
  "centerLabel": "Keskitä",
  "errorMessage": "Määrityssivu sisältää virheitä. Korjaa ennen käyttöä.",
  "checkBoxLabel": "Näytä ruudukko, kun pienoisohjelma suljetaan",
  "checkBoxLabelDashboard": "Näytä ruudukko",
  "gzd": "Ruudukon vyöhykemääritys (GZD)",
  "gsid": "Ruudukon 100 000 metrin neliön tunnus (GSID)",
  "grid10k": "10 000 metrin ruudukkoviivat",
  "grid1k": "1 000 metrin ruudukkoviivat",
  "grid100m": "100 metrin ruudukkoviivat",
  "grid10m": "10 metrin ruudukkoviivat",
  "switchBasemap": "Vaihda taustakartta"
});