define({
  "_widgetLabel": "Conhecimento Operacional",
  "locate_incident": "Localizar Incidente",
  "reverse_geocoded_address": "Endereço mais Próximo",
  "reverse_geocoded_error": "Não disponível",
  "now": "AGORA",
  "wind": "VENTO",
  "SUN": "DOM",
  "MON": "SEG",
  "TUE": "TER",
  "WED": "QUA",
  "THU": "QUI",
  "FRI": "SEX",
  "SAT": "SÁB",
  "actionLabel": "Definir Localização",
  "drawPoint": "Desenhar ponto",
  "drawLine": "Desenhar linha",
  "drawPolygon": "Desenhar polígono",
  "saveIncident": "Guardar",
  "clearIncident": "Começar Novamente",
  "noFeaturesFound": "Não foram encontrados nenhuns elementos.",
  "downloadCSV": "Descarregar",
  "sum": "Soma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Média",
  "count": "CONTAGEM",
  "area": "ÁREA",
  "length": "COMPRIMENTO",
  "update_btn": "Concluído",
  "delete_btn": "Eliminar",
  "get_directions": "Obter Direcções",
  "incident": "Incidente",
  "incidents": "Incidentes",
  "buffer": "Buffer",
  "buffers": "Buffers",
  "weather": "Meteorologia",
  "poweredBy": "Fornecido por",
  "_featureAction_ActionLabel": "Definir Localização",
  "_featureAction_AddRemoveActionLabel": "Adicionar/Remover Localização",
  "snapshot": "Pasta SnapShot criada pela id de Aplicação:",
  "user_credentials": "O utilizador não possui privilégios válidos.",
  "notPolySnapShot": "Por favor, especifique uma distância de buffer antes de criar um snapshot.",
  "notPolyReport": "Não existem resultados válidos para adicionar ao relatório.",
  "notValidDownload": "Não existem quaisquer resultados para transferir.",
  "of_append": "de",
  "layer_append": "camada",
  "downloadAll": "Transferir todos",
  "createSnapshot": "Criar snapshot",
  "createReport": "Criar relatório",
  "calculated_results": "Informações Resumidas",
  "closest": "Elemento Mais Próximo",
  "proximity": "Proximidade",
  "summary": "Resumo",
  "groupedSummary": "Contagens Agrupadas",
  "_count": "Contagem",
  "approximate": "aproximado",
  "snapshot_name": "Definir Propriedades de Imagem Instantânea",
  "report_name": "Definir Propriedades de Relatórios",
  "invalid_snapshot_name": "Nome de snapshot inválido.",
  "invalid_report_name": "Título de relatório inválido.",
  "orientation": "Orientação",
  "pageSize": "Tamanho de Página",
  "comments": "Comentários",
  "choose_group": "Grupos",
  "forecast": "Previsão",
  "select_group": "Selecionar Grupo",
  "select_group_instruction": "A imagem instantânea será criada e partilhada com o grupo selecionado",
  "information_append": " Informações",
  "distance": "DISTÂNCIA",
  "buffer_invalid": "Introduza um número válido entre ${min} e ${max}"
});