define({
  "tabs_section_Label": "File",
  "addTab": "Adăugare filă",
  "layerName": "Strat tematic",
  "layerType": "Tip analiză",
  "layerLabel": "Etichetă",
  "actions": "Acţiuni",
  "closest": "Cel mai apropiat obiect spaţial",
  "proximity": "Proximitate",
  "summary": "Rezumat",
  "select_lbl": "-- Selectare --",
  "general_setting_Label": "Setări generale",
  "units_text_lbl": "Unităţi distanţă",
  "maximum_distance_lbl": "Distanţă maximă până la cel mai apropiat obiect spaţial",
  "buffer_text_lbl": "Etichetă buffer",
  "buffer_lbl": "Distanţă buffer",
  "buffer_max_lbl": "Distanţă maximă buffer",
  "buffer_min_lbl": "Distanţă minimă buffer",
  "buffer_default_lbl": "Distanţă implicită zonă tampon",
  "not_less_than_max": "Distanța trebuie să fie mai mică decât distanța tampon maximă",
  "not_between": "Distanța trebuie să fie între distanța tampon minimă și maximă",
  "not_more_than_min": "Distanța trebuie să fie mai mare decât distanța tampon minimă",
  "not_valid_number": "Trebuie să fie un număr valabil",
  "invalid_value": "Valoarea ${type} nu este valabilă",
  "routing_checkBox": "Activare rutare",
  "weather_Label": "Setări meteo",
  "weather_checkBox": "Activare meteo",
  "weather_map_layers": "Selectare straturi tematice meteo...",
  "selected_map_layers": " straturi tematice meteo selectate",
  "instruction_weather": "Afişaţi informaţiile meteo în panou.",
  "instruction_weather_layers": "Afişaţi straturi tematice meteo adiţionale.",
  "instruction_weather_metric": "Afişaţi valori standard/în sistemul metric.",
  "selectLayers": "Selectare straturi tematice meteo",
  "weather_removed_message": "Opțiunile de vreme nu mai sunt disponibile pentru acest widget.",
  "currentlySelectedLayer": "Selectare din straturi tematice hartă",
  "missingTabLabel": "Cel puţin o filă nu are etichetă",
  "missingLayerInWebMap": "Nu s-a găsit niciun strat tematic operaţional.",
  "selectFields": "Selectare câmpuri",
  "addField": "Adăugare câmp",
  "sum": "Sumă",
  "min": "Minim",
  "max": "Maxim",
  "avg": "Medie",
  "count": "NUMĂR",
  "area": "SUPRAFAŢĂ",
  "length": "LUNGIME",
  "count_checkBox": "Afişare număr obiecte spaţiale",
  "area_checkBox": "Afişare sumă suprafeţe",
  "length_checkBox": "Afişare sumă lungimi",
  "max_records": "Limită maximă atinsă",
  "save_label": "Opţiuni salvare",
  "save_checkbox": "Activare salvare",
  "report_label": "Opţiuni raport",
  "report_checkbox": "Activare raport",
  "csv_label": "Opţiuni CSV",
  "csv_checkbox": "Export toate câmpurile",
  "display_label": "Opţiuni de afişare",
  "display_checkbox": "Afişare obiecte spaţiale rezumat",
  "snapshot_label": "Opţiuni snapshot",
  "snapshot_checkbox": "Activare snapshot",
  "must_select_template": "Selectaţi unul dintre şabloanele de editare din Opţiuni salvare.",
  "count_label": "Etichetă număr",
  "area_label": "Etichetă suprafaţă",
  "length_label": "Etichetă lungime",
  "invalid_string_width": "Valoarea este prea lungă. ",
  "layer_type_not_supported": "Tip de strat tematic nesuportat",
  "groupedSummary": "Numere grupate",
  "groupByField": "Câmp Grupare după",
  "labelType": "Anexare etichetă",
  "prefix": "Ca prefix",
  "suffix": "Ca sufix",
  "need_group_field": "Utilizaţi acţiunea de editare pentru a defini un câmp Grupare după.",
  "fieldTitle": "Câmp",
  "typeTitle": "Tip",
  "actionsTitle": "Acţiuni",
  "save_point_checkbox": "Salvare puncte",
  "save_line_checkbox": "Salvare linii",
  "save_poly_checkbox": "Salvare poligoane",
  "no_valid_popup_fields": "Nu există câmpuri valide în fereastra pop-up. Utilizaţi acţiunea de editare pentru a defini un câmp.",
  "no_valid_fields": "Nu există câmpuri valide. Utilizaţi acţiunea de editare pentru a defini opţiunile de afişare.",
  "incident_label": "Etichetă filă",
  "locate_incident_label": "Etichetă zonă de interes",
  "incident": "Incident",
  "locate_incident": "Localizare incident",
  "buffer_value": "Distanţă buffer",
  "tab_options": "Analiză",
  "export_options": "Ieşire",
  "instruction_save": "Salvaţi locaţia în serviciul de obiecte spaţiale.",
  "instruction_snapshot": "Creaţi o hartă web pe baza locaţiei.",
  "instruction_report": "Creaţi un raport imprimat al locaţiei.",
  "instruction_all_fields": "Exportaţi toate câmpurile cu descărcarea CSV.",
  "data_label": "Setări ieşire date",
  "layer_error": "Strat tematic lipsă sau nevalid.",
  "visibility_checkBox": "Dezactivare gestionare vizibilitate straturi tematice",
  "downloadTab": {
    "reportLegend": "Setări raport",
    "textColorLabel": "Selectare culoare pentru titlurile de coloană",
    "setButtonLabel": "Setare",
    "printGPServiceLabel": "URL serviciu de imprimare",
    "logoLabel": "Siglă",
    "logoChooserHint": "Faceţi clic pe pictograma imaginii pentru a modifica imaginea",
    "footnoteLabel": "Notă de subsol"
  }
});