define({
  "selectAnalysisTools": "Pilih alat analisis untuk digunakan dalam widget.",
  "graphicalDisplay": "Tampilan Grafis",
  "toolSetting": "Tetapkan detail alat",
  "toolLabel": "Alat tersebut menampilkan nama",
  "showHelpTip": "Tampilkan tautan bantuan dalam widget",
  "showCurrentMapExtent": "Tampilkan opsi untuk menggunakan jangkauan peta saat ini",
  "showCredits": "Tampilkan opsi <b>Tampilkan kredit</b>",
  "saveAsFeatureService": "Simpan hasil di akun pengguna",
  "showReadyToUseLayers": "Tampilkan layer siap digunakan dari ArcGIS Online Living Atlas of The World",
  "toolNotAvailable": "Alat ini tidak tersedia karena peta tidak berisi layer fitur yang diperlukan.",
  "aggregatePoints": "Titik Agregat",
  "aggregatePointsUsage": "Titik agregat ke poligon tempat titik berada.",
  "calculateDensity": "Hitung Kepadatan",
  "calculateDensityUsage": "Buat peta kepadatan dari fitur titik atau garis dengan menyebarkan jumlah beberapa fenomena (diwakili sebagai atribut dari titik atau garis) yang diketahui sepanjang peta.",
  "connectOriginsToDestinations": "Hubungkan Asal ke Tujuan",
  "connectOriginsToDestinationsUsage": "Ukur waktu perjalanan atau jarak antara beberapa pasangan titik.",
  "createBuffers": "Buat Buffer",
  "createBuffersUsage": "Buat poligon buffer dari fitur input.",
  "createDriveTimeAreas": "Buat Area Waktu Mengemudi",
  "createDriveTimeAreasUsage": "Buat poligon waktu mengemudi (atau jarak mengemudi) di sekitar titik input untuk nilai waktu mengemudi yang diberikan.",
  "createViewshed": "Buat Viewshed",
  "createViewshedUsage": "Buat area yang terlihat berdasarkan lokasi yang Anda tentukan.",
  "createWatersheds": "Buat DAS (Daerah Aliran Sungai)",
  "createWatershedsUsage": "Buat area resapan berdasarkan lokasi yang Anda tentukan.",
  "deriveNewLocations": "Ambil Lokasi Baru",
  "deriveNewLocationsUsage": "Ambil fitur baru dari layer input yang memenuhi query yang Anda tentukan",
  "dissolveBoundaries": "Dissolve Batas",
  "dissolveBoundariesUsage": "Dissolve poligon yang tumpang tindih atau yang berbagi batasan umum.",
  "enrichLayer": "Enrich Layer",
  "enrichLayerUsage": "Enrich fitur input dengan orang, tempat, dan fakta bisnis tentang area di sekitar.",
  "extractData": "Ekstrak Data",
  "extractDataDesc": "Ekstrak data dari satu layer atau lebih dalam jangkauan yang diberikan",
  "findExistingLocations": "Temukan Lokasi yang Ada",
  "findExistingLocationsUsage": "Pilih fitur dari input layer yang memenuhi atribut dan/atau query spasial yang telah Anda tentukan",
  "findHotSpots": "Cari Hot Spots",
  "findHotSpotsUsage": "Temukan kluster fitur input yang signifikan secara statistik atau memiliki nilai tinggi/rendah.",
  "findNearest": "Temukan Terdekat",
  "findNearestUsage": "Untuk setiap fitur pada input layer, temukan fitur terdekatnya dari layer lain",
  "findSimilarLocations": "Cari Lokasi Serupa",
  "findSimilarLocationsUsage": "Ukur kesamaan calon lokasi pada satu lokasi rujukan atau lebih.",
  "interpolatePoints": "Titik Interpolasi",
  "interpolatePointsUsage": "Prediksikan nilai pada lokasi baru berdasarkan pengukuran dari kumpulan titik.",
  "mergeLayers": "Gabungkan Layer",
  "mergeLayersUsage": "Gabungkan fitur dari beberapa layer ke dalam layer baru",
  "overlayLayers": "Tampalan Layer",
  "overlayLayersUsage": "Gabungkan beberapa layer ke dalam layer tunggal dengan informasi dari layer asli yang dipertahankan.",
  "planRoutes": "Rencanakan Rute",
  "planRoutesUsage": "Tentukan cara membagi tugas secara efisien antar tenaga kerja yang aktif bergerak.",
  "summarizeNearby": "Ringkasan di Sekitar",
  "summarizeNearbyUsage": "Untuk setiap fitur pada input layer, ringkasan data berada dalam jarak dari fitur pada layer lain.",
  "summarizeWithin": "Ringkas di Dalam",
  "summarizeWithinUsage": "Untuk setiap polygon pada input layer polygon, ringkas data yang terletak di dalamnya dari fitur pada layer lain.",
  "traceDownstream": "Lacak Downstream (Hilir)",
  "traceDownstreamUsage": "Tentukan jalur aliran pada arah downstream (hilir) dari lokasi yang Anda tentukan.",
  "allowToExport": "Izinkan untuk mengekspor hasil",
  "joinFeatures": "Gabung Fitur",
  "joinFeaturesUsage": "Alat Gabung Fitur akan mentransfer atribut dari satu layer atau tabel ke yang lain berdasarkan hubungan spasial dan atribut. Selain itu, statistik dapat dihitung untuk fitur yang digabung.",
  "includeRouteLayer": "Sertakan layer rute",
  "findOutliers": "Temukan Pencilan",
  "findOutliersUsage": "Alat Temukan Pencilan akan menentukan apakah terdapat pencilan signifikan secara statistik dalam pola spasial data Anda."
});