define({
  "add": "Klicka för att lägga till en ny",
  "title": "Titel",
  "placeholderBookmarkName": "Namn på bokmärke",
  "ok": "OK",
  "cancel": "Avbryt",
  "warning": "Slutför redigeringen!",
  "edit": "Redigera bokmärke",
  "errorNameExist": "Det finns ett bokmärke!",
  "errorNameNull": "Ogiltigt namn på bokmärke!",
  "addBookmark": "Skapa ny",
  "thumbnail": "Miniatyrbild",
  "thumbnailHint": "Klicka på bilden för att uppdatera den",
  "displayBookmarksAs": "Visa bokmärken som",
  "cards": "Kort",
  "list": "Lista",
  "cardsTips": "Kortvy",
  "listTips": "Listvy",
  "makeAsDefault": "Utse till standard",
  "default": "Standard",
  "editable": "Tillåt att bokmärken läggs till i widgeten.",
  "alwaysSync": "Visa bokmärken från webbkartan",
  "configCustom": "Visa anpassade bokmärken",
  "import": "Importera",
  "create": "Skapa",
  "importTitle": "Importera bokmärken",
  "importFromWeb": "Importera bokmärken från den aktuella webbkartan",
  "selectAll": "Markera alla",
  "noBookmarkInConfig": "Klicka på â€œImporteraâ€ eller â€œSkapa nyâ€ för att lägga till bokmärken.",
  "noBookmarkInWebMap": "Inget bokmärke är konfigurerat i kartan.",
  "extent": "Utbredning",
  "saveExtent": "Spara kartutbredningen till det här bokmärket",
  "savelayers": "Spara lagrets synlighet",
  "withVisibility": "Med lagrets synlighet",
  "bookmark": "Bokmärke",
  "addBtn": "Lägg till",
  "deleteBtn": "Ta bort",
  "editBtn": "Redigera",
  "dragReorderTip": "Håll och dra för att ändra ordning",
  "deleteBtnTip": "Ta bort bokmärket",
  "editBtnTip": "Redigera bokmärket"
});