define({
  "_widgetLabel": "Priročnik za obvladovanje nujnih primerov",
  "ergMainPageTitle": "Na podlagi Priročnika za obvladovanje nujnih primerov iz leta 2016",
  "coordInputLabelStart": "Lokacija razlitja (DD)",
  "coordInputLabel": "Lokacija razlitja",
  "addPointToolTip": "Dodaj lokacijo razlitja",
  "drawPointToolTip": "Kliknite, da dodate lokacijo razlitja",
  "material": "Material",
  "materialPlaceholder": "Začnite tipkati, če želite poiskati material",
  "table3Message": "Za izbrani material so zahtevane dodatne informacije, če gre za veliko razlitje.\n\nZagotovite, da ste izbrali pravilne vrednosti za hitrost vetra in transportni zabojnik.",
  "table2Message": "Izbrani material lahko pri razlitju v vodo povzroči velike količine strupenih plinov, ki predstavljajo nevarnost za zdravje pri vdihavanju.\n\nPremislite o uporabi naslednjih materialov:\n\n",
  "spillSize": "Velikost razlitja",
  "small": "Majhna",
  "large": "Velika",
  "fireLabel": "Pokaži območje požarne zaščite",
  "weatherLabel": "Trenutne vremenske razmere na lokaciji razlitja",
  "weatherIntialText": "<br />Enkrat posodobljeno ob določitvi lokacije razlitja",
  "temperature": "Temperatura",
  "wind": "Veter",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Informacije o vremenskih razmerah niso pridobljene. Ročno posodobite vrednosti hitrosti vetra in časa razlitja",
  "windDirection": "Smer vetra (smer pihanja)",
  "timeOfSpill": "Čas razlitja",
  "day": "Dan",
  "night": "Noč",
  "windSpeed": "Hitrost vetra",
  "low": "Nizko",
  "moderate": "Zmerno",
  "high": "Visoko",
  "transportContainer": "Transportni zabojnik",
  "rail": "Železniška cisterna",
  "semi": "Tovornjak s cisterno ali priklopnik",
  "mton": "Večtonski valji",
  "ston": "Več manjših valjev ali enotonski valj",
  "ag": "Kmetijska cisterna",
  "msm": "Več manjših valjev",
  "bleveLabel": "Pokaži območje izolacije BLEVE",
  "capacity": "Prostornina zabojnika (litrov)",
  "bleveMessage": "Za izbrani material je za BLEVE možno prikazati dodatno evakuacijsko razdaljo.\n\nTo lahko omogočite tako, da gumb za preklapljanje Pokaži območje izolacije BLEVE nastavite na vklop in izberete ustrezno prostornino zabojnika.",
  "noPAZoneMessage": "Za ta material ni nobenih razdalj pri varstvenih ukrepih. Izračunani sta bili samo začetno zajezitveno in evakuacijsko območje",
  "settingsTitle": "Nastavitve",
  "spillLocationLabel": "Lokacija razlitja",
  "spillLocationButtonLabel": "Konfiguriraj nastavitve lokacije razlitja",
  "IISettingsLabel": "Začetno zajezitveno območje",
  "IIButtonLabel": "Konfiguriraj nastavitve začetne zajezitve",
  "PASettingsLabel": "Varstvena območja",
  "PAButtonLabel": "Konfiguriraj nastavitve varstvenih ukrepov",
  "downwindSettingsLabel": "Območje smeri vetra",
  "downwindButtonLabel": "Konfiguriraj nastavitve smeri vetra",
  "fireSettingsLabel": "Območje požarne zaščite",
  "fireButtonLabel": "Konfiguriraj nastavitve požarne izolacije",
  "bleveSettingsLabel": "Območje izolacije BLEVE",
  "bleveButtonLabel": "Konfiguriraj nastavitve BLEVE",
  "style": "Slog",
  "lineStyles": {
    "esriSLSDash": "Črtica",
    "esriSLSDashDot": "Črtica pika",
    "esriSLSDashDotDot": "Črtica pika pika",
    "esriSLSDot": "Pika",
    "esriSLSLongDash": "Dolga črtica",
    "esriSLSLongDashDot": "Dolga črtica pika",
    "esriSLSNull": "Brez vrednosti",
    "esriSLSShortDash": "Kratka črtica",
    "esriSLSShortDashDot": "Kratka črtica pika",
    "esriSLSShortDashDotDot": "Kratka črtica pika pika",
    "esriSLSShortDot": "Kratka pika",
    "esriSLSSolid": "Enobarvno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Nazaj",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Diagonalno",
    "esriSFSForwardDiagonal": "Naprej",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Brez vrednosti",
    "esriSFSSolid": "Enobarvno",
    "esriSFSVertical": "Vertikalno"
  },
  "resultsTitle": "Rezultati",
  "publishERGBtn": "Objavi",
  "ERGLayerName": "Objavljeno ime sloja ERG",
  "invalidERGLayerName": "Ime sloja mora vsebovati le alfanumerične znake in podčrtaje",
  "missingERGLayerName": "Vnesti morate ime za ERG",
  "publishingFailedLayerExists": "Objavljanje ni uspelo: imate že geoobjektno storitev z imenom {0}. Izberite drugo ime.",
  "checkService": "Preveri storitev: {0}",
  "createService": "Ustvari storitev: {0}",
  "unableToCreate": "Ni mogoče ustvariti: {0}",
  "addToDefinition": "Dodaj v določitev: {0}",
  "successfullyPublished": "Uspešno je bil objavljen spletni sloj{0}Upravljanje spletnega sloja",
  "userRole": "Storitve ni mogoče ustvariti, ker uporabnik nima dovoljenj",
  "transparency": "Prosojnost",
  "outline": "Obroba",
  "fill": "Polnilo (barva se uporablja le, če je slog nastavljen na enobarvno polnilo)",
  "createERGBtn": "Ustvari območja",
  "clearERGBtn": "Počisti",
  "labelFormat": "Format napisa",
  "helpIconTooltip": "Prag med malimi in velikimi velikostmi razlitja je:\nTekočine – 55 galonov (208 litrov)\nTrdne snovi – 60 funtov (300 kilogramov)",
  "cellWidth": "Širina celice (x)",
  "cellHeight": "Višina celice (y)",
  "invalidNumberMessage": "Vnesena vrednost ni veljavna",
  "invalidRangeMessage": "Vrednost mora biti večja od 0",
  "gridAngleInvalidRangeMessage": "Vrednost mora biti med -89,9 in 89,9",
  "formatIconTooltip": "Vhodni format",
  "setCoordFormat": "Nastavi format niza koordinat",
  "prefixNumbers": "Pozitivnim in negativnim številkam dodaj predpono »+/–«",
  "cancelBtn": "Prekliči",
  "applyBtn": "Uporabi",
  "comfirmInputNotation": "Potrdite zapis vnosa",
  "notationsMatch": "Najden je zapis, ki se ujema z vašim vnosom. Potrdite, katerega želite uporabiti:",
  "missingLayerNameMessage": "Pred objavo morate vnesti veljavno ime sloja",
  "parseCoordinatesError": "Koordinat ni mogoče razčleniti. Preverite svoj vnos.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalne stopinje – geografska širina/geografska dolžina",
  "DDLongLatNotation": "Decimalne stopinje – geografska dolžina/geografska širina",
  "DDMLatLongNotation": "Stopinje Decimalne minute – geografska širina/geografska dolžina",
  "DDMLongLatNotation": "Stopinje Decimalne minute – geografska dolžina/geografska širina",
  "DMSLatLongNotation": "Stopinje Minute Sekunde – geografska širina/geografska dolžina",
  "DMSLongLatNotation": "Stopinje Minute Sekunde – geografska dolžina/geografska širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – črka pasu",
  "UTMHemNotation": "UTM – hemisfera (S/J)"
});