define({
  "layerSelect": "Valitse kuvan karttataso",
  "displayMeasureResultInPopup": "Näytä mittaustulokset ponnahdusikkunassa",
  "angularUnitSelect": "Oletuskulmayksikkö",
  "linearUnitSelect": "Oletuslineaariyksikkö",
  "areaUnitSelect": "Oletuspinta-alayksikkö",
  "displayOperationSelect": "Valitse mittaustoiminnot",
  "errorSectionMessage": "Karttatasot eivät tue mittaustoimintoja.",
  "unitLabel": {
    "esriInches": "Tuumaa",
    "esriFeet": "Jalkaa",
    "esriYards": "Jaardia",
    "esriMiles": "Mailia",
    "esriNauticalMiles": "Meripeninkulmaa",
    "esriMillimeters": "Millimetriä",
    "esriCentimeters": "Senttimetriä",
    "esriDecimeters": "Desimetriä",
    "esriMeters": "Metriä",
    "esriKilometers": "Kilometriä",
    "esriDURadians": "Radiaaneina",
    "esriDUDecimalDegrees": "Asteet",
    "esriSquareInches": "Neliötuumaa",
    "esriSquareFeet": "Neliöjalkaa",
    "esriSquareYards": "Neliöjaardia",
    "esriAcres": "Aaria",
    "esriSquareMiles": "Neliömailia",
    "esriSquareMillimeters": "Neliömillimetriä",
    "esriSquareCentimeters": "Neliösenttimetriä",
    "esriSquareDecimeters": "Neliödesimetriä",
    "esriSquareMeters": "Neliömetriä",
    "esriAres": "Aaria",
    "esriHectares": "Hehtaaria",
    "esriSquareKilometers": "Neliökilometriä"
  },
  "operationLabel": {
    "esriMensurationPoint": "Sijainti",
    "esriMensurationDistanceAndAngle": "Etäisyys ja kulma",
    "esriMensurationAreaAndPerimeter": "Alue ja ympärysmitta",
    "esriMensurationHeightFromBaseAndTop": "Korkeus: alhaalta ylös",
    "esriMensurationHeightFromBaseAndTopShadow": "Korkeus: alhaalta yläreunan varjostukseen",
    "esriMensurationHeightFromTopAndTopShadow": "Korkeus: ylhäältä yläreunan varjostukseen",
    "esriMensurationCentroid": "Painopiste",
    "esriMensurationPoint3D": "Sijainti (3D)",
    "esriMensurationDistanceAndAngle3D": "Etäisyys ja kulma (3D)",
    "esriMensurationAreaAndPerimeter3D": "Alue ja ympärysmitta (3D)",
    "esriMensurationCentroid3D": "Painopiste (3D)"
  }
});