define({
  "labelBookmarkName": "Установить закладку на текущем виде",
  "labelPlay": "Воспроизвести всё",
  "labelStop": "Стоп",
  "labelDelete": "Удалить",
  "placeholderBookmarkName": "Имя закладки",
  "errorNameExist": "Закладка уже существует!",
  "errorNameNull": "Недопустимое имя закладки!",
  "editTip": "Редактировать закладки",
  "exitEditTip": "Выйти из режима редактирования",
  "syncTip": "Синхронизировать",
  "cardsTips": "Таблица",
  "listTips": "Список",
  "addBtn": "Добавить",
  "deleteBtn": "Удалить",
  "changeThumbnailTip": "Изменить значок",
  "dragReorderTip": "Удерживать и перетащить, чтобы изменить порядок",
  "deleteBtnTip": "Удалить закладку",
  "editBtnTip": "Редактировать закладку",
  "withVisibility": "С видимостью слоя",
  "searchBookmark": "Поиск",
  "bookmarksFromConfig": "Предварительно настроенные закладки",
  "bookmarksFromCache": "Локальные временные закладки",
  "notice": "Предупреждение",
  "changeNoticeTips": "Изменения будут сохранены только в кэше вашего браузера. Синхронизация между виджетом и его настройками будет прекращена, как только будут произведены изменения.",
  "syncNoticeTips": "Это сотрет все ваши изменения и восстановит настроенные закладки.",
  "dontShowAgain": "Больше не показывать",
  "saveVisibility": "Сохранить видимость слоя",
  "_widgetLabel": "Закладка"
});